/**
 * AP Chinese Language — Character Recognition and Tone System.
 */

import type { LessonPlan } from '../types';

export const SEED_AP_CHINESE_LANG_CHARACTERS: LessonPlan = {
  id: 'evelyn.ap.chinese-lang.characters.v1',
  title: 'AP Chinese Language — Characters, Pinyin, Tones',
  curriculum: 'AP',
  grade: '11',
  subject: 'languages',
  topic: 'ap-chinese-lang',
  locale: 'en',
  los: [{ id: 'ap.chinese-lang.characters', description: 'Master Chinese tone system, pinyin spelling, character radicals, and high-frequency vocabulary for AP.', standard: 'AP-CHINESE-LANG' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 16,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'AP Chinese tests both characters AND audio recognition — and tones are absolutely critical.', script: 'AP Chinese is delivered partially via computer with character/pinyin input. Tones change meaning entirely (mā 妈 mother vs mǎ 马 horse). Today: tones, pinyin spelling rules, character radicals, high-frequency vocab.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Tones, pinyin rules, radicals, common characters.', keyIdeas: [
      'FOUR MAIN TONES (memorise + practice):',
      '  TONE 1 (mā): high, level. Like "mom" with rising pitch sustained.',
      '  TONE 2 (má): rising. Like asking "what?" in English.',
      '  TONE 3 (mǎ): low-dipping (falls then rises slightly). The trickiest.',
      '  TONE 4 (mà): sharply falling. Authoritative tone.',
      '  NEUTRAL TONE (ma): unstressed, brief.',
      'TONE CHANGES (sandhi):',
      '  Two TONE 3s in a row → first becomes TONE 2. "Nǐ hǎo" → pronounced "Ní hǎo."',
      '  Three TONE 3s → first two often pronounced as TONE 2.',
      'PINYIN spelling rules:',
      '  "i" after sh, ch, zh, r is voiced (almost like "ih" sound).',
      '  "u" after j, q, x, y is pronounced like "ü" (rounded).',
      '  Tone marks go on the main vowel.',
      '  -ng endings: nasal sound; pronounce like "sing."',
      'CHARACTER RADICALS — most characters are composed of radicals indicating:',
      '  MEANING (semantic): 木 (wood) appears in 林 (forest), 树 (tree), 桥 (bridge).',
      '  SOUND (phonetic): 马 (mǎ) appears in 妈 (mā mother) — same sound mostly.',
      'KEY RADICALS to know (memorise):',
      '  亻(person): 你 you, 他 he/she, 们 plural.',
      '  口 (mouth): 吃 eat, 喝 drink, 说 say.',
      '  心 (heart): 想 think, 怕 afraid.',
      '  水 / 氵 (water): 河 river, 湖 lake.',
      '  火 (fire): 烧 burn, 烤 grill.',
      '  日 (sun): 明 bright, 时 time.',
      'STROKE ORDER: top-to-bottom, left-to-right, outside-then-inside (with closing). Important for handwriting, less for AP\'s typed format.',
      'HIGH-FREQUENCY characters (memorise the most common 100):',
      '  我 wǒ I/me, 你 nǐ you, 他/她 tā he/she, 是 shì to be, 的 de (possessive), 不 bù not, 在 zài at/in, 有 yǒu have, 这 zhè this, 那 nà that, 什么 shénme what.',
      'COMMON WORDS for AP (memorise + use in writing):',
      '  好 hǎo good, 坏 huài bad, 大 dà big, 小 xiǎo small, 多 duō many, 少 shǎo few, 高 gāo tall, 低/矮 short, 漂亮 piàoliang pretty, 累 lèi tired.',
      'ESSAY/SPEAKING vocabulary:',
      '  因为...所以... (yīnwèi...suǒyǐ...) — because...so...',
      '  虽然...但是... (suīrán...dànshì...) — although...but...',
      '  如果...就... (rúguǒ...jiù...) — if...then...',
    ], vocabulary: [{ term: 'tone sandhi', definition: 'tone changes that occur in connected speech, especially with two tone-3s adjacent.' }, { term: 'pinyin', definition: 'romanisation system for Mandarin used to learn pronunciation; converted to characters when typing.' }], estimatedMinutes: 5 },
    { id: 'worked', kind: 'worked_example', problem: 'How would you teach a beginner to distinguish "mā 妈" (mother) from "mǎ 马" (horse)?', steps: [
      '1. Both are spelled "ma" in pinyin — TONE distinguishes them.',
      '2. Tone 1 is HIGH and LEVEL: "mā" sounds like singing one steady note.',
      '3. Tone 3 is LOW and DIPPING: "mǎ" starts low, dips lower, rises slightly.',
      '4. Practice: alternate "mā mā mā" (high) and "mǎ mǎ mǎ" (dipping) until the difference is felt physically.',
      '5. Use context to distinguish in sentences: 我妈在那里 (My mother is there) vs 我有一只马 (I have one horse — using measure word 只).',
      '6. Native speakers process tones automatically; AP students must train this attention.',
    ], answer: 'Same pinyin, different tones; train tonal contrast through alternating practice + context cues.', estimatedMinutes: 4 },
    { id: 'try-1', kind: 'try_yourself', problem: 'Why is "你好" pronounced "Ní hǎo" rather than "Nǐ hǎo"?', expectedAnswer: 'TONE SANDHI: when two tone-3 syllables come together, the FIRST changes to tone 2. So "Nǐ hǎo" (3 + 3) is pronounced "Ní hǎo" (2 + 3). The written tone marks may stay as 3+3 in some textbooks, but in spoken Chinese, the change happens automatically. This is one of the first tone changes learners encounter.', responseFormat: 'free', hints: ['What happens with two tone-3s in a row?', 'The first changes to which tone?'], estimatedMinutes: 2 },
    { id: 'misconception-tones-not-important', kind: 'misconception_check', question: 'A student says "tones don\'t really matter; people will understand from context." Why is this wrong for AP?', commonErrors: [{ answer: 'Tones don\'t matter', misconception: 'Treating Chinese tones as accent rather than meaning.', correctsTo: 'Tones CHANGE WORDS in Chinese. "Mā" (mother), "má" (hemp), "mǎ" (horse), "mà" (scold), "ma" (question particle) — five different words from the same syllable. Saying "mǎ" instead of "mā" can mean "horse" instead of "mother" — embarrassing in conversation. While context can sometimes save you, AP graders are listening for tonal accuracy and your peers/teachers will too. Train tones as part of vocabulary, not as ornament.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Four tones + neutral; tones distinguish meaning.', 'Tone 3 + tone 3 → first becomes tone 2 (sandhi).', 'Radicals carry meaning + sound clues.', '因为...所以..., 虽然...但是..., 如果...就... — common essay structures.', 'Train tonal contrast with alternating practice.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
