/**
 * AP Environmental Science — CED Unit 9.1+9.2: Stratospheric Ozone
 * Depletion and the Montreal Protocol.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U9_OZONE: LessonPlan = {
  id: 'evelyn.ap.envsci.ozone.v1', title: 'U9.1 Stratospheric Ozone Depletion',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.ozone', description: 'Distinguish good (stratospheric) ozone from bad (tropospheric) ozone. Trace ozone-CFC chemistry. Identify the Montreal Protocol as the most successful environmental treaty.', standard: 'AP-ENVSCI-9.1-9.2' }],
  prerequisites: [], followUps: ['apenvsci.greenhouse-climate'], estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame the ozone success story.', script: "Stratospheric OZONE absorbs UV radiation that would otherwise burn DNA. In the 1980s, scientists discovered a HOLE in the ozone layer over Antarctica. The world responded with the Montreal Protocol — and the hole is now SHRINKING. Today: how it happened and how we fixed it.", estimatedMinutes: 2 },
    { id: 'concept-ozone', kind: 'concept', goal: 'Cover good vs bad ozone, depletion chemistry, Montreal Protocol.',
      keyIdeas: [
        'TWO OZONES — opposite roles:',
        '  • STRATOSPHERIC OZONE (15-35 km altitude): "GOOD" ozone. Absorbs UV-B and UV-C radiation. Protects life on Earth from DNA damage, skin cancer, cataracts, ecosystem damage.',
        '  • TROPOSPHERIC OZONE (ground-level): "BAD" ozone. Component of photochemical smog. Damages lungs, irritates eyes, harms vegetation.',
        '  • SAME molecule (O₃) — different effects depending on location.',
        'OZONE FORMATION (in stratosphere):',
        '  • UV light splits O₂ → 2 O atoms.',
        '  • O atom + O₂ → O₃ (ozone).',
        '  • OZONE-OXYGEN CYCLE continuously creates and destroys ozone naturally; net concentration ~10 ppm in stratosphere.',
        'OZONE DEPLETION:',
        '  • CFCs (chlorofluorocarbons) — used as refrigerants, propellants, solvents from 1930s. Stable in atmosphere; rise to stratosphere over years.',
        '  • UV light splits CFCs → release CHLORINE atoms.',
        '  • Cl + O₃ → ClO + O₂. Ozone destroyed.',
        '  • ClO + O₃ → Cl + 2O₂. Cl atom released to destroy MORE ozone.',
        '  • CATALYTIC: one Cl atom destroys ~100,000 O₃ molecules over ~100 years before being removed.',
        '  • Other ozone-depleting substances: HALONS (Br), nitrous oxide, methyl bromide, methyl chloroform.',
        'ANTARCTIC OZONE HOLE:',
        '  • Discovered 1985 by British Antarctic Survey.',
        '  • Forms in spring (Sept-Oct) over Antarctic.',
        '  • Polar stratospheric clouds + extreme cold + isolation of polar vortex create perfect conditions for chlorine chemistry.',
        '  • Hole grew to ~30 million sq km in late 1990s.',
        '  • CONSEQUENCES: \n     - Increased UV reaching surface.\n     - Skin cancer rates higher in S. Hemisphere.\n     - Phytoplankton damage in Antarctic Ocean → cascade through food web.\n     - Damage to crops, marine life.',
        'MONTREAL PROTOCOL (1987):',
        '  • International treaty to PHASE OUT ozone-depleting substances.',
        '  • RATIFIED BY 197 NATIONS — universal ratification (only treaty in UN history).',
        '  • Banned CFCs by 2010 (developed countries) / 2030 (developing).',
        '  • REPLACED CFCs WITH:\n     - HCFCs (hydrochlorofluorocarbons) — less ozone-depleting; phase-out underway.\n     - HFCs (hydrofluorocarbons) — no ozone depletion BUT potent greenhouse gas.\n     - Newer alternatives (HFOs) reduce both impacts.',
        '  • RESULTS:\n     - CFC emissions dropped >99% from peak.\n     - Stratospheric chlorine levels declining.\n     - OZONE LAYER HEALING; expected full recovery by 2070.\n     - Antarctic hole already smaller in 2020s than peak.',
        'WHY MONTREAL SUCCEEDED (compared to Paris Agreement on climate):',
        '  • Smaller number of substances to regulate.',
        '  • Substitutes were available (industrial chemists found alternatives).',
        '  • Strong scientific consensus + visible threat (skin cancer).',
        '  • Industry initially resisted but eventually saw market opportunities.',
        '  • Trade penalties for non-compliant nations.',
        '  • Periodic strengthening (London, Copenhagen, Kigali Amendments).',
      ],
      vocabulary: [
        { term: 'CFC', definition: 'chlorofluorocarbon — ozone-depleting substance, banned.' },
        { term: 'Montreal Protocol', definition: '1987 treaty phasing out ozone-depleting substances; universal ratification.' },
        { term: 'stratospheric ozone', definition: '"good" ozone protecting life from UV radiation.' },
      ],
      estimatedMinutes: 5 },
    { id: 'worked-cycle', kind: 'worked_example',
      problem: 'Trace the chemistry: how does a CFC molecule (e.g., CFCl₃, "Freon-11") in your refrigerator end up destroying stratospheric ozone?',
      steps: [
        'STEP 1 — CFC LEAKS or is released during refrigerator disposal.',
        'STEP 2 — CFC is STABLE in lower atmosphere (won\'t decay quickly). Slowly rises with air currents — takes ~5-10 YEARS to reach stratosphere.',
        'STEP 3 — In stratosphere (15-35 km), UV light is intense.',
        'STEP 4 — UV BREAKS the C-Cl bond: CFCl₃ + UV → CFCl₂• + Cl•',
        'STEP 5 — Free Cl atom: Cl + O₃ → ClO + O₂. ONE OZONE DESTROYED.',
        'STEP 6 — ClO + O (single atom from another O₂ split) → Cl + O₂. CHLORINE REGENERATED.',
        'STEP 7 — That same Cl atom can destroy MORE OZONE — net catalysis.',
        'STEP 8 — One Cl atom destroys ~100,000 O₃ molecules over its ~100-year stratospheric lifetime.',
        'CONCLUSION: stable CFC in your refrigerator → catalytic stratospheric chlorine cycle → massive ozone depletion. Why CFCs were banned despite seeming safe.',
      ],
      answer: 'CFC → rises to stratosphere → UV releases Cl → catalytic cycle destroys ~100,000 ozone molecules per Cl.', estimatedMinutes: 4 },
    { id: 'try-good-bad', kind: 'try_yourself',
      problem: 'Stratospheric ozone is GOOD; tropospheric ozone is BAD. Explain why each is true.',
      expectedAnswer: 'STRATOSPHERIC ozone (good): \n• 15-35 km altitude. \n• Absorbs UV-B and UV-C radiation that would damage DNA. \n• Protects life from skin cancer, cataracts, immune suppression, ecosystem damage. \n• 90% of stratospheric ozone is "good." \nTROPOSPHERIC ozone (bad): \n• Ground-level. \n• A SECONDARY pollutant — formed when NOx + VOCs + sunlight react. \n• Component of photochemical smog. \n• Damages lungs (especially asthma), irritates eyes, harms crops/forests. \n• EPA criteria pollutant; one of 6 regulated. \nSAME molecule, different effects depending on altitude. Ground ozone harms us; stratospheric ozone protects us.',
      responseFormat: 'free', hints: ['Same O₃, different roles by altitude.'], estimatedMinutes: 2 },
    { id: 'try-success', kind: 'try_yourself',
      problem: 'Why is the Montreal Protocol considered the most successful environmental treaty? Compare it to the Paris Agreement on climate.',
      expectedAnswer: 'MONTREAL SUCCESS factors:\n• UNIVERSAL RATIFICATION (197 nations).\n• CFC emissions dropped >99%.\n• Stratospheric chlorine declining.\n• Ozone layer HEALING; full recovery expected by 2070.\nWHY IT SUCCEEDED:\n1. SMALLER scope (~100 substances vs all carbon).\n2. AFFORDABLE substitutes available (HCFCs, HFCs, newer alternatives).\n3. CLEAR scientific consensus (well-defined chemistry).\n4. VISIBLE threat (skin cancer, ozone hole image dramatic).\n5. INDUSTRY incentive: developed substitutes, captured market.\n6. ENFORCEMENT: trade penalties for non-compliance.\n7. PERIODIC strengthening (London, Copenhagen, Kigali, Beijing amendments).\nVERSUS PARIS AGREEMENT (climate):\n• MUCH larger scope (energy, transport, agriculture, industry, all sectors).\n• SUBSTITUTES less mature; cost-effective alternatives still emerging.\n• ENFORCEMENT WEAK (voluntary national commitments, no penalties).\n• POLITICAL TIMING: ratifying nations don\'t implement aggressively enough.\n• ECONOMIC interests deeply embedded.\nMontreal teaches: international cooperation works for SOLVABLE, BOUNDED problems. Climate is harder.',
      responseFormat: 'free', hints: ['Compare structural factors.'], estimatedMinutes: 4 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. The HFCs that replaced CFCs don\'t deplete ozone but ARE potent greenhouse gases (1,000-3,000× CO₂). The 2016 KIGALI AMENDMENT to the Montreal Protocol mandates phasing them down. (a) Explain the regulatory progression CFCs → HCFCs → HFCs → new alternatives. (b) Why did Kigali extend Montreal to address climate? (c) What does this teach about regulatory tradeoffs?',
      expectedAnswer: '(a) Progression:\n• CFCs (1930s-1990s): destroyed ozone. Banned by Montreal 1987. \n• HCFCs (transitional): less ozone-depleting (still some), used as bridge. Now phasing out. \n• HFCs (1990s+): NO ozone depletion. But VERY high GHG potency. \n• Newer HFOs (hydrofluoroolefins): low ozone depletion + low GHG impact. Still cost premium. \nThe sequence: each generation solved the LAST problem but introduced a new one. (2)\n(b) Kigali Amendment (2016):\n• Recognized that HFCs, while not ozone-depleting, are POTENT GHGs (1,000-3,000× CO₂ over 100 years). \n• Used MONTREAL FRAMEWORK (proven effective) to phase down HFCs. \n• Required developed nations to reduce HFC use 85% by 2036. \n• Estimated to avoid 0.5°C of warming by 2100. \n• Extends ozone treaty success to climate change. \n• Bipartisan US support; ratified 2022. (2)\n(c) Lessons on tradeoffs:\n• "SOLVING" one problem can create another. \n• REGULATORS need to anticipate full lifecycle impacts. \n• Industry CAN INNOVATE under pressure (developed HFO alternatives in years). \n• Existing successful frameworks can be EXTENDED to new problems. \n• ACADEMIC INVOLVEMENT crucial — chemistry/atmosphere science guided policy. \n• REGRETS can be addressed: HFCs were good replacements but not best long-term. (2)\nTotal: 6 points.',
      responseFormat: 'frq', hints: ['Regulatory progression; Kigali extension; broader lesson.'], estimatedMinutes: 5 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Two ozones: stratospheric (good, blocks UV) vs tropospheric (bad, smog).',
      'CFCs broken by UV in stratosphere release catalytic Cl atoms.',
      'One Cl destroys ~100,000 ozone molecules over its lifetime.',
      'Montreal Protocol (1987): universal ratification, >99% reduction in CFCs.',
      'Kigali Amendment extends to phase down HFCs (climate-relevant).',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '9', cedTopic: '9.1-9.2', cedTitle: 'Stratospheric Ozone', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '17,19', note: 'Standard ozone + Montreal Protocol.' }] },
};
