/**
 * AP Environmental Science — CED Unit 2.5 + 2.7: Natural Disruptions and
 * Ecological Succession.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U2_DISRUPTIONS_SUCCESSION: LessonPlan = {
  id: 'evelyn.ap.envsci.disruptions-succession.v1', title: 'U2.3 Natural Disruptions and Ecological Succession',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.disruptions-succession', description: 'Identify natural disruptions (fire, flood, hurricane, volcanic eruption) and human disruptions. Distinguish primary and secondary succession; identify pioneer species and climax community.', standard: 'AP-ENVSCI-2.5+2.7' }],
  prerequisites: ['apenvsci.tolerance-adaptations'], followUps: [], estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame disturbance as both destructive and renewing.', script: "Wildfire, hurricane, volcanic eruption — disturbances LOOK destructive. But many ecosystems EVOLVED with regular disturbance. After disruption comes ECOLOGICAL SUCCESSION — the predictable rebuilding of communities.", estimatedMinutes: 2 },
    { id: 'concept-disturbance', kind: 'concept', goal: 'Cover disturbances + succession.',
      keyIdeas: [
        'DISTURBANCE: an event that disrupts an ecosystem, removes biomass, or alters availability of resources.',
        'NATURAL DISTURBANCES:',
        '  • FIRE: removes overstory; releases nutrients; some species require fire to germinate (jack pine cones open in heat). DROUGHT increases fire risk.',
        '  • FLOODS: deposit sediments; transport nutrients; create new habitat in wetlands.',
        '  • HURRICANES / TROPICAL STORMS: snap canopy trees; reset coastal ecosystems.',
        '  • VOLCANIC ERUPTIONS: bury everything in lava/ash; create entirely new substrate.',
        '  • EARTHQUAKES, LANDSLIDES: remove soil; expose new substrate.',
        '  • PEST OUTBREAKS, DISEASE: locally eliminate dominant species.',
        'HUMAN DISTURBANCES: deforestation, urbanization, mining, dam construction, war.',
        'ECOLOGICAL SUCCESSION: predictable sequence of community changes after disturbance.',
        'PRIMARY SUCCESSION: starts with NO SOIL — bare rock or new substrate (post-volcanic, retreated glacier, new island).',
        '  • PIONEER SPECIES: lichens (acid breaks down rock, creates first soil), mosses, then small plants.',
        '  • Slow process: hundreds to thousands of years to reach climax.',
        'SECONDARY SUCCESSION: starts with SOIL ALREADY PRESENT (post-fire, abandoned farmland, post-flood).',
        '  • Pioneer species: fast-growing herbs, weeds, grasses.',
        '  • Faster: decades to centuries to reach climax.',
        'TYPICAL TERRESTRIAL SUCCESSION SEQUENCE (e.g., abandoned field): \n  bare ground → annual weeds → perennial grasses → shrubs → fast-growing trees (pines, birch) → slower-growing climax forest (oak, maple, hickory).',
        'CLIMAX COMMUNITY: relatively stable, mature community in equilibrium. Specific to the region (climax in temperate east US ≠ climax in desert).',
        'r-SELECTED vs K-SELECTED species:',
        '  • r-SELECTED (pioneers): many small offspring, fast growth, short lives, high dispersal. Weeds, insects, mice. Dominate early succession.',
        '  • K-SELECTED (late succession): few large offspring, slow growth, long-lived. Trees, large mammals. Dominate climax communities.',
        'CONCEPT TENSION (modern view): "climax community" oversimplifies. Many ecosystems are NEVER in true equilibrium — disturbance is recurring. The PATCH MOSAIC or DISTURBANCE REGIME view says ecosystems have a mix of successional stages at any time.',
      ],
      vocabulary: [
        { term: 'primary succession', definition: 'colonization of bare substrate (no soil); slow.' },
        { term: 'secondary succession', definition: 'recovery on existing soil; fast.' },
        { term: 'pioneer species', definition: 'first colonizers — lichens (primary) or weeds/grasses (secondary).' },
        { term: 'climax community', definition: 'mature, stable end-stage of succession (idealized).' },
      ],
      estimatedMinutes: 6 },
    { id: 'worked-classify', kind: 'worked_example',
      problem: 'For each scenario, identify whether it would lead to PRIMARY or SECONDARY succession: (a) Mount St. Helens eruption (1980) — lava and ash buried the area. (b) A wildfire burns through Yellowstone\'s forests (1988). (c) An abandoned cornfield in Iowa.',
      steps: [
        'STEP 1 — (a) Volcanic eruption obliterates soil → starts on lava → PRIMARY succession. Pioneer = lichens.',
        'STEP 2 — (b) Fire kills above-ground vegetation but soil remains → SECONDARY succession. Pioneer = grasses/weeds.',
        'STEP 3 — (c) Tilled soil is intact → SECONDARY succession. Pioneer = annual weeds (ragweed, foxtail).',
      ],
      answer: '(a) Primary. (b) Secondary. (c) Secondary.', estimatedMinutes: 3 },
    { id: 'try-sequence', kind: 'try_yourself',
      problem: 'A farm in Pennsylvania is abandoned. Predict the successional sequence over 100 years.',
      expectedAnswer: 'Year 0 (after abandonment): bare/recently tilled soil. \nYears 1-3: annual WEEDS (ragweed, dandelion, foxtail) — fast-growing pioneers. \nYears 3-15: perennial grasses, herbs, then SHRUBS (sumac, dogwood, blackberry brambles). \nYears 15-50: FAST-GROWING TREES (pines, birch, aspen, cherry) form young forest. \nYears 50-150+: SLOWER-GROWING climax species (oak, hickory, maple) dominate as mature forest develops. Original pines die out as shaded by oaks/maples. \nClimax: TEMPERATE DECIDUOUS FOREST. (This is the climax for that region.)',
      responseFormat: 'free', hints: ['Weeds → grasses → shrubs → fast trees → climax forest.'], estimatedMinutes: 4 },
    { id: 'try-fire', kind: 'try_yourself',
      problem: 'Some forests (e.g., longleaf pine in southeastern US, lodgepole pine in West) DEPEND on regular fire. Explain why and what happens if fire is suppressed.',
      expectedAnswer: 'These species evolved with regular fire and have adaptations: \n• LONGLEAF PINE: fire-resistant bark; cone shapes that release seeds after fire. \n• LODGEPOLE PINE: SEROTINOUS cones — sealed with resin that only opens at high temperatures (during fire). \nFire benefits: clears underbrush, reduces competition, releases nutrients in ash, creates open ground for seedlings. \nFire SUPPRESSION (mistakenly trying to prevent ALL fires): \n• Fuel accumulates over years/decades. \n• When a fire eventually does start, it burns hotter and longer (catastrophic crown fires, not low-intensity ground fires the ecosystem is adapted to). \n• Fire-dependent species fail to reproduce. \n• Successional species (shrubs, hardwoods) replace the pine ecosystem. \nMODERN MANAGEMENT: PRESCRIBED BURNING — controlled, low-intensity fires that mimic the natural fire regime.',
      responseFormat: 'free', hints: ['Fire as ecosystem necessity; suppression backfires.'], estimatedMinutes: 4 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. Mt. St. Helens erupted in May 1980, devastating 600 km² of mature forest. Areas closer to the volcano became bare lava/ash; areas farther had soil and roots remaining. (a) Predict what KIND of succession would occur in each zone. (b) Compare expected recovery times. (c) Identify two pioneer species you\'d expect in each zone. (d) After 40+ years (now), what stages should each zone be in?',
      expectedAnswer: '(a) Closer-in zones (lava/ash, no soil): PRIMARY succession. Outer zones (soil intact, root systems present): SECONDARY succession. (1.5)\n(b) PRIMARY: hundreds of years to centuries to reach mature forest. SECONDARY: decades to ~100 years. (1.5)\n(c) PRIMARY pioneers: lichens, mosses, fireweed. Then nitrogen-fixing alders. SECONDARY pioneers: fireweed, lupines, herbaceous plants from surviving roots, plus tree saplings re-sprouting. (2)\n(d) After 40+ years: \n• Primary zones: still in EARLY-TO-MID succession. Patches of fireweed, alders, scattered conifer seedlings. NOT YET a young forest. Soil still developing. \n• Secondary zones: WELL INTO YOUNG FOREST stage. Closed canopy of fast-growing trees (Douglas-fir, alder); recovering wildlife. Approaching mid-succession. (2)\nTotal: 7 points.',
      responseFormat: 'frq', hints: ['Different zones → different succession types and rates.'], estimatedMinutes: 5 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Disturbance is normal; some ecosystems require it (fire-adapted forests).',
      'Primary: bare substrate; lichens; very slow.',
      'Secondary: soil intact; weeds first; faster.',
      'Pioneer (r-selected) → climax (K-selected) species over time.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '2', cedTopic: '2.5+2.7', cedTitle: 'Disruptions and Succession', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '4', note: 'Standard succession.' }] },
};
