/**
 * AP Environmental Science — CED Unit 1.5 + 1.6: Nitrogen and Phosphorus
 * Cycles.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U1_NITROGEN_PHOSPHORUS_CYCLES: LessonPlan = {
  id: 'evelyn.ap.envsci.nitrogen-phosphorus-cycles.v1', title: 'U1.3 Nitrogen and Phosphorus Cycles',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.nitrogen-phosphorus-cycles', description: 'Trace nitrogen through fixation, ammonification, nitrification, assimilation, and denitrification. Trace phosphorus through weathering, plant uptake, decomposition, sedimentation. Identify human disruptions (fertilizer runoff → eutrophication; mining; combustion).', standard: 'AP-ENVSCI-1.5-1.6' }],
  prerequisites: ['apenvsci.carbon-water-cycles'], followUps: ['apenvsci.productivity-energy-flow'], estimatedMinutes: 20,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame nitrogen as the limiting nutrient.', script: "Atmosphere is 78% nitrogen — but plants can\'t use it. The N₂ molecule is too stable. Only specific bacteria can \"FIX\" nitrogen into usable forms. The whole ecosystem hinges on this. Phosphorus has its own bottleneck — no atmospheric stage at all.", estimatedMinutes: 2 },
    { id: 'concept-nitrogen', kind: 'concept', goal: 'Cover nitrogen cycle steps.',
      keyIdeas: [
        'NITROGEN CYCLE — five key processes (memorize order):',
        '  • NITROGEN FIXATION: N₂ (atmospheric) → NH₃/NH₄⁺ (ammonia/ammonium). Performed by:',
        '    - Symbiotic bacteria in legume roots (e.g., Rhizobium in soybean nodules).',
        '    - Free-living soil bacteria (Azotobacter).',
        '    - Cyanobacteria in water.',
        '    - Lightning (small amount).',
        '    - Industrial Haber-Bosch process (synthesizes fertilizer).',
        '  • NITRIFICATION: NH₄⁺ → NO₂⁻ (nitrite) → NO₃⁻ (nitrate). Performed by nitrifying bacteria (Nitrosomonas → Nitrobacter). NO₃⁻ is the form most plants absorb.',
        '  • ASSIMILATION: plants absorb NO₃⁻ (or sometimes NH₄⁺) and incorporate into amino acids, proteins, DNA. Animals get N by eating plants/animals.',
        '  • AMMONIFICATION: decomposers convert dead organic N back to NH₄⁺.',
        '  • DENITRIFICATION: NO₃⁻ → N₂ (returned to atmosphere). Performed by anaerobic bacteria in oxygen-poor soils/wetlands.',
        'KEY: nitrogen FIXATION and DENITRIFICATION are MIRROR PROCESSES — fixation pulls N from air; denitrification returns N to air.',
        'WHY N IS OFTEN LIMITING: although abundant in atmosphere, biologically usable forms (NO₃⁻, NH₄⁺) are scarce. Adding N fertilizer typically boosts plant growth.',
        'HUMAN DISRUPTIONS to nitrogen cycle:',
        '  • SYNTHETIC FERTILIZER (Haber-Bosch process): doubles natural nitrogen-fixation rate globally.',
        '  • RUNOFF: excess fertilizer washes into streams → EUTROPHICATION (algal blooms → oxygen depletion → fish kills). Gulf of Mexico DEAD ZONE from Mississippi runoff.',
        '  • COMBUSTION: high-temp combustion (cars, power plants) creates NOx → acid rain, smog.',
        'PHOSPHORUS CYCLE — major differences from N:',
        '  • NO ATMOSPHERIC STAGE. P stays in solid/dissolved form.',
        '  • Source: WEATHERING of phosphate-containing rocks releases PO₄³⁻ into soil/water.',
        '  • Plant uptake → consumed by animals → released back via decomposition or excretion.',
        '  • Eventual SEDIMENTATION on ocean floor — geological uplift returns rocks to land slowly.',
        '  • Often LIMITING in freshwater systems (just as N often limits land/marine).',
        'HUMAN DISRUPTIONS to phosphorus cycle:',
        '  • PHOSPHATE MINING for fertilizer (finite resource).',
        '  • DETERGENTS (banned in many places now).',
        '  • FERTILIZER RUNOFF → eutrophication of freshwater lakes (Lake Erie algal blooms).',
      ],
      vocabulary: [
        { term: 'nitrogen fixation', definition: 'converting atmospheric N₂ to biologically usable forms (NH₃, NH₄⁺).' },
        { term: 'eutrophication', definition: 'nutrient enrichment of water → algal bloom → O₂ depletion → fish kill.' },
        { term: 'denitrification', definition: 'NO₃⁻ → N₂; returns N to atmosphere; anaerobic bacteria.' },
      ],
      estimatedMinutes: 7 },
    { id: 'worked-eutrophication', kind: 'worked_example',
      problem: 'A farmer applies excess nitrogen fertilizer to his fields. Heavy rain washes the fertilizer into a nearby pond. Trace the chain of events leading to fish kills.',
      steps: [
        'STEP 1 — Fertilizer (rich in NO₃⁻ and PO₄³⁻) enters pond. Nutrient enrichment.',
        'STEP 2 — ALGAL BLOOM: algae explode in population given the nutrients.',
        'STEP 3 — Algae quickly die off (life cycle short or shading themselves out).',
        'STEP 4 — Decomposers break down dead algae using OXYGEN — DECOMPOSITION CONSUMES DISSOLVED O₂.',
        'STEP 5 — Pond becomes HYPOXIC (low oxygen) or ANOXIC (no oxygen).',
        'STEP 6 — FISH KILL: fish suffocate. Surviving organisms are mostly anaerobic.',
      ],
      answer: 'Fertilizer → algal bloom → die-off → decomposition consumes O₂ → fish kill (eutrophication).', estimatedMinutes: 4 },
    { id: 'try-process-id', kind: 'try_yourself',
      problem: 'Identify the nitrogen-cycle process in each: \n(a) A soybean plant\'s root nodules absorb N₂ via Rhizobium bacteria. \n(b) Bacteria in waterlogged soil convert NO₃⁻ to N₂ gas. \n(c) Nitrosomonas converts NH₄⁺ to NO₂⁻. \n(d) A leaf falls; bacteria break it down; NH₄⁺ is released to soil.',
      expectedAnswer: '(a) Nitrogen fixation. (b) Denitrification. (c) Nitrification. (d) Ammonification (also called mineralization).',
      responseFormat: 'free', hints: ['Match each to a named cycle process.'], estimatedMinutes: 3 },
    { id: 'try-compare', kind: 'try_yourself',
      problem: 'Name TWO differences between the nitrogen and phosphorus cycles.',
      expectedAnswer: '(1) NITROGEN has an atmospheric stage (78% of air is N₂); PHOSPHORUS does NOT have an atmospheric stage — stays in soil/water/rocks. \n(2) Nitrogen has many biological-microbial steps (fixation, nitrification, denitrification); phosphorus is mostly weathering + assimilation + decomposition + sedimentation. \n(3) The N cycle has rapid biotic flux; P cycle is slow (relies on geologic uplift to return ocean sediments to land). \n(4) Limiting nutrient differs: N often limits terrestrial/marine; P often limits freshwater.',
      responseFormat: 'free', hints: ['Atmospheric stage; flux speed; limiting in different ecosystems.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. The Mississippi River watershed drains farmland heavy in N and P fertilizer. The Gulf of Mexico has a "dead zone" the size of New Jersey each summer. (a) Identify the cause. (b) Trace how fertilizer becomes a dead zone. (c) Suggest two on-farm or watershed-level practices to reduce the dead zone.',
      expectedAnswer: '(a) NUTRIENT POLLUTION (mainly N from fertilizer runoff) leading to EUTROPHICATION. (1.5)\n(b) Fertilizer applied to fields → spring rain runoff → enters streams → flows into Mississippi → discharged into Gulf → algal bloom in nutrient-rich seawater → algae die → decomposers consume DO (dissolved oxygen) → hypoxic zone where fish/crustaceans die or flee → recurring summer dead zone. (3)\n(c) Practices: \n• PRECISION AGRICULTURE — apply only as much fertilizer as plants need; use soil testing. \n• COVER CROPS in winter to prevent runoff and absorb residual N. \n• BUFFER STRIPS (vegetated borders) along streams to absorb runoff before it reaches water. \n• CONSTRUCTED WETLANDS to filter agricultural drainage. \n• Reduced/no-till farming. \n• Manure management — keep livestock waste out of waterways. (2.5)\nTotal: 7 points.',
      responseFormat: 'frq', hints: ['Cause; mechanism; mitigation at source.'], estimatedMinutes: 5 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'N cycle: fixation, nitrification, assimilation, ammonification, denitrification.',
      'Fixation = N₂ → NH₃/NH₄⁺. Denitrification = NO₃⁻ → N₂.',
      'P cycle: NO atmospheric stage; weathering → uptake → decomposition → sedimentation.',
      'Both cycles disrupted by fertilizer runoff → eutrophication → dead zones.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '1', cedTopic: '1.5-1.6', cedTitle: 'Nitrogen and Phosphorus Cycles', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '3', note: 'Standard nutrient cycles.' }] },
};
