/**
 * AP Environmental Science — CED Unit 4.4+4.5: Earth's Atmosphere and
 * Global Wind Patterns.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U4_ATMOSPHERE_WIND: LessonPlan = {
  id: 'evelyn.ap.envsci.atmosphere-wind.v1', title: 'U4.2 Atmosphere and Global Wind Patterns',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.atmosphere-wind', description: 'Identify atmospheric layers and gas composition. Explain Coriolis effect and convection cells (Hadley, Ferrel, Polar). Predict global wind belts and prevailing winds. Describe rain shadow effect.', standard: 'AP-ENVSCI-4.4-4.5' }],
  prerequisites: ['apenvsci.plate-tectonics-soil'], followUps: ['apenvsci.watersheds-solar'], estimatedMinutes: 20,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame Earth\'s circulating atmosphere.', script: "The atmosphere isn\'t just a still blanket. It CIRCULATES in giant convection cells. Equatorial heating drives the engine. Earth\'s rotation deflects winds. The result: predictable patterns of rain belts, deserts, and prevailing winds.", estimatedMinutes: 2 },
    { id: 'concept-atmosphere', kind: 'concept', goal: 'Cover layers, composition, circulation.',
      keyIdeas: [
        'ATMOSPHERIC LAYERS (bottom to top):',
        '  • TROPOSPHERE (0-12 km): where weather happens; temperature decreases with altitude. Most water vapor here.',
        '  • STRATOSPHERE (12-50 km): contains OZONE LAYER (~20-30 km, blocks UV). Temperature INCREASES with altitude (UV absorption by ozone).',
        '  • MESOSPHERE (50-85 km): coldest layer; meteors burn up.',
        '  • THERMOSPHERE (85-600+ km): aurora; very thin air.',
        'GAS COMPOSITION of dry air (memorize):',
        '  • N₂ (nitrogen): 78%.',
        '  • O₂ (oxygen): 21%.',
        '  • Ar (argon): 0.9%.',
        '  • CO₂: ~0.04% (420 ppm in 2024). Greenhouse gas.',
        '  • Trace: water vapor (variable), Ne, He, CH₄.',
        'CONVECTION CELLS — three pairs of Hadley/Ferrel/Polar cells per hemisphere drive global circulation:',
        '  • HADLEY CELL: equator to ~30° latitude. Warm air rises at equator → moves poleward → cools and SINKS at ~30° → returns to equator at surface. SINKING air at 30° creates DESERT BELTS (Sahara, Middle East, Australia, southwestern US).',
        '  • FERREL CELL: 30° to 60° latitude. Mid-latitudes — variable weather.',
        '  • POLAR CELL: 60° to pole. Sinking cold dense air at poles.',
        'CORIOLIS EFFECT: due to Earth\'s rotation, moving air (and water) is DEFLECTED — RIGHT in Northern Hemisphere, LEFT in Southern Hemisphere. Stronger at higher latitudes. Causes:',
        '  • Cyclones rotate counter-clockwise in N. hemisphere, clockwise in S.',
        '  • Wind belts curve.',
        'GLOBAL WIND BELTS (resulting from convection + Coriolis):',
        '  • TRADE WINDS: 0-30°. From east toward equator (NE in N, SE in S). Drove sailing ships from Europe to Americas.',
        '  • WESTERLIES: 30-60°. From west. Drove return voyages.',
        '  • POLAR EASTERLIES: 60-90°. From east.',
        'INTERTROPICAL CONVERGENCE ZONE (ITCZ): where N and S Hadley cells converge near equator. Heavy rain belt.',
        'RAIN SHADOW: when moist air rises over a mountain range, it cools, condenses, and rains on the windward side. After crossing the peak, it descends, warms, and is dry on the leeward side. Creates desert just downwind of mountains. Examples: Death Valley (downwind of Sierras); eastern Cascades (Washington); Atacama (downwind of Andes).',
      ],
      vocabulary: [
        { term: 'Hadley cell', definition: 'tropical convection cell from equator to 30°; sinking creates deserts.' },
        { term: 'Coriolis effect', definition: 'apparent deflection of moving objects due to Earth\'s rotation.' },
        { term: 'rain shadow', definition: 'dry zone leeward of mountains; common cause of regional deserts.' },
      ],
      estimatedMinutes: 6 },
    { id: 'worked-deserts', kind: 'worked_example',
      problem: 'Why are most major deserts located near 30° latitude? Use atmospheric circulation to explain.',
      steps: [
        'STEP 1 — Equatorial sun heats air → air rises (low pressure at equator, lots of rain).',
        'STEP 2 — Rising air cools, dumps moisture as rain over equator.',
        'STEP 3 — Now-dry air moves poleward at high altitude (within Hadley cell).',
        'STEP 4 — Around 30° latitude, the cooled-but-now-dry air SINKS toward surface.',
        'STEP 5 — Sinking air WARMS as it descends (compression heating) and remains DRY (already lost moisture).',
        'STEP 6 — At surface, this dry warm air creates a HIGH-pressure belt with little precipitation → DESERTS.',
        'STEP 7 — Examples: Sahara, Arabia, Australian outback, Mojave/Sonoran (US), Atacama (S. America), Kalahari (S. Africa).',
      ],
      answer: 'Hadley cell descending dry air at 30° latitude creates global desert belts.', estimatedMinutes: 4 },
    { id: 'try-coriolis', kind: 'try_yourself',
      problem: 'A hurricane forms in the Atlantic at 20°N. Without Earth\'s rotation, it would just move toward low pressure. With Coriolis: (a) which direction is the hurricane deflected? (b) Which direction does its rotation spin?',
      expectedAnswer: '(a) DEFLECTED to the RIGHT in N hemisphere. So a hurricane moving northward gets deflected toward the east, then back; or moving westward gets deflected northward — net effect is the curving paths typical of hurricanes (often hitting Florida from the east, then curving north). (b) ROTATES COUNTER-CLOCKWISE (cyclonic in N hemisphere). Air flowing INTO the low pressure center is deflected right — creates counter-clockwise spiral. (Tropical cyclones in S hemisphere rotate clockwise.)',
      responseFormat: 'free', hints: ['Right in N. hemisphere.'], estimatedMinutes: 3 },
    { id: 'try-rainshadow', kind: 'try_yourself',
      problem: 'The Sierra Nevada mountains run N-S in California. Prevailing winds come from the Pacific (west). Predict which side is wet, which is dry, and name a desert downwind.',
      expectedAnswer: 'WESTERN (windward) side: wet. Pacific moisture pushed up by mountains; cools and rains. Heavy snowpack, rainforest in places. \nEASTERN (leeward) side: DRY. Air descends, warms, has already lost moisture. \nDOWNWIND DESERTS: Death Valley (lowest point in US, hottest in summer), Mojave Desert. The Great Basin (Nevada, Utah) is also rain-shadow desert.',
      responseFormat: 'free', hints: ['Wind hits west, wet up + dry down on east.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. (a) Why does the equator have the highest precipitation despite receiving the most direct sunlight (which you might expect to dry it out)? (b) Why do tropical rainforests cluster along the equator? (c) What happens to the ITCZ during seasons?',
      expectedAnswer: '(a) High insolation HEATS surface and lower atmosphere → AIR RISES → moisture-laden air COOLS as it rises → CONDENSATION → heavy precipitation. So strong heating actually drives the rain belt. The ITCZ tracks where Hadley cells converge and air rises hardest. (2)\n(b) Tropical rainforests need: \n• Year-round high temperatures (equator, no winter). \n• Year-round high precipitation (rising air at ITCZ). \n• Long growing season (no frost). \nClustered at equator because that\'s where these conditions converge. Amazon, Congo, Indonesian rainforests all lie within ~10° of equator. (1.5)\n(c) ITCZ MIGRATES with seasons:\n• Northern Summer (June-August): sun overhead is at Tropic of Cancer (23.5°N). ITCZ shifts NORTH. Brings monsoon to S. Asia, W. Africa. \n• Southern Summer (Dec-Feb): sun overhead at Tropic of Capricorn (23.5°S). ITCZ shifts SOUTH. Brings rains to S. America, S. Africa, N. Australia. \n• Equatorial regions get rain twice a year (when ITCZ passes through twice). \n• ITCZ migration also drives MONSOON systems. (2.5)\nTotal: 6 points.',
      responseFormat: 'frq', hints: ['Convection drives rain; ITCZ drives biome distribution; seasonal migration.'], estimatedMinutes: 5 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Atmosphere: troposphere (weather), stratosphere (ozone), mesosphere, thermosphere.',
      'Composition: 78% N₂, 21% O₂, 0.04% CO₂.',
      '3 cells per hemisphere: Hadley (0-30°), Ferrel (30-60°), Polar (60-90°). Sinking at 30° → deserts.',
      'Coriolis: deflects right in N, left in S; drives global wind belts.',
      'Rain shadow: dry side leeward of mountains.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '4', cedTopic: '4.4-4.5', cedTitle: 'Atmosphere and Wind', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '7', note: 'Standard atmospheric circulation.' }] },
};
