/**
 * AP Environmental Science — CED Unit 8.3+8.7+8.8: Endocrine Disruptors,
 * POPs, Bioaccumulation/Biomagnification.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U8_TOXICS_POPS_BIOMAG: LessonPlan = {
  id: 'evelyn.ap.envsci.toxics-pops-biomag.v1', title: 'U8.3 Endocrine Disruptors, POPs, Biomagnification',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.toxics-pops-biomag', description: 'Define endocrine disruptors and their health effects. Identify persistent organic pollutants (POPs) and their characteristics. Trace biomagnification through trophic levels.', standard: 'AP-ENVSCI-8.3+8.7+8.8' }],
  prerequisites: ['apenvsci.eutrophication-thermal'], followUps: ['apenvsci.solid-waste'], estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame toxic chemistry.', script: "Some pollutants don\'t go away. They PERSIST in the environment for decades — accumulating in fat tissues, biomagnifying up the food chain, disrupting hormones at vanishingly small doses. They\'re a permanent legacy of 20th-century chemistry.", estimatedMinutes: 2 },
    { id: 'concept-toxics', kind: 'concept', goal: 'Cover endocrine disruptors, POPs, biomagnification.',
      keyIdeas: [
        'ENDOCRINE DISRUPTORS: chemicals that interfere with hormone systems. Many bind hormone receptors and either MIMIC or BLOCK natural hormones.',
        'EXAMPLES:',
        '  • BPA (bisphenol A): in plastics; binds estrogen receptors. Linked to developmental effects, reproductive issues.',
        '  • PHTHALATES: in PVC plastics, cosmetics. Reduce sperm count.',
        '  • DDT (older): mimics estrogen. Caused eggshell thinning in birds.',
        '  • ATRAZINE (herbicide): feminizes male frogs.',
        '  • PCBs (polychlorinated biphenyls): industrial; disrupt thyroid + reproduction.',
        '  • PESTICIDES like organophosphates.',
        '  • Pharmaceuticals (especially birth control, hormones) excreted into water.',
        'HEALTH EFFECTS:',
        '  • Reproductive problems (fertility, hormonal imbalance).',
        '  • DEVELOPMENTAL effects in fetuses/children.',
        '  • Increased cancer risk (estrogen-sensitive tumors).',
        '  • Metabolic disorders.',
        '  • EXPOSURE CONCERN: low-dose effects can occur at concentrations far below classical toxicity thresholds — disrupts developmental signaling.',
        'PERSISTENT ORGANIC POLLUTANTS (POPs):',
        '  • Characteristics:\n     - PERSISTENT (don\'t break down readily).\n     - BIOACCUMULATIVE (accumulate in fat tissues).\n     - TOXIC.\n     - LONG-RANGE TRANSPORT (carried globally; found in Arctic ice).',
        '  • Examples:\n     - DDT (banned 1972 US).\n     - PCBs (banned 1979 US).\n     - DIOXINS (byproduct of combustion, paper bleaching).\n     - FURANS.\n     - ALDRIN, DIELDRIN, ENDRIN (banned pesticides).\n     - HEXACHLOROBENZENE.\n     - PFAS / PFOA ("forever chemicals" — recent additions).',
        '  • STOCKHOLM CONVENTION (2001): international treaty banning/restricting 12 initial POPs ("dirty dozen"); now 30+ chemicals.',
        '  • US: Toxic Substances Control Act (TSCA) regulates toxic chemicals.',
        'BIOACCUMULATION: a single organism accumulates a substance over its lifetime — concentration in body increases over time.',
        'BIOMAGNIFICATION: substance concentration INCREASES at HIGHER TROPHIC LEVELS as predators eat many prey, each containing some toxin.',
        '  • CLASSIC EXAMPLE — DDT:\n     - Algae: 0.04 ppm.\n     - Zooplankton: 0.4 ppm.\n     - Small fish: 4 ppm.\n     - Larger fish: 40 ppm.\n     - Fish-eating birds: 400 ppm.\n     - Concentration multiplied 10,000× from algae to top.',
        '  • TRAITS that promote biomagnification:\n     - FAT-SOLUBLE (lipophilic): stored in fat, not flushed out by liver/kidney.\n     - PERSISTENT: doesn\'t break down.\n     - LOW EXCRETION RATE.',
        'HISTORIC CASE — DDT:\n  • Used as agricultural pesticide widely in 1940s-60s.\n  • Caused EGGSHELL THINNING in raptors (interferes with calcium metabolism).\n  • Bald eagles, ospreys, peregrine falcons declined to near-extinction.\n  • RACHEL CARSON\'S "Silent Spring" (1962) raised awareness.\n  • DDT BANNED 1972 in US.\n  • Bird populations recovered; bald eagle delisted from endangered list 2007.',
        'HISTORIC CASE — MERCURY in tuna:\n  • Coal-burning emits mercury.\n  • Atmospheric deposition into oceans.\n  • Accumulates in fish tissue.\n  • TUNA, SWORDFISH, SHARK have highest concentrations.\n  • EPA/FDA advise: pregnant women, children limit consumption (< 1 serving/week).\n  • Long-term: mercury causes neurological damage, especially in developing fetus.',
      ],
      vocabulary: [
        { term: 'endocrine disruptor', definition: 'chemical that interferes with hormone systems.' },
        { term: 'POP', definition: 'persistent organic pollutant — long-lasting, bioaccumulative, toxic.' },
        { term: 'biomagnification', definition: 'increasing concentration at higher trophic levels.' },
      ],
      estimatedMinutes: 6 },
    { id: 'worked-biomag', kind: 'worked_example',
      problem: 'A pesticide enters a lake at 0.04 ppm in algae. Biomagnification factor between trophic levels is 10×. (a) Compute concentrations at each higher level. (b) Identify which characteristics enable this biomagnification.',
      steps: [
        '(a) Concentrations:\n  • Algae: 0.04 ppm.\n  • Zooplankton: 0.04 × 10 = 0.4 ppm.\n  • Small fish: 0.4 × 10 = 4 ppm.\n  • Large fish: 4 × 10 = 40 ppm.\n  • Fish-eating bird: 40 × 10 = 400 ppm.\n  • 10,000× concentration from algae to top predator.',
        '(b) Characteristics enabling biomagnification:\n  • LIPOPHILIC (fat-soluble): stored in fat, not excreted.\n  • PERSISTENT: doesn\'t degrade in environment OR in body.\n  • LOW EXCRETION RATE: body retains it across years.\n  • Eaten by predators that consume MANY prey, each contributing accumulated toxin.\n  • Top predators get the SUM. Birds with longer lifespans accumulate more.',
        '(c) Bird at 400 ppm: extremely high. Likely effects: \n  • Eggshell thinning (DDT-style).\n  • Reproductive failure.\n  • Population decline.\n  • Persisting at top trophic level for the bird\'s lifetime.',
      ],
      answer: 'Algae 0.04 → Zooplankton 0.4 → Small fish 4 → Large fish 40 → Bird 400 ppm. 10,000× total magnification.', estimatedMinutes: 4 },
    { id: 'try-pop-traits', kind: 'try_yourself',
      problem: 'Why are POPs particularly concerning? Identify three characteristics and explain.',
      expectedAnswer: '(1) PERSISTENT — they don\'t break down for decades or even centuries. So they keep accumulating in the environment without being removed. \n(2) BIOACCUMULATIVE — fat-soluble, stored in tissues. Body cannot easily excrete them. Lifetime accumulation builds up. \n(3) TOXIC — even at very low doses, often disrupt hormones, cause cancer, harm development. \n(4) LONG-RANGE TRANSPORT — atmospheric circulation carries them globally, including to Arctic. Found in polar bears, indigenous peoples\' breast milk in Greenland. \nResult: GLOBAL persistent contamination. Banning a chemical NOW doesn\'t reverse the legacy. DDT banned in 1972 still found in soils, sediments, and people\'s bodies decades later.',
      responseFormat: 'free', hints: ['PBT: persistent, bioaccumulative, toxic + transport.'], estimatedMinutes: 3 },
    { id: 'try-modern', kind: 'try_yourself',
      problem: 'PFAS ("forever chemicals") are a recent concern — found in waterproof clothing, non-stick cookware, firefighting foam. Explain why they\'re considered POPs.',
      expectedAnswer: 'PFAS (per- and polyfluoroalkyl substances) qualify as POPs because:\n• PERSISTENT — extremely strong carbon-fluorine bonds. Don\'t break down in environment for decades or centuries (hence "forever chemicals"). \n• BIOACCUMULATIVE — accumulate in human and animal tissues. Detected in blood of nearly all Americans. \n• TOXIC — linked to: kidney/testicular cancer, immune dysfunction, thyroid disorders, increased cholesterol, low birth weight, reduced vaccine response. \n• LONG-RANGE — found in remote Arctic ecosystems, in rainwater globally. \n• WIDESPREAD — used in 1000s of consumer products. \n• Recent regulatory response: \n  - 2024 EPA designated PFOA and PFOS as hazardous substances. \n  - 2022 PFOA, PFOS limits in drinking water (4 ppt). \n  - Stockholm Convention added several PFAS in 2009-2024. \n  - Bans on use in firefighting foam in some states. \n• Cleanup costs estimated at $billions for water systems.',
      responseFormat: 'free', hints: ['Apply POP criteria to PFAS specifically.'], estimatedMinutes: 4 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Endocrine disruptors interfere with hormones. BPA, phthalates, atrazine, DDT.',
      'POPs: persistent, bioaccumulative, toxic, long-range transport.',
      'Bioaccumulation = within individual; biomagnification = across trophic levels.',
      'DDT classic case: thinned eagle eggshells, banned 1972, populations recovered.',
      'PFAS: modern POP concern; "forever chemicals."',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '8', cedTopic: '8.3+8.7+8.8', cedTitle: 'Toxics, POPs, Biomagnification', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '17', note: 'Standard toxicology.' }] },
};
