/**
 * AP Environmental Science — CED Unit 5.1+5.8+5.11+5.12: Tragedy of the
 * Commons, Overfishing, Ecological Footprint, Sustainability.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U5_COMMONS_FISHING_FOOTPRINT: LessonPlan = {
  id: 'evelyn.ap.envsci.commons-fishing-footprint.v1', title: 'U5.4 Commons, Overfishing, and Sustainability',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.commons-fishing-footprint', description: 'Apply tragedy-of-the-commons theory to shared resources. Identify causes and consequences of overfishing. Calculate ecological footprint. Define sustainability and sustainable development.', standard: 'AP-ENVSCI-5.1+5.8+5.11+5.12' }],
  prerequisites: ['apenvsci.urbanization-water'], followUps: [], estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame the structural problem.', script: "Why do we OVER-EXPLOIT shared resources? Garrett Hardin\'s 1968 essay \"The Tragedy of the Commons\" diagnosed it: each user benefits individually from taking more, but everyone loses collectively. Today: this dynamic explains overfishing — and how we measure our planetary impact.", estimatedMinutes: 2 },
    { id: 'concept-commons', kind: 'concept', goal: 'Cover commons + overfishing + footprint + sustainability.',
      keyIdeas: [
        'TRAGEDY OF THE COMMONS (Hardin 1968): when a resource is COMMONLY HELD (not privately owned, no quota), each user has incentive to take MORE — gains all benefit personally, costs spread across all users. Cumulatively this OVER-EXPLOITS the resource.',
        'CLASSIC EXAMPLES of commons:',
        '  • Open ocean fisheries.',
        '  • Atmospheric carbon sink.',
        '  • Communal grazing lands.',
        '  • Groundwater aquifers.',
        '  • Watershed and air quality.',
        'SOLUTIONS to commons problems:',
        '  • REGULATIONS (catch limits, quotas, bag limits, hunting seasons).',
        '  • PRIVATIZATION (assign tradable rights — ITQs, individual transferable quotas in fisheries).',
        '  • COMMUNITY MANAGEMENT (Ostrom\'s research: local communities can manage commons effectively when monitoring is feasible).',
        '  • TAXES on resource use (carbon tax for atmosphere).',
        '  • TECHNOLOGY (monitoring, GPS).',
        'OVERFISHING is the prototype tragedy of the commons:',
        '  • Open-access ocean fisheries with no global quotas.',
        '  • New technology (sonar, GPS, larger nets) made fishing easier and faster.',
        '  • Result: ~1/3 of global fish stocks overfished; ~60% fully fished (no room for growth); only ~7% underfished.',
        '  • COD (Atlantic, off Newfoundland) collapsed in 1992; still hasn\'t recovered.',
        '  • TUNA, SHARKS, GROUPERS all heavily overfished.',
        'BYCATCH: non-target species caught in fishing gear. Sea turtles, dolphins, sharks, juvenile fish often killed. Trawling is especially destructive.',
        'BOTTOM TRAWLING: drags weighted nets across seafloor. Destroys benthic habitat (corals, sponges) over thousands of years to recover.',
        'FISHING SOLUTIONS:',
        '  • CATCH LIMITS / QUOTAS.',
        '  • SIZE LIMITS (allow juveniles to mature).',
        '  • SEASONAL CLOSURES (during spawning).',
        '  • MARINE PROTECTED AREAS (no-take zones — fish populations recover, spillover supports surrounding fisheries).',
        '  • SUSTAINABLE GEAR REQUIREMENTS (turtle excluder devices, hook size).',
        '  • CONSUMER CHOICES (Marine Stewardship Council labels).',
        'ECOLOGICAL FOOTPRINT: amount of biologically productive land + sea needed to PRODUCE all resources consumed by a person/household/population AND ABSORB their waste.',
        '  • Units: hectares per person.',
        '  • Earth\'s sustainable capacity: ~1.6 hectares per person.',
        '  • US average: ~8 hectares per person (5× sustainable).',
        '  • If everyone lived US-style: would need ~5 Earths.',
        '  • Lower in developing countries: India ~1, Niger ~0.6.',
        'SUSTAINABILITY: meeting present needs without compromising future generations\' ability to meet their needs (Brundtland Commission, 1987).',
        '  • Three pillars: ENVIRONMENTAL, ECONOMIC, SOCIAL.',
        '  • Environmental sustainability: don\'t deplete resources faster than regeneration; don\'t pollute faster than absorption.',
        'SUSTAINABLE DEVELOPMENT: development that meets present needs while protecting environment.',
      ],
      vocabulary: [
        { term: 'tragedy of the commons', definition: 'over-exploitation of a shared resource due to misaligned individual incentives.' },
        { term: 'ecological footprint', definition: 'biologically productive land/sea required to support consumption + absorb waste.' },
        { term: 'sustainability', definition: 'meeting present needs without compromising future generations.' },
      ],
      estimatedMinutes: 6 },
    { id: 'worked-cod', kind: 'worked_example',
      problem: 'The Atlantic cod fishery off Newfoundland collapsed in 1992 after centuries of fishing. Use tragedy of the commons to explain WHY.',
      steps: [
        'STEP 1 — Cod was an OPEN-ACCESS resource — anyone could fish, no quotas, no enforcement.',
        'STEP 2 — Each fishing boat captain had individual incentive to catch as much as possible. Profit was personal; depletion was shared.',
        'STEP 3 — Improved technology (sonar, factory trawlers) increased catches dramatically post-WWII.',
        'STEP 4 — Fishing pressure exceeded reproduction rate. Stock declined.',
        'STEP 5 — Despite warnings from scientists, regulators were politically captive to fishing industry. Quotas set above sustainable yield.',
        'STEP 6 — 1992: cod stock crashed. Canadian government imposed moratorium — too late. \n• 30,000 jobs lost overnight. \n• Cod still hasn\'t fully recovered 30+ years later. \n• Atlantic ecosystem regime-shifted: smaller fish, jellyfish dominate.',
        'STEP 7 — Lesson: open-access + improving technology + weak regulation = inevitable collapse.',
      ],
      answer: 'Open access + better tech + weak regulation = collapse. Classic commons tragedy.', estimatedMinutes: 4 },
    { id: 'try-fishery-mgmt', kind: 'try_yourself',
      problem: 'Suggest three policies to make fishing more sustainable. For each, explain the mechanism and a potential downside.',
      expectedAnswer: '(1) CATCH QUOTAS (Total Allowable Catch / ITQs): scientists set a sustainable yield; quotas allocated to fishers. Mechanism: limits total extraction. Downside: quotas may be set too high politically; poaching; allocation issues. \n(2) MARINE PROTECTED AREAS (MPAs): no-take zones in critical habitats. Mechanism: fish populations recover; spillover benefits surrounding fishery. Downside: enforcement difficult on open ocean; fishers oppose loss of grounds. \n(3) GEAR RESTRICTIONS (banning bottom trawling, mandating turtle excluder devices): reduces bycatch, habitat damage. Downside: more selective fishing reduces total catch. \n(4) SEASONAL CLOSURES during spawning: protects reproduction. Downside: forces seasonal employment cycles. \n(5) SIZE LIMITS: only fish above certain size taken. Mechanism: juveniles can mature. Downside: bycatch mortality of small fish. \n(6) CONSUMER LABELING (MSC): consumer pressure drives sustainable practices. Downside: certification can be gamed; doesn\'t cover all fisheries.',
      responseFormat: 'free', hints: ['Multiple management tools; trade-offs in each.'], estimatedMinutes: 4 },
    { id: 'try-footprint', kind: 'try_yourself',
      problem: 'A typical American has an ecological footprint of 8 hectares; a typical Bangladeshi has 0.6 hectares. (a) Why so different? (b) Earth\'s biocapacity is ~12 billion hectares for 8 billion people. What\'s sustainable per person? (c) If everyone consumed at US level, what would be true?',
      expectedAnswer: '(a) Differences:\n• ENERGY USE — Americans use ~10× more energy per capita (driving, AC, electronics, manufacturing). \n• MEAT CONSUMPTION — Americans eat ~3× more meat (high footprint per kcal). \n• HOUSING — larger homes, more materials, more land. \n• CONSUMPTION — more clothing, electronics, throwaway goods. \n• LOWER POPULATION DENSITY in US allows sprawling lifestyle. \n(b) Sustainable per person = 12 billion / 8 billion = 1.5 hectares per person. \n(c) US ≈ 8 hectares × 8 billion people = 64 billion hectares needed. Earth has 12 billion. We\'d need ~5 Earths to support 8B people at US lifestyle. Not possible.',
      responseFormat: 'numeric', hints: ['Per-capita differences; sustainable share.'], estimatedMinutes: 4 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. Hardin (1968) argued that the commons problem requires "mutual coercion mutually agreed upon" (regulation). Some economists disagreed, suggesting privatization or community management. Use the open-ocean fisheries case to evaluate three approaches: (a) International quota, (b) Private property rights, (c) Community management. Discuss feasibility for OCEANS specifically.',
      expectedAnswer: '(a) INTERNATIONAL QUOTA (Hardin\'s preferred):\n• Mechanism: nations agree on Total Allowable Catch; allocations enforced. \n• Pros: scientific basis; collective action against extractive industry. \n• Cons: enforcement on high seas is HARD. Nations have economic incentive to exceed quotas. Free-rider problem (a country that ignores quota benefits while others reduce). Fish migrate across borders. \n• Feasibility: PARTIAL — Some success in Northern fisheries (cod, salmon). Failed for tuna in some regions. Best when species\' range falls within enforceable EEZs (Exclusive Economic Zones). (3)\n(b) PRIVATIZATION (Coasean approach):\n• Mechanism: assign individual transferable quotas (ITQs); fishers own permanent fishing rights. \n• Pros: aligns incentives — owners want long-term sustainability. Has worked in some fisheries (Iceland, New Zealand). \n• Cons: \n  - Hard to assign property rights to migrating fish. \n  - Concentrates fishing rights in fewer (larger) hands. \n  - Doesn\'t address foreign fishing or illegal poaching. \n  - Poor people excluded from buying quotas. \n• Feasibility: WORKS for some species in some EEZs; doesn\'t solve high-seas problem. (3)\n(c) COMMUNITY MANAGEMENT (Ostrom\'s approach):\n• Mechanism: local fishing communities self-organize, monitor, enforce rules. \n• Pros: Effective for SMALL, LOCAL fisheries (lobsters in Maine, sea urchin Japan). Sociocultural capital strong. \n• Cons: Doesn\'t scale to GLOBAL HIGH-SEAS fisheries (no community claims open ocean). Requires geographically defined community of users with shared interests. Modern industrial fleets disrupt this. \n• Feasibility: GOOD for coastal/local fisheries; fails for international high-seas fisheries. (3)\nCONCLUSION: in practice, ocean management uses a HYBRID — international quotas + EEZs + ITQs in some areas + MPAs + community co-management. No single approach perfect for the global commons. (1)\nTotal: 10 points.',
      responseFormat: 'frq', hints: ['Compare approaches with feasibility for high-seas case.'], estimatedMinutes: 7 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Tragedy of commons: open access + individual incentive → over-exploitation.',
      'Solutions: regulation, privatization, community management.',
      'Overfishing: 1/3 of stocks over-exploited; cod collapse the warning.',
      'Ecological footprint: US ~8 ha/person; sustainable is ~1.5 ha; 5x overshoot.',
      'Sustainability: meeting present needs without compromising future.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '5', cedTopic: '5.1+5.8+5.11+5.12', cedTitle: 'Commons, Fishing, Footprint', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '13,15', note: 'Standard commons + sustainability.' }] },
};
