/**
 * AP Environmental Science — CED Unit 3.6+3.7: Age Structure Diagrams and
 * Total Fertility Rate.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U3_AGE_STRUCTURE_FERTILITY: LessonPlan = {
  id: 'evelyn.ap.envsci.age-structure-fertility.v1', title: 'U3.3 Age Structure and Fertility',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.age-structure-fertility', description: 'Read and interpret age structure (population pyramid) diagrams to predict population trajectory. Define total fertility rate (TFR) and replacement-level fertility. Connect TFR to population trajectory.', standard: 'AP-ENVSCI-3.6-3.7' }],
  prerequisites: ['apenvsci.carrying-capacity-growth'], followUps: ['apenvsci.demographic-transition'], estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame the population pyramid.', script: "Look at a country\'s POPULATION PYRAMID — a bar chart of people by age and sex — and you can predict its growth for the next 50 years. Wide base = young population, will grow. Narrow base = aging, will shrink. Today: how to read these and what they predict.", estimatedMinutes: 2 },
    { id: 'concept-pyramid', kind: 'concept', goal: 'Cover age structure + TFR + replacement-level.',
      keyIdeas: [
        'AGE STRUCTURE DIAGRAM (population pyramid): horizontal bar chart with age groups stacked vertically (youngest at bottom). Males on left, females on right. Bar length = percent of total population in that age-sex group.',
        'THREE TYPICAL SHAPES:',
        '  • EXPANDING (broad-base pyramid): many young, few old. High birth rate, future growth. Examples: Niger, Uganda, Afghanistan.',
        '  • STABLE (column / rectangle): roughly equal across ages. Birth rate ≈ death rate. Examples: USA, UK, France.',
        '  • DECLINING / TOP-HEAVY (narrow base, wider middle): more elderly than children. Will shrink. Examples: Japan, Italy, Germany.',
        'WHAT A PYRAMID PREDICTS:',
        '  • Expanding → lots of young people will reach reproductive age → continued growth.',
        '  • Stable → reproductive replacement balances mortality → flat trajectory.',
        '  • Declining → too few young people to replace dying elderly → population decreases over time.',
        '  • POPULATION MOMENTUM: even if fertility drops to replacement level, an expanding pyramid will keep growing for ~30-50 years as young cohorts move through their reproductive years.',
        'TOTAL FERTILITY RATE (TFR): the AVERAGE number of children a woman would have over her lifetime, given current age-specific fertility rates. NOT the same as births per year.',
        'REPLACEMENT-LEVEL FERTILITY: the TFR needed to maintain population size over time, accounting for child mortality. \n  • In LOW-mortality countries: ~2.1 (each woman replaces herself + male partner; the 0.1 accounts for childhood mortality and gender ratio).',
        '  • In HIGH-mortality countries: 2.5-3.0+ (need more births to compensate for higher infant/child mortality).',
        'CURRENT WORLD TFR: ~2.3 (2024). Has been falling worldwide; expected to drop to ~1.8 by 2100.',
        'TFR PATTERNS:',
        '  • TFR ≈ 1.0-1.5: well below replacement; population aging and shrinking. Japan (1.3), Italy (1.2), South Korea (0.7 — the lowest in world).',
        '  • TFR ≈ 1.8-2.2: near replacement. USA (~1.7), UK, France.',
        '  • TFR ≈ 4-7: high fertility, population growing. Niger (6.5), Somalia (6.0), DRC (6.0).',
        'FACTORS LOWERING TFR:',
        '  • Education, especially of women.',
        '  • Access to contraception and family planning.',
        '  • Women in workforce (delayed childbearing).',
        '  • Urbanization (children less economically valuable).',
        '  • Lower infant mortality (parents don\'t need many to ensure survival).',
        '  • Higher cost of raising children (modern economies).',
      ],
      vocabulary: [
        { term: 'population pyramid', definition: 'age-sex distribution chart predicting future population trends.' },
        { term: 'TFR', definition: 'total fertility rate — average lifetime children per woman.' },
        { term: 'replacement-level fertility', definition: 'TFR needed to maintain population (~2.1 in low-mortality settings).' },
        { term: 'population momentum', definition: 'continued growth from young cohorts even after fertility drops.' },
      ],
      estimatedMinutes: 6 },
    { id: 'worked-pyramid', kind: 'worked_example',
      problem: 'Country X has a population pyramid where children 0-9 represent 35% of the population and adults over 60 represent 5%. Country Y has 0-9 at 12% and over-60 at 25%. Predict each country\'s 50-year population trajectory.',
      steps: [
        'STEP 1 — COUNTRY X: very wide base (35% young), very narrow top (5% old). EXPANDING pyramid. \n  • Young cohorts will reach reproductive age and have children. \n  • Population will GROW substantially over next 50 years even if TFR drops (population momentum). \n  • Likely TFR is high (4-6).',
        'STEP 2 — COUNTRY Y: narrow base (12% young), heavy top (25% old). DECLINING pyramid. \n  • Few young people to reach reproductive age. \n  • Population will DECLINE over next 50 years. \n  • Likely TFR is low (1.0-1.5).',
        'STEP 3 — Implications differ: X faces resource pressure, education needs; Y faces aging-population challenges (pensions, healthcare, shrinking workforce).',
      ],
      answer: 'X will grow; Y will shrink.', estimatedMinutes: 4 },
    { id: 'try-tfr', kind: 'try_yourself',
      problem: 'For each country, predict whether population will grow, stay stable, or decline (in low-mortality setting): (a) Country with TFR = 1.4. (b) TFR = 2.1. (c) TFR = 3.5.',
      expectedAnswer: '(a) DECLINE. 1.4 well below replacement (2.1). Population will shrink and age. \n(b) STABLE. At replacement level. Population remains roughly constant (assuming no big migration). \n(c) GROW. TFR 3.5 is well above replacement → growing population. Likely a developing country.',
      responseFormat: 'free', hints: ['Replacement-level ≈ 2.1 in low-mortality.'], estimatedMinutes: 2 },
    { id: 'try-momentum', kind: 'try_yourself',
      problem: 'China\'s TFR dropped from 6.0 in 1965 to 1.2 in 2022. Yet its population kept GROWING until 2022, then started shrinking. Why the lag?',
      expectedAnswer: 'POPULATION MOMENTUM. China\'s 1965 fertility produced enormous cohorts of young people. As those young people aged into their reproductive years, they had children — even if fewer per woman than their mothers — adding to the population. \nThe massive cohorts of 30-50 year olds in 2010-2020 were the result of the high-fertility decades. Their continued reproduction (even at low rates) plus low death rates (improved medicine) kept population growing. \nOnly when those large cohorts age past reproductive age AND die does the population finally start to decline. The lag is typically 30-50 years between fertility drop and population peak. China hit peak in 2022 — about 50 years after fertility started dropping.',
      responseFormat: 'free', hints: ['Lag from young cohorts moving through reproductive years.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. Country X has TFR = 5.5, broad-base pyramid, infant mortality 80/1000, mostly rural population. Country Y has TFR = 1.3, top-heavy pyramid, infant mortality 4/1000, urbanized. (a) Identify likely development stage of each. (b) Predict population trajectory of each over 50 years. (c) Explain how lowering TFR in X might lower TFR. (d) What challenges does Y face?',
      expectedAnswer: '(a) X: developing/early demographic transition. High fertility, high mortality. Rural agriculture, children economic asset. \nY: post-industrial. Low fertility, low mortality. Urban, children economic cost. (1.5)\n(b) X: GROW substantially. Even if TFR falls, population momentum → continued growth ~50 years. \nY: SHRINK and AGE. Already declining; will see 10-30% decrease over 50 years. (2)\n(c) X\'s TFR could lower via:\n• Education access (especially for girls). \n• Family planning programs / contraceptive access. \n• Urbanization. \n• Increased women\'s economic participation. \n• Reduced infant mortality (parents need fewer births to ensure survival). (2)\n(d) Y\'s challenges:\n• AGING POPULATION → strain on pensions, healthcare. \n• SHRINKING WORKFORCE → fewer workers per retiree. \n• Declining tax base. \n• Need IMMIGRATION or pro-natal policies to compensate. \n• Rural school closures, economic stagnation. (1.5)\nTotal: 7 points.',
      responseFormat: 'frq', hints: ['Diagnose, predict, prescribe interventions.'], estimatedMinutes: 5 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Population pyramid: wide base = expanding; column = stable; narrow base = declining.',
      'TFR ≈ 2.1 = replacement (low-mortality settings); 2.5-3+ in high-mortality.',
      'Population momentum: 30-50 year lag between TFR drop and population decline.',
      'TFR drops with education, urbanization, women\'s participation, lower infant mortality.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '3', cedTopic: '3.6-3.7', cedTitle: 'Age Structure and Fertility', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '6', note: 'Standard demography.' }] },
};
