/**
 * AP Environmental Science — CED Unit 5.10+5.13: Urbanization and Methods
 * to Reduce Urban Runoff.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U5_URBANIZATION_WATER: LessonPlan = {
  id: 'evelyn.ap.envsci.urbanization-water.v1', title: 'U5.3 Urbanization and Stormwater Management',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.urbanization-water', description: 'Identify environmental impacts of urbanization (urban heat island, impervious surfaces, habitat loss, runoff). Describe green-infrastructure methods to reduce urban runoff and pollution.', standard: 'AP-ENVSCI-5.10+5.13' }],
  prerequisites: ['apenvsci.forestry-mining'], followUps: ['apenvsci.commons-fishing-footprint'], estimatedMinutes: 16,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame the urban transformation.', script: "Cities cover ~3% of land but house >55% of people. Urbanization radically transforms ecosystems — replacing forest/wetland with concrete. Today: impacts and how green infrastructure can offset some damage.", estimatedMinutes: 2 },
    { id: 'concept-urban', kind: 'concept', goal: 'Cover urban impacts + green infrastructure.',
      keyIdeas: [
        'URBANIZATION: shift of population from rural to urban areas. Currently >55% urban; projected 68% by 2050.',
        'URBAN ENVIRONMENTAL IMPACTS:',
        '  • IMPERVIOUS SURFACES: pavement, roofs prevent water infiltration → stormwater runoff dominates.',
        '  • URBAN HEAT ISLAND: cities are 2-7°C warmer than surrounding rural areas due to concrete absorbing heat, reduced vegetation, building waste heat. Worse during summer; raises AC demand → more emissions.',
        '  • AIR POLLUTION: concentrated emissions from vehicles, buildings, industry. Higher PM2.5, NOx, ozone.',
        '  • LIGHT POLLUTION: bright sky disrupts ecosystems (migrating birds disoriented, etc.) and human circadian rhythms.',
        '  • HABITAT LOSS / FRAGMENTATION: forests and wetlands replaced; remaining green spaces small and isolated.',
        '  • WASTE: huge volumes of municipal waste, sewage, hazardous waste.',
        '  • NOISE POLLUTION: stress on humans + wildlife.',
        'STORMWATER PROBLEM in cities:',
        '  • Rain falls on impervious surfaces.',
        '  • Concentrated in storm drains → discharged into streams/rivers RAPIDLY.',
        '  • Carries: oil from cars, road salt, sediment, pet waste, lawn fertilizer/pesticides, heavy metals.',
        '  • COMBINED SEWER OVERFLOWS (CSOs): in older cities (Boston, NYC, etc.), stormwater + sewage share same pipes. Heavy rain overwhelms treatment plant → raw sewage discharged into waterways.',
        '  • Result: streams flooded with polluted runoff during storms; flow drops to nothing between storms.',
        'GREEN INFRASTRUCTURE — design strategies that mimic natural water cycling:',
        '  • RAIN GARDENS: shallow plantings designed to collect runoff and let it infiltrate.',
        '  • PERMEABLE PAVEMENT: porous concrete/pavers allow water to soak through.',
        '  • GREEN ROOFS: vegetation on rooftops; absorbs rain, reduces heat island.',
        '  • CONSTRUCTED WETLANDS: filter pollutants and store stormwater.',
        '  • BIOSWALES: vegetated channels along roads that slow and clean runoff.',
        '  • RAIN BARRELS / CISTERNS: collect rainwater for reuse.',
        '  • TREE CANOPY: intercept rain; cool through evapotranspiration; combat heat island.',
        '  • POROUS PARKING LOTS, swales, infiltration basins.',
        'URBAN PLANNING FOR SUSTAINABILITY:',
        '  • Mixed-use zoning (reduces car trips).',
        '  • Public transit investment.',
        '  • Bicycle/pedestrian infrastructure.',
        '  • PRESERVE green space (parks, urban forests).',
        '  • DENSITY (taller buildings) reduces sprawl.',
      ],
      vocabulary: [
        { term: 'impervious surface', definition: 'pavement/concrete that prevents water infiltration.' },
        { term: 'urban heat island', definition: '2-7°C warmer in cities due to concrete + reduced vegetation.' },
        { term: 'green infrastructure', definition: 'natural-process design (rain gardens, etc.) for stormwater.' },
      ],
      estimatedMinutes: 5 },
    { id: 'worked-runoff', kind: 'worked_example',
      problem: 'A 50-acre forested watershed is converted to a strip mall. Predict three changes to local water hydrology.',
      steps: [
        'STEP 1 — INFILTRATION DECREASES: paved surfaces prevent water from soaking in.',
        'STEP 2 — RUNOFF INCREASES: water flows off paved surfaces into storm drains rapidly.',
        'STEP 3 — Stream peak flows INCREASE during storms — flooding risk rises.',
        'STEP 4 — Stream BASE FLOW (between storms) DECREASES — less groundwater recharge keeping the stream flowing.',
        'STEP 5 — Stream water QUALITY degrades: sediment, oil, road salt, fertilizer enter via runoff.',
        'STEP 6 — AQUATIC HABITAT degraded: flashier flows, warmer water (concrete heated), polluted.',
        'STEP 7 — Downstream COMMUNITIES have higher flood risk and water-treatment costs.',
      ],
      answer: 'Less infiltration, more runoff, flash floods, polluted water, degraded streams.', estimatedMinutes: 3 },
    { id: 'try-green-infra', kind: 'try_yourself',
      problem: 'A new urban shopping center is being built. Suggest three green-infrastructure features that would reduce its hydrological impact and explain how each works.',
      expectedAnswer: '(1) PERMEABLE PARKING LOT — porous concrete/pavers in parking areas. Rain soaks INTO ground rather than running off. Mimics natural soil. \n(2) GREEN ROOF on the building. Vegetated rooftop absorbs rain, reduces runoff volume by ~50-70%. Also reduces heat island effect, insulates building. \n(3) RAIN GARDENS in landscaped areas. Shallow depressions planted with deep-rooted natives. Captures runoff from roofs and parking; infiltrates into groundwater while plants filter pollutants. \n(4) BIOSWALES along roadway edges — vegetated channels that slow runoff, allow it to infiltrate while filtering pollutants. \n(5) NATIVE TREE PLANTINGS — deep-rooted, intercept rain, reduce wind, cool the area.',
      responseFormat: 'free', hints: ['Mimic natural infiltration with permeable surfaces and vegetation.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. A growing city is experiencing flash floods, stream pollution, urban heat-island temperatures 6°C above rural surroundings, and combined-sewer overflows. (a) Diagnose the underlying causes. (b) Suggest a comprehensive green-infrastructure plan addressing each issue. (c) What ECONOMIC arguments support investment in green infrastructure?',
      expectedAnswer: '(a) Underlying causes:\n• Excessive IMPERVIOUS SURFACES → fast runoff → flash floods. \n• REPLACEMENT of vegetation with concrete → less evapotranspiration cooling → urban heat island. \n• OLDER COMBINED SEWERS overwhelmed by stormwater + sewage → CSO. \n• Vehicle emissions + parking-lot runoff carry pollutants to streams. (2)\n(b) Comprehensive green-infrastructure plan:\n• Mandate PERMEABLE PAVEMENT for new parking lots. \n• REQUIRE GREEN ROOFS on commercial buildings >5000 sq ft. \n• Build BIOSWALES along major streets. \n• Plant 10,000 STREET TREES — provides shade, intercepts rain, fights heat island. \n• Install RAIN GARDENS in parks and right-of-way areas. \n• CONSTRUCTED WETLANDS at strategic locations to filter runoff. \n• Separate stormwater from sewage (capital intensive but solves CSO). \n• POROUS pavement repaving program. \n• Citizen RAIN BARREL incentives. (3)\n(c) Economic arguments:\n• REDUCED FLOOD DAMAGE — green infrastructure handles 1-2 inch storms better than gray. \n• LOWER WATER TREATMENT COSTS — cleaner runoff means less to clean at plant. \n• ENERGY SAVINGS — green roofs reduce AC needs (~25% summer). \n• PROPERTY VALUES rise near green spaces (3-15% premium). \n• REDUCED HEAT-ISLAND mortality — heat waves kill thousands; cooler cities save lives. \n• Tourism/livability premium attracts businesses, residents. \n• Employment in installation/maintenance creates green jobs. \n• Long-term CHEAPER than expanding gray infrastructure. (3)\nTotal: 8 points.',
      responseFormat: 'frq', hints: ['Diagnose; multi-strategy plan; economic justification.'], estimatedMinutes: 6 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Urbanization: imperv surfaces, heat island, air/light pollution, habitat loss.',
      'Stormwater carries pollution; CSOs in older cities discharge sewage during storms.',
      'Green infrastructure: rain gardens, permeable pavement, green roofs, bioswales, trees.',
      'Green infrastructure economics often beats gray infrastructure long-term.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '5', cedTopic: '5.10+5.13', cedTitle: 'Urbanization and Stormwater', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '14', note: 'Standard urban impacts + green infrastructure.' }] },
};
