/**
 * AP Environmental Science — CED Unit 5.3+5.4+5.5+5.6+5.7+5.14+5.15+5.16:
 * Agriculture (Green Revolution, irrigation, pesticides, livestock, IPM,
 * sustainable agriculture, aquaculture).
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U5_AGRICULTURE: LessonPlan = {
  id: 'evelyn.ap.envsci.agriculture.v1', title: 'U5.1 Agriculture and Food Production',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.agriculture', description: 'Trace Green Revolution and identify environmental impacts of industrial agriculture. Compare irrigation methods. Distinguish pesticide types. Understand IPM, sustainable agriculture, and aquaculture trade-offs.', standard: 'AP-ENVSCI-5.3-5.7+5.14-5.16' }],
  prerequisites: [], followUps: ['apenvsci.forestry-mining'], estimatedMinutes: 22,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame agriculture as transformation.', script: "Feeding 8 billion people requires industrial-scale agriculture. The Green Revolution enabled this — but at significant environmental cost. Today: methods, impacts, and sustainable alternatives.", estimatedMinutes: 2 },
    { id: 'concept-ag', kind: 'concept', goal: 'Cover Green Rev, impacts, irrigation, pest, livestock, IPM, sust ag, aquaculture.',
      keyIdeas: [
        'GREEN REVOLUTION (1940s-1960s): dramatic increase in food production via:',
        '  • HIGH-YIELD VARIETIES (HYVs) — selectively bred for higher productivity (e.g., Norman Borlaug\'s wheat, IRRI rice).',
        '  • SYNTHETIC FERTILIZERS (Haber-Bosch nitrogen).',
        '  • CHEMICAL PESTICIDES.',
        '  • IRRIGATION expansion.',
        '  • MECHANIZATION (tractors, combines).',
        '  • FOSSIL-FUEL DEPENDENT — high energy per calorie produced.',
        'GREEN REVOLUTION IMPACTS:',
        '  • POSITIVE: averted famines (esp. India, Mexico); doubled global yields.',
        '  • NEGATIVE: monoculture vulnerability; soil degradation; pesticide pollution; water depletion; loss of crop genetic diversity.',
        'INDUSTRIAL AGRICULTURE IMPACTS:',
        '  • SOIL DEGRADATION: erosion (10× faster than soil formation); compaction; nutrient depletion.',
        '  • WATER USE: 70% of human freshwater goes to agriculture.',
        '  • EUTROPHICATION: fertilizer runoff → algal blooms → dead zones.',
        '  • PESTICIDE POLLUTION: groundwater contamination; biomagnification (DDT precedent).',
        '  • GHG EMISSIONS: livestock (methane), N₂O from fertilizer, fossil fuels for machinery.',
        'IRRIGATION METHODS:',
        '  • FLOOD/FURROW: water flows over fields. Cheap; INEFFICIENT (~40% reaches plant); causes waterlogging, salinization.',
        '  • SPRAY/SPRINKLER: like rain. Better; ~70% efficient; energy needed.',
        '  • DRIP IRRIGATION: water delivered at root zone via tubes. Highly efficient (~90%); high upfront cost. Best for sustainability.',
        '  • SALINIZATION: salt accumulates in soil from repeated evaporation of irrigation water; reduces fertility (Aral Sea, Mesopotamia historical decline).',
        'PESTICIDE TYPES:',
        '  • INSECTICIDES (kill insects), HERBICIDES (kill weeds), FUNGICIDES, RODENTICIDES.',
        '  • Issues: PEST RESISTANCE evolves (overuse drives selection); BENEFICIAL insects killed; biomagnification.',
        '  • PERSISTENT pesticides (DDT) — bioaccumulate. Banned 1972 in US.',
        'INTEGRATED PEST MANAGEMENT (IPM): minimize pesticides via:',
        '  • Crop rotation; resistant varieties; biological controls (predators, parasitoids); pheromone traps.',
        '  • Pesticide as LAST resort, applied only when economically necessary.',
        'SUSTAINABLE AGRICULTURE practices:',
        '  • CROP ROTATION — alternates crops year-to-year; breaks pest cycles, balances nutrients.',
        '  • POLYCULTURE / INTERCROPPING — multiple crops in same field; mimics natural diversity.',
        '  • COVER CROPS — winter cover (rye, clover) prevents erosion, fixes nitrogen.',
        '  • CONSERVATION TILLAGE / NO-TILL — reduces soil disturbance.',
        '  • ORGANIC FARMING — no synthetic pesticides/fertilizers.',
        'LIVESTOCK and FOOD CHOICES:',
        '  • Beef has highest environmental footprint per calorie (water, land, GHG).',
        '  • CAFOs (concentrated animal feeding operations): efficient meat production but high pollution (manure runoff), antibiotic use, animal welfare concerns.',
        '  • Plant-based diets reduce footprint; the 10% rule (eating low on food chain).',
        'AQUACULTURE: fish farming. ~50% of seafood eaten today is farmed.',
        '  • POSITIVE: reduces pressure on wild fisheries; controlled production.',
        '  • NEGATIVE: pollution (waste), antibiotic use, escape of farmed fish (genetic dilution of wild), fish-feed pressure on wild stocks (carnivorous farmed species need wild fishmeal).',
        '  • SUSTAINABLE: filter feeders (oysters, clams), herbivores (tilapia), closed-system fishfarms.',
      ],
      vocabulary: [
        { term: 'Green Revolution', definition: 'mid-20th-century yield increases from HYVs, fertilizers, pesticides, irrigation.' },
        { term: 'IPM', definition: 'integrated pest management — minimize pesticides via biological/cultural controls.' },
        { term: 'salinization', definition: 'salt buildup in irrigated soil; reduces fertility.' },
      ],
      estimatedMinutes: 7 },
    { id: 'worked-irrigation', kind: 'worked_example',
      problem: 'A farmer in California currently uses flood irrigation. Water costs are rising and the region faces drought. Recommend an alternative method and justify with environmental and economic benefits.',
      steps: [
        'STEP 1 — Recommend DRIP IRRIGATION.',
        'STEP 2 — Environmental benefits: ~90% efficiency (vs ~40% for flood) → 50% LESS WATER USED. Reduces groundwater depletion. Less salinization (less water → less salt deposition).',
        'STEP 3 — Economic benefits: lower water bill (less water used). Fertilizer can be applied through drip system (FERTIGATION) — uses less fertilizer too. Higher yields per unit water.',
        'STEP 4 — Trade-offs: high upfront cost for installation. May need maintenance.',
        'STEP 5 — Net: drip irrigation pays back over 3-7 years in arid agriculture.',
      ],
      answer: 'Drip irrigation: 90% efficient, less salinization, lower water/fertilizer costs.', estimatedMinutes: 4 },
    { id: 'try-ipm', kind: 'try_yourself',
      problem: 'A farmer wants to reduce pesticide use on a tomato crop. Suggest three IPM strategies. For each, explain the mechanism.',
      expectedAnswer: '(1) CROP ROTATION — plant tomatoes in different field each year. Breaks pest life cycles (specific pests can\'t accumulate in one location). \n(2) BIOLOGICAL CONTROL — release ladybugs to eat aphids. Or trichogramma wasps to parasitize caterpillar eggs. Targets specific pests without chemicals. \n(3) RESISTANT VARIETIES — choose tomato cultivars bred for resistance to common pests/diseases. \n(4) MONITORING & THRESHOLDS — only apply pesticide IF pest population exceeds economic threshold (avoid prophylactic spraying). \n(5) PHEROMONE TRAPS — disrupt pest mating cycles. \n(6) MECHANICAL/PHYSICAL — row covers, sticky traps, crop residue removal.',
      responseFormat: 'free', hints: ['Pesticide as last resort; biological/cultural alternatives.'], estimatedMinutes: 3 },
    { id: 'try-aquaculture', kind: 'try_yourself',
      problem: 'A company wants to start a salmon farm. Identify two environmental concerns and how they could be mitigated.',
      expectedAnswer: '(1) WASTE POLLUTION: salmon excrete waste, uneaten food → eutrophies surrounding water. Mitigation: closed-system tanks (recirculating aquaculture); rotating cage locations; lower fish density. \n(2) ESCAPED FISH: farmed salmon escape and breed with wild fish, diluting wild gene pool. Mitigation: sterile (triploid) farmed fish; secure containment; native species only. \n(3) FEED FROM WILD STOCKS: salmon are carnivorous; need fishmeal from wild fish. Mitigation: switch to plant-based feed (insect protein, soy); shift to lower-trophic farmed species. \n(4) ANTIBIOTICS: dense conditions promote disease, treated with antibiotics → antibiotic resistance, water pollution. Mitigation: lower density, vaccines, genetic selection for disease resistance.',
      responseFormat: 'free', hints: ['Pollution, escapes, feed source, antibiotics.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. The Green Revolution dramatically increased global food production but had significant environmental costs. (a) Identify three KEY innovations of the Green Revolution. (b) Identify three NEGATIVE environmental consequences. (c) Suggest how modern sustainable agriculture might address each negative consequence.',
      expectedAnswer: '(a) Green Revolution innovations:\n• HIGH-YIELD VARIETIES (semi-dwarf wheat/rice with shorter stems supporting larger grain heads). \n• SYNTHETIC FERTILIZERS (especially Haber-Bosch nitrogen). \n• CHEMICAL PESTICIDES. \n• IRRIGATION EXPANSION (canals, dams, pumped wells). \n• MECHANIZATION. (2)\n(b) Negative consequences:\n• EUTROPHICATION from fertilizer runoff (Gulf of Mexico dead zone, etc.). \n• SOIL DEGRADATION: erosion, compaction, salinization from irrigation. \n• AQUIFER DEPLETION (Ogallala, Punjab, Saudi). \n• BIODIVERSITY LOSS: monoculture vulnerability, genetic narrowing of crops, pesticide effects on pollinators and beneficials. \n• PESTICIDE RESISTANCE: continued evolution of resistant pests requires more pesticide. \n• HIGH FOSSIL-FUEL DEPENDENCY → climate change. (3)\n(c) Sustainable agriculture solutions:\n• Reduce eutrophication: precision agriculture, cover crops, buffer strips, integrated nutrient management (use only as much fertilizer as needed). \n• Address soil degradation: no-till farming, cover crops, terracing, IRRIGATION efficiency (drip), avoid waterlogging. \n• Address biodiversity loss: crop rotation, polyculture/intercropping, hedgerows for pollinators, IPM (Integrated Pest Management) reduces pesticide use. \n• Reduce energy use: organic farming, integrated systems with livestock manure for fertilizer. \n• AGROFORESTRY (combining trees with crops) restores ecosystems while producing food. (3)\nTotal: 8 points.',
      responseFormat: 'frq', hints: ['Innovation, consequences, mitigation framework.'], estimatedMinutes: 6 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Green Revolution: HYVs + fertilizer + pesticides + irrigation + mechanization. Doubled yields with environmental cost.',
      'Irrigation efficiency: flood (40%) < spray (70%) < drip (90%). Salinization risk.',
      'IPM minimizes pesticides via biological + cultural controls.',
      'Sustainable ag: rotation, cover crops, no-till, polyculture, agroforestry.',
      'Aquaculture trade-offs: feeds people but pollution, escapes, antibiotics.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '5', cedTopic: '5.3-5.7+5.14-5.16', cedTitle: 'Agriculture and Food Production', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '12', note: 'Standard agriculture coverage.' }] },
};
