/**
 * AP Research — Phase 1: Formulating a Research Question.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_RESEARCH_U1_RESEARCH_QUESTION: LessonPlan = {
  id: 'evelyn.ap.research.research-question.v1', title: 'R1 Formulating a Research Question',
  curriculum: 'AP', grade: '12', subject: 'ss', topic: 'ap-research', locale: 'en',
  los: [{ id: 'apresearch.research-question', description: 'Formulate an answerable, focused, original research question. Identify gaps in existing literature. Distinguish researchable from non-researchable questions.', standard: 'AP-RESEARCH-QUEST' }],
  prerequisites: [], followUps: ['apresearch.literature-review'], estimatedMinutes: 22,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame the research question as the foundation.', script: "Your AP Research project lives or dies by your QUESTION. A good question is FOCUSED, RESEARCHABLE with available methods, and addresses a GAP. A weak question dooms the rest. Today: how to formulate one.", estimatedMinutes: 2 },
    { id: 'concept-question', kind: 'concept', goal: 'Cover question criteria, gap identification, narrowing.',
      keyIdeas: [
        'A GOOD research question is:',
        '  • FOCUSED — narrow enough to investigate within scope (one academic year, ~5000-word paper).',
        '  • RESEARCHABLE — answerable with available methods, data, time, and resources.',
        '  • ORIGINAL — addresses a GAP in existing knowledge.',
        '  • COMPLEX — not answerable by simple "yes/no" or single fact.',
        '  • FEASIBLE — within your access, expertise, ethical constraints.',
        '  • SIGNIFICANT — matters to a discipline, community, or stakeholder.',
        '',
        'TYPES of research questions:',
        '  • DESCRIPTIVE: "What is the prevalence of X?"',
        '  • EXPLANATORY: "Why does X happen?"',
        '  • PREDICTIVE: "How does X relate to Y?"',
        '  • EXPLORATORY: "What patterns emerge in X?"',
        '  • EVALUATIVE: "How effective is X?"',
        '',
        'COMMON STRUCTURES:',
        '  • "What is the relationship between X and Y in [context]?"',
        '  • "How do [population] experience [phenomenon]?"',
        '  • "To what extent does [variable] influence [outcome]?"',
        '  • "Why do [population] do [behavior] in [context]?"',
        '',
        'WHAT MAKES A QUESTION TOO BROAD vs TOO NARROW:',
        '  • TOO BROAD: "How does education affect society?" (entire disciplines)',
        '  • BETTER: "How does outdoor recess time affect 4th-grade focus in suburban schools?"',
        '  • TOO NARROW: "Did Mrs. Smith\'s class improve after recess on Tuesday?" (one observation)',
        '',
        'IDENTIFYING GAPS:',
        '  • Read existing literature in your topic area.',
        '  • Look for: contradictory findings, unanswered questions, populations not studied, methods not used, recent developments.',
        '  • Discuss with mentor / teacher / domain experts.',
        '',
        'ITERATIVE REFINEMENT:',
        '  • Start with broad interest → narrow over weeks.',
        '  • Read 5-10 sources → identify what\'s known and unknown.',
        '  • Refine question based on what\'s feasible.',
        '  • Get feedback from teacher.',
        '',
        'NON-RESEARCHABLE QUESTIONS (avoid):',
        '  • Pure opinion or value judgment ("Is X morally right?").',
        '  • Yes/no without analysis ("Did Y happen?").',
        '  • Already definitively answered ("Is the Earth round?").',
        '  • Beyond your access ("What happens in classified meetings?").',
        '  • Predictions about the future you can\'t test.',
      ],
      vocabulary: [
        { term: 'research gap', definition: 'unanswered question or under-explored area in existing literature.' },
        { term: 'feasibility', definition: 'whether a question can be investigated given resources and ethics.' },
        { term: 'specificity', definition: 'the level of detail in a research question.' },
      ],
      estimatedMinutes: 7 },
    { id: 'worked-narrowing', kind: 'worked_example',
      problem: 'A student wants to research social media. Walk through narrowing this to a research-able question.',
      steps: [
        'STEP 1 — START BROAD: "How does social media affect people?"',
        '  • Issue: too broad (covers all populations, all platforms, all effects).',
        'STEP 2 — Narrow population: "How does social media affect TEENAGERS?"',
        '  • Still broad (which teenagers? which platforms? what outcome?).',
        'STEP 3 — Narrow platform/context: "How does TIKTOK USE affect TEENAGERS\' SLEEP PATTERNS?"',
        '  • Now specific platform + specific outcome. Better.',
        'STEP 4 — Narrow population further: "...affect HIGH SCHOOL JUNIORS\' SLEEP PATTERNS in [specific high school or geographic region]?"',
        '  • Researchable population. Could survey ~50-200 students.',
        'STEP 5 — REFINE: "To what extent does daily TikTok usage correlate with sleep quality and duration among 11th graders at [specific high school]?"',
        '  • FOCUSED, RESEARCHABLE, has correlation framework. \n  • Methodology suggested: surveys, sleep logs.',
        'STEP 6 — VERIFY in literature: existing studies on screen time + sleep, but few specifically on TikTok\'s short-form video format with this age group → there\'s likely a gap.',
        'CONCLUSION: from too broad → research-able question in 5 iterations.',
      ],
      answer: 'Start broad → narrow population, platform, outcome → verify gap.', estimatedMinutes: 4 },
    { id: 'try-evaluate', kind: 'try_yourself',
      problem: 'For each, identify if it\'s a GOOD research question. If not, suggest improvement: (a) "Is climate change real?" (b) "What are the causes of poverty?" (c) "How do online learning platforms affect engagement among rural high schoolers?" (d) "Is Shakespeare a good writer?"',
      expectedAnswer: '(a) NOT GOOD — already definitively answered scientifically. Better: "What perceptions do high school seniors hold about climate change?" \n(b) TOO BROAD — entire disciplines study this. Better: "How does access to early childhood education affect college enrollment in [specific community]?" \n(c) GOOD — focused, researchable, narrow population. Could investigate via surveys, focus groups, observation. \n(d) NOT RESEARCHABLE — value judgment / opinion. Better: "How do Shakespeare\'s themes resonate with contemporary high school students?" or "What stylistic features distinguish Shakespeare from contemporary playwrights?"',
      responseFormat: 'free', hints: ['Researchable, specific, gap-addressing.'], estimatedMinutes: 3 },
    { id: 'try-question', kind: 'try_yourself',
      problem: 'AP-style synthesis. A student is interested in mental health. (a) Generate 3 progressively narrower research questions about this topic. (b) For your final narrowest question, identify methods needed. (c) Identify ONE potential ethical concern.',
      expectedAnswer: '(a) Narrowing progression:\n• BROAD: "How does mental health affect people?" \n• MIDDLE: "How does anxiety affect academic performance?" \n• NARROW: "To what extent does test anxiety correlate with course performance among AP students at [specific high school]?" \n(b) Methods for the narrow question:\n• SURVEYS — standardized anxiety scale (e.g., Test Anxiety Inventory). \n• ACADEMIC RECORDS — course performance data with consent. \n• Possibly INTERVIEWS for qualitative depth. \n• STATISTICAL ANALYSIS (correlation, regression). \n(c) Ethical concerns:\n• PRIVACY — students disclosing anxiety + grades. \n• CONFIDENTIALITY of disclosed mental health data. \n• INFORMED CONSENT (and assent for minors). \n• Avoiding harm to participants discussing sensitive topics. \n• CONSENT FROM PARENTS for under-18. \n• IRB/IRC approval needed before collecting data. \n• Anonymization of identities in final paper.',
      responseFormat: 'frq', hints: ['Narrow systematically; methods + ethics.'], estimatedMinutes: 5 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Good research question: focused, researchable, original, complex, feasible, significant.',
      'Narrow systematically: topic → population → context → variable.',
      'Identify gaps in existing literature.',
      'Avoid: pure opinion, already-answered, too broad, not feasible.',
      'Iterate with feedback from mentor/teacher.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: 'R1', cedTopic: 'QUEST', cedTitle: 'Research Question', sources: [{ type: 'concept', book: 'frankfort-nachmias', chapter: '1', note: 'Standard research question formulation.' }] },
};
