/**
 * Grades 9-10 CS — Python Functions.
 */

import type { LessonPlan } from '../types';

export const SEED_G910_CS_PYTHON_FUNCTIONS: LessonPlan = {
  id: 'evelyn.g910.cs.python.functions.v1',
  title: 'Python — Functions, Parameters, and Return Values',
  curriculum: 'CCSS',
  grade: '9',
  subject: 'cs',
  topic: 'intro-python',
  locale: 'en',
  los: [
    {
      id: 'g910.cs.python.functions',
      description: 'Define and call Python functions with parameters, return values, default arguments, and proper scope.',
      standard: 'CSTA-2-AP-14',
    },
  ],
  prerequisites: ['g910.cs.python.control-flow'],
  followUps: [],
  estimatedMinutes: 16,
  segments: [
    {
      id: 'hook',
      kind: 'hook',
      goal: 'Functions package up code for reuse — and let you build complex programs from simple parts.',
      script: 'Imagine writing the same 5 lines every time you want to greet a user. With a function, you write it ONCE and call it whenever needed. Functions also organise code so you can REASON about each piece separately. Today: the building blocks of every non-trivial program.',
      estimatedMinutes: 1,
    },
    {
      id: 'concept-functions',
      kind: 'concept',
      goal: 'Definition, call, parameters, return, scope, defaults, common patterns.',
      keyIdeas: [
        'DEFINING a function:',
        '  def function_name(parameter1, parameter2):',
        '      """Optional docstring describing what the function does."""',
        '      # body',
        '      return result',
        'CALLING a function:',
        '  result = function_name(arg1, arg2)',
        '  Arguments are values passed in for parameters.',
        'PARAMETERS: variables in the function\'s definition that receive values.',
        'ARGUMENTS: actual values passed when calling.',
        '  def add(a, b):  # a and b are parameters',
        '      return a + b',
        '  sum = add(3, 5)  # 3 and 5 are arguments',
        'RETURN VALUE: the value the function sends back.',
        '  Without return: function returns None.',
        '  With return: caller gets the returned value.',
        'DEFAULT ARGUMENTS: parameters with a default if not provided:',
        '  def greet(name, greeting="Hello"):',
        '      print(f"{greeting}, {name}!")',
        '  greet("Alex")             # Hello, Alex!',
        '  greet("Alex", "Hi")       # Hi, Alex!',
        'SCOPE: variables defined inside a function are LOCAL; they don\'t exist outside.',
        '  Variables defined outside any function are GLOBAL.',
        '  Best practice: pass values via parameters; return what you need.',
        'WHY FUNCTIONS:',
        '  REUSE: write code once, call many times.',
        '  ABSTRACTION: hide complexity behind a simple interface.',
        '  TESTING: easier to test small functions than monolithic code.',
        '  READABILITY: well-named functions document intent.',
        'COMMON PATTERNS:',
        '  HELPER functions: small utility functions called from main code.',
        '  PURE functions: return a value, no side effects (don\'t modify globals or print). Easier to reason about + test.',
      ],
      vocabulary: [
        { term: 'parameter', definition: 'a variable in a function definition that receives a value when the function is called.' },
        { term: 'return value', definition: 'the value a function sends back to its caller via the return statement.' },
      ],
      estimatedMinutes: 5,
    },
    {
      id: 'worked',
      kind: 'worked_example',
      problem: 'Write a Python function that takes a temperature in Celsius and returns it in Fahrenheit.',
      steps: [
        'Define the function with one parameter:',
        '  def celsius_to_fahrenheit(c):',
        '      """Convert Celsius to Fahrenheit."""',
        '      return c * 9/5 + 32',
        'Test it:',
        '  print(celsius_to_fahrenheit(0))    # 32.0',
        '  print(celsius_to_fahrenheit(100))  # 212.0',
        '  print(celsius_to_fahrenheit(25))   # 77.0',
        'The function is REUSABLE (call as often as needed) and TESTABLE (compare output to known values).',
      ],
      answer: 'def celsius_to_fahrenheit(c): return c * 9/5 + 32',
      estimatedMinutes: 3,
    },
    {
      id: 'try-1',
      kind: 'try_yourself',
      problem: 'Write a function `is_even(n)` that returns True if n is even, False otherwise.',
      expectedAnswer: 'def is_even(n):\n    return n % 2 == 0\n\nThe expression `n % 2 == 0` already returns True or False, so just return the comparison directly. Test: is_even(4) → True; is_even(7) → False.',
      responseFormat: 'free',
      hints: [
        'Use the modulo operator %.',
        'A comparison expression like `x == 0` already evaluates to True or False.',
      ],
      estimatedMinutes: 3,
    },
    {
      id: 'misconception-no-return',
      kind: 'misconception_check',
      question: 'A student writes:\n  def double(x):\n      x * 2\n\n  result = double(5)\n  print(result)  # prints None\nWhy?',
      commonErrors: [
        {
          answer: 'Forgets return statement',
          misconception: 'Confusing computing a value with returning it.',
          correctsTo: 'The function COMPUTES x * 2 but doesn\'t RETURN it. Without `return`, the function implicitly returns None. The fix: add `return` before the expression:\n  def double(x):\n      return x * 2\nNow result = 10. Common bug: students think evaluating an expression automatically returns it. It doesn\'t — Python requires explicit return.',
        },
      ],
      estimatedMinutes: 3,
    },
    {
      id: 'recap',
      kind: 'recap',
      mustRemember: [
        'def name(params): ... return value',
        'No return → function returns None.',
        'Default arguments allow optional parameters.',
        'Local variables stay inside the function (scope).',
        'Pass values in, return what you need out.',
        'Pure functions (return only, no side effects) are easiest to reason about.',
      ],
      estimatedMinutes: 1,
    },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
