/**
 * Grades 9-10 CS — Python Control Flow.
 */

import type { LessonPlan } from '../types';

export const SEED_G910_CS_PYTHON_CONTROL_FLOW: LessonPlan = {
  id: 'evelyn.g910.cs.python.control-flow.v1',
  title: 'Python — Conditionals and Loops',
  curriculum: 'CCSS',
  grade: '9',
  subject: 'cs',
  topic: 'intro-python',
  locale: 'en',
  los: [
    {
      id: 'g910.cs.python.control-flow',
      description: 'Use conditionals (if/elif/else) and loops (while, for) to control program execution.',
      standard: 'CSTA-2-AP-13',
    },
  ],
  prerequisites: [],
  followUps: ['g910.cs.python.functions'],
  estimatedMinutes: 16,
  segments: [
    {
      id: 'hook',
      kind: 'hook',
      goal: 'Control flow lets a program make decisions and repeat work — without it, programs are just sequences.',
      script: 'A program that prints "Hello" once is a one-trick pony. Add an `if` and now it can decide what to print. Add a `for` loop and it can do something a thousand times. Today: the two control-flow tools that turn linear code into useful programs.',
      estimatedMinutes: 1,
    },
    {
      id: 'concept-control-flow',
      kind: 'concept',
      goal: 'Conditionals, comparison + logical operators, while + for loops, common patterns.',
      keyIdeas: [
        'CONDITIONALS:',
        '  if condition:',
        '      do_something()',
        '  elif other_condition:',
        '      do_something_else()',
        '  else:',
        '      default_action()',
        '  Indentation matters in Python — use 4 spaces consistently.',
        'COMPARISON OPERATORS: == (equal), != (not equal), <, >, <=, >=.',
        'LOGICAL OPERATORS: and, or, not.',
        '  if age >= 18 and has_id: print("Allowed in.")',
        '  if not is_logged_in: redirect_to_login()',
        'WHILE LOOP — repeat while a condition is true:',
        '  count = 0',
        '  while count < 5:',
        '      print(count)',
        '      count += 1',
        '  Watch for INFINITE LOOPS (forgetting to update the condition variable).',
        'FOR LOOP — iterate over a sequence:',
        '  for fruit in ["apple", "banana", "cherry"]:',
        '      print(fruit)',
        '  for i in range(5):  # 0, 1, 2, 3, 4',
        '      print(i)',
        '  range(start, stop, step) — flexible iteration.',
        'BREAK + CONTINUE:',
        '  break — exit the loop entirely.',
        '  continue — skip to next iteration.',
        'COMMON PATTERNS:',
        '  COUNTING: keep a counter, increment in the loop.',
        '  ACCUMULATION: build up a list or sum.',
        '  SEARCH: loop until you find an item, break.',
        '  VALIDATION: while loop asking for input until valid.',
      ],
      vocabulary: [
        { term: 'conditional', definition: 'a code structure (if/elif/else) that runs different code depending on a condition\'s truth.' },
        { term: 'iteration', definition: 'one pass through a loop body; loops repeat by iterating.' },
      ],
      estimatedMinutes: 5,
    },
    {
      id: 'worked',
      kind: 'worked_example',
      problem: 'Write a Python loop that prints all even numbers from 1 to 20.',
      steps: [
        'Approach 1: use range with a step:',
        '  for n in range(2, 21, 2):',
        '      print(n)',
        '  This prints 2, 4, 6, ..., 20.',
        'Approach 2: use a conditional inside a loop:',
        '  for n in range(1, 21):',
        '      if n % 2 == 0:',
        '          print(n)',
        '  Same output. The modulo (%) returns the remainder; n % 2 == 0 means n is even.',
        'Both work. Approach 1 is more efficient (only checks even numbers); approach 2 is more general (you could change the condition).',
      ],
      answer: 'Use range(2, 21, 2) or range(1, 21) with if n % 2 == 0.',
      estimatedMinutes: 4,
    },
    {
      id: 'try-1',
      kind: 'try_yourself',
      problem: 'Write a Python loop that asks the user for a positive number, and keeps asking until they enter one.',
      expectedAnswer: 'Use a while loop that re-asks until input is valid:\n  num = -1\n  while num <= 0:\n      num = float(input("Enter a positive number: "))\n  print(f"Got {num}")\nAlternative with break:\n  while True:\n      num = float(input("Enter a positive number: "))\n      if num > 0:\n          break\nThe second pattern is common when the validation is more complex.',
      responseFormat: 'free',
      hints: [
        'Use a while loop that runs until the condition is satisfied.',
        'Convert input() to float() since input() returns a string.',
      ],
      estimatedMinutes: 3,
    },
    {
      id: 'misconception-infinite-loop',
      kind: 'misconception_check',
      question: 'A student writes:\n  count = 0\n  while count < 5:\n      print(count)\nThis runs forever. What\'s missing?',
      commonErrors: [
        {
          answer: 'Forgets to update count',
          misconception: 'Forgetting to mutate the loop variable.',
          correctsTo: 'The condition (count < 5) is checked each iteration. Without updating count, it stays 0 forever — INFINITE LOOP. Add `count += 1` inside the loop to make progress toward the exit condition. The general pattern: every while loop must contain a statement that eventually makes the condition false. If you can\'t see how the loop exits, you have a bug.',
        },
      ],
      estimatedMinutes: 3,
    },
    {
      id: 'recap',
      kind: 'recap',
      mustRemember: [
        'if/elif/else: indentation matters; use 4 spaces.',
        'while: repeat while condition is true; update the condition variable inside.',
        'for: iterate over a sequence; range(start, stop, step) for numeric loops.',
        'break exits loop; continue skips to next iteration.',
        'Always ensure your while loop\'s condition can become false.',
      ],
      estimatedMinutes: 1,
    },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
