/**
 * IB Biology — Genetics Topic.
 */

import type { LessonPlan } from '../types';

export const SEED_IB_BIOLOGY_GENETICS: LessonPlan = {
  id: 'evelyn.ibdp.biology.genetics.v1',
  title: 'IB Biology — Genetics: Mendel, Chromosomes, Genetic Engineering',
  curriculum: 'IB-DP',
  grade: '11-12',
  subject: 'science',
  topic: 'ib-biology',
  locale: 'en',
  los: [{ id: 'ibdp.biology.genetics', description: 'Apply Mendel\'s laws, chromosome theory, sex-linkage, modern biotech (PCR, gel electrophoresis), with NoS framing.', standard: 'IB-DP-BIO-3' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'IB Genetics Topic 3 spans Mendel to CRISPR — high yield + long-tail content.', script: 'Mendel + chromosome theory + biotech tools. IB asks data-analysis questions on inheritance plus knowledge questions on technique. Master both.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Genes/alleles, Mendel laws, chromosomes, sex-linkage, biotech.', keyIdeas: [
      'GENE = section of DNA coding for a trait. ALLELE = version of a gene.',
      'GENOTYPE = alleles present. PHENOTYPE = observable trait.',
      'HOMOZYGOUS = two same alleles. HETEROZYGOUS = two different.',
      'MENDEL\'S LAWS:',
      '  SEGREGATION: each parent passes one allele per gene.',
      '  INDEPENDENT ASSORTMENT: alleles for different genes assort independently (UNLESS linked).',
      'PUNNETT SQUARES for monohybrid + dihybrid crosses.',
      '  Aa × Aa: 1:2:1 genotype, 3:1 phenotype.',
      '  AaBb × AaBb: 9:3:3:1 phenotype.',
      'CODOMINANCE: both alleles fully expressed (e.g. ABO blood: IA + IB → AB type).',
      'MULTIPLE ALLELES: ABO blood has IA, IB, i. IUPAC notation in IB.',
      'POLYGENIC inheritance: many genes contribute (skin colour, height).',
      'SEX-LINKED inheritance:',
      '  Genes on X chromosome.',
      '  Recessive disorders (haemophilia, color-blindness) more common in males.',
      '  Females (XX) need two recessive X alleles to be affected.',
      'CHROMOSOME THEORY (Sutton-Boveri): genes on chromosomes; chromosome behavior in meiosis explains Mendel.',
      'PEDIGREE patterns:',
      '  Autosomal dominant: every generation; affected parent → 50% offspring.',
      '  Autosomal recessive: skips generations; both parents must be carriers.',
      '  X-linked recessive: more males; carrier mothers; never father-to-son.',
      'KARYOTYPE = picture of chromosomes paired by size. Detects trisomy 21 (Down syndrome), other aneuploidies.',
      'BIOTECHNOLOGY (IB-tested):',
      '  PCR amplifies DNA. Three steps cycled: denature (94°C), anneal primers (~55°C), extend with Taq (72°C).',
      '  GEL ELECTROPHORESIS: DNA migrates by size — smaller pieces migrate faster.',
      '  DNA PROFILING: combine PCR + gel; STR repeat patterns are individual-specific.',
      '  GMO: insertion of foreign genes into organisms (Bt cotton, golden rice).',
      '  CLONING: somatic-cell nuclear transfer (Dolly the sheep, 1996).',
      'NoS framing:',
      '  Mendel\'s 1866 paper rediscovered 1900 — example of how knowledge can be lost and rediscovered.',
      '  Hershey-Chase experiment (1952) confirmed DNA (not protein) is genetic material.',
      '  Watson-Crick (1953) double helix — collaborated with Franklin\'s X-ray data.',
    ], vocabulary: [{ term: 'codominance', definition: 'when both alleles in a heterozygote are fully expressed (e.g., AB blood type).' }, { term: 'pedigree', definition: 'a chart showing inheritance of a trait through generations of a family.' }], estimatedMinutes: 6 },
    { id: 'worked', kind: 'worked_example', problem: 'In humans, blood type ABO has alleles IA, IB, i. IA and IB are CODOMINANT; both are dominant over i. A parent is type A (genotype IA i) crossed with a parent type B (IB i). Find offspring genotypes and phenotypes.', steps: [
      'Punnett: parent 1 gametes: IA, i. Parent 2 gametes: IB, i.',
      'Offspring: IA IB, IA i, IB i, i i. Equal probability (1/4 each).',
      'Phenotypes:',
      '  IA IB → AB (codominance).',
      '  IA i → A.',
      '  IB i → B.',
      '  i i → O.',
      'Result: 1/4 AB : 1/4 A : 1/4 B : 1/4 O. Equal probability of all four blood types! Surprising for many.',
    ], answer: '1:1:1:1 ratio of AB : A : B : O.', estimatedMinutes: 5 },
    { id: 'try-1', kind: 'try_yourself', problem: 'A mother is a carrier of haemophilia (X-linked recessive). The father is unaffected. What is the probability of an affected child?', expectedAnswer: 'Mother: X^H X^h (carrier). Father: X^H Y (unaffected). Punnett: X^H X^H, X^H X^h, X^H Y, X^h Y. So: 1/4 unaffected daughter, 1/4 carrier daughter, 1/4 unaffected son, 1/4 AFFECTED son. Affected only in sons. P(affected child) = 1/4. P(affected son specifically) = 1/2 of all sons (half of male offspring).', responseFormat: 'free', hints: ['Set up Punnett with X-chromosome inheritance.', 'Sons inherit X from mother, Y from father.'], estimatedMinutes: 3 },
    { id: 'misconception-male-carrier', kind: 'misconception_check', question: 'A student says males can be carriers of X-linked recessive disorders. What\'s wrong?', commonErrors: [{ answer: 'Males as X-linked carriers', misconception: 'Importing autosomal-carrier logic to sex-linked.', correctsTo: 'Males have ONE X chromosome. If their X carries a recessive allele, they are AFFECTED (they\'ll express it — there\'s no second X to mask). Only females (XX) can be carriers — having one normal and one recessive X. This is exactly why X-linked recessive disorders show up almost exclusively in males. (Females with both Xs recessive are rare.)' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Mendel: segregation + independent assortment.', 'Codominance: both expressed (AB blood); incomplete dominance: intermediate.', 'X-linked recessive: more males affected; carrier mothers.', 'PCR + gel for biotech (memorise steps + temps).', 'Cell theory + NoS framing earn extra marks.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
