/**
 * IB Chemistry — Bonding Topic Deep Dive.
 */

import type { LessonPlan } from '../types';

export const SEED_IB_CHEMISTRY_BONDING: LessonPlan = {
  id: 'evelyn.ibdp.chemistry.bonding.v1',
  title: 'IB Chemistry — Chemical Bonding (Topic 4)',
  curriculum: 'IB-DP',
  grade: '11-12',
  subject: 'science',
  topic: 'ib-chemistry',
  locale: 'en',
  los: [{ id: 'ibdp.chemistry.bonding', description: 'Apply ionic, covalent, and metallic bonding; predict shapes via VSEPR; use hybridisation; explain intermolecular forces.', standard: 'IB-DP-CHEM-4' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Bonding (Topic 4) is the foundation of structure-property reasoning — IB tests it heavily.', script: 'Why is NaCl a hard solid but methane a gas? Different bond types, different forces. IB Chem Topic 4 covers ionic, covalent, metallic bonding + intermolecular forces. Today the systematic framework.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Three bond types, VSEPR, hybridisation, intermolecular forces.', keyIdeas: [
      'IONIC BONDING: between metal (cation) and non-metal (anion). Strong electrostatic attraction. Examples: NaCl, MgO.',
      '  Properties: high MP/BP, conducts electricity when molten or dissolved (ions free), hard, brittle, soluble in polar solvents.',
      'COVALENT BONDING: shared electron pairs between non-metals.',
      '  Single, double, triple bonds (1, 2, 3 shared pairs).',
      '  Bond strength: triple > double > single. Bond length: triple < double < single.',
      'METALLIC BONDING: positive ions in a sea of delocalised electrons. Strong + non-directional.',
      '  Properties: conducts electricity (electrons mobile), malleable + ductile, lustrous, high MP.',
      'POLAR vs NONPOLAR covalent: depends on electronegativity difference.',
      '  ΔEN > 1.7: ionic. 0.4-1.7: polar covalent. < 0.4: nonpolar.',
      '  HF, H₂O, NH₃ have polar bonds.',
      'VSEPR (Valence Shell Electron Pair Repulsion):',
      '  Count electron domains around central atom.',
      '  2 domains: linear (180°). BeCl₂, CO₂.',
      '  3: trigonal planar (120°). BF₃.',
      '  4: tetrahedral (109.5°). CH₄.',
      '    With 1 LP: trigonal pyramidal. NH₃ (~107°).',
      '    With 2 LPs: bent. H₂O (~104.5°).',
      '  5: trigonal bipyramidal. PCl₅.',
      '  6: octahedral. SF₆.',
      '  Lone pairs reduce bond angles (LP-BP > BP-BP repulsion).',
      'HYBRIDISATION:',
      '  sp (linear, 2 domains).',
      '  sp² (trig planar, 3).',
      '  sp³ (tetrahedral, 4).',
      'POLAR MOLECULES: depend on (a) bond polarity, (b) shape symmetry.',
      '  Symmetric shape with polar bonds → can cancel (CO₂ nonpolar despite polar C=O bonds).',
      '  Asymmetric shape → polar (H₂O bent → polar).',
      'INTERMOLECULAR FORCES (between molecules; weaker than bonds):',
      '  London (dispersion) forces: temporary dipoles. Present in ALL molecules. Increase with size/molar mass.',
      '  Dipole-dipole: between polar molecules.',
      '  Hydrogen bonding: H bonded to F, O, or N attracts another N/O/F. Strongest IMF.',
      '  Explains anomalously high BPs of H₂O, HF, NH₃.',
      'GIANT COVALENT NETWORKS: diamond, graphite, SiO₂ — atoms covalently bonded throughout. Very high MP.',
    ], vocabulary: [{ term: 'VSEPR', definition: 'theory predicting molecular shape from arrangement of electron domains around central atom.' }, { term: 'hydrogen bonding', definition: 'strongest intermolecular force; H bonded to F/O/N is attracted to lone pair on another F/O/N.' }], estimatedMinutes: 6 },
    { id: 'worked', kind: 'worked_example', problem: 'Predict the shape, hybridisation, and polarity of CCl₄ vs CHCl₃.', steps: [
      'CCl₄: C is central, 4 bonds (4 electron domains, all bonded). Tetrahedral, 109.5° angles. sp³ hybridised.',
      '  Polarity: C-Cl bonds are polar. But the 4 polar bonds are arranged SYMMETRICALLY in tetrahedron — DIPOLES CANCEL. CCl₄ is NONPOLAR.',
      'CHCl₃: C central, 3 C-Cl + 1 C-H. Tetrahedral with one different bond. Asymmetric.',
      '  C-H much less polar than C-Cl. Net dipole (toward Cl side) doesn\'t cancel. CHCl₃ is POLAR.',
      'Lesson: same TETRAHEDRAL shape; symmetry decides polarity.',
    ], answer: 'CCl₄: tetrahedral, sp³, NONPOLAR. CHCl₃: tetrahedral, sp³, POLAR.', estimatedMinutes: 5 },
    { id: 'try-1', kind: 'try_yourself', problem: 'Why does H₂O have a higher boiling point than H₂S, even though S is heavier than O?', expectedAnswer: 'H₂O has hydrogen bonding (H attached to highly electronegative O). H₂S does not — S is less electronegative, so doesn\'t form classical H-bonds. The strong hydrogen bonds in water require more energy to break, raising BP. H₂O BP = 100°C; H₂S BP = −60°C — a huge difference. This is why hydrogen bonding is highlighted in IB: it explains many "anomalies" of water.', responseFormat: 'free', hints: ['Look at intermolecular forces in each.', 'What requires F, O, or N to form?'], estimatedMinutes: 3 },
    { id: 'misconception-shape-vs-electron', kind: 'misconception_check', question: 'A student says NH₃ is tetrahedral. What should they say?', commonErrors: [{ answer: 'NH₃ is tetrahedral', misconception: 'Confusing electron-domain geometry with molecular shape.', correctsTo: 'NH₃ has 4 ELECTRON DOMAINS around N (3 bonds + 1 lone pair) — so the ELECTRON GEOMETRY is tetrahedral. But the MOLECULAR SHAPE describes only the atom positions (lone pairs are not "atoms"). NH₃ is therefore TRIGONAL PYRAMIDAL with one lone pair at the apex above the N. Bond angles ~107° (compressed from 109.5° by LP repulsion).' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Ionic, covalent, metallic — different bond types, different properties.', 'VSEPR shape from electron domain count + lone pairs.', 'sp/sp²/sp³ for 2/3/4 domains.', 'Polarity: bond polarity + shape symmetry.', 'IMF: London < dipole-dipole < hydrogen bonding < ion-dipole.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
