/**
 * SAT R&W — Transitions and Logical Connectors.
 */

import type { LessonPlan } from '../types';

export const SEED_SAT_RW_TRANSITIONS: LessonPlan = {
  id: 'evelyn.testprep.sat-rw.transitions.v1',
  title: 'SAT R&W — Transitions and Logical Connectors',
  curriculum: 'CCSS',
  grade: 'sat-act',
  subject: 'test-prep',
  topic: 'sat-reading-writing',
  locale: 'en',
  los: [{ id: 'satrw.transitions', description: 'Choose transitions that match the LOGICAL relationship between sentences/clauses.', standard: 'CCSS.ELA.LANGUAGE' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 12,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Transition questions test LOGIC, not vocabulary — match the relationship.', script: 'Choose between "however," "therefore," "moreover," "for example." Each signals a DIFFERENT relationship between sentences. Match logic to transition.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Transition categories, common signals, strategy.', keyIdeas: [
      'TRANSITIONS by RELATIONSHIP type:',
      '  ADDITION (continuing a thought): also, moreover, furthermore, additionally, in addition, similarly.',
      '  CONTRAST (opposing/qualifying): however, nevertheless, on the other hand, yet, still, although, in contrast.',
      '  CAUSE/EFFECT: therefore, thus, consequently, as a result, hence, accordingly, so.',
      '  EXAMPLE: for instance, for example, namely, specifically, such as.',
      '  SEQUENCE: first, next, then, finally, subsequently, meanwhile.',
      '  EMPHASIS: indeed, in fact, certainly, especially, particularly.',
      '  CONCLUSION: in summary, in conclusion, overall, all in all, thus.',
      'STRATEGY for SAT transition questions:',
      '  Read the SENTENCE BEFORE and the SENTENCE AFTER.',
      '  Identify the LOGICAL RELATIONSHIP between them.',
      '  Pick the transition that signals that relationship.',
      '  IGNORE the difficulty of the transition word — pick the LOGICAL fit, not the fanciest.',
      'EXAMPLE:',
      '  "Studying improves test scores. _____, students who study consistently outperform those who cram."',
      '  Relationship: continuation/example. → "For example," or "Indeed," or "Specifically."',
      '  WRONG: "However," (no contrast). "Therefore," (no cause-effect).',
      'TRAPS:',
      '  Transition that fits one of the sentences but not the relationship.',
      '  Transition with wrong logical direction (contrast vs continuation).',
      '  Transition that\'s grammatically correct but contextually wrong.',
      'TEST your choice: read the sentences with the transition INSERTED. Does it sound LOGICAL?',
      'COMMON SAT TRAPS by transition:',
      '  "However" used between two AGREEING sentences (no contrast) — WRONG.',
      '  "Therefore" used between two unconnected sentences (no cause-effect) — WRONG.',
      '  "Moreover" used between contrasting sentences — WRONG (moreover signals continuation).',
    ], vocabulary: [{ term: 'transition', definition: 'a word or phrase signaling the logical relationship between sentences or clauses.' }], estimatedMinutes: 5 },
    { id: 'worked', kind: 'worked_example', problem: 'Choose: "The new policy was expected to reduce traffic. _____, congestion has actually INCREASED in the past month." (A) Therefore (B) Moreover (C) However (D) For example.', steps: [
      'Read both sentences. Sentence 1: policy expected to REDUCE traffic. Sentence 2: actually INCREASED.',
      'Relationship: CONTRAST (expected vs actual).',
      'Pick contrast transition: HOWEVER, NEVERTHELESS, YET.',
      'Match: (C) However.',
      '(A) Therefore would imply effect — wrong direction.',
      '(B) Moreover signals continuation/agreement — wrong.',
      '(D) For example would introduce a specific case — wrong; sentence 2 isn\'t an example.',
    ], answer: '(C) However', estimatedMinutes: 3 },
    { id: 'try-1', kind: 'try_yourself', problem: 'Choose: "The factory produces 500 units per day. _____, demand has been increasing, so they plan to expand." (A) However (B) For example (C) Moreover (D) In conclusion.', expectedAnswer: '(C) Moreover. The two sentences continue/add information (production amount + demand increase). They are AGREEING, not contrasting. (A) However signals contrast — wrong. (B) For example would introduce a specific case — sentence 2 isn\'t an example of production amount. (D) In conclusion would summarise — sentence 2 isn\'t a summary.', responseFormat: 'free', hints: ['Are the sentences agreeing or contrasting?', 'Pick a continuation transition for agreement.'], estimatedMinutes: 3 },
    { id: 'misconception-fancy-transition', kind: 'misconception_check', question: 'A student picks "Furthermore" thinking it sounds sophisticated, regardless of context. Why does this hurt?', commonErrors: [{ answer: 'Pick fanciest', misconception: 'Treating transition selection as vocabulary test.', correctsTo: 'Transitions are LOGIC SIGNALS, not vocabulary showcases. "Furthermore" signals ADDITION/CONTINUATION. If the relationship is CONTRAST, "Furthermore" is WRONG no matter how sophisticated. Pick by LOGIC FIT, not by impressiveness. Simple "But" can be the right answer over "Notwithstanding" if the logic favours the simpler word.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Identify the relationship between sentences first.', 'Match transition to relationship: addition, contrast, cause/effect, example, sequence.', 'Read with transition inserted — does it sound logical?', 'Don\'t pick fanciest — pick fittest.', 'Common traps: contrast where addition needed (or vice versa).'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
