/**
 * World History — Unit 10 CED 10.3: The End of the Cold War.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.hs.whist.end-of-cold-war.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_WHIST_U10_END_OF_COLD_WAR: TopicNotesBaseline = {
  baselineId: 'evelyn.hs.whist.end-of-cold-war.v1',
  course: 'World History',
  cedUnit: 10,
  cedTopic: '10.3',
  cedTitle: 'The End of the Cold War',
  planId: 'evelyn.hs.whist.end-of-cold-war.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-08-01',
  sources: [{ type: 'plan', planId: 'evelyn.hs.whist.end-of-cold-war.v1' }],
  theory: [
    { loId: 'whist.end-of-cold-war', kind: 'framework', title: 'Strong at rockets, weak at refrigerators', content: `STRONG AT ROCKETS, WEAK AT REFRIGERATORS — the Soviet command economy, where central planners set output targets instead of prices and markets, was genuinely good at concentrating resources on a few state priorities: steel, coal, heavy machinery, tanks, the first satellite (1957) and the first human in space (1961). It was bad at everything that requires variety, quality, and fast change — shoes, food distribution, cars, and above all computers, which spread through Western economies in the 1970s and 1980s while Soviet planners struggled to copy them. By the 1980s, shortages and queues for ordinary goods were normal life.` },
    { loId: 'whist.end-of-cold-war', kind: 'framework', title: 'The cost of superpower status', content: `THE COST OF SUPERPOWER STATUS — the Soviet economy was substantially smaller than the American one, yet it tried to match it weapon for weapon while also subsidizing allied governments across Eastern Europe. The 1970s brought détente, a deliberate thaw: direct summits and arms-control agreements (the SALT talks, beginning with SALT I in 1972) capped some categories of nuclear weapons. Détente eased the rivalry but never ended it, and it collapsed at the end of the decade — the Soviet invasion of Afghanistan in 1979 and a sharp rise in tension and military spending on both sides in the early 1980s.` },
    { loId: 'whist.end-of-cold-war', kind: 'framework', title: 'Afghanistan, 1979-1989', content: `AFGHANISTAN, 1979-1989 — the USSR sent troops into Afghanistan to prop up a friendly Communist government against a widening insurgency, and stayed for nearly a decade against fighters who were armed and funded from outside, including by the United States. The war was expensive, unwinnable, and increasingly unpopular at home; Soviet forces withdrew in 1989. It did not by itself bring down the Soviet Union, but it drained money, soldiers, and public confidence at exactly the wrong moment.` },
    { loId: 'whist.end-of-cold-war', kind: 'framework', title: 'Glasnost', content: `GLASNOST — Mikhail Gorbachev became Soviet leader in 1985 believing the system could be saved if it were told the truth about itself. Glasnost ("openness") loosened censorship: newspapers could print what had been unprintable, and the Soviet past — famines, purges, deportations — became suddenly speakable. The credibility breaker was the Chernobyl nuclear disaster of April 1986, when the government hid a catastrophe for days while radiation spread. Once people had permission to ask why, they did not stop at 1986.` },
    { loId: 'whist.end-of-cold-war', kind: 'framework', title: 'Perestroika', content: `PERESTROIKA — "restructuring," Gorbachev's attempt to fix the economy by loosening central control, allowing limited private cooperatives, and giving factories more autonomy. The problem was sequencing: perestroika dismantled the old commands before any working market existed to replace them. Output fell, shortages worsened, and the reforms produced a system that was neither planned nor market — which discredited the reformer and the system at the same time.` },
    { loId: 'whist.end-of-cold-war', kind: 'framework', title: 'The renunciation that mattered most', content: `THE RENUNCIATION THAT MATTERED MOST — Soviet control of Eastern Europe had always rested on one implicit promise: Moscow would send tanks. It had, in Hungary in 1956 and in Prague in 1968 (Topic 10.1). This was the Brezhnev Doctrine — the claim that the USSR could intervene militarily to keep an allied Communist government in power. Gorbachev abandoned it, saying openly that each nation should choose its own path. He may have expected reformed Communist governments to survive the choice. That is not what happened.` },
    { loId: 'whist.end-of-cold-war', content: `1989, THE DOMINO YEAR — Poland went first: the Solidarity trade union, led by Lech Walesa and banned since 1981, was legalized and swept the semi-free elections of June 1989. Hungary opened its border with Austria, and East Germans began escaping westward through it — voting with their feet. On November 9, 1989, a muddled East German announcement about travel rules sent crowds to the Berlin Wall; the overwhelmed guards opened the gates, and no tanks came. Czechoslovakia's Velvet Revolution put the playwright Vaclav Havel, recently a political prisoner, in the presidency within weeks. Romania was the violent exception: Nicolae Ceausescu's government fell after street fighting, and he was executed in December 1989. Germany reunified in October 1990.` },
    { loId: 'whist.end-of-cold-war', kind: 'framework', title: 'The union itself unravels', content: `THE UNION ITSELF UNRAVELS — AND THE ARGUMENT ABOUT WHY — the same openness that freed Eastern Europe worked inside the USSR: Lithuania, Latvia, and Estonia demanded independence, and other republics followed. In August 1991 hardliners staged a coup to stop the slide; it failed in three days when soldiers would not fire and crowds filled Moscow's streets. Authority drained to the republics, and on December 25, 1991, the Soviet flag came down — fifteen independent states where one superpower had been. What followed was uneven: NATO and the European Union expanded eastward, Russia endured a turbulent and impoverishing 1990s, and Yugoslavia broke apart in wars that produced the Srebrenica massacre of 1995 (Topic 9.4) — proof that the peaceful endings of 1989 were an achievement, not a rule. Historians still weigh four explanations against each other — Western and specifically Reagan-era pressure, Gorbachev's own choices, people power in the streets, and long-run economic exhaustion — and serious accounts use all four rather than picking one.` },
    { loId: 'whist.end-of-cold-war', kind: 'definition', title: 'glasnost', content: `"openness" — Gorbachev's policy of loosening censorship so Soviet problems and Soviet history could be discussed publicly.` },
    { loId: 'whist.end-of-cold-war', kind: 'definition', title: 'perestroika', content: `"restructuring" — Gorbachev's attempt to reform the command economy by relaxing central control, which dismantled old mechanisms faster than it built new ones.` },
    { loId: 'whist.end-of-cold-war', kind: 'definition', title: 'Brezhnev Doctrine', content: `the Soviet claim of a right to intervene militarily to keep allied Communist governments in power — enforced in Hungary (1956) and Czechoslovakia (1968), abandoned by Gorbachev in the late 1980s.` },
  ],
  methods: [
    {
      title: 'Worked causal chain',
      steps: [
        `Start with the economic stall, not with any one leader. The command economy could hit a few enormous targets — steel, rockets, warheads — because planners could pour everything into them. It could not deliver variety or keep up with fast-moving technology, so consumer goods stayed scarce and computing fell steadily further behind through the 1970s and 1980s.`,
        `Add the fixed costs. A smaller economy was paying for a full arms race plus subsidies to allied governments across Eastern Europe. Détente and the SALT agreements of the 1970s slowed that bill briefly; the Afghanistan war from 1979 and renewed tension in the early 1980s sent it back up. Money and confidence both drained.`,
        `Now bring in Gorbachev in 1985. His diagnosis was that the system was salvageable if it stopped lying to itself, so glasnost opened up speech and perestroika loosened economic control. Chernobyl in 1986 proved his point about the lying and destroyed public trust at the same time — and perestroika removed the old commands before anything worked in their place, so shortages got worse, not better.`,
        `Follow the consequence into foreign policy — this is the hinge. Eastern European Communist governments had survived on the certainty that Moscow would send tanks, as it had in Hungary in 1956 and Prague in 1968. Gorbachev renounced that guarantee. He did not order the revolutions of 1989; he removed the reason not to attempt them.`,
        `Close the chain with 1989 itself. Poland held semi-free elections in June, Hungary opened its border, East Germans left through it, the Berlin Wall opened on November 9 after a bureaucratic fumble met a crowd, and Czechoslovakia changed governments in weeks. The pattern: economic stall → reform that exposed the stall → withdrawn threat of force → people who had always been unwilling now discovering they were also unstopped. Only Romania ended in bloodshed.`,
      ],
      example: { problem: `Build the causal chain: how did a state that launched the first satellite and matched American missile for missile end up unable to hold its own alliance together by 1989 — without a war being fought over it?`, solution: `A command economy that could not modernize, carrying superpower costs it could not afford, was opened up by reforms that exposed the weakness rather than fixing it — and when Gorbachev withdrew the promise of Soviet tanks, the Eastern European governments that had rested on that promise fell to popular movements within a single year.` },
      relatedLoIds: ['whist.end-of-cold-war'],
    },
    {
      title: 'Worked Gorbachev speech',
      steps: [
        `Read it against the rule it replaced. For twenty years the operating principle in Eastern Europe had been the Brezhnev Doctrine: a Communist government in the bloc could count on Soviet troops if its own people turned against it. "Freedom of choice ... admits of no exceptions" cancels precisely that guarantee.`,
        `Ask who the audience really was. The speech was delivered to the United Nations, but the people who most needed to hear it were in Warsaw, Budapest, East Berlin, and Prague — both the governments relying on the guarantee and the citizens who had learned in 1956 and 1968 what happened without it.`,
        `Notice what the sentence does NOT say. It does not promise elections, it does not dissolve the Warsaw Pact, and it does not predict that Communist governments will lose. Gorbachev appears to have expected reform-minded Communist governments to win a free choice. The words gave away the enforcement mechanism, not the ideology.`,
        `Watch the claim get tested. Within a year, Poland held semi-free elections, Hungary opened its western border, and East Germans massed at the Berlin Wall. The test each time was the same: would Soviet troops move? They did not — and once that was demonstrated in one country, the calculation changed in every other one. Words became credible only after 1989 proved them.`,
        `Weigh it as evidence. This is a leader stating an intention in public, so it is strong evidence about the policy Gorbachev announced and weaker evidence about what he privately expected or how ordinary people felt. Pair it with what happened next: Yugoslavia, where no outside power was withdrawing a guarantee, still fell into war in the 1990s — a reminder that the absence of tanks made peaceful endings possible, not automatic.`,
      ],
      example: { problem: `In a December 1988 speech to the United Nations, Gorbachev told the world (paraphrased): "Freedom of choice is a universal principle that admits of no exceptions. Force and the threat of force can no longer be instruments of foreign policy." Work out what this sentence actually changed — and what it did not say.`, solution: `The speech publicly renounced the Brezhnev Doctrine — the promise of Soviet military force to keep allied Communist governments in power — without promising democracy or predicting those governments would fall; it removed the deterrent that had held Eastern Europe since 1956 and 1968, and the revolutions of 1989 followed once people saw the renunciation was real.` },
      relatedLoIds: ['whist.end-of-cold-war'],
    },
  ],
  pointers: [
    { content: `Outside pressure is one real factor, not the whole story. Historians weigh at least four: Western military and economic pressure in the early 1980s; Gorbachev's own choices from 1985 — glasnost, perestroika, and above all the renunciation of the Brezhnev Doctrine; people power, from Poland's Solidarity to the crowds in Leipzig, Prague, and Moscow during the August 1991 coup; and the long-run economic exhaustion of a command system that could build rockets but not modern consumer or computing industries. Serious accounts use all four and argue about the weighting. Notice also which side actually made the decisive moves: the Wall opened because an Eastern government fumbled its own announcement and no Soviet tanks were sent, not because anyone from outside forced it.`, kind: 'common-error' },
    { content: `The Soviet command economy was strong at concentrated priorities (steel, rockets, warheads) and weak at consumer goods and computers — a stall that deepened through the 1970s and 1980s while superpower costs and the Afghanistan war (1979-1989) drained resources.`, kind: 'tip' },
    { content: `Gorbachev, from 1985, tried to save the system: glasnost opened up speech (Chernobyl, 1986, destroyed the government's credibility) and perestroika dismantled old economic controls without building working replacements.`, kind: 'tip' },
    { content: `The decisive move was abandoning the Brezhnev Doctrine — no more Soviet tanks to prop up allied governments, unlike Hungary (1956) and Czechoslovakia (1968).`, kind: 'tip' },
    { content: `1989 in order: Poland's Solidarity elections (June), Hungary's open border, the Berlin Wall opened November 9, Czechoslovakia's Velvet Revolution under Vaclav Havel, and violence only in Romania; Germany reunified in 1990.`, kind: 'tip' },
    { content: `The USSR itself dissolved on December 25, 1991, after Baltic independence movements and the failed August coup — the Cold War ended without the great-power war everyone had feared, though Yugoslavia's violent breakup (Srebrenica, 1995) shows peaceful endings were an achievement, not a guarantee.`, kind: 'tip' },
    { content: `Don't swap *glasnost* and *perestroika*. Glasnost = openness/speech/censorship; perestroika = restructuring the economy. A sentence about Chernobyl being reported belongs to glasnost; a sentence about private cooperatives and factory autonomy belongs to perestroika.`, kind: 'vocab-note' },
    { content: `The Berlin Wall (Nov 9, 1989) is NOT the end of the USSR. Keep the two dates apart: Wall opens 1989, Germany reunifies October 1990, USSR dissolves December 25, 1991 after the failed August 1991 coup.`, kind: 'common-error' },
    { content: `Gorbachev did not order or intend the 1989 revolutions. Say he *removed the deterrent* — he expected reformed Communist governments to win a free choice. Writing that he 'freed Eastern Europe' credits him with an outcome he did not plan.`, kind: 'gotcha' },
    { content: `Never explain the Cold War's end with one cause. Name at least two of the four — Western pressure, Gorbachev's choices, people power, long-run economic exhaustion — and say how they interact. 'Reagan won it' erases the Soviet and Eastern European actors who did the work.`, kind: 'common-error' },
    { content: `Romania is the violent exception to 1989, and Yugoslavia is a separate case entirely — it broke apart in the 1990s where no outside guarantee was being withdrawn. Don't file Yugoslavia's wars under 'the fall of communism in Eastern Europe, 1989.'`, kind: 'edge-case' },
    { content: `'Command economy was inefficient' is too vague. Specify the split: good at concentrating resources on few state priorities (steel, rockets, Sputnik), bad at variety, quality, and fast-changing tech (shoes, food, cars, computers).`, kind: 'tip' },
    { content: `The Brezhnev Doctrine is a claimed right to intervene militarily to keep allied Communist governments in power — not a general Cold War doctrine and not a treaty. Anchor it to Hungary 1956 and Prague 1968, and to Gorbachev's UN speech of December 1988 renouncing it.`, kind: 'vocab-note' },
    { content: `Afghanistan (1979-1989) drained money, soldiers, and confidence — it did not by itself collapse the USSR. Also remember it killed détente rather than following from it: SALT-era thaw came first, invasion ended it.`, kind: 'gotcha' },
  ],
};
