/**
 * World History — Unit 4 CED 4.3: The Medieval Church & the Crusades.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.hs.whist.church-and-crusades.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_WHIST_U4_CHURCH_AND_CRUSADES: TopicNotesBaseline = {
  baselineId: 'evelyn.hs.whist.church-and-crusades.v1',
  course: 'World History',
  cedUnit: 4,
  cedTopic: '4.3',
  cedTitle: 'The Medieval Church & the Crusades',
  planId: 'evelyn.hs.whist.church-and-crusades.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-08-01',
  sources: [{ type: 'plan', planId: 'evelyn.hs.whist.church-and-crusades.v1' }],
  theory: [
    { loId: 'whist.church-and-crusades', kind: 'framework', title: 'One universal institution', content: `ONE UNIVERSAL INSTITUTION — in a western Europe with no unified state, the Catholic Church was the only organization present in every village from Ireland to Poland, with a single head (the pope), a chain of command (pope, archbishops, bishops, parish priests), and its own courts. Kings ruled patches of land; the Church reached everyone.` },
    { loId: 'whist.church-and-crusades', kind: 'framework', title: 'Cradle to grave, and after', content: `CRADLE TO GRAVE, AND AFTER — the Church's hold was built on the sacraments: baptism, marriage, confession, and last rites marked every stage of a life, and in a society that took eternal punishment literally, the power to withhold them was enormous. EXCOMMUNICATION cut one person off from the sacraments; the INTERDICT suspended them across an entire kingdom, pressuring a ruler by pressuring everyone he governed.` },
    { loId: 'whist.church-and-crusades', kind: 'framework', title: `The Church's power was material too`, content: `THE CHURCH'S POWER WAS MATERIAL TOO — the tithe (a tenth of income, owed by everyone) funded it; canon law, its own legal code, judged marriage, wills, oaths, and clergy in Church courts rather than royal ones; and centuries of donations made the Church the largest landholder in Europe. It was simultaneously a faith, a government, a court system, and a landlord.` },
    { loId: 'whist.church-and-crusades', kind: 'framework', title: 'Latin literacy and the monasteries', content: `LATIN LITERACY AND THE MONASTERIES — nearly everyone who could read and write was a churchman, so kings had to staff their governments with clergy, and Latin served as the shared language of worship, law, scholarship, and diplomacy across dozens of spoken tongues. Monks and nuns following the Benedictine rule copied manuscripts by hand, preserving Roman and Greek texts that would otherwise have been lost, and ran schools, hospitals, and farms. Wealth and royal meddling corrupted many houses, so reform came from inside: the abbey of Cluny, founded in 910 and answering to the pope alone, spread a movement demanding independence from local lords — and that reforming energy is exactly what pushed the popes to confront kings.` },
    { loId: 'whist.church-and-crusades', kind: 'framework', title: 'Church versus crown', content: `CHURCH VERSUS CROWN — THE INVESTITURE CONTROVERSY — who appoints bishops? Bishops held huge estates and troops, so kings had long installed loyal men themselves. Pope Gregory VII banned lay investiture; Emperor Henry IV refused; Gregory excommunicated him in 1076, freeing his nobles from their oaths. Henry crossed the Alps and did public penance at Canossa in 1077 to have it lifted — a political calculation more than a surrender, since the fight resumed and Henry later drove Gregory from Rome. The compromise came in 1122 at the Concordat of Worms: the Church invests bishops with spiritual office, the king with their lands. The lasting lesson is that excommunication was a weapon that worked because obedience to a ruler was itself understood as a religious duty.` },
    { loId: 'whist.church-and-crusades', kind: 'framework', title: 'Why the Crusades began', content: `WHY THE CRUSADES BEGAN — several causes at once, not one. The Seljuk Turks defeated Byzantium badly at Manzikert in 1071 and took most of Anatolia, so Emperor Alexios I asked the pope for western troops — he wanted mercenaries, and got something far larger. At the Council of Clermont in 1095, Pope Urban II called on Christians to recover Jerusalem and promised that those who went would have the penalties for their sins remitted. Add land-hungry younger sons who would inherit nothing, Italian merchants who wanted eastern ports, and a papacy eager to lead a united Christendom and perhaps heal the 1054 split with the Orthodox East.` },
    { loId: 'whist.church-and-crusades', kind: 'framework', title: 'How the Crusades went', content: `HOW THE CRUSADES WENT — the First Crusade captured Jerusalem in 1099 after a brutal siege in which the Muslim and Jewish inhabitants were massacred, and set up small crusader states along the coast. It was the only major military success. Saladin retook Jerusalem in 1187; the Third Crusade (1189–1192) failed to win it back and settled for guaranteed pilgrim access. The Fourth Crusade never reached the Holy Land at all: diverted by Venetian debts and Byzantine politics, it sacked Christian Constantinople in 1204, permanently crippling the empire and hardening the East–West rift. The last mainland crusader stronghold, Acre, fell in 1291.` },
    { loId: 'whist.church-and-crusades', kind: 'framework', title: 'The consequences that actually matter', content: `THE CONSEQUENCES THAT ACTUALLY MATTER — measured by their stated goal the Crusades failed, yet they reshaped Europe. Sustained contact revived trade with the eastern Mediterranean (sugar, spices, silk, cotton, glass, paper) and made Venice and Genoa rich and powerful. Greek philosophy and science, Arabic mathematics, medicine, and astronomy flowed back into European universities, much of it through Muslim Spain and Sicily as well. Kings taxed and organized for war, strengthening royal power, while nobles who mortgaged estates or died abroad weakened the feudal order. Byzantium never recovered from 1204. And the wars left durable bitterness between Christians, Muslims, and Jews — including massacres of Jewish communities in the Rhineland in 1096, before the armies ever left Europe.` },
    { loId: 'whist.church-and-crusades', kind: 'definition', title: 'excommunication', content: `formal exclusion from the sacraments and the community of the Church — spiritually terrifying and, for a ruler, politically dangerous because it released subjects from their duty to obey.` },
    { loId: 'whist.church-and-crusades', kind: 'definition', title: 'lay investiture', content: `the appointment of bishops and abbots by kings or nobles rather than by the Church — the practice at the heart of the struggle between Gregory VII and Henry IV.` },
    { loId: 'whist.church-and-crusades', kind: 'definition', title: 'Crusade', content: `a military campaign called by the papacy, from 1095 onward, aimed chiefly at taking and holding Jerusalem and the surrounding region.` },
  ],
  methods: [
    {
      title: 'Worked causal chain',
      steps: [
        `Start at Manzikert, 1071. The Seljuk Turks crush a Byzantine army and take most of Anatolia — the recruiting ground and breadbasket that had kept Byzantium standing. The empire is suddenly too weak to fix this alone.`,
        `Follow the appeal westward. Emperor Alexios I asks the pope for western fighting men. Note what he requests: hired soldiers under his own command, not an independent army of armed pilgrims with its own goals.`,
        `Follow what the papacy does with the request. At Clermont in 1095, Urban II converts a limited military favor into something far bigger — a call to recover Jerusalem, with the penalties for sin remitted for those who go. The offer answers real anxieties, and it also puts the pope at the head of all of Christendom.`,
        `Follow who answers and why. Knights bound by feudal service, younger sons with no inheritance, and genuine pilgrims all take the cross — and Italian port cities agree to move and supply them, for a price. Tens of thousands travel east, and in 1099 Jerusalem falls to the First Crusade.`,
        `Follow the shipping, not the battles. Two centuries of armies needing transport, food, weapons, and money mean permanent sea lanes between Italy and the eastern Mediterranean. Venice and Genoa build fleets, warehouses, and banking to serve that traffic — and keep trading long after the fighting stops.`,
        `Follow what travels on those ships besides cargo. Sugar, spices, cotton, and glass move west, and so do texts: Greek philosophy and science preserved and expanded in the Islamic world, Arabic mathematics, medicine, and astronomy. Translated in centers such as Toledo and Sicily as well as through crusader contact, these books land in the new universities.`,
        `Close the chain, including the irony. A defeat in Anatolia produced an appeal, the appeal produced a holy war, the war failed at its stated goal — and its side effects (trade, cities, ideas) mattered far more than its conquests, while the empire that asked for help was wrecked by the Fourth Crusade in 1204.`,
      ],
      example: { problem: `Build the causal chain: how does a Turkish victory in eastern Anatolia in 1071 end with Venetian merchants growing rich and Greek science arriving in European universities?`, solution: `Manzikert (1071) forced a Byzantine appeal, which Urban II turned into the Crusades (1095); two centuries of supplying those armies built permanent Italian trade networks with the eastern Mediterranean, and along those routes came the Greek and Arabic learning that fed European universities — consequences nobody intended and Byzantium did not survive.` },
      relatedLoIds: ['whist.church-and-crusades'],
    },
    {
      title: 'Worked Clermont source',
      steps: [
        `Source it first. This is a chronicler's report of a speech, written down after the fact by someone who knew the crusade had already been called — so it captures the appeal as people remembered and retold it, which is exactly what makes it useful for asking why they answered.`,
        `Read the first appeal: rescue. "Our brothers in the East cry out for help" frames the war as defensive aid to fellow Christians under attack — an answer to the Byzantine request, and a claim that responds to duty rather than ambition.`,
        `Read the second appeal: redirection. "Those who once fought their own countrymen for plunder" is a direct comment on Europe's own problem — knights raiding each other constantly. The Church had already tried to limit that violence through the Peace and Truce of God; here it proposes exporting the violence instead.`,
        `Read the third appeal, and the strongest one: salvation. The promise that the penalty for sins would be remitted speaks to a society that took judgment after death literally. For a knight whose profession involved killing, this reframed his exact skill set as a route to salvation.`,
        `Notice the motives the passage does not mention. Nothing here about land for landless younger sons, plunder, Italian merchants seeking eastern ports, or the papacy's interest in leading a united Christendom and healing the 1054 split with the Orthodox Church. A source can be accurate about what it says and still be incomplete.`,
        `Weigh it as evidence. Use this to explain the appeal's persuasive power — duty, an outlet for warriors, and salvation combined — but not as a full account of causes, and not as proof of what any individual crusader personally believed.`,
      ],
      example: { problem: `A chronicler recorded Pope Urban II's appeal at Clermont in 1095 (paraphrased): "Our brothers in the East cry out for help, for the Turks have overrun their lands; let those who once fought their own countrymen for plunder now fight a war worth fighting, and whoever dies on the road shall have his sins' penalty remitted." Work out what this short account reveals about why the First Crusade drew so many people.`, solution: `The appeal worked by stacking three motives at once — defending eastern Christians, redirecting Europe's knightly violence outward, and offering remission of sin's penalty to a society that feared judgment — while saying nothing about the land hunger, merchant profit, and papal ambition that historians count among the causes too.` },
      relatedLoIds: ['whist.church-and-crusades'],
    },
  ],
  pointers: [
    { content: `Christendom was not one side. The Catholic West and Orthodox East had split in 1054 and distrusted each other from the start; Alexios I had asked for hired soldiers under his own command and instead received independent armies with their own aims. The clearest evidence is the Fourth Crusade: entangled in Venetian debts and Byzantine succession politics, it never reached the Holy Land and instead besieged and sacked Constantinople — a Christian capital — in 1204, carrying off its wealth and relics. Byzantium was retaken by Greek rulers in 1261 but never recovered its strength, and the sack deepened the East–West rift for centuries. Crusading violence also struck non-combatants inside Europe, including massacres of Jewish communities in the Rhineland in 1096. So: the Crusades did not protect Byzantium — they helped destroy it.`, kind: 'common-error' },
    { content: `The Church was medieval Europe's one universal institution: sacraments from cradle to grave, the tithe, canon law and its own courts, a near-monopoly on Latin literacy, and monasteries preserving manuscripts — reformed from within by Cluny (founded 910).`, kind: 'tip' },
    { content: `The investiture controversy pitted Gregory VII against Henry IV over who appoints bishops: excommunication in 1076 freed Henry's nobles from their oaths, forcing his penance at Canossa in 1077; the Concordat of Worms split the difference in 1122.`, kind: 'tip' },
    { content: `The Crusades had stacked causes: the Byzantine appeal after Manzikert (1071), Urban II's call at Clermont (1095) with remission of sin's penalty, landless knights, and merchants seeking eastern ports.`, kind: 'tip' },
    { content: `Militarily they mostly failed — Jerusalem taken in 1099 and lost in 1187, and the Fourth Crusade sacked Christian Constantinople in 1204 instead, crippling Byzantium and deepening the East–West rift.`, kind: 'tip' },
    { content: `The consequences that lasted were unintended: trade revival with the eastern Mediterranean, the rise of Venice and Genoa, Greek and Arabic learning flowing into European universities, stronger kings and weaker nobles — and enduring bitterness among Christians, Muslims, and Jews.`, kind: 'tip' },
    { content: `Don't use *excommunication* and *interdict* interchangeably. Excommunication cuts off **one person**; an interdict suspends the sacraments across **a whole territory**, squeezing a ruler by punishing everyone he governs.`, kind: 'vocab-note' },
    { content: `Canossa (1077) was not a surrender. Henry IV did penance to get the excommunication lifted, then resumed the fight and later drove Gregory VII from Rome. Write it as a political calculation, not 'the pope defeated the emperor.'`, kind: 'common-error' },
    { content: `Excommunication worked against Henry IV because it **released his vassals from their oaths** — not because he personally feared hell. Obedience to a ruler was itself a religious duty, so the weapon was political as well as spiritual.`, kind: 'gotcha' },
    { content: `*Lay investiture* means a **king or noble** appointing a bishop or abbot — 'lay' = not clergy. It doesn't mean 'laying hands on' or ordination. The Concordat of Worms (1122) split it: spiritual office from the Church, lands from the king.`, kind: 'vocab-note' },
    { content: `Alexios I asked for **hired soldiers under his own command**, not a holy war. Urban II converted a limited military request into a call to retake Jerusalem. Keep the request and the response distinct in any causal chain.`, kind: 'gotcha' },
    { content: `Never write 'Christendom' as one side. The 1054 schism split Catholic West from Orthodox East, and the Fourth Crusade sacked Christian Constantinople in 1204. Crusader violence also hit Jewish communities in the Rhineland in 1096 — inside Europe.`, kind: 'common-error' },
    { content: `'The Crusades failed' and 'the Crusades were a turning point' are both true — state the goal you're measuring. Militarily they lost Jerusalem; their lasting effects (Italian trade, Greek and Arabic learning, stronger kings) were unintended side effects.`, kind: 'tip' },
    { content: `Urban's Clermont appeal is a chronicler's later paraphrase, and it names only rescue, redirected knightly violence, and remission of sin's penalty. It says nothing about landless younger sons or Italian merchants — accurate isn't the same as complete.`, kind: 'edge-case' },
  ],
};
