/**
 * World History — Unit 8 CED 8.2: Industrial Society & Reform Movements.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.hs.whist.industrial-society-reform.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_WHIST_U8_INDUSTRIAL_SOCIETY_REFORM: TopicNotesBaseline = {
  baselineId: 'evelyn.hs.whist.industrial-society-reform.v1',
  course: 'World History',
  cedUnit: 8,
  cedTopic: '8.2',
  cedTitle: 'Industrial Society & Reform Movements',
  planId: 'evelyn.hs.whist.industrial-society-reform.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-08-01',
  sources: [{ type: 'plan', planId: 'evelyn.hs.whist.industrial-society-reform.v1' }],
  theory: [
    { loId: 'whist.industrial-society-reform', kind: 'framework', title: 'A new class map', content: `A NEW CLASS MAP — industrial society reorganized people not by birth rank but by their relationship to capital: an industrial MIDDLE CLASS that owned the factories, mines, banks, and shops, and a far larger WORKING CLASS that owned nothing to sell but its own labor, priced by the hour. The old landed aristocracy did not vanish, but wealth and political weight steadily shifted toward manufacturers.` },
    { loId: 'whist.industrial-society-reform', kind: 'framework', title: 'Who actually worked the machines', content: `WHO ACTUALLY WORKED THE MACHINES — women and children were employed heavily because they could be paid far less. A British parliamentary committee investigating the mines reported in 1842 that children were working underground hauling coal, some from a very young age, in passages too low for adults. Its findings shocked a public that had not seen the work with its own eyes — the report itself became the argument.` },
    { loId: 'whist.industrial-society-reform', kind: 'framework', title: 'The double burden', content: `THE DOUBLE BURDEN — factory work pulled wage labor out of the home, but housework did not follow it out. Working-class women commonly did a full mill shift AND the cooking, laundry, childcare, and water-hauling in crowded housing without plumbing. Meanwhile, middle-class households increasingly treated a wife's staying out of paid work as the marker of respectability — one industrial economy, two very different female experiences.` },
    { loId: 'whist.industrial-society-reform', kind: 'framework', title: 'Answer one', content: `ANSWER ONE — LAISSEZ-FAIRE: leave it alone. Economic liberals argued that markets left free of interference coordinate themselves through self-interest, and that wage laws or hour limits would only destroy jobs. Adam Smith was invoked constantly, often past what he actually wrote — he had also argued for public works and schooling. Thomas Malthus (population outruns food) and David Ricardo (wages tend back down to subsistence) supplied the pessimism: suffering was a law of nature, and charity or regulation only postponed it.` },
    { loId: 'whist.industrial-society-reform', kind: 'framework', title: 'Answer two', content: `ANSWER TWO — REFORM FROM ABOVE: use the state, but keep the system. Britain passed the Factory Act of 1833, which mattered less for its hour limits than for creating a small corps of PAID GOVERNMENT INSPECTORS — for the first time, the law could actually be checked. The Mines Act of 1842 barred women and young children from underground work; the Ten Hours Act of 1847 capped the working day for women and youths in textile mills; later education acts pushed toward schooling for all children, producing the first mass literate publics.` },
    { loId: 'whist.industrial-society-reform', kind: 'framework', title: 'Answer three', content: `ANSWER THREE — PUBLIC HEALTH: Edwin Chadwick's 1842 sanitary report argued that filth and disease were not just cruel but EXPENSIVE, since sick workers cost employers and taxpayers money. Cholera epidemics helped, in a grim way, because contaminated water crossed class lines. In 1854 the London physician John Snow mapped cholera deaths street by street and found them clustered around a single public water pump — evidence that the disease traveled in water, not bad air, and a decisive argument for spending public money on sewers and clean supply.` },
    { loId: 'whist.industrial-society-reform', kind: 'framework', title: 'Answer four', content: `ANSWER FOUR — WORKERS ORGANIZE: British Combination Acts had made workers' associations illegal in the early 1800s; unions were built anyway, gained legal footing over decades, and won solid legal protection in the 1870s. Their leverage was simple and new: one worker was replaceable, but ALL the workers stopping at once shut down machinery that cost a fortune to sit idle. The strike converted numbers into bargaining power.` },
    { loId: 'whist.industrial-society-reform', kind: 'framework', title: 'Answer five', content: `ANSWER FIVE — SOCIALISM, IN TWO FLAVORS: the "utopian" socialists tried to build the alternative and show it worked — Robert Owen ran his New Lanark mill in Scotland with shorter hours, no young children, decent housing, and a school, then promoted planned cooperative communities. Karl Marx and Friedrich Engels rejected persuasion: their Communist Manifesto (1848) argued that all history is a struggle between classes, that industry had simplified it to owners versus workers, and that the workers would eventually overthrow the system rather than be granted relief from it. Marx expected that revolution in the MOST industrial countries; the revolutions carried out in his name came instead in largely agrarian Russia (1917) and China (1949) — a puzzle Units 9 and 10 take up.` },
    { loId: 'whist.industrial-society-reform', kind: 'framework', title: 'Reform is not the same as socialism', content: `REFORM IS NOT THE SAME AS SOCIALISM — and the toolkit outlives both. Factory acts and sewers were designed to STABILIZE industrial capitalism; socialism proposed to replace it. What the era standardized was a method of pressure: mass petitions, boycotts, investigative reports, public meetings, and pamphlets. The campaign that ended slavery in the British Empire in 1833 refined that method; women's rights organizers used it (the Seneca Falls convention of 1848 is an early marker in the United States), and so did later suffrage, labor, and civil-rights movements everywhere.` },
    { loId: 'whist.industrial-society-reform', kind: 'definition', title: 'laissez-faire', content: `the view that the economy works best when government leaves markets and employers largely alone.` },
    { loId: 'whist.industrial-society-reform', kind: 'definition', title: 'trade union', content: `an organization of workers that bargains collectively over wages, hours, and conditions, with the strike as its ultimate leverage.` },
    { loId: 'whist.industrial-society-reform', kind: 'definition', title: 'proletariat', content: `Marx's term for the industrial working class — people who own no productive property and live by selling their labor.` },
  ],
  methods: [
    {
      title: 'Worked how Britain started regulating',
      steps: [
        `Start with visibility. Conditions inside mills and mines were invisible to the voting public until parliamentary committees went and asked. The 1842 mines committee reporting children hauling coal underground did something no speech could: it made the cost of cheap coal concrete, in testimony, to people who had never been down a shaft.`,
        `Follow the outrage into law — but notice WHICH law worked. Earlier child-labor rules existed and were widely ignored, because nobody checked. The Factory Act of 1833 added paid inspectors, and the Mines Act of 1842 followed the report directly. Enforcement, not good intentions, is the hinge.`,
        `Add the disease argument, which converted opponents. Chadwick argued in 1842 that filth was a financial drain, not merely a moral scandal — an argument aimed straight at ratepayers. Then cholera crossed into respectable neighborhoods, and self-interest and reform pointed the same way.`,
        `Add proof. Snow's 1854 map tied cholera deaths to one water pump, turning sanitation from a matter of opinion into a matter of evidence. Public money for water and sewers now had a demonstrable payoff.`,
        `Now close the chain and note the trick in it. Each measure was sold as a narrow exception for people presumed unable to bargain for themselves — children, women underground, the water everyone drinks. But exceptions accumulated: inspectors, hour limits, sanitary boards, school acts. Investigate, publicize, legislate, ENFORCE — that sequence built the modern regulatory state without anyone announcing they were building it.`,
      ],
      example: { problem: `In 1830 the ruling opinion in Britain was that government had no business telling a factory owner how to run his mill. Within about forty years Britain was inspecting factories, banning children from the mines, and spending public money on sewers. Build the causal chain that got a laissez-faire country to regulate itself.`, solution: `Investigation made conditions public, public outrage produced laws, inspectors made the laws real, and the shared threat of disease plus hard evidence justified public spending — a chain of narrow exceptions that added up to systematic regulation.` },
      relatedLoIds: ['whist.industrial-society-reform'],
    },
    {
      title: 'Worked manifesto paraphrase',
      steps: [
        `Source it first. This is Marx and Engels in the Communist Manifesto (1848) — a political program written to persuade, not a neutral description of conditions. Read it as one competing answer among several, and check its claims against evidence rather than accepting or dismissing it on reputation.`,
        `Identify the claims. Three of them: (1) conflict between classes is the ENGINE of history, not an occasional breakdown; (2) industry has simplified older, layered hierarchies into a two-camp structure, owners versus workers; (3) the workers therefore have no stake in preserving the arrangement — the "chains" line is a claim about interest, not just a slogan.`,
        `Contrast with the reformers working at the same moment. The Ten Hours Act passed in 1847, one year before this pamphlet. Reformers accepted the factory system and tried to make it survivable; the Manifesto argues that improvements granted from above leave the underlying ownership of the machines untouched, so the conflict returns. Same conditions, incompatible diagnoses — this is why "reformer" and "socialist" are not synonyms.`,
        `Test the prediction against what happened. Marx expected revolution first where industry was most advanced — Britain, Belgium, Germany. It did not happen there. Industrial Britain went the other route: legal unions, expanding voting rights, factory law, and eventually social insurance. The revolutions made in Marx's name came in largely agrarian Russia (1917) and China (1949), and you will examine why in Units 9 and 10.`,
        `State what the source can and cannot tell you. It is excellent evidence for how industrial conditions were being interpreted in 1848 and for the birth of an ideology that shaped the next century and a half. It is not evidence about what any particular mill actually paid — for that you want the investigative reports, wage records, and testimony.`,
      ],
      example: { problem: `A political pamphlet published by two German writers in 1848 argued, in paraphrase: "The history of every society so far has been the history of struggles between classes. Modern industry has simplified that struggle into two great camps — those who own the factories and those who own only their labor. The workers have nothing to lose but their chains." Analyze what this argument claims, how it differs from the reformers of the same decade, and how its prediction turned out.`, solution: `The Manifesto claims class conflict drives history, that industry reduced it to owners versus workers, and that workers have no stake in the system — a revolutionary alternative to reformers who wanted to make the factory system tolerable. Its prediction misfired geographically: industrial Britain reformed, while revolutions in its name came in agrarian Russia and China.` },
      relatedLoIds: ['whist.industrial-society-reform'],
    },
  ],
  pointers: [
    { content: `They were rival answers, not one movement. Factory and mines acts, sanitary boards, and school acts were written mostly by aristocrats, evangelicals, and middle-class reformers who ACCEPTED private ownership of industry and wanted to make it survivable — several were sold explicitly as ways to protect capitalism from unrest. Socialists argued the opposite: that relief granted from above leaves ownership untouched, so the conflict returns. Unions sit in between — bargaining hard within the system, and often hostile to both the laissez-faire employers and the revolutionaries. Three positions, one set of conditions.`, kind: 'common-error' },
    { content: `Industrial cities remade the class map — an owning middle class and a much larger working class — and ran on the cheap labor of women and children, with working-class women carrying wage work and household work at once.`, kind: 'tip' },
    { content: `Laissez-faire (Smith invoked past what he wrote, plus Malthus and Ricardo) said leave it alone; reform said legislate and INSPECT — the 1833 Factory Act inspectors, the Mines Act of 1842, the Ten Hours Act of 1847, and later education acts.`, kind: 'tip' },
    { content: `Public health turned opinion into evidence: Chadwick's 1842 cost argument, then Snow's 1854 pump map, justified public money for sewers and clean water.`, kind: 'tip' },
    { content: `Unions moved from illegal under the Combination Acts to legally protected in the 1870s; the strike turned worker numbers into bargaining power.`, kind: 'tip' },
    { content: `Socialism had two flavors: Owen's New Lanark and the utopian communities tried to demonstrate an alternative; Marx and Engels's Manifesto (1848) predicted revolution instead — which arrived in agrarian Russia and China, not industrial Britain.`, kind: 'tip' },
    { content: `Reform is not socialism, and the toolkit outlasted both: petitions, boycotts, investigative reports, and mass meetings — refined in the campaign that abolished slavery in the British Empire in 1833 and reused by women's rights organizers (Seneca Falls, 1848) and every movement after.`, kind: 'tip' },
    { content: `Don't call every 1800s worker advocate a socialist. Factory Acts, sanitary boards, and school acts were mostly written by aristocrats, evangelicals, and middle-class reformers who ACCEPTED private ownership — several sold reform as insurance against revolution. Reform ≠ socialism.`, kind: 'common-error' },
    { content: `When asked why the 1833 Factory Act mattered, don't lead with the hour limits — earlier child-labor rules existed and were ignored. The answer is PAID INSPECTORS: enforcement, not intention, is the hinge.`, kind: 'gotcha' },
    { content: `Adam Smith is not a synonym for 'no government ever.' He also argued for public works and schooling. Say that laissez-faire advocates *invoked* Smith, often past what he wrote — and that the pessimism came from Malthus (population) and Ricardo (subsistence wages).`, kind: 'vocab-note' },
    { content: `Marx's prediction misfired *geographically*, not entirely. Industrial Britain reformed (unions, votes, factory law); revolutions in his name came in agrarian Russia (1917) and China (1949). Don't write 'Marx was right' or 'Marx was wrong' — specify what missed.`, kind: 'edge-case' },
    { content: `'Proletariat' means people who own no productive property and live by selling labor — not simply 'poor people.' Peasants and artisans who own land or tools are not proletarians in Marx's sense. The new class map sorts by relationship to capital, not by income.`, kind: 'vocab-note' },
    { content: `'Working-class women' and 'middle-class women' are not one story. Working-class women did a mill shift PLUS all household labor in housing without plumbing; middle-class respectability meant a wife staying out of paid work. One economy, two opposite experiences.`, kind: 'common-error' },
    { content: `Snow's 1854 pump map mattered because it converted sanitation from opinion into EVIDENCE (water, not bad air). Chadwick's 1842 report is the separate move — the cost argument aimed at ratepayers. Don't merge the two men or the two dates.`, kind: 'gotcha' },
    { content: `Treat the Communist Manifesto as a persuasive political program, not a neutral description of factory conditions. It's strong evidence for how 1848 interpreted industry; for actual wages and hours, cite investigative reports and testimony instead.`, kind: 'tip' },
  ],
};
