import type { Passage } from '../types';

/**
 * ACT Form A (mock exam) — Reading section, 4 original shared passages.
 * ORIGINAL content authored for this mock; not derived from any released
 * ACT test. Passage 4 is a paired passage (Passage A / Passage B inside
 * fullText) supporting act.paired-passages items.
 */
export const ACT_MOCK_A_READING_PASSAGES: Passage[] = [
  {
    id: 'evelyn.passage.act-mock-a-reading-1.v1',
    title: 'The Shelf of Failures',
    author: 'Evelyn (original)',
    year: 2026,
    sourceUrl: 'internal:act-mock-a',
    license: 'internal-original',
    genre: 'fiction',
    fullText:
      `Ines had been sweeping the floor of Solano's bindery for three months before Mr. Solano let her touch a book that wasn't already ruined. The one he handed her that October afternoon was a ledger from a shipping company, its spine cracked clean through, its pages loose as a fan of playing cards. "Small mistakes here don't show," he said, setting a bone folder in her palm. "Big mistakes show for a hundred years. Learn the difference before you decide which kind you're willing to make."\n\n` +
      `She had come to the bindery the way most of the apprentices did, sideways. Her mother wanted her to finish the accounting certificate at the community college and take the front-desk job that was, everyone agreed, already half promised to her. Ines had taken the job at Solano's instead, for a summer, to save money for textbooks she never bought. The summer became a year. She told herself, and occasionally her mother, that it was temporary.\n\n` +
      `The ledger took her four attempts. The first time, she trimmed the new spine cloth crooked and had to peel it back before the glue set, tearing a thread of the old leather beneath it. The second time, she rushed the pressing and the boards dried warped, so that the whole book sat on the table like it was trying to close itself. Mr. Solano did not offer to fix her mistakes. He set the ruined attempts on a shelf behind the register, in view of the workbench, where she could see them every day she came back to try again.\n\n` +
      `"Why do you keep them out?" she finally asked, on the afternoon of the third failure, when she was tired enough to ask questions she normally would have swallowed.\n\n` +
      `"Because the day you stop looking at them is the day you stop learning anything," he said. "I kept my own first ten years on a shelf in the back room until the shop got too small for the shelf. Then I kept photographs instead."\n\n` +
      `She had not thought of him as someone who failed. He moved through the shop with the unhurried certainty of a man who had never doubted where his hands should go, folding endsheets and pasting headbands as if his fingers had memorized the motions before he was born. It had not occurred to her that certainty might be something built rather than something given, one botched spine at a time, on a shelf where you could not pretend it away.\n\n` +
      `The fourth attempt, she slowed down. She measured the cloth twice before cutting it, checked the grain direction against the light the way he had shown her, and let the glue rest exactly as long as the humidity in the shop demanded rather than as long as her patience allowed. When she finally set the ledger under the press, she did not know if it had worked. She only knew that for the first time, she had not been racing to finish before the mistake could catch up to her.\n\n` +
      `It took two days for the boards to fully dry. When she pulled the ledger from the press on the third morning, the spine sat flat and square, the cloth taut without a single pucker, the corners crisp as folded paper. She ran her thumb along the joint the way she had seen Mr. Solano do a hundred times, testing for the give of a hinge that would open freely for another century of use.\n\n` +
      `He examined it under the lamp for a long moment without speaking, turning it once, twice, opening the cover to check the pastedown before closing it again. Then he set it on the shelf with the shipping company's other restored ledgers, not the shelf of failures behind the register.\n\n` +
      `"You'll bind worse than that again," he told her, not unkindly. "Everyone does, even after they've bound better. That's not the part that matters." He nodded toward the shelf of failed attempts, still sitting where she could see them from the bench. "The part that matters is that you're the kind of person who leaves the evidence out where you'll have to look at it. Most people take it down the first chance they get."\n\n` +
      `Ines did not tell her mother that week about the ledger, or about the shelf, or about the accounting certificate she had quietly let lapse. But that night, walking home past the community college with its dark windows, she found she was no longer rehearsing the explanation she had been carrying around for months. She was thinking instead about the grain of the cloth, and the exact weight a hinge should carry before it was asked to open.`,
    lineNumbered: false,
    wordCount: 784,
  },
  {
    id: 'evelyn.passage.act-mock-a-reading-2.v1',
    title: 'Land Apart: The Community Land Trust Model',
    author: 'Evelyn (original)',
    year: 2026,
    sourceUrl: 'internal:act-mock-a',
    license: 'internal-original',
    genre: 'informational',
    fullText:
      `In most American housing markets, land and the buildings on it are sold together, as a single package, to a single buyer. A community land trust, or CLT, breaks that package apart. A nonprofit organization governed by residents, local officials, and other community members acquires land and holds it permanently, while individual families buy only the homes built on that land. Because the land itself is removed from the speculative market, the price of the home drops sharply, sometimes by thirty percent or more compared to a nearby house with land included. When the homeowner later sells, a resale formula—typically written into a ninety-nine-year ground lease—caps how much the price can rise, so the home remains affordable to the next buyer rather than being sold at whatever the open market will bear.\n\n` +
      `The model traces its roots to a set of rural land reform movements of the mid-twentieth century, but it took its now-familiar suburban and urban form in the 1980s, as cities searching for ways to preserve affordable housing amid rising land values began chartering trusts of their own. Proponents argue that the CLT structure solves a problem that conventional affordable-housing subsidies do not: permanence. A city that spends public money to build a below-market-rate home has no guarantee that the home will remain affordable once it is resold; the first owner may sell at full market price and pocket the appreciation, effectively converting a public subsidy into a private windfall. Because the CLT retains ownership of the land and enforces the resale formula through its lease, the affordability persists through every subsequent sale, not just the first one.\n\n` +
      `Critics of the model, including some economists who otherwise support affordable-housing policy, raise a different concern: wealth building. Homeownership has historically been one of the primary ways American families accumulate assets across generations, and a resale formula that caps appreciation also caps how much equity a CLT homeowner can pass on to their children. A family that buys a market-rate home in a rapidly appreciating neighborhood may see its equity multiply several times over two decades; a family in a CLT home in the same neighborhood, bound by the resale formula, will not. Trust administrators generally respond that this tradeoff is the point rather than a flaw—the formula exists precisely to prevent the kind of appreciation that would price out the next lower-income buyer—but the disagreement reflects two different, and not entirely compatible, goals for affordable housing: keeping homes affordable for the community indefinitely, and helping any individual family build as much wealth as possible.\n\n` +
      `A second, more practical challenge concerns financing. Because CLT homeowners do not own the land beneath their homes, some conventional mortgage lenders have been reluctant to treat the arrangement as ordinary homeownership, worried that a ground lease complicates foreclosure and resale in ways a standard mortgage does not. Trusts have responded by working with government-backed loan programs that now explicitly recognize ground-lease homeownership, and by standardizing lease language across the sector so that lenders can evaluate the risk more easily. Even so, appraisers unfamiliar with the model sometimes undervalue CLT homes, since comparable sales in a given neighborhood are almost always full-market transactions rather than resale-restricted ones.\n\n` +
      `Despite these frictions, the number of community land trusts in the United States has grown substantially since the 1980s, and the model has expanded beyond its original single-family-home focus to include multifamily rental buildings, commercial storefronts, and even agricultural land leased to small farmers. Several cities facing acute affordability pressure have begun capitalizing new trusts directly with public land, reasoning that publicly owned parcels—vacant lots, former school sites, land seized for unpaid taxes—can be converted into permanently affordable housing stock without the trust first having to purchase land at market price, which is typically the largest expense a new trust faces. Whether this approach can be scaled to meaningfully affect regional housing supply, rather than producing a modest number of affordable units at the margins of much larger markets, remains a subject of active debate among housing economists, several of whom note that even the largest CLTs still represent a small fraction of total housing stock in any city where they operate. What is less disputed is that the trusts which do exist have proven durable: decades after the earliest urban CLTs were chartered, the vast majority of their original homes remain both occupied and affordable, a record that few other subsidized housing programs can match.`,
    lineNumbered: false,
    wordCount: 738,
  },
  {
    id: 'evelyn.passage.act-mock-a-reading-3.v1',
    title: 'Setting the Light: Mosaic Restoration in Ravenna',
    author: 'Evelyn (original)',
    year: 2026,
    sourceUrl: 'internal:act-mock-a',
    license: 'internal-original',
    genre: 'informational',
    fullText:
      `The mosaics that cover the interior of several sixth-century churches in Ravenna, Italy, are made of tesserae—small cut pieces of colored glass and stone—set into wet plaster by hand, one at a time, across surfaces that in some buildings exceed a thousand square feet. To stand beneath them today is to see something close to what a worshipper saw fifteen hundred years ago, which is a rarer achievement in the history of art than it might first appear, since most large-scale decorative programs from antiquity have either vanished entirely or survive only as fragments reconstructed from written description. That the Ravenna mosaics survive largely intact owes less to luck than to a continuous, often unglamorous tradition of restoration that has occupied craftspeople for centuries.\n\n` +
      `Restoration of glass mosaic differs in a fundamental way from restoration of panel painting or fresco, and the difference explains much about why the discipline developed its own specialized guild rather than being absorbed into general art conservation. A painting can, in principle, be cleaned or its losses inpainted without removing the original surface; a damaged mosaic section, by contrast, usually cannot be stabilized without lifting the loose tesserae, cleaning and consolidating the plaster bed beneath them, and resetting the same pieces of glass in their original positions—or, where pieces are missing beyond recovery, matching new glass to the color, texture, and even the deliberately irregular tilt of the surrounding original tesserae, since medieval mosaicists set individual pieces at slightly varied angles to catch candlelight and produce a shimmering, non-uniform surface that a mechanically flat repair would betray at a glance.\n\n` +
      `For much of the modern restoration era, that color-matching problem was solved by melting new glass to order in small local furnaces, a practice that kept a handful of glassmaking workshops in business in Ravenna and neighboring Venice for generations and that restorers still rely on today when a historic color can no longer be sourced from salvaged material. The furnaces do not simply reproduce a shade from a swatch; because the original glass was colored with metallic oxides whose proportions were never standardized and whose optical behavior changes with the thickness of the tessera and the angle of the light striking it, matching a new piece convincingly requires testing samples directly against the damaged section, under the same lighting conditions a viewer would experience, before a single new piece is set permanently in plaster.\n\n` +
      `This dependence on direct, in-place judgment has made mosaic restoration resistant to some of the standardization that transformed other conservation fields over the twentieth century. Panel-painting conservators can, and routinely do, draw on chemical analysis of pigment samples to identify an exact historical formulation before treatment begins. Mosaic restorers use analysis too, but the final decision about whether a new tessera reads correctly against its neighbors is still made by eye, on site, by a restorer standing where the original craftsperson once stood—a continuity of method, across fifteen centuries, that some conservators consider not merely a practical necessity but a value worth preserving for its own sake, since it keeps the restorer's judgment embedded in the same physical and visual conditions that shaped the original work.\n\n` +
      `That continuity has not spared the mosaics from the pressures of the modern city. Ravenna sits on ground that has been slowly subsiding for centuries, partly from natural geological settling and partly from decades of groundwater extraction in the surrounding region, and the shifting foundations beneath several of the churches have opened hairline cracks in vaulted ceilings that took mosaicists years to complete. Modern restoration teams now spend as much effort monitoring structural movement with sensors embedded in the walls as they do resetting individual tesserae, on the reasoning that no amount of skilled glasswork can outpace a building that continues to move beneath it. The result is a discipline that has had to absorb structural engineering into a practice historically defined by close, patient handwork, without abandoning the older skill that engineering alone cannot replace: the trained eye that can still tell, at a glance, whether a piece of glass set into plaster this year belongs beside one set there in the sixth century.`,
    lineNumbered: false,
    wordCount: 691,
  },
  {
    id: 'evelyn.passage.act-mock-a-reading-4.v1',
    title: 'What Killed the Megafauna? Two Views',
    author: 'Evelyn (original)',
    year: 2026,
    sourceUrl: 'internal:act-mock-a',
    license: 'internal-original',
    genre: 'informational',
    fullText:
      `Passage A\n\n` +
      `Between roughly 13,000 and 10,000 years ago, North America lost most of its largest mammals: mammoths, mastodons, giant ground sloths, camels, horses, and several species of large predators disappeared within a geologically narrow window. The timing of this wave of extinctions, known collectively as the Pleistocene megafaunal extinction, lines up closely with the arrival and rapid spread of human hunter-gatherers across the continent, and that alignment is the foundation of what researchers call the overkill hypothesis.\n\n` +
      `The case for human-driven extinction rests on more than coincidence of timing. Archaeological sites across North America preserve mammoth and mastodon remains alongside distinctive fluted stone spear points, some still lodged in rib bones or embedded near vertebrae, direct physical evidence that humans were killing the largest animals on the continent during precisely the period those animals vanished. Proponents also point to a broader pattern: on every continent and island chain that humans reached for the first time, a wave of large-animal extinctions followed within a few thousand years of their arrival, regardless of the local climate at the time. Madagascar's giant lemurs and elephant birds survived tens of thousands of years of climate fluctuation without incident, then disappeared within roughly a thousand years of human settlement. Australia's giant marsupials followed a similar pattern tens of thousands of years earlier. If climate alone explained these losses, overkill proponents argue, extinctions should track climate swings independent of when humans showed up on a given landmass; instead, they track human arrival almost everywhere paleontologists have looked closely.\n\n` +
      `Critics of overkill note that human populations in Ice Age North America were almost certainly small and thinly spread, which raises a real question about whether so few hunters, using stone-tipped spears, could have driven tens of millions of large animals to extinction across a continent in a few thousand years. Overkill proponents respond that large mammals reproduce slowly, with long gestation periods and few offspring per year, so even modest, sustained hunting pressure—removing animals faster than slow-breeding populations could replace them—could compound into extinction over centuries without requiring implausibly large hunting parties or kill rates.\n\n` +
      `Passage B\n\n` +
      `An alternative explanation for the Pleistocene megafaunal extinction points not to human hunters but to the climate itself. The extinction window, roughly 13,000 to 10,000 years ago, coincides with the end of the last Ice Age, a period of dramatic and rapid environmental upheaval: glaciers retreated, sea levels rose, and established vegetation zones shifted or vanished as temperatures swung sharply within a span of centuries, including an abrupt millennium-long cold snap known as the Younger Dryas that interrupted the general warming trend. Large mammals adapted to Ice Age steppe and tundra environments would have faced shrinking, fragmenting habitat and disappearing food sources as those environments transformed faster than slow-reproducing populations could adapt or relocate.\n\n` +
      `Climate proponents point out that the North American extinction was not an isolated event but one of several comparable megafaunal die-offs that occurred at the end of previous glacial periods, stretching back hundreds of thousands of years, long before any human hunters were present on the continent. If human predation were the primary driver, they argue, those earlier extinctions at the close of earlier ice ages would be difficult to explain, since no toolmaking hominins were hunting North American mammoths a quarter-million years ago. The recurrence of similar extinction pulses at similar points in the glacial cycle suggests, in this view, a climatic mechanism operating independently of human presence.\n\n` +
      `Overkill proponents counter that the earlier glacial-cycle extinctions climate researchers cite were generally smaller in scale and more gradual than the rapid, near-simultaneous loss of dozens of large species that characterized the terminal Pleistocene event in North America, and that the coincidence with human arrival on this particular occasion remains difficult to dismiss as chance. Most researchers who have reviewed the evidence in recent decades now favor some combination of both mechanisms—climate stress that reduced and fragmented megafaunal populations, compounded by hunting pressure that a healthier, less stressed population might have withstood—over either explanation taken alone, though the two camps continue to disagree sharply about which factor deserves greater weight.`,
    lineNumbered: false,
    wordCount: 684,
  },
];
