/**
 * AP Environmental Science — CED Unit 1.8+1.9+1.10: Primary Productivity,
 * Trophic Levels, and Energy Flow.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U1_PRODUCTIVITY_ENERGY_FLOW: LessonPlan = {
  id: 'evelyn.ap.envsci.productivity-energy-flow.v1', title: 'U1.4 Primary Productivity and Energy Flow',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.productivity-energy-flow', description: 'Define gross primary productivity (GPP) and net primary productivity (NPP). Identify trophic levels (producers, primary/secondary/tertiary consumers, decomposers). Apply the 10% rule to predict energy availability at higher trophic levels.', standard: 'AP-ENVSCI-1.8-1.10' }],
  prerequisites: ['apenvsci.nitrogen-phosphorus-cycles'], followUps: ['apenvsci.food-webs'], estimatedMinutes: 20,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame energy flow as one-way.', script: "Energy flows through ecosystems in ONE DIRECTION — from sun to plants to consumers — and is LOST as heat at every step. About 90% is lost between trophic levels. This is why apex predators are rare.", estimatedMinutes: 2 },
    { id: 'concept-energy', kind: 'concept', goal: 'Cover GPP/NPP, trophic levels, 10% rule.',
      keyIdeas: [
        'PRIMARY PRODUCTIVITY: rate at which producers capture solar energy (or chemical energy in chemosynthesis) into biomass.',
        '  • GROSS PRIMARY PRODUCTIVITY (GPP): TOTAL energy captured by photosynthesis.',
        '  • NET PRIMARY PRODUCTIVITY (NPP) = GPP − Respiration. Energy AVAILABLE to consumers (after producers use some for their own metabolism).',
        '  • Units: typically kcal/m²/year or g C/m²/year.',
        'PRODUCTIVITY VARIES by biome: tropical rainforests, estuaries, coral reefs HIGHEST. Open ocean and tundra LOWEST (per area). But OPEN OCEAN total NPP is huge because of vast area.',
        'TROPHIC LEVELS — energy flow hierarchy:',
        '  • TROPHIC LEVEL 1 — PRODUCERS (autotrophs): plants, algae, cyanobacteria. Make their own food via photosynthesis (or chemosynthesis at hydrothermal vents).',
        '  • TROPHIC LEVEL 2 — PRIMARY CONSUMERS (herbivores): eat producers. Rabbits, cows, zooplankton.',
        '  • TROPHIC LEVEL 3 — SECONDARY CONSUMERS (carnivores or omnivores): eat primary consumers. Foxes, small fish.',
        '  • TROPHIC LEVEL 4 — TERTIARY CONSUMERS (top carnivores): eat secondary consumers. Hawks, sharks.',
        '  • DECOMPOSERS: bacteria, fungi. Break down dead organic matter; release nutrients back to soil. Operate at all levels.',
        '  • DETRITIVORES: eat detritus (dead matter, leaf litter). Earthworms, vultures, dung beetles.',
        'TEN-PERCENT RULE: only ~10% of the energy at one trophic level is incorporated into biomass at the next level. The other ~90% is LOST as heat (respiration), used for movement/metabolism, or undigested.',
        '  • Consequence: ENERGY PYRAMIDS — much more biomass at producer level than at top.',
        '  • Consequence: SHORT food chains. Rare to see > 4-5 trophic levels — not enough energy left.',
        '  • Consequence: EATING LOWER on the food chain (vegetarian) is more energy-efficient. Producing 1 kg beef requires ~10 kg plant feed.',
        'EXAMPLE: 10,000 kcal of plants → 1,000 kcal in herbivores → 100 kcal in carnivores → 10 kcal in top predators.',
        'PYRAMID OF NUMBERS / BIOMASS: at any moment, more producer individuals/biomass than consumers above. EXCEPTION: parasitic pyramids can invert (one tree, many caterpillars).',
      ],
      vocabulary: [
        { term: 'GPP', definition: 'gross primary productivity — total energy captured by photosynthesis.' },
        { term: 'NPP', definition: 'net primary productivity = GPP − respiration; available to consumers.' },
        { term: '10% rule', definition: 'only ~10% of energy passes from one trophic level to the next.' },
      ],
      estimatedMinutes: 6 },
    { id: 'worked-pyramid', kind: 'worked_example',
      problem: 'A grassland ecosystem has producers with NPP of 50,000 kcal/m²/yr. Estimate the energy available to: (a) primary consumers, (b) secondary consumers, (c) tertiary consumers.',
      steps: [
        'STEP 1 — Apply the 10% rule at each step.',
        'STEP 2 — Producers: 50,000 kcal/m²/yr (given as NPP).',
        'STEP 3 — (a) Primary consumers: 50,000 × 0.10 = 5,000 kcal/m²/yr.',
        'STEP 4 — (b) Secondary consumers: 5,000 × 0.10 = 500 kcal/m²/yr.',
        'STEP 5 — (c) Tertiary consumers: 500 × 0.10 = 50 kcal/m²/yr.',
        'STEP 6 — From 50,000 to 50: a 1000-fold reduction. Why apex predators are rare and need large territories.',
      ],
      answer: '(a) 5,000 kcal/m²/yr. (b) 500. (c) 50.', estimatedMinutes: 4 },
    { id: 'try-gpp-npp', kind: 'try_yourself',
      problem: 'A forest has GPP = 30,000 kcal/m²/yr. Producers use 18,000 kcal/m²/yr for respiration. (a) Compute NPP. (b) Why does NPP matter more than GPP for consumers?',
      expectedAnswer: '(a) NPP = GPP − Respiration = 30,000 − 18,000 = 12,000 kcal/m²/yr. \n(b) NPP is what\'s LEFT OVER after producers meet their own needs — the energy actually AVAILABLE to consumers (or accumulating as biomass). GPP includes energy producers will use themselves and never pass on.',
      responseFormat: 'numeric', hints: ['NPP = GPP − R; NPP is the consumer-relevant quantity.'], estimatedMinutes: 3 },
    { id: 'try-trophic-level', kind: 'try_yourself',
      problem: 'For each, identify the trophic level: (a) phytoplankton, (b) shrimp eating phytoplankton, (c) tuna eating shrimp, (d) shark eating tuna, (e) fungi decomposing a dead shark.',
      expectedAnswer: '(a) Producer (level 1). (b) Primary consumer (level 2). (c) Secondary consumer (level 3). (d) Tertiary consumer (level 4). (e) Decomposer.',
      responseFormat: 'free', hints: ['Producer → primary → secondary → tertiary; decomposers separate.'], estimatedMinutes: 2 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. A vegetarian diet is often called more "energy-efficient" than a meat-based diet. (a) Use the 10% rule to explain why. (b) If 1 hectare of land yields 5000 kcal of plant food per year, how much energy reaches a human eating that plant directly vs eating an animal that ate the plant? (c) Suggest a sustainability implication.',
      expectedAnswer: '(a) Each trophic level loses ~90% of incoming energy as heat. Eating plants directly (level 2) skips a level vs eating animals (level 3+). More of the original solar energy reaches you. (1.5)\n(b) DIRECT (vegetarian): human at level 2. Energy = 5000 × 0.10 = 500 kcal. EATING AN ANIMAL (carnivore at level 3): human at level 3. Energy = 5000 × 0.10 × 0.10 = 50 kcal. Vegetarian gets 10× more energy from the same land. (2)\n(c) Sustainability: producing meat requires ~10× more land/water/energy per kcal of food than plant-based diets. Plant-based diets reduce environmental footprint per person fed. Land freed could be used for restoration, more crops, or carbon sequestration. (1.5)\nTotal: 5 points.',
      responseFormat: 'frq', hints: ['Energy efficiency; arithmetic with 10% rule; food-system land use.'], estimatedMinutes: 4 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'GPP = total energy captured. NPP = GPP − respiration.',
      'Trophic levels: producer → primary → secondary → tertiary; decomposers process all.',
      '10% rule: ~90% of energy lost between levels (heat, metabolism, undigested).',
      'Energy pyramids → short food chains → vegetarian diets more efficient.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '1', cedTopic: '1.8-1.10', cedTitle: 'Productivity and Energy Flow', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '3', note: 'Standard productivity + 10% rule.' }] },
};
