/**
 * AP Environmental Science — CED Unit 6.8+6.9+6.10+6.11+6.12: Renewables
 * (Solar, Hydro, Geothermal, Hydrogen, Wind).
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U6_RENEWABLES: LessonPlan = {
  id: 'evelyn.ap.envsci.renewables.v1', title: 'U6.3 Renewable Energy (Solar, Hydro, Wind, Geothermal, Hydrogen)',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.renewables', description: 'Compare renewable energy sources — solar, wind, hydro, geothermal, hydrogen — on energy capture method, environmental impact, scalability.', standard: 'AP-ENVSCI-6.8-6.12' }],
  prerequisites: ['apenvsci.nuclear-biomass'], followUps: ['apenvsci.energy-conservation'], estimatedMinutes: 22,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame the renewable transition.', script: "RENEWABLES grew from 5% of global electricity in 1990 to ~30% in 2024. Solar and wind costs have fallen 80%+ in 15 years. Today: how each captures energy, where it works, and where it doesn\'t.", estimatedMinutes: 2 },
    { id: 'concept-renewables', kind: 'concept', goal: 'Cover solar, wind, hydro, geothermal, hydrogen.',
      keyIdeas: [
        'SOLAR ENERGY:',
        '  • PHOTOVOLTAIC (PV): silicon panels convert sunlight → electricity directly via photoelectric effect.',
        '  • SOLAR THERMAL (CSP): mirrors focus sunlight to heat fluid → steam → turbine.',
        '  • Best in: deserts, sunny regions (SW US, Spain, Australia, Sahara).',
        '  • Pros: zero emissions, modular (rooftop to utility-scale), prices DROPPED 90% since 2010.',
        '  • Cons: INTERMITTENT (no power at night, less in winter), requires storage or backup. Land-intensive at utility scale. Toxic materials in panels (cadmium, lead in some).',
        'WIND ENERGY:',
        '  • Wind turbines convert kinetic energy of wind → rotary motion → electricity (generator).',
        '  • ONSHORE: most common, cheapest. Best in: Great Plains US, Texas Panhandle, Europe coast.',
        '  • OFFSHORE: stronger wind, less land conflict, but expensive (saltwater corrosion, deep-water support).',
        '  • Pros: zero emissions, second-cheapest electricity, scalable.',
        '  • Cons: INTERMITTENT, requires backup. Bird/bat mortality. Visual/noise complaints. Land use (though sheep can graze under turbines).',
        'HYDROELECTRIC POWER:',
        '  • Dams: water released through turbines → electricity. Fast-responsive (good for grid balancing).',
        '  • RUN-OF-RIVER: smaller, no large reservoir. Lower environmental impact.',
        '  • Pros: ~17% of global electricity, mature technology, zero direct emissions.',
        '  • Cons: \n    - Reservoir flooding displaces communities, species.\n    - Sediment trapping → erodes downstream beaches.\n    - Blocks fish migration (salmon).\n    - Drought-vulnerable.\n    - LARGE METHANE emissions from decomposing reservoir vegetation (especially in tropics).\n    - Construction destructive.',
        '  • Examples: Three Gorges (China — largest), Hoover Dam, Itaipu (Brazil/Paraguay).',
        'GEOTHERMAL ENERGY: tap underground heat (volcanic regions, hot springs).',
        '  • DRY STEAM: well drilled into hot underground reservoir; steam directly drives turbine. Geysers, CA.',
        '  • FLASH STEAM: hot pressurized water flashed to steam.',
        '  • BINARY CYCLE: hot water heats secondary fluid (low boiling point); secondary fluid drives turbine. Lower temperature requirement.',
        '  • GEOTHERMAL HEAT PUMPS: residential — uses constant ~12°C ground temperature for heating/cooling. Highly efficient.',
        '  • Best in: Iceland (~25% of electricity), Italy, NZ, geothermal regions of US (CA, NV).',
        '  • Pros: 24/7 reliable, low emissions, small footprint.',
        '  • Cons: location-restricted; subsurface cooling can occur over decades; hydrogen sulfide gas; potential for induced seismicity.',
        'HYDROGEN FUEL:',
        '  • Hydrogen burned (or used in fuel cell) produces ENERGY + water (H₂ + ½O₂ → H₂O + energy). Zero CO₂.',
        '  • PROBLEM: hydrogen must be PRODUCED. Currently ~95% from fossil fuels via steam-methane reforming → emits CO₂.',
        '  • GREEN HYDROGEN: produced via electrolysis using renewable electricity. Truly zero-carbon. Currently ~5% but growing.',
        '  • FUEL CELLS: convert H₂ chemical energy → electrical (no combustion).',
        '  • Pros: high energy density per mass, zero point-of-use emissions.',
        '  • Cons: low energy density per VOLUME (needs compression/liquefaction). Storage/transport challenging. Currently expensive. Hydrogen embrittles materials. Requires NEW infrastructure.',
        '  • Use cases: heavy industry (steel making), trucks, aircraft, shipping (where electric batteries impractical).',
        'INTERMITTENCY PROBLEM:',
        '  • Solar: night, winter.',
        '  • Wind: variable, sometimes still.',
        '  • SOLUTION 1: STORAGE — batteries (lithium-ion), pumped hydro, compressed air.',
        '  • SOLUTION 2: GRID INTEGRATION — large geographic area smooths variability; long-distance transmission.',
        '  • SOLUTION 3: COMPLEMENTARY mix — solar peaks midday, wind often peaks at night.',
        '  • SOLUTION 4: DEMAND-SIDE management — schedule heavy usage when supply is high.',
      ],
      vocabulary: [
        { term: 'photovoltaic', definition: 'PV — solar panels converting light to electricity directly.' },
        { term: 'intermittency', definition: 'variability in renewable output (e.g., solar at night).' },
        { term: 'green hydrogen', definition: 'hydrogen produced via electrolysis using renewable electricity.' },
      ],
      estimatedMinutes: 7 },
    { id: 'worked-region', kind: 'worked_example',
      problem: 'For each region, recommend the most suitable renewable energy source(s) and explain why: (a) Iceland. (b) US Great Plains. (c) Sahara Desert. (d) Norway.',
      steps: [
        '(a) ICELAND: GEOTHERMAL (volcanic terrain, ~25% of electricity already from this) + HYDRO (rivers from glaciers, ~70%). Total: ~100% renewable. Limited solar (high latitude, long winters).',
        '(b) US GREAT PLAINS: WIND. Constant high winds across plains, low population density (no land conflicts), well-developed transmission. Texas, Oklahoma, Iowa, Kansas already lead in wind capacity.',
        '(c) SAHARA: SOLAR (PV or thermal). Constant sunshine, hot/dry climate ideal. Limited water requirement, large land available. Major projects (Noor Solar Complex in Morocco).',
        '(d) NORWAY: HYDROELECTRIC. ~95% of electricity already from hydro. Mountainous terrain, abundant rivers and snowmelt. Limited solar (high latitude).',
      ],
      answer: 'Iceland: geothermal + hydro. Plains: wind. Sahara: solar. Norway: hydro.', estimatedMinutes: 3 },
    { id: 'try-source-tradeoffs', kind: 'try_yourself',
      problem: 'You\'re consulting on energy planning for a small island nation. Compare solar, wind, geothermal, and hydro on: (a) capacity factor (% of time generating), (b) cost trends, (c) environmental impact.',
      expectedAnswer: '(a) CAPACITY FACTOR: Geothermal ~85-90% (high — operates ~24/7). Hydro 30-60% (depends on water availability). Wind 30-45% (offshore higher than onshore). Solar 15-25% (no nighttime). \n(b) COSTS: Solar PV — DROPPED 90% since 2010, currently CHEAPEST new electricity. Wind — DROPPED 70%, second cheapest. Geothermal — moderate cost, regional. Hydro — depends on dam costs; large dams expensive. \n(c) ENVIRONMENTAL IMPACT: \n• Solar: minimal direct, some land use, panel disposal. \n• Wind: minimal direct, some bird/bat impact, visual concerns. \n• Geothermal: minimal direct, emissions of H₂S, induced seismicity. \n• Hydro: REGIONAL impact LARGE (reservoir flooding, fish blockage, sediment).',
      responseFormat: 'free', hints: ['Multi-criteria analysis.'], estimatedMinutes: 4 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. Critics of solar and wind argue they\'re INTERMITTENT and can\'t replace fossil fuels. (a) Why is intermittency a real concern? (b) Suggest THREE solutions to address intermittency. (c) Hydrogen could play a role — explain how green hydrogen storage works.',
      expectedAnswer: '(a) Intermittency concern:\n• Solar: zero generation at night; reduced in winter and cloudy days. \n• Wind: variable from minute to minute, hour to hour. \n• Demand: electricity use is constant (or peaks evening when solar drops); supply must match. \n• Without storage, grid blackouts when supply lags demand. \n• Cannot use as 100% replacement for fossil fuels without addressing this. (2)\n(b) Solutions:\n• ENERGY STORAGE: batteries (lithium-ion increasingly cheap), pumped hydro (most common large-scale), compressed air, thermal. \n• GRID INTEGRATION: large geographic area smooths variability; long-distance HVDC transmission lines. \n• DEMAND-SIDE management: smart appliances, thermal storage, EV charging when supply high. \n• COMPLEMENTARY MIX: solar peaks midday, wind peaks at night (often); diversity smooths supply. \n• BACKUP CAPACITY: gas peaker plants for true emergencies, declining role. \n• DEMAND RESPONSE: large customers reduce usage during peaks. (2)\n(c) GREEN HYDROGEN STORAGE:\n• When excess renewable electricity is available, run ELECTROLYSIS: 2 H₂O → 2 H₂ + O₂.\n• Store hydrogen in tanks, salt caverns, or fuel pipelines.\n• When electricity is needed: H₂ + O₂ → H₂O + ENERGY (via fuel cell or combustion).\n• Net: stores excess renewable electricity in chemical form for hours, days, or seasons.\n• Currently EXPENSIVE — round-trip efficiency only ~30-40%. But scalable as renewables get cheaper. (2)\nTotal: 6 points.',
      responseFormat: 'frq', hints: ['Mechanism, multi-strategy, hydrogen role.'], estimatedMinutes: 5 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Solar: PV (cheapest), thermal. Best in deserts.',
      'Wind: onshore (cheap) vs offshore (stronger). Best in plains, coast.',
      'Hydro: 17% globally, but reservoir + fish + methane impacts.',
      'Geothermal: 24/7 baseload in volcanic regions.',
      'Hydrogen: storage carrier; green H₂ from electrolysis.',
      'Intermittency: solved by storage, grid, demand management, complementary mix.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '6', cedTopic: '6.8-6.12', cedTitle: 'Renewable Energy', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '16', note: 'Standard renewables.' }] },
};
