/**
 * AP Environmental Science — CED Unit 6.6+6.7: Nuclear Power and Biomass.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U6_NUCLEAR_BIOMASS: LessonPlan = {
  id: 'evelyn.ap.envsci.nuclear-biomass.v1', title: 'U6.2 Nuclear and Biomass',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.nuclear-biomass', description: 'Describe nuclear fission and reactor operation. Identify advantages and risks of nuclear power. Distinguish biomass types and their environmental trade-offs.', standard: 'AP-ENVSCI-6.6-6.7' }],
  prerequisites: ['apenvsci.energy-overview-fossil'], followUps: ['apenvsci.solar-wind-hydro'], estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame nuclear and biomass.', script: "Two unusual energy sources: NUCLEAR (uranium fission, no CO₂) and BIOMASS (plant material burned for energy). One is feared for its waste; the other is renewable in theory but has hidden costs. Today: how each works and what they trade off.", estimatedMinutes: 2 },
    { id: 'concept-nuclear-biomass', kind: 'concept', goal: 'Cover nuclear fission, accidents, biomass.',
      keyIdeas: [
        'NUCLEAR FISSION: heavy atom (uranium-235 typical) is split by absorbing a neutron → smaller atoms + 2-3 neutrons + ENERGY (heat).',
        '  • Chain reaction: released neutrons split more U-235.',
        '  • Controlled by control rods (boron, cadmium absorb neutrons).',
        '  • Released heat used to boil water → steam → turbine → electricity.',
        'NUCLEAR REACTOR COMPONENTS:',
        '  • FUEL ROD: enriched uranium (3-5% U-235; natural is 0.7%).',
        '  • CONTROL RODS: regulate reaction by absorbing neutrons. Lowered to slow; raised to speed up.',
        '  • COOLANT: water (most common) carries heat away.',
        '  • MODERATOR: slows neutrons (water in light-water reactors).',
        '  • CONTAINMENT VESSEL: thick concrete + steel, prevents radiation escape.',
        '  • Generates ~20% of US electricity, ~10% globally. Produces zero direct CO₂.',
        'NUCLEAR ADVANTAGES:',
        '  • NO CO₂ EMISSIONS during operation.',
        '  • HIGH ENERGY DENSITY (1 kg uranium ~ 3M kg coal).',
        '  • Reliable BASE-LOAD power (operates 24/7).',
        '  • Limited air pollution.',
        '  • Small land footprint.',
        'NUCLEAR DISADVANTAGES:',
        '  • RADIOACTIVE WASTE: highly hazardous for thousands of years. No permanent disposal site (Yucca Mountain politically blocked).',
        '  • CATASTROPHIC ACCIDENT POTENTIAL: \n    - THREE MILE ISLAND (1979, US): partial meltdown; minimal radiation released. \n    - CHERNOBYL (1986, USSR/Ukraine): full meltdown after operator error + design flaw. ~50 immediate deaths; 4,000+ thyroid cancer cases; 20-mile Exclusion Zone uninhabitable today. \n    - FUKUSHIMA (2011, Japan): tsunami flooded reactors → 3 meltdowns. Required mass evacuation; ongoing cleanup ~$400 billion.',
        '  • COSTLY: nuclear plants cost $5-15 billion to build. Long lead times (10-20 years).',
        '  • PROLIFERATION RISK: enriched uranium can be used for weapons.',
        '  • THERMAL POLLUTION: cooling water discharged warm, harming aquatic life.',
        '  • Decommissioning takes decades and is expensive.',
        'BIOMASS ENERGY: burning plant or animal material for heat or electricity.',
        '  • Sources: wood, agricultural residues (corn stover), animal manure (methane), garbage (waste-to-energy plants), dedicated energy crops.',
        '  • Biomass is RENEWABLE if regrowth replaces what\'s burned.',
        'BIOMASS TYPES:',
        '  • TRADITIONAL (wood, dung): used by ~40% of world\'s population for cooking. Major air pollution; ~3 million premature deaths/year from indoor smoke.',
        '  • MODERN BIOMASS:',
        '    - ETHANOL (corn-based, US; sugarcane, Brazil) — added to gasoline.',
        '    - BIODIESEL (from soy, palm oil) — for diesel engines.',
        '    - WOOD PELLETS — for heating, sometimes for electricity.',
        '    - BIOGAS — methane from anaerobic decomposition (landfills, sewage).',
        'BIOMASS ADVANTAGES:',
        '  • Theoretically CARBON-NEUTRAL (CO₂ released = CO₂ absorbed during growth).',
        '  • Uses WASTE materials (otherwise discarded).',
        '  • Can use existing infrastructure.',
        '  • LOCAL — reduces foreign energy dependence.',
        'BIOMASS DISADVANTAGES:',
        '  • COMPETES WITH FOOD CROPS for land (corn ethanol).',
        '  • DEFORESTATION risk if demand exceeds regrowth.',
        '  • AIR POLLUTION from combustion (often less clean than fossil fuels).',
        '  • LIFECYCLE EMISSIONS not zero — fossil fuels used in agriculture/transport often offset gains.',
        '  • LAND USE CHANGE emissions (clearing forest for biofuel crops).',
      ],
      vocabulary: [
        { term: 'fission', definition: 'splitting heavy atoms (U-235) to release energy.' },
        { term: 'biomass', definition: 'organic material burned for energy.' },
        { term: 'meltdown', definition: 'reactor core overheats and melts; releases radiation.' },
      ],
      estimatedMinutes: 6 },
    { id: 'worked-disaster', kind: 'worked_example',
      problem: 'Compare the Chernobyl (1986) and Fukushima (2011) nuclear disasters in terms of cause, scale, and ongoing impact.',
      steps: [
        'CAUSE:\n  • CHERNOBYL: human error during a safety test + flawed reactor design (RBMK had positive void coefficient, exacerbating runaway). Operator pushed reactor into unstable state.\n  • FUKUSHIMA: 9.0 earthquake + 14m tsunami exceeded design specs. Tsunami overran sea wall, flooded backup generators → loss of cooling → 3 meltdowns.',
        'SCALE:\n  • CHERNOBYL: full reactor explosion + 10-day fire spreading radioactive plume across Europe. ~30 immediate deaths; estimated 4,000+ thyroid cancer cases over decades.\n  • FUKUSHIMA: 3 reactors melted but containment partially held. ~160,000 evacuated; ongoing cleanup. Health impact mostly from evacuation stress; few direct radiation deaths.',
        'IMPACT:\n  • CHERNOBYL: Exclusion Zone of 1,000 sq miles still uninhabited 40 years later. Wildlife thrives in absence of humans (paradoxically a wildlife refuge).\n  • FUKUSHIMA: Most evacuees still displaced or have not returned. Decommissioning will take ~50 years. Reactor core debris being slowly removed.',
        'BOTH highlighted: \n  • Reactor SAFETY ENGINEERING is critical. \n  • Decisions to evacuate/return are politically/socially complex. \n  • Public confidence in nuclear power damaged for years/decades. \n  • Encouraged shift away from nuclear in some countries (Germany), reconsidered acceptance in others.',
      ],
      answer: 'Chernobyl: human error + design flaw, larger radiation release, 1000 sq mi exclusion. Fukushima: natural disaster, contained but ongoing.', estimatedMinutes: 4 },
    { id: 'try-nuclear-tradeoffs', kind: 'try_yourself',
      problem: 'A country debates whether to expand nuclear power. List three SCIENTIFIC arguments for nuclear and three arguments against. Then state your conclusion based on environmental priorities.',
      expectedAnswer: 'FOR:\n• ZERO DIRECT CO₂ EMISSIONS during operation. \n• HIGH ENERGY DENSITY — small footprint per kWh. \n• Reliable base-load (operates 24/7, unlike intermittent solar/wind). \n• Could replace coal as a low-carbon alternative. \nAGAINST:\n• RADIOACTIVE WASTE management is unresolved. \n• CATASTROPHIC ACCIDENT potential (Chernobyl, Fukushima). \n• HIGH COSTS — billions to build, decades to recover. \n• PROLIFERATION RISK — civilian → military uses. \nCONCLUSION (varies by view):\n• PRO-NUCLEAR: climate change is most urgent; nuclear is necessary bridge to renewable future. \n• ANTI-NUCLEAR: emerging renewables + storage cheaper, safer, faster to deploy. \n• Reasonable disagreement among environmentalists.',
      responseFormat: 'free', hints: ['Multi-faceted analysis; conclusion is value-laden.'], estimatedMinutes: 3 },
    { id: 'try-biomass', kind: 'try_yourself',
      problem: 'Brazil produces ethanol from sugarcane. The US produces ethanol from corn. Compare the two on (a) yield per acre, (b) emissions, (c) food vs fuel trade-off.',
      expectedAnswer: '(a) YIELD: Sugarcane yields ~600 gallons ethanol/acre. Corn yields ~450 gallons/acre. Sugarcane is more efficient. \n(b) EMISSIONS: Sugarcane has lower lifecycle emissions because it requires less fertilizer and energy to grow. Corn ethanol emissions can be NEGLIGIBLE NET BENEFIT after accounting for fertilizer (Haber-Bosch), tractors, transport, and processing — sometimes even slightly negative. \n(c) FOOD vs FUEL: Both compete with food production. Corn used for ethanol could be eaten as feed/food. US corn ethanol diverts ~40% of corn crop. Drives up corn prices globally. \nBRAZILIAN sugarcane has historical advantage: ratooning (regrows annually) and tropical climate; well-suited. Cost-effective. \nUS corn ethanol persists largely due to political subsidies (Iowa primary politics).',
      responseFormat: 'free', hints: ['Different crops, different efficiencies.'], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Nuclear: zero direct CO₂; risks of accident + waste; expensive but reliable.',
      '3 major accidents: Three Mile Island, Chernobyl (worst), Fukushima.',
      'Biomass: theoretically renewable; practical issues with food competition + air pollution.',
      'Corn ethanol: marginal; sugarcane: better; second-gen (cellulosic) developing.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '6', cedTopic: '6.6-6.7', cedTitle: 'Nuclear and Biomass', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '16', note: 'Standard nuclear + biomass.' }] },
};
