/**
 * AP Environmental Science — CED Unit 5.2+5.9+5.17: Clearcutting,
 * Mining, and Sustainable Forestry.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U5_FORESTRY_MINING: LessonPlan = {
  id: 'evelyn.ap.envsci.forestry-mining.v1', title: 'U5.2 Forestry and Mining',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.forestry-mining', description: 'Distinguish clearcutting from selective cutting; identify environmental consequences. Compare surface vs subsurface mining; identify mining impacts and reclamation. Describe sustainable forestry practices.', standard: 'AP-ENVSCI-5.2+5.9+5.17' }],
  prerequisites: ['apenvsci.agriculture'], followUps: ['apenvsci.urbanization-water'], estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame extraction as transformation.', script: "We extract enormous quantities of wood, metals, and fossil fuels from the Earth. The methods used determine whether the land recovers or remains degraded. Today: forestry and mining trade-offs.", estimatedMinutes: 2 },
    { id: 'concept-extraction', kind: 'concept', goal: 'Cover forestry methods + mining types + reclamation.',
      keyIdeas: [
        'FORESTRY METHODS:',
        '  • CLEARCUTTING: harvest ALL trees in an area at once. \n     - PRO: efficient, cheap, regenerates as a single new stand.\n     - CON: massive soil erosion, sediment pollution of streams, habitat destruction, carbon release.',
        '  • SELECTIVE CUTTING: harvest only specific trees, leaving most standing.\n     - PRO: preserves canopy, reduces erosion, maintains habitat.\n     - CON: more expensive per board-foot.',
        '  • SHELTERWOOD CUTTING: gradual harvest in stages — leaves shelter trees to protect seedlings, then removed in 2nd cut.',
        '  • SEED-TREE CUTTING: most trees harvested but a few left for natural reseeding.',
        'IMPACTS OF DEFORESTATION (esp. clearcutting):',
        '  • Carbon release (lost storage + decomposition).',
        '  • Soil erosion (no roots holding soil).',
        '  • Habitat loss / biodiversity decline.',
        '  • Disrupted water cycle (transpiration↓, runoff↑).',
        '  • Loss of ecosystem services (flood control, water purification).',
        'SUSTAINABLE FORESTRY:',
        '  • Selective cutting + replanting.',
        '  • CERTIFICATION (FSC — Forest Stewardship Council).',
        '  • Maintain corridors for wildlife.',
        '  • Match harvest to forest growth rate (don\'t cut faster than regrowth).',
        '  • PRESERVE old-growth ecosystems (NOT replaceable in human timescales).',
        'MINING TYPES:',
        '  • SURFACE MINING: shallow ore.\n     - STRIP MINING: rip off surface in long strips (coal in Appalachia).\n     - OPEN-PIT: huge dug pits (copper at Bingham Canyon, UT).\n     - MOUNTAINTOP REMOVAL: blast off mountain peaks (Appalachia coal). Catastrophically destructive.\n     - PLACER MINING: stream sluicing (gold). Erodes/contaminates streams.',
        '  • SUBSURFACE MINING: deeper ore.\n     - SHAFT MINING (vertical), DRIFT MINING (horizontal into hillsides).\n     - More expensive, less surface destruction, but workers face cave-ins, black lung, methane explosions.',
        'MINING IMPACTS:',
        '  • SURFACE DESTRUCTION: stripping, slope failures.',
        '  • ACID MINE DRAINAGE: exposed sulfide ores react with water → SULFURIC ACID → kills aquatic life downstream. Persistent for centuries.',
        '  • HEAVY METAL CONTAMINATION (lead, arsenic, mercury) leaches from tailings.',
        '  • DUST AND PARTICULATES.',
        '  • OVERBURDEN waste piles.',
        '  • WATER POLLUTION: tailings ponds, leaking processing chemicals (cyanide for gold).',
        'RECLAMATION:',
        '  • Restoring mined or clearcut land to a stable post-mining state.',
        '  • Required by US Surface Mining Control and Reclamation Act (1977) for coal.',
        '  • Practices: regrade slopes, restore topsoil, replant native vegetation, monitor water.',
        '  • Reality: rarely restores to pre-disturbance ecosystem; partial recovery at best.',
      ],
      vocabulary: [
        { term: 'clearcutting', definition: 'harvesting all trees in an area at once.' },
        { term: 'acid mine drainage', definition: 'sulfuric acid produced when sulfide ores in mining waste contact water.' },
        { term: 'reclamation', definition: 'restoring disturbed land to a stable, productive state.' },
      ],
      estimatedMinutes: 6 },
    { id: 'worked-mtr', kind: 'worked_example',
      problem: 'A company proposes mountaintop-removal mining for coal in Appalachia. Identify FIVE environmental and social impacts.',
      steps: [
        'STEP 1 — Topographic destruction: peaks blasted off, debris dumped into adjacent valleys (VALLEY FILLS). Permanently alters watersheds.',
        'STEP 2 — Stream burial: ~2,000 miles of Appalachian streams buried under valley fills. Aquatic ecosystems destroyed.',
        'STEP 3 — Acid mine drainage: exposed sulfide ores → sulfuric acid → kills downstream fish, contaminates drinking water.',
        'STEP 4 — Health impacts on local communities: airborne dust (silica → silicosis), contaminated well water, increased rates of cancer, birth defects, chronic illness.',
        'STEP 5 — Carbon emissions: extracted coal burned → contributes to climate change.',
        'STEP 6 — Forest loss: temperate hardwoods clear-cut before mining. Decades to recover.',
        'STEP 7 — Reclamation rarely restores native ecosystem. New surface = grass + pioneer species, no mature forest. Biodiversity loss permanent.',
      ],
      answer: 'Topographic destruction, stream burial, acid drainage, public health, climate.', estimatedMinutes: 4 },
    { id: 'try-clearcut-vs-select', kind: 'try_yourself',
      problem: 'A timber company is offered a forest stand. Compare CLEARCUTTING vs SELECTIVE CUTTING for: (a) economic return, (b) erosion risk, (c) habitat preservation, (d) regrowth time.',
      expectedAnswer: '(a) ECONOMIC: clearcutting wins short-term (efficient, all trees at once). Selective requires multiple visits, careful selection, more labor. \n(b) EROSION: clearcutting MUCH WORSE. No roots holding soil; one storm causes massive erosion. Selective leaves canopy and roots intact. \n(c) HABITAT: selective preserves multi-story forest structure → nesting, cover, food for wildlife continues. Clearcut destroys habitat — must wait for regrowth (decades). \n(d) REGROWTH: clearcut produces a uniform stand of one age (monoculture-like). Faster recovery to "tree-covered" but slow to mature ecosystem. Selective maintains continuous mature forest.',
      responseFormat: 'free', hints: ['Trade-off: efficiency vs ecosystem function.'], estimatedMinutes: 3 },
    { id: 'try-amd', kind: 'try_yourself',
      problem: 'Acid mine drainage from an abandoned mine flows into a trout stream, killing fish. Trace the chemistry from mine to stream and suggest one remediation.',
      expectedAnswer: 'CHEMISTRY:\n• Mine exposes pyrite (FeS₂, sulfide ores) to oxygen and water. \n• Pyrite + O₂ + H₂O → sulfuric acid (H₂SO₄) + iron sulfate. \n• pH of mine water drops to 2-4 (very acidic). \n• Acidic water dissolves heavy metals (Fe, Al, Mn, Pb) in surrounding rock. \n• Acid + heavy metals enter stream → kill trout (sensitive to low pH and metals). \n• Iron precipitates as orange-yellow "yellow boy" coating stream beds. \nREMEDIATION:\n• PASSIVE TREATMENT: alkaline rocks (limestone, dolomite) buffer acid. \n• CONSTRUCTED WETLANDS — bacteria and plants neutralize acid, precipitate metals. \n• ACTIVE TREATMENT: lime addition, aeration, settling ponds. \n• MINE SEALING — prevent water entry to source. \n• PROACTIVE PREVENTION: don\'t mine sulfide-rich rock, or pre-remove sulfides.',
      responseFormat: 'free', hints: ['Sulfide oxidation; treatment options.'], estimatedMinutes: 4 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. Forests cover ~30% of Earth\'s land but their net loss continues at ~10 million hectares per year (mostly tropical). (a) Identify three drivers of deforestation. (b) Identify three environmental consequences. (c) Suggest two specific policy or economic interventions to slow tropical deforestation.',
      expectedAnswer: '(a) Drivers:\n• AGRICULTURE EXPANSION (cattle ranching in Amazon; palm-oil plantations in SE Asia; soy in Brazil). #1 driver. \n• ILLEGAL LOGGING for timber. \n• MINING and INFRASTRUCTURE (roads, dams). \n• FUELWOOD demand (sub-Saharan Africa). \n• FIRE (sometimes intentional clearing, sometimes wildfires). (2)\n(b) Consequences:\n• CARBON EMISSIONS — deforestation contributes ~10-15% of global CO₂ emissions. \n• BIODIVERSITY LOSS — tropical forests host most species; loss is irreversible. \n• WATER CYCLE DISRUPTION — reduced transpiration → reduced regional rainfall. \n• SOIL DEGRADATION + EROSION on cleared lands. \n• INDIGENOUS PEOPLE displaced or harmed. (2.5)\n(c) Policy interventions:\n• REDUCE DEMAND: certifications (FSC) for sustainably sourced wood; reduce beef consumption; transition to plant proteins. \n• ECONOMIC INCENTIVES: payments for forest carbon (REDD+ — Reducing Emissions from Deforestation and forest Degradation). \n• Strong PROPERTY RIGHTS for Indigenous communities (proven correlation: indigenous-managed forests have lowest deforestation rates). \n• ENFORCEMENT: satellite monitoring, criminal penalties for illegal clearing. \n• PROTECTED AREAS: parks, reserves with adequate funding for enforcement. \n• TRADE RESTRICTIONS on illegally sourced products. \n• REFORESTATION programs (paid for by wealthy nations or carbon markets). (2.5)\nTotal: 7 points.',
      responseFormat: 'frq', hints: ['Drivers, consequences, multi-level interventions.'], estimatedMinutes: 6 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Clearcutting: efficient, but erosion, habitat loss. Selective: better ecology, more expensive.',
      'Surface mining: strip, open-pit, mountaintop removal. Subsurface: shaft. Acid mine drainage is persistent.',
      'Reclamation required for coal but rarely restores original ecosystem.',
      'Tropical deforestation drivers: agriculture, logging, infrastructure.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '5', cedTopic: '5.2+5.9+5.17', cedTitle: 'Forestry and Mining', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '13-14', note: 'Standard forestry + mining.' }] },
};
