/**
 * AP Environmental Science — CED Unit 6.13: Energy Conservation.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U6_ENERGY_CONSERVATION: LessonPlan = {
  id: 'evelyn.ap.envsci.energy-conservation.v1', title: 'U6.4 Energy Conservation',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.energy-conservation', description: 'Distinguish energy conservation from efficiency. Identify strategies for residential, commercial, industrial, and transportation energy reduction.', standard: 'AP-ENVSCI-6.13' }],
  prerequisites: ['apenvsci.renewables'], followUps: [], estimatedMinutes: 16,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame the cheapest energy source.', script: "The cleanest, cheapest energy is the energy you DON\'T USE. Energy conservation and efficiency improvements reduce demand without sacrificing services. Often paid back in months.", estimatedMinutes: 2 },
    { id: 'concept-conservation', kind: 'concept', goal: 'Cover conservation, efficiency, sectors.',
      keyIdeas: [
        'CONSERVATION vs EFFICIENCY:',
        '  • CONSERVATION: USING LESS energy (turn off lights, drive less, lower thermostat).',
        '  • EFFICIENCY: getting more service per unit energy (LED bulb gives same light using ~85% less).',
        '  • Both reduce demand, often combined.',
        'WHY conservation/efficiency matter:',
        '  • CHEAPEST way to reduce emissions and pollution.',
        '  • Reduces need for expensive new generating capacity.',
        '  • Lower electric bills for consumers.',
        '  • Reduces import dependence (oil security).',
        '  • IEA: efficiency must provide ~40% of needed CO₂ reductions for net-zero by 2050.',
        'RESIDENTIAL conservation strategies:',
        '  • LIGHTING: replace incandescent (efficiency ~5%) with LED (~30%, lasts 25× longer).',
        '  • APPLIANCES: ENERGY STAR rated (10-50% less energy).',
        '  • INSULATION: better insulation reduces heating/cooling needs by 20-50%.',
        '  • WINDOWS: double or triple-pane low-e (low-emissivity) glass.',
        '  • SMART THERMOSTATS: program to reduce when away/sleeping.',
        '  • WATER: low-flow showerheads, faucets, dishwashers.',
        '  • Behavior: lower thermostat in winter, higher in summer.',
        'COMMERCIAL conservation:',
        '  • Building energy management systems (BEMS) — sensors, automated controls.',
        '  • LED lighting + occupancy sensors.',
        '  • HVAC efficiency upgrades.',
        '  • Cool roofs, green roofs.',
        '  • Building codes (e.g., LEED certification, ENERGY STAR for buildings).',
        'INDUSTRIAL conservation:',
        '  • Cogeneration / CHP (combined heat and power): use waste heat for electricity.',
        '  • Process improvements (e.g., more efficient motors, pumps).',
        '  • Recycling materials reduces energy needs vs virgin materials (recycling aluminum saves 95% energy vs new).',
        '  • Industrial heat recovery.',
        'TRANSPORTATION conservation:',
        '  • FUEL ECONOMY standards (CAFE in US): pushes higher mpg.',
        '  • EV TRANSITION: ~2-3× more efficient than gasoline cars (electric motor efficiency).',
        '  • Public transportation: bus 5-10× more efficient per passenger-mile vs single-occupant car.',
        '  • Rail freight: 4× more efficient than truck per ton-mile.',
        '  • Carpooling, biking, walking, e-bikes.',
        '  • Telecommuting, mixed-use development.',
        'BARRIERS:',
        '  • UPFRONT COSTS — efficient appliances cost more initially (paid back over years).',
        '  • SPLIT INCENTIVES — landlord pays appliance, tenant pays energy bill.',
        '  • REBOUND EFFECT — efficiency leads to MORE use (LED lights → leaving more lights on; better mileage → driving more).',
        '  • LACK OF AWARENESS or expertise.',
        'POLICIES:',
        '  • Building energy codes.',
        '  • Appliance efficiency standards.',
        '  • Tax credits for efficiency upgrades.',
        '  • Energy efficiency programs by utilities (often required by law).',
        '  • Carbon pricing makes inefficient choices more expensive.',
      ],
      vocabulary: [
        { term: 'conservation', definition: 'using less energy.' },
        { term: 'efficiency', definition: 'getting more service per unit energy.' },
        { term: 'rebound effect', definition: 'efficiency gains partially offset by increased usage.' },
      ],
      estimatedMinutes: 5 },
    { id: 'worked-payback', kind: 'worked_example',
      problem: 'A homeowner spends $200 to replace 20 incandescent bulbs with LEDs. Each LED uses 7W vs 60W. House operates lights ~5 hours/day. Electricity costs $0.15/kWh. Compute payback period and 10-year savings.',
      steps: [
        'STEP 1 — Energy savings per bulb: 60W − 7W = 53W per hour saved.',
        'STEP 2 — 20 bulbs × 53W × 5 hours/day = 5,300 Wh/day = 5.3 kWh/day.',
        'STEP 3 — Daily savings: 5.3 × $0.15 = $0.795/day. Annual: $290/year.',
        'STEP 4 — PAYBACK: $200 / $290 ≈ 0.69 years (8 months).',
        'STEP 5 — 10-YEAR SAVINGS: $290 × 10 − $200 = $2,700.',
        'STEP 6 — LEDs also last ~25× longer than incandescents → fewer replacements over 10 years (extra savings on bulbs).',
      ],
      answer: 'Payback ~8 months; saves ~$2,700 over 10 years.', estimatedMinutes: 4 },
    { id: 'try-strategies', kind: 'try_yourself',
      problem: 'For each sector, suggest two specific energy-conservation actions: (a) Residential. (b) Transportation. (c) Industrial.',
      expectedAnswer: '(a) RESIDENTIAL: LED bulbs; ENERGY STAR appliances; better insulation; double-pane windows; smart thermostat; lower water heater temperature; air seal house. \n(b) TRANSPORTATION: drive an EV or efficient hybrid; carpool / public transit; combine errands; maintain tire pressure (3% mpg gain); avoid idling; e-bike for short trips. \n(c) INDUSTRIAL: cogeneration (CHP); upgrade old electric motors to high-efficiency; recover process heat; insulate steam lines; recycle materials; LED industrial lighting; reduce material use through design.',
      responseFormat: 'free', hints: ['Multiple options each sector.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. The "rebound effect" can partially offset efficiency gains. (a) Define rebound and give an example. (b) When does it MOST happen — for inelastic-demand activities (e.g., heating) or elastic-demand (e.g., driving)? (c) How can policymakers compensate?',
      expectedAnswer: '(a) REBOUND EFFECT: efficiency gains lead to INCREASED USAGE that partially or fully offsets energy savings. \nEXAMPLE: more fuel-efficient cars → people drive more (longer commutes, more leisure driving). LEDs use less energy per bulb → people leave more lights on. (1.5)\n(b) Rebound is LARGER when demand is ELASTIC (responds to price/cost): \n• DRIVING: as cost per mile drops, people drive significantly more. Rebound can be 10-30%. \n• Air conditioning: as efficiency improves, people use more AC. Rebound 5-20%. \n• HEATING is more INELASTIC (you set a thermostat) — small rebound. \nGenerally rebound is 5-30%; rarely fully offsets gains. (2)\n(c) Policy responses to rebound:\n• CARBON PRICING — raises cost of energy regardless of efficiency, blunting rebound. Even efficient cars get more expensive to drive. \n• Total energy CAPS or quotas — sets absolute ceiling regardless of efficiency. \n• PUBLIC TRANSIT investment — alternatives reduce need to drive at all. \n• Efficiency standards combined with conservation campaigns. \n• Education about rebound so people are aware. (1.5)\nTotal: 5 points.',
      responseFormat: 'frq', hints: ['Define, condition, mitigation.'], estimatedMinutes: 4 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Conservation (less use) vs efficiency (more service per unit) — both reduce demand.',
      'Cheapest way to cut emissions; often pays back in months/years.',
      'Sectors: residential (LED, insulation), transportation (EV, transit), industrial (CHP, motors).',
      'Rebound effect partially offsets gains; policies can blunt.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '6', cedTopic: '6.13', cedTitle: 'Energy Conservation', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '16', note: 'Standard energy conservation.' }] },
};
