/**
 * AP Environmental Science — CED Unit 1.11: Food Chains and Food Webs.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U1_FOOD_WEBS: LessonPlan = {
  id: 'evelyn.ap.envsci.food-webs.v1', title: 'U1.5 Food Chains and Food Webs',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.food-webs', description: 'Distinguish food chains (single trophic path) from food webs (interconnected). Identify keystone species and predict effects of their removal. Trace bioaccumulation and biomagnification through trophic levels.', standard: 'AP-ENVSCI-1.11' }],
  prerequisites: ['apenvsci.productivity-energy-flow'], followUps: [], estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame webs as more realistic than chains.', script: "A FOOD CHAIN shows ONE path. But real ecosystems are FOOD WEBS — networks where a fox eats rabbits AND mice AND birds, and a hawk eats foxes AND mice AND snakes. Today: webs, keystone species, and how toxins amplify up the food web.", estimatedMinutes: 2 },
    { id: 'concept-food-webs', kind: 'concept', goal: 'Cover webs, keystones, biomagnification.',
      keyIdeas: [
        'FOOD CHAIN: linear sequence of organisms each feeding on the next. e.g., grass → rabbit → fox → hawk.',
        'FOOD WEB: multiple interconnected food chains. More realistic. Most species occupy multiple positions.',
        'Why webs > chains for stability: REDUNDANCY — if one species declines, predators have alternatives. Simple food chains are FRAGILE.',
        'KEYSTONE SPECIES: species whose IMPACT on the ecosystem is DISPROPORTIONATELY LARGE relative to its abundance. Removing it dramatically restructures the community.',
        '  • Examples:',
        '    - SEA OTTERS: eat sea urchins. Without otters, urchins overgraze KELP forests → ecosystem collapse to "urchin barrens."',
        '    - WOLVES (Yellowstone): keep elk populations in check. Without wolves, elk overgraze willows → trophic cascade affects beavers, songbirds, riparian zones.',
        '    - BEAVERS: ECOSYSTEM ENGINEERS — dams create wetlands.',
        '    - CORALS: reef-builders; provide habitat for thousands of species.',
        '  • Distinguish from DOMINANT species (most abundant) — keystone need not be most abundant.',
        'TROPHIC CASCADE: change at one trophic level ripples through the rest. Wolves → elk → willows → songbirds is a classic cascade.',
        'BIOACCUMULATION: a single organism accumulates a substance (e.g., a fat-soluble toxin) over its lifetime — concentration in its body increases over time.',
        'BIOMAGNIFICATION: concentration INCREASES at HIGHER TROPHIC LEVELS. Each predator eats many prey, each of which has accumulated some toxin → predator gets the SUM. Toxins concentrate up the food web.',
        '  • Classic example: DDT in 1960s. Algae absorbed DDT → fish accumulated → birds (eagles, ospreys) had highest concentrations → eggshell thinning, near-extinction. Banned 1972.',
        '  • MERCURY in fish (especially top predators like tuna, swordfish, sharks). Pregnant women advised to limit consumption.',
        '  • PCBs, DIOXINS — fat-soluble organic pollutants.',
        'TRAITS that make a substance prone to biomagnification:',
        '  • FAT-SOLUBLE (lipophilic) — stored in fatty tissues; not flushed out.',
        '  • PERSISTENT — degrades slowly in environment.',
        '  • LOW EXCRETION RATE.',
      ],
      vocabulary: [
        { term: 'keystone species', definition: 'species with disproportionately large ecosystem impact relative to abundance.' },
        { term: 'biomagnification', definition: 'increase in toxin concentration at successive trophic levels.' },
        { term: 'trophic cascade', definition: 'effect at one trophic level ripples through others.' },
      ],
      estimatedMinutes: 5 },
    { id: 'worked-keystone', kind: 'worked_example',
      problem: 'Sea otters off the California coast prey on sea urchins, which graze on kelp. Predict three changes if a disease wiped out the sea otters.',
      steps: [
        'STEP 1 — Without otters, urchins are released from predation → urchin population EXPLODES.',
        'STEP 2 — Urchins overgraze KELP → kelp forests COLLAPSE to "urchin barrens" (bare rock).',
        'STEP 3 — Loss of kelp → loss of HABITAT for hundreds of species (rockfish, crabs, sea lions). Biodiversity declines.',
        'STEP 4 — Bonus: kelp sequesters carbon. Loss → less ocean carbon storage.',
        'STEP 5 — Bonus: kelp dampens wave energy. Loss → coastal erosion increases.',
        'CONCLUSION: sea otters are a KEYSTONE species — their removal triggers a TROPHIC CASCADE.',
      ],
      answer: 'Urchin explosion → kelp collapse → biodiversity loss + downstream effects (carbon, erosion).', estimatedMinutes: 4 },
    { id: 'try-biomagnification', kind: 'try_yourself',
      problem: 'A pesticide enters a lake. Concentrations measured in organisms (in ppm): algae 0.04, zooplankton 0.4, small fish 4, large fish 40, fish-eating bird 400. (a) Identify whether this is bioaccumulation or biomagnification. (b) What is the magnification factor between trophic levels? (c) Why are top predators most at risk?',
      expectedAnswer: '(a) BIOMAGNIFICATION — concentration RISES across trophic levels. (Bioaccumulation refers to within-individual buildup over time.) \n(b) Each level concentrates ~10× the prior level (0.04 → 0.4 → 4 → 40 → 400). 10× per step. \n(c) Top predators eat many prey items, each with accumulated toxin. They get the SUM. Plus longer lifespans → more time to accumulate. The bird at 400 ppm is at 10,000× the algae concentration.',
      responseFormat: 'free', hints: ['Magnification factor; cumulative effect across levels.'], estimatedMinutes: 4 },
    { id: 'try-keystone-id', kind: 'try_yourself',
      problem: 'For each scenario, identify whether the species is likely keystone, dominant, or neither: \n(a) Bison make up 80% of large grazer biomass on a prairie; their removal would significantly affect grass cover. \n(b) Beavers (rare) build dams that create wetlands hosting hundreds of species. \n(c) Dandelions are abundant in suburban lawns but their removal wouldn\'t restructure the ecosystem.',
      expectedAnswer: '(a) DOMINANT (could also have keystone characteristics if their impact is disproportionate, but the description emphasizes abundance). (b) KEYSTONE — rare but disproportionately impactful (ecosystem engineering). (c) NEITHER — abundant but low impact; their removal doesn\'t change much.',
      responseFormat: 'free', hints: ['Keystone = high impact / abundance. Dominant = high abundance.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. A coastal community is experiencing declines in their kelp-forest fishery. Investigators find that recreational hunting has reduced sea otter populations from 100/km² to 10/km². (a) Diagnose the chain of cause and effect. (b) Suggest a management response. (c) The pesticide DDT, banned in the US in 1972, was responsible for collapses of bird populations including bald eagles. Explain DDT\'s effect using biomagnification.',
      expectedAnswer: '(a) Sea otters (keystone) reduced → urchin populations grow unchecked → urchins overgraze kelp → kelp forest collapses → habitat for fish lost → fishery declines. CLASSIC TROPHIC CASCADE from removal of a keystone predator. (3)\n(b) PROTECT/RESTORE OTTERS: ban hunting, establish marine reserves, support otter reintroduction. As otters recover, kelp recovers, fishery recovers. Slow but proven (e.g., West Coast otter recovery). (1.5)\n(c) DDT was sprayed on crops. Algae/insects absorbed it → fish ate insects → eagles ate fish. DDT is FAT-SOLUBLE and PERSISTENT, so it BIOMAGNIFIED at each step — eagles had the HIGHEST concentrations. DDT in eagles caused EGGSHELL THINNING (interfered with calcium metabolism) → eggs broke during incubation → reproductive failure → near-extinction. Banning DDT (1972) led to recovery; bald eagles delisted from endangered species list in 2007. (2.5)\nTotal: 7 points.',
      responseFormat: 'frq', hints: ['Cascade; management; classic biomagnification example.'], estimatedMinutes: 6 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Food web > food chain in real ecosystems. Webs add stability via redundancy.',
      'Keystone species: high impact / low abundance. Removal triggers trophic cascades.',
      'Bioaccumulation = within individual. Biomagnification = across trophic levels.',
      'Fat-soluble + persistent + low-excretion → high biomagnification risk.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '1', cedTopic: '1.11', cedTitle: 'Food Chains and Webs', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '3', note: 'Standard food webs + biomagnification.' }] },
};
