/**
 * AP Environmental Science — CED Unit 8.1+8.2+8.4: Sources of Pollution +
 * Human Impacts on Wetlands and Mangroves.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U8_WATER_POLLUTION_SOURCES: LessonPlan = {
  id: 'evelyn.ap.envsci.water-pollution-sources.v1', title: 'U8.1 Water Pollution Sources and Wetlands',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.water-pollution-sources', description: 'Identify point and nonpoint water pollution sources. Distinguish surface vs groundwater pollution. Understand the role of wetlands and mangroves in water filtration and habitat provision.', standard: 'AP-ENVSCI-8.1+8.2+8.4' }],
  prerequisites: [], followUps: ['apenvsci.eutrophication-thermal'], estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame water pollution scope.', script: "Roughly 80% of global wastewater is released into waterways untreated. Pollution comes from POINT sources (factories, sewage plants) and NONPOINT (agriculture runoff, urban runoff). The most critical natural defense — wetlands — has been drained at half the rate of forests.", estimatedMinutes: 2 },
    { id: 'concept-pollution', kind: 'concept', goal: 'Cover sources + wetlands.',
      keyIdeas: [
        'WATER POLLUTION SOURCES:',
        '  • POINT SOURCE: identifiable, fixed location.\n     Examples: sewage treatment plant outfall, factory discharge, oil-tanker spill, chemical plant pipe.\n     Easier to regulate and monitor.',
        '  • NONPOINT SOURCE: diffuse, hard to trace.\n     Examples: agricultural runoff (fertilizer, pesticide), urban runoff (oil, lawn chemicals), atmospheric deposition (mercury), construction sediment.\n     LARGER total contribution; harder to regulate.',
        'TYPES OF POLLUTANTS:',
        '  • PATHOGENS (bacteria, viruses, parasites): from sewage, livestock waste. Cause cholera, typhoid, dysentery.',
        '  • OXYGEN-DEMANDING WASTES: organic matter that decomposers consume O₂ to break down. Includes sewage, food processing.',
        '  • INORGANIC NUTRIENTS (N, P): cause eutrophication.',
        '  • TOXIC HEAVY METALS (lead, mercury, arsenic): bioaccumulate, persist.',
        '  • SYNTHETIC ORGANIC COMPOUNDS: pesticides, PCBs, pharmaceuticals.',
        '  • SEDIMENT: from erosion. Cloudy water blocks light, smothers eggs/larvae.',
        '  • RADIOACTIVE: from mining, nuclear, medical waste.',
        '  • THERMAL: heated water from power plants reduces dissolved O₂.',
        'SURFACE vs GROUNDWATER:',
        '  • SURFACE WATER: rivers, lakes, oceans. Easier to clean (sunlight, mixing). Pollution visible.',
        '  • GROUNDWATER (in AQUIFERS): below land surface. SLOW to contaminate AND slow to clean. Once polluted, takes decades to centuries to recover. Examples of groundwater contamination: leaking underground gasoline tanks, septic systems, fracking fluid, agricultural nitrates.',
        'INDICATOR SPECIES: their presence/absence reveals water quality. Mayflies, stoneflies = clean; midge larvae, blackworms = polluted.',
        'CLEAN WATER ACT (1972, US): regulates point sources via NPDES (National Pollutant Discharge Elimination System) permits. Limited control over nonpoint sources.',
        'WETLANDS AND MANGROVES:',
        '  • WETLANDS: areas saturated with water (swamps, marshes, bogs, fens).',
        '  • Functions:\n     - WATER PURIFICATION (plants and microbes break down pollutants).\n     - FLOOD CONTROL (act as sponges).\n     - SEDIMENT TRAPPING.\n     - HABITAT (50% of N. American bird species use wetlands).\n     - CARBON STORAGE (peat).\n     - RECHARGE GROUNDWATER.',
        '  • THREATS: drainage for agriculture and development. ~50% of US wetlands lost; >85% in some states (CA).',
        '  • MANGROVES: salt-tolerant trees in tropical/subtropical coasts.',
        '  • Functions:\n     - PROTECT COASTS from storms (10-15 mm waves reduced per 100 m of mangrove).\n     - PREVENT EROSION (root systems hold sediment).\n     - NURSERY for fisheries (shrimp, crabs, fish).\n     - CARBON STORAGE (mangroves store ~5x more C per area than terrestrial forests).',
        '  • THREATS: shrimp aquaculture (mangrove cleared for ponds), coastal development, sea-level rise.',
        '  • Loss: ~30-50% of historical mangrove cover gone; 1-2% disappearing per year.',
      ],
      vocabulary: [
        { term: 'point source', definition: 'identifiable, fixed pollution location.' },
        { term: 'nonpoint source', definition: 'diffuse pollution (agriculture, urban runoff).' },
        { term: 'mangrove', definition: 'salt-tolerant tropical/subtropical coastal tree; nursery + protection.' },
      ],
      estimatedMinutes: 5 },
    { id: 'worked-classify', kind: 'worked_example',
      problem: 'Classify each as POINT or NONPOINT water pollution source: (a) Wastewater pipe from sewage treatment plant. (b) Lawn fertilizer washed into a stream during rain. (c) Oil tanker spill. (d) Atmospheric deposition of mercury onto a lake.',
      steps: [
        '(a) POINT — single, identifiable pipe.',
        '(b) NONPOINT — diffuse, occurs across many lawns; rainfall-dependent.',
        '(c) POINT — single identifiable spill location.',
        '(d) NONPOINT — atmospheric source spread across watershed.',
      ],
      answer: '(a) Point. (b) Nonpoint. (c) Point. (d) Nonpoint.', estimatedMinutes: 2 },
    { id: 'try-wetlands', kind: 'try_yourself',
      problem: 'A coastal city loses 50% of its mangrove forest to shrimp farming. Predict three consequences.',
      expectedAnswer: '(1) INCREASED COASTAL EROSION — root systems gone, no sediment trapping. \n(2) GREATER STORM DAMAGE — mangroves dampen waves; without them, hurricanes/typhoons cause more flooding/destruction. \n(3) FISHERY DECLINE — many fish/shrimp/crab species use mangroves as nurseries; without them, populations crash. \n(4) BIODIVERSITY LOSS — bird, reptile, mammal species dependent on mangroves displaced. \n(5) CARBON RELEASE — mangroves store huge carbon; clearing releases it as CO₂. \n(6) IRONICALLY: shrimp farming itself worsens fishery (the pond spreads, fewer wild shrimp). \n(7) SEA-LEVEL RISE protection lost — mangroves slow inundation.',
      responseFormat: 'free', hints: ['Multi-faceted ecosystem service loss.'], estimatedMinutes: 3 },
    { id: 'try-groundwater', kind: 'try_yourself',
      problem: 'Why is GROUNDWATER pollution especially serious? Explain three reasons.',
      expectedAnswer: '(1) SLOW CLEANUP — water moves slowly underground (often inches/year), so contaminated plumes spread slowly and clean naturally only over decades-centuries. \n(2) DIFFICULT TO REMEDIATE — accessing contaminated zones requires expensive pumping or chemical treatment; some methods don\'t work for certain contaminants. \n(3) NO SUNLIGHT — UV doesn\'t naturally break down many pollutants in groundwater. Less microbial activity than surface water. \n(4) LARGE STAKES — ~30% of US drinking water from groundwater; aquifers are major sources for agriculture/cities. \n(5) HIDDEN — pollution often discovered only when wells start failing. By then it\'s widespread. \n(6) CONTAMINATION SOURCES persistent — leaking storage tanks, agricultural nitrates, septic systems can contaminate for decades after source is removed.',
      responseFormat: 'free', hints: ['Slow, difficult, hidden.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. The Cuyahoga River in Cleveland CAUGHT FIRE in 1969 due to oil and chemical pollution. (a) Why is it remarkable that a river burned? (b) What policies followed and how have things changed? (c) What about NONPOINT sources today?',
      expectedAnswer: '(a) Rivers don\'t burn — water is non-flammable. The Cuyahoga had so much oil, chemical waste, and debris on its surface that the LAYER OF POLLUTION was thick enough to ignite from sparks (from a passing train). The river had burned MULTIPLE TIMES (1936, 1952, 1969) due to industrial pollution. Symptoms of severely degraded urban water — oxygen-depleted, biologically dead. (1.5)\n(b) Policy response:\n• 1969 fire (and similar events) galvanized environmental movement. \n• 1970: ENVIRONMENTAL PROTECTION AGENCY founded. \n• 1972: CLEAN WATER ACT passed. \n• Sets discharge standards via NPDES permits. \n• Required SECONDARY TREATMENT at sewage plants. \n• Funded $50+ billion in wastewater infrastructure. \nResults: \n• Cuyahoga has not burned since. \n• Fish returned (60+ species). \n• Industrial discharges dramatically reduced. \n• POINT-SOURCE pollution largely controlled. (2.5)\n(c) NONPOINT sources today:\n• Major remaining challenge — Clean Water Act has limited authority over nonpoint. \n• Agricultural runoff (Mississippi → Gulf dead zone, Chesapeake Bay). \n• Urban stormwater runoff. \n• Atmospheric deposition. \n• REMAINING POLLUTANTS: nutrients, sediment, pesticides, plastics. \n• Solutions: best management practices on farms, green infrastructure, watershed-level planning, but enforcement weaker than for point sources. (2)\nTotal: 6 points.',
      responseFormat: 'frq', hints: ['Iconic case → policy → contemporary challenges.'], estimatedMinutes: 5 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Point (factory, pipe) vs nonpoint (agriculture, urban) pollution.',
      'Pathogens, oxygen-demanding wastes, nutrients, toxics, sediment, thermal, radioactive.',
      'Groundwater pollution slow to develop AND to clean up.',
      'Wetlands + mangroves provide flood control, habitat, water purification, carbon storage.',
      'Clean Water Act 1972 controls point sources via NPDES; nonpoint less regulated.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '8', cedTopic: '8.1-8.2+8.4', cedTitle: 'Water Pollution Sources', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '11', note: 'Standard water pollution.' }] },
};
