/**
 * AP Environmental Science — Unit 9 FRQ Practice.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U9_FRQ_PRACTICE: LessonPlan = {
  id: 'evelyn.ap.envsci.u9-frq-practice.v1', title: 'U9 FRQ Practice',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.u9-frq-practice', description: 'Apply Unit 9 global change concepts to AP-style FRQs.', standard: 'AP-ENVSCI-9-FRQ' }],
  prerequisites: ['apenvsci.biodiversity-threats'], followUps: [], estimatedMinutes: 26,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Stakes.', script: "Two Unit 9 FRQs synthesizing climate change, ozone, ocean changes, biodiversity.", estimatedMinutes: 2 },
    { id: 'concept-strategy', kind: 'concept', goal: 'Refresh.', keyIdeas: [
      'Greenhouse effect; CO₂, CH₄, N₂O, F-gases; GWP.',
      'Stratospheric vs tropospheric ozone. Montreal Protocol success.',
      'Ocean: warming → bleaching; CO₂ + H₂O → acidification → shell-builders.',
      'HIPPCO. Invasive species + endangered species + ESA.',
    ], estimatedMinutes: 2 },
    { id: 'try-frq-climate', kind: 'try_yourself',
      problem: 'FRQ Practice 1 — Climate Change Synthesis. Atmospheric CO₂ has risen from ~280 ppm pre-industrial to ~420 ppm in 2024 — the fastest rate in 800,000 years. (a) Identify the two largest sources of human CO₂ emissions. (b) Trace at least THREE evidence lines that confirm anthropogenic origin. (c) Identify TWO POSITIVE FEEDBACK loops. (d) Identify ONE major international agreement and explain why it has been less successful than the Montreal Protocol.',
      expectedAnswer: '(a) Two largest CO₂ sources:\n• FOSSIL FUEL COMBUSTION (~75% of emissions): coal for electricity, oil for transportation, natural gas for heating + industry. \n• DEFORESTATION + LAND-USE CHANGE (~10-15%): clearing forests releases stored C, removes future absorption. (1.5)\n(b) Evidence of anthropogenic origin:\n1. Direct EMISSIONS measurements correlate with atmospheric CO₂ rise. \n2. ISOTOPIC SIGNATURE: rising atmospheric CO₂ is depleted in ¹⁴C (radioactive carbon, has decayed in ancient fossil fuels). Carbon from fossil fuels has fingerprint different from natural sources. \n3. CO₂ rise CORRELATES with industrialization (post-1850 acceleration). \n4. SPATIAL pattern: more CO₂ near population centers. \n5. CARBON BUDGET — atmospheric CO₂ + ocean uptake matches emissions. \n6. ICE CORE records show CO₂ never reached 420 ppm in 800,000 years. (2.5)\n(c) Positive feedback loops:\n1. ALBEDO feedback: warming → ice/snow melt → exposed darker surfaces → more solar absorption → more warming. \n2. METHANE FROM PERMAFROST: warming thaws Arctic permafrost → releases stored methane → more warming. \n3. WATER VAPOR feedback: warming → more water vapor → which is GHG → more warming. \n4. FOREST DIEBACK: drought + heat → trees die → CO₂ released → more warming. \n5. Wildfire feedback: hotter, drier → more fires → CO₂ release. (2)\n(d) PARIS AGREEMENT (2015):\n• Voluntary national commitments (NDCs) to reduce emissions. \n• 195 nations participating. \n• Goal: hold warming below 2°C, ideally 1.5°C. \nWhy LESS SUCCESSFUL than Montreal:\n• MUCH LARGER scope (all carbon emissions vs ~100 ozone-depleting substances). \n• ALTERNATIVES less mature (renewable energy still scaling). \n• ENFORCEMENT WEAK — voluntary, no penalties. \n• NATIONAL POLITICS shift; commitments not always implemented. \n• ECONOMIC interests deeply embedded in fossil-fuel infrastructure. \n• Current emissions reductions falling SHORT of pledges. \n• Plus: Paris doesn\'t require negative emissions, only reductions. \n• Despite Paris, atmospheric CO₂ continues rising. (2)\nTotal: 8 points.',
      rubric: { parts: [
        { criterionId: 'a', maxPoints: 2, scoringCriteria: 'Identifies the two largest human CO₂ sources: fossil-fuel combustion and deforestation/land-use change.', modelResponse: 'FOSSIL-FUEL COMBUSTION (~75% of emissions — coal, oil, gas) and DEFORESTATION / LAND-USE CHANGE (~10-15%), which releases stored carbon and removes future absorption.' },
        { criterionId: 'b', maxPoints: 3, scoringCriteria: 'Traces at least three evidence lines for anthropogenic origin (emissions correlation, depleted ¹⁴C/¹³C isotopic signature, correlation with industrialization, ice-core records, or the carbon budget).', modelResponse: 'Emissions measurements correlate with the atmospheric CO₂ rise; the added CO₂ carries a fossil ISOTOPIC SIGNATURE (depleted in ¹⁴C); the rise CORRELATES with industrialization since 1850; and ice-core records show CO₂ never reached 420 ppm in 800,000 years.' },
        { criterionId: 'c', maxPoints: 2, scoringCriteria: 'Identifies two positive feedback loops (albedo/ice-melt, permafrost methane, water vapor, forest dieback, or wildfire).', modelResponse: 'ALBEDO feedback: warming melts ice/snow, exposing darker surfaces that absorb more sunlight; and PERMAFROST METHANE: warming thaws Arctic permafrost, releasing methane that drives further warming (water-vapor feedback also qualifies).' },
        { criterionId: 'd', maxPoints: 2, scoringCriteria: 'Names a major international agreement (Paris Agreement) and explains why it has been less successful than the Montreal Protocol (larger scope, immature alternatives, weak/voluntary enforcement, embedded economic interests).', modelResponse: 'The PARIS AGREEMENT (2015) relies on voluntary national commitments; it is less successful than Montreal because it covers all carbon emissions (far broader than ~100 ozone substances), alternatives are less mature, and enforcement is weak and voluntary, so emissions keep rising.' },
      ] },
      responseFormat: 'frq', hints: ['Sources, evidence, feedbacks, comparison.'], estimatedMinutes: 7 },
    { id: 'try-frq-biodiv', kind: 'try_yourself',
      problem: 'FRQ Practice 2 — Biodiversity. The Amazon rainforest is a major biodiversity hotspot facing serious threats. (a) Apply HIPPCO to identify TWO major threats with specific examples. (b) Identify TWO ecosystem services lost when Amazon forests are cleared. (c) Suggest THREE policy interventions to slow Amazon deforestation. (d) Why is the Amazon called a "tipping point" candidate?',
      expectedAnswer: '(a) Threats from HIPPCO:\nH (HABITAT DESTRUCTION): \n• Cattle ranching — Brazilian beef production drives most clearing. \n• Soy plantations expanding into former forest. \n• Roads and infrastructure (BR-319 highway expansion). \nO (OVEREXPLOITATION): \n• Illegal logging of mahogany and other valuable timbers. \n• Wildlife trafficking (parrots, monkeys for pet trade). \nC (CLIMATE CHANGE): \n• Amazon experiencing more droughts; some areas approaching forest-dieback threshold. \n• Higher temperatures stress remaining forest. \nP (POLLUTION): \n• Mercury from gold mining contaminating rivers. \n• Pesticide runoff from agricultural expansion. (2.5)\n(b) Ecosystem services lost:\n1. CARBON STORAGE: Amazon stores ~150-200 Gt of carbon. Loss via deforestation contributes 5-10% of global emissions. \n2. WATER CYCLE: Amazon transpires huge volumes; reduced transpiration → reduced rainfall regionally and globally. Could affect crops in S. Brazil, Argentina. \n3. BIODIVERSITY: Amazon hosts 10% of world species; loss is unique. \n4. CLIMATE REGULATION: heat balance and atmospheric circulation. \n5. INDIGENOUS culture and human rights. \n6. PHARMACEUTICAL potential — undescribed species may yield medicines. (2)\n(c) Policy interventions:\n1. STRENGTHEN BRAZIL\'S environmental enforcement — IBAMA inspections, satellite monitoring. \n2. ECONOMIC INCENTIVES: payments for forest conservation (REDD+ programs); pay nations to protect forests. \n3. INDIGENOUS LAND RIGHTS: protected when indigenous communities have legal title (proven correlation: indigenous-managed forests have lowest deforestation rates). \n4. Reduce DEMAND for products driving deforestation: certified sustainable beef, soy. Consumer pressure on multinationals (e.g., Cargill, JBS). \n5. INTERNATIONAL TRADE pressure: trade penalties for nations failing on deforestation. \n6. STRATEGIC zoning: designate protected areas around riverways, biodiversity hotspots. \n7. Investment in alternative livelihoods for forest communities. (2.5)\n(d) Tipping point candidate because:\n• Amazon recycles ~50% of its OWN rainfall through evapotranspiration. \n• If deforestation passes critical threshold (~25% loss; we are at ~20%), the FOREST CANNOT MAINTAIN ITS RAINFALL — would dry out. \n• At that point, FOREST WOULD COLLAPSE TO SAVANNA — a TIPPING POINT (irreversible on human timescales). \n• Once tipped, no recovery without artificial intervention. \n• Would release 100+ Gt of CO₂. \n• Would cause precipitation reduction across South America. \n• Most rainforest research suggests we are approaching but not yet past this threshold; another 5-10% deforestation could trigger it. (2)\nTotal: 9 points.',
      rubric: { parts: [
        { criterionId: 'a', maxPoints: 3, scoringCriteria: 'Applies HIPPCO to identify two major Amazon threats with specific examples (habitat destruction from ranching/soy, overexploitation via logging/trafficking, climate-driven drought, or mining/pesticide pollution).', modelResponse: 'HABITAT DESTRUCTION (H): cattle ranching and soy plantations clearing forest, plus roads like BR-319. OVEREXPLOITATION (O): illegal mahogany logging and wildlife trafficking. (Climate-driven drought and mercury pollution from gold mining also qualify.)' },
        { criterionId: 'b', maxPoints: 2, scoringCriteria: 'Identifies two ecosystem services lost when Amazon forest is cleared (carbon storage, water-cycle/rainfall regulation, biodiversity, climate regulation, or pharmaceutical potential).', modelResponse: 'CARBON STORAGE — the Amazon holds ~150-200 Gt of carbon that clearing releases; and the WATER CYCLE — its huge transpiration generates regional rainfall, so deforestation reduces precipitation across South America (plus lost biodiversity).' },
        { criterionId: 'c', maxPoints: 2, scoringCriteria: 'Suggests three policy interventions to slow deforestation (enforcement/satellite monitoring, REDD+ payments, Indigenous land rights, demand-side certification, or trade pressure).', modelResponse: 'Strengthen ENFORCEMENT with satellite monitoring (IBAMA), pay for conservation through REDD+ programs, and secure INDIGENOUS LAND RIGHTS (Indigenous-managed forests have the lowest deforestation) — with demand-side sustainable certification and trade pressure as further tools.' },
        { criterionId: 'd', maxPoints: 2, scoringCriteria: 'Explains why the Amazon is a tipping-point candidate: it recycles ~half its own rainfall, so past a deforestation threshold (~25%) it cannot sustain its rainfall and would collapse irreversibly to savanna.', modelResponse: 'The Amazon recycles ~50% of its own rainfall through evapotranspiration; past a critical threshold (~25% loss; we are near 20%) it cannot maintain that rainfall, drying out and collapsing to SAVANNA — an irreversible TIPPING POINT that would release 100+ Gt of CO₂.' },
      ] },
      responseFormat: 'frq', hints: ['HIPPCO; services; policies; tipping point reasoning.'], estimatedMinutes: 7 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'CO₂, CH₄, N₂O, F-gases all warm Earth at different GWPs.',
      'Ocean buffers climate but pays cost: warming + acidification.',
      'Coral reefs and shell-builders most acutely vulnerable.',
      'HIPPCO: habitat, invasives, pop, pollution, climate, overexploitation.',
      'Tipping points: Amazon, ice sheets, AMOC, permafrost.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '9', cedTopic: '9-FRQ', cedTitle: 'Unit 9 FRQ Practice', sources: [{ type: 'frq-style', source: 'AP Plans Initiative author', note: 'Modeled on AP Env Sci Unit-9 FRQs.' }] },
};
