/**
 * AP French Language — Grammar and Verb System.
 */

import type { LessonPlan } from '../types';

export const SEED_AP_FRENCH_LANG_GRAMMAR: LessonPlan = {
  id: 'evelyn.ap.french-lang.grammar.v1',
  title: 'AP French Language — Verb System and Grammar',
  curriculum: 'AP',
  grade: '11',
  subject: 'languages',
  topic: 'ap-french-lang',
  locale: 'en',
  los: [{ id: 'ap.french-lang.grammar', description: 'Master French verb tenses (passé composé/imparfait/subjonctif), agreement, pronoun placement at AP level.', standard: 'AP-FRENCH-LANG' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 16,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'AP French Lang demands varied tenses, correct agreement, and proper subjunctive use.', script: 'Passé composé vs imparfait, subjonctif, pronoun placement, agreement (gender + number) — these are the high-yield grammar topics graders look for. Today: structures + common errors.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Tenses, subjunctive triggers, agreement, pronoun placement.', keyIdeas: [
      'KEY VERB TENSES:',
      '  PRÉSENT: present routine, present truth.',
      '  PASSÉ COMPOSÉ: completed past actions ("J\'ai vu le film"). Auxiliary AVOIR or ÊTRE + past participle.',
      '  IMPARFAIT: ongoing/habitual past ("J\'allais à l\'école tous les jours").',
      '  PLUS-QUE-PARFAIT: had-done (had + past participle).',
      '  FUTUR SIMPLE: future ("Je verrai demain"). Also probability about present.',
      '  CONDITIONNEL: would-action ("Je verrais si je pouvais"). Politeness ("Je voudrais...").',
      '  SUBJONCTIF (présent + passé): triggered by specific structures.',
      'PASSÉ COMPOSÉ vs IMPARFAIT (the most-tested distinction):',
      '  PC: completed event with clear endpoint. "J\'ai mangé une pomme."',
      '  Imparfait: background, ongoing state, habitual. "Je mangeais des pommes chaque jour."',
      '  Often together: "J\'étudiais (imp) quand le téléphone a sonné (PC)" — background interrupted by event.',
      'AUXILIARY: most verbs use AVOIR. Use ÊTRE for: DR + MRS VANDERTRAMP verbs (Devenir, Revenir, Mourir, Rester, Sortir, Venir, Aller, Naître, Descendre, Entrer, Rentrer, Tomber, Retourner, Arriver, Monter, Partir) — verbs of motion / state change. Reflexive verbs always use ÊTRE.',
      '  With ÊTRE: past participle agrees with subject (gender + number). "Elle est partie." "Ils sont partis."',
      '  With AVOIR: past participle agrees with PRECEDING DIRECT OBJECT only. "La pomme que j\'ai mangée."',
      'SUBJONCTIF triggers (memorise):',
      '  Volonté/désir: vouloir que, désirer que.',
      '  Émotion: être content que, regretter que.',
      '  Doute/négation: douter que, ne pas croire que.',
      '  Nécessité/jugement: il faut que, il est important que.',
      '  Conjunctions: bien que, pour que, avant que, jusqu\'à ce que, à condition que.',
      '  After certain superlatives: "le seul/dernier... que".',
      'PRONOUN PLACEMENT order in declarative:',
      '  Subject + (ne) + me/te/se/nous/vous + le/la/les + lui/leur + y + en + verb (+ pas).',
      '  "Je le lui donne." (I give it to him.)',
      '  In passé composé: pronoun goes BEFORE the auxiliary. "Je le lui ai donné."',
      'AGREEMENT:',
      '  Adjectives agree in gender + number with noun.',
      '  Past participles with être agree with subject.',
      '  Past participles with avoir agree with preceding direct object only.',
      'COMMON ERRORS that hurt AP scores:',
      '  Using passé composé where imparfait needed (or vice versa).',
      '  Indicative where subjunctive triggered.',
      '  Wrong auxiliary (avoir vs être).',
      '  Wrong pronoun order.',
      '  Adjective agreement (especially feminine -e + plural -s).',
    ], vocabulary: [{ term: 'subjonctif', definition: 'French verb mood for wishes, doubt, emotion, necessity; triggered by specific verbs and conjunctions.' }, { term: 'DR + MRS VANDERTRAMP', definition: 'mnemonic for verbs that take ÊTRE auxiliary in passé composé (verbs of motion + state change).' }], estimatedMinutes: 5 },
    { id: 'worked', kind: 'worked_example', problem: 'Translate: "I want you to come early so we can talk before the meeting begins."', steps: [
      '"I want you to come" → "Vouloir que" + subjonctif. "Je veux que tu viennes."',
      '"early" → "tôt".',
      '"so we can talk" → "pour que nous puissions parler" (pour que + subjonctif).',
      '"before the meeting begins" → "avant que la réunion (ne) commence" (avant que + subjonctif; optional ne expletive).',
      'Full: "Je veux que tu viennes tôt pour que nous puissions parler avant que la réunion (ne) commence."',
    ], answer: 'Je veux que tu viennes tôt pour que nous puissions parler avant que la réunion commence.', estimatedMinutes: 4 },
    { id: 'try-1', kind: 'try_yourself', problem: 'Choose passé composé or imparfait: "Quand j\'(arriver), il (pleuvoir)."', expectedAnswer: 'Quand j\'ai ARRIVÉ → wrong! Arriver takes ÊTRE: "Quand je SUIS ARRIVÉ(E)" (with subject agreement). "Il pleuvait" — the rain was ONGOING when I arrived (background), so IMPARFAIT. Full: "Quand je suis arrivé(e), il pleuvait."', responseFormat: 'free', hints: ['"Arriver" takes which auxiliary?', 'Was the rain a completed action or ongoing background?'], estimatedMinutes: 3 },
    { id: 'misconception-aller-avoir', kind: 'misconception_check', question: 'A student writes "J\'ai allé au cinéma." What\'s wrong?', commonErrors: [{ answer: 'J\'ai allé', misconception: 'Defaulting to AVOIR for all verbs in passé composé.', correctsTo: 'ALLER takes ÊTRE (one of the DR+MRS VANDERTRAMP verbs of motion). Correct: "Je suis allé(e) au cinéma." With ÊTRE, the past participle ALSO agrees with subject — "allée" if subject is feminine. Memorise the ÊTRE-list of motion verbs and the agreement rule.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Passé composé: completed past. Imparfait: ongoing/habitual.', 'DR+MRS VANDERTRAMP verbs take ÊTRE; participle agrees with subject.', 'Subjonctif triggers: vouloir que, douter que, il faut que, pour que, avant que.', 'Pronoun order: me/te/se/nous/vous + le/la/les + lui/leur + y + en.', 'Adjective + participle agreement (gender + number).'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
