/**
 * AP Psychology — CED Unit 1.4: The Brain.
 * Specialization.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_PSYCH_U1_BRAIN_STRUCTURES: LessonPlan = {
  id: 'evelyn.ap.psych.brain-structures.v1', title: 'U1.4 The Brain',
  curriculum: 'AP', grade: '11', subject: 'ss', topic: 'ap-psychology', locale: 'en',
  los: [{ id: 'appsych.brain-structures', description: 'Identify major brain structures (hindbrain, midbrain, forebrain) and their functions. Identify the four cortical lobes. Distinguish left vs. right hemisphere specialization. Understand brain plasticity and lesion studies.', standard: 'AP-PSYCH-1.4' }],
  prerequisites: ['appsych.neurons-neurotransmitters'], followUps: ['appsych.nervous-endocrine'], estimatedMinutes: 22,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame the brain as functionally specialized.', script: "Your brain isn\'t one undifferentiated soup. SPECIFIC areas do SPECIFIC jobs. We know this because: when these areas get damaged, predictable abilities are lost. The famous Phineas Gage and patient HM cases revealed brain specialization.", estimatedMinutes: 2 },
    { id: 'concept-brain', kind: 'concept', goal: 'Cover brain regions + lobes + hemispheres + plasticity.',
      keyIdeas: [
        'BRAIN ORGANIZATION (3 main regions, oldest to newest evolutionarily):',
        '',
        'HINDBRAIN (life support):',
        '  • MEDULLA: heartbeat, breathing, blood pressure. Damage = death.',
        '  • PONS: sleep, arousal, facial expressions, breathing rhythm.',
        '  • CEREBELLUM: balance, coordination, MOTOR LEARNING (riding bike, typing). "Little brain."',
        '',
        'MIDBRAIN:',
        '  • RETICULAR FORMATION (reticular activating system): arousal, alertness, sleep-wake cycle.',
        '  • Substantia nigra: dopamine production; degenerates in Parkinson\'s.',
        '',
        'FOREBRAIN (most complex):',
        '  • THALAMUS: SENSORY RELAY station (all senses except smell pass through). "Switchboard."',
        '  • HYPOTHALAMUS: HUNGER, thirst, body temperature, sex drive, autonomic nervous system. Controls pituitary gland.',
        '  • LIMBIC SYSTEM (emotion + memory):',
        '    - HIPPOCAMPUS: forms NEW MEMORIES. Damage = anterograde amnesia (cannot form new memories). Patient HM lost his hippocampus and could not remember anything new for the rest of his life.',
        '    - AMYGDALA: FEAR and aggression. Damage may produce fearless monkeys, lions.',
        '  • CEREBRUM: CORTEX (gray matter on outside, white matter inside).',
        '',
        'CEREBRAL CORTEX — divided into 4 LOBES per hemisphere (8 total):',
        '  • FRONTAL LOBE: planning, judgment, personality, motor control. Contains MOTOR CORTEX (primary motor strip — homunculus map). BROCA\'S AREA (left frontal): speech production. Damage to left frontal → trouble speaking. Phineas Gage: railroad spike through frontal lobe → personality changed dramatically.',
        '  • PARIETAL LOBE: TOUCH/sensation, spatial awareness. Contains SOMATOSENSORY CORTEX (sensory strip). Damage may cause hemispatial neglect.',
        '  • TEMPORAL LOBE: HEARING, language comprehension. WERNICKE\'S AREA (left temporal): language understanding. Damage → fluent but meaningless speech.',
        '  • OCCIPITAL LOBE: VISION. Contains primary VISUAL cortex. Damage → blindness despite eyes being OK.',
        '',
        'HEMISPHERIC SPECIALIZATION:',
        '  • LEFT HEMISPHERE: language, math, logic, analytical thinking. Controls RIGHT side of body.',
        '  • RIGHT HEMISPHERE: spatial, music, faces, holistic processing. Controls LEFT side of body.',
        '  • CORPUS CALLOSUM: thick band of fibers connecting two hemispheres.',
        '  • SPLIT-BRAIN PATIENTS (Roger Sperry\'s research): corpus callosum severed (epilepsy treatment). Each hemisphere processes its own side independently. Famous: object shown to right hemisphere → patient cannot NAME it (language is in left) but can pick it up with left hand (right hemisphere control).',
        '',
        'BRAIN PLASTICITY: ability to reorganize and form new neural connections.',
        '  • Most pronounced in young brains (infants); persists into adulthood.',
        '  • After stroke: surrounding tissue may take over functions of damaged areas.',
        '  • Long-term learning physically rewires the brain.',
        '  • NEUROGENESIS: new neurons form in some areas (hippocampus) throughout life.',
        '',
        'NEUROIMAGING:',
        '  • EEG: brain electrical activity (good time, poor space).',
        '  • CT/MRI: brain structure.',
        '  • fMRI: brain activity by tracking blood flow (good space, poor time).',
        '  • PET: tracks radioactive glucose to identify active regions.',
      ],
      vocabulary: [
        { term: 'hippocampus', definition: 'limbic structure for forming new memories.' },
        { term: 'amygdala', definition: 'limbic structure for fear and aggression.' },
        { term: 'corpus callosum', definition: 'fibers connecting left and right hemispheres.' },
        { term: 'plasticity', definition: 'brain\'s ability to reorganize and form new connections.' },
      ],
      estimatedMinutes: 8 },
    { id: 'worked-localize', kind: 'worked_example',
      problem: 'A stroke damages a patient\'s left frontal lobe near Broca\'s area. Predict their symptoms.',
      steps: [
        'STEP 1 — BROCA\'S AREA = left frontal lobe, controls speech production.',
        'STEP 2 — Damage to left side of brain affects RIGHT side of body (motor control crosses).',
        'STEP 3 — Predicted symptoms:\n  • DIFFICULTY SPEAKING (Broca\'s aphasia): patient understands speech, knows what they want to say, but can\'t produce fluent words. Speech is halting, telegraphic.\n  • RIGHT-side weakness/paralysis (frontal lobe motor cortex damage).\n  • Possibly difficulty with planning, judgment (frontal lobe broader functions).',
        'STEP 4 — UNDERSTANDING is intact (Wernicke\'s area is left TEMPORAL, may be unaffected).',
        'STEP 5 — Recovery via plasticity: surrounding tissue and right-hemisphere areas may gradually take over some functions over months.',
      ],
      answer: 'Broca\'s aphasia (production), right-side weakness, intact comprehension.', estimatedMinutes: 4 },
    { id: 'try-localize', kind: 'try_yourself',
      problem: 'For each scenario, identify the most likely damaged brain region: (a) Patient cannot form new memories but recalls childhood. (b) Patient is highly emotional, fearful, easily startled. (c) Patient walks unsteadily, can\'t coordinate hand movements. (d) Patient is blind even though eyes are healthy.',
      expectedAnswer: '(a) HIPPOCAMPUS — anterograde amnesia (cannot form new memories), past memories preserved. \n(b) AMYGDALA (potentially overactive, or related limbic region damage). Or hyperexcitable amygdala. \n(c) CEREBELLUM — coordination, balance. \n(d) OCCIPITAL LOBE (visual cortex) — cortical blindness despite intact eyes/optic nerves.',
      responseFormat: 'free', hints: ['Match symptom to specialized region.'], estimatedMinutes: 3 },
    { id: 'try-split-brain', kind: 'try_yourself',
      problem: 'A split-brain patient has their corpus callosum severed. They are shown the word "DOG" only to their LEFT visual field (right hemisphere). What can they do?',
      expectedAnswer: 'Left visual field input goes to RIGHT hemisphere. Right hemisphere recognizes the word but CANNOT name it (language is in LEFT hemisphere, which has no information about what was shown). \nSo: \n• Patient CANNOT VERBALLY NAME "dog" — left hemisphere doesn\'t know. \n• Patient CAN POINT to a dog with their LEFT HAND (controlled by right hemisphere). \n• Patient CAN draw a dog with the LEFT HAND. \n• If you ask "what did you see?" — patient says "nothing" (because the talking left hemisphere doesn\'t know). \nThis revealed that hemispheres process information independently when not connected.',
      responseFormat: 'free', hints: ['Visual field crosses; language is left; left hand = right hem.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. (a) Phineas Gage survived a railroad spike through his FRONTAL LOBE in 1848. He recovered physically but his personality dramatically changed (became impulsive, profane, unable to plan). What does this tell us about frontal lobe function? (b) Patient HM had his hippocampus removed in 1953 to treat severe epilepsy. He could remember his childhood and the surgery, but couldn\'t form new memories afterward — for the next 55 years. What does this tell us about memory? (c) Identify ONE brain area whose function we know primarily from lesion studies of damaged patients.',
      expectedAnswer: '(a) PHINEAS GAGE: frontal lobe is essential for: \n• PERSONALITY and emotional regulation. \n• PLANNING and judgment (executive function). \n• IMPULSE CONTROL. \n• Social appropriateness (he became profane, unprofessional). \nThe injury revealed that personality and rationality aren\'t evenly distributed — they\'re heavily concentrated in the frontal cortex. (2)\n(b) PATIENT HM: \n• HIPPOCAMPUS is critical for FORMING NEW EXPLICIT MEMORIES (declarative). \n• Memories of past events were stored elsewhere — those weren\'t lost. \n• PROCEDURAL memory (riding a bike, typing) is also intact (different system). \n• Implicit/explicit memory dichotomy: hippocampus → explicit; cerebellum/basal ganglia → procedural. \n• HM could learn new motor skills (better at puzzles over days) but couldn\'t REMEMBER having done them. (2)\n(c) Brain areas known from lesion studies:\n• BROCA\'S AREA (Pierre Paul Broca\'s 1861 patient "Tan" — only word he could say). \n• WERNICKE\'S AREA. \n• Hippocampus. \n• Amygdala. \n• Frontal lobe (Gage and many others). \n• Visual cortex (cortical blindness from occipital damage). \nMany of these were known LONG before brain imaging. Lesion studies remain valuable today. (1.5)\nTotal: 5.5 points.',
      responseFormat: 'frq', hints: ['Iconic cases revealed function via dysfunction.'], estimatedMinutes: 5 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Hindbrain: medulla (autonomic), pons (sleep), cerebellum (coord/motor learning).',
      'Forebrain: thalamus (relay), hypothalamus (drive), limbic (hippocampus = memory; amygdala = fear).',
      'Cortex: frontal (planning/Broca/motor), parietal (touch), temporal (hearing/Wernicke), occipital (vision).',
      'Left = language, math, logic. Right = spatial, faces, music. Connected by corpus callosum.',
      'Brain shows plasticity; damaged areas can be partially compensated.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '1', cedTopic: '1.4', cedTitle: 'The Brain', sources: [{ type: 'concept', book: 'feldman', chapter: '2', note: 'Standard brain structures.' }] },
};
