/**
 * AP Spanish Language — Grammar and Verb System.
 */

import type { LessonPlan } from '../types';

export const SEED_AP_SPANISH_LANG_GRAMMAR: LessonPlan = {
  id: 'evelyn.ap.spanish-lang.grammar.v1',
  title: 'AP Spanish Language — Verb System and Grammar',
  curriculum: 'AP',
  grade: '11',
  subject: 'languages',
  topic: 'ap-spanish-lang',
  locale: 'en',
  los: [{ id: 'ap.spanish-lang.grammar', description: 'Master Spanish verb tenses, mood (subjunctive vs indicative), and ser-vs-estar distinction at AP-language level.', standard: 'AP-SPAN-LANG' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 16,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'AP Spanish Lang demands fluency with the FULL verb system + the ser/estar + subjunctive distinctions.', script: 'AP graders look for varied tenses, correct subjunctive use, and proper ser vs estar choices. These are also the most common error categories. Today: the structures + the high-yield rules.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Tenses, ser vs estar, subjunctive triggers, common errors.', keyIdeas: [
      'KEY VERB TENSES (memorise + USE in writing):',
      '  PRESENTE: routine, present truth.',
      '  PRETÉRITO: completed past actions ("Compré el libro ayer").',
      '  IMPERFECTO: ongoing or habitual past ("Iba a la escuela todos los días").',
      '  FUTURO: future ("Iré mañana"). Also expresses probability about present ("Serán las 3").',
      '  CONDICIONAL: would-action ("Iría si pudiera"). Also probability about past.',
      '  PRESENTE PERFECTO: completed action with relevance to present (with HABER + past participle).',
      '  PLUSCUAMPERFECTO: had-done (HABÍA + part.).',
      '  SUBJUNCTIVE forms (presente, imperfecto, perfecto subjuntivo).',
      'PRETÉRITO vs IMPERFECTO:',
      '  Pretérito: completed action with clear endpoint.',
      '  Imperfecto: background, ongoing state, repeated past habit.',
      '  Often together: "Estaba leyendo (imp) cuando sonó (pret) el teléfono" — background interrupted by event.',
      'SER vs ESTAR (both = "to be"):',
      '  SER: identity, profession, origin, time, possession, characteristics (permanent traits).',
      '    "Soy profesor." "Es de Madrid." "Es alto."',
      '  ESTAR: location, mood, ongoing condition, progressive tense.',
      '    "Estoy aquí." "Está enfermo." "Está estudiando."',
      '  Same adjective, different meaning: "Es aburrido" (he\'s a boring person) vs "Está aburrido" (he\'s feeling bored right now).',
      'SUBJUNCTIVE (mode for uncertainty/desire/emotion):',
      '  Triggers (memorise — WEIRDO):',
      '  W — Wishes (querer que, desear que): "Quiero que vengas."',
      '  E — Emotions (alegrarse de que, temer que): "Me alegro de que estés aquí."',
      '  I — Impersonal expressions (es necesario que, es importante que): "Es importante que estudies."',
      '  R — Recommendations (recomendar que, sugerir que).',
      '  D — Doubt/Denial (dudar que, no creer que): "Dudo que sea verdad."',
      '  O — Ojalá (I wish/hope): "Ojalá llueva."',
      '  Also: future-uncertain time clauses (cuando, antes de que, hasta que + acción no realizada).',
      'COMMON ERRORS that hurt AP scores:',
      '  Using indicative where subjunctive required after WEIRDO triggers.',
      '  Confusing pretérito + imperfecto.',
      '  Picking ser when estar is needed (location, condition).',
      '  GENDER agreement on adjectives + articles.',
      '  Por vs para (purpose, duration, motion).',
    ], vocabulary: [{ term: 'subjunctive mode', definition: 'verb form expressing wishes, doubt, emotion, or uncertainty; required after specific triggers in Spanish.' }, { term: 'WEIRDO triggers', definition: 'mnemonic for subjunctive triggers: Wishes, Emotions, Impersonal expressions, Recommendations, Doubt/Denial, Ojalá.' }], estimatedMinutes: 5 },
    { id: 'worked', kind: 'worked_example', problem: 'Translate: "It is important that you study every day, because I want you to pass the exam." Use AP-level grammar.', steps: [
      '"It is important that..." → impersonal expression triggers SUBJUNCTIVE: "Es importante que..."',
      '"you study" → estudies (presente subjunctive 2nd person sing).',
      'Continuing: "Es importante que estudies cada día, porque quiero que apruebes el examen."',
      'Note: "quiero que" → triggers subjunctive (desire). "Apruebes" is presente subjunctive.',
      'Both subjunctive triggers — appropriate at AP level.',
    ], answer: 'Es importante que estudies cada día, porque quiero que apruebes el examen.', estimatedMinutes: 4 },
    { id: 'try-1', kind: 'try_yourself', problem: 'Choose: "Mi profesora ____ (ser/estar) muy aburrida hoy."', expectedAnswer: 'ESTÁ. The sentence says "today" — referring to a temporary mood/condition. ESTAR for current state. ("Es aburrida" would mean she IS a boring person — different meaning.)', responseFormat: 'free', hints: ['Today = current/temporary condition.', 'Same word, different meaning depending on ser vs estar.'], estimatedMinutes: 2 },
    { id: 'misconception-subjunctive-when', kind: 'misconception_check', question: 'A student writes "Cuando llega, vamos a comer" intending to mean "When he arrives, we\'ll eat" (future). What\'s the error?', commonErrors: [{ answer: 'Indicative after future cuando', misconception: 'Forgetting that future-uncertain time clauses trigger subjunctive.', correctsTo: 'When the cuando-clause refers to a FUTURE EVENT NOT YET REALIZED, Spanish requires SUBJUNCTIVE: "Cuando LLEGUE, vamos a comer." (Llegue = presente subjunctive of llegar.) The error of using indicative llega makes it sound habitual ("when he arrives [as a routine pattern]"). For future single events: subjunctive. For habitual present: indicative ("Cuando llega temprano, comemos juntos" — when he arrives early as a pattern).' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Pretérito = completed; imperfecto = ongoing/habitual.', 'Ser = essence; estar = state.', 'Subjunctive triggers: WEIRDO + future time clauses.', 'Adjective gender + number agreement.', 'AP graders reward varied tense + correct subjunctive.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
