/**
 * AP Test Strategy — Free-Response Question (FRQ) Approach.
 */

import type { LessonPlan } from '../types';

export const SEED_AP_TEST_STRATEGY_FRQ: LessonPlan = {
  id: 'evelyn.ap.test-strategy.frq.v1',
  title: 'AP Exam Strategy — FRQ Approach Across Subjects',
  curriculum: 'AP',
  grade: '11',
  subject: 'test-prep',
  topic: 'ap-test-strategy',
  locale: 'en',
  los: [{ id: 'ap.test-strategy.frq', description: 'Apply structural FRQ strategy: address every part, allocate time, show work, label clearly across AP subjects.', standard: 'AP-EXAM-STRATEGY' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 16,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'AP graders see thousands of FRQs — the ones that score 4-5s share habits independent of subject.', script: 'Whether it\'s AP Bio, AP Calc, or AP US History, the FRQ is structured: prompt → multiple parts → time pressure. The students who max out their score have habits we can drill.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Structural patterns, time allocation, scoring, common errors.', keyIdeas: [
      'ANSWER EVERY SUB-PART. FRQs are usually labeled (a), (b), (c), etc. ANSWER ALL OF THEM, even if briefly.',
      '  Skipping = guaranteed zero on that part.',
      '  A weak answer on a part still scores partial credit.',
      'ALLOCATE TIME proportionally to point value.',
      '  AP Calc: 6 FRQs in 90 min ≈ 15 min each.',
      '  AP US Hist: 3 SAQs (40 min) + 1 LEQ (40 min) + 1 DBQ (60 min).',
      '  AP Bio: 6 FRQs in 90 min, complex weighting.',
      '  CHECK YOUR CLOCK regularly. If you\'re behind, skip subparts to keep pace.',
      'SHOW YOUR WORK ALWAYS:',
      '  STEM and math FRQs: write the equation/setup BEFORE numbers.',
      '  Even if calculator-allowed, write the integral/derivative/equation explicitly.',
      '  Method marks add up — even if the final number is wrong.',
      'LABEL parts clearly. Write "(a)", "(b)", etc. before each section.',
      '  Graders score by part — clarity helps them give you credit.',
      'USE THE PROMPT\'S LANGUAGE.',
      '  If the prompt says "DESCRIBE", describe (factual account). Don\'t evaluate.',
      '  If "EXPLAIN", give mechanism / reason.',
      '  If "JUSTIFY", show why your answer must be correct.',
      'FOR ESSAYS (history, English):',
      '  THESIS as the FIRST SENTENCE of the intro.',
      '  Each body paragraph: ONE claim → evidence → analysis.',
      '  Don\'t hedge. Take a position even on "to what extent" prompts.',
      'FOR PROBLEM-SOLVING (math, science):',
      '  Step 1: identify what\'s asked.',
      '  Step 2: identify given values + units.',
      '  Step 3: choose equation/relationship + write it down.',
      '  Step 4: substitute + solve.',
      '  Step 5: state answer with units. Reasonable check.',
      'COMMON SCORING TRAPS:',
      '  Wrong UNITS in scientific answers (1 point loss is common).',
      '  Failing to JUSTIFY when prompted.',
      '  Skipping a sub-part (zero on that part).',
      '  Going off-topic in essays.',
      'IF STUCK: write SOMETHING relevant — even partial credit beats zero. Move on; return if time permits.',
      'PARTIAL CREDIT: AP graders are TRAINED to find what students did right. Show enough so they can find it.',
    ], vocabulary: [{ term: 'FRQ', definition: 'free-response question; the constructed-response section of an AP exam, scored 0 to a max (typically 4-9 points per question).' }], estimatedMinutes: 5 },
    { id: 'worked', kind: 'worked_example', problem: 'You\'re on AP Bio FRQ. With 5 minutes left, you have 2 unanswered subparts (3 points each) and 1 partially answered. What\'s the best strategy?', steps: [
      'Total at stake: 3 + 3 + (some) ≈ 8 points.',
      'Strategy: TRIAGE. Glance at each unanswered subpart. Pick the one you can answer FASTEST with HIGH confidence.',
      'Spend 1-2 minutes writing a short, focused answer to that subpart. Aim for 3 points.',
      'Spend 1-2 min on the next subpart — even a partial answer is worth ~1-2 points.',
      'Final 1 min: glance at the partially-answered question and add ANY relevant fact you missed.',
      'NEVER spend all 5 min on one subpart at the cost of leaving others blank. 5+5 partial > 9 + 0.',
    ], answer: 'Triage by speed × points; brief answers to multiple subparts > deep answer to one.', estimatedMinutes: 4 },
    { id: 'try-1', kind: 'try_yourself', problem: 'On AP Calc, why is "show the integral set up" worth doing even if you can\'t solve it?', expectedAnswer: 'Method marks. AP Calc gives points for the SETUP (correct integral expression) separately from the EVALUATION. A correctly set up integral with no numerical answer often scores 1-2 of 3 points. Skipping leaves zero. Even if the integration is beyond you, write the integral. The graders are trained to award setup credit.', responseFormat: 'free', hints: ['What does "method marks" mean?', 'Setup vs evaluation as separate scoring elements.'], estimatedMinutes: 2 },
    { id: 'misconception-perfect-or-nothing', kind: 'misconception_check', question: 'A student leaves a sub-part blank because they "don\'t know the perfect answer." Why is this strategically wrong?', commonErrors: [{ answer: 'Perfect or blank', misconception: 'Treating partial credit as not real.', correctsTo: 'AP exams give substantial PARTIAL CREDIT. Writing ANYTHING relevant beats blank. A 1-of-4 score on a sub-part is much better than 0/4. Across 6 FRQs and dozens of sub-parts, "I don\'t know the perfect answer so I\'ll skip" can cost 10+ points — easily the difference between a 4 and a 5. The discipline: write something for every sub-part, even if you\'re unsure. Graders are trained to award what is correct.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Answer EVERY sub-part. Skipping = zero.', 'Show work + setup, even when calc allowed.', 'Match command term: describe, explain, justify, evaluate.', 'Triage by points × speed.', 'Partial credit > nothing. Write SOMETHING.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
