/**
 * AP Test Strategy — Multiple-Choice Approach.
 */

import type { LessonPlan } from '../types';

export const SEED_AP_TEST_STRATEGY_MCQ: LessonPlan = {
  id: 'evelyn.ap.test-strategy.mcq.v1',
  title: 'AP Exam Strategy — Multiple-Choice Approach',
  curriculum: 'AP',
  grade: '11',
  subject: 'test-prep',
  topic: 'ap-test-strategy',
  locale: 'en',
  los: [{ id: 'ap.test-strategy.mcq', description: 'Drill MCQ strategy: pacing, elimination, guessing math, common trap patterns across AP subjects.', standard: 'AP-EXAM-STRATEGY' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 14,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'MCQ pacing decides cutoffs across AP subjects — and the right elimination habits add 3-8 raw points easily.', script: 'AP Calc MC: 45 min for 30 q. AP US Hist MC: 55 min for 55 q. AP Bio MC: 90 min for 60 q. Different subjects, similar problem: pace + elimination + educated guessing.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Pacing, elimination, guessing math, trap patterns.', keyIdeas: [
      'NO PENALTY for wrong answers in modern AP MCQ (since 2011). Always GUESS.',
      'PACING is the limiting factor. Calculate time per question:',
      '  AP Calc AB: 45 min / 30 q = 1.5 min/q. Slower for FR-style q.',
      '  AP US Hist: 55 min / 55 q = 60 sec/q.',
      '  AP Bio: 90 min / 60 q = 1.5 min/q.',
      'TWO-PASS strategy:',
      '  First pass: answer EASY questions immediately. MARK harder ones for return.',
      '  Second pass: tackle marked questions with whatever time remains.',
      '  Final: ENSURE every question has SOMETHING bubbled (no penalty).',
      'ELIMINATION:',
      '  Cross out OBVIOUSLY wrong options (often 2 of 4).',
      '  Of remaining, look for distinguishing features.',
      '  EXTREME LANGUAGE often wrong on inference / interpretation: "always", "never", "all".',
      '  TWO OPPOSITES — usually one is right and one is the wrong-direction trap.',
      '  RECOGNISE TRAPS in your subject:',
      '    AP Bio: "memorise" answers vs "explain mechanism" — pick mechanism.',
      '    AP Calc: arithmetic vs interpretation — interpretation is right answer if both work.',
      '    AP Hist: "the cause" oversimplifies — pick option naming MULTIPLE causes.',
      'GUESSING math (no penalty):',
      '  Eliminate 0: random guess = 1/4 chance × correct value.',
      '  Eliminate 1: 1/3 chance.',
      '  Eliminate 2: 1/2 chance — strongly worth guessing.',
      '  Eliminate 3: certainty (1/1).',
      '  Always guess on every blank — modern AP rewards it.',
      'WHEN STUCK on a question for > 2x target time:',
      '  Pick BEST GUESS, mark it, move on.',
      '  Spending 5 min on one question costs you the chance at 3 easier ones.',
      'COMMON TRAP PATTERNS:',
      '  "ALL OF THE ABOVE": often correct when present. Often missing → look at incompleteness.',
      '  "NONE OF THE ABOVE": often wrong (test writers prefer specific answers).',
      '  Two answers SUPER similar: usually one is the trap, one is right.',
      '  Negation in stem: "Which is NOT...?" — slow down and re-read.',
      'OMR DISCIPLINE: bubble as you go. Don\'t batch at end (running out of time AND bubbles missed = catastrophe).',
    ], vocabulary: [{ term: 'two-pass strategy', definition: 'first pass answers easy questions; second pass handles marked harder ones with remaining time.' }], estimatedMinutes: 5 },
    { id: 'worked', kind: 'worked_example', problem: 'AP Bio: "Which is NOT a cause of the increase in atmospheric CO₂ over the past 200 years?" (a) Burning fossil fuels (b) Deforestation (c) Industrial agriculture (d) Volcanic activity.', steps: [
      'Watch for NEGATION: "NOT a cause." Easy to misread.',
      'Eliminate options that ARE causes (the question wants the one that ISN\'T).',
      '(a) Fossil fuels: definitely CAUSE. Eliminate.',
      '(b) Deforestation: yes, reduces CO₂ uptake AND releases stored carbon. Eliminate.',
      '(c) Industrial agriculture: nitrous oxide + methane more, but some CO₂. Borderline.',
      '(d) Volcanic activity: emits CO₂ but at much LOWER rate than human sources. Across 200 years, contributes much less than fossil fuels.',
      'The "NOT" answer is the option that is NOT a major cause: (d) volcanic activity (background-level natural source).',
      'Lesson: NEGATION questions need slow re-reads.',
    ], answer: '(d) volcanic activity — natural background source, much smaller than human industrial sources.', estimatedMinutes: 3 },
    { id: 'try-1', kind: 'try_yourself', problem: 'On AP exams, you have time for 50 questions but encounter 60. What should you do?', expectedAnswer: 'Pace through the 50 you have time for, doing them with high accuracy. For the remaining 10, GUESS (no penalty in modern AP). Eliminate any obvious wrong options before guessing — eliminate 1 → 33% correct rate (~3 right), eliminate 2 → 50% (~5 right). Either way, guessing beats blanks (which are guaranteed zero). Plan: ~7 min reserved at the end for guessing if you\'re running short.', responseFormat: 'free', hints: ['No penalty for wrong = always guess.', 'Eliminate options before guessing for higher EV.'], estimatedMinutes: 3 },
    { id: 'misconception-no-guess', kind: 'misconception_check', question: 'A student doesn\'t guess on AP MCQ because they "don\'t want to risk a wrong answer." Why is this strategy losing points?', commonErrors: [{ answer: 'No guessing', misconception: 'Treating modern AP scoring as if there\'s a penalty.', correctsTo: 'Modern AP exams (since 2011) have NO PENALTY for wrong MCQ answers. Blank = guaranteed 0. Random guess = 25% expected value (1/4 × 1 = 0.25). Educated guess (eliminate 1-2) = 33-50%. Across 60 questions where 5-10 are blank because of "no guessing," that\'s 1-3 points lost. Often enough to drop a 4 to a 3. The discipline: bubble SOMETHING for every question. The exam rewards it.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['No penalty in modern AP — always guess.', 'Two-pass strategy: easy first, hard second.', 'Eliminate before guessing for higher EV.', 'Watch for NEGATION ("NOT") in question stems.', 'Bubble as you go — don\'t batch.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
