/**
 * IB Physics — Mechanics Topic.
 */

import type { LessonPlan } from '../types';

export const SEED_IB_PHYSICS_MECHANICS: LessonPlan = {
  id: 'evelyn.ibdp.physics.mechanics.v1',
  title: 'IB Physics — Mechanics (Topic 2)',
  curriculum: 'IB-DP',
  grade: '11-12',
  subject: 'science',
  topic: 'ib-physics',
  locale: 'en',
  los: [{ id: 'ibdp.physics.mechanics', description: 'Apply IB Topic 2: Newton\'s laws, kinematics, energy, momentum, with IB-style modelling.', standard: 'IB-DP-PHYS-2' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'IB Phys Topic 2 (Mechanics) is foundational and tested in BOTH papers.', script: 'Kinematics, Newton, energy, momentum. IB rewards CLEAR diagrams + EXPLICIT equations BEFORE numbers. Today the workflow.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Kinematics, Newton, energy, momentum, IB modelling.', keyIdeas: [
      'KINEMATIC equations (constant acceleration):',
      '  v = u + at',
      '  s = ut + (1/2)at²',
      '  v² = u² + 2as',
      '  s = (u + v)t / 2',
      'PROJECTILE motion: decompose into independent x (no a) and y (a = -g) motions.',
      'NEWTON\'S LAWS:',
      '  N1: object stays at rest or constant velocity unless net force.',
      '  N2: F = ma. Net force gives acceleration.',
      '  N3: action and reaction equal + opposite.',
      'FREE-BODY DIAGRAM: identify all forces (gravity, normal, friction, tension, applied). Sum vectorially.',
      'WORK-ENERGY: W_net = ΔKE = (1/2)mv² − (1/2)mv₀².',
      'CONSERVATION OF ENERGY: KE + PE constant when no friction.',
      '  PE_grav = mgh.',
      '  PE_spring = (1/2)kx².',
      'POWER: P = W/t = Fv.',
      'MOMENTUM: p = mv. Conservation: total p constant when no external force.',
      'IMPULSE: J = FΔt = Δp.',
      'COLLISIONS:',
      '  ELASTIC: KE and momentum BOTH conserved.',
      '  INELASTIC: only momentum conserved.',
      '  PERFECTLY INELASTIC: stick together; momentum conserved.',
      'CIRCULAR MOTION: a_c = v²/r toward center. F_c = mv²/r.',
      'GRAVITATION: F = GMm/r². Orbital velocity: v = √(GM/r).',
      'IB COMMAND TERMS for mechanics:',
      '  STATE (one word answer).',
      '  DESCRIBE (factual account).',
      '  EXPLAIN (give mechanism / reason).',
      '  CALCULATE / DETERMINE (numerical with units).',
      '  SHOW THAT (derive from premises).',
      'IB writing style: ALWAYS write the equation BEFORE substituting numbers; this earns method marks even if arithmetic slips.',
    ], vocabulary: [{ term: 'free-body diagram', definition: 'a diagram showing all forces on a single object as labeled vectors; the starting point of every Newton problem.' }, { term: 'impulse-momentum theorem', definition: 'F·Δt = Δp; impulse equals change in momentum.' }], estimatedMinutes: 6 },
    { id: 'worked', kind: 'worked_example', problem: 'A 5 kg block on a frictionless inclined plane at 30° is released from rest. Find its acceleration and speed after sliding 10 m.', steps: [
      'Draw free-body: gravity mg downward, normal N perpendicular to incline.',
      'Decompose gravity along incline (mg sin θ) and perpendicular (mg cos θ).',
      'Net force ALONG incline = mg sin θ (perpendicular components balance).',
      'Acceleration a = g sin θ = 9.8 × sin(30°) = 9.8 × 0.5 = 4.9 m/s².',
      'Speed after 10 m: v² = u² + 2as = 0 + 2(4.9)(10) = 98. v = √98 ≈ 9.9 m/s.',
      'Method marks: free-body diagram, decomposition, equation BEFORE substitution.',
    ], answer: 'a = 4.9 m/s², v ≈ 9.9 m/s', estimatedMinutes: 5 },
    { id: 'try-1', kind: 'try_yourself', problem: 'A 2 kg ball moving at 3 m/s right hits a stationary 1 kg ball. After collision, the 2 kg ball moves at 1 m/s right. What\'s the velocity of the 1 kg ball?', expectedAnswer: 'Conservation of momentum: m₁v₁ + m₂v₂ = m₁v₁\' + m₂v₂\'. (2)(3) + (1)(0) = (2)(1) + (1)v₂\'. 6 = 2 + v₂\'. v₂\' = 4 m/s right.', responseFormat: 'numeric', hints: ['Use momentum conservation.', 'Track signs (all moving right here).'], estimatedMinutes: 3 },
    { id: 'misconception-show-that', kind: 'misconception_check', question: 'A "show that" question asks you to derive T = 2π√(L/g). A student writes T = 2π√(L/g), substitutes numbers, and gets a value matching the expected answer. Why score zero?', commonErrors: [{ answer: 'Numerical verification', misconception: 'Treating "show that" as "verify."', correctsTo: 'SHOW THAT requires DERIVATION step-by-step from premises. For T = 2π√(L/g) of simple pendulum: start from F = -mg sinθ ≈ -mgθ for small θ, write SHM equation m(d²x/dt²) = -mgθ with x = Lθ, recognise SHM ω² = g/L, use T = 2π/ω. The marks live in EACH STEP. Numerical verification proves nothing about the general formula.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Kinematics: 4 equations (constant a). Decompose 2D into x + y.', 'Newton: F = ma; free-body diagram first.', 'Energy conservation when no friction; momentum always in collisions.', 'Always: equation BEFORE numbers. Units throughout.', '"Show that" needs derivation, not verification.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
