/**
 * JEE Math — Differential and Integral Calculus.
 */

import type { LessonPlan } from '../types';

export const SEED_JEE_MATH_CALCULUS: LessonPlan = {
  id: 'evelyn.jee.math.calculus.v1',
  title: 'JEE Math — Calculus (Differentiation, Integration, Applications)',
  curriculum: 'JEE-MAIN',
  grade: 'iitjee',
  subject: 'test-prep',
  topic: 'jee-math',
  locale: 'en',
  los: [{ id: 'jee.math.calculus', description: 'Drill JEE calculus: limits, differentiation rules, integration techniques, definite integral properties, applications.', standard: 'JEE-MATH-CALCULUS' }],
  prerequisites: ['jee.math.algebra'],
  followUps: [],
  estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Calculus is ~30% of JEE Math — and rewards both formula memorisation and clever substitutions.', script: 'JEE Calc questions split into two halves: differentiation (rules + applications) and integration (techniques + definite integrals + areas). The faster you recognise patterns, the higher your score.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Differentiation rules, integration techniques, applications.', keyIdeas: [
      'LIMITS — standard results to memorise:',
      '  lim_{x→0} sin(x)/x = 1.',
      '  lim_{x→0} (1−cos x)/x² = 1/2.',
      '  lim_{x→0} (eˣ − 1)/x = 1.',
      '  lim_{x→∞} (1 + 1/x)ˣ = e.',
      '  L\'Hôpital: 0/0 or ∞/∞ form? differentiate numerator and denominator.',
      'DIFFERENTIATION rules:',
      '  Power: d/dx(xⁿ) = n·x^(n−1).',
      '  Product: (uv)\' = u\'v + uv\'.',
      '  Quotient: (u/v)\' = (u\'v − uv\')/v².',
      '  Chain: (f(g(x)))\' = f\'(g(x)) · g\'(x).',
      '  Implicit: differentiate both sides w.r.t. x, treating y as a function of x.',
      'APPLICATIONS of derivative:',
      '  TANGENT line at (a, f(a)): y − f(a) = f\'(a)(x − a).',
      '  MAXIMA/MINIMA: critical points where f\' = 0 or undefined. Use 2nd derivative test.',
      '  RATE problems: dy/dt = (dy/dx)(dx/dt).',
      '  ROLLE\'S + MEAN VALUE theorems are JEE staples.',
      'INTEGRATION techniques:',
      '  Substitution: let u = inner function, du = u\'(x)dx.',
      '  By parts: ∫u dv = uv − ∫v du. Mnemonic: ILATE (Inverse-trig, Log, Algebraic, Trig, Exp) for picking u.',
      '  Partial fractions: split rational functions before integrating.',
      '  Trig substitutions: √(a² − x²) → x = a sin θ; √(a² + x²) → x = a tan θ; √(x² − a²) → x = a sec θ.',
      'DEFINITE INTEGRAL properties:',
      '  ∫₀ᵃ f(x)dx = ∫₀ᵃ f(a−x)dx (symmetry).',
      '  ∫₋ₐᵃ f(x)dx = 0 if f is ODD; = 2∫₀ᵃ f(x)dx if EVEN.',
      'APPLICATIONS:',
      '  AREA between curves: ∫(top − bottom)dx.',
      '  VOLUME of revolution: disk/shell methods.',
      '  AVERAGE value of f on [a,b]: (1/(b−a)) ∫ₐᵇ f(x)dx.',
    ], vocabulary: [{ term: 'L\'Hôpital\'s rule', definition: 'for 0/0 or ∞/∞ limits: lim f/g = lim f\'/g\' (if the latter exists).' }, { term: 'integration by parts', definition: '∫u dv = uv − ∫v du; used when integrand is a product.' }], estimatedMinutes: 6 },
    { id: 'worked', kind: 'worked_example', problem: 'Evaluate lim_{x→0} (sin 3x − 3 sin x)/x³ using L\'Hôpital.', steps: [
      'At x = 0: numerator = 0 − 0 = 0, denominator = 0. So 0/0 form.',
      'L\'Hôpital: differentiate top and bottom.',
      'd/dx (sin 3x − 3 sin x) = 3 cos 3x − 3 cos x.',
      'd/dx (x³) = 3x².',
      'New limit: (3 cos 3x − 3 cos x)/(3x²). At x = 0: (3 − 3)/0 = 0/0 again.',
      'Apply L\'Hôpital again. d/dx of numerator: −9 sin 3x + 3 sin x. d/dx of denominator: 6x.',
      'New limit: (−9 sin 3x + 3 sin x)/(6x). Still 0/0.',
      'L\'Hôpital again. d/dx of numerator: −27 cos 3x + 3 cos x. d/dx of denominator: 6.',
      'At x = 0: (−27 + 3)/6 = −24/6 = −4.',
    ], answer: '−4', estimatedMinutes: 5 },
    { id: 'try-1', kind: 'try_yourself', problem: 'Compute ∫ x · eˣ dx.', expectedAnswer: 'Integration by parts. Let u = x, dv = eˣ dx. Then du = dx, v = eˣ. ∫x·eˣ dx = x·eˣ − ∫eˣ dx = x·eˣ − eˣ + C = eˣ(x − 1) + C.', responseFormat: 'free', hints: ['Product of algebraic and exponential — by parts.', 'ILATE: pick u = x (algebraic), dv = eˣ dx.'], estimatedMinutes: 4 },
    { id: 'misconception-chain', kind: 'misconception_check', question: 'A student differentiates sin(x²) and writes cos(x²). What\'s missing?', commonErrors: [{ answer: 'cos(x²)', misconception: 'Forgetting the chain rule when there\'s an inner function.', correctsTo: 'Apply chain rule: derivative of sin(u) is cos(u) · du/dx. Here u = x², so du/dx = 2x. Correct: d/dx[sin(x²)] = cos(x²) · 2x = 2x cos(x²). The "inner derivative" is what the chain rule contributes — easy to forget.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Memorise standard limits + e formula.', 'Chain rule: outer\' × inner\'. Always check for inner functions.', 'Integration by parts: ∫u dv = uv − ∫v du. Use ILATE.', 'Definite integral symmetries — leverage odd/even functions.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
