/**
 * NEET UG — Overall Exam Strategy.
 */

import type { LessonPlan } from '../types';

export const SEED_NEET_UG_STRATEGY: LessonPlan = {
  id: 'evelyn.neet.ug.strategy.v1',
  title: 'NEET UG — Exam Strategy and Time Management',
  curriculum: 'NEET',
  grade: 'medical-entrance',
  subject: 'test-prep',
  topic: 'neet-ug',
  locale: 'en',
  los: [{ id: 'neet.ug.strategy', description: 'Apply NEET-specific time management, section-wise approach, negative-marking strategy, and prep optimisation.', standard: 'NEET-UG' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 16,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'NEET is India\'s gateway to MBBS — and section-wise pacing decides the cutoff.', script: 'NEET UG: 200 questions in 200 minutes. Every wrong answer is −1 mark. The aspirants who clear are not always the smartest — they\'re the ones who pace, skip wisely, and don\'t guess blindly. Today: the strategy.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'NEET format, section breakdown, marking, time strategy, prep cycle.', keyIdeas: [
      'FORMAT (current): 200 questions across 4 subjects + 200 minutes. Pen-paper.',
      '  Physics: 50 questions (35 + 15 in two sections; attempt 50).',
      '  Chemistry: 50.',
      '  Botany (Biology Part 1): 50.',
      '  Zoology (Biology Part 2): 50.',
      '  Total: 200 questions.',
      'MARKING: +4 for correct, −1 for incorrect, 0 for unattempted. Heavy negative marking.',
      'TIME ALLOCATION (200 min for 200 q ≈ 1 min/q):',
      '  Biology (botany + zoology): faster, ~40 sec/q. ~70 min total.',
      '  Chemistry: ~50 sec/q. ~45 min.',
      '  Physics: slowest, ~1 min 30 sec/q. ~70 min.',
      '  Buffer: 15 min for review.',
      'STRATEGY by section:',
      '  BIOLOGY: NCERT-heavy (~95% from NCERT). Fast-paced. Read each question carefully — small word changes (e.g., "all of the following EXCEPT").',
      '  CHEMISTRY: balance of memorisation (organic, inorganic) and calculation (physical). Time the calculations.',
      '  PHYSICS: most calculation-heavy. Skip-and-return aggressively. Don\'t spend > 2 min on first pass.',
      'NEGATIVE-MARKING strategy:',
      '  4 options, expected value of guessing = (1/4)(+4) + (3/4)(−1) = 0.25. Slightly positive — but only if YOU CAN ELIMINATE NONE.',
      '  Eliminate 1: EV = (1/3)(+4) + (2/3)(−1) = +0.67. Worth guessing.',
      '  Eliminate 2: EV = +1.5. Strongly worth.',
      '  Skip if you can\'t eliminate ANY and have NO clue.',
      'PREP CYCLE:',
      '  NCERT FIRST. Read every line, especially Biology.',
      '  Mock tests every week from Year 2.',
      '  Last 60 days: ALL OUT mocks + revision. No new topics.',
      '  Time-bound practice — simulate exam pressure.',
      'CRITICAL: Biology is the difference-maker. ~70-90% of biology questions are direct from NCERT. A 360/360 in Biology is achievable; that score alone qualifies many candidates for MBBS.',
    ], vocabulary: [{ term: 'NEET cutoff', definition: 'minimum marks needed for MBBS admission; varies by category and college.' }], estimatedMinutes: 6 },
    { id: 'worked', kind: 'worked_example', problem: 'On the NEET, you skim a Biology question and can confidently eliminate 1 of 4 options but are unsure between the remaining 3. Should you guess?', steps: [
      'Compute expected value with 1 option eliminated.',
      'Probability of correct guess: 1/3. EV from correct = (1/3)(+4) = +4/3.',
      'Probability of incorrect: 2/3. EV from incorrect = (2/3)(−1) = −2/3.',
      'Total EV = +4/3 − 2/3 = +2/3 ≈ +0.67 marks per question.',
      'CONCLUSION: yes, GUESS. Across many such questions, you\'ll gain about 2/3 mark per guess on average.',
      'Compare to skipping: 0 marks always. Guessing with 1 elimination beats skipping.',
    ], answer: 'YES — guess. Expected value is +0.67 per such question.', estimatedMinutes: 4 },
    { id: 'try-1', kind: 'try_yourself', problem: 'You have 30 minutes left and 25 questions remaining (15 Physics, 10 Biology). What\'s the optimal strategy?', expectedAnswer: 'Allocate by speed: Biology is faster (~40 sec/q × 10 = 7 min). Physics is slow (~1 min 30 × 15 = 22 min). Hits 29 min total — barely fits. Strategy: do BIOLOGY FIRST (faster, higher accuracy). Then race through Physics, prioritising single-step calculations + concept questions. SKIP any Physics question that needs > 2 min. With 30 min and 15 Physics, aim for ~12 attempts at 2 min each + 3 skips. Keep moving.', responseFormat: 'free', hints: ['Speed varies by subject. Pick the fastest first.', 'Skip the longest Physics questions; come back if time.'], estimatedMinutes: 4 },
    { id: 'misconception-skip-everything', kind: 'misconception_check', question: 'A student skips every Physics question they\'re unsure of, attempting only what they know cold. Why does this often hurt their score?', commonErrors: [{ answer: 'Skip every uncertain question', misconception: 'Treating any uncertainty as risk — ignoring expected value.', correctsTo: 'NEET\'s negative marking is designed so educated guessing is positive EV. Eliminate 1 option → +0.67 per question. Eliminate 2 → +1.5. Skipping these throws away marks. The ONLY questions to skip: ones where you genuinely can\'t eliminate ANY option (pure guess). Across 200 questions, the "always guess if you can eliminate one" strategy can add 20-30 marks vs strict no-guess.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['200 q / 200 min. +4/−1. Time biology fastest, physics slowest.', 'Eliminate 1 → guess (+0.67 EV). Eliminate 0 → skip.', 'NCERT is biology bible — ~95% of bio questions there.', 'Mocks weekly from year 2; daily in last 60 days.', 'Bio cracked = NEET cleared.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
