/**
 * SAT R&W — Sentence Structure: Run-ons, Fragments, Parallelism.
 */

import type { LessonPlan } from '../types';

export const SEED_SAT_RW_GRAMMAR_STRUCTURE: LessonPlan = {
  id: 'evelyn.testprep.sat-rw.grammar-structure.v1',
  title: 'SAT R&W — Sentence Structure: Run-ons, Fragments, Parallelism',
  curriculum: 'CCSS',
  grade: 'sat-act',
  subject: 'test-prep',
  topic: 'sat-reading-writing',
  locale: 'en',
  los: [{ id: 'satrw.grammar-structure', description: 'Identify run-ons, fragments, dangling modifiers, parallelism errors on SAT.', standard: 'CCSS.ELA.LANGUAGE' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 14,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Run-ons + fragments + parallelism = ~5 SAT R&W questions per test.', script: 'A complete sentence has subject + verb + complete thought. Anything less = fragment. Anything more (without proper joining) = run-on. Parallelism: items in a list/comparison must match form. Today: drill all four.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Run-ons, fragments, dangling modifiers, parallelism.', keyIdeas: [
      'COMPLETE SENTENCE = subject + verb + complete thought.',
      '  "Birds sing." Subject (Birds), verb (sing). Complete.',
      'FRAGMENT = missing subject, verb, or complete thought.',
      '  "Singing in the trees." (no subject)',
      '  "Although she went home." (subordinate clause; thought incomplete)',
      'RUN-ON = two complete sentences improperly joined.',
      '  COMMA SPLICE: "I love reading, she prefers TV." (comma alone joining two independents — WRONG)',
      '  FUSED: "I love reading she prefers TV." (no punctuation — WRONG)',
      'FIX run-ons by:',
      '  Period: "I love reading. She prefers TV."',
      '  Semicolon: "I love reading; she prefers TV."',
      '  FANBOYS comma: "I love reading, but she prefers TV."',
      '  Subordinator: "While I love reading, she prefers TV." (one becomes dependent)',
      'DANGLING MODIFIER: introductory phrase modifies the wrong subject.',
      '  WRONG: "Walking home, the rain started." (rain wasn\'t walking)',
      '  RIGHT: "Walking home, I noticed the rain start." (I was walking)',
      '  RULE: the subject of the next clause must be what the modifier describes.',
      'MISPLACED MODIFIER: modifier in the wrong position, changing meaning.',
      '  "I almost worked all day." (didn\'t work at all) vs "I worked almost all day." (worked most of day).',
      'PARALLELISM: items in a list, comparison, or pair must have matching grammatical form.',
      '  WRONG: "He likes running, swimming, and to bike."',
      '  RIGHT: "He likes running, swimming, and biking." OR "to run, to swim, and to bike."',
      'COMPARISON parallelism:',
      '  "Her writing is more elegant THAN her speaking." (both gerund)',
      '  "Her style is more like Hemingway\'s THAN Fitzgerald\'s." (both possessive)',
      'CORRELATIVE pairs (both...and, either...or, neither...nor, not only...but also): both sides must match form.',
      '  WRONG: "She not only sings but also plays piano well."',
      '  Better: "She not only sings but also plays piano." (verb forms match)',
    ], vocabulary: [{ term: 'parallelism', definition: 'using the same grammatical form for items in a series, comparison, or correlative pair.' }, { term: 'dangling modifier', definition: 'a modifier that doesn\'t logically connect to the subject of the sentence it introduces.' }], estimatedMinutes: 5 },
    { id: 'worked', kind: 'worked_example', problem: 'Identify and fix the error: "Walking down the street, the building looked enormous."', steps: [
      'Identify the modifier: "Walking down the street."',
      'Identify the subject of the next clause: "the building."',
      'Logical check: was the BUILDING walking? NO.',
      'DANGLING MODIFIER. The modifier should describe a person (the walker), not the building.',
      'FIX 1: "Walking down the street, I saw the enormous building." (subject changed to walker)',
      'FIX 2: "The building looked enormous as I walked down the street." (no opening modifier)',
    ], answer: 'Dangling modifier — fix by changing subject to walker.', estimatedMinutes: 4 },
    { id: 'try-1', kind: 'try_yourself', problem: 'Fix the parallelism error: "She enjoys reading novels, hiking in mountains, and to play chess."', expectedAnswer: 'Items must match form: "reading novels," "hiking in mountains" (both gerund + object), but "to play chess" is infinitive — DOESN\'T MATCH. Fix: "She enjoys reading novels, hiking in mountains, and PLAYING chess." Or: "to read novels, to hike in mountains, and to play chess." All match.', responseFormat: 'free', hints: ['Items in a list need matching grammatical form.', 'Two are gerunds; the third is infinitive — make them all match.'], estimatedMinutes: 3 },
    { id: 'misconception-comma-splice', kind: 'misconception_check', question: 'A student joins two independent clauses with just a comma. What\'s the SAT-correct way to fix?', commonErrors: [{ answer: 'Comma joining two independents', misconception: 'Treating comma as sufficient to join sentences.', correctsTo: 'A COMMA ALONE cannot join two independent clauses — that\'s a COMMA SPLICE. Fix options: (1) PERIOD between them. (2) SEMICOLON. (3) Comma + FANBOYS (and, but, so, etc.). (4) Subordinator (while, because, although) to make one dependent. SAT often offers all four — pick whichever is grammatically + stylistically best for the context.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Sentence = subject + verb + complete thought.', 'Comma splice = two independent clauses joined by ONLY a comma — wrong.', 'Dangling modifier: opening phrase must describe the next clause\'s subject.', 'Parallelism: items in lists/comparisons match form.', 'Correlative pairs (not only...but also) need matching forms.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
