/**
 * SAT Math — Geometry: Triangles, Circles, Polygons.
 */

import type { LessonPlan } from '../types';

export const SEED_SAT_MATH_GEOMETRY: LessonPlan = {
  id: 'evelyn.testprep.sat-math.geometry.v1',
  title: 'SAT Math — Geometry: Triangles, Circles, Polygons',
  curriculum: 'CCSS',
  grade: 'sat-act',
  subject: 'test-prep',
  topic: 'sat-math',
  locale: 'en',
  los: [{ id: 'satmath.geometry', description: 'Apply triangle, circle, and polygon properties on SAT geometry questions.', standard: 'CCSS.MATH.HSG' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 16,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Geometry = ~5-7 SAT Math questions. The formulas are FEW and the patterns repeat.', script: 'Triangle angle sum, Pythagorean theorem, circle area + circumference, special triangles. SAT recycles these heavily. Memorise + recognise patterns.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Triangles, circles, polygons, special triangles, area + perimeter formulas.', keyIdeas: [
      'TRIANGLE basics:',
      '  Interior angles sum to 180°.',
      '  Pythagorean theorem (right triangle): a² + b² = c² (c = hypotenuse).',
      '  Triangle inequality: sum of two sides > third side.',
      'SPECIAL RIGHT TRIANGLES (memorise!):',
      '  3-4-5 (and multiples 6-8-10, 9-12-15, etc.).',
      '  5-12-13.',
      '  30-60-90: sides 1 : √3 : 2 (short : long : hyp).',
      '  45-45-90: sides 1 : 1 : √2.',
      'SIMILAR triangles: corresponding angles equal, corresponding sides PROPORTIONAL.',
      'CONGRUENT triangles: same shape AND size. SSS, SAS, ASA, AAS, HL.',
      'AREA of triangle: (1/2) × base × height.',
      'CIRCLES:',
      '  CIRCUMFERENCE: 2πr (or πd). DIAMETER = 2r.',
      '  AREA: πr².',
      '  ARC length = (θ/360°) × 2πr (θ in degrees).',
      '  SECTOR area = (θ/360°) × πr².',
      '  TANGENT line is PERPENDICULAR to radius at point of tangency.',
      'CIRCLE EQUATIONS: (x − h)² + (y − k)² = r². Center (h, k), radius r.',
      'POLYGON interior angle sum = (n − 2) × 180°. Each interior angle of REGULAR n-gon: (n − 2) × 180°/n.',
      'PARALLEL LINES + transversal:',
      '  Alternate interior angles equal.',
      '  Corresponding angles equal.',
      '  Co-interior (same-side) angles supplementary (sum to 180°).',
      'AREA formulas:',
      '  Rectangle: l × w.',
      '  Parallelogram: base × height.',
      '  Trapezoid: (1/2) × (b₁ + b₂) × height.',
      '3D VOLUME (SAT formula sheet provides):',
      '  Rectangular prism: lwh.',
      '  Cylinder: πr²h.',
      '  Sphere: (4/3)πr³.',
      '  Cone: (1/3)πr²h.',
      'SAT TRICK: PROBLEMS often look complex but reduce to 3-4-5, 5-12-13, or special triangles.',
    ], vocabulary: [{ term: 'special right triangle', definition: '3-4-5, 5-12-13, 30-60-90, 45-45-90; their proportions appear constantly on SAT.' }, { term: 'similar triangles', definition: 'same shape, different size; corresponding angles equal, corresponding sides proportional.' }], estimatedMinutes: 5 },
    { id: 'worked', kind: 'worked_example', problem: 'A right triangle has one leg 6 and hypotenuse 10. Find the other leg.', steps: [
      'Recognise: 6, ?, 10 — could it be a 6-8-10 (multiples of 3-4-5)?',
      'Verify with Pythagoras: 6² + b² = 10² → 36 + b² = 100 → b² = 64 → b = 8. ✓',
      'Other leg: 8. (Same as 3-4-5 scaled by 2.)',
    ], answer: '8', estimatedMinutes: 3 },
    { id: 'try-1', kind: 'try_yourself', problem: 'A circle has equation (x − 2)² + (y + 5)² = 16. Find the center and radius.', expectedAnswer: 'Compare to standard (x − h)² + (y − k)² = r². h = 2, k = −5 (note the +5 means k is negative because (y − (−5)) = (y + 5)). r² = 16 → r = 4. Center: (2, −5). Radius: 4.', responseFormat: 'free', hints: ['Match against (x − h)² + (y − k)² = r².', 'Be careful with signs in (y + 5).'], estimatedMinutes: 3 },
    { id: 'misconception-circle-eq-sign', kind: 'misconception_check', question: 'A student reads (x − 3)² + (y − 4)² = 25 and says the radius is 25. What\'s wrong?', commonErrors: [{ answer: 'Radius = 25', misconception: 'Confusing r² with r in circle equation.', correctsTo: 'In (x − h)² + (y − k)² = r², the right side is r SQUARED. To get r, take SQUARE ROOT. Here r² = 25 → r = 5. Center (3, 4), radius 5. SAT routinely tests this — students forget to take the square root.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Triangle angles = 180°. Pythagorean a² + b² = c².', 'Special triangles 3-4-5, 5-12-13, 30-60-90, 45-45-90.', 'Circle area πr², circumference 2πr.', 'Circle equation (x − h)² + (y − k)² = r² — take √ for r.', 'Tangent ⊥ radius at point of tangency.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
