/**
 * SAT R&W — Comma Rules and Punctuation.
 */

import type { LessonPlan } from '../types';

export const SEED_SAT_RW_GRAMMAR_COMMAS: LessonPlan = {
  id: 'evelyn.testprep.sat-rw.grammar-commas.v1',
  title: 'SAT R&W — Comma Rules and Punctuation',
  curriculum: 'CCSS',
  grade: 'sat-act',
  subject: 'test-prep',
  topic: 'sat-reading-writing',
  locale: 'en',
  los: [{ id: 'satrw.grammar-commas', description: 'Apply SAT comma rules + semicolon, colon, dash, apostrophe usage.', standard: 'CCSS.ELA.LANGUAGE' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 14,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Punctuation = ~6 SAT R&W questions per test. Knowing the rules earns these reliably.', script: 'Comma rules look fussy but reduce to a small set of patterns. Semicolon = comma+conjunction for two independent clauses. Colon = introduce list or explanation. Today: the canonical rules.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Commas, semicolons, colons, dashes, apostrophes.', keyIdeas: [
      'COMMA RULES (high-yield):',
      '  Between INDEPENDENT clauses joined by FANBOYS conjunction (for, and, nor, but, or, yet, so).',
      '    "I went home, AND she stayed at work."',
      '  After INTRODUCTORY phrases or clauses.',
      '    "Walking home, I saw a cat."',
      '  Around NON-ESSENTIAL clauses (which can be removed without changing core meaning).',
      '    "My brother, who lives in Tokyo, called."',
      '  In LISTS (Oxford comma optional but SAT prefers it).',
      '    "apples, oranges, and grapes."',
      '  NEVER between SUBJECT and VERB.',
      '    "The cat sleeps." (no comma between cat and sleeps).',
      'SEMICOLON (;): joins TWO INDEPENDENT clauses (no FANBOYS conjunction needed).',
      '  "I love reading; she prefers TV."',
      '  Both sides must be complete sentences.',
      '  ALSO used in lists with internal commas: "I visited Tokyo, Japan; Paris, France; and Lima, Peru."',
      'COLON (:): introduces a list, explanation, or quote.',
      '  "I brought three things: a book, a pen, and a notebook."',
      '  Independent clause MUST come BEFORE the colon.',
      '  WRONG: "I brought: a book, a pen, a notebook." (no complete sentence before colon).',
      'DASH (—): emphasises a non-essential phrase or sets off a clarification.',
      '  "She had only one goal—victory."',
      '  Pair of dashes used like commas around an interruption.',
      'APOSTROPHE:',
      '  POSSESSIVE: "the cat\'s tail." For plural ending in s: "the dogs\' tails."',
      '  CONTRACTION: "it\'s" = "it is." NOT "its" (possessive of it).',
      '  Common error: confusing its / it\'s; their / they\'re; whose / who\'s.',
      'CRITICAL TRAPS:',
      '  Comma between subject and verb: WRONG.',
      '  Comma splice: two independent clauses joined by comma WITHOUT FANBOYS — WRONG.',
      '  Semicolon with fragment: WRONG.',
      '  Apostrophe + plural (without possession): "He has two cat\'s." — WRONG.',
    ], vocabulary: [{ term: 'independent clause', definition: 'a clause that can stand as a complete sentence.' }, { term: 'comma splice', definition: 'incorrect punctuation joining two independent clauses with only a comma.' }], estimatedMinutes: 5 },
    { id: 'worked', kind: 'worked_example', problem: 'Choose: "The committee, after long debate ___ released its report." (A) , (B) ; (C) : (D) [no punctuation]', steps: [
      '"After long debate" is a non-essential clause inside the sentence.',
      'It needs to be set off by COMMAS on both sides — already has comma BEFORE.',
      'After "debate" we need closing comma to match.',
      'Answer: (A) comma.',
      'Wrong options: (B) semicolon would split into two independent clauses, but "released its report" isn\'t complete on its own. (C) colon similar problem. (D) no punctuation leaves the inserted phrase floating.',
    ], answer: '(A) comma', estimatedMinutes: 3 },
    { id: 'try-1', kind: 'try_yourself', problem: 'Choose: "I love hiking ___ I go every weekend." (A) , (B) ; (C) , and (D) , so', expectedAnswer: '(B) semicolon OR (C) , and OR (D) , so. Both clauses are independent ("I love hiking" + "I go every weekend"). They need either: semicolon (B), or comma + FANBOYS (C "and" or D "so"). NOT (A) comma alone (comma splice — wrong). Best answer depends on context; semicolon (B) is grammatically correct. (D) ", so" adds reasoning — also fits.', responseFormat: 'free', hints: ['Two independent clauses cannot be joined by ONLY a comma (comma splice).', 'Need: semicolon, OR comma + FANBOYS.'], estimatedMinutes: 3 },
    { id: 'misconception-comma-everywhere', kind: 'misconception_check', question: 'A student inserts a comma every time they pause when reading aloud. Why does this often produce wrong answers?', commonErrors: [{ answer: 'Comma at every pause', misconception: 'Treating commas as breath markers.', correctsTo: 'English commas follow GRAMMATICAL RULES, not natural pauses. Where you breathe is not where commas go. SAT tests the RULES: between subject + verb (no comma), between independent clauses + FANBOYS (yes), around non-essentials (yes). Drill the rules; ignore your natural pause instinct.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['FANBOYS comma between independent clauses.', 'Semicolon between independents (no conjunction).', 'Colon needs complete sentence before.', 'No comma between subject and verb.', 'It\'s = it is. Its = possessive.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
