/**
 * Freestyle lesson-plan cleanup.
 *
 * Deletes orphan freestyle plans from the `lessonplans` collection. A
 * freestyle plan is one generated by `plan-from-text` / `expand-plan-los`
 * (carries `metadata.generatedFromText: true`). Each freestyle paste creates
 * a fresh plan id; there is currently no UI to resume one, so over time
 * these accumulate.
 *
 * Selection criteria:
 *   - metadata.generatedFromText === true   (only freestyle plans — seeds
 *                                            and curated plans don't carry
 *                                            this flag, so they're never
 *                                            touched)
 *   - updatedAt < now - <days> days        (default 30; protects live
 *                                            sessions because `updatedAt`
 *                                            is bumped on every expand-los
 *                                            write during the session)
 *
 * The 30-day age filter alone is sufficient — pending-picker plans older
 * than 30 days are abandoned just like fully-confirmed ones, so we don't
 * exclude them.
 *
 * Usage:
 *   # Dry-run (default — prints matched plans, deletes nothing)
 *   npx tsx scripts/cleanup-freestyle-plans.ts
 *
 *   # Custom retention
 *   npx tsx scripts/cleanup-freestyle-plans.ts --days 14
 *
 *   # Actually delete
 *   npx tsx scripts/cleanup-freestyle-plans.ts --apply
 *
 * Required env: MONGODB_URI.
 */

import mongoose from 'mongoose';

const MONGODB_URI = process.env.MONGODB_URI;
const DEFAULT_RETENTION_DAYS = 30;

interface Args {
  days: number;
  apply: boolean;
}

function parseArgs(): Args {
  const args: Args = { days: DEFAULT_RETENTION_DAYS, apply: false };
  for (let i = 2; i < process.argv.length; i++) {
    const a = process.argv[i];
    if (a === '--apply') args.apply = true;
    else if (a === '--days') {
      const v = parseInt(process.argv[++i], 10);
      if (!Number.isFinite(v) || v < 0) throw new Error('--days requires a non-negative integer');
      args.days = v;
    } else if (a === '--help' || a === '-h') {
      console.log('Usage: tsx scripts/cleanup-freestyle-plans.ts [--days N] [--apply]');
      process.exit(0);
    } else {
      throw new Error(`Unknown flag: ${a}`);
    }
  }
  return args;
}

interface PlanSummary {
  _id: string;
  title: string;
  subject: string;
  grade: string;
  updatedAt: Date;
  pendingPicker: boolean;
}

async function main() {
  if (!MONGODB_URI) throw new Error('MONGODB_URI not set');
  const { days, apply } = parseArgs();

  const cutoff = new Date(Date.now() - days * 86_400_000);

  await mongoose.connect(MONGODB_URI);
  const LessonPlan = mongoose.connection.collection('lessonplans');

  const filter = {
    'metadata.generatedFromText': true,
    updatedAt: { $lt: cutoff },
  };

  const docs = await LessonPlan
    .find(filter, { projection: { _id: 1, title: 1, subject: 1, grade: 1, updatedAt: 1, 'metadata.pendingPicker': 1 } })
    .sort({ updatedAt: 1 })
    .toArray();

  const plans: PlanSummary[] = docs.map(d => ({
    _id: String(d._id),
    title: String(d.title ?? '(no title)'),
    subject: String(d.subject ?? ''),
    grade: String(d.grade ?? ''),
    updatedAt: d.updatedAt as Date,
    pendingPicker: Boolean((d.metadata as { pendingPicker?: boolean } | undefined)?.pendingPicker),
  }));

  console.log(`Cutoff: ${cutoff.toISOString()} (${days} days ago)`);
  console.log(`Matched ${plans.length} freestyle plan(s):\n`);
  for (const p of plans) {
    const age = ((Date.now() - p.updatedAt.getTime()) / 86_400_000).toFixed(1);
    const picker = p.pendingPicker ? ' [pendingPicker]' : '';
    console.log(`  ${p._id}  ${age}d  ${p.subject}/${p.grade}  "${p.title}"${picker}`);
  }
  console.log('');

  if (plans.length === 0) {
    await mongoose.disconnect();
    return;
  }

  if (!apply) {
    console.log('Dry-run (no --apply). Re-run with --apply to delete.');
    await mongoose.disconnect();
    return;
  }

  const res = await LessonPlan.deleteMany(filter);
  console.log(`Deleted ${res.deletedCount} plan(s).`);

  await mongoose.disconnect();
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
