/**
 * Grade 6 Science — Unit 4 CED 4.1: Evidence for Continental Drift.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m6sci.evidence-for-continental-drift.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M6SCI_U4_EVIDENCE_FOR_CONTINENTAL_DRIFT: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m6sci.evidence-for-continental-drift.v1',
  course: 'Grade 6 Science',
  cedUnit: 4,
  cedTopic: '4.1',
  cedTitle: 'Evidence for Continental Drift',
  planId: 'evelyn.ms.m6sci.evidence-for-continental-drift.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-03',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m6sci.evidence-for-continental-drift.v1' }],
  theory: [
    { loId: 'm6sci.evidence-for-continental-drift', content: `A CONTINENT-SIZED PUZZLE. In 1912, a scientist named Alfred Wegener proposed that all of Earth's continents were once joined together in a single landmass, which he called Pangaea, and that they have been slowly drifting apart ever since. That idea is called continental drift. Wegener was not guessing at random -- he built his case out of several separate kinds of evidence, each one pointing the same direction on its own.` },
    { loId: 'm6sci.evidence-for-continental-drift', content: `EVIDENCE 1: THE COASTLINES FIT. The eastern coastline of South America and the western coastline of Africa are shaped like two pieces of the same jigsaw puzzle: the bulge of Brazil fits into the curve of the African coast near the Gulf of Guinea. A coastline shape is not something that should match by accident between two continents thousands of kilometers apart, unless the two continents were once joined.` },
    { loId: 'm6sci.evidence-for-continental-drift', content: `EVIDENCE 2: MATCHING FOSSILS ON SEPARATED CONTINENTS. Fossils of several land and freshwater organisms turn up on continents that an ocean now separates, even though none of those organisms could have made the crossing themselves. Mesosaurus, a small reptile that lived only in fresh water, is found in matching-age rock in South America and in southern Africa. Glossopteris, a seed fern whose seeds were too heavy to be carried far by wind, is found across South America, southern Africa, India, Australia, and Antarctica. Lystrosaurus and Cynognathus, two land animals that could not swim an ocean, each turn up on more than one continent that an ocean now separates. An organism that cannot cross an ocean, found on both sides of one, is evidence the ocean was not always there.` },
    { loId: 'm6sci.evidence-for-continental-drift', content: `EVIDENCE 3: MATCHING ROCK LAYERS. Sequences of rock layers, in the same order and of the same age, appear in regions of South America and in regions of southern Africa. A rock layer records the conditions that were present when it formed, so the same sequence forming in two regions that are now far apart is another sign those regions were once side by side.` },
    { loId: 'm6sci.evidence-for-continental-drift', content: `EVIDENCE 4: THE SEAFLOOR'S OWN RECORD. Decades after Wegener, scientists mapping the floor of the Atlantic Ocean found something new. As certain minerals in seafloor rock cool and harden, they lock in a record of which way Earth's magnetic field pointed at that moment, and that field has flipped direction many times over Earth's history. Near a mid-ocean ridge, a long undersea mountain range, the resulting stripe pattern on one side is a mirror image of the pattern on the other side. That mirror image means new rock is being added at the ridge and moving outward in both directions over time -- the ocean floor itself is spreading.` },
    { loId: 'm6sci.evidence-for-continental-drift', content: `THE MISSING PIECE, AND WHY IT MATTERED. Wegener's coastline, fossil, and rock-layer evidence held up. What did not hold up were his own guesses about WHAT could possibly move something as massive as a continent -- he pointed to forces such as the pull of the sun and moon, and other scientists correctly calculated that those forces were far too weak. For decades, most scientists rejected continental drift for exactly that reason: solid evidence that continents had moved, with no believable explanation of how. The mirror-image seafloor stripes, discovered long after Wegener died in 1930, did not by themselves explain what causes continents to move -- that is a separate lesson -- but they showed, directly, that the ocean floor is created and moves. That was the missing piece that finally turned a rejected idea into an accepted one.` },
    { loId: 'm6sci.evidence-for-continental-drift', kind: 'definition', title: 'continental drift', content: `the idea that Earth's continents have moved across the surface of the planet over long spans of time.` },
    { loId: 'm6sci.evidence-for-continental-drift', kind: 'definition', title: 'Pangaea', content: `the name Wegener gave to the single, joined landmass he proposed the continents were once part of.` },
    { loId: 'm6sci.evidence-for-continental-drift', kind: 'definition', title: 'mid-ocean ridge', content: 'a long undersea mountain range where new ocean floor rock forms.' },
    { loId: 'm6sci.evidence-for-continental-drift', kind: 'definition', title: 'magnetic stripe pattern', content: `a mirror-image pattern of alternating magnetic direction recorded in seafloor rock on either side of a mid-ocean ridge.` },
    { loId: 'm6sci.evidence-for-continental-drift', kind: 'definition', title: 'seafloor spreading', content: 'new ocean floor forming at a mid-ocean ridge and moving outward over time.' },
  ],
  methods: [
    {
      title: 'Worked fossil evidence',
      steps: [
        `Start with what Mesosaurus could and could not do. It lived only in fresh water, and it was not built for a long ocean swim. A creature like that cannot cross a wide, salty ocean on its own.`,
        `Now look at where its fossils turn up: in matching-age rock in South America and in southern Africa, continents an ocean currently separates by thousands of kilometers.`,
        `If Mesosaurus could not make that crossing, and nothing else obviously carried it across, the simplest explanation is that the crossing did not exist yet -- the two landmasses were joined, or close enough together, for Mesosaurus to reach both without ever entering open ocean.`,
        `Check that against other, different kinds of evidence rather than trusting one fossil alone. Glossopteris, a seed fern with seeds too heavy to blow far on the wind, shows the same separated-but-matching pattern across five present-day continents -- a different kind of organism, same conclusion. Sequences of rock layers, which are not living things at all, also match across the same two continents. Three different kinds of clue -- a freshwater reptile, a heavy-seeded plant, and a nonliving rock sequence -- all point to the same joined-continents answer.`,
        `Now change one condition and check that the answer moves the way it should. Suppose Mesosaurus had instead been a strong, fast swimmer capable of crossing thousands of kilometers of open salt water. Finding its fossils on both continents would then say nothing about whether the continents were ever joined -- it would simply mean Mesosaurus swam there. The evidence only works because the animal specifically could not have made the trip itself. That is what makes it evidence, not just an interesting coincidence.`,
      ],
      example: { problem: `Fossils of Mesosaurus, a reptile that lived only in fresh water and was far too weak a swimmer to cross open ocean, are found in matching-age rock in South America and in southern Africa -- continents that today sit on opposite sides of the Atlantic Ocean. Explain why this fossil pattern is evidence that the two continents were once joined, rather than evidence that Mesosaurus crossed the ocean by some other means.`, solution: `The fossil pattern is evidence that South America and southern Africa were once joined, or close enough together for Mesosaurus to move between them without crossing open ocean, because a freshwater animal too weak to survive that ocean crossing has no other way of reaching both continents.` },
      relatedLoIds: ['m6sci.evidence-for-continental-drift'],
    },
    {
      title: 'Worked seafloor and the missing mechanism',
      steps: [
        `Start with what a magnetic stripe records. As certain minerals in seafloor rock cool and harden, they lock in the direction of Earth's magnetic field at that moment, and that field has flipped direction many times over Earth's history. So a strip of seafloor rock carries a permanent record of which way the field pointed when that rock formed.`,
        `A mirror-image pattern on both sides of the ridge means rock at the same distance from the ridge, on either side, carries the same magnetic record and formed at the same time.`,
        `The simplest way to produce that pattern is if new rock keeps forming right at the ridge and gets pushed outward on both sides as more rock forms behind it -- so rock right at the ridge is the youngest, and rock farther from the ridge on either side is older, in matching pairs. That means the ocean floor itself is not fixed. It is being created at the ridge and is spreading outward over time.`,
        `WRONG: "Wegener's proposal was rejected because his coastline, fossil, and rock-layer evidence was mistaken." CORRECT: that evidence held up over time and was never disproven. What was missing was a believable answer to a different question -- what could possibly move something as massive as a continent -- and Wegener's own guesses about that cause, such as tidal forces, were shown by calculation to be far too weak.`,
        `The mirror-image seafloor pattern succeeded where the earlier evidence had not because it did something the coastline, fossil, and rock-layer evidence could not: it showed the ocean floor itself being made and moving, in rock scientists could directly measure and date, decades after Wegener died in 1930 without seeing his idea accepted.`,
        `Run the two checks a science answer needs, since there is no arithmetic to redo here. First, look for clues of different kinds that agree: the mirrored stripe pattern itself, the separate fact that rock farther from the ridge is measurably older than rock close to it, and the historical fact that this new evidence lined up with the coastline, fossil, and rock-layer evidence collected decades earlier. Three different kinds of clue, one answer. Second, change one condition and check that the answer moves with it: if the stripe pattern on the two sides of the ridge did NOT mirror each other, and looked random instead, there would be no reason to conclude the seafloor spreads outward from the ridge at all, and this piece of evidence would not exist.`,
      ],
      example: { problem: `Scientists mapping the floor of the Atlantic Ocean near the Mid-Atlantic Ridge find that the pattern of magnetic stripes recorded in the rock is a mirror image: the same sequence of stripes appears on the ridge's western side and again, in reverse order, on its eastern side. Explain what that mirrored pattern shows, and why this particular evidence succeeded in convincing scientists that continents move, when Wegener's original coastline, fossil, and rock-layer evidence had not been enough.`, solution: `The mirrored stripe pattern shows that new ocean floor forms at the ridge and spreads outward on both sides over time, so the ocean floor itself moves. That succeeded in convincing scientists because it gave them something Wegener never had: direct, measurable evidence that the seafloor is created and in motion, rather than only evidence that continents once fit together.` },
      relatedLoIds: ['m6sci.evidence-for-continental-drift'],
    },
  ],
  pointers: [
    { content: `Students often say "Wegener's idea was rejected because his evidence was wrong." — Wegener's coastline, fossil, and rock-layer evidence held up over time and was never shown to be false. What got continental drift rejected for decades was that Wegener could not explain a believable physical cause for the motion -- what could possibly move something as massive as a continent -- and the causes he did guess at, such as tidal forces, were shown by calculation to be far too weak. The evidence was solid; the explanation of the cause was missing.`, kind: 'common-error' },
    { content: `Students often say "The matching magnetic stripes just mean both sides of the ocean formed at exactly the same time." — The mirror-image pattern means rock at the same distance from the ridge, on either side, formed at the same time and carries the same magnetic record -- not that the whole ocean floor formed at once. Rock right at the ridge is the youngest; rock farther from the ridge, on either side, is progressively older, because new rock keeps forming at the ridge and spreads outward over a very long span of time.`, kind: 'common-error' },
    { content: `Wegener proposed in 1912 that the continents were once joined in a single landmass, which he called Pangaea, and have since drifted apart.`, kind: 'tip' },
    { content: `Matching coastline shapes, such as the fit between South America and Africa, were one of his first clues.`, kind: 'tip' },
    { content: `Matching fossils -- Mesosaurus, Glossopteris, Lystrosaurus, and Cynognathus -- found on continents an ocean now separates, in organisms that could not have crossed that ocean on their own, are strong evidence the continents were once joined.`, kind: 'tip' },
    { content: `Matching sequences of rock layers, in the same order and of the same age, found on separated continents point to the same conclusion.`, kind: 'tip' },
    { content: `Wegener's evidence held up. What got his proposal rejected for decades was that he could not explain a plausible physical cause for continental motion, and the causes he guessed at, such as tidal forces, were shown to be far too weak.`, kind: 'tip' },
    { content: `Decades later, scientists mapping the ocean floor found mirror-image magnetic stripe patterns on either side of mid-ocean ridges, showing that new ocean floor forms at the ridge and spreads outward over time.`, kind: 'tip' },
    { content: `That seafloor evidence, discovered after Wegener died in 1930, is what finally persuaded scientists that continents really do move.`, kind: 'tip' },
    { content: `Four different kinds of evidence -- coastlines, fossils, rock layers, and the seafloor's magnetic pattern -- together made a case no single line of evidence could have made alone.`, kind: 'tip' },
    { content: `Don't say Wegener's evidence was wrong. His coastline, fossil, and rock-layer clues held up fine. Scientists rejected continental drift because he had no believable explanation for *how* continents could move — not because the evidence failed.`, kind: 'common-error' },
    { content: `A fossil is evidence for continental drift only if the organism *could not* have crossed the ocean on its own. Mesosaurus was a weak freshwater swimmer — that's what makes it evidence. A strong ocean swimmer found on both continents would prove nothing.`, kind: 'gotcha' },
    { content: `Matching rock layers on separated continents are evidence the continents were once joined *at the time the layers formed*, not that they've never moved. The layers say where the continents were then, not where they are now.`, kind: 'vocab-note' },
    { content: `Mirror-image magnetic stripes do NOT mean the entire ocean floor formed all at once. They mean rock gets older the farther you go from the ridge. New rock forms at the ridge continuously; older rock gets pushed outward.`, kind: 'common-error' },
    { content: `Coastline shape alone is not airtight proof — continents could drift and have different shapes by now. But coastline *plus* fossils *plus* rock layers *plus* seafloor stripes? Four independent clues pointing the same way is much harder to ignore.`, kind: 'tip' },
    { content: `Wegener died in 1930 and never saw his idea accepted. The magnetic stripe evidence, discovered decades later, is what changed minds. Know that timeline — it explains why his evidence didn't convince people at the time.`, kind: 'edge-case' },
    { content: `Don't mix up 'continental drift' with 'seafloor spreading.' Drift is the continents moving. Seafloor spreading is ocean floor being made at ridges and pushing outward. They're related, but not the same thing.`, kind: 'vocab-note' },
  ],
};
