/**
 * Grade 6 Science — Unit 7 CED 7.4: Weathering, Erosion & Deposition by Water.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m6sci.weathering-erosion-and-deposition-by-water.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M6SCI_U7_WEATHERING_EROSION_AND_DEPOSITION_BY_WATER: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m6sci.weathering-erosion-and-deposition-by-water.v1',
  course: 'Grade 6 Science',
  cedUnit: 7,
  cedTopic: '7.4',
  cedTitle: 'Weathering, Erosion & Deposition by Water',
  planId: 'evelyn.ms.m6sci.weathering-erosion-and-deposition-by-water.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-03',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m6sci.weathering-erosion-and-deposition-by-water.v1' }],
  theory: [
    { loId: 'm6sci.weathering-erosion-and-deposition-by-water', content: `THREE DIFFERENT JOBS, ONE AGENT: MOVING WATER. WEATHERING breaks rock apart right where it sits. EROSION carries the already-loosened pieces, called sediment, away from where they formed. DEPOSITION drops that carried sediment somewhere else. These are three separate jobs, not three names for the same thing, and water can do all three -- but never at the same moment, and never in the wrong order. Rock has to be weathered before there is anything loose for erosion to carry, and sediment has to be carried before deposition has anything to drop.` },
    { loId: 'm6sci.weathering-erosion-and-deposition-by-water', content: `MECHANICAL WEATHERING BY WATER breaks rock into smaller pieces of the exact same material -- nothing about what the rock is made of changes, only its size. Two common ways water does this: ICE WEDGING, where water seeps into a crack, freezes, and expands, forcing the crack a little wider each time it happens, until a piece finally breaks off; and simple GRINDING, where fast-moving water rolls rock fragments against a riverbed or against each other, chipping off small pieces the way a rock tumbler wears down stones.` },
    { loId: 'm6sci.weathering-erosion-and-deposition-by-water', content: `CHEMICAL WEATHERING BY WATER changes WHAT the rock is made of, not just its size. Rainwater picks up a small amount of carbon dioxide from the air on its way down and becomes slightly acidic. That weak acid can slowly dissolve certain minerals -- limestone is the clearest example -- widening cracks and hollowing out rock over time. The rock that comes out the other side is chemically different from what went in, which is what separates chemical weathering from mechanical weathering.` },
    { loId: 'm6sci.weathering-erosion-and-deposition-by-water', content: `EROSION BY WATER carries away the sediment that weathering has already loosened, and moving water is picky about what it can carry. Fast, powerful water -- a rushing mountain stream, a river in flood -- has enough force to carry large, heavy pieces like gravel along with smaller sand and mud. Slow-moving water can only keep small, light pieces like fine sand and mud suspended; it cannot carry gravel at all. How much power the water has decides how large a piece it can move.` },
    { loId: 'm6sci.weathering-erosion-and-deposition-by-water', content: `DEPOSITION BY WATER happens wherever moving water SLOWS DOWN, never where it is moving fastest. The instant water loses the speed it needs to keep carrying its load, it starts dropping sediment -- heaviest pieces first, because they need the most power to stay suspended, and lightest pieces last, because they can still be carried a little farther before the water finally gives them up too. Two landforms come from this: a DELTA, a fan of new land where a fast river slows sharply on reaching a larger, calmer body of water and dumps what it was carrying (the Mississippi River builds a real delta this way, where its current meets the calm water of the Gulf of Mexico); and a FLOODPLAIN, the flat strip of land beside a river that gains a new layer of mud every time the river rises over its banks, spreads out across flat ground, and slows to a crawl (the Nile River's floodplain formed this way, built up by its floods long before any dam controlled the river).` },
    { loId: 'm6sci.weathering-erosion-and-deposition-by-water', content: `A CANYON IS THE OPPOSITE OUTCOME OF THE SAME THREE PROCESSES. Instead of building new land somewhere else, erosion can cut land DOWN. When a river keeps carrying away the sediment that weathering keeps loosening from its own bed and walls, over an extremely long stretch of time, the river channel gets deeper and deeper relative to the rock on either side of it, until the land drops far below the surrounding rock layers -- a canyon (the Colorado River has cut the Grand Canyon this way). A canyon and a delta are not opposites in what CAUSES them; they are opposites in where the SEDIMENT ends up. A canyon is what is left behind once erosion has carried the sediment away. A delta is what erosion carried and deposition finally dropped.` },
    { loId: 'm6sci.weathering-erosion-and-deposition-by-water', kind: 'definition', title: 'mechanical weathering', content: `breaking rock into smaller pieces of the same material, without changing what the rock is made of, such as by ice wedging or by moving water grinding fragments together.` },
    { loId: 'm6sci.weathering-erosion-and-deposition-by-water', kind: 'definition', title: 'chemical weathering', content: `changing what a rock is made of, such as by rainwater slowly dissolving a mineral like limestone.` },
    { loId: 'm6sci.weathering-erosion-and-deposition-by-water', kind: 'definition', title: 'erosion', content: `the carrying away of loose sediment by moving water, from the place where weathering loosened it.` },
    { loId: 'm6sci.weathering-erosion-and-deposition-by-water', kind: 'definition', title: 'deposition', content: `the dropping of sediment that moving water was carrying, which happens wherever the water slows down.` },
    { loId: 'm6sci.weathering-erosion-and-deposition-by-water', kind: 'definition', title: 'delta', content: `new land built where a river slows sharply on reaching a larger, calmer body of water and deposits its sediment.` },
    { loId: 'm6sci.weathering-erosion-and-deposition-by-water', kind: 'definition', title: 'floodplain', content: `the flat land beside a river that is built up, layer by layer, by sediment deposited each time the river floods.` },
  ],
  methods: [
    {
      title: 'Worked mountain stream to delta',
      steps: [
        `Start with the ledge. Fast water rolling rocks against the ledge and against each other, chipping off gravel and sand, is breaking rock apart right where it sits -- that is weathering, and specifically MECHANICAL weathering, because pieces are physically broken off without anything about the rock dissolving or chemically changing.`,
        `The river then carrying that gravel and sand downstream, mile after mile, is a separate job: erosion. Erosion never breaks the rock -- weathering already did that at the ledge -- erosion only moves what is already loose.`,
        `WRONG: "The river eroded the rock into gravel and sand at the ledge." CORRECT: "The river's rushing water weathered the rock into gravel and sand at the ledge; only afterward did erosion carry those loose pieces downstream." Naming the wrong process at the wrong step is the single most common mistake on this topic.`,
        `Now follow the sediment to the lake. As the fast-flowing river reaches the calm, still lake water, it abruptly loses the push that let it carry gravel and sand -- calm standing water does not shove the river forward the way a steep mountain slope does. Losing that push is exactly the condition that causes deposition: moving water can only carry sediment as long as it keeps moving fast enough, and here it suddenly does not.`,
        `The heaviest pieces -- the gravel -- drop out first, right where the river meets the lake. The lighter sand is carried a little farther into the calmer water before it, too, settles out.`,
        `Repeated over many years, sediment builds up in a fan shape spreading out from the river's mouth into the lake. That built-up fan is a delta.`,
        `Now run the two checks a science answer needs, because there is no arithmetic here to redo. First, look for clues of DIFFERENT KINDS that agree. The order of the story only makes sense one way -- pieces cannot be carried before they are broken loose, and cannot be dropped before they are carried. The sorting by size (gravel first, then sand) matches the general rule that heavier pieces need more moving power to stay suspended. And the location matches the rule too: deposition happens exactly where the water loses speed, which is exactly where the fast river meets the calm lake. Three different kinds of evidence, one answer.`,
        `Second, change one condition and check that the answer moves with it. Suppose the river had instead kept flowing fast the whole way, straight into a narrow, steep gorge with no calm water anywhere in sight. Then nothing would ever slow the water down enough to drop its sediment, and no delta would form there at all -- the river would instead keep eroding and cutting the gorge deeper, the same process that carves a canyon rather than building a delta. Change the ending condition and the outcome changes with it.`,
      ],
      example: { problem: `Every spring, snowmelt speeds up a mountain river. Where the fast water rushes over a rocky ledge, it repeatedly rolls small rocks against the ledge and against each other, chipping off gravel and sand. The river then carries that gravel and sand a long way downstream, out past the mountains and across flat land, until it finally reaches the calm, still water of a lake. Trace what happens to the rock at the ledge from start to finish, and name the landform that eventually forms where the river meets the lake.`, solution: `Mechanical weathering breaks gravel and sand off the rocky ledge; erosion carries that sediment downstream; deposition drops it where the river's fast current meets the lake's calm water, building a delta.` },
      relatedLoIds: ['m6sci.weathering-erosion-and-deposition-by-water'],
    },
    {
      title: 'Worked limestone and floodplain',
      steps: [
        `Look closely at what changed the limestone: rainwater DISSOLVED part of the rock. That is a chemical change -- the rock is not the same substance it was before, part of it has actually dissolved away -- so this is CHEMICAL weathering, not mechanical weathering.`,
        `WRONG: "Water loosening rock is always mechanical weathering, because ice and rushing water break rock apart mechanically." CORRECT: "Whether weathering by water is mechanical or chemical depends on HOW the rock is changed: physically breaking into smaller pieces of the same material is mechanical, like ice wedging a crack wider; dissolving or chemically altering the rock is chemical, like rainwater dissolving limestone." The involvement of water does not decide which kind it is -- the kind of change does.`,
        `Once the chunks fall loose into the river, carrying them away would be erosion -- but that is a separate step from the dissolving that loosened them in the first place.`,
        `Now the flooding. Water spreading out of the channel across flat land loses speed immediately -- a thin sheet of water spread wide across flat ground moves far slower than the same water confined to a narrow channel. Losing that speed is what causes deposition, so the mud the floodwater was carrying settles out onto the land.`,
        `This happens again every few years, each flood leaving one more thin layer of mud on top of the last. Built up over many floods, this creates the flat strip of built-up land beside the river called a floodplain.`,
        `WRONG: "A river drops sediment wherever it happens to be flowing." CORRECT: "A river drops sediment specifically where it SLOWS DOWN -- confined in its channel it can keep carrying sediment for miles, but the moment it spreads out or empties into calmer water, it loses the power to keep carrying what it had."`,
        `Now run the two checks. First, three clues of different kinds that agree: the mechanism (dissolving) matches the definition of chemical weathering; the location of the new mud, right where the water spread out and slowed, matches the deposition rule; and the fact that only fine mud gets deposited on the floodplain, rather than gravel, matches the earlier rule that slow water can only carry small, light pieces. Second, change one condition: if that same river, instead of spreading across flat land, stayed confined between steep canyon walls even during high water, it would keep moving fast and would keep eroding the canyon deeper rather than depositing mud beside it -- which is exactly why a canyon has bare rock walls while a floodplain has soft, layered soil.`,
      ],
      example: { problem: `Farther downstream, that same river flows past a limestone cliff for many years. Slightly acidic rainwater trickles into cracks in the limestone and slowly dissolves some of the rock, widening the cracks and eventually loosening chunks that fall into the river. Meanwhile, every few years during a heavy rainy season, the river rises over its banks and spreads a thin sheet of muddy water across the flat land beside it; the water then drains back into the channel days later, leaving a new layer of mud on the ground. Which kind of weathering loosened the limestone chunks, and what landform is being built beside the river by the repeated flooding?`, solution: `Chemical weathering (the rainwater dissolved part of the limestone) loosened the chunks; the repeated flooding is building a floodplain, because the floodwater loses speed and drops its mud once it spreads out across the flat land.` },
      relatedLoIds: ['m6sci.weathering-erosion-and-deposition-by-water'],
    },
  ],
  pointers: [
    { content: `Students often say "The rushing water erodes the rocks into mud in the first place." — Weathering is the process that breaks rock apart into loose sediment, whether by mechanical force (fast water grinding rock against rock, or water freezing and expanding in a crack) or by chemical change (rainwater dissolving part of a rock such as limestone). Erosion is a separate, later process: it carries sediment that weathering has already loosened. Rushing water can do both jobs, but they are not the same job -- the rock has to be broken apart before erosion has anything loose to carry.`, kind: 'common-error' },
    { content: `Students often say "It drops that mud wherever it happens to be flowing fastest." — Moving water deposits sediment exactly where it SLOWS DOWN, not where it speeds up. Fast water has the power to keep sediment suspended and moving; only once the water loses speed -- spreading out over flat land during a flood, or emptying into the calm water of a lake, bay, or ocean -- does it lose the power to keep carrying its load, and drop it. That is why deltas and floodplains form at exactly those slow, spread-out places, never where a river is rushing fastest.`, kind: 'common-error' },
    { content: `Weathering breaks rock apart where it sits; erosion carries the loosened sediment away; deposition drops it somewhere else -- three different jobs, not one.`, kind: 'tip' },
    { content: `Mechanical weathering breaks rock into smaller pieces of the same material (ice wedging a crack wider, or fast water grinding rock against rock). Chemical weathering changes what the rock is made of (rainwater dissolving part of a rock such as limestone).`, kind: 'tip' },
    { content: `Moving water can carry larger, heavier pieces of sediment only while it keeps moving fast; slower water can only carry small, light pieces.`, kind: 'tip' },
    { content: `Deposition happens wherever moving water slows down, never where it is moving fastest. Heaviest sediment drops first; lighter sediment travels farther before settling.`, kind: 'tip' },
    { content: `A delta is new land built where a river slows abruptly on meeting a larger, calmer body of water and drops its sediment (for example, where the Mississippi River meets the Gulf of Mexico).`, kind: 'tip' },
    { content: `A floodplain is the flat land beside a river that gets a new layer of sediment each time the river overflows its banks, spreads out, and slows down (for example, the Nile River's floodplain).`, kind: 'tip' },
    { content: `A canyon forms the opposite way -- erosion keeps carrying away the sediment that weathering loosens from a riverbed and walls, cutting the land down deeper over an extremely long stretch of time (for example, the Grand Canyon, cut by the Colorado River).`, kind: 'tip' },
    { content: `A canyon and a delta come from the very same three processes; a canyon is what erosion leaves behind, and a delta is what erosion carried away and deposition dropped somewhere else.`, kind: 'tip' },
    { content: `Don't say "water eroded the rock into sediment." Say "water weathered the rock loose, then erosion carried it away." Weathering breaks rock; erosion only moves what's already broken. Two jobs, two words, in order.`, kind: 'common-error' },
    { content: `Mechanical weathering = same rock, smaller pieces. Chemical weathering = rock composition actually changes. The presence of water doesn't decide which—how the rock changes does.`, kind: 'vocab-note' },
    { content: `Deposition happens where water SLOWS DOWN, never where it rushes fastest. Fast water carries sediment; slow water drops it. Heaviest pieces fall first.`, kind: 'gotcha' },
    { content: `A canyon and a delta both use weathering + erosion + deposition, but opposite outcomes. Canyon: erosion carries sediment away, leaving a hole. Delta: erosion carries sediment there, and deposition fills it in.`, kind: 'edge-case' },
    { content: `Ice wedging breaks rock by freezing and expanding in a crack, repeating over time. It's mechanical weathering, not a one-time event. Same with grinding—it takes many tumbles to break a boulder into sand.`, kind: 'tip' },
    { content: `Rainwater picks up CO₂ from air and becomes slightly acidic, letting it dissolve limestone. That's chemical weathering. Don't confuse it with just water physically breaking rock.`, kind: 'vocab-note' },
    { content: `A river can't deposit sediment in a narrow, steep gorge because the water stays fast. Deposition needs slow water. A canyon forms instead because erosion keeps winning.`, kind: 'tip' },
    { content: `Slow-moving water can only carry tiny pieces (sand, mud). Fast water can carry gravel and boulders. The speed of the water decides the size limit of what it hauls.`, kind: 'vocab-note' },
  ],
};
