/**
 * Grade 6 Science — Unit 10 CED 10.2: Evidence for Rising Global Temperatures.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m6sci.evidence-for-rising-global-temperatures.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M6SCI_U10_EVIDENCE_FOR_RISING_GLOBAL_TEMPERATURES: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m6sci.evidence-for-rising-global-temperatures.v1',
  course: 'Grade 6 Science',
  cedUnit: 10,
  cedTopic: '10.2',
  cedTitle: 'Evidence for Rising Global Temperatures',
  planId: 'evelyn.ms.m6sci.evidence-for-rising-global-temperatures.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-03',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m6sci.evidence-for-rising-global-temperatures.v1' }],
  theory: [
    { loId: 'm6sci.evidence-for-rising-global-temperatures', content: `A TREND IS NOT A SINGLE READING. A temperature record moves up and down from year to year because of ordinary variation, the same way a single day's weather can sit above or below a region's climate pattern. A real trend can only be seen by looking at many decades of readings together. One unusually warm year is not evidence that Earth is warming, and one unusually cold year is not evidence that it is not -- in either direction, a single year is one reading, not a trend.` },
    { loId: 'm6sci.evidence-for-rising-global-temperatures', content: `THE TEMPERATURE RECORD HAS A SHAPE. Direct instrument records covering the past century and more show that Earth's average temperature has been higher, on average, in recent decades than it was in the early 1900s, and the rise has been fastest in the most recent several decades rather than steady the whole way through. This lesson works with the SHAPE of that record -- comparatively flat, then rising, then rising faster -- rather than any single current number, because the exact current number changes as new data arrive every year.` },
    { loId: 'm6sci.evidence-for-rising-global-temperatures', content: `THE CO2 RECORD HAS A MATCHING SHAPE. Carbon dioxide in the atmosphere is measured directly today and reconstructed from air trapped in ice for earlier periods. That record also rises over the same century-plus span: comparatively steady for a long stretch, then rising, with the fastest rise in the decades since large-scale fossil-fuel combustion -- coal first, then oil and natural gas -- expanded sharply worldwide, roughly from the middle of the 1900s onward, alongside fast industrial growth.` },
    { loId: 'm6sci.evidence-for-rising-global-temperatures', content: `THE MECHANISM THAT CONNECTS THEM. Sunlight passes through the atmosphere and warms Earth's surface. Earth then radiates some of that heat back outward. Carbon dioxide absorbs part of that outgoing heat and keeps it from escaping right away, which warms the lower atmosphere -- this is the greenhouse effect, and the natural version of it is what keeps Earth's surface warm enough to support life in the first place. Adding more carbon dioxide to the atmosphere strengthens that heat-trapping effect. This mechanism is the physical reason a rising CO2 trend and a rising temperature trend are expected to move together, rather than being two unrelated lines that simply happen to rise in the same years.` },
    { loId: 'm6sci.evidence-for-rising-global-temperatures', content: `STRONG EVIDENCE FOR AN ASSOCIATION NEEDS THREE THINGS TOGETHER. First, each record must show a sustained trend across many decades, not a single-year blip. Second, the timing of the fastest rise in each record must line up with the timing of the sharpest scale-up in human fossil-fuel combustion. Third, there must be a known physical mechanism -- carbon dioxide's heat-trapping property -- that explains why the two would rise together. Two records rising over the same stretch of decades, by themselves, are not enough on their own: plenty of unrelated things can rise over the same span purely by coincidence. It is trend, matching timing, and mechanism together that make the case strong, not any one of the three alone, and not simply how many people repeat the conclusion.` },
    { loId: 'm6sci.evidence-for-rising-global-temperatures', content: `WHAT THIS EVIDENCE DOES, AND DOES NOT, ESTABLISH. Reading the records this way supports the conclusion that Earth's warming trend over the past century is real and is associated with the rise in human fossil-fuel use. It does not, by itself, predict next year's weather at any one place, and it says nothing about what should be done in response -- proposing or evaluating a response is a different lesson.` },
    { loId: 'm6sci.evidence-for-rising-global-temperatures', kind: 'definition', title: 'trend', content: `a sustained direction seen across many readings taken over time, as distinct from any single reading.` },
    { loId: 'm6sci.evidence-for-rising-global-temperatures', kind: 'definition', title: 'atmospheric carbon dioxide (CO2)', content: `a gas in the atmosphere, measured directly today and reconstructed from ice for earlier periods, that absorbs some of Earth's outgoing heat.` },
    { loId: 'm6sci.evidence-for-rising-global-temperatures', kind: 'definition', title: 'greenhouse effect', content: `the trapping of some of Earth's outgoing heat by gases including carbon dioxide, which keeps Earth's surface warmer than it would otherwise be.` },
    { loId: 'm6sci.evidence-for-rising-global-temperatures', kind: 'definition', title: 'fossil fuel', content: `coal, oil, or natural gas, burned by people for energy, releasing carbon dioxide that had been stored out of the atmosphere for a very long time.` },
    { loId: 'm6sci.evidence-for-rising-global-temperatures', kind: 'definition', title: 'association', content: `a relationship in which two things reliably rise or fall together, supported here by a matching trend, matching timing, and a known mechanism connecting them.` },
  ],
  methods: [
    {
      title: 'Worked reading the temperature index',
      steps: [
        `First, read the direction from one decade to the next: 100, then 101, then 102, then 104, then 108, then 115. Every single step is an increase. Across all six decades, the index never once goes down.`,
        `A rise that holds across six separate decades, with no reversal, is a genuine multi-decade trend, not a single-reading blip -- this is exactly the kind of evidence a single year could never provide by itself.`,
        `Now compute how much the index changes from one decade to the next, to see whether the pace is steady or changing: 101 - 100 = 1; 102 - 101 = 1; 104 - 102 = 2; 108 - 104 = 4; 115 - 108 = 7.`,
        `Read the five differences in order: 1, 1, 2, 4, 7. The differences themselves are getting bigger, not staying the same. That means the index is not just rising -- it is rising FASTER in the more recent decades than it did in the earliest ones.`,
        `WRONG: "The index went up in every decade, so the rate of increase must be about the same throughout." CORRECT: "The index went up in every decade, and the SIZE of each decade's increase grew over time, from 1 in the earliest decades to 7 in the most recent one, so the rise has been speeding up."`,
        `Run the three-clues check, since there is no equation to work backward through here. First, a consistency clue: every one of the five decade-to-decade steps is upward, with no exception across the whole six-decade span. Second, a magnitude clue, independent of the first: the size of the increases themselves grows over time (1, 1, 2, 4, 7), which is a second and separate way the data show acceleration, not merely persistence. Third, a shape clue: this pattern -- comparatively flat early, then rising faster later -- matches the general shape of the real, published temperature record, without needing to state any of its actual numbers.`,
        `Now change the input and check that the answer moves with it. Suppose the index had instead read 100, 105, 103, 108, 104, 110 -- up, then down, then up, then down, then up. That record would NOT show a genuine trend, because the direction reverses rather than holding across the six decades; no conclusion about warming could be drawn from a record shaped like that, however far the last number sits above the first.`,
      ],
      example: { problem: `A simplified temperature index is reported for six decades, from the early 1900s to recent decades. The index numbers, oldest to most recent, are: 100, 101, 102, 104, 108, 115. There is no real unit here; the numbers are invented for this exercise to carry the correct shape of the real record. Does this record show a genuine multi-decade trend, and if so, is the pace of that trend speeding up, slowing down, or steady?`, solution: `Yes, this is a genuine multi-decade warming trend: the index rises in every one of the six decades with no reversal. The pace is also speeding up, not steady -- the decade-to-decade increases grow from 1 to 1 to 2 to 4 to 7, so the rise has been faster in the most recent decades than in the earliest ones.` },
      relatedLoIds: ['m6sci.evidence-for-rising-global-temperatures'],
    },
    {
      title: 'Worked comparing temperature and co2 timing',
      steps: [
        `Read the CO2 index's direction the same way as before: 100, 100, 101, 104, 110, 121. It never decreases across any of the six decades -- a second genuine multi-decade trend, by the same test used on the temperature index.`,
        `Compute the decade-to-decade increases: 100 - 100 = 0; 101 - 100 = 1; 104 - 101 = 3; 110 - 104 = 6; 121 - 110 = 11.`,
        `Read the five differences in order: 0, 1, 3, 6, 11. Just like the temperature index, the CO2 index is not just rising -- it is rising faster over time, and it is doing so in the SAME later decades: the temperature increases jumped from small (1, 1) to much larger (2, 4, 7) starting at the fourth decade, and the CO2 increases jumped from small (0, 1) to much larger (3, 6, 11) starting at that same fourth decade. That is a timing match between the two records, not just two separate trends that both happen to rise somewhere in the six decades.`,
        `Bring in the history: large-scale fossil-fuel combustion scaled up sharply beginning around the middle of the 1900s, as coal use kept growing and oil and natural gas use expanded worldwide alongside rapid industrial growth. That is the same stretch of decades where both indexes' increases jump from small to much larger.`,
        `Bring in the mechanism from the concept segment: carbon dioxide absorbs some of the heat Earth radiates outward, trapping it near the surface. That known mechanism is WHY a rise in CO2 would be expected to cause more warming, rather than the two trends merely happening to occur in the same years.`,
        `WRONG: "The temperature index and the CO2 index both went up over the six decades, so one must be the entire explanation for the other." CORRECT: "The two sustained trends, their matching acceleration timing, and the independently known heat-trapping property of carbon dioxide together support an association; the rise in the two indexes alone, without the timing match and the mechanism, would be much weaker evidence."`,
        `Run the three-clues check, using three genuinely different kinds of evidence. First, a consistency clue, within each record on its own: neither index ever reverses across the six decades. Second, a timing clue, comparing the two records to each other: both indexes' increases jump from small to large starting in the same later decade, matching the era when fossil-fuel combustion itself scaled up. Third, a mechanism clue, independent of both records: carbon dioxide's known heat-trapping property gives a physical reason the two would rise together, not merely an observed coincidence.`,
        `Now change one input and check that the conclusion moves with it. Suppose the CO2 index had instead stayed flat at 100 across all six decades while the temperature index still rose the way it did. The timing match would be gone, and there would be no reason from this evidence to connect the temperature trend to CO2 specifically, even though the temperature trend itself would still be real. Take away the matching timing, or take away the mechanism, and the case for an association gets much weaker -- which is exactly why this lesson checks for all three rather than stopping at "both went up."`,
      ],
      example: { problem: `Alongside the temperature index from the previous problem, a simplified CO2 index is reported for the same six decades, oldest to most recent: 100, 100, 101, 104, 110, 121. Again, there is no real unit; the numbers are invented to carry the shape of the real record. Using both records together, evaluate whether the data support an association between the rising CO2 trend and the rising temperature trend, and whether that association fits with the history of human fossil-fuel use.`, solution: `Yes: both indexes show a genuine multi-decade trend, both accelerate in the same later decades, that timing matches the historical scale-up of fossil-fuel combustion, and carbon dioxide's known heat-trapping property supplies the mechanism connecting the two. Trend, matching timing, and mechanism together support an association between rising CO2 from human fossil-fuel use and the rising temperature trend -- not simply two lines that happen to move at the same time.` },
      relatedLoIds: ['m6sci.evidence-for-rising-global-temperatures'],
    },
  ],
  pointers: [
    { content: `Students often say "It was unusually cold where I live last winter, so global warming cannot be real." — One unusually cold winter at one place is a single reading, in one location, over one season. It does not test the global multi-decade record at all. A genuine warming trend is established only by looking at temperature records across many decades and across the whole globe, not by any single place's single season -- and a real long-term warming trend can still include individual cold winters at individual places, in the same way a rainy-climate region can still have a dry week without its climate description being wrong.`, kind: 'common-error' },
    { content: `Students often say "Carbon dioxide is only a small fraction of the atmosphere, so it cannot possibly cause a big change in temperature." — Nitrogen makes up about 78 percent of the atmosphere and oxygen about 21 percent, leaving carbon dioxide as a small fraction of the total -- that part is true. But nitrogen and oxygen do not trap outgoing heat the way carbon dioxide does, so the amount of the atmosphere a gas takes up is not what decides its effect; its specific heat-trapping property is. A small quantity of something can still have a large effect if it has a strong specific property: a small amount of dye placed in a large tank of water is still enough to change the color of the whole tank, because color-changing is a property of the dye itself, not something that requires a large quantity of it.`, kind: 'common-error' },
    { content: `A trend requires a sustained direction across many decades of records. A single year, warmer or colder than usual, is one reading, not a trend, in either direction.`, kind: 'tip' },
    { content: `Earth's temperature record and the atmospheric CO2 record both show the same shape over the past century and more: comparatively flat early on, then rising, fastest in the most recent decades.`, kind: 'tip' },
    { content: `Carbon dioxide absorbs some of the heat Earth radiates outward and traps it near the surface -- the greenhouse effect. Adding more CO2 strengthens that trapping, which is the mechanism connecting the two rising trends.`, kind: 'tip' },
    { content: `Strong evidence for an association needs three things together: a sustained trend in each record, matching timing between the two records and with the scale-up of fossil-fuel combustion, and a known mechanism connecting them. Any one of the three alone is weaker.`, kind: 'tip' },
    { content: `Two trends rising over the same span, a conclusion resting on how many people state it, or a model's future prediction, are each weaker forms of support than trend, timing and mechanism taken together.`, kind: 'tip' },
    { content: `This evidence establishes that Earth's warming trend is real and is associated with human fossil-fuel use. It does not by itself predict next year's weather or say what to do in response.`, kind: 'tip' },
    { content: `A trend is NOT one warm year or one cold year. You need many decades of readings all going the same direction (mostly up, with no reversals) to call it a trend. One outlier year proves nothing about climate.`, kind: 'common-error' },
    { content: `Don't say "CO₂ causes warming" without also checking: (1) Does temperature actually rise over many decades? (2) Do both records accelerate in the SAME decades? (3) Is there a known mechanism? All three matter; two trends rising together is not enough.`, kind: 'gotcha' },
    { content: `"Small amount" does not mean "small effect." CO₂ is only ~0.04% of air, but it traps heat very well. A tiny dose of poison or dye can change a whole tank. The gas's heat-trapping property matters, not its percentage of the air.`, kind: 'vocab-note' },
    { content: `The pace of the trend is not steady. Look at the decade-to-decade CHANGES in temperature and CO₂: if those changes get bigger over time (1, 1, 2, 4, 7), the trend is accelerating, not just rising at the same rate the whole way.`, kind: 'tip' },
    { content: `Timing match means both records jump from small increases to big increases in the SAME decades—and those decades match when fossil-fuel use ramped up. That's not a coincidence; it's the timing clue. If CO₂ stayed flat while temp rose, timing wouldn't match.`, kind: 'vocab-note' },
    { content: `Don't mix up your evidence sources. The three clues are: (1) each record's own shape over decades, (2) when both records accelerate relative to each other and history, (3) how CO₂ works physically. Don't use the same clue twice; they must be different kinds of evidence.`, kind: 'edge-case' },
    { content: `This lesson explains why warming and CO₂ are linked over the past 100+ years. It does NOT predict tomorrow's weather at your location, and it does NOT say whether we should burn coal or use solar. Those are separate questions.`, kind: 'edge-case' },
    { content: `The greenhouse effect is natural and keeps Earth livable. Adding MORE CO₂ just strengthens the trapping. Don't confuse 'greenhouse effect exists normally' with 'adding more CO₂ has no extra effect.' More of something that traps heat = more trapping.`, kind: 'common-error' },
  ],
};
