/**
 * Grade 6 Science — Unit 10 CED 10.1: The Carbon Cycle in Rocks, Ocean & Air.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m6sci.the-carbon-cycle-in-rocks-ocean-and-air.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M6SCI_U10_THE_CARBON_CYCLE_IN_ROCKS_OCEAN_AND_AIR: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m6sci.the-carbon-cycle-in-rocks-ocean-and-air.v1',
  course: 'Grade 6 Science',
  cedUnit: 10,
  cedTopic: '10.1',
  cedTitle: 'The Carbon Cycle in Rocks, Ocean & Air',
  planId: 'evelyn.ms.m6sci.the-carbon-cycle-in-rocks-ocean-and-air.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-03',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m6sci.the-carbon-cycle-in-rocks-ocean-and-air.v1' }],
  theory: [
    { loId: 'm6sci.the-carbon-cycle-in-rocks-ocean-and-air', content: `CARBON IS STORED IN THREE BIG RESERVOIRS. A RESERVOIR is just a place where something is stored for a while. Carbon on Earth is stored in three huge reservoirs: the ATMOSPHERE, where it exists mostly as carbon dioxide gas; the OCEAN, where a large amount of carbon is dissolved directly in the water; and the GEOSPHERE, where carbon is locked inside solid rock, mostly as carbonate rock such as limestone. Just like a rock moving through the rock cycle, carbon does not sit still in any one reservoir forever -- it is always moving along one pathway or another.` },
    { loId: 'm6sci.the-carbon-cycle-in-rocks-ocean-and-air', content: `GEOSPHERE TO ATMOSPHERE: VOLCANIC OUTGASSING. Deep inside Earth, some carbon is trapped in rock and in melted rock. When a volcano erupts, it releases gas from deep underground straight into the sky, and carbon dioxide is part of that gas. This pathway, carbon moving from the geosphere into the atmosphere through an eruption, is called VOLCANIC OUTGASSING.` },
    { loId: 'm6sci.the-carbon-cycle-in-rocks-ocean-and-air', content: `ATMOSPHERE AND OCEAN TRADE GAS DIRECTLY, IN BOTH DIRECTIONS. At the ocean's surface, carbon dioxide gas from the air can dissolve directly into the water, the same kind of exchange as the fizz in a soda bottle, just far slower and on a far larger scale. That exchange also runs the other way: dissolved carbon already in the ocean can leave the water and enter the air. Which direction wins at a given place and time depends on conditions there, but the exchange itself is always two-way, never a one-way drain in only one direction.` },
    { loId: 'm6sci.the-carbon-cycle-in-rocks-ocean-and-air', content: `ATMOSPHERE TO OCEAN BY WAY OF LAND: CHEMICAL WEATHERING AND RIVERS. Rainwater falling through the atmosphere picks up a small amount of carbon dioxide gas on the way down and becomes slightly acidic. That slightly acidic rainwater slowly reacts with rock on land, and the dissolved carbon it picks up does not stay on land -- rivers carry it onward until it eventually reaches the ocean. This pathway starts in the atmosphere and ends in the ocean, even though rock on land is where the reaction actually happens partway through.` },
    { loId: 'm6sci.the-carbon-cycle-in-rocks-ocean-and-air', content: `OCEAN TO GEOSPHERE: CARBONATE ROCK FORMS ON THE OCEAN FLOOR. Once dissolved carbon and dissolved calcium are both present in ocean water, they can become part of solid calcium carbonate. Over long stretches of time, that solid material can build up on the ocean floor in thick layers and become carbonate rock, such as limestone. That newly formed rock is now carbon stored in the geosphere -- carbon that started the trip as gas in the atmosphere has ended up locked in solid rock.` },
    { loId: 'm6sci.the-carbon-cycle-in-rocks-ocean-and-air', content: `GEOSPHERE BACK TO ATMOSPHERE, THE SLOW WAY: PLATE MOTION CLOSES THE LOOP. Plate motion can carry carbonate rock down into deeper, hotter parts of Earth at certain plate boundaries. There, heat and pressure can break the rock down and free the carbon it has been holding, and that freed carbon can rise and reach the atmosphere again through a later volcanic eruption -- the same outgassing pathway named above, now running on rock that started out as ocean sediment instead of rock that had been underground all along. No reservoir is a permanent trap. Far more carbon is stored in rock than in the ocean and the atmosphere combined, and carbon can stay locked in rock for a far longer stretch of time than it stays in the air or the ocean -- but even rock eventually lets some of it go.` },
    { loId: 'm6sci.the-carbon-cycle-in-rocks-ocean-and-air', kind: 'definition', title: 'reservoir', content: 'a place where something, such as carbon, is stored for a while before moving on.' },
    { loId: 'm6sci.the-carbon-cycle-in-rocks-ocean-and-air', kind: 'definition', title: 'volcanic outgassing', content: `carbon dioxide and other gases moving from deep underground into the atmosphere through a volcanic eruption.` },
    { loId: 'm6sci.the-carbon-cycle-in-rocks-ocean-and-air', kind: 'definition', title: 'chemical weathering', content: `here, rainwater carrying a small amount of atmospheric carbon dioxide reacting slowly with rock on land, producing dissolved carbon that a river can carry away.` },
    { loId: 'm6sci.the-carbon-cycle-in-rocks-ocean-and-air', kind: 'definition', title: 'dissolved carbon', content: `carbon that is mixed directly into liquid water rather than existing as a gas or as part of solid rock.` },
    { loId: 'm6sci.the-carbon-cycle-in-rocks-ocean-and-air', kind: 'definition', title: 'carbonate rock', content: `solid rock, such as limestone, made mostly of calcium carbonate that has built up and hardened over a long stretch of time.` },
  ],
  methods: [
    {
      title: 'Worked volcano to ocean',
      steps: [
        `Identify the starting reservoir. The problem states the carbon dioxide had been trapped deep in rock underground, so it started in the geosphere.`,
        `Name the first move. The volcanic eruption released that trapped gas straight from deep underground into the sky. Carbon moving from the geosphere into the atmosphere through an eruption is volcanic outgassing.`,
        `Name the second move. Once the carbon dioxide was mixed into the air, some of it dissolved directly into the ocean's surface water. Carbon dioxide gas moving from the atmosphere into the ocean by dissolving directly into it is the direct gas exchange between those two reservoirs.`,
        `WRONG: "The carbon dioxide reached the ocean because rainwater carried it there through rock on land." CORRECT: "This story never mentions rain or rock on land -- the gas dissolved directly into the ocean's surface water from the air above it. Rainwater carrying dissolved carbon through rock is a different pathway, used when the story actually describes rain falling on land."`,
        `Now run the two checks a science answer needs, because there is no arithmetic here to redo. First, look for clues of DIFFERENT KINDS that agree. Source: nothing already in the atmosphere produces new carbon dioxide out of nothing, so gas appearing during an eruption has to have come from underground, matching outgassing. Timing: the ocean's carbon dioxide rises gradually over the following weeks rather than all at once, matching a slow surface-to-surface gas exchange rather than a sudden dump of liquid. Setting: the volcano sits along a coastline, so the ocean is right there to receive gas mixed into the nearby air, with no long overland trip needed. Three different kinds of evidence, one answer.`,
        `Second, change one condition and check that the answer moves with it. Picture the same eruption happening deep inland, hundreds of kilometers from any ocean. The carbon dioxide would still leave the geosphere and enter the atmosphere through outgassing, but reaching the ocean afterward would most plausibly happen by a completely different pathway -- carried down eventually by rain and rivers, rather than dissolving directly from nearby air into nearby water. Move the volcano, and the second half of the story has to change with it.`,
      ],
      example: { problem: `A volcano along a coastline erupts. Among the gases shooting high into the sky is carbon dioxide that had been trapped deep in rock underground. Over the following weeks, some of that same carbon dioxide, now mixed into the air, slowly dissolves into the surface waters of the ocean nearby. Trace which reservoirs the carbon passed through, in order, and name the process that moved it at each step.`, solution: `Geosphere to atmosphere by volcanic outgassing, then atmosphere to ocean by direct gas exchange at the ocean's surface.` },
      relatedLoIds: ['m6sci.the-carbon-cycle-in-rocks-ocean-and-air'],
    },
    {
      title: 'Worked limestone and the loop',
      steps: [
        `Start at the atmosphere, since that is where the carbon began. Rainwater falling through the atmosphere picked up a small amount of carbon dioxide gas and became slightly acidic; that slightly acidic rainwater reacted slowly with rock on land, and rivers carried the dissolved carbon it picked up out to the ocean. That is the atmosphere-to-ocean pathway by way of land.`,
        `Continue at the ocean. Once that dissolved carbon was in the ocean, along with dissolved calcium already there, it became part of solid calcium carbonate, which settled on the ocean floor in thick layers over a very long stretch of time and hardened into limestone. That is the ocean-to-geosphere pathway.`,
        `WRONG: "Once carbon becomes part of solid limestone, it is stored there permanently and cannot move again." CORRECT: "No reservoir in this cycle is a permanent trap. Given enough time, carbon locked in rock can be freed again."`,
        `Now answer the permanence question directly. Plate motion can carry rock like this down into deeper, hotter parts of Earth at certain plate boundaries. There, heat and pressure can break the rock down and free the carbon it has been holding, and that freed carbon can reach the atmosphere again through a later volcanic eruption -- the exact same outgassing pathway that starts the cycle over, just running now on rock that began as ocean sediment.`,
        `Run the two checks. First, three clues of different kinds that agree. Composition: the rock is described as calcium carbonate, which matches what forms specifically from dissolved carbon and calcium in ocean water, not from any other pathway. Setting: limestone exposed on a mountainside, far from any ocean today, fits rock that formed somewhere else and was later moved and lifted -- consistent with a very long history rather than a recent, unmoved deposit. Timing: "hundreds of millions of years" fits the geologic time scale this whole cycle runs on, not a scale of days or years. Three different kinds of evidence, one consistent story.`,
        `Second, change one condition and check that the answer moves. Suppose this same limestone were never carried underground by plate motion, and instead stayed sitting exposed at the surface indefinitely. Without heat and pressure acting on it deep underground, that particular slab of rock would not release its carbon through outgassing -- although it could still be weathered at the surface over time, which is a different pathway back toward the ocean. The heat-and-pressure release pathway specifically depends on the rock actually being carried underground; take that condition away, and that particular return path does not happen.`,
      ],
      example: { problem: `A geologist studies a thick layer of limestone exposed on a mountainside, far from any ocean today. She explains that the calcium carbonate making up this rock originally formed from carbon dissolved in ocean water hundreds of millions of years ago. Explain how carbon that started out as gas in the atmosphere could have ended up locked in that rock, and then explain whether that same carbon is trapped there permanently.`, solution: `Atmosphere to ocean by chemical weathering and rivers, then ocean to geosphere as the dissolved carbon becomes part of solid calcium carbonate that hardens into limestone. That carbon is not trapped permanently: plate motion can carry the rock underground, where heat and pressure can free the carbon again and return it to the atmosphere through a later eruption.` },
      relatedLoIds: ['m6sci.the-carbon-cycle-in-rocks-ocean-and-air'],
    },
  ],
  pointers: [
    { content: `Students often say "The ocean only ever soaks up carbon dioxide from the air, it never gives any back." — The exchange at the ocean's surface runs both ways, the same way gas can leave a soda bottle instead of staying dissolved. Carbon dioxide gas from the air can dissolve into the ocean, and dissolved carbon already in the ocean can also leave the water and enter the air. Which direction wins at a given place and time depends on conditions there, but the exchange itself is never a one-way drain in only one direction.`, kind: 'common-error' },
    { content: `Students often say "Once carbon becomes part of a rock, it is locked away forever." — No reservoir in this cycle is a permanent trap. Plate motion can carry carbon-holding rock down into deeper, hotter parts of Earth at certain plate boundaries. There, heat and pressure can break the rock down and free the carbon it has been holding, letting it reach the atmosphere again through a later volcanic eruption. Carbon can stay locked in rock for a far longer stretch of time than it stays in the air or the ocean, but even rock eventually lets some of it go.`, kind: 'common-error' },
    { content: `Carbon is stored in three reservoirs: the atmosphere (mostly as carbon dioxide gas), the ocean (as dissolved carbon), and the geosphere (locked in rock, mostly carbonate rock such as limestone).`, kind: 'tip' },
    { content: `Volcanic outgassing moves carbon from the geosphere into the atmosphere: a volcanic eruption releases carbon dioxide trapped deep underground into the sky.`, kind: 'tip' },
    { content: `The atmosphere and the ocean trade carbon dioxide directly at the ocean's surface, in both directions -- the same kind of exchange as fizz leaving a soda bottle, just far slower and on a far larger scale.`, kind: 'tip' },
    { content: `Chemical weathering moves carbon from the atmosphere to the ocean by way of land: rainwater picks up carbon dioxide, reacts slowly with rock, and rivers carry the dissolved carbon onward to the ocean.`, kind: 'tip' },
    { content: `Dissolved carbon in the ocean can become part of solid calcium carbonate, which builds up on the ocean floor and can harden into carbonate rock, such as limestone -- carbon moving from the ocean into the geosphere.`, kind: 'tip' },
    { content: `Plate motion can carry carbonate rock underground at a plate boundary, where heat and pressure can free its carbon and return it to the atmosphere through a later eruption -- closing the loop.`, kind: 'tip' },
    { content: `No reservoir is a permanent trap for carbon. Far more carbon is stored in rock than in the ocean and atmosphere combined, and it can stay locked in rock far longer than it stays in the air or the ocean, but even rock eventually lets some of it go.`, kind: 'tip' },
    { content: `Don't call the atmosphere-to-ocean exchange a "one-way street." Carbon dioxide goes BOTH ways at the ocean surface — from air into water AND from water back into air. Which direction "wins" depends on conditions, but the exchange itself is always two-way.`, kind: 'common-error' },
    { content: `"Dissolved carbon" is NOT the same as "carbon dioxide gas." Dissolved carbon is mixed INTO liquid water. Carbon dioxide gas floats ABOVE the water. At the ocean surface, gas can switch to dissolved — but they are not the same thing.`, kind: 'vocab-note' },
    { content: `Don't skip naming the process when you trace carbon. Not just "carbon moves from A to B" — always say HOW: volcanic outgassing, direct gas exchange, chemical weathering, or carbonate rock formation. The process name IS the explanation.`, kind: 'tip' },
    { content: `Carbonate rock does NOT lock carbon permanently. Plate motion can drag it underground, heat and pressure can break it, and volcanic outgassing can send the carbon back to the air. No reservoir is a permanent trap — rock is just the longest-term storage.`, kind: 'gotcha' },
    { content: `Chemical weathering needs RAIN to work. Rainwater picks up CO₂ from air, becomes acidic, reacts with rock on land, and rivers carry it away. If there's no rain or land in the story, this pathway doesn't apply — use direct gas exchange instead.`, kind: 'common-error' },
    { content: `Volcanic outgassing brings carbon from DEEP UNDERGROUND into the atmosphere in one jump — not from the surface, not from rock that's already been weathered. The eruption itself is the release mechanism.`, kind: 'vocab-note' },
    { content: `When you trace a pathway, check: Does the story actually mention the things needed? If it names a volcano near the coast but NOT rain or rivers, carbon probably went direct to the ocean, not through land. Let the details guide your answer.`, kind: 'tip' },
    { content: `The three reservoirs hold VERY different amounts of carbon. Far more carbon is locked in rock than in the ocean and atmosphere combined. Rock is slow, but it's the biggest storage tank — remember this when thinking about the whole cycle.`, kind: 'edge-case' },
  ],
};
