/**
 * Grade 6 Science — Unit 5 CED 5.2: Absolute Dating & the Geologic Time Scale.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m6sci.absolute-dating-and-the-geologic-time-scale.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M6SCI_U5_ABSOLUTE_DATING_AND_THE_GEOLOGIC_TIME_SCALE: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m6sci.absolute-dating-and-the-geologic-time-scale.v1',
  course: 'Grade 6 Science',
  cedUnit: 5,
  cedTopic: '5.2',
  cedTitle: 'Absolute Dating & the Geologic Time Scale',
  planId: 'evelyn.ms.m6sci.absolute-dating-and-the-geologic-time-scale.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-03',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m6sci.absolute-dating-and-the-geologic-time-scale.v1' }],
  theory: [
    { loId: 'm6sci.absolute-dating-and-the-geologic-time-scale', content: `RADIOMETRIC DATING GIVES AN AGE IN YEARS, NOT JUST AN ORDER. Unlike the previous lesson, which could only put layers and events in ORDER relative to each other, this lesson produces an actual number of years. It works because a radioactive atom (the PARENT) is unstable and, over time, changes into a different, stable atom (the DAUGHTER). That change happens at a fixed, measurable rate for a given radioactive element, called its HALF-LIFE: the amount of time it takes for exactly half of the parent atoms in a sample to become the daughter atom. A half-life does not speed up or slow down no matter how hot, cold, wet or dry the surroundings are, which is what makes it usable as a clock. This lesson does not explain WHY a parent atom decays -- that mechanism belongs to Grade 8 physical science. What matters here is that the rate is fixed and measurable.` },
    { loId: 'm6sci.absolute-dating-and-the-geologic-time-scale', content: `COUNTING HALF-LIVES GIVES AN AGE. If half of the original parent atoms remain, exactly 1 half-life has passed. If a quarter remain, that is half of a half, so 2 half-lives have passed. If an eighth remain, that is half of a half of a half, so 3 half-lives have passed. Multiply the number of half-lives that have passed by the length of one half-life, in years, and the result is the age of the sample in years.` },
    { loId: 'm6sci.absolute-dating-and-the-geologic-time-scale', content: `TWO METHODS, MATCHED TO MATERIAL. There are several radiometric methods, but this lesson covers the two used most often at this level. CARBON-14 DATING measures the decay of carbon-14 in once-living material -- wood, bone, shell -- and its half-life is about 5,730 years; because that half-life is short, carbon-14 gives reliable ages anywhere from very recent up to about 50,000 years, and past that point too little of it remains to measure accurately. URANIUM-LEAD DATING measures the decay of uranium locked inside minerals that crystallize as igneous rock cools, and its half-life is about 4.5 billion years, which is why it is used for rock rather than organic material, and why it is the method that reaches back hundreds of millions to billions of years. WRONG: "Carbon-14 dating shows this rock is 300 million years old." CORRECT: "Carbon-14 cannot date rock at all, and it cannot measure ages anywhere near 300 million years; a number that large would come from uranium-lead dating of a mineral in the rock, not from carbon-14."` },
    { loId: 'm6sci.absolute-dating-and-the-geologic-time-scale', content: `THE GEOLOGIC TIME SCALE NESTS EON, THEN ERA, THEN PERIOD, LARGEST TO SMALLEST -- similar to how a calendar nests decade, then year, then month. Almost all of Earth's roughly 4.6-billion-year history, before fossils became abundant in the rock record, is grouped as the PRECAMBRIAN. The eon we are still in, the PHANEROZOIC, began about 541 million years ago and is named for its abundant, visible fossils. The Phanerozoic Eon holds three eras: the PALEOZOIC ("ancient life", about 541 million to about 252 million years ago), the MESOZOIC ("middle life", about 252 million to about 66 million years ago, when most dinosaurs lived), and the CENOZOIC ("recent life", about 66 million years ago to today, the age of mammals, including humans). Each era is further split into PERIODS -- the Mesozoic Era's last period, for example, is called the Cretaceous -- but this lesson places an age only down to the ERA, not the period.` },
    { loId: 'm6sci.absolute-dating-and-the-geologic-time-scale', content: `PLACE THE AGE BY COMPARING NUMBERS. Once an age in years is known, compare it to the era boundary years just given: an age that falls between two boundary numbers belongs to the era between them. Two cautions. First, always write every number out in full before comparing -- million and billion look similar side by side in a sentence, but a billion is a thousand times a million, and lining up the zeros is what keeps that difference from disappearing. Second, an age far older than the Phanerozoic's roughly 541-million-year start is not sorted into the Paleozoic, Mesozoic or Cenozoic Era at all -- it falls in the Precambrian instead.` },
    { loId: 'm6sci.absolute-dating-and-the-geologic-time-scale', content: `THE ROUTINE, IN ORDER -- (1) Identify the material: once-living organic material points to carbon-14; a mineral inside igneous rock points to uranium-lead. (2) Get an age in years: either count half-lives from the fraction of parent atoms remaining and multiply by the half-life length, or read an already-computed age straight from a lab report. (3) Check the age against the method's range: a carbon-14 result should be well under about 50,000 years; a uranium-lead result in the hundreds of millions to billions is expected. (4) Place the age on the geologic time scale by comparing it to the era boundary years, after writing every number out in full so millions and billions cannot be confused. (5) Read the placement back and ask whether it makes sense: an igneous rock reported at 1.8 billion years old, for instance, cannot belong to any of the three named eras, because all three sit inside the Phanerozoic's most recent 541 million years.` },
    { loId: 'm6sci.absolute-dating-and-the-geologic-time-scale', kind: 'definition', title: 'radiometric dating', content: `finding the age of an object in years by measuring the decay of a radioactive element it contains.` },
    { loId: 'm6sci.absolute-dating-and-the-geologic-time-scale', kind: 'definition', title: 'half-life', content: `the fixed amount of time it takes for half of the radioactive (parent) atoms in a sample to change into a different, stable (daughter) atom.` },
    { loId: 'm6sci.absolute-dating-and-the-geologic-time-scale', kind: 'definition', title: 'parent atom', content: 'the original radioactive atom in a sample, before it decays.' },
    { loId: 'm6sci.absolute-dating-and-the-geologic-time-scale', kind: 'definition', title: 'daughter atom', content: 'the new, stable atom a parent atom becomes after it decays.' },
    { loId: 'm6sci.absolute-dating-and-the-geologic-time-scale', kind: 'definition', title: 'carbon-14 dating', content: `a radiometric method that measures the decay of carbon-14 in once-living material, reliable for ages up to about 50,000 years.` },
    { loId: 'm6sci.absolute-dating-and-the-geologic-time-scale', kind: 'definition', title: 'uranium-lead dating', content: `a radiometric method that measures the decay of uranium in minerals within igneous rock, used for ages of hundreds of millions to billions of years.` },
    { loId: 'm6sci.absolute-dating-and-the-geologic-time-scale', kind: 'definition', title: 'geologic time scale', content: `the nested system of eons, eras and periods scientists use to organize Earth's history.` },
  ],
  methods: [
    {
      title: 'Worked carbon 14 half life',
      steps: [
        `Step 1, identify the material and method. The tool is wood, once part of a living plant, so carbon-14 dating is the right method -- it measures decay in once-living material, not in rock.`,
        `Step 2, get an age in years. The wood has 1/4 of its original carbon-14 remaining. After 1 half-life, 1/2 remains; after 2 half-lives, half of that half remains: 1/2 x 1/2 = 1/4. So 2 half-lives have passed. Multiply: 2 half-lives x 5,730 years per half-life = 11,460 years. (2 x 5,730 = 11,460.)`,
        `Step 3, check the age against the method's range. Carbon-14 stays reliable up to about 50,000 years, because past that point too little of it remains to measure accurately. 11,460 years is well under 50,000 years, so this result is inside carbon-14's reliable range.`,
        `Step 4, place the age on the time scale. 11,460 years is far smaller than even the Cenozoic Era's span of about 66 million years, so the wood clearly belongs to the Cenozoic Era, right near the present-day end of it -- no comparison to the older Paleozoic or Mesozoic boundaries is even needed once a number this small shows up.`,
        `WRONG: "Since some of the carbon-14 has decayed, this wood could be millions of years old." CORRECT: "Carbon-14 can only measure ages up to about 50,000 years; a measurable amount of carbon-14 remaining tells us the wood is thousands of years old, not millions."`,
        `Step 5, read the answer back with the two checks a science answer needs, because there is no equation to work backward here. First, clues of DIFFERENT KINDS that agree: the fraction remaining (1/4) gives 2 half-lives; the material (once-living wood) confirms carbon-14 is the right tool; the size of the answer (11,460 years, far under 50,000) confirms the result sits inside the method's reliable range. Three different kinds of check, one answer. Second, change one thing and see the answer move with it: if only 1/8 of the carbon-14 remained instead of 1/4, that would be 3 half-lives (1/2 x 1/2 x 1/2 = 1/8), for an age of 3 x 5,730 = 17,190 years -- still comfortably inside the 50,000-year range and still Cenozoic, but a different, larger number than before, exactly as it should be.`,
      ],
      example: { problem: `A wooden tool found buried at an old campsite is tested for carbon-14. The lab reports that exactly one-quarter of the wood's original carbon-14 is still present; the rest has already decayed into nitrogen. Carbon-14's half-life is about 5,730 years. How old is the wood, and which era of the geologic time scale does it belong to?`, solution: `The wood is about 11,460 years old (2 half-lives x 5,730 years = 11,460 years), well inside carbon-14's reliable range, and it belongs to the Cenozoic Era.` },
      relatedLoIds: ['m6sci.absolute-dating-and-the-geologic-time-scale'],
    },
    {
      title: 'Worked uranium lead and era placement',
      steps: [
        `Step 1, identify the material and method. This is igneous rock -- rock that cooled from magma or lava -- so uranium-lead dating is the right method, not carbon-14; uranium-lead's half-life of about 4.5 billion years is built for spans this large, while carbon-14 would have run out of measurable carbon-14 within the first 50,000 years of this rock's history.`,
        `Step 2, get an age in years. The lab has already converted the measured uranium-to-lead ratio into an age for us: about 1.8 billion years. (Turning a ratio that is not a clean fraction like 1/2 or 1/4 into an exact age uses math beyond this lesson; a lab instrument does that conversion.)`,
        `Step 3, check the age against the method's range. Uranium-lead dating is used for ages of hundreds of millions to billions of years, and 1.8 billion years sits comfortably inside that range.`,
        `Step 4, place the age on the time scale. Line up the units before comparing anything: 1.8 billion years is 1,800,000,000 years, and the oldest Phanerozoic boundary given is 541 million years, or 541,000,000 years. Since 1,800,000,000 is much larger than 541,000,000, the rock is much older than the start of the Phanerozoic Eon, so it does not belong to the Paleozoic, Mesozoic or Cenozoic Era at all -- it formed during the Precambrian, the span before the Phanerozoic began.`,
        `A number worth seeing, just for scale: how much of Earth's roughly 4.6-billion-year history came before the Phanerozoic even started? 4,600,000,000 years minus 541,000,000 years is 4,059,000,000 years, or about 4.06 billion years. This rock, at 1.8 billion years, sits well inside that huge Precambrian stretch, nowhere near the three named eras.`,
        `WRONG: "The rock is 1.8 billion years old, so it must belong to the Paleozoic Era, since that is the oldest era listed." CORRECT: "The Paleozoic Era only reaches back to about 541 million years ago. An age of 1.8 billion years is far older than that, so the rock predates the entire Phanerozoic Eon, and none of the three named eras applies."`,
        `Step 5, read the answer back with the two checks. First, clues of DIFFERENT KINDS that agree: the material (igneous rock, not organic) points to uranium-lead; the size of the number (1.8 billion, far past any Phanerozoic boundary) points to a time before the Phanerozoic; and the definition of the Precambrian (everything before the Phanerozoic) is exactly where a number like this belongs. Second, change one thing and check the answer moves: if the lab had instead reported 68 million years, that number falls between the Mesozoic's boundaries of about 252 million and about 66 million years ago, so the rock would land in the Mesozoic Era instead of the Precambrian -- a much smaller age lands in a much later part of the time scale, exactly as it should.`,
      ],
      example: { problem: `A geologist collects a sample of solid igneous rock. A lab test of the uranium locked inside one of its minerals reports a uranium-lead age of about 1.8 billion years. Using the era boundaries -- Paleozoic Era: about 541 million to about 252 million years ago; Mesozoic Era: about 252 million to about 66 million years ago; Cenozoic Era: about 66 million years ago to today -- say whether this rock belongs to one of the three Phanerozoic eras, and if not, say what that means.`, solution: `The rock is about 1.8 billion years old. Because that is far older than the Phanerozoic Eon's start at about 541 million years ago, the rock belongs to the Precambrian rather than to the Paleozoic, Mesozoic or Cenozoic Era.` },
      relatedLoIds: ['m6sci.absolute-dating-and-the-geologic-time-scale'],
    },
  ],
  pointers: [
    { content: `Students often say "Carbon-14 dating showed the dinosaur bone is 230 million years old." — Carbon-14 becomes unreliable after about 50,000 years, because so little of it is left by then that it cannot be measured accurately. A dinosaur bone this old -- dinosaurs lived in the Mesozoic Era, tens to hundreds of millions of years ago -- needs a method built for much larger spans, such as uranium-lead dating of minerals in nearby igneous rock. Carbon-14 cannot produce a number like 230 million years at all.`, kind: 'common-error' },
    { content: `Students often say "After two half-lives, all of a sample's radioactive atoms are completely gone." — Half-life means half of whatever is LEFT decays each time, not half of the original amount every time. After 1 half-life, half remains (1/2). After 2 half-lives, half of that half remains (1/4), not zero. The amount keeps shrinking by half, getting smaller and smaller, but it never mathematically reaches exactly zero -- it just eventually gets too small to measure.`, kind: 'common-error' },
    { content: `Radiometric dating gives an age in YEARS; relative dating (the previous lesson) gives only an ORDER.`, kind: 'tip' },
    { content: `A half-life is the fixed time it takes for half of a sample's parent atoms to decay into daughter atoms. It never speeds up or slows down.`, kind: 'tip' },
    { content: `Multiply the number of half-lives that have passed by the length of one half-life to get an age in years.`, kind: 'tip' },
    { content: `Carbon-14 dating (half-life about 5,730 years) works on once-living material and stays reliable up to about 50,000 years.`, kind: 'tip' },
    { content: `Uranium-lead dating (half-life about 4.5 billion years) works on minerals in igneous rock and reaches back hundreds of millions to billions of years.`, kind: 'tip' },
    { content: `The geologic time scale nests eon, then era, then period. The Phanerozoic Eon (started about 541 million years ago) holds the Paleozoic, Mesozoic and Cenozoic Eras; everything before it is the Precambrian.`, kind: 'tip' },
    { content: `Place an age by comparing it to the era boundary numbers, after writing every number out in full so millions are never confused with billions.`, kind: 'tip' },
    { content: `This lesson does not explain WHY an atom decays -- that mechanism is Grade 8 physical science.`, kind: 'tip' },
  ],
};
