/**
 * Grade 7 World Geography — Unit 7 CED 7.3: Latin America: Economy & Cities.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m7geo.latin-america-economy-and-cities.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M7GEO_U7_LATIN_AMERICA_ECONOMY_AND_CITIES: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m7geo.latin-america-economy-and-cities.v1',
  course: 'Grade 7 World Geography',
  cedUnit: 7,
  cedTopic: '7.3',
  cedTitle: 'Latin America: Economy & Cities',
  planId: 'evelyn.ms.m7geo.latin-america-economy-and-cities.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-08-21',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m7geo.latin-america-economy-and-cities.v1' }],
  theory: [
    { loId: 'm7geo.latin-america-economy-and-cities', content: `THE REGION SELLS RAW PRODUCTS AND MANUFACTURED GOODS, AND YOU HAVE TO SAY BOTH HALVES. Farms and mines across Latin America send out coffee, soybeans, beef, bananas, copper and oil, among many other things. Those are primary activity, straight out of Unit 5. But factories in the region also build cars, appliances, machinery, electronics and aircraft, and that manufacturing matters especially in Mexico and in Brazil. Calling Latin America a place that only digs things up and grows things is an out-of-date cartoon, and it is the first thing to drop. AND THE REGION IS NOT ONE ECONOMY EITHER. It holds many countries, and they do not earn a living the same way. Chile has large copper mines. Brazil and Argentina grow and ship a great deal of soybeans and beef. Brazil and Colombia grow coffee. Several Caribbean island economies depend heavily on visitors and on the services that visitors need. Mexico and Brazil run large manufacturing industries. One sentence cannot cover all of that, so do not try to write one.` },
    { loId: 'm7geo.latin-america-economy-and-cities', content: `EARNING MOST OF YOUR EXPORT INCOME FROM A FEW PRODUCTS IS RISKY, AND THIS IS THE ANALYTICAL HEART OF THE LESSON. A COMMODITY is a raw product that is bought and sold on a world market at a world price, such as copper, oil, coffee or soybeans. No single country sets that price. So when the world price of a commodity drops, a country that earns most of its export money from that one commodity loses income all at once -- and because export earnings pay for imported goods, for government services and for the jobs connected to that industry, the fall reaches far past the mine or the farm itself. Spreading the earnings across more products and more industries is called DIVERSIFICATION, and it is the standard answer to this risk. Now the part that is not optional: this RISK IS NOT A RANK. It is a statement about how income is spread, exactly like the indicators in Unit 5, and it is not a score for a country or for anybody who lives there. Higher-income and lower-income describe economies. The words third world, backward, primitive, advanced and civilized describe people instead, and this course does not use them.` },
    { loId: 'm7geo.latin-america-economy-and-cities', content: `LATIN AMERICA IS HIGHLY URBANIZED, WHICH SURPRISES ALMOST EVERYONE. Remember from Unit 3 that urbanization is a SHARE. In this region that share is high: a large majority of the people live in cities and towns rather than in the countryside. The region contains a number of very large metropolitan areas, among them Mexico City, Sao Paulo, Buenos Aires, Lima and Bogota. We are not putting those in order and we are not attaching numbers to them. The point is simply that great big cities are an ordinary feature of this region, not an exception in it.` },
    { loId: 'm7geo.latin-america-economy-and-cities', content: `A PRIMATE CITY IS ONE CITY THAT IS FAR LARGER THAN ANY OTHER IN ITS COUNTRY AND THAT CONCENTRATES ALMOST EVERYTHING. Government offices, company headquarters, the main airport, the university everyone has heard of, and the roads and rail lines that all bend toward the same place. Several countries in this region have that pattern, and it is common elsewhere in the world too. Two warnings. A primate city is not the same thing as a capital city: those often overlap, but the capital of Brazil is Brasilia, while Sao Paulo is a separate and very large city, and Brazil contains several very large cities rather than a single one that dwarfs the rest. And primate is a description of size and concentration, not a compliment.` },
    { loId: 'm7geo.latin-america-economy-and-cities', content: `WHEN CITIES GREW FASTER THAN HOUSING WAS BUILT, PEOPLE BUILT HOUSING THEMSELVES. Rural-to-urban migration and city-born children pushed many cities in the region to grow very quickly, and construction of homes, water pipes, sewers and paved roads did not keep pace. So new neighborhoods went up on the edges of cities and on steep hillsides, built by the residents themselves, often before any piped water or paved street reached them. Geographers call these INFORMAL SETTLEMENTS, meaning they were built outside the official planning and permit process. State the facts plainly: residents built these homes and improved them over years, many of these neighborhoods are well organized, they run their own associations and businesses, and in a great many cases water, electricity, transport and legal ownership have been extended to them since. This is a story about how fast housing can be built. It is not a story about what anybody is like.` },
    { loId: 'm7geo.latin-america-economy-and-cities', content: `LOCATION STILL SHAPES TRADE HERE, EXACTLY AS UNIT 5 SAID IT WOULD. A canal cut across the narrow waist of Central America, in Panama, joins the Atlantic Ocean side to the Pacific Ocean side. Before it existed, a ship going between the two oceans had to sail all the way around the southern end of South America. The canal removes that entire journey, which is why so much shipping is funneled through one narrow lane of water. That is the same idea as the straits and passes in Unit 5, drawn at regional size: geography decides where trade piles up.` },
    { loId: 'm7geo.latin-america-economy-and-cities', kind: 'definition', title: 'commodity', content: `a raw product such as copper, oil, coffee or soybeans that is bought and sold on a world market at a world price.` },
    { loId: 'm7geo.latin-america-economy-and-cities', kind: 'definition', title: 'export concentration', content: `a situation in which most of the export income of a country comes from only one or a few products.` },
    { loId: 'm7geo.latin-america-economy-and-cities', kind: 'definition', title: 'diversification', content: `spreading the earnings of an economy across more products and industries so that no single price controls the result.` },
    { loId: 'm7geo.latin-america-economy-and-cities', kind: 'definition', title: 'primate city', content: `a city that is far larger than any other city in its country and concentrates government, business and transport.` },
    { loId: 'm7geo.latin-america-economy-and-cities', kind: 'definition', title: 'informal settlement', content: `a neighborhood built by its own residents outside the official planning and permit process, common where cities grew faster than housing was built.` },
    { loId: 'm7geo.latin-america-economy-and-cities', kind: 'definition', title: 'canal', content: 'a waterway dug across land so that ships can pass between two bodies of water.' },
  ],
  methods: [
    {
      title: 'Worked export concentration',
      steps: [
        `Start with what a world price is. Neither country sets it. A commodity price is set on a world market, so both countries wake up to the same lower price and neither one chose it.`,
        `Look at Aldera. Nearly all of its export income came from that mineral. When the price falls, nearly all of its export income falls with it. There is nothing else earning to cushion it.`,
        `Now follow the fall past the mine, because this is the part students skip. Export earnings are what a country uses to pay for imported goods, and taxes on that industry help pay for government services, and the trucking companies, ports and repair shops that serve the mine all depend on it running at full speed. So a price set somewhere else reaches schools, hospitals and shops that never touched the mineral. That is why concentration is a whole-economy problem, not a mining problem.`,
        `Now look at Ravela. The same mineral price fell for Ravela too, so it loses income as well. But three other earners are still working, and their prices did not move. The hit is real and it is smaller, and the rest of the economy keeps running.`,
        `Name the difference correctly. This is EXPORT CONCENTRATION in Aldera versus DIVERSIFICATION in Ravela. It is a description of how income is SPREAD, and nothing else.`,
        `Now the sentence that must not be skipped. WRONG: "Ravela is more advanced than Aldera." CORRECT: "Ravela is less exposed to a fall in the price of that one mineral than Aldera is." One of those describes an economy. The other one ranks countries, and this course does not rank countries. Notice also that Aldera did nothing foolish -- a country mines what is in the ground under it.`,
      ],
      example: { problem: `Two invented countries sit in the same region and both export a great deal. Work out which one is more exposed when a world price falls, and be careful to say what that does and does not mean.

"Country Aldera earns nearly all of its export income from one mineral, which it digs up and ships out. Country Ravela earns its export income from four different things: a mineral, two farm crops, and finished goods from its factories. This year the world price of that one mineral drops sharply. It is the same mineral in both countries."`, solution: `Aldera is more exposed, because nearly all of its export income depends on the single price that fell, and export earnings pay for imports, government services and the jobs connected to that industry. Ravela loses income too, but three other earners are unaffected. The correct way to state the difference is export concentration versus diversification, which describes how income is spread and does not rank either country against the other.` },
      relatedLoIds: ['m7geo.latin-america-economy-and-cities'],
    },
    {
      title: 'Worked read a city pattern',
      steps: [
        `Take the first question apart. A primate city needs two things: it is far larger than any other city in the country, AND it concentrates the important functions.`,
        `Check the size test. The description says far more people live there than in any other city in Verano and that the next city down is a small fraction of its size. Size test passed.`,
        `Check the concentration test. Government, the main international airport, the main cargo seaport, and the head offices of nearly every large company are all in the same city. Concentration test passed. So yes, this is a primate city.`,
        `Careful with what that does NOT mean. It does not mean Verano has only one city, and it does not mean the city is well run or badly run. Primate describes size and concentration. It is not praise and it is not criticism.`,
        `Now the second question. Read the growth sentences: many families moved in from rural districts over several decades, and neighborhoods went up on the slopes, built by the residents, without piped water or paved streets at first.`,
        `Say what that shows in the right order. People arrived faster than homes, pipes and roads were built, so residents built homes themselves on land at the edges and on the hillsides. Those are INFORMAL SETTLEMENTS, meaning built outside the official planning process. The last sentence matters as much as the rest: water lines and bus routes have since reached most of them, which is a very common pattern.`,
        `WRONG way to describe this: anything about what the residents are like. CORRECT way: a statement about how fast housing supply moved compared with how fast the city grew.`,
      ],
      example: { problem: `Read this description of an invented country and answer two questions: is the city described a primate city, and what does the description tell you about how fast it grew?

"In the country of Verano, one city holds the national government, the main international airport, the seaport that handles most cargo, and the head offices of nearly every large company. Far more people live there than in any other Verano city, and the next city down is a small fraction of its size. Over the past several decades many families moved in from rural districts. Neighborhoods spread up the slopes above the city, built by the families who live in them, and for years many of those streets had no piped water and no pavement. Water lines and bus routes have since reached most of them."`, solution: `Yes, it is a primate city: it is far larger than any other city in Verano and it concentrates the government, the main airport, the main cargo port and most company head offices. The hillside neighborhoods show that people arrived faster than housing, water pipes and paved roads were built, so residents built homes themselves outside the official planning process, and services have since been extended to most of those neighborhoods.` },
      relatedLoIds: ['m7geo.latin-america-economy-and-cities'],
    },
  ],
  pointers: [
    { content: `Students often say "Latin America is a poor region that just sells raw materials to richer countries." — Take the three apart. FIRST, the region is not one economy: it holds many countries, and mining, large-scale farming, factory manufacturing and tourism-and-service economies all sit inside it. Chile has large copper mines, Brazil and Argentina ship soybeans and beef, several Caribbean island economies depend heavily on visitors and services, and Mexico and Brazil run large manufacturing industries that build cars, machinery, electronics and aircraft. SECOND, the commodity half is only half. Saying the region only sells raw materials leaves out the factories entirely. THIRD, and this is the important one, poor and rich are not the categories here. WRONG: "That region is behind." CORRECT: "Some economies there earn most of their export income from a small number of commodities, which leaves them exposed when a world price falls." The second sentence describes how income is spread. The first one ranks places, and this course measures economies and never scores them.`, kind: 'common-error' },
    { content: `Students often say "The biggest cities are all national capitals." — Capital means the seat of government and nothing more. Primate city means far larger than any other city in the country and concentrating business, transport and services. Those two often land on the same city, but they do not have to. Brasilia is the capital of Brazil, and Sao Paulo is a separate and very large city. It also runs the other way: Brazil contains several very large cities rather than a single one that dwarfs all the rest, so not every country has a primate city at all. Check the two tests separately every time, and do not put cities in order of size, because that is a number nobody in this course is asking you for.`, kind: 'common-error' },
    { content: `The region exports farm and mineral commodities AND manufactures goods. Say both halves, and remember it is many different economies, not one.`, kind: 'tip' },
    { content: 'A commodity has a world price that no single country sets.', kind: 'tip' },
    { content: `Export concentration means most export income comes from a few products, so a fall in one world price hits the whole economy. Diversification is the answer to it.`, kind: 'tip' },
    { content: `Concentration is a risk, not a rank. Describe how income is spread; never score a country or its people.`, kind: 'tip' },
    { content: `Latin America is highly urbanized: a large majority of its people live in cities and towns.`, kind: 'tip' },
    { content: `A primate city is far larger than any other city in its country and concentrates government, business and transport. It is not the same thing as a capital city.`, kind: 'tip' },
    { content: `Where cities grew faster than housing, residents built neighborhoods themselves on edges and hillsides, and services have often been extended to them since.`, kind: 'tip' },
    { content: `The canal across Panama joins the Atlantic and Pacific sides and saves ships the voyage around the southern end of South America. Location still decides where trade piles up.`, kind: 'tip' },
    { content: `Never write "Latin America only sells raw materials." Say **both halves**: farms and mines export coffee, copper, soybeans, beef and oil, AND factories in Mexico and Brazil build cars, machinery, electronics and aircraft.`, kind: 'common-error' },
    { content: `Don't write one sentence for the whole region. It holds many economies: Chile's copper, Brazil and Argentina's soybeans and beef, Caribbean tourism and services, Mexican and Brazilian manufacturing. Name specific countries when you answer.`, kind: 'gotcha' },
    { content: `Export concentration is a **risk, not a rank**. Write "Aldera is more exposed to a fall in that one price," never "Aldera is behind" or "less advanced." The words third world, backward and primitive are not used in this course.`, kind: 'vocab-note' },
    { content: `Primate city ≠ capital city. Capital only means the seat of government. Check the two primate tests separately: far larger than any other city, AND concentrating government, business and transport. Brasília is Brazil's capital; São Paulo is the huge city.`, kind: 'gotcha' },
    { content: `Some countries have **no** primate city. Brazil has several very large cities rather than one that dwarfs the rest, so it fails the size test. If the next city down is not a small fraction of the biggest, don't use the term.`, kind: 'edge-case' },
    { content: `When a commodity price falls, don't stop at the mine. Say that export earnings pay for imports, taxes fund government services, and ports, trucking and repair shops depend on the industry — so shops and schools feel it too.`, kind: 'common-error' },
    { content: `Describe informal settlements as a **housing-speed** fact, never a fact about the people. Correct: "the city grew faster than homes, pipes and roads were built." Also add the ending: services and legal ownership have often been extended since.`, kind: 'vocab-note' },
    { content: `Urbanization is a **share**, not a count of big cities. Saying Latin America is highly urbanized means a large majority of people live in cities and towns. Don't rank Mexico City, São Paulo, Lima and Bogotá by size — no numbers are asked for.`, kind: 'tip' },
  ],
};
