/**
 * Grade 7 World Geography — Unit 8 CED 8.2: Europe & Russia: History & Culture.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m7geo.europe-history-and-culture.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M7GEO_U8_EUROPE_HISTORY_AND_CULTURE: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m7geo.europe-history-and-culture.v1',
  course: 'Grade 7 World Geography',
  cedUnit: 8,
  cedTopic: '8.2',
  cedTitle: 'Europe & Russia: History & Culture',
  planId: 'evelyn.ms.m7geo.europe-history-and-culture.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-08-21',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m7geo.europe-history-and-culture.v1' }],
  theory: [
    { loId: 'm7geo.europe-history-and-culture', content: `THE REGION, AND WHAT THIS LESSON IS ACTUALLY DOING. This unit covers Europe together with Russia, because Russia stretches from eastern Europe across northern Asia, with the Ural Mountains usually taken as the dividing line between the two continents. Europe alone holds more than forty countries. Our job today is not to learn a story of the past in order. Our job is to look at things you could notice right now -- which language people speak, which letters they write with, which buildings stand in the middle of a city -- and explain why each one sits where it sits. History shows up in this lesson only as an answer to a question that starts with the word why.` },
    { loId: 'm7geo.europe-history-and-culture', content: `MOST EUROPEAN LANGUAGES BELONG TO ONE FAMILY, IN THREE BIG BRANCHES, AND ONE BRANCH EXPLAINS ITSELF. Back in the language unit you learned that a language family is a group of languages descended from one ancestor language. Most languages of Europe belong to the Indo-European family, and inside that family they gather into three large branches that sit in different parts of the region. GERMANIC languages are spoken across the north and northwest: English, German, Dutch, Danish, Swedish, Norwegian and Icelandic. ROMANCE languages are spoken across the southwest and south: Spanish, Portuguese, French, Italian and Romanian. SLAVIC languages are spoken across the east: Russian, Polish, Czech, Ukrainian, Bulgarian and Serbian. Those branches are geographic clumps, not a scattering, and the Romance clump is the one with the cleanest explanation. Romance languages are all descended from Latin, the language of the Roman Empire. The empire ran the lands around the western Mediterranean for centuries, and Latin traveled with its soldiers, officials, roads and schools. After the empire ended, the everyday Latin spoken in each area kept changing on its own, and over many generations those local versions drifted far enough apart to become separate languages. That is descent, not borrowing -- the same distinction from the language unit. And the branch is not a neat block: Romanian is a Romance language sitting in eastern Europe, well away from the others, because Latin reached that area too.` },
    { loId: 'm7geo.europe-history-and-culture', content: `TWO ALPHABETS, AND A CULTURAL BOUNDARY YOU CAN SEE ON A SIGN. Much of Europe writes with the LATIN alphabet, the twenty-six letters on your keyboard, which came from the Romans along with Latin itself. Much of eastern and southeastern Europe writes with the CYRILLIC alphabet, a different set of letters. Greece uses a third, the Greek alphabet. Here is the useful part. The alphabet split lines up broadly with which branch of Christianity spread into an area. Where Roman Catholic Christianity spread from Rome, the Latin alphabet came with it. Where Eastern Orthodox Christianity spread from the Greek-speaking Byzantine world, Cyrillic came with it -- the alphabet is named after Cyril, a missionary from that world. That is why Polish and Czech are Slavic languages written in Latin letters while Russian, Ukrainian and Bulgarian are Slavic languages written in Cyrillic. Two neighbors can speak closely related languages and still write them in different letters. In the borders unit this is called a cultural boundary: a line that follows a difference between people rather than a river or a ruler-straight line. It is a boundary you can see on a street sign today, put there by something that happened long ago.` },
    { loId: 'm7geo.europe-history-and-culture', content: `THE RELIGIOUS MAP, DESCRIBED PLAINLY AND FROM THE OUTSIDE. Christianity has been the most widespread religion in Europe historically, and it has three large branches that are concentrated in different parts of the region. ROMAN CATHOLIC Christianity is the historically most widespread branch across southern Europe, including Italy, Spain and Portugal, and also in countries such as Poland and Ireland. PROTESTANT branches, which began with a movement in the fifteen hundreds called the Reformation, took hold mainly across northern Europe, including the Scandinavian countries and parts of Germany and Britain. EASTERN ORTHODOX Christianity is the historically most widespread branch across eastern and southeastern Europe, including Russia, Greece, Bulgaria, Serbia and Romania. Other religions have long and continuing presences here as well: Islam has been present in parts of Europe for many centuries, and Muslim communities live across the region today, and Jewish communities have lived in Europe for many centuries and are part of Europe today. Many people in Europe follow no religion at all. Every sentence in this key idea is a statement about WHERE, and nothing more. We describe beliefs and practices as the people who hold them describe them. We do not decide whether any of them is right, and we never rank one against another. That is not what geography does.` },
    { loId: 'm7geo.europe-history-and-culture', content: `TWO MOVEMENTS THAT EXPLAIN WHAT A CITY LOOKS LIKE, AND ONE WARNING. The RENAISSANCE was a movement in art and learning that began in the Italian city-states in the thirteen and fourteen hundreds and spread across Europe, and it is a large part of why so many European cities have old art museums, painted churches and historic centers that visitors travel to see. Universities in the region are old too: the University of Bologna in Italy has been operating since the ten hundreds. The INDUSTRIAL REVOLUTION was the shift to making goods in factories with powered machines. It began in Britain in the seventeen hundreds and spread across parts of western and central Europe, usually taking hold near coal fields, rivers and ports, because that is where the fuel and the shipping were. That is why regions such as northern England and the Ruhr area of western Germany are still lined with factory towns, canals and old mine works. Now the warning, and it is the most important sentence in this lesson. None of this makes Europe ahead of anywhere else, and geography never makes that kind of claim. Every world region has its own long record of art, learning, building and invention. Explaining WHERE something happened and WHY it happened there is geography. Deciding that it makes one place better than another is not geography at all, and it is not true.` },
    { loId: 'm7geo.europe-history-and-culture', content: `EUROPE AND RUSSIA ARE NOT ONE CULTURE, AND NO SINGLE COUNTRY IS EITHER. Start with the languages the three branches leave out, because not every language here is Indo-European at all. Finnish, Estonian and Hungarian belong to the Uralic family. Basque, spoken in a region on both sides of the border between Spain and France, is not known to be related to any other language on Earth. Add it up: more than forty countries, three large language branches plus languages that belong to no branch at all, several alphabets and many religious traditions do not make one way of living. Look inside a single country and the same thing happens again. Switzerland has four national languages: German, French, Italian and Romansh. Russia is home to many peoples and many languages besides Russian, including Tatar, which belongs to the Turkic family rather than the Indo-European one. People have also moved to Europe from every part of the world, and large European cities are home to communities with roots across Africa, Asia, the Americas and the rest of Europe, which adds more languages, foods and traditions to places that already had many. Any sentence that begins with the words Europeans are is already wrong, because the region contains far too many different people for that sentence to finish honestly.` },
    { loId: 'm7geo.europe-history-and-culture', kind: 'definition', title: 'language branch', content: `a smaller group inside a language family, holding languages that are more closely related to each other than to the rest of the family.` },
    { loId: 'm7geo.europe-history-and-culture', kind: 'definition', title: 'Romance languages', content: `the branch of Indo-European languages descended from Latin, including Spanish, Portuguese, French, Italian and Romanian.` },
    { loId: 'm7geo.europe-history-and-culture', kind: 'definition', title: 'Cyrillic alphabet', content: `the set of letters used to write Russian and several other languages of eastern and southeastern Europe.` },
    { loId: 'm7geo.europe-history-and-culture', kind: 'definition', title: 'cultural boundary', content: `a boundary that follows a difference between people, such as a difference in language, alphabet or religion.` },
    { loId: 'm7geo.europe-history-and-culture', kind: 'definition', title: 'Renaissance', content: `a movement in art and learning that began in the Italian city-states in the thirteen and fourteen hundreds and spread across Europe.` },
    { loId: 'm7geo.europe-history-and-culture', kind: 'definition', title: 'Industrial Revolution', content: `the shift to making goods in factories with powered machines, which began in Britain in the seventeen hundreds and spread.` },
  ],
  methods: [
    {
      title: 'Worked read the language map',
      steps: [
        `Sort first, explain second. Swedish and Dutch are Germanic. Portuguese and Italian are Romance. Polish is Slavic. Finnish belongs to none of the three, because Finnish is not an Indo-European language at all.`,
        `Now put the sorted list next to the directions given. Germanic is north and northwest. Romance is southwest and south. Slavic is east. The branches are clumps on the map, and each clump sits in one part of the region.`,
        `Take the Romance clump, because it is the one with a clean explanation. Portuguese and Italian both descended from Latin, the language of the Roman Empire, which controlled the lands around the western Mediterranean for centuries. Latin traveled with the empire, then kept changing separately in each area after the empire ended, and the local versions became separate languages.`,
        `Be careful about what kind of relationship that is. Portuguese and Italian are similar because they DESCENDED from the same ancestor language, not because Portugal and Italy traded words with each other. That is the descent-versus-borrowing test from the language unit.`,
        `Now handle Finnish, because a good answer says what does not fit. Finland sits in northern Europe surrounded by Germanic-speaking neighbors, but Finnish belongs to the Uralic family, along with Estonian and Hungarian. A regional pattern is a pattern, not a rule with no exceptions.`,
        `State the limit out loud. This is six languages out of a great many. Sorting the big branches is a starting point for reading the map, never a claim that everyone inside a branch shares one way of living.`,
      ],
      example: { problem: `Here are six languages and where each is widely spoken. Sort them into branches, then explain why the branches sit where they do.

Swedish: Sweden, in the north. Dutch: the Netherlands, in the northwest. Portuguese: Portugal, in the southwest. Italian: Italy, in the south. Polish: Poland, in the east. Finnish: Finland, in the north.`, solution: `Germanic in the north and northwest: Swedish and Dutch. Romance in the southwest and south: Portuguese and Italian, both descended from the Latin that spread with the Roman Empire and then changed separately in each area. Slavic in the east: Polish. Finnish fits none of the three, because it is Uralic rather than Indo-European.` },
      relatedLoIds: ['m7geo.europe-history-and-culture'],
    },
    {
      title: 'Worked read a city',
      steps: [
        `Do not guess yet. List the four things plainly: an old cathedral, a Renaissance art museum, a brick factory district with a coal canal, and a street of shops and restaurants with roots in several parts of the world.`,
        `Take the cathedral. A large old Christian building in the middle of a European city reflects the fact that Christianity has been the most widespread religion in Europe historically. Which branch of Christianity is most widespread nearby depends on which part of the region the city sits in: Roman Catholic across much of the south, Protestant branches across much of the north, Eastern Orthodox across much of the east and southeast. Notice what we just did. We located a pattern. We did not say anything about whether any belief is right, because that is not a geography question.`,
        `Take the museum. Renaissance paintings hang there because the Renaissance began in the Italian city-states and spread across Europe as a movement in art and learning. That is why old art museums and painted churches are a common feature of European city centers today. One sentence of past explains one present-day building.`,
        `Take the factory district and the canal. Factories with powered machines spread across parts of Europe during the Industrial Revolution, which began in Britain, and they clustered near coal, rivers and ports because that is where the fuel and the shipping were. The canal in this city carried coal, so Vellham is exactly that kind of place, and its brick district is what is left standing.`,
        `Take the last street. People have moved to Europe from every part of the world, and large cities hold communities with roots across many continents. Those shops and restaurants are part of the city now, not an addition to it, and they are one of the reasons the cultural map keeps changing.`,
        `Say the limit, because it matters. Vellham is one invented city. A town in the Scandinavian north, a village in southern Italy and a city on the Russian plain would each give you a different walk. Explaining one place is not describing a region of more than forty countries, and nothing here tells you what any person who lives there is like.`,
      ],
      example: { problem: `Walk through an invented European city called Vellham and trace each part of it back to what put it there.

In the center stands a stone cathedral several hundred years old. A few streets away, an art museum holds paintings made during the Renaissance. Down by the river sits a district of long brick buildings that used to be textile factories, beside a canal that once carried coal. On the next street, shops and restaurants are run by families with roots in West Africa, South Asia and eastern Europe.`, solution: `The cathedral traces to the long presence of Christianity in Europe, with the branch depending on which part of the region the city sits in. The museum traces to the Renaissance, which began in the Italian city-states and spread. The brick factories and coal canal trace to the Industrial Revolution, which began in Britain and took hold near coal, rivers and ports. The shops and restaurants trace to people moving to Europe from many parts of the world. Each is one present-day thing explained by one reason -- and Vellham is a single invented city, not a whole region.` },
      relatedLoIds: ['m7geo.europe-history-and-culture'],
    },
  ],
  pointers: [
    { content: `Students often say "Europe is basically one culture -- European." — WRONG: Europe is one culture. CORRECT: Europe alone holds more than forty countries. Its languages fall into three large branches that sit in different parts of the region -- Germanic, Romance and Slavic -- plus languages that belong to none of them, such as Finnish, Estonian, Hungarian and Basque. Several alphabets are in daily use, including Latin, Cyrillic and Greek. Several branches of Christianity are concentrated in different areas, Islam and Judaism have long and continuing presences, and many people follow no religion. The variety repeats inside single countries too: Switzerland has four national languages, and Russia is home to many peoples and languages besides Russian. A region is an area geographers group together for one reason, never a claim that everyone inside it lives the same way.`, kind: 'common-error' },
    { content: `Students often say "Since the Renaissance and the Industrial Revolution happened there, Europe was ahead of everywhere else." — WRONG: those movements mean Europe was ahead of everywhere else. CORRECT: geography explains where something happened and why it happened in that spot, and it stops there. The Industrial Revolution took hold near coal fields, rivers and ports because that is where the fuel and the shipping were -- that is a statement about resources and location, not about people. Every world region has its own long record of art, learning, building and invention, and this course covers several of them. Ranking regions or the people in them is not a geographic finding, it is not measurable, and it is not true. Ask why here and not there. Never ask who is better.`, kind: 'common-error' },
    { content: `Most European languages are Indo-European and gather into three branches that sit in different parts of the region: Germanic in the north and northwest, Romance in the southwest and south, Slavic in the east. Finnish, Estonian, Hungarian and Basque are not in any of the three.`, kind: 'tip' },
    { content: `Romance languages sit where they sit because they all descended from Latin, which spread with the Roman Empire and then changed separately in each area over many generations.`, kind: 'tip' },
    { content: `Much of the west writes with the Latin alphabet and much of the east writes with Cyrillic, and that split lines up broadly with where Roman Catholic and Eastern Orthodox Christianity spread. It is a cultural boundary you can see on a street sign today.`, kind: 'tip' },
    { content: `Christianity has been the most widespread religion in Europe historically, with Roman Catholic, Protestant and Eastern Orthodox branches concentrated in different areas. Islam and Judaism have long and continuing presences, and many people follow no religion. Geography says where; it never evaluates a religion.`, kind: 'tip' },
    { content: `The Renaissance is a large part of why European cities have old art museums and historic centers, and the Industrial Revolution, which began in Britain, is why regions near coal, rivers and ports are still lined with factory towns.`, kind: 'tip' },
    { content: `Europe and Russia are not one culture, and neither is any single country in them. Switzerland has four national languages, Russia has many peoples and languages besides Russian, and people from every part of the world live in European cities. Any sentence starting Europeans are is already wrong.`, kind: 'tip' },
    { content: `Language branch ≠ alphabet. Polish and Russian are both Slavic, but Polish uses Latin letters and Russian uses Cyrillic. Sort by branch first, then ask separately which alphabet the area writes with — the two questions have different answers.`, kind: 'common-error' },
    { content: `"Romance language" has nothing to do with love or romance. It means "descended from Latin" — the language of Rome. Spanish, Portuguese, French, Italian and Romanian are the ones on our list.`, kind: 'vocab-note' },
    { content: `Say **descended from**, not **borrowed from**. Spanish and Italian resemble each other because both grew out of Latin, not because Spain and Italy traded words. Descent = same ancestor language; borrowing = words passed between neighbors.`, kind: 'vocab-note' },
    { content: `The three branches are patterns, not rules. Finnish, Estonian and Hungarian are Uralic, and Basque isn't known to be related to any language on Earth. Romanian is Romance but sits way east of the other Romance languages. A good answer names the exceptions.`, kind: 'edge-case' },
    { content: `Russia sits in both Europe and Asia — the Ural Mountains are the usual dividing line. Don't call Russia "an Asian country" or "a European country" as if you must pick one.`, kind: 'gotcha' },
    { content: `Explaining where the Renaissance or Industrial Revolution happened is geography. Saying it made Europe "ahead" of other regions is not. Factories clustered near coal, rivers and ports — that's about fuel and shipping, not about people. Ask *why here*, never *who is better*.`, kind: 'common-error' },
    { content: `Never start a sentence with "Europeans are…" Europe alone has 40+ countries, several alphabets and many religions — and one country can hold many cultures too. Switzerland has four national languages; Russia has Tatar and many others besides Russian.`, kind: 'gotcha' },
    { content: `When you name a religious branch, describe **where** it is most widespread — nothing more. "Eastern Orthodox is historically most widespread in Russia, Greece and Bulgaria" is geography. Judging or ranking beliefs is not, and neither is assuming everyone there is religious.`, kind: 'tip' },
  ],
};
