/**
 * Grade 7 World Geography — Unit 7 CED 7.2: Latin America: History & Culture.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m7geo.latin-america-history-and-culture.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M7GEO_U7_LATIN_AMERICA_HISTORY_AND_CULTURE: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m7geo.latin-america-history-and-culture.v1',
  course: 'Grade 7 World Geography',
  cedUnit: 7,
  cedTopic: '7.2',
  cedTitle: 'Latin America: History & Culture',
  planId: 'evelyn.ms.m7geo.latin-america-history-and-culture.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-08-21',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m7geo.latin-america-history-and-culture.v1' }],
  theory: [
    { loId: 'm7geo.latin-america-history-and-culture', content: `THE REGION, AND WHERE ITS NAME CAME FROM. Latin America is the name for Mexico, Central America, the Caribbean islands and South America taken together, which is the same region you studied in the last lesson. The name points at the languages: Spanish, Portuguese and French all grew out of Latin, so the whole region was named Latin America after those languages, and the name stuck. That is worth noticing, because it is how region names usually work. A region name is a label people chose, and it highlights one part of a place while leaving other parts out. This name says nothing about the indigenous languages of the region or about its African heritage, and both are here.` },
    { loId: 'm7geo.latin-america-history-and-culture', content: `INDIGENOUS PEOPLES CAME FIRST AND ARE STILL HERE. Indigenous peoples have lived in this region for thousands of years, and they live here now. Long before any European ship arrived, large states had already been built: the MAYA in parts of what is now southern Mexico and Central America, the AZTEC, who called themselves the MEXICA, in central Mexico, and the INCA along the Andes in western South America. The Mexica capital, Tenochtitlan, stood on an island in a lake, and Mexico City stands on that same ground today. Cusco, the Inca capital high in the Andes of Peru, is a working city right now. And the languages did not stop: Quechua and Aymara are spoken in the Andes, Nahuatl and Mayan languages in Mexico and Central America, and Paraguay has two official languages, Spanish and Guarani, which is an indigenous language of the region.` },
    { loId: 'm7geo.latin-america-history-and-culture', content: `COLONIZATION IS WHY THE LANGUAGES ARE WHERE THEY ARE TODAY. Starting in the late 1400s, European countries took control of land and people across the region. That is what colonization means: one country taking control of another place, its resources and the people living there. Spain took control of most of the mainland. Portugal took control of what is now Brazil. That single fact is the reason Spanish is the most widely spoken language across much of the region today and Portuguese is the language of Brazil. It is also why Roman Catholicism, the form of Christianity the Spanish and Portuguese brought, became the most widespread religion in the region. Other European countries colonized parts of the Caribbean and the northern coast of South America, which is why French is spoken in Haiti, English in Jamaica, and Dutch in Suriname.` },
    { loId: 'm7geo.latin-america-history-and-culture', content: `AFRICANS WERE BROUGHT HERE BY FORCE. Over several hundred years, millions of people were captured in Africa, carried across the Atlantic Ocean against their will, and sold into slavery in the Americas. This was the TRANSATLANTIC SLAVE TRADE, and in the language of the migration unit it is forced migration -- these people had no choice at any point. Most of them were made to work on plantations growing sugar and other crops, and the largest numbers were taken to the Caribbean islands and to the coast of Brazil. That is exactly where communities of African descent are largest in the region today, and it is why African heritage is central to the culture of those places.` },
    { loId: 'm7geo.latin-america-history-and-culture', content: `THE RESULT IS CULTURAL BLENDING, AND YOU CAN TASTE IT AND HEAR IT. Three sets of traditions ended up in the same places, and over generations they combined. Food: corn, beans, chili peppers, potatoes and cacao were grown in the Americas long before contact, while cattle, pigs, wheat and cheese arrived with Europeans, and dishes across the region use both. Music: in Brazil, samba grew out of communities of African descent, and its drumming and rhythms have roots in West and Central Africa, while many instruments in the same bands came from Europe and some, such as the maraca, were already in use in the Americas. Religious practice blends too. In Mexico, Day of the Dead falls at the start of November on days that also sit on the Roman Catholic calendar, and families remember relatives who have died with altars, flowers, photographs and foods that person liked -- an observance that joins Catholic practice with traditions that were in the region long before.` },
    { loId: 'm7geo.latin-america-history-and-culture', content: `THE REGION IS NOT ONE CULTURE, AND SAYING SO IS THE POINT. Latin America holds many different countries and territories, several major languages plus many indigenous languages, and climates that run from the Amazon rainforest to high cold Andean valleys to Caribbean islands to the dry far south. The blend is different everywhere: a highland Andean town, a city neighborhood in Sao Paulo, a Caribbean island and a village in southern Mexico do not share one way of living. Anything that begins with the words people in Latin America are is already wrong, because the region contains far too many different people for that sentence to finish honestly.` },
    { loId: 'm7geo.latin-america-history-and-culture', kind: 'definition', title: 'indigenous peoples', content: `the peoples who were living in a region first and whose communities and languages continue there today.` },
    { loId: 'm7geo.latin-america-history-and-culture', kind: 'definition', title: 'colonization', content: `one country taking control of another place, its resources and the people who live there, and settling its own people there.` },
    { loId: 'm7geo.latin-america-history-and-culture', kind: 'definition', title: 'transatlantic slave trade', content: `the forced movement of millions of people from Africa across the Atlantic Ocean, where they were sold into slavery in the Americas.` },
    { loId: 'm7geo.latin-america-history-and-culture', kind: 'definition', title: 'cultural blending', content: `what happens when traditions from different sources come together in one place over generations and combine into new languages, foods, music and customs.` },
    { loId: 'm7geo.latin-america-history-and-culture', kind: 'definition', title: 'official language', content: `a language a country names for use in its government, its courts and its schools.` },
  ],
  methods: [
    {
      title: 'Worked language pattern',
      steps: [
        `Start by sorting, not explaining. Five European languages appear in this short list: Spanish, Portuguese, French, English and Dutch. Haitian Creole is the sixth language named, and it is not European. Five European languages, all in one region.`,
        `Ask the geographer question: what do the places sharing a language have in common? Mexico and Colombia are both on the mainland, and Spain took control of most of the mainland. So Spanish is there because Spanish colonizers settled there and ran the government and the schools in Spanish.`,
        `Brazil breaks the pattern for one reason. Portugal, not Spain, colonized what is now Brazil. Same mechanism, different colonizing country, so a different language. Brazil is not an exception to the rule -- it is the rule working exactly as stated.`,
        `Now the three smaller cases. France, Britain and the Netherlands colonized different islands and stretches of coast, and each left its own language behind in the places it controlled. Haiti was colonized by France, Jamaica by Britain, Suriname by the Netherlands.`,
        `Look harder at Haiti, because it shows the next step. Haitian Creole is the everyday language of Haiti. Much of its vocabulary comes from French, but it developed in Haiti among people who had been brought there by force from Africa, and it is a language in its own right, not a version of French. A blended history produced a language that belongs to that place.`,
        `Last, say what the list leaves out. None of these is an indigenous language, but indigenous languages are spoken across the region every day: Quechua and Aymara in the Andes, Nahuatl and Mayan languages in Mexico and Central America, and Guarani, which is an official language of Paraguay alongside Spanish. A list of the biggest languages is not a list of all the languages.`,
      ],
      example: { problem: `Here is the language most widely spoken in six places in the region. Explain the pattern -- why each language ended up where it did.

Mexico: Spanish. Colombia: Spanish. Brazil: Portuguese. Haiti: Haitian Creole, with French also an official language. Jamaica: English. Suriname: Dutch.`, solution: `Each European language sits where the country that spoke it took colonial control: Spain across most of the mainland, Portugal in Brazil, France in Haiti, Britain in Jamaica, the Netherlands in Suriname. Haitian Creole shows the blending that followed, and indigenous languages such as Quechua, Aymara, Nahuatl, Mayan languages and Guarani are still everyday languages the list does not show.` },
      relatedLoIds: ['m7geo.latin-america-history-and-culture'],
    },
    {
      title: 'Worked trace the blend',
      steps: [
        `Do not guess yet. List the parts plainly: drums and samba rhythms, guitars and brass instruments, black beans, pork, rice, oranges.`,
        `Take the music first. Samba grew out of communities of African descent in Brazil, and its drumming and rhythms have roots in West and Central Africa. Ask why those communities are on this coast at all, and the answer is the transatlantic slave trade: people were taken there by force, and the largest numbers went to the Caribbean and to coastal Brazil.`,
        `Now the instruments beside the drums. Guitars and brass instruments came from Europe, arriving with Portuguese colonization and staying. The same band is playing two histories at once.`,
        `Now the food. Beans were grown in the Americas long before European contact. Pigs came with Europeans. Oranges and rice are not native to the Americas either, and both arrived after European contact. One plate, more than one source.`,
        `Name the idea. This is cultural blending: elements from indigenous, European and African sources combining over generations into something that belongs to this place and is not any one of the three by itself.`,
        `Finish with the limit, because it matters. This scene is a coastal Brazilian festival. It is not Latin America in general. A highland Andean town or a village in southern Mexico blends a different set of sources in a different way, and no single festival stands in for a region of many different countries.`,
      ],
      example: { problem: `A street festival in a coastal city in Brazil has drum groups playing samba, singers using guitars and brass instruments, and food stalls selling black beans cooked with pork, served with rice and slices of orange. Trace each part back to where it came from, and name what the whole scene shows.`, solution: `The drums and samba rhythms trace to African heritage carried to coastal Brazil by the forced migration of the transatlantic slave trade; the guitars, brass and pork came with European colonization, and oranges and rice also arrived after European contact; the beans were grown in the Americas long before contact. Together they are cultural blending -- and they describe one coastal city, not a whole region.` },
      relatedLoIds: ['m7geo.latin-america-history-and-culture'],
    },
  ],
  pointers: [
    { content: `Students often say "Latin America is one culture and everybody there speaks Spanish." — WRONG: Latin America is one culture and everybody speaks Spanish. CORRECT: the region holds many different countries and territories. Portuguese is the language of Brazil, the most populous country in the region. Haitian Creole and French are spoken in Haiti, English in Jamaica, Dutch in Suriname, and indigenous languages such as Quechua, Aymara, Nahuatl, Mayan languages and Guarani are spoken every day. The climates run from Amazon rainforest to high Andean valleys to Caribbean islands to the dry far south, and the way traditions blend is different in each. A region is an area geographers group together for one reason, never a claim that everyone inside it lives the same way.`, kind: 'common-error' },
    { content: `Students often say "The indigenous peoples of the region are all in the past." — WRONG: indigenous peoples of the region belong to the past. CORRECT: indigenous peoples have lived in this region for thousands of years and live here now, in every part of it. Mayan languages are spoken in Guatemala and southern Mexico, Quechua and Aymara in the Andes, Nahuatl in Mexico, and Guarani is an official language of Paraguay alongside Spanish. States such as the Maya kingdoms, the Mexica state and the Inca empire ended, but the peoples did not. Say what actually happened -- a state ended -- and keep the people in the present tense, where they are.`, kind: 'common-error' },
    { content: `Indigenous peoples have lived in this region for thousands of years and live here today. The Maya, the Mexica or Aztec, and the Inca built large states before any European arrived, and indigenous languages such as Quechua, Aymara, Nahuatl, Mayan languages and Guarani are spoken now.`, kind: 'tip' },
    { content: `Spanish is the most widely spoken language across much of the region and Portuguese is the language of Brazil because Spain colonized most of the mainland and Portugal colonized what is now Brazil. Roman Catholicism became widespread the same way.`, kind: 'tip' },
    { content: `French, English and Dutch appear in parts of the Caribbean and the northern coast of South America for the same reason: France, Britain and the Netherlands colonized those places.`, kind: 'tip' },
    { content: `Millions of Africans were taken across the Atlantic by force through the transatlantic slave trade, most of them to the Caribbean and coastal Brazil. African heritage is central to the culture of those places today.`, kind: 'tip' },
    { content: `Cultural blending is the result: food, music, language and religious practice that combine indigenous, European and African elements into something that belongs to the place it grew in.`, kind: 'tip' },
    { content: `The region is not one culture. Many different countries and territories, several major languages plus many indigenous languages, and climates from rainforest to high mountains to islands. Any sentence that starts people in Latin America are is already wrong.`, kind: 'tip' },
    { content: `Never say indigenous peoples "were" in Latin America. The Maya, Mexica and Inca **states** ended; the **peoples** did not. Mayan languages, Quechua, Aymara, Nahuatl and Guarani are spoken today. Write "the Inca empire ended," not "the Inca disappeared."`, kind: 'common-error' },
    { content: `Brazil speaks Portuguese, not Spanish — and that's not an exception to the rule. Portugal colonized Brazil, Spain colonized most of the rest of the mainland. Same rule, different colonizing country.`, kind: 'gotcha' },
    { content: `"Latin America" is a label people chose, named for languages that grew out of Latin (Spanish, Portuguese, French). The name leaves out indigenous languages and African heritage — but both are absolutely there. A region name never lists everything in the region.`, kind: 'vocab-note' },
    { content: `Any sentence beginning "People in Latin America are..." is already wrong. Say which country, which city, which highland town. A coastal Brazilian festival is not the Andes and not southern Mexico.`, kind: 'common-error' },
    { content: `The transatlantic slave trade was **forced** migration — no choice at any step. Don't call it "moving," "coming over," or "immigration." Those words suggest a decision that nobody made.`, kind: 'vocab-note' },
    { content: `Haitian Creole is its own language, not "bad French" or "a kind of French." Much of its vocabulary comes from French, but it grew in Haiti among people brought there by force from Africa.`, kind: 'edge-case' },
    { content: `Not every non-native food came from Europe. Oranges and rice arrived after European contact too. Corn, beans, chili peppers, potatoes and cacao are the Americas ones. Check each ingredient separately instead of splitting the plate in half.`, kind: 'gotcha' },
    { content: `African heritage is strongest in the Caribbean and coastal Brazil for a geographic reason: that's where the largest numbers of enslaved people were taken to work sugar plantations. Tie the culture back to the place, not to chance.`, kind: 'tip' },
  ],
};
