/**
 * Grade 7 World Geography — Unit 10 CED 10.2: South & East Asia: History & Culture.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m7geo.south-and-east-asia-culture.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M7GEO_U10_SOUTH_AND_EAST_ASIA_CULTURE: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m7geo.south-and-east-asia-culture.v1',
  course: 'Grade 7 World Geography',
  cedUnit: 10,
  cedTopic: '10.2',
  cedTitle: 'South & East Asia: History & Culture',
  planId: 'evelyn.ms.m7geo.south-and-east-asia-culture.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-08-21',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m7geo.south-and-east-asia-culture.v1' }],
  theory: [
    { loId: 'm7geo.south-and-east-asia-culture', content: `START WITH THE ONE SENTENCE THAT MATTERS MOST: NO SINGLE DESCRIPTION COVERS THIS REGION. South Asia, East Asia and Southeast Asia together hold dozens of countries, hundreds of languages, religious traditions of every kind, and climates that run from cold northern grassland to high mountain valleys to tropical islands. A village in a mountain valley, a fishing town on an island and a neighborhood in a huge city do not share one way of living. So there is no such thing as one Asian culture, and any sentence that begins with the words people in Asia are is already wrong before it finishes. Everything below is a pattern with a reason, never a rule about everybody. And remember what a regional lesson is for: we are explaining why a present-day pattern sits where it does, not learning a story of the past in order.` },
    { loId: 'm7geo.south-and-east-asia-culture', content: `THE LANGUAGES, AND WHY THEY SORT THE WAY THEY DO. Back in the language unit you learned that a language family is a group of languages descended from one ancestor language. South Asia holds languages from more than one family at the same time. INDO-EUROPEAN languages, the same family that English and Spanish belong to, are widely spoken across the northern part of South Asia: Hindi in northern India, Bengali in Bangladesh and eastern India, and Urdu in Pakistan are examples. DRAVIDIAN languages, which belong to a completely different family, are widely spoken across the south: Tamil and Telugu in southern India are examples. Two great families in one region, in a broad north and south pattern. East Asia is different again. The Chinese languages, including Mandarin, belong to the Sino-Tibetan family, while Japanese and Korean each belong to a different family of their own. Southeast Asia adds more families still, including the Austronesian family you met in the language unit, which includes Indonesian. Hold on to one point here: being in a different family is not being a lesser language. A family is a family tree, not a scoreboard.` },
    { loId: 'm7geo.south-and-east-asia-culture', content: `THE BEST STORY IN THIS LESSON: ONE WRITING SYSTEM, FOUR DIFFERENT ANSWERS. A writing system is a set of signs used to put a language on a page, and here is the thing students almost never expect -- a writing system can be borrowed by a language it is not related to at all. The Chinese writing system, whose characters descend from writing used in China thousands of years ago, spread outward to Japan, to the Korean Peninsula and to Vietnam through long contact: traders, travelers, teachers and scholars who read the same books. And in every one of those places it was ADAPTED rather than simply copied. Japanese is written with those characters together with two additional sets of signs, called hiragana and katakana, that were developed in Japan and stand for syllables. Korean today is written mainly with an alphabet developed on the Korean Peninsula in the fourteen hundreds. Vietnamese today is written with an alphabet built from Latin letters, worked out with European missionaries and made the standard script during the period of French colonial rule. Look at what that adds up to. The same starting point produced four different answers. In the words of the globalization lesson, that is CONVERGENCE and DIVERGENCE happening at once: places became more alike in one detail and then went their own ways in the details underneath. And notice how it happened. This was a cultural boundary drawn by CONTACT -- people reading, trading and traveling -- not by anybody conquering a language.` },
    { loId: 'm7geo.south-and-east-asia-culture', content: `TRADE ROUTES CARRIED IDEAS, AND THEY CARRIED THEM BOTH WAYS. Two great sets of routes tied this region to the rest of the world for a very long time. Overland, the SILK ROADS ran across Central Asia, linking East Asia and South Asia to Southwest Asia and Europe. By sea, ships crossed the Indian Ocean between the coasts of East Africa, Southwest Asia, South Asia and Southeast Asia, and those sailing routes ran on the monsoon: winds that blow one way for part of the year and reverse for the rest, which is exactly the wind pattern you met in the physical geography lesson. Goods moved on those routes, and so did religions and technologies, and this is the part to hold on to -- the movement went in BOTH directions. Ideas that began in South Asia reached East Asia. Papermaking and other technologies developed in China reached Southwest Asia and eventually Europe. Cotton cloth and spices from South and Southeast Asia reached ports in every direction. Influence is not one-directional, and it never was. Ideas about family, education and social order associated with the teaching of Confucius, who lived in China, also spread among societies across East Asia, where they shaped how families, schools and communities were organized. Geographers note where an influence reached and what it touched. Grading it is not a geography question.` },
    { loId: 'm7geo.south-and-east-asia-culture', content: `THE RELIGIOUS MAP, DESCRIBED PLAINLY AND FROM THE OUTSIDE. You already met these traditions in the religions lesson, so this is about WHERE, not about what anybody should believe. BUDDHISM began in South Asia and spread north and east along the overland routes across Central Asia and the sea routes across the Indian Ocean, into Central, East and Southeast Asia, and different schools of it developed in different places along the way. That is a diffusion story, and it explains a pattern that surprises people: a tradition can be widely practiced very far from the region where it began. HINDUISM remains centered in South Asia, and it is widely practiced in India and Nepal. ISLAM is widely practiced across parts of South Asia and across much of Southeast Asia, including Indonesia. Other traditions are practiced throughout the region as well, among them Sikhism and Jainism, which developed in South Asia, and Shinto in Japan, while Christianity is widely practiced in the Philippines. Many people in the region follow no religion at all. Every sentence in this key idea is a statement about where, and nothing more. We describe beliefs and practices the way the people who hold them describe them, we do not decide whether any of them is right, and we never rank one against another.` },
    { loId: 'm7geo.south-and-east-asia-culture', content: `RICE AND SETTLEMENT: THE MOST GEOGRAPHIC PATTERN IN THE REGION. WET-RICE FARMING means growing rice in fields that are flooded with a few inches of water for part of the growing season. It needs flat land, plenty of water and a warm season, which is why it fits river valleys and DELTAS -- the flat, fan-shaped land where a river splits into channels as it reaches the sea -- in the monsoon parts of South, Southeast and East Asia. Two consequences follow, and both are things you can see. First, a flooded rice field produces a great deal of food from a small area, so the same land supports far more people than drier farmland nearby. That is why some of these valleys and deltas hold the densest RURAL settlement anywhere on Earth: villages close together, fields worked right up to the edge of the houses, and terraces cut into the hillsides where the flat ground runs out. Second, the work sets the calendar. Planting waits for the rains, the harvest follows months later, and holidays and market days in many places line up with that year. Rice is also the base of the everyday meal across much of the region. But hold the pattern in its place: this is not the whole region. Wheat and millet are grown across the drier north of China, herding is common on high plateaus and dry interiors, and mountains and cold northern lands support few farms of any kind. One kind of farming explains one kind of place.` },
    { loId: 'm7geo.south-and-east-asia-culture', kind: 'definition', title: 'wet-rice farming', content: `growing rice in fields flooded with shallow water for part of the growing season; it needs flat land, plenty of water and a warm season.` },
    { loId: 'm7geo.south-and-east-asia-culture', kind: 'definition', title: 'delta', content: `the flat, fan-shaped land built up where a river splits into channels as it reaches the sea.` },
    { loId: 'm7geo.south-and-east-asia-culture', kind: 'definition', title: 'monsoon', content: `a wind pattern that blows from one direction for part of the year and reverses for the rest, bringing a wet season and a dry season.` },
    { loId: 'm7geo.south-and-east-asia-culture', kind: 'definition', title: 'Silk Roads', content: `the network of overland trade routes across Central Asia that linked East and South Asia with Southwest Asia and Europe.` },
    { loId: 'm7geo.south-and-east-asia-culture', kind: 'definition', title: 'writing system', content: `the set of signs used to put a language on a page; a language can borrow a writing system from a language it is not related to.` },
    { loId: 'm7geo.south-and-east-asia-culture', kind: 'definition', title: 'adaptation', content: `changing something after it arrives so that it fits the place it arrived in; also called cultural divergence.` },
  ],
  methods: [
    {
      title: 'Worked trace the writing',
      steps: [
        `Sort before you explain. Only Chinese and Japanese use the characters today. Korean and Vietnamese each use an alphabet, and the two alphabets are not the same one.`,
        `Now find the shared starting point, because the sorted list hides it. All four of these languages were written with Chinese characters at some point. The characters spread outward from China to Japan, to the Korean Peninsula and to Vietnam.`,
        `Ask how a writing system travels from one language to a completely different one like that. Not by the languages being related -- Japanese, Korean and Vietnamese are not in the same family as the Chinese languages. It crossed by CONTACT: traders, travelers, teachers and scholars reading the same books over a very long time. A writing system is a tool, and a tool can be picked up by anybody who finds it useful.`,
        `Now explain the differences, one at a time. Japanese kept the characters and added two sets of syllable signs developed in Japan, so it writes with both at once. Korean is written mainly with an alphabet developed on the Korean Peninsula in the fourteen hundreds. Vietnamese is written with an alphabet built from Latin letters, worked out with European missionaries and made standard during the period of French colonial rule.`,
        `Name what just happened with the vocabulary from the globalization lesson. Something spread and made four places more alike -- that is convergence. Then each place changed it to fit its own language, and they ended up different -- that is divergence, or adaptation. Both are true at the same time, and that is the normal result, not a contradiction.`,
        `Say the limit out loud. This explains writing, and writing only. It does not tell you that these places share one culture, and it does not tell you anything at all about what anybody who lives there is like.`,
      ],
      example: { problem: `Here is how four languages are written today. Explain the pattern: what is shared, what is different, and why.

Chinese: written with characters, each standing for a word or a piece of a word.
Japanese: written with those same characters plus two sets of syllable signs developed in Japan.
Korean: written mainly with an alphabet developed on the Korean Peninsula in the fourteen hundreds.
Vietnamese: written with an alphabet built from Latin letters.`, solution: `All four languages were written at some point with Chinese characters, which spread outward through long contact rather than because the languages are related. Each place then adapted the system its own way: Japanese uses the characters plus two sets of syllable signs developed in Japan, Korean uses an alphabet developed on the Korean Peninsula in the fourteen hundreds, and Vietnamese uses an alphabet built from Latin letters. That is convergence in the starting point and divergence in what each place made of it.` },
      relatedLoIds: ['m7geo.south-and-east-asia-culture'],
    },
    {
      title: 'Worked read a delta',
      steps: [
        `List the details plainly first, without explaining anything. Flat land. A river splitting into channels. A long wet season and a long dry season. Villages close together. Flooded fields. Rice at meals. Markets and a holiday timed to the harvest.`,
        `Start with the physical facts, because they come first in the chain. Flat land where a river splits into channels as it meets the sea is a delta. Rain for several months and then almost none is the monsoon pattern from the physical geography lesson.`,
        `Put those two together and you get the farming. Wet-rice farming needs flat land, a lot of water and a warm season. A monsoon delta supplies all three, which is why the fields are flooded rather than dry.`,
        `Now the settlement, which is the geographic payoff. Flooded rice fields produce a great deal of food from a small area, so a small amount of land can feed a lot of people. That is why the villages sit close together instead of spreading out -- dense RURAL settlement, packed with farms rather than with city blocks.`,
        `Then the diet and the calendar, which follow from the same fact. What a place grows in quantity is usually what a place eats, so rice is at nearly every meal. And planting has to wait for the rains, so the harvest lands at a fixed time of year, and the markets and the holiday sit right after it. The year is built around the crop.`,
        `Finish with the limit, and it matters. This chain explains a monsoon delta. Travel inland to a dry plateau, north to where wheat and millet grow, or up into the mountains, and every step of it changes. One kind of farming explains one kind of place, never a whole region.`,
      ],
      example: { problem: `An invented river delta is described below. Explain why each detail is there.

The land is flat for miles and the river splits into many channels before reaching the sea. Heavy rain falls for several months and then almost none falls for several more. Villages sit close together, each surrounded by flooded fields. Rice appears at nearly every meal. The busiest market days of the year come just after the harvest, and the local holiday falls a few weeks later.`, solution: `Flat land where a river splits into channels makes a delta, and the wet-then-dry pattern is the monsoon. Together they suit wet-rice farming, which is why the fields are flooded. Flooded rice fields feed many people from a small area, which is why villages sit close together in dense rural settlement. Rice is grown in quantity, so rice is eaten at most meals, and because planting waits for the rains, the harvest, the markets and the holiday all fall at the same point in the year.` },
      relatedLoIds: ['m7geo.south-and-east-asia-culture'],
    },
  ],
  pointers: [
    { content: `Students often say "South and East Asia all share one Asian culture." — WRONG: there is one Asian culture. CORRECT: no single description covers this region, and saying so is part of the lesson, not a footnote to it. There are dozens of countries and hundreds of languages, drawn from several different language families -- Indo-European and Dravidian in South Asia, Sino-Tibetan and others in East Asia, Austronesian and others in Southeast Asia. Every major religious tradition is practiced here, and many people practice none. The climates run from cold northern grassland to high mountains to tropical islands, and what people grow, eat and build changes with them. A mountain village, an island fishing town and a huge city are not one way of living. Describe the particular place you are actually talking about.`, kind: 'common-error' },
    { content: `Students often say "Japan, Korea and Vietnam basically just copied Chinese culture." — WRONG: they copied it. CORRECT: the Chinese writing system spread through long contact, and every place that received it ADAPTED it. Japanese is written with the characters plus two sets of syllable signs developed in Japan. Korean is written mainly with an alphabet developed on the Korean Peninsula in the fourteen hundreds. Vietnamese is written with an alphabet built from Latin letters. Same starting point, four different answers -- that is convergence and divergence at the same time, exactly as in the globalization lesson. And influence is not one-directional. Ideas that began in South Asia reached East Asia, technologies developed in China reached Southwest Asia and Europe, and goods from South and Southeast Asia reached ports in every direction. Borrowing something is not losing what you had, and it is never evidence that one place ranks above another.`, kind: 'common-error' },
    { content: `No single description covers this region. Dozens of countries, hundreds of languages from several different families, every major religious tradition and many people who follow none. Any sentence that begins people in Asia are is already wrong.`, kind: 'tip' },
    { content: `South Asia holds Indo-European languages such as Hindi, Bengali and Urdu across the north and Dravidian languages such as Tamil and Telugu across the south. East Asia holds the Chinese languages, which are Sino-Tibetan, plus Japanese and Korean, which are not.`, kind: 'tip' },
    { content: `The Chinese writing system spread to Japan, the Korean Peninsula and Vietnam through contact, not conquest, and every place ADAPTED it: characters plus syllable signs in Japan, an alphabet developed on the Korean Peninsula in the fourteen hundreds, and a Latin-based alphabet for Vietnamese today. Convergence and divergence at the same time.`, kind: 'tip' },
    { content: `Overland routes across Central Asia and sea routes across the Indian Ocean carried goods, religions and technologies in BOTH directions, and the Indian Ocean routes ran on the monsoon winds.`, kind: 'tip' },
    { content: `Buddhism began in South Asia and spread north and east along those routes, developing different schools along the way, which is why it is widely practiced far from where it began. Hinduism remains centered in South Asia, and Islam is widely practiced across parts of South Asia and much of Southeast Asia, including Indonesia. Religions are described from the outside and never ranked.`, kind: 'tip' },
    { content: `Wet-rice farming in monsoon valleys and deltas feeds many people from a small area, which is why some of the densest RURAL settlement on Earth is there, and why diet and the yearly calendar are built around the crop. Drier and colder parts of the region grow wheat and millet or support herding instead.`, kind: 'tip' },
    { content: `Never start a sentence with "People in Asia are..." or "Asian culture is...". The region holds dozens of countries, hundreds of languages and every major religion. Name the actual place: "In the Ganges delta...", "In northern China...".`, kind: 'common-error' },
    { content: `Sharing a writing system does NOT mean sharing a language family. Japanese, Korean and Vietnamese all used Chinese characters, but none of them is Sino-Tibetan. A writing system is a borrowed tool, not proof of a family tree.`, kind: 'gotcha' },
    { content: `Say "adapted," not "copied." Japan added hiragana and katakana, Korea developed its own alphabet in the 1400s, Vietnam uses Latin letters. Same starting point, four different answers — that's convergence and divergence at once.`, kind: 'vocab-note' },
    { content: `Influence ran both ways on those routes. South Asian ideas reached East Asia; papermaking from China reached Southwest Asia and Europe. Don't write as if the biggest place only gave and the others only received.`, kind: 'common-error' },
    { content: `A religion's birthplace and where it's practiced today are two different map questions. Buddhism began in South Asia but is widely practiced in East and Southeast Asia; Hinduism stayed centered in South Asia. Answer the one you were asked.`, kind: 'gotcha' },
    { content: `Dense doesn't mean urban. Rice deltas hold some of the densest RURAL settlement on Earth — packed villages and fields, not city blocks. Don't picture skyscrapers when you read "crowded countryside."`, kind: 'vocab-note' },
    { content: `Wet-rice explains one kind of place, not the whole region. Drier northern China grows wheat and millet, high plateaus support herding, and cold or mountainous land supports few farms. Check the climate before you predict the crop.`, kind: 'edge-case' },
    { content: `Describe religions from the outside and never rank them. "Islam is widely practiced in Indonesia" is geography. Deciding which belief is better is not — and neither is treating a different language family as a lesser language.`, kind: 'tip' },
  ],
};
