/**
 * Grade 8 English Language Arts — Unit 2 CED 2.1: How a Theme Develops Through Character & Setting.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8ela.how-a-theme-develops-through-character-and-setting.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8ELA_U2_HOW_A_THEME_DEVELOPS_THROUGH_CHARACTER_AND_SETTING: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8ela.how-a-theme-develops-through-character-and-setting.v1',
  course: 'Grade 8 English Language Arts',
  cedUnit: 2,
  cedTopic: '2.1',
  cedTitle: 'How a Theme Develops Through Character & Setting',
  planId: 'evelyn.ms.m8ela.how-a-theme-develops-through-character-and-setting.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8ela.how-a-theme-develops-through-character-and-setting.v1' }],
  theory: [
    { loId: 'm8ela.how-a-theme-develops-through-character-and-setting', content: `A THEME DEVELOPS, WHICH MEANS IT ARRIVES IN STAGES. On the first line, a theme is only one of several things the story could turn out to mean. By the last line, it is the one thing the story has claimed. So every developed theme has a BEFORE, a TURN and an AFTER. The before is the situation the excerpt opens on, where the story could still go several ways. The after is the ending, where the theme pays off and you can see it plainly. The turn is the single change in between that the after cannot do without. You are handed the theme today. Your job is to find the turn and name it.` },
    { loId: 'm8ela.how-a-theme-develops-through-character-and-setting', content: `THE TURN IS A CHANGE IN A CHARACTER OR A CHANGE IN THE SETTING, AND YOU SAY WHICH. A change in a character means what someone wants, believes, knows or does is different afterward: a boy who forgot the back door every morning starts checking it three times a night. A change in the setting means where or when the story happens shifts, or the rules of the place shift: a lake freezes, a family moves into two rooms, a sign goes up over the one table where two friends talk. The plot is only the order the changes arrive in. Your answer is always one moment and one kind: "the moment the sign goes up, a change in the setting."` },
    { loId: 'm8ela.how-a-theme-develops-through-character-and-setting', content: `A CHANGE IS NOT AN EVENT. An event is something that happens; a change is something that is different afterward. A storm is an event. "After the storm, Leo stops walking the long way home" is a change. The theme rides on the change, and the loudest event in an excerpt is the usual wrong answer, because it is easy to spot and often changes nothing about anyone. You already know the plot has a turning point; the theme's turn is a different thing, and it is often quieter. Ask of every event: what is different in a character or in the place because of this? If nothing is, it moved the plot and left the theme where it was.` },
    { loId: 'm8ela.how-a-theme-develops-through-character-and-setting', content: `THE COVER TEST DECIDES IT. Cover the change you suspect and read the ending again. If the ending still makes the theme's point, that change was not the turn. If the ending now comes from nowhere, or makes a different point, you have found it. Try it: Ana walks the long way home for months to avoid a dog, the dog's owner moves away, and Ana keeps walking the long way. The theme is that a habit can outlive its reason. Cover the owner moving away and the ending means nothing, because there is no reason left for the habit to outlive. The move is the turn, a change in the setting. When changes come in a chain, the turn is the first one the ending cannot do without; everything after it is the theme playing out.` },
    { loId: 'm8ela.how-a-theme-develops-through-character-and-setting', content: `A SETTING CHANGE COUNTS ONLY WHEN IT CHANGES WHAT A CHARACTER CAN DO OR SEE. You already know a setting detail can be scenery. A theme cannot ride on scenery. If the cafeteria gets new paint and everyone eats exactly the way they did before, the paint is not a turn, however carefully the writer describes it. If a no-talking rule goes up over the one table where two friends talk, the place has changed what they can do, and that is a turn. Sort every setting change by that question before you credit it with anything.` },
    { loId: 'm8ela.how-a-theme-develops-through-character-and-setting', content: `THE ENDING IS WHERE THE THEME SHOWS, NOT WHERE IT TURNS, AND THE OPENING IS NOT A CHANGE. The ending is where the theme is easiest to see, which is exactly why it is the tempting wrong answer: it is the after, the payoff, not the change that produced it. The opening situation is the before, and a before is not a change from anything, so it cannot be the turn either. The turn sits between them. "The middle of the story" is not an answer; "the moment she puts the key ring in his hand, a change in a character" is.` },
    { loId: 'm8ela.how-a-theme-develops-through-character-and-setting', kind: 'definition', title: 'develop', content: `of a theme: to arrive in stages across a story, from one of several things the story could mean to the one thing it claims.` },
    { loId: 'm8ela.how-a-theme-develops-through-character-and-setting', kind: 'definition', title: 'the turn', content: `the single change, in a character or in the setting, after which the ending is settled and the theme is the one the story means.` },
    { loId: 'm8ela.how-a-theme-develops-through-character-and-setting', kind: 'definition', title: 'before and after', content: `the situation an excerpt opens on, where several themes are still possible, and the ending, where the stated theme pays off. The turn sits between them.` },
    { loId: 'm8ela.how-a-theme-develops-through-character-and-setting', kind: 'definition', title: 'the cover test', content: `hiding one change and re-reading the ending: if the ending still makes the theme's point, that change was not the turn.` },
    { loId: 'm8ela.how-a-theme-develops-through-character-and-setting', kind: 'definition', title: 'scenery', content: `a detail of the setting that shifts without changing what any character can do or see; a theme cannot ride on it.` },
  ],
  methods: [
    {
      title: 'Worked find the turn in a character',
      steps: [
        `Find the before. The excerpt opens on a year of reminders and forgetting: "most mornings he forgot, and she went back and did it herself." That is the situation the story starts from. A before is not a change, so it cannot be the turn; it is what the turn will change.`,
        `Find the after. The last two sentences: "By March Jonah was locking the door, walking back from the bus stop to check it, and checking it again at ten with a flashlight. Nobody had reminded him of anything." This is where the theme pays off. A boy who could not be told has changed. The after is the proof, not the turn.`,
        `List every change between them and name its kind. Mrs. Okafor "stopped reminding him" and "put the key ring in his hand and told him the back door was his now": a change in a character, in what she does. The raccoon, the alarm and the police cars: an event, a loud one, and the reason this excerpt is easy to misread.`,
        `Run the cover test on the raccoon. Hide that sentence and read the ending again. Jonah has the key, the door is his, and by March he is checking it three times. The ending follows without a hitch, so the alarm changed nothing in anyone. It moved the night along and left the theme where it was.`,
        `Run the cover test on the key ring. Hide "She put the key ring in his hand and told him the back door was his now" and the sentence before it, and read the ending. A boy who forgot for a year is suddenly checking a lock three times a night, and nothing left in the excerpt explains why. The ending comes from nowhere. That is the turn.`,
        `Say the whole answer, moment and kind. The turn is the moment Mrs. Okafor stops reminding Jonah and puts the key ring in his hand, a change in a character: she goes from telling him to trusting him. Before it, the story could have been about a boy who never learns. After it, every check of the lock is the theme playing out.`,
      ],
      example: { problem: `The theme of this excerpt is: being trusted with something changes a person faster than being told to be responsible. Find the turn, say whether it is a change in a character or in the setting, and show that the ending cannot do without it.

"Every morning for a year, Mrs. Okafor reminded Jonah to lock the bakery's back door before he left, and most mornings he forgot, and she went back and did it herself. One morning in February, without saying why, she stopped reminding him. She put the key ring in his hand and told him the back door was his now. That night a raccoon got into the dumpster and set off the alarm, and two police cars came. By March Jonah was locking the door, walking back from the bus stop to check it, and checking it again at ten with a flashlight. Nobody had reminded him of anything."`, solution: `The turn is the moment Mrs. Okafor stops reminding Jonah and puts the key ring in his hand, telling him the back door is his now: a change in a character, from telling him to trusting him. Cover it and the ending, a boy checking the lock three times a night with nobody reminding him, comes from nowhere; cover the raccoon and the alarm instead and the ending follows exactly as before.` },
      relatedLoIds: ['m8ela.how-a-theme-develops-through-character-and-setting'],
    },
    {
      title: 'Worked find the turn in the setting',
      steps: [
        `Find the before. The corner table, every day since sixth grade, "trading halves of everything." The friendship looks unbreakable, and that is the point of a before: the story could still turn out to be about a friendship that survives anything.`,
        `Find the after. "By April Priya was eating with the robotics kids and Marcus was eating outside, and neither of them could have said whose idea that was." The theme pays off in that last clause: the place did the work, and neither friend noticed. This is the payoff, not the turn.`,
        `List the changes between them and name each kind. The vending machines hauled away: a change in the setting. The sign, "quiet study zone, no talking": a change in the setting, in the rules of the place. Two days of whispering: a change in the characters, in how they behave at their table.`,
        `Run the cover test on the vending machines. Hide that sentence. The sign still goes up, the table still goes quiet, April still arrives. The ending follows. The machines leaving changed how the corner looked and nothing about what Priya and Marcus could do there. That is scenery: a setting change that turns nothing.`,
        `Run the cover test on the sign. Hide it. The machines are gone, but the table is still theirs and they can still talk, and then, in April, they are at different tables for no reason the excerpt gives. The ending comes from nowhere. The sign is the turn, and it is a change in the setting: a rule of the place changed what two friends could do at their table.`,
        `Check the whispering, because it is a change in the characters and the tempting answer for anyone who assumes the turn has to be a person. Hide it. The sign goes up and April arrives just the same. The whispering is the after beginning, the theme starting to play out, not the change that produced it.`,
        `Say the whole answer: the turn is the moment the no-talking sign goes up over their end of the cafeteria, a change in the setting. Before it, the story could have been about a friendship that survives anything. After it, every lunch apart is the theme playing out.`,
      ],
      example: { problem: `The theme of this excerpt is: some friendships depend on a place more than either friend realizes. Find the turn, name its kind, and say why the other changes are not it.

"Priya and Marcus had eaten lunch at the corner table by the vending machines every day since sixth grade, trading halves of everything. In March the school hauled the vending machines away. A week later a sign went up at that end of the cafeteria: quiet study zone, no talking. They tried the zone for two days, whispering over their sandwiches. By April Priya was eating with the robotics kids and Marcus was eating outside, and neither of them could have said whose idea that was."`, solution: `The turn is the moment the sign goes up making their end of the cafeteria a quiet study zone with no talking: a change in the setting, because a rule of the place now changes what the two friends can do at their table. The vending machines leaving is scenery, since the ending follows just the same without it, and the two days of whispering are the after beginning, not the change that produced it.` },
      relatedLoIds: ['m8ela.how-a-theme-develops-through-character-and-setting'],
    },
  ],
  pointers: [
    { content: `Students often say "The turn is the car being wrecked, because it is the biggest thing that happens and the house feels different after it." — Ask what is different in a character or in the place because of the crash. Marisol has the same secret before it and after it, and she keeps it exactly the same way. Now run the cover test: hide the crash and read December again. Marisol is still skipping dinner and still avoiding her brother's eyes, so the ending follows without the crash, and the crash was never the turn. It moved the plot for a week and left the theme where it was. The turn is the moment in September when Marisol decides not to mention the report card, a change in a character: she goes from having no secret to holding one, and every heavier day after that depends on it.`, kind: 'common-error' },
    { content: `Students often say "The turn is Marisol telling her mother, because that is where the theme finally shows." — The student is right that the theme shows most plainly at the end, and that is exactly why the ending is the tempting wrong answer. Run the cover test: hide the night she tells her mother and read what is left. Marisol is skipping dinner to avoid her brother's eyes, the secret is already heavy, and the theme still stands. So the telling is the after, the theme paid off, not the change that produced it. Walk back to the first change the ending cannot do without: the September decision to say nothing, a change in a character. Hide that one, and a girl with nothing to hide is skipping dinner for no reason the story gives.`, kind: 'common-error' },
    { content: `A theme develops in stages: a BEFORE where the story could still mean several things, a TURN, and an AFTER where the theme pays off. You are handed the theme; you find the turn.`, kind: 'tip' },
    { content: `The turn is a single change, in a character (what someone wants, believes, knows or does) or in the setting (where, when, or the rules of the place), and your answer names the moment and its kind.`, kind: 'tip' },
    { content: `A change is not an event. The loudest thing that happens is the usual wrong answer; ask what is different in a character or in the place because of it, and if nothing is, it moved the plot and not the theme.`, kind: 'tip' },
    { content: `The cover test: hide the change you suspect and re-read the ending. If the ending still makes the theme's point, keep looking. If it now comes from nowhere or makes a different point, you have found the turn.`, kind: 'tip' },
    { content: `A setting change counts only when it changes what a character can do or see. A setting that shifts and changes nothing is scenery, and a theme cannot ride on scenery.`, kind: 'tip' },
    { content: `The ending is where the theme shows, not where it turns, and the opening situation is a before, not a change. The turn sits between them; when changes come in a chain, it is the first one the ending cannot do without.`, kind: 'tip' },
  ],
};
