/**
 * Grade 8 English Language Arts — Unit 8 CED 8.3: Cohesion Among Claim, Counterclaim & Evidence.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8ela.cohesion-among-claim-counterclaim-and-evidence.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8ELA_U8_COHESION_AMONG_CLAIM_COUNTERCLAIM_AND_EVIDENCE: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8ela.cohesion-among-claim-counterclaim-and-evidence.v1',
  course: 'Grade 8 English Language Arts',
  cedUnit: 8,
  cedTopic: '8.3',
  cedTitle: 'Cohesion Among Claim, Counterclaim & Evidence',
  planId: 'evelyn.ms.m8ela.cohesion-among-claim-counterclaim-and-evidence.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8ela.cohesion-among-claim-counterclaim-and-evidence.v1' }],
  theory: [
    { loId: 'm8ela.cohesion-among-claim-counterclaim-and-evidence', content: `EVERY SENTENCE HAS TO SAY WHOSE SIDE IT IS ON. An argument moves among four things: your claim, the counterclaim, your rebuttal, and the evidence underneath. The reader never sees those labels. All they get is one sentence after another. So test any sentence by covering the ones around it and asking two questions: is this the writer talking or the other side, and how does this sentence relate to the one before it? If you have to look back to answer, so did the reader, and that is the moment an argument starts to sound like it changed its mind. You already know to put a phrase such as "Some parents say" in front of the other side's idea. This lesson is about the places where a phrase at the front is not enough, because both sides are inside one sentence.` },
    { loId: 'm8ela.cohesion-among-claim-counterclaim-and-evidence', content: `A CONCESSIVE CLAUSE HOLDS BOTH SIDES IN ONE SENTENCE. Take a starter word — while, although, even though — attach the true part of the other side's point to it, and put your own point in the independent clause: "While it is true that the skate park lights would add to the town's electric bill, the lights on the tennis courts already stay on until nine." One sentence, and the reader hears you take the objection seriously and answer it without ever losing track of who is speaking. A concession is not a surrender. It is the fastest way to show that you read the other side before you disagreed with it.` },
    { loId: 'm8ela.cohesion-among-claim-counterclaim-and-evidence', content: `THE SEATS DECIDE WHAT THE READER CARRIES AWAY. You already know that whatever sits in the independent clause is the part a reader remembers, and that the starter-word clause is the part they let go of. That is the whole reason the order matters here: the other side goes in the starter-word clause, and you go in the independent clause. WRONG: "Although the front steps are the only place students can sit outside, some teachers say the steps have no shade at noon." That sentence ends on the objection, so the objection is what the reader keeps. CORRECT: "Although some teachers say the steps have no shade at noon, the front steps are the only place students can sit outside."` },
    { loId: 'm8ela.cohesion-among-claim-counterclaim-and-evidence', content: `CONCEDE WHAT THEY ACTUALLY SAID. A concession goes wrong in two ways, and both are invisible to the writer. You can grant a smaller, easier version of their point, which answers nothing that was raised. Or you can grant your own best reason by mistake, which hands them your argument. WRONG: "While it is true that the art room at lunch is where the quiet students go, the custodians say the room is not cleaned until after seventh period." The writer wants the art room open, and that sentence gives away the reason for it and then finishes on the objection. Read your starter-word clause on its own and ask whose point is sitting inside it.` },
    { loId: 'm8ela.cohesion-among-claim-counterclaim-and-evidence', content: `A TURN-BACK HAS TO POINT AT SOMETHING. "Even so" and "That figure leaves out" are hinges, and a hinge is only useful with a door on it. Name the exact piece of the counterclaim you are answering, then answer that piece. WEAK: "Even so, the recycling bins should stay in the cafeteria." That announces a turn without saying what is being turned against, so the reader is left holding the objection. STRONG: "Even so, the bins only overflow on Fridays, and the club has offered to empty them that afternoon." One more thing: a "however" bolted onto the front of every sentence is not cohesion. After the second one the reader stops believing that a turn is coming at all.` },
    { loId: 'm8ela.cohesion-among-claim-counterclaim-and-evidence', content: `EVIDENCE NEEDS A CLAUSE THAT SAYS WHAT IT SHOWS. A number or a fact dropped into an argument just sits there until you connect it to the reason it was brought in for, and the clause-level way to do that is to hang the connection off the evidence in the same sentence. WEAK: "Forty students signed the list asking for the library to stay open until four." STRONG: "Forty students signed the list asking for the library to stay open until four, which shows that the late-bus riders are not the only ones who would use that hour." Say what the evidence shows about YOUR reason, and no more than that. A link that claims more than the evidence carries is the place where a careful reader stops trusting you.` },
    { loId: 'm8ela.cohesion-among-claim-counterclaim-and-evidence', kind: 'definition', title: 'cohesion', content: `the quality of an argument in which every sentence makes clear whose side it is on and how it relates to the sentence before it.` },
    { loId: 'm8ela.cohesion-among-claim-counterclaim-and-evidence', kind: 'definition', title: 'concessive clause', content: `a starter-word clause (while, although, even though) that grants the true part of the other side's point, inside a sentence whose independent clause carries your own.` },
    { loId: 'm8ela.cohesion-among-claim-counterclaim-and-evidence', kind: 'definition', title: 'concession', content: `the part of the other side's point that you agree is true; granting it is not the same as giving up the argument.` },
    { loId: 'm8ela.cohesion-among-claim-counterclaim-and-evidence', kind: 'definition', title: 'turn-back', content: `the move that returns the reader to your side after a counterclaim, named for the exact piece it answers, as in "Even so" or "That figure leaves out".` },
    { loId: 'm8ela.cohesion-among-claim-counterclaim-and-evidence', kind: 'definition', title: 'evidence-to-reason link', content: `a clause attached to a piece of evidence that says what it shows about the reason it was brought in for, usually beginning "which shows that".` },
  ],
  methods: [
    {
      title: 'Worked build the concessive and the link',
      steps: [
        `Sort the four parts and say whose side each one is on before writing a word. The claim is Jonah's: add a second late bus at four thirty. The counterclaim belongs to the budget committee: a second bus costs more than the fund can cover. The rebuttal will be Jonah's. The evidence, the driver's shift and the empty seats, is Jonah's too. A reader who cannot tell which of those four they are reading has stopped following the argument, however good the sentences are.`,
        `Find the part of the objection that is actually true, because that is the part you concede. Money is real: a second run does cost something. What is not true is how much. So the concession is the cost, and the answer is what the cost turns out to be.`,
        `Build the concessive sentence with the seats right: the committee in the starter-word clause, Jonah in the independent clause. CORRECT: "While it is true that a second run would cost the activity fund something, the driver's shift already runs to four thirty, so the school would be paying for fuel rather than for a second salary." The reader hears the objection taken seriously and still finishes the sentence on Jonah's side.`,
        `Watch the two ways that sentence goes wrong. Reversed seats, first. WRONG: "While it is true that the driver's shift already runs to four thirty, a second bus would cost more than the activity fund can cover." Every fact in it is Jonah's own research, and it still ends on the committee's point, so the committee is what the reader carries away.`,
        `The second failure is conceding his own reason. WRONG: "While it is true that the late bus matters most to the students in clubs, the activity fund is already stretched thin." That gives away the reason he wants the bus and ends on the objection, so the sentence argues the other side twice.`,
        `Now bring the evidence in with a clause that says what it shows. WEAK: "The three fifteen bus goes out with about a third of its seats empty." True, and the reader is left to work out for themselves why it is here. CORRECT: "The three fifteen bus goes out with about a third of its seats empty, which shows that the problem is the hour rather than the number of seats the district can pay for."`,
        `Read the two finished sentences back to back and run the whose-side test on each. Sentence one: the committee, then Jonah, with "While it is true that" marking exactly where the handoff happened. Sentence two: Jonah again, with the link stating what the empty seats prove. Neither sentence makes the reader look back.`,
      ],
      example: { problem: `Hollis Middle runs one late bus, at three fifteen. Jonah is arguing that the school should add a second late bus at four thirty. The strongest thing the other side says: some parents on the budget committee say a second bus would cost more than the activity fund can cover, and the activity fund pays for the very clubs the bus would carry students home from. Jonah has checked two things with the Hollis district transportation office. The driver's shift already runs to four thirty, and the three fifteen bus goes out with about a third of its seats empty. Write the sentence that opens his rebuttal, then the sentence that brings his evidence in.`, solution: `Rebuttal opener: "While it is true that a second run would cost the activity fund something, the driver's shift already runs to four thirty, so the school would be paying for fuel rather than for a second salary." Evidence sentence: "The three fifteen bus goes out with about a third of its seats empty, which shows that the problem is the hour rather than the number of seats the district can pay for."` },
      relatedLoIds: ['m8ela.cohesion-among-claim-counterclaim-and-evidence'],
    },
    {
      title: 'Worked repair a stretch',
      steps: [
        `Sentence two is the first place a reader trips. WRONG: "The lifeguards go back to school in August and the town cannot staff the mornings." Nothing in that sentence says whose it is, so a reader who has just been told the pool should stay open now hears Nadia arguing against herself. It is the other side's point, and it has to arrive as the other side's point.`,
        `Hand it over and fold it into a concessive clause in one move, so the sentence ends on Nadia's side. CORRECT: "While it is true that the lifeguards go back to school in August, the town does not have to open the pool in the mornings at all." Same fact, same words for it, and now the reader knows both who said it and what Nadia thinks of it.`,
        `Sentence three is a hinge with nothing on it. WRONG: "However, the water is still warm." The reader is told a turn is coming but not what is being turned against, and warm water is not an answer to a staffing problem at all. Answer the piece that was actually raised, which is who would sit in the chair. CORRECT: "Even so, the shortage is only in the mornings, because the two college guards who work weekends do not leave town until the last week of September."`,
        `Notice what that repair did, and what it did not do. Swapping "However" for "Even so" changed nothing by itself; the two phrases do the same job. What fixed the sentence was naming the mornings and the two guards. The phrase is the hinge and the clause behind it is the door, and a hinge with no door is why a reader ends a paragraph still holding the objection.`,
        `Sentence four is evidence with no link. WEAK: "The Parks Department counted more swimmers on the last weekend in August than on any weekend in July." A reader can read that count and still not know why it is sitting in an argument about September. CORRECT: "The Parks Department counted more swimmers on the last weekend in August than on any weekend in July, which shows that the season people actually swim in does not end when the school year starts."`,
        `Read the repaired stretch straight through and test each sentence on its own. Claim: Nadia. Counterclaim: granted and answered inside one sentence. Turn-back: naming the mornings and the guards. Evidence: with a clause saying what it shows. Four sentences, and at every one of them the reader knows exactly where they are standing.`,
      ],
      example: { problem: `Nadia is arguing that the Ashgrove community pool should stay open through September. She has two facts she has not used yet: the two college guards who work weekends do not leave town until the last week of September, and the Ashgrove Parks Department counted more swimmers on the last weekend in August than on any weekend in July. Here is her draft.

"The pool should stay open through September. The lifeguards go back to school in August and the town cannot staff the mornings. However, the water is still warm. The Parks Department counted more swimmers on the last weekend in August than on any weekend in July."

Repair the last three sentences so that a reader always knows whose side they are hearing.`, solution: `The repaired stretch: "The pool should stay open through September. While it is true that the lifeguards go back to school in August, the town does not have to open the pool in the mornings at all. Even so, the shortage is only in the mornings, because the two college guards who work weekends do not leave town until the last week of September. The Parks Department counted more swimmers on the last weekend in August than on any weekend in July, which shows that the season people actually swim in does not end when the school year starts."` },
      relatedLoIds: ['m8ela.cohesion-among-claim-counterclaim-and-evidence'],
    },
  ],
  pointers: [
    { content: `Students often say "Putting "However" at the front of every sentence after the counterclaim, so that the reader always knows a turn is coming." — A turn-back has to name what it is turning against. "However, the crosswalk is still a good idea" reports that a turn happened and leaves the reader holding the objection, because nothing in it answers anything. "Even so, the count was taken in July, when half the families on Elm Street were away" answers a piece the reader can point at, and the phrase in front of it barely matters. Stacking the word on every sentence makes it worse rather than better: it promises a turn where there is none, and after the second one the reader stops believing it. Use the turn-back once, at the point where the argument really does come back to your side, and put the answer in the clause behind it.`, kind: 'common-error' },
    { content: `Students often say ""Although the new schedule would give every club an extra half hour, some teachers say the last period would be too short."" — The seats decide what the reader carries away. The starter-word clause is the part a reader lets go of, and the independent clause is the part they keep, so this writer has put their own best reason in the clause that gets dropped and ended the sentence on the objection. A reader finishes it believing the last period is the real problem. Swap the seats and keep every word: "Although some teachers say the last period would be too short, the new schedule would give every club an extra half hour." Then check the starter-word clause on its own and confirm that the point inside it belongs to the other side.`, kind: 'common-error' },
    { content: `Cover the sentences around any one sentence and ask two questions: is this the writer or the other side, and how does it relate to the sentence before it? If you have to look back, so does the reader.`, kind: 'tip' },
    { content: `A concessive clause holds both sides at once: the true part of their point goes in the starter-word clause (while, although, even though), and your point goes in the independent clause.`, kind: 'tip' },
    { content: `The seats decide what the reader keeps. WRONG: "Although the wall has been blank for six years, some neighbors say the mural paint would fade." CORRECT: "Although some neighbors say the mural paint would fade, the wall has been blank for six years."`, kind: 'tip' },
    { content: `Concede the point they actually made. Granting a smaller version answers nothing, and granting your own best reason by mistake hands them the argument.`, kind: 'tip' },
    { content: `"Even so" and "That figure leaves out" are hinges, and the clause behind them is the door. Name the exact piece you are answering, and do not bolt a turn onto every sentence.`, kind: 'tip' },
    { content: `Evidence needs a clause that says what it shows: "..., which shows that ...". Say what it shows about your reason, and never more than the evidence carries.`, kind: 'tip' },
  ],
};
