/**
 * Grade 8 English Language Arts — Unit 4 CED 4.2: Is the Reasoning Sound?.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8ela.is-the-reasoning-sound.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8ELA_U4_IS_THE_REASONING_SOUND: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8ela.is-the-reasoning-sound.v1',
  course: 'Grade 8 English Language Arts',
  cedUnit: 4,
  cedTopic: '4.2',
  cedTitle: 'Is the Reasoning Sound?',
  planId: 'evelyn.ms.m8ela.is-the-reasoning-sound.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8ela.is-the-reasoning-sound.v1' }],
  theory: [
    { loId: 'm8ela.is-the-reasoning-sound', content: `AN ARGUMENT HAS TWO JOINTS, AND YOU HAVE ONLY EVER TESTED ONE OF THEM. Under the claim sits a reason; under the reason sits evidence. That gives two places the argument can come apart: between the evidence and the reason, and between the reason and the claim. You already know how to work the lower joint. The upper one, the LINK from a reason to a claim, is what this lesson is about, and an argument can pass every check you know and still break there.` },
    { loId: 'm8ela.is-the-reasoning-sound', content: `THE LINK TEST: SAY IT AS "THEREFORE", THEN ASK WHETHER THE CLAIM HAS TO FOLLOW. Put the reason and the claim into one sentence with "therefore" in the middle, and read it out loud. "More students ride the late bus this year than ever before, therefore the school should cancel the late bus." Now the real question: even if the reason were completely true, would the claim have to follow? Notice what that question does not ask. It does not ask whether the reason is true, and it does not ask whether you like the claim.` },
    { loId: 'm8ela.is-the-reasoning-sound', content: `WHEN THE LINK IS WEAK, NAME THE STEP THE WRITER LEFT OUT. A weak link almost always means the writer needed one more sentence and never said it. Find that sentence and say it out loud, because writers leave those steps unsaid exactly when saying them would sound ridiculous: "a school should cancel whatever more students have started using." Naming the unstated step is the whole move. A verdict that names it can be argued with; a verdict that only says the argument feels off cannot.` },
    { loId: 'm8ela.is-the-reasoning-sound', content: `THE EVIDENCE HAS TO PROVE THE CLAIM THAT WAS MADE, NOT A NEIGHBOR OF IT. Set the evidence beside the claim and check three things in each: WHO it is about, WHEN it applies, and HOW MUCH it covers. Evidence about students who signed up on their own does not prove a claim about students who would be required to. Evidence from last spring does not prove a claim about next year. Evidence that one class enjoyed one afternoon does not prove a claim about every class, always. When any of the three does not match, the evidence has proved a smaller, nearby statement, and the claim is still standing there unsupported.` },
    { loId: 'm8ela.is-the-reasoning-sound', content: `A VIVID EXTRA SENTENCE OFTEN SITS RIGHT WHERE THE LINK IS WEAKEST. When a writer cannot get from the reason to the claim, the argument starts to feel thin, and the easiest way to make it feel full again is to add something true, interesting and completely beside the point: an award, a crowd, a story about somebody the reader likes. Test each sentence by asking which joint it strengthens. If the honest answer is neither, that sentence is not proof. It is there to keep you busy, and where it sits tells you where the writer knew the argument was weak.` },
    { loId: 'm8ela.is-the-reasoning-sound', content: `JUDGE THE ROAD, NOT THE DESTINATION. Unsound reasoning does not mean the claim is false. A writer can argue badly for something that turns out to be right, and argue beautifully for something that turns out to be wrong; the verdict "the reasoning is not sound" says the argument has not earned the claim, not that the opposite is true. So neither of these is a finding about reasoning. WRONG: "The reasoning is bad because I disagree with what the writer wants." CORRECT: "The reason is true and the claim still does not follow from it, because the writer needed a step they never stated."` },
    { loId: 'm8ela.is-the-reasoning-sound', kind: 'definition', title: 'reasoning', content: `the steps that are supposed to carry a reader from a reason to the claim it supports.` },
    { loId: 'm8ela.is-the-reasoning-sound', kind: 'definition', title: 'sound reasoning', content: `reasoning in which the reason really does lead to the claim and the evidence proves the claim that was actually made.` },
    { loId: 'm8ela.is-the-reasoning-sound', kind: 'definition', title: 'the link', content: 'the step between a reason and the claim above it; the joint this lesson tests.' },
    { loId: 'm8ela.is-the-reasoning-sound', kind: 'definition', title: 'the unstated step', content: `the sentence a writer would have to add for a weak link to hold; naming it is how a reader shows the link is weak.` },
    { loId: 'm8ela.is-the-reasoning-sound', kind: 'definition', title: 'scope', content: `how far a statement reaches: who it is about, when it applies, and how much it covers. Evidence and claim have to match on all three.` },
  ],
  methods: [
    {
      title: 'Worked run the link test',
      steps: [
        `Map it in one pass, because you already know how. Claim: the library should stop lending graphic novels. Reason: graphic novels are checked out more often than any other kind of book. Evidence: the empty shelf most Fridays, and the librarian reordering them more often than anything else.`,
        `Check the lower joint first, and watch it pass. Is the evidence about the reason it sits under? An empty shelf and constant reordering are exactly what heavy borrowing looks like, so yes. Is there more than one piece? Yes, two, from two different places. So if something is still wrong with this notice, it is not down here, and this is the moment the old questions run out.`,
        `Now the upper joint. Build one sentence out of the notice's own words, with "therefore" in the middle: "Graphic novels are checked out more often than any other kind of book in this library, therefore the Ridgeway library should stop lending graphic novels." Read it out loud and ask the link question: even if that reason were completely true, would the claim have to follow?`,
        `It would not, so find the step the writer needed and never said. To get from a reason about heavy borrowing to a claim about stopping the lending, a reader would have to accept something like this: a library should stop lending whatever people borrow most. Say that sentence out loud. Nobody would sign it, which is precisely why it was left out.`,
        `Ask where the reason actually points, because a true reason always points somewhere. Heavy borrowing is an argument for buying more copies, or for a second shelf, or for longer loan periods. It points away from the claim, not toward it. That is a broken link, not thin evidence.`,
        `Say the verdict in the form the lesson asks for: the joint, and the missing step. WRONG: "The reasoning is not sound because taking graphic novels away from students is unfair." That judges the destination, and it would be just as true if the argument had been perfect. CORRECT: "The reasoning is not sound because the link breaks. The evidence supports the reason, but the reason does not lead to the claim without an unstated step nobody would accept, that a library should stop lending whatever people borrow most."`,
      ],
      example: { problem: `Decide whether the reasoning in this notice is sound. If it is not, name the joint that breaks and the step the writer left out.

"The Ridgeway library should stop lending graphic novels. Graphic novels are checked out more often than any other kind of book in this library, and the shelf by the window is empty most Fridays. Our librarian has said she reorders them more often than she reorders anything else."`, solution: `The reasoning is not sound, and the break is at the link, not at the evidence. The empty shelf and the reordering do support the reason that graphic novels are the most borrowed books, but that reason does not lead to the claim. Getting there would require an unstated step, that a library should stop lending whatever people borrow most, which no reader would accept once it is said out loud. Heavy borrowing is a reason to buy more copies, not to stop lending.` },
      relatedLoIds: ['m8ela.is-the-reasoning-sound'],
    },
    {
      title: 'Worked scope and the distraction',
      steps: [
        `Map it first. Claim: every student should be required to join a club. Reason: clubs are where students make friends. Evidence: the survey of last spring's sixth grade. That leaves the tournament sentence sitting under nothing, which is worth remembering for the last step.`,
        `Run the link test on the reason and the claim, building the sentence out of the letter's own words. "Clubs are where students make friends, therefore every student at Hillcrest should be required to join a club." Even if the reason were completely true, does the claim follow? Not on its own. The unstated step is that a student who is made to join gets out of a club what a student who chose it gets, and that is a sentence a reader would want to argue about rather than accept in silence.`,
        `Now set the evidence beside the claim and check who, when and how much. WHO: the evidence is about sixth graders who had joined a club "on their own". The claim is about every student, including the ones who would rather not. Those are two different groups, and the difference is the exact thing the argument needs and does not have.`,
        `HOW MUCH, and WHEN. The evidence says most of those sixth graders "said they had made a new friend that year" — a report, from one grade, about one year. The claim asks for a permanent rule covering everybody. So the evidence does prove something. It proves that joining a club on your own often helps a sixth grader make a friend. That is a fine sentence, and it is not the claim; the claim is standing next to it, unsupported.`,
        `Take the last sentence and ask which joint it strengthens. Does the tournament filling the cafeteria make the link from friendship to a requirement any stronger? No. Does it prove anything about students who did not choose to join? No. It is true, it is about clubs, and it strengthens neither joint. Notice where it sits: right after the weak spot, doing the job of making a thin argument feel full.`,
        `Say the whole verdict. WRONG: "The reasoning is not sound because there are only two pieces of evidence in the whole letter." That is counting, and counting was never going to find either of these problems. CORRECT: "The reasoning is not sound for two reasons. The link needs an unstated step, that a required member gets what a volunteer gets. And the evidence is about sixth graders who joined on their own, so it proves a nearby statement rather than the claim. The tournament sentence supports neither joint." And notice what none of that settles: whether required clubs are a good idea. The letter has not earned its claim, which is a different finding from the claim being false.`,
      ],
      example: { problem: `This letter has two problems: a weak link and evidence that proves something nearby instead of the claim. Find both, then decide what the last sentence is doing.

"Every student at Hillcrest should be required to join a club. Clubs are where students make friends. When the school surveyed last spring's sixth grade, most sixth graders who had joined a club on their own said they had made a new friend that year. The chess club's fall tournament filled the cafeteria and ran until nine at night, and three families drove in from two towns over to watch it."`, solution: `Two problems. First the link: "Clubs are where students make friends" leads to "Every student at Hillcrest should be required to join a club" only if a reader accepts an unstated step, that a student who is required to join gets what a student who chose to join gets. Second the scope: the evidence is about sixth graders who had joined a club on their own, one grade, one year, so it proves that joining a club on your own often helps a sixth grader make a friend, and not the claim about every student. The tournament sentence is true and beside the point; it strengthens neither joint and sits right where the argument is weakest.` },
      relatedLoIds: ['m8ela.is-the-reasoning-sound'],
    },
  ],
  pointers: [
    { content: `Students often say "The reasoning is sound, because every sentence in it is true and every sentence is about eighth graders." — True and on topic is where the checking starts now, not where it ends. Say the argument as one sentence with "therefore" in the middle: the eighth grade has the most homework and is turning work in late, therefore the eighth grade should get its own study hall period. Even granting every word, the claim does not have to follow. The unstated step is that a study hall period is what fixes late work, and a reader could answer that the homework load itself is the thing to change, or that students who fall behind need help rather than time. The writer needed that step and never said it, and no amount of true, on-topic evidence underneath supplies it. Every sentence being true tells you the argument is honest. It does not tell you the reasoning is sound.`, kind: 'common-error' },
    { content: `Students often say "The reasoning is not sound, because a study hall would just be a free period and the eighth grade does not need one." — This verdict never touches the argument. It would read the same if the writer had reasoned perfectly, which is the sign that it is an answer to the claim rather than to the reasoning. Argue with the road instead: which joint breaks, and what step is missing? Here the link breaks, and the missing step is that a study hall period is what fixes late work. Written that way, the verdict is something the writer can answer, and it stays true whatever you personally think about study halls. Keep the two findings apart. "This argument has not earned its claim" is about the reasoning. "The eighth grade does not need a study hall" is a claim of your own, and it would need its own reason and its own evidence.`, kind: 'common-error' },
    { content: `An argument has two joints: evidence to reason, and reason to claim. You already test the lower one. Sound reasoning means the upper one holds too.`, kind: 'tip' },
    { content: `The link test: say it as "reason, therefore claim" out loud, then ask whether the claim would have to follow even if the reason were completely true.`, kind: 'tip' },
    { content: `When a link is weak, name the step the writer left out. Writers leave a step unsaid exactly when saying it out loud would sound ridiculous, so say it out loud.`, kind: 'tip' },
    { content: `Check that the evidence proves the claim that was made, by matching who, when and how much. A different group, an earlier time or a smaller reach means the evidence proved a nearby statement instead.`, kind: 'tip' },
    { content: `Ask of every sentence which joint it strengthens. One that strengthens neither is not proof, and it usually sits right where the writer knew the argument was thin.`, kind: 'tip' },
    { content: `Judge the road, not the destination. WRONG: "The reasoning is bad because I disagree with what the writer wants." CORRECT: "The reason does not lead to the claim without a step the writer never stated." Unsound reasoning means the claim has not been earned, not that it is false.`, kind: 'tip' },
    { content: `Don't stop at the lower joint. True evidence about the right topic still leaves the upper joint untested. Always build the sentence: "reason, therefore claim" and ask aloud whether the claim *has* to follow.`, kind: 'common-error' },
    { content: `When you name a weak link, don't say the argument "feels weak" or "is unclear." Say the exact sentence the writer left out. Say it out loud. If it sounds ridiculous when spoken, that's proof the writer knew it was missing.`, kind: 'tip' },
    { content: `Match WHO, WHEN, and HOW MUCH between evidence and claim. Evidence about one group, one time, or one instance can be true and still prove a *different* claim than the one being made.`, kind: 'vocab-note' },
    { content: `A vivid, true sentence sitting right after a weak link is usually a distraction, not proof. Ask: does this sentence strengthen the evidence-to-reason joint or the reason-to-claim joint? If no, it's there to make a thin argument feel full.`, kind: 'gotcha' },
    { content: `"Unsound reasoning" does not mean the claim is false. It means the argument has not *earned* the claim. A bad argument can lead to a true conclusion; a perfect argument can lead to a false one. Judge the road, not where it ends up.`, kind: 'edge-case' },
    { content: `Don't confuse "the reason is true" with "the reason leads to the claim." A true reason that points somewhere else (like toward buying more books instead of stopping a service) does not support the claim at all.`, kind: 'common-error' },
    { content: `Scope problems are about the *difference* between evidence and claim: different people, different timing, or different scale. One class in May does not prove a rule for all classes, forever. Say what the evidence *actually* proves.`, kind: 'tip' },
  ],
};
