/**
 * Grade 8 English Language Arts — Unit 1 CED 1.3: How an Incident Provokes a Decision.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8ela.how-an-incident-provokes-a-decision.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8ELA_U1_HOW_AN_INCIDENT_PROVOKES_A_DECISION: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8ela.how-an-incident-provokes-a-decision.v1',
  course: 'Grade 8 English Language Arts',
  cedUnit: 1,
  cedTopic: '1.3',
  cedTitle: 'How an Incident Provokes a Decision',
  planId: 'evelyn.ms.m8ela.how-an-incident-provokes-a-decision.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8ela.how-an-incident-provokes-a-decision.v1' }],
  theory: [
    { loId: 'm8ela.how-an-incident-provokes-a-decision', content: `AN INCIDENT IS ONE EVENT THAT HAPPENS TO A CHARACTER. A text arrives, a bus leaves early, a hose splits, a coach posts a roster. It is something the character did not choose, and it is one thing you can point at in one sentence. It is not the situation the story opened with (six weeks of practice, a position shared for two seasons), and it is not a feeling. Those were already true before anything happened, and a decision is provoked by something that HAPPENS, not by a condition that was sitting there all along.` },
    { loId: 'm8ela.how-an-incident-provokes-a-decision', content: `A DECISION IS A CHOICE BETWEEN AT LEAST TWO THINGS THE CHARACTER COULD HAVE DONE. Find the thing the character does, and then find the alternative, the thing they passed up. A good writer almost always shows it: the character looks at the program in her hand before giving it away, types the message and deletes it, watches the others head for the shade before picking up a bucket. If you cannot find a second thing the character could have done, you have found an event, not a decision. And a decision can be quiet. Staying put, saying nothing and handing something over are all choices.` },
    { loId: 'm8ela.how-an-incident-provokes-a-decision', content: `THE COVER TEST PROVES THE INCIDENT PROVOKED THE DECISION. This is the same move you used on a line of dialogue in the last lesson, now applied to an event. Put your thumb over the incident and read on. Would the character still have made this choice? If yes, the incident did not provoke it. Then check the reverse: the choice has to be ABOUT what the incident changed. An event that comes before a decision did not automatically cause it; a fire alarm can go off between the incident and the choice and have nothing to do with either. After is not because.` },
    { loId: 'm8ela.how-an-incident-provokes-a-decision', content: `AN INCIDENT PROVOKES A DECISION BY CHANGING ONE OF THREE THINGS. It changes what the character KNOWS (she now knows a younger student has nothing to play), what the character CAN DO (the bus is gone, so the planned way to get there is gone), or what a choice will COST (keeping the solo now costs someone else her one night). Name which one, because that is the link in the chain, and the link is what the question is asking for.` },
    { loId: 'm8ela.how-an-incident-provokes-a-decision', content: `THE DECISION REVEALS THE CHARACTER; THE INCIDENT NEVER DOES. You already read a character from what they do. Here the action is a choice, and the reveal lives in the gap between what they chose and what they passed up. The same incident can provoke opposite decisions from two people standing on the same curb, which is exactly why the incident tells you nothing about either of them and the decision tells you almost everything. Say the reveal as what mattered more: she chose someone else's one night over six weeks of her own work. WRONG: "The bus leaving without him shows that he is unlucky." That reads the incident as if it were about him. CORRECT: "When the bus leaves without him, he decides to text the teacher that it was not his fault instead of finding another way there, which shows that his first concern is who gets blamed."` },
    { loId: 'm8ela.how-an-incident-provokes-a-decision', content: `SAY THE WHOLE CHAIN IN ONE SENTENCE, WITH THE INCIDENT CITED EXACTLY. The shape is: when INCIDENT, NAME decides to CHOICE instead of ALTERNATIVE, which shows WHAT. All four parts, in that order, and the incident quoted from the page, not from memory. A sentence that stops after the choice has not done the analysis, and a sentence that skips the alternative has not earned its "which shows", because a choice only shows something when you know what it was chosen over.` },
    { loId: 'm8ela.how-an-incident-provokes-a-decision', kind: 'definition', title: 'incident', content: `one event that happens to a character and that the character did not choose; the first link in the chain.` },
    { loId: 'm8ela.how-an-incident-provokes-a-decision', kind: 'definition', title: 'decision', content: `a choice between at least two things a character could have done; it can be quiet, and it can be a choice not to act.` },
    { loId: 'm8ela.how-an-incident-provokes-a-decision', kind: 'definition', title: 'provoke', content: `to bring about a decision by changing what a character knows, can do or must pay. An incident provokes a decision when the decision would not have happened without it and is about what it changed.` },
    { loId: 'm8ela.how-an-incident-provokes-a-decision', kind: 'definition', title: 'alternative', content: `the thing the character could have done and did not, usually shown on the page; the decision reveals the character only when read against it.` },
    { loId: 'm8ela.how-an-incident-provokes-a-decision', kind: 'definition', title: 'cause-to-choice chain', content: `the one-sentence statement of incident, decision, alternative and what the decision shows, in that order.` },
  ],
  methods: [
    {
      title: 'Worked trace one chain',
      steps: [
        `Find the incident: one event that happens to Nadia and that she did not choose. It is the second sentence. "Mr. Okafor pulled her aside" and told her about Wren and the grandmother who "had driven three hours to hear her play" and now had nothing to hear. Notice what is NOT the incident: the six weeks of rehearsal and the name "in bold on the program" were already true when the excerpt opened. They are the situation the incident lands on, not the incident.`,
        `Find the decision and the alternative. The decision is in the last sentence: she "handed her sheet music to Mr. Okafor" and said "Give it to Wren." The alternative is on the page too. Her name is in bold, she has six weeks in this piece, and she "looked at the program in her hand for a long moment." That pause is the writer showing you the other choice, keeping the solo, and showing you that Nadia saw it.`,
        `Run the cover test. Cover the sentence where Mr. Okafor pulls her aside and read the rest. Nadia rehearses for six weeks, her name is on the program, and then she hands her music away? Nothing left in the excerpt gives her any reason to. So the decision does not survive without the incident. Now the reverse: is the decision about what the incident changed? Yes. Every word she says is about Wren, and Wren is what the incident put in front of her.`,
        `Name how the incident provoked the decision. Did it take an option away? No. She could still have played. Did it change what she knew? Yes, and that is the link: she now knows a seventh grader is in the hallway with a grandmother who drove three hours and nothing to play. Knowing that put a cost on keeping the solo that was not there ten minutes earlier.`,
        `Read the decision against the alternative to find the reveal. On one side, six weeks of her own work and a bold name on a program. On the other, one younger student's one night. She chose the second, and notice that nothing in the excerpt says Mr. Okafor asked her to. Read against what she gave up, the choice shows that another person's moment matters more to her than her own recognition.`,
        `Say the whole chain in one sentence, with the incident cited. When "Mr. Okafor pulled her aside" ten minutes before the concert and told her Wren had nothing to play, Nadia decides to give Wren the solo instead of keeping the one her name was printed for, which shows that someone else's one night matters more to her than six weeks of her own work.`,
      ],
      example: { problem: `Find the incident, the decision and the alternative, prove the incident provoked the decision, and say what the decision reveals.

"Nadia had rehearsed the solo for six weeks, and her name sat in bold on the program. Ten minutes before the spring concert, Mr. Okafor pulled her aside: Wren, the seventh grader who had learned the piece as a backup, was in the hallway trying not to cry, because her grandmother had driven three hours to hear her play and there was nothing on the program for her to play. Nadia looked at the program in her hand for a long moment. Then she handed her sheet music to Mr. Okafor and said, 'Give it to Wren. Tell her I said the solo is hers tonight,' and went to find a seat in the second row."`, solution: `Incident: ten minutes before the concert, "Mr. Okafor pulled her aside" and told Nadia that Wren's grandmother "had driven three hours to hear her play" and that there was nothing for Wren to play. Decision: Nadia hands over her sheet music and says "Give it to Wren." instead of keeping the solo her name was printed for, which the long look at the program shows she considered. The incident provoked it by changing what she knew, and the choice, read against six weeks of work and a bold name, shows that another person's one night matters more to her than her own recognition.` },
      relatedLoIds: ['m8ela.how-an-incident-provokes-a-decision'],
    },
    {
      title: 'Worked same incident two decisions',
      steps: [
        `Find the incident, and notice that there is exactly one. The bus left without them: they "stood at the curb watching its taillights turn onto the highway." It happened to both of them at once, and neither chose it. Hold on to that, because it is the point of this example: whatever you learn about Marcus and whatever you learn about Priya, none of it can come from the bus.`,
        `Marcus first. His decision: he "sat down on the curb" and "started a text to their teacher" saying that "missing the bus was not their fault." His alternative is printed in the very next sentence, because Priya takes it: find another way to the fair. So Marcus chooses explaining over arriving.`,
        `Priya. Her decision: she "pulled up the city bus schedule," found a route, "picked up the project box and started walking to the stop." Her alternative is printed in the sentence before hers, because Marcus takes it: sit down and explain. So Priya chooses arriving over explaining.`,
        `Cover test, both. Cover the first sentence. Does Marcus text the teacher about a bus that never left? Does Priya go looking for a city bus? Neither. And both decisions are about what the incident changed: the bus is what Marcus is explaining and the bus is what Priya is replacing. So the same incident provoked both.`,
        `Name the link. The incident changed what they could do: the planned way to the fair is gone. Then notice that each of them answered a different part of that loss. Marcus answers the question of who will be blamed for it. Priya answers the question of how to get there anyway. Same event, different piece of it picked up.`,
        `Now the reveal, read against the alternative each one passed up. Marcus, choosing to explain instead of to go, shows that his first concern when something goes wrong is that it not be counted against him. Priya, choosing to go instead of to explain, shows that her first concern is the fair itself, and that she treats a problem as something to solve before anyone talks about it. Neither decision is silly. They are just different, and the difference is the whole reveal. If the incident could show character, both of them would have to be shown the same thing by the same bus, and they plainly are not.`,
      ],
      example: { problem: `One incident, two characters. Trace both chains, and say why the two decisions show something the incident does not.

"The bus to the regional science fair pulled out of the parking lot at 6:40, and at 6:52 Priya and Marcus, who had been in the lab finishing the wiring on their shared project, stood at the curb watching its taillights turn onto the highway. Marcus sat down on the curb, took out his phone and started a text to their teacher explaining that they had been in the lab the whole time and that missing the bus was not their fault. Priya pulled up the city bus schedule, saw that the 7:05 route stopped two blocks from the convention center, picked up the project box and started walking to the stop."`, solution: `The one incident is the bus leaving without them. When it does, Marcus decides to sit down and text the teacher that "missing the bus was not their fault" instead of finding another way there, which shows that his first concern is not being blamed; Priya decides to find the 7:05 city bus and start walking with the project instead of stopping to explain, which shows that her first concern is getting the project to the fair. The same event provoked opposite choices, so the reveal is in each decision, not in the incident.` },
      relatedLoIds: ['m8ela.how-an-incident-provokes-a-decision'],
    },
  ],
  pointers: [
    { content: `Students often say "The fire alarm provoked Lila's decision, because she made it right after the alarm went off." — After is not because. Run the cover test both ways. Cover the alarm: would Lila still cross to Bea? Yes. She would do it in the cafeteria instead of on the sidewalk, because the alarm changed where everyone was standing and nothing else. Now cover the screenshot: is there any reason left for Lila to walk over to Bea while people whisper and look at her? None. And the decision is about what the screenshot changed, which is that Bea is now standing alone in front of the whole grade. The screenshot is the incident. The alarm is just an event that happened to land between the incident and the choice.`, kind: 'common-error' },
    { content: `Students often say "The screenshot provoked her decision, and the decision shows that Lila is the kind of person people gossip about." — The screenshot happened to Lila. It tells you what the world of the story is like on that day, and it tells you nothing about who she is, because it would have happened to every person in that chat. The reveal is in the choice, read against the alternative. Her alternative is easy to see: stay on the grass with everyone else, at a safe distance from the person the whole grade is looking at. She walks across and stands next to Bea instead. So the chain is: when the screenshot goes around and Bea is left standing alone, Lila decides to stand beside her instead of keeping her distance, which shows that being seen next to someone who is being laughed at matters more to her than staying out of it.`, kind: 'common-error' },
    { content: `An incident is one event that happens to a character and that the character did not choose. Point at it in one sentence. A situation that was already true when the story opened is not an incident.`, kind: 'tip' },
    { content: `A decision is a choice with an alternative, and the writer usually shows the alternative on the page. No alternative means you have found an event, not a decision.`, kind: 'tip' },
    { content: `The cover test proves the link: cover the incident, and ask whether the character would still have chosen this. Then check that the choice is about what the incident changed. After is not because.`, kind: 'tip' },
    { content: `An incident provokes a decision by changing what the character knows, what the character can do, or what a choice will cost. Name which.`, kind: 'tip' },
    { content: `The decision reveals the character; the incident never does. WRONG: "The bus leaving without them shows that Marcus is unlucky." CORRECT: read the choice against what he passed up, and say what mattered more to him.`, kind: 'tip' },
    { content: `Say the whole chain in one sentence: when INCIDENT, NAME decides to CHOICE instead of ALTERNATIVE, which shows WHAT. All four parts, with the incident quoted exactly.`, kind: 'tip' },
  ],
};
