/**
 * Grade 8 English Language Arts — Unit 9 CED 9.3: Establishing Point of View & Shifting Time in a Narrative.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8ela.establishing-point-of-view-and-shifting-time-in-a-narrative.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8ELA_U9_ESTABLISHING_POINT_OF_VIEW_AND_SHIFTING_TIME_IN_A_NARRATIVE: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8ela.establishing-point-of-view-and-shifting-time-in-a-narrative.v1',
  course: 'Grade 8 English Language Arts',
  cedUnit: 9,
  cedTopic: '9.3',
  cedTitle: 'Establishing Point of View & Shifting Time in a Narrative',
  planId: 'evelyn.ms.m8ela.establishing-point-of-view-and-shifting-time-in-a-narrative.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8ela.establishing-point-of-view-and-shifting-time-in-a-narrative.v1' }],
  theory: [
    { loId: 'm8ela.establishing-point-of-view-and-shifting-time-in-a-narrative', content: `THE OPENING SENTENCE MAKES THE CHOICE, SO MAKE IT ON PURPOSE. A narrative point of view is a decision about who tells the story and how much that teller is able to know, and a reader locks it in from the first sentence they read. You already know to ask whose thoughts the narration gives you; as a writer you now answer that question before you start, because the answer decides what your reader is allowed to find out and when they find it out.` },
    { loId: 'm8ela.establishing-point-of-view-and-shifting-time-in-a-narrative', content: `FIRST PERSON PUTS THE READER INSIDE ONE CHARACTER AND HANDS OVER THAT CHARACTER'S VOICE. The narrator is a person in the story, saying I: "I told her the bus was always late, which was true, and which was not the reason I was late." The reader gets one person's thoughts in that person's own words, and learns things at the exact moment they do. Choose it when the story turns on what the narrator is thinking, or on what the narrator is not saying out loud.` },
    { loId: 'm8ela.establishing-point-of-view-and-shifting-time-in-a-narrative', content: `THIRD PERSON LIMITED STAYS IN ONE HEAD BUT WATCHES FROM JUST OUTSIDE IT. An outside voice tells the story with names and with he, she or they, and goes inside exactly one character: "Dev decided the sound in the practice room was nothing. He put his hand flat on the door anyway." The reader still gets one person's thoughts, and the narration can also describe that person from the outside, including things the character would never say about themselves. Choose it when the reader needs to see the character, not only to hear them.` },
    { loId: 'm8ela.establishing-point-of-view-and-shifting-time-in-a-narrative', content: `CHOOSE BY WHAT THE STORY NEEDS THE READER TO KNOW, AND THEN LIVE WITH THE CLOSED DOORS. Every choice closes some doors, and the closed doors are the point. Neither of these two can report what a second character is thinking. A second character is only what your narrator can watch them do and hear them say. So if the whole story depends on the reader knowing something your narrator has no way to reach, you have chosen the wrong point of view, and the fix is to change the choice, not to break it for one sentence.` },
    { loId: 'm8ela.establishing-point-of-view-and-shifting-time-in-a-narrative', content: `A POINT OF VIEW BREAKS IN TWO WAYS, AND ONE OF THEM IS QUIET. The loud way is a pronoun that slips: a story that starts with I and later calls the same person she. The quiet way keeps every pronoun exactly where it was and adds a fact the narrator cannot reach, which is the one most writers miss in their own drafts. WRONG FOR THIS POINT OF VIEW: "I waved at Ms. Ortega, who was already dreading the conversation." CORRECT: "I waved at Ms. Ortega, and she looked at the clock before she waved back."` },
    { loId: 'm8ela.establishing-point-of-view-and-shifting-time-in-a-narrative', content: `A JUMP IN TIME OR PLACE NEEDS A SIGNAL AT THE FRONT OF THE SENTENCE, AND THE SIGNAL HAS TWO JOBS. A reader assumes the story keeps running where you left it, so a jump with nothing in front of it reads as the next thing that happened. Put the signal first, and make it say which direction the story moved and how far: "Two summers before that," "By the time the practice room emptied," "Back at my grandmother's apartment, an hour later." One word can do the job (later, meanwhile, afterward), and a phrase or a whole clause can carry the time and the place at once, which is why writers reach for them. Mark the way back as well as the way out; a reader who is taken somewhere and never brought back stays there.` },
    { loId: 'm8ela.establishing-point-of-view-and-shifting-time-in-a-narrative', kind: 'definition', title: 'point of view', content: `in a narrative you are writing, the choice of who tells the story and how much that teller is able to know — made in the opening sentence and held to the last one.` },
    { loId: 'm8ela.establishing-point-of-view-and-shifting-time-in-a-narrative', kind: 'definition', title: 'first person', content: `a point of view in which the narrator is a character inside the story, telling it as I.` },
    { loId: 'm8ela.establishing-point-of-view-and-shifting-time-in-a-narrative', kind: 'definition', title: 'third person limited', content: `a point of view in which an outside voice tells the story with names and with he, she or they, and goes inside exactly one character's thoughts.` },
    { loId: 'm8ela.establishing-point-of-view-and-shifting-time-in-a-narrative', kind: 'definition', title: 'point-of-view slip', content: `a sentence that steps outside the point of view the story chose, either by changing the narrator's pronoun or by reporting something the narrator has no way to know.` },
    { loId: 'm8ela.establishing-point-of-view-and-shifting-time-in-a-narrative', kind: 'definition', title: 'time-and-place signal', content: `a transition word, phrase, or clause placed at the front of a sentence to tell the reader that the story has moved to a different time or a different setting.` },
  ],
  methods: [
    {
      title: 'Worked choose the point of view',
      steps: [
        `Ask what the story needs the reader to know, and when. The whole ride works only if the reader is on that bus not knowing about the case, in the same way Rosa does not know. So the reader has to be sealed inside one person, and that person has to be Rosa.`,
        `That rules out any narration that reaches into a second character. If the opening reports that Rosa's brother woke up at seven and found an empty spot on the shelf, the wait is over before the bus pulls out. Whatever else this opening does, it can know only what Rosa knows.`,
        `Now choose between the two points of view that seal a reader inside one person. First person would give the reader Rosa's own voice for the length of the ride. Third person limited would give the reader Rosa's thoughts and also let the narration describe her from the outside, including things she would not say about herself.`,
        `Pick by what this ride needs. Nothing here depends on seeing Rosa from the outside; it depends on hearing her talk herself into being calm. So the choice is first person, and the very first sentence has to establish the I and the moment, not wait until the second paragraph to get around to it.`,
        `Draft the two sentences, then check that no word in them reaches past Rosa. CORRECT: "I got the window seat and set the case flat across my knees, because the last time I held one upright the bus took a corner and I nearly wore it. Two rows up, Marcus said something about scales, and I told him I ran mine twice before breakfast, which was true and which did not help at all."`,
        `Read it back with one question: is there anything in here that Rosa could not have known or said? Marcus is only what she can hear from two rows away. The case is only a weight across her knees. The point of view holds, and the reader is going to open that case at the same second she does.`,
      ],
      example: { problem: `A writer is starting a narrative from this idea: on the morning of the district band audition, Rosa takes her brother's clarinet case by mistake and does not find out until she opens it in the warm-up room. The story is built on the bus ride, and the reader is meant to sit through it knowing exactly what Rosa knows and nothing more. Choose a point of view for the opening and write the first two sentences.`, solution: `First person, told by Rosa, because the story depends on the reader knowing exactly what she knows for the length of the bus ride: "I got the window seat and set the case flat across my knees, because the last time I held one upright the bus took a corner and I nearly wore it. Two rows up, Marcus said something about scales, and I told him I ran mine twice before breakfast, which was true and which did not help at all."` },
      relatedLoIds: ['m8ela.establishing-point-of-view-and-shifting-time-in-a-narrative'],
    },
    {
      title: 'Worked repair slip and unmarked jump',
      steps: [
        `Find the point of view the draft chose. The first sentence stands behind Elena: she counts, she sets the chair down. There is no I, so this is an outside voice going inside one character, and the character it has gone inside is Elena.`,
        `Find where the point of view breaks. The second sentence goes into her father and reports that he "wondered whether anyone would come at all." Elena cannot hear a thought from across a room, and no pronoun changed, so this is the quiet kind of slip. WRONG FOR THIS POINT OF VIEW: "Her father, watching from the doorway, wondered whether anyone would come at all." CORRECT: "Her father stood in the doorway with his hands in his pockets and did not say anything about the empty rows."`,
        `Notice what the repair keeps. The father is still there, still in the doorway, and a reader can still tell he is worried, because standing silently in a doorway in front of empty rows shows it. Other characters do not have to disappear when you hold a point of view. They can be watched and heard as much as you like; they cannot be read.`,
        `Find the jump. The last sentence leaves the community room and goes to a phone call on some earlier day, with nothing in front of it. A reader who has just been told the room is cold and the box is taped shut will take that phone call as the next thing happening in the room, and will be confused twice: once about where, and once about when.`,
        `Put the signal at the front and make it carry both jobs. WRONG FOR THIS TIME SHIFT: "Elena told the woman on the phone that her family would run the used-book sale, because it sounded easy." CORRECT: "Three weeks earlier, standing in her own kitchen with the phone against her shoulder, Elena told the woman that her family would run the used-book sale, because it sounded easy."`,
        `Read the repaired paragraph straight through. One head the whole way, one clear jump backward that a reader can follow, and if the next paragraph comes back to the cold room it will need a signal of its own to bring the reader with it.`,
      ],
      example: { problem: `Repair this draft so that it holds one point of view and marks its jump in time.

Draft: "Elena counted the folding chairs twice and set the last one at the end of the row. Her father, watching from the doorway, wondered whether anyone would come at all. The community room was cold and the box of paperback novels was still taped shut on the table. Elena told the woman on the phone that her family would run the used-book sale, because it sounded easy."`, solution: `"Elena counted the folding chairs twice and set the last one at the end of the row. Her father stood in the doorway with his hands in his pockets and did not say anything about the empty rows. The community room was cold and the box of paperback novels was still taped shut on the table. Three weeks earlier, standing in her own kitchen with the phone against her shoulder, Elena told the woman that her family would run the used-book sale, because it sounded easy."` },
      relatedLoIds: ['m8ela.establishing-point-of-view-and-shifting-time-in-a-narrative'],
    },
  ],
  pointers: [
    { content: `Students often say "I changed some of the I sentences to Kayla sentences, because starting six sentences in a row with I sounded repetitive." — Once a narrative says I, that I is the person telling the story, and calling the same person Kayla two paragraphs later tells a reader that somebody else has taken over the telling. WRONG FOR THIS POINT OF VIEW: "I waited by the pool doors until the list went up, and then Kayla read it twice from the bottom." CORRECT: "I waited by the pool doors until the list went up, and then I read it twice from the bottom." Fix the monotony somewhere else in the sentence: start with the time or the place ("By the second hour, I stopped watching the doors"), or fold two short sentences into one. The narrator's pronoun is not the part you vary.`, kind: 'common-error' },
    { content: `Students often say "I never changed a single pronoun, so my point of view is fine. In the middle I added that the coach was already regretting the whole tryout." — Ask the second question every time: could this narrator actually know this? A narrator sitting outside the pool cannot know what the coach regrets, because regret happens inside the coach and nothing carries it across the hallway. WRONG FOR THIS POINT OF VIEW: "The coach was already regretting the whole tryout." CORRECT: "The coach came out twice to look at the sign-up sheet and went back in without saying anything." The rule is not that other characters have to vanish. They can be watched and heard all you like; they cannot be read.`, kind: 'common-error' },
    { content: `Choose the point of view in the opening sentence, on purpose: first person, where the narrator is a person in the story saying I, or third person limited, where an outside voice tells it with names and goes inside exactly one character.`, kind: 'tip' },
    { content: `Choose by what the story needs the reader to know. First person hands the reader that character's own voice and nothing else. Third person limited hands over the same single head plus a view of that person from the outside.`, kind: 'tip' },
    { content: `Both choices close the same door: a second character is only what your narrator can watch them do and hear them say. If the story needs the reader to know what that character is thinking, change the choice rather than break it for one sentence.`, kind: 'tip' },
    { content: `A point of view breaks two ways. The loud way is a pronoun slip, I becoming she. The quiet way keeps every pronoun and adds a fact the narrator cannot reach. WRONG FOR THIS POINT OF VIEW: "I waved at Ms. Ortega, who was already dreading the conversation." CORRECT: "I waved at Ms. Ortega, and she looked at the clock before she waved back."`, kind: 'tip' },
    { content: `A reader assumes the story keeps running where you left it, so every jump in time or place needs a signal at the front of the sentence, saying which direction the story went, how far, and where it stands now. One word can do it; a phrase or a clause can do it and carry more.`, kind: 'tip' },
    { content: `Mark the way back as well as the way out. A reader taken to another time or another place and never brought back stays there for the rest of the page.`, kind: 'tip' },
  ],
};
