/**
 * Grade 8 World Geography — Unit 4 CED 4.1: North America: Population Patterns.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.north-america-population-patterns.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U4_NORTH_AMERICA_POPULATION_PATTERNS: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.north-america-population-patterns.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 4,
  cedTopic: '4.1',
  cedTitle: 'North America: Population Patterns',
  planId: 'evelyn.ms.m8geo.north-america-population-patterns.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.north-america-population-patterns.v1' }],
  theory: [
    { loId: 'm8geo.north-america-population-patterns', content: `A NATIONAL DENSITY FIGURE IS DIVIDED BY LAND NOBODY IS ON, SO RUN THE DIVISION AGAIN OVER THE BAND THAT HOLDS THE PEOPLE. Density is people divided by land area, so the figure moves whenever the land under the division line moves. Take a country whose people sit in a strip along one edge. Divide the whole population by the whole country and you get the NATIONAL figure. Divide the people inside the strip by the land inside the strip and you get the SETTLED-AREA figure, which can be four, ten or thirty times larger. The move has four parts: find the sentence in the data that draws the band, add the people inside it, add the land inside it, and divide once. Then report both figures and say what each one answers. The national figure answers how many people the country holds for each square kilometer of territory. The settled-area figure answers how many people are on each square kilometer where anybody actually is. Only the second one describes a place you could stand in.` },
    { loId: 'm8geo.north-america-population-patterns', content: `TWO SHARES MEASURE HOW BADLY THE NATIONAL FIGURE MISDESCRIBES THE COUNTRY, AND YOU NEED BOTH OF THEM. Work out the share of the people inside the band -- band population divided by total population -- and the share of the land inside the band -- band area divided by total area. Ninety percent of the people on twenty percent of the land is a country the national figure describes nowhere in: not the band, which sits far above it, and not the land outside, which sits far below it. Ninety percent of the people on eighty-five percent of the land is a country where the national figure is close to honest, because almost all of the land is doing the holding. One share on its own settles nothing. A large population share is only evidence of distortion when it is set beside a small land share, and the gap between the two shares is the size of the problem.` },
    { loId: 'm8geo.north-america-population-patterns', content: `NAMING A PHYSICAL CONTROL EXPLAINS NOTHING UNTIL YOU CHECK THAT IT VARIES WHERE THE DENSITY VARIES. The conditions that make settlement easier are the candidates: a growing season long enough to raise a crop, soil deep enough to farm, fresh water, and a coast or navigable water that a cargo can reach. Run each candidate down the described regions and keep only the ones that change where the density changes. If the dense region and the sparse region have the same deep soil, soil is not what separates them, however true it is that crops need soil. If the sparse region has the LONGER growing season, the growing season is ruled out for that pair. The explanation you are entitled to is the set of candidates that survive the test, and it is usually two or three of them working together rather than one. North America is where you practice this. The eastern half of the United States and both of its coasts are the most densely settled parts of that country, and Canada's people are concentrated in a band close to its southern border with a sparsely settled North above it. Run the candidates down the Canadian pattern and the one that changes hardest from south to north is the growing season, which shortens toward the far north until crops cannot be raised at all.` },
    { loId: 'm8geo.north-america-population-patterns', content: `LONG-STANDING SETTLEMENT IS ITSELF A CONTROL, AND IT SHOWS UP WHERE THE PHYSICAL CONDITIONS MATCH AND THE DENSITIES DO NOT. A region settled longer has its roads, ports, water lines, power lines and towns already standing, so somebody arriving now joins a network that exists instead of building one. That is why two regions can match on every physical condition the data lists and still differ several times over in density: the physical conditions decided where settlement could start, and the network that grew there decided where it kept going. So when your controls test comes back with no physical difference and a large density difference, this is the reading the data supports. Two cautions. It is a statement about what is built on the ground, not about the people in either region. And it is a reading you are only entitled to when the data leaves no physical condition differing -- if the data names a harbor in one region and mountains in the other, that difference is in front of you and you do not need to reach past it.` },
    { loId: 'm8geo.north-america-population-patterns', content: `MOVE THE BAND'S EDGE AND THE SETTLED-AREA FIGURE MOVES, SO THE EDGE HAS TO BE STATED AND THEN TESTED. A settled-area density is only as good as the line drawn around the band. Widen the band and you take in land faster than you take in people, because the people nearest the edge are the thinnest on the ground, so the figure falls. Narrow it and the figure climbs. Nobody moves house while any of that happens. So whoever reports a settled-area figure states the line they used -- within three hundred kilometers of the southern border, within two hundred kilometers of the coast -- and whoever reads one re-runs the division with the edge moved to see whether the verdict survives. And keep the words straight while you do it: densely settled and sparsely settled are measurements of people for each square kilometer and nothing else, never a verdict on a region or on the people living in it.` },
    { loId: 'm8geo.north-america-population-patterns', kind: 'definition', title: 'national density', content: `the figure produced by dividing a whole country's population by its whole land area, so that every square kilometer of territory enters the division whether anybody is on it or not.` },
    { loId: 'm8geo.north-america-population-patterns', kind: 'definition', title: 'settled-area density', content: `the figure produced by dividing the population of a stated part of a country by the land area of that same part, leaving the land nobody is on out of the division entirely.` },
    { loId: 'm8geo.north-america-population-patterns', kind: 'definition', title: 'settled band', content: `the part of a country that holds most of its people, marked out by a stated line such as a distance from a border, a coast or a river rather than by a political boundary.` },
    { loId: 'm8geo.north-america-population-patterns', kind: 'definition', title: 'concentration share', content: `the percentage of a place's people that a named part of it holds, found by dividing that part's population by the whole population.` },
    { loId: 'm8geo.north-america-population-patterns', kind: 'definition', title: 'physical control', content: `a condition of land, water or climate offered as an explanation for a difference in density, and kept only if it varies where the density varies.` },
  ],
  methods: [
    {
      title: 'Worked national figure versus the band',
      steps: [
        `Step one: the national figure, which is the one the travel site used. 20,000,000 people divided by 5,000,000 square kilometers is 4 people per square kilometer. The site did that division correctly, so the argument cannot be that the number is wrong.`,
        `Step two: the settled-area figure. The band is drawn by one sentence in the data -- within 300 kilometers of the southern border -- and that sentence gives both numbers you need. 18,000,000 people divided by 1,000,000 square kilometers is 18 people per square kilometer. That is four and a half times the national figure, because 18 divided by 4 is 4.5.`,
        `Step three: work out what is left, since the two parts have to add back to the whole. People: 20,000,000 minus 18,000,000 is 2,000,000. Land: 5,000,000 minus 1,000,000 is 4,000,000 square kilometers. So the land north of the band runs at 2,000,000 divided by 4,000,000, which is 0.5 people per square kilometer. The band is 18 and the north is 0.5, and 18 divided by 0.5 is 36, so the band is thirty-six times as densely settled as the north.`,
        `Step four: the two shares. People inside the band: 18,000,000 divided by 20,000,000 is 0.90, which is 90 percent. Land inside the band: 1,000,000 divided by 5,000,000 is 0.20, which is 20 percent. Ninety percent of the people on twenty percent of the land. That gap is the whole finding.`,
        `Step five: invert every division and make the counts come back. 4 times 5,000,000 is 20,000,000. 18 times 1,000,000 is 18,000,000. 0.5 times 4,000,000 is 2,000,000. 0.90 times 20,000,000 is 18,000,000, and 0.20 times 5,000,000 is 1,000,000. Every count returns, so no zero slipped.`,
        `Give the verdict. WRONG: "Norvale averages 4 people per square kilometer, so wherever you go in Norvale you will have the place to yourself." CORRECT: "Norvale averages 4 people per square kilometer, and no part of Norvale is like that. Nine people in ten are in a band running at 18 for each square kilometer, and the land north of the band runs at 0.5." The national figure is not false. It is a figure about the country's territory being read as a figure about the country's places.`,
        `Rewind the input and read it backwards to confirm the verdict follows from the data. 18,000,000 and 2,000,000 add to 20,000,000; 1,000,000 and 4,000,000 add to 5,000,000. Most of the people with a small share of the land, and a small share of the people with most of the land, is exactly what a settled band on top of a sparse interior looks like, so the verdict came out of the table and not out of a guess.`,
        `Now change ONE input and run it again. Widen the band from 300 kilometers to 600 kilometers of the southern border. The wider band holds 19,200,000 people on 1,600,000 square kilometers, so its figure is 19,200,000 divided by 1,600,000, which is 12 people per square kilometer; the check is 12 times 1,600,000, which is 19,200,000. The figure fell from 18 to 12 and not one person moved. Look at what the widening added: 19,200,000 minus 18,000,000 is 1,200,000 more people, on 1,600,000 minus 1,000,000, which is 600,000 more square kilometers. 1,200,000 divided by 600,000 is 2 people per square kilometer for the ring that was added, and a ring at 2 pulls an average of 18 down every time. That is why a settled-area figure is worth nothing until the line it was drawn on is stated.`,
      ],
      example: { problem: `Run the routine straight through, then move one edge of the band.

"Norvale has 20,000,000 people and 5,000,000 square kilometers of land. Within 300 kilometers of its southern border live 18,000,000 of those people, on 1,000,000 square kilometers. The rest of the country stretches north from there." A travel site writes: "Norvale averages 4 people per square kilometer, so wherever you go in Norvale you will have the place to yourself." Test the claim.`, solution: `The claim is not supported, even though its number is right. Norvale's national figure is 20,000,000 divided by 5,000,000, which is 4 people per square kilometer, but 18,000,000 of the people are inside a band of 1,000,000 square kilometers, which is 18 per square kilometer, and the remaining 2,000,000 people are spread over 4,000,000 square kilometers at 0.5 per square kilometer. Ninety percent of the people are on twenty percent of the land, so the national figure describes neither part. Multiplying each figure back by its own land area returns every count. Widening the band to 600 kilometers takes in a ring running at only 2 people per square kilometer and drops the settled-area figure from 18 to 12, which is why the line has to be stated.` },
      relatedLoIds: ['m8geo.north-america-population-patterns'],
    },
    {
      title: 'Worked which control varies',
      steps: [
        `Compute all four densities before explaining anything, because an explanation of a pattern you have not measured is a guess. Alder Coast: 12,000,000 divided by 150,000 is 80 people per square kilometer. Brayle Plain: 8,000,000 divided by 400,000 is 20. Cantrel Basin: 1,200,000 divided by 600,000 is 2. Dunmoor North: 250,000 divided by 2,500,000 is 0.1.`,
        `Invert all four at once. 80 times 150,000 is 12,000,000. 20 times 400,000 is 8,000,000. 2 times 600,000 is 1,200,000. 0.1 times 2,500,000 is 250,000. Every count comes back. The order is Alder Coast, Brayle Plain, Cantrel Basin, Dunmoor North, and the spread is large: 80 divided by 2 is 40, and 80 divided by 0.1 is 800.`,
        `Take the hardest pair first, Cantrel Basin at 2 against the two dense regions, and test the growing season. Cantrel Basin has 250 days, Alder Coast has 240 and Brayle Plain has 180. The SPARSE region has the longest growing season of the three. A candidate that runs the opposite way to the density cannot be the explanation, so the growing season is ruled out for this pair. WRONG: "Cantrel Basin is sparse, so its growing season must be too short." CORRECT: "Cantrel Basin has the longest growing season of the three and the lowest density, so something other than the season is holding it down."`,
        `Test water on the same pair. Cantrel Basin has 200 millimeters of rain a year and no navigable river. Alder Coast has a large river; Brayle Plain has a large river. Water changes exactly where the density changes, so water stays in. Now test soil. Cantrel Basin is thin and stony; both dense regions have deep soil. Soil also changes where the density changes, so soil stays in as well.`,
        `The check to remember, on three clues of different kinds. The rainfall and river figures are one kind of evidence and they separate Cantrel Basin from both dense regions. The soil descriptions are a second kind and they separate the same way. The growing-season numbers are a third kind and they run the OPPOSITE way, which is what lets you rule that candidate out rather than merely leave it unmentioned. One number is a hunch; three of different kinds, two agreeing and one actively excluded, is evidence. The verdict for Cantrel Basin is water and soil together, and not the growing season.`,
        `Now take the pair the controls do NOT separate: Alder Coast at 80 against Brayle Plain at 20, a factor of 4. Both have deep soil. Both have a large river. Both have a growing season long enough to raise a crop. The one named difference is reachable water: Alder Coast has an ocean coast with three deep harbors, and Brayle Plain is 900 kilometers from the nearest port. Where a region can load and unload cargo, its towns, roads and rail lines are already standing and a new arrival joins them rather than building them, and that is what the data supports for a four-fold gap between two regions that match on everything else.`,
        `Read Dunmoor North last and notice that it is not a puzzle. Growing season 60 days, thin soil over frozen ground, and a coast usable only part of the year: three candidates all pointing the same way, and a density of 0.1. Say it as a measurement, not a verdict -- 0.1 people for each square kilometer is what the figure is, and it says nothing about anybody who lives there.`,
      ],
      example: { problem: `Explain a density pattern by testing each physical control, and say which candidates the data supports.

"Ternhall has four regions. Alder Coast: 12,000,000 people, 150,000 square kilometers; growing season 240 days; deep soil; a large river crossing it; an ocean coast with three deep harbors. Brayle Plain: 8,000,000 people, 400,000 square kilometers; growing season 180 days; deep soil; a large river; no coast, and 900 kilometers to the nearest port. Cantrel Basin: 1,200,000 people, 600,000 square kilometers; growing season 250 days; thin stony soil; 200 millimeters of rain a year and no navigable river. Dunmoor North: 250,000 people, 2,500,000 square kilometers; growing season 60 days; thin soil over ground that stays frozen below the surface; plenty of lake water; a coast that is icebound most of the year."`, solution: `Densities: Alder Coast 80 people per square kilometer (12,000,000 divided by 150,000), Brayle Plain 20 (8,000,000 divided by 400,000), Cantrel Basin 2 (1,200,000 divided by 600,000), Dunmoor North 0.1 (250,000 divided by 2,500,000); multiplying each back by its land area returns every count. For Cantrel Basin the data supports water and soil and rules the growing season OUT, because at 250 days its season is the longest of the three regions compared and its density the lowest. For Alder Coast against Brayle Plain the physical conditions match on soil, river and season, and the one named difference is reachable water -- three deep harbors against 900 kilometers to a port -- with the built network that follows a port. Dunmoor North sits at 0.1 with three candidates all pointing the same way.` },
      relatedLoIds: ['m8geo.north-america-population-patterns'],
    },
  ],
  pointers: [
    { content: `Students often say "Tolmar works out at 2 people per square kilometer, so there is open land in every part of Tolmar." — The national figure is right and the conclusion drawn from it is not. 9,000,000 divided by 4,500,000 is 2 people per square kilometer; check, 2 times 4,500,000 is 9,000,000. Now run the second division. The band holds 8,100,000 people on 900,000 square kilometers, so 8,100,000 divided by 900,000 is 9 people per square kilometer; check, 9 times 900,000 is 8,100,000. What is left is 9,000,000 minus 8,100,000, which is 900,000 people, on 4,500,000 minus 900,000, which is 3,600,000 square kilometers, so 900,000 divided by 3,600,000 is 0.25 people per square kilometer; check, 0.25 times 3,600,000 is 900,000. The shares finish it: 8,100,000 divided by 9,000,000 is 90 percent of the people, and 900,000 divided by 4,500,000 is 20 percent of the land. WRONG: "Tolmar is at 2 per square kilometer, so there is open land in every part of it." CORRECT: "Tolmar is at 2 per square kilometer as a whole, at 9 inside the band and at 0.25 beyond it, so the national figure describes neither part." The band is thirty-six times the density of the land beyond it, because 9 divided by 0.25 is 36. And say it as a measurement: 9 and 0.25 are counts of people for each square kilometer, not verdicts on either part of Tolmar or on anybody living there.`, kind: 'common-error' },
    { content: `Students often say "Alder Coast is four times as dense as Brayle Plain, so Alder Coast must have the better soil." — Check the candidate against the data before accepting it. Alder Coast is 12,000,000 divided by 150,000, which is 80 people per square kilometer; Brayle Plain is 8,000,000 divided by 400,000, which is 20; and 80 divided by 20 is 4, so the four-fold gap is real. But the data gives deep soil in BOTH regions and a large river in BOTH, so neither can be the separator. The one condition that differs is reachable water: Alder Coast has an ocean coast with three deep harbors, while Brayle Plain is 900 kilometers from the nearest port. WRONG: "Four times as dense, so the soil must be better." CORRECT: "Four times as dense with the same soil and the same river, so the explanation has to be the difference the data actually names, which is the harbors and the port distance." A control that is identical on both sides of a density gap explains none of it, no matter how important that control is to settlement in general.`, kind: 'common-error' },
    { content: `Run the division twice. The national figure is the whole population over the whole land area; the settled-area figure is the people inside a stated band over the land inside that band. The second one describes a place you could stand in.`, kind: 'tip' },
    { content: `Take both shares: the share of the people inside the band and the share of the land inside the band. Ninety percent of the people on twenty percent of the land is a national figure that describes nowhere in the country.`, kind: 'tip' },
    { content: `Invert everything. Multiply each figure back by its own land area and make the count come back, and check that the band and the land beyond it add up to the whole country on both sides.`, kind: 'tip' },
    { content: `A physical control explains a density gap only if it varies where the density varies. A condition that is the same in the dense region and the sparse one is ruled out, and a condition that runs the opposite way is ruled out hardest.`, kind: 'tip' },
    { content: `Where the physical conditions match and the densities do not, the reading the data supports is the network already standing on the ground -- roads, ports, water lines and towns that somebody arriving now joins rather than builds.`, kind: 'tip' },
    { content: `In North America the two patterns to know are that the eastern half of the United States and both of its coasts are its most densely settled parts, and that Canada's people are concentrated in a band near its southern border with a sparsely settled North, so Canada's low national figure misdescribes where Canadians live.`, kind: 'tip' },
    { content: `Move one edge of the band and the settled-area figure moves, because a widened band takes in land faster than people. State the line you drew, and re-run the division with it moved before you trust a verdict.`, kind: 'tip' },
    { content: `Densely settled and sparsely settled are measurements of people for each square kilometer. They are never a verdict on a region or on the people living in it.`, kind: 'tip' },
    { content: `National density and settled-area density answer different questions. National density says how many people the whole country holds per square kilometer of ALL its territory. Settled-area density says how many people actually live on each square kilometer WHERE PEOPLE ARE. Only the second describes a place you could stand in.`, kind: 'vocab-note' },
    { content: `Do not read a national figure as a verdict on every part of the country. A country at 4 people per square kilometer does NOT have 4 people everywhere. Your first move is always: run the division twice—once for the whole country, once for the band where people actually are.`, kind: 'common-error' },
    { content: `You need BOTH shares to know whether the national figure misdescribes the country. Ninety percent of people on 20 percent of land is a huge gap. Eighty percent of people on 75 percent of land is a small gap. One share alone tells you nothing.`, kind: 'tip' },
    { content: `A physical control is ruled OUT if it is identical in the dense region and the sparse region. Same deep soil in both? Soil cannot explain the gap. Same growing season in both? That control is ruled out. Only controls that DIFFER between the regions you are comparing can explain the difference in density.`, kind: 'common-error' },
    { content: `If a control runs the OPPOSITE way from density, rule it out hardest. Cantrel Basin has the longest growing season of three regions but the lowest density. That means 'longer season = denser' is wrong for this comparison. Name it explicitly when you exclude it.`, kind: 'gotcha' },
    { content: `Move one edge of the band and the settled-area figure moves—no one moves house. Widen the band from 300 km to 600 km and you add land faster than people, so the figure falls. Always state the line you drew (e.g., 'within 300 kilometers of the border'), and test by moving it.`, kind: 'edge-case' },
    { content: `'Densely settled' and 'sparsely settled' are measurements only—counts of people per square kilometer. They are never a verdict on whether a region is good or bad, or on the people who live there. Say '0.1 people per square kilometer,' not 'the region is empty.'`, kind: 'vocab-note' },
    { content: `When two regions match on physical conditions but differ hugely in density, the reading the data supports is the built network already on the ground—roads, ports, towns, power lines—that a new arrival joins rather than builds. But only name this when the data leaves NO physical difference.`, kind: 'tip' },
  ],
};
