/**
 * Grade 8 World Geography — Unit 5 CED 5.2: Evaluating Population Projections.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.evaluating-population-projections.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U5_EVALUATING_POPULATION_PROJECTIONS: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.evaluating-population-projections.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 5,
  cedTopic: '5.2',
  cedTitle: 'Evaluating Population Projections',
  planId: 'evelyn.ms.m8geo.evaluating-population-projections.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.evaluating-population-projections.v1' }],
  theory: [
    { loId: 'm8geo.evaluating-population-projections', content: `TURN THE RATE INTO A TIME WITH ONE DIVISION, THEN CHECK IT BY MULTIPLYING BACK. A growth rate is a speed rather than a size, so on its own it never says WHEN a place reaches a particular number. The rule of 70 turns the speed into a time in one step: divide 70 by the growth rate written as a number of percent per year, and the answer is roughly the number of years the population takes to double. A place growing at 2 percent a year doubles in 70 divided by 2, which is about 35 years. Check every one of these by multiplying back, because a slipped decimal point is invisible inside a division and obvious in the check: 35 times 2 is 70. And the 70 is a rounded number, so the answer is an estimate. It belongs in a sentence as "about 35 years" and never as "exactly 35 years".` },
    { loId: 'm8geo.evaluating-population-projections', content: `THE TIME AND THE RATE MOVE IN PROPORTION, NOT IN STEP. Doubling the rate always halves the doubling time, and that is the whole behavior of the division. Run it three times: 1 percent gives 70 years, 2 percent gives 35 years, 4 percent gives 17.5 years. Each check closes, since 70 times 1, 35 times 2 and 17.5 times 4 all come back to 70. Now look at what each percentage point bought. Going from 1 percent to 2 added one point and took 35 years off the answer; going from 2 percent to 4 added two points and took only 17.5 years off. One percentage point is worth an enormous number of years at the slow end and very few at the fast end, which is why the same small change in the rate matters far more to a slow-growing place than to one already growing fast. Neither end is better than the other: the rate is a measurement and the doubling time is a planning figure, never a score for a town or for the people in it.` },
    { loId: 'm8geo.evaluating-population-projections', content: `A PROJECTION SAYS IF, AND A PREDICTION SAYS WILL. A doubling time is not a date. The division holds the rate still for the entire stretch, and nothing about a growth rate promises to do that, so the answer only means anything with its condition attached. "IF this place keeps growing at 2 percent a year, it doubles in about 35 years" is a projection, and it can be tested, because it names the thing that has to stay true. "This place will double in 35 years" is a prediction, and the arithmetic does not support it. Restoring that condition is a step of the routine rather than a caution added at the end, because the condition is exactly the part a headline drops.` },
    { loId: 'm8geo.evaluating-population-projections', content: `WHEN TWO PROJECTIONS OF ONE PLACE DISAGREE, COMPARE THE ASSUMPTIONS AND NOT THE ANSWERS. Two teams working on the same town will publish two different doubling times, and the division is almost never where they part company -- both teams do the same division, and both checks close. They part company on what they held fixed. One holds the birth rate where it is and the other has it falling. One counts net migration, the people moving in minus the people moving out, and the other leaves it out because the work that brought the arrivals is ending. Set the assumption lists side by side and find the line the two teams do not share; that line, not the arithmetic, is worth the entire gap between the answers.` },
    { loId: 'm8geo.evaluating-population-projections', content: `TO FIND THE ASSUMPTION A HEADLINE IS RESTING ON, TAKE THE ASSUMPTIONS AWAY ONE AT A TIME. A projection usually rests on more than one condition, and the conditions almost never carry equal weight. So switch one off, run the division again, and watch the answer: the assumption whose removal moves the number furthest is the one the headline is resting on, and it is the one to ask hard questions about. This is worth doing even when the reflex answer feels obvious, because the reflex is often wrong -- the assumption everybody argues over can turn out to be worth eight years while the quiet one nobody mentions is worth fifty.` },
    { loId: 'm8geo.evaluating-population-projections', content: `A RATE THAT DOES NOT HOLD STILL IS NOT ONE RATE, SO REPORT A RANGE. The division takes a single steady rate, so when a place is growing at one rate now and is expected to be growing at a slower one later, you cannot run the rule of 70 once and print the answer. Run it at each end instead and report the bracket: at 4 percent about 17.5 years, at 1 percent about 70 years, so somewhere between those two. That bracket is not the method failing. It is the assumption made visible, and it is the honest output, because a planner who builds for the fast end and gets the slow one has paid for buildings that stand empty, while one who builds for the slow end and gets the fast one has children with nowhere to sit.` },
    { loId: 'm8geo.evaluating-population-projections', kind: 'definition', title: 'doubling time', content: `the number of years a population takes to reach twice its present size while it keeps growing at one stated rate, estimated by dividing 70 by that rate.` },
    { loId: 'm8geo.evaluating-population-projections', kind: 'definition', title: 'rule of 70', content: `the division that turns a growth rate in percent per year into a doubling time in years, 70 divided by the rate, which gives an estimate and never an exact figure.` },
    { loId: 'm8geo.evaluating-population-projections', kind: 'definition', title: 'projection', content: `a figure worked out from stated assumptions, which says what follows if those assumptions hold rather than what will happen.` },
    { loId: 'm8geo.evaluating-population-projections', kind: 'definition', title: 'assumption', content: `a condition a projection holds fixed while it runs, such as a rate that stays where it is or migration counted at its present level, and the thing to name before the answer is read.` },
    { loId: 'm8geo.evaluating-population-projections', kind: 'definition', title: 'net migration', content: `the number of people moving into a place minus the number moving out over the same period, added to the change from births and deaths to give the growth rate.` },
  ],
  methods: [
    {
      title: 'Worked run the routine',
      steps: [
        `Step one: read the rate and be clear about what it is a rate of. Two percent a year means two more people each year for every 100 already living there, which on 24,000 people is 480 people in the first year -- 2 percent of 24,000 is 480, and the check is 480 divided by 24,000, which is 0.02, or 2 percent. That is a speed, and the headline is asking for a time. The size it is heading for is twice 24,000, which is 48,000, and the paper has that part right.`,
        `Step two: divide 70 by the rate. 70 divided by 2 is 35. At 2 percent a year Marran takes about 35 years to go from 24,000 people to 48,000.`,
        `Step three: invert. 35 times 2 is 70, so the division closes and no decimal point slipped on the way through.`,
        `Step four: restore the condition, which is the step the headline skipped. WRONG: "Marran will have 48,000 people in 35 years." CORRECT: "If Marran keeps growing at 2 percent a year for the whole stretch, it reaches about 48,000 people in about 35 years." The arithmetic is identical in both sentences. The difference is that the second one can be checked, because it names the thing that has to stay true for the number to arrive.`,
        `Rewind the input and read it backwards, to be sure the answer follows from the data rather than from a habit. A town adding 480 people to a base of 24,000 is adding one fiftieth of itself in the first year, and one fiftieth is 2 percent, which is where the rate came from. Something adding a fiftieth of itself every year plainly does not need a century to double, so an answer of about 35 years is the right order of size. Now notice the trap sitting right next to it. Adding 480 people every single year would take 24,000 divided by 480, which is 50 years, not 35. WRONG: "2 percent a year means 100 percent in 50 years." CORRECT: "2 percent a year doubles the town in about 35 years, because each year the 2 percent is charged on the new total rather than on the old one, so the 480 does not stay 480." The rule of 70 gives the shorter answer for exactly that reason.`,
        `Now change ONE input and run it again, so that 35 years is not memorized as a fact about Marran. Suppose the next count comes in and the growth rate is 1 percent rather than 2. 70 divided by 1 is 70 years, and the check is 70 times 1, which is 70. Halving the rate doubled the time, from about 35 years to about 70. Nobody left Marran and the town did not shrink; one input moved, and the second school the headline was arguing for now has a whole lifetime to arrive in instead of half of one. The date was never a fact about the town. It was a fact about the rate somebody assumed.`,
      ],
      example: { problem: `Run the routine straight through on a newspaper claim, and name what the claim left out.

"Marran has 24,000 people, and its population grew by 2 percent over the past year. The town paper prints a headline: Marran will have 48,000 people in 35 years, and the town is on course to double."`, solution: `The paper has the size right and the time unsupported, because it dropped the condition. The rule of 70 gives 70 divided by 2, which is about 35 years to go from 24,000 people to 48,000, and the check closes because 35 times 2 is 70. Written honestly it reads: if Marran keeps growing at 2 percent a year, it reaches about 48,000 people in about 35 years. Adding the first year's 480 people every year instead would take 50 years, since 24,000 divided by 480 is 50, which is why the percent has to be charged on the new total. And if the rate turns out to be 1 percent, the same division gives 70 divided by 1, which is about 70 years, so one percentage point is worth about 35 years here.` },
      relatedLoIds: ['m8geo.evaluating-population-projections'],
    },
    {
      title: 'Worked two projections one town',
      steps: [
        `Put the two teams on the same footing first, by turning the migration figure into a rate. The division takes one number and that number is a percent per year, so a head count of arrivals has to be converted: 600 people a year on a town of 60,000 is 600 divided by 60,000, which is 0.01, or 1 percent a year. Check by going the other way: 1 percent of 60,000 is 600. Migration is worth 1 percent a year here and births and deaths are worth 2.5 percent.`,
        `Run the county team's projection. Their assumptions give 2.5 percent plus 1 percent, which is a growth rate of 3.5 percent a year. 70 divided by 3.5 is 20, and the check is 20 times 3.5, which is 70. Twice 60,000 is 120,000, so the county team's 20 years and the newspaper's 120,000 people are the same claim stated twice.`,
        `Run the regional team's projection. Their assumptions take the migration away and leave 2.5 percent a year. 70 divided by 2.5 is 28, and the check is 28 times 2.5, which is 70. Same town, same division, same day, and an answer 8 years further out.`,
        `Say where they part company, and be exact about it. Neither team made an arithmetic mistake: both divisions close under their own check. The two teams differ on ONE line of their assumption lists, whether the arrivals keep coming, and that one line is worth the whole gap of 8 years. WRONG: "They cannot both be right, so one of those teams divided wrong." CORRECT: "Both divisions are right, and the answers differ because the assumption lists differ -- so the thing to argue about is whether the arrivals keep coming, not the arithmetic."`,
        `Now answer the question the headline forces, by taking the assumptions away one at a time. Take migration away and leave births and deaths at 2.5 percent: the answer goes from 20 years to 28 years, so that assumption is worth 8 years. Now take the other one away instead. Suppose births fall until they only balance deaths, so births and deaths add nothing, while migration holds at 1 percent: 70 divided by 1 is 70 years, and the check is 70 times 1, which is 70. That assumption is worth 50 years. The headline is resting far more heavily on births and deaths than on the arrivals everybody in town is arguing about, and a reader who only interrogates the migration line has checked the smaller of the two conditions.`,
        `Rewind the inputs and read them backwards to confirm nothing was misread: 60,000 people, 2.5 percent from births and deaths, 600 arrivals a year which is 1 percent, giving 3.5 percent together. Three pieces of evidence agree that the county figure is the fastest of the three answers on the table -- it uses the largest rate of the three, 3.5 against 2.5 and 1; it gives the shortest time, 20 years against 28 and 70; and it is the only one of the three that needs BOTH assumptions to hold at once. A headline quotes the fastest projection, and the fastest projection is the one with the most conditions attached.`,
        `Now change ONE input and run it again, and this time change the one the two teams both held fixed. Suppose the births-and-deaths part neither stays at 2.5 percent nor goes to nothing, but slides down across the decades while migration holds at 1 percent. Then there is no single rate to divide by, and the rule of 70 cannot be run once. Run it at each end instead: at the top the rate is 3.5 percent, giving 70 divided by 3.5, which is 20 years, and at the bottom it is 1 percent, giving 70 divided by 1, which is 70 years. The honest output is a bracket -- somewhere between about 20 and about 70 years -- and the width of that bracket is not vagueness. It is the assumption, finally written down where a planner can see it.`,
      ],
      example: { problem: `Two teams project the same town and publish different answers. Find where they part company, work out which assumption the headline is resting on, and then say what happens if the birth rate does not hold either.

"Oskett has 60,000 people. Both teams agree on the recent figures: births and deaths on their own are adding 2.5 percent a year, and net migration has been adding 600 more people a year on top of that. The county team assumes both of those carry on. The regional team assumes the arrivals stop, because the construction work that brought them is finishing, while births and deaths carry on as they are. The county newspaper prints: Oskett will pass 120,000 people within 20 years, so the county should buy the land for a second high school now."`, solution: `The 600 arrivals are 1 percent a year, since 600 divided by 60,000 is 0.01 and 1 percent of 60,000 is 600. The county team assumes 2.5 percent plus 1 percent, so 70 divided by 3.5 is about 20 years, checked by 20 times 3.5 being 70. The regional team assumes 2.5 percent alone, so 70 divided by 2.5 is about 28 years, checked by 28 times 2.5 being 70. Both divisions are right and the teams differ on one assumption, worth 8 years. Removing the other assumption instead -- births falling until they only balance deaths, leaving migration at 1 percent -- gives 70 divided by 1, which is about 70 years, worth 50. So the 20-year headline rests far more on births and deaths than on the arrivals. If the births-and-deaths part slides rather than holding or stopping, there is no single rate and the honest answer is the bracket from about 20 to about 70 years.` },
      relatedLoIds: ['m8geo.evaluating-population-projections'],
    },
  ],
  pointers: [
    { content: `Students often say "Marran will have 48,000 people in 35 years." — The arithmetic stands: 70 divided by 2 is about 35 years, and the check closes, since 35 times 2 is 70. What the sentence drops is the condition the division ran on. WRONG: "Marran will have 48,000 people in 35 years." CORRECT: "If Marran keeps growing at 2 percent a year, it reaches about 48,000 people in about 35 years." Then price the condition, so that the difference is not just a wording point. At 1 percent a year the same division gives 70 divided by 1, which is about 70 years, and the check is 70 times 1, which is 70. One percentage point off the rate moves the answer by about 35 years, so the date was never a fact about Marran. It was a fact about the rate somebody assumed, and the honest sentence is the one that says so.`, kind: 'common-error' },
    { content: `Students often say "Two different doubling times for one town means one of the teams divided wrong." — Check both divisions and both of them close. The county team assumed 2.5 percent from births and deaths plus 1 percent from migration, which is 3.5 percent: 70 divided by 3.5 is 20 years, and 20 times 3.5 is 70. The regional team assumed the arrivals stop, leaving 2.5 percent: 70 divided by 2.5 is 28 years, and 28 times 2.5 is 70. Neither division is wrong. WRONG: "Two answers, so one of them is a mistake." CORRECT: "Two answers, so there are two assumption lists, and the question to settle is the one line they do not share -- whether the arrivals keep coming." And once that is the question, the two figures become useful together rather than one of them being thrown away: a planner reads them as a bracket, about 20 years at the fast end and about 28 at the slow end, and buys land that still works at the later date.`, kind: 'common-error' },
    { content: `Doubling time is one division: 70 divided by the growth rate in percent per year. Check every one by multiplying back, because the doubling time times the rate has to come back to 70.`, kind: 'tip' },
    { content: `The answer is an estimate, because 70 is a rounded number. Say "about 35 years", never "exactly 35 years".`, kind: 'tip' },
    { content: `Rate and time move in proportion, not in step. Doubling the rate halves the time, so one percentage point is worth a great many years at the slow end and very few at the fast end.`, kind: 'tip' },
    { content: `A projection says IF and a prediction says WILL. Write the condition into the sentence, because the condition is the part a headline drops.`, kind: 'tip' },
    { content: `When two projections of one place disagree, the division is almost never where they part company. Set the assumption lists side by side and name the one line they do not share.`, kind: 'tip' },
    { content: `To find the assumption a headline is resting on, switch the assumptions off one at a time and see which one moves the answer furthest. The quiet assumption can be worth 50 years while the one everybody argues about is worth 8.`, kind: 'tip' },
    { content: `A rate that slides is not one rate. Run the division at each end and report the bracket; the width of the bracket is the assumption, made visible.`, kind: 'tip' },
    { content: `A growth rate and a doubling time are measurements of a speed. Fast growth and slow growth are measured here, never ranked, and neither is a score for a town or for the people in it.`, kind: 'tip' },
  ],
};
