/**
 * Grade 8 World Geography — Unit 9 CED 9.2: Maritime Zones & Ocean Boundaries.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.maritime-zones-and-ocean-boundaries.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U9_MARITIME_ZONES_AND_OCEAN_BOUNDARIES: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.maritime-zones-and-ocean-boundaries.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 9,
  cedTopic: '9.2',
  cedTitle: 'Maritime Zones & Ocean Boundaries',
  planId: 'evelyn.ms.m8geo.maritime-zones-and-ocean-boundaries.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.maritime-zones-and-ocean-boundaries.v1' }],
  theory: [
    { loId: 'm8geo.maritime-zones-and-ocean-boundaries', content: `EVERY ZONE QUESTION IS A DISTANCE FROM A BASELINE, SO THE ANSWER IS A SUBTRACTION. A state makes its own laws inside its own territory, and offshore that territory is fixed by measured distance from a line called the BASELINE, normally the low-water line along the coast. Three distances do the work, and most countries have agreed to them in the United Nations Convention on the Law of the Sea, opened for signature in 1982 and in force since 1994: out to 12 nautical miles is the TERRITORIAL SEA, out to 200 nautical miles is the EXCLUSIVE ECONOMIC ZONE, and past 200 nautical miles from any coast is the HIGH SEAS. To place an activity you take its distance from the nearest baseline and hold it against 12 and against 200, nothing more. A boat 30 nautical miles out is 30 minus 12, which is 18 nautical miles past the territorial sea, and 200 minus 30, which is 170 nautical miles short of the outer limit, so it sits in the exclusive economic zone with room on both sides.` },
    { loId: 'm8geo.maritime-zones-and-ocean-boundaries', content: `THE ZONES DIFFER IN WHAT THEY CONTROL, SO THE ACTIVITY DECIDES AS MUCH AS THE DISTANCE DOES. Inside the territorial sea the coastal state's laws apply much as they do on its land, and ships of other states may still pass through so long as the passage keeps going and does no harm. Inside the exclusive economic zone the coastal state controls the RESOURCES -- the fish in the water, and the oil, gas and minerals in the seabed -- while the ships and aircraft of every state stay free to cross it. Past 200 nautical miles the fish are not any single state's to license. That is why two boats in the same square of ocean get two different answers: at 60 nautical miles out a cargo ship crossing needs nobody's permission and a trawler with its nets down needs the coastal state's. Distance picks the zone; the zone together with the activity gives the answer.` },
    { loId: 'm8geo.maritime-zones-and-ocean-boundaries', content: `AN ISLAND CARRIES ITS OWN BASELINE, SO A SMALL ISLAND FAR OUT DRAGS THE WHOLE OUTER LIMIT WITH IT. Under the convention a naturally formed island that stays above water at high tide and can support people or an economic life of its own generates the same zones as a mainland coast does. The island's AREA never enters the arithmetic; only its position does. An island of one square kilometer lying 40 nautical miles offshore moves the outer edge of its state's exclusive economic zone from 200 nautical miles off the mainland to 40 plus 200, which is 240 nautical miles off the mainland, and the check runs backwards: 240 minus 200 is 40, the distance out to the island. The convention sets one limit on this, and it is the one worth knowing: a bare rock that cannot support people or an economic life of its own gets a territorial sea but no exclusive economic zone. So the question to ask about a feature is what it is and where it is, never how big it looks.` },
    { loId: 'm8geo.maritime-zones-and-ocean-boundaries', content: `TWO COASTS CLOSER THAN 400 NAUTICAL MILES APART PRODUCE AN OVERLAP, AND AN OVERLAP IS SPLIT RATHER THAN AWARDED. Two states facing each other across 300 nautical miles of water would each claim 200, and 200 plus 200 is 400, which is 100 more than 300 -- so a band 100 nautical miles wide sits inside both claims at once. Neither claim is wrong, and that is exactly why the 200 rule cannot settle anything inside the band: it says yes twice. The construction the convention gives for the territorial sea, and the line two states usually start from for the wider zone, is the MEDIAN LINE, every point of which is the same distance from the nearest point of each coast. Across 300 nautical miles it runs 300 divided by 2, which is 150 nautical miles from each coast, so each state keeps 150 instead of 200 and gives up 200 minus 150, which is 50 -- the 100-mile band split into 50 and 50.` },
    { loId: 'm8geo.maritime-zones-and-ocean-boundaries', content: `NAME THE BASELINE YOU MEASURED FROM, THEN ADD THE DISTANCES BACK. Two slips produce most wrong answers in this work. The first is measuring from the mainland when an island of the same state lies nearer, which makes a point look farther out than it is. The second is settling a point inside an overlap with the 200 rule, which cannot choose between two correct claims. So say which baseline the distance came from, and then check it: a fishing ground 120 nautical miles from one coast, where the two coasts are 300 nautical miles apart, is 300 minus 120, which is 180 nautical miles from the other, and 120 plus 180 is 300, the gap you started with. Because 120 is less than 150 it lies on the near state's side of the median line, and because 120 is less than 180 that state is the nearer one. Two tests, same answer, which is how you know neither was a guess.` },
    { loId: 'm8geo.maritime-zones-and-ocean-boundaries', kind: 'definition', title: 'baseline', content: `the line every offshore distance is measured from, normally the low-water line along the coast; move the baseline and every zone measured from it moves too.` },
    { loId: 'm8geo.maritime-zones-and-ocean-boundaries', kind: 'definition', title: 'nautical mile', content: `the unit distances at sea are measured in, fixed at 1,852 meters, so a 12-nautical-mile limit reaches 12 times 1,852 meters, which is 22,224 meters, a little over 22 kilometers.` },
    { loId: 'm8geo.maritime-zones-and-ocean-boundaries', kind: 'definition', title: 'territorial sea', content: `the belt from the baseline out to 12 nautical miles, inside which the coastal state's laws apply much as they do on land, while other states' ships keep the right to pass through.` },
    { loId: 'm8geo.maritime-zones-and-ocean-boundaries', kind: 'definition', title: 'exclusive economic zone', content: `the belt from the baseline out to 200 nautical miles, inside which the coastal state controls the resources -- the fish, and the oil, gas and minerals of the seabed -- while every state stays free to sail and fly across it.` },
    { loId: 'm8geo.maritime-zones-and-ocean-boundaries', kind: 'definition', title: 'high seas', content: `the water beyond every state's 200-nautical-mile zone, whose fish are not any single state's to license.` },
    { loId: 'm8geo.maritime-zones-and-ocean-boundaries', kind: 'definition', title: 'median line', content: `the line drawn through an overlap so that every point on it is the same distance from the nearest point of each coast, which splits the doubly claimed band in half.` },
  ],
  methods: [
    {
      title: 'Worked place four activities',
      steps: [
        `Set the two limits you will hold everything against before looking at a single boat. The territorial sea runs from the baseline out to 12 nautical miles. The exclusive economic zone runs out to 200. Every question below is one distance compared with those two numbers, and then one question about what is being done.`,
        `The first trawler, 8 nautical miles out. 8 is less than 12, and 12 minus 8 is 4, so it is 4 nautical miles inside the outer edge of the territorial sea. There Marenza's law applies much as it does ashore, so a foreign boat taking fish needs Marenza's permission.`,
        `The cargo ship, 40 nautical miles out. 40 minus 12 is 28, so it is 28 nautical miles past the territorial sea; 200 minus 40 is 160, so it is 160 nautical miles short of the outer limit. It is in the exclusive economic zone. What Marenza controls there is the resources, and sailing through is not a resource, so the ship needs no permission. WRONG: "It is inside 200 nautical miles, so it is in Marenza's waters and has to ask." CORRECT: "It is inside the exclusive economic zone, where every state keeps the freedom to sail; Marenza controls the fish and the seabed there, not the traffic."`,
        `The gas well, 85 nautical miles out. 85 minus 12 is 73 and 200 minus 85 is 115, so it is in the exclusive economic zone as well. The seabed and what lies under it are exactly what the coastal state controls in that zone, so this one does need Marenza's permission. Same zone as the cargo ship, opposite answer, and the activity is the only thing that changed.`,
        `The second trawler, 260 nautical miles out. 260 minus 200 is 60, so it is 60 nautical miles beyond the outer limit and on the high seas, where the fish are not Marenza's to license. It needs no permission from Marenza.`,
        `Invert every distance so that no figure slipped. 12 plus 28 is 40, the cargo ship. 12 plus 73 is 85, the well. 40 plus 160 is 200, the outer limit. 200 plus 60 is 260, the far trawler. 8 plus 4 is 12, the edge of the territorial sea. Every number comes back.`,
        `Rewind the four distances and read them backwards -- 260, 85, 40, 8 -- checking each against 12 and 200 one more time: past 200, between 12 and 200, between 12 and 200, under 12. Now change ONE input. Move the first trawler from 8 nautical miles out to 40, so that it sits beside the cargo ship. The zone is now identical for the two of them and the answers still differ: the cargo ship sails free, and the trawler still needs a permit, because at 40 nautical miles Marenza controls the fish and not the traffic. Distance alone never finishes the job.`,
      ],
      example: { problem: `Marenza has a long, straight coastline. Four things are happening off it on the same afternoon, and every distance is measured from the nearest point of Marenza's baseline. Decide which zone each falls in and whether it needs Marenza's permission.

"A trawler registered in another country is netting fish 8 nautical miles out.

A cargo ship registered in another country is steaming north, 40 nautical miles out.

A drilling company from another country is sinking a gas well into the seabed 85 nautical miles out.

A second foreign trawler is netting fish 260 nautical miles out."`, solution: `The trawler at 8 nautical miles is inside the 12-nautical-mile territorial sea and needs permission. The cargo ship at 40 and the gas well at 85 are both in the exclusive economic zone, past 12 and short of 200, but only the well needs permission, because the coastal state controls resources there and not navigation. The trawler at 260 is 60 nautical miles past the 200-nautical-mile limit, on the high seas, and needs none. Moving the first trawler out to 40 nautical miles does not free it: in the same zone as the cargo ship, it still needs a permit to fish.` },
      relatedLoIds: ['m8geo.maritime-zones-and-ocean-boundaries'],
    },
    {
      title: 'Worked split the overlap',
      steps: [
        `Test first whether there is a problem at all. Each state may claim 200 nautical miles, and 200 plus 200 is 400, while the water is only 300 nautical miles wide. 400 minus 300 is 100, so a band 100 nautical miles wide lies inside both claims at once. Both claims are correct, which is why the 200 rule decides nothing inside that band.`,
        `Find where the band sits, because that is the part people skip. Corvell's claim runs from 0 to 200 nautical miles off its own coast. Denhault's claim runs from 0 to 200 off its own coast, which measured off Corvell's coast is from 300 minus 200, that is 100, out to 300. So the overlap runs from 100 to 200 nautical miles off Corvell, and 200 minus 100 is 100, which matches the width already computed.`,
        `Draw the median line, the construction both states start from. Every point on it is the same distance from the nearest point of each coast, so across 300 nautical miles it runs 300 divided by 2, which is 150 nautical miles from each. Check: 150 plus 150 is 300. Each state keeps 150 nautical miles instead of 200 and gives up 200 minus 150, which is 50, so the 100-mile band is split 50 and 50.`,
        `Place the fishing ground, 120 nautical miles from Corvell. 300 minus 120 is 180, so it lies 180 nautical miles from Denhault, and 120 plus 180 is 300. Since 120 is less than 150 it is on Corvell's side of the median line, and since 120 is less than 180 Corvell is also the nearer coast. Both tests agree: the ground is Corvell's. It does sit inside the overlap, since 120 falls between 100 and 200, so Denhault could claim it under the 200 rule -- being inside the overlap is what makes the median line necessary, and the line, once drawn, leaves nothing in doubt.`,
        `Place the gas field, 160 nautical miles from Corvell. 300 minus 160 is 140, so it lies 140 nautical miles from Denhault, and 160 plus 140 is 300. It is inside the overlap, since 160 falls between 100 and 200. Against the median line, 160 is more than 150, so it is on Denhault's side, and the two distances agree, since 140 is less than 160. WRONG: "The field is 160 nautical miles from Corvell, which is inside Corvell's 200, so it is Corvell's." CORRECT: "It is inside 200 nautical miles of BOTH coasts, so the 200 rule says yes twice and settles nothing; the median line at 150 settles it, and at 160 the field falls on Denhault's side, 140 nautical miles from Denhault against 160 from Corvell."`,
        `Rewind, then change ONE input. Read the numbers backwards first: a gas field at 160 and a fishing ground at 120, against a 300-mile gap and a median line at 150. Now push the two coasts apart to 420 nautical miles. 200 plus 200 is 400, and 400 is less than 420, so the claims no longer meet: 420 minus 400 is 20, and a strip of high seas 20 nautical miles wide runs down the middle, where the fish are neither state's to license. No median line is needed, because nothing is claimed twice. The whole problem existed because 300 was under 400, and that is the number to test first every time.`,
      ],
      example: { problem: `Corvell and Denhault face each other across open water. The nearest point of Corvell's coast and the nearest point of Denhault's coast are 300 nautical miles apart. Work out what each state can claim, where the line between them falls, and which state two described sites belong to.

"A fishing ground lies 120 nautical miles from Corvell's coast, on the straight line between the two nearest points.

A gas field lies 160 nautical miles from Corvell's coast, on that same straight line."`, solution: `Each state may claim 200 and the water is 300 nautical miles wide, so 400 minus 300 leaves 100 nautical miles claimed twice, running from 100 to 200 nautical miles off Corvell. The median line sits 150 nautical miles from each coast, since 300 divided by 2 is 150, so each state keeps 150 and gives up 50. The fishing ground at 120 from Corvell is inside 150 and is Corvell's; the gas field at 160 from Corvell is past 150 and is Denhault's, which the distances confirm, since it lies 140 from Denhault against 160 from Corvell. Push the coasts to 420 nautical miles apart and 420 minus 400 leaves a 20-nautical-mile strip of high seas between the zones, with no overlap to split.` },
      relatedLoIds: ['m8geo.maritime-zones-and-ocean-boundaries'],
    },
  ],
  pointers: [
    { content: `Students often say "Past 12 nautical miles the sea is international, so anyone can do anything there." — There are three zones, not two, and the band between the first and the last is the widest of them: 200 minus 12 is 188 nautical miles in which the coastal state controls the resources while every other state keeps the freedom to sail and fly. Take a boat 60 nautical miles out. 60 is more than 12, so the territorial sea has indeed been left behind, but 200 minus 60 is 140, so the boat is still 140 nautical miles inside the exclusive economic zone: a cargo ship crossing needs no permission and a trawler fishing does. Only past 200 nautical miles, on the high seas, are the fish not any single state's to license. WRONG: "Past 12 nautical miles, anything goes." CORRECT: "Past 12 the traffic is free and the resources are not, all the way out to 200."`, kind: 'common-error' },
    { content: `Students often say "An island one square kilometer across is too small to change where a zone ends." — Area is not in the calculation. What a naturally formed island above water at high tide, able to support people or an economic life of its own, brings with it is a baseline, and every zone is measured from a baseline. Put such an island 90 nautical miles offshore and the outer edge of its state's exclusive economic zone moves from 200 nautical miles off the mainland to 90 plus 200, which is 290 nautical miles off the mainland, whatever the island measures across. Check it backwards: 290 minus 200 is 90, the distance out to the island. WRONG: "It is tiny, so it cannot matter." CORRECT: "Its area never enters the arithmetic; its position sets the baseline, and the baseline sets the zone." The one feature that does not do this is a bare rock that cannot support people or an economic life of its own: it gets a territorial sea but no exclusive economic zone, which is again a question of what the feature is, not of how big it looks.`, kind: 'common-error' },
    { content: `Every offshore distance is measured from the baseline, normally the low-water line along the coast: out to 12 nautical miles is the territorial sea, out to 200 is the exclusive economic zone, and past 200 from any coast is the high seas.`, kind: 'tip' },
    { content: `Placing an activity is a subtraction. Hold its distance against 12 and against 200, say which zone it lands in, then add the pieces back to recover the distance you started with.`, kind: 'tip' },
    { content: `The zone tells you WHAT is controlled, not that everything is. In the exclusive economic zone the coastal state controls the fish and the seabed while every state keeps the freedom to sail across, so two boats side by side can get two different answers.`, kind: 'tip' },
    { content: `An island that counts as land carries its own baseline, so an island 40 nautical miles offshore moves the outer limit to 40 plus 200, which is 240 nautical miles from the mainland. The island's area never enters the arithmetic, and a bare rock that cannot support people or an economic life of its own gets no exclusive economic zone at all.`, kind: 'tip' },
    { content: `Two coasts closer than 400 nautical miles apart produce an overlap, because 200 plus 200 is 400. Inside the overlap the 200 rule says yes to both states and therefore settles nothing.`, kind: 'tip' },
    { content: `The median line splits the overlap: every point on it is the same distance from the nearest point of each coast, so across 300 nautical miles it runs at 150 from each. Test a point by comparing its two distances, which must add back to the gap.`, kind: 'tip' },
    { content: `An overlap is split, not awarded. Both claims were correct, and the line is where two states start from, not a verdict that one of them was wrong.`, kind: 'tip' },
    { content: `Don't say "international waters" for everything past 12 nautical miles. Past 12 is the exclusive economic zone (12–200 nm), where the coastal state still controls fish and seabed. Only past 200 nm is the high seas.`, kind: 'common-error' },
    { content: `Always name the baseline you measured from, then add the distances back to check. If a point is 120 nm from Coast A across a 300 nm gap, it must be 180 nm from Coast B, and 120 + 180 = 300.`, kind: 'tip' },
    { content: `Island size (area) does not matter. A 1 km² island 150 nm offshore moves the exclusive economic zone to 350 nm (150 + 200), same as a 1,000 km² island at the same spot.`, kind: 'gotcha' },
    { content: `A bare rock (no people, no economic life) gets a 12 nm territorial sea but no exclusive economic zone. So a bare rock 180 nm out does not extend the zone to 380 nm.`, kind: 'edge-case' },
    { content: `Inside an overlap, the 200 nm rule says yes twice and settles nothing. You must use the median line. Across 300 nm, the median is at 150 nm from each coast.`, kind: 'vocab-note' },
    { content: `Test for an overlap first: if the two coasts are less than 400 nm apart, there is one (because 200 + 200 = 400). If the gap is 400 or more, no overlap exists.`, kind: 'tip' },
    { content: `Distance and activity both matter. Two boats at 40 nm: a cargo ship needs no permit (crossing is not a resource), but a trawler does (fishing is a resource). Same zone, different answers.`, kind: 'common-error' },
    { content: `When two coasts face each other, measure both distances from the same baseline on one coast to check your work. The distances must sum to the gap between the coasts.`, kind: 'tip' },
  ],
};
