/**
 * Grade 8 World Geography — Unit 6 CED 6.2: Comparing Energy Sources.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.comparing-energy-sources.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U6_COMPARING_ENERGY_SOURCES: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.comparing-energy-sources.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 6,
  cedTopic: '6.2',
  cedTitle: 'Comparing Energy Sources',
  planId: 'evelyn.ms.m8geo.comparing-energy-sources.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.comparing-energy-sources.v1' }],
  theory: [
    { loId: 'm8geo.comparing-energy-sources', content: `A TABLE OF SOURCES HAS NO WINNER UNTIL A GOAL AND A PLACE ARE ATTACHED TO IT. Sources sort into the ones that replace themselves and the ones that do not, and that sort does not settle this question -- two towns holding the same table and the same sort pick differently, and neither is mistaken. So read the goal first and split it into two lists. The MUST-HAVES are the things a source either satisfies or is out of the comparison: a goal of "supply the town every hour of the year" makes steadiness a must-have. The rest are the criteria the survivors are compared on: with that must-have settled, cost decides among what is left. Change the goal to "cut what we send up the chimney" and the emissions column takes charge while fuel cost drops to a tiebreaker. Same five columns, two different winners.` },
    { loId: 'm8geo.comparing-energy-sources', content: `CROSS OUT WHAT THE PLACE CANNOT HOST BEFORE YOU COMPARE ANYTHING. One of the five columns asks whether the source has to sit near a particular thing: a river with enough fall and a steady flow, hot rock close to the surface, a ridge where the wind blows hard most of the time, a basin with many clear days, a seam of fuel or a rail line, pipeline or port that can bring fuel in. That column is a gate, not a preference. A source that comes out ahead on every other column and cannot be built in that place comes out at nothing there, and a comparison that leaves it in the list is holding a real option up against something that is not one. Do the crossing-out first, and name the place-fact that did it: "no fall in the river" is an answer, and "the hydro plant came out low" is not.` },
    { loId: 'm8geo.comparing-energy-sources', content: `A RATING IS A CEILING; SIZE THE PLAN BY THE AVERAGE. The number on the brochure is what a source puts out when conditions are at their best. What a plan can count on is the average it delivers across a whole year. An array rated at 27 megawatts that averages 9 megawatts across the year delivers one third of its rating: 9 divided by 27 is one third, and one third of 27 is 9, so the check closes. Turn that average into the figure a day is built from by multiplying by the hours in a day: 9 megawatts times 24 hours is 216 megawatt-hours. Putting the rating where the average belongs -- 27 times 24, which is 648 -- overstates the source by exactly the gap between the two numbers, and it is the most common wrong step in this whole comparison.` },
    { loId: 'm8geo.comparing-energy-sources', content: `A SOURCE WHOSE OUTPUT VARIES WITH THE WEATHER IS COMPARED AS PART OF A MIX, NEVER ON ITS OWN. An average across a year is not a promise about any particular day. On a calm, cloudy day a weather-dependent source delivers close to nothing, and the demand does not drop to nothing alongside it, so something else has to run. That something is part of the candidate, not a separate question: the honest comparison sets the variable source PLUS its backup against a source that runs steadily on its own, because only those two things do the same job. And the backup is sized by the worst day rather than the average one. It has to be able to carry the whole demand by itself, even if it spends most of the year carrying a quarter of it.` },
    { loId: 'm8geo.comparing-energy-sources', content: `PRICE THE MIX ACROSS A WHOLE DAY, WITH THE DIGITS, AND THEN INVERT. Take what the day needs, subtract what the variable source supplies on an average day, and the remainder is what the fuel-burning part has to make. A town drawing 12 megawatts every hour needs 12 times 24, which is 288 megawatt-hours a day. If the variable source supplies 180 of those, the remainder is 288 minus 180, which is 108. At $150 for each megawatt-hour that is 108 times 150, or $16,200 on an average day, against 288 times 150, which is $43,200, on a day the variable source is out entirely. Then invert: $16,200 divided by $150 is 108 megawatt-hours, and 108 plus 180 is 288, which is the day you started from. If the day does not come back, a zero slipped.` },
    { loId: 'm8geo.comparing-energy-sources', content: `NAME THE TRADE-OFF THE WINNER CARRIES, AND CHECK WHAT THE TABLE LEFT OUT. A verdict that names only the winner is half an answer. The full verdict names the column the winner loses on and says what the plan does about it: the array that buys no fuel needs land and needs a backup; the plant that runs whenever it is called buys fuel on every day it runs and puts out emissions while it does. If one source appears to come out ahead on every column at once, that is the moment to ask whether a column that matters in this place was left out of the table. And the verdict is about the fit between a source and a place, never about the place: a town that burns fuel because nothing else can reach it is not behind anything, it is a town whose siting column came out the way it did.` },
    { loId: 'm8geo.comparing-energy-sources', kind: 'definition', title: 'energy mix', content: `the set of sources a place runs together, chosen so that what one of them does not supply in a given hour, another one does.` },
    { loId: 'm8geo.comparing-energy-sources', kind: 'definition', title: 'rated output', content: `what a source puts out when conditions are at their best, which is a ceiling on its output and never the figure a plan is sized by.` },
    { loId: 'm8geo.comparing-energy-sources', kind: 'definition', title: 'average output', content: `what a source delivers across a whole year once its good and its bad days are counted together, found by spreading the year evenly; this is the figure a plan is sized by.` },
    { loId: 'm8geo.comparing-energy-sources', kind: 'definition', title: 'variable source', content: `a source whose output rises and falls with the weather, so that what it delivers on any one day is not something a plan can count on.` },
    { loId: 'm8geo.comparing-energy-sources', kind: 'definition', title: 'steady source', content: `a source that can be run at a chosen level whenever it is called for, which is what lets it cover the hours a variable source is out.` },
    { loId: 'm8geo.comparing-energy-sources', kind: 'definition', title: 'siting requirement', content: `a condition a source has to find already present in a place before it can be built there at all, which removes a candidate from a comparison rather than lowering it in one.` },
  ],
  methods: [
    {
      title: 'Worked run the routine on carron',
      steps: [
        `Step one: read the goal and split it. "Every hour of the year" is a must-have, and it is a hard one: a candidate has to be able to supply Carron on its worst day, not only on an average one. "Hold the fuel bill as low as that goal allows" is the criterion the survivors are compared on. Nothing else is being compared here, and saying that out loud keeps the emissions and land columns from quietly taking over a decision the council did not ask them to make.`,
        `Step two: cross out what the plateau cannot host. The hydro plant needs a river with a fall and a steady flow, and no river within reach of Carron has any fall at all. It is out. The place-fact that put it out is "no fall in the river", not a poor showing on cost. Two candidates remain, and neither the wind array nor the generator set has a siting requirement Carron fails: the ridge is windy and a road reaches the town.`,
        `Step three: turn the rating into the figure the plan is built from. WRONG: "The array is rated at 45 megawatts and the town draws 20, so wind alone covers Carron twice over." CORRECT: the rating is what the ridge delivers when the wind is at its strongest. Across a year the array averages 15 megawatts. 15 divided by 45 is one third, and one third of 45 is 15, so the check closes. The wrong step is worth pricing so you can recognize it later: 45 times 24 hours is 1,080 megawatt-hours, which is more than double what Carron uses in a day, and it would tell the council to build no generators at all.`,
        `Step four: work the average day. Carron draws 20 megawatts every hour, so a day takes 20 times 24, which is 480 megawatt-hours. The array supplies 15 times 24, which is 360 of them. The generator set makes up the rest: 480 minus 360 is 120 megawatt-hours.`,
        `Step five: apply the must-have, which the average day hides. On a calm day the array delivers close to nothing and Carron still needs its 480 megawatt-hours. So the array cannot meet the goal on its own, and the generator set is not a rival candidate -- it is part of the same one. It also has to be sized at the full 20 megawatts, even though on an average day it supplies only 120 of the 480, which is 120 divided by 480, or one quarter. Check: one quarter of 480 is 120. A backup is sized by the worst day.`,
        `Step six: price the mix on the criterion the goal named. At $180 for each megawatt-hour, an average day costs 120 times 180, which is $21,600. A day with no wind at all costs 480 times 180, which is $86,400. Generators on their own would cost that $86,400 every day of the year; the array takes 360 megawatt-hours a day off the bill, and 360 times 180 is $64,800, which is exactly $86,400 minus $21,600.`,
        `Step seven: invert, then rewind the input. $21,600 divided by $180 is 120 megawatt-hours; 120 plus 360 is 480; 480 divided by 24 is 20 megawatts, which is the demand the problem started from, so nothing slipped. Now read the data backwards and confirm the verdict follows from it: no fall in the river, a ridge windy most days, 45 rated against 15 averaged, $180 a megawatt-hour by road, 20 megawatts wanted every hour. A town with a windy ridge, no river and expensive delivered fuel is exactly the place where a mix of array and generators beats generators alone, and where the array alone cannot be trusted with an every-hour goal.`,
        `Now change ONE input and run it again. Suppose a survey finds that a stream reaching Carron drops 50 meters through a gorge just above the town and runs all year. The hydro row is no longer crossed out. It runs steadily, so it satisfies the must-have by itself, and it buys no fuel, so on the criterion the goal named it comes out at $0 a day against $21,600 for the array-and-generator mix. Nothing about the wind changed. Nothing about the price of fuel changed. One column changed -- the one that asks what the place has -- and the answer changed completely. That column is why two towns holding the same table build different things.`,
      ],
      example: { problem: `Run the routine straight through, then price what it leaves you with.

Carron is a town on a high, dry plateau. The ridge above it is windy on most days of the year. No river within reach of the town has any fall in it, there is no hot rock near the surface, and the nearest fuel pipeline ends 300 kilometers away, though a road reaches the town. Carron draws 20 megawatts of electricity at every hour of the day and night, all year round.

The council has three candidates.

"Wind array on the ridge: rated 45 megawatts, averages 15 megawatts across a year, no fuel to buy.

Oil-burning generator set: runs at any level up to 20 megawatts whenever it is called for, fuel delivered by road at $180 for each megawatt-hour.

Small hydro plant: runs steadily, no fuel to buy, needs a river with a fall and a steady flow."

The goal: keep Carron supplied every hour of the year, and hold the fuel bill as low as that goal allows.`, solution: `The hydro plant is crossed out before anything is compared, because no river within reach of Carron has a fall. The rating is not the plan figure: the array averages 15 of its 45 megawatts, which is one third, so it supplies 15 times 24, or 360, of the 480 megawatt-hours Carron uses in a day (20 times 24). The generator set makes the other 120, at 120 times $180, which is $21,600 on an average day; on a day with no wind it makes all 480, at $86,400. The array cannot meet the goal alone, because the goal is every hour and a calm day delivers close to nothing, so the answer is the mix, with the generator set sized at the full 20 megawatts. If a survey found a stream with a 50-meter fall, the hydro row would come back into the comparison, meet the must-have by itself and take the fuel bill to $0 -- one column about the place, and a different answer.` },
      relatedLoIds: ['m8geo.comparing-energy-sources'],
    },
    {
      title: 'Worked same table two places',
      steps: [
        `Run the gate column in each town first, before any arithmetic. Thornvale: a river dropping 60 meters through the valley and running all year is a fall and a steady flow, so the hydro row passes in Thornvale. Delmar: a river that drops 3 meters over its whole length has no fall to work with, so the hydro row is crossed out in Delmar. Same candidate, opposite result, and the reason is a fact about the place rather than anything about the plant.`,
        `Run the land arithmetic for the solar array in each town. The plan calls for 30 megawatts of rating and the array needs 2 hectares for each megawatt, so it needs 30 times 2, which is 60 hectares. Delmar has far more flat land than that at the edge of town, so the array fits there. Thornvale has 12 hectares of unbuilt flat ground: 12 divided by 2 is 6 megawatts of rating, and that is all that will fit. Check the division: 6 times 2 is 12 hectares. Six megawatts against the 30 the plan calls for is one fifth of it, because 6 divided by 30 is one fifth, and one fifth of 30 is 6.`,
        `Deliver Delmar's verdict. Delmar's hydro row is out on the gate, the solar row fits on land with room to spare, the plain has many clear days, and the goal forbids buying fuel, which removes every burning candidate. Delmar builds the array -- not because a solar array is the better source, but because it is the only candidate Delmar can host that meets the goal it was given.`,
        `Now check Thornvale's verdict, and take three pieces of evidence of three different kinds, because any one of them alone would only be a hunch. First, an arithmetic clue: the land allows 6 megawatts of rating against the 30 the plan needs, which is one fifth of it. Second, a seasonal clue of a different kind: Thornvale's shortest days fall in the months the town draws its heaviest load, so the array would be weakest exactly when it is needed most -- a shortfall the land arithmetic says nothing about. Third, a clue of a third kind, from the gate column: the 60-meter fall passes, and a plant on that river runs steadily whatever the sky is doing, which is what an every-hour goal asks for. One number is a hunch; three of different kinds, all pointing the same way, is evidence. Thornvale builds the hydro plant.`,
        `Name the lesson in one line. Not one column of the table changed between the two towns, and not one number in the two candidate rows changed either. What changed was the place: Delmar failed the fall, Thornvale failed the land and the season, and each town's best source is the other town's worst one.`,
        `Say what neither verdict means, because this is where a comparison turns into a ranking if nobody stops it. Neither town is ahead of the other and neither source is the better source. A source is a fit or a misfit for one stated goal in one stated place. And the winner carries a trade-off in both towns: Delmar's array takes 60 hectares out of other use and delivers less through a cloudy week, and Thornvale's plant rests on a single river, so a year that leaves the river low leaves the town short.`,
      ],
      example: { problem: `Two towns are handed the same two candidates and the same goal. Say what each town should build, and name the fact that decides it in each place.

"Delmar: a wide coastal plain with many clear days, and more flat land for sale at the edge of town than any plan would need. The river that crosses the plain drops 3 meters over its whole length.

Thornvale: a narrow valley in the far north. The valley floor is the only flat ground, and 12 hectares of it are not already built on. Winter days there are short, and the town draws its heaviest load in those months. A river drops 60 meters through the valley and runs all year."

Both councils set the same goal: supply the town every hour of the year without buying fuel.

"Solar array: no fuel to buy, output varies with the weather and with the season, needs 2 hectares of flat land for each megawatt of rating. The plan calls for 30 megawatts of rating.

Small hydro plant: no fuel to buy, runs steadily as long as the river runs, needs a river with a fall and a steady flow, needs under 1 hectare."`, solution: `Delmar builds the solar array and Thornvale builds the hydro plant. Delmar's river drops 3 meters over its whole length, so the hydro row is crossed out there on the siting column, while Delmar's flat land easily holds the 60 hectares a 30-megawatt array needs (30 times 2). Thornvale's river drops 60 meters and runs all year, so the hydro row passes there, while Thornvale's 12 hectares of unbuilt flat ground hold only 12 divided by 2, which is 6 megawatts of rating -- one fifth of the plan -- and the town's shortest days fall in its heaviest months. Nothing in the candidate rows changed between the two towns; the places did, and each town failed a different column.` },
      relatedLoIds: ['m8geo.comparing-energy-sources'],
    },
  ],
  pointers: [
    { content: `Students often say "The array is rated at 72 megawatts and Mossen draws 18, so it covers the town four times over and the generators can be shut down for good." — Size the plan by the average, then size the backup by the worst day. Mossen's array averages 24 megawatts across the year: 24 divided by 72 is one third, and one third of 72 is 24, so the check closes. On an average day that is 24 times 24, which is 576 megawatt-hours, against the town's 18 times 24, which is 432 -- more than enough on an average day, and the sentence is still wrong. On a calm day the array delivers close to nothing and Mossen still needs its 432 megawatt-hours. WRONG: "Rated at four times the demand, so the generators can go." CORRECT: "The average says the array carries most of the year; the calm day says the generators stay, and they stay sized at the full 18 megawatts, because a backup is sized by the worst day and not by the average one."`, kind: 'common-error' },
    { content: `Students often say "Norbeck should build a hydro plant, because the town across the ridge built one and it came out best on every column." — Run the siting column for Norbeck before anything is compared. The valley across the ridge has a river that drops 90 meters through it and runs all year. The river at Norbeck drops 4 meters across the whole 30 kilometers it takes to cross the plain, so a plant that needs a fall has nothing there to work with. The hydro row is crossed out of Norbeck's comparison rather than placed at the top of it. WRONG: "It came out best over the ridge, so it comes out best here." CORRECT: "Cross out what Norbeck cannot host, then compare what is left against Norbeck's own goal -- and if that goal is not the same goal the neighboring town set, expect a different winner even among the sources both towns could build."`, kind: 'common-error' },
    { content: `Read the goal and the place first. A table of energy sources has no winner until a goal and a place are attached to it, and the same table gives different winners in different places.`, kind: 'tip' },
    { content: `The column asking whether a source must sit near a particular thing is a gate, not a preference. Cross out what the place cannot host before anything is compared, and name the place-fact that did the crossing.`, kind: 'tip' },
    { content: `A rating is what a source puts out at its best. Size the plan by the average: an array rated at 45 megawatts that averages 15 delivers one third of its rating, and 15 times 24 hours is 360 megawatt-hours on an average day.`, kind: 'tip' },
    { content: `A source whose output varies with the weather is compared as part of a mix, never on its own, because something has to run on the calm day. Size that something by the worst day, not by the average one.`, kind: 'tip' },
    { content: `Price the mix, not the source. On an average day 360 of Carron's 480 megawatt-hours came from the wind and 120 from the generators, and 120 times $180 is $21,600, against 480 times $180, which is $86,400, on a day with no wind at all.`, kind: 'tip' },
    { content: `Invert every figure once: divide the bill back by the price to recover the megawatt-hours, and add the parts back to recover the day.`, kind: 'tip' },
    { content: `Name the trade-off the winner carries. Sources are not good or bad and places are not ahead or behind -- a source is a fit or a misfit for one stated goal in one stated place, and changing one fact about the goal or the place can change the answer.`, kind: 'tip' },
    { content: `Don't use the rating where the average belongs. A 45-megawatt array rated at its best delivers only 15 megawatts on average across a year. Multiply 15 by 24 hours, not 45, to get the megawatt-hours a day is built from.`, kind: 'common-error' },
    { content: `The siting column is a gate, not a ranking. If a place cannot host a source—no river fall, no steady wind, no fuel pipeline—cross it out completely before you compare anything. Name the place-fact that blocked it.`, kind: 'gotcha' },
    { content: `A variable source (wind, solar) always needs a backup. Never compare a wind array by itself against a coal plant by itself. Compare wind-plus-backup as one candidate against coal as another, because only those two do the same job on a calm day.`, kind: 'common-error' },
    { content: `Change the goal or change the place, and the winner changes. Same table, same sources, two towns—different answers. A source is not 'better'; it is a fit or misfit for one goal in one place.`, kind: 'vocab-note' },
    { content: `Size the backup by the worst day, not the average day. If a wind array averages 10 megawatts but drops to zero on a calm day and the town needs 20 megawatts every hour, the generator must be sized at 20 megawatts, not 10.`, kind: 'common-error' },
    { content: `Price the mix across a whole day with arithmetic, then invert. If 120 megawatt-hours costs 120 × $180 = $21,600, divide back: $21,600 ÷ $180 = 120. Add the pieces back: 120 + 360 = 480. If the day does not return, a zero slipped.`, kind: 'tip' },
    { content: `Don't swap goal and place. Read the goal first to find the must-haves and the deciding criterion. Then cross out what the place cannot host. Goal tells you what matters; place tells you what is possible.`, kind: 'vocab-note' },
    { content: `Name what the winner gives up. A verdict that says only 'build the array' is half an answer. Say also: 'the array takes 60 hectares of land out of other use and delivers less on cloudy weeks'—that is the trade-off it carries.`, kind: 'gotcha' },
  ],
};
