/**
 * Grade 8 World Geography — Unit 5 CED 5.3: Migration Flows & Their Effects.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.migration-flows-and-their-effects.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U5_MIGRATION_FLOWS_AND_THEIR_EFFECTS: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.migration-flows-and-their-effects.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 5,
  cedTopic: '5.3',
  cedTitle: 'Migration Flows & Their Effects',
  planId: 'evelyn.ms.m8geo.migration-flows-and-their-effects.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.migration-flows-and-their-effects.v1' }],
  theory: [
    { loId: 'm8geo.migration-flows-and-their-effects', content: `PUSH AND PULL PREDICT A FLOW, AND THE ANALYSIS LIVES WHERE THE PREDICTION MISSES. A reason that describes the country people left is a push and a reason that describes the country they went to is a pull, so sorting the stated conditions and settling the direction -- arrivals minus departures for each country, positive for a net receiving country, negative and written with a minus sign for a net sending country -- is the setup, not the answer. Now hold the two against each other. If the country offering the largest pay gap is taking the smallest flow, the pushes and pulls are not wrong; they are incomplete. Something between the two ends is deciding where the flow actually goes, and measuring it is this lesson.` },
    { loId: 'm8geo.migration-flows-and-their-effects', content: `AN INTERVENING OBSTACLE SITS BETWEEN THE TWO ENDS, AND YOU PRICE IT AGAINST WHAT THE MOVER HAS. It comes in three kinds and a case usually states all three: money, which is the fare and the fees and the deposit; distance, which is the days the journey takes; and the rules at the border, which may require a permit, a job offer first, or a wait. A figure on its own settles nothing, so divide the money by the pay where the mover lives and read the answer in months: $3,000 is ten months of pay where pay is $300 a month, and one month of pay where it is $3,000. Price a wait the same way, in the gain it holds back -- two years of waiting is two years of the larger gap arriving as zero. An obstacle does not cancel a pull. It prices it and it delays it, which is why a flow goes first to the smaller gap behind the cheaper crossing.` },
    { loId: 'm8geo.migration-flows-and-their-effects', content: `CHAIN MIGRATION IS THE OBSTACLE FALLING FOR WHOEVER COMES NEXT, AND YOU READ IT AS A COUNT. The data for it is one number: how many people from the origin already live at the destination. It is a count of people and never a description of them. What the count changes is the size of the next mover's obstacle -- a room for the first few weeks instead of a deposit, word about which employers are hiring instead of a search, help with forms in an unfamiliar language -- so each year of arrivals makes the following year cheaper to move into. That is why a flow that has started keeps pointing at the same destination even after another destination begins to offer more, and why arrivals concentrate in a few districts rather than spreading evenly. Chains explain PERSISTENCE and CONCENTRATION. They do not explain why a flow started, because a chain with no pull behind it moves nobody.` },
    { loId: 'm8geo.migration-flows-and-their-effects', content: `EVERY FLOW HAS EFFECTS AT BOTH ENDS, AND A REPORT ON ONE END IS NOT AN EVALUATION. There are four measurements, two at each end, and each one is a number the data can give you. At the origin: money sent home, which is how many people are sending multiplied by how much each sends multiplied by how many months, and then stated as a share OF something the country earns; and the loss of trained workers, which is the share of the people the country trained in an occupation who now work abroad, read together with the posts standing unfilled at home. At the destination: labor supply, read as the unfilled posts before and after; and pressure on housing, read as the households arriving against the homes finished. Compute all four before saying one word about either country.` },
    { loId: 'm8geo.migration-flows-and-their-effects', content: `A GAIN AND A LOSS IN DIFFERENT UNITS DO NOT CANCEL, SO SAY WHAT EACH ONE BUYS AND HOW LONG IT TAKES TO REBUILD. Money sent home arrives every month and can be spent on anything. A trained nurse takes years of training to replace, and the money does not shorten those years. Subtracting a share of export earnings from a share of trained nurses gives a number that means nothing, so the verdict is two sentences instead of one: here is what this country gained, here is what it lost, and here is which of the two can be rebuilt inside the period under discussion. The same discipline holds at the other end -- posts filled this year, homes short this year -- and neither end is added into a single score, because a country is measured on each figure and is never ranked as the winner or the loser of a flow.` },
    { loId: 'm8geo.migration-flows-and-their-effects', content: `A SHORTFALL IS A GAP BETWEEN TWO NUMBERS, AND ONLY ONE OF THEM IS ABOUT ARRIVALS. 2,500 households arriving against 1,500 homes finished is a shortfall of 1,000 homes; finish 2,800 homes instead and the same 2,500 households arrive into a surplus of 300. Point the arithmetic at both inputs and the sentence that comes out is about a building rate as much as an arrival rate, which is what the data actually holds. Every figure in this lesson counts moves, money, posts and homes, and not one of them describes the people who moved. A country at either end holds many communities, many languages and many kinds of work, and a net figure is the balance of thousands of separate household decisions, so no table here supports a sentence that begins "people from that country are".` },
    { loId: 'm8geo.migration-flows-and-their-effects', kind: 'definition', title: 'intervening obstacle', content: `whatever sits between the two ends of a move and has to be paid, waited out or crossed -- the fare and fees, the days of travel, the permit and its wait -- measured against what the person moving has rather than in the abstract.` },
    { loId: 'm8geo.migration-flows-and-their-effects', kind: 'definition', title: 'chain migration', content: `a flow that keeps running to the same destination because the people already there lower what the next move costs, by offering somewhere to stay, word about who is hiring, and help with unfamiliar forms.` },
    { loId: 'm8geo.migration-flows-and-their-effects', kind: 'definition', title: 'money sent home', content: `earnings a worker in another country sends back to a household at home, counted as senders multiplied by amount multiplied by months, and read as a share of something the origin earns; geographers call one of these payments a remittance.` },
    { loId: 'm8geo.migration-flows-and-their-effects', kind: 'definition', title: 'loss of trained workers', content: `the share of the people a country trained in an occupation who now work in another country, read together with the posts left unfilled at home; it is often called brain drain.` },
    { loId: 'm8geo.migration-flows-and-their-effects', kind: 'definition', title: 'net migration', content: `arrivals minus departures for one country over one period, positive when the country gained people by moving and negative when it lost them.` },
  ],
  methods: [
    {
      title: 'Worked largest gap smallest flow',
      steps: [
        `Settle the direction first, because an explanation cannot be tested until you know which way the people went. Departures: Kerrow 24,000 plus 2,000 is 26,000; Talven 6,000; Osmire 1,000. Arrivals: Kerrow 6,000 plus 1,000 is 7,000; Talven 24,000; Osmire 2,000. Subtract for each: Kerrow 7,000 minus 26,000 is -19,000, a net sending country; Talven 24,000 minus 6,000 is 18,000, net receiving; Osmire 2,000 minus 1,000 is 1,000, net receiving. The three nets add to zero: -19,000 plus 18,000 plus 1,000 is 0.`,
        `Size the two pulls, because that is the prediction the rest of the work has to explain away. Talven pays $900 against Kerrow $300, a gain of $600 a month. Osmire pays $2,400 against $300, a gain of $2,100 a month. 2,100 divided by 600 is 3.5, so the monthly gain at Osmire is three and a half times the gain at Talven. Push and pull on their own predict that Osmire takes the larger flow.`,
        `Compare that with what the table says. 24,000 divided by 2,000 is 12: twelve times as many people went the other way, to the smaller gain. Check the division by multiplying back, 12 times 2,000 is 24,000. So the prediction missed, and it missed by a wide margin. WRONG: "People from Kerrow must prefer Talven." CORRECT: "The prediction left something out, and the something is between the two ends, so measure it."`,
        `Price the money obstacle in months of Kerrow pay, which is the only scale that means anything to somebody earning $300 a month. Talven: $150 divided by $300 is 0.5, half a month of pay, paid once, with one day of travel and no permit. Osmire: $3,000 divided by $300 is 10, ten months of pay, before anybody has eaten. Check both by multiplying back: 0.5 times 300 is 150, and 10 times 300 is 3,000.`,
        `Price the wait, because a gain that arrives later is a smaller gain now. Through Talven the first year is $600 a month times 12 months, which is $7,200, less the $150 fare, which leaves $7,050. Through Osmire the permit has not arrived in the first year, so the gain is $0 and the $3,000 still has to be raised. Run it out three years: Talven is $600 times 36 months, which is $21,600, less $150, which is $21,450; Osmire is nothing for 24 months and then $2,100 times 12 months, which is $25,200, less $3,000, which is $22,200. Three years out the two are within $750 of each other, since 22,200 minus 21,450 is 750. One year out they are not close at all. The obstacle never canceled the larger pull -- it pushed the payoff two years down the road, and a household deciding this year is deciding about this year, which is also why the flow to Osmire is 2,000 rather than zero.`,
        `Count the community at each far end, and read it as what it is. 80,000 people born in Kerrow live in Talven and 500 live in Osmire: 80,000 divided by 500 is 160, so one destination holds a hundred and sixty times the number of people from Kerrow that the other holds; check, 160 times 500 is 80,000. That count is why the next move toward Talven costs less than the $150 fare alone suggests -- a room for the first weeks, word about who is hiring, somebody who has filled in the same forms -- so the flow that has been running keeps running the same way. The count says how many people are there. It says nothing whatever about them.`,
        `The check to remember, and it is three clues of different kinds. The flow arithmetic is one kind: twelve times the flow went to one third of the monthly gain. The obstacle arithmetic is a second kind and an independent one: half a month of pay and no wait against ten months of pay and a two-year wait. The community counts are a third kind: 80,000 against 500. All three point the same way, so the verdict is that the flow followed the crossing a Kerrow household could actually pay for this year, not the largest gap on offer. One number is a hunch; three of different kinds, all pointing the same way, is evidence.`,
      ],
      example: { problem: `Explain why the country offering the largest pay gap took the smallest flow.

Three countries recorded every move between them for one year.

"Kerrow to Talven: 24,000. Kerrow to Osmire: 2,000. Talven to Kerrow: 6,000. Osmire to Kerrow: 1,000."

The conditions stated for each country:

"Kerrow: average pay $300 a month. Farm jobs have fallen for six years running.

Talven: average pay $900 a month. It shares a land border with Kerrow; the bus takes one day and the fare is $150; citizens of Kerrow need no permit to work there. 80,000 people born in Kerrow live in Talven.

Osmire: average pay $2,400 a month. It lies across an ocean; the flight and the agency fees come to $3,000; a work permit requires a job offer first and takes about two years to arrive. 500 people born in Kerrow live in Osmire."`, solution: `Kerrow is the net sending country at -19,000 (7,000 arrivals minus 26,000 departures); Talven is net receiving at 18,000 and Osmire at 1,000, and the nets add to zero. Osmire offers the larger pull, $2,100 a month against $600, which is 3.5 times as much, yet it took one twelfth of the flow. The obstacle explains it: $150 is half a month of Kerrow pay against $3,000, which is ten months, and the Osmire permit takes two years, so the first year returns $7,050 through Talven against $0 through Osmire. The chain reinforces it: 80,000 people born in Kerrow live in Talven against 500 in Osmire, 160 times as many, which lowers the cost of the next move in one direction only.` },
      relatedLoIds: ['m8geo.migration-flows-and-their-effects'],
    },
    {
      title: 'Worked effects at both ends',
      steps: [
        `Origin, first measurement: money sent home. 60,000 senders times $40 a month is $2,400,000 a month, and $2,400,000 times 12 months is $28,800,000 for the year. Invert it to be sure: 28,800,000 divided by 12 is 2,400,000, and 2,400,000 divided by 60,000 is 40. Now say what it is a share OF, because a large number with nothing under it is not a measurement: 28,800,000 divided by 120,000,000 is 0.24, so the money sent home came to 24 percent of what Kerrow earned from exports. Check, 0.24 times 120,000,000 is 28,800,000.`,
        `Origin, second measurement: the loss of trained workers. 240 of the 600 nurses Kerrow trained in five years now work in Talven, and 240 divided by 600 is 0.4, which is 40 percent; check, 0.4 times 600 is 240. Read it with the posts, not on its own: 150 nursing posts stand unfilled in Kerrow clinics. Two numbers, one share and one count, and together they say what the country is short of rather than merely who left.`,
        `Destination, both measurements. Labor supply: unfilled posts fell from 22,000 to 4,000, so 22,000 minus 4,000 is 18,000 posts filled over the year; check by adding back, 4,000 plus 18,000 is 22,000. Housing: 6,000 households arrived against 3,000 homes finished, which is a shortfall of 3,000 homes. The household size is worth confirming, since it is where a count of people becomes a count of homes: 18,000 people divided by 6,000 households is 3 people to a household, and 6,000 times 3 is 18,000. Rent: 460 minus 400 is a rise of $60, and 60 divided by 400 is 0.15, a rise of 15 percent; check, 0.15 times 400 is 60.`,
        `Now evaluate each end separately, and do not run the two sides together. Kerrow gained $28,800,000 arriving month by month into households, which is 24 percent of what its exports earned -- and lost 40 percent of the nurses it trained in five years, with 150 posts unfilled. Talven filled 18,000 posts that had been standing empty -- and ended the year 3,000 homes short of the households that arrived, with rents in those districts 15 percent higher. WRONG: "Kerrow gained 24 percent and lost 40 percent, so Kerrow finished 16 percent behind." CORRECT: "24 percent is a share of export earnings and 40 percent is a share of trained nurses; they are shares of different things and they do not subtract." Say instead which loss can be rebuilt in the period: money can be spent this month, and a nurse takes years of training to replace, so the nursing gap is the one that outlasts the year.`,
        `Rewind the input and read the destination lines backwards, to confirm the answer came from the data. Rent $460 from $400. Posts 4,000 from 22,000. Homes 3,000 finished against 6,000 households. Two of those three lines are about what Talven built and filled; only the household figure is about who arrived.`,
        `Now change ONE input and run it again. Suppose Talven had finished 7,000 homes instead of 3,000, and nothing else changed at all. 7,000 homes against 6,000 households is 1,000 more homes than households, and the shortfall of 3,000 is gone. The same 18,000 people arrived, the same 6,000 households formed, the same 18,000 posts were filled. The shortfall was never a property of the people who arrived: it was the gap between a building number and an arrival number, and the number that moved was the building number.`,
        `Close on what the four figures are and are not. They are measurements of money, posts, nurses and homes, and every one of them belongs to a stated year. They are not a score. Kerrow is not the loser of this flow and Talven is not the winner of it; each country has two figures pointing one way and two pointing the other, and each country holds many communities, many languages and many kinds of work that none of these numbers describes.`,
      ],
      example: { problem: `Evaluate the effects of the Kerrow-to-Talven flow at both ends, then test whether the housing result is a fact about the people who arrived.

"Kerrow, last year: of the 80,000 people born in Kerrow who live in Talven, 60,000 are in paid work, and each sends home $40 a month on average. Kerrow earned $120,000,000 from its exports last year. Kerrow trained 600 nurses over the past five years; 240 of them now work in Talven, and clinics in Kerrow list 150 nursing posts unfilled.

Talven, last year: the net gain from the flow was 18,000 people, who formed 6,000 households. Talven finished 3,000 new homes. Unfilled posts in the districts where arrivals settled fell from 22,000 in January to 4,000 in December. Average rent in those districts rose from $400 to $460 a month."`, solution: `Kerrow: money sent home is 60,000 times $40 times 12, which is $28,800,000, and that is 24 percent of the $120,000,000 Kerrow earned from exports; against it, 240 of 600 trained nurses, or 40 percent, now work in Talven, with 150 posts unfilled. Talven: 18,000 posts filled (22,000 down to 4,000), against 6,000 arriving households and 3,000 homes finished, a shortfall of 3,000, with rent in those districts up $60 on $400, which is 15 percent. The two sides do not subtract, because the shares are shares of different things. Change one input -- 7,000 homes finished instead of 3,000 -- and the same 18,000 arrivals produce 1,000 more homes than households and no shortfall at all, which shows the shortfall sat in the building rate, not in the people who arrived.` },
      relatedLoIds: ['m8geo.migration-flows-and-their-effects'],
    },
  ],
  pointers: [
    { content: `Students often say "Osmire pays eight times what Kerrow pays, so Osmire should be taking the biggest flow." — The pay gaps are real and the flow still runs the other way, so the missing part is the obstacle. Osmire pays $2,400 against Kerrow $300, a gain of $2,100 a month; Talven pays $900, a gain of $600; 2,100 divided by 600 is 3.5, so the Osmire gain is three and a half times larger. But the Osmire journey costs $3,000, and 3,000 divided by 300 is 10 months of Kerrow pay, while the Talven fare of $150 divided by 300 is half a month. The Osmire permit adds a two-year wait, so the first year through Talven returns $600 times 12 less $150, which is $7,050, against $0 through Osmire. And 80,000 people born in Kerrow live in Talven against 500 in Osmire, which is 160 times as many and lowers the cost of the next move in one direction only. WRONG: "The largest pay gap takes the largest flow." CORRECT: "The largest pay gap sits behind the largest obstacle, so the flow of 24,000 went to the crossing that costs half a month of pay and starts immediately, and 2,000 went to the one that costs ten months and starts in two years." An obstacle prices a pull and delays it; the numbers were never wrong.`, kind: 'common-error' },
    { content: `Students often say "The rents went up 15 percent, so the people who arrived pushed them up, and Talven would have been better off without them." — A shortfall is a subtraction and it has two inputs. 6,000 households arrived and Talven finished 3,000 homes, so the gap is 3,000 homes. Had Talven finished 7,000, the same 6,000 households would have arrived into 1,000 more homes than households and there would have been no shortfall at all -- the arrival number is identical in both versions, which is exactly what shows the shortfall is not a property of the people who arrived. The sentence also reports one measurement and drops the other: in the same districts in the same year, unfilled posts fell from 22,000 to 4,000, which is 18,000 posts filled. WRONG: "The people who arrived pushed the rents up, so Talven would have been better off without them." CORRECT: "Talven finished 3,000 homes for 6,000 arriving households, a gap of 3,000, while 18,000 posts that had stood empty were filled; both figures belong in the account, and the building rate is the input that moved." Talven holds many communities, many languages and many kinds of work, and so does Kerrow. A country is measured on each figure and is never ranked as the winner or the loser of a flow, and no table of moves supports a sentence about what the people who moved are like.`, kind: 'common-error' },
    { content: `Sorting conditions into push and pull and subtracting arrivals from departures settles the direction. That is the setup. The analysis starts where the largest pull and the largest flow are not the same country.`, kind: 'tip' },
    { content: `Price an intervening obstacle against what the mover has: divide the fare and fees by monthly pay at the origin and read the answer in months. $3,000 is ten months of pay at $300 a month and one month at $3,000.`, kind: 'tip' },
    { content: `Price a wait in the gain it delays. Two years of waiting is two years of the larger gap arriving as zero, which is why a smaller gap behind a cheaper crossing takes the flow first.`, kind: 'tip' },
    { content: `Chain migration is a count: how many people from the origin already live at the destination. It lowers the next mover's obstacle, so it explains why a flow persists and concentrates -- never why it started, and never anything about the people counted.`, kind: 'tip' },
    { content: `Four effect measurements, two at each end: money sent home as a share of what the origin earns, trained workers abroad as a share of those it trained with the posts left unfilled, unfilled posts before and after at the destination, and households arriving against homes finished.`, kind: 'tip' },
    { content: `Shares of different things do not subtract. Report the gain and the loss as two sentences, and say which one can be rebuilt inside the period; money arrives monthly, and a trained nurse takes years to replace.`, kind: 'tip' },
    { content: `A housing shortfall is a gap between households arriving and homes finished, and the building number can move it on its own. Every figure here counts moves, money, posts and homes; none of them describes the people who moved, and no country is ranked as the winner or the loser of a flow.`, kind: 'tip' },
  ],
};
