/**
 * Grade 8 World Geography — Unit 4 CED 4.3: North America: Metropolitan Regions & Urban Form.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.north-america-metropolitan-regions.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U4_NORTH_AMERICA_METROPOLITAN_REGIONS: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.north-america-metropolitan-regions.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 4,
  cedTopic: '4.3',
  cedTitle: 'North America: Metropolitan Regions & Urban Form',
  planId: 'evelyn.ms.m8geo.north-america-metropolitan-regions.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.north-america-metropolitan-regions.v1' }],
  theory: [
    { loId: 'm8geo.north-america-metropolitan-regions', content: `MEASURE THE SPREAD WITH TWO GROWTH FACTORS AND COMPARE THEM, BECAUSE NEITHER ONE ALONE SAYS ANYTHING ABOUT FORM. A growth factor is the later figure divided by the earlier one: a metropolitan area that went from 600,000 people to 900,000 has a population factor of 1.5, and one whose built-up land went from 200 square kilometers to 600 has a land factor of 3. The comparison is the whole move. If the land factor is the bigger of the two, the built-up area spread faster than the population grew and each square kilometer now holds fewer people than before. If the population factor is bigger, the metropolitan area filled in. If they match, the form held steady while the place got larger. "The city grew" is not an answer to this question, because a metropolitan area can grow in people, in ground, or in both, and only the two factors side by side say which.` },
    { loId: 'm8geo.north-america-metropolitan-regions', content: `DIVIDE THE POPULATION FACTOR BY THE LAND FACTOR AND YOU GET THE DENSITY FACTOR DIRECTLY. Density is people divided by land area, so dividing a factor by a factor tells you what happened to that division without computing either density first: 1.5 divided by 3 is 0.5, and a density factor of 0.5 means the people for each square kilometer came out half what they were. Then check it the long way -- 600,000 divided by 200 is 3,000 people per square kilometer, 900,000 divided by 600 is 1,500, and 3,000 times 0.5 is 1,500 -- and invert, by multiplying each density back by its own area to recover its population. If the population does not come back, a zero slipped.` },
    { loId: 'm8geo.north-america-metropolitan-regions', content: `ONE METROPOLITAN DENSITY IS TWO FORMS AVERAGED TOGETHER, SO SPLIT IT BEFORE YOU DESCRIBE ANYTHING. A metropolitan area has a CORE, where buildings stand close together, shops sit under apartments and most of what a person needs in a day is within walking distance, and a SUBURBAN RING around it, where homes stand on separate lots with yards, parking and wide roads between the destinations. Divide each part's population by its OWN land area and the two figures come out several times apart -- a core at 6,000 people per square kilometer beside a ring at 1,000 is a ratio of six. The metropolitan-wide figure is neither of them, and it does not sit halfway either: because most of the built-up land is out in the ring, the average is pulled down close to the ring's figure. Handing the metropolitan average to the core, or to the ring, is the commonest wrong step in this whole lesson.` },
    { loId: 'm8geo.north-america-metropolitan-regions', content: `A VERDICT ABOUT FORM NEEDS THREE KINDS OF EVIDENCE, NOT THREE VERSIONS OF ONE. The first kind is a density: people for each square kilometer, computed for each part separately. The second kind is a share against a share: if the ring holds 90 percent of the built-up land and only 60 percent of the people, it is spread out by construction, and that comparison is true whatever the densities come to. The third kind is how people get around: when homes, shops and jobs are far apart, nearly every trip is driven, and when they are close together a route passes enough doors to be worth running -- so a part where 95 of every 100 trips are by car and a part where 60 of every 100 are is telling you about the distance between destinations. One number is a hunch; three of different kinds, all pointing the same way, is evidence. And every one of those numbers is a measurement of buildings, land and travel, never a verdict on the households living in either part.` },
    { loId: 'm8geo.north-america-metropolitan-regions', content: `THE UNITED STATES RUNS A MULTI-CENTERED URBAN SYSTEM, AND YOU READ IT OFF WHERE THE NATIONAL FUNCTIONS SIT. You already know the pattern in which a single city dwarfs every other in its country and gathers the government, the main business center, the main port and the main airport into one place. The United States is not arranged that way, and the test is to go looking for those functions one at a time. The national government sits in Washington, D.C. Major seaports work the Atlantic coast, the Pacific coast and the Gulf coast. Large airline hubs sit in several different metropolitan areas, inland and coastal. Business centers sit in different places again, and different ones lead in different industries. Because no single metropolitan area holds all of that, the country has many large metropolitan areas rather than one dominant one -- a multi-centered urban system. Along the Atlantic seaboard those centers run in a chain, from the Washington, D.C. area north through Baltimore, Philadelphia and New York to Boston, close enough together that the belt is treated as one northeastern corridor -- and even that corridor is one part of the country's urban system, not its single center.` },
    { loId: 'm8geo.north-america-metropolitan-regions', content: `EVALUATE A GROWTH PROPOSAL BY COMPUTING THE NEW FIGURE FIRST AND NAMING BOTH SIDES OF THE TRADE-OFF SECOND. A GROWTH BOUNDARY is a line around a metropolitan area's built-up land past which new building is not permitted, so that growth goes inward instead of outward. Do the arithmetic before the opinion: put the extra residents on the land the proposal allows and recompute the people for each square kilometer, so the change is a number and not a mood. Then say what is gained -- shorter trips, and more households served by each kilometer of pipe, road and bus route, which lowers what the network costs for each household, and open land outside the line left unbuilt. Then say what is given up and who it lands on -- fewer detached lots for the households that wanted one, and, if building inside the line does not keep pace with the people arriving, higher prices inside it, which press hardest on the households with the least to spend. A proposal that is said to cost nobody anything has not been evaluated; it has been repeated.` },
    { loId: 'm8geo.north-america-metropolitan-regions', kind: 'definition', title: 'built-up area', content: `the ground a settlement actually covers with buildings, streets, parking and yards, measured in square kilometers and counted separately from the number of people standing on it.` },
    { loId: 'm8geo.north-america-metropolitan-regions', kind: 'definition', title: 'metropolitan area', content: `a core settlement together with the surrounding built-up land whose daily travel for work, school and services runs into that core, counted as one unit.` },
    { loId: 'm8geo.north-america-metropolitan-regions', kind: 'definition', title: 'core', content: `the part of a metropolitan area where buildings stand closest together and most of a day's destinations lie within walking distance of one another.` },
    { loId: 'm8geo.north-america-metropolitan-regions', kind: 'definition', title: 'suburban ring', content: `the built-up land around a core, where homes sit on separate lots and the destinations of a daily trip are far enough apart that most trips are driven.` },
    { loId: 'm8geo.north-america-metropolitan-regions', kind: 'definition', title: 'growth factor', content: `the later figure divided by the earlier one, which says how many times as large a quantity became between two dates.` },
    { loId: 'm8geo.north-america-metropolitan-regions', kind: 'definition', title: 'growth boundary', content: `a line drawn around a metropolitan area's built-up land past which new building is not permitted, used to send growth inward rather than outward.` },
  ],
  methods: [
    {
      title: 'Worked two growth factors',
      steps: [
        `Step one: the population factor. 900,000 divided by 600,000 is 1.5. Averly has one and a half times the people it had.`,
        `Step two: the land factor. 600 divided by 200 is 3. Averly covers three times the ground it covered.`,
        `Step three: compare the two factors and get the density factor. 3 is larger than 1.5, so the land outran the people, and dividing gives the size of it: 1.5 divided by 3 is 0.5. A density factor of 0.5 means the people on each square kilometer came out at half what they were. WRONG: "The land grew with the people." CORRECT: "The land grew twice as fast as the people, so the built-up area spread out and each square kilometer now holds half as many people."`,
        `Step four: compute the two densities the long way and check they agree. First survey: 600,000 divided by 200 is 3,000 people per square kilometer. Second survey: 900,000 divided by 600 is 1,500 people per square kilometer. And 3,000 times 0.5 is 1,500, so the factor and the long way give the same answer.`,
        `Invert both, because this is where a slipped zero shows itself. 3,000 times 200 is 600,000, which is the first population. 1,500 times 600 is 900,000, which is the second. Both counts come back.`,
        `Rewind the input and read it backwards. Averly added half again as many people and tripled the ground they stand on. Half again as many people on three times the land is exactly what a halved density looks like, so the verdict comes out of the table and not out of a guess. Notice also what the council report got right: both numbers did go up, and every word of the report is true. It is true and it is useless, because two rises only mean something once you divide one by the other.`,
        `Now change ONE input and run it again, so "growing means spreading" does not get memorized as a rule. Suppose the built-up land at the second survey had been 300 square kilometers instead of 600, with the same 900,000 people. The land factor becomes 300 divided by 200, which is 1.5 -- the same as the population factor -- so the density factor is 1.5 divided by 1.5, which is 1, and nothing changed. Check it the long way: 900,000 divided by 300 is 3,000 people per square kilometer, the same as the first survey, and 3,000 times 300 is 900,000. Same people, same growth, same thirty years, and the form held steady. The spreading was never in the population figure; it was in the land figure all along.`,
      ],
      example: { problem: `Run the routine straight through on a metropolitan area measured twice.

"The Averly metropolitan area. At the first survey: 600,000 people living on 200 square kilometers of built-up land. At the second survey, taken thirty years later: 900,000 people living on 600 square kilometers of built-up land."

A council report says: "Averly grew, and the built-up land grew with it." Measure what actually happened to the form.`, solution: `The population factor is 1.5 (900,000 divided by 600,000) and the land factor is 3 (600 divided by 200), so the density factor is 1.5 divided by 3, which is 0.5: Averly halved its density, from 3,000 people per square kilometer (600,000 divided by 200) to 1,500 (900,000 divided by 600). Multiplying each density back by its own area returns each population. The built-up area spread faster than the population grew. Had the land reached only 300 square kilometers instead of 600, the two factors would both be 1.5, the density would have stayed at 3,000, and the same population growth would have produced no spreading at all.` },
      relatedLoIds: ['m8geo.north-america-metropolitan-regions'],
    },
    {
      title: 'Worked split the average and price the plan',
      steps: [
        `Split the density first, one part at a time, each against its own land. Core: 360,000 divided by 60 is 6,000 people per square kilometer. Ring: 540,000 divided by 540 is 1,000 people per square kilometer. Invert both: 6,000 times 60 is 360,000 and 1,000 times 540 is 540,000, and the two add back to 900,000 on 60 plus 540, which is 600 square kilometers. The split closes.`,
        `Now look at where the metropolitan figure of 1,500 actually sits. The core is at 6,000, the ring is at 1,000, and 6,000 divided by 1,000 is 6 -- the core is six times as dense as the ring. The metropolitan figure is not halfway between them and was never going to be. WRONG: "Averly is a city of 1,500 people per square kilometer, so its neighborhoods are moderately dense." CORRECT: "Averly is 6,000 in the core and 1,000 in the ring, and the 1,500 sits close to the ring because nine tenths of the built-up land is out there."`,
        `Second kind of evidence: a share of land against a share of people. The ring holds 540 of the 600 square kilometers, and 540 divided by 600 is 0.90, so 90 percent of the built-up land. It holds 540,000 of the 900,000 people, and 540,000 divided by 900,000 is 0.60, so 60 percent of the people. Ninety percent of the ground carrying sixty percent of the people is a spread-out form by construction. Check the other way round: the core is 60 of 600 square kilometers, which is 10 percent of the land, and 360,000 of 900,000 people, which is 40 percent of the people. 90 plus 10 is 100 and 60 plus 40 is 100, so nothing has gone missing.`,
        `Third kind of evidence: how people get around. In the ring 95 of every 100 trips are driven and 5 are made by transit; in the core it is 60 driven and 40 by transit, and each pair adds to 100. That gap is a distance measurement in disguise. A transit route earns its riders from the doors it passes, so a part of the metropolitan area where the destinations are far apart gives it too few doors to be worth running, and the trips go by car instead.`,
        `Put the three together. A density of 6,000 against 1,000 is one kind of evidence. Ninety percent of the land holding sixty percent of the people is a second kind. Ninety-five trips in a hundred driven against sixty is a third kind. All three point the same way, and they are not restatements of each other -- the first counts people on land, the second compares two shares, the third counts trips. One number is a hunch; three of different kinds, all pointing the same way, is evidence. The verdict: Averly has a dense core and a low-density suburban ring, and it is a description of buildings, land and travel, not a judgment about anybody living in either part.`,
        `Now evaluate the proposal, and compute before you comment. The next 180,000 residents go inside the present 600 square kilometers: 900,000 plus 180,000 is 1,080,000, and 1,080,000 divided by 600 is 1,800 people per square kilometer. Invert: 1,800 times 600 is 1,080,000. So the proposal is a move from 1,500 to 1,800 across the metropolitan area, and now the trade-off can be stated against a number rather than a feeling.`,
        `Name both sides and say who each lands on. GAINED: destinations move closer together, so trips get shorter; each kilometer of water pipe, road and bus route serves more households, which lowers what the network costs for each household; and the open land outside the line stays unbuilt. GIVEN UP: fewer detached lots with yards for the households that wanted one, which is a real loss to those households and not a small one; and if building inside the line does not keep pace with 180,000 arriving people, the homes inside get more expensive, and higher prices press hardest on the households with the least to spend. Those two sentences are the evaluation. A council that says the boundary costs nobody anything has skipped the second one.`,
      ],
      example: { problem: `Averly's metropolitan density at the second survey is 1,500 people per square kilometer. Split that figure into its two forms, say what kind of form each part has, and then evaluate the council's proposal.

"Averly at the second survey: 900,000 people on 600 square kilometers of built-up land. The core holds 360,000 of those people on 60 square kilometers. The suburban ring holds the other 540,000 on the other 540 square kilometers. In the core, 60 of every 100 trips are made by car and 40 by transit. In the ring, 95 of every 100 trips are made by car and 5 by transit.

The council proposes a growth boundary: no new building outside the present 600 square kilometers, with the next 180,000 residents housed inside it."`, solution: `Core: 360,000 divided by 60 is 6,000 people per square kilometer. Ring: 540,000 divided by 540 is 1,000. The core is six times as dense, and the metropolitan figure of 1,500 sits near the ring because the ring holds 90 percent of the built-up land (540 of 600) while holding 60 percent of the people (540,000 of 900,000). The travel data agrees: 95 of every 100 ring trips are driven against 60 in the core. Three kinds of evidence, one verdict -- a dense core and a low-density suburban ring. Under the proposal, 1,080,000 people on 600 square kilometers is 1,800 per square kilometer, up from 1,500. It buys shorter trips, cheaper networks for each household and unbuilt land outside the line; it costs the households that wanted a detached lot, and, if building does not keep pace, it raises prices inside the line on the households least able to pay them.` },
      relatedLoIds: ['m8geo.north-america-metropolitan-regions'],
    },
  ],
  pointers: [
    { content: `Students often say "The population went up by 300,000 and the land went up by 400, so the two grew by about the same amount." — Compare the factors, not the differences. Population: 900,000 divided by 600,000 is 1.5. Land: 600 divided by 200 is 3. The land factor is twice the population factor, so 1.5 divided by 3 is 0.5 and the density halved -- 600,000 divided by 200 is 3,000 people per square kilometer at the first survey, and 900,000 divided by 600 is 1,500 at the second. Check by inverting: 3,000 times 200 is 600,000 and 1,500 times 600 is 900,000. WRONG: "300,000 and 400 are about the same, so the shape held." CORRECT: "One and a half times the people on three times the land is half the density, so the built-up area spread." A difference between two counts of different things is not a comparison; a factor is, because dividing a quantity by itself leaves the units behind.`, kind: 'common-error' },
    { content: `Students often say "Averly comes to 1,500 people per square kilometer, so that is what the core is like." — Split it and each part speaks for itself. Core: 360,000 divided by 60 is 6,000 people per square kilometer; check, 6,000 times 60 is 360,000. Ring: 540,000 divided by 540 is 1,000 people per square kilometer; check, 1,000 times 540 is 540,000. The core is six times the ring, and 1,500 is neither figure. It sits near the ring because the ring is 540 of the 600 square kilometers, which is 90 percent of the built-up land, and an average over land follows the land. WRONG: "The metropolitan figure is 1,500, so the core is around 1,500." CORRECT: "The core is 6,000, the ring is 1,000, and 1,500 is the figure you get after averaging a small dense part with a large spread-out one." Before describing any part of a metropolitan area, divide that part's people by that part's land.`, kind: 'common-error' },
    { content: `Two growth factors, then compare them. Later population divided by earlier population; later built-up area divided by earlier built-up area. Whichever factor is bigger tells you whether the place spread out or filled in.`, kind: 'tip' },
    { content: `Population factor divided by land factor is the density factor: 1.5 divided by 3 is 0.5, so the density halved. Check it the long way, then multiply each density back by its own area to recover the population.`, kind: 'tip' },
    { content: `One metropolitan density is two forms averaged together. Divide each part by its OWN land: a core at 6,000 and a ring at 1,000 average to a figure that describes neither, and it lands near the ring because the ring holds most of the land.`, kind: 'tip' },
    { content: `A form verdict needs three kinds of evidence, not three versions of one: a density, a share of land set against a share of people, and the share of trips that are driven. All three are measurements of buildings, land and travel, never verdicts on the people living there.`, kind: 'tip' },
    { content: `The United States has many large metropolitan areas rather than one dominant one -- a multi-centered urban system. The national government, the major seaports on three coasts, the large airline hubs and the leading business centers sit in different metropolitan areas, and along the Atlantic seaboard those centers run in a chain from the Washington, D.C. area north through Baltimore, Philadelphia and New York to Boston.`, kind: 'tip' },
    { content: `Evaluate a growth proposal with the arithmetic first: put the new residents on the allowed land and recompute the people for each square kilometer.`, kind: 'tip' },
    { content: `Then name both sides. What is gained -- shorter trips, cheaper networks for each household, land left unbuilt -- and what is given up and who bears it: fewer detached lots, and higher prices inside the line if building does not keep pace. A proposal said to cost nobody anything has not been evaluated.`, kind: 'tip' },
    { content: `Never compare raw differences (e.g., "population went up 300,000 and land went up 400") across two different quantities. Always divide later by earlier to get growth factors, then compare those factors. 1.5 versus 3 tells you something; 300,000 versus 400 tells you nothing.`, kind: 'common-error' },
    { content: `The metropolitan density (e.g., 1,500 people/km²) does NOT describe the core or the ring. Always split it: divide each part's people by THAT part's land separately. A core at 6,000 and a ring at 1,000 cannot be replaced by the metropolitan average of 1,500.`, kind: 'gotcha' },
    { content: `To evaluate a growth boundary or any proposal, compute the new density first (arithmetic, not opinion). Then state both the gain AND the loss and who it lands on. A proposal said to cost nobody anything has skipped the trade-off; that's not evaluation.`, kind: 'tip' },
    { content: `Three kinds of evidence for urban form are NOT three versions of the same thing: (1) densities of each part, (2) share of land vs. share of people, (3) share of trips by car. One number is a hunch; three different kinds pointing the same way is proof.`, kind: 'vocab-note' },
    { content: `The United States is NOT a one-city system like Paris or Tokyo. National government sits in Washington, D.C.; major ports dot three coasts; airline hubs scatter across different metros; business centers vary by industry. That spread across many metros is the definition of multi-centered.`, kind: 'vocab-note' },
    { content: `The Northeastern Corridor (Washington, D.C. to Boston) is ONE part of the U.S. multi-centered system, not the whole system. Don't confuse the corridor with the entire national urban pattern.`, kind: 'edge-case' },
    { content: `Check your density calculation by inverting it: if density × land area does NOT return the population, a zero slipped. Example: 1,500 people/km² × 600 km² = 900,000 people. If that doesn't match, recalculate.`, kind: 'tip' },
    { content: `Don't confuse the core or ring density with the metropolitan density. The ring at 1,000 pulls the average down to 1,500 because the ring holds 90 percent of the land. Density follows land, not population count.`, kind: 'common-error' },
  ],
};
