/**
 * Grade 8 World Geography — Unit 6 CED 6.1: Water Scarcity & Allocation.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.water-scarcity-and-allocation.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U6_WATER_SCARCITY_AND_ALLOCATION: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.water-scarcity-and-allocation.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 6,
  cedTopic: '6.1',
  cedTitle: 'Water Scarcity & Allocation',
  planId: 'evelyn.ms.m8geo.water-scarcity-and-allocation.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.water-scarcity-and-allocation.v1' }],
  theory: [
    { loId: 'm8geo.water-scarcity-and-allocation', content: `START WITH THE BALANCE, AND READ THE SHORTFALL AGAINST TOTAL DEMAND. A river's flow arrives fresh every year and can still be promised out past what arrives, so the first move in any basin is arithmetic: add every user's demand, then subtract the flow available for use. If the demands come to 1,500 million cubic meters a year and the river delivers 1,200, the shortfall is 300. Now say what that 300 is a share OF, because the denominator changes the sentence. 300 divided by the total demand of 1,500 is 0.20, which is 20 percent, and it means every promise in the basin is 20 percent bigger than the water standing behind it. 300 divided by the supply of 1,200 is 25 percent, which is also true and answers a different question -- how much extra water the basin would need. When the claim is about the promises, the denominator is total demand.` },
    { loId: 'm8geo.water-scarcity-and-allocation', content: `THE SHORTFALL IS ONE NUMBER FOR THE WHOLE BASIN, AND IT DOES NOT SAY WHO GOES SHORT. That is the allocation rule's job. An allocation rule is a written procedure that turns one basin-wide supply into an amount for every user, and two basins with identical flow, identical users and identical demands can produce completely different lists of who goes dry, because the rules are different. No arithmetic error is involved in either one. So evaluating a rule is never a question of whether the sums are right. It is the question of who the rule puts at the end of the line, and how much the user at the end of the line loses.` },
    { loId: 'm8geo.water-scarcity-and-allocation', content: `RUN EACH RULE EXACTLY AS WRITTEN, THEN ADD THE DELIVERIES BACK. Three rules cover most basins, and each one is an operation you can carry out. FIXED SHARES: every user holds a written volume and takes it as the water passes, so the users the river reaches first take theirs in full and whoever is last takes what is left. PRIORITY BY FIRST USE: the oldest use is filled completely, then the next oldest, until the water runs out, so the newest uses get nothing -- and the order is by when a user first took water, never by how much a user asks for or where the user sits on the river. PROPORTIONAL CUTS: divide the available flow by the total demand to get one percentage, then give every user that percentage of what it asked for. Whichever rule you run, finish by adding the deliveries. They have to come to the available flow exactly, and if they come to more, the rule was run wrong or some water was counted twice.` },
    { loId: 'm8geo.water-scarcity-and-allocation', content: `TELL THE TWO KINDS OF SCARCITY APART WITH A TEST, NOT WITH HOW SHORT SOMEONE IS. Ask one question about the user who is short: if more water arrived in the basin this year, would this user get some of it? If the answer is yes, the shortage is PHYSICAL -- the basin does not carry enough for the demands on it. If the answer is no, because no canal or pipeline reaches them or the delivered price is past what they can pay, the shortage is ECONOMIC, and the water is already there. The test matters because the fix follows the diagnosis. A physical shortage moves only when demand falls or supply rises. An economic shortage does not move at all when supply rises, because a bigger reservoir sends the extra water down the canals that already exist, to the users already connected to them.` },
    { loId: 'm8geo.water-scarcity-and-allocation', content: `EVERY RULE PROTECTS SOMEONE AND EXPOSES SOMEONE, AND THE DRY YEAR IS WHERE YOU SEE IT. In an average year a rule can look tolerable to every user, because the shortfall is small and everybody still receives something. Drop the flow and the rule shows its shape. A rule made of fixed volumes hands the whole of the additional loss to whoever is last in line, so that user's delivery can fall to zero while the users above them do not lose a drop. A proportional rule moves every user down together. Neither is automatically the better rule, and that is exactly why you run both: an allocation rule is evaluated on the dry-year numbers, because the average year is the year it was designed to survive.` },
    { loId: 'm8geo.water-scarcity-and-allocation', content: `A USER WITH NOTHING IN WRITING BEARS THE SHORTAGE FIRST, AND IS THE EASIEST ONE TO MISS IN THE ARITHMETIC. The river channel itself, a marsh at the mouth, a fishery below the last diversion: each of those has a need you can put a number on, and under any rule that fills written shares first it receives whatever is left over, which in a short year is nothing. The arithmetic still balances, because the deliveries still add to the supply -- so a basin can come out perfectly balanced on paper and still have a user at zero. Before calling a rule workable, list every user the basin has, not every user the rule names, and check what each one actually receives.` },
    { loId: 'm8geo.water-scarcity-and-allocation', kind: 'definition', title: 'river basin', content: `all the land whose water drains into one river system, which is why every user in it is dividing up a single annual flow.` },
    { loId: 'm8geo.water-scarcity-and-allocation', kind: 'definition', title: 'available flow', content: `the volume of water a river carries past a point in a year that can be taken for use, and the supply every allocation is divided out of.` },
    { loId: 'm8geo.water-scarcity-and-allocation', kind: 'definition', title: 'shortfall', content: `the amount by which the demands on a basin exceed its available flow, found by adding the demands and subtracting the flow.` },
    { loId: 'm8geo.water-scarcity-and-allocation', kind: 'definition', title: 'physical scarcity', content: `a shortage that remains once the whole flow has been divided out, because the demands add up to more water than the basin carries.` },
    { loId: 'm8geo.water-scarcity-and-allocation', kind: 'definition', title: 'economic scarcity', content: `a shortage that remains for a user while water is still available in the basin, because nothing delivers it to them or the delivered price is past what they can pay.` },
    { loId: 'm8geo.water-scarcity-and-allocation', kind: 'definition', title: 'allocation rule', content: `the written procedure that turns one basin-wide supply into an amount for each user, and so decides who bears a shortage.` },
  ],
  methods: [
    {
      title: 'Worked balance and two scarcities',
      steps: [
        `Add the demands before anything else, because a basin balance is a sum and a subtraction and nothing more. 600 plus 300 is 900, plus 450 is 1,350, plus 150 is 1,500. Total demand is 1,500 million cubic meters a year against an available flow of 1,200.`,
        `Subtract to get the shortfall. 1,500 minus 1,200 is 300 million cubic meters a year that the promises call for and the river does not carry.`,
        `Say what the 300 is a share of, because the denominator changes the sentence. 300 divided by 1,500 is 0.20, which is 20 percent: every promise in this basin is 20 percent bigger than the water standing behind it. WRONG: "The shortfall is 300 out of the 1,200 the river carries, so the basin is 25 percent short of its promises." CORRECT: "300 divided by the total demand of 1,500 is 20 percent, which is the share of the promises that cannot be kept. 300 divided by the supply of 1,200 is 25 percent, which is a true figure answering a different question -- how much extra water the basin would need in order to keep them."`,
        `Invert both figures. 1,200 plus 300 is 1,500, so the supply and the shortfall rebuild the demand. 20 percent of 1,500 is 300, so the share rebuilds the shortfall. And 25 percent of 1,200 is also 300, which is exactly why each percentage has to be labeled with what it was divided by: the same 300 sits underneath both of them.`,
        `Diagnose the basin, then diagnose Dunmere, running the same test each time: if more water arrived in the basin this year, would this user get some of it? For Adder Valley, Brackwell, Corran and the marshes the answer is yes, because all four sit on the river or on its canals and a bigger flow is a bigger delivery. The basin's 300 million cubic meter shortfall is PHYSICAL scarcity. For Dunmere the answer is no. Dunmere stands 300 meters above the river with no pipeline, so extra water in the channel runs past below the town and nothing about the town changes.`,
        `Check Dunmere with three clues of different kinds, because one clue is a hunch. First, a volume: the basin delivers 1,200 million cubic meters a year, so water is being moved in quantity nearby. Second, a piece of geometry: the nearest canal is 40 kilometers away and 300 meters below the town, and no pipeline closes that gap. Third, a price: Dunmere pays $8 for 1,000 liters against $1 on the canal, and 8 divided by 1 is 8, so the same water costs eight times as much by the time it reaches a Dunmere household. A volume, a distance and a price are three different kinds of evidence, and all three point the same way -- Dunmere faces ECONOMIC scarcity.`,
        `Now change ONE input and run it again, which is also the sharpest test of both diagnoses. Suppose a wet year brings the available flow to 1,600 million cubic meters. 1,600 minus 1,500 is a surplus of 100: every written demand is met in full and the physical shortage is gone. Dunmere is still 40 kilometers from the canal, still 300 meters above the river, and still paying $8 for 1,000 liters. One kind of scarcity vanished with the extra water and the other did not move at all, which is the whole reason for keeping them apart.`,
      ],
      example: { problem: `Work out whether this basin can meet its demands, and then work out what kind of shortage each user faces.

"The Kestrel River rises in mountains and flows west across dry country. Measured where it leaves the mountains, the flow available for use averages 1,200 million cubic meters a year. Four users draw on it. In the order the water passes them: Adder Valley Farms, which asks for 600 million cubic meters a year; the city of Brackwell, which asks for 300; Corran Orchards, 450; and the Kestrel Marshes at the river mouth, whose stated need is 150.

The town of Dunmere, 4,000 people, sits in the same basin on a bluff 300 meters above the river and 40 kilometers from the nearest canal. No pipeline reaches it. Dunmere households buy water from tanker trucks at $8 for 1,000 liters. Households beside the canal pay $1 for the same 1,000 liters."`, solution: `Total demand is 1,500 million cubic meters a year (600 plus 300 plus 450 plus 150) against 1,200 available, so the shortfall is 300. That is 20 percent of total demand (300 divided by 1,500), not the 25 percent you get by dividing by the supply. The basin's shortfall is PHYSICAL scarcity, because more water in the river would reach all four users on it. Dunmere faces ECONOMIC scarcity: water is being delivered in quantity 40 kilometers away and 300 meters below the town, no pipeline reaches it, and tanker water costs $8 for 1,000 liters against $1 on the canal, which is eight times as much. In a wet year of 1,600 the physical shortfall turns into a surplus of 100 and Dunmere's shortage does not change.` },
      relatedLoIds: ['m8geo.water-scarcity-and-allocation'],
    },
    {
      title: 'Worked three rules and a dry year',
      steps: [
        `Rule one, FIXED SHARES: each user holds a written volume equal to its demand and takes it as the water passes. Adder Valley takes 600, leaving 1,200 minus 600, which is 600. Brackwell takes 300, leaving 300. Corran asks for 450 and 300 is what is there, so Corran takes 300 and is short 150. The marshes take what is left, which is nothing, and are short 150. Add the deliveries: 600 plus 300 plus 300 plus 0 is 1,200, the whole supply. Add the losses: 150 plus 150 is 300, the whole shortfall. Corran loses 150 of the 450 it asked for, which is one third of its demand, and the marshes lose all 150 of theirs.`,
        `Rule two, PRIORITY BY FIRST USE: fill the oldest use completely, then the next oldest, until the water runs out. The order here is Corran, then Brackwell, then Adder Valley, and it is not the order the water flows in. Corran takes 450, leaving 750. Brackwell takes 300, leaving 450. Adder Valley asks for 600 and receives 450, so it is short 150. The marshes have no recorded use and receive nothing, short 150. Add the deliveries: 450 plus 300 plus 450 plus 0 is 1,200. WRONG: "Adder Valley is the farthest upstream, so Adder Valley is served first." CORRECT: "This rule orders users by when each first took water, not by where each sits, and Adder Valley is the newest use of the three, so Adder Valley is the one that goes short."`,
        `Rule three, PROPORTIONAL CUTS: one percentage for everybody. Divide the available flow by the total demand: 1,200 divided by 1,500 is 0.8, so every user receives 80 percent of what it asked for and takes a 20 percent cut. Adder Valley: 80 percent of 600 is 480. Brackwell: 80 percent of 300 is 240. Corran: 80 percent of 450 is 360. The marshes: 80 percent of 150 is 120. Add the deliveries: 480 plus 240 plus 360 plus 120 is 1,200. Add the cuts: 120 plus 60 plus 90 plus 30 is 300.`,
        `Now put the three lists beside one another and answer the real question, which is not what the arithmetic is but who bears the shortage. Under fixed shares the whole 300 falls on Corran and the marshes, the last two users the water reaches. Under priority by first use the whole 300 falls on Adder Valley and the marshes, the two newest uses, and the orchard that went short under the first rule is now filled completely. Under proportional cuts nobody escapes and nobody is wiped out: the 300 is split 120, 60, 90 and 30. One basin, one shortfall, three different answers, and not one of the three involves a mistake.`,
        `Rewind the input and read it backwards to be sure nothing was misread: 150 for the marshes, 450 for Corran, 300 for Brackwell, 600 for Adder Valley. 150 plus 450 is 600, plus 300 is 900, plus 600 is 1,500. The available flow is 1,200. Those are the two figures all three rules were run on.`,
        `Change ONE input -- the flow -- and run two of the rules again. A dry year brings the available flow to 900 million cubic meters. FIXED SHARES: Adder Valley takes its written 600, leaving 300; Brackwell takes its written 300, leaving nothing; Corran receives 0 and the marshes receive 0. Adder Valley and Brackwell lose nothing at all, and Corran falls from 300 in the average year to 0. PROPORTIONAL CUTS: 900 divided by 1,500 is 0.6, so every user receives 60 percent -- Adder Valley 360, Brackwell 180, Corran 270, the marshes 90 -- and 360 plus 180 plus 270 plus 90 is 900. Every user's delivery falls by exactly a quarter from the average year: 480 to 360, 240 to 180, 360 to 270, 120 to 90.`,
        `That is the evaluation, and it could not have been made on the average-year numbers, where both rules still delivered something to almost everybody. Losing an extra 300 between two users and losing it across four users are not the same event, and the rule decided which one happened. A fixed-volume rule concentrates a dry year on whoever is last in line; a proportional rule spreads it. Which one a basin should choose is an argument about who can absorb a loss, but the arithmetic settles what each rule actually does, and that is the part you can check.`,
      ],
      example: { problem: `Three allocation rules, one basin, the same 300 million cubic meters of shortfall. Work out what each user receives under each rule, say who bears the shortage, and then test two of the rules on a dry year.

"The Kestrel River again: 1,200 million cubic meters a year available, and demands of 600 for Adder Valley Farms, 300 for the city of Brackwell, 450 for Corran Orchards and 150 for the Kestrel Marshes, which come to 1,500. The water passes the users in that order, Adder Valley first and the marshes last.

The basin keeps a record of when each user first took water. Corran Orchards was first, then Brackwell, then Adder Valley Farms. The marshes hold no written share and have no recorded date."`, solution: `Fixed shares: Adder Valley 600, Brackwell 300, Corran 300, the marshes 0, so the whole 300 shortfall falls on the last two users the water reaches. Priority by first use: Corran 450, Brackwell 300, Adder Valley 450, the marshes 0, so the whole 300 falls on the newest uses, which moves it from Corran onto Adder Valley. Proportional cuts: 1,200 divided by 1,500 is 80 percent for everybody, giving 480, 240, 360 and 120, and splitting the 300 as 120, 60, 90 and 30. Every list adds back to 1,200. In a dry year of 900 the fixed-share rule takes Corran from 300 to 0 while Adder Valley and Brackwell lose nothing, and the proportional rule drops every user to 60 percent of demand.` },
      relatedLoIds: ['m8geo.water-scarcity-and-allocation'],
    },
  ],
  pointers: [
    { content: `Students often say "A proportional cut is the equal rule, so all three users end up with the same amount of water." — Run it with the digits. The demands add to 300 plus 150 plus 50, which is 500, against an available flow of 400, so the shortfall is 100 and the cut is 100 divided by 500, which is 20 percent. Every user receives 80 percent of what it asked for: 80 percent of 300 is 240, 80 percent of 150 is 120, and 80 percent of 50 is 40. Check it both ways: 240 plus 120 plus 40 is 400, the whole supply, and the cuts of 60, 30 and 10 add to 100, the whole shortfall. WRONG: "Everyone is cut the same, so everyone ends up with the same." CORRECT: "Everyone is cut by the same 20 percent, which is 60 million cubic meters for the largest user and 10 for the smallest, so what a proportional rule equalizes is the percentage, never the water."`, kind: 'common-error' },
    { content: `Students often say "Larrow Farms asks for the most, so priority puts Larrow first." — The order is Quennet, then Rilby, then Larrow, because that is the order in which they first took water. Fill the oldest completely: Quennet receives its 100, leaving 500 minus 100, which is 400. Rilby receives its 150, leaving 250. Larrow asks for 350 and 250 is what is there, so Larrow receives 250 and bears the whole shortage, which is 350 minus 250, or 100. Check: 100 plus 150 plus 250 is 500, the whole supply, and the demands of 100 plus 150 plus 350 come to 600, so the shortfall is 600 minus 500, which is 100 -- the same 100 that Larrow lost. WRONG: "The biggest user is served first." CORRECT: "The oldest use is served first, and under this rule the largest user can be the one that goes short, because it happens to be the newest."`, kind: 'common-error' },
    { content: `Start with the balance: add every user's demand, subtract the available flow, and the difference is the shortfall.`, kind: 'tip' },
    { content: `Divide the shortfall by TOTAL DEMAND to say what share of the promises cannot be kept. Dividing it by the supply is a true figure that answers a different question.`, kind: 'tip' },
    { content: `The shortfall is one number for the whole basin and says nothing about who goes short. The allocation rule decides that.`, kind: 'tip' },
    { content: `Fixed shares: each user takes its written volume as the water passes, and whoever is last takes what is left. Priority by first use: the oldest use is filled first and the newest gets nothing, ordered by date and never by size or position. Proportional cuts: available flow divided by total demand gives one percentage for everybody.`, kind: 'tip' },
    { content: `Whichever rule you run, add the deliveries back. They have to come to the available flow exactly.`, kind: 'tip' },
    { content: `Physical or economic: if more water arrived in the basin, would this user get some? Yes means physical, and only demand or supply can move it. No means economic, and the fix is a pipeline or a price, because a bigger reservoir sends its water to the users who are already connected.`, kind: 'tip' },
    { content: `Evaluate a rule on the dry-year numbers. A fixed-volume rule can take the last user to zero while the users above lose nothing; a proportional rule moves everyone down together.`, kind: 'tip' },
  ],
};
