/**
 * Grade 8 World Geography — Unit 10 CED 10.3: Comparing Two Regions with Indicators.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.comparing-two-regions-with-indicators.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U10_COMPARING_TWO_REGIONS_WITH_INDICATORS: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.comparing-two-regions-with-indicators.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 10,
  cedTopic: '10.3',
  cedTitle: 'Comparing Two Regions with Indicators',
  planId: 'evelyn.ms.m8geo.comparing-two-regions-with-indicators.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.comparing-two-regions-with-indicators.v1' }],
  theory: [
    { loId: 'm8geo.comparing-two-regions-with-indicators', content: `WRITE THE CRITERION DOWN BEFORE YOU READ THE TABLE. A criterion is one sentence saying what a comparison is FOR: keeping homes out of floodwater, holding export earnings steady through a bad year, reaching every household with an online service. "Which region is doing better" is not a criterion, and it is not a question a table can answer, because the figures in a table are in different units and each one answers a different question. Until the criterion is written down, every row looks equally relevant and none of them is, which is exactly the state in which a person picks the row that suits the answer they already wanted.` },
    { loId: 'm8geo.comparing-two-regions-with-indicators', content: `THE CRITERION SELECTS THE ROWS, AND NAMING THE ROWS YOU SET ASIDE IS PART OF THE WORK. Go dimension by dimension -- physical, population, economic, connectivity -- and for each one say whether it bears on the criterion and why. A criterion about floodwater reaching homes uses the flood-zone figures and nothing else: how many people arrive or leave each year, how much comes in from exports and how many households have a connection say nothing about whether water gets into a house. Setting a row aside out loud is not skipping it. It is the record of the decision, and it is the first thing a person checking your verdict will read.` },
    { loId: 'm8geo.comparing-two-regions-with-indicators', content: `COMPARE ONLY THE SELECTED FIGURES, SHOW THE DIGITS, AND INVERT EACH ONE. Put the two figures side by side in the same form, do the division where the criterion asks for a share, and say how much bigger one is than the other. 300 homes out of 6,000 is 300 divided by 6,000, which is 0.05, or 5 percent; 4,500 out of 15,000 is 0.30, or 30 percent. Then invert: 5 percent of 6,000 is 300 and 30 percent of 15,000 is 4,500, so nothing slipped. A comparison whose arithmetic is not shown cannot be checked by anybody, and a comparison that is not checked is a preference.` },
    { loId: 'm8geo.comparing-two-regions-with-indicators', content: `STATE THE VERDICT IN THE CRITERION'S OWN WORDS, THEN STATE WHAT IT DOES NOT COVER. A finished comparison is two sentences, not one. The first says which region's figures show the greater challenge on this criterion and by how much: "on keeping homes out of floodwater, the second region faces the greater challenge -- 30 percent of its homes sit inside the flood zone against 5 percent, and 4,500 homes against 300." The second says what the verdict is silent about: it says nothing about earnings, nothing about connections, and nothing about the region as a place. Indicators measure conditions. They never grade a region, and they never grade the people who live in one.` },
    { loId: 'm8geo.comparing-two-regions-with-indicators', content: `CHANGE THE CRITERION AND THE VERDICT CAN FLIP, WITH NOT ONE FIGURE CHANGED. The same table that puts one region ahead on floodwater can put the other ahead on export earnings or on connections, because those verdicts are drawn from different rows of it. A flip is not a contradiction and it is not evidence that somebody was careless: both verdicts are true, and they answer different questions. This is also the honesty test for a comparison already made -- ask what criterion would flip it. If the answer is that nothing would, the comparison was almost certainly never about a criterion at all. And a count of dimensions led on is not a verdict either: four figures in four different units answer four different questions, so there is no single question they can vote on, and the one dimension a region loses can be precisely the one the criterion is about.` },
    { loId: 'm8geo.comparing-two-regions-with-indicators', content: `BECAUSE A REGION IS A GROUPING SOMEBODY MADE FOR A JOB, A COMPARISON OF TWO REGIONS ONLY EVER ANSWERS A JOB'S QUESTION. One region can be the districts that drain into a single river, put together so that one river's water could be planned; another can be the districts one port and its rail line serve, put together so that freight could be planned. Neither boundary was found in the ground, and neither was drawn with the other one in mind. So "which of these two is better" is not a question either grouping was built to answer, and the comparisons that do mean something are the ones made on a criterion both groupings can speak to -- floodwater, earnings, connections. Ask what a region was FOR, then ask what your comparison is for, and the two questions together tell you which figures you are allowed to use.` },
    { loId: 'm8geo.comparing-two-regions-with-indicators', kind: 'definition', title: 'criterion', content: `the one sentence stating what a comparison is for, which decides which figures the comparison uses and which it sets aside.` },
    { loId: 'm8geo.comparing-two-regions-with-indicators', kind: 'definition', title: 'dimension', content: `one family of measurements inside a comparison table -- physical, population, economic, connectivity -- grouped so that a criterion can name a whole family at once.` },
    { loId: 'm8geo.comparing-two-regions-with-indicators', kind: 'definition', title: 'grouping rule', content: `the stated rule that decides which districts a region contains, such as draining into one river or being served by one port, and therefore what every figure for that region is a figure for.` },
    { loId: 'm8geo.comparing-two-regions-with-indicators', kind: 'definition', title: 'export concentration', content: `the share of a place's export earnings that comes from its single largest export, found by dividing that export's earnings by the total.` },
    { loId: 'm8geo.comparing-two-regions-with-indicators', kind: 'definition', title: 'net migration', content: `the number of people arriving in a year minus the number leaving, written with a minus sign when more leave than arrive.` },
    { loId: 'm8geo.comparing-two-regions-with-indicators', kind: 'definition', title: 'flip', content: `a change of verdict produced by changing the criterion while every figure in the table stays exactly as it was.` },
  ],
  methods: [
    {
      title: 'Worked run the criterion then change it',
      steps: [
        `Step one: the criterion is already written down, so read it and hold onto it. It is about water getting into homes. Every step after this one is allowed to use only the figures that bear on that.`,
        `Step two: go dimension by dimension and say what is in and what is out. Physical, homes inside the flood zone: IN -- that is the whole of this criterion. Population, net migration: OUT -- whether more people arrive than leave says nothing about whether water reaches a house. Economic, exports: OUT. Connectivity, home internet: OUT. Three of the four dimensions are set aside, and saying so is part of the answer, not a shortcut around it.`,
        `Step three: compare the two figures that are in, in both forms, and show the digits. Counts: 4,500 homes against 300, and 4,500 divided by 300 is 15, so Dunmare has fifteen times as many homes inside the zone. Shares: 300 divided by 6,000 is 0.05, which is 5 percent, and 4,500 divided by 15,000 is 0.30, which is 30 percent; 30 divided by 5 is 6, so Dunmare's share is six times larger. Both forms point the same way, which is worth noticing -- the regions are different sizes, and here that did not change the direction of the answer.`,
        `Invert the arithmetic before going further. 5 percent of 6,000 is 0.05 times 6,000, which is 300. 30 percent of 15,000 is 0.30 times 15,000, which is 4,500. Both counts come back, so no zero slipped.`,
        `Step four: the verdict, in the criterion's own words, and then its limits. On keeping homes out of floodwater, Dunmare faces the greater challenge: 30 percent of its homes sit inside the flood zone against 5 percent, and 4,500 homes against 300. And the second sentence, which is not optional: that verdict says nothing about earnings, nothing about connections, nothing about how many people are arriving or leaving, and nothing whatever about Dunmare as a place or about anybody who lives there. WRONG: "Dunmare is the worse-off region." CORRECT: "On this one criterion, Dunmare's figures show the greater challenge."`,
        `Rewind the input and read it backwards to be sure the verdict came from the table. Dunmare has more homes altogether, 15,000 against 6,000, AND a larger fraction of them in the zone, 30 percent against 5 percent. More homes and a larger fraction is exactly what the largest exposure to floodwater looks like, so the verdict follows from the data rather than from an impression.`,
        `Now change ONE thing -- the criterion, not a single figure -- and run the routine again. New criterion: which region faces the greater challenge in reaching every household with a service that needs a home internet connection? Step two: connectivity is IN; the flood zone, migration and exports are OUT. Step three: Verath has 40 of every 100 households connected, so 100 minus 40, which is 60 of every 100, are not; Dunmare has 80 connected, so 100 minus 80, which is 20 of every 100, are not; and 60 divided by 20 is 3. Invert: 60 plus 40 is 100, and 20 plus 80 is 100, so the two halves of each region account for all of it. Step four: on reaching every household, Verath faces the greater challenge, with three times the share of households left to reach. The verdict has flipped, no figure moved, and both verdicts are true -- they are answers to two different questions.`,
      ],
      example: { problem: `Run the routine straight through on a stated criterion, then run it again on a second criterion and the same table.

A planning agency keeps figures for two regions it drew itself. Verath is the nine districts that drain into one river, grouped so that the river's water could be planned. Dunmare is the six districts served by one port and its rail line, grouped so that freight could be planned.

"Physical -- homes inside the flood zone. Verath: 300 of its 6,000 homes. Dunmare: 4,500 of its 15,000 homes.

Population -- net migration. Verath: -1,200 people a year. Dunmare: +3,000 people a year.

Economic -- exports. Verath earns $200 million a year from exports, of which $124 million is one fruit crop, and it sells 3 different goods abroad. Dunmare earns $500 million, of which $90 million is its largest export, and it sells 11 different goods abroad.

Connectivity -- home internet. Verath: 40 of every 100 households have a connection. Dunmare: 80 of every 100."

Criterion: which region faces the greater challenge in keeping homes out of floodwater?`, solution: `On keeping homes out of floodwater, Dunmare faces the greater challenge: 4,500 of its 15,000 homes are inside the flood zone, which is 30 percent, against 300 of 6,000, which is 5 percent -- fifteen times the homes and six times the share. Migration, exports and connectivity were set aside because none of them bears on whether water reaches a house. The verdict covers that criterion and nothing else. Change the criterion to reaching every household with an online service and the same table flips it: 60 of every 100 Verath households have no connection against 20 of every 100 in Dunmare, three times the share, so Verath faces the greater challenge on that one.` },
      relatedLoIds: ['m8geo.comparing-two-regions-with-indicators'],
    },
    {
      title: 'Worked repair a comparison with no criterion',
      steps: [
        `Check the count on its own terms first, because a wrong move is not always a wrong count. Physical: 5 percent of Verath's homes are inside the flood zone against 30 percent of Dunmare's, so Verath's figure is the lower one. Population: Verath is at -1,200 people a year and Dunmare at +3,000, so Dunmare's is the higher one. Economic: $124 million of Verath's $200 million comes from one crop, which is 124 divided by 200, or 62 percent, against $90 million of Dunmare's $500 million, which is 18 percent, so Dunmare's earnings come from a wider set of sources. Connectivity: 40 of every 100 households against 80, so Dunmare's is the higher one. Three of the four dimensions do read in Dunmare's favor. The count is correct.`,
        `Now say why the correct count settles nothing. The four figures are a share of homes, a number of people a year, a share of dollars and a number of households out of a hundred. Four different units, four different questions -- so there is no single question all four are votes on, and adding up how many each region leads on is not arithmetic, it is a habit. The one dimension Dunmare loses is the flood zone, and if the comparison is about floodwater then that lone dimension is the entire answer. WRONG: "Dunmare leads three to one, so Dunmare is the better-off region." CORRECT: "Dunmare's figures read better on three dimensions and worse on one, and which of those matters is decided by a criterion that this comparison never stated."`,
        `Say the second thing that is wrong, which is bigger than the first. "Better-off region" is not a verdict indicators support at all. The figures measure conditions on named dimensions for a grouping of districts somebody drew for a job -- Verath so that one river's water could be planned, Dunmare so that freight could be planned. Neither grouping was built to answer which of the two is better, and a region is not the kind of thing a measurement grades. The honest form is always: on this criterion, these figures show the greater challenge.`,
        `Repair the comparison by supplying the criterion the agency actually faces: which region faces the greater challenge in holding its export earnings and its population steady through a year in which one industry does badly? Step two, select: the economic dimension is IN, the population dimension is IN because the criterion names population, the flood zone is OUT and connectivity is OUT.`,
        `Step three, compare the selected figures with the digits. Concentration: 124 divided by 200 is 0.62, so 62 percent of Verath's export earnings come from one crop, against 90 divided by 500, which is 0.18, or 18 percent for Dunmare. If that one export earned half as much for a year, Verath would lose half of $124 million, which is $62 million, and 62 divided by 200 is 0.31, a fall of 31 percent in total export earnings; Dunmare would lose half of $90 million, which is $45 million, and 45 divided by 500 is 0.09, a fall of 9 percent. Invert both: 0.31 times $200 million is $62 million, and 0.09 times $500 million is $45 million. Count of goods sold abroad: 3 against 11. Net migration: -1,200 a year against +3,000 a year.`,
        `The check to remember: three clues of different kinds, and they have to be different kinds. The first is a share of money -- a bad year takes 31 percent of Verath's export earnings and 9 percent of Dunmare's. The second is a count of things -- Verath sells 3 different goods abroad and Dunmare sells 11, so Verath has fewer separate earners for the total to fall back on. The third is a flow of people -- Verath is already at -1,200 a year while Dunmare is at +3,000, so a bad year would arrive at Verath on top of a fall that is already happening. A share, a count and a flow, all pointing the same way: one number is a hunch; three of different kinds, all agreeing, is evidence. The verdict is that on THIS criterion Verath faces the greater challenge -- and the first worked example, from the same table, put Dunmare there on flooding. Neither sentence is about the regions. Both are about criteria.`,
      ],
      example: { problem: `A comparison was made without a criterion. Find what is wrong with it, repair it, and reach a verdict the data actually supports.

Using the same two regions and the same figures, a regional newsletter writes: "Dunmare is the better-off region. It is ahead of Verath on three of the four dimensions, so it wins three to one."`, solution: `The count of three to one is correct and the move is wrong twice over. First, four figures in four different units answer four different questions, so there is no question they can vote on, and the single dimension Dunmare loses is the whole answer if the criterion is about floodwater. Second, "better-off region" grades a grouping of districts that was drawn for a job, which is not something indicators do. Repaired with a real criterion -- holding export earnings and population steady through a bad year for one industry -- the economic and population rows are the ones that bear on it, and three clues of different kinds agree: a bad year costs Verath 31 percent of export earnings ($62 million of $200 million) against 9 percent for Dunmare ($45 million of $500 million); Verath sells 3 different goods abroad against 11; and Verath is at -1,200 people a year against +3,000. On that criterion Verath faces the greater challenge, while on flooding the same table put Dunmare there.` },
      relatedLoIds: ['m8geo.comparing-two-regions-with-indicators'],
    },
  ],
  pointers: [
    { content: `Students often say "The flood answer and the export answer cannot both be right, because only one region can be the one facing the greater challenge." — Both verdicts are right, and they are answers to different questions. On floodwater the rows are the flood-zone figures: 4,500 of Dunmare's 15,000 homes are inside the zone, which is 30 percent, against 300 of Verath's 6,000, which is 5 percent, so Dunmare faces the greater challenge there. On holding export earnings through a bad year the row is export concentration: $124 million of Verath's $200 million comes from one crop, which is 62 percent, against 18 percent for Dunmare, so half a year's price on that crop costs Verath 31 percent of its export earnings and Dunmare 9 percent, and Verath faces the greater challenge there. WRONG: "Only one of them can be right." CORRECT: "Both are right, because a verdict belongs to its criterion and the two criteria read different rows." The test of a comparison is not whether it can be reversed -- it is whether the criterion was stated and the right rows were used.`, kind: 'common-error' },
    { content: `Students often say "Regions are just groupings somebody drew, so comparing them does not really tell you anything." — The grouping is a choice, and that is exactly why the criterion has to be stated -- not a reason to give up. Everything inside the grouping is still real: 300 homes inside a flood zone is a real count of real homes, and 4,500 is a real count of real homes, whichever districts the total covers. What the chosen boundary settles is which houses are in the total and therefore which questions the total can answer. Verath is the districts draining into one river, so its figures answer questions about that river's basin; Dunmare is the districts one port and its rail line serve, so its figures answer questions about that port's hinterland. WRONG: "The boundary was drawn by people, so the comparison is meaningless." CORRECT: "The boundary was drawn for a job, so state the criterion, use the rows that bear on it, and say what the verdict does not cover." The answer to a grouping being a tool is to name the tool's job, not to stop measuring.`, kind: 'common-error' },
    { content: `Write the criterion down before you read the table. "Which region is doing better" names no criterion and no table can answer it.`, kind: 'tip' },
    { content: `The criterion selects the rows. Go dimension by dimension -- physical, population, economic, connectivity -- and say out loud which rows are in and which are set aside.`, kind: 'tip' },
    { content: `Compare only the selected figures, show the digits, and invert each computed figure: 300 divided by 6,000 is 5 percent, and 5 percent of 6,000 is 300.`, kind: 'tip' },
    { content: `A verdict is two sentences: which region's figures show the greater challenge on this criterion and by how much, then what the verdict does not cover.`, kind: 'tip' },
    { content: `Change the criterion and the verdict can flip with no figure changed. A flip is two true answers to two different questions, never a contradiction.`, kind: 'tip' },
    { content: `Counting how many dimensions a region leads on is not a verdict. Four units answer four questions, and the one dimension it loses may be the whole criterion.`, kind: 'tip' },
    { content: `A region is a grouping somebody made for a job, so the figures are real and the question they answer is chosen. Measure conditions on a criterion; never grade a region or the people in it.`, kind: 'tip' },
  ],
};
