/**
 * Grade 8 World Geography — Unit 10 CED 10.1: Building a Geographic Argument from Data.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.building-a-geographic-argument.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U10_BUILDING_A_GEOGRAPHIC_ARGUMENT: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.building-a-geographic-argument.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 10,
  cedTopic: '10.1',
  cedTitle: 'Building a Geographic Argument from Data',
  planId: 'evelyn.ms.m8geo.building-a-geographic-argument.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.building-a-geographic-argument.v1' }],
  theory: [
    { loId: 'm8geo.building-a-geographic-argument', content: `A CLAIM IS AN ANSWER TO THE STATED QUESTION, WRITTEN SO THE DATA COULD DISAGREE WITH IT. Before you write one, read the question again and answer THAT question, not the interesting one next to it. Then run the one test that separates a claim from an opinion: name the result that would make your sentence false. "The park is not serving the whole town" fails if every neighborhood turns out to visit at the same rate for each resident, so it is a claim. "The park is a bit disappointing" cannot fail, because no figure could contradict it, so it is not a claim and no amount of data will ever support it. Write the falsifying result down next to the claim. It tells you what to go and look for, and half the time it tells you that you have written a feeling.` },
    { loId: 'm8geo.building-a-geographic-argument', content: `EVIDENCE IS SELECTED, NOT RECITED. A dataset almost always holds more numbers than an argument needs, and the ones that do not bear on the claim are not neutral -- they bury the ones that do. Pick the few figures the claim stands or falls on, and then do the thing most people skip: say what you are leaving out and why. The strongest set is two or three figures of DIFFERENT KINDS -- a rate worked out from counts, a measured distance, a yes-or-no fact about a service -- because three figures of the same kind can all be wrong for the same reason, while three of different kinds cannot.` },
    { loId: 'm8geo.building-a-geographic-argument', content: `REASONING IS THE SENTENCE THAT SAYS WHAT YOU DID TO THE EVIDENCE AND WHY THE RESULT COUNTS. A figure sitting next to a claim is a coincidence until a sentence connects them, and the connecting sentence has two jobs. It names the OPERATION: you already know that a count has to be divided by the denominator the claim names before two places of different size can be compared, so the reasoning says which division you ran -- visits divided by residents, not visits compared straight across. And it names the CRITERION: it says what the claim would mean in the language of that result, so that "harder to reach" becomes "a larger share of residents live beyond a kilometer of it". Miss either job and you have a claim and a number in the same paragraph, which is not an argument.` },
    { loId: 'm8geo.building-a-geographic-argument', content: `A CLAIM OVERREACHES WHEN IT COVERS MORE THAN THE EVIDENCE MEASURED, AND IT RUNS OVER IN THREE SEPARATE DIRECTIONS. EXTENT: the claim names more places or more people than were counted -- a survey at one school becomes a statement about a county. TIME: one reading becomes a trend, or a present becomes a future -- one week in October becomes a typical week of the year. CAUSE: two things measured together become one causing the other -- new lights went in and the count rose, so the lights raised it. Check the three directions one at a time, because a sentence can be honest in two of them and reach in the third, and a reader who checks the sentence as a whole will miss it.` },
    { loId: 'm8geo.building-a-geographic-argument', content: `REPAIR AN OVERREACH BY SHRINKING THE CLAIM, NOT BY SOFTENING IT. Adding "probably", "roughly" or "it seems that" lowers your confidence in the sentence and changes nothing about which places, which dates or which people it covers, so the sentence is still claiming what the data cannot cover. The repair is to rewrite the claim so its extent, its time and its cause each stop exactly where the evidence stops: not "most students in the county live too far to walk" but "at the one school surveyed, 40 percent of students live more than 3 kilometers away". A smaller claim that is fully supported beats a large one that is not, and it is the one you can act on.` },
    { loId: 'm8geo.building-a-geographic-argument', content: `THE DECIDING TEST IS THE DATA YOU DO NOT HAVE YET, AND THE ONE WORTH ASKING FOR IS THE ONE WHOSE TWO POSSIBLE RESULTS POINT OPPOSITE WAYS. Before you request a figure, say out loud what a high result and a low result would each do to your claim. If both answers leave the claim exactly where it is, the figure is decoration, however interesting it sounds -- and a figure that would only repeat what you already have is the commonest kind of decoration. A figure that could overturn the claim is worth more than one that could only agree with it, which is why the most useful question is usually asked somewhere the claim has NOT been tested: the schools nobody surveyed, the path that got no new lights.` },
    { loId: 'm8geo.building-a-geographic-argument', kind: 'definition', title: 'claim', content: `the one-sentence answer to the stated question, written so that a stated result could show it to be false.` },
    { loId: 'm8geo.building-a-geographic-argument', kind: 'definition', title: 'evidence', content: `the particular figures from the data that the claim stands or falls on, chosen out of the dataset rather than listed from it.` },
    { loId: 'm8geo.building-a-geographic-argument', kind: 'definition', title: 'reasoning', content: `the sentence that names the operation run on the evidence and says why that result counts as support for the claim.` },
    { loId: 'm8geo.building-a-geographic-argument', kind: 'definition', title: 'scope of a claim', content: `the places, the span of time and the cause a claim covers, each of which must stop where the measuring stopped.` },
    { loId: 'm8geo.building-a-geographic-argument', kind: 'definition', title: 'overreach', content: `a claim that covers more places, more time or more cause than its evidence measured, repaired by narrowing the claim rather than by hedging it.` },
    { loId: 'm8geo.building-a-geographic-argument', kind: 'definition', title: 'deciding test', content: `a figure not yet collected whose two possible results would point to opposite verdicts on the claim.` },
  ],
  methods: [
    {
      title: 'Worked build the argument',
      steps: [
        `Write a claim that answers the question asked, and write down what would make it false. The question is whether the park is serving the whole town, so the claim has to be about all four neighborhoods: "Park use is concentrated in the two neighborhoods nearest the park; Brightmoor and Corve are not being served yet." That sentence fails if all four neighborhoods turn out to visit at about the same rate for each resident, which means a number can decide it. WRONG: "The park is not popular enough." CORRECT: "Park use is concentrated in the two neighborhoods nearest the park." The first sentence names no figure that could contradict it, so no dataset could ever support it.`,
        `Select the evidence the claim stands on, and put the counts on the same footing first. Visits for each 100 residents: Aldren, 480 divided by 1,200 is 0.4, which is 40 visits for each 100 residents. Brightmoor, 300 divided by 3,000 is 0.1, which is 10 for each 100. Corve, 200 divided by 2,000 is 0.1, which is 10 for each 100. Dunmere, 320 divided by 800 is 0.4, which is 40 for each 100. Invert every one to be sure no zero slipped: 40 for each 100 across 12 hundreds of residents is 480 visits; 10 across 30 hundreds is 300; 10 across 20 hundreds is 200; 40 across 8 hundreds is 320. All four counts come back.`,
        `Notice what the raw counts would have told you, because this is the figure a reader reaches for. WRONG: "Brightmoor and Dunmere use the park about the same -- 300 visits against 320." CORRECT: "300 visits out of 3,000 residents is 10 for each 100, and 320 out of 800 residents is 40 for each 100, so Dunmere uses the park four times as heavily as Brightmoor." The two counts are nearly equal and the two rates differ by a factor of four, so the counts belong in the table and the rates belong in the argument.`,
        `Add the two other kinds of evidence, and leave the rest out on purpose. Distance: the two neighborhoods at 40 visits for each 100 residents are 0.5 and 0.8 kilometers from the park, and the two at 10 are 3.2 and 4.0 kilometers away. Service: the bus reaches the two near neighborhoods and neither far one. Left out: the four raw visit counts, for the reason just given. That is three kinds of evidence -- a rate worked out from counts, a measured distance, and a yes-or-no fact about a bus -- rather than three versions of the same number.`,
        `Write the reasoning sentence, which is the part that is usually missing. "Visits for each 100 residents are four times higher in the two neighborhoods within one kilometer of the park than in the two more than three kilometers away, and the bus reaches only the near pair, so what the counter measured tracks how easy the park is to reach and not how many people live in each neighborhood." That sentence names the operation (visits divided by residents, then compared) and the criterion (serving the whole town means comparable use for each resident across all four neighborhoods).`,
        `Fix the scope before you sign the claim. Extent: four neighborhoods were counted and the claim names those four, so it does not reach. Time: one week was counted, so the claim says "in the week counted" and not "always". Cause: the counter recorded entries, and nobody asked anyone why they did or did not come, so the claim can say that use tracks distance and bus access, and it cannot say why any person stayed home. WRONG: "Brightmoor and Corve residents are not interested in the park." CORRECT: "In the week counted, Brightmoor and Corve residents visited at a quarter of the rate of the two neighborhoods with a short walk and a bus."`,
        `The check to remember. The rates are one kind of evidence and they say use differs by a factor of four. The distances are a second kind and they say the low-use neighborhoods are the far ones. The bus route is a third kind and it says the low-use neighborhoods are the unserved ones. One number is a hunch; three of different kinds, all pointing the same way, is evidence. And the verdict is a measurement of distance, service and use, not a judgment about any neighborhood.`,
      ],
      example: { problem: `A town council asks one question about the riverside park it opened last spring: is the park serving the whole town? Build the argument -- claim, evidence, reasoning -- and give the verdict.

"Varnley has four neighborhoods and one riverside park. For one week a counter at the park gate recorded which neighborhood each visitor came from.

Aldren: 1,200 residents, 480 visits. Brightmoor: 3,000 residents, 300 visits. Corve: 2,000 residents, 200 visits. Dunmere: 800 residents, 320 visits.

Walking distance from each neighborhood center to the park: Aldren 0.5 kilometers, Dunmere 0.8 kilometers, Brightmoor 3.2 kilometers, Corve 4.0 kilometers. The town bus route runs through Aldren and Dunmere and stops at the park. It does not enter Brightmoor or Corve."`, solution: `Claim: in the week counted, park use is concentrated in the two neighborhoods nearest the park, so the park is not yet serving Brightmoor and Corve. Evidence, three kinds: visits for each 100 residents are 40 in Aldren (480 divided by 1,200) and 40 in Dunmere (320 divided by 800) against 10 in Brightmoor (300 divided by 3,000) and 10 in Corve (200 divided by 2,000); the two high-use neighborhoods are 0.5 and 0.8 kilometers from the park and the two low-use ones are 3.2 and 4.0 kilometers away; the bus reaches only the near pair. Reasoning: use for each resident is four times higher where the park is a short walk and a bus ride away, so the counter is tracking ease of reaching the park rather than neighborhood size. The raw counts of 300 and 320 are left out because they make Brightmoor and Dunmere look alike while the rates differ fourfold, and the claim says nothing about why anyone stayed home, because nobody was asked.` },
      relatedLoIds: ['m8geo.building-a-geographic-argument'],
    },
    {
      title: 'Worked repair the overreach',
      steps: [
        `Check the quantifier against the arithmetic first, because it is the one defect that is wrong even about the school that WAS surveyed. 240 divided by 600 is 0.40, which is 40 percent; invert it, 0.40 times 600 is 240, so the division is right. "Most" means more than half, which at this school would be more than 300 of the 600 students. WRONG: "Most students live too far to walk." CORRECT: "40 percent of students live more than 3 kilometers away." 40 percent is a large share and it is not most, and the two words carry different claims.`,
        `Check the extent. The sentence says "students in Tarn County". The survey covered one of the county's four schools, so the evidence reaches the 600 students at Vale Middle School and stops there. Nothing is known about the other three schools -- not that they are similar, and not that they are different.`,
        `Check what the recommendation rests on. "Buy more buses" needs the number of far-living students who are not already carried, and the data gives it: of the 240, 150 already ride a bus, so 240 minus 150 is 90 who do not. Check the split: 150 plus 90 is 240. Those 90 are 90 out of 600 students, which is 15 percent of the school; check, 0.15 times 600 is 90. So the honest version of the recommendation is about 90 students at one school, not about a county.`,
        `Repair the claim by shrinking it to the evidence, and notice what a hedge would not have done. WRONG: "Most students in Tarn County probably live too far to walk." CORRECT: "At Vale Middle School, 240 of 600 students -- 40 percent -- live more than 3 kilometers from school, and 90 of them are not on a bus route." The word "probably" lowers the confidence and leaves the extent, the quantifier and the recommendation exactly as wrong as they were; the rewrite moves all three to where the measuring stopped.`,
        `Now find the deciding test for the county-wide version, by saying in advance what each result would mean. Ask the same distance question at the other three schools. If they come back near 40 percent, the county claim is supported and the survey at Vale was representative of the county. If they come back near 10 percent, the county claim is overturned and Vale is the exception. Two possible results, opposite verdicts, so this is the figure to ask for. A second survey at Vale a month later would be a figure whose high and low results both leave the county claim exactly where it is, and a question about whether students would ride a bus measures willingness rather than distance, which is not what the claim says.`,
        `Rewind the input and read it backwards to confirm nothing was misread: no survey at three of the schools; 150 of the 240 far-living students already on a bus; 240 of the 600 students beyond 3 kilometers; four middle schools in the county. Everything the argument used is in those four lines.`,
        `Change ONE input and run the scope test again, so the repair is not memorized as one fix. Suppose the survey had been run at all four schools, which hold 600 students each -- 4 times 600 is 2,400 students -- and had found 960 of them living more than 3 kilometers away. 960 divided by 2,400 is 0.40, which is 40 percent; check, 0.40 times 2,400 is 960. The EXTENT defect is now gone: the claim may say "in Tarn County". The QUANTIFIER defect is untouched: 40 percent is still not most, and most would still need more than 1,200 of the 2,400. One new input repaired one direction and left the other standing, which is exactly why the three directions are checked one at a time.`,
      ],
      example: { problem: `A local news post reads: "Most students in Tarn County live too far from school to walk, so the county should buy more buses." Find every direction in which that sentence outruns its evidence, repair it, and name the one added piece of data that would most strengthen or overturn the county-wide version.

"Tarn County has four middle schools. A survey was run at one of them, Vale Middle School, which has 600 students. It found that 240 of the 600 live more than 3 kilometers from the school. Of those 240, 150 already ride an existing county bus and 90 do not. No survey was run at the other three schools."`, solution: `The sentence outruns its evidence in three directions. Quantifier: 240 of 600 is 40 percent (240 divided by 600 is 0.40, and 0.40 times 600 is 240), and most would need more than 300 of the 600. Extent: one of the county's four schools was surveyed, so the evidence covers Vale Middle School, not Tarn County. Recommendation: 150 of the 240 already ride a bus, so 240 minus 150 leaves 90 students not carried, which is 15 percent of the school. Repaired: "At Vale Middle School, 240 of 600 students -- 40 percent -- live more than 3 kilometers from school, and 90 of them are not on a bus route." The deciding test is the same distance question at the other three schools, because near 40 percent there would support the county claim and near 10 percent would overturn it. Adding "probably" repairs nothing, since a hedge does not change which students were counted.` },
      relatedLoIds: ['m8geo.building-a-geographic-argument'],
    },
  ],
  pointers: [
    { content: `Students often say "An argument is stronger when it uses every number in the table." — Evidence is selected, and the selection is part of the argument. The claim is about whether the park reaches all four neighborhoods, so the figures it stands on are the visits for each 100 residents (480 divided by 1,200 is 40 for each 100 in Aldren, against 300 divided by 3,000, which is 10 for each 100 in Brightmoor), the walking distances (0.5 and 0.8 kilometers for the high-use pair against 3.2 and 4.0 for the low-use pair) and the bus route. The raw visit counts belong in the table and not in the argument, because 300 visits from Brightmoor set beside 320 from Dunmere say the two neighborhoods use the park about equally, and that is the opposite of what the rates say: 10 for each 100 residents against 40. WRONG: "Put every number in, so the argument has more behind it." CORRECT: "Put in the figures the claim stands or falls on, and say which ones you left out and why." An argument that recites the whole table buries the three figures that decide it.`, kind: 'common-error' },
    { content: `Students often say "Most students in the county probably live too far to walk." — The word "probably" changes nothing that was wrong. Two things were wrong and both survive it. First the quantifier: 240 of 600 students is 240 divided by 600, which is 0.40, or 40 percent, and the check is 0.40 times 600, which is 240; most would need more than 300 of the 600, so "most" is false about the one school that was surveyed. Second the extent: those 600 students are at one of the county's four middle schools, and no survey was run at the other three, so no figure in hand covers the county at all. WRONG: "Most students in the county probably live too far to walk." CORRECT: "At the one school surveyed, 240 of 600 students, which is 40 percent, live more than 3 kilometers from school." Shrink the claim until its extent, its time and its cause each stop where the measuring stopped; a hedge moves none of the three.`, kind: 'common-error' },
    { content: `A claim answers the stated question and can be shown false by a stated result. Write the falsifying result beside it; if no figure could contradict the sentence, it is an opinion and no data will ever support it.`, kind: 'tip' },
    { content: `Evidence is selected, not recited. Pick the few figures the claim stands or falls on, say what you left out and why, and prefer two or three figures of different kinds over three versions of the same one.`, kind: 'tip' },
    { content: `Reasoning names the operation and the criterion: which division was run, and what the result means in the words of the claim. A figure next to a claim with no such sentence is a coincidence, not an argument.`, kind: 'tip' },
    { content: `Counts and rates can point opposite ways, so the argument uses the one the claim needs: 300 visits from 3,000 residents is 10 for each 100, while 320 from 800 residents is 40 for each 100.`, kind: 'tip' },
    { content: `A claim can overreach in three separate directions -- extent, time and cause. Check them one at a time, because a sentence can be honest in two and reach in the third.`, kind: 'tip' },
    { content: `Repair an overreach by shrinking the claim, never by hedging it. "Probably" lowers your confidence and leaves the places, the dates and the cause exactly as wide as they were.`, kind: 'tip' },
    { content: `The deciding test is the figure you do not have yet whose two possible results point opposite ways. Say what each result would mean before you ask for it, and ask somewhere the claim has not already been tested.`, kind: 'tip' },
  ],
};
