/**
 * Grade 8 World Geography — Unit 6 CED 6.4: Food Systems & Food Security.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.food-systems-and-food-security.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U6_FOOD_SYSTEMS_AND_FOOD_SECURITY: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.food-systems-and-food-security.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 6,
  cedTopic: '6.4',
  cedTitle: 'Food Systems & Food Security',
  planId: 'evelyn.ms.m8geo.food-systems-and-food-security.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.food-systems-and-food-security.v1' }],
  theory: [
    { loId: 'm8geo.food-systems-and-food-security', content: `COMPARE TWO FARMING SYSTEMS MEASURE BY MEASURE, AND EXPECT THE VERDICT TO SPLIT. A farming system is described by several figures at once: the food that comes off each hectare, the water each ton of food took, the hectares one worker covers, and what the purchased inputs cost for each hectare. Every one of them is divided by the thing that produced it, because a larger operation wins every total simply by being larger, and a total is not a comparison. Run all four and the usual result is a SPLIT: one system leads on some measures and the other leads on the rest. A split is not a failure to decide. It IS the finding, and it turns the question from "which system is better" into the only question that has an answer -- better at what, for a place that needs what? Neither system in this lesson is the advanced one and neither is behind; they are two arrangements with different figures.` },
    { loId: 'm8geo.food-systems-and-food-security', content: `EVERY MEASURE YOU LIKE IS PAID FOR SOMEWHERE THE MEASURE DOES NOT SHOW, AND YOU NAME THE COST WITH ITS MECHANISM AND ITS RATE. You already know that a change to the land gains one thing and gives up another, and that the gainer and the cost-bearer can be different people. What this row adds is the mechanism and a number. Irrigating a dry field raises the food off each hectare; the water carries dissolved salt, and the water leaves by evaporating and through the crop while the salt stays behind, so salt collects in the soil unless extra water is run through to flush it down past the roots. Fertilizer raises the food off each hectare; whatever the crop does not take up is carried off the field by rain and by irrigation water, into ditches and streams. Planting one crop across a wide area makes machinery, storage and selling cheap; it also puts the entire income on one crop's price. "Irrigation is bad" is not an analysis. "This plain salts thirty-six hectares a year, which is one and eight tenths of a percent of its irrigated land each year, in exchange for its yield" is one, because it can be measured, compared and acted on.` },
    { loId: 'm8geo.food-systems-and-food-security', content: `A REGION'S FOOD SECURITY IS NOT ONE NUMBER, AND A HARVEST TOTAL ONLY REACHES THE FIRST OF THREE MEASURES. AVAILABILITY asks whether enough food is physically there. ACCESS asks whether the people there can actually obtain it -- the price of a month of food against what a household has to spend, and whether roads and markets reach the places people live. STABILITY asks whether the first two hold through a bad year -- how far the supply swings, what is in store, and whether one crop, one road or one buyer carries everything. The three are read separately and they fail separately, which is the whole reason to read them separately: the measure that fails is the one that names the problem, and a region can pass two and fail the third. These are measurements of a region's supply, its prices and its swings. They are never a judgment about a region or about the people in it.` },
    { loId: 'm8geo.food-systems-and-food-security', content: `AVAILABILITY IS A BALANCE YOU COMPUTE, NOT A HARVEST YOU READ. Start with what the farms produced, add what comes in from outside, subtract what is sold out of the region, and subtract what never reaches a person at all -- grain held back for seed, grain fed to animals, and grain lost in storage and on the way. Divide what is left by the number of people, and that figure, food for each person, is availability. It is the step that catches the front page out: a region that sells most of what it grows, or loses a large share of it before it arrives, ends up with an availability figure far below its harvest figure. Compute the balance before you believe the total, and check it by multiplying back -- the figure for each person times the number of people has to return the tons you started from.` },
    { loId: 'm8geo.food-systems-and-food-security', content: `ACCESS AND STABILITY ARE READ FROM DIFFERENT EVIDENCE, AND THE EVIDENCE IS NOT THE HARVEST. For access, compare a price against what there is to spend: if the month of grain a household buys went from one hundred dollars to one hundred and sixty while the money coming in did not move, food went from forty percent of that month to sixty-four percent, and the barrier is the price and not the supply. For stability, read the series and the plumbing: a harvest of two hundred, then one hundred and thirty, then two hundred and ten thousand tons is a supply that swings by most of a half, and one road into a town, one crop in the ground or two weeks of grain in store all say the same thing -- the good year does not carry the bad one. And a regional figure covers many kinds of farm and many kinds of household inside that region, so a region that passes on the regional numbers can still hold towns where the price moved and the money did not.` },
    { loId: 'm8geo.food-systems-and-food-security', kind: 'definition', title: 'food security', content: `a region's food situation judged on separate measures rather than on one total -- in this lesson, whether enough food is there, whether people can obtain it, and whether both hold through a bad year.` },
    { loId: 'm8geo.food-systems-and-food-security', kind: 'definition', title: 'availability', content: `the food physically present for each person, computed as production plus what comes in, minus what is sold out and minus what never reaches people, divided by the population.` },
    { loId: 'm8geo.food-systems-and-food-security', kind: 'definition', title: 'access', content: `whether the people in a place can actually obtain the food that is there, read from the price of food against what a household has to spend and from whether markets and roads reach them.` },
    { loId: 'm8geo.food-systems-and-food-security', kind: 'definition', title: 'stability', content: `whether availability and access hold from one year to the next, read from how far the supply swings and from what carries a place through a bad year.` },
    { loId: 'm8geo.food-systems-and-food-security', kind: 'definition', title: 'yield for each hectare', content: `the food harvested from each hectare of land, found by dividing the harvest by the hectares it came off; this lesson also says it as the food off each hectare.` },
    { loId: 'm8geo.food-systems-and-food-security', kind: 'definition', title: 'purchased input', content: `something bought and brought onto a farm to raise what it produces -- fertilizer, fuel, seed, irrigation water, machinery time -- counted for each hectare so that operations of different size can be set side by side.` },
  ],
  methods: [
    {
      title: 'Worked compare two systems',
      steps: [
        `Refuse the totals first, because the totals are what the eye reaches for. Corran Plain harvested 9,000 tons against 1,200, which is seven and a half times as much food -- and it planted 2,000 hectares against 400, which is five times as much land. WRONG: "Corran Plain produces seven and a half times as much, so it is the stronger system." CORRECT: "Corran Plain is five times the size, so of course it harvests more; the comparison has to be per unit of what produced it."`,
        `Food for each hectare. Marn Side: 1,200 tons divided by 400 hectares is 3 tons for each hectare. Corran Plain: 9,000 divided by 2,000 is 4.5 tons for each hectare. Corran Plain leads, and by half again rather than by seven and a half times.`,
        `Water for each ton of food. Marn Side: 2,400 divided by 1,200 is 2 thousand cubic meters for each ton. Corran Plain: 27,000 divided by 9,000 is 3 thousand cubic meters for each ton. Marn Side leads on this one: it takes two thirds as much water to put a ton of food on the truck.`,
        `Land one worker covers, and what the inputs cost. Marn Side: 400 hectares divided by 80 people is 5 hectares for each worker. Corran Plain: 2,000 divided by 40 is 50 hectares for each worker, ten times as much land for each pair of hands. Inputs are given already divided: $200 for each hectare on Marn Side against $500 on Corran Plain.`,
        `Invert everything before going on, because a slipped zero here would carry through the rest. 3 times 400 is 1,200 and 4.5 times 2,000 is 9,000, so both harvests come back. 2 times 1,200 is 2,400 and 3 times 9,000 is 27,000, so both water figures come back. 5 times 80 is 400 and 50 times 40 is 2,000, so both areas come back. Nothing slipped.`,
        `Now state the split, which is the finding. Corran Plain leads on food for each hectare (4.5 against 3) and on land for each worker (50 against 5). Marn Side leads on water for each ton (2 against 3) and on purchased inputs for each hectare ($200 against $500). Two measures each. There is no overall winner in these four columns, and looking for one is the mistake -- a place short of water and a place short of land would choose differently on exactly this data, and neither would be choosing the better system.`,
        `Put a number on the trade-off the yield is bought with. Corran Plain irrigates, and irrigation water carries dissolved salt that stays in the soil when the water evaporates or leaves through the crop. The survey figures: 300 hectares salted now against 120 five years ago is a rise of 180 hectares, and 180 divided by 5 is 36 hectares a year. As a share of the 2,000 hectares it irrigates, 36 divided by 2,000 is 0.018, which is 1.8 percent of the irrigated land each year. Check it: 36 times 5 is 180, and 120 plus 180 is 300. That is what a measured trade-off looks like -- 4.5 tons for each hectare now, and 1.8 percent of the ground going salty each year, which is a cost that is real, dated and comparable rather than an opinion about irrigation.`,
        `Rewind the data and read it backwards to be sure nothing was misread: 300 and 120 salted, $500 inputs, 40 workers, 27,000 water, 9,000 tons, 2,000 hectares for Corran Plain; $200, 80 workers, 2,400 water, 1,200 tons, 400 hectares for Marn Side. Then change ONE input. A dry year cuts Corran Plain's harvest to 6,000 tons off the same 2,000 hectares, with the same 27,000 thousand cubic meters pumped. Food for each hectare: 6,000 divided by 2,000 is 3 tons, exactly level with Marn Side. Water for each ton: 27,000 divided by 6,000 is 4.5 thousand cubic meters, more than twice Marn Side's 2. Check: 3 times 2,000 is 6,000, and 4.5 times 6,000 is 27,000. One bad year erased the whole yield lead and doubled the water cost of every ton, which is the first thing you will meet again when a region is judged on stability.`,
      ],
      example: { problem: `Two farming districts send their figures to the same regional office. Compare the systems on every measure, state the split, put a number on one trade-off, then work out what a dry year does to the comparison.

"Marn Side: small mixed farms selling into the towns nearby. 400 hectares planted. 1,200 tons harvested. 2,400 thousand cubic meters of irrigation water used. 80 people work the land. Purchased inputs cost $200 for each hectare.

Corran Plain: large farms growing one crop for buyers far away. 2,000 hectares planted. 9,000 tons harvested. 27,000 thousand cubic meters of irrigation water used. 40 people work the land. Purchased inputs cost $500 for each hectare. A soil survey five years ago found salt built up in the top layer of 120 of those hectares; this year's survey finds 300."`, solution: `Per unit, the verdict splits two and two. Corran Plain leads on food for each hectare, 4.5 tons (9,000 divided by 2,000) against 3 tons (1,200 divided by 400), and on land for each worker, 50 hectares (2,000 divided by 40) against 5 (400 divided by 80). Marn Side leads on water for each ton, 2 thousand cubic meters (2,400 divided by 1,200) against 3 (27,000 divided by 9,000), and on purchased inputs, $200 for each hectare against $500. The yield lead is bought with a measurable cost: Corran Plain's salted area went from 120 hectares to 300 in five years, which is 36 hectares a year, or 1.8 percent of its irrigated land each year. In a dry year that cuts the harvest to 6,000 tons, the yield lead disappears entirely (3 tons for each hectare in both districts) and the water cost rises to 4.5 thousand cubic meters for each ton.` },
      relatedLoIds: ['m8geo.food-systems-and-food-security'],
    },
    {
      title: 'Worked evaluate food security',
      steps: [
        `Availability first, and compute the balance rather than reading the harvest. Start with production, 200,000 tons. Add what comes in: 200,000 plus 20,000 is 220,000. Subtract what is sold out: 220,000 minus 90,000 is 130,000. Subtract what never reaches a person: 130,000 minus 10,000 is 120,000 tons left for people.`,
        `Turn that into a figure for each person. 120,000 tons divided by 400,000 people is 0.3 tons each, and 0.3 tons is 300 kilograms. The standard is 200 kilograms. Availability PASSES, and with half again to spare. Invert to be sure: 300 kilograms times 400,000 people is 120,000,000 kilograms, which is 120,000 tons, and 120,000 plus 10,000 plus 90,000 minus 20,000 is 200,000 tons of production. The balance closes in both directions.`,
        `Access second, and the evidence here is a price against what there is to spend, not a tonnage. The month of grain went from $100 to $160, a rise of $60 on $100, which is 60 percent. What the household has to spend stayed at $250. So food went from 100 divided by 250, which is 0.4 or 40 percent of the month, to 160 divided by 250, which is 0.64 or 64 percent. Check: 40 percent of 250 is 100 and 64 percent of 250 is 160, so both shares recover their dollar figures. Access is FAILING in those towns, and nothing in the availability figure said so.`,
        `Stability third, read from the series and from the plumbing. The five harvests are 200, 130, 210, 205 and 120 thousand tons. The highest is 210 and the lowest is 120, and 120 divided by 210 is about four sevenths, so a bad year delivers a little over half of a good one. Against that swing the region holds two months of store, and the eastern towns are reached by one road that closes for about three weeks each spring. Stability is the measure that comes out weak: the store and the road are not sized for the gap the series shows.`,
        `Now the check, and it needs three clues of different kinds pointing the same way, because one figure is a hunch. The question on the table is whether a program to raise harvests is what this region needs. Clue one is a computed balance: 300 kilograms for each person against a 200 kilogram standard, so the food is already there in quantity, and more of it does not change that. Clue two is a price against a budget: 64 percent of the month rather than 40 percent, with the money unchanged, so the barrier in the eastern towns is what a household can pay. Clue three is a series plus two pieces of plumbing: harvests that swing from 210 down to 120, two months of store and a single road that closes each spring, so grain harvested in a good year does not reach the towns in the bad one. A balance, a price and a series are three different kinds of evidence, and all three say the same thing about the same proposal. One number is a hunch; three of different kinds, all pointing the same way, is evidence.`,
        `State the verdict, and keep it a measurement. Orvale passes on availability and fails on access, with stability weak enough to make the access failure worse. Raising the harvest adds to the measure that already passes. The measure that fails is the one that names the fix -- the price against what households have, and what stands between a good harvest and a bad spring. And say what this verdict is not: it is a reading of Orvale's supply, prices and swings in one year, not a judgment about Orvale or about anybody living there.`,
      ],
      example: { problem: `A regional council is about to fund a program to raise harvests. Evaluate the region's food security on all three measures first, and say whether a bigger harvest is the thing this region needs.

"Orvale: 400,000 people. The farms harvest 200,000 tons of grain a year. 20,000 tons come in from outside. 90,000 tons are sold out of the region. 10,000 tons are held back for seed and animal feed or lost in storage and on the road. The council's planning standard is 200 kilograms of grain for each person each year.

In Orvale's eastern towns, the grain a household buys in a month cost $100 a year ago and costs $160 now, and what those households have to spend each month has not moved from $250.

The last five harvests, in thousands of tons: 200, 130, 210, 205, 120. The eastern towns are served by one road, which is closed for about three weeks each spring. The regional store holds two months of what the region eats."`, solution: `Availability passes: 200,000 plus 20,000 minus 90,000 minus 10,000 leaves 120,000 tons, and 120,000 divided by 400,000 people is 0.3 tons, or 300 kilograms each, against a 200 kilogram standard. Access fails in the eastern towns: the month of grain rose from $100 to $160, a rise of 60 percent, while the money stayed at $250, so food went from 40 percent of the month to 64 percent. Stability is weak: harvests of 200, 130, 210, 205 and 120 thousand tons swing from 210 down to 120, and against that the region holds two months of store and the eastern towns have one road that closes about three weeks each spring. A program to raise harvests adds to the measure that already passes, so it is not what this region needs; the failing measure, access, names the fix.` },
      relatedLoIds: ['m8geo.food-systems-and-food-security'],
    },
  ],
  pointers: [
    { content: `Students often say "Orvale grows plenty of grain for the number of people in it, so the region is food secure." — Two separate steps are missing. First, the harvest is not availability: 200,000 tons produced plus 20,000 coming in, minus 90,000 sold out and 10,000 that never reaches a person, leaves 120,000 tons, and 120,000 divided by 400,000 people is 0.3 tons, or 300 kilograms each. That does pass the 200 kilogram standard, and the check confirms it -- 300 kilograms times 400,000 people is 120,000 tons. Second, passing availability settles one measure of three. Access in Orvale's eastern towns is failing: the month of grain went from $100 to $160 while the money stayed at $250, which is 64 percent of the month rather than 40 percent. Stability is weak: harvests of 200, 130, 210, 205 and 120 thousand tons, two months of store and one road that closes each spring. WRONG: "Plenty of grain is grown, so the region is food secure." CORRECT: "Availability computes to 300 kilograms each and passes; access fails on price and stability is weak, so the region is not secure and the failing measure names the fix." A production total can never answer a question about price or about a bad year, because it does not contain a price or a second year.`, kind: 'common-error' },
    { content: `Students often say "Corran Plain gets more food off each hectare, so it is the better farming system." — Four measures were computed and they split two and two. Corran Plain leads on food for each hectare, 4.5 against 3, and on land for each worker, 50 hectares against 5. Marn Side leads on water for each ton, 2 thousand cubic meters against 3, and on purchased inputs, $200 for each hectare against $500. On top of that the yield lead carries a dated cost -- Corran Plain's salted area went from 120 hectares to 300 in five years, which is 36 hectares a year, or 1.8 percent of its irrigated land each year -- and in a dry year that cuts its harvest to 6,000 tons the lead vanishes completely, since 6,000 divided by 2,000 is 3 tons for each hectare, level with Marn Side. WRONG: "Higher yield for each hectare, so the better system." CORRECT: "Higher yield for each hectare, lower on water for each ton and on input cost, ten times the land for each worker, 1.8 percent of the ground salting each year, and level on yield in a dry year -- so the answer depends on what the place is short of." Better at what, for a place that needs what, is the only form of the question that has an answer.`, kind: 'common-error' },
    { content: `Compare farming systems per unit, never by the total: food for each hectare, water for each ton, hectares for each worker, purchased inputs for each hectare. A larger operation wins every total simply by being larger.`, kind: 'tip' },
    { content: `Expect the verdict to split. When one system leads on two measures and the other leads on two, the split is the finding, and the question becomes better at what, for a place short of what.`, kind: 'tip' },
    { content: `State a trade-off with its mechanism and its rate. Irrigation water leaves the salt behind when it evaporates or passes through the crop; fertilizer the crop does not take up washes off the field; one crop across a wide area puts the whole income on one price.`, kind: 'tip' },
    { content: `A measured cost beats an opinion: 120 hectares salted five years ago and 300 now is 36 hectares a year, which is 1.8 percent of 2,000 irrigated hectares each year.`, kind: 'tip' },
    { content: `Food security is read on three separate measures. Availability is whether the food is there, access is whether people can obtain it, stability is whether both hold through a bad year, and a harvest total only ever reaches the first.`, kind: 'tip' },
    { content: `Availability is a balance: production, plus what comes in, minus what is sold out, minus what never reaches a person, divided by the number of people. Multiply the figure for each person back by the population to check it.`, kind: 'tip' },
    { content: `The measure that fails is the one that names the fix, and a bigger harvest does not fix a price. These are measurements of a region's supply, prices and swings, never a judgment about a region or the people in it.`, kind: 'tip' },
    { content: `Never compare farming systems by totals. Always divide by what produced it: food per hectare, water per ton, hectares per worker, dollars per hectare. A bigger farm wins every total just by existing.`, kind: 'common-error' },
    { content: `A split verdict (one system leads on two measures, the other on two) is NOT a tie — it's the answer. It means 'better at what, for a place that needs what?' Always ask that second question.`, kind: 'gotcha' },
    { content: `Harvest and availability are not the same number. Availability = production + imports − exports − waste, then divided by population. A region can harvest plenty and have low availability if it sells most of it out.`, kind: 'vocab-note' },
    { content: `Food security has three separate measures: availability (is it there), access (can people afford it), stability (does it hold year to year). A region can pass one and fail another. Test each one separately.`, kind: 'vocab-note' },
    { content: `State a trade-off with a mechanism and a number, not an opinion. Bad: 'Irrigation harms the soil.' Good: 'Salt built up in 120 hectares five years ago, 300 now — that's 36 hectares per year, or 1.8% of irrigated land annually.'`, kind: 'tip' },
    { content: `Access fails on price or roads, not on total food supply. If grain cost rises 60% while household income doesn't move, access fails even if availability is high. Check price against budget, not tonnage.`, kind: 'edge-case' },
    { content: `Stability is weak when harvests swing wide, storage is short, or one road/crop/buyer carries everything. Read the series and the plumbing separately, then together. A good year alone does not carry a bad one.`, kind: 'common-error' },
    { content: `Always check your work by multiplying back: food per person × population should equal the tons available. If it doesn't match, a zero slipped or a subtraction reversed.`, kind: 'tip' },
  ],
};
