/**
 * Grade 8 World Geography — Unit 1 CED 1.2: Evaluating a Choropleth Map.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.evaluating-a-choropleth.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U1_EVALUATING_A_CHOROPLETH: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.evaluating-a-choropleth.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 1,
  cedTopic: '1.2',
  cedTitle: 'Evaluating a Choropleth Map',
  planId: 'evelyn.ms.m8geo.evaluating-a-choropleth.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.evaluating-a-choropleth.v1' }],
  theory: [
    { loId: 'm8geo.evaluating-a-choropleth', content: `A CHOROPLETH SHOWS CLASSES, NOT VALUES, SO WRITE DOWN THE BREAKS BEFORE YOU READ ANY PATTERN. A choropleth shades each whole area one tone according to which band of values that area falls into, and a map key states what each shade stands for. That means the shading carries exactly one fact about an area: which band its value landed in. It does not carry the value. Two areas shaded alike are somewhere inside the same band and can sit at opposite ends of it; two areas shaded differently are in different bands and can sit a hair apart across the line between them. The pattern you are about to read off the tones was produced by two things together -- the numbers, and the places somebody decided to cut them -- so both go on your paper before you say a single word about the pattern.` },
    { loId: 'm8geo.evaluating-a-choropleth', content: `PLACE EVERY VALUE IN ITS CLASS, THEN COUNT THE AREAS BACK. A class is stated as a lower bound and an upper bound: "40 up to but not including 60". A value belongs to the class whose lower bound it reaches and whose upper bound it does not reach, so 59 is in that class and 60 is in the next one up. Work through every area, one at a time, and write the class beside its value. Then invert: add up how many areas you put in each class and check that the total is the number of areas on the map. If the total comes out one too high, a value sitting exactly on a break got placed twice; one too low, and an area was skipped.` },
    { loId: 'm8geo.evaluating-a-choropleth', content: `SUBTRACT TWICE: THE RANGE INSIDE A CLASS, AND THE GAP ACROSS THE BREAK BESIDE IT. The within-class range is the highest value in a class minus the lowest value in that class, and it is precisely the part of the data the map does not show, because everything inside it is drawn identically. The gap across a break is the lowest value above the break minus the highest value below it, and it is the difference the map draws as a visible edge. Do both subtractions. When the gap across the break comes out SMALLER than the range inside the class next to it, the map is showing you an edge that is smaller than a difference it is hiding, and any conclusion about a sharp divide there is a conclusion about the break, not about the places.` },
    { loId: 'm8geo.evaluating-a-choropleth', content: `RE-DRAW ONE BREAK, RE-PLACE EVERY VALUE, AND SEE WHAT MOVES. The way to find out whether a grouping is in the data or in the classing is to change one break value and run step two again on the same untouched numbers. If a pair that shared a tone now splits, and a pair that was split now shares, the grouping belonged to the breaks. This does not make the first map a lie -- both maps place every value correctly, and a mapmaker has to cut the numbers somewhere. What it makes false is a conclusion that treats one set of breaks as the only way the data could have been cut.` },
    { loId: 'm8geo.evaluating-a-choropleth', content: `A COUNT MAP AND A RATE MAP OF THE SAME PLACES ARE DIFFERENT MAPS, AND THE BIG AREA IS DARK ON THE FIRST ONE ALMOST AUTOMATICALLY. A rate is a count divided by a stated denominator, so shading the count answers "how many are here" while shading the rate answers "how many for each resident". Those two maps can put one area in the darkest class and near the lightest class, because the area with the most of something very often has the most of it for the plain reason that it is the biggest. So the first step of the routine has a second half: find the sentence that says what quantity is being shaded, and hold on to it, because every conclusion drawn from the map has to be a conclusion about THAT quantity.` },
    { loId: 'm8geo.evaluating-a-choropleth', content: `JUDGE A CONCLUSION BY SORTING WHAT THE MAP IS RELIABLE ABOUT FROM WHAT IT IS NOT. A choropleth is exactly reliable about class membership: an area drawn in a class really does have a value inside that class, and one drawn outside it really does not. It is not reliable about distance, because every value inside a class is drawn the same. So a conclusion shaped like "this area is at least 50" survives, while a conclusion shaped like "these two are about the same" or "there is a sharp divide along this line" has to be checked against the printed values and the break values before you accept it. Say which of the two shapes the conclusion has, then check it.` },
    { loId: 'm8geo.evaluating-a-choropleth', kind: 'definition', title: 'choropleth', content: `a map that sorts every area into a class by its value and shades the whole area with that class's tone, so what the map displays is the class and not the value.` },
    { loId: 'm8geo.evaluating-a-choropleth', kind: 'definition', title: 'class', content: `a band of values grouped together and drawn alike, stated as a lower bound the value must reach and an upper bound it must not reach.` },
    { loId: 'm8geo.evaluating-a-choropleth', kind: 'definition', title: 'class break', content: `the value where one class ends and the next begins, chosen by the mapmaker before any shading and never fixed by the data.` },
    { loId: 'm8geo.evaluating-a-choropleth', kind: 'definition', title: 'classing', content: `the whole set of choices about how many classes to use and where to cut between them, made once and applied to every area on the map.` },
    { loId: 'm8geo.evaluating-a-choropleth', kind: 'definition', title: 'within-class range', content: `the highest value inside one class minus the lowest value inside it: the difference the map draws as no difference at all.` },
  ],
  methods: [
    {
      title: 'Worked run the routine and move a break',
      steps: [
        `Step one: write down the breaks and the shaded quantity. The breaks are at 40, 60 and 80, and the quantity is a percent of each district's own land, so no district is dark merely for being large. Both halves of step one are now on paper.`,
        `Step two: place every value. Doverly at 38 is under 40, so it is in the lightest class. Eastmere at 59 reaches 40 and does not reach 60, so it is in the second class. Fenhollow at 61 and Grasholt at 78 both reach 60 and neither reaches 80, so both are in the third class. Haldane at 88 reaches 80, so it is in the darkest class.`,
        `Invert the placement by counting back. One district in the lightest class, one in the second, two in the third, one in the darkest: 1 plus 1 plus 2 plus 1 is 5, and Anselm has five districts. Nothing was placed twice and nothing was skipped.`,
        `Step three: subtract twice. The within-class range of the third class is 78 minus 61, which is 17 points, and the map draws those two districts identically. The gap across the break at 60 is 61 minus 59, which is 2 points, and the map draws that as an edge between two different tones. So the difference the map shows is 2 and the difference the map hides is 17.`,
        `Now test the first half of the report. WRONG: "Fenhollow and Grasholt carry the same tone, so they are close in farmland." CORRECT: "Fenhollow is at 61 percent and Grasholt is at 78 percent, which is 17 points apart -- they share a class because the class is 20 points wide, not because their farmland is alike."`,
        `Test the second half. WRONG: "Eastmere is in a lighter class than Fenhollow, so Eastmere is well behind it." CORRECT: "Eastmere is at 59 percent and Fenhollow is at 61 percent, 2 points apart -- they are drawn in different tones because the break at 60 happened to fall between them." The report is not supported on either half, and the two halves fail in opposite directions.`,
        `Step four: re-draw ONE break and re-place every value, so the pattern is not memorized as a fact about these districts. Move the break at 60 up to 65 and change nothing else. Doverly at 38 is still under 40. Eastmere at 59 and Fenhollow at 61 now both reach 40 and neither reaches 65, so they share the second class. Grasholt at 78 reaches 65 and does not reach 80, so it stands alone in the third. Haldane at 88 is still in the darkest. Count back: 1 plus 2 plus 1 plus 1 is 5 districts again.`,
        `Rewind the input and read the five values backwards against the new classes to be sure nothing was misread: 88 is 80 or more; 78 reaches 65 and not 80; 61 reaches 40 and not 65; 59 reaches 40 and not 65; 38 is under 40. On the new map Eastmere and Fenhollow share a tone and Fenhollow and Grasholt do not -- the exact reverse of the first map, from five numbers that never moved. Step five: the conclusion the report drew was a conclusion about where the break sat.`,
      ],
      example: { problem: `Run the routine straight through on a described map, then move one break.

A choropleth of the invented country of Anselm shades each of its five districts by the percent of that district's land that is farmland. The key lists four classes: under 40 percent; 40 up to but not including 60 percent; 60 up to but not including 80 percent; and 80 percent or more, which is the darkest tone.

"Doverly: 38 percent. Eastmere: 59 percent. Fenhollow: 61 percent. Grasholt: 78 percent. Haldane: 88 percent."

A farming report says: "The map shows that Fenhollow and Grasholt are close to each other in farmland, and that Eastmere is well behind Fenhollow." Test the report.`, solution: `The report is not supported, on both halves. Fenhollow at 61 percent and Grasholt at 78 percent share the third class but are 17 points apart, which is the within-class range the map hides; Eastmere at 59 percent and Fenhollow at 61 percent are in different classes but only 2 points apart, which is the break at 60 falling between them. Placing the five values gives 1, 1, 2 and 1 districts across the four classes, which counts back to 5. Moving the single break at 60 up to 65 puts Eastmere and Fenhollow in one class and leaves Grasholt alone, reversing both groupings without changing one number.` },
      relatedLoIds: ['m8geo.evaluating-a-choropleth'],
    },
    {
      title: 'Worked count map against rate map',
      steps: [
        `Step one on the first map: the breaks are at 10 and 50, and the shaded quantity is a count of clinics. Place the values. Caldren at 9 is under 10. Dunreath at 12 and Brinmoor at 24 both reach 10 and neither reaches 50. Ashgate at 60 reaches 50, so Ashgate alone is in the darkest class. Count back: 1 plus 2 plus 1 is 4 districts.`,
        `Step one on the second map: the breaks are at 2 and 5, and the shaded quantity is clinics for every 10,000 residents. Work out each rate, since the denominator is stated. Ashgate: 300,000 residents contains 30 lots of 10,000, and 60 divided by 30 is 2 clinics per 10,000. Brinmoor: 60,000 contains 6 lots of 10,000, and 24 divided by 6 is 4. Caldren: 90,000 contains 9 lots, and 9 divided by 9 is 1. Dunreath: 20,000 contains 2 lots, and 12 divided by 2 is 6.`,
        `Invert every division before placing anything. 2 times 30 is 60, which returns Ashgate's clinics. 4 times 6 is 24, which returns Brinmoor's. 1 times 9 is 9, Caldren's. 6 times 2 is 12, Dunreath's. All four counts come back, so no zero slipped.`,
        `Step two on the second map. Caldren at 1 is under 2. Ashgate at 2 and Brinmoor at 4 both reach 2 and neither reaches 5. Dunreath at 6 reaches 5, so Dunreath alone is in the darkest class. Count back: 1 plus 2 plus 1 is 4 districts again.`,
        `Step three, and here it is a swap rather than a subtraction. Ashgate goes from the darkest class on the count map to the middle class on the rate map. Dunreath goes from the middle class to the darkest. Caldren stays lightest and Brinmoor stays in the middle. Two of four districts changed class, and not one measurement changed with them.`,
        `Step five: judge the conclusion. WRONG: "Ashgate holds 60 clinics, more than any other district, so Ashgate is the best served." CORRECT: "Ashgate holds the most clinics and also holds the most residents to share them: 2 clinics for every 10,000 people, against 6 in Dunreath and 4 in Brinmoor. On clinics for each resident Ashgate is third of the four." The conclusion is not supported. It was read off a map that shades how many clinics a district holds, and it is a claim about how well residents are served.`,
        `Rewind the input, then change ONE thing. Read the four lines backwards to confirm them: 12 and 20,000; 9 and 90,000; 24 and 60,000; 60 and 300,000. Now suppose Ashgate had 100,000 residents instead of 300,000, with the same 60 clinics. 100,000 contains 10 lots of 10,000, and 60 divided by 10 is 6 clinics per 10,000; check, 6 times 10 is 60. Ashgate now reaches 5 and joins Dunreath in the darkest class of the rate map -- while the count map does not move at all, because Ashgate still has exactly 60 clinics. One input changed, one map changed, the other stood still. That is the sharpest way to see that the two maps are answering two different questions.`,
      ],
      example: { problem: `The same four places, shaded two ways. Decide whether the conclusion survives.

The invented country of Torvin has four districts. "Ashgate: 60 public health clinics, 300,000 residents. Brinmoor: 24 clinics, 60,000 residents. Caldren: 9 clinics, 90,000 residents. Dunreath: 12 clinics, 20,000 residents."

The first map shades each district by its NUMBER of clinics, in three classes: under 10; 10 up to but not including 50; and 50 or more, the darkest. The second map shades the same districts by CLINICS PER 10,000 RESIDENTS, in three classes: under 2; 2 up to but not including 5; and 5 or more, the darkest.

A health board writes: "Ashgate is the darkest district on the map, so Ashgate is the best-served district in Torvin for clinics." Test it.`, solution: `The conclusion is not supported. The first map shades a count, and Ashgate is darkest on it because it holds 60 clinics. On clinics per 10,000 residents the figures are Ashgate 2 (60 divided by 30 lots of 10,000), Brinmoor 4 (24 divided by 6), Caldren 1 (9 divided by 9) and Dunreath 6 (12 divided by 2), each of which multiplies back to its count. On the rate map Dunreath alone is darkest and Ashgate falls to the middle class, so two of the four districts swap classes between the two maps. Changing only Ashgate's residents to 100,000 lifts its rate to 6 and moves it into the darkest class of the rate map while leaving the count map untouched.` },
      relatedLoIds: ['m8geo.evaluating-a-choropleth'],
    },
  ],
  pointers: [
    { content: `Students often say "Sennet and Tressick carry the same tone, so their figures are nearly the same." — Do the two subtractions. Inside the middle class, Tressick is at 74 percent and Sennet is at 52 percent: 74 minus 52 is 22 points, and the map draws that as no difference at all. Across the break at 50, Sennet is at 52 and Umber is at 49: 52 minus 49 is 3 points, and the map draws that as a visible edge. Place all four values back to check the classing: 49 is under 50; 52 and 74 both reach 50 and neither reaches 75; 81 reaches 75. One plus two plus one is 4, which is every district in Quarl. WRONG: "Same tone, so nearly the same." CORRECT: "Same class, 22 points apart, while the pair the map separates is 3 points apart." A shared tone tells you the band; only the printed values tell you the distance.`, kind: 'common-error' },
    { content: `Students often say "The mapmaker could have cut the classes anywhere, so a choropleth cannot be trusted for anything." — A choropleth is exactly reliable about class membership and unreliable about distance, and the repair is to keep conclusions in the shape it can support. Tressick's tone supports "Tressick is at least 50 percent paved and under 75 percent", and 74 is inside that band, so that conclusion is true. It does not support "Tressick is close to Sennet". Test it by moving one break: cut the lowest class at 53 instead of 50 and Sennet at 52 joins Umber in the lightest class while Tressick stands alone in the middle. Count back: two plus one plus one is 4 districts. The membership claim about Tressick changes to "at least 53 and under 75" and is still true of the data, while the closeness claim was never supported by either map. WRONG: "The breaks were chosen, so the map is worthless." CORRECT: "The breaks were chosen, so read class membership off the map and read distance off the values."`, kind: 'common-error' },
    { content: `A choropleth displays the class, not the value. Write down the break values and the value of every area before you say anything about the pattern.`, kind: 'tip' },
    { content: `Step one has two halves: the breaks, and what quantity is being shaded. A count map and a rate map of the same places are two different maps.`, kind: 'tip' },
    { content: `Place each value in the class whose lower bound it reaches and whose upper bound it does not reach, then count the class members back to the number of areas on the map.`, kind: 'tip' },
    { content: `Subtract twice. The within-class range is what the map hides; the gap across the break is what the map shows. When the gap is smaller than the range, the visible divide belongs to the break.`, kind: 'tip' },
    { content: `Re-draw one break and re-place every value. Pairs that split and pairs that join tell you the grouping was in the classing, not in the data.`, kind: 'tip' },
    { content: `Shading a count puts the biggest area in the darkest class almost by itself, because the place with the most of something is very often simply the largest place.`, kind: 'tip' },
    { content: `Class membership is what a choropleth is reliable about. Distance between two values is not. Judge every conclusion by which of those two shapes it has.`, kind: 'tip' },
    { content: `Don't confuse the class with the value. A shared tone means "same band", not "same number". Always subtract: highest in class minus lowest in class. That gap is what the map hides.`, kind: 'common-error' },
    { content: `On a class like "40 up to but not including 60": 40 belongs in it, 60 does not. Value 60 jumps to the next class. Check every placement: if your region count doesn't match the map's region count, a boundary value got placed twice.`, kind: 'vocab-note' },
    { content: `Before you read any pattern off the map, write down (1) the break values and (2) the quantity being shaded. If it says "number of clinics", it's a count map. If it says "clinics per 10,000 people", it's a rate map. They are two different maps.`, kind: 'tip' },
    { content: `A visible edge on the map (two different shades side by side) does not mean a big divide in the data. Subtract: the value just above the break minus the value just below it. If that gap is smaller than the within-class range hiding next to it, the edge is about the break, not about the places.`, kind: 'gotcha' },
    { content: `To test whether a grouping is real or just in the classing: move ONE break value, re-place all the values, and count again. If pairs that shared a tone now split, the grouping lived in the breaks, not the data.`, kind: 'edge-case' },
    { content: `A count map almost always puts the biggest area in the darkest class—not because it's special, just because it's largest. Switch to a rate map (divide by population or size) and that same area often becomes middle or light. Read the label first.`, kind: 'common-error' },
    { content: `A choropleth is reliable about class membership: "This region is in the 40–60 class, so its value is between 40 and 60." It is not reliable about distance: "These two regions are in the same class, so they're close." Judge every conclusion by which type it is, then check the printed numbers.`, kind: 'vocab-note' },
  ],
};
