/**
 * Grade 8 World Geography — Unit 1 CED 1.3: Scale of Analysis & Hidden Patterns.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.scale-of-analysis-and-hidden-patterns.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U1_SCALE_OF_ANALYSIS_AND_HIDDEN_PATTERNS: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.scale-of-analysis-and-hidden-patterns.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 1,
  cedTopic: '1.3',
  cedTitle: 'Scale of Analysis & Hidden Patterns',
  planId: 'evelyn.ms.m8geo.scale-of-analysis-and-hidden-patterns.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.scale-of-analysis-and-hidden-patterns.v1' }],
  theory: [
    { loId: 'm8geo.scale-of-analysis-and-hidden-patterns', content: `NAME THE UNIT BEFORE YOU READ THE FIGURE. One set of records -- how many households there are, and how many of them have the thing being measured -- can be totaled over a street, a district, a region or a whole country, and each size of unit produces a different figure from the very same records. A figure for a whole place is an average, and that is the premise this lesson starts from rather than the point of it: every one of those figures is correct, and none of them is a mistake. The work begins one step later. Say out loud which unit the number was computed over, because a figure with no unit named is not yet information, and then ask what a unit that size is able to say.` },
    { loId: 'm8geo.scale-of-analysis-and-hidden-patterns', content: `TO GO FROM SMALL UNITS UP TO A BIG ONE, ADD THE COUNTS AND DIVIDE ONCE. Never average the unit percentages, because that quietly gives a tiny district the same weight as a huge one. A district of 30,000 households at 10 percent and a district of 10,000 households at 50 percent give 3,000 plus 5,000, which is 8,000 out of 40,000 households, or 20 percent for the two together. Averaging 10 and 50 gives 30 percent, which is the figure for no place on the table. The bigger the unit, the harder it pulls, and adding the counts is what makes it pull the right amount. Check the aggregation by multiplying back: 20 percent of 40,000 is 8,000.` },
    { loId: 'm8geo.scale-of-analysis-and-hidden-patterns', content: `MATCH THE CLAIM TO THE SCALE, BECAUSE THAT IS WHERE CORRECT DATA GOES WRONG. A claim about the whole -- most households in the country are within walking distance of a stop -- is settled by the country figure and by nothing else. A claim about one household, one street or one district is settled only by the figure for the unit that household sits inside. The national figure never travels downward: it cannot tell you about a district, and a district figure never travels upward to stand for the country. So for each claim, name the unit the claim is about, then ask whether you have a figure computed over that unit. If you do not, the honest answer is that the data cannot settle it yet.` },
    { loId: 'm8geo.scale-of-analysis-and-hidden-patterns', content: `THE UNITS WERE DRAWN BY SOMEBODY, SO A PATTERN CAN BE MADE TO APPEAR OR DISAPPEAR WITHOUT ANY DATA CHANGING. Group the same small districts one way and a pattern stands out; group them another way and it is gone. Pair every high district with a low one and the difference averages itself away inside each new unit; keep the high districts together and the difference is the first thing anybody sees. Neither grouping is a lie, and no household moved. So report the grouping along with the figure, and when a pattern is going to be acted on, test whether it survives a different grouping of the same units.` },
    { loId: 'm8geo.scale-of-analysis-and-hidden-patterns', content: `REPORT THE SPREAD, NOT ONLY THE MIDDLE FIGURE. Beside any figure for a large unit, give the highest and the lowest of the units inside it and how many sit near each end. Two countries can both report 60 percent and be built completely differently: one where every district lands near 60, and one where a single large district at 90 percent carries four small districts sitting at 15. The middle figure is identical and the two countries need completely different plans, so a report that gives the middle figure alone has left out the part a planner uses.` },
    { loId: 'm8geo.scale-of-analysis-and-hidden-patterns', content: `THE DECISION PICKS THE SCALE. How much to buy, build or ship for a whole country is a question about a total, and the national figure answers it. Where the next library, clinic or bus route goes is a question about places, and only the finest unit you have can answer that. When somebody hands you a figure at one scale and a decision at another, the move is to say which unit the decision needs a figure for, and to ask for that figure rather than stretching the one you were given.` },
    { loId: 'm8geo.scale-of-analysis-and-hidden-patterns', kind: 'definition', title: 'scale of analysis', content: `the size of the unit a figure is computed over -- street, district, region or country -- chosen by whoever makes the figure, before anybody reads it.` },
    { loId: 'm8geo.scale-of-analysis-and-hidden-patterns', kind: 'definition', title: 'aggregate', content: `to combine the records of several smaller units into one figure for a larger unit, by adding the counts and then dividing once.` },
    { loId: 'm8geo.scale-of-analysis-and-hidden-patterns', kind: 'definition', title: 'weighted average', content: `an average in which each unit counts in proportion to its size, which is exactly what adding the counts and dividing once produces.` },
    { loId: 'm8geo.scale-of-analysis-and-hidden-patterns', kind: 'definition', title: 'grouping', content: `the choice of which smaller units are combined into each larger one, made by whoever draws the boundary rather than by the data.` },
    { loId: 'm8geo.scale-of-analysis-and-hidden-patterns', kind: 'definition', title: 'spread', content: `the distance between the highest and the lowest figure among the units inside a larger unit, reported beside that larger unit's figure.` },
  ],
  methods: [
    {
      title: 'Worked three scales one claim each',
      steps: [
        `Start at the finest unit, the district, because the coarser figures are built out of it. Harbor: 54,000 divided by 60,000 is 0.90, which is 90 percent. Kelm: 1,500 divided by 10,000 is 0.15, which is 15 percent, and Needle, Ostry and Pell are each 15 percent for the same reason. So the district figures are 90, 15, 15, 15 and 15.`,
        `Move up to the regional unit by adding the counts and dividing once. The Harbor region holds one district, so it stays at 90 percent. The Interior region: 1,500 plus 1,500 plus 1,500 plus 1,500 is 6,000 households served, out of 10,000 plus 10,000 plus 10,000 plus 10,000, which is 40,000 households. 6,000 divided by 40,000 is 0.15, which is 15 percent.`,
        `Move up to the national unit the same way. Served households: 54,000 plus 6,000 is 60,000. Total households: 60,000 plus 40,000 is 100,000. 60,000 divided by 100,000 is 0.60, which is 60 percent. WRONG: "Average the five district figures: 90 plus 15 plus 15 plus 15 plus 15 is 150, and 150 divided by 5 is 30 percent, so the national figure must be 30." CORRECT: "Add the counts and divide once: 60,000 served out of 100,000 households is 60 percent. The five districts are not the same size, so they cannot each count equally -- Harbor alone holds 60,000 of the 100,000 households."`,
        `Invert every figure to check it. 90 percent of 60,000 is 54,000. 15 percent of 10,000 is 1,500, and four of those is 6,000. 15 percent of 40,000 is 6,000. 60 percent of 100,000 is 60,000, and 54,000 plus 6,000 is 60,000. Every count comes back, so no zero slipped.`,
        `Now take the claims one at a time and name the unit each one is about. Claim A says "most households in Mersaine", which is a claim about the country, and the country figure is 60 percent. More than half of 100,000 households is more than 50,000, and 60,000 households are served, so claim A is SUPPORTED, at the national scale, and only there. Claim B says "a household in Ostry", which is a claim about one district, so it needs Ostry's own figure, which is 15 percent. Fifteen percent is not probable; 85 percent of households in Ostry are farther than 2 kilometers. Claim B is NOT SUPPORTED. Same records, same day, two claims, two scales, two different verdicts.`,
        `Three clues of different kinds say the national figure describes one district and no other. First, where the served households are: 54,000 of the 60,000 served households sit in Harbor, and 54,000 divided by 60,000 is 0.90, so 90 percent of everything the library network reaches is in one district. Second, how much weight that district carries: Harbor holds 60,000 of the 100,000 households, which is 60 percent of the country, so its own figure nearly sets the national one by itself. Third, the spread across the units: the district figures run from 90 percent down to 15 percent, a spread of 75 percentage points, and four of the five districts sit at the bottom of it. One number is a hunch; three of different kinds, all pointing the same way, is evidence.`,
        `Say the verdict in one line. The national figure of 60 percent is correct, it settles a national claim, and it describes exactly one of the five districts. A report that gives 60 percent and stops has told the truth and hidden the thing a planner needs: four districts at 15 percent.`,
      ],
      example: { problem: `Work one set of records at three sizes of unit, then decide which of two claims each scale can settle.

"Mersaine has five districts and two regions. The Harbor region is the single district of Harbor. The Interior region is the other four districts: Kelm, Needle, Ostry and Pell.

Harbor: 60,000 households, 54,000 of them within 2 kilometers of a public library.

Kelm, Needle, Ostry and Pell: 10,000 households each, 1,500 of them within 2 kilometers of a public library in each one."

Claim A, from a national newspaper: "Most households in Mersaine live within 2 kilometers of a library." Claim B, from the same article: "A household in Ostry is probably within 2 kilometers of a library."`, solution: `District figures: Harbor 90 percent (54,000 divided by 60,000), and Kelm, Needle, Ostry and Pell 15 percent each (1,500 divided by 10,000). Regional figures: Harbor region 90 percent, Interior region 15 percent (6,000 divided by 40,000). National figure: 60 percent (60,000 divided by 100,000), not the 30 percent that averaging the five district percentages would give. Claim A is supported at the national scale, because 60,000 of 100,000 households is more than half. Claim B is not supported, because Ostry is a district and its own figure is 15 percent.` },
      relatedLoIds: ['m8geo.scale-of-analysis-and-hidden-patterns'],
    },
    {
      title: 'Worked regrouping makes a pattern vanish',
      steps: [
        `District scale first. Northwest: 800 divided by 10,000 is 0.08, which is 8 percent. Northeast: 200 divided by 10,000 is 0.02, which is 2 percent. Southwest is 8 percent and Southeast is 2 percent, by the same division. The pattern at this scale is plain: the two western districts are at 8 percent and the two eastern districts are at 2 percent, which is four times as high in the west.`,
        `County scale next. 800 plus 200 plus 800 plus 200 is 2,000 homes with no piped water, out of 40,000 homes. 2,000 divided by 40,000 is 0.05, which is 5 percent. At the county scale there is one figure and no pattern at all, and 5 percent is the figure for neither an 8 nor a 2.`,
        `Regional scale, grouping one: the water boards. West: 800 plus 800 is 1,600 homes, out of 20,000 homes, and 1,600 divided by 20,000 is 0.08, which is 8 percent. East: 200 plus 200 is 400 homes out of 20,000, and 400 divided by 20,000 is 0.02, which is 2 percent. The four-to-one pattern survives this grouping exactly, because it keeps the two high districts together.`,
        `Now change ONE input -- the grouping, and nothing else -- and run it again. Regional scale, grouping two: the school boards. North: 800 plus 200 is 1,000 homes out of 20,000, and 1,000 divided by 20,000 is 0.05, which is 5 percent. South: 800 plus 200 is 1,000 out of 20,000, which is 5 percent as well. The two regions are identical. The pattern has vanished, and not one home changed, and no number in the records changed. Each new unit was handed one high district and one low district, and the merge averaged the difference away inside it.`,
        `Rewind the input and read the four district counts backwards to be sure nothing was misread: 200 Southeast, 800 Southwest, 200 Northeast, 800 Northwest. The two 800s are the two western districts. That is the whole explanation of both results: a grouping that keeps the 800s together shows the gap, and a grouping that splits them apart hides it.`,
        `Invert to check the arithmetic. 8 percent of 20,000 is 1,600, and 2 percent of 20,000 is 400, so the water-board figures return their counts. 5 percent of 20,000 is 1,000, twice, so the school-board figures return theirs. 5 percent of 40,000 is 2,000, which is the county total, and 1,600 plus 400 is 2,000 while 1,000 plus 1,000 is 2,000 as well. Both groupings recover the same county total, which is what tells you the two answers are the same data and not two datasets.`,
        `The verdict. WRONG: "North and South both report 5 percent, so the need for piped water is even across Callant." CORRECT: "North and South both report 5 percent because each of them contains one district at 8 percent and one at 2 percent; at the district scale the figures run from 2 to 8, and the western districts have four times the need of the eastern ones." Report the grouping with the figure, and before acting on a pattern, check whether it survives a different grouping of the same units.`,
      ],
      example: { problem: `Hold the data completely still and change only the grouping, then evaluate what happened to the pattern.

"Callant is a county of four districts, each with 10,000 homes: Northwest, Northeast, Southwest and Southeast. Homes with no piped water connection: Northwest 800, Northeast 200, Southwest 800, Southeast 200.

Callant runs its water service through two water boards, West (Northwest and Southwest) and East (Northeast and Southeast), and its schools through two school boards, North (Northwest and Northeast) and South (Southwest and Southeast)."`, solution: `District scale: Northwest 8 percent, Southwest 8 percent, Northeast 2 percent, Southeast 2 percent. County scale: 2,000 of 40,000 homes, which is 5 percent, showing no pattern. Grouped as water boards, West is 1,600 of 20,000, which is 8 percent, and East is 400 of 20,000, which is 2 percent, so the four-to-one pattern survives. Grouped as school boards, North is 1,000 of 20,000 and South is 1,000 of 20,000, both 5 percent, so the pattern vanishes entirely. The records never changed; only the grouping did, and both groupings add back to the same 2,000 homes.` },
      relatedLoIds: ['m8geo.scale-of-analysis-and-hidden-patterns'],
    },
  ],
  pointers: [
    { content: `Students often say "The country is at 60 percent, so my district is at about 60 percent too." — The national figure is a weighted average and it travels in one direction only: upward, out of the districts. In Mersaine, 60,000 of 100,000 households are within 2 kilometers of a library, which is 60 percent for the country. Harbor district is 54,000 of 60,000, which is 90 percent, and each of Kelm, Needle, Ostry and Pell is 1,500 of 10,000, which is 15 percent. WRONG: "The country is at 60 percent, so my district is about 60 percent." CORRECT: "The country is at 60 percent, and the district figures are 90, 15, 15, 15 and 15, so unless I am in Harbor my district is at 15 percent." To answer a claim about a district, get the figure computed over that district; the country figure cannot settle it, and no amount of correct national arithmetic will make it.`, kind: 'common-error' },
    { content: `Students often say "North and South both come out at 5 percent, so the water problem is spread evenly across the county." — The two figures match because of how the districts were paired, not because the county is even. North is Northwest at 800 homes plus Northeast at 200 homes, which is 1,000 of 20,000 homes, or 5 percent, and South is Southwest at 800 plus Southeast at 200, which is also 1,000 of 20,000, or 5 percent. Each of those two units was handed one district at 8 percent and one at 2 percent. Group the very same four districts as West and East instead and West is 1,600 of 20,000, which is 8 percent, against East at 400 of 20,000, which is 2 percent -- four times as high in the west, from records that never changed. WRONG: "The two regions match, so the county is even." CORRECT: "The two regions match because each contains one high district and one low district; at the district scale the figures run from 2 percent to 8 percent." Before believing a pattern, or believing that there is none, ask how the units were grouped and re-run the arithmetic on a different grouping.`, kind: 'common-error' },
    { content: `Every figure is computed over a unit, and the unit is a choice. Name the unit -- street, district, region, country -- before you read the number, because a figure with no unit named is not yet information.`, kind: 'tip' },
    { content: `To aggregate small units into a big one, add the counts and divide once. Averaging the unit percentages gives a tiny district the same weight as a huge one: 90, 15, 15, 15 and 15 average to 30 percent, while the counts give 60,000 of 100,000, which is 60 percent.`, kind: 'tip' },
    { content: `Match the claim to the scale. A claim about the country is settled by the country figure; a claim about a household or a district needs the figure for the unit it sits in. A national figure never travels down onto a district, and a district figure never travels up to stand for the country.`, kind: 'tip' },
    { content: `Report the spread beside the middle figure: the highest unit, the lowest unit, and how many sit at each end. Two places reported at the same 60 percent can be built completely differently and need completely different plans.`, kind: 'tip' },
    { content: `The groupings were drawn by somebody. Pair each high district with a low one and the difference averages away inside the new unit; keep the high districts together and it stands out. Callant is 8, 8, 2 and 2 at district scale, 8 against 2 grouped one way, and 5 against 5 grouped the other, from records that never changed.`, kind: 'tip' },
    { content: `Check every aggregation by multiplying back: 8 percent of 20,000 homes is 1,600, and the groupings must all add back to the same county total.`, kind: 'tip' },
    { content: `Let the decision pick the scale: a total to buy or ship is a national question, and where to put the next library, clinic or bus route is a question only the finest unit you have can answer.`, kind: 'tip' },
    { content: `These figures measure service and access in a place. They are never a score for a place or for the people who live in it.`, kind: 'tip' },
    { content: `Always name the unit first—street, district, region, or country—before you even look at the number. A figure with no unit is not information yet.`, kind: 'tip' },
    { content: `Never average the percentages of unequal districts. Always add the counts and divide once. Averaging 90, 15, 15, 15, 15 gives 30%, but the real figure is 60,000÷100,000 = 60%.`, kind: 'common-error' },
    { content: `A national figure never travels downward to describe a district. A 60% national figure does not mean your district is at 60%. Get the figure for your own district instead.`, kind: 'gotcha' },
    { content: `The same four numbers can produce a pattern or no pattern at all, depending only on how you group them. Always report which grouping you used and test whether the pattern survives a different grouping.`, kind: 'edge-case' },
    { content: `Always report the spread—highest, lowest, and how many units sit at each end—alongside the middle figure. Two places at 60% can be built completely differently.`, kind: 'common-error' },
    { content: `Check your aggregation by multiplying back. If 60% of 100,000 is 60,000, and your counts add to 60,000, you are right. If they don't match, you made an error.`, kind: 'tip' },
    { content: `Match the claim to the scale first. A claim about 'most households in the country' needs the country figure. A claim about 'a household in Ostry' needs only Ostry's figure, not the country's.`, kind: 'vocab-note' },
    { content: `The decision picks the scale. Buying for a whole country needs a national total. Deciding where to put the next clinic needs the finest unit—district, not region.`, kind: 'gotcha' },
  ],
};
