/**
 * Grade 8 World Geography — Unit 9 CED 9.3: Transboundary Problems & Cooperation.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.transboundary-problems-and-cooperation.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U9_TRANSBOUNDARY_PROBLEMS_AND_COOPERATION: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.transboundary-problems-and-cooperation.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 9,
  cedTopic: '9.3',
  cedTitle: 'Transboundary Problems & Cooperation',
  planId: 'evelyn.ms.m8geo.transboundary-problems-and-cooperation.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.transboundary-problems-and-cooperation.v1' }],
  theory: [
    { loId: 'm8geo.transboundary-problems-and-cooperation', content: `A SHARED PROBLEM HAS AN ARITHMETIC STRUCTURE, SO TEST IT WITH ARITHMETIC INSTEAD OF ARGUING ABOUT IT. You already know that many problems cross borders and that no single country can finish the job alone. What turns that into an analysis is one structural fact you can check in the figures: the gain from taking more is kept by whoever took it, and the cost of taking more is divided among everybody. When those two things are true, the move that is better for each country is worse for all of them, and the outcome everybody ends in is one that nobody picked. That is not a claim about what countries are like. It is a property of the numbers, and the way to establish it in a case is to compute each country's own figure under each of its choices and read what the figures say.` },
    { loId: 'm8geo.transboundary-problems-and-cooperation', content: `RUN THE COMPARISON A COUNTRY CAN ACTUALLY MAKE, BECAUSE THAT IS THE ONE THAT DECIDES WHAT HAPPENS. A country chooses its own level and nothing else. So take one country, hold the other country's choice fixed, and compare that country's own figure under restraint against its figure under taking. Then do it again with the other country's choice set the other way. If taking wins both comparisons, every country takes, whatever anybody says beforehand. The most common wrong step in this analysis is to compare the everybody-restrains outcome with the everybody-takes outcome and conclude that restraint is obviously better: it is better, and it is also a comparison no single country is able to make by its own decision, which is exactly why the problem is hard.` },
    { loId: 'm8geo.transboundary-problems-and-cooperation', content: `AN AGREEMENT IS A DESIGN, AND A DESIGN HAS THREE PARTS YOU CHECK ONE AT A TIME. Reading the promises tells you what an agreement intends; checking these three tells you whether it can hold. MONITORING: is there a measurement of what each member actually did, taken by something every member accepted in advance? ENFORCEMENT: does anything actually follow for a member whose measured figure misses the one it agreed to? A WAY TO STOP FREE RIDING: can anybody get the benefit without paying the cost -- a member that signs and then does nothing, or a country that never signed at all and enjoys the result anyway? Every agreement you evaluate in this lesson gets those three questions and no others, and the answer to each is yes or no on the evidence of the design as written.` },
    { loId: 'm8geo.transboundary-problems-and-cooperation', content: `THE THREE PARTS ARE ORDERED, AND CHECKING THEM OUT OF ORDER GIVES THE WRONG DIAGNOSIS. Monitoring comes first -- not because it matters most, but because enforcement has nothing to act on until a measurement says which member did what, so an agreement with a consequence and no measurement has a consequence that never triggers. Free riding comes last, because closing it means changing who gets the benefit or who pays the cost, and you cannot tell whether it needs closing until you can see who is actually doing what. When you find one part missing, say which part FIRST, then say what the other two would be worth once it is there. An agreement that gains one part often moves its failure rather than losing it.` },
    { loId: 'm8geo.transboundary-problems-and-cooperation', content: `EACH MISSING PART LEAVES ITS OWN SIGNATURE IN THE OUTCOME DATA, SO MATCH THE DATA TO THE SIGNATURE RATHER THAN GUESSING WHICH PART LOOKS WEAKEST. No monitoring: the members' own reports add up to the target while an independent measurement of the whole does not, and the gap is some whole number of members' worth of the promised cut. No enforcement: the measurement names the same members missing the same figures year after year and nothing changes. No way to stop free riding: the members deliver exactly what they promised, and the total for the shared thing barely moves, because what fell inside the agreement rose outside it. That third one is the one students miss, and the arithmetic that catches it is a subtraction -- the members' fall minus the outsider's rise is the whole change, and if those two are close, the design leaked.` },
    { loId: 'm8geo.transboundary-problems-and-cooperation', content: `JUDGE THE DESIGN BY THE SHARED THING, NOT BY COMPLIANCE, AND NEVER BY THE MEMBERS. Compliance is measured against the figure a member agreed to. Success is measured against what happened to the fish, the air or the woodland. They are different measurements and they come apart all the time: an agreement every single member complied with can leave the shared thing worse off than before, and when it does, the design is what failed, not the members. Hold the same line about the countries themselves. A country that does not restrain is answering the arithmetic of the design -- taking pays it more than restraint under either of the other choices -- and a country in a well-designed agreement answers different arithmetic. This course evaluates designs and measures outcomes. It does not grade countries, and it does not describe the people who live in them at all.` },
    { loId: 'm8geo.transboundary-problems-and-cooperation', kind: 'definition', title: 'shared problem', content: `one resource or one harm that several countries each control a piece of, where what each one takes or gives off changes what the others get.` },
    { loId: 'm8geo.transboundary-problems-and-cooperation', kind: 'definition', title: 'free riding', content: `taking the benefit of what others paid for or gave up, while paying nothing and giving up nothing.` },
    { loId: 'm8geo.transboundary-problems-and-cooperation', kind: 'definition', title: 'monitoring', content: `a measurement of what each member actually did, taken by something every member accepted in advance, as opposed to a figure a member reports about itself.` },
    { loId: 'm8geo.transboundary-problems-and-cooperation', kind: 'definition', title: 'enforcement', content: `whatever actually follows for a member whose measured figure misses the one it agreed to; if nothing follows, the agreement has none.` },
    { loId: 'm8geo.transboundary-problems-and-cooperation', kind: 'definition', title: 'compliance', content: `meeting the figure you agreed to, measured against that figure alone and never against what happened to the shared thing.` },
  ],
  methods: [
    {
      title: 'Worked fishing ground two years',
      steps: [
        `Both at the agreed level first, because it is the line every other line gets compared against. 300 plus 300 is 600, which is exactly what the ground replaces, so the overtake is 600 minus 600, which is 0, and the ground replaces the full 600 tonnes again the following year. Split evenly, that is 300 each. Two-year total: 300 plus 300 is 600 tonnes for each country.`,
        `Now one country high and one at the agreed level. Marrin at 500 and Oswen at 300 is 800 tonnes in the first year. 800 minus 600 is 200 tonnes of overtake. 200 divided by 100 is 2, and 2 multiplied by 150 is 300, so the ground replaces 600 minus 300, which is 300 tonnes, the following year. Split evenly, that is 150 each. Marrin lands 500 plus 150, which is 650. Oswen lands 300 plus 150, which is 450.`,
        `Invert that line before going on, because this is where an order-of-magnitude slip would hide. 150 multiplied by 2 is 300, which recovers the second year's ground. The 300-tonne drop divided by 150 for every 100 tonnes is 2, and 2 multiplied by 100 is 200, which recovers the overtake. And 650 plus 450 is 1,100, which is what the pair landed.`,
        `Now both high. 500 plus 500 is 1,000 tonnes in the first year. 1,000 minus 600 is 400 tonnes of overtake. 400 divided by 100 is 4, and 4 multiplied by 150 is 600, so the ground replaces 600 minus 600, which is 0. Each country lands 500 plus 0, which is 500 tonnes over the two years.`,
        `Run the comparison Marrin can actually make, which is the only one that decides anything. Marrin picks its own level and cannot pick Oswen's. If Oswen stays at the agreed level, Marrin lands 600 by staying and 650 by going high. If Oswen goes high, Marrin lands 450 by staying and 500 by going high. Going high wins both times, by 50 tonnes each time. The figures are built the same way for Oswen, so the same two comparisons come out the same way for Oswen. Both go high, and both land 500 -- which is 100 tonnes less than the 600 each of them had when both stayed. WRONG: "Both countries should simply pick the line where each lands 600, because 600 is more than 500." CORRECT: "No single country can pick that line. Each picks its own level, and from either of the other country's choices, going high pays 50 tonnes more."`,
        `The check to remember, and it is three clues of three different kinds. The first kind is each country's OWN figure at the moment it decides: 650 against 600, and 500 against 450, so taking pays whatever the other one does. The second kind is the figure for the pair together: 600 plus 600 is 1,200 when both stay, 650 plus 450 is 1,100 when one goes high, and 500 plus 500 is 1,000 when both do, so every step toward deciding alone shrinks the whole. The third kind is the ground itself, which belongs to neither of them: it replaces 600 tonnes, then 300, then 0. That third clue is the one that settles it, because it shows the 200 missing tonnes are not a transfer from one country to the other -- they are fish that no longer exist. One number is a hunch; three of different kinds, all pointing the same way, is evidence.`,
      ],
      example: { problem: `Marrin and Oswen fish one ground that lies across the line between them. Work out what each country lands over two years under each of the three combinations, and say what the figures show about deciding alone.

"The ground replaces 600 tonnes of fish a year. In the first year each country can fish at the agreed level, which is 300 tonnes, or at the high level, which is 500 tonnes.

Whatever the two take together above 600 tonnes in that year comes out of the breeding fish, and for every 100 tonnes of that overtake the ground replaces 150 tonnes less the following year.

In the second year both countries fish at the agreed level and split evenly whatever the ground has replaced."`, solution: `Both at the agreed level: no overtake, so the ground replaces 600 again and each country lands 300 plus 300, which is 600 tonnes over two years. One high: 800 taken, 200 of overtake, so the ground replaces 600 minus 300, which is 300, and the high country lands 500 plus 150, which is 650, while the other lands 300 plus 150, which is 450. Both high: 1,000 taken, 400 of overtake, so the ground replaces nothing and each lands 500. Going high pays a country 50 tonnes more under either of the other country's choices -- 650 against 600, and 500 against 450 -- so both go high and both end on 500, which is 100 tonnes less each than the 600 they had by staying. The pair total falls 1,200, 1,100, 1,000 and the ground itself falls 600, 300, 0, so the loss is fish that stopped existing rather than fish that changed hands.` },
      relatedLoIds: ['m8geo.transboundary-problems-and-cooperation'],
    },
    {
      title: 'Worked dust agreement design',
      steps: [
        `Turn the promises into one figure for the plain before looking at any outcome. 4 multiplied by 180 is 720 units, so that is what the agreement asked the plain to carry. Before the agreement it carried 4 multiplied by 300, which is 1,200. The promised cut is 1,200 minus 720, which is 480 units, and that is 120 units from each country, because 4 multiplied by 120 is 480 and 300 minus 180 is 120.`,
        `Put the two totals for the first year side by side. The four reports add to 4 multiplied by 180, which is 720. The weather service measured 840. Both cannot be right, and the one that does not depend on anybody reporting about themselves is the measurement, so the gap is 840 minus 720, which is 120 units.`,
        `Read the gap instead of just noticing it, because its size names the shortfall. 120 units is exactly one country's promised cut. So 840 is the figure you get when three countries cut to 180 and one did not cut at all: 180 plus 180 plus 180 is 540, and 540 plus 300 is 840. Check it from the other direction. The delivered cut is 1,200 minus 840, which is 360 units, and three countries cutting 120 each is 3 multiplied by 120, which is 360. Both directions tell the same story.`,
        `Say how much of the promise arrived, as a share. 360 delivered out of 480 promised is 360 divided by 480, which is 0.75, or 75 percent. Because every country promised the same cut, that share is also the share of the members that kept it: three of four is 0.75 as well. The share of the promise and the share of the members agree only because the cuts were equal, and they agree here.`,
        `Now put the design through the three questions. MONITORING: the only measurement of the plain is plain-wide, taken by a weather service for its own reasons, and every country's own figure is a figure it wrote about itself -- so the design can produce a total and cannot produce a name. ENFORCEMENT: the agreement says nothing follows from missing 180. FREE RIDING: whichever country is still at 300 is breathing the same cleaner air that the other three paid 120 units each to produce. WRONG: "One of the four is not telling the truth, so the agreement needs stricter promises." CORRECT: "The agreement already has the promises. What it does not have is anything that measures them, so a stricter promise is the same design with bigger numbers in it."`,
        `Name the missing part FIRST, because the order decides the fix. It is monitoring. Not because enforcement matters less, but because a consequence cannot attach to a country until a measurement says which country it is, and here the design can only say that somebody on the plain is 120 units short.`,
        `Rewind the data, then change one line and run the evaluation again. Backwards: 840 measured, 720 reported, 180 promised each, 300 before, four countries -- nothing misread. Now change ONE line of the design and nothing else: a measuring station on each country's side of the plain, paid for by all four, whose figures all four accepted in advance. Re-run the three questions. The 840 now splits into four named figures -- 180, 180, 180 and 300, which add back to 840 -- so monitoring is satisfied and the design can say which country is short. And then nothing happens, because the design still names no consequence, and the country at 300 still breathes the air the others paid for. The verdict moves from "you cannot tell who" to "you can tell, and it costs that country nothing." Adding one part moved the failure rather than removing it, which is why the three questions are asked together and in order.`,
      ],
      example: { problem: `Four countries -- Halvik, Ronne, Palt and Esker -- sit around one plain, and the wind carries dust from each of them over the whole of it. Evaluate the agreement they signed against the data from its first year, then work out what changes if one line of the design is different.

"Before the agreement each of the four sent 300 units of dust a year into the air over the plain.

The agreement: each country cuts to 180 units. Each country measures its own output and reports that figure once a year. The agreement names no consequence for a country whose figure misses 180. All four countries on the plain signed it.

After the first year all four reported 180 units. A weather service that measures the plain as a whole, for its own forecasting, put the total at 840 units."`, solution: `The agreement asked for 4 multiplied by 180, which is 720 units, down from 4 multiplied by 300, which is 1,200 -- a promised cut of 480, or 120 from each country. The reports add to 720 but the measurement says 840, a gap of 120, which is exactly one country's cut: 180 plus 180 plus 180 plus 300 is 840. The delivered cut was 1,200 minus 840, which is 360 of the 480 promised, and 360 divided by 480 is 0.75, matching the three of four members who kept it. The missing part is monitoring: every figure is self-reported, so the design produces a total and never a name, and the consequence it lacks would have nothing to attach to anyway. Add per-country measuring stations and nothing else, and the 840 splits into 180, 180, 180 and 300 -- the design can now name the country, and still nothing follows for it, so the failure moves from monitoring to enforcement rather than disappearing.` },
      relatedLoIds: ['m8geo.transboundary-problems-and-cooperation'],
    },
  ],
  pointers: [
    { content: `Students often say "The dust problem was solved once all four signed, because they promised and the total came down." — The total did come down, and it came down by three-quarters of what was promised, which is the part the sentence skips. The plain carried 4 multiplied by 300, which is 1,200 units, before the agreement; the agreement asked for 4 multiplied by 180, which is 720; the measurement after one year was 840. So the delivered cut was 1,200 minus 840, which is 360 units, against a promised cut of 1,200 minus 720, which is 480, and 360 divided by 480 is 0.75. The missing 120 units are exactly one country's cut, because 300 minus 180 is 120, and 180 plus 180 plus 180 plus 300 is 840. WRONG: "They signed, so it is solved." CORRECT: "Three of the four cut and one did not, and the design cannot say which, because every figure is one a country wrote about itself." A signature is a promise. A design is monitoring, enforcement and a way to stop free riding, and the outcome data is what tells you which of the three is missing.`, kind: 'common-error' },
    { content: `Students often say "The country that stayed at 300 is a greedy country, and that is why Marrin and Oswen both went high as well." — The figures do the explaining, and they explain it for every country at once. Going high paid Marrin 50 tonnes more whichever level Oswen picked: 650 against 600 when Oswen stayed at the agreed level, and 500 against 450 when Oswen went high. The figures are built the same way for Oswen, so both of Oswen's comparisons come out the same. A situation in which the gain from taking is kept by the taker while the cost is split among everybody produces that result from any set of countries, which is why the fix is a design and not a lecture -- and once the design changes what taking pays, the same countries answer different arithmetic. WRONG: "That country is greedy." CORRECT: "Taking paid 50 tonnes more than restraint under either of the other country's choices, so the thing to change is what taking pays." This course evaluates designs and measures outcomes. It does not grade countries, and it says nothing about the people who live in them.`, kind: 'common-error' },
    { content: `A shared problem is an arithmetic structure: the gain from taking is kept by the taker and the cost is split among everybody, so the move that is better for each is worse for all. Show it with figures rather than asserting it.`, kind: 'tip' },
    { content: `Run the comparison a country can actually make. Hold the other country's choice fixed and compare one country's own figure under each of its own choices, then repeat with the other choice fixed: 650 against 600, and 500 against 450, means taking pays either way.`, kind: 'tip' },
    { content: `Comparing the everybody-restrains outcome with the everybody-takes outcome is a comparison no single country can make by its own decision, and treating it as the deciding one is the most common wrong step here.`, kind: 'tip' },
    { content: `Put every agreement through three questions in order. Monitoring: is what each member did measured by something all of them accepted in advance? Enforcement: does anything follow from missing the figure? A way to stop free riding: can anybody get the benefit without paying the cost?`, kind: 'tip' },
    { content: `Each missing part has its own signature. Self-reports adding to the target while an independent measurement does not means no monitoring, and the gap is a whole number of members' cuts: 840 minus 720 is 120, which is exactly one country's 300 minus 180.`, kind: 'tip' },
    { content: `Members delivering exactly what they promised while the total for the shared thing barely moves means no way to stop free riding. Subtract to catch it: 600 hectares less inside the agreement against 450 more outside it leaves the belt only 150.`, kind: 'tip' },
    { content: `Compliance is measured against the figure a member agreed to; success is measured against what happened to the shared thing, and the two come apart. When they do, the design is what failed -- a country that does not restrain is answering the arithmetic, and this course grades no country and describes no people.`, kind: 'tip' },
    { content: `Don't compare the "everybody restrains" outcome to the "everybody takes" outcome and call that the deciding comparison. No single country can choose for both at once. Hold the OTHER country's choice fixed and compare THAT country's own figure under its two choices — that is the comparison each country actually makes.`, kind: 'common-error' },
    { content: `When one country's figure is 650 vs. 600 AND 500 vs. 450, taking wins both times — this is what 'going high pays more under either of the other country's choices' means. If taking only paid more in one scenario, restraint would be the choice in the other scenario.`, kind: 'vocab-note' },
    { content: `The three parts of an agreement—monitoring, enforcement, free riding—have a fixed order. Check them in order because enforcement needs a measurement to act on, and free riding detection needs to know who actually did what. Skip the order and you misdiagnose the problem.`, kind: 'gotcha' },
    { content: `A gap between self-reports and independent measurement that equals exactly one member's promised cut (like 840 vs. 720 = 120) is a signature of missing monitoring. It means you can see how much is short, but not which country is short.`, kind: 'tip' },
    { content: `Members delivered exactly what they promised AND the shared thing barely moved? Subtract the cut inside the agreement from the rise outside it. If those are close, free riding is the problem — the benefit leaked to non-members or stayed outside the agreement.`, kind: 'tip' },
    { content: `Never judge an agreement by compliance alone or by whether the number moved at all. Judge it by (1) putting it through the three questions and (2) comparing what was promised to what was actually delivered as a percentage or difference.`, kind: 'common-error' },
    { content: `Don't explain why a country took too much by saying it is 'greedy' or blaming its people. Explain it by the arithmetic: what did taking pay compared to restraint under the other country's actual choice? If taking paid more, the design is what needs to change, not the country's character.`, kind: 'common-error' },
    { content: `Compliance and success are two different measurements. An agreement where every member complies perfectly can leave the shared thing in worse shape than before if the design has no way to stop free riding. When they diverge, grade the design, not the countries.`, kind: 'vocab-note' },
  ],
};
