/**
 * Grade 8 World Geography — Unit 8 CED 8.2: Composite Indicators & Inequality.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.composite-indicators-and-inequality.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U8_COMPOSITE_INDICATORS_AND_INEQUALITY: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.composite-indicators-and-inequality.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 8,
  cedTopic: '8.2',
  cedTitle: 'Composite Indicators & Inequality',
  planId: 'evelyn.ms.m8geo.composite-indicators-and-inequality.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.composite-indicators-and-inequality.v1' }],
  theory: [
    { loId: 'm8geo.composite-indicators-and-inequality', content: `RANK EACH COLUMN SEPARATELY, BECAUSE THE UNITS DO NOT ADD. Four indicators for the same places arrive in four different units -- dollars a year, years of life, years of schooling, percent of households -- and dollars plus years plus percent is not a quantity of anything, so a composite can never be made by adding the raw figures. Take one indicator at a time, put the places in order on that indicator alone, and write down the position: rank 1 for the best figure in the column, then 2, then 3. Ranking strips the units off and leaves a position, and positions can be averaged. Notice exactly what is being ranked: a column of figures, for a list of indicators somebody chose. Ranking figures is not ranking places, and this course never does the second one -- a composite is a measurement, never a verdict on a country or on the people who live in it.` },
    { loId: 'm8geo.composite-indicators-and-inequality', content: `BEFORE YOU RANK A COLUMN, SAY WHICH END GETS RANK 1. For most indicators the larger figure is the better one: more years of schooling, a longer life expectancy, a larger share of households with a tap with clean water at home. For some the smaller figure is: the number of people sharing one doctor, the share of households with no electricity, the number of children who leave school early. Decide the direction out loud, column by column, before any number is written down. Then check the column: with three places it must contain 1, 2 and 3 exactly once, and with four places 1 through 4 exactly once. A column that gives two places the same rank is a column that was never really ranked.` },
    { loId: 'm8geo.composite-indicators-and-inequality', content: `AVERAGE THE RANKS, AND REMEMBER THE SCALE RUNS BACKWARDS. Add each place's ranks and divide by the number of indicators: four ranks adding to 6 give 6 divided by 4, which is 1.5. A LOWER average rank is the HIGHER position on the composite, because rank 1 is the best rank -- the composite scale runs the opposite way from the figures underneath it, and that is the single easiest thing in this routine to get backwards. Then invert, twice. Multiply each average back by the number of indicators and the total has to come back: 1.5 times 4 is 6. And add the totals across the whole table: with three places every column adds to 1 plus 2 plus 3, which is 6, so four columns add to 24, and the three place totals must add to 24 as well. If they do not, a column was ranked from the wrong end or a rank was used twice.` },
    { loId: 'm8geo.composite-indicators-and-inequality', content: `THE COMPOSITE KEEPS THE ORDER AND THROWS THE GAPS AWAY. A place ranked third on income might be a few dollars below second, or it might be at half of second, and the rank is 3 in both cases. That is the price of being able to combine dollars with years: the composite carries the ORDER on each indicator and nothing at all about how large the differences were. So a composite can put two places one step apart when the figures behind them are nearly identical, and one step apart when the figures behind them are miles apart. Say that out loud whenever you report one, because it is the first question a careful reader asks.` },
    { loId: 'm8geo.composite-indicators-and-inequality', content: `CHANGE THE LIST OF INDICATORS AND THE ANSWER CHANGES, SO THE LIST IS PART OF THE RESULT. Add an indicator and every total gains a rank while every average is divided by a bigger number; drop an indicator and the opposite happens. A place that led on four indicators can tie, or fall behind, on five. That is not a flaw to be fixed -- it is what a composite is: the result of a decision about what to count. Two people who count honestly and count different things get different orders, and neither is lying. So a composite is always reported together with the list it was built from, and a composite quoted without its list cannot be checked by anybody.` },
    { loId: 'm8geo.composite-indicators-and-inequality', content: `AN AVERAGE REPORTS HOW MUCH THERE IS; A DISTRIBUTION MEASURE REPORTS HOW IT IS SPREAD. Sort everybody in a country by income and cut them into five equal fifths, each holding a fifth of the people. The share of all the income that goes to the top fifth, and the share that goes to the bottom fifth, are two more figures, and the top share divided by the bottom share says how many times as much the top fifth receives: 36 percent against 9 percent is 36 divided by 9, which is 4 times; 50 percent against 5 percent is 10 times. Two countries with exactly the same income per person can sit at 4 times and at 10 times, and every indicator in the composite would be identical for them. To turn a share back into money, divide it by 20, because a fifth of the people is 20 percent of them, and multiply by the income per person. A country is never one thing inside, and this pair of numbers is how the spread gets measured instead of guessed.` },
    { loId: 'm8geo.composite-indicators-and-inequality', kind: 'definition', title: 'rank', content: `a place's position in one column of figures, counted from the end of that column the analyst named as best, so that 1 is the best position.` },
    { loId: 'm8geo.composite-indicators-and-inequality', kind: 'definition', title: 'composite', content: `one figure built from several indicators by ranking each indicator separately and averaging the ranks, which is what allows measurements in different units to be combined at all.` },
    { loId: 'm8geo.composite-indicators-and-inequality', kind: 'definition', title: 'average rank', content: `the total of a place's ranks divided by the number of indicators used; a lower average rank is a higher position on the composite.` },
    { loId: 'm8geo.composite-indicators-and-inequality', kind: 'definition', title: 'income share', content: `the percent of all the income in a place that goes to one group of its people, which reports how the total is spread rather than how large it is.` },
    { loId: 'm8geo.composite-indicators-and-inequality', kind: 'definition', title: 'top-fifth to bottom-fifth ratio', content: `the top fifth's share of income divided by the bottom fifth's share, giving how many times as much income the top fifth receives.` },
  ],
  methods: [
    {
      title: 'Worked build and move the composite',
      steps: [
        `Step one: name the direction for each of the four columns. More money, a longer life, more years of schooling and a larger share of households with clean water at home are all the larger-is-better direction, so in all four columns rank 1 goes to the largest figure. Say it before ranking anything, because the next worked table will not be this tidy.`,
        `Step two: rank each column on its own. Income: $15,000, then $9,000, then $6,000, so Bellun 1, Adera 2, Corvale 3. Life expectancy: 78, then 74, then 71, so Adera 1, Corvale 2, Bellun 3. Schooling: 13, then 11, then 9, so Corvale 1, Adera 2, Bellun 3. Clean water: 96, then 92, then 88, so Adera 1, Corvale 2, Bellun 3. Each of the four columns used 1, 2 and 3 exactly once, which is the first check.`,
        `Step three: add each country's four ranks and divide by 4. Adera: 2 plus 1 plus 2 plus 1 is 6, and 6 divided by 4 is 1.5. Bellun: 1 plus 3 plus 3 plus 3 is 10, and 10 divided by 4 is 2.5. Corvale: 3 plus 2 plus 1 plus 2 is 8, and 8 divided by 4 is 2.0.`,
        `Step four: invert, both ways. Multiply back: 1.5 times 4 is 6, 2.5 times 4 is 10, 2.0 times 4 is 8, so all three totals return. Add across the table: 6 plus 10 plus 8 is 24, and four columns of three ranks each must add to 4 times 6, which is 24. The table closes.`,
        `Now read the order, remembering that the scale runs backwards. Adera at 1.5 is first, Corvale at 2.0 is second, Bellun at 2.5 is third. WRONG: "Bellun has an average rank of 2.5, the biggest of the three, so Bellun comes out on top -- and it earns more than twice what Corvale earns." CORRECT: "Rank 1 is the best rank, so the lowest average is the highest position: Adera 1.5, then Corvale 2.0, then Bellun 2.5. Bellun leads on income by a wide margin and sits last on the other three columns, and the composite counts all four the same." And say what has actually been ordered: four columns of figures, for one chosen list of four indicators. Nobody has been graded.`,
        `Rewind the input and read it backwards to confirm the order follows from the table. Corvale is last on money and first on schooling; Adera is second on money and first or second on everything else; Bellun is first on money and last on everything else. A country that is near the top of three columns out of four should come out ahead of a country that is at the bottom of three, and that is exactly what the averages say.`,
        `Now change ONE thing and run the routine again. A fifth indicator joins the list: the number of people sharing one doctor -- Adera 900, Bellun 400, Corvale 1,200. This is the column where the direction matters: FEWER people for each doctor is the better figure, so rank 1 goes to the smallest number. Bellun 400 is 1, Adera 900 is 2, Corvale 1,200 is 3, and the column used 1, 2 and 3 once each. New totals: Adera 6 plus 2 is 8, and 8 divided by 5 is 1.6. Bellun 10 plus 1 is 11, and 11 divided by 5 is 2.2. Corvale 8 plus 3 is 11, and 11 divided by 5 is 2.2. Check by multiplying back: 1.6 times 5 is 8, 2.2 times 5 is 11, and the totals add to 8 plus 11 plus 11, which is 30, and five columns must add to 5 times 6, which is 30.`,
        `Read what the change did, in both directions. Adding the doctor indicator leaves Adera first and closes the two-step gap between Corvale and Bellun completely: they were 2.0 against 2.5, and they are now tied at 2.2. Run it the other way and the same digits say the same thing: drop the doctor indicator from the five and the tie breaks again, with Corvale back at 2.0 ahead of Bellun at 2.5. Nothing about any country changed between those two answers -- not one figure in the table moved. What moved was the list.`,
      ],
      example: { problem: `Build the composite for three invented countries, then evaluate what happens when a fifth indicator joins the list.

"Adera: income per person $9,000 a year; life expectancy 78 years; 11 years of schooling for a typical adult; 96 percent of households have a tap with clean water at home.

Bellun: $15,000 a year; 71 years; 9 years; 88 percent.

Corvale: $6,000 a year; 74 years; 13 years; 92 percent."`, solution: `On the four-indicator list the ranks are Adera 2, 1, 2, 1 for a total of 6 and an average of 1.5; Bellun 1, 3, 3, 3 for 10 and 2.5; Corvale 3, 2, 1, 2 for 8 and 2.0. Rank 1 is best, so the order is Adera, Corvale, Bellun. Multiplying each average back by 4 returns each total, and the totals add to 24, which is four columns of 6. Adding a fifth indicator -- people for each doctor, where the smaller figure ranks 1 -- gives Adera 8 and 1.6, Bellun 11 and 2.2, and Corvale 11 and 2.2, so Corvale and Bellun tie and the gap between them disappears. Dropping that indicator again restores Corvale ahead of Bellun. The figures never changed; the list did.` },
      relatedLoIds: ['m8geo.composite-indicators-and-inequality'],
    },
    {
      title: 'Worked same average different spread',
      steps: [
        `Start with what the two countries share, because it is the whole point of the example. Income per person is $12,000 in both. On an income indicator they would tie, take the same rank, and contribute the same number to a composite. Every other indicator could tie too. So far the two countries are indistinguishable.`,
        `Take the top-fifth to bottom-fifth ratio for each. Dunmere: 36 divided by 9 is 4, so the top fifth receives 4 times as much income as the bottom fifth. Esketh: 50 divided by 5 is 10, so the top fifth receives 10 times as much. Same average, and one country is spread two and a half times more widely than the other on this measure.`,
        `Check that the shares are complete before trusting them. Dunmere: 36 plus 9 is 45, so the middle three fifths hold 100 minus 45, which is 55 percent. Esketh: 50 plus 5 is 55, so the middle three fifths hold 100 minus 55, which is 45 percent. Both countries add to 100 percent across all five fifths, so no share is missing and none was counted twice.`,
        `Now turn the shares into money, which is where the size of the gap becomes visible. A fifth of the people is 20 percent of the people, so a group with 36 percent of the income and 20 percent of the people has 36 divided by 20, which is 1.8 times the average income: 1.8 times $12,000 is $21,600 for each person in Dunmere's top fifth. Dunmere's bottom fifth: 9 divided by 20 is 0.45, and 0.45 times $12,000 is $5,400. Esketh's top fifth: 50 divided by 20 is 2.5, and 2.5 times $12,000 is $30,000. Esketh's bottom fifth: 5 divided by 20 is 0.25, and 0.25 times $12,000 is $3,000.`,
        `Invert the conversion to make sure no decimal slipped. $21,600 divided by $12,000 is 1.8, and 1.8 times 20 is 36, the share it came from. $3,000 divided by $12,000 is 0.25, and 0.25 times 20 is 5. And the dollar figures reproduce the ratios directly: $21,600 divided by $5,400 is 4, and $30,000 divided by $3,000 is 10, the same two numbers the shares gave.`,
        `Say the verdict and say what it is not. WRONG: "Both countries report $12,000 per person, so a household in one is in about the same position as a household in the other." CORRECT: "Both countries report $12,000 per person, and inside that identical average Dunmere's bottom fifth has $5,400 each while Esketh's has $3,000 each -- a difference of $2,400 per person that the average and the composite are both blind to." The ratio measures how the income is spread. It does not say that either country is better or worse than the other, and it says nothing about anybody who lives in either one.`,
        `Rewind the shares and read them backwards to confirm nothing was misread: Esketh 5 and 50, Dunmere 9 and 36; the smaller bottom share and the larger top share both belong to Esketh, which is why Esketh is the wider of the two. Now change ONE input. Suppose Esketh's top fifth received 40 percent instead of 50 and its bottom fifth 10 percent instead of 5, with the middle three fifths holding 100 minus 50, which is 50 percent. The ratio becomes 40 divided by 10, which is 4 -- the same as Dunmere. The bottom fifth is now 10 divided by 20, which is 0.5, and 0.5 times $12,000 is $6,000 for each person, double the $3,000 it was. Income per person did not move, the total income in Esketh did not move, and every rank in every composite would be exactly what it was before.`,
      ],
      example: { problem: `Two invented countries report the same income per person. Work out how differently that income is spread, and say what the composite would have shown.

"Dunmere: income per person $12,000 a year. Sorted by income and cut into five equal fifths, the top fifth of the people receives 36 percent of all the income in the country and the bottom fifth receives 9 percent.

Esketh: income per person $12,000 a year. The top fifth receives 50 percent and the bottom fifth receives 5 percent."`, solution: `The two countries are identical on the average: $12,000 per person each, the same rank on an income indicator, the same contribution to a composite. They are not identical inside it. Dunmere's top fifth receives 36 percent against its bottom fifth's 9 percent, and 36 divided by 9 is 4 times; Esketh's is 50 against 5, and 50 divided by 5 is 10 times. In money, Dunmere runs $21,600 against $5,400 for each person and Esketh runs $30,000 against $3,000, and those pairs divide back to 4 and 10. Both sets of five shares add to 100 percent. If Esketh moved to 40 percent and 10 percent its ratio would become 4, matching Dunmere, while its income per person and every composite rank stayed exactly the same.` },
      relatedLoIds: ['m8geo.composite-indicators-and-inequality'],
    },
  ],
  pointers: [
    { content: `Students often say "Bellun scored 2.5, the highest of the three, so Bellun is the most developed country." — Take the arithmetic first. Adera's ranks add to 2 plus 1 plus 2 plus 1, which is 6, and 6 divided by 4 is 1.5. Corvale's add to 3 plus 2 plus 1 plus 2, which is 8, and 8 divided by 4 is 2.0. Bellun's add to 1 plus 3 plus 3 plus 3, which is 10, and 10 divided by 4 is 2.5. Rank 1 is the best rank, so the lowest average is the highest position and Bellun at 2.5 is LAST of the three, not first. WRONG: "Bellun scored 2.5, the highest of the three, so Bellun comes out on top." CORRECT: "Bellun has the highest average rank, which on this scale means the lowest position: Adera 1.5, Corvale 2.0, Bellun 2.5." Now the second half of the sentence, which no arithmetic can repair. What was ordered is four columns of figures, for a list of four indicators somebody chose -- and adding a fifth indicator, people for each doctor, pulls Bellun level with Corvale at 2.2. An order that a change to the list can rewrite is not a property of a country. Say what the measurement measures: on this list of indicators, these figures come in this order. A country is not more developed or less developed than another, and this course does not grade places or the people who live in them.`, kind: 'common-error' },
    { content: `Students often say "Both countries are at $12,000 per person, so households in them are equally well off." — The average is genuinely equal, and the spread is not. Divide the top-fifth share by the bottom-fifth share inside each country: Dunmere is 36 divided by 9, which is 4 times, and Esketh is 50 divided by 5, which is 10 times. Put it in money by dividing each share by 20, because a fifth of the people is 20 percent of them, and multiplying by $12,000: Dunmere runs $21,600 for each person in the top fifth against $5,400 in the bottom fifth, and Esketh runs $30,000 against $3,000. Check the conversion by dividing back, $21,600 divided by $12,000 is 1.8 and 1.8 times 20 is 36. WRONG: "Same income per person, so the same situation inside." CORRECT: "Same income per person, and a bottom fifth living on $5,400 each in one country and $3,000 each in the other." An average and a distribution measure answer two different questions -- how much there is, and how it is spread -- and a country is never one thing inside, which is exactly why the second question has to be asked out loud.`, kind: 'common-error' },
    { content: `Units do not add, so a composite is built by ranking each indicator column separately and averaging the positions, never by adding the raw figures.`, kind: 'tip' },
    { content: `Name the direction before you rank a column: larger is better for schooling, life expectancy and clean water; smaller is better for people sharing one doctor or households with no electricity. Then check the column used each rank exactly once.`, kind: 'tip' },
    { content: `A lower average rank is the higher position, because rank 1 is the best rank. The composite scale runs the opposite way from the figures underneath it.`, kind: 'tip' },
    { content: `Two checks, every time: multiply each average back by the number of indicators to recover the total, and confirm the totals add to the number of columns times 1 plus 2 plus 3.`, kind: 'tip' },
    { content: `The composite keeps the order and throws the gaps away, so it cannot tell you whether third place was just behind second or nowhere near it.`, kind: 'tip' },
    { content: `Change the list and the answer changes: four indicators put Corvale at 2.0 ahead of Bellun at 2.5, and adding a fifth ties them both at 2.2. Report a composite with the list it was built from, or nobody can check it.`, kind: 'tip' },
    { content: `An average says how much there is; the top fifth's share divided by the bottom fifth's share says how it is spread. Two countries at $12,000 per person can run 4 times and 10 times, so a country is never one thing inside.`, kind: 'tip' },
    { content: `All of this ranks columns of figures for a chosen list of indicators. It is a measurement, never a score for a country or for the people who live there.`, kind: 'tip' },
    { content: `Rank 1 is the BEST rank, so a lower average rank means a higher position. Don't read the composite scale like a report card — it runs backwards from the numbers underneath.`, kind: 'common-error' },
    { content: `Before you rank ANY column, say out loud which end is better — larger or smaller. Then check: the column must use ranks 1, 2, 3 (or 1, 2, 3, 4) exactly once each, no repeats.`, kind: 'tip' },
    { content: `Don't add the raw figures across columns — dollars plus years plus percent equals nothing. Rank each column separately, then average the ranks. That's what lets you mix different units.`, kind: 'gotcha' },
    { content: `The composite keeps order but throws gaps away. Rank 3 could mean 'slightly behind rank 2' or 'miles behind' — you can't tell from the average. Always say what the numbers actually show.`, kind: 'edge-case' },
    { content: `Change the indicator list and the answer changes — that's not a flaw, it's what a composite IS. Always report the list with the result, or nobody can check it.`, kind: 'vocab-note' },
    { content: `An average (like $12,000 per person) hides what's inside. The top-fifth to bottom-fifth ratio shows the spread: 36÷9 = 4 times versus 50÷5 = 10 times. Same average, wildly different distribution.`, kind: 'common-error' },
    { content: `To turn an income share back into dollars per person: divide the share by 20 (because a fifth = 20% of people), then multiply by income per person. 36% ÷ 20 × $12,000 = $21,600.`, kind: 'tip' },
    { content: `A composite is a measurement of four columns for a chosen list, never a grade on a country or the people in it. Don't say 'Bellun is less developed' — say 'on this list, Bellun ranks lower.'`, kind: 'vocab-note' },
  ],
};
