/**
 * Grade 8 World Geography — Unit 2 CED 2.3: Site Selection with Weighted Criteria.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.site-selection-with-weighted-criteria.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U2_SITE_SELECTION_WITH_WEIGHTED_CRITERIA: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.site-selection-with-weighted-criteria.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 2,
  cedTopic: '2.3',
  cedTitle: 'Site Selection with Weighted Criteria',
  planId: 'evelyn.ms.m8geo.site-selection-with-weighted-criteria.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.site-selection-with-weighted-criteria.v1' }],
  theory: [
    { loId: 'm8geo.site-selection-with-weighted-criteria', content: `SPLIT THE LIST BEFORE YOU SCORE ANYTHING, BECAUSE A SITING LIST ALWAYS HOLDS TWO KINDS OF CRITERIA. What makes a site good -- the ground itself and what it connects to -- is already on the table; the work here is turning that into a decision somebody can defend in public. A MUST-HAVE is answered yes or no: the lot holds at least 2 hectares, or it does not; the town owns it, or it does not. A WEIGHTED PREFERENCE is answered with a rating and then counts in an amount somebody chose: closeness to the homes a pool would serve might count five times over while room to expand later counts twice. So the first question of a siting decision is not "which site is best" but "which sites are even in the comparison", and those two questions have different answers more often than you would expect.` },
    { loId: 'm8geo.site-selection-with-weighted-criteria', content: `A MUST-HAVE IS A GATE, NOT A VERY LARGE WEIGHT. This is the step that goes wrong most often, and it goes wrong while looking careful. Once a site fails a must-have it is out, and no score anywhere else brings it back, because a must-have is a statement about whether the site can be used at all rather than about how good it would be. Turn a gate into a heavily weighted criterion and two bad things happen at once: a failing site with strong ratings everywhere else can win, and the answer starts depending on the size of a number nobody can defend. Eliminate first, score second, and expect to lose a site that would have scored highest. The honest sentence at the end of a siting decision is "the best of the sites we can actually use".` },
    { loId: 'm8geo.site-selection-with-weighted-criteria', content: `A WEIGHTED TOTAL IS EVERY RATING MULTIPLIED BY ITS OWN WEIGHT, ADDED UP, AND THE ROUTINE NEVER CHANGES. One: rate every surviving site on every preference, on one fixed scale, 1 through 5, where 5 is best. Two: multiply each rating by that criterion's weight. Three: add the products for each site. Four: compare the totals. Five: check by dividing each total by the sum of the weights, which gives that site's average rating and has to land between the lowest and the highest rating you gave it. A total of 40 against weights adding to 10 is an average of 4, and if that site never scored above 3, the arithmetic slipped somewhere and the verdict is worth nothing until you find it.` },
    { loId: 'm8geo.site-selection-with-weighted-criteria', content: `JUSTIFY BY NAMING WHERE THE MARGIN CAME FROM, NOT BY NAMING THE WINNER. A total on its own persuades nobody, and "it led on most of the criteria" is not a reason, because counting the criteria a site leads is a different calculation from scoring it and the two disagree all the time. A site can be rated higher on two preferences out of three and still lose, if the one it lost carries the heaviest weight and the widest rating gap. The margin is made where a big weight meets a big gap, so find that criterion, say its name, and say its numbers.` },
    { loId: 'm8geo.site-selection-with-weighted-criteria', content: `THE WINNER IS A PROPERTY OF THE WEIGHTS, NOT OF THE SITE, SO CHANGE ONE WEIGHT AND RUN IT AGAIN. Weights are a judgment about what matters, different people set them differently, and a siting result is therefore only as settled as the weights behind it. Re-score every site with one weight changed and you learn something no single total can tell you: raising a weight by 3 points is worth 3 times each site's OWN rating on that criterion, so it pushes the sites apart instead of lifting them together. Go one step further and name the exact weight at which two sites tie. A decision that flips when a weight moves by a point or two is a decision to report as close, not as settled.` },
    { loId: 'm8geo.site-selection-with-weighted-criteria', content: `TOTALS ARE ONLY COMPARABLE INSIDE ONE WEIGHTING. Every site in one comparison gets the same weights, and the moment a weight changes, every site is scored again -- including the ones nobody is worried about. A total from the old weights set beside a total from the new ones compares nothing, because the maximum moved too: weights adding to 10 put every total out of 50, and weights adding to 12 put every total out of 60. If two weightings really do have to be compared, read each total against the maximum for its own weighting, and say plainly that what changed was what somebody decided to count, not the land.` },
    { loId: 'm8geo.site-selection-with-weighted-criteria', kind: 'definition', title: 'must-have', content: `a criterion answered yes or no that decides whether a site is scored at all; a site that fails one leaves the comparison before any scoring starts.` },
    { loId: 'm8geo.site-selection-with-weighted-criteria', kind: 'definition', title: 'weight', content: `the number a criterion carries, saying how many points each rating point on that criterion adds to a site's total.` },
    { loId: 'm8geo.site-selection-with-weighted-criteria', kind: 'definition', title: 'rating', content: `the score one site is given on one criterion, on a single fixed scale used for every site, so that unlike qualities can be added together.` },
    { loId: 'm8geo.site-selection-with-weighted-criteria', kind: 'definition', title: 'weighted total', content: `the sum of every rating multiplied by its own weight; it means something only against other totals computed from the same weights.` },
    { loId: 'm8geo.site-selection-with-weighted-criteria', kind: 'definition', title: 'sensitivity', content: `how far a weight has to move before the ranking changes, found by re-scoring every site with that weight changed.` },
  ],
  methods: [
    {
      title: 'Worked run the routine',
      steps: [
        `Step one: split the list and run the gates first, before anything is multiplied. The must-haves are at least 2 hectares of level ground and a sewer connection. Larkin has 3 hectares and the connection, so it passes both. Netherby has exactly 2 hectares, and "at least 2" is met by exactly 2, so it passes, and it is on the line as well. Moss Row has the most land of the three and no sewer connection, so it fails a must-have and leaves the comparison right here.`,
        `Step two: score Moss Row anyway, once, so that elimination is not a word but a price. Closeness 5 times 5 is 25, cost 3 times 4 is 12, room 2 times 4 is 8, and 25 plus 12 plus 8 is 45 -- higher than anything the other two sites are going to reach. Moss Row is still out. A pool with nowhere to send its water is not a pool, and 45 points do not lay 3 kilometers of pipe. WRONG: "Moss Row scores highest, so Moss Row wins." CORRECT: "Moss Row is not in the comparison at all; the winner is the highest total among the sites Ardith can actually use."`,
        `Step three: score the two survivors, one criterion at a time. Larkin: 5 times 3 is 15 for closeness, 3 times 5 is 15 for cost, 2 times 5 is 10 for room. 15 plus 15 plus 10 is 40. Netherby: 5 times 5 is 25 for closeness, 3 times 3 is 9 for cost, 2 times 2 is 4 for room. 25 plus 9 plus 4 is 38. Larkin wins, 40 to 38.`,
        `Step four: invert the arithmetic to check it. The weights add to 5 plus 3 plus 2, which is 10, so every total is out of 5 times 10, which is 50, and both totals sit under that. Now divide each total by 10 to recover the average rating. Larkin: 40 divided by 10 is 4, and Larkin was rated between 3 and 5, so 4 sits where it should. Netherby: 38 divided by 10 is 3.8, and Netherby was rated between 2 and 5. Multiply back: 4 times 10 is 40, and 3.8 times 10 is 38. Nothing slipped.`,
        `Step five: say where the margin came from, because a total persuades nobody by itself. Netherby is the closer site and closeness carries the heaviest weight, so it takes 5 times the 2-point rating gap, which is 10 points. Larkin takes cost, 3 times a 2-point gap, which is 6, and room to expand, 2 times a 3-point gap, which is 6. 6 plus 6 is 12 against 10, so Larkin wins by 2. That is the justification to write down: Larkin is cheaper to prepare and has room to grow, and those two together just outweigh the fact that Netherby is closer.`,
        `Rewind the input and read it backwards to confirm the verdict follows from the data rather than from the order the sites were written in. Larkin was the middle site on land, took the top rating on two of the three preferences, and passed both gates. A margin of 2 points out of a possible 50 is narrow, and a narrow margin is the signal to test the weights before anybody signs anything.`,
        `Now change ONE weight and run it again. Suppose the council hears from families with no car and raises the closeness weight from 5 to 7, leaving cost at 3 and room at 2. Re-score BOTH sites, not only the close one. Larkin: 7 times 3 is 21, plus 15, plus 10, which is 46. Netherby: 7 times 5 is 35, plus 9, plus 4, which is 48. Netherby now wins by 2. Not one thing about either lot changed; the council changed what it was counting. And the tipping point can be named exactly: at a closeness weight of 6, Larkin is 18 plus 15 plus 10, which is 43, and Netherby is 30 plus 9 plus 4, which is 43 as well. Below 6 Larkin wins, above 6 Netherby wins, and the pool is being sited by the choice of one number.`,
      ],
      example: { problem: `Run the routine straight through, then test the answer.

The town of Ardith is choosing a site for a new public swimming pool. Two criteria are must-haves: the lot must have at least 2 hectares of level ground, and it must already be connected to the town sewer line. Three criteria are weighted preferences: closeness to the homes the pool would serve counts 5, the cost of preparing the ground counts 3, and room to expand later counts 2. Every site is rated 1 to 5 on each preference, where 5 is best.

"Larkin: 3 hectares of level ground, on the sewer line. Closeness 3, cost 5, room to expand 5.

Moss Row: 4 hectares of level ground, no sewer connection -- the nearest line ends 3 kilometers away. Closeness 5, cost 4, room to expand 4.

Netherby: 2 hectares of level ground, on the sewer line. Closeness 5, cost 3, room to expand 2."

Which site should Ardith choose, and how far would the closeness weight have to move before the answer changes?`, solution: `Larkin, at 40 points against Netherby at 38. Moss Row is eliminated before scoring because it has no sewer connection, even though it would have scored 45. Larkin's margin comes from cost, 3 times a 2-point gap, which is 6, and room to expand, 2 times a 3-point gap, which is 6 -- together outweighing the 10 points closeness hands Netherby. Multiplying each average rating back by the weight sum of 10 returns 40 and 38. The result is sensitive: at a closeness weight of 6 the two sites tie at 43, and at 7 Netherby wins, 48 to 46.` },
      relatedLoIds: ['m8geo.site-selection-with-weighted-criteria'],
    },
    {
      title: 'Worked repair the gate',
      steps: [
        `Check the arithmetic before arguing with the method, because a wrong verdict is not always a wrong sum. Solway Flats on the three preferences: 2 times 5 is 10, 4 times 5 is 20, 4 times 5 is 20, and 10 plus 20 plus 20 is 50. Redding Field: 2 times 3 is 6, 4 times 5 is 20, 4 times 4 is 16, and 6 plus 20 plus 16 is 42. Underhill: 2 times 5 is 10, 4 times 2 is 8, 4 times 3 is 12, and 10 plus 8 plus 12 is 30. Add the ownership points the student invented and the three totals are 51, 47 and 35, exactly as written. Every figure is right. The method is what is wrong.`,
        `Name the slip. "The district must already own it" is answered yes or no, which makes it a gate, and the student turned it into a weighted preference. Notice that the student handled the other gate correctly -- Thorn Lane is 3 hectares against a minimum of 4, so it is out -- and then let the second gate be bought off by a strong score somewhere else.`,
        `Show that the method cannot be repaired by choosing a better weight, which is the move a student usually reaches for next. Keep everything else the same and try an ownership weight of 3: Solway Flats is 3 plus 50, which is 53, and Redding Field is 15 plus 42, which is 57, so Redding Field wins. Try 2: Solway Flats is 2 plus 50, which is 52, and Redding Field is 10 plus 42, which is 52 as well, a tie. Try 1, the number the student used: Solway Flats wins by 4. One method, three numbers that all look reasonable, three different answers -- and not one of them changes the fact that the district cannot buy land this year. Hunting for the right weight for a gate IS the error; it is not a fix for it.`,
        `Re-run it properly. Eliminate first: Thorn Lane fails the size gate at 3 hectares, and Solway Flats fails the ownership gate because it is for sale rather than owned. Two parcels survive. Score those two on the three preferences only: Redding Field is 42 and Underhill is 30, so Redding Field wins by 12. WRONG: "Solway Flats scores 50 out of 50 on the preferences, so it is the best parcel available." CORRECT: "Solway Flats is not available, so the comparison is Redding Field at 42 against Underhill at 30, and Redding Field wins by 12."`,
        `Invert to check. The weights add to 2 plus 4 plus 4, which is 10, so every total is out of 50. Solway Flats was rated 5 on all three, and its 50 is exactly that maximum, which checks that line. Redding Field: 42 divided by 10 is an average rating of 4.2, its ratings ran from 3 to 5, and 4.2 times 10 is 42. Underhill: 30 divided by 10 is 3, its ratings ran from 2 to 5, and 3 times 10 is 30.`,
        `Rewind the input and read the two survivors backwards. Underhill is the larger parcel and the shorter walk; Redding Field drains better and has more room to park. Drainage and parking carry 4 each while walking carries 2, so the two criteria Redding Field leads are the two the district decided to count most heavily. The verdict follows from the weights, and the weights were the district's own judgment.`,
        `Now change ONE weight and run it again, because a winner nobody has tested is a guess. Suppose the district finds that most students walk, and raises the walking weight from 2 to 5. Redding Field: 5 times 3 is 15, plus 20, plus 16, which is 51. Underhill: 5 times 5 is 25, plus 8, plus 12, which is 45. Redding Field still wins, and the margin has fallen from 12 to 6. Push further and the tie point is findable: at a walking weight of 8, Redding Field is 24 plus 20 plus 16, which is 60, and Underhill is 40 plus 8 plus 12, which is 60 as well -- but 8 is twice what drainage or parking carries, and the district has no reason to go there. This time the re-run confirmed the winner instead of overturning it, and that is worth just as much: now the district knows the answer does not hang on a small change.`,
      ],
      example: { problem: `A student ran a siting decision and let a must-have be outvoted. Find the slip, repair it, and show why the student's method cannot be rescued by picking a better number.

The Fenmore school district is choosing a parcel for a new sports field. Two must-haves: the parcel must be at least 4 hectares, and the district must already own it, because no land can be bought this budget year. Three weighted preferences: how far students walk counts 2, how well the ground drains counts 4, and room for parking counts 4. Ratings run 1 to 5, where 5 is best.

"Redding Field: district-owned, 5 hectares. Walk 3, drainage 5, parking 4.

Solway Flats: privately owned and for sale, 6 hectares. Walk 5, drainage 5, parking 5.

Thorn Lane: district-owned, 3 hectares. Walk 4, drainage 3, parking 2.

Underhill: district-owned, 7 hectares. Walk 5, drainage 2, parking 3."

The student wrote: "Thorn Lane is only 3 hectares, so it is out. For ownership I added a fourth criterion, owned or not owned, with a weight of 1, scoring 5 for a district parcel and 1 for a private one. Solway Flats: 1 plus 50 is 51. Redding Field: 5 plus 42 is 47. Underhill: 5 plus 30 is 35. Solway Flats wins."`, solution: `The arithmetic was right and the method was wrong. "The district must already own it" is a must-have, answered yes or no, and the student scored it as a weighted preference instead. That method gives three different winners for three different ownership weights -- Solway Flats at a weight of 1, a tie at 2, Redding Field at 3 -- which is the sign that a number is doing work no number can defend. Run correctly, Thorn Lane is out at 3 hectares against a 4-hectare minimum and Solway Flats is out because it is for sale, leaving Redding Field at 42 against Underhill at 30. Raising the walking weight from 2 to 5 narrows the margin to 51 against 45 without changing the winner, and the two would not tie until that weight reached 8.` },
      relatedLoIds: ['m8geo.site-selection-with-weighted-criteria'],
    },
  ],
  pointers: [
    { content: `Students often say "Moss Row scored 45, the highest of the three, so Moss Row should get the pool." — Moss Row has no sewer connection, and the sewer connection was a must-have, so Moss Row is not in the comparison at all and its 45 is a number about a site that cannot be used. The real comparison is Larkin, where 5 times 3 is 15, plus 3 times 5, which is 15, plus 2 times 5, which is 10, giving 40, against Netherby, where 25 plus 9 plus 4 gives 38. Larkin wins by 2. WRONG: "Moss Row scores highest, so Moss Row wins." CORRECT: "Moss Row fails a must-have and leaves before any scoring; Larkin is the best of the sites Ardith can actually use, 40 against 38." A must-have answers whether a site may be used; a weight answers how much one quality counts once the site is already allowed. Those are two different questions, and no weight is large enough to turn a no into a yes.`, kind: 'common-error' },
    { content: `Students often say "Netherby scored 48 under the new weights, which beats the 40 Larkin scored, so Netherby was the better site all along." — Two totals compare only when the same weights produced them. Under the first weights, which add to 10, every total is out of 50: Larkin is 40, Netherby is 38, and Larkin wins. Under the raised closeness weight the weights add to 12, so every total is out of 60: Larkin is 21 plus 15 plus 10, which is 46, and Netherby is 35 plus 9 plus 4, which is 48, and Netherby wins. Setting 48 against 40 crosses the two weightings and compares nothing. If the two runs really must be read side by side, read each total against the maximum for its own weighting: 40 out of 50 is 80 percent, and 48 out of 60 is 80 percent as well. WRONG: "48 beats 40, so Netherby is the better site." CORRECT: "Larkin wins under the first weights and Netherby wins under the second, and what changed between the runs was what the council decided to count, not the land." Neither run used wrong numbers; they used different judgments, and a siting result is only as settled as the weights behind it.`, kind: 'common-error' },
    { content: `Split the criteria before scoring anything: must-haves are answered yes or no and decide who is in the comparison, while weighted preferences are rated and decide who wins.`, kind: 'tip' },
    { content: `Eliminate first, score second. A site that fails a must-have is out however well it would have scored, and the honest verdict names the best of the sites that can actually be used.`, kind: 'tip' },
    { content: `A gate has no weight. Give one a weight and the answer follows the size of that number: at a weight of 1 the ineligible parcel won, at 2 it tied, at 3 it lost.`, kind: 'tip' },
    { content: `Weighted total: multiply each rating by its own weight and add. Check it by dividing the total by the sum of the weights, because that average rating has to sit between the site's own lowest and highest rating.`, kind: 'tip' },
    { content: `Justify by naming where the margin came from. Leading on the most criteria is not winning; the margin is made where a heavy weight meets a wide rating gap.`, kind: 'tip' },
    { content: `Change one weight and run it again, re-scoring every site. Raising a weight by 3 points is worth 3 times each site's own rating on that criterion, so it pushes sites apart rather than lifting them together.`, kind: 'tip' },
    { content: `Totals compare only inside one weighting. Weights adding to 10 put every total out of 50 and weights adding to 12 put every total out of 60, so a total from one weighting says nothing against a total from the other.`, kind: 'tip' },
  ],
};
