/**
 * Grade 8 World Geography — Unit 5 CED 5.4: Refugees & Displacement.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.refugees-and-displacement.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U5_REFUGEES_AND_DISPLACEMENT: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.refugees-and-displacement.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 5,
  cedTopic: '5.4',
  cedTitle: 'Refugees & Displacement',
  planId: 'evelyn.ms.m8geo.refugees-and-displacement.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.refugees-and-displacement.v1' }],
  theory: [
    { loId: 'm8geo.refugees-and-displacement', content: `TWO QUESTIONS SETTLE WHICH WORD FITS, AND YOU ASK THEM IN ORDER. Before either one, there is a gate: was the person forced from home by danger, conflict or disaster, rather than choosing to move? Somebody who moved for a job or a school has not been displaced, and none of the three words applies to them. Once the gate is passed, question one is a line on a map: has the person crossed an international border? If the answer is no, the person is an INTERNALLY DISPLACED PERSON -- forced from home, but still inside their own country and still under its laws and its protection. If the answer is yes, ask question two: has the claim for protection been decided? While the claim is waiting, the person is counted as an ASYLUM SEEKER. Once it has been decided in their favor, they are counted as a REFUGEE. Distance settles nothing in either question: a family that traveled 600 kilometers inside their own country is internally displaced, and a family that walked 12 kilometers across a border and asked for protection is an asylum seeker.` },
    { loId: 'm8geo.refugees-and-displacement', content: `THE WORD NAMES A SITUATION AND THE RULES THAT COME WITH IT, NEVER A KIND OF PERSON. Each of the three words says which country is responsible and which rules apply -- an internally displaced person is protected by their own government, and somebody who has crossed a border is asking another country for that protection instead. It says nothing about the person. The clearest proof is that the same person can be counted in two categories in one year without changing at all: an asylum seeker whose claim is decided in their favor on a Tuesday is counted as a refugee on the Wednesday, and somebody internally displaced in March who crosses a border in June is counted as an asylum seeker in June. A border crossing and a decision moved; the person did not. So every count of these groups is a count on a stated date, and when you read one, ask what date it was taken on.` },
    { loId: 'm8geo.refugees-and-displacement', content: `DISTANCE, MONEY AND DOCUMENTS FILTER EVERY STEP AWAY FROM HOME, AND THAT IS WHY MOST PEOPLE DO NOT GET FAR. Most people forced out of their homes stay inside their own country or in the country next door, and the reason is visible in the data every time. Take a case: 40,000 people leave the eastern districts of Averin. Moving to Dorval, a city 120 kilometers away inside Averin, costs a $6 bus fare and needs no document at all. Crossing into Solvane, the neighboring country, means a 60-kilometer trip, a $12 fare and an identity card at the crossing. Getting past Solvane to Marrin means 900 kilometers, a visa that has to be applied for, and $180. Each step multiplies the money and adds a document, so each group is smaller than the one before it: 26,000 stayed inside Averin, 12,000 crossed into Solvane, and 2,000 reached Marrin or farther. That is 65 percent, 30 percent and 5 percent of the 40,000 -- and 0.65 times 40,000 is 26,000, so the shares recover the counts.` },
    { loId: 'm8geo.refugees-and-displacement', content: `TAKE EACH GROUP AS A SHARE OF EVERYBODY WHO LEFT HOME, AND CHECK THE SHARES ADD TO 100 PERCENT. A count of one group on its own settles nothing, because a claim like "most of them" is a claim about all of them, and a count cannot say what share of all of them one group is. Divide each group by everybody who left home, and the picture rearranges itself: in the Averin case the far-away group is 2,000 out of 40,000, which is 5 percent, and a claim built on that group is a claim about one person in twenty. When three shares are supposed to cover everybody, add them up. If they do not reach 100 percent, either a group is missing or somebody has been counted twice.` },
    { loId: 'm8geo.refugees-and-displacement', content: `A RESPONSE IS EVALUATED AGAINST STATED CRITERIA, OVER A STATED LENGTH OF STAY, AND SOMEBODY BEARS EVERY COST. Two responses come up again and again: a camp near the border, and settling people in towns. Neither is the right answer in general, and the way to tell them apart is to settle each stated criterion on its own -- how soon shelter is ready, the total cost over the expected stay, the share of school-age children with a school place, whether adults can earn -- and then say which criteria each response wins. Two rules do most of the work. First, a one-time setup cost is not a monthly cost: divide it by the monthly saving to find the month the cheaper-to-run response catches up, and total both responses over the same number of months before comparing. Second, ask who bears each cost, including the people who were already living where the response happens, because a cost that falls outside the plan is still a cost.` },
    { loId: 'm8geo.refugees-and-displacement', kind: 'definition', title: 'displacement', content: `being forced to leave home by conflict, violence or disaster rather than choosing to move; it is the condition the three words below sort into categories.` },
    { loId: 'm8geo.refugees-and-displacement', kind: 'definition', title: 'internally displaced person', content: `a person forced from home who has not crossed an international border, and who therefore stays under the protection of their own country.` },
    { loId: 'm8geo.refugees-and-displacement', kind: 'definition', title: 'asylum seeker', content: `a person who has crossed an international border, asked that country for protection, and is waiting for the claim to be decided.` },
    { loId: 'm8geo.refugees-and-displacement', kind: 'definition', title: 'refugee', content: `a person who has left their own country because of persecution, conflict or violence, and whose claim for protection has been decided in their favor.` },
    { loId: 'm8geo.refugees-and-displacement', kind: 'definition', title: 'host community', content: `the people already living where displaced people arrive, whose housing, schools and services carry part of the cost of a response.` },
  ],
  methods: [
    {
      title: 'Worked run the two questions',
      steps: [
        `Start at the gate, before either question. Sena, Tomas and Ilka each left because staying was not safe. Bran moved four years ago to take a job and renews a permit every year, so he was not forced from home and none of the three words applies to him: he is somebody who moved to another country to work. WRONG: "Bran is from Averin and lives in Solvane, so he must be a refugee now." CORRECT: "Bran chose to move for work before any of this, so the two questions never start for him."`,
        `Sena, question one: has she crossed an international border? No. Dorval is in western Averin, so she is still in her own country. That settles it on the first question -- Sena is an internally displaced person -- and the 400 kilometers do not enter into it. She is still under Averin's laws and Averin's protection.`,
        `Tomas, question one: yes, he is in Solvane. So ask question two: has his claim been decided? No. He asked three weeks ago and is waiting, so he is counted as an asylum seeker. WRONG: "Tomas fled the fighting, so he is a refugee." CORRECT: "Tomas crossed a border and asked for protection, and while the claim is waiting he is counted as an asylum seeker."`,
        `Ilka, question one: yes. Question two: yes, her claim was decided in her favor. She is counted as a refugee. Notice what separates her from Tomas, because it is the whole of question two: not the danger they left, not the border they both crossed, but one decision on one date.`,
        `Rewind the four cases and read them backwards to check nothing was misread: a work permit renewed every year, a claim decided in her favor, a claim still waiting, a move to a city inside the country. Now change ONE fact in two of them. If Solvane decides Tomas's claim in his favor next month, he is counted as a refugee from that day, and nothing about Tomas will have changed -- a decision will have changed. And if Sena had gone east to the Solvane border instead of west to Dorval, 60 kilometers instead of 400, and asked Solvane for protection, she would be counted as an asylum seeker rather than an internally displaced person, on the shorter journey of the two. The border and the decision do the sorting. The distance and the danger do not.`,
      ],
      example: { problem: `Run the two questions on four described people, then say what would have to change for any of the answers to change.

"Fighting spread through the eastern districts of Averin in the spring.

Sena left her home in an eastern district when the fighting reached it. She moved to Dorval, a city in western Averin, 400 kilometers away, and has been there five months.

Tomas crossed the border into Solvane three weeks ago and asked Solvane for protection. His claim has not been decided.

Ilka crossed into Solvane fourteen months ago and asked for protection. Her claim was decided in her favor last spring.

Bran moved from Averin to Solvane four years ago to take a job at a bottling plant, and renews a work permit every year."`, solution: `Sena is an internally displaced person: forced from home, no border crossed, so question one settles it and the 400 kilometers are irrelevant. Tomas is an asylum seeker: border crossed, claim asked for, no decision yet. Ilka is a refugee: border crossed, claim decided in her favor. Bran is none of the three, because he moved for work and was not forced from home. A decision on Tomas's claim would make him a refugee without anything about him changing, and Sena would have been an asylum seeker if she had traveled 60 kilometers east instead of 400 kilometers west.` },
      relatedLoIds: ['m8geo.refugees-and-displacement'],
    },
    {
      title: 'Worked camp or towns',
      steps: [
        `Criterion one, how soon shelter is ready. Response A is ready in 3 weeks and Response B in 11, so A is 8 weeks sooner, and for those 8 weeks Response B leaves people in emergency shelter. Write that down as A's win and keep going, because one criterion is not a verdict.`,
        `Criterion two, total cost, and the trap is in the shape of the numbers. The monthly figures are per person, so scale them: A is 20,000 times $60, which is $1,200,000 a month. B is 20,000 times $45, which is $900,000 a month. B is $300,000 a month cheaper to run. WRONG: "B costs $45 a person plus $900,000 every month, so B is far more expensive." CORRECT: "B costs $300,000 a month less and $900,000 once, so the real question is how many months it takes to pay that $900,000 back."`,
        `Work that month out, then total both over the stated stay. $900,000 divided by $300,000 a month is 3 months, so from month 4 onward B is the cheaper response. Two years is 24 months. A: $1,200,000 times 24 is $28,800,000. B: $900,000 times 24 is $21,600,000, plus the $900,000 setup, which is $22,500,000. B costs $6,300,000 less. Invert to check by the other route: 24 months of saving $300,000 is $7,200,000, minus the $900,000 setup is $6,300,000. The two routes agree, so no zero slipped.`,
        `Criterion three, school places, as a share of the children rather than a count. Of 3,000 school-age children, A seats 1,200: 1,200 divided by 3,000 is 0.40, or 40 percent. B seats 2,700: 2,700 divided by 3,000 is 0.90, or 90 percent. Check both by multiplying back -- 0.40 times 3,000 is 1,200 and 0.90 times 3,000 is 2,700 -- and take the difference: B seats 1,500 more children.`,
        `Criterion four, whether adults can earn, and then the question about who else bears a cost. The camp sits 8 kilometers from the nearest town with no work on the site, so adults there earn nothing; the packing plants near the five towns are short of workers and will hire. Against that, rents in those five towns rose 15 percent in the first year, and that cost falls on the households who were already living there and were not part of the choice. Name it rather than leaving it out: a response can win on the stated criteria and still put a cost on somebody who did not choose it.`,
        `Now assemble the verdict, and notice that the evidence for it is three different kinds. Money says B, by $6,300,000 over the stated stay. Children say B, by 1,500 school places. Work says B, because the plants will hire and the camp has nothing within 8 kilometers. One number is a hunch; three of different kinds, all pointing the same way, is evidence. A wins on speed by 8 weeks, and the honest verdict says so out loud instead of pretending every criterion agreed.`,
        `Change ONE input and run it again. Suppose the authority expects the stay to last 2 months rather than two years. A: $1,200,000 times 2 is $2,400,000. B: $900,000 times 2 is $1,800,000, plus the $900,000 setup, which is $2,700,000. Now A is $300,000 cheaper, which follows from the 3-month figure computed earlier, and being ready 8 weeks sooner matters enormously when the whole stay is about 9 weeks -- B would barely have opened before people went home. Nothing about either response changed. The expected length of the stay flipped the verdict, which is why it belongs in the criteria and not in a footnote.`,
      ],
      example: { problem: `Evaluate two responses against the stated criteria, then say what would flip the verdict.

"Twenty thousand people who crossed from Averin into Solvane need somewhere to live, and the regional authority in Solvane is choosing between two responses. The stay is expected to last at least two years. The stated criteria are: how soon shelter is ready, the total cost over the expected stay, the share of school-age children with a school place, and whether adults can earn. The authority has also asked who else bears a cost. 3,000 of the arrivals are school-age.

Response A, a camp on open land 8 kilometers from the border: shelter ready in 3 weeks; $60 per person per month to run; no setup cost; a camp school with places for 1,200 children; no work on the site, and the nearest town is 8 kilometers away; the camp can be closed in a week when people go home.

Response B, rented rooms and repaired empty buildings in five towns within 50 kilometers: shelter ready in 11 weeks; $45 per person per month; a one-time setup cost of $900,000 for deposits, repairs and extra teachers; town schools have places for 2,700 children; the fruit-packing plants in the five towns are short of workers and will hire; rents in the five towns rose 15 percent in the first year."`, solution: `Over the stated two-year stay the criteria support Response B on three of the four, and the file should say which one it loses. Cost: B is $22,500,000 against A at $28,800,000, so B is $6,300,000 less, because $300,000 saved a month pays back the $900,000 setup in 3 months. School places: B seats 2,700 of 3,000 children, which is 90 percent, against A at 1,200, which is 40 percent, so B seats 1,500 more. Earning: the towns have plants that will hire and the camp has no work within 8 kilometers. A wins on speed, by 8 weeks. A cost also falls outside both plans: rents in the five towns rose 15 percent for the households already living there. If the expected stay were 2 months instead, A would cost $2,400,000 against B at $2,700,000 and the verdict would flip.` },
      relatedLoIds: ['m8geo.refugees-and-displacement'],
    },
  ],
  pointers: [
    { content: `Students often say "Everybody who had to leave home because of the fighting is a refugee." — Being forced from home is where the questions start, not where they finish. Of the 40,000 people who left home in eastern Averin, 26,000 never crossed a border: 26,000 divided by 40,000 is 0.65, so 65 percent of them are internally displaced people, still inside Averin and still under its protection; check, 0.65 times 40,000 is 26,000. Of the 12,000 who crossed into Solvane, the ones whose claims are still waiting are counted as asylum seekers, and only the ones whose claims have been decided in their favor are counted as refugees. WRONG: "Forced from home, therefore a refugee." CORRECT: "Forced from home, then ask whether a border was crossed, and if it was, ask whether the claim has been decided." Using one word for all three groups is not just imprecise: it hides the group that never crossed a border, and that group is usually the biggest of the three.`, kind: 'common-error' },
    { content: `Students often say "The camp is the cheaper response, because $60 a person each month beats $45 a person each month plus $900,000." — Put both responses on the same footing, which means a total over the same number of months. Running costs: 20,000 times $60 is $1,200,000 a month for the camp, and 20,000 times $45 is $900,000 a month for the towns, so the towns save $300,000 every month. The setup is $900,000 once, and $900,000 divided by $300,000 a month is 3 months, so the towns response is behind for 3 months and ahead from month 4. Over the stated two years, which is 24 months: the camp is $1,200,000 times 24, or $28,800,000; the towns are $900,000 times 24 plus the $900,000 setup, or $22,500,000; the towns cost $6,300,000 less. WRONG: "$60 beats $45 plus $900,000." CORRECT: "$45 a person plus a one-time $900,000 beats $60 a person from month 4 onward, and by $6,300,000 over two years." If the stay were 2 months instead, the same arithmetic gives the opposite answer: $2,400,000 for the camp against $2,700,000 for the towns.`, kind: 'common-error' },
    { content: `Two questions settle the word, in order. Was an international border crossed? If no, the person is an internally displaced person. If yes, has the claim for protection been decided? Waiting means asylum seeker; decided in the person's favor means refugee.`, kind: 'tip' },
    { content: `Before either question there is a gate: somebody who moved for work or school was not forced from home, so none of the three words applies.`, kind: 'tip' },
    { content: `Distance decides none of it. Six hundred kilometers inside one country is internal displacement; twelve kilometers across a border with a claim filed is an asylum seeker.`, kind: 'tip' },
    { content: `The word names a situation and the rules that come with it, never a kind of person. The same person can be counted in two categories in one year, because a border was crossed or a decision was made.`, kind: 'tip' },
    { content: `Most people forced from home stay inside their own country or in the country next door, and the data shows why: each further step costs more money and asks for another document.`, kind: 'tip' },
    { content: `Take each group as a share of everybody who left home, and check the shares add to 100 percent. A count of one group cannot settle a claim about all of them.`, kind: 'tip' },
    { content: `Evaluate a response against the stated criteria over the stated length of stay. Spread a one-time setup cost across the months instead of charging it every month, say which criterion the winning response loses, and say who else bears a cost.`, kind: 'tip' },
  ],
};
