/**
 * Grade 8 World Geography — Unit 4 CED 4.4: North America: Economic Regions & Trade.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.north-america-economic-regions-and-trade.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U4_NORTH_AMERICA_ECONOMIC_REGIONS_AND_TRADE: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.north-america-economic-regions-and-trade.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 4,
  cedTopic: '4.4',
  cedTitle: 'North America: Economic Regions & Trade',
  planId: 'evelyn.ms.m8geo.north-america-economic-regions-and-trade.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.north-america-economic-regions-and-trade.v1' }],
  theory: [
    { loId: 'm8geo.north-america-economic-regions-and-trade', content: `CLASSIFY THE STEP, NEVER THE REGION AND NEVER THE INDUSTRY. Primary work takes material out of the earth, secondary work makes something out of it, tertiary work moves it or serves the people who use it, and quaternary work handles the information about it -- and the thing you hang one of those four labels on is a STEP. "A wheat region" is not a classification, because growing the wheat is primary, milling it into flour is secondary, hauling the flour is tertiary, and the office that forecasts the harvest is quaternary, and all four of those can sit inside one county. So when a description hands you a region, split it into steps first, then ask of every step the same question: what was the material when this step began, and what is it when the step ends? Nearly every region in North America runs all four levels at once, and a report that hangs a single label on a whole region has skipped the split.` },
    { loId: 'm8geo.north-america-economic-regions-and-trade', content: `EVERY STEP SITS WHERE IT SITS FOR A REASON YOU CAN NAME, AND THE REASON IS EITHER PHYSICAL OR LOCATIONAL. A PHYSICAL factor is something the place itself supplies: deep soil and level land, a long frost-free season, water that can be delivered to it, oil and gas in the rock below, a harbor deep enough for a loaded ship. A LOCATIONAL factor is something that being NEAR supplies: a large market close at hand, cheap water or rail transport, other firms doing related work, a pool of workers already trained for the job. Neither kind outranks the other and both are real explanations. The discipline is to name ONE factor for each step and to say which of the two kinds it is before explaining anything, because everything you do next depends on the kind.` },
    { loId: 'm8geo.north-america-economic-regions-and-trade', content: `THE KIND OF FACTOR TELLS YOU WHETHER THE WORK COULD MOVE, AND THAT IS HOW YOU CHECK THE LABEL. Work pinned by a physical factor cannot leave it: the gas is where the rock put it, and an orchard cannot be carried to a region with a shorter growing season. Work pinned by a locational factor can move, because a second place is able to offer the same nearness -- cheaper transport, a larger market, more trained workers. So run the test on every step you have just labeled: if you called a factor physical and you can still picture the work happening three states away, you named the wrong factor. The sharp cases are the secondary steps, which go sometimes to the material and sometimes to the market, depending on which of the two is more expensive to move.` },
    { loId: 'm8geo.north-america-economic-regions-and-trade', content: `A TRADE TABLE HAS TWO COLUMNS, AND A CLAIM BUILT ON ONE OF THEM IS NOT A CLAIM ABOUT TRADE. Every trading pair has a flow in each direction, and the finding called interdependence is simply that both flows are large: each place is a supplier to the other and a customer of the other at the same time. The United States and Canada are the clearest case on this continent, and the two columns are worth hearing side by side. Crossing from Canada into the United States: crude oil and natural gas, and motor vehicles and vehicle parts. Crossing from the United States into Canada: motor vehicles and vehicle parts again, along with machinery. Read one column and you can write "one country supplies the other". Read both and you find the same product family moving in both directions, which happens only when factories on the two sides of the border are working on parts of the same thing.` },
    { loId: 'm8geo.north-america-economic-regions-and-trade', content: `DEPENDENCE IS A SHARE, NOT A TOTAL, AND THE LARGER SHIPMENT USUALLY BELONGS TO THE LESS DEPENDENT COUNTRY. To say how much a place depends on one partner, divide what it sends to that partner by everything it sends abroad, and set the two shares side by side. A large country spreads its selling across many partners, so even a huge shipment to one neighbor can be a small slice of its total; a smaller neighbor may send almost everything it sells to that one country, so a smaller shipment is nearly all of its total. That is exactly backwards from the way a raw total reads, and reading the total as the dependence is the most common mistake made with a trade table. A share is a measurement of a flow, never a score for a country or for the people in it.` },
    { loId: 'm8geo.north-america-economic-regions-and-trade', content: `READ A REGION'S MIX BACKWARD TO ITS FACTORS, AND STOP THERE. Once every step is labeled and every factor named, the mix says something real: a region full of primary work is a region where the soil, the water or the rock is, and a region full of quaternary work is a region where trained workers and related firms are. That is the whole of what a mix supports. It does not support a ranking. A region of grain fields and gas wells is not behind a region of design studios, and the people in it are not less capable -- the grain and the gas are there, and work follows what is there. Describe the mix, trace it back to the factors, and stop. Never score it, and never score the people.` },
    { loId: 'm8geo.north-america-economic-regions-and-trade', kind: 'definition', title: 'physical factor', content: `a reason a step sits where it does that the place itself supplies -- its soil, water, climate, rock or harbor -- and that the work cannot take with it.` },
    { loId: 'm8geo.north-america-economic-regions-and-trade', kind: 'definition', title: 'locational factor', content: `a reason a step sits where it does that comes from what the place is near: a market, cheap transport, other firms, or a pool of trained workers.` },
    { loId: 'm8geo.north-america-economic-regions-and-trade', kind: 'definition', title: 'activity mix', content: `the split of the work done in a place across the four levels, found by labeling each step separately instead of labeling the place as a whole.` },
    { loId: 'm8geo.north-america-economic-regions-and-trade', kind: 'definition', title: 'trade flow', content: `the value of goods moving in ONE direction between two places over a stated period; a two-way table holds one flow for each direction.` },
    { loId: 'm8geo.north-america-economic-regions-and-trade', kind: 'definition', title: 'export share', content: `the fraction of everything a place sells abroad that goes to one named partner, found by dividing the flow to that partner by that place's total sales abroad.` },
    { loId: 'm8geo.north-america-economic-regions-and-trade', kind: 'definition', title: 'interdependence', content: `what a two-way table shows when both flows are large: each place is at the same time a supplier to the other and a customer of the other.` },
  ],
  methods: [
    {
      title: 'Worked label the steps and name the factors',
      steps: [
        `Interior plains first, and split before labeling. Ask the one question: what was the material when the step began, and what is it when the step ends? Nothing existed before the field and the herd; the land produced the grain and the cattle. That is PRIMARY work. The factor is level land and deep soil with enough rain, all of which the plains themselves supply, so the factor is PHYSICAL. Could the work move? Not off that soil and not out of that rain, so the answer is no.`,
        `Dry valleys in the West. Fruit and vegetables come out of the ground too, so this is also PRIMARY -- but the factor is a different one, and reading it as the same one is the first trap. Very little rain falls on these valleys. What makes the orchards possible is a long frost-free season with a great deal of sun, which the valley does supply, together with water that the valley does not supply and that arrives by canal from mountain snow. Both halves are PHYSICAL, and the work sits exactly where the two halves meet. WRONG: "These valleys are farmed for the same reason the plains are, because rain falls on them." CORRECT: "Very little rain falls on them, so the farming rests on a long growing season plus a water delivery, and taking either one away stops the orchards."`,
        `Oil and gas, and this is where two levels sit side by side pinned by two different kinds of factor. Pumping crude oil and natural gas out of the rock is PRIMARY, and its factor is as PHYSICAL as a factor gets: the oil and gas are where the rock put them, and no decision anybody makes can move them. Now look at the refineries on the Gulf coast. Turning crude oil into fuels is SECONDARY, and the refinery is not sitting on an oil field at all. It is sitting where the pipelines from the fields meet water deep enough for tankers. That is a LOCATIONAL factor: nearness to two different ways of moving the material.`,
        `The Great Lakes region. Building machinery and vehicles is SECONDARY. The factor is LOCATIONAL: two heavy materials, iron ore from ranges to the north and coal from hills to the southeast, had to be brought together, and moving heavy cargo across the lakes was the cheap way to do it, after which the suppliers and the customers were there too. Could the work move? Yes, in principle, and that is exactly why manufacturing regions shift over decades while an oil field never does.`,
        `Large metropolitan areas. Banks, hospitals and universities serve people, which is TERTIARY. Design studios and software firms work on information, which is QUATERNARY. Both have the same LOCATIONAL factor, and it has three parts: a large pool of trained workers, customers close at hand, and other firms doing related work. Could this move? Yes, and it does move, which is why it collects in large metropolitan areas instead of spreading itself evenly across the map.`,
        `Read the labels down the list and say what the pattern is -- and then say what it is not. Every primary step here is pinned by something in the ground, the water or the sky. Every tertiary and quaternary step is pinned by nearness to people. The secondary steps split, one going to where the pipelines meet deep water and one going to where cheap transport brought two heavy materials together. That is a description of factors. It is not a ranking: a region of grain fields and gas wells is not behind a region of software firms, it is a region where the grain and the gas are.`,
        `Rewind the data and read it backwards to confirm every label came from a sentence and not from memory: software firms and banks, vehicle factories on cheap lake transport, refineries at pipelines and deep water, wells on the oil and gas, orchards on sun and delivered water, grain and cattle on deep soil. Now change ONE input, twice, once on each kind of factor. First, suppose the canal deliveries to the dry valleys were cut in half. The sun does not change and the soil does not change, but the water does, and physically pinned work cannot follow a factor it has lost, so the orchards shrink where they stand. Second, suppose moving cargo across the lakes stopped being cheap. The vehicle factories are pinned by nearness rather than by rock, and a second place can offer the same nearness, so the work moves instead of shrinking. One change each way, and the difference between the two kinds of factor turns into the difference between shrinking and moving.`,
      ],
      example: { problem: `Five parts of North America, and the work done in each. For every one, name the level of activity, name the ONE factor that pins the work to that place, say whether that factor is physical or locational, and then run the test: could the work move?

"Interior plains: level land, deep soils and wide fields, with steady rain in the eastern half and grassland further west. Grain is grown and cattle are raised.

Dry valleys in the West: very little rain falls, the growing season is long and sunny with few frosts, and irrigation water arrives by canal from snow melting in the mountains alongside them. Fruit, nuts and vegetables are grown.

Western interior and the Gulf coast: oil and natural gas lie in the rock below. Wells pump them, pipelines carry them, and refineries on the Gulf coast turn crude oil into fuels beside water deep enough for tankers.

The Great Lakes region: factories build machinery and vehicles. Iron ore comes down the lakes from ranges to the north, coal comes up from hills to the southeast, and lake freighters move heavy cargo cheaply.

Large metropolitan areas: banks, hospitals, universities, design studios and software firms."`, solution: `Grain and cattle on the interior plains: primary, pinned by a physical factor (level land, deep soil, enough rain), and it cannot move. Irrigated fruit and vegetables in dry western valleys: primary, pinned by two physical factors that meet there (a long frost-free sunny season, plus water delivered by canal from mountain snow), and it cannot move. Oil and gas in the western interior and along the Gulf: pumping is primary and pinned physically by what is in the rock, while refining on the Gulf coast is secondary and pinned by a locational factor, the meeting of pipelines and deep water. Machinery and vehicles in the Great Lakes region: secondary, pinned by the locational factor of cheap lake transport bringing ore and coal together, and it could move. Services and technology in large metropolitan areas: tertiary and quaternary, pinned by the locational factor of trained workers, nearby customers and related firms, and it moves to wherever those are. Cut the canal water and physically pinned work shrinks in place; raise the cost of lake shipping and work pinned by nearness relocates.` },
      relatedLoIds: ['m8geo.north-america-economic-regions-and-trade'],
    },
    {
      title: 'Worked read the table both ways',
      steps: [
        `Add each direction before comparing anything, because a trade table is read down both columns and never down one. Crossing south: 60 billion dollars plus 15 billion is 75 billion. Crossing north: 70 billion plus 20 billion is 90 billion. Both figures are large and neither is zero, so goods are moving in both directions, and that single fact already breaks the picture of one country supplying another.`,
        `Now read what is inside each column, not only the totals. Vehicle parts cross south and finished vehicles cross north. The same product family is moving both ways, and that happens only when factories on the two sides of the border are working on parts of the same thing. A one-way supply relationship cannot produce that pattern at all.`,
        `Turn each direction into a share of the sending country's own selling, because that is what dependence is. Norvane sells 100 billion abroad in all, and 75 billion of it crosses into Halder: 75 divided by 100 is 0.75, which is 75 percent. Halder sells 600 billion abroad in all, and 90 billion of it crosses into Norvane: 90 divided by 600 is 0.15, which is 15 percent.`,
        `Invert both, because a slipped zero inside a share stays invisible until you multiply back. 0.75 times 100 is 75, which is the southbound total, and 60 plus 15 is 75, so the column adds up as well. 0.15 times 600 is 90, which is the northbound total, and 70 plus 20 is 90. Every figure returns.`,
        `Give the verdict on each half of the claim separately. "Norvane depends on Halder" is supported, and the share says how much: three quarters of everything Norvane sells abroad goes to one neighbor. "Halder barely notices Norvane" is NOT supported. Fifteen percent is a smaller share than 75 percent, but it is 90 billion dollars of sales, which is more than crosses the other way, and Halder would have to find other buyers for all of it. WRONG: "Halder ships the larger load, so Halder is the more dependent of the two." CORRECT: "Halder ships the larger load and carries the smaller share, because a large seller spreads its selling across many partners." And WRONG: "Halder's share is small, so Halder barely notices." CORRECT: "A small share of a large total is still a large amount, and 15 percent of 600 billion is 90 billion."`,
        `The check to remember, and notice that it rests on three clues of three different kinds. The direction totals are one kind: 75 billion south and 90 billion north, both large, so the flow runs both ways. What is inside the columns is a second kind: parts going one way and finished vehicles coming back means a single production chain crosses the border twice. The shares are a third kind: 75 percent against 15 percent, which says the dependence is real on both sides and uneven in size. One number is a hunch; three of different kinds, all pointing the same way, is evidence. The verdict is that the two countries are interdependent, with Norvane carrying the larger share, and that verdict is a measurement of two flows -- never a score for either country or for the people in it.`,
      ],
      example: { problem: `A large southern country, Halder, and its smaller northern neighbor, Norvane, share a long land border, and most people in Norvane live in a band close to it. Here is one year of trade between them.

"Crossing south, from Norvane into Halder: crude oil and natural gas, 60 billion dollars; vehicle parts, 15 billion dollars.

Crossing north, from Halder into Norvane: machinery and finished vehicles, 70 billion dollars; packaged foods and household goods, 20 billion dollars.

Norvane sells 100 billion dollars abroad in total. Halder sells 600 billion dollars abroad in total."

A commentator says: "Norvane depends on Halder, and Halder barely notices Norvane." Test the claim against the table.`, solution: `The claim is half right. Crossing south is 60 plus 15, which is 75 billion dollars, and crossing north is 70 plus 20, which is 90 billion, so both directions are large and the trade is two-way. As a share of its own selling abroad, Norvane sends 75 of 100 billion to Halder, which is 75 percent, while Halder sends 90 of 600 billion to Norvane, which is 15 percent; multiplying each share back by its total returns 75 and 90. So Norvane does depend heavily on Halder, but Halder does not barely notice: 15 percent of a large total is 90 billion dollars of sales, more than crosses the other way, and vehicle parts going south against finished vehicles coming north show one production chain crossing the border in both directions.` },
      relatedLoIds: ['m8geo.north-america-economic-regions-and-trade'],
    },
  ],
  pointers: [
    { content: `Students often say "Region Denby writes software and Region Kesset grows grain and pumps gas, so Denby is more advanced and Kesset needs to catch up." — A mix is evidence about factors and nothing else. Kesset has grain and gas because the soil, the rain and the rock are there, and those are physical factors that no region can decide to have. Denby has software firms because trained workers, clients and other design firms are there, and those are locational factors. Split each region into steps and both regions turn out to run all four levels anyway: Kesset's grain fields are primary, the mill that turns the grain into flour is secondary, the trucks that carry the flour are tertiary, and the office that forecasts the harvest is quaternary. WRONG: "Denby is more advanced, and Kesset needs to catch up." CORRECT: "Kesset's mix follows its soil and its rock, and Denby's follows its workers and its clients, so each mix names the factors that region has and neither names a rank." A mix is described and traced back to its factors. It is never scored, and the people are never scored either.`, kind: 'common-error' },
    { content: `Students often say "Halder ships 90 billion dollars north and Norvane ships 75 billion south, so Halder has more at stake in that border." — Dependence is a share, so each shipment is divided by that country's own total sales abroad. Norvane sells 100 billion dollars abroad in all and 75 billion of it goes to Halder: 75 divided by 100 is 0.75, which is 75 percent. Halder sells 600 billion abroad in all and 90 billion of it goes to Norvane: 90 divided by 600 is 0.15, which is 15 percent. Check both by multiplying back: 0.75 times 100 is 75, and 0.15 times 600 is 90, so both shipments return. WRONG: "Halder ships more, so Halder has more at stake." CORRECT: "Halder ships the larger load and carries the smaller share, 15 percent against 75 percent, because Halder spreads its selling across many partners while Norvane sends three quarters of everything it sells to one neighbor." The 90 billion is still real and still matters, because Halder would have to find other buyers for it, so the finding is that the dependence runs in both directions and is uneven, not that it runs one way.`, kind: 'common-error' },
    { content: `Classify the step, never the region. Growing the grain is primary, milling it is secondary, hauling the flour is tertiary and forecasting the harvest is quaternary, and one region runs all four at once.`, kind: 'tip' },
    { content: `Name one factor for each step and say which kind it is. A physical factor is what the place itself supplies; a locational factor is what being near something supplies.`, kind: 'tip' },
    { content: `Check the label with the could-it-move test. Physically pinned work cannot leave its soil, water or rock; work pinned by nearness goes wherever that nearness is cheaper.`, kind: 'tip' },
    { content: `Primary steps are nearly always pinned physically and quaternary steps nearly always by nearness. The secondary steps are the interesting ones: a refinery goes where the pipelines meet deep water, and a vehicle plant goes where cheap transport and suppliers are.`, kind: 'tip' },
    { content: `Read a trade table down both columns before saying anything. Interdependence is the finding that both flows are large, so each place is a supplier to the other and a customer of the other at the same time.`, kind: 'tip' },
    { content: `Dependence is a share, not a total: divide each country's shipment to its partner by everything that country sells abroad. The larger shipment usually belongs to the less dependent country.`, kind: 'tip' },
    { content: `A mix is evidence about factors and never a rank. A region carries the work its soil, rock, water, workers and neighbors allow, and no region and no group of people is ahead of or behind another.`, kind: 'tip' },
  ],
};
