/**
 * Grade 8 World Geography — Unit 2 CED 2.2: Buffers & Proximity Analysis.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.buffers-and-proximity.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U2_BUFFERS_AND_PROXIMITY: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.buffers-and-proximity.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 2,
  cedTopic: '2.2',
  cedTitle: 'Buffers & Proximity Analysis',
  planId: 'evelyn.ms.m8geo.buffers-and-proximity.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.buffers-and-proximity.v1' }],
  theory: [
    { loId: 'm8geo.buffers-and-proximity', content: `A BUFFER TURNS A DISTANCE RULE INTO A LINE THAT EVERY LOCATION CAN BE TESTED AGAINST. Saying a parcel is near the river decides nothing, because near is an opinion and two people will draw it in two different places. A buffer replaces the opinion with a measurement: the zone made of every point within a stated distance of a chosen feature. Before you test anything, name three things out loud, in this order. One: the FEATURE the distance is measured from, such as the river bank, the school door or the edge of the highway. Two: the DISTANCE the rule states. Three: whether the rule wants what is INSIDE the buffer or what is OUTSIDE it, because a rule that holds building away from a river and a rule that promises a service to nearby homes are built the same way and then want opposite halves. Skip the third one and you can measure everything perfectly and still hand back exactly the wrong list.` },
    { loId: 'm8geo.buffers-and-proximity', content: `THE BUFFER TAKES ITS SHAPE FROM THE FEATURE, AND YOU MEASURE TO THE NEAREST PART OF IT. A buffer around a point, such as a well or a library door, is a circle of that radius around the point. A buffer around a line, such as a river or a rail line, is a band of the same width running along both sides of it, so a 200-meter buffer on a river is a strip 200 meters wide on the north side and 200 meters wide on the south side, 400 meters across in total with the river down the middle. Either way, the distance that counts is the distance straight to the NEAREST part of the feature, and never to a landmark that happens to sit on it: a parcel 120 meters from the bank is 120 meters from the river even when the nearest bridge is half a kilometer away.` },
    { loId: 'm8geo.buffers-and-proximity', content: `SUBTRACT, AND YOU GET THE VERDICT AND THE MARGIN IN ONE MOVE. Set each location's distance beside the buffer distance and take the difference. Under a 200-meter setback a parcel at 150 meters is inside the forbidden strip by 50 meters, and a parcel at 400 meters is clear of it by 200 meters. The verdict is one of two words, inside or outside, and it hides how close the call was; the margin is the number that does not. The margin is exactly how far that location would have to move, or how far the stated distance would have to shift, before the verdict flips. Sort the locations by distance and the margins line them all up in the order they will change.` },
    { loId: 'm8geo.buffers-and-proximity', content: `A LOCATION SITTING EXACTLY ON THE LINE IS DECIDED BY THE WORDING OF THE RULE, NOT BY THE GEOMETRY. The measurement cannot break that tie, because the measurement is what produced it. So read the rule's own words. WITHIN 300 meters includes a location exactly 300 meters away. AT LEAST 200 meters from the bank, and NO CLOSER THAN 200 meters, both allow a building at exactly 200 meters. MORE THAN 200 meters does not. A stated rule almost always contains one of those phrases, and when it does not, the honest answer names the reading you used and says that the case sat on the edge.` },
    { loId: 'm8geo.buffers-and-proximity', content: `CHANGING THE DISTANCE CHANGES THE ANSWER, AND IT CHANGES IT IN ONE DIRECTION ONLY. Widen a buffer and every location already inside it stays inside; the only thing a wider buffer can do is pull in locations that were outside. Narrow it and only the reverse can happen. That is why the list sorted by distance is worth keeping: it is the order in which locations enter the buffer as it grows, so you can say how many are caught at any distance without measuring a single thing again. It also means a coverage figure can be made to look like almost anything by moving the distance, which is the reason the distance has to come from the rule and be said out loud.` },
    { loId: 'm8geo.buffers-and-proximity', content: `WHICH DISTANCE A RULE REQUIRES COMES FROM WHAT THE RULE IS FOR, AND THE RULE ALSO FIXES HOW DISTANCE IS MEASURED. A setback is written to hold something away from a feature, so its distance is the width of the harm it is holding off. A service radius is written to say who is close enough to use something, so its distance is the trip people will really make. Use a wider buffer than the rule states and the served share climbs without one household moving, which is a claim about the buffer and not about the place. One limit belongs here. A buffer measures the straight line, while the distance along the roads -- what a geographer with the right tool would call network distance -- can be far longer, so a household inside the circle is not always inside the walk. When the rule is written in straight-line distance, the straight line is what you measure, and the difference is worth naming and stopping at.` },
    { loId: 'm8geo.buffers-and-proximity', kind: 'definition', title: 'buffer', content: `the zone made of every point within a stated distance of a chosen feature, used as a test that each location either passes or fails.` },
    { loId: 'm8geo.buffers-and-proximity', kind: 'definition', title: 'setback', content: `a rule requiring a minimum distance between a feature and anything built, so the locations it allows are the ones OUTSIDE the buffer.` },
    { loId: 'm8geo.buffers-and-proximity', kind: 'definition', title: 'service radius', content: `a distance stated as the limit of what counts as close enough to use a facility, so the locations it counts are the ones INSIDE the buffer.` },
    { loId: 'm8geo.buffers-and-proximity', kind: 'definition', title: 'margin', content: `the difference between a location's distance and the buffer distance, which is how far that location would have to move for its verdict to flip.` },
    { loId: 'm8geo.buffers-and-proximity', kind: 'definition', title: 'straight-line distance', content: `the distance measured directly to the nearest part of a feature, taking no account of the route anyone would travel to get there.` },
  ],
  methods: [
    {
      title: 'Worked run the setback',
      steps: [
        `Step one: name the feature, the distance and the side the rule wants. The feature is the river bank, and the rule says either bank, so a parcel north of the river and a parcel south of it are tested in exactly the same way. The distance is 200 meters. And the rule wants what is OUTSIDE: the buffer is the forbidden strip, so building is allowed everywhere the strip does not reach. WRONG: "The rule is about the 200-meter strip, so the strip is where the town wants the new buildings." CORRECT: "A setback names the strip that is closed, so the parcels that may be built on are the ones the strip does not cover."`,
        `Step two: give the buffer the shape of the feature. The river is a line, so its buffer is a band 200 meters wide on the north side and 200 meters wide on the south side -- 400 meters across in total, with the river down the middle.`,
        `Step three: set each distance beside 200 and subtract, which gives the verdict and the margin together. Alder: 150 is less than 200, so Alder is inside the forbidden strip, by 200 minus 150, which is 50 meters. Birch: 400 is greater than 200, so Birch is clear of it, by 400 minus 200, which is 200 meters. Cedar: 50 is less than 200, so Cedar is inside, by 200 minus 50, which is 150 meters.`,
        `Step four: rule on the edge from the wording. Dunlin sits at exactly 200 meters, and no amount of measuring can break that tie, because the measuring is what produced it. The rule says no closer than 200 meters, and 200 meters is not closer than 200 meters, so Dunlin is allowed, with a margin of zero. WRONG: "Dunlin is exactly on the line, so it is inside the buffer and cannot be built on." CORRECT: "The wording decides the edge: no closer than 200 allows a building at exactly 200, so Dunlin is allowed, by the narrowest margin there is."`,
        `Step five: invert the test to check it. Take the two blocked parcels and add each margin back: 150 plus 50 is 200, and 50 plus 150 is 200, so each one lands exactly on the rule after moving by its own margin. Take the two allowed parcels and subtract: 400 minus 200 is 200 meters of clearance, and 200 minus 200 is zero. Two blocked and two allowed is four parcels, which is every parcel on the list and none of them twice.`,
        `Rewind the data and read it backwards: Dunlin 200 south, Cedar 50 south, Birch 400 north, Alder 150 north. Sorted by distance the parcels run Cedar 50, Alder 150, Dunlin 200, Birch 400, and the two blocked ones are simply the first two in that order. The verdict follows from the list of distances, not from which side of the river a parcel sits on.`,
        `Now change ONE input and run it again, so the answer is not memorized as a fact about these four parcels. The council widens the setback to 250 meters and changes nothing else. Cedar at 50 and Alder at 150 were already inside and stay inside. Dunlin at 200 is now less than 250, so Dunlin flips from allowed to blocked, by 250 minus 200, which is 50 meters. Birch at 400 is still clear, now by 150. Three blocked and one allowed, and 3 plus 1 is 4. Notice what could NOT happen: no parcel came out of the strip. A wider buffer only ever pulls locations in, and the one it pulled in first was the one with the smallest margin.`,
      ],
      example: { problem: `Run the buffer test straight through on a town rule.

The Wrenford river runs east to west across the town. The council has a new rule: no new building may stand closer than 200 meters to either bank. Four parcels are up for building. "Alder: 150 meters north of the bank. Birch: 400 meters north. Cedar: 50 meters south. Dunlin: 200 meters south." Which parcels may be built on?`, solution: `Birch and Dunlin may be built on; Alder and Cedar may not. The buffer is a band 200 meters wide on each side of the river. Alder at 150 meters is inside it by 50 meters and Cedar at 50 meters is inside it by 150 meters, so both are blocked. Birch at 400 meters is clear by 200 meters. Dunlin sits at exactly 200 meters, and the rule says no closer than 200, so Dunlin is allowed with a margin of zero. Widening the setback to 250 meters flips Dunlin and nothing else, leaving three blocked and one allowed, because a wider buffer can only pull locations in.` },
      relatedLoIds: ['m8geo.buffers-and-proximity'],
    },
    {
      title: 'Worked repair the service radius',
      steps: [
        `Check the arithmetic first, because a wrong verdict is not always a wrong measurement. Add the households: 400 plus 250 is 650, plus 150 is 800, plus 200 is 1,000. The town holds 1,000 households. And the student is right that every neighborhood lies within 1,200 meters, since the farthest is exactly 1,200. The slip is not in the adding and it is not in the comparing.`,
        `Go back to step one of the routine, which the student skipped: the distance has to come from the rule being applied. The rule here is the library standard, and it is written as a 10-minute walk, which the handbook sets at 800 meters. The 1,200 meters belongs to a different rule about a different feature, because a bus stop is not a library. Borrowing it does not serve one extra household; it only makes the buffer bigger.`,
        `Re-run the test at 800 meters. Fern Row: 600 is less than 800, so it is served, with 200 meters to spare. Granby: exactly 800, and the standard says within a 10-minute walk, so 800 meters is within 800 meters and Granby is served, with a margin of zero. Ivens: 950 is greater than 800, so it is not served, and it misses by 950 minus 800, which is 150 meters. Holloway: 1,200 is greater than 800, so it is not served, and it misses by 400 meters.`,
        `Now the second slip: count the thing the rule is about. The standard is about HOUSEHOLDS, not about neighborhoods. Two of the four neighborhoods are served, which is 50 percent of the neighborhoods, but the two served ones are not average-sized: Fern Row is the largest of the four and Ivens is the smallest. Served households are 400 plus 250, which is 650, out of 1,000. WRONG: "Two neighborhoods out of four are served, so the library reaches half the town." CORRECT: "650 households out of 1,000 are within 800 meters, which is 65 percent, and that is higher than the neighborhood count suggests because the two served neighborhoods are the larger ones."`,
        `Invert to check. 65 percent of 1,000 is 650, which is the served count back again. The unserved are 150 plus 200, which is 350, and 350 out of 1,000 is 35 percent. 650 plus 350 is 1,000, and 65 plus 35 is 100, so every household is counted exactly once.`,
        `Rewind the data backwards and confirm nothing was misread: Holloway 1,200 meters and 200 households, Ivens 950 and 150, Granby 800 and 250, Fern Row 600 and 400. Sorted by distance the neighborhoods run Fern Row 600, Granby 800, Ivens 950, Holloway 1,200, so Ivens is the next one any wider buffer would reach.`,
        `Now change ONE input and run it again. Suppose the council counted a 12-minute walk instead of a 10-minute walk. The handbook's own pace is 800 meters in 10 minutes, which is 800 divided by 10, or 80 meters a minute, so 12 minutes is 80 times 12, which is 960 meters; check it the other way round, 960 divided by 80 is 12 minutes. At 960 meters Ivens at 950 comes inside, by 10 meters, and Holloway at 1,200 stays outside. Served households are 650 plus 150, which is 800, and 800 out of 1,000 is 80 percent; 800 plus 200 is 1,000. One decision about a walking time moved the coverage figure from 65 percent to 80 percent while nobody moved house. That is why the distance is read off the rule and stated out loud: the distance is the part a person chose.`,
        `One limit to say before leaving this. Every distance here is straight-line distance, because that is how the handbook wrote the standard. The walk along the streets can be longer -- a river with one bridge, a rail line with one crossing -- so a household 800 meters away in a straight line is not always a 10-minute walk away. Measuring along the roads instead is a different tool with a name of its own, network distance, and it answers a different question. The rule in front of you was written in straight lines, so straight lines are what you measure.`,
      ],
      example: { problem: `A student applied a buffer with the wrong distance and then counted the wrong thing. Find both slips, repair them, and give the corrected figure.

Oakmere has one library. The council's planning handbook counts a 10-minute walk as 800 meters of straight-line distance, and the council's standard is that a household is SERVED by the library if it is within a 10-minute walk. The town has four neighborhoods. "Fern Row: 600 meters from the library, 400 households. Granby: 800 meters, 250 households. Ivens: 950 meters, 150 households. Holloway: 1,200 meters, 200 households."

The student wrote: "Our bus rule counts a household as reachable if it is within 1,200 meters of a stop, so I used 1,200 meters. Every neighborhood is inside that, so the library serves all four neighborhoods, which is 100 percent of the town."`, solution: `The student used the wrong distance and then counted the wrong thing. The library standard is a 10-minute walk, which the handbook sets at 800 meters, not the 1,200 meters of the bus rule. At 800 meters, Fern Row at 600 meters and Granby at exactly 800 are served, while Ivens at 950 misses by 150 meters and Holloway at 1,200 misses by 400. The standard counts households, not neighborhoods: 400 plus 250 is 650 of 1,000 households, which is 65 percent -- not the 100 percent the student reported, and not the 50 percent that counting neighborhoods would give. If the council counted a 12-minute walk, which at 80 meters a minute is 960 meters, Ivens would come inside and the figure would be 80 percent.` },
      relatedLoIds: ['m8geo.buffers-and-proximity'],
    },
  ],
  pointers: [
    { content: `Students often say "The Quarry Lane parcel is more than 500 meters from the footbridge, so a 200-meter setback does not touch it." — A buffer uses the distance to the NEAREST part of the feature. The Quarry Lane parcel lies 120 meters north of the bank and 500 meters east along the creek from the footbridge, so it is indeed more than 500 meters from the bridge and it is 120 meters from the creek. The setback is tested against the second figure: 120 is less than 200, so the parcel is inside the forbidden strip, by 200 minus 120, which is 80 meters; check it by adding the margin back, since 120 plus 80 is 200, exactly the rule. WRONG: "More than 500 meters from the bridge, so the setback does not touch it." CORRECT: "120 meters from the nearest bank, so the setback blocks it by 80 meters." The landmark you can name on a line feature is never the thing you measure to.`, kind: 'common-error' },
    { content: `Students often say "The parcels within 200 meters of the river are the ones the town is opening up for building." — The wording settles it. "No building within 200 meters of the river" closes that strip; it does not open it. The buffer is the forbidden zone, so the parcels that may be built on are the ones the buffer does not cover: a parcel at 150 meters is inside the strip by 50 meters and is blocked, while a parcel at 400 meters is outside it by 200 meters and is allowed. WRONG: "Within 200 meters of the river is where building is allowed." CORRECT: "Within 200 meters of the river is where building is forbidden, and the allowed parcels are the ones further out than that." The very same 200-meter band, written instead as a service radius -- every home within 200 meters of a new playground, say -- would pick out the opposite list, and nothing in the geometry tells you which; only the rule does.`, kind: 'common-error' },
    { content: `Name three things before testing anything: the feature the distance is measured from, the distance the rule states, and whether the rule wants what is inside the buffer or what is outside it.`, kind: 'tip' },
    { content: `The buffer takes its shape from the feature -- a circle around a point, a band of equal width along both sides of a line -- and the distance that counts is the distance to the nearest part of the feature, never to a landmark sitting on it.`, kind: 'tip' },
    { content: `Subtract, and you get the verdict and the margin in one move. The margin is how far a location would have to move before its verdict flips.`, kind: 'tip' },
    { content: `A location exactly on the line is decided by the rule's wording: within 300 meters includes 300; no closer than 200 meters allows exactly 200; more than 200 meters does not.`, kind: 'tip' },
    { content: `Widening a buffer can only pull locations in, and narrowing it can only let them out. Sorted by distance, the locations are already in the order they will flip.`, kind: 'tip' },
    { content: `A setback wants the outside and a service radius wants the inside, and the distance each requires comes from what the rule is for. Widen the buffer and a coverage figure climbs without one household moving.`, kind: 'tip' },
    { content: `A buffer measures the straight line. The trip along the roads can be much longer, so a location inside the circle is not always inside the walk.`, kind: 'tip' },
  ],
};
