/**
 * Grade 8 World Geography — Unit 5 CED 5.1: Population Pyramids & Dependency.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.population-pyramids-and-dependency.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U5_POPULATION_PYRAMIDS_AND_DEPENDENCY: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.population-pyramids-and-dependency.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 5,
  cedTopic: '5.1',
  cedTitle: 'Population Pyramids & Dependency',
  planId: 'evelyn.ms.m8geo.population-pyramids-and-dependency.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.population-pyramids-and-dependency.v1' }],
  theory: [
    { loId: 'm8geo.population-pyramids-and-dependency', content: `THE DENOMINATOR IS THE WORKING-AGE BAND, NEVER THE WHOLE POPULATION. An age structure sorts a population into three bands -- under 15, 15 to 64, and 65 or older -- so the dependency ratio has one fixed recipe: add the two outer bands, divide by the middle band, multiply by 100, and read the answer as dependents for every 100 working-age people. The step that goes wrong most often is the division. Dividing by the whole population instead gives the SHARE of the population that falls outside the two age lines, which is a true figure answering a different question, and it is always the smaller of the two, because the working-age band is smaller than the whole population whenever anybody is a dependent. One country, two numbers, and they are not interchangeable: half dependents and half working-age is 50 percent dependent as a share, and 100 dependents per 100 working-age people as a ratio. And DEPENDENT here is a bookkeeping label set by two age lines and nothing else. It does not say that nobody under 15 or over 64 works, it does not say that anybody is a burden, and the ratio measures a structure, never the people standing inside it.` },
    { loId: 'm8geo.population-pyramids-and-dependency', content: `THE ROUTINE, IN ORDER. One: check that the three bands add to 100, because a structure that does not add to 100 has a band missing or a digit wrong, and every later step inherits the error. Two: add the under-15 band and the 65-and-over band to get the numerator. Three: divide that by the working-age band and multiply by 100. Four: invert, twice. Multiply the ratio by the working-age band and divide by 100, and the dependent total has to come back; then add the dependent total to the working-age band, and 100 has to come back. If either check fails, the division went the wrong way round or a band was dropped on the way in.` },
    { loId: 'm8geo.population-pyramids-and-dependency', content: `NAME THE SHAPE FROM THE TWO OUTER BANDS, NOT FROM THE MIDDLE ONE. The shape is a one-word summary of WHERE the numerator sits, and you assign it by setting the two dependent bands against each other. If one of them is at least twice the size of the other, the structure takes its name from the bigger one: WIDE-BASED when that is the under-15 band, TOP-HEAVY when it is the 65-and-over band. When the two outer bands are closer together than that, the structure is COLUMN-SHAPED -- 25 under 15, 50 working-age and 25 aged 65 or older is a column, because its two outer bands are the same size. Now notice what the shape is not. The shape compares the outer bands with each other; the ratio compares them with the middle band. So the shape does not fix the ratio and the ratio does not fix the shape, and you will see both halves of that in this lesson: a structure whose shape stays put while its ratio moves by 50, and a pair of structures with the same ratio and opposite shapes.` },
    { loId: 'm8geo.population-pyramids-and-dependency', content: `A RATIO OF 100 MADE OF CHILDREN AND A RATIO OF 100 MADE OF OLDER ADULTS ARE NOT THE SAME SITUATION, SO SPLIT THE NUMERATOR. Run the same division twice more: once with only the under-15 band on top, which gives the YOUTH part, and once with only the 65-and-over band on top, which gives the OLD-AGE part. The two parts add back to the whole ratio, which is also a check on your arithmetic. A country at 45 under 15, 50 working-age and 5 aged 65 or older splits into 90 and 10. A country at 15 under 15, 50 working-age and 35 aged 65 or older splits into 30 and 70. Both of them report 100 dependents per 100 working-age people, and the two of them need opposite things built. The ratio tells you HOW MUCH; the split tells you WHAT OF; and a report that hands you only the ratio has handed you half of it.` },
    { loId: 'm8geo.population-pyramids-and-dependency', content: `MOVING ONE BAND MOVES BOTH SIDES OF THE RATIO AT ONCE, WHICH IS WHY IT JUMPS. The three bands have to add to 100, so no band can grow without another one shrinking, and that is not a technicality -- it is the reason this figure moves so fast. Take ten of every 100 people out of the working-age band and put them in the 65-and-over band: the numerator gains ten and the denominator loses ten at the same moment, so 50 over 50 becomes 60 over 40, and the ratio goes from 100 to 150. Ten points of structure, fifty points of ratio. Hold on to that before you read anyone describing a ten-point shift as a small one.` },
    { loId: 'm8geo.population-pyramids-and-dependency', content: `TO SAY WHAT A PLACE MUST PROVIDE IN TEN YEARS, FIND THE PEOPLE WHO CROSS A LINE IN TEN YEARS. The under-15 band does not arrive all at once. Only the people who are already 5 or older today are 15 or older ten years from now, so it is the 5-to-14 slice, not the whole band, that has to be met with work or training places within ten years, while the under-5 slice is still in a classroom at the end of that decade. Read the other end the same way: the 65-and-over band is the care, the clinics and the pensions that have to be ready now, not later. One warning that keeps this honest. Naming who crosses a line is a statement about which way the pressure runs; it is not a forecast of what the ratio will be, because births, deaths and moves all change the bands, and this routine assumes none of them.` },
    { loId: 'm8geo.population-pyramids-and-dependency', kind: 'definition', title: 'dependency ratio', content: `the under-15 band plus the 65-and-over band, divided by the working-age band and multiplied by 100, read as the number of dependents for every 100 working-age people.` },
    { loId: 'm8geo.population-pyramids-and-dependency', kind: 'definition', title: 'working-age band', content: `the share of a population between the two age lines the ratio uses, 15 and 64, which serves as the denominator of the ratio and as nothing else.` },
    { loId: 'm8geo.population-pyramids-and-dependency', kind: 'definition', title: 'dependent bands', content: `the two bands outside those age lines, under 15 and 65 or older, added together to form the numerator, whatever anybody in them actually does.` },
    { loId: 'm8geo.population-pyramids-and-dependency', kind: 'definition', title: 'youth part of the ratio', content: `the same division run with only the under-15 band on top, which says how much of the ratio comes from children.` },
    { loId: 'm8geo.population-pyramids-and-dependency', kind: 'definition', title: 'old-age part of the ratio', content: `the same division run with only the 65-and-over band on top, which adds to the youth part to give the whole ratio back.` },
    { loId: 'm8geo.population-pyramids-and-dependency', kind: 'definition', title: 'column-shaped', content: `an age structure whose two outer bands are close enough in size that neither is twice the other, so the structure is named after neither end.` },
  ],
  methods: [
    {
      title: 'Worked run the routine',
      steps: [
        `Step one: check the bands. 45 plus 50 plus 5 is 100. Nothing is missing, so the structure can be worked. Check the slice too: 30 plus 15 is 45, which is the whole under-15 band.`,
        `Step two: build the numerator. The dependent bands are the under-15 band and the 65-and-over band: 45 plus 5 is 50 dependents for every 100 people.`,
        `Step three: divide by the working-age band and scale. 50 divided by 50 is 1, and 1 times 100 is 100. Tolmarch has 100 dependents for every 100 working-age people. WRONG: "50 dependents out of 100 people, so the ratio is 50 per 100." CORRECT: "50 dependents divided by the 50 people in the working-age band is 100 per 100 -- dividing by the whole population answers a different question, which is what share of the country falls outside the two age lines, and that share is 50 percent."`,
        `Step four: invert, twice. 100 times 50 divided by 100 is 50, which is the dependent total back again. And 50 dependents plus 50 working-age is 100, which is the whole structure back again. The arithmetic closes.`,
        `Now split the numerator, because 100 on its own does not say what to build. Youth part: 45 divided by 50 is 0.9, and 0.9 times 100 is 90. Old-age part: 5 divided by 50 is 0.1, and 0.1 times 100 is 10. Check the split: 90 plus 10 is 100, which is the whole ratio. Ninety of Tolmarch's 100 points of dependency are children.`,
        `Name the shape from the two outer bands. The under-15 band is 45 and the 65-and-over band is 5, and 45 is nine times 5, which is far past twice, so the structure is WIDE-BASED. The middle band played no part in that decision.`,
        `Say what has to be ready in ten years, and use the slice rather than the band. The 45 under 15 are in classrooms now, so classrooms and teachers are the present bill. Within ten years the 30 people per 100 who are aged 5 to 14 today will be 15 to 24, so Tolmarch needs work or training places for 30 of every 100 people it has today, on top of the 50 already in the working-age band. The 15 per 100 who are under 5 are still in school at the end of that decade. This says which way the pressure runs and does not forecast the ratio itself, because births, deaths and moves all change the bands and this routine assumes none of them.`,
        `Rewind the input and read it backwards to confirm the verdict follows from the data. Nine times as many children as older adults, a dependent group that is exactly as large as the working-age group, and two-thirds of that dependent group already old enough to cross the working-age line within the decade. Wide-based, 100 per 100, and a jobs-and-training bill arriving in ten years. Every piece of that came off the three percentages.`,
        `Now change ONE band and run it again. In an age structure the bands must add to 100, so moving one band moves another: take ten of every 100 people out of the working-age band and put them in the 65-and-over band, giving 45 under 15, 40 working-age and 15 aged 65 or older. Check: 45 plus 40 plus 15 is 100. Numerator: 45 plus 15 is 60. 60 divided by 40 is 1.5, and 1.5 times 100 is 150. Invert: 150 times 40 divided by 100 is 60, and 60 plus 40 is 100. The ratio moved from 100 to 150 on a ten-point change, because the ten points left the denominator and joined the numerator in the same move. And the shape did not move at all: 45 is three times 15, so the structure is still wide-based. Same shape, a ratio 50 points higher -- the shape and the ratio are answering different questions.`,
      ],
      example: { problem: `Run the routine straight through, name the shape, and say what the place has to have ready in ten years.

"Tolmarch: of every 100 people, 45 are under 15, 50 are 15 to 64, and 5 are 65 or older. Of the 45 who are under 15, 30 are aged 5 to 14 and 15 are under 5."`, solution: `Tolmarch has 100 dependents for every 100 working-age people: 45 plus 5 is 50 dependents, and 50 divided by 50 times 100 is 100. The inversions close, since 100 times 50 divided by 100 is 50 and 50 plus 50 is 100. The split is 90 youth and 10 old-age, which add back to 100, so the dependency is almost entirely children, and the two outer bands, 45 against 5, make the structure wide-based. Tolmarch needs classrooms now and work or training places within ten years for the 30 people per 100 who are aged 5 to 14 today. Moving ten points from the working-age band into the 65-and-over band leaves the shape wide-based but takes the ratio from 100 to 150, because those ten points leave the denominator and join the numerator at once.` },
      relatedLoIds: ['m8geo.population-pyramids-and-dependency'],
    },
    {
      title: 'Worked repair and split',
      steps: [
        `Check the bands before anything else. 15 plus 50 plus 35 is 100, and the slice checks too, since 10 plus 5 is 15. The data is sound, so the slip is in the handling.`,
        `Check the numerator. 15 plus 35 is 50, and that part is right: the student added the two outer bands correctly.`,
        `Find the slip in the denominator. The student divided 50 by 100, the whole population. The ratio is dependents for every 100 WORKING-AGE people, so the denominator is the middle band: 50 divided by 50 is 1, and 1 times 100 is 100 dependents per 100 working-age people. WRONG: "50 dependents out of 100 people, so the ratio is 50 per 100." CORRECT: "50 dependents divided by the 50 working-age people is a ratio of 100 per 100; 50 out of the whole 100 is the dependent SHARE, which is 50 percent."`,
        `Say what the student's number actually was, because it was not nonsense. Fifty percent is the share of Havren that falls outside the two age lines, and it is true. It just cannot be compared with a figure that was divided by something else. That is the whole reason the wrong denominator is dangerous here: it does not produce an absurd number, it produces a believable one.`,
        `Invert to confirm the repair. 100 times 50 divided by 100 is 50 dependents, and 50 plus 50 is 100. Both checks return, so the repaired ratio is right.`,
        `Now test the conclusion, which was the bigger error. Havren is 100 per 100 and Tolmarch is 100 per 100. The ratios are not double and half -- they are identical. So split both. Havren youth part: 15 divided by 50 is 0.3, times 100 is 30. Havren old-age part: 35 divided by 50 is 0.7, times 100 is 70. Check: 30 plus 70 is 100. Tolmarch split 90 youth and 10 old-age. Same total, mirrored insides.`,
        `Name each shape from the two outer bands. Havren: 35 against 15, and 35 is more than twice 15, so Havren is TOP-HEAVY. Tolmarch: 45 against 5, so Tolmarch is wide-based. WRONG: "Equal ratios mean the same building program, just scaled." CORRECT: "Equal ratios, opposite shapes: 70 of Havren's 100 points are people aged 65 or older, and 90 of Tolmarch's 100 points are children, so one country is building clinics, home care and pension capacity while the other is building classrooms."`,
        `Finish with the ten-year line for Havren, from the slice. Ten people per 100 are aged 5 to 14 today, so 10 per 100 cross into the working-age band within ten years, against 30 per 100 in Tolmarch. Havren is not about to be handed a wave of new workers, and its 35 per 100 aged 65 or older are the provision it has to have ready now. Again, which way the pressure runs -- not a forecast of the ratio.`,
        `Change ONE thing and run it again, and this time change the insides rather than the total. Suppose Havren's two outer bands were swapped: 35 under 15, 50 working-age, 15 aged 65 or older. Check: 35 plus 50 plus 15 is 100. Numerator: 35 plus 15 is 50. 50 divided by 50 times 100 is 100 -- the ratio did not move at all. But the split is now 70 youth and 30 old-age, which still adds to 100, and 35 is more than twice 15, so the shape has flipped to wide-based. In worked example 1 the shape held still while the ratio jumped 50 points; here the ratio holds still while the shape flips. Neither one is a substitute for the other, which is why the routine reports all three: the ratio, the split and the shape.`,
      ],
      example: { problem: `A student ran the routine on a second country and then drew a conclusion from the two ratios. Find the slip, repair it, say what the wrong number was actually measuring, and test the conclusion.

"Havren: of every 100 people, 15 are under 15, 50 are 15 to 64, and 35 are 65 or older. Of the 15 who are under 15, 10 are aged 5 to 14 and 5 are under 5."

The student wrote: "Havren has 15 plus 35, which is 50 dependents out of 100 people, so the ratio is 50 per 100. Tolmarch came out at 100 per 100. Tolmarch therefore carries twice the load, and the two countries need the same kind of building program, only Tolmarch needs more of it."`, solution: `The numerator was right and the denominator was wrong. Dependents are divided by the working-age band, not by the whole population: 50 divided by 50 times 100 is 100 dependents per 100 working-age people, and the inversions close, since 100 times 50 divided by 100 is 50 and 50 plus 50 is 100. The student's 50 was the dependent share, 50 percent, which is true and answers a different question. The conclusion fails too: Havren and Tolmarch both come out at 100, so neither carries twice the other. Splitting them shows why they still need opposite things -- Havren is 30 youth and 70 old-age and its two outer bands, 35 against 15, make it top-heavy, while Tolmarch is 90 youth and 10 old-age and wide-based. Only 10 people per 100 cross into Havren's working-age band within ten years, against 30 in Tolmarch. Swapping Havren's outer bands leaves the ratio at 100 and flips the shape to wide-based.` },
      relatedLoIds: ['m8geo.population-pyramids-and-dependency'],
    },
  ],
  pointers: [
    { content: `Students often say "The dependency ratio is the percentage of a country that does not work, so both countries are at 50." — Take the arithmetic first. In both countries the dependent bands add to 50 of every 100 people -- 45 plus 5 in Tolmarch, 15 plus 35 in Havren -- and the working-age band is 50. Dividing by the whole population gives 50 divided by 100, which is 0.50, the SHARE outside the two age lines, 50 percent. The ratio divides by the working-age band: 50 divided by 50 is 1, and 1 times 100 is 100 dependents for every 100 working-age people. Check: 100 times 50 divided by 100 is 50, and 50 plus 50 is 100. WRONG: "The ratio is 50." CORRECT: "The share is 50 percent and the ratio is 100 per 100, from the same two numbers, because they divide by different things." Then the wording. The bands are drawn at age 15 and age 65, and the ratio never asks whether anybody has a job. Plenty of people over 64 work and plenty of people in the working-age band do not; the ratio is a measurement of a structure, and it is not a statement about any person in it.`, kind: 'common-error' },
    { content: `Students often say "Once two countries match on the ratio, there is nothing left in the age structure to tell them apart." — Split the ratio and the difference reappears at once. Tolmarch youth part: 45 divided by 50 is 0.9, times 100 is 90. Tolmarch old-age part: 5 divided by 50 is 0.1, times 100 is 10. Check: 90 plus 10 is 100. Havren youth part: 15 divided by 50 is 0.3, times 100 is 30. Havren old-age part: 35 divided by 50 is 0.7, times 100 is 70. Check: 30 plus 70 is 100. Both countries report 100, and 90 of Tolmarch's points are children while 70 of Havren's are people aged 65 or older. The shapes say it too, from the two outer bands: 45 against 5 is wide-based, and 35 against 15 is top-heavy. WRONG: "Equal ratios, equal situations." CORRECT: "Equal ratios, opposite insides -- one country has to build classrooms and then work and training places, and the other has to build clinics, home care and pension capacity."`, kind: 'common-error' },
    { content: `The dependency ratio divides the two outer bands by the WORKING-AGE band and multiplies by 100. Dividing by the whole population instead gives the dependent share, which is a different, smaller and true figure answering a different question.`, kind: 'tip' },
    { content: `Run the checks every time: the three bands add to 100, the ratio times the working-age band divided by 100 gives the dependent total back, and the dependent total plus the working-age band gives 100 back.`, kind: 'tip' },
    { content: `Split the ratio into its youth part and its old-age part by running the same division with one outer band on top at a time. The two parts add back to the whole ratio, and they are what tells you which things to build.`, kind: 'tip' },
    { content: `Assign the shape from the two outer bands only: wide-based when the under-15 band is at least twice the 65-and-over band, top-heavy when it is the other way round, column-shaped when neither is twice the other.`, kind: 'tip' },
    { content: `Shape and ratio are answering different questions. A structure can keep its shape while its ratio moves 50 points, and two structures can share a ratio and have opposite shapes.`, kind: 'tip' },
    { content: `Because the three bands must add to 100, moving ten points out of the working-age band adds ten to the numerator and takes ten off the denominator at once, which is why 50 over 50 becomes 60 over 40 and the ratio jumps from 100 to 150.`, kind: 'tip' },
    { content: `For a ten-year question, use the slice that crosses the line: only the people already aged 5 to 14 today are in the working-age band within ten years. That says which way the pressure runs; it is not a forecast of the ratio, because births, deaths and moves all change the bands.`, kind: 'tip' },
    { content: `Dependency is a measurement of a structure, never a score for a place or for the people in it. The age lines are bookkeeping, not a claim about who works.`, kind: 'tip' },
    { content: `**Always divide by the working-age band (15–64), never the whole population.** Dividing by 100 gives the dependent *share* (50%), not the ratio (100 per 100). They are different answers to different questions—the ratio is what you need.`, kind: 'common-error' },
    { content: `Check your arithmetic three times: (1) bands add to 100, (2) ratio × working-age ÷ 100 = dependents, (3) dependents + working-age = 100. If any check fails, you divided the wrong way or lost a band.`, kind: 'tip' },
    { content: `Don't use the ratio alone to predict what a place needs. Always split it into youth part and old-age part. Two countries with ratio 100 might need classrooms for one and clinics for the other.`, kind: 'gotcha' },
    { content: `Name the shape from the two *outer* bands only (under-15 vs. 65+), not from the working-age band. If neither is twice the other, the shape is column-shaped, not determined by the middle.`, kind: 'vocab-note' },
    { content: `Moving 10 points from the working-age band into another band makes the ratio jump 50 points, not 10. The 10 points leave the denominator and *join* the numerator at once.`, kind: 'edge-case' },
    { content: `For a ten-year question, use the slice (e.g., aged 5–14 today), not the whole band (under-15). Only people already aged 5–14 cross into the working-age band in ten years; those under 5 are still in school.`, kind: 'common-error' },
    { content: `Don't confuse 'dependent' (a person in the under-15 or 65+ band, by definition) with 'doesn't work' or 'is a burden.' The age lines are bookkeeping. The ratio measures structure, never judges people.`, kind: 'vocab-note' },
    { content: `Same ratio, different shapes = opposite needs. Same shape, different ratios = same direction but different scale. Shape and ratio answer *different* questions; always report both.`, kind: 'gotcha' },
  ],
};
