/**
 * Grade 8 World Geography — Unit 9 CED 9.1: Analyzing a Boundary Dispute.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.analyzing-a-boundary-dispute.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U9_ANALYZING_A_BOUNDARY_DISPUTE: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.analyzing-a-boundary-dispute.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 9,
  cedTopic: '9.1',
  cedTitle: 'Analyzing a Boundary Dispute',
  planId: 'evelyn.ms.m8geo.analyzing-a-boundary-dispute.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.analyzing-a-boundary-dispute.v1' }],
  theory: [
    { loId: 'm8geo.analyzing-a-boundary-dispute', content: `EVERY CASE IS A RECORD, AND EACH PREDICTABLE CAUSE LEAVES A DIFFERENT MARK ON IT. Boundary disagreements come from a small set of causes that keep repeating, so analyzing a case is not guesswork -- it is matching the record against the mark each cause leaves behind. A pair of DATED surveys that disagree about where a physical feature sits is the mark of a feature that has moved. Two documents of different dates, each one quoted by a different side, is the mark of two accounts of what was agreed. A line both sides accept, plus people cut off from the school, clinic or market they actually use, is the mark of a line drawn without regard to the people living there. A boundary nobody complained about for decades, until the year something valuable was mapped under it, is the mark of a resource sitting across the line. You do not pick the cause that sounds most likely. You pick the one whose mark the record actually carries.` },
    { loId: 'm8geo.analyzing-a-boundary-dispute', content: `RULE CAUSES OUT ONE AT A TIME, AND NAME THE PIECE OF EVIDENCE THAT DID IT. Three questions do most of the work, and each one eliminates rather than confirms. One: do both sides quote the same document and read its words the same way? If they do, two different accounts is out. Two: does a survey both sides signed find the markers and the feature where the record places them? If it does, a feature that moved is out, and so is any question about where the line runs. Three: what changed just before the argument started, and who is affected by the line today? That question separates the last two causes, because a resource case turns on a thing both sides want and a drawn-without-regard case turns on people whose daily journeys the line cuts. A cause you can support only by saying it sounds likely has not been supported, and an analysis that names a cause without naming the evidence that ruled the other three out is not an analysis yet.` },
    { loId: 'm8geo.analyzing-a-boundary-dispute', content: `SORT THE LINE BY WHAT IT FOLLOWS, THEN USE THE TYPE AS AN INSTRUCTION RATHER THAN A CONCLUSION. A boundary is sorted the usual way, by whether the line follows a landform, a straight surveyed line, or a difference between people -- and the answer tells you which evidence to go and collect. If the line follows a landform, go and get two DATED surveys of that landform, because a feature that can move is the one that leaves a dated trail. If the line is a straight surveyed line, go and get the settlement and service data on both sides, because a straight line is the one that can cut a community in half while nothing on the ground changes at all. Sorting the type is not the finding. It is the instruction that tells you where to look first, and a case where the type points you at evidence the record does not contain is a case you have not finished collecting.` },
    { loId: 'm8geo.analyzing-a-boundary-dispute', content: `THE MECHANISM FOLLOWS FROM WHAT IS OPEN RIGHT NOW, NOT FROM WHAT STARTED THE ARGUMENT. Before choosing anything, say in one sentence what is actually open, and it will be one of four things. If the wording is agreed and only a position on the ground is unknown, what is open is a MEASUREMENT, and a joint survey commission -- a standing team with members from both countries -- finds that position and marks it. If the wording never covered the situation at all, what is open is a MISSING RULE, and no amount of measuring or deciding creates one: only a new agreement that both countries negotiate and sign can add it. If the wording exists but points two ways and both countries want one binding answer, what is open is a MEANING, and arbitration puts that single question to a decider the two sides choose together, on terms they set, having agreed in advance to accept the answer. And if both countries have already accepted a standing court, a question about which existing rule applies can go there instead. Hold the difference between the last two: in arbitration the two sides build the decider and write the terms for this one question, while a court is already in place, with its judges and its rules, before the disagreement arises.` },
    { loId: 'm8geo.analyzing-a-boundary-dispute', content: `MEASURE WHAT EACH READING PUTS IN QUESTION, BECAUSE AGREEING THE RULE USUALLY SHRINKS THE CASE BEFORE ANYBODY DECIDES ANYTHING. A disagreement has a size, and the size is an area you can compute: the strip between the two lines the two sides are reading, its width multiplied by its length. Do it in one unit throughout -- 700 meters is 0.7 kilometers, and 0.7 multiplied by a 12-kilometer front is 8.4 square kilometers, not 8,400 of anything. Then compute what the parts of the case that are already agreed take off the table: if the wording both sides accept settles all but a 300-meter band, that band is 0.3 multiplied by 12, which is 3.6 square kilometers, and the case has shrunk from 8.4 to 3.6 before a single decision has been made. That arithmetic is often the most useful sentence in the whole analysis, because it tells two governments how much is actually at stake and whether the mechanism they are reaching for is worth the trouble.` },
    { loId: 'm8geo.analyzing-a-boundary-dispute', content: `WHAT THE ANALYSIS PRODUCES, AND WHERE IT STOPS. A finished analysis names five things: the cause the evidence supports, the piece of evidence that ruled each other cause out, the type of the boundary, what is open right now, and the mechanism that fits -- plus the area each reading puts in question. It does not name a winner. Saying which country ought to end up with the land is not a geographic result and this course does not produce one; describing the disagreement precisely is the whole job, and it is the part that actually helps, because a case correctly described is a case somebody can fix. Keep the scale of all this in view as well. The four mechanisms are ordinary machinery, not the apparatus of a crisis: survey teams re-mark worn lines, and neighboring countries negotiate new agreements about crossings, bridges and shared works constantly, almost always without anybody outside hearing about it.` },
    { loId: 'm8geo.analyzing-a-boundary-dispute', kind: 'definition', title: 'joint survey commission', content: `a standing team with members from both countries whose job is to find an agreed line on the ground and mark it; it measures and marks, and it does not decide what a disputed wording means.` },
    { loId: 'm8geo.analyzing-a-boundary-dispute', kind: 'definition', title: 'demarcation', content: `the marking of an agreed line on the ground with posts, cairns or cut lines, as distinct from the wording that describes where the line is supposed to run.` },
    { loId: 'm8geo.analyzing-a-boundary-dispute', kind: 'definition', title: 'treaty', content: `a written agreement two countries negotiate and both sign; it can add a rule an earlier agreement never contained, and it binds only because both sides consented to it.` },
    { loId: 'm8geo.analyzing-a-boundary-dispute', kind: 'definition', title: 'arbitration', content: `putting one stated question to a decider the two sides choose together and on terms they set, after agreeing in advance to accept the answer.` },
    { loId: 'm8geo.analyzing-a-boundary-dispute', kind: 'definition', title: 'standing court', content: `a body of judges already in place, with its rules already in force, before any particular disagreement arises; the two sides bring a question to it rather than building it for the question.` },
  ],
  methods: [
    {
      title: 'Worked ore bed under an agreed line',
      steps: [
        `Rule out before you rule in, and start with the survey, because the position of the line is what people reach for by reflex. A joint re-survey three years ago found every post where the agreement's record places it, and BOTH countries signed it. Nothing has moved and nothing is unmeasured, so a feature that moved is out -- and so is any question about where the line runs. WRONG: "The agreement is old, so the line has probably drifted by now." CORRECT: "A survey both sides signed says the posts stand where the record puts them, so the position of the line is not what is open here."`,
        `Now the documents. Both countries quote the same agreement, both read its words the same way, and no second document exists anywhere in the record. Two different accounts of what was agreed is out. Notice how cheap that elimination was: one line of the record did it.`,
        `Now people and timing together. Nobody lives on the plateau and the nearest settlement is 30 kilometers away, so nobody has been cut off from a school, a clinic or a market by this line -- a line drawn without regard to the people living there is out. And the timing is the loudest fact in the record: decades with no complaint, then an argument in the year a mineral survey mapped the bed. The cause the evidence supports is a resource sitting across the line.`,
        `Classify the boundary while you are here, because it checks the diagnosis. The line follows a straight surveyed line between two points -- not a landform, and not a difference between people -- so it is geometric, and a geometric line is exactly the kind that can run across something valuable without anyone noticing for decades. Then size the resource. The bed covers 500 hectares: 320 hectares on the Brantia side and 180 on the Selvane side. Check that the parts make the whole: 320 plus 180 is 500. The shares are 320 divided by 500, which is 0.64, or 64 percent, and 180 divided by 500, which is 0.36, or 36 percent. Invert both: 0.64 multiplied by 500 is 320, and 0.36 multiplied by 500 is 180, and 64 plus 36 is 100, so the two shares account for the whole bed with nothing double-counted.`,
        `Say what is open, in one sentence, before choosing a mechanism. Not the position of the line: the re-survey settled it. Not the meaning of the wording: both sides read it the same way. Not which existing rule applies: the agreement never mentions minerals at all, so there is no rule here to apply. What is open is a MISSING RULE, and a missing rule cannot be measured into existence or decided into existence. The mechanism that fits is a new agreement the two countries negotiate and both sign, which can set who works which part of the bed, in what proportion, and on what terms Selvane ore crosses to a railhead 40 kilometers nearer than its own. WRONG: "Send it to a court, because the two countries cannot agree." CORRECT: "A court applies rules already in force, and there is no rule here to apply; what is missing is the rule itself, and only the two countries together can write one."`,
        `The check to remember, and it is three clues of three different kinds. The SURVEY evidence is a measurement, and it says nothing moved. The DOCUMENT evidence is a single shared agreement, and it says there are not two accounts. The SETTLEMENT AND TIMING evidence is an empty plateau plus decades of quiet ending in the year the ore was mapped, and it says the thing both sides want is the ore. One number is a hunch; three of different kinds, all pointing the same way, is evidence. And notice where the analysis stops: 64 percent and 36 percent measure where a bed lies under a line both countries accept. They are not a ruling about who ought to get the ore, and this analysis does not produce one.`,
      ],
      example: { problem: `Work out which cause the evidence supports, classify the boundary, and say which resolution mechanism fits.

"Brantia and Selvane are separated by a boundary that runs dead straight across the Ilder Plateau. The agreement that fixed it describes the line as a straight line between two surveyed points. A joint re-survey three years ago found every marker post standing where the agreement's record places it, and both countries signed that re-survey.

Both countries quote the same agreement, and neither reads its words differently from the other. Neither has produced any other document.

Nobody lives on the plateau. The nearest settlement on either side is 30 kilometers away.

The plateau carried no complaint on record for decades. Last year a mineral survey mapped one continuous bed of iron ore beneath it: 500 hectares in all, 320 hectares on the Brantia side of the line and 180 hectares on the Selvane side. Both countries want to mine it. Brantia has a rail spur that already reaches the edge of the bed; the nearest railhead on the Selvane side is 40 kilometers away."`, solution: `The evidence supports a resource sitting across the line. The signed re-survey rules out a feature that moved, the single shared agreement rules out two different accounts, and an empty plateau 30 kilometers from the nearest settlement rules out a line drawn without regard to the people living there; the argument began in the year the bed was mapped. The boundary is geometric. The bed is 500 hectares, 320 (64 percent) on the Brantia side and 180 (36 percent) on the Selvane side, and 320 plus 180 is 500. What is open is a missing rule, because the agreement never mentions minerals, so the mechanism that fits is a new agreement both countries negotiate and sign -- not a survey, which has nothing left to measure, and not a court, which would have no rule to apply.` },
      relatedLoIds: ['m8geo.analyzing-a-boundary-dispute'],
    },
    {
      title: 'Worked shore that moved and one word change',
      steps: [
        `Name the cause first, and it comes straight off the dated pair. Two surveys of the same feature, taken 40 years apart and accepted by both countries, put the shore in two different places: the feature moved. Nothing about the document is in dispute, so this is not a case of two accounts. Work the rate while it is in front of you: 700 meters over 40 years is 700 divided by 40, which is 17.5 meters a year; check it by multiplying back, and 17.5 multiplied by 40 is 700. The line follows a landform, so the boundary is natural, and the dated pair is exactly the evidence that a natural boundary tells you to go and collect.`,
        `Size the strip the falling lake uncovered. It is 700 meters wide and runs the whole 12-kilometer front. Put both in one unit first: 700 meters is 0.7 kilometers. 0.7 multiplied by 12 is 8.4 square kilometers of land that was lakebed on the day of signing and is dry ground now. Check by inverting: 8.4 divided by 12 is 0.7, which is the width back again.`,
        `Now read the wording, because the wording decides what those 8.4 square kilometers are. The agreement fixes the boundary at the shore AS IT STOOD ON THE DAY OF SIGNING, and both countries accept that wording without argument. A boundary pinned to a dated position does not travel with the feature, so the ground the lake uncovered does not change hands just because it is dry now: the boundary stays at the old shore, wherever the old shore is shown to have run. WRONG: "The water moved north, so the boundary moved north with it." CORRECT: "The boundary follows the shore of a stated day; the shore of today is a different line, and the agreement does not point at it."`,
        `So what is genuinely open? Only this: where did the shore run on the day of signing, in between the four points the old survey recorded? The line was never marked, and there the two maps differ by up to 300 meters. That band is 0.3 multiplied by 12, which is 3.6 square kilometers still in question. The rest of the uncovered strip, 8.4 minus 3.6, is 4.8 square kilometers that both maps already place on the lake side of the old shore. Check: 3.6 plus 4.8 is 8.4. The wording both sides accept shrank the case from 8.4 square kilometers to 3.6 before anybody decided anything.`,
        `Choose the mechanism from that sentence. What is open is a MEASUREMENT, so a joint survey commission fits, and it is measurable twice over: the four recorded points still sit in the signing-day record, and a lake surface that stands in one place for a long time builds a beach ridge -- a low bank of sand and gravel piled at the water line -- which stays where it is when the water falls. A team with members from both countries can work from the record and the ridge, agree the position, and demarcate it with posts. WRONG: "Take it to arbitration, because the two maps disagree." CORRECT: "Two maps disagreeing about a position is a measurement, and a decider chosen to answer a question of meaning cannot measure a shoreline, while a survey can."`,
        `Rewind the data before the last move, reading it backwards to be sure nothing was misread: 300 meters between the maps, 12 kilometers of front, 700 meters of retreat, 40 years, one agreement that both sides read the same way. Now change ONE input. Suppose the agreement had said only that the boundary follows the southern shore of the lake, with no date attached to it. Nothing on the ground changes -- the retreat is still 700 meters, the front is still 12 kilometers, the strip is still 8.4 square kilometers -- but now Odram reads those words as the shore at signing and Kestran reads them as the shore wherever it is today, and the whole 8.4 square kilometers is in question again instead of 3.6. Surveying settles none of it, because both countries already agree exactly where both shorelines are. What is open is the MEANING of a sentence. If the two want one binding answer and are content to choose the decider together and set the terms, that is arbitration; if they have already accepted a standing court, the question can go there and be answered on rules already in force. Same ground, same arithmetic, different mechanism -- because one line of wording changed what was open.`,
      ],
      example: { problem: `Decide what is open and which mechanism fits, then work out what changes if one line of the agreement is different.

"Lake Orenn lies inside Odram. The agreement signed 40 years ago says the boundary follows the southern shore of the lake as that shore stood on the day of signing; Kestran territory begins south of that line.

The lake level has fallen since. This year's survey puts the southern shore 700 meters north of the signing-day shore, all along a 12-kilometer front. Both countries accept both surveys.

The signing-day survey fixed the old shore at only four points along that front, and the line was never marked on the ground. Odram's map joins those four points one way and Kestran's map joins them another, so between the recorded points the two lines differ by up to 300 meters, with Kestran's the more northerly.

Nobody lives on the exposed strip. Animals from farms on the Kestran side graze part of it in summer."`, solution: `The cause is a feature that moved: two accepted surveys 40 years apart put the shore 700 meters apart, which is 17.5 meters a year, and 17.5 multiplied by 40 is 700. The boundary is natural. The uncovered strip is 0.7 kilometers by 12 kilometers, which is 8.4 square kilometers, and because both countries accept a wording that pins the line to the signing-day shore, only the 300-meter band where their two maps of the old shore differ is open: 0.3 multiplied by 12 is 3.6 square kilometers, with 4.8 already agreed and 3.6 plus 4.8 recovering 8.4. What is open is a measurement, so a joint survey commission fits -- it can work from the four points the old survey recorded and from the beach ridge, and demarcate the line. Delete the date from the wording and nothing on the ground changes, but all 8.4 square kilometers are in question, what is open becomes a meaning, and the fitting mechanism becomes arbitration, or a standing court if both countries have already accepted one.` },
      relatedLoIds: ['m8geo.analyzing-a-boundary-dispute'],
    },
  ],
  pointers: [
    { content: `Students often say "The lake shrank, so the uncovered land belongs to Kestran, because whatever is dry next to your side of the water is yours." — The wording is the whole point, and both countries accept it: the boundary follows the southern shore AS IT STOOD ON THE DAY OF SIGNING, so the shore moving does not carry the boundary with it. The strip the falling lake uncovered is 0.7 kilometers wide along a 12-kilometer front, which is 8.4 square kilometers, and the question is not whether that ground turned into Kestran land when it dried out; it is where the old shore ran. The only part still open is the 300-meter band where the two maps of the old shore differ: 0.3 multiplied by 12 is 3.6 square kilometers, which leaves 4.8 square kilometers that both maps already place on the lake side, and 3.6 plus 4.8 recovers 8.4. WRONG: "The water moved, so the boundary moved." CORRECT: "The boundary follows the shore of a stated day, and locating that day's shore is a measuring job for a joint survey commission." The second half of the sentence is the worse half. Even in the version where the wording IS open, the analysis says how many square kilometers each reading puts in question and stops there; naming the country that ought to end up with the land is not something this course does.`, kind: 'common-error' },
    { content: `Students often say "Both cases end up in front of a court, because a court is the strongest way to settle any disagreement." — A court applies rules that are already in force, so it needs an existing rule and a question about which rule applies. In the Brantia and Selvane case there is no rule about a mineral bed crossing that line, because the agreement never mentions minerals, so a court would have nothing to work from: what is open is a missing rule, and only a new agreement the two countries negotiate and sign can supply one, setting who works which share of the 500-hectare bed -- 320 hectares, or 64 percent, on one side and 180 hectares, or 36 percent, on the other, and 320 plus 180 is 500 -- and how ore reaches a railhead. In the Odram and Kestran case as written, nobody disputes the wording at all; what is open is where the old shore ran, which is a measurement, and a joint survey commission measures and marks it. WRONG: "Use the strongest mechanism available." CORRECT: "Say what is open -- a measurement, a missing rule, a meaning, or which existing rule applies -- and the mechanism follows from that." The four are not ranked against each other; they answer four different questions.`, kind: 'common-error' },
    { content: `A case is a record, and each predictable cause leaves a different mark on it: a dated pair of surveys that disagree means a feature moved; two documents of different dates, one per side, means two accounts; a line everybody accepts plus people cut off from the services they use means a line drawn without regard to them; decades of quiet ending the year something valuable was mapped means a resource across the line.`, kind: 'tip' },
    { content: `Rule causes out one at a time and name the evidence that did it. A signed joint survey rules out a feature that moved; one agreement both sides read the same way rules out two accounts; who is affected and what changed just before the argument separates the last two.`, kind: 'tip' },
    { content: `Sort the line by what it follows and treat the answer as an instruction: a landform sends you for two dated surveys, a straight surveyed line sends you for the settlement and service data on both sides.`, kind: 'tip' },
    { content: `Name what is open before choosing a mechanism. A measurement goes to a joint survey commission, a missing rule needs a new agreement both countries sign, a meaning both want settled goes to arbitration on terms they set, and a question about which existing rule applies goes to a standing court both have already accepted.`, kind: 'tip' },
    { content: `Size the case in square kilometers: the strip between the two readings, width multiplied by length, in one unit throughout. 0.7 multiplied by 12 is 8.4 square kilometers; agree the wording and the same case can shrink to 0.3 multiplied by 12, which is 3.6.`, kind: 'tip' },
    { content: `A boundary pinned to a feature as it stood on a stated day does not travel when the feature moves, and one line of wording can change what is open and therefore which mechanism fits.`, kind: 'tip' },
    { content: `The analysis names the cause, the evidence that ruled the others out, the type, what is open, the mechanism and the area in question. It never names a winner -- and most boundaries stay quiet precisely because this machinery is used constantly and without any news at all.`, kind: 'tip' },
    { content: `Don't confuse 'the feature moved' with 'the boundary moved.' A boundary pinned to a feature ON A STATED DATE stays put even if the feature moves later. The wording is everything.`, kind: 'common-error' },
    { content: `Always ask 'What is open RIGHT NOW?' before picking a mechanism. Don't pick the fanciest one or assume a court handles everything. Match the mechanism to what's actually unsettled: measurement → survey; missing rule → treaty; disputed meaning → arbitration or court.`, kind: 'gotcha' },
    { content: `A feature-based boundary (river, shoreline, ridge) sends you hunting for TWO DATED SURVEYS. A straight geometric boundary sends you hunting for SETTLEMENT AND SERVICE DATA. The boundary type is your instruction for what evidence to collect next.`, kind: 'tip' },
    { content: `Convert all distances to ONE UNIT before multiplying. 700 meters = 0.7 kilometers; then 0.7 × 12 km = 8.4 km². Not '700 × 12 = 8,400 of something confused.' Unit confusion collapses the whole size calculation.`, kind: 'common-error' },
    { content: `A dated wording ('as it stood on the day of signing') shrinks the case before anyone decides anything. If both sides accept that wording, a huge strip of land is already off the table. Always compute what agreement has already settled.`, kind: 'vocab-note' },
    { content: `Don't name a winner. Saying 'Country A should get that land' is not geography and this course does not produce it. A finished analysis describes the disagreement precisely—that's the part that actually helps someone fix it.`, kind: 'edge-case' },
    { content: `Rule OUT before you rule IN. Start with the signed survey (rules out 'feature moved'), then the shared document (rules out 'two accounts'), then people + timing (separates the last two). One line of evidence can eliminate a cause entirely.`, kind: 'tip' },
    { content: `Check your arithmetic by inverting it. If 320 + 180 = 500 (the whole bed), then 320 ÷ 500 = 0.64 and 0.64 × 500 = 320 again. If it doesn't loop back, you've made an error and your case size is wrong.`, kind: 'tip' },
  ],
};
