/**
 * Grade 8 World Geography — Unit 2 CED 2.1: GIS Layers & Overlay Reasoning.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.gis-layers-and-overlay.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U2_GIS_LAYERS_AND_OVERLAY: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.gis-layers-and-overlay.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 2,
  cedTopic: '2.1',
  cedTitle: 'GIS Layers & Overlay Reasoning',
  planId: 'evelyn.ms.m8geo.gis-layers-and-overlay.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.gis-layers-and-overlay.v1' }],
  theory: [
    { loId: 'm8geo.gis-layers-and-overlay', content: `LAYERS ARE SEPARATE RECORDS OF THE SAME GROUND, SO THE FIRST MOVE IS TO LINE THEM UP PLACE BY PLACE. A geographic information system, usually called a GIS, does not keep one map of everything. It keeps each kind of fact in its own LAYER -- one layer for the parcels of land, one for the roads, one for the flood zone, one for land use -- and every layer is tied to the same locations, so the same parcel carries a value in each of them. One layer read on its own answers a question about its own one topic, and that is not why the system exists. It exists because the layers line up: the first move in every question below is to go place by place and write down what each layer says about that place, before answering anything.` },
    { loId: 'm8geo.gis-layers-and-overlay', content: `AN OVERLAY IS ONE CONDITION PER LAYER, RUN AT EVERY PLACE. Turn the question into conditions -- one condition for each layer it touches -- then run each condition down the list of places separately and keep the places that pass. Run them in order and carry only the survivors into the next condition; that is less work and it makes the count checkable later. Two consequences are worth holding on to, because both are checks. Adding a condition can shrink the answer set or leave it the same size, and can never grow it. And the answer set is always part of the shortest list you ran, so an answer with more places in it than the shortest list is already wrong, before anyone looks at which places they are.` },
    { loId: 'm8geo.gis-layers-and-overlay', content: `THE CONNECTOR COMES FROM THE RULE, AND AND, OR AND AND NOT DO NOT GIVE THE SAME ANSWER. Say the connector out loud before touching the lists. Inside the flood zone AND fronting a paved road keeps only the places both layers name. Inside the flood zone OR fronting a paved road keeps every place either layer names, which is a far longer answer. Inside the flood zone AND NOT inside the wetland uses the wetland layer as an EXCLUSION: the places it names are the ones that fail. An AND rule run as OR is the most common wrong answer in this whole subject, and it gives itself away in the arithmetic before it gives itself away in the geography: two lists of 4 places and 5 places, in a town that holds 8 parcels, come to 9, and a town cannot hand back more parcels than it has. The extra came from counting the places on both lists twice.` },
    { loId: 'm8geo.gis-layers-and-overlay', content: `COUNT THE SURVIVORS, THEN CHECK THE COUNT BY ELIMINATION. A where-question usually wants a how-many alongside the which-ones, and the count is easy to get slightly wrong. Count each eliminated place out ONCE, at the first condition it fails, so that no place is counted out twice, and then the eliminated places plus the survivors have to come back to the total you started with. If they do not, either a place was dropped or one was counted out twice, and the second is the more likely of the two.` },
    { loId: 'm8geo.gis-layers-and-overlay', content: `THE STACK ANSWERS ONLY THE QUESTIONS ITS LAYERS WERE BUILT TO ANSWER. Every layer was collected by somebody, for a reason, and it records what that reason needed and nothing else. If no layer records what a question asks about, the honest answer is that this stack cannot answer it, and the fix is another layer, not a cleverer reading of the ones already there. Answering a question about who lives in a place by pointing at the layer that records what the land is used for is a guess about the world wearing the clothes of a reading of the data. One reading rule goes with this, and every layer in this lesson states it: a layer written as a list names every place it covers, so a place the list does not name is outside that layer, not unknown.` },
    { loId: 'm8geo.gis-layers-and-overlay', content: `THE ANSWER SET BELONGS TO THE LAYERS AND THE RULE, NOT TO THE PLACES. Correct one layer, or change one condition, and run the overlay again: places cross into the answer and out of it without moving a single meter. That is worth saying out loud whenever an overlay answer is handed to somebody, because "these are the parcels that were inside the flood zone and fronting a paved road when these layers were recorded" is a different sentence from "these are the risky parcels", and only the first one is what the overlay produced.` },
    { loId: 'm8geo.gis-layers-and-overlay', kind: 'definition', title: 'layer', content: `one kind of fact recorded for every place across the same area and kept separately from the other kinds, so it can be read on its own or alongside them.` },
    { loId: 'm8geo.gis-layers-and-overlay', kind: 'definition', title: 'overlay', content: `reading two or more layers at the same locations at once and keeping the places that satisfy a condition in each of them.` },
    { loId: 'm8geo.gis-layers-and-overlay', kind: 'definition', title: 'attribute', content: `the value one layer records for one place -- vacant or built on, inside the zone or outside it, connected to the line or not.` },
    { loId: 'm8geo.gis-layers-and-overlay', kind: 'definition', title: 'condition', content: `the test a rule sets for one layer, which every place either passes or fails; a rule has one condition for each layer it touches.` },
    { loId: 'm8geo.gis-layers-and-overlay', kind: 'definition', title: 'exclusion layer', content: `a layer whose condition removes places instead of keeping them, so that the places the layer names are the ones that fail.` },
    { loId: 'm8geo.gis-layers-and-overlay', kind: 'definition', title: 'answer set', content: `the places left once every condition has been run, belonging to the layers and the rule it was built from rather than to the places themselves.` },
  ],
  methods: [
    {
      title: 'Worked flood and road overlay',
      steps: [
        `Say the connector before touching the lists. The rule carries the word AND, so a parcel has to be on the flood-zone list AND on the road list. WRONG: "Gather every parcel that either layer names." CORRECT: "Keep only the parcels that both layers name." The two readings give very different answers, and the rule, not the habit, decides which one is wanted.`,
        `Run the first condition down the parcel layer. Inside the flood zone: parcels 2, 3, 5 and 7 pass. Parcels 1, 4, 6 and 8 fail. Four parcels survive the first condition.`,
        `Run the second condition on those four only, not on the whole town -- that is what running them in order buys you. Parcel 2 is on the road list, so it passes. Parcel 3 is not on the road list, so it fails. Parcel 5 is on the road list and passes. Parcel 7 is not, so it fails. Two parcels are left: parcel 2 and parcel 5.`,
        `Put a number on it. 2 parcels out of 8 is 2 divided by 8, which is 0.25, or 25 percent of the town parcels. Invert the division to check it: 0.25 times 8 is 2. The count comes back, so the share is right.`,
        `Check the count a second way, by elimination, counting each parcel out once at the first condition it fails. Four parcels failed the flood condition: 1, 4, 6 and 8. Two more failed the road condition: 3 and 7. 4 plus 2 is 6 eliminated, and 8 minus 6 is 2 surviving, which is the answer already reached.`,
        `Look at what the other connector would have done, because OR is the answer most people give. OR keeps every parcel either layer names: 4 on one list plus 5 on the other is 9, and Marden holds 8 parcels, so 9 is impossible. Parcels 2 and 5 sit on both lists and were counted twice, so the honest OR answer is 9 minus 2, which is 7 -- every parcel except parcel 4, which neither layer names. Seven parcels out of eight is useless to the flood office, and the arithmetic said something was wrong before anybody read a single parcel record.`,
        `Rewind the input, then test a contrasting case. Read the two lists backwards to be sure nothing was misread: road 8, 6, 5, 2, 1; flood 7, 5, 3, 2. Parcels 2 and 5 appear on both, and no third parcel does. Now change ONE input. A survey finds that parcel 5 sits above the flood line, and the flood-zone layer is corrected to parcels 2, 3 and 7. Re-run: of those three, only parcel 2 is on the road list, so the answer set falls from two parcels to one. Elimination checks it: five parcels now fail the flood condition -- 1, 4, 5, 6 and 8 -- and two of the rest fail the road condition -- 3 and 7 -- so 5 plus 2 is 7 eliminated and 8 minus 7 is 1. Nothing moved. Parcel 5 is exactly where it always was; the layer changed, and the answer changed with it.`,
      ],
      example: { problem: `Marden keeps its town records as a geographic information system. Answer the question the flood office asked, put a number on the answer, and then say what would change it.

"The parcel layer holds eight parcels, numbered 1 through 8. The flood-zone layer names every parcel the mapped flood reaches: parcels 2, 3, 5 and 7. The road layer names every parcel that fronts a paved road: parcels 1, 2, 5, 6 and 8. A parcel a layer does not name is outside that layer."

The flood office needs the parcels that are inside the flood zone AND front a paved road, because those are the ones a truck can reach on a flood day. Which parcels are they, and what share of the town parcels is that?`, solution: `Parcels 2 and 5, the only two that the flood-zone layer and the road layer both name, which is 2 out of 8 parcels, or 25 percent. Elimination confirms the count: 4 parcels fail the flood condition, 2 more fail the road condition, and 8 minus 6 is 2. The same two layers read with OR give 7 parcels, because 4 plus 5 is 9 in a town of 8 and the two shared parcels were counted twice. If the flood-zone layer is corrected to parcels 2, 3 and 7, the answer set falls to parcel 2 alone.` },
      relatedLoIds: ['m8geo.gis-layers-and-overlay'],
    },
    {
      title: 'Worked repair the connector and the exclusion',
      steps: [
        `Check the two lists the clerk read out, because a wrong answer does not always come from a misread layer. Vacant: A, C and D, which matches the land-use layer, since B is housing and E is a workshop. Connected to the sewer line: A, C and E. Both lists are read correctly. The mistakes are in what was done with them.`,
        `First mistake: the connector. The rule says vacant AND connected, and the clerk kept every parcel on either list. The arithmetic shows it without any parcel letters at all: 3 vacant plus 3 on the sewer line is 6, in a town of 5 parcels. Parcels A and C are on both lists and were counted twice, so the clerk list is 6 minus 2, which is the 4 parcels written down. WRONG: "A, C, D and E, because each of them is vacant or on the sewer line." CORRECT: "A and C, because they are the only two that are vacant AND on the sewer line."`,
        `Second mistake: the exclusion. A condition joined by AND NOT is not optional, and what a layer is "about" is not the test -- the rule named the wetland layer, so the wetland layer runs. It works in the opposite direction from the other two, which is its only difference: the parcels it names are the ones that fail. It names C, so C fails. Of A and C, only A is left.`,
        `Count it by elimination, each parcel counted out once at the first condition it fails. Parcels B and E fail the vacancy condition: 2. Of A, C and D, parcel D fails the sewer condition: 1 more. Of A and C, parcel C fails the wetland exclusion: 1 more. 2 plus 1 plus 1 is 4 eliminated, and 5 minus 4 is 1 surviving. One parcel, A, which is what the conditions gave.`,
        `Now the check to remember, and it is three clues of three different kinds at one location. The land-use layer says what parcel A is used for: nothing, it is vacant. The sewer layer says what service reaches it: the town line does. The wetland layer says what natural area covers it: none, because that layer names only C. Three offices collected those three facts separately, for three unrelated reasons, and all three agree at parcel A. One layer is a hunch; three layers that agree at the same place is an answer.`,
        `Say what the stack cannot do, out loud, because the clerk is also asked which qualifying parcel has the most shade trees. No layer here records trees. The honest answer is that this stack cannot answer that question, and reading the land-use layer as a stand-in -- vacant, so probably bare -- would be a guess about the world dressed up as a reading of the data. The fix is a tree layer, not a cleverer reading of the layers already there.`,
      ],
      example: { problem: `A permit clerk in Thornbury ran an overlay and got it wrong twice. Find both mistakes, repair the analysis, and say which parcel survives.

"Five parcels: A, B, C, D and E. The land-use layer records A vacant, B housing, C vacant, D vacant, E a workshop. The sewer layer names every parcel connected to the town sewer line: A, C and E. The wetland layer names every parcel inside the mapped wetland: C. A parcel a layer does not name is outside that layer."

The rule for a building permit: the parcel must be vacant AND connected to the sewer line AND NOT inside the wetland. The clerk wrote: "Vacant parcels are A, C and D. Sewer parcels are A, C and E. That gives A, C, D and E, so four parcels qualify. The wetland layer is a nature layer, so I left it out."`, solution: `Parcel A alone. The clerk made two mistakes. Reading AND as OR is the first, and the arithmetic exposes it: 3 vacant plus 3 on the sewer line is 6 names in a town of 5 parcels, because A and C were counted twice, which is how 4 parcels ended up on the list. Dropping the exclusion is the second, and it is what kept C, the one parcel inside the wetland. Vacant AND connected to the sewer line gives A and C; AND NOT inside the wetland removes C. Elimination checks it: 2 parcels fail vacancy, 1 fails the sewer condition, 1 fails the wetland exclusion, and 5 minus 4 is 1. Three different layers agree at parcel A, and the stack cannot say anything at all about trees, because no layer records them.` },
      relatedLoIds: ['m8geo.gis-layers-and-overlay'],
    },
  ],
  pointers: [
    { content: `Students often say "Nine parcels are inside the flood zone and front a paved road, because four are in the flood zone and five front a road." — Start with the arithmetic, because it fails before any parcel is looked up. Marden holds 8 parcels, and 4 plus 5 is 9, so a nine-parcel answer hands back more parcels than the town has. Parcels 2 and 5 are on both lists and were counted twice, so even the OR answer is 9 minus 2, which is 7. The rule, though, says AND, and AND keeps only the parcels both layers name: parcel 2 and parcel 5, which is 2 out of 8, or 25 percent. Elimination checks it: parcels 1, 4, 6 and 8 fail the flood condition and parcels 3 and 7 fail the road condition, so 4 plus 2 is 6 eliminated and 8 minus 6 is 2. WRONG: "Four plus five is nine parcels." CORRECT: "Both layers name parcels 2 and 5, so the answer is two parcels -- and an answer set is never bigger than the shortest list it came from."`, kind: 'common-error' },
    { content: `Students often say "Parcel C qualifies, because the wetland layer is a nature layer and does not belong in a building rule." — The rule is vacant AND connected to the sewer line AND NOT inside the wetland, and the third condition is a condition exactly like the other two. It runs in the opposite direction, and that is its only difference: the parcels the wetland layer names are the ones that fail. It names C, so C fails, and parcel A is the only parcel left. What a layer is "about" never decides whether it is in a rule; the rule decides, and an AND NOT condition is the one most often dropped, because removing places feels like a different kind of act from keeping them. Elimination checks it: B and E fail the vacancy condition, D fails the sewer condition, C fails the wetland exclusion, and 5 minus 4 is 1. WRONG: "The wetland layer is about nature, so leave it out." CORRECT: "The rule named the wetland layer, so the wetland layer runs, and it removes parcel C."`, kind: 'common-error' },
    { content: `A geographic information system keeps each kind of fact in its own layer, all of them tied to the same locations, so the first move in any question is to go place by place and write down what each layer says about that place.`, kind: 'tip' },
    { content: `An overlay is one condition per layer, run at every place. AND keeps only the places that pass every condition, adding a condition can never grow the answer set, and the answer set is always part of the shortest list you ran.`, kind: 'tip' },
    { content: `Take the connector from the rule: AND keeps the places on both lists, OR keeps the places on either list, and AND NOT turns a layer into an exclusion whose named places fail. The same layers give different answers under each.`, kind: 'tip' },
    { content: `An AND rule run as OR shows itself in the arithmetic: lists of 4 and 5 places in a town of 8 parcels come to 9, which is more parcels than exist, because the places on both lists were counted twice.`, kind: 'tip' },
    { content: `Check a survivor count by elimination. Count each place out once, at the first condition it fails, and the eliminated places plus the survivors must return the total you started with.`, kind: 'tip' },
    { content: `A stack answers only the questions its layers were built to answer. If no layer records what the question asks about, say so; a layer that records something else cannot stand in for one nobody collected.`, kind: 'tip' },
    { content: `The answer set belongs to the layers and the rule, not to the places. Correct one layer and a parcel crosses in or out without moving a meter, so an overlay answer travels with the rule that produced it and the date of the layers behind it.`, kind: 'tip' },
    { content: `AND keeps only places on BOTH lists. OR keeps places on EITHER list. Say the connector out loud before you touch anything — they give completely different answers.`, kind: 'common-error' },
    { content: `An AND rule in a GIS overlay can NEVER grow the answer set — it can only shrink it or stay the same. If your answer set is bigger than the shortest list you're working with, stop and recheck.`, kind: 'tip' },
    { content: `AND NOT is an EXCLUSION layer. The places it names are the ones that FAIL — they get removed, not kept. Treat it exactly like any other condition; don't leave it out because it 'sounds like' it doesn't belong.`, kind: 'gotcha' },
    { content: `A layer only answers questions about what it records. No layer here records tree shade? Then 'the stack cannot answer that question' — don't guess by reading a different layer sideways.`, kind: 'vocab-note' },
    { content: `Run conditions in order and carry only survivors forward — don't run every condition against the full list. This saves work AND makes your count checkable: eliminated places plus survivors must equal your starting total.`, kind: 'tip' },
    { content: `Check your count by ELIMINATION. Count each place out once at the first condition it fails. If (eliminated + survivors) ≠ total, you double-counted something or dropped a place.`, kind: 'tip' },
    { content: `The answer set is owned by the layers AND the rule — not by the place itself. Change the layers or the rule, and a place moves in or out without moving a meter on the map.`, kind: 'vocab-note' },
    { content: `If two lists add up to more places than the town actually has, you read OR as AND. Check: 4 + 5 = 9 in a town of 8? The overlapping places got counted twice.`, kind: 'common-error' },
  ],
};
