/**
 * Grade 8 World Geography — Unit 4 CED 4.2: North America: Migration Flows.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.north-america-migration-flows.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U4_NORTH_AMERICA_MIGRATION_FLOWS: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.north-america-migration-flows.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 4,
  cedTopic: '4.2',
  cedTitle: 'North America: Migration Flows',
  planId: 'evelyn.ms.m8geo.north-america-migration-flows.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.north-america-migration-flows.v1' }],
  theory: [
    { loId: 'm8geo.north-america-migration-flows', content: `A FLOW TABLE IS READ IN TWO DIRECTIONS, AND ONE DIRECTION ON ITS OWN IS NEVER AN ANSWER. An origin-destination table lists moves: each line names the region a group of people left, the region they arrived in, and how many of them there were. Every region therefore appears in two kinds of line. Lines that START at the region are its DEPARTURES, also called out-migration. Lines that END at the region are its ARRIVALS, also called in-migration. Add each kind separately, from the whole table, before you say one word about the region. Calling a region a sender because a large number left it is the first wrong step in this entire subject, and it is the one that survives into grown-up headlines.` },
    { loId: 'm8geo.north-america-migration-flows', content: `NET MIGRATION IS ARRIVALS MINUS DEPARTURES, AND THE SIGN IS THE VERDICT. Subtract the departures from the arrivals for one region over one period. A positive result means the region ended with more people than it started with from moving, and it is a NET RECEIVING region. A negative result, written with a minus sign -- -1,200 people -- means a NET SENDING region. A result of zero means the region traded evenly and gained nobody, which is a real and common outcome, not a missing answer. The word "net" is carrying all the weight here: it means after the counterflow has been taken off. Two regions can send 10,000 people to each other in the same year and neither one is a sender.` },
    { loId: 'm8geo.north-america-migration-flows', content: `THE WHOLE TABLE CHECKS ITSELF, SO USE IT EVERY TIME. Every move in the table is one departure for one region and one arrival for another, so two things have to be true when you are finished. Total arrivals across the table equals total departures across the table. And the net figures of all the regions add to zero, because the people who left somewhere arrived somewhere. If your nets do not add to zero, you dropped a line or counted one twice, and you now know that before your conclusion does. The check costs one addition and it catches the mistake that otherwise travels all the way to the end.` },
    { loId: 'm8geo.north-america-migration-flows', content: `A SORTED LIST OF REASONS IS NOT YET AN EXPLANATION. Sorting is the easy half: a reason that describes the region people left is a push and a reason that describes the region they went to is a pull, so the question to ask of each reason is which region it is about. The hard half, and this row, is testing the sorted reasons against the direction the table actually shows. A candidate explanation survives only if the condition sits at the end of the flow its label claims -- a pull has to sit in the region that GAINED, and a push has to sit in the region that LOST. Until a reason has been held against the arithmetic, it is a guess with a label on it.` },
    { loId: 'm8geo.north-america-migration-flows', content: `THREE WAYS A CANDIDATE EXPLANATION FAILS, AND YOU CHECK FOR ALL THREE. First, the condition is present at BOTH ends: both regions have long winters, both have universities. The statement is perfectly true and it cannot explain why the flow ran one way rather than the other, which makes it the hardest failure to catch. Second, the condition points the WRONG WAY: housing is cheaper in the region that LOST people, so cheap housing cannot be what drew them to the expensive one. Third, the condition is not in the data at all, and you supplied it yourself from what you already believed. Run all three checks on every explanation anybody hands you, including the one you thought of first.` },
    { loId: 'm8geo.north-america-migration-flows', content: `A FLOW TABLE ANSWERS TWO QUESTIONS AND REFUSES A THIRD. It tells you how many people moved and between which regions, and, with the conditions written beside it, which offered explanation fits the direction. It does not tell you what the people who moved are like. A region is many places -- many communities, many languages, many kinds of work and many ways of living -- and a net figure is the balance of thousands of separate household decisions, so no table of moves can support a sentence that begins "people from that region are". There is a time limit on it too: one period of figures supports a claim about that period. Geographers describe a movement within the United States that has run for decades, from the interior and the Northeast toward the South and the West, and a long movement out of rural areas toward metropolitan areas, and a claim of that size rests on many periods of data all pointing the same way, never on one year. Arrivals from other countries are handled exactly like every other line: one more origin, counted, subtracted and checked, with no story attached to it.` },
    { loId: 'm8geo.north-america-migration-flows', kind: 'definition', title: 'origin-destination table', content: `a table in which each line names the region a group of people left, the region they arrived in, and how many moved, so that both directions of every exchange are on the page.` },
    { loId: 'm8geo.north-america-migration-flows', kind: 'definition', title: 'in-migration', content: `the moves that end in a region, added up: the arrivals side of that region's account.` },
    { loId: 'm8geo.north-america-migration-flows', kind: 'definition', title: 'out-migration', content: `the moves that start in a region, added up: the departures side of that region's account.` },
    { loId: 'm8geo.north-america-migration-flows', kind: 'definition', title: 'net migration', content: `arrivals minus departures for one region over one period, positive when the region gained people by moving and negative when it lost them.` },
    { loId: 'm8geo.north-america-migration-flows', kind: 'definition', title: 'counterflow', content: `the moves running the opposite way between the same two regions, which have to be subtracted before either region can be called a sender or a receiver.` },
  ],
  methods: [
    {
      title: 'Worked net from a flow table',
      steps: [
        `Add the departures first, which are the lines that START at each region. Adair: 9,000 to Byrne plus 6,000 to Corvel is 15,000 departures. Byrne: 4,000 plus 5,000 is 9,000 departures. Corvel: 2,000 plus 3,000 is 5,000 departures.`,
        `Now add the arrivals, which are the lines that END at each region, and take them from the whole table rather than from the lines that happen to be easiest to see. Adair received 4,000 from Byrne and 2,000 from Corvel, which is 6,000 arrivals. Byrne received 9,000 from Adair and 3,000 from Corvel, which is 12,000. Corvel received 6,000 from Adair and 5,000 from Byrne, which is 11,000.`,
        `Subtract, region by region, and read the sign. Adair: 6,000 arrivals minus 15,000 departures is -9,000, so Adair is a net sending region. Byrne: 12,000 minus 9,000 is 3,000, so Byrne is a net receiving region. Corvel: 11,000 minus 5,000 is 6,000, so Corvel is net receiving as well, and by twice as much as Byrne.`,
        `Run the whole-table check before going one step further. Total departures: 15,000 plus 9,000 plus 5,000 is 29,000. Total arrivals: 6,000 plus 12,000 plus 11,000 is 29,000. They match, so every move has been counted exactly once. Now the nets: -9,000 plus 3,000 plus 6,000 is 0. Everybody who left a region arrived in another one, so zero is the only total the nets are allowed to have.`,
        `Read the surprise in the table, because it is the reason for doing the arithmetic at all. The single largest flow anywhere in the table is the 9,000 who went from Adair to Byrne, which makes Byrne look like the big winner of the year. It is not. Byrne also sent 9,000 people out, while Corvel, which never appears in a flow bigger than 6,000, gained twice what Byrne gained. WRONG: "Byrne took in the biggest flow in the table, so Byrne gained the most." CORRECT: "Byrne gained 3,000 and Corvel gained 6,000, because a gain is arrivals minus departures, and Byrne sent 9,000 out while Corvel sent only 5,000."`,
        `Rewind the input and read the table backwards to confirm the answer follows from it. Corvel shows up as an origin twice, for 2,000 and for 3,000, which is a small total; it shows up as a destination twice, for 6,000 and for 5,000, which is a much larger one. Small in the origin lines and large in the destination lines is exactly what a net receiver looks like, so the verdict comes from the table rather than from a hunch.`,
        `Now change ONE line and run it again, so the result is not memorized as "Corvel wins". Suppose Byrne had sent only 1,000 people to Corvel instead of 5,000, and nothing else changed. Byrne departures become 4,000 plus 1,000, which is 5,000, and its arrivals are still 12,000, so its net is 12,000 minus 5,000, which is 7,000. Corvel arrivals become 6,000 plus 1,000, which is 7,000, against 5,000 departures, so its net is 2,000. Adair does not move at all: still -9,000. Check: -9,000 plus 7,000 plus 2,000 is 0, and total arrivals, 6,000 plus 12,000 plus 7,000, is 25,000, which matches total departures, 15,000 plus 5,000 plus 5,000. Byrne and Corvel have swapped places, and not one person arriving in Byrne changed. A ranking of regions is a balance, not a property of a region.`,
      ],
      example: { problem: `Read a one-year flow table both ways, name the net sending and the net receiving regions, and check the table against itself.

Three regions of one country recorded every move between them for a year.

"Adair to Byrne: 9,000. Adair to Corvel: 6,000. Byrne to Adair: 4,000. Byrne to Corvel: 5,000. Corvel to Adair: 2,000. Corvel to Byrne: 3,000."`, solution: `Adair is the net sending region at -9,000 (6,000 arrivals minus 15,000 departures). Byrne and Corvel are both net receiving, Byrne at 3,000 (12,000 minus 9,000) and Corvel at 6,000 (11,000 minus 5,000). The table checks out: 29,000 total arrivals equals 29,000 total departures, and the three nets add to zero. Byrne took in the largest single flow in the table and still gained half of what Corvel gained, because Byrne sent 9,000 people out. Changing one line -- Byrne to Corvel falling from 5,000 to 1,000 -- makes Byrne the larger gainer, at 7,000 against 2,000.` },
      relatedLoIds: ['m8geo.north-america-migration-flows'],
    },
    {
      title: 'Worked which explanation the data supports',
      steps: [
        `Settle the direction before reading a single reason, because a reason is only testable once you know which way the people went. Selby: 12,000 arrivals minus 4,000 departures is 8,000, so Selby is the net receiving region. Dunmere: 4,000 minus 12,000 is -8,000, so Dunmere is the net sending region. Check the pair: 8,000 plus -8,000 is 0. And invert the subtraction to be sure of it: add the counterflow back, 8,000 plus 4,000, and the 12,000 who left Dunmere for Selby comes straight back.`,
        `Test explanation one against the direction. Cheaper housing is a pull, and a pull has to sit in the region that GAINED. Housing is cheapest in Dunmere, which lost 8,000 people, and it is high and rising in the region they moved to. The condition points the wrong way, so the data does not support the explanation. WRONG: "Housing is cheaper in Dunmere, so people moved for cheaper housing." CORRECT: "The people who moved went from the cheaper region to the more expensive one, so cheap housing cannot be what drew them."`,
        `Test explanation two. Two universities in Dunmere, two universities in Selby. The condition is present at both ends, identical on the side people left and on the side they arrived at, so it cannot account for a flow that ran one way. It is a true statement that explains nothing about this table, and it is the failure that is hardest to catch, because there is nothing false in the sentence to notice.`,
        `Test explanation three, one half at a time. Farm jobs falling for six years running describes Dunmere, the region people left, so it is a push and it sits at the correct end. Warehouses and hospitals hiring describes Selby, the region people arrived in, so it is a pull and it also sits at the correct end. Both halves point the way the 8,000 actually went, so this is the explanation the data supports.`,
        `Now put the verdict on three clues of different kinds rather than on one. The arithmetic is the first kind: a net of 8,000 toward Selby, with the 4,000-person counterflow already subtracted out of it. The employment conditions are a second kind, and they are the only pair in the data that moves in opposite directions at the two ends -- work disappearing where people left, work appearing where they arrived. The climate line is a third and independent kind: mild winters describe Selby, the region that gained, so that condition at least points the right way, while the housing line points backwards and the university line is flat. One agreeing number is a hunch; three clues of different kinds, all pointing the same way, is evidence.`,
        `Say the limit out loud, because the table cannot carry more than this. The data supports the third explanation and rules out the first two, for this year and this pair of regions. It does not show that each of the 12,000 people moved for work. Four thousand people moved the OTHER way under exactly the same stated conditions, which is the clearest possible sign that a region is not one thing and the people in it are not one kind of person. A net figure is a balance struck between thousands of separate decisions, and it never describes the people who made them.`,
        `The same test runs on the patterns that matter most in North America: the movement within the United States that has run for decades from the interior and the Northeast toward the South and the West, and the movement out of rural areas toward metropolitan areas. Nothing about the test changes when the regions are real ones. What changes is how much data a claim of that size needs -- one year of figures can support a claim about one year, and a claim about decades needs many years of figures all pointing the same way.`,
      ],
      example: { problem: `A newspaper offers three explanations for a flow. Test each one against the table and say which the data supports.

"Over one year, 12,000 people moved from Region Dunmere to Region Selby, and 4,000 moved from Selby to Dunmere.

Dunmere: farm work has become more mechanized and the number of farm jobs has fallen for six years running. Winters are long and cold. Housing costs are among the lowest in the country. There are two universities.

Selby: warehouses and hospitals opened recently and are hiring. Winters are mild. Housing costs are high and rising. There are two universities."

The three explanations offered: one, people moved for cheaper housing; two, people moved because of the universities; three, lost farm work pushed people out of Dunmere and new warehouse and hospital jobs pulled them into Selby.`, solution: `The flow runs toward Selby: 12,000 minus 4,000 is a net of 8,000, and Dunmere is -8,000, which checks because 8,000 plus 4,000 returns the 12,000 gross flow. Cheaper housing fails the direction test, since housing is cheapest in the region people left. The universities fail because both regions have two, so the condition is identical at each end. The third explanation survives: falling farm work sits in the region people left, new warehouse and hospital hiring sits in the region they arrived in, and mild winters in Selby point the same way. The data supports it for this year and this pair of regions, and the 4,000 who moved the other way show that a net figure is a balance, not a statement about what a region's people are like.` },
      relatedLoIds: ['m8geo.north-america-migration-flows'],
    },
  ],
  pointers: [
    { content: `Students often say "Hale lost 6,000 people, and three times as many left Hale as left Ivor, so Hale is emptying out fastest." — Net migration is arrivals minus departures, so do the subtraction for both regions. Hale: 9,000 minus 6,000 is 3,000, a net GAIN of 3,000; check by adding the departures back, 3,000 plus 6,000, which returns the 9,000 who arrived. Ivor: 3,000 minus 2,000 is 1,000, a net gain of 1,000; check, 1,000 plus 2,000 returns the 3,000 who arrived. Neither region is emptying out, and the one the student called the fastest-emptying is the one that grew the most. WRONG: "Six thousand left Hale, so Hale lost 6,000." CORRECT: "Hale gained 3,000, because 9,000 arrived and 6,000 left." The 6,000 is a true number being asked to do a job it cannot do: it is one direction of a two-direction account. And a larger region will record larger figures on BOTH sides, which is a second reason a departure count on its own settles nothing.`, kind: 'common-error' },
    { content: `Students often say "People from Hale are just the restless type." — No flow table can support a sentence about what people are like, and neither can any other table in this course. Hale is a region, which means many communities, many kinds of work, many languages and many ways of living, and the figures say exactly this much: 9,000 people arrived, 6,000 left, and the balance is a gain of 3,000. Those 15,000 moves were 15,000 separate household decisions, and 9,000 of them were decisions to move IN, which by itself breaks the sentence. WRONG: "People from Hale are just the restless type." CORRECT: "Hale recorded 6,000 departures and 9,000 arrivals; to explain either figure, find the conditions the data states at each end and test them against the direction people actually moved." An explanation names conditions, never characters.`, kind: 'common-error' },
    { content: `A flow table is read in two directions. Lines that start at a region are its departures; lines that end at it are its arrivals. Add each kind separately before saying anything about the region.`, kind: 'tip' },
    { content: `Net migration is arrivals minus departures. Positive is net receiving, negative is net sending, and zero means the region traded evenly and gained nobody.`, kind: 'tip' },
    { content: `Check the whole table every time: total arrivals equals total departures, and the nets of all the regions add to zero, because every departure is somebody else's arrival.`, kind: 'tip' },
    { content: `The largest single flow into a region does not make it the biggest gainer. What the region sent out comes off first, and that is what "net" means.`, kind: 'tip' },
    { content: `Sorting reasons into push and pull is the easy half. An explanation has to be held against the direction the table shows.`, kind: 'tip' },
    { content: `Three ways an explanation fails: the condition is present at both ends, the condition points the wrong way, or the condition is not in the data at all.`, kind: 'tip' },
    { content: `A flow table counts moves. It never says what the people who moved are like, and one period of figures supports a claim about that period only.`, kind: 'tip' },
    { content: `**Departures ≠ Loss.** A region with 10,000 departures is not losing 10,000 people unless you ignore arrivals. Always subtract: net = arrivals − departures. If 10,000 left but 15,000 arrived, the region gained 5,000.`, kind: 'common-error' },
    { content: `**The largest flow into a region does not make it the biggest gainer.** Read the flow one way, then subtract the flow the other way. Byrne received 9,000 but sent 9,000 out (net +3,000). Corvel received only 6,000 but sent only 5,000 out (net +6,000). Corvel gained twice as much.`, kind: 'gotcha' },
    { content: `**Check the table before you write your answer.** Total arrivals must equal total departures. All regional nets must sum to zero. If they don't, you dropped a line or double-counted. This check catches the error before it ruins your conclusion.`, kind: 'tip' },
    { content: `**A condition present at BOTH ends explains nothing.** Both regions have cold winters? Both have universities? That's true but useless—it cannot explain why people moved one way rather than the other. Test every explanation for this trap.`, kind: 'edge-case' },
    { content: `**Push sits at the region people LEFT; pull sits at the region they ARRIVED IN.** Cheap housing where people left is a failed push (they left anyway). Cheap housing where they arrived is a successful pull. Check which end the condition is actually at before labeling it.`, kind: 'vocab-note' },
    { content: `**One year of data answers one year's question.** The interior-to-South-and-West shift is a *decades-long* pattern, so one year's table cannot prove or disprove it. A claim about decades needs many years of data all pointing the same way.`, kind: 'edge-case' },
    { content: `**A table counts moves, not character.** If 6,000 people left Region X, do NOT write 'people from Region X are restless.' The table says what happened (6,000 departed), not who moved or why as an individual trait. Find the *conditions* the table states and test those.`, kind: 'common-error' },
    { content: `**Counterflow is real.** If 12,000 moved from Dunmere to Selby AND 4,000 moved from Selby to Dunmere, Selby's net is 8,000, not 12,000. The 4,000 go back into the 12,000 first. Never ignore the flow running the opposite direction.`, kind: 'vocab-note' },
  ],
};
