/**
 * Grade 8 World Geography — Unit 6 CED 6.3: Carrying Capacity & Ecological Footprint.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.carrying-capacity-and-ecological-footprint.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U6_CARRYING_CAPACITY_AND_ECOLOGICAL_FOOTPRINT: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.carrying-capacity-and-ecological-footprint.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 6,
  cedTopic: '6.3',
  cedTitle: 'Carrying Capacity & Ecological Footprint',
  planId: 'evelyn.ms.m8geo.carrying-capacity-and-ecological-footprint.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.carrying-capacity-and-ecological-footprint.v1' }],
  theory: [
    { loId: 'm8geo.carrying-capacity-and-ecological-footprint', content: `A CAPACITY QUESTION IS A SUBTRACTION WITH TWO SIDES, AND YOU PUT BOTH SIDES ON ONE PERSON BEFORE YOU SUBTRACT. A supply drawn on faster than it is replaced runs short, so the useful question about a place is never whether it uses land but whether it uses more land than it has. The demand side is the ECOLOGICAL FOOTPRINT: the productive land it takes to supply what one person there uses in a year -- the fields the food grows in, the forest the timber comes from, the ground the house and the road sit on -- written in hectares for each person. The supply side is the productive land the place actually holds, and you put it on the same footing by dividing it by the number of people. Ardwell holds 120,000 hectares and has 40,000 residents, so 120,000 divided by 40,000 is 3.0 hectares of its own land for each resident. Its footprint is 2.5 hectares for each resident. 3.0 minus 2.5 is 0.5 hectares to spare for each resident, so Ardwell is WITHIN its own capacity. Scale the gap up to the whole place by multiplying: 0.5 times 40,000 is 20,000 hectares of productive land Ardwell does not need this year.` },
    { loId: 'm8geo.carrying-capacity-and-ecological-footprint', content: `EVERY PLACE IS MEASURED AGAINST ITS OWN LAND, AND THAT IS WHY THE SMALLEST FOOTPRINT IN A TABLE CAN BE THE ONE THAT IS BEYOND. Brightmere has 60,000 residents on 90,000 hectares, and a footprint of 2.0 hectares for each resident -- a SMALLER footprint than Ardwell's 2.5. But 90,000 divided by 60,000 is only 1.5 hectares of its own land for each resident, and 1.5 minus 2.0 is a shortfall of 0.5 hectares for each resident, which is 0.5 times 60,000, or 30,000 hectares. Brightmere is BEYOND its own capacity while Ardwell, using more land for each person, is within. Comparing footprints across places answers a real question -- who uses more land for each person -- but it is not the question "who is beyond", and it never will be, because the answer to that one lives half in the footprint and half in the land.` },
    { loId: 'm8geo.carrying-capacity-and-ecological-footprint', content: `THE SAME DIVISION READ THE OTHER WAY GIVES HOW MANY PEOPLE THE LAND SUPPORTS, AND THAT IS YOUR CHECK. Instead of dividing the land by the people, divide the land by the footprint: Brightmere's 90,000 hectares divided by 2.0 hectares for each person is 45,000 people, against a population of 60,000, so it is 15,000 people beyond what its own land carries. That is the CARRYING CAPACITY of that land at that footprint. Multiply back to check: 45,000 times 2.0 is 90,000, which is the land you started with. Two forms of one division, and they must agree -- if the hectare answer says a shortfall and the people answer says a surplus, a zero slipped somewhere and you go back.` },
    { loId: 'm8geo.carrying-capacity-and-ecological-footprint', content: `CAPACITY IS NOT A NUMBER A PLACE HAS; IT IS A NUMBER THREE INPUTS PRODUCE, AND A FOURTH MOVE CLOSES THE SUM WITHOUT TOUCHING ANY OF THEM. The three inputs are the footprint, the land, and the number of people, and each one moves the answer on its own. Change the FOOTPRINT: a change in how Brightmere's cropland is farmed that lowers it from 2.0 to 1.5 hectares makes 90,000 divided by 1.5 equal 60,000 people, exactly its population, and the shortfall closes. Change the LAND: give Brightmere 120,000 hectares instead of 90,000 and 120,000 divided by 2.0 is also 60,000 people, with nothing about a resident changed. Change the NUMBER OF PEOPLE: at 90,000 hectares and a footprint of 2.0 the land carries 45,000, so a Brightmere of 45,000 residents would sit exactly at capacity on the same land with the same habits. Then the fourth move, which is not an input at all: import what was grown somewhere else, and the sum inside the border closes while the footprint, the land and the population all stand exactly where they were. So there is no such thing as the carrying capacity of a place. There is only the capacity of THIS land, at THIS footprint, for THIS many people, and a figure that does not say which three is not yet a figure.` },
    { loId: 'm8geo.carrying-capacity-and-ecological-footprint', content: `AN OVERSHOOT CLAIM IS A CLAIM ABOUT A BOUNDARY, SO FIND THE EDGE OF THE SUM BEFORE YOU AGREE WITH IT. When someone says a place lives inside its means, ask what was counted: the land inside the border only, or all the land the residents' consumption uses wherever that land sits. Both sums are real and both can be right at the same time about the same place, which is exactly why the claim has to say which one it ran. A place whose imports cover 0.5 hectares for each resident has closed its inside-the-border books and moved 0.5 hectares for each of its residents onto somebody else's books, and the residents' footprint has not changed by a single hectare. The one-line test to carry out of here: a balance is only as wide as the boundary drawn around it, so say which boundary, every time.` },
    { loId: 'm8geo.carrying-capacity-and-ecological-footprint', content: `READ THE VERDICT AS A MEASUREMENT OF LAND, NOT AS A SCORE FOR A PLACE. Within and beyond are the results of a subtraction between two quantities of hectares. They are not grades, and neither one is a statement about the people who live there or how they behave. How much productive land a place holds depends on rock, slope, water and latitude, which nobody chose, and why a footprint is the size it is depends on what the work of that place is and what living there takes -- and the subtraction tells you neither. Two figures, one subtraction, one verdict about hectares -- and then the interesting question, which is always which of those inputs could move and what moving it would take.` },
    { loId: 'm8geo.carrying-capacity-and-ecological-footprint', kind: 'definition', title: 'ecological footprint', content: `the productive land it takes to supply what one person uses in a year, written in hectares for each person so that two places can be set side by side.` },
    { loId: 'm8geo.carrying-capacity-and-ecological-footprint', kind: 'definition', title: 'productive land', content: `land that produces something people use -- crops, grazing, timber -- or that their buildings and roads stand on, counted in hectares.` },
    { loId: 'm8geo.carrying-capacity-and-ecological-footprint', kind: 'definition', title: 'hectare', content: `a unit of area equal to 10,000 square meters, which is a square 100 meters on each side.` },
    { loId: 'm8geo.carrying-capacity-and-ecological-footprint', kind: 'definition', title: 'carrying capacity', content: `how many people a stated area of productive land supports at a stated footprint, found by dividing the land by the footprint for each person.` },
    { loId: 'm8geo.carrying-capacity-and-ecological-footprint', kind: 'definition', title: 'overshoot', content: `the amount by which the land a population demands exceeds the land available to it, found by subtracting the second from the first.` },
  ],
  methods: [
    {
      title: 'Worked three places own balance',
      steps: [
        `Do not start by comparing the footprints, which is what the eye wants to do. Brightmere and Caldon are both at 2.0 and Ardwell is at 2.5, and that comparison is going to turn out to say nothing about who is beyond. Start instead by giving every place its own land, one resident at a time.`,
        `Land for each resident. Ardwell: 120,000 divided by 40,000 is 3.0 hectares. Brightmere: 90,000 divided by 60,000 is 1.5 hectares. Caldon: 50,000 divided by 25,000 is 2.0 hectares.`,
        `Subtract, place by place. Ardwell: 3.0 minus 2.5 leaves 0.5 hectares spare for each resident, so Ardwell is WITHIN. Brightmere: 1.5 minus 2.0 is a shortfall of 0.5 hectares for each resident, so Brightmere is BEYOND. Caldon: 2.0 minus 2.0 is zero, so Caldon sits EXACTLY at its capacity.`,
        `Scale each gap up to the whole place, because hectares for each person are hard to picture. Ardwell: 0.5 times 40,000 is 20,000 hectares spare. Brightmere: 0.5 times 60,000 is 30,000 hectares short. Caldon: zero times 25,000 is zero.`,
        `Invert every division before going further. Total demand is the footprint times the residents. Ardwell: 2.5 times 40,000 is 100,000 hectares demanded against 120,000 held, and 120,000 minus 100,000 is 20,000 spare -- the same figure. Brightmere: 2.0 times 60,000 is 120,000 demanded against 90,000 held, and 120,000 minus 90,000 is 30,000 short -- the same figure. Caldon: 2.0 times 25,000 is 50,000 demanded against 50,000 held, and the difference is zero. Every per-resident answer is recovered from the whole-place side, so no zero slipped.`,
        `Name the number that misleads. It is the footprint read on its own. WRONG: "Brightmere and Caldon both use 2.0 hectares for each resident, so they are in the same position, and Ardwell at 2.5 is the one in trouble." CORRECT: "Brightmere is 30,000 hectares beyond, Caldon is exactly balanced and Ardwell is 20,000 hectares within, because the two places at 2.0 hold 1.5 and 2.0 hectares for each resident and Ardwell holds 3.0."`,
        `Rewind the input and read the three lines backwards to confirm nothing was misread: 2.0, 50,000, 25,000; 2.0, 90,000, 60,000; 2.5, 120,000, 40,000. Then change ONE input so the result is not memorized as a fact about Brightmere. Suppose Brightmere held 120,000 hectares of productive land instead of 90,000, with the same 60,000 residents and the same footprint. 120,000 divided by 60,000 is 2.0 hectares for each resident, 2.0 minus 2.0 is zero, and Brightmere is now exactly at capacity; the check is 2.0 times 60,000, which is 120,000, the land it now has. Nobody changed what a resident of Brightmere uses. The supply side moved, and the verdict moved with it, which is what it means to say that a capacity is produced by inputs rather than owned by a place.`,
      ],
      example: { problem: `Work out whether each place is within or beyond its own capacity, and say which of the three numbers given for each place is the one that misleads.

"Ardwell: 40,000 residents, 120,000 hectares of productive land, footprint 2.5 hectares for each resident.

Brightmere: 60,000 residents, 90,000 hectares of productive land, footprint 2.0 hectares for each resident.

Caldon: 25,000 residents, 50,000 hectares of productive land, footprint 2.0 hectares for each resident."`, solution: `Ardwell is within its capacity by 20,000 hectares: 120,000 divided by 40,000 is 3.0 hectares for each resident against a footprint of 2.5, and 0.5 times 40,000 is 20,000. Brightmere is beyond by 30,000 hectares: 90,000 divided by 60,000 is 1.5 against a footprint of 2.0, and 0.5 times 60,000 is 30,000. Caldon is exactly at capacity: 50,000 divided by 25,000 is 2.0 against a footprint of 2.0. Multiplying each footprint by its population recovers demands of 100,000, 120,000 and 50,000 hectares, which reproduces all three verdicts. The misleading number is the footprint read on its own, because the place with the smaller footprint is the one that is beyond. Give Brightmere 120,000 hectares and it sits exactly at capacity with nothing else changed.` },
      relatedLoIds: ['m8geo.carrying-capacity-and-ecological-footprint'],
    },
    {
      title: 'Worked two buttons one number',
      steps: [
        `Run change one. The demand side falls: 1.5 times 60,000 is 90,000 hectares, against 90,000 hectares of land, so the balance is exactly zero. Read it the other way as a check: 90,000 divided by 1.5 is 60,000 people supported, which is exactly the population, and 60,000 times 1.5 is 90,000, which recovers the land. The capacity of Brightmere's land rose from 45,000 people to 60,000 without one hectare being added.`,
        `Run change two. The footprint is still 2.0 hectares for each resident, so total demand is still 2.0 times 60,000, which is 120,000 hectares. What changed is where 0.5 hectares for each resident comes from: 0.5 times 60,000 is 30,000 hectares, and those 30,000 hectares are in Dunmere. The land drawn on inside Brightmere is therefore 1.5 times 60,000, which is 90,000 hectares -- exactly what Brightmere holds. Add the two pieces back: 90,000 inside plus 30,000 outside is 120,000, which is the demand the first line gave.`,
        `Notice that both changes produce the same inside-the-border number, 90,000 hectares against 90,000 hectares, and that the sentence "Brightmere now lives inside its capacity" is reported the same way after each. So the number cannot be what tells them apart. Something else has to.`,
        `Check the first kind of evidence: the arithmetic of Brightmere's own land. In both cases it closes at 90,000 against 90,000, and in both cases the inversion holds -- 1.5 times 60,000 is 90,000. On this evidence alone the two changes are identical and the sentence is true twice.`,
        `Check a second kind of evidence, which is a quantity from outside the boundary. Under change one there is no outside quantity at all. Under change two there are 30,000 hectares in Dunmere producing for Brightmere residents, and that number appears in nobody's sum when Brightmere adds up its own land. Dunmere itself still has room -- 2.0 times 50,000 is 100,000 hectares for its own residents, plus the 30,000 exported is 130,000, against 200,000 hectares held, so Dunmere is 70,000 hectares within -- but the 30,000 hectares exist and are doing work for Brightmere either way.`,
        `Check a third kind of evidence, which is an input that did NOT move. Under change one the footprint fell from 2.0 to 1.5 hectares, so what each resident uses is genuinely smaller. Under change two the footprint is still 2.0 hectares, exactly what it was before the change, so nothing at all about Brightmere's demand moved. Three kinds of evidence -- a closed inside-the-border sum, a 30,000-hectare quantity that sits outside it, and an unchanged demand figure -- and they point one way: one number is a hunch, three of different kinds all pointing the same way is evidence.`,
        `Give the verdict, and make it about the sentence rather than about Brightmere. After change one the sentence is true on both readings: the land inside the border carries the residents, and the residents' total demand is 90,000 hectares. After change two the sentence is true of Brightmere's own land and false of what Brightmere's residents use, which is still 120,000 hectares. WRONG: "Change two means Brightmere stopped overshooting." CORRECT: "Change two moved 30,000 hectares of the demand onto land in Dunmere and left the demand itself at 2.0 hectares for each resident; the claim counted the land inside the border and left out the land outside it." Neither verdict says anything about the people of Brightmere or of Dunmere; both are statements about hectares and about which boundary a sum used.`,
      ],
      example: { problem: `Brightmere is 30,000 hectares beyond its own land. Two different changes are proposed, and both of them are reported afterward as "Brightmere now lives inside its capacity". Work out what each change does to the numbers, then judge that sentence.

"Brightmere before either change: 60,000 residents, 90,000 hectares of productive land, footprint 2.0 hectares for each resident.

Change one: a change in how Brightmere's cropland is farmed means each resident's needs now take 1.5 hectares instead of 2.0. Nothing else moves.

Change two: the footprint stays at 2.0 hectares. Brightmere imports the food and timber that account for 0.5 hectares for each resident, grown in Dunmere. Dunmere has 50,000 residents, 200,000 hectares of productive land, and a footprint of 2.0 hectares for each resident."`, solution: `Change one lowers the demand: 1.5 times 60,000 is 90,000 hectares against 90,000 held, so the balance closes, and the land now supports 90,000 divided by 1.5, which is 60,000 people, exactly the population. Change two leaves the demand at 2.0 times 60,000, which is 120,000 hectares, and moves 0.5 times 60,000, which is 30,000 hectares, onto land in Dunmere; the land used inside Brightmere is 1.5 times 60,000, which is 90,000, and 90,000 plus 30,000 recovers the 120,000. The sentence "Brightmere now lives inside its capacity" is true both ways after change one, and after change two it is true of the land inside the border and false of the land its residents use. Dunmere, at 100,000 hectares for its own residents plus 30,000 exported against 200,000 held, is 70,000 hectares within.` },
      relatedLoIds: ['m8geo.carrying-capacity-and-ecological-footprint'],
    },
  ],
  pointers: [
    { content: `Students often say "Brightmere uses less land for each resident than Ardwell, so Brightmere is the one living within its means." — The footprint is only half of each balance, and the two places do not hold the same land. Ardwell: 120,000 hectares divided by 40,000 residents is 3.0 hectares for each resident, and 3.0 minus 2.5 leaves 0.5 spare, which is 0.5 times 40,000, or 20,000 hectares within. Brightmere: 90,000 divided by 60,000 is 1.5 hectares for each resident, and 1.5 minus 2.0 is a shortfall of 0.5, which is 0.5 times 60,000, or 30,000 hectares beyond. Check by the other route: 2.5 times 40,000 is 100,000 demanded against 120,000 held, and 2.0 times 60,000 is 120,000 demanded against 90,000 held. WRONG: "The smaller footprint is the one within its means." CORRECT: "Ardwell is 20,000 hectares within on a footprint of 2.5, and Brightmere is 30,000 hectares beyond on a footprint of 2.0, because Ardwell holds twice as much land for each resident." Each place is measured against its own land, and a footprint read on its own can put the places in the opposite order from the balance.`, kind: 'common-error' },
    { content: `Students often say "Buying the food from Dunmere means those 30,000 hectares stop being used, so the demand falls to 90,000 hectares." — The food still has to grow on something. Brightmere's footprint is unchanged at 2.0 hectares for each resident, so the demand is still 2.0 times 60,000, which is 120,000 hectares. What the import changes is where 0.5 times 60,000, or 30,000, of those hectares sit: they are in Dunmere, which is why Brightmere's own land now carries 1.5 times 60,000, or 90,000 hectares, exactly what it holds. Add them back and 90,000 plus 30,000 is 120,000, the number you started from. WRONG: "The imported hectares stop being used." CORRECT: "The imported hectares are being used in Dunmere, and Brightmere's inside-the-border sum simply stops counting them." Dunmere can carry them -- 2.0 times 50,000 is 100,000 hectares for its own residents, plus 30,000 exported is 130,000 against the 200,000 hectares it holds, so it is 70,000 hectares within -- but a hectare that moved across a boundary is still a hectare in use, and an overshoot claim has to say which boundary its sum used.`, kind: 'common-error' },
    { content: `A capacity question is a subtraction with two sides. Divide the place's productive land by its people to get hectares for each person, set that against the footprint for each person, and subtract: positive is within, negative is beyond.`, kind: 'tip' },
    { content: `Scale the per-person gap up to the whole place by multiplying it by the population, and check it the other way by multiplying the footprint by the population and comparing that demand with the land held.`, kind: 'tip' },
    { content: `Every place is measured against its own land, never against another place's footprint. The smaller footprint in a table can belong to the place that is beyond, because the other half of the balance is how much land there is.`, kind: 'tip' },
    { content: `Divide the land by the footprint instead and you get how many people that land supports: 90,000 hectares divided by 2.0 hectares for each person is 45,000 people. Multiply back and the land has to return.`, kind: 'tip' },
    { content: `There is no carrying capacity of a place, only the capacity of this land, at this footprint, for this many people. Change any one of the three and the number moves.`, kind: 'tip' },
    { content: `A change in farming or technology lowers what each person's needs take; an import changes which land is drawn on and leaves the footprint exactly where it was. Both can close the same inside-the-border sum.`, kind: 'tip' },
    { content: `An overshoot claim is a claim about a boundary. Ask which land the sum counted, because a balance is only as wide as the boundary drawn around it.`, kind: 'tip' },
    { content: `Within and beyond are measurements of hectares against hectares. They are never a grade for a place or a statement about the people who live there.`, kind: 'tip' },
  ],
};
