/**
 * Grade 8 World Geography — Unit 3 CED 3.3: North America: River Systems & Watersheds.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8geo.north-america-river-systems-and-watersheds.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8GEO_U3_NORTH_AMERICA_RIVER_SYSTEMS_AND_WATERSHEDS: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8geo.north-america-river-systems-and-watersheds.v1',
  course: 'Grade 8 World Geography',
  cedUnit: 3,
  cedTopic: '3.3',
  cedTitle: 'North America: River Systems & Watersheds',
  planId: 'evelyn.ms.m8geo.north-america-river-systems-and-watersheds.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8geo.north-america-river-systems-and-watersheds.v1' }],
  theory: [
    { loId: 'm8geo.north-america-river-systems-and-watersheds', content: `THE ROUTINE, IN ORDER, AND IT IS THE SAME EVERY TIME. A tributary joins a larger river instead of reaching the sea on its own, so tracing a drop is walking a chain of junctions, one link at a time. One: find the drop against the nearest divide and say which side of it the drop is on. Two: name the stream that carries water off that side. Three: follow that stream to the first river it joins, then follow that river to the next junction, and keep going downstream. Four: if the chain reaches a lake, do not stop -- find the lake's outlet and carry on from there. Five: name the ocean, gulf or sea the last river empties into. Then rewind: start at the mouth, read the chain backwards to the drop, and check that every link still connects.` },
    { loId: 'm8geo.north-america-river-systems-and-watersheds', content: `THE SIDE OF THE DIVIDE DECIDES, AND DISTANCE PROVES NOTHING. A divide is a ridge line, and the only question it asks of a location is which of its two slopes the water runs down. Two points one step apart on opposite sides of a single crest send their water to different oceans. A place four hundred kilometers from the nearest coast can drain to that coast, and a place five kilometers from a coast can drain away from it for two thousand kilometers to a different ocean, because a ridge stands in between. So "which ocean is nearest" is the wrong question, and the answer it gives is the one the ridge was hiding. Find the crest line in the description first, put the location on one side of it, and only then ask where the water goes.` },
    { loId: 'm8geo.north-america-river-systems-and-watersheds', content: `A CONFLUENCE ADDS, SO THE TOTAL GOES UP AT EVERY JUNCTION AND NEVER DOWN. The land that drains through a point on a river is that point's upstream drainage area, and at a junction the areas of the two joining branches add together. A branch draining 4,000 square kilometers meeting a branch draining 6,000 gives 10,000 square kilometers draining through the junction -- not 6,000, and not the average of the two. Check by taking the sum apart again: 10,000 minus 6,000 is 4,000, which is the branch you started with. The same addition gives you the SHARE of a river mouth's basin that has already passed an inland point: divide the area above that point by the area at the mouth. Ten thousand square kilometers out of a 20,000-square-kilometer basin is 10,000 divided by 20,000, which is 50 percent, and the check is that 50 percent of 20,000 is 10,000.` },
    { loId: 'm8geo.north-america-river-systems-and-watersheds', content: `A LAKE IS A GATE, NOT AN END, SO FIND THE OUTLET BEFORE YOU ANSWER. Water that reaches a lake with an outlet has not arrived anywhere. It has been slowed down and then handed to a single channel, and every drop that entered that lake from any of its feeding rivers leaves by that same channel. That is what makes a lake outlet the narrowest point in a whole drainage network. Only a lake with NO outlet ends a chain, and a description will say so in as many words. When your trace hits a lake, the next line to look for in the description is the one that names what flows out of it.` },
    { loId: 'm8geo.north-america-river-systems-and-watersheds', content: `THE THREE PLACES A NETWORK NARROWS ARE THE THREE PLACES THE BIG INLAND CITIES SIT. A confluence is where two routes become one, so everything moving on either branch has to pass it. A lake outlet is where a whole lake's worth of traffic is squeezed into one channel. A river mouth is where the vessel itself has to change -- a break-of-bulk point -- so every cargo that came down the river is unloaded and handled in the same place. Those are not three separate reasons; they are one reason three times over, which is that the site collects traffic with no other way through. So candidate sites are ranked by asking, for each one, how much of the network must pass it, and that is a number you can read straight off the described network.` },
    { loId: 'm8geo.north-america-river-systems-and-watersheds', content: `CHANGE ONE INPUT AND RUN THE TRACE AGAIN, BECAUSE THE ANSWER LIVES IN THE NETWORK AND NOT IN THE PLACE. Move the crest of a divide a few kilometers and a whole valley changes ocean. Take one tributary out of a basin and every share below the junction where it used to join has to be worked out again. Nothing moved on the ground except one link, and the destination, the shares and the best site for a port can all change together. Running it a second time with one input altered is the test that you traced the network instead of guessing from the name of a place.` },
    { loId: 'm8geo.north-america-river-systems-and-watersheds', kind: 'definition', title: 'watershed', content: `all the land whose water drains through one common point, so what puts a piece of land inside it is where a drop from that land ends up.` },
    { loId: 'm8geo.north-america-river-systems-and-watersheds', kind: 'definition', title: 'continental divide', content: `a ridge line whose two slopes send their water to different oceans, used to sort a location into one basin or the other.` },
    { loId: 'm8geo.north-america-river-systems-and-watersheds', kind: 'definition', title: 'confluence', content: `the point where two streams join into one channel, and therefore the point at which their upstream drainage areas add together.` },
    { loId: 'm8geo.north-america-river-systems-and-watersheds', kind: 'definition', title: 'outlet', content: `the single channel by which a lake passes its water downstream, through which everything the lake received has to leave.` },
    { loId: 'm8geo.north-america-river-systems-and-watersheds', kind: 'definition', title: 'upstream drainage area', content: `the total area of land that drains through a chosen point on a river, found by adding the areas of every branch above that point.` },
  ],
  methods: [
    {
      title: 'Worked trace three drops',
      steps: [
        `Drop one, link by link, downstream. The creek runs into the Monongahela. The Monongahela and the Allegheny join at Pittsburgh and form the Ohio. The Ohio joins the Mississippi at Cairo. The Mississippi empties into the Gulf of Mexico. That is three junctions passed -- creek into Monongahela, Monongahela into Ohio, Ohio into Mississippi -- and the answer is the Gulf of Mexico.`,
        `Drop two, and this is where a trace usually stops too early. Lake Erie is a lake, so look for its outlet rather than writing down an answer: the Niagara carries Lake Erie's water into Lake Ontario. Lake Ontario is a lake too, so look again: its outlet is the St. Lawrence, which reaches the Atlantic Ocean. WRONG: "Lake Erie, because that is the first large body of water the drop reaches." CORRECT: "The Atlantic Ocean, because both lakes on this chain have outlets, and a lake with an outlet is a gate rather than an end."`,
        `Drop three, and here the temptation is to measure. Do not measure to a coast; read the side. The snowfield lies 200 meters WEST of the crest, so it is on the western slope, so its meltwater joins the Columbia system, and the Columbia reaches the Pacific Ocean. The 200 meters is not what settles it -- 2 meters or 200 kilometers west of the crest would settle it the same way.`,
        `The same two questions -- which side, then which chain -- settle the rest of the continent, and it is worth saying the four big answers out loud. West of the Divide, the Columbia network drains to the Pacific Ocean and the Colorado network drains toward the Gulf of California, on the Pacific side of the continent. East of it, the Mississippi system, fed by the Missouri and the Ohio, drains to the Gulf of Mexico. In the northeast, the Great Lakes drain through the St. Lawrence to the Atlantic. In the far north, the Mackenzie runs north out of Great Slave Lake to the Beaufort Sea, which is part of the Arctic Ocean -- another lake outlet, traced exactly the same way.`,
        `Rewind each chain and read it backwards from the mouth. Gulf of Mexico, up the Mississippi, up the Ohio at Cairo, up the Monongahela at Pittsburgh, up the creek to the farm: every link connects. Atlantic Ocean, up the St. Lawrence, into Lake Ontario, up the Niagara, into Lake Erie: every link connects. Pacific Ocean, up the Columbia, up to the western slope of the Divide: every link connects.`,
        `Now change ONE input. Move drop three 400 meters east, so that it lands 200 meters east of the same crest instead of 200 meters west of it. Nothing about the snowfield has changed except which slope it sits on. The meltwater now joins the Missouri, the Missouri joins the Mississippi just above St. Louis, and the water finishes in the Gulf of Mexico -- the same water body as drop one, which started most of a continent away in western Pennsylvania.`,
        `The check to remember. A 400-meter move across one crest changed the ocean, while a farm most of a continent away shares an ocean with the moved drop. Distance decided nothing in either case. The side of the ridge decided everything, and the chain of junctions did the rest.`,
      ],
      example: { problem: `Run the trace straight through on three positions in North America, and name the water body each one reaches.

"Drop one falls on a farm in the hills of western Pennsylvania, on a creek that runs into the Monongahela River. The Monongahela meets the Allegheny at Pittsburgh, and the two together form the Ohio River. The Ohio runs southwest and joins the Mississippi at Cairo, Illinois. The Mississippi runs south to the Gulf of Mexico.

Drop two falls on the northern shore of Lake Erie. Lake Erie drains through the Niagara River into Lake Ontario, and Lake Ontario drains through the St. Lawrence River.

Drop three falls on a snowfield on the crest of the Continental Divide in the northern Rocky Mountains, along a stretch where the western slope drains into the Columbia system and the eastern slope drains into the Missouri. The snowfield lies 200 meters west of the crest."`, solution: `Drop one reaches the Gulf of Mexico: creek into the Monongahela, Monongahela and Allegheny into the Ohio at Pittsburgh, Ohio into the Mississippi at Cairo, Mississippi into the Gulf. Drop two reaches the Atlantic Ocean: Lake Erie out through the Niagara into Lake Ontario, Lake Ontario out through the St. Lawrence -- neither lake is an end, because both have outlets. Drop three reaches the Pacific Ocean, because 200 meters west of the crest puts it on the western slope and the western slope feeds the Columbia. Moved 400 meters east, so that it sits 200 meters east of the same crest, that drop feeds the Missouri instead and finishes in the Gulf of Mexico.` },
      relatedLoIds: ['m8geo.north-america-river-systems-and-watersheds'],
    },
    {
      title: 'Worked add the basin and place the port',
      steps: [
        `Work downstream and add at every junction, because a confluence adds. At Hale the Aldon and the Brix meet: 3,000 plus 5,000 is 8,000 square kilometers draining through Hale. At Merrow the Cleave joins: 8,000 plus 2,000 is 10,000 square kilometers draining through Merrow. At Sandell the Dray joins: 10,000 plus 10,000 is 20,000 square kilometers draining through Sandell, which is the whole basin.`,
        `Get the total a second way as a check, by adding the four streams straight across: 3,000 plus 5,000 plus 2,000 plus 10,000 is 20,000 square kilometers. The two routes to the total agree, so no junction was skipped and no area was counted twice.`,
        `Turn each stream into a share of the basin by dividing its area by the 20,000 at the mouth. Aldon: 3,000 divided by 20,000 is 0.15, which is 15 percent. Brix: 5,000 divided by 20,000 is 0.25, which is 25 percent. Cleave: 2,000 divided by 20,000 is 0.10, which is 10 percent. Dray: 10,000 divided by 20,000 is 0.50, which is 50 percent.`,
        `Invert the shares two ways. Add them: 15 plus 25 plus 10 plus 50 is 100 percent, so nothing has been lost and nothing double counted. Then multiply one back out: 50 percent of 20,000 is 10,000 square kilometers, which is the Dray's area exactly as it was given.`,
        `Now the settlement question, and the same numbers answer it. Merrow has 10,000 square kilometers above it, which is 10,000 divided by 20,000, or 50 percent of the basin, and every barge coming off the Aldon, the Brix or the Cleave has to pass it. Hale has only 8,000 above it, which is 8,000 divided by 20,000, or 40 percent, because the Cleave joins below Hale and never passes it. WRONG: "Hale is the hub, because Hale is where two rivers meet and only one river joins at Merrow." CORRECT: "Merrow is the hub, because 50 percent of the basin drains through Merrow against 40 percent through Hale, and a junction is worth what it gathers, not how many channels meet there."`,
        `Sandell is the port, and its reason is a second reason on top of Merrow's. All 20,000 square kilometers, which is 100 percent of the basin, drain through Sandell, so it gathers more than any inland site can. And it is the point where ocean ships stop, so every cargo leaving the basin by water is unloaded from one kind of vessel and loaded onto another right there. Merrow collects. Sandell collects and transfers.`,
        `Rewind the input and read the basin backwards to be sure nothing was misread. Sandell 20,000, of which the Dray brought 10,000; Merrow 10,000, of which the Cleave brought 2,000; Hale 8,000, made of the Brix at 5,000 and the Aldon at 3,000. Every subtraction returns a stream: 20,000 minus 10,000 is 10,000, 10,000 minus 2,000 is 8,000, and 8,000 minus 5,000 is 3,000.`,
        `Now change ONE input. Suppose the Dray had risen on the far side of the ridge that bounds its valley, so that its whole 10,000 square kilometers drained to a different sea. Sandell would then stand at the mouth of a 10,000-square-kilometer basin instead of a 20,000-square-kilometer one, and Merrow's 10,000 would be 10,000 divided by 10,000, which is 100 percent of everything reaching the port, up from 50 percent. Not one river inside the basin changed course. One ridge moved, and the inland hub went from handling half the traffic to handling all of it.`,
      ],
      example: { problem: `Add up a described basin, then say where its inland hub and its port belong.

"On an invented coast, the Corran River reaches the Amber Sea. Four streams feed it. The Aldon drains 3,000 square kilometers and the Brix drains 5,000 square kilometers; they meet at the town of Hale, and below Hale the joined river is called the Corran. The Cleave drains 2,000 square kilometers and joins the Corran at the town of Merrow. The Dray drains 10,000 square kilometers and joins the Corran at Sandell, the town standing where the river meets the sea. No other stream joins the Corran anywhere. Barges can travel all four streams and the Corran; ocean ships can reach Sandell and no further inland."

Find the upstream drainage area at Hale, at Merrow and at Sandell, give each stream its share of the basin, and say which town is the inland hub and which is the port.`, solution: `Upstream drainage area: Hale 8,000 square kilometers (3,000 plus 5,000), Merrow 10,000 (8,000 plus 2,000), Sandell 20,000 (10,000 plus 10,000), and adding the four streams straight across gives the same 20,000. Shares of the basin: Aldon 15 percent, Brix 25 percent, Cleave 10 percent, Dray 50 percent, which sum to 100 percent. Merrow is the inland hub, with 50 percent of the basin above it against 40 percent above Hale. Sandell is the port, because 100 percent of the basin drains through it and it is also the point where cargo has to move between barge and ocean ship. If the Dray drained to a different sea, Sandell would gather 10,000 square kilometers and Merrow would rise from 50 percent to 100 percent of what reaches the port.` },
      relatedLoIds: ['m8geo.north-america-river-systems-and-watersheds'],
    },
  ],
  pointers: [
    { content: `Students often say "Below Farrow the river drains 7,000 square kilometers, because the Odell is the bigger of the two rivers that join there." — At a confluence the upstream drainage areas add. 4,000 plus 7,000 is 11,000 square kilometers draining through the river below Farrow, and the check is to take the sum apart again: 11,000 minus 7,000 is 4,000, which is the Wyre, and 11,000 minus 4,000 is 7,000, which is the Odell. WRONG: "The bigger branch sets the total below the junction." CORRECT: "Both branches set it, because every drop from both of them passes the same channel below Farrow, and 4,000 plus 7,000 is 11,000." That the Odell is the larger branch is true, and it answers a different question: the Odell supplies 7,000 of the 11,000 and the Wyre supplies 4,000, and those two supplies add back to 11,000. Being the larger branch never subtracts the smaller one from the total.`, kind: 'common-error' },
    { content: `Students often say "Ives is 5 kilometers from the west coast, so its water reaches the western ocean." — Ives sits on the EASTERN slope of the coastal ridge, so its streams run east, away from the coast that is 5 kilometers off, into the Verrin, and the Verrin empties into the eastern ocean. WRONG: "Five kilometers from the west coast, so the water goes west." CORRECT: "The ridge stands between Ives and the west coast, so the water runs down the eastern slope and crosses the whole country to the eastern ocean." The distance to a coast is a fact about how far something is, never a fact about where water goes; the side of the divide is the fact that does the work, and the description states it in the very same sentence that gives the distance.`, kind: 'common-error' },
    { content: `Trace in order: which side of the divide, which stream carries that side, which river it joins, and what the last river empties into. If the chain hits a lake, find the outlet and keep going.`, kind: 'tip' },
    { content: `The side of a ridge decides the ocean. Two points a step apart on opposite slopes finish on different coasts, and a place close to one coast can drain away from it for the width of a continent.`, kind: 'tip' },
    { content: `A confluence adds. The upstream drainage area at a junction is the sum of the branches above it: 3,000 plus 5,000 is 8,000, and 8,000 minus 5,000 returns the 3,000.`, kind: 'tip' },
    { content: `A share of a basin is the area above a point divided by the area at the mouth. 10,000 out of 20,000 is 50 percent, and the check is that 50 percent of 20,000 is 10,000.`, kind: 'tip' },
    { content: `A lake with an outlet is a gate, not an end. Everything that entered the lake leaves through that one channel, which is what makes an outlet the narrowest point in a network.`, kind: 'tip' },
    { content: `The largest inland cities sit at confluences, lake outlets and river mouths for one reason three times over: those are the points every route has to pass. A mouth adds one more thing on top, which is the transfer between river vessel and ocean vessel.`, kind: 'tip' },
    { content: `Change one input and run the trace again. Move a crest, or take one tributary out of the basin, and the destination, the shares and the best site can all change while nothing else moves at all.`, kind: 'tip' },
  ],
};
