/**
 * Grade 8 Science — Unit 10 CED 10.3: Light versus Sound & the Electromagnetic Spectrum.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.light-versus-sound-and-the-electromagnetic-spectrum.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U10_LIGHT_VERSUS_SOUND_AND_THE_ELECTROMAGNETIC_SPECTRUM: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.light-versus-sound-and-the-electromagnetic-spectrum.v1',
  course: 'Grade 8 Science',
  cedUnit: 10,
  cedTopic: '10.3',
  cedTitle: 'Light versus Sound & the Electromagnetic Spectrum',
  planId: 'evelyn.ms.m8sci.light-versus-sound-and-the-electromagnetic-spectrum.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.light-versus-sound-and-the-electromagnetic-spectrum.v1' }],
  theory: [
    { loId: 'm8sci.light-versus-sound-and-the-electromagnetic-spectrum', content: `SOUND IS A MECHANICAL WAVE, AND A MECHANICAL WAVE IS A DISTURBANCE PASSED ALONG BY MATTER. You already know this from the lesson on what a wave is, so it is here as a reminder and not as new ground. A sound travels because one bit of matter pushes the next bit, which pushes the next, all the way to your ear. Any matter will do: sound travels through the air in a room, through the water in a fish tank, and through a solid wooden door. What sound cannot do is travel where there is no matter at all. A region with no matter in it is called a vacuum, and outer space is very nearly one. Be careful how you say the result, because the everyday words are too weak for it. A sound in a vacuum is not quiet, and it is not muffled. There is no sound, because there is nothing there to do the passing along.` },
    { loId: 'm8sci.light-versus-sound-and-the-electromagnetic-spectrum', content: `LIGHT IS NOT A WAVE IN MATTER, AND THAT SINGLE FACT IS THE WHOLE DIFFERENCE. Light crosses a vacuum without any trouble, which is how sunlight reaches Earth through nothing. So light cannot be a disturbance passed along by matter, because there is no matter out there to pass it. A light wave is a traveling pattern of electric and magnetic effects, and a pattern of electric and magnetic effects does not need matter to exist in. That is exactly where the name comes from: light is an ELECTROMAGNETIC WAVE. One qualifier keeps the rule honest, and people get it wrong in both directions. "Light does not need matter" does not mean "light cannot cross matter" -- light travels perfectly well through air, through water and through a sheet of glass. It means that matter is optional for light and required for sound.` },
    { loId: 'm8sci.light-versus-sound-and-the-electromagnetic-spectrum', content: `THE TWO SPEED COMPARISONS RUN IN OPPOSITE DIRECTIONS, AND THIS IS THE SLIP TO WATCH FOR. Start with how fast each one is. In empty space light travels about 300,000 kilometers every second, and it goes very nearly that fast through air as well. Sound in air at room temperature travels about 340 meters every second. Those are not close: light is nearly a million times faster, which is why you see a distant flash before you hear it. Now the part that catches people. Sound is FASTER in water and in steel than it is in air, because the particles of a liquid or a solid sit close together and pass the disturbance along sooner. Light is SLOWER in water and in glass than it is in air. WRONG: "Water is thicker than air, so it slows both of them down." CORRECT: "Water speeds sound up and slows light down. The two comparisons point opposite ways, and you have to hold both." The slowing of light in water and glass is the same slowing that made the straw look broken in the last lesson, when the light bends at the surface; here you need only the direction it goes, not the bending.` },
    { loId: 'm8sci.light-versus-sound-and-the-electromagnetic-spectrum', content: `VISIBLE LIGHT IS ONE NARROW BAND OF A MUCH WIDER FAMILY, AND THE FAMILY IS SORTED BY WAVELENGTH. Every member of that family is an electromagnetic wave, and together they are called the ELECTROMAGNETIC SPECTRUM. Laid out from the longest wavelength to the shortest, the order is: radio, microwave, infrared, visible light, ultraviolet, X-ray, gamma. Radio waves have the longest wavelength of all and gamma rays the shortest. The visible band -- the only one your eyes can detect -- is a narrow strip in the middle, and inside that strip the order runs the same way: red has the longest wavelength of the colors you can see and violet the shortest, with orange, yellow, green and blue in between. The two names on either side of the visible band tell you which side they are on. Infrared marks the red edge, just outside the colors on the long-wavelength side; ultraviolet marks the violet edge, just outside them on the short-wavelength side.` },
    { loId: 'm8sci.light-versus-sound-and-the-electromagnetic-spectrum', content: `ONE EVERYDAY USE FOR EACH BAND, SO THE LIST IS NOT SEVEN WORDS TO MEMORIZE. RADIO: a television station's broadcast picked up by a rooftop antenna. MICROWAVE: a microwave oven warming a bowl of food. INFRARED: the warmth you feel on your face standing near a campfire, before you touch anything. VISIBLE LIGHT: the only band your eyes detect, which is the whole of what you see. ULTRAVIOLET: the part of sunlight that reddens skin on a summer afternoon. X-RAY: the image a hospital makes of a broken bone. GAMMA: sterilizing surgical instruments, which kills the germs on them without opening the sealed packet. Every one of those is the same kind of wave as the light you are reading by. They differ in wavelength, and in nothing else about what they are.` },
    { loId: 'm8sci.light-versus-sound-and-the-electromagnetic-spectrum', content: `EVERY ELECTROMAGNETIC WAVE TRAVELS AT THE SAME SPEED IN EMPTY SPACE, SO A SHORTER WAVE IS NOT A FASTER WAVE. A gamma ray and a radio wave set off across a vacuum side by side arrive together. Their wavelengths are wildly different and their speed is identical. This matters because the order you just learned is an order of WAVELENGTH and nothing else -- it is not an order of speed, and it is not a ranking of which one is stronger. So here are the two questions to ask about any wave in this lesson. First: does it need matter to travel? If yes it is a mechanical wave like sound, and a vacuum stops it dead. If no it is an electromagnetic wave like light, and a vacuum does not slow it at all. Second, if it is electromagnetic: where does it sit in the order by wavelength, radio at the long end and gamma at the short end?` },
    { loId: 'm8sci.light-versus-sound-and-the-electromagnetic-spectrum', kind: 'definition', title: 'mechanical wave', content: `a wave that travels by one bit of matter pushing or pulling the next bit, so it needs matter and cannot cross a vacuum. Sound is one.` },
    { loId: 'm8sci.light-versus-sound-and-the-electromagnetic-spectrum', kind: 'definition', title: 'medium', content: 'the matter a mechanical wave travels through -- a gas, a liquid or a solid.' },
    { loId: 'm8sci.light-versus-sound-and-the-electromagnetic-spectrum', kind: 'definition', title: 'vacuum', content: 'a region with no matter in it. Outer space is very nearly a vacuum.' },
    { loId: 'm8sci.light-versus-sound-and-the-electromagnetic-spectrum', kind: 'definition', title: 'electromagnetic wave', content: `a traveling pattern of electric and magnetic effects, which needs no matter and so can cross a vacuum. Light is one.` },
    { loId: 'm8sci.light-versus-sound-and-the-electromagnetic-spectrum', kind: 'definition', title: 'electromagnetic spectrum', content: `the whole family of electromagnetic waves, ordered by wavelength: radio, microwave, infrared, visible, ultraviolet, X-ray, gamma.` },
    { loId: 'm8sci.light-versus-sound-and-the-electromagnetic-spectrum', kind: 'definition', title: 'wavelength', content: `the distance from one point on a wave to the matching point on the next wave; it is what the electromagnetic spectrum is ordered by.` },
  ],
  methods: [
    {
      title: 'Worked flash then bang',
      steps: [
        `Name the two waves and say what each one needs. The bang is a sound, and sound is a mechanical wave, so it needs matter to pass it along -- here that matter is the air between the burst and your ear. The flash is light, and light is an electromagnetic wave, so it needs no matter at all, although it crosses the air quite happily.`,
        `Put the two speeds side by side, and get the units into the same form before comparing them. Light in empty space travels about 300,000 kilometers every second, and very nearly that fast through air. One kilometer is 1,000 meters, so 300,000 kilometers is 300,000 multiplied by 1,000, which gives 300,000,000 meters. Light travels about 300,000,000 meters every second. Sound in air at room temperature travels about 340 meters every second. Both numbers are now in meters per second and can be compared.`,
        `Do the comparison. Dividing 300,000,000 meters per second by 340 meters per second gives about 880,000, so light is nearly a million times faster than sound in air. Over the same stretch of lake, then, the light gets to you so quickly that it feels instant, while the sound spends whole seconds crossing. That is the flash-then-bang gap. Notice what this step does NOT tell you: how far away the shell burst. Working a distance out of the delay needs the wave-speed lesson, and this question does not ask for one.`,
        `Now change the setting to the vacuum of space. WRONG: "In space you would hear the bang later, because the sound has farther to travel." CORRECT: "In space you would never hear the bang at all, because there is no matter between the burst and you for the sound to be passed along by." The flash, meanwhile, arrives exactly as it did over the lake. Nothing about light needed the air.`,
        `Run the check a science answer needs, because there is no arithmetic left to redo. First, three clues of DIFFERENT kinds that agree. The clue from OBSERVATION: the flash comes first for every shell, all evening, never once the other way round -- a one-off might be luck, but a rule that holds every time is telling you something about the two waves and not about that shell. The clue from QUANTITY: the two speeds are about 300,000,000 meters per second and about 340 meters per second, and the division puts them nearly a million to one, which is far more than enough to turn "the same distance" into "several seconds apart". The clue from MECHANISM: something has to carry the bang and the air is the only candidate, while nothing has to carry the flash. An observation, a number and a mechanism, all pointing the same way.`,
        `Second, change one condition at a time and check that the answer moves. Move the burst closer -- almost straight overhead -- and the gap shrinks to almost nothing, because the sound has much less air to cross. Move it to the far end of a much bigger lake and the gap grows. Take the air away completely, which is the space version, and the gap does not just grow: the bang never arrives at all, while the flash is unchanged. The answer moved every single time the setting moved, and it moved on the sound's side each time. That is what tells you the gap belongs to the sound crossing the air, and not to the light being held up by anything.`,
      ],
      example: { problem: `You are watching a fireworks display from the far side of a lake. A shell bursts high over the water. You see the burst as a flash of light, and a few seconds later you hear the bang. It happens in that order for every shell, all evening. Explain why the flash arrives first. Then say what somebody would see and hear if the same shell burst in the vacuum of space instead.`, solution: `The flash arrives first because light is an electromagnetic wave that needs no matter and travels about 300,000 kilometers -- that is 300,000,000 meters -- every second, while the bang is a mechanical wave the air has to carry at about 340 meters every second, nearly a million times slower. If the same shell burst in the vacuum of space, the flash would look exactly the same and the bang would never arrive at all, because there would be no matter between the burst and the watcher to pass the sound along.` },
      relatedLoIds: ['m8sci.light-versus-sound-and-the-electromagnetic-spectrum'],
    },
    {
      title: 'Worked sorting the spectrum',
      steps: [
        `Name the band each description belongs to before ordering anything. The ship calling the coastguard is using RADIO. The phone reaching its tower is using MICROWAVE. The remote control sends its command as INFRARED. A red traffic light is VISIBLE light. The germ-killing lamp is ULTRAVIOLET. The airport bag scanner uses X-RAYS. The narrow medical beam is GAMMA.`,
        `Now put the seven bands in order from the longest wavelength to the shortest: radio, microwave, infrared, visible, ultraviolet, X-ray, gamma. Reading the descriptions back in that order gives the ship's radio call, the phone reaching its tower, the remote control, the red traffic light, the water treatment lamp, the airport bag scanner, and the hospital beam.`,
        `WRONG: "The hospital beam goes first, because it is the most powerful of the seven and a list like this should start with the strongest." CORRECT: "The list is an order of WAVELENGTH and nothing else. Gamma has the shortest wavelength of the seven, so the hospital beam goes last." Sorting this family by how much of a punch each one packs is a different question from sorting it by wavelength, and only the wavelength order is what the word spectrum means here.`,
        `Answer the second half. What all seven have in common is that every one of them is an electromagnetic wave: not one of them needs matter to travel, every one of them would cross a vacuum, and in empty space all seven travel at exactly the same speed. They differ in wavelength and in what we happen to use them for. They do not differ in what kind of thing they are.`,
        `Run the check, with three clues of DIFFERENT kinds that agree on the order. The clue from your own EYES: the only one of the seven you can actually see is the red traffic light, so visible light sits in the middle of the list with bands on both sides of it. The clue from the NAMES: infrared means the band at the red edge and ultraviolet means the band at the violet edge, so the remote control sits just outside the visible band on the long-wavelength side and the water treatment lamp just outside it on the short-wavelength side -- the two names hand you their own positions. The clue from the two FIXED ENDS: radio has the longest wavelength of the whole family and gamma the shortest, so the ship's call is first and the hospital beam is last, which leaves only one place each for the phone (between radio and infrared) and the bag scanner (between ultraviolet and gamma). An eye test, a pair of names and two fixed ends: three different kinds of clue, one order.`,
        `Then change one thing and check that the answer moves. Swap the airport bag scanner for a second television broadcast. That description leaves its place between ultraviolet and gamma and jumps to the very front of the list, ahead of the phone, because the band changed and the band is what the order is built from. Now change the QUESTION instead of the signals: ask for the same seven in order of their speed in empty space, and there is no order to give at all, because all seven travel at the same speed there. The order you built moves when a wavelength moves and vanishes when you stop asking about wavelength, which is exactly what an order by wavelength should do.`,
      ],
      example: { problem: `Seven signals are described here, each by one thing it does. A ship at sea calls the coastguard by radio. A phone reaches the nearest tower. A remote control changes the television channel from across the room. A traffic light shows red. A lamp in a water treatment plant kills germs in the water flowing past it. A scanner at an airport shows what is inside a closed bag. A hospital machine aims a narrow beam at a small growth deep inside a patient. All seven are electromagnetic waves. Put them in order from the longest wavelength to the shortest, and then say what all seven have in common.`, solution: `From the longest wavelength to the shortest: the ship's radio call (radio), the phone reaching its tower (microwave), the remote control (infrared), the red traffic light (visible), the water treatment lamp (ultraviolet), the airport bag scanner (X-ray), the hospital beam (gamma). What all seven have in common is that each one is an electromagnetic wave -- none of them needs matter to travel, and in empty space all seven travel at the same speed.` },
      relatedLoIds: ['m8sci.light-versus-sound-and-the-electromagnetic-spectrum'],
    },
  ],
  pointers: [
    { content: `Students often say "Explosions in space movies are loud, so sound can travel through space." — Sound is a mechanical wave. It travels only by one bit of matter pushing or pulling the next bit, and it stops where the matter stops. Outer space is very nearly a vacuum, so there is nothing out there to pass the vibration along, and a real explosion in space would be completely silent. Say that carefully: not quiet, not muffled, not faint -- silent, with no sound at all. The flash would still reach a camera, because light is an electromagnetic wave and needs no matter. The roar in the movie was added in a studio afterward, for the same reason the music was: it feels right to an audience, and it is not a recording of anything. Notice also that this rule is about matter and nothing else. Astronauts inside a space station hear each other perfectly well, because the station is full of air, and the space a few centimeters away on the other side of that wall carries no sound at all. WRONG: "There is no sound in space because space is so cold and so empty of everything." CORRECT: "There is no sound in space because there is no matter there to carry it."`, kind: 'common-error' },
    { content: `Students often say "Light must be traveling through some invisible material, so space cannot really be empty." — That assumption is the one this lesson breaks. A light wave is not a disturbance of matter at all. It is a traveling pattern of electric and magnetic effects, and such a pattern does not need matter to exist in, which is precisely why light crosses a region that has no matter in it. That is where the name electromagnetic wave comes from, and it is the reasoning behind the standard statement that because light can travel through space, it cannot be a wave in matter. There is no invisible material filling space for light to shake: scientists once expected to find one and searched carefully for it, and it is not there. Light does travel through air, water and glass as well, so "light does not need matter" is not the same claim as "light cannot cross matter" -- but crossing matter is not what makes it a wave, and it is slower when it does. WRONG: "Space must be full of something, or the light could never get here." CORRECT: "Light is not a wave in matter, so it does not need space to be full of anything."`, kind: 'common-error' },
    { content: `Sound is a mechanical wave: it is passed along by matter, so it travels through gases, liquids and solids, and it does not travel at all through a vacuum. A real explosion in space is silent, not quiet.`, kind: 'tip' },
    { content: `Light is an electromagnetic wave: a traveling pattern of electric and magnetic effects, which needs no matter. That is how sunlight reaches Earth through nothing.`, kind: 'tip' },
    { content: `"Light does not need matter" is not "light cannot cross matter". Light travels through air, water and glass too.`, kind: 'tip' },
    { content: `Light in empty space travels about 300,000 kilometers every second, which is 300,000,000 meters every second. Sound in air at room temperature travels about 340 meters every second. Light is nearly a million times faster, which is why the flash comes before the bang.`, kind: 'tip' },
    { content: `The two speed comparisons run in OPPOSITE directions. Sound is FASTER in water and in steel than in air. Light is SLOWER in water and in glass than in air -- the same slowing that bent the light and made the straw look broken in the last lesson.`, kind: 'tip' },
    { content: `Visible light is one narrow band of the electromagnetic spectrum. In order from the longest wavelength to the shortest: radio, microwave, infrared, visible, ultraviolet, X-ray, gamma.`, kind: 'tip' },
    { content: `Inside the visible band the same order holds: red has the longest wavelength you can see and violet the shortest. Infrared marks the red edge of the band and ultraviolet marks the violet edge.`, kind: 'tip' },
    { content: `One use each: radio for a television broadcast, microwave for an oven, infrared for the warmth off a campfire, visible for seeing, ultraviolet for the sunburn in sunlight, X-ray for the image of a broken bone, gamma for sterilizing surgical instruments.`, kind: 'tip' },
    { content: `Every electromagnetic wave travels at the same speed in empty space, so a shorter wavelength is not a faster wave. The spectrum is an order of wavelength and nothing else.`, kind: 'tip' },
    { content: `Sound in a vacuum is not "quiet" or "muffled." There is NO sound at all. Say it that way every time.`, kind: 'vocab-note' },
    { content: `Light does NOT need matter, but it CAN travel through matter. Don't flip it to "light cannot cross matter." Both sentences are true at once.`, kind: 'common-error' },
    { content: `The two speed comparisons RUN OPPOSITE DIRECTIONS. Sound speeds up in water; light slows down in water. Hold both, not just one.`, kind: 'gotcha' },
    { content: `The electromagnetic spectrum is sorted by WAVELENGTH only. Shorter wavelength ≠ faster wave and ≠ stronger wave. Don't add those assumptions.`, kind: 'common-error' },
    { content: `Every electromagnetic wave travels at the same speed in empty space. A gamma ray and a radio wave arrive together, not at different times.`, kind: 'edge-case' },
    { content: `Infrared is at the RED edge of visible light; ultraviolet is at the VIOLET edge. The names tell you which side they sit on. Use that to anchor the order.`, kind: 'tip' },
    { content: `A medium is the matter a mechanical wave travels through. Light doesn't travel "through a medium of empty space." There is no medium in a vacuum.`, kind: 'vocab-note' },
    { content: `Light travels 300,000,000 meters per second; sound travels 340 meters per second. Convert to the same units BEFORE comparing, or the numbers will confuse you.`, kind: 'tip' },
  ],
};
