/**
 * Grade 8 Science — Unit 8 CED 8.4: Synthetic Materials from Natural Resources.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.synthetic-materials-from-natural-resources.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U8_SYNTHETIC_MATERIALS_FROM_NATURAL_RESOURCES: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.synthetic-materials-from-natural-resources.v1',
  course: 'Grade 8 Science',
  cedUnit: 8,
  cedTopic: '8.4',
  cedTitle: 'Synthetic Materials from Natural Resources',
  planId: 'evelyn.ms.m8sci.synthetic-materials-from-natural-resources.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.synthetic-materials-from-natural-resources.v1' }],
  theory: [
    { loId: 'm8sci.synthetic-materials-from-natural-resources', content: `WHAT A SYNTHETIC MATERIAL IS. A NATURAL RESOURCE is something people take from the Earth or from living things roughly as it is found: crude oil pumped from deep underground, rock quarried from a hillside, clay, timber, cotton. A SYNTHETIC material is one people make by running a CHEMICAL REACTION on a natural resource. Every atom in the new material came out of the starting materials -- no atom is created and none is destroyed, which is the rule you already hold -- but the reaction joins some atoms and separates others into a different arrangement, and a different arrangement of the same atoms is a DIFFERENT SUBSTANCE. That is why the new material has properties its source never had.` },
    { loId: 'm8sci.synthetic-materials-from-natural-resources', content: `THE TRACE, IN THREE STEPS, AND IT IS NOT FINISHED UNTIL ALL THREE ARE THERE. (1) Name the NATURAL RESOURCE or resources the material started from. (2) Name the CHANGE -- the reaction, and what it did, such as joining small molecules into larger ones, or taking one element away from another. (3) COMPARE PROPERTIES: name at least one property the new material has that the resource did not, using the same kind of words for both, such as what state it is in, what color it is, whether it bends or cracks, whether it dissolves, whether it carries electricity. A trace that names a resource and a reaction but no property difference has not proved that anything new was made.` },
    { loId: 'm8sci.synthetic-materials-from-natural-resources', content: `RESHAPING IS NOT MAKING, AND THE EARLIER LESSON ALREADY GAVE YOU THE TEST. Cutting, crushing, melting, spinning, weaving and pouring into a mold change the FORM of a substance and leave the substance alone: a cotton shirt is still cotton, a plank is still wood, and a melted-then-cooled solid is the same solid it was. Only a chemical reaction gives a synthetic material. The test is the one from the lesson on evidence of a reaction: does the material after have a property that nothing you started with had, and does undoing the physical condition -- cooling what was heated, drying what was wetted -- bring the original back? If the original comes back, the change was physical and nothing synthetic was made.` },
    { loId: 'm8sci.synthetic-materials-from-natural-resources', content: `FOUR TRACES, ONE SENTENCE EACH. A PLASTIC: crude oil is separated into small molecules, and a reaction joins those small molecules end to end into far larger ones, giving a clear solid that holds its shape where the oil was a dark runny liquid. A SYNTHETIC FIBER: the same oil, reacted into long thin threads that can be knitted into cloth which dries much faster than wool cloth does. A MEDICINE: willow bark contains a substance that eases pain but is hard on the stomach, and a reaction with a second substance turns it into a related compound, aspirin, that still eases pain and is easier on the stomach. CONCRETE: quarried rock and clay are roasted in a kiln, which drives a reaction that leaves cement powder, and mixing that powder with water and stones starts a second reaction that locks the whole mixture into a solid that can be poured into any shape first.` },
    { loId: 'm8sci.synthetic-materials-from-natural-resources', content: `WEIGHING A BENEFIT AGAINST A COST, AND THE TWO RULES THAT KEEP IT HONEST. A BENEFIT is something the material does better than what it replaced; a COST is what making it, using it or throwing it away takes or damages. Rule one: WEIGH ONLY THE STATED FACTS. If a question does not tell you what a material costs, how long it lasts, or what happens to it afterward, you cannot use that as a reason, however sure you feel. Rule two: WEIGH AGAINST A STATED PURPOSE. The words "better" and "worth it" mean nothing on their own -- better for what? The same material, with the same one benefit and the same one cost in play, can be the right choice for one purpose and the wrong choice for another. And note what neither rule says: "natural" does not mean harmless and "synthetic" does not mean harmful. Both sides of the weighing come from the facts in front of you.` },
    { loId: 'm8sci.synthetic-materials-from-natural-resources', kind: 'definition', title: 'natural resource', content: `a material people take from the Earth or from living things roughly as it is found, such as crude oil, rock, clay, timber or cotton.` },
    { loId: 'm8sci.synthetic-materials-from-natural-resources', kind: 'definition', title: 'synthetic material', content: `a material people make by running a chemical reaction on a natural resource, so that the product is a new substance with properties the resource did not have.` },
    { loId: 'm8sci.synthetic-materials-from-natural-resources', kind: 'definition', title: 'property', content: `something about a substance you can state and compare, such as its color, its state at room temperature, whether it bends or cracks, whether it dissolves, or whether it carries electricity.` },
    { loId: 'm8sci.synthetic-materials-from-natural-resources', kind: 'definition', title: 'benefit', content: `something a material does better than what it replaced, for a purpose someone has stated.` },
    { loId: 'm8sci.synthetic-materials-from-natural-resources', kind: 'definition', title: 'cost', content: `what making, using or throwing away a material takes or damages, stated as a fact rather than as an opinion about the material.` },
    { loId: 'm8sci.synthetic-materials-from-natural-resources', kind: 'definition', title: 'trade-off', content: `the situation where one choice brings both a benefit and a cost, so that the decision has to be made against a stated purpose rather than by finding an option with no downside.` },
  ],
  methods: [
    {
      title: 'Worked plastic bottle',
      steps: [
        `Step 1, name the natural resource. Crude oil, pumped from deep underground. That is the only starting material named, and everything the bottle is made of has to have come out of it.`,
        `Step 2, name the change. Two things happened, and only the second one is a reaction. The separating is a physical step -- it sorts molecules that were already there without making anything new. The joining is the reaction: small molecules that were loose in the oil are joined end to end into molecules far larger than any of them. Different arrangement, same atoms, new substance.`,
        `Step 3, compare the properties, in the same kind of words on both sides. BEFORE: a liquid, dark, you cannot see through it, runny, burns easily. AFTER: a solid, clear, you can see straight through it, holds its shape, springs back when squeezed, holds water. Three properties in the after list -- being a solid that holds a shape, being clear, springing back -- belong to nothing in the before list. The trace is complete.`,
        `WRONG: "The oil was melted and poured into a bottle mold, so the bottle is oil in a solid form." CORRECT: "The oil was separated and then REACTED; the bottle is a substance the oil never contained." Test the wrong version and it falls apart on its own: a substance that is solid because it was cooled goes back to liquid when it warms, and a warm bottle is a warm bottle. Melting and molding are reshaping, and reshaping keeps the substance.`,
        `Now run the two checks a science answer needs, because there is no arithmetic here to redo. First, three clues of DIFFERENT KINDS that agree. The property comparison says the after list holds properties nothing in the before list had. The reversal says no amount of warming, chilling or squeezing turns the bottle back into runny dark oil, and no physical step separates the oil back out of it. The origin says no well anywhere pumps up bottle material, so every gram of it had to be made. Three different kinds of evidence, one answer: a reaction made a new substance. Second, change one condition and check that the answer moves. Suppose the plant had only chilled the oil until it went stiff and waxy, and skipped the reaction. Warm it and the runny dark oil is back; nothing in the after list is a property the oil lacked; and the waxy stuff is not a synthetic material at all, just the same oil in a different state. The reaction is what made the difference, so removing it removes the answer.`,
      ],
      example: { problem: `A clear plastic drink bottle. Here is everything known about where it came from. Crude oil is a dark, thick, runny liquid pumped from deep underground; it burns easily, and you cannot see through a jar of it. At a plant, the oil is first separated into small molecules. Then a reaction joins huge numbers of those small molecules end to end into molecules far larger than any the oil contained. The material that comes out of that reaction is a clear solid that holds its shape, springs back when you squeeze it, and holds water without soaking it up or leaking. Run the trace on it: resource, change, property comparison.`, solution: `Resource: crude oil, pumped from deep underground. Change: after a physical separating step, a reaction joins small molecules from the oil end to end into far larger ones. Property comparison: the oil is a dark runny liquid you cannot see through, and the bottle is a clear solid that holds its shape, springs back when squeezed, and holds water -- properties nothing in the before list had, so a new substance was made.` },
      relatedLoIds: ['m8sci.synthetic-materials-from-natural-resources'],
    },
    {
      title: 'Worked fleece jacket',
      steps: [
        `Step 1, read the stated purpose FIRST, before any fact about the jackets. It is: warm in wet weather, and dry again by the next morning. Everything that follows gets held against that sentence.`,
        `Step 2, pick the benefit that touches the purpose. Both jackets keep a person warm when damp, so warmth is not what separates them and cannot decide anything. The fleece dries in about an hour and the wool takes most of a day. "Dry again by the next morning" is exactly what that difference is about, so the drying time is the benefit that counts here.`,
        `Step 3, name the cost, exactly as stated and no further. Washing a fleece jacket sheds tiny fibers into the wash water, and catching them needs a filter on the machine. That is the whole stated cost. The price is a stated number rather than a judgment: $40 divided over 4 winters is $10 a winter. Notice what you cannot do with it -- no price is given for a wool jacket, so the money fact cannot separate the two options, and using it would break rule one.`,
        `Step 4, weigh, against the purpose and nothing else. The benefit answers the purpose directly. The cost is real, it is stated, and the item also states the thing that reduces it: a filter catches the shed fibers. So the fleece meets the stated purpose, and the cost is a condition attached to that choice rather than a reason against it.`,
        `WRONG: "Wool is natural, so the wool jacket is the better choice." CORRECT: "Wool keeps a person warm when damp and so does fleece, and wool takes most of a day to dry against the fleece's hour, so against THIS purpose the fleece is better." Being natural is not one of the stated facts about drying, warmth or shedding, and slipping it in is deciding before reading. WRONG: "The fleece sheds fibers, so it is the wrong choice." CORRECT: "The fleece sheds fibers, and the stated remedy is a filter; a cost does not outweigh a benefit automatically, it outweighs it only against a stated purpose."`,
        `Now the two checks. First, three clues of DIFFERENT KINDS agree. The purpose match: the only stated difference that touches "dry by the next morning" is the drying time. The remedy: the one stated cost has a stated way of being caught, printed in the same set of facts. The unusable fact: the money number has no partner number for wool, so it cannot decide, which is a different kind of check because it works by ruling a reason OUT. Second, change one condition and see whether the answer moves. Suppose the club's purpose were instead a single dry week at summer camp with no washing machine anywhere. Now the drying-time benefit never comes up, the shedding cost never arises because nothing is washed, and nothing left in the stated facts favors the fleece -- so the wool is at least as good a choice. Same jackets, same benefit, same cost, different purpose, different answer. That is the test working.`,
      ],
      example: { problem: `A hiking club is buying jackets, and these are the facts it has. A fleece jacket is made from the same crude oil the bottle came from: a reaction turns small molecules from the oil into long fibers, and the fibers are knitted into cloth. The fleece keeps a person warm even when it is damp, and it dries in about an hour. A wool jacket is made from sheep wool, washed and spun with no reaction anywhere in the process; it also keeps a person warm when damp, and it takes most of a day to dry. Each fleece jacket is quoted at $40 and the club expects it to last 4 winters. Every time a fleece jacket is washed, tiny fibers break off and leave with the wash water, and a filter fitted to the machine is needed to catch them. The club states its purpose: jackets for weekend hikes in wet weather, where a jacket often has to be dry again by the next morning. Weigh one benefit against one cost and say whether the fleece meets the stated purpose.`, solution: `Yes, against the stated purpose. Benefit: the fleece dries in about an hour where the wool takes most of a day, and drying by the next morning is what the club said it needs. Cost: washing sheds tiny fibers into the wash water, and a filter is needed to catch them. The benefit answers the stated purpose and the cost has a stated remedy, so the fleece meets the purpose -- and if the purpose changed, the answer could change with it.` },
      relatedLoIds: ['m8sci.synthetic-materials-from-natural-resources'],
    },
  ],
  pointers: [
    { content: `Students often say "Synthetic means fake, so the natural version is always the better choice." — Synthetic says one thing and one thing only: people made this substance by running a chemical reaction on a natural resource. It says nothing about whether the material is cheap, weak, or bad for anyone. A synthetic material is a real substance with real properties of its own, and those properties are sometimes better for a job and sometimes worse. It also runs the other way: natural does not mean harmless. Which material is the better choice is decided one job at a time, by holding the stated facts against a stated purpose. WRONG: "It is synthetic, so the natural one is better." CORRECT: "Here is the purpose, here is one stated benefit, here is one stated cost -- and here is which one the purpose picks."`, kind: 'common-error' },
    { content: `Students often say "The synthetic material is really still the resource it was made from, only processed." — Both halves of that sentence cannot stand together. It is true that no atom was created and none destroyed, so every atom in the new material came out of what went in. It is not true that the substance is unchanged, because what makes a substance the substance it is is how its atoms are joined and arranged, not only which atoms are present. Rearrange them and you have a different substance with a different set of properties -- which is exactly what the property comparison in a trace is for. And the earlier lesson gives the test: undo the physical condition, cooling what was heated or drying what was wetted, and see whether the original comes back. If it does, the change was only physical. If it does not, and the product has a property nothing you started with had, a new substance was made. WRONG: "Same atoms, so same stuff, only processed." CORRECT: "Same atoms, joined a different way, so a different substance -- and the new property list is the proof."`, kind: 'common-error' },
    { content: `A synthetic material is one people make by running a CHEMICAL REACTION on a natural resource, so the product is a new substance rather than the resource in a new shape.`, kind: 'tip' },
    { content: `No atom is created and none is destroyed. The reaction rearranges them, and a different arrangement of the same atoms is a different substance with a different property list.`, kind: 'tip' },
    { content: `The trace has three steps and is not finished until all three are there: name the natural resource, name the reaction and what it did, and name one property the new material has that the resource did not.`, kind: 'tip' },
    { content: `Reshaping is not making. Cutting, crushing, melting, spinning and molding keep the substance; undo the physical condition and the original comes back.`, kind: 'tip' },
    { content: `Weighing rule one: use only the facts you are given. A fact you were not told is not a reason, however sure you feel about it.`, kind: 'tip' },
    { content: `Weighing rule two: weigh against a STATED purpose. "Better" means nothing until someone says better for what, and the same benefit and cost can point different ways for different purposes.`, kind: 'tip' },
    { content: `Natural does not mean harmless, and synthetic does not mean harmful. Both sides of the weighing come from the stated facts about the job.`, kind: 'tip' },
    { content: `A trace is NOT finished when you name the resource and reaction. You MUST compare properties — name something the new material does that the starting resource never did. Without that step, you have not proved a new substance was made.`, kind: 'common-error' },
    { content: `Melting, cooling, spinning, and molding are NOT chemical reactions. They change the SHAPE or FORM, not the substance. Test: if warming brings back the original, it was only a physical change — no synthetic material was made.`, kind: 'gotcha' },
    { content: `When you weigh a benefit against a cost, START by reading the stated PURPOSE. Every answer after that has to touch that purpose. A benefit that does not matter for the stated job cannot decide the answer.`, kind: 'tip' },
    { content: `Do NOT use facts you were not given, no matter how sure you feel. If the problem does not tell you the cost, the price, or what happens after, you cannot use it as a reason. That breaks the weighing.`, kind: 'vocab-note' },
    { content: `Same atoms rearranged = different substance with different properties. Conservation of atoms does NOT mean conservation of substance. If atoms are joined a different way, the material is different — that's what the property list proves.`, kind: 'common-error' },
    { content: `When you weigh a benefit against a cost, do NOT automatically say the cost wins. A cost is real, but it only outweighs the benefit if it blocks the stated purpose. A cost with a stated remedy may not stop the choice.`, kind: 'common-error' },
    { content: `'Natural' does not mean harmless and 'synthetic' does not mean harmful. Synthetic just means 'made by a chemical reaction from a natural resource.' The material itself is judged by properties and facts, not by the word 'synthetic.'`, kind: 'vocab-note' },
    { content: `When weighing, the same benefit and same cost can point DIFFERENT ways if the purpose changes. Check your work: if the purpose changed, would your answer flip? If not, you may have missed something.`, kind: 'tip' },
  ],
};
