/**
 * Grade 8 Science — Unit 4 CED 4.4: When Motion Changes, Energy Is Transferred.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.energy-transfer-when-motion-changes.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U4_ENERGY_TRANSFER_WHEN_MOTION_CHANGES: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.energy-transfer-when-motion-changes.v1',
  course: 'Grade 8 Science',
  cedUnit: 4,
  cedTopic: '4.4',
  cedTitle: 'When Motion Changes, Energy Is Transferred',
  planId: 'evelyn.ms.m8sci.energy-transfer-when-motion-changes.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.energy-transfer-when-motion-changes.v1' }],
  theory: [
    { loId: 'm8sci.energy-transfer-when-motion-changes', content: `KINETIC ENERGY IS THE ENERGY AN OBJECT HAS BECAUSE IT IS MOVING, AND IT NEVER CHANGES ON ITS OWN. You already know that kinetic energy grows with mass and grows much faster with speed -- doubling the speed makes the kinetic energy four times as large. This lesson asks a different question about it. Not how much, but where from and where to. An object sitting alone, with nothing pushing or pulling on it, keeps the kinetic energy it has: zero if it is at rest, and a steady amount if it is moving. The only way for that number to go up or down is for another object to push or pull on it. So a change in an object's kinetic energy is not just a fact about that object. It is evidence that a second object was involved, and the whole of this lesson is learning to find that second object and say which way the energy went.` },
    { loId: 'm8sci.energy-transfer-when-motion-changes', content: `THE FORCE IS THE PATHWAY. ENERGY IS WHAT TRAVELS ALONG IT. Two objects can trade energy only while they are interacting -- while one is pushing or pulling on the other. Be careful with the words here, because the everyday way of saying this is wrong, and it is wrong in a way that hides the real event. WRONG: "The bat gives its force to the ball." CORRECT: "While the bat and the ball are touching, the bat pushes on the ball, and along that push energy moves from the bat to the ball." A force is not a thing an object owns and hands over in pieces; it is an interaction between two objects, and it lasts exactly as long as they are acting on each other and not one moment longer. Energy is the thing an object can have more or less of, and energy is what changes hands. The two objects do not always have to touch, either -- a magnet can speed up a steel ball from a little way off -- but there is always a push or a pull between two objects, and that push or pull is when the trade happens.` },
    { loId: 'm8sci.energy-transfer-when-motion-changes', content: `THE DIRECTION OF THE PUSH TELLS YOU WHICH WAY THE ENERGY WENT. If the push on an object points along the direction it is already moving, the object speeds up, its kinetic energy goes up, and it RECEIVED energy from whatever was pushing it. If the push points against the motion, the object slows down, its kinetic energy goes down, and it GAVE energy away to whatever was pushing it. That is the whole rule, and the second half of it is the one people forget: slowing down is a transfer just as much as speeding up is. The energy leaves instead of arriving. There is a third case worth naming so it does not confuse you. An object moving at a steady speed in a straight line is not gaining or losing kinetic energy at all, even though forces may well be acting on it, because the forward and backward pushes cancel. A cyclist pedaling along a flat road at a steady speed is putting energy into the bike's motion exactly as fast as friction and the air are taking it away, so the kinetic energy stays where it is.` },
    { loId: 'm8sci.energy-transfer-when-motion-changes', content: `THE ENERGY THAT LEAVES ALWAYS ARRIVES SOMEWHERE, AND YOUR ARGUMENT HAS TO NAME WHERE. Energy is never used up, made or destroyed -- that is the rule you already have, and it does not bend here. So when a moving object slows down, the energy it lost is somewhere, and in everyday cases it is almost always in one of two places. Either another object started moving, and the energy is now kinetic energy in that object. Or two surfaces rubbed against each other, and the energy is now thermal energy in those surfaces and in the air right beside them, which is why they end up warmer than they were. WRONG: "The brakes used up the bike's energy of motion." CORRECT: "The bike's energy of motion moved into the brake pads, the wheel rim and the air, which are warmer than they were." The warmth is not a side effect of the stopping. The warmth IS the energy, in the place it went.` },
    { loId: 'm8sci.energy-transfer-when-motion-changes', content: `THE ARGUMENT, IN FOUR MOVES. (1) Name the one object you are arguing about, say how its kinetic energy changed, and say how you know -- it sped up, so the energy went up; it slowed down, so the energy went down. (2) Name the other object that was pushing or pulling on it while the change was happening, and say which way that push pointed compared with the motion. (3) Say which object gave and which received, and name where the energy is now: moving in the other object, or making surfaces and the air warmer. (4) Test the argument by changing exactly one thing. Take the other object away, or swap it for a different one, and say what the motion would do instead. If the change in motion disappears when you remove that object, you have found the giver or the receiver, and your argument is evidence and not just a story.` },
    { loId: 'm8sci.energy-transfer-when-motion-changes', content: `WHAT THIS ARGUMENT CLAIMS, AND WHAT IT DOES NOT. It claims a direction and a pair: which object gave, which received, and where the energy ended up. It does not claim an amount. Nothing in this lesson asks how much energy moved, and there is no formula here for working that out from a push and a distance. Two more limits, because both are places students overshoot. Giving energy away does not leave an object empty or used up: a cue ball that hands its motion to another ball is simply sitting still on the felt, ready to be pushed again. And a transfer does not have to be tidy. When two objects collide you can usually hear a small share of the energy leave as sound, and the place where they touched is left very slightly warmer, so "nearly all of it went to the other ball" is a more honest sentence than "all of it did".` },
    { loId: 'm8sci.energy-transfer-when-motion-changes', kind: 'definition', title: 'kinetic energy', content: `the energy an object has because it is moving. It grows with the object's mass and with its speed, and an object at rest has none.` },
    { loId: 'm8sci.energy-transfer-when-motion-changes', kind: 'definition', title: 'energy transfer', content: `the movement of energy from one object to another, which happens while the two are pushing or pulling on each other.` },
    { loId: 'm8sci.energy-transfer-when-motion-changes', kind: 'definition', title: 'thermal energy', content: `the form of energy that shows up as how warm an object is -- an object gains thermal energy when it warms up and loses it when it cools.` },
    { loId: 'm8sci.energy-transfer-when-motion-changes', kind: 'definition', title: 'friction', content: `a force between two touching surfaces that pushes against their sliding or rolling across each other.` },
    { loId: 'm8sci.energy-transfer-when-motion-changes', kind: 'definition', title: 'collision', content: `a brief interaction in which two objects touch and push on each other, so that the motion of each one changes.` },
    { loId: 'm8sci.energy-transfer-when-motion-changes', kind: 'definition', title: 'conservation of energy', content: `the rule that energy is never created or destroyed; it only moves between objects and changes from one form into another.` },
  ],
  methods: [
    {
      title: 'Worked cue ball and struck ball',
      steps: [
        `Move one, name each object and say how its kinetic energy changed. Take the first ball. Before the click it was rolling at about 2 meters per second; after the click it is barely moving. It slowed down, so its kinetic energy went down. Now take the second ball. Before the click it was standing still, so it had no kinetic energy at all; after the click it is moving at close to 2 meters per second, so its kinetic energy went up from nothing to a real amount. Two objects, two changes, in opposite directions.`,
        `Move two, name the other object and the direction of the push. The only thing that touched either ball is the other ball, and they touched for one very short moment -- the click. While they were touching, the first ball pushed forward on the second ball, in the direction the first ball was already going, and a push on an object that is standing still is what sets it moving in the direction of that push. At the same moment the second ball pushed backward on the first ball, against its motion, and a push against the motion is what slows an object down. Both changes in motion have a push behind them, and both pushes existed only while the two balls were in contact.`,
        `Move three, say who gave, who received, and where the energy is now. The first ball slowed, so it gave energy away. The second ball sped up from a standstill, so it received energy. Nearly all of the kinetic energy that left the first ball is now kinetic energy in the second ball, which is why the second ball crosses the felt at close to the speed the first one had. Not quite all of it: you heard a small share leave as the sound of the click, and the small patch where the two balls touched is left very slightly warmer than it was.`,
        `WRONG: "The first ball gave the second ball its force." CORRECT: "While the two balls were touching, the first ball pushed on the second, and along that push energy moved from the first ball to the second." The force was an interaction between the two balls and it ended the instant they came apart; neither ball carried it off afterward. Energy is the thing that moved and stayed moved, which is why the second ball is still traveling long after the push is over.`,
        `Now check the argument the way a science answer has to be checked, because there is no arithmetic here to redo. Look for three clues of DIFFERENT KINDS that agree. The first is timing: the second ball did not start moving a moment before the click or a moment after it, but exactly at the click, which is exactly when the two balls were pushing on each other. The second is the force inventory: nothing else was touching either ball -- no hand, no cue, no third ball -- so the only interaction available to explain either change is the one between these two. The third is that the two changes match in size: the speed the first ball lost is very close to the speed the second ball gained, which is what you expect if what left one arrived at the other, and is not what you would expect if the two changes had separate causes of their own.`,
        `Then change exactly one thing and check that the answer moves with it. Take the second ball off the table and roll the first ball down the same line at the same speed. Now it does not stop; it rolls on to the far cushion, losing speed only slowly to friction with the felt. The sudden stop needed the second ball to be there, which is the sign that the second ball is where the energy went. Change the second ball instead of removing it -- put a much more massive ball in its place -- and the first ball bounces back toward you rather than stopping, because a lighter object pushing on a much heavier one does not hand over all of its motion. The answer moves every time the other object moves. That is what makes this an argument from evidence rather than a description.`,
      ],
      example: { problem: `On a pool table, one ball is rolling at about 2 meters per second straight toward a second ball of the same size that is standing still. The two meet with a click. Straight after the click the first ball is barely moving, and the second ball is traveling away at close to 2 meters per second in the direction the first ball had been going. Nothing else touches either ball. Build the argument: whose kinetic energy changed, which way, and which object gave and which received?`, solution: `The first ball gave energy to the second ball. The first ball slowed almost to a stop, so its kinetic energy went down; the second ball went from standing still to close to 2 meters per second, so its kinetic energy went up; and the two were pushing on each other at exactly the moment both changes happened, with the first ball pushing forward on the second and the second pushing backward on the first. Nearly all of the first ball's kinetic energy is now kinetic energy in the second ball, with a small share carried off as the sound of the click and a slight warming where they touched.` },
      relatedLoIds: ['m8sci.energy-transfer-when-motion-changes'],
    },
    {
      title: 'Worked brake pads warm',
      steps: [
        `Move one, name the object and say how its kinetic energy changed. The object is the bike with its rider. Before the braking they were moving at a steady speed, so they had a steady amount of kinetic energy. A few seconds later they are at rest, so their kinetic energy has gone down to nothing. The whole of it left. That is a large change, and the rule says a change that large had a second object on the other end of it.`,
        `Move two, name the other object and the direction of the push. The pads are squeezed against the rim, the rim is turning, and so the two surfaces rub against each other. Friction between them pushes against the motion of the rim everywhere the two touch. That backward push is the pathway, and notice that it is the only thing in this story that changed when the brakes went on -- the road is the same road, the air is the same air, and the bike is the same bike.`,
        `Move three, say who gave, who received, and where the energy is now. The bike and rider slowed, so they gave energy away. The pads and the rim received it, and for once you can feel exactly where it went: those two surfaces are warmer than they were, and so is the air right beside them. The energy of motion did not vanish when the speed did. It became thermal energy in the pads and the rim, and it is spreading from there into the air.`,
        `WRONG: "The brakes used up the bike's energy of motion, and now it is gone." CORRECT: "The bike's energy of motion moved into the brake pads, the rim and the air around them, which are warmer than they were." Used up is not something energy does. Moved into a place you can name, and can check by touching, is. The warm rim is not a side effect of the braking; it is the receipt.`,
        `Now look for three clues of DIFFERENT KINDS that agree, since there is no arithmetic to redo. The first is location: the pads and the rim are warmer and the seat, frame and handlebars are not, and the pads and the rim are precisely the two surfaces that were rubbing. If the warmth had come from the weather or from the rider, it would not have picked out those two parts. The second is timing: they warm up during the braking and only during the braking, not on the long coast before it. The third is size: braking from a higher speed, or braking for longer, leaves them warmer still, so the more motion that is lost, the more warmth appears -- the two quantities move together, which is what you expect if one is becoming the other.`,
        `Then change exactly one thing, twice. First, coast along the same flat road without touching the brakes. The bike keeps almost all of its speed for a long way, losing it only slowly to friction and the air, and the rim stays cool. The warmth appears only when the fast slowing does. Second, squeeze the brakes just as hard while the bike is already standing still. The pads press the rim exactly as before, and nothing warms at all, because there is no motion for them to take energy from. Put those two together and the rubbing on its own is ruled out as the source. The source is the kinetic energy the bike had, and the rubbing is only the pathway it left by.`,
      ],
      example: { problem: `A cyclist coasting along a flat, straight road at a steady speed squeezes the brakes and comes to a stop in a few seconds. The brake pads press against the turning metal rim of the wheel the whole time. Once the bike has stopped, the pads and the rim are clearly warmer than they were before the braking, while the seat, the frame and the handlebars are not. A student says: "The bike had energy of motion, the brakes used it up, and now it is gone." Build the argument properly: whose kinetic energy changed, which object gave, and which object received?`, solution: `The bike and rider gave the energy away, and the brake pads, the wheel rim and the air beside them received it. The bike and rider slowed from a steady speed to rest, so their kinetic energy went down to nothing; the pathway was the friction between the pads and the turning rim, a push against the motion; and the energy is now thermal energy in those two surfaces, which is why they are warmer and the rest of the bike is not. Nothing was used up.` },
      relatedLoIds: ['m8sci.energy-transfer-when-motion-changes'],
    },
  ],
  pointers: [
    { content: `Students often say "The bike's energy of motion was used up by the brakes and is gone." — Energy is never used up, made or destroyed. It moves from one object to another and changes from one form to another, and that is all it ever does. The bike's energy of motion went into the brake pads, the wheel rim and the air right beside them, which are warmer after the braking than they were before. That warmth is the receipt. The reason this is so easy to miss is that thermal energy spread through a lot of material does not look like anything, while a moving bike obviously does, so the energy seems to have stopped existing at the moment it stopped being visible. The test that settles it is to take the receiver out of the story: coast along the same flat road without touching the brakes, and the rim stays cool while the bike keeps almost all of its speed. The warmth appears exactly when, and only when, the speed goes away. WRONG: "The brakes used the energy up." CORRECT: "The brakes moved the energy into the pads, the rim and the air, where it is now thermal energy."`, kind: 'common-error' },
    { content: `Students often say "The moving ball gives the still ball some of its force." — A force is a push or a pull between two objects, and it lasts exactly as long as the interaction lasts. While the two balls are touching, the first pushes on the second; the instant they come apart that push is over, and neither ball is carrying it anywhere. What a moving object HAS is kinetic energy, and kinetic energy is what changes hands: the first ball slows because energy left it, and the second ball speeds up because that energy arrived. Saying it correctly also makes the direction easy to read, because a push along the motion means energy arriving and a push against the motion means energy leaving, and a possession that gets handed over has no direction to read at all. WRONG: "The first ball gave the second ball some of its force." CORRECT: "While they were touching, the first ball pushed on the second, and along that push energy moved from the first ball to the second."`, kind: 'common-error' },
    { content: `An object's kinetic energy changes only when another object pushes or pulls on it. It never rises or falls on its own, so a change in motion is evidence that a second object was involved.`, kind: 'tip' },
    { content: `A push along the direction of motion speeds an object up, so that object RECEIVED energy. A push against the motion slows it down, so that object GAVE energy away.`, kind: 'tip' },
    { content: `Slowing down is a transfer just as much as speeding up is. The energy leaves instead of arriving.`, kind: 'tip' },
    { content: `The force is the pathway and energy is what travels along it. A force is not something an object carries and hands over; it exists only while the two objects are acting on each other.`, kind: 'tip' },
    { content: `Energy is never used up. When a moving object slows, the energy it lost is somewhere you can name: moving in another object, or making rubbing surfaces and the air beside them warmer.`, kind: 'tip' },
    { content: `The argument in four moves: name the object and whether its kinetic energy went up or down; name the other object pushing or pulling on it and which way; say who gave, who received, and where the energy is now; then remove or change that other object and check that the change in motion moves with it.`, kind: 'tip' },
    { content: `A collision passes energy along the push the two objects put on each other while they touch, and a small share of it usually leaves as the sound you hear.`, kind: 'tip' },
    { content: `Giving energy away does not leave an object empty, and an object moving at a steady speed in a straight line is neither gaining nor losing kinetic energy.`, kind: 'tip' },
  ],
};
