/**
 * Grade 8 Science — Unit 1 CED 1.3: Velocity & Acceleration.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.velocity-and-acceleration.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U1_VELOCITY_AND_ACCELERATION: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.velocity-and-acceleration.v1',
  course: 'Grade 8 Science',
  cedUnit: 1,
  cedTopic: '1.3',
  cedTitle: 'Velocity & Acceleration',
  planId: 'evelyn.ms.m8sci.velocity-and-acceleration.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.velocity-and-acceleration.v1' }],
  theory: [
    { loId: 'm8sci.velocity-and-acceleration', content: `SPEED ANSWERS ONE QUESTION: HOW FAST? A speed tells you how much distance an object covers in each unit of time, and nothing more. You already know how to find one: speed equals distance divided by time (speed = distance ÷ time). A runner who covers 50 meters in 10 seconds has a speed of 5 meters per second, because 50 divided by 10 is 5. Now notice everything that number does not tell you. It does not say whether she is running toward the gate or away from it, north or south, up the hill or down. Two runners can both be moving at 5 meters per second and be heading in completely opposite directions. A speed is a number with a unit -- meters per second in science, or miles per hour on a car dial -- and a number with a unit cannot point anywhere.` },
    { loId: 'm8sci.velocity-and-acceleration', content: `VELOCITY IS A SPEED TOGETHER WITH A DIRECTION. Velocity answers two questions at once: how fast, and which way. "Five meters per second" is a speed. "Five meters per second toward the north end of the field" is a velocity. Because a velocity is built out of two parts, there are two separate ways to make it different. Change the number and the velocity is different. Change the direction and the velocity is different, even if the number never moves at all. A velocity stays the same only when BOTH parts stay the same. WRONG: "Velocity is just a longer word for speed." CORRECT: "Velocity is a speed with a direction attached, so two objects can share a speed and still have different velocities."` },
    { loId: 'm8sci.velocity-and-acceleration', content: `ACCELERATION IS ANY CHANGE IN VELOCITY, AND THERE ARE THREE WAYS TO GET ONE. An object is accelerating whenever its velocity is changing. Because a velocity has two parts, that gives exactly three kinds of change, and every one of them counts. (1) SPEEDING UP: the number rises while the direction holds. (2) SLOWING DOWN: the number falls while the direction holds. (3) TURNING: the direction changes, whether the number moves or not. Any one of the three on its own is acceleration. The flip side matters just as much: an object whose number and direction both hold steady is not accelerating at all, no matter how fast it happens to be going. A jet flying level in a straight line at a steady 200 meters per second is not accelerating. A bicycle creeping around a corner at 2 meters per second is.` },
    { loId: 'm8sci.velocity-and-acceleration', content: `SLOWING DOWN IS ACCELERATION, EVEN THOUGH THE EVERYDAY WORD SAYS OTHERWISE. Outside science, "accelerate" means one thing only: press the gas and gain speed. That everyday meaning is the biggest source of trouble in this lesson, because it makes slowing down sound like the opposite of accelerating instead of one of its kinds. Science uses the wider meaning, and it has to, because there is nothing special about a number going up rather than down -- either way the velocity is different from what it was. "Deceleration" is a handy everyday name for the slowing-down kind, and it is a kind of acceleration, not its opposite. WRONG: "The elevator was decelerating as it came up to my floor, so it was not accelerating." CORRECT: "The elevator was slowing, so its velocity was changing, so it was accelerating -- and slowing down is the kind of acceleration people call deceleration." The true opposite of accelerating is constant velocity: a steady number and a steady direction, both at once.` },
    { loId: 'm8sci.velocity-and-acceleration', content: `TURNING AT A STEADY SPEED IS ACCELERATION, AND THIS IS THE ONE PEOPLE MISS. Picture a car driving all the way around a bend with the speedometer needle parked on one number the whole way. The number never moves, so it is tempting to say that nothing about its motion changed. But the car was heading east when it entered the bend and heading north when it left, and the direction is half of a velocity. The velocity it has at the end of the bend is not the velocity it had at the start, so the car was accelerating the entire way around, at a steady speed. There is a way to check this that uses no science at all: watch what loose things do. On a straight road at a steady speed, a bag on the back seat sits still. On the bend at that same steady speed, it slides across the seat -- which is also what it does when the driver brakes hard, and what it never does while the car is holding a steady speed on a straight road. The stages where loose things move are the stages where the velocity is changing.` },
    { loId: 'm8sci.velocity-and-acceleration', content: `HOW TO ANSWER ANY QUESTION IN THIS LESSON. First, write down the speed at the start and the speed at the end, each with its unit. Second, write down the direction at the start and the direction at the end. Third, compare the two pairs. If the number changed, or the direction changed, or both did, then the velocity changed and the object is accelerating -- and you can say which of the three kinds it is. If neither changed, the velocity is constant and the object is not accelerating. Two warnings while you run it. Moving is not the same as accelerating: an object can travel for hours at a constant velocity and never accelerate once. And an object sitting at rest is not a trick case either -- its velocity is not changing, so it is not accelerating.` },
    { loId: 'm8sci.velocity-and-acceleration', kind: 'definition', title: 'speed', content: `how much distance an object covers in each unit of time, found by dividing the distance by the time and written with a unit such as meters per second.` },
    { loId: 'm8sci.velocity-and-acceleration', kind: 'definition', title: 'velocity', content: `an object's speed together with the direction it is traveling in, such as 3 meters per second due north.` },
    { loId: 'm8sci.velocity-and-acceleration', kind: 'definition', title: 'acceleration', content: `any change in an object's velocity: speeding up, slowing down, or changing direction.` },
    { loId: 'm8sci.velocity-and-acceleration', kind: 'definition', title: 'constant velocity', content: `motion in which the speed and the direction both stay the same, so the velocity does not change and the object is not accelerating.` },
    { loId: 'm8sci.velocity-and-acceleration', kind: 'definition', title: 'deceleration', content: `the everyday name for the kind of acceleration in which an object's speed is falling; it is one kind of acceleration, not the opposite of it.` },
    { loId: 'm8sci.velocity-and-acceleration', kind: 'definition', title: 'meters per second', content: `the unit a speed is usually given in for science; it says how many meters the object covers in each second.` },
  ],
  methods: [
    {
      title: 'Worked two joggers and a turn',
      steps: [
        `Find Ana's speed. Speed equals distance divided by time (speed = distance ÷ time), so 120 meters divided by 40 seconds is 3 meters per second. Carry the unit with the number: the answer is 3 meters per second, not 3.`,
        `Find Ben's speed the same way. 90 meters divided by 30 seconds is 3 meters per second. So the answer to the first question is yes -- the two runners have exactly the same speed, even though neither the distance nor the time matched.`,
        `Now the second question, which needs the other half. Ana's velocity is 3 meters per second due north. Ben's velocity is 3 meters per second due east. A velocity is a speed together with a direction, and a velocity stays the same only when both parts match. The numbers match and the directions do not, so their velocities are different. WRONG: "They cover ground at the same rate, so they have the same velocity." CORRECT: "They have the same speed, and different velocities, because they are heading different ways."`,
        `Now the turn. Run the routine on Ana across the moment she turns. Her speed at the start of the turn is 3 meters per second and her speed at the end of the turn is 3 meters per second, so the number did not change. Her direction at the start is due north and at the end is due east, so the direction did change. One part changed, and one part is enough: her velocity changed, so Ana IS accelerating while she turns, at a steady 3 meters per second.`,
        `Run the check for clues of DIFFERENT KINDS that agree, because there is no arithmetic left to redo here. The first clue is the definition inventory: the number held and the direction moved, and a velocity needs both to hold. The second clue is where she actually ends up, which is a fact about the world rather than about a definition -- ten seconds after the turn she is 30 meters east of the fence, because 3 meters per second times 10 seconds is 30 meters, whereas without the turn those same ten seconds would have put her 30 meters further north. Her motion produced a different result, so her motion was not the same motion. The third clue is an observation anyone can make without knowing any of this: a water bottle lying loose in the open bag on her back rolls to one side of the bag while she is going around the turn, and lies still while she runs straight. Three different kinds of evidence, one answer.`,
        `Now change exactly one condition and check that the answer moves with it. First, suppose the north path simply carried on and Ana ran straight past the fence at 3 meters per second. Then the number is unchanged and the direction is unchanged, her velocity is constant, and she is NOT accelerating. Second, suppose instead that she keeps heading due north but speeds up from 3 meters per second to 5 meters per second. Now the direction is unchanged and the number is not, and she IS accelerating again -- the speeding-up kind this time. The verdict follows whichever part of the velocity moves, which is exactly what "any change in velocity" means. An explanation that gave the same answer in all three of those setups would not be an explanation at all.`,
      ],
      example: { problem: `Two friends set out from the same corner of a park at the same moment. Ana runs 120 meters along a straight path heading due north, and it takes her 40 seconds. Ben runs 90 meters along a straight path heading due east, and it takes him 30 seconds. Each runs at a steady rate the whole way. Do the two of them have the same speed? Do they have the same velocity? Then Ana reaches the fence at the north end, turns onto a path heading due east, and keeps running at exactly the rate she had before. Is she accelerating while she turns?`, solution: `Ana and Ben have the same speed, 3 meters per second each, because 120 meters divided by 40 seconds and 90 meters divided by 30 seconds both come to 3 meters per second. They do not have the same velocity: Ana's is 3 meters per second due north and Ben's is 3 meters per second due east, and a velocity is a speed together with a direction. Ana IS accelerating while she turns. Her speed holds at 3 meters per second and her direction changes from due north to due east, and a change in either part is a change in velocity, which is what acceleration means.` },
      relatedLoIds: ['m8sci.velocity-and-acceleration'],
    },
    {
      title: 'Worked bus four stages',
      steps: [
        `Stage 1. Speed at the start is 0 meters per second and speed at the end is 8 meters per second, a rise of 8 meters per second, because 8 meters per second minus 0 meters per second leaves 8 meters per second. Direction at the start is due east and at the end is due east, so the direction held. The number changed, so the velocity changed: the bus IS accelerating, and this is the speeding-up kind. Almost nobody argues with this one, which is why it is worth doing first -- it fixes the routine before the routine gets hard.`,
        `Stage 2. Speed at the start is 8 meters per second and at the end is 8 meters per second, so the number held. Direction at the start is due east and at the end is due east, so the direction held. Both parts held, so the velocity is constant and the bus is NOT accelerating. This is the only one of the four stages where nothing about the velocity changes, and notice that the bus is moving quickly throughout it. Moving fast and accelerating are not the same thing.`,
        `Stage 3, and this is the one that matters most. Speed at the start is 8 meters per second and at the end is 8 meters per second: the number held, and the speedometer needle really did sit still the whole way around. Direction at the start is due east and at the end is due south: the direction changed. One part changed, so the velocity changed, so the bus IS accelerating all the way around the curve -- the turning kind. WRONG: "The speedometer held at 8 meters per second around the whole curve, so stage 3 is not acceleration." CORRECT: "The speedometer only reports the number. The bus went in heading east and came out heading south, and the direction is half of the velocity, so the velocity changed even though the number did not."`,
        `Stage 4. Speed at the start is 8 meters per second and at the end is 0 meters per second, a fall of 8 meters per second, because 8 meters per second minus 0 meters per second leaves 8 meters per second again, this time as a drop rather than a rise. Direction at the start is due south and at the end is due south, so the direction held. The number changed, so the velocity changed and the bus IS accelerating -- the slowing-down kind. WRONG: "Stage 4 is deceleration, and deceleration is the opposite of acceleration, so it does not count." CORRECT: "Deceleration is the everyday name for the kind of acceleration in which the speed falls. It is one of the three kinds, not the opposite of the set."`,
        `Run the check for clues of DIFFERENT KINDS on stage 3, since that is the stage a reader is most likely to doubt. The first clue is the definition inventory, already done: the direction went from east to south while the number held. The second clue is the record a passenger could keep with nothing but a compass and the dial -- "8 meters per second east" written down at the start of the curve and "8 meters per second south" written down at the end are two different entries, and a quantity with two different values at two different times has changed. The third clue is purely observational and needs no definitions at all: shopping bags standing on the floor of the bus slide across it during stages 1, 3 and 4, and stand still during stage 2. Stage 3 groups itself with the two stages everybody already agrees are acceleration, and separates itself from the one stage that is not. Three clues of different kinds, all pointing the same way.`,
        `Now change exactly one condition and check that the answer moves. Suppose the ramp in stage 3 had been straight instead of curved, with the speedometer still holding at 8 meters per second. Then the direction holds as well as the number, stage 3 becomes a second stage 2, the velocity is constant, and the bags on the floor stay put. Change the road and the verdict changes with it, which is what tells you the curve was doing the work -- and not, say, the length of the road or the speed the bus happened to be traveling at.`,
      ],
      example: { problem: `A city bus makes one short trip in four stages. Stage 1: it pulls away from a stop and its speed rises steadily from 0 meters per second to 8 meters per second while it heads due east along a straight street. Stage 2: it holds 8 meters per second along that same straight street for the next 20 seconds. Stage 3: it follows a curved ramp onto a road heading due south, and the speedometer holds at 8 meters per second the whole way around the curve. Stage 4: it brakes in a straight line and its speed falls steadily from 8 meters per second to 0 meters per second at the next stop. For each stage, say whether the bus is accelerating, and where it is, say which part of its velocity changed.`, solution: `Stage 1: accelerating, the speeding-up kind -- the number rose from 0 meters per second to 8 meters per second while the direction held due east. Stage 2: not accelerating -- both the number and the direction held, so the velocity is constant. Stage 3: accelerating, the turning kind -- the number held at 8 meters per second but the direction changed from due east to due south, and direction is half of a velocity. Stage 4: accelerating, the slowing-down kind -- the number fell from 8 meters per second to 0 meters per second while the direction held due south, and slowing down is a kind of acceleration rather than its opposite. Three of the four stages are acceleration, and only stage 2 is not.` },
      relatedLoIds: ['m8sci.velocity-and-acceleration'],
    },
  ],
  pointers: [
    { content: `Students often say "A car going around a roundabout at a steady speed is not accelerating, because its speed never changes." — A velocity has two parts, the number and the direction, and a velocity stays the same only when both of them stay the same. The car enters the roundabout heading east and leaves it heading north, so its direction changed while the number held, and a change in either part is a change in velocity. That is exactly what acceleration means, so the car was accelerating the whole way around, at a steady 9 meters per second. There is a check that needs no definitions at all. Take the same car at the same steady 9 meters per second along a straight road: a bag on the back seat sits still. Put it on the roundabout at that same steady 9 meters per second and the bag slides across the seat. Change the road and the loose objects change what they do, which is what tells you the velocity was changing on the curve and not on the straight. WRONG: "The number never changed, so nothing about its motion changed." CORRECT: "The number never changed, but the direction did, and the direction is half of the velocity."`, kind: 'common-error' },
    { content: `Students often say "Braking is deceleration, which is the opposite of accelerating." — In science, acceleration is the word for a velocity changing in any way whatever, and there are three ways that can happen: the number rises, the number falls, or the direction turns. Slowing down is the second of those three. It is a kind of acceleration, not the opposite of it, and there is nothing special about a number going up rather than down -- either way the velocity at the end is not the velocity at the start. "Deceleration" is simply a convenient everyday name for the slowing-down kind, and it is fine to use it as long as you remember what it is a name for. The real opposite of accelerating is constant velocity: a steady number and a steady direction, both at the same time. WRONG: "It was decelerating, so it was not accelerating." CORRECT: "It was slowing, so its velocity was changing, so it was accelerating -- the slowing-down kind."`, kind: 'common-error' },
    { content: `A speed says how fast and nothing else. It is a number with a unit, such as 5 meters per second, and a number with a unit cannot point anywhere.`, kind: 'tip' },
    { content: `A velocity is a speed together with a direction: 5 meters per second due north. It stays the same only when BOTH parts stay the same.`, kind: 'tip' },
    { content: `Two objects can have the same speed and different velocities, because they are heading different ways.`, kind: 'tip' },
    { content: `Acceleration is ANY change in velocity. There are three kinds: speeding up, slowing down, and changing direction.`, kind: 'tip' },
    { content: `Slowing down is acceleration. Deceleration is the everyday name for that one kind, not the opposite of the whole idea.`, kind: 'tip' },
    { content: `Turning at a steady speed is acceleration. A car going around a bend with the needle parked on one number is accelerating the entire way, because the direction is half of the velocity.`, kind: 'tip' },
    { content: `Moving is not the same as accelerating. An object can travel for hours at a constant velocity and never accelerate, and an object at rest is not accelerating either.`, kind: 'tip' },
    { content: `To decide any case: write down the speed at the start and at the end, then the direction at the start and at the end. If either pair differs, the velocity changed and the object is accelerating. If neither differs, the velocity is constant.`, kind: 'tip' },
    { content: `A check that uses no definitions: a loose object resting on a smooth seat or floor slides across it during the stages where the velocity is changing, and stays put during the stages where it is not.`, kind: 'tip' },
    { content: `Don't say "the object has acceleration" or "the object has velocity." Say "acceleration is acting on the object" or "the object's velocity is [value and direction]." Velocity and acceleration describe motion, not things an object owns.`, kind: 'vocab-note' },
    { content: `A speedometer reads only the NUMBER part of velocity. Don't use the needle staying still as proof the velocity isn't changing. Always check the DIRECTION separately.`, kind: 'common-error' },
    { content: `Deceleration is NOT the opposite of acceleration. It's the everyday name for ONE KIND of acceleration (the slowing-down kind). The real opposite of accelerating is CONSTANT velocity—both number AND direction stay the same.`, kind: 'gotcha' },
    { content: `An object moving at a constant velocity—same number, same direction, for hours—is NOT accelerating at all, even if it's moving very fast. Moving ≠ accelerating.`, kind: 'edge-case' },
    { content: `Always write velocity as TWO pieces: a number with its unit AND a direction. "3 m/s north" is velocity. "3 m/s" alone is speed. If you skip the direction, you've lost half the definition.`, kind: 'vocab-note' },
    { content: `When a loose object (bag, water bottle, coin) slides on a seat or floor during an event, the velocity is changing during that event. When it stays still, the velocity is constant. This check needs zero math—just watch.`, kind: 'tip' },
    { content: `The three kinds of acceleration are speeding up (number changes, direction holds), slowing down (number changes, direction holds), and turning (direction changes, number can hold or change). Don't forget turning is acceleration.`, kind: 'common-error' },
    { content: `To decide if acceleration is happening: write speed-start, speed-end, direction-start, direction-end. If ANY of those four change, velocity changed, so acceleration happened. If none change, no acceleration.`, kind: 'tip' },
  ],
};
