/**
 * Grade 8 Science — Unit 2 CED 2.3: Newton's Third Law: Action-Reaction Pairs.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.newtons-third-law-action-reaction-pairs.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U2_NEWTONS_THIRD_LAW_ACTION_REACTION_PAIRS: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.newtons-third-law-action-reaction-pairs.v1',
  course: 'Grade 8 Science',
  cedUnit: 2,
  cedTopic: '2.3',
  cedTitle: `Newton's Third Law: Action-Reaction Pairs`,
  planId: 'evelyn.ms.m8sci.newtons-third-law-action-reaction-pairs.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.newtons-third-law-action-reaction-pairs.v1' }],
  theory: [
    { loId: 'm8sci.newtons-third-law-action-reaction-pairs', content: `A FORCE IS NEVER SOMETHING ONE OBJECT DOES ALONE. A force is a push or a pull between two objects, and Newton's third law says it always comes with a partner: when object A pushes on object B, object B pushes back on A at the same instant, with a force of the same size, in the opposite direction. The two forces are called an action-reaction pair, and the two names are just labels -- neither force comes first, neither one causes the other, and they start and stop together. Say a pair out loud in two matching sentences and it is hard to get wrong: "my hands push the wall to the north" and "the wall pushes my hands to the south". The two objects are the same two in both sentences, the directions are opposite, and the sizes are equal.` },
    { loId: 'm8sci.newtons-third-law-action-reaction-pairs', content: `THE TWO FORCES OF A PAIR ACT ON DIFFERENT OBJECTS, AND THAT IS THE WHOLE REASON THEY NEVER CANCEL. One of them acts on A and the other acts on B, always. And two forces add up only when they act on the SAME object -- that is what finding a net force means, and it is why the very first question about any force is "on what?" So the two halves of a pair are never added to each other, because there is no single object for that sum to be about. WRONG: "The push and the push back are equal and opposite, so they cancel and nothing can move." CORRECT: "The push acts on B and the push back acts on A. Each object's motion is changed by the force acting on IT, and neither force does anything at all to the object it is not on." If pairs really did cancel, nothing you have ever pushed would have moved, and things move all day.` },
    { loId: 'm8sci.newtons-third-law-action-reaction-pairs', content: `A PAIR AND A SET OF BALANCED FORCES LOOK THE SAME ON PAPER AND ARE NOT THE SAME THING. Both are two forces, equal in size and opposite in direction. The difference is the count of objects. Stand still on the floor. Earth pulls you downward and the floor pushes you upward, those two are the same size in opposite directions, and both of them act on YOU -- one object, two forces, so they are balanced forces and the net force on you is zero, which is why you stay put. Now find the partner of the floor's push on you: it is your push downward on the floor, and that one acts on the FLOOR, not on you. Even Earth's pull on you has a partner, which is your pull upward on Earth. So the test is a counting test. Name the object each force acts on. Two forces on one object are balanced forces. Two forces on two objects, each pushing the other, are an action-reaction pair.` },
    { loId: 'm8sci.newtons-third-law-action-reaction-pairs', content: `EQUAL FORCES DO NOT MEAN EQUAL EFFECTS, AND THAT IS WHY THE WORLD LOOKS ONE-SIDED. Jump straight up. Your feet push downward on Earth and Earth pushes upward on you, and those two forces are the same size. You clearly speed upward, and Earth clearly does not visibly move. Nothing about the forces is unequal -- what is unequal is the mass. You already know from the first-law lesson that inertia grows with mass, so the same size force changes the motion of a small mass a lot and the motion of an enormous one far too little to detect. Earth's mass is beyond enormous next to yours. WRONG: "The bigger object pushes harder, and that is why the smaller one goes flying." CORRECT: "The two pushes are the same size. The smaller mass changes its motion more, because there is less inertia to change."` },
    { loId: 'm8sci.newtons-third-law-action-reaction-pairs', content: `ONCE YOU SEE THE PAIRS, THEY ARE WHAT GETS EVERYTHING MOVING. Walk across a room: your shoe pushes backward on the ground, and the ground pushes forward on your shoe, and that forward push on you is what moves you -- which is why walking on smooth ice, where your shoe cannot get the grip to push backward on the ground, does not work. A car does the same thing through its tires: the tires push backward on the road, the road pushes forward on the tires. In every one of these, the useful force -- the one that changes the motion you care about -- is the partner, the one pointing back at you. That is the pattern worth carrying: to get pushed forward, push something backward.` },
    { loId: 'm8sci.newtons-third-law-action-reaction-pairs', content: `HOW TO NAME AND USE A PAIR, IN ORDER. First, name the two objects that are touching or otherwise interacting. Second, write one sentence: object A pushes on object B, in this direction. Third, the partner is written by swapping the two objects and reversing the direction, keeping the size the same: object B pushes on object A, in the opposite direction. Fourth -- and this is the step that answers every "why does it move" question -- pick the ONE object whose motion you are asking about, list only the forces acting on THAT object, and add those. The partner force is not on that list, because it acts on the other object. Most wrong answers about the third law come from skipping step four and adding forces that live on two different objects.` },
    { loId: 'm8sci.newtons-third-law-action-reaction-pairs', kind: 'definition', title: `Newton's third law`, content: `when one object pushes or pulls on a second object, the second object pushes or pulls back on the first at the same instant, with a force of the same size in the opposite direction.` },
    { loId: 'm8sci.newtons-third-law-action-reaction-pairs', kind: 'definition', title: 'action-reaction pair', content: `the two forces of one interaction: equal in size, opposite in direction, and acting on two different objects. Also called a force pair.` },
    { loId: 'm8sci.newtons-third-law-action-reaction-pairs', kind: 'definition', title: 'interaction', content: 'two objects acting on each other, which is what every force really is.' },
    { loId: 'm8sci.newtons-third-law-action-reaction-pairs', kind: 'definition', title: 'balanced forces', content: `two or more forces on ONE object that add to a net force of zero, so that object's motion does not change.` },
    { loId: 'm8sci.newtons-third-law-action-reaction-pairs', kind: 'definition', title: 'net force', content: `the single force left over when all the forces on one object are added together, taking their directions into account.` },
    { loId: 'm8sci.newtons-third-law-action-reaction-pairs', kind: 'definition', title: 'inertia', content: `how hard an object's motion is to change. Inertia grows with mass, so the same size force changes a small mass more than a large one.` },
  ],
  methods: [
    {
      title: 'Worked rocket and its gas',
      steps: [
        `Name the two objects that are interacting. It is tempting to say the rocket and the ground, but the rocket leaves the ground in the first moment and keeps rising for a long time after that, so the ground cannot be the answer. It is also tempting to say the rocket and the air. The two objects actually pushing on each other are the ROCKET and the HOT GAS it is throwing out.`,
        `Write the first half of the pair as one sentence, with the object and the direction stated. The rocket pushes the hot gas downward, hard and continuously, out of the bottom of the engine.`,
        `Write the partner by swapping the objects and reversing the direction, keeping the size the same. The hot gas pushes the rocket upward, with a force of exactly the same size, at the same instant. That upward push on the rocket is what lifts it. Nothing else needs to be under the rocket at all.`,
        `Now check that the pair does not cancel, which is where the counting test earns its place. The downward force acts on the GAS, and you can see what it does: the gas shoots downward at enormous speed. The upward force acts on the ROCKET, and you can see what that does too: the rocket rises. Two forces, two objects, two different results. There is no one object for them to add up on, so they never cancel.`,
        `WRONG: "The rocket rises because the gas pushes down on the ground, or on the air, and shoves the rocket up." CORRECT: "The gas pushes on the ROCKET, because the rocket is what pushed the gas. A rocket needs nothing underneath it to push against, which is why a rocket keeps working high above the ground where there is almost no air left." A common way to say this badly is that the rocket is "riding on" the exhaust. It is not resting on anything. It is being pushed by the gas it threw away.`,
        `Run the check a science answer needs, because there is no arithmetic here to redo. First, three clues of DIFFERENT KINDS that agree. The object inventory: after lift-off nothing is touching the rocket except its own gas and the air around it, and the air is pushing backward against its motion, not forward. The directions: the gas leaves downward and the rocket goes upward, exactly opposite, which is what a pair requires and what no other explanation predicts. The timing: the rocket starts rising at the instant the gas starts leaving and stops gaining speed the moment the engines shut off, which is what you would see if the gas were the pusher and would not see if the ground were.`,
        `Second, change one condition and check that the answer moves with it. Steer the engines so that the hot gas leaves sideways, to the east, instead of downward. The pair follows the change: the rocket pushes the gas east, so the gas pushes the rocket west, and the rocket is pushed sideways rather than up. The direction of the push on the rocket is always exactly opposite the direction it threw the gas. If the ground were doing the pushing, turning the nozzle could not have changed which way the rocket went.`,
      ],
      example: { problem: `A rocket stands on a launch pad. Its engines burn fuel and send a huge stream of hot gas straight downward out of the bottom of the rocket, and the rocket lifts off. A student says the rocket rises because the hot gas pushes down against the ground. Name the action-reaction pair, say what pushes the rocket upward, and say whether the student is right.`, solution: `The pair is: the rocket pushes the hot gas downward, and the hot gas pushes the rocket upward with a force of the same size at the same instant. The upward push on the rocket is what lifts it. The student is not right -- the gas does not need to push against the ground or the air, and the proof is that a rocket still works high above the ground where there is almost no air, and that aiming the gas sideways pushes the rocket the opposite way.` },
      relatedLoIds: ['m8sci.newtons-third-law-action-reaction-pairs'],
    },
    {
      title: 'Worked pushing a box',
      steps: [
        `Name the pair first, before anything is added. The two objects interacting are you and the box. You push the box forward with 40 newtons; the box pushes you backward with 40 newtons, at the same instant. Equal in size, opposite in direction, one force on the box and one force on you.`,
        `Now pick the ONE object whose motion the question is about. It is the box. So list only the forces acting ON THE BOX: your push, 40 newtons forward, and friction from the floor, 10 newtons backward. The box's 40-newton push on YOU is not on this list, and leaving it off is not a trick -- it acts on you, so it changes your motion, not the box's.`,
        `Add the forces on the box along the line of motion. Forty newtons forward and 10 newtons backward leave a net force of 30 newtons forward, because 40 - 10 = 30. A net force of 30 newtons forward on the box means the box's motion changes forward: it speeds up. That is the answer to the question asked.`,
        `WRONG: "The 40 newtons forward and the 40 newtons backward cancel." CORRECT: "Those two forces are never added together, because they act on different objects. The only forces that get added are the ones on the same object -- here, the 40 newtons forward and the 10 newtons backward, both on the box." The student added one force on the box to one force on a person. That sum is about nothing.`,
        `For completeness, run the same routine on the other object, which is you. The forces on you along the line are the box pushing you backward with 40 newtons and friction from the floor pushing your shoes forward. That is why you cannot push a heavy box while standing on slick ice: without the floor's forward push on your shoes, the box's backward push on you simply slides you away.`,
        `Run the check. First, three clues of DIFFERENT KINDS that agree that the box's push on you is real and is on you. Your hands feel pressed and flattened while you push, which is that force acting on them. Your body leans forward into the box, which is what a person does to stay put against a backward push. And the ice case just described is a contrast of a third kind: remove the floor's grip on your shoes and you, not the box, are the thing that moves.`,
        `Second, change exactly one condition and see the answer move. Push the same box, with the same 40 newtons, onto thick carpet where friction pushes backward on the box with 40 newtons instead of 10. Now the forces on the box are 40 newtons forward and 40 newtons backward, and 40 - 40 = 0, so the net force on the box is zero and the box stops speeding up -- it keeps whatever steady speed it had, or stays at rest if it was at rest. Notice what did NOT change: the action-reaction pair is still 40 newtons on the box and 40 newtons on you, exactly as before. The pair never decided anything. What decided it was the list of forces on the box.`,
      ],
      example: { problem: `You push a heavy box forward across a gym floor with a force of 40 newtons. Friction from the floor pushes backward on the box with a force of 10 newtons. The box speeds up. A student objects: "The box pushes back on you with 40 newtons, so 40 newtons forward and 40 newtons backward cancel, and the box cannot speed up at all." Name the pair, and explain why the box speeds up anyway.`, solution: `The pair is: you push the box forward with 40 newtons, and the box pushes you backward with 40 newtons. Those two never cancel, because one acts on the box and one acts on you. The box speeds up because the forces ON THE BOX are 40 newtons forward and 10 newtons of friction backward, and 40 - 10 = 30 newtons of net force forward. On thick carpet, with 40 newtons of friction, 40 - 40 = 0 and the box would stop speeding up, even though the pair is unchanged.` },
      relatedLoIds: ['m8sci.newtons-third-law-action-reaction-pairs'],
    },
  ],
  pointers: [
    { content: `Students often say "The two forces of a pair cancel, so nothing could ever be pushed anywhere." — Forces are added only when they act on the same object, and the two halves of a pair never do. Push a book across a table: your hand pushes the book forward, and that force acts on the BOOK, so the book speeds up forward. The book pushes your hand backward, and that force acts on your HAND, so your hand is pushed backward and you feel the book press into your fingers. There is no single object for those two to be added on, so there is no sum, and nothing cancels. The way to catch this every time is to write the object beside each force before adding anything: "20 newtons forward, on the book" and "20 newtons backward, on the hand" cannot be added, while "20 newtons forward on the book" and "6 newtons of friction backward on the book" can, and those two leave a net force of 14 newtons forward on the book. And if pairs really did cancel, then no push you have ever given anything would have moved it, because every push you have ever given has had a partner.`, kind: 'common-error' },
    { content: `Students often say "I push on the cart harder than the cart pushes on me, because I am the one doing the pushing and the cart is the thing that rolls away." — The two forces are the same size, always, no matter which object is heavier, which one is moving, or which one you think of as doing the pushing. What is different is not the forces but the masses, and inertia grows with mass, so the same size force changes a light object's motion a lot and a heavy object's motion very little. The empty cart rolls away because it has far less mass than you do and its wheels turn freely; you barely move because you have much more mass and because friction from the floor holds your shoes in place. Change one condition and watch the answer move: push the same cart just as hard while standing on a smooth floor in socks, and now YOU slide backward too, even though the push is exactly the size it was before. WRONG: "The one that moves more was pushed harder." CORRECT: "Both were pushed the same. The one with less mass changed its motion more."`, kind: 'common-error' },
    { content: `Newton's third law: when object A pushes or pulls on object B, object B pushes or pulls back on A at the same instant, with a force of the same size, in the opposite direction.`, kind: 'tip' },
    { content: `The two forces of an action-reaction pair act on DIFFERENT objects -- one on each -- and that is the whole reason they never cancel.`, kind: 'tip' },
    { content: `Forces are added together only when they act on the same object. Before adding anything, write the object beside each force.`, kind: 'tip' },
    { content: `A pair is two forces on two objects, each pushing the other. Balanced forces are two forces on ONE object that add to zero. They look identical until you count the objects.`, kind: 'tip' },
    { content: `Equal forces do not mean equal effects. The same size force changes a small mass much more than a large one, because inertia grows with mass.`, kind: 'tip' },
    { content: `To answer "why did it move", pick the one object you care about, list only the forces on THAT object, and add those. The partner force belongs to the other object and is not on the list.`, kind: 'tip' },
    { content: `To name a pair: name the two objects, write "A pushes B this way", then swap the objects and reverse the direction, keeping the size the same.`, kind: 'tip' },
    { content: `To get pushed forward, push something backward: a shoe pushes the ground back and the ground pushes the shoe forward; a rocket pushes gas down and the gas pushes the rocket up.`, kind: 'tip' },
  ],
};
