/**
 * Grade 8 Science — Unit 1 CED 1.1: Motion, Reference Points & Speed.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.motion-reference-points-and-speed.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U1_MOTION_REFERENCE_POINTS_AND_SPEED: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.motion-reference-points-and-speed.v1',
  course: 'Grade 8 Science',
  cedUnit: 1,
  cedTopic: '1.1',
  cedTitle: 'Motion, Reference Points & Speed',
  planId: 'evelyn.ms.m8sci.motion-reference-points-and-speed.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.motion-reference-points-and-speed.v1' }],
  theory: [
    { loId: 'm8sci.motion-reference-points-and-speed', content: `MOTION IS ALWAYS A COMPARISON, AND THE THING YOU COMPARE WITH IS THE REFERENCE POINT. An object is in MOTION when its position -- how far it is from a chosen object, and in which direction -- changes as time passes. It is AT REST when that position stays the same. The chosen object is called the reference point, and you get to choose it: a seat, a curb, a stop sign, a doorway, a friend standing on the sidewalk. Take a passenger sitting on a bus that is driving down a road. Compared with his seat, he stays exactly where he is: same distance from the back of the seat, same distance from the armrest, second after second. Compared with a stop sign back on the sidewalk, he is farther away every second. Nothing about the passenger is different in those two sentences. What changed is what he was compared with.` },
    { loId: 'm8sci.motion-reference-points-and-speed', content: `THE SAME OBJECT CAN BE AT REST AND IN MOTION AT THE SAME MOMENT, AND THAT IS NOT A TRICK. The passenger is at rest compared with his seat and in motion compared with the stop sign, and both statements are true at once. They do not fight each other, because each one names a different reference point. This is why a motion question is not finished until the reference point is said out loud. WRONG: "Is the passenger moving? Yes." CORRECT: "The passenger is at rest compared with his seat, and moving compared with the stop sign." A question that gives you no reference point and expects one answer is a question you cannot answer, and saying so is the right move.` },
    { loId: 'm8sci.motion-reference-points-and-speed', content: `SPEED PUTS A NUMBER ON HOW QUICKLY THE POSITION CHANGES. Average speed equals the total distance divided by the total time (speed = distance ÷ time). Both measurements come from the same trip, measured from the same reference point, and both go into the answer. The unit is built out of the two measurements you divided: meters divided by seconds gives METERS PER SECOND (m/s), and that unit is a sentence in itself -- it says how many meters the object covers during each second of the trip. A speed of 3 meters per second means 3 meters of ground in the first second, 3 more in the next, and so on. Drop the unit and the number stops meaning anything: "3" could be 3 meters, 3 seconds or 3 meters per second, and those are three different facts.` },
    { loId: 'm8sci.motion-reference-points-and-speed', content: `AN AVERAGE IS A WHOLE-TRIP NUMBER, NOT A REPORT ON ANY ONE MOMENT. Average speed is built from just two measurements -- the total distance and the total time -- and it throws away everything that happened in between. The best way to say what it means is this: it is the one steady speed that would have covered the same distance in the same time. A trip that included a wait at a red light and a fast stretch afterwards has exactly the same average speed as a smooth trip with the same total distance and the same total time. So the average tells you about the trip as a whole, and it does not tell you what was happening at any single second of it.` },
    { loId: 'm8sci.motion-reference-points-and-speed', content: `THE ROUTINE, IN ORDER. (1) Name the reference point, because without one there is no question. (2) Compare the object's position with that reference point at the start and at the end: if the distance or direction from it changed, the object was in motion; if not, it was at rest. (3) If a speed is wanted, collect the total distance and the total time, in units that match -- one minute is 60 seconds, so a trip timed at 2 minutes is a trip of 120 seconds. (4) Divide the distance by the time. (5) Say the answer with its unit, in words: so many meters per second. (6) Check it by turning the formula around -- distance = speed × time -- and confirming that the speed multiplied by the time gives back the distance you were told. To compare two objects, run steps 3 to 6 separately for each one, using that object's own two numbers, and then compare the two speeds. Never compare the distances on their own, and never compare the times on their own.` },
    { loId: 'm8sci.motion-reference-points-and-speed', kind: 'definition', title: 'reference point', content: `the object you choose to compare something with when you decide whether it is moving; the comparison is meaningless until this is named.` },
    { loId: 'm8sci.motion-reference-points-and-speed', kind: 'definition', title: 'position', content: `where an object is, given as its distance and direction from a chosen reference point.` },
    { loId: 'm8sci.motion-reference-points-and-speed', kind: 'definition', title: 'motion', content: `a change in an object's position compared with a chosen reference point as time passes; an object whose position does not change is at rest with respect to that point.` },
    { loId: 'm8sci.motion-reference-points-and-speed', kind: 'definition', title: 'distance', content: 'how much ground an object covered, measured in meters.' },
    { loId: 'm8sci.motion-reference-points-and-speed', kind: 'definition', title: 'average speed', content: `the total distance of a trip divided by the total time it took; the one steady speed that would have covered that distance in that time.` },
    { loId: 'm8sci.motion-reference-points-and-speed', kind: 'definition', title: 'meters per second', content: `the unit that comes from dividing a distance in meters by a time in seconds, saying how many meters are covered during each second.` },
  ],
  methods: [
    {
      title: 'Worked bus passenger and its speed',
      steps: [
        `Step 1, name the reference point, because the motion question is not answerable without one. Two are offered here, the seat and the stop sign, so take them one at a time and answer twice.`,
        `Step 2, compare the position at the start with the position at the end, using the seat. He sat down on that seat, and 30 seconds later he is on the same seat, the same distance from its back and the same distance from its armrest. His position with respect to the seat did not change. With respect to the seat, he is at rest.`,
        `Step 3, run the identical comparison against the stop sign. At the start he was level with the stop sign, so the distance between him and the sign was zero. After 30 seconds that distance is 240 meters, and it grew a little more with every second in between. His position with respect to the stop sign changed. With respect to the stop sign, he is in motion. Both answers stand, and neither one cancels the other, because each one names the point it was measured from.`,
        `Step 4, now the speed. Average speed is the total distance divided by the total time: speed = distance ÷ time. Measured from the stop sign, the distance is 240 meters and the time is 30 seconds, so the average speed is 240 meters divided by 30 seconds, which is 8 meters per second. Say the unit, because it carries half the meaning: 8 meters per second means the bus gets 8 meters farther from that stop sign during each second of the ride. WRONG: "The answer is 8 meters." CORRECT: "The answer is 8 meters per second, and over 30 seconds of that the bus covered 240 meters."`,
        `Now run the two checks a science answer needs. First, three clues of DIFFERENT KINDS that agree. One, the arithmetic itself: 240 meters divided by 30 seconds gives 8 meters per second. Two, the formula turned around: distance = speed × time, and 8 meters per second × 30 seconds = 240 meters, which is exactly the distance the problem gave, so the division was done the right way up. Three, a size check against something you already know: a person walking covers a couple of meters in a second at most, so a bus on an open road ought to come out several times a walking pace, and 8 meters per second does. Had the division been done upside down, dividing the 30 seconds by the 240 meters, the number would have been 0.125 rather than 8, and a bus creeping along at 0.125 meters per second would be far slower than a person on foot. The size check catches that on its own, without redoing the division.`,
        `Second, change one thing about the setup and confirm that the answer moves the way it should. Change the reference point from the stop sign to the seat, and the answer to "is he moving" flips from yes to no, while absolutely nothing about the passenger changed -- which is the sign that this answer belongs to the PAIR of objects and not to the passenger by himself. Now leave the reference point alone and change the time instead: if the same 240 meters had taken 60 seconds, the average speed would be 240 meters divided by 60 seconds, which is 4 meters per second, half of what it was. Both times, the answer moved when the evidence moved.`,
      ],
      example: { problem: `A bus pulls away from a stop and drives along a straight road. A passenger sits still in his seat with his phone in his lap the whole way. After 30 seconds the bus is 240 meters down the road from the stop sign it started level with. First: is the passenger moving? Answer for two reference points -- the seat he is sitting on, and the stop sign back on the sidewalk. Then find the bus's average speed over those 30 seconds.`, solution: `With respect to his seat the passenger is at rest, because his position on the seat does not change. With respect to the stop sign he is in motion, because his distance from it grows to 240 meters. Both are true, and each one names its reference point. The bus's average speed over the 30 seconds is 240 meters divided by 30 seconds, which is 8 meters per second.` },
      relatedLoIds: ['m8sci.motion-reference-points-and-speed'],
    },
    {
      title: 'Worked comparing two average speeds',
      steps: [
        `Step 1, notice why neither measurement settles this on its own. The jogger covered more ground, which sounds like the faster one. The skateboarder used less time, which also sounds like the faster one. Distance alone and time alone point at different people, so neither of them is the answer. Average speed is the one number with BOTH measurements inside it, and that is the whole reason for working it out.`,
        `Step 2, divide for the skateboarder, using the skateboarder's own two numbers. Speed = distance ÷ time, so 60 meters divided by 20 seconds gives 3 meters per second.`,
        `Step 3, divide for the jogger, using the jogger's own two numbers and never mixing them with the skateboarder's. 100 meters divided by 50 seconds gives 2 meters per second.`,
        `Step 4, compare the two speeds, which is now a comparison of two numbers with the same unit. 3 meters per second is greater than 2 meters per second, so the skateboarder had the greater average speed even though the jogger covered the greater distance. WRONG: "The jogger went 100 meters and the skateboarder went only 60 meters, so the jogger was faster." CORRECT: "The jogger covered more ground but spent two and a half times as long doing it, because 50 seconds divided by 20 seconds is 2.5; per second of travel, the skateboarder covered more."`,
        `Now the two checks. Three clues of DIFFERENT KINDS that agree. One, the two divisions: 3 meters per second against 2 meters per second. Two, a like-for-like comparison over equal time, which asks the question a different way instead of repeating the division: in 20 seconds the skateboarder covers 60 meters, and the jogger at 2 meters per second covers 2 meters per second × 20 seconds = 40 meters in that same 20 seconds, so over equal time the skateboarder is ahead by 20 meters. Three, the formula turned around on each one: 3 meters per second × 20 seconds = 60 meters, and 2 meters per second × 50 seconds = 100 meters, and both of those are the distances the problem gave.`,
        `And now change one thing. Leave the jogger's 100 meters exactly as it is, and let her cover it in 25 seconds instead of 50. Her average speed becomes 100 meters divided by 25 seconds, which is 4 meters per second, and the jogger is now the faster of the two, at 4 meters per second against 3 meters per second. Not one distance changed; a single time did, and the verdict flipped. That is how you know the verdict was really resting on both measurements, and was not quietly resting on the distances alone.`,
      ],
      example: { problem: `On the same flat, straight path, a skateboarder rolls 60 meters in 20 seconds, and a jogger runs 100 meters in 50 seconds. The jogger covered the greater distance. The skateboarder was finished in the shorter time. Which one had the greater average speed?`, solution: `The skateboarder. 60 meters divided by 20 seconds gives 3 meters per second, and 100 meters divided by 50 seconds gives 2 meters per second, so the skateboarder covers more ground during each second of travel even though the jogger covered the greater total distance. Over the same 20 seconds, the jogger would cover only 40 meters.` },
      relatedLoIds: ['m8sci.motion-reference-points-and-speed'],
    },
  ],
  pointers: [
    { content: `Students often say "Standing still on a moving walkway, I am not moving, because I am not walking." — Motion is a comparison, and the sentence is only half finished until it says what the comparison is with. Compared with the surface of the walkway under your shoes, and with a suitcase riding along beside you, you are at rest: your distance from both of them stays the same second after second. Compared with the floor beside the walkway, or with a gate sign on the wall, you are in motion, because your distance from those is changing every second. Both statements are true at the same moment and they do not fight each other, because each one names the reference point it was measured from. WRONG: "I am not moving." CORRECT: "I am at rest compared with the walkway, and in motion compared with the floor beside it."`, kind: 'common-error' },
    { content: `Students often say "The van averaged 10 meters per second, so it was going 10 meters per second the whole way." — An average speed is built from exactly two measurements, the total distance and the total time, and it throws away everything that happened in between. Suppose the van covered 600 meters in 60 seconds: its average speed is 600 meters divided by 60 seconds, which is 10 meters per second. That same average fits a van that rolled steadily for the whole minute, and it fits a van that waited at a red light for 20 seconds and then covered all 600 meters in the remaining 40 seconds, which works out at 600 meters divided by 40 seconds, or 15 meters per second while it was actually moving. An average speed is the one steady speed that would have covered the same distance in the same time. WRONG: "The average was 10 meters per second, so it was doing 10 meters per second at every moment." CORRECT: "The average over the whole trip was 10 meters per second, and what the van was doing at any one second is not something an average can tell you."`, kind: 'common-error' },
    { content: `An object is in motion when its position changes compared with a chosen reference point, and it is at rest when that position stays the same.`, kind: 'tip' },
    { content: `Every statement about motion has to name its reference point. "The passenger is moving" is not finished; "the passenger is moving compared with the stop sign" is.`, kind: 'tip' },
    { content: `The same object can be at rest compared with one reference point and in motion compared with another at the same moment, and both statements are true.`, kind: 'tip' },
    { content: `Average speed is the total distance divided by the total time: speed = distance ÷ time.`, kind: 'tip' },
    { content: `The unit comes from the two measurements you divided. Meters divided by seconds gives meters per second, which says how many meters are covered during each second. A speed reported as a number of meters is not a speed.`, kind: 'tip' },
    { content: `Check a speed by turning the formula around: distance = speed × time. The speed multiplied by the time should give back the distance you were told.`, kind: 'tip' },
    { content: `To decide which of two objects is faster, divide each one's own distance by its own time and compare the two speeds. The greater distance does not settle it, and neither does the smaller time.`, kind: 'tip' },
    { content: `An average speed is the one steady speed that would have covered the same distance in the same time. It does not report what was happening at any single moment of the trip.`, kind: 'tip' },
    { content: `Every motion sentence must name its reference point or it is not finished. "The passenger is moving" stops mid-thought. Say what you're comparing it to: "The passenger is moving compared with the stop sign."`, kind: 'common-error' },
    { content: `An object can be at rest AND in motion at the exact same moment. Both are true if they name different reference points. Stop thinking one answer must be right and the other wrong.`, kind: 'gotcha' },
    { content: `To compare speeds, divide EACH object's own distance by THAT object's own time. Never compare distances alone or times alone. A bigger distance with a much bigger time can be slower.`, kind: 'common-error' },
    { content: `The unit matters as much as the number. "3" without a unit is meaningless—it could be 3 meters, 3 seconds, or 3 meters per second, and those are three different facts. Always write the unit.`, kind: 'vocab-note' },
    { content: `Average speed is a whole-trip number built from two measurements: total distance and total time. It does NOT tell you what was happening at any one second. A van that waits at a light and speeds up later has the same average as one that rolls steadily, if the distance and time are the same.`, kind: 'edge-case' },
    { content: `Check your speed answer by flipping the formula: distance = speed × time. Multiply speed by time and you should get back the distance the problem gave you. If not, you divided upside down.`, kind: 'tip' },
    { content: `Position is distance AND direction from a reference point. Saying "the bus is 240 meters from the stop sign" is complete, but saying "the bus is 240 meters" is not—farther away in which direction from what?`, kind: 'vocab-note' },
  ],
};
