/**
 * Grade 8 Science — Unit 6 CED 6.3: Density, Thermal Expansion & Why Warm Fluids Rise.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.density-thermal-expansion-and-why-warm-fluids-rise.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U6_DENSITY_THERMAL_EXPANSION_AND_WHY_WARM_FLUIDS_RISE: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.density-thermal-expansion-and-why-warm-fluids-rise.v1',
  course: 'Grade 8 Science',
  cedUnit: 6,
  cedTopic: '6.3',
  cedTitle: 'Density, Thermal Expansion & Why Warm Fluids Rise',
  planId: 'evelyn.ms.m8sci.density-thermal-expansion-and-why-warm-fluids-rise.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.density-thermal-expansion-and-why-warm-fluids-rise.v1' }],
  theory: [
    { loId: 'm8sci.density-thermal-expansion-and-why-warm-fluids-rise', content: `DENSITY IS HOW MUCH MASS IS PACKED INTO EACH BIT OF SPACE. Two measurements decide it. One is how much matter the sample contains, which we measure as its mass in grams. The other is how much room that matter takes up, which we measure as its volume in cubic centimeters. To get the density, divide the mass by the volume, and the answer comes out in grams per cubic centimeter -- the number of grams sitting in every single cubic centimeter of the sample. A sample with a mass of 40 grams that takes up 8 cubic centimeters has 5 grams in every cubic centimeter, so its density is 5 grams per cubic centimeter. Water is the one worth holding on to: the density of water is about 1 gram per cubic centimeter, so one cubic centimeter of water holds about one gram of water.` },
    { loId: 'm8sci.density-thermal-expansion-and-why-warm-fluids-rise', content: `DENSITY IS NOT MASS, AND IT IS NOT SIZE. This is the part that takes real work, because in everyday speech "dense" and "heavy" are used to mean almost the same thing, and they are not. A sample can have a large mass and a low density: a beach ball blown up full of air has more mass than a small glass marble, and the marble is the denser of the two by an enormous margin, because the beach ball spreads its small amount of matter through a huge volume. A sample can also have a small mass and a high density, which is exactly what the marble is. And here is the test that separates density from mass every time: density does not depend on how much of a sample you have. Cut a block cleanly in half and each half has half the mass and half the volume, so the grams in every cubic centimeter are exactly what they were. Mass changes when you cut. Volume changes when you cut. Density does not.` },
    { loId: 'm8sci.density-thermal-expansion-and-why-warm-fluids-rise', content: `WARMING A FLUID SPREADS ITS PARTICLES OUT, AND THAT IS ALL IT DOES TO THEM. A fluid is anything that flows and takes the shape of its container -- a liquid or a gas. Warm a fluid and its particles move faster, and faster particles knock one another farther apart, so on average there is more space between them than there was. Two things follow, and you should say them separately. The mass does not change, because no particles were added and none were taken away; every particle that was there is still there. The volume goes up, because those same particles now need more room. Same mass, bigger volume, fewer grams in every cubic centimeter: the fluid has become LESS DENSE. That spreading out is called thermal expansion, and cooling runs it backward -- the particles slow down, crowd closer, the volume shrinks and the density goes up. WRONG: "Heating makes each particle swell up to a bigger size." CORRECT: "Every particle stays exactly the same size. What changes is how fast they move and how far apart they sit." One caution about water, because it is the exception people meet first: when liquid water freezes it EXPANDS, so ice is less dense than liquid water and floats on it. Never say that a solid is always denser than its liquid.` },
    { loId: 'm8sci.density-thermal-expansion-and-why-warm-fluids-rise', content: `NOTHING RISES BECAUSE IT WANTS TO. Put a warmed, less dense parcel of fluid next to the cooler, denser fluid around it, and here is what actually happens. The cooler fluid has more mass in every cubic centimeter, so it sinks, and as it sinks it slides underneath the warmed parcel and pushes that parcel up. The warm part going up and the cool part coming down are one single exchange, not two separate events, and you cannot have either half without the other. That is the answer to the room at the start: the heater warmed the air down at floor level, that air became less dense, and the cooler air filling the rest of the room sank under it and pushed it toward the ceiling. WRONG: "Warm air rises because it is trying to get away from the heater." CORRECT: "Warm air is less dense than the cooler air around it, so the cooler air sinks under it and pushes it up." When that exchange keeps going round and round inside a fluid it has a name -- convection -- and how it carries thermal energy from place to place is a separate lesson. This lesson is about the density difference that starts it.` },
    { loId: 'm8sci.density-thermal-expansion-and-why-warm-fluids-rise', content: `THE SAME SENTENCE WORKS AT EVERY SIZE. In a room, air warmed near the floor ends up near the ceiling, because the cooler air comes down and takes its place. In the ocean, water that is colder is denser than the water above it and sinks beneath it, setting slow movements going that a separate lesson follows. And far below your feet, in the layer of rock called the mantle, the rock is hot enough to creep along like something thick and slow rather than snapping like a brittle solid; hotter mantle rock is less dense than the cooler rock around it and moves upward, while cooler, denser rock sinks. Three wildly different sizes, from a bedroom to the inside of a planet, and the sentence you say about each of them is word for word the same one. It is the density difference that does the work, and how big the thing is makes no difference at all to the reasoning.` },
    { loId: 'm8sci.density-thermal-expansion-and-why-warm-fluids-rise', content: `HOW TO ANSWER ANY DENSITY QUESTION IN THIS LESSON. First, name the two things you are comparing, and check that you have the mass AND the volume of each of them -- or, if only one thing is being changed, check what happened to its mass and what happened to its volume. Second, if you have numbers, divide each mass by its own volume and read off the grams in every cubic centimeter, keeping each sample's two numbers together. If you do not have numbers, ask the two questions separately: did the mass change, and did the volume change? Third, say which one is denser, and say it as "more grams in every cubic centimeter", never as "heavier". Fourth, if the question is about a fluid, finish the sentence: the denser fluid sinks, slides underneath, and pushes the less dense fluid up above it. Getting the first step right is most of the work, because a question that hands you two masses and no volumes has not told you which sample is denser.` },
    { loId: 'm8sci.density-thermal-expansion-and-why-warm-fluids-rise', kind: 'definition', title: 'density', content: `how much mass is packed into each unit of volume; the mass of a sample divided by its volume, given here in grams per cubic centimeter.` },
    { loId: 'm8sci.density-thermal-expansion-and-why-warm-fluids-rise', kind: 'definition', title: 'volume', content: 'how much room a sample takes up, measured here in cubic centimeters.' },
    { loId: 'm8sci.density-thermal-expansion-and-why-warm-fluids-rise', kind: 'definition', title: 'mass', content: `the amount of matter in a sample, measured here in grams. Warming or cooling a sealed sample does not change it.` },
    { loId: 'm8sci.density-thermal-expansion-and-why-warm-fluids-rise', kind: 'definition', title: 'fluid', content: 'anything that flows and takes the shape of its container -- a liquid or a gas.' },
    { loId: 'm8sci.density-thermal-expansion-and-why-warm-fluids-rise', kind: 'definition', title: 'thermal expansion', content: `the growth in a sample's volume when it is warmed, caused by its particles moving faster and spreading farther apart, and never by the particles themselves growing.` },
  ],
  methods: [
    {
      title: 'Worked three samples',
      steps: [
        `Set up the one calculation you need, and run it three times. For each sample, the question is how many grams sit in every single cubic centimeter of it, and you get that by dividing the mass by the volume. Keep each sample's two numbers together and never mix one sample's mass with another sample's volume.`,
        `Sample A: 48 grams divided by 6 cubic centimeters gives 8 grams per cubic centimeter. Sample B: 48 grams divided by 16 cubic centimeters gives 3 grams per cubic centimeter. Sample C: 120 grams divided by 15 cubic centimeters gives 8 grams per cubic centimeter.`,
        `Read the three answers off. Sample A and Sample C both hold 8 grams in every cubic centimeter, so they are equally dense, and they are the densest. Sample B holds 3 grams in every cubic centimeter and is the least dense of the three. The order from densest to least dense is Sample A and Sample C tied, then Sample B.`,
        `Now the second question, and it is the one that catches people out. Sample C has by far the largest mass -- 120 grams against 48 grams -- and it is not denser than Sample A. It is exactly as dense. WRONG: "Sample C has the most mass, so Sample C must be the densest." CORRECT: "Sample C has the most mass AND the most room to spread that mass through, and the two grew together, so the grams in every cubic centimeter came out the same." Look at both numbers at once: 48 grams times 2.5 is 120 grams, and 6 cubic centimeters times 2.5 is 15 cubic centimeters. Sample C is two and a half Sample A's, and two and a half of something is packed exactly as tightly as one of it.`,
        `Now run the two checks a science answer needs. First, look for clues of DIFFERENT KINDS that agree that Sample A and Sample C are equally dense. The division says so: both come out at 8 grams per cubic centimeter. A same-volume comparison says so a second way, and it does not use the division at all -- take a 6 cubic centimeter piece out of Sample C, and since every cubic centimeter of Sample C holds 8 grams, that piece holds 8 times 6, which is 48 grams, exactly the mass of the whole of Sample A in exactly the same volume. And a sample-size test says so a third way: take a third of Sample C, which is 40 grams filling 5 cubic centimeters, and divide -- 40 grams divided by 5 cubic centimeters is 8 grams per cubic centimeter again. Cutting the sample did not move the number, which is what density does and what mass does not. Three different kinds of check, one answer.`,
        `Second, change one thing and check that the answer moves the way it should. Leave Sample C with its 120 grams, but suppose it had taken up 40 cubic centimeters instead of 15. Now 120 grams divided by 40 cubic centimeters is 3 grams per cubic centimeter, so Sample C would be tied with Sample B as the LEAST dense sample on the bench -- with exactly the mass it had before. The mass never moved. The volume moved, and the answer moved with it, which is the sign that the volume was pulling its weight in the reasoning all along.`,
      ],
      example: { problem: `Three samples sit on a bench, all of them at the same temperature. Sample A has a mass of 48 grams and takes up 6 cubic centimeters. Sample B has a mass of 48 grams and takes up 16 cubic centimeters. Sample C has a mass of 120 grams and takes up 15 cubic centimeters. Put the three in order from densest to least dense. Then answer a second question: is the sample with the largest mass the densest one?`, solution: `Sample A and Sample C are equally dense at 8 grams per cubic centimeter, and Sample B is the least dense at 3 grams per cubic centimeter, so the order from densest to least dense is Sample A and Sample C tied, then Sample B. No, the sample with the largest mass is not the densest: Sample C has two and a half times the mass of Sample A and two and a half times the volume, so the two of them pack their matter exactly as tightly as each other.` },
      relatedLoIds: ['m8sci.density-thermal-expansion-and-why-warm-fluids-rise'],
    },
    {
      title: 'Worked warmed pouch',
      steps: [
        `Start with the mass, because it is the one that does not move. The pouch is sealed: nothing was added and nothing leaked out, so every particle that was inside at the start is still inside at the end. The mass is 300 grams before and 300 grams after. Warming a fluid does not add matter to it.`,
        `Now the volume. It went from 100 cubic centimeters to 120 cubic centimeters. Why? The particles are moving faster than they were, so they knock one another farther apart, and the same particles now need more room to move in. WRONG: "The particles got bigger, so the fluid got bigger." CORRECT: "Every particle is exactly the same size it always was. It is the spaces between them that got bigger."`,
        `Now the density, which is only those two numbers put together. Before: 300 grams divided by 100 cubic centimeters is 3 grams per cubic centimeter. After: 300 grams divided by 120 cubic centimeters is 2.5 grams per cubic centimeter. The same 300 grams is now spread through more room, so every cubic centimeter of it holds less. The density fell from 3 grams per cubic centimeter to 2.5 grams per cubic centimeter.`,
        `Now the last question. The room-temperature Sample L filling the tank is still at 3 grams per cubic centimeter, and the warmed fluid is at 2.5 grams per cubic centimeter, which is less. So the room-temperature fluid, with more mass in every cubic centimeter, sinks underneath the warmed fluid and pushes it up. The warmed fluid moves upward -- not because it is trying to, and not because warmth travels upward, but because denser fluid went under it.`,
        `Now run the two checks. First, three clues of DIFFERENT KINDS that agree the density went down. The inventory clue: the mass is pinned at 300 grams by the seal while the volume grew, and a fixed amount of matter spread over a growing amount of room can only thin out. The arithmetic clue: 3 grams per cubic centimeter before and 2.5 grams per cubic centimeter after, worked out from the stated numbers. And the particle clue, which uses no numbers at all: the same particles are now spread through 120 cubic centimeters instead of 100, so any cubic centimeter you pick out contains fewer of them than it used to. An inventory, a division and a picture of the particles, all pointing the same way.`,
        `Second, change one thing and check that the answer moves. Put the same sealed pouch in a refrigerator instead of a warm room. Now the particles slow down, they crowd closer together and the pouch shrinks -- say to 75 cubic centimeters. The mass is still 300 grams, because the pouch is still sealed, so the density is 300 grams divided by 75 cubic centimeters, which is 4 grams per cubic centimeter. That is MORE than the 3 grams per cubic centimeter of the room-temperature fluid in the tank, so this time the pouchful would sink instead of being pushed up. One condition changed -- warmed became cooled -- and the answer turned right around, which is how you know the density was doing the work and not something else.`,
      ],
      example: { problem: `Sample L is a fluid. Its numbers are picked to keep the arithmetic easy, and the swelling described here is drawn far larger than any real liquid would show. A sealed, stretchy pouch holds 300 grams of Sample L, and at room temperature the fluid inside takes up 100 cubic centimeters. The pouch is left somewhere warm. Nothing is added to it and nothing leaks out of it. When the fluid has warmed all the way through, the pouch has swelled and the fluid inside takes up 120 cubic centimeters. What has happened to the mass, the volume and the density of Sample L? And if that warmed pouchful were released gently in the middle of a deep tank of Sample L at room temperature, would it move up or down?`, solution: `The mass is unchanged at 300 grams, because the pouch is sealed. The volume rose from 100 cubic centimeters to 120 cubic centimeters, because the faster-moving particles spread farther apart. So the density fell from 3 grams per cubic centimeter to 2.5 grams per cubic centimeter. Released in a deep tank of room-temperature Sample L, which is still at 3 grams per cubic centimeter, the warmed fluid would move upward, because the denser room-temperature fluid sinks under it and pushes it up.` },
      relatedLoIds: ['m8sci.density-thermal-expansion-and-why-warm-fluids-rise'],
    },
  ],
  pointers: [
    { content: `Students often say "Heavy things sink and light things float, so a steel ship should go straight to the bottom." — What decides whether something stays up in water is its density -- how many grams it has in every cubic centimeter -- and not its mass. A solid bolt of steel is several times denser than water, so it sinks. A ship built out of the same steel is mostly hollow: the steel is wrapped around an enormous volume of air, and the ship as a whole, air included, is less dense than water, so it stays up. Nothing about the steel itself changed. The volume it was spread around did. WRONG: "It is heavy, so it sinks." CORRECT: "It has more grams in every cubic centimeter than water does, so it sinks." The pair that settles the argument is the beach ball and the glass marble from earlier in this lesson: the beach ball has the greater mass and it floats, the marble has the smaller mass and it sinks. If mass were deciding the answer, that pair could not happen.`, kind: 'common-error' },
    { content: `Students often say "When you heat a liquid up it takes more room because every particle in it swells." — A particle does not change size when it is warmed, and it does not melt, shrink or change color either. What warming changes is how fast the particles move. Faster particles knock one another farther apart, so the average space between them grows, and it is that extra space -- not bigger particles -- that makes the sample take up more room. The clearest sign of this is what happens to a gas. Warming a gas can easily make it take up half as much room again, and no particle grows by half. What grows is the empty space between the particles, which in a gas is already far larger than the particles themselves. WRONG: "The particles swell up when you heat them." CORRECT: "The particles stay exactly the same size, and they move farther apart."`, kind: 'common-error' },
    { content: `Density is how much mass is packed into each bit of space. Divide the mass by the volume and read the answer as the grams sitting in every cubic centimeter.`, kind: 'tip' },
    { content: `Density is not mass and it is not size. A sample can have a large mass and a low density, and another can have a small mass and a high density.`, kind: 'tip' },
    { content: `Density does not depend on how much of a sample you have. Cut it in half and the mass halves, the volume halves, and the density is unchanged.`, kind: 'tip' },
    { content: 'The density of water is about 1 gram per cubic centimeter.', kind: 'tip' },
    { content: `Warming a fluid makes its particles move faster and spread farther apart. The mass stays the same, the volume goes up, and so the density goes down. That is thermal expansion, and cooling runs it backward.`, kind: 'tip' },
    { content: 'The particles themselves never swell. Only the spaces between them change.', kind: 'tip' },
    { content: `Nothing rises because it wants to. The cooler, denser fluid sinks, slides underneath the less dense fluid, and pushes it up -- one exchange, not two separate events.`, kind: 'tip' },
    { content: `One sentence covers air near a ceiling, water in the ocean and hot rock in the mantle: the denser fluid sinks and the less dense fluid is pushed up above it.`, kind: 'tip' },
    { content: `Ice is less dense than liquid water, because water expands when it freezes, so never say that a solid is always denser than its liquid.`, kind: 'tip' },
    { content: `Don't say "the warmed fluid rises." Say "the cooler, denser fluid sinks underneath and pushes the warmer fluid up." Rising and sinking are one exchange, not two separate events.`, kind: 'common-error' },
    { content: `Density is NOT mass, NOT size, and NOT how heavy something feels. Two samples with the same mass can have different densities if their volumes differ. A beach ball (heavy) can be less dense than a marble (light).`, kind: 'vocab-note' },
    { content: `When you heat a sealed fluid, the MASS does not change (no particles added or removed), the VOLUME gets bigger, so the DENSITY must go down. Don't say particles swell—they stay the same size, just move farther apart.`, kind: 'common-error' },
    { content: `If a problem gives you two masses but NO volumes, you cannot yet say which sample is denser. You need both numbers for each sample before you divide.`, kind: 'gotcha' },
    { content: `Density does not change when you cut a sample in half. Half the mass, half the volume, same grams in every cubic centimeter. This is the test that proves density is independent of sample size.`, kind: 'edge-case' },
    { content: `Water is weird: ice floats because ice is LESS dense than liquid water. Don't say solids are always denser than liquids—that rule breaks for water.`, kind: 'edge-case' },
    { content: `Always check BOTH what happened to mass AND what happened to volume before you answer a density question. If only one changed, the density changed. If neither changed, the density didn't.`, kind: 'tip' },
    { content: `The same sentence explains a heater at the bottom of a tank, ocean currents, and mantle convection: denser fluid sinks, less dense fluid is pushed up. Size doesn't matter; density difference is what matters.`, kind: 'tip' },
  ],
};
