/**
 * Grade 8 Science — Unit 8 CED 8.3: Reactions That Release or Absorb Thermal Energy.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.reactions-that-release-or-absorb-thermal-energy.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U8_REACTIONS_THAT_RELEASE_OR_ABSORB_THERMAL_ENERGY: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.reactions-that-release-or-absorb-thermal-energy.v1',
  course: 'Grade 8 Science',
  cedUnit: 8,
  cedTopic: '8.3',
  cedTitle: 'Reactions That Release or Absorb Thermal Energy',
  planId: 'evelyn.ms.m8sci.reactions-that-release-or-absorb-thermal-energy.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.reactions-that-release-or-absorb-thermal-energy.v1' }],
  theory: [
    { loId: 'm8sci.reactions-that-release-or-absorb-thermal-energy', content: `EVERY REACTION MOVES THERMAL ENERGY ONE WAY OR THE OTHER. You already know how to tell that a reaction has happened: something after it has a property that nothing you started with had. This lesson asks a second question about that same reaction. Did thermal energy move OUT of the reacting substances and into everything around them, or did it move IN from everything around them? Those are the only two answers. Everything around the reaction -- the rest of the mixture, the container, the table, the air, your hand -- gets one name in this lesson: the surroundings.` },
    { loId: 'm8sci.reactions-that-release-or-absorb-thermal-energy', content: `RELEASING: THE MIXTURE AND ITS CONTAINER GET WARMER. The temperature after is higher than the temperature before, and higher than the room, with no flame, no heater and no hot plate anywhere near it. Here is the part to say carefully: that thermal energy was not made. It was already stored in the substances you started with, held in the way their atoms were arranged, and the reaction moved it out into the surroundings. Energy is never created and never used up -- it is moved, and it is changed from one form into another. WRONG: "The reaction made new energy." CORRECT: "The reaction moved energy that was already stored in the substances out into the surroundings as thermal energy."` },
    { loId: 'm8sci.reactions-that-release-or-absorb-thermal-energy', content: `ABSORBING: THE MIXTURE AND ITS CONTAINER GET COLDER. The temperature after is lower than the temperature before and lower than the room, again with nothing outside cooling it. Here is the part that trips almost everybody: nothing let the cold in, because cold is not a substance and cold does not move anywhere. Thermal energy always moves from the warmer thing to the cooler thing, which is a rule you already hold. The reaction pulled thermal energy out of the mixture, the container and the table, and it keeps pulling it out of your hand for as long as your hand is warmer than the pack. That is the whole reason the pack feels cold to you.` },
    { loId: 'm8sci.reactions-that-release-or-absorb-thermal-energy', content: `THE CLASSIFYING ROUTINE, IN ORDER. (1) Check that nothing outside is doing the heating or the cooling -- no flame, no stove, no freezer, no sunlight on the container. If something outside is doing it, the reading tells you nothing about the reaction. (2) Write down the temperature before and the temperature after. (3) Compare them, and compare the after reading with the room as well, because a mixture that ends up warmer than the room it is sitting in cannot have been warmed by that room. (4) Warmer means the reaction released thermal energy; colder means it absorbed thermal energy. If you can also compare against the same substances sitting there not reacting, do it, because that is the cleanest check of all.` },
    { loId: 'm8sci.reactions-that-release-or-absorb-thermal-energy', content: `JUDGING A DEVICE: THREE QUESTIONS, ALWAYS IN THIS ORDER. First DIRECTION. Does the job need something warmed, which takes a reaction that releases thermal energy, or something cooled, which takes one that absorbs it? A design that gets the direction wrong is finished, and no amount of speed or strength rescues it. Second HOW MUCH. Does it reach the temperature the job asks for, and does it stay inside any limit the job sets? Too little is useless and too much can be unsafe, so a brief usually states both a floor and a ceiling. Third HOW FAST. Does it get there in the time allowed, and does it keep going for as long as it is needed? Two reactions can move exactly the same total amount of thermal energy while one of them is over in half a minute and the other keeps going all afternoon, so how long a device lasts is a separate question from how much it moves.` },
    { loId: 'm8sci.reactions-that-release-or-absorb-thermal-energy', kind: 'definition', title: 'thermal energy', content: `the energy a sample of matter has because its particles are moving; the more of it a sample holds, the more it can warm something cooler that it touches.` },
    { loId: 'm8sci.reactions-that-release-or-absorb-thermal-energy', kind: 'definition', title: 'surroundings', content: `everything around the reacting substances -- the container, the table, the air, and anything holding it -- that thermal energy can move into or out of.` },
    { loId: 'm8sci.reactions-that-release-or-absorb-thermal-energy', kind: 'definition', title: 'releases thermal energy', content: `moves thermal energy out of the reacting substances and into the surroundings, so the mixture and its container end up warmer.` },
    { loId: 'm8sci.reactions-that-release-or-absorb-thermal-energy', kind: 'definition', title: 'absorbs thermal energy', content: `moves thermal energy out of the surroundings and into the reacting substances, so the mixture and its container end up colder.` },
    { loId: 'm8sci.reactions-that-release-or-absorb-thermal-energy', kind: 'definition', title: 'design brief', content: `the written list of what a device has to do, including the temperature it must reach, any limit it must not pass, and how long it has to work.` },
  ],
  methods: [
    {
      title: 'Worked classify two mixtures',
      steps: [
        `Case one, step 1: rule out the outside. The bucket is on the floor of a room at 20 degrees Celsius. There is no flame under it, no heater beside it and no sunlight on it. Nothing outside the bucket is capable of warming it, so whatever the thermometer does is down to what is happening inside.`,
        `Case one, steps 2 and 3: the readings are 20 degrees Celsius before and 31 degrees Celsius after, which is a rise of 11 degrees Celsius. Compare the after reading with the room as well: 31 degrees Celsius in a room at 20 degrees Celsius means the bucket is 11 degrees Celsius warmer than everything around it. A room at 20 degrees Celsius cannot push anything above 20 degrees Celsius, because thermal energy moves from the warmer thing to the cooler thing and never the other way.`,
        `Case one, step 4: warmer means the reaction RELEASED thermal energy. Energy that was already stored in the cement powder and the water moved out into the bucket, the floor and the air. Nothing was created; the store that was there at the start is smaller now and the surroundings are warmer. Note that 11 degrees Celsius is what this one bucket did, not a number that belongs to cement: a bigger bucket of the same mix releases more thermal energy and a thin smear of it releases so little that you would struggle to read the rise at all. The direction is the finding. The size of the rise depends on how much you mixed.`,
        `Case two, same four steps. Nothing outside is cooling the cup -- no freezer, no ice, no cold pack under it. The readings are 20 degrees Celsius before and 16 degrees Celsius after, which is a drop of 4 degrees Celsius, and the cup is now 4 degrees Celsius colder than the room it is sitting in. Colder means the reaction ABSORBED thermal energy: it pulled thermal energy out of the mixture and the cup, and it goes on pulling it out of your fingers for as long as your fingers are warmer than the cup.`,
        `WRONG: "The fizzing cup got cold because the cold from the room moved into it." CORRECT: "The room is at 20 degrees Celsius and the cup is at 16 degrees Celsius, so the room is the WARMER of the two -- thermal energy is moving from the room into the cup, not the other way, and the cup is cold anyway because the reaction is taking thermal energy out faster than the room is putting it back."`,
        `Now the two checks a science answer needs. First, three clues of DIFFERENT KINDS that agree on case one. The reading rose by 11 degrees Celsius. The bucket ended up warmer than the room, which rules out the room as the source. And the same bag of dry cement powder left unopened beside the bucket stays at 20 degrees Celsius all afternoon, which rules out the powder simply being a warm material. Three different kinds of evidence, one answer. Second, change one thing and check that the answer moves. Stand the same bucket in bright sunlight through a window. Now the reading climbs, but the climb no longer proves anything at all, because step 1 fails -- something outside is heating it. The answer has to move when the evidence moves, and the piece of evidence that carries this verdict is not the rise on its own. It is the rise with nothing outside to explain it.`,
      ],
      example: { problem: `Two reactions, both in a room that stays at 20 degrees Celsius, and nothing is heated or cooled from outside at any point. Case one: dry cement powder and water are stirred together in a bucket and left alone on the floor to set. A thermometer pushed into the middle of the bucket reads 20 degrees Celsius at the start and 31 degrees Celsius two hours later, and the outside of the bucket is warm to the touch. Case two: a spoonful of baking soda is stirred into a cup of vinegar. The mixture fizzes and gives off a gas, and a thermometer in the cup reads 20 degrees Celsius before the powder goes in and 16 degrees Celsius half a minute after. Classify each one.`, solution: `Case one released thermal energy: the bucket rose 11 degrees Celsius, ending warmer than the 20-degree-Celsius room, with nothing outside to heat it. Case two absorbed thermal energy: the cup fell 4 degrees Celsius, ending colder than the same room, with nothing outside to cool it.` },
      relatedLoIds: ['m8sci.reactions-that-release-or-absorb-thermal-energy'],
    },
    {
      title: 'Worked evaluate cold pack',
      steps: [
        `Question one, DIRECTION, and it comes first for a reason. The job is to take thermal energy out of the ankle, so the pack has to be colder than the ankle, which means the reaction inside it has to ABSORB thermal energy. Mixture P absorbs, so it passes. Mixture Q releases, which would leave the pack warmer than the room and warmer than the ankle, and thermal energy would then move from the pack into the ankle. That is the opposite of the job. Mixture Q is out, and nothing else about it needs checking.`,
        `Question two, HOW MUCH, run on the one mixture still standing. The brief sets a floor of 0 degrees Celsius that the pack must never go below. Mixture P reaches 4 degrees Celsius, which is 4 degrees Celsius above that floor, and its warmest reading in the stated range, 8 degrees Celsius, is well below the 20 degrees Celsius of the room, so it stays genuinely colder than the ankle it is pressed against. It passes on how much.`,
        `Question three, HOW FAST. The brief allows about 30 seconds to get cold; Mixture P is at 4 degrees Celsius after 20 seconds, which is inside that. The brief asks for at least 15 minutes of cold; Mixture P stays between 4 and 8 degrees Celsius for about 20 minutes, which is 5 minutes more than the brief asks for. It passes on how fast, at both ends -- the getting there and the lasting.`,
        `WRONG: "Mixture Q is the better pack, because 35 degrees Celsius is a bigger change away from the room than 4 degrees Celsius is, and a bigger change means a stronger pack." CORRECT: "Direction is decided before size, so a mixture that warms the ankle is out no matter how big its change is. And the size claim is not even true here: Mixture Q rises 15 degrees Celsius above the room while Mixture P falls 16 degrees Celsius below it, so the absorbing mixture makes the larger change of the two."`,
        `Now the two checks. First, three clues of DIFFERENT KINDS agree that Mixture P is the answer: the direction test (the job needs thermal energy taken out, and only P takes it out), the limit test (P stops at 4 degrees Celsius and never reaches the 0-degree-Celsius floor), and the two timing tests (cold in 20 seconds against about 30 allowed, and lasting about 20 minutes against 15 required). Second, change one thing and check that the answer moves. Rewrite the first line of the brief so that the device is a warming pack for a stiff shoulder on a cold morning, and change nothing else. Now the direction requirement flips, Mixture Q passes the question it used to fail, and Mixture P is the one that is out. The answer moved when the requirement moved, which is what tells you the direction question was doing real work and not just being recited.`,
      ],
      example: { problem: `A first-aid company is designing an instant cold pack to press on a twisted ankle at the side of the field. The brief says three things. The pack must take thermal energy out of the ankle. It must be cold within about 30 seconds of being squeezed, and it must stay cold for at least 15 minutes. And its temperature must never go below 0 degrees Celsius, so that no ice can form against the skin. Two mixtures are offered, both in a room at 20 degrees Celsius. Mixture P absorbs thermal energy: 20 seconds after it is squeezed it reads 4 degrees Celsius, and it stays between 4 and 8 degrees Celsius for about 20 minutes. Mixture Q releases thermal energy: 20 seconds after it is squeezed it reads 35 degrees Celsius. Which mixture meets the brief?`, solution: `Mixture P. It absorbs thermal energy, which is the direction the job needs; it reaches 4 degrees Celsius, staying above the 0-degree-Celsius floor the brief sets; and it is cold in 20 seconds and stays cold for about 20 minutes, beating both of the times the brief asks for.` },
      relatedLoIds: ['m8sci.reactions-that-release-or-absorb-thermal-energy'],
    },
  ],
  pointers: [
    { content: `Students often say "A cold pack works by sending cold into your skin." — There is no cold to send anywhere. Thermal energy moves from the warmer thing to the cooler thing, always, and nothing ever moves the other way. Your skin is warmer than the pack, so thermal energy leaves your skin and goes into the pack, and the mixture inside the pack goes on absorbing it. What you feel as cold is your own skin losing thermal energy. WRONG: "The pack sends cold into my ankle." CORRECT: "My ankle sends thermal energy into the pack, because the pack is colder, and the mixture inside keeps taking that thermal energy in."`, kind: 'common-error' },
    { content: `Students often say "A hand warmer makes new energy, because nothing is plugged into it." — Energy is never created and never destroyed. The iron powder and the oxygen the packet takes in from the air already hold energy in the way their atoms are arranged, and when they combine, the reaction moves some of that store out into the surroundings as thermal energy. A battery is not the only place energy can be stored; a chemical store does not look like anything at all from the outside. WRONG: "The packet makes energy." CORRECT: "The packet releases energy that was already stored in the iron and the oxygen, as thermal energy that spreads into my hand and the air."`, kind: 'common-error' },
    { content: `A reaction either RELEASES thermal energy into its surroundings or ABSORBS thermal energy from them. Warmer mixture means released; colder mixture means absorbed.`, kind: 'tip' },
    { content: `The surroundings are everything around the reacting substances: the rest of the mixture, the container, the table, the air, and your hand.`, kind: 'tip' },
    { content: `Releasing does not make energy. The energy was already stored in the substances you started with, and the reaction moved it out as thermal energy.`, kind: 'tip' },
    { content: `Absorbing does not let cold in. Cold is not a substance and does not move. Thermal energy always travels from the warmer thing to the cooler thing.`, kind: 'tip' },
    { content: `The classifying routine: rule out any outside heater or cooler, take the temperature before and after, compare the after reading with the room too, then call it released or absorbed.`, kind: 'tip' },
    { content: `A mixture that ends up warmer than the room it sits in cannot have been warmed by that room.`, kind: 'tip' },
    { content: `Judge a device in this order: DIRECTION (warming needs a releasing reaction, cooling needs an absorbing one), then HOW MUCH (does it reach the temperature asked for and stay inside the limit set), then HOW FAST (does it get there in time and last as long as it is needed).`, kind: 'tip' },
    { content: `A design that gets the direction wrong is out. Being quicker or hotter never rescues it.`, kind: 'tip' },
    { content: `How much thermal energy a reaction moves and how long it takes to move it are two different questions. Two designs can move the same total amount while one is over in moments and the other works away for hours.`, kind: 'tip' },
  ],
};
