/**
 * Grade 8 Science — Unit 4 CED 4.3: Energy Transformations & Conservation.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.energy-transformations-and-conservation.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U4_ENERGY_TRANSFORMATIONS_AND_CONSERVATION: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.energy-transformations-and-conservation.v1',
  course: 'Grade 8 Science',
  cedUnit: 4,
  cedTopic: '4.3',
  cedTitle: 'Energy Transformations & Conservation',
  planId: 'evelyn.ms.m8sci.energy-transformations-and-conservation.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.energy-transformations-and-conservation.v1' }],
  theory: [
    { loId: 'm8sci.energy-transformations-and-conservation', content: `ENERGY COMES IN FORMS, AND A FORM IS JUST A WAY OF HAVING ENERGY. KINETIC energy is the energy something has because it is moving. GRAVITATIONAL POTENTIAL energy is stored because of how high something is; ELASTIC POTENTIAL energy is stored in something stretched or squashed; CHEMICAL POTENTIAL energy is stored in the materials themselves, in a battery or a fuel. You already met those stored kinds in the last lesson, and nothing about how they are stored changes here. THERMAL energy is the energy of the jiggling of the particles an object is made of, and an object warms up when it gains some. LIGHT is energy traveling as a wave, and it can cross empty space. SOUND is energy carried by a vibration passing through air, water or a solid. ELECTRICAL energy is energy carried along wires by moving charges, which is how energy gets from a battery to the part of a device that uses it. What is new today is not the list. It is following one store as it turns into another.` },
    { loId: 'm8sci.energy-transformations-and-conservation', content: `A TRANSFORMATION IS THE SAME ENERGY IN A NEW FORM, AND A CHAIN IS SEVERAL OF THEM IN A ROW. Nothing is added and nothing is removed when energy changes form; the same energy is simply being held a different way, often by a different object. Trace a chain in four moves. First, name the objects the chain runs through, in order, and include the air and the room at the end, because the chain almost always leaves the device. Second, name the form the energy is in at the start, and say which object holds it. Third, step along, saying what became what, and in which object it happened. Fourth -- and this is the move people skip -- do not stop at the interesting part. Keep going until everything has been named, including the parts that got warm and any sound you would have heard.` },
    { loId: 'm8sci.energy-transformations-and-conservation', content: `THE TOTAL NEVER CHANGES, AND THAT IS CONSERVATION OF ENERGY. Add up all the energy in all its forms before a change, add it all up after, and you get the same amount. Energy is never created and never destroyed; it is transferred from one object to another and transformed from one form to another. You already know this rule in one setting: a living thing does not make energy, it releases energy that was already stored in its food. That is not a special rule about living things. It is a rule about everything -- batteries, balls, rides, engines, stars. WRONG: "The flashlight used up the battery's energy." CORRECT: "The battery's chemical energy became light and thermal energy that spread into the room."` },
    { loId: 'm8sci.energy-transformations-and-conservation', content: `EVERY REAL CHAIN ENDS THE SAME WAY: THERMAL ENERGY SPREAD INTO THE SURROUNDINGS. Wherever two surfaces rub, wherever something pushes through the air, wherever a wire or a bulb warms up, wherever a sound fades away, part of the energy becomes thermal energy in the objects and the air nearby. Expect it. A chain you have traced that does not end this way is a chain you have not finished tracing. And notice what has and has not happened to that part. It is still energy, it still counts in the total, and it is exactly where you left it -- but it is now spread across an enormous number of particles, a tiny amount each, and no device can gather it up again and put it back to work. When people say energy was "wasted" or "lost", that is what they mean, and both words are misleading: spread out and out of reach, never destroyed.` },
    { loId: 'm8sci.energy-transformations-and-conservation', content: `HOW TO CATCH YOURSELF SAYING "USED UP". There is one question, and you ask it over and over until you run out of chain: where did it go? A good answer always names two things, a form and an object holding it -- "thermal energy, in the back of a charging phone and the air around it". "It was used up" names neither, so it is never an answer; it is the sentence you write when you have stopped tracing early. WRONG: "The engine used up the fuel's energy." CORRECT: "The chemical potential energy stored in the fuel became kinetic energy of the car, sound, and thermal energy in the engine, the exhaust gases and the air." The second sentence is longer because it is finished.` },
    { loId: 'm8sci.energy-transformations-and-conservation', kind: 'definition', title: 'energy transformation', content: 'a change of energy from one form into another, with the total amount unchanged.' },
    { loId: 'm8sci.energy-transformations-and-conservation', kind: 'definition', title: 'conservation of energy', content: `the rule that energy is never created and never destroyed, so the total in all its forms stays the same.` },
    { loId: 'm8sci.energy-transformations-and-conservation', kind: 'definition', title: 'kinetic energy', content: 'the energy an object has because it is moving.' },
    { loId: 'm8sci.energy-transformations-and-conservation', kind: 'definition', title: 'potential energy', content: `energy stored by the arrangement of things: gravitational (because of height), elastic (because something is stretched or squashed), or chemical (stored in the materials themselves).` },
    { loId: 'm8sci.energy-transformations-and-conservation', kind: 'definition', title: 'thermal energy', content: `the energy of the jiggling of the particles an object is made of; an object warms up when it gains thermal energy.` },
    { loId: 'm8sci.energy-transformations-and-conservation', kind: 'definition', title: 'electrical energy', content: `energy carried along wires by moving charges, from a source such as a battery to the part of a device that turns it into something else.` },
  ],
  methods: [
    {
      title: 'Worked flashlight chain',
      steps: [
        `Move one, name the objects the chain runs through, in order: the batteries, the wires and the switch inside the flashlight, the bulb, and then the room -- the air, the walls, the floor and everything the light lands on. Putting the room on the list at the start is what stops you finishing at the bulb.`,
        `Move two, name the starting form. The batteries hold chemical potential energy, stored in the materials inside them. Nothing is moving and nothing is glowing yet, so at this instant that store is the whole of the energy in the chain.`,
        `Move three, step along. Closing the switch lets the chemical potential energy in the batteries become electrical energy, carried along the wires to the bulb. At the bulb that electrical energy becomes two forms at once: light, which leaves in every direction, and thermal energy, which is why the bulb and the metal ring around it are hot. Some thermal energy also appears in the batteries and the wires themselves as the energy passes through them, which is why the batteries are warm.`,
        `Move four, do not stop at the bulb. Follow the light. It crosses the room and lands on the walls, the floor, the ceiling and everything in it, and those surfaces absorb it. Light that has been absorbed has become thermal energy in whatever absorbed it, spread out very thinly. So the far end of the chain is thermal energy, spread through the flashlight, the air and the whole room.`,
        `Now answer what was asked. Nothing was destroyed. Every bit of the chemical potential energy the batteries started with is still here: a very small part of it is still on its way across the room as light at any instant, and essentially all of the rest is thermal energy spread so thinly through the room that you cannot feel it. WRONG: "The flashlight used up the batteries' energy." CORRECT: "The batteries' chemical energy became light and thermal energy that spread into the room." A dead battery is not a battery whose energy left the world. It is a battery whose materials have finished changing, so there is no store left inside it for the flashlight to draw on.`,
        `Run the checks a science answer needs, because there is no arithmetic here to redo. First, look for clues of DIFFERENT KINDS that agree that the energy went somewhere rather than nowhere. You can feel one: the bulb, the metal ring and the batteries are all warmer than they were, and warm is what "thermal energy arrived here" feels like. You can see another: the room is brighter, and brightness is energy arriving at every surface in the room. And a controlled comparison agrees with both: an identical flashlight left switched off on a shelf still works weeks later, so what wears the batteries out is not time passing but light and warmth being produced. A feel, a look and a comparison -- three different kinds, one answer.`,
        `Second, change one thing and check that the answer moves the way it should. Swap the bulb for an LED that gives about the same brightness and barely warms up. Now a much larger share of the chemical potential energy leaves as light and a much smaller share becomes thermal energy inside the flashlight, and the same two batteries last far longer. Conservation did not change -- the total is still the total. What changed is how that total is split between the forms. And notice what this rules out: if the batteries were simply being consumed at a fixed rate, changing the bulb could not possibly change how long they last.`,
      ],
      example: { problem: `You switch on a flashlight that runs on two ordinary batteries, and you leave it on. The room gets brighter. After a few minutes the bulb and the metal ring around it are hot to touch, and the batteries are slightly warm. After an hour the light has gone dim, and soon after that the batteries will not light it at all. Trace the energy from the batteries to the end of the chain, and say whether any energy was destroyed along the way.`, solution: `Chemical potential energy in the batteries becomes electrical energy carried along the wires, and at the bulb it becomes light plus thermal energy, with a little thermal energy appearing in the batteries and wires on the way. The light is then absorbed by the walls, floor and air and becomes thermal energy there too. Nothing was destroyed: the total is exactly what it was, but almost all of it is now thermal energy spread thinly through the room, where no device can gather it back.` },
      relatedLoIds: ['m8sci.energy-transformations-and-conservation'],
    },
    {
      title: 'Worked coaster hill to hill',
      steps: [
        `Move one, name the objects: the car, the track it runs on, and the air it pushes through. The rails and the air belong on the list for the same reason the room did in the last example.`,
        `Move two, the starting form. At the top of the first hill the car is high up and barely moving. Almost all of its energy is gravitational potential energy, stored because of how high it is, and only a little is kinetic.`,
        `Move three, step along. Going down, gravitational potential energy becomes kinetic energy, and the car speeds up; at the bottom it is moving fastest and the store that height gave it is nearly all kinetic now. Climbing the second hill runs that same change backward: kinetic energy becomes gravitational potential energy again, and the car slows as it rises.`,
        `Move four, do not stop at the interesting part -- and here the part people skip is the whole answer to the student. The wheels rub on the rails and the car pushes through the air, the entire way round. Wherever surfaces rub and wherever something pushes through air, part of the energy becomes thermal energy in the wheels, the rails and the air, which is why they are warm at the end of the day, and part becomes sound, which is why the ride is noisy. Both of those parts are still energy, and neither of them can lift the car. So the energy still available to lift the car is smaller at the second hill than it was at the first, and smaller again at the third. That is why the hills have to keep getting lower, and why, once the car has been let go and given no new push, they can never get higher.`,
        `WRONG: "The ride loses energy, so the total goes down every time the car goes round." CORRECT: "The total stays exactly the same. Part of it keeps changing into thermal energy and sound, which spread into the rails and the air, and that part can no longer lift the car." Notice that the student's question had the right observation in it -- the hills really do get lower -- and only the explanation was wrong.`,
        `Run the checks. Three clues of DIFFERENT KINDS agree. The pattern: every hill is lower than the one before, and a ride that is given no new push part-way round never climbs higher than its first hill, which is what you expect if part of the energy keeps leaving the useful pile and never comes back. The warmth: the wheels and rails are warm at the end of the day, and that warmth was not there in the morning. The sound: you can hear the ride from the queue, and sound is energy traveling away through the air. A pattern, a feel and a sound are three different kinds of evidence, and all three point at the same place.`,
        `Second, change one thing and check that the answer moves. Take almost all of the rubbing and the air-pushing away. A pendulum -- a heavy weight hanging on a long string, swinging in still air -- comes back to very nearly the height it was released from, swing after swing after swing, and only creeps lower over many minutes. It is the same two forms trading back and forth as on the coaster, with far less rubbing, and the shortfall is far smaller. The size of the shortfall tracks how much rubbing and air-pushing there is. That is exactly what you would see if rubbing and air are where the energy is going, and it is not what you would see if energy simply drained away on its own, which would not care what the string and the air were doing.`,
      ],
      example: { problem: `A roller coaster car is pulled to the top of the first hill and let go. It races to the bottom, climbs a second hill that is lower than the first, races down again, and climbs a third hill that is lower still. The ride is noisy while it runs, and at the end of the day the wheels and the rails are warm. A student asks why the hills have to keep getting lower, and whether the ride is losing energy. Trace the energy and answer the student.`, solution: `At the top of the first hill the car's energy is almost all gravitational potential energy. Going down it becomes kinetic energy; climbing, kinetic energy becomes gravitational potential energy again. Every time round, the wheels rubbing on the rails and the car pushing through the air turn part of the energy into thermal energy in the wheels, rails and air, and part into sound. The ride is not losing energy -- the total is unchanged -- but the part now held as thermal energy and sound cannot lift the car, so each hill has to be lower than the one before.` },
      relatedLoIds: ['m8sci.energy-transformations-and-conservation'],
    },
  ],
  pointers: [
    { content: `Students often say "When the batteries go dead, their energy has been used up and is gone." — Energy is never created and never destroyed. Every bit of the chemical potential energy those batteries started with is still in the world. Some of it left the flashlight as light, which the walls and the floor absorbed and which warmed them very slightly; the rest became thermal energy in the bulb, the wires, the batteries themselves and the air around them. The word "dead" describes the store, not the energy: the materials inside the batteries have finished changing, so there is nothing left in them for the flashlight to draw on. The energy is out there in the room, spread so thinly across so much matter that no device can gather it back. The question that catches this every time is "where did it go?", and "used up" is never an answer to it, because it names no form and no object holding it.`, kind: 'common-error' },
    { content: `Students often say "Energy is only really conserved in a perfect system; in the real world some of it is always lost." — Conservation of energy is not an approximation that friction breaks. It holds exactly, in the messiest situation you can find, and the messy situations are where it is most worth using. What a scientist means by "lost" is "no longer useful to us": the energy has become thermal energy spread through the surroundings, a tiny amount held by each of an enormous number of particles, and there is no way to collect it back up and put it to work again. Lost to us, not lost from the world. WRONG: "Friction destroys some of the energy." CORRECT: "Friction turns part of the energy into thermal energy in the two surfaces and the air around them, and the total is unchanged."`, kind: 'common-error' },
    { content: `Energy comes in forms: kinetic, gravitational potential, elastic potential, chemical potential, thermal, light, sound and electrical. A form is just a way of having energy.`, kind: 'tip' },
    { content: `A transformation is the same energy in a new form. Nothing is added and nothing is removed when energy changes form.`, kind: 'tip' },
    { content: `Conservation of energy: energy is never created and never destroyed. Add it all up before and after, in every form, and the total is the same.`, kind: 'tip' },
    { content: `Trace a chain in four moves: name the objects it runs through including the air and the room, name the starting form, step along saying what became what and in which object, and do not stop until everything is named.`, kind: 'tip' },
    { content: `Every real chain ends with part of the energy as thermal energy spread into the surroundings -- wherever surfaces rub, wherever something pushes through air, wherever a wire warms, wherever a sound fades.`, kind: 'tip' },
    { content: `That spread-out thermal energy is still there and still counts in the total. It is just shared so thinly between so many particles that no device can gather it back and use it.`, kind: 'tip' },
    { content: `"Wasted" and "lost" are misleading words for that part. Spread out and out of reach is not the same as destroyed.`, kind: 'tip' },
    { content: `A finished answer names a form and an object holding it: "thermal energy, in the back of a charging phone and the air around it". "It was used up" names neither, so it is never a finished answer.`, kind: 'tip' },
    { content: 'Keep asking the one question -- where did it go? -- until you run out of chain.', kind: 'tip' },
    { content: `Don't say energy "goes away" or "is used up." Always answer "where did it go?" with both a FORM (kinetic, thermal, light, etc.) and an OBJECT holding it (the wall, the air, the batteries). "Used up" names neither.`, kind: 'common-error' },
    { content: `"Conservation of energy" is NOT a classroom rule that breaks in real situations. Friction, air resistance and rubbing do NOT destroy energy—they turn it into thermal energy spread into the surroundings. The total never changes.`, kind: 'gotcha' },
    { content: `A finished energy chain always ends in thermal energy spread through the air, walls, or objects—ALWAYS. If your chain stops at 'the bulb glows' or 'the ball moves,' you have not finished. Keep asking where that energy goes next.`, kind: 'tip' },
    { content: `Energy transformation ≠ energy disappearing. Transformation means the SAME energy is now in a different form, held by the same or a different object. Nothing is added, nothing is removed.`, kind: 'vocab-note' },
    { content: `Thermal energy is NOT just 'heat.' It is the energy of jiggling particles inside the object. When an object gets warm, it has GAINED thermal energy—thermal energy moved INTO it from somewhere else in the chain.`, kind: 'vocab-note' },
    { content: `When tracing a chain, list the OBJECTS first (batteries, wires, bulb, room, air), then the FORMS (chemical potential, electrical, light, thermal). Mixing them up makes it hard to finish the chain cleanly.`, kind: 'tip' },
    { content: `Don't confuse 'the total energy is conserved' with 'all the energy is still useful.' Thermal energy spread thinly through a room is still energy and still counts—but no device can gather it back up to do work.`, kind: 'edge-case' },
    { content: `The word 'lost' in 'energy is lost to friction' means 'no longer useful to us,' NOT 'gone from the world.' Check yourself: can you name the form and the object? If yes, the energy is not lost—it is just spread out and unreachable.`, kind: 'common-error' },
  ],
};
