/**
 * Grade 8 Science — Unit 5 CED 5.1: Temperature & Thermal Energy.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.temperature-and-thermal-energy.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U5_TEMPERATURE_AND_THERMAL_ENERGY: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.temperature-and-thermal-energy.v1',
  course: 'Grade 8 Science',
  cedUnit: 5,
  cedTopic: '5.1',
  cedTitle: 'Temperature & Thermal Energy',
  planId: 'evelyn.ms.m8sci.temperature-and-thermal-energy.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.temperature-and-thermal-energy.v1' }],
  theory: [
    { loId: 'm8sci.temperature-and-thermal-energy', content: `EVERY PARTICLE IN EVERY SAMPLE IS MOVING, AND MOVING MEANS KINETIC ENERGY. Everything around you is made of particles far too small to see, and those particles are never still. They jiggle, tumble and bump into one another in a warm room and in a freezer alike. You already know that a moving object has kinetic energy -- the energy of motion -- and that kinetic energy grows with mass and with speed. A particle is no different: every particle in a sample carries some kinetic energy, because every particle is moving. One more thing to hold on to before the two definitions arrive: the particles in a single sample are not all moving at the same speed. At any moment some are faster and some are slower. That is exactly why the two quantities that follow are built out of an AVERAGE and a TOTAL rather than out of one particle.` },
    { loId: 'm8sci.temperature-and-thermal-energy', content: `TEMPERATURE IS THE AVERAGE KINETIC ENERGY PER PARTICLE. When you read a temperature, you are reading how much kinetic energy a typical particle in that sample has: the average, taken across all of them. Warm the sample and its particles move faster, so the average goes up and the reading goes up with it. Cool it and they slow, and the reading falls. Now notice what that average leaves out. It says nothing at all about how many particles there are. One drop of water at 60 degrees Celsius and a full bucket of water at 60 degrees Celsius have particles with the same average energy of motion, and that is exactly why the same thermometer reads 60 degrees Celsius in both of them. Temperature is a per-particle measurement, and a sample does not get a higher reading for being big.` },
    { loId: 'm8sci.temperature-and-thermal-energy', content: `THERMAL ENERGY IS THE TOTAL FOR THE WHOLE SAMPLE. Now add up the kinetic energy of every particle in the sample instead of averaging it. That sum is the sample's thermal energy. Because it is a total and not an average, it depends on two things at once: how fast the particles are moving on average, which is the temperature, and how many particles there are, which is how much matter the sample contains. Take twice as much matter at the same temperature and you are adding up twice as many amounts, so the total is twice as large. That is the whole difference between the two words. Temperature is per particle. Thermal energy is for the whole sample. One condition before any comparison: every comparison you are asked to settle in this lesson is between samples of the SAME substance. What a sample is made of matters too, and that is a later lesson.` },
    { loId: 'm8sci.temperature-and-thermal-energy', content: `A COOLER SAMPLE CAN HOLD MORE THERMAL ENERGY THAN A HOTTER ONE, AND THAT IS THE POINT OF TODAY. A bathtub of warm water holds more thermal energy than a cup of boiling water. The cup wins on temperature: its particles are moving faster on average, and a thermometer says so. The bathtub wins on the total, and it wins by a long way, because it holds so many more water particles that adding up their smaller amounts still comes to far more. WRONG: "The cup is hotter, so the cup must hold more thermal energy." CORRECT: "The cup has the higher average per particle. The bathtub has enormously more particles, and thermal energy is the total, so the bathtub holds more of it." Hotter tells you which way one of the two factors points. On its own it does not settle the total.` },
    { loId: 'm8sci.temperature-and-thermal-energy', content: `A THERMOMETER READS ONLY ONE OF THE TWO, AND "HEAT" IS A THIRD WORD. A thermometer reads the average and nothing else, so no thermometer can tell you how much thermal energy a sample holds. To answer that you need the reading AND the amount of matter, and you have to go and find the second one. While you are sorting words out, sort out one more. In everyday speech people say that a hot object "has a lot of heat". In science an object has THERMAL ENERGY. The word heat names thermal energy on the move, from a warmer object to a cooler one, and how that moving happens is the next lesson. An object does not contain heat, and heat is not a substance that can be stored anywhere.` },
    { loId: 'm8sci.temperature-and-thermal-energy', content: `HOW TO ANSWER ANY QUESTION OF THIS KIND. First, decide which of the two quantities the question is actually asking for: the average per particle, which is temperature, or the total over the sample, which is thermal energy. Second, if it is temperature, compare only how fast the particles are moving on average and ignore the amounts completely. Third, if it is thermal energy, you need the temperature AND the amount of matter, so collect both before you answer. Fourth, settle it with the two clean cases wherever you can: for the same substance at the same temperature, more matter means more thermal energy; for the same substance in the same amount, the higher temperature means more thermal energy. And when one sample is hotter while the other is much bigger, weigh the two against each other. A difference in amount of ten times or a hundred times is far larger than any difference two everyday temperatures can make, so in that situation the much bigger sample holds the larger total.` },
    { loId: 'm8sci.temperature-and-thermal-energy', kind: 'definition', title: 'particle', content: `one of the extremely small pieces that all matter is made of, far too small to see, and always in motion.` },
    { loId: 'm8sci.temperature-and-thermal-energy', kind: 'definition', title: 'kinetic energy', content: `the energy something has because it is moving; it grows with mass and with speed.` },
    { loId: 'm8sci.temperature-and-thermal-energy', kind: 'definition', title: 'temperature', content: `a measure of the AVERAGE kinetic energy of the particles in a sample. It is what a thermometer reads, and it does not depend on how much of the sample there is.` },
    { loId: 'm8sci.temperature-and-thermal-energy', kind: 'definition', title: 'thermal energy', content: `the TOTAL kinetic energy of all the particles in a sample. It depends on the temperature and on how much matter the sample contains.` },
    { loId: 'm8sci.temperature-and-thermal-energy', kind: 'definition', title: 'average', content: `the amount each member of a group would have if the total were shared out equally among them; it describes a typical member and says nothing about how many members there are.` },
    { loId: 'm8sci.temperature-and-thermal-energy', kind: 'definition', title: 'heat', content: `thermal energy on the move from a warmer object to a cooler one. An object has thermal energy; it does not contain heat.` },
  ],
  methods: [
    {
      title: 'Worked saucepan and pot',
      steps: [
        `Split the question into its two halves, because it is asking for two different quantities and they have to be answered separately. Half one is temperature. Half two is thermal energy. Answering both at once with one comparison is how this question gets missed.`,
        `Temperature first, because it is the short half. Temperature is the average kinetic energy per particle, so the amount of water does not enter into it at all. The saucepan reads 90 degrees Celsius and the pot reads 30 degrees Celsius, so the saucepan has the higher temperature. The reading is the answer, and 200 grams against 2,000 grams changes nothing about it.`,
        `Now thermal energy, which needs both factors collected before anything is decided. Factor one, the temperature: a typical particle in the saucepan is moving faster than a typical particle in the pot, so each of the saucepan's particles carries more kinetic energy. Factor two, the amount of matter: 2,000 grams divided by 200 grams is 10, so the pot holds ten times as much water as the saucepan, and therefore ten times as many water particles.`,
        `Weigh the two factors against each other. The pot is adding up ten times as many amounts. For the saucepan to win anyway, each of its amounts would have to be more than ten times bigger than each of the pot's -- and it is not, nowhere near. Both pans hold ordinary liquid water, one at 90 degrees Celsius and one at 30 degrees Celsius, and a particle in the hotter water is moving faster but nothing like ten times faster. Ten times as many particles, each carrying a little less: the pot holds far more thermal energy.`,
        `WRONG: "The saucepan is at 90 degrees Celsius and the pot is only at 30 degrees Celsius, so the saucepan holds three times the thermal energy." CORRECT: "The saucepan has the higher average per particle, the pot has ten times as many particles, and so the pot holds far more thermal energy." Two separate mistakes are packed into the wrong version. It reads a thermometer as if the thermometer measured the total, and it treats 90 degrees Celsius as "three times" 30 degrees Celsius, which is not something a Celsius reading lets you say about how fast particles are moving.`,
        `Now run the checks a science answer needs, because there is very little arithmetic here to redo. First, look for clues of DIFFERENT KINDS that agree. The definition puts the count of particles inside the total, and the count favors the pot ten to one. The arithmetic agrees from a second direction: ten times as many particles against particles that are faster but nowhere near ten times faster. And the behavior of a thermometer agrees from a third: dip one into the big pot, then into a single spoonful lifted out of that pot, and both read 30 degrees Celsius. A reading that does not change when almost all of the water is taken away cannot be a measurement of the total. Three different kinds of evidence, one answer.`,
        `Second, change one condition and check that the answer moves. Pour water out of the big pot until only 200 grams of it is left, still at 30 degrees Celsius. Nothing has been heated or cooled, so both temperatures are exactly what they were, 90 degrees Celsius and 30 degrees Celsius -- but the amounts are equal now, and the saucepan holds more thermal energy than the pot. The thermal-energy answer flipped and the temperature answer did not move at all. That is the proof that the amount of matter was doing the work, and that these are two quantities and not one.`,
      ],
      example: { problem: `A small saucepan holds 200 grams of water at 90 degrees Celsius. A large pot standing beside it holds 2,000 grams of water at 30 degrees Celsius. Both hold ordinary liquid water, and nothing is heating or cooling either one at this moment. Which has the higher temperature, and which holds more thermal energy? Say how you know.`, solution: `The saucepan has the higher temperature, 90 degrees Celsius against 30 degrees Celsius, because temperature is the average kinetic energy per particle and the amount of water does not affect it. The pot holds far more thermal energy, because thermal energy is the total over every particle: the pot holds ten times as much water, and a particle in the hotter saucepan is moving faster but nothing like ten times faster. Pour the pot down to 200 grams and the thermal-energy answer reverses while the temperatures stay where they were, which shows that the amount of matter was what decided it.` },
      relatedLoIds: ['m8sci.temperature-and-thermal-energy'],
    },
    {
      title: 'Worked ranking three samples',
      steps: [
        `Rank by temperature first, and use nothing but the readings. Temperature is the average per particle, so 50 grams and 5,000 grams are equally irrelevant to this half of the question. Sample A is at 100 degrees Celsius; Samples B and C are both at 20 degrees Celsius. So Sample A is the hottest, and Samples B and C are tied at the bottom. Being a hundred times bigger bought Sample C nothing whatsoever on this ranking.`,
        `Now thermal energy, and take the easy pair first. Samples A and B hold the same amount of water, 50 grams each, so they have the same number of particles and the same number of amounts to add up. The only thing separating them is how much each particle carries, and Sample A's particles are moving faster. Sample A holds more thermal energy than Sample B.`,
        `Now the hard pair, Sample A against Sample C. Sample C is at the lower temperature, so each of its particles carries less kinetic energy than each of Sample A's. But 5,000 grams divided by 50 grams is 100, so Sample C holds a hundred times as much water as Sample A and a hundred times as many particles. For Sample A to win the total, each of its particles would have to carry more than a hundred times what one of Sample C's carries, and that is nowhere near true of liquid water at 100 degrees Celsius set against liquid water at 20 degrees Celsius. Sample C holds much more thermal energy than Sample A. The full ranking by thermal energy is Sample C first, then Sample A, then Sample B.`,
        `There is a cleaner way to see Sample C against Sample B, and it is worth keeping. Sample C is 5,000 grams of water at 20 degrees Celsius and Sample B is 50 grams of water at 20 degrees Celsius, so Sample C is exactly a hundred Sample Bs poured together. Divide Sample C into a hundred equal portions and every single portion is a copy of Sample B: 50 grams, 20 degrees Celsius. A hundred copies hold a hundred times the thermal energy of one copy, and every copy reads the same on a thermometer as the whole of Sample C does. Same temperature, a hundred times the thermal energy, with no estimating anywhere in the argument.`,
        `Now the student's claim. WRONG: "Sample C must be the hottest, because it holds the most energy of motion in total." CORRECT: "Sample C holds the most thermal energy and is tied for the LOWEST temperature, because a total counts every particle while a temperature reports the average for one." The claim runs the lesson backward. A large total tells you nothing on its own about the average behind it, in the same way that the school with the most students is not automatically the school with the tallest average student. That comparison is about averages and totals only; nothing about a student resembles a particle in any other way, and it is here to make the arithmetic point and nothing more.`,
        `Run the checks. Three clues of different kinds agree on the thermal-energy ranking. The definition puts the particle count inside the total and keeps it out of the average. The arithmetic gives a factor of one hundred in amount against a per-particle difference far smaller than a hundred. And the hundred-copies argument settles Sample C against Sample B exactly, with no estimate in it at all. Then change one condition: shrink Sample C from 5,000 grams to 5 grams and leave it at 20 degrees Celsius. Its reading has not moved, and neither has its place in the temperature ranking -- still tied with Sample B at the bottom. But it now holds the LEAST thermal energy of the three, having gone from first to last. One condition changed, one ranking moved, the other did not. That is what it means for these to be two different quantities.`,
      ],
      example: { problem: `Three samples of ordinary liquid water are described. Sample A is 50 grams at 100 degrees Celsius. Sample B is 50 grams at 20 degrees Celsius. Sample C is 5,000 grams at 20 degrees Celsius. Rank the three by temperature, then rank them by thermal energy. Then deal with this claim from a student: "Sample C must be the hottest of the three, because it holds the most energy of motion in total."`, solution: `By temperature: Sample A at 100 degrees Celsius is the hottest, and Samples B and C are tied at 20 degrees Celsius. By thermal energy: Sample C first, then Sample A, then Sample B. Sample C holds a hundred times as much water as Sample A, which more than makes up for its lower temperature, and Sample C is exactly a hundred copies of Sample B at the same temperature as Sample B. The student is wrong: holding the largest total says nothing on its own about the average per particle, and Sample C is tied for the lowest temperature of the three.` },
      relatedLoIds: ['m8sci.temperature-and-thermal-energy'],
    },
  ],
  pointers: [
    { content: `Students often say "The mug is far hotter, so the mug must hold far more thermal energy." — Temperature is the average kinetic energy per particle and thermal energy is the total across every particle in the sample, so a comparison of totals has to count the particles as well as read the thermometer. The mug holds a few hundred grams of water. A swimming pool holds many thousands of mugfuls of water. Each particle in the pool is moving more slowly on average than each particle in the mug, but there are so vastly many more of them that adding up their smaller amounts comes to far more than adding up the mug's. The pool holds far more thermal energy, and the pool is at the lower temperature. The test that settles it is to scoop one mugful out of the pool. That mugful reads 15 degrees Celsius, exactly as the whole pool does, and it holds only a tiny share of the pool's thermal energy -- so the amount changed the total and left the reading alone. WRONG: "Hotter, so more thermal energy." CORRECT: "Hotter means a higher average per particle. More thermal energy means a bigger total, and a total counts how much matter there is."`, kind: 'common-error' },
    { content: `Students often say "Thermal energy and temperature are two words for the same measurement." — They are two different quantities, and only one of them can be read off a thermometer. Temperature is an average taken per particle, so dividing a sample does not change it: half a pot of water is at the same temperature as the whole pot was. Thermal energy is a total taken over the sample, so dividing a sample does change it: half a pot of water holds half the thermal energy the whole pot held. If the two words named the same measurement, dividing a sample could not possibly change one of them and leave the other exactly where it was. To state how much thermal energy a sample holds you need the temperature AND the amount of matter, and no thermometer will hand you the second of those. One more word to keep straight while you are here: an object has thermal energy, and it does not contain heat. Heat is the name for thermal energy moving from a warmer object to a cooler one.`, kind: 'common-error' },
    { content: `Every particle in every sample is moving, and a moving particle has kinetic energy. The particles in one sample are not all moving at the same speed.`, kind: 'tip' },
    { content: `Temperature is the AVERAGE kinetic energy per particle. It is what a thermometer reads, and it does not depend on how much of the sample there is.`, kind: 'tip' },
    { content: `Thermal energy is the TOTAL kinetic energy of all the particles in the sample. It depends on the temperature AND on how much matter there is.`, kind: 'tip' },
    { content: `Because one is an average and the other is a total, a cooler sample can hold more thermal energy than a hotter one: a bathtub of warm water holds more than a cup of boiling water.`, kind: 'tip' },
    { content: `For the same substance at the same temperature, more matter means more thermal energy. For the same substance in the same amount, the higher temperature means more thermal energy.`, kind: 'tip' },
    { content: `Divide a sample in half and the temperature does not move while the thermal energy is halved. That one test separates the two quantities every time.`, kind: 'tip' },
    { content: `A large total says nothing on its own about the average behind it, so the sample holding the most thermal energy is not always the hottest sample.`, kind: 'tip' },
    { content: `No thermometer can tell you how much thermal energy a sample holds. You need the reading and the amount of matter.`, kind: 'tip' },
    { content: `An object has thermal energy; it does not contain heat. Heat is the name for thermal energy moving from a warmer object to a cooler one.`, kind: 'tip' },
  ],
};
