/**
 * Grade 8 Science — Unit 9 CED 9.4: Amplitude & Wave Energy.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.amplitude-and-wave-energy.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U9_AMPLITUDE_AND_WAVE_ENERGY: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.amplitude-and-wave-energy.v1',
  course: 'Grade 8 Science',
  cedUnit: 9,
  cedTopic: '9.4',
  cedTitle: 'Amplitude & Wave Energy',
  planId: 'evelyn.ms.m8sci.amplitude-and-wave-energy.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.amplitude-and-wave-energy.v1' }],
  theory: [
    { loId: 'm8sci.amplitude-and-wave-energy', content: `A WAVE ARRIVES CARRYING ENERGY, AND THE ONLY WAY TO SEE IT IS TO WATCH THE FAR END. A wave is a disturbance that travels, and you already know that it does not carry the material along with it -- the water at the beach is the same water it was before, and the air in a room does not blow across at you when someone speaks. What travels from one end to the other is energy. So you can never point at a wave and see its energy directly. You have to watch what happens where the wave arrives, and ask whether something there changed. Did an object move that was still before? Did something rattle, swing, get flicked, get warmer, or start working? Every argument in this lesson is built on an observation at the far end, and an argument with no far-end observation in it is not finished.` },
    { loId: 'm8sci.amplitude-and-wave-energy', content: `AMPLITUDE IS THE DIAL THAT PUTS ENERGY INTO THE WAVE. Amplitude is how far the material is pushed away from its rest position as the wave goes by. Turning that dial up costs something at the source: to make a bigger wave you have to shake the rope through a wider swing, drive the loudspeaker cone further in and out, or push more water further up. Energy is never made out of nothing, so that extra effort at the source is where the extra energy in the wave comes from, and the wave carries it along to whatever it reaches. That is why the three observations people always reach for point the same way: a bigger ocean wave moves more sand than a small one, a louder sound shakes a window harder than a quiet one, and a brighter light warms a surface more than a dim one. WRONG: "The energy is stored up in the humps, so the dips between them are carrying nothing." CORRECT: "A hump and a dip are both the material pushed away from its rest position, one way and then the other way, and the energy is carried by the whole repeating disturbance -- not piled up in the high parts."` },
    { loId: 'm8sci.amplitude-and-wave-energy', content: `THE COMPARISON IS ONLY HONEST WHEN THE FREQUENCY IS HELD FIXED. Amplitude is not the only measure a wave has. How often the waves arrive matters too, and a small wave arriving very often can deliver plenty of energy. That is exactly why the rule in this lesson is written for two waves OF THE SAME FREQUENCY: for two waves of the same kind, traveling in the same material, arriving at the same rate, the one with the bigger amplitude carries more energy. Take the same-rate condition away and the comparison stops working. If one wave has taller humps AND the other brings many more waves each second, then two things changed at once, and the taller humps on their own do not settle it. When you are handed a comparison like that, the correct answer is that this comparison does not test the claim -- not a guess about which one wins.` },
    { loId: 'm8sci.amplitude-and-wave-energy', content: `CHANGING THE AMPLITUDE DOES NOT CHANGE THE SPEED. You know from the last lesson that a wave travels at a speed set by the material it is moving through, not by whoever made it. Making a wave bigger does not make it hurry. Two sounds crossing the same room reach you at the same instant whether one is a whisper and the other is a shout, and the big sea wave and the small one roll in at the same pace. So when a big wave does more damage than a small one, the reason is not that it arrived faster or hit at a higher speed. The reason is that it arrived carrying more energy. Keep those two apart, because a wave that carries more energy and a wave that travels faster are different claims about different measurements.` },
    { loId: 'm8sci.amplitude-and-wave-energy', content: `HOW TO ARGUE THE COMPARISON, IN FOUR MOVES. First, state the claim you are testing: the wave with the bigger amplitude carries more energy. Second, name the two waves and list what is being held fixed -- same kind of wave, same material, same distance, same rate of arrival. Third, name the observation at the far end and say what it took: an object that was flicked off, a panel that started working, a surface that got warmer. Fourth, say which way the evidence points, and stop there. If something other than the amplitude also changed between the two waves, the honest fourth move is to say that the comparison cannot settle the claim, and to say what you would change to fix it.` },
    { loId: 'm8sci.amplitude-and-wave-energy', content: `SAY WHICH ONE, NOT HOW MANY TIMES. This lesson compares two waves and tells you which one carries more energy. It does not tell you how much more, and you should not estimate it. It is tempting to look at a wave whose humps are twice as high and say that it must carry twice the energy, and that is not how it works: the energy grows faster than the height does. Working out exactly how much faster is a job for a later course with more mathematics in it. Here, the finished answer is a direction with a reason and an observation attached -- "the second wave carried more energy, because it pushed the material much further from its rest position while the waves kept arriving at the same rate, and that is why the object at the far end was knocked loose when the first wave only shook it."` },
    { loId: 'm8sci.amplitude-and-wave-energy', kind: 'definition', title: 'amplitude', content: `how far the material of a wave is pushed from its rest position, measured from the rest position up to the top of a hump. You met this measure in an earlier lesson; here it is always given to you, never measured.` },
    { loId: 'm8sci.amplitude-and-wave-energy', kind: 'definition', title: 'rest position', content: `where the material sits when no wave is passing -- the flat line of a still water surface, or a hanging line that nobody is shaking.` },
    { loId: 'm8sci.amplitude-and-wave-energy', kind: 'definition', title: 'frequency', content: `how many whole waves pass a fixed point each second. In this lesson it is the measure that is deliberately held fixed while two amplitudes are compared.` },
    { loId: 'm8sci.amplitude-and-wave-energy', kind: 'definition', title: 'loudness', content: `what a sound wave's amplitude comes through as when you hear it: a bigger amplitude is a louder sound.` },
    { loId: 'm8sci.amplitude-and-wave-energy', kind: 'definition', title: 'brightness', content: `what a light wave's amplitude comes through as when you see it, for light of one color: a bigger amplitude is a brighter light.` },
  ],
  methods: [
    {
      title: 'Worked two reading lamps',
      steps: [
        `State the claim being tested and name the two waves. The claim is that the wave with the bigger amplitude carries more energy. The two waves are the light from the dim setting and the light from the bright setting. For light of one color, brightness is what a bigger amplitude comes through as, so this is a comparison of two amplitudes.`,
        `List what is held fixed. Same kind of bulb, so the same kind of wave. Same color, so the same frequency. Same distance from the lamp to the panel. Same calculator with the same panel. Nothing in the setup differs except the brightness, which means nothing differs except the amplitude. That is what makes this a comparison that can settle anything.`,
        `Name the observation at the far end and say what it took. Under the dim lamp the display stays blank; under the bright lamp it switches on and stays on. The description tells you what that takes: the panel needs a certain amount of energy arriving each second before the display will light. So under the dim lamp less than that amount was arriving each second, and under the bright lamp more than that amount was.`,
        `Say which way it points, and stop there. The bright lamp's light waves, the ones with the bigger amplitude at the same frequency, carry more energy to the panel. Notice what has NOT been claimed. Nothing here says how many times more energy the bright setting delivers, and nothing in this lesson lets you work that out. The finished answer is a direction with an observation attached.`,
        `Now run the check a science answer needs, because there is no arithmetic here to redo. Half one: look for clues of DIFFERENT KINDS that agree. The first clue is electrical and sits at the far end -- the calculator runs on the bright lamp and not on the dim one. The second is an accounting clue at the source: the bright setting uses more energy each second than the dim setting, and energy is never made or destroyed, so the extra going in each second leaves the bulb each second as light and as thermal energy. The third comes from a completely different kind of detector: leave a dark sheet of paper under the bright lamp for a few minutes and it feels warm to the hand, while the same sheet under the dim lamp does not. An electrical effect, an energy count at the source, and a warming effect -- three kinds of evidence, one answer.`,
        `Half two: change exactly one condition and check that the answer moves with it. Turn the first lamp up to bright and the second one down to dim, and leave everything else exactly where it is -- same desk, same distances, same calculator. Now the display lights under the first lamp and goes blank under the second. The answer followed the setting, not the lamp, so it is the brightness -- the amplitude -- doing the work and not some difference between the two lamps. If the answer had stayed with the same lamp after the swap, the explanation would have been wrong.`,
      ],
      example: { problem: `Two identical reading lamps stand on the same desk, each the same distance from a small solar-powered calculator lying flat between them. Both lamps hold the same kind of bulb and both give out light of the same color, so the light waves leaving them have the same frequency. The first lamp is set to dim and the second to bright. With only the dim lamp on, the calculator's display stays blank. With only the bright lamp on, from the same distance, the display switches on and stays on. The panel on the calculator turns light into the electricity that runs it, and it needs a certain amount of energy arriving each second before the display will light at all. Which lamp's light waves carry more energy to the calculator, and what in this description is the evidence?`, solution: `The bright lamp's light waves carry more energy to the calculator. Everything else in the setup is held fixed -- the same kind of bulb, light of the same color and so the same frequency, the same distance and the same panel -- so the only difference is the brightness, which is the amplitude of the light wave. The evidence is the observation at the far end: the panel needs a certain amount of energy arriving each second to light the display, and the display lights only under the bright lamp. How many times more energy the bright setting delivers is not something this lesson claims. Swap the two settings over and the display lights under the other lamp, which shows the brightness and not the lamp was doing the work.` },
      relatedLoIds: ['m8sci.amplitude-and-wave-energy'],
    },
    {
      title: 'Worked clothesline and clothespin',
      steps: [
        `State the claim and name the two waves. The claim is that the wave with the bigger amplitude carries more energy. The two waves are the trial-one wave, with humps 3 centimeters above the rest position, and the trial-two wave, with humps 25 centimeters above it.`,
        `List what is held fixed. Same clothesline, tied to the same posts at the same tightness, so the same material. Same clothespin, clipped the same way at the same place. Same rate: 2 whole waves each second in both trials. The only thing that changed is how far the line is pushed from its rest position, which is the amplitude.`,
        `Name the far-end observation and say what it took. In trial one the clothespin jiggles and stays on. In trial two it is flicked clear of the line and ends up on the grass. Sending an object flying takes energy, and it takes more energy than making the same object wobble in place. Whatever arrived at the far post in trial two was able to do something that whatever arrived in trial one could not.`,
        `Bring in her second observation, the one at the source. Her arm tires faster in trial two. Making the bigger wave costs her more each second, and energy is not created inside the clothesline -- it is handed to the line at her end and carried along to the far end. So more energy going in each second is more energy arriving each second, and that matches what the clothespin did.`,
        `Say which way it points, and guard the answer against a wrong reason. At the same rate of arrival, the bigger amplitude carried more energy. WRONG: "The big wave flicked the clothespin off because it was racing along the line faster than the small one." CORRECT: "Both waves travel along that line at the same speed, because the speed is set by the line itself and not by how hard she shakes it. The big one is not quicker -- it arrives carrying more energy." And say only that much: nothing here tells you how many times more energy trial two delivered.`,
        `Run the check. Half one: three clues of DIFFERENT KINDS that agree. The first is the effect on another object at the far end, the clothespin flicked off. The second is the cost at the source, her arm tiring faster, which is an energy count rather than an effect. The third comes from the line itself in between: at 2 whole waves each second, every bit of the line has to travel much further up and down in the same amount of time in trial two, so each bit of it is moving faster -- and you already know that faster-moving matter carries more kinetic energy. Far end, source and the material in between, all pointing one way.`,
        `Half two: change exactly one condition and see the answer move. Go back to humps 3 centimeters above the rest position -- the small wave from trial one -- but shake at 6 whole waves each second instead of 2, which is three times as many. The clothespin is flicked off again. So the amplitude is not the only dial there is: a small wave arriving much more often can also deliver enough energy to do the job. That is precisely why the rule this lesson states compares waves arriving at the SAME rate. The answer moved when the rate moved, which shows the earlier comparison was honest only while the rate was being held still.`,
      ],
      example: { problem: `A clothesline is tied tightly between two posts in a yard. A student stands at one post and shakes her end up and down at a steady rate of 2 whole waves each second, sending humps traveling along the line to the far post. A wooden clothespin is clipped loosely onto the line near that far post. In the first trial the humps rise 3 centimeters above the line's rest position, and the clothespin jiggles but stays on. In the second trial she shakes her end through a much wider swing, still at 2 whole waves each second, and the humps rise 25 centimeters above the rest position; this time the clothespin is flicked off the line and lands on the grass. She also notices that her arm tires much faster during the second trial. Which trial's waves carried more energy to the clothespin, and how do both of her observations support that?`, solution: `The trial-two waves carried more energy. Everything else was held fixed -- the same line at the same tightness, the same clothespin in the same place, and 2 whole waves each second in both trials -- so the only difference was the amplitude, 25 centimeters above the rest position instead of 3. Two observations support it: at the far end the clothespin was flicked clear of the line instead of merely jiggling, and at the source her arm tired faster, which is where the extra energy came from. Both waves traveled along the line at the same speed; the bigger one simply arrived with more energy. Keep the humps small but shake three times as often, at 6 whole waves each second, and the clothespin comes off again -- which is why the comparison only works with the rate held fixed.` },
      relatedLoIds: ['m8sci.amplitude-and-wave-energy'],
    },
  ],
  pointers: [
    { content: `Students often say "Humps twice as high means exactly twice the energy." — The direction is right and the number is not. Taller humps at the same rate of arrival do mean more energy, so the student has the comparison the right way round. But the energy does not simply keep pace with the height: it grows faster than the height does, so doubling the amplitude gives more than double the energy, not exactly double. Working out how much more takes mathematics that belongs to a later course, which is why this lesson never asks how many times. The finished answer here is "the big waves carried more energy, and here is what they did at the far end that the small ones did not", and adding a number to it makes the answer worse, not better.`, kind: 'common-error' },
    { content: `Students often say "Wave A must carry more energy, because its humps are taller." — The rule compares two waves of the SAME frequency, and these two are not. Wave A has humps twice as tall as Wave B, since 6 centimeters divided by 3 centimeters is 2, but Wave B brings four times as many waves each second, since 4 divided by 1 is 4. Two things changed at once, so the taller humps on their own settle nothing, and the honest answer is that this comparison cannot test the claim. Notice that this is not the same as saying the two carry equal energy -- it is saying the comparison does not tell you. To fix it, hold the rate the same in both: run Wave B at 1 wave each second too, or run Wave A at 4, and then the difference in the humps is the only difference left. One more thing the student should not conclude: neither wave is traveling faster than the other. Both cross the same water at the same speed, just as two claps in a gym, one soft and one loud, both cross the air at about 340 meters per second and reach the far wall together.`, kind: 'common-error' },
    { content: `A wave carries energy from where it is made to whatever it reaches, and it does not carry the material along with it. You cannot see a wave's energy directly -- you see what it does when it arrives.`, kind: 'tip' },
    { content: `Amplitude is how far the material is pushed from its rest position. For two waves of the same kind, in the same material, arriving at the same rate, the one with the bigger amplitude carries more energy.`, kind: 'tip' },
    { content: `The extra energy comes from the source. Making a bigger wave costs more at the end where it is made -- a wider swing of the arm, a harder push -- and that is what the wave carries away.`, kind: 'tip' },
    { content: `The evidence always sits at the far end: an object flicked off, a boat pressed harder, a panel that starts working, a surface that gets warmer. An argument with no far-end observation in it is not finished.`, kind: 'tip' },
    { content: `The same-rate condition is part of the rule, not decoration. If the amplitude and the rate of arrival both changed, the taller humps settle nothing, and the honest answer is that the comparison cannot test the claim.`, kind: 'tip' },
    { content: `Say which one, not how many times. Twice as tall does not mean twice the energy -- the energy grows faster than the height does, and how much faster is a question for a later course.`, kind: 'tip' },
    { content: `A bigger wave is not a faster wave. In a given material every wave travels at the same speed, so a big wave and a small one arrive together; the big one simply arrives carrying more energy.`, kind: 'tip' },
    { content: `To argue it: state the claim, name the two waves and what is held fixed, name the observation at the far end and what it took, then say which way the evidence points -- and stop.`, kind: 'tip' },
  ],
};
