/**
 * Grade 8 Science — Unit 2 CED 2.4: Collisions & Designing for Safety.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.collisions-and-designing-for-safety.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U2_COLLISIONS_AND_DESIGNING_FOR_SAFETY: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.collisions-and-designing-for-safety.v1',
  course: 'Grade 8 Science',
  cedUnit: 2,
  cedTopic: '2.4',
  cedTitle: 'Collisions & Designing for Safety',
  planId: 'evelyn.ms.m8sci.collisions-and-designing-for-safety.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.collisions-and-designing-for-safety.v1' }],
  theory: [
    { loId: 'm8sci.collisions-and-designing-for-safety', content: `IN A COLLISION, BOTH OBJECTS ARE PUSHED, AND THE TWO PUSHES ARE THE SAME SIZE. You already know the third law: when two objects interact, each pushes on the other with a force equal in size and opposite in direction, and the two forces act on DIFFERENT objects, so they never cancel. A collision is that law happening fast. While a bat and a ball are touching, the bat pushes forward on the ball and the ball pushes backward on the bat, and those two pushes are the same size. Nothing travels out of the bat and into the ball. The bat pushes the ball only while they are touching, and the push ends when they come apart. What is different about the two objects is their mass, and that is where the second law comes in: force equals mass times acceleration (F = m × a), so the same size push produces a much bigger change in motion in the object with less mass. The ball, with far less mass than the bat and the arms swinging it, flies off at high speed. The bat slows a little in the batter's hands. Same size force on each, wildly different results, and the reason is mass and nothing else.` },
    { loId: 'm8sci.collisions-and-designing-for-safety', content: `STOPPING IS A CHANGE IN MOTION, SO STOPPING TAKES A FORCE. Slowing down is a change in velocity in exactly the way that speeding up is, and any change in velocity needs a force. If you are moving at 6 meters per second and then you are at rest, your speed has dropped by the whole 6 meters per second, and something pushed on you to do it. Here is the part that decides everything else in this lesson: no safety design can remove that drop. If you are moving and then you have stopped, all of the speed is gone, whatever is wrapped around you. A design does not get to choose WHETHER you stop. It only gets to choose HOW the stop is delivered -- how long it takes, and how much of you it lands on.` },
    { loId: 'm8sci.collisions-and-designing-for-safety', content: `RULE ONE: THE SAME DROP IN SPEED, SPREAD OVER A LONGER TIME, NEEDS A SMALLER FORCE. Acceleration is how fast the speed is changing, and it is measured in meters per second each second. If a stop takes three times as long, the same drop in speed happens three times more slowly, so the acceleration is one third as big -- and since force equals mass times acceleration and the mass has not changed, the force is one third as big too. That is the whole of bending your knees. It is also what a CRUMPLE ZONE is: the front of a car built from panels designed to fold and crush during a collision, so that the passenger compartment behind them comes to rest over a longer time than a rigid front would allow. It is what an AIRBAG is: a bag that inflates in a collision so that a person's head and chest push into it and slow down over a longer time than they would against a hard steering wheel. And it is what an EGG-DROP CUSHION is: a crushable layer that keeps crushing while the egg inside it is still slowing, so that the egg loses its speed over a longer time than it would against the floor.` },
    { loId: 'm8sci.collisions-and-designing-for-safety', content: `RULE TWO: THE SAME PUSH, SPREAD OVER A LARGER AREA, LANDS LESS HEAVILY ON ANY ONE PART. This rule is different from rule one and it is easy to run them together. Spreading a push over a larger area does not make the total push any smaller. What it changes is how much of that push arrives at any one part of you. A SEAT BELT is a wide strap that lies across the chest and the hips rather than a thin cord across the stomach, so the backward push that slows you is shared out across a wide band instead of concentrated on one narrow line. A HELMET'S hard outer shell does the same job for the head: whatever the shell is resting against, the shell presses on the head over the whole area it covers, instead of one small patch of skull taking all of it. Many good designs use both rules at once -- a helmet has a hard shell for the area and a crushable liner for the time -- and when you evaluate a design it is worth asking about each rule separately.` },
    { loId: 'm8sci.collisions-and-designing-for-safety', content: `WHAT A SAFETY DESIGN CANNOT DO, SAID PLAINLY. It cannot absorb the force so that none of it reaches you: you still have to lose all of your speed, and something still has to push on you to take it away. It cannot let you keep your speed while everything around you stops. And a soft layer that squashes completely flat the instant it is loaded -- what engineers call BOTTOMING OUT -- buys almost no extra time at all, because once it is flat you are stopping against whatever is behind it, in the same short time as if the layer had never been there. That is why "softer" and "safer" are not the same word. What lengthens a stop is a layer that keeps giving way for the whole time you are still slowing down, which needs both enough thickness and enough firmness to keep pushing back the whole way.` },
    { loId: 'm8sci.collisions-and-designing-for-safety', content: `HOW TO EVALUATE A PROPOSED SAFETY DESIGN, IN ORDER. (1) Name the thing being protected and the change in motion it has to go through -- from what speed, to rest, and remember the design cannot change that part. (2) Ask what the design does to the TIME: does anything crush, fold, stretch or give way while the stop is happening, and does it keep giving way for the whole stop rather than flattening at once? (3) Ask what the design does to the AREA: does the push arrive over a wide part of the object, or all at one small spot? (4) Check that the design still does its other jobs: staying on, staying together, holding the protected thing in place. (5) Compare the candidates on those answers -- not on which one feels softer to the hand, and not on which one comes out of the test undamaged, because a part that crushed is a part that was doing rule one.` },
    { loId: 'm8sci.collisions-and-designing-for-safety', kind: 'definition', title: 'collision', content: `an interaction in which two objects come into contact and push on each other, changing the motion of both.` },
    { loId: 'm8sci.collisions-and-designing-for-safety', kind: 'definition', title: 'action-reaction pair', content: `the two forces of an interaction: equal in size, opposite in direction, and acting on two different objects, so they never cancel. This is the third law, from the last lesson.` },
    { loId: 'm8sci.collisions-and-designing-for-safety', kind: 'definition', title: 'stopping time', content: `how long an object takes to go from its starting speed to rest. It is the quantity most safety designs are built to make longer.` },
    { loId: 'm8sci.collisions-and-designing-for-safety', kind: 'definition', title: 'crumple zone', content: `a part of a vehicle, usually the front, built from panels designed to fold and crush during a collision rather than keep their shape.` },
    { loId: 'm8sci.collisions-and-designing-for-safety', kind: 'definition', title: 'bottoming out', content: `what a padded layer does when it squashes completely flat early in a stop, after which the object is stopping against whatever is behind the layer.` },
    { loId: 'm8sci.collisions-and-designing-for-safety', kind: 'definition', title: 'newton', content: `the unit of force. A force of 1 newton acting on a mass of 1 kilogram makes its speed change at a rate of 1 meter per second each second.` },
  ],
  methods: [
    {
      title: 'Worked cart into a barrier',
      steps: [
        `Step 1, name what is being stopped and the change in motion. The cart is being stopped, and in both tests it goes from 6 meters per second to rest, so the drop in speed is the same 6 meters per second both times. The padding did not change that and could not have. Hold on to this: it is the reason the comparison is fair.`,
        `Step 2, the time. Test one stops the cart at a rate of 60 meters per second each second. That rate means 6 meters per second is lost in each tenth of a second, so the whole 6 meters per second is gone in one tenth of a second. Test two stops it at a rate of 20 meters per second each second, which means 2 meters per second is lost in each tenth of a second, so losing 6 meters per second takes three tenths of a second: 2 + 2 + 2 = 6. Three tenths of a second is three times one tenth of a second, which is exactly the "three times as long" the test reported. The two numbers agree.`,
        `Step 3, the force, from force equals mass times acceleration (F = m × a). Test one: 2 kilograms × 60 meters per second each second = 120 newtons. Test two: 2 kilograms × 20 meters per second each second = 40 newtons. Compare them: 120 newtons ÷ 40 newtons = 3, so the padded barrier puts one third of the force on the cart. Notice that the force ratio and the time ratio are the same number, 3, running opposite ways: three times as long, one third the force.`,
        `Step 4, the other object. While the cart and the barrier are touching, the barrier pushes backward on the cart and the cart pushes forward on the barrier, equal in size and opposite in direction. So in test one the barrier feels 120 newtons from the cart and in test two it feels 40 newtons. WRONG: "The barrier pushes 120 newtons on the cart and the cart pushes 120 newtons back, so they cancel and the cart should not slow down at all." CORRECT: "One of those forces acts on the cart and the other acts on the barrier. Two forces on two different objects cannot cancel. The only force here acting on the cart is the barrier's 120 newtons, and that is what stops it."`,
        `Step 5, run the two checks a science answer needs. First, look for clues of DIFFERENT KINDS that agree. The arithmetic agrees: the same 2 kilograms multiplied by a rate one third as big gives a force one third as big. The timing agrees independently: the reported stopping time was three times longer, and the rate of speed change came out three times smaller, two measurements that did not have to match and did. And the physical evidence agrees: after test two the padded block is crushed and stays crushed, so something really did give way over a distance while the cart was still moving -- the longer stop is visible on the block, not just felt.`,
        `Step 6, change one condition and check that the answer moves. Make the padded block twice as thick, so it keeps crushing for six times as long as the bare barrier stop instead of three times. Now the same 6 meters per second is lost at a rate of 10 meters per second each second, and 2 kilograms × 10 meters per second each second = 20 newtons, which is one sixth of 120 newtons. The answer moved, and it moved the right way. Now change a different condition instead: replace the padding with a material that feels just as soft but squashes completely flat in the first instant. It has bottomed out, the cart is stopping against the bare barrier behind it, the stopping time is back to the short one and the force is back to 120 newtons. Softness was never the cause. Crushing for the whole stop was.`,
      ],
      example: { problem: `A test cart with a mass of 2 kilograms rolls along a track at 6 meters per second and is brought to rest by a barrier at the end. The test is run twice, at the same 6 meters per second both times. Test one uses the bare barrier, which keeps its shape, and the cart's speed drops at a rate of 60 meters per second each second while it is stopping. Test two fits the same barrier with a padded block that crushes and stays crushed; the stop takes three times as long as test one, and the cart's speed drops at a rate of 20 meters per second each second. Find the force on the cart in each test, say which force the barrier feels, and say what the padding did and did not change.`, solution: `Test one: 2 kilograms × 60 meters per second each second = 120 newtons on the cart, and the cart pushes 120 newtons on the barrier. Test two: 2 kilograms × 20 meters per second each second = 40 newtons on the cart, and 40 newtons on the barrier. The padding did not change the cart's mass or the 6 meters per second it had to lose; it made the losing take three times as long, and that made the force one third as large.` },
      relatedLoIds: ['m8sci.collisions-and-designing-for-safety'],
    },
    {
      title: 'Worked evaluate three helmets',
      steps: [
        `Step 1, name what is being protected and the change in motion. The head is being protected, and it goes from whatever speed the skateboarder was falling at to rest against the ground. No helmet changes that speed or that stop. Every design here is competing on how the stop is delivered.`,
        `Step 2, ask each design what it does to the TIME. Design A: the shell keeps its shape and does not crush, so nothing gives way while the head is slowing, and the head stops in as short a time as it would with no helmet at all. Design B: the foam crushes slowly and stays crushed, so it keeps giving way for the whole stop and the head loses its speed over a longer time. Design C: the same foam liner is inside it, so it lengthens the stop in the same way design B does. On rule one, B and C pass and A fails.`,
        `Step 3, ask each design what it does to the AREA. Design A: the shell touches the head all over, so the push arrives spread across the whole covered area rather than at one small spot. Design B: the foam also touches the head all over, but with no shell there is nothing to hold the outside rigid, so the ground or an object on it presses into the foam at one place and the push arrives at the head over a smaller patch. Design C: the hard shell holds its shape and presses on the liner, and through it on the head, over the whole covered area. On rule two, A and C pass and B is the weakest.`,
        `Step 4, check the other jobs and compare. All three stay on and stay together, so nothing separates them there. Line up the two rules: A gives area but not time, B gives time but the least area, and C gives both. Design C best meets the criterion. WRONG: "Design A is best, because a hard shell is the strongest of the three and the strongest material must protect the head best." CORRECT: "Strength is not the criterion. The criterion is a smaller force on the head, and a part that keeps its shape does nothing at all to the stopping time -- what makes the force smaller is a layer that crushes for the whole stop, held under a shell that spreads the push out." A shell that comes through the fall undamaged has told you nothing about the head inside it. As it happens, design C is how skateboard and bicycle helmets are actually built: a hard outer shell over a crushable foam liner.`,
        `Step 5, run the two checks. First, three clues of DIFFERENT KINDS agree on design C. The time test says it is the only design with both a crushing layer and something to hold that layer in shape while it crushes. The area test says it is the only design in which a rigid surface spreads the push across the whole head. And the failure test agrees from the other side: each of A and B fails exactly one of the two rules, and C is what you get by fixing the failure in each. Three different questions, one answer.`,
        `Step 6, change one condition and check that the answer moves. Take design C and use a liner that has ALREADY been crushed flat in an earlier fall. The liner stays crushed, which was the stated property, so there is nothing left to give way, and design C now behaves like design A: the shell still spreads the push over the whole head, but the stop is as short as with no liner at all. The answer moved, and it moved for a reason we can name. That is also the honest limit of the whole design: a crushable layer does its job by crushing, so a layer that has already done it once has nothing left to do.`,
      ],
      example: { problem: `Three helmet designs are proposed for a skateboarder, and every fact you need about them is given here. Design A is a single hard plastic shell, shaped to the head and touching it all over, with nothing inside it; the shell keeps its shape when it is pushed on and does not crush. Design B is a thick liner of crushable foam with no outer shell; the foam crushes slowly and stays crushed, and it touches the head all over. Design C is a hard plastic shell like design A with a thick crushable foam liner like design B inside it. All three stay on the head and stay together. The criterion is the one the designs are being judged against: make the force on the head as small as possible when the head is brought to rest against the ground. Which design best meets it, and why?`, solution: `Design C. The head has to lose the same speed whatever it is wearing, so the designs compete on time and area. The crushable liner keeps giving way while the head is slowing, which lengthens the stopping time and so lowers the force; the hard shell keeps its shape and presses on the head over the whole area it covers, so less of the push lands on any one part. Design A does the area job and nothing for the time; design B does the time job but delivers the push over a smaller patch. Only C does both.` },
      relatedLoIds: ['m8sci.collisions-and-designing-for-safety'],
    },
  ],
  pointers: [
    { content: `Students often say "An airbag absorbs the force so that none of it reaches you." — A force is a push between two objects while they are touching, not a fluid that can be stored somewhere. If you are moving and then you are at rest, all of your speed is gone, and something pushed on you to take it away -- the airbag itself is the thing pushing on you. What the airbag changes is not whether it pushes but how. It inflates so that your head and chest push into it and slow down over a longer time than they would against a hard steering wheel, and force equals mass times acceleration, so a drop in speed spread over a longer time means a smaller acceleration and a smaller force. It also touches you across a wide area rather than at one small spot, so less of that push lands on any one part of you. WRONG: "The bag absorbed the force." CORRECT: "The bag delivered the force, over a longer time and a wider area, which is what made it smaller."`, kind: 'common-error' },
    { content: `Students often say "In a crash between a big truck and a small car, the truck hits the car harder than the car hits the truck." — The third law settles the forces and it has no exception for size. While the truck and the car are touching, the truck pushes on the car and the car pushes back on the truck with a force equal in size and opposite in direction. Those two forces act on two different vehicles, so they never cancel. The difference in outcome comes from force equals mass times acceleration: the same size push acting on the car's much smaller mass changes the car's motion far more than it changes the truck's. To see that mass is what makes the difference, change one thing -- give the car the same mass as the truck. The two pushes are still equal, as they always were, but now the two vehicles have their motion changed by the same amount and neither is thrown around by the other. WRONG: "The truck hit harder." CORRECT: "The pushes were equal, and the car has less mass, so the same push changed its motion much more."`, kind: 'common-error' },
    { content: `In a collision the two objects push on each other with forces equal in size and opposite in direction, acting on two different objects, so they never cancel.`, kind: 'tip' },
    { content: `The same size push changes the motion of the object with less mass much more, because force equals mass times acceleration (F = m × a).`, kind: 'tip' },
    { content: `Stopping is a change in motion, so it takes a force. No safety design can remove the drop in speed; it can only change how the stop is delivered.`, kind: 'tip' },
    { content: `Rule one, time: the same drop in speed spread over a longer time is a smaller acceleration, so a smaller force. Three times as long means one third the force.`, kind: 'tip' },
    { content: `Rule two, area: spreading a push over a larger area does not make the total push smaller, but less of it lands on any one part.`, kind: 'tip' },
    { content: `A crumple zone, an airbag and an egg-drop cushion are all rule one. A seat belt and a helmet shell are rule two, and a helmet does both at once.`, kind: 'tip' },
    { content: `Softer is not the same as safer. A layer that squashes flat at once has bottomed out, and after that the stop is as short as with no layer at all.`, kind: 'tip' },
    { content: `To evaluate a proposed design: name what is protected and the change in motion it must go through, ask what the design does to the time, ask what it does to the area, check its other jobs, then compare.`, kind: 'tip' },
    { content: `A part that crushed was doing its job. Coming through undamaged is not evidence that a design protected what was inside it.`, kind: 'tip' },
  ],
};
