/**
 * Grade 8 Science — Unit 3 CED 3.1: Gravity: Mass, Distance & Weight.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.gravity-mass-distance-and-weight.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U3_GRAVITY_MASS_DISTANCE_AND_WEIGHT: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.gravity-mass-distance-and-weight.v1',
  course: 'Grade 8 Science',
  cedUnit: 3,
  cedTopic: '3.1',
  cedTitle: 'Gravity: Mass, Distance & Weight',
  planId: 'evelyn.ms.m8sci.gravity-mass-distance-and-weight.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.gravity-mass-distance-and-weight.v1' }],
  theory: [
    { loId: 'm8sci.gravity-mass-distance-and-weight', content: `GRAVITY IS A PULL BETWEEN OBJECTS THAT HAVE MASS, AND IT ONLY EVER PULLS. Every object that has mass attracts every other object that has mass. Gravity never pushes, and there is no material you can put between two objects to shield one from the other. It acts between Earth and you, between Earth and the Moon, and -- this is the part that surprises people -- between you and the chair you are sitting on. You do not feel that last one because you and the chair both have tiny masses next to Earth's, so the pull between the two of you is far too weak to notice. Too weak to notice is not the same as zero. Gravity also acts between two objects that are nowhere near touching, which is how Earth pulls on something high above the ground; how a pull can reach across a gap like that is the question a later lesson in this unit takes up.` },
    { loId: 'm8sci.gravity-mass-distance-and-weight', content: `TWO THINGS SET THE STRENGTH OF THE PULL: THE MASSES, AND THE DISTANCE. The more mass the two objects have, the stronger the pull between them. That is the whole reason Earth holds you on the ground: there is nothing special about ground, there is just an enormous amount of mass underneath it. And the farther apart the two objects are, the weaker the pull between them becomes. Both parts are at work at the same time, so a question about gravity is always a question about two masses and one distance. The Moon is the example to hold on to. The Moon has far less mass than Earth does, and that is why anything resting on the Moon is pulled toward the Moon much less strongly than the same object is pulled toward Earth here.` },
    { loId: 'm8sci.gravity-mass-distance-and-weight', content: `THE PULL WEAKENS WITH DISTANCE, BUT IT NEVER RUNS OUT. There is no line you can cross where gravity stops. Move an object farther from Earth and Earth's pull on it gets weaker, and weaker again, and it goes on getting weaker forever without ever reaching exactly zero. Earth's pull reaches all the way out to the Moon -- it is the force that keeps the Moon circling Earth instead of drifting off in a straight line -- and it keeps reaching far beyond that. WRONG: "Gravity ends where the air ends." CORRECT: "Gravity gets weaker with distance and never ends; the air ending has nothing to do with it." Exactly how much weaker the pull gets for a given extra distance is a real question with a formula behind it, and that formula belongs to a later course. What this lesson needs is the direction: more distance, less pull.` },
    { loId: 'm8sci.gravity-mass-distance-and-weight', content: `MASS AND WEIGHT ARE TWO DIFFERENT QUANTITIES WITH TWO DIFFERENT UNITS. Mass is the amount of matter in an object. It is measured in kilograms, and it is the same everywhere -- in this room, on the Moon, on a space station, drifting far from every star. Moving an object somewhere else does not add matter to it or take matter away. Weight is a force: it is the gravitational pull on that mass, it is measured in newtons, and it depends on where the object is and on what large mass is nearby. On Earth, each kilogram of mass weighs about 10 newtons. On the Moon, each kilogram of mass weighs about one sixth of that. WRONG: "I weigh 50 kilograms." CORRECT: "My mass is 50 kilograms, and on Earth that mass weighs about 500 newtons." Everyday English uses the word "weigh" for both quantities, which is exactly why they get tangled; in science they are as different as a length and a temperature.` },
    { loId: 'm8sci.gravity-mass-distance-and-weight', content: `FLOATING IS NOT THE SAME AS HAVING NO GRAVITY. A space station circles a few hundred kilometers above the ground. That sounds enormous until you compare it with Earth itself, which measures thousands of kilometers from its center out to its surface, so an astronaut up there is only a little farther from Earth's center than you are right now, and Earth's pull on her is almost as strong as its pull on you. She floats for a completely different reason: she, the station, and every loose object inside it are all falling together at the same rate, so nothing presses on anything. No floor pushes up on her feet and no strap digs into her shoulder, and that is what people are describing when they say she feels weightless. You have felt a two-second version of it on a drop ride, in the moment when the car falls and the bag on your lap lifts away from you. Why the station keeps going around Earth instead of arriving at the ground is an orbit question, and it is not this lesson's question.` },
    { loId: 'm8sci.gravity-mass-distance-and-weight', content: `HOW TO ANSWER ANY MASS-VERSUS-WEIGHT QUESTION. First, decide which quantity the question is actually about: the amount of matter, which is answered in kilograms, or the pull on that matter, which is answered in newtons. Second, if it is mass, the answer does not depend on location at all -- the same number goes in every place the object is taken. Third, if it is weight, ask what large mass is nearby and how far the object is from it, because those are the only two things that can change the answer. Fourth, check the size of your answer against the two figures worth remembering: on Earth each kilogram of mass weighs about 10 newtons, on the Moon about one sixth of that, and far from every large mass an object weighs very nearly nothing while every gram of matter in it is still there.` },
    { loId: 'm8sci.gravity-mass-distance-and-weight', kind: 'definition', title: 'gravity', content: `the attraction between any two objects that have mass. It always pulls them toward each other and never pushes.` },
    { loId: 'm8sci.gravity-mass-distance-and-weight', kind: 'definition', title: 'mass', content: `the amount of matter in an object, measured in kilograms. It is the same wherever the object is taken.` },
    { loId: 'm8sci.gravity-mass-distance-and-weight', kind: 'definition', title: 'weight', content: `the gravitational force on an object, measured in newtons. It depends on what large mass is nearby and how far away it is.` },
    { loId: 'm8sci.gravity-mass-distance-and-weight', kind: 'definition', title: 'newton', content: `the unit forces are measured in. On Earth, one kilogram of mass weighs about 10 newtons.` },
    { loId: 'm8sci.gravity-mass-distance-and-weight', kind: 'definition', title: 'kilogram', content: `the unit mass is measured in. It counts matter, not pull, so it does not change with location.` },
    { loId: 'm8sci.gravity-mass-distance-and-weight', kind: 'definition', title: 'free fall', content: `the state of an object that is falling with nothing holding it up. Objects falling together do not press on one another, which is why an astronaut in free fall feels weightless.` },
  ],
  methods: [
    {
      title: 'Worked toolbox on the moon',
      steps: [
        `Sort the question into its two quantities before doing anything else. Mass is the amount of matter in the toolbox and is answered in kilograms. Weight is the gravitational pull on that matter and is answered in newtons. The question asks for both, in two places, so there are four numbers to produce.`,
        'Mass on Earth. The problem gives it: 30 kilograms. Nothing to work out.',
        `Weight on Earth. Each kilogram of mass weighs about 10 newtons on Earth, and the toolbox has 30 kilograms of mass, so its weight is 30 lots of 10 newtons, which comes to about 300 newtons.`,
        `Mass on the Moon. Nobody opened the toolbox, so no matter left it and no matter joined it. Its mass is still 30 kilograms. A trip changes where an object is; it does not change how much matter the object is made of. WRONG: "Its mass on the Moon is one sixth of 30 kilograms, which is 5 kilograms." CORRECT: "Its mass on the Moon is 30 kilograms, exactly as it was on Earth."`,
        `Weight on the Moon. The Moon has far less mass than Earth has, so it pulls much less strongly on anything resting on it: each kilogram of mass weighs about one sixth as much there as it does here. One sixth of 300 newtons is 50 newtons, so the toolbox weighs about 50 newtons on the Moon. That is the number that fell, and it fell because what was pulling on the toolbox changed, not because the toolbox changed.`,
        `Now run the two checks a science answer needs. First, look for clues of DIFFERENT KINDS that agree. The units agree: the question about matter is answered in kilograms and only the newtons answer moved. The object agrees: the box was sealed the whole time, so there is no way for matter to have left it. And the surroundings agree: the one thing that genuinely changed between the two weighings is which large mass the toolbox was resting on, and that is precisely the thing weight depends on. Three different kinds of evidence, one answer.`,
        `Second, change one condition and check that the answer moves the way it should. Carry the same sealed toolbox far away from Earth and the Moon and every other large mass, out where the nearest one is billions of kilometers off. Its mass is still 30 kilograms -- the same matter, in the same box -- and now a scale under it would read very nearly zero newtons. The mass reading has not moved once across three locations. The newtons reading has moved every single time. That is the test: weight is the quantity that answers to where you are, and mass is the quantity that does not.`,
      ],
      example: { problem: `A rover toolbox has a mass of 30 kilograms. It is weighed on Earth, and later the same sealed toolbox is weighed on the surface of the Moon with a scale that reads in newtons. Nothing is added to it or taken out of it at any point. Give its mass and its weight in both places, and say which of the two quantities changed and why.`, solution: `Mass: 30 kilograms on Earth and 30 kilograms on the Moon -- unchanged, because no matter was added or removed. Weight: about 300 newtons on Earth (30 kilograms at about 10 newtons for each kilogram) and about 50 newtons on the Moon (one sixth of 300 newtons). Only the weight changed, because weight is the gravitational pull on the toolbox and the Moon, with far less mass than Earth, pulls much less strongly on anything at its surface.` },
      relatedLoIds: ['m8sci.gravity-mass-distance-and-weight'],
    },
    {
      title: 'Worked no gravity in space claim',
      steps: [
        `Take the claim apart. There are two pieces welded together: a claim about the world (there is no gravity in space) and an explanation built on it (that is why things float). They have to be checked separately, because the second one can fail even where the first one sounds convincing.`,
        `Check the first piece against the distance rule. Gravity gets weaker with distance and never switches off, so the only question is how much weaker it is up there. A space station circles a few hundred kilometers above the ground, while Earth measures thousands of kilometers from its center out to its surface. Moving up a few hundred kilometers is therefore a small change in the distance from Earth's center, and Earth's pull on an astronaut on the station is almost as strong as its pull on you sitting still right now. The first piece is not slightly overstated. It is false.`,
        `There is a second reason to be sure of that. Earth's pull reaches all the way out to the Moon, which is very much farther away than any space station, and it is what keeps the Moon circling Earth. A pull that reaches that far has obviously not run out a few hundred kilometers up.`,
        `Now give the real reason for the floating. The station, the astronaut and every loose object inside are all falling, and all falling at the same rate together. Nothing is pressing on anything: no floor pushes up on her feet, no shelf pushes up on the toolbag. The feeling people call weightlessness is the feeling of nothing pressing on you. WRONG: "The tools hang in mid-air because there is no gravity acting on them." CORRECT: "The tools are falling, and so is everything around them, so they do not move away from the astronaut and nothing has to hold them up." Why the station keeps going around Earth instead of arriving at the ground is an orbit question, and it is not this lesson's question.`,
        `Say what was right, because part of it was. Things really do float on a space station, and gravity really does get weaker as you go farther out -- the student had the direction of that rule correct. What went wrong is the size (a few hundred kilometers barely weakens Earth's pull) and the reason (the floating comes from falling together, not from an absence of gravity).`,
        `Run the two checks. First, three clues of DIFFERENT KINDS agree. The distance comparison says a few hundred kilometers is small next to the thousands of kilometers from Earth's center to its surface. The reach of Earth's pull says the same thing from another direction, since that pull extends past the station all the way to the Moon. And an everyday case says it a third way: on a drop ride, the bag on your lap lifts away from you for a second or two, and nobody thinks Earth's gravity switched off at the top of the tower -- gravity is exactly what is making the car fall.`,
        `Second, change one condition and watch the answer move. Suppose the station could be held still, at the same height, on top of an impossibly tall tower, so that it was no longer falling. The distance from Earth's center would be unchanged, so the pull would be unchanged -- but the astronaut would now stand on the floor with almost her full weight, and the released toolbag would drop to her feet. The floating vanished when the falling stopped, and the distance never moved. That is how you know the floating was about the falling.`,
      ],
      example: { problem: `A student writes: "There is no gravity in space. That is why astronauts on the space station float, and why a bag of tools let go in mid-air just hangs there instead of dropping." Using what you know about how gravity depends on mass and distance, say what is right in that claim and what is wrong with it, and give the correct reason for the floating.`, solution: `The claim is wrong where it matters most. Gravity weakens with distance but never switches off, and a space station is only a few hundred kilometers up against the thousands of kilometers from Earth's center to its surface, so Earth's pull on an astronaut there is almost as strong as it is on the ground -- and the same pull reaches far past her to the Moon. The astronaut and the tools float because they and the station are all falling together at the same rate, so nothing presses on anything. Hold the station still at that height and she would stand on the floor with almost her full weight.` },
      relatedLoIds: ['m8sci.gravity-mass-distance-and-weight'],
    },
  ],
  pointers: [
    { content: `Students often say "On the Moon my mass would be one sixth of what it is on Earth." — It is the WEIGHT that falls to about one sixth on the Moon, and the mass that stays put. Mass is the amount of matter in you, and a rocket journey does not remove five sixths of your atoms. Take a student with a mass of 60 kilograms. On Earth that mass is 60 kilograms and, at about 10 newtons for each kilogram, it weighs about 600 newtons. On the Moon that mass is still 60 kilograms, and it weighs about one sixth of 600 newtons, which is about 100 newtons. WRONG: "My mass would be one sixth." CORRECT: "My mass would be exactly what it is now; my weight would be about one sixth of what it is now." The quick check is the unit: kilograms count matter and travel with you unchanged, newtons measure a pull and depend on what is pulling.`, kind: 'common-error' },
    { content: `Students often say "My weight is just how much stuff I am made of." — Weight is a force, and a force is always an interaction between two objects. Your weight on Earth is the gravitational pull between you and Earth, so it depends on Earth being there and on how far from its center you are -- take Earth out of the situation and the number changes. The quantity that really does describe how much stuff you are made of is your mass, in kilograms. Carry the same body far from every large mass and its weight is very nearly nothing, while every atom of it is still there and its mass has not moved by a gram. WRONG: "Weight is the amount of stuff in me." CORRECT: "Mass is the amount of stuff in me. Weight is how hard something else is pulling on that mass right now."`, kind: 'common-error' },
    { content: `Gravity is an attraction between any two objects that have mass. It only ever pulls, it acts between objects that are not touching, and it cannot be blocked or shielded.`, kind: 'tip' },
    { content: `Two things set the strength of the pull: the masses involved (more mass, more pull) and the distance between them (more distance, less pull).`, kind: 'tip' },
    { content: `The pull weakens with distance but never runs out. Earth's pull reaches the Moon and keeps going, so there is no boundary in space where gravity switches off.`, kind: 'tip' },
    { content: `Mass is the amount of matter in an object, measured in kilograms, and it is the same everywhere you take the object.`, kind: 'tip' },
    { content: `Weight is the gravitational force on that mass, measured in newtons, and it changes with what large mass is nearby and how far away it is.`, kind: 'tip' },
    { content: `On Earth each kilogram of mass weighs about 10 newtons. On the Moon each kilogram weighs about one sixth of that, because the Moon has far less mass than Earth.`, kind: 'tip' },
    { content: `Astronauts float because they, the station and everything loose inside are all falling together at the same rate, so nothing presses on anything -- not because gravity is missing up there.`, kind: 'tip' },
    { content: `To answer any question of this kind: decide whether it is asking about matter (kilograms, never changes with location) or about a pull (newtons, changes with what is nearby and how far).`, kind: 'tip' },
    { content: `Don't say an object "has" weight. Weight is a force—a pull between two objects. Say "weighs" (present tense, describes the pull right now) or "the weight on it is" (describes the force acting). Your mass you have; your weight Earth gives you.`, kind: 'vocab-note' },
    { content: `When you move an object to a new place, its mass does not change—ever. No matter is added or removed by travel. If a problem says mass changed between locations, reread it; the problem is asking about weight (in newtons), not mass (in kilograms).`, kind: 'common-error' },
    { content: `Gravity never stops, even billions of kilometers away. The pull gets weaker and weaker, but the exponent is never zero. Wrong: "Gravity ends where the air ends." Right: "Gravity gets weaker with distance; air has nothing to do with it."`, kind: 'gotcha' },
    { content: `Floating astronauts still have gravity pulling on them—almost as hard as on the ground. They float because they, the station, and loose objects all fall together at the same rate. Nothing presses on them. It's free fall, not no gravity.`, kind: 'common-error' },
    { content: `Always ask two things when a weight question looks stuck: What large mass is nearby? How far is the object from that mass? Weight depends on both. If you don't name them, you haven't finished the problem.`, kind: 'tip' },
    { content: `Check your mass-versus-weight answer with units first. Mass goes in kilograms and never moves with location. Weight goes in newtons and moves every time location or the nearby mass changes. If your units don't do this, the answer is wrong.`, kind: 'tip' },
    { content: `Don't confuse 'pull gets weaker' with 'pull disappears.' On the Moon the pull is one sixth as strong, not zero. At the station the pull is almost Earth-strength, not zero. Use 'weaker' and 'smaller'; never say gravity is 'gone.'`, kind: 'vocab-note' },
  ],
};
