/**
 * Grade 8 Science — Unit 10 CED 10.2: Refraction: Bending Light at a Boundary.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.refraction-bending-light-at-a-boundary.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U10_REFRACTION_BENDING_LIGHT_AT_A_BOUNDARY: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.refraction-bending-light-at-a-boundary.v1',
  course: 'Grade 8 Science',
  cedUnit: 10,
  cedTopic: '10.2',
  cedTitle: 'Refraction: Bending Light at a Boundary',
  planId: 'evelyn.ms.m8sci.refraction-bending-light-at-a-boundary.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.refraction-bending-light-at-a-boundary.v1' }],
  theory: [
    { loId: 'm8sci.refraction-bending-light-at-a-boundary', content: `INSIDE ONE MATERIAL, LIGHT GOES IN STRAIGHT LINES. Light crossing a room, a tank of clear water or a block of glass travels in straight lines the whole way through. It does not curve, it does not sag and it does not wander. The only place its direction changes is a BOUNDARY: the surface where one transparent material ends and a different one begins. A tank of water has two of those on the path of a beam that goes in and comes out again -- the surface where the light enters and the surface where it leaves -- and a bend can happen at each one, with a straight run in between. So the first move in any question of this kind is to find the boundaries and ignore everything in between, because nothing happens in between.` },
    { loId: 'm8sci.refraction-bending-light-at-a-boundary', content: `THE BEND HAPPENS BECAUSE THE SPEED CHANGES, AND NOTHING TOUCHES THE LIGHT. Light travels fastest where there is nothing in its way at all, about 300,000 kilometers per second, and it travels more slowly inside a transparent material. It is slower in water than in air, and slower in glass than in air. When light crosses a boundary, its speed changes at that surface, and that change of speed is what turns its path. This is the sentence to be careful with. WRONG: "The water is heavier than the air, so it pushes the light over to one side." CORRECT: "Nothing pushes the light. The light travels at a different speed on the far side of the surface, and a path that changes speed at a slant changes direction there." The name for the whole effect -- the change of direction at a boundary because of a change of speed -- is REFRACTION.` },
    { loId: 'm8sci.refraction-bending-light-at-a-boundary', content: `WHICH WAY IT BENDS, AND THE ONE CASE WHERE IT DOES NOT BEND AT ALL. Direction needs a reference, so use this one: the line that stands straight up out of the surface at the exact point where the light arrives. Going from a faster material into a slower one at a slant -- air into water, air into glass -- the path bends TOWARD that upright line. Going the other way, from a slower material into a faster one at a slant -- water into air, glass into air -- it bends AWAY from that line. And now the case that decides whether a student really has the idea: light that arrives square-on, traveling exactly along that upright line, does not bend at all. Its speed still changes, because the material still changed. There is simply no side of the beam that meets the surface ahead of the other side, so there is nothing to turn it. Refraction needs both a change of speed AND an arrival at a slant.` },
    { loId: 'm8sci.refraction-bending-light-at-a-boundary', content: `REFRACTION IS WHY A THING CAN LOOK LIKE IT IS SOMEWHERE IT IS NOT. You see a thing because light from it reaches your eye. Your eye has no way of knowing where that light has been; it only knows the direction the light was going when it arrived, and it assumes, always, that the light came in a straight line all the way. When the light has actually bent at a surface on its way to you, that assumption is wrong, and the thing appears along the straight line traced backward from the direction the light was last going -- which is not where the thing is. That is the whole of the pool. Light leaves the bottom of the pool, bends away from the upright line as it escapes into the air, and reaches your eye traveling in a direction that traces back to a point higher than the real bottom. So the pool looks shallower than it is. Nothing moved. The light took a bent path and your eye read it as a straight one.` },
    { loId: 'm8sci.refraction-bending-light-at-a-boundary', content: `A LENS IS THE SAME RULE APPLIED TO A CURVED SURFACE, TWICE. A lens is a piece of transparent material whose surfaces are curved rather than flat, so that different parts of a wide beam meet the surface at different slants and are turned by different amounts. The rule that makes a lens predictable is this one: when light crosses a wedge of transparent material at a slant, it is turned TOWARD the thicker part of that wedge, first at the surface where it enters and again at the surface where it leaves. A lens that is thicker at its middle than at its edges therefore turns every ray toward its middle, and a wide beam of parallel rays passing through it is brought together at a single point beyond it. Compare that with a flat sheet of window glass, whose two surfaces are parallel: there the light bends toward the upright line going in and away from it by the same amount coming out, so it leaves traveling in the direction it started, shifted a little to one side and gathered nowhere.` },
    { loId: 'm8sci.refraction-bending-light-at-a-boundary', content: `HOW TO ANSWER ANY REFRACTION QUESTION. First, name the two materials and say which of them light travels more slowly in. Second, find the boundary, and be sure it is the only place anything happens. Third, ask how the light arrives there: at a slant, so it turns, or square-on, so it does not. Fourth, say which way it turns -- toward the upright line if it is entering the slower material, away from it if it is leaving one. Fifth, and only if the question is about how something LOOKS, trace the straight line backward from the direction the light was going when it reached the eye, and say where that line says the thing is. Run those five in order and the awkward cases stop being awkward.` },
    { loId: 'm8sci.refraction-bending-light-at-a-boundary', kind: 'definition', title: 'refraction', content: `the change in direction of light where it crosses at a slant from one transparent material into another, caused by the change in its speed at that boundary.` },
    { loId: 'm8sci.refraction-bending-light-at-a-boundary', kind: 'definition', title: 'transparent', content: `letting light pass through, so that things can be seen through it -- air, clear water, window glass and clear plastic are all transparent.` },
    { loId: 'm8sci.refraction-bending-light-at-a-boundary', kind: 'definition', title: 'boundary', content: `the surface where one material ends and another begins; the only place along a light path where the direction can change.` },
    { loId: 'm8sci.refraction-bending-light-at-a-boundary', kind: 'definition', title: 'normal line', content: `the imaginary line that stands straight up out of a surface at the point where light meets it, used to say which way a bend goes; it is a reference line, not a real thing.` },
    { loId: 'm8sci.refraction-bending-light-at-a-boundary', kind: 'definition', title: 'lens', content: `a piece of transparent material with curved surfaces, which refracts the parts of a wide beam by different amounts and so brings the beam together or spreads it out.` },
    { loId: 'm8sci.refraction-bending-light-at-a-boundary', kind: 'definition', title: 'apparent position', content: `where an object looks as though it is, found by tracing the light straight back from the direction it was going when it reached the eye; it differs from the real position whenever the light was refracted on the way.` },
  ],
  methods: [
    {
      title: 'Worked straw looks broken',
      steps: [
        `Name the two materials and say which one light is slower in. The light that shows you the underwater part of the straw has to leave the water and cross into the air before it can reach your eye. So the two materials are water and air, and light travels more slowly in water than in air.`,
        `Find the boundary. There is exactly one on this path: the flat top surface of the water. Below it the light runs in a straight line through the water; above it the light runs in a straight line through the air; the only place the direction can change is the surface itself. Notice that this already predicts something about what you see -- if the direction changes only at the surface, then the apparent snap should sit exactly at the surface and nowhere else.`,
        `Say which way the light turns, and how it arrives. Light leaving the underwater part of the straw reaches the surface at a slant, because you are looking from the side rather than from straight overhead. It is crossing from the slower material into the faster one, so it bends AWAY from the line that stands straight up out of the water surface.`,
        `Trace the line back, because this question is about how something looks. Your eye receives that light and assumes it came in a straight line the whole way. Trace that straight line backward and it does not arrive at the real underwater straw; it arrives beside it. So the underwater half is seen at an apparent position that is shifted from its real one, while the half in the air, whose light never crossed a boundary, is seen exactly where it is. Two halves of one straight straw, seen in two places that do not line up, with the mismatch at the surface. That is the snap. WRONG: "The water is squashing or bending the straw." CORRECT: "The straw is straight. The light from its lower half changed direction at the water surface, and the eye read that bent path as a straight one."`,
        `Now run the two checks a science answer needs, because there is no arithmetic here to redo. First, look for clues of DIFFERENT KINDS that agree. WHERE the effect appears agrees: the apparent break sits exactly at the water line, not spread along the straw, which is what a boundary effect looks like and not what squashing would look like. WHAT THE OBJECT IS LIKE agrees: lift the straw out and it is straight, and run a finger down it while it is still under the water and it is straight under your finger too, so nothing has happened to the straw. And HOW IT DEPENDS ON THE VIEWER agrees: move your head around until you are looking down into the glass from as close to straight above the straw as you can get, and the apparent break shrinks away to almost nothing, because the light from the underwater half is now leaving the surface close to square-on and is barely turned at all. Three different kinds of evidence, one answer -- and the third kind is one that squashing could never produce, because an object that was really bent would look bent from every side.`,
        `Second, change one thing about the setup and check that the answer moves the way it should. Pour the water out and leave the straw leaning in the empty glass. Same straw, same glass, same light, same viewing position -- and the straw now looks perfectly straight, because there is no longer a water-to-air boundary on the path. Then pour water back in, but only half as deep. The apparent snap comes back, and it comes back at the new water line, lower down the straw. The effect follows the boundary, not the straw.`,
      ],
      example: { problem: `A straight plastic straw stands at a slant in a tall glass of clear water, leaning against the rim, with its lower half under the water and its upper half in the air. Looked at from the side, the straw does not look straight. It looks as though it has been snapped at the water line, with the underwater part shifted to one side of where the upper part points. A student says the water must be squashing the straw. Explain what is actually happening, and how you would show that the straw itself is fine.`, solution: `The straw is straight and nothing is happening to it. Light from the underwater half of the straw meets the top surface of the water at a slant and crosses from water into air, which is a change from a slower material to a faster one, so it bends away from the line that stands straight up out of the surface. Your eye assumes that light travels in a straight line all the way, traces the arriving light straight back, and places the underwater half beside where it really is, while the half in the air is seen exactly where it is. The mismatch appears at the surface, which is where the bend happened. Empty the glass and the straw looks straight again.` },
      relatedLoIds: ['m8sci.refraction-bending-light-at-a-boundary'],
    },
    {
      title: 'Worked magnifier bright spot',
      steps: [
        `Start with the light before it reaches the glass. The sun is so far away that the sunlight arriving at the glass is a wide patch of rays all traveling parallel to one another, spread across the whole width of the glass. Nothing about that patch is concentrated yet: the same light is falling on the paper beside the glass, and there it is just ordinary daylight.`,
        `Apply the boundary rule at the first surface. Each ray meets the curved top surface of the glass at a slant -- a different slant at each place across the glass, because the surface is curved -- and crosses from air into glass, which is a change into a slower material. So each ray is turned, and the amount of the turn is different at different places across the glass. The way to keep track of all of them at once is the wedge rule: light crossing a wedge of transparent material at a slant is turned toward the thicker part of the wedge.`,
        `Apply it again at the second surface, then read off the result. The rays cross the curved bottom surface on the way out, from glass back into air, and are turned toward the thicker part once more. For this glass the thick part is the middle, so every ray is turned inward toward the middle, and the rays that entered spread right across the wide face of the glass all arrive at one small place on the paper.`,
        `Now say what the student has wrong. WRONG: "The glass makes the light stronger." CORRECT: "The glass does not make any light at all, and it adds nothing to the light that falls on it. It gathers the light from its whole wide face into a small spot, so all of that light arrives in one small place instead of being spread out." The spot is bright for the same reason it is warm: the light that used to land on a face the size of your palm is now landing on a patch the size of a pinhead. The total is the same light, delivered to a smaller place.`,
        `Now run the two checks a science answer needs. First, look for clues of DIFFERENT KINDS that agree. The AREAS agree: a wide face of glass, a tiny spot, and nothing bright anywhere else on the paper -- light gathered from somewhere has to have left somewhere. The SHADOW agrees: the paper immediately around the bright spot, in the glass's own shadow, is darker than the paper further away, which is exactly what you would see if the light that should have landed there had been redirected inward. And COVERING PART OF THE GLASS agrees: put your hand over half of the glass and the spot stays in the same place and keeps its shape, and only gets dimmer -- so every part of the glass was sending light to that same spot, which is what "gathered" means and is not what "made stronger" would predict.`,
        `Second, change one thing and check that the answer moves the way it should. Swap the magnifying glass for a flat sheet of window glass of the same thickness, whose two surfaces are parallel instead of curved. The light still slows down inside it, and it still bends at each surface -- but at parallel surfaces the second bend undoes the first, so the rays leave still parallel to one another, shifted slightly to one side, and no spot forms at all. Same material, same sunlight, same height above the paper; only the shape of the surfaces changed, and the spot vanished. That is the evidence that the gathering comes from the curve of the surfaces and not from the glass being glass.`,
      ],
      example: { problem: `On a bright day, a magnifying glass -- a round piece of clear glass that is thicker at its middle than at its edges -- is held still, about a hand's width above a sheet of paper, with sunlight falling on it from above. A small, very bright spot appears on the paper, and the paper under the spot becomes warm. A student says the glass is making the sunlight stronger. Explain what the glass actually did to the light, and say what the student has wrong.`, solution: `The glass did not make the sunlight stronger and did not add anything to it. Sunlight reaches the glass as a wide patch of parallel rays. Each ray refracts at the curved top surface as it crosses from air into the slower glass, and again at the curved bottom surface on the way out, and at both surfaces it is turned toward the thicker part of the glass, which for this lens is the middle. Every ray is therefore turned inward, and the light from the whole wide face of the glass is gathered into one small spot on the paper. The spot is bright and warm because the same amount of light is arriving in a much smaller place. Replace the lens with a flat sheet of window glass, whose surfaces are parallel, and the two bends cancel, the rays leave parallel, and there is no spot.` },
      relatedLoIds: ['m8sci.refraction-bending-light-at-a-boundary'],
    },
  ],
  pointers: [
    { content: `Students often say "Light bends because the water is heavier and pushes it over to one side." — Nothing touches the light and nothing pushes it. What changes at the surface is the SPEED: light travels more slowly in water than in air, and a path whose speed changes at a slant changes direction there. The test that settles it is the square-on case. Send a beam straight down into the water, along the line that stands straight up out of the surface, and it slows down by exactly as much as a slanted beam does -- and it does not turn at all. A push would still be a push whichever way the beam was pointing, so a push cannot explain a bend that disappears the moment the beam arrives square-on. WRONG: "The water pushes the light over." CORRECT: "The light changes speed at the surface, and it turns only if it arrives at a slant."`, kind: 'common-error' },
    { content: `Students often say "Light travels faster in water than in air, the way sound does." — Light travels fastest where there is nothing in its way at all, about 300,000 kilometers per second, and more slowly inside a transparent material: slower in water than in air, and slower in glass than in air. Sound goes the other way, moving faster through water and through steel than through air. So for light, going from air into water is going into a SLOWER material, and that is why a slanted beam turns toward the line that stands straight up out of the surface as it enters, and away from that line when it leaves the water again. Get the speed comparison backward and every direction in this lesson comes out reversed. WRONG: "Water carries waves better, so light must speed up in it." CORRECT: "Sound speeds up in water and light slows down in it, and refraction follows the light rule, not the sound rule."`, kind: 'common-error' },
    { content: `Inside one material light travels in straight lines. The only place its direction changes is a boundary, where one transparent material ends and another begins.`, kind: 'tip' },
    { content: `Refraction is the change of direction at a boundary, and the cause is the change of SPEED there. Nothing touches the light and nothing pushes it.`, kind: 'tip' },
    { content: `Light travels fastest where nothing is in its way, about 300,000 kilometers per second, and more slowly in a transparent material. It is slower in water than in air, and slower in glass than in air.`, kind: 'tip' },
    { content: `Sound runs the opposite way -- faster in water and in steel than in air. Refraction follows the light rule, not the sound rule.`, kind: 'tip' },
    { content: `Entering a slower material at a slant, light bends TOWARD the line that stands straight up out of the surface. Leaving a slower material at a slant, it bends AWAY from that line.`, kind: 'tip' },
    { content: `Light arriving square-on does not bend at all, even though its speed still changes. Refraction needs a change of speed AND an arrival at a slant.`, kind: 'tip' },
    { content: `Your eye assumes that light came in a straight line. When the light bent on the way, the object is seen along that straight line traced backward, which is why a pool looks shallower than it is and a straw looks snapped at the water line. Nothing moved; the light took a bent path.`, kind: 'tip' },
    { content: `A lens has curved surfaces, so different parts of a beam are turned by different amounts. At each surface the light is turned toward the thicker part of the material, so a lens thicker at its middle gathers a parallel beam into a point.`, kind: 'tip' },
    { content: `To answer any refraction question: name the two materials and the slower one, find the boundary, ask whether the light arrives at a slant or square-on, say which way it turns, and only then trace the line back to say where something looks.`, kind: 'tip' },
    { content: `Light bends ONLY at a boundary between two different materials. Inside one material—even if it's thick—light travels straight. Find the boundary first; nothing else matters.`, kind: 'gotcha' },
    { content: `Don't say 'the water pushes the light' or 'the glass moves the beam.' Nothing touches light. The light CHANGES SPEED at the boundary, and that speed change causes the bend if the light arrives at a slant.`, kind: 'common-error' },
    { content: `Light travels SLOWER in water and glass than in air. Sound does the opposite. If you mix them up, every direction comes out backward.`, kind: 'vocab-note' },
    { content: `A light beam arriving square-on (straight down along the normal line) does NOT bend, even though its speed still changes. Bending needs BOTH a speed change AND a slant arrival.`, kind: 'edge-case' },
    { content: `Use the normal line (the upright line out of the surface) as your reference. Into slower material = bend TOWARD it. Out of slower material = bend AWAY from it. Flip this and your answer flips.`, kind: 'tip' },
    { content: `The straw looks broken because light took a bent path, but your eye assumes straight light. Trace the light backward from where it was going when it reached your eye—that's where the object LOOKS, not where it IS.`, kind: 'vocab-note' },
    { content: `A lens is not magic. A curved surface bends different rays by different amounts. Thicker-in-the-middle turns every ray toward the center; thinner-in-the-middle spreads them apart. Both follow the same speed-change rule.`, kind: 'common-error' },
    { content: `When answering a refraction question, go in order: (1) name the two materials and which is slower, (2) find the boundary, (3) does light arrive at a slant or square-on?, (4) which way does it turn? Only then trace back if you need the apparent position.`, kind: 'tip' },
  ],
};
