/**
 * Grade 8 Science — Unit 3 CED 3.2: Electric Forces & Charge.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.electric-forces-and-charge.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U3_ELECTRIC_FORCES_AND_CHARGE: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.electric-forces-and-charge.v1',
  course: 'Grade 8 Science',
  cedUnit: 3,
  cedTopic: '3.2',
  cedTitle: 'Electric Forces & Charge',
  planId: 'evelyn.ms.m8sci.electric-forces-and-charge.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.electric-forces-and-charge.v1' }],
  theory: [
    { loId: 'm8sci.electric-forces-and-charge', content: `THERE ARE TWO KINDS OF CHARGE, AND MOST THINGS CARRY PLENTY OF BOTH. Electric charge is a property of matter, and it comes in exactly two kinds: positive and negative. Almost everything around you holds an enormous amount of both kinds at the same time, in equal amounts, and an object like that is called neutral. Neutral does not mean empty of charge. It means the two kinds are balanced, so the object has no overall charge of its own. An object is positively or negatively charged only when that balance has been broken, which means it now has more of one kind than of the other.` },
    { loId: 'm8sci.electric-forces-and-charge', content: `LIKE CHARGES REPEL, OPPOSITE CHARGES ATTRACT, AND THE FORCE REACHES ACROSS A GAP. Two objects that both carry negative charge push each other apart. Two objects that both carry positive charge push each other apart in exactly the same way. An object with negative charge and an object with positive charge pull toward each other. That is the whole rule. Two things to say about it straight away. First, it runs both ways at once: each of the two objects feels the force, as is true of every force you have met. Second, the objects do not have to be touching. A charged object pushes or pulls on another charged object while there is still air between them, which is why two rubbed balloons start pushing apart before they meet. HOW a push can cross a gap is taken up in a later lesson in this unit; THAT it crosses one is what you need today.` },
    { loId: 'm8sci.electric-forces-and-charge', content: `RUBBING DOES NOT MAKE CHARGE. IT MOVES ELECTRONS FROM ONE OBJECT ONTO THE OTHER. The negative charge in ordinary matter is carried by electrons, tiny particles that sit on the outside of atoms, and some of them are held loosely enough that dragging two surfaces across each other pulls them off one surface and onto the other. Positive charge does not travel between everyday objects that way; it stays fixed in place. So rubbing always charges BOTH objects, and always with opposite kinds: the surface that gained electrons now has extra negative charge, and the surface that lost them is short by exactly that many and is left positive. WRONG: "Rubbing creates negative charge on the balloon." CORRECT: "Rubbing moved electrons from the hair onto the balloon, and the hair is left positive by exactly the amount the balloon gained." Add up the charge on both objects together and it is the same after the rubbing as it was before. Nothing was made and nothing was destroyed. It was moved.` },
    { loId: 'm8sci.electric-forces-and-charge', content: `A CHARGED OBJECT ALSO PULLS ON A NEUTRAL ONE, AND THAT IS THE BALLOON-ON-THE-WALL PUZZLE. A wall nobody has rubbed is neutral, and a rubbed balloon sticks to it anyway. The reason is that the charges in the wall's surface can shift a short way without leaving the wall. Hold a negatively charged balloon close to the surface and the negative charges in it are pushed slightly deeper in, which leaves the part of the surface nearest the balloon slightly positive while the negative charge sits slightly farther back. So the pull on the balloon comes from charges that are NEARER and the push comes from charges that are FARTHER, and the electric force is stronger over a shorter distance -- which means the pull is the bigger of the two and the balloon is attracted. The wall never gains an overall charge. Its charges only rearrange, and they settle back as soon as the balloon is taken away.` },
    { loId: 'm8sci.electric-forces-and-charge', content: `TWO THINGS SET HOW STRONG AN ELECTRIC FORCE IS: HOW MUCH CHARGE, AND HOW FAR APART. Put more charge on either one of the two objects and the force between them gets stronger. Move the two objects farther apart and the force gets weaker; bring them closer and it gets stronger. Both factors are working at the same time, which is why a lightly charged object held very close can pull just as hard as a heavily charged one held far away, and why you cannot judge either factor from a single trial. You already know this shape of rule from the lesson before this one, where gravity grew with the amount and weakened with distance -- but here is the difference that makes this force new: gravity only ever pulls, while an electric force pulls or pushes depending on which kinds of charge are involved.` },
    { loId: 'm8sci.electric-forces-and-charge', content: `HOW TO READ A SET OF TRIALS FOR ITS FACTORS. When you are handed the results of several trials and asked what changes the strength of the force, hunt for a PAIR of trials that differ in exactly one thing. If two trials used the same distance and different amounts of rubbing, that pair tells you what the amount of charge did. If two trials used the same rubbing and different distances, that pair tells you what the distance did. A pair that differs in two things at once tells you nothing about either one, however interesting the two results look side by side, because there is no way to say which of the two changes produced what you are seeing.` },
    { loId: 'm8sci.electric-forces-and-charge', kind: 'definition', title: 'electric charge', content: `a property of matter that comes in two kinds, positive and negative, and that makes objects push or pull on one another.` },
    { loId: 'm8sci.electric-forces-and-charge', kind: 'definition', title: 'neutral', content: `carrying equal amounts of positive and negative charge, and so having no overall charge -- which is not the same as having no charge at all.` },
    { loId: 'm8sci.electric-forces-and-charge', kind: 'definition', title: 'electron', content: `a tiny particle that carries negative charge and sits on the outside of atoms; electrons are what moves when two surfaces are rubbed together.` },
    { loId: 'm8sci.electric-forces-and-charge', kind: 'definition', title: 'electric force', content: `the push or the pull between two charged objects, or between a charged object and a neutral one.` },
    { loId: 'm8sci.electric-forces-and-charge', kind: 'definition', title: 'repel', content: 'to push apart. Two objects carrying the same kind of charge repel each other.' },
    { loId: 'm8sci.electric-forces-and-charge', kind: 'definition', title: 'attract', content: `to pull together. Two objects carrying opposite kinds of charge attract each other, and a charged object also attracts a neutral one.` },
  ],
  methods: [
    {
      title: 'Worked balloon hair and wall',
      steps: [
        `Start with what the rubbing did, and be exact about it, because this is where the student went wrong the first time. Rubbing does not make charge; it moves electrons. Dragging the rubber of the balloon across your hair pulls electrons off the hair and onto the balloon. The balloon therefore ends up with more electrons than it started with, which is an overall negative charge, and your hair ends up short by exactly that many electrons, which is an overall positive charge. Two surfaces were rubbed, so two objects ended up charged, and they got opposite kinds.`,
        `Check that against what your hair is doing, because the hair is evidence you can see. Every single hair lost electrons, so every single hair now carries positive charge -- the same kind as the hair next to it. Like charges repel, so the hairs push one another apart and stand up instead of lying flat. The hair as a whole is pulled toward the balloon at the same time, because positive and negative attract. One transfer, two behaviors, and they are opposite behaviors: apart from each other, toward the balloon.`,
        `Now the wall, which is the part the student got wrong the second time. The wall is neutral. It holds equal amounts of positive and negative charge and nobody has moved any of it. But the charges in the wall's surface can shift a short way in place. The balloon's negative charge pushes the surface electrons a little deeper in, so the surface right under the balloon is left slightly positive while the negative charge sits slightly farther back. The balloon is pulled toward the nearer positive charge and pushed by the farther negative charge, and because the electric force is stronger over a shorter distance, the pull beats the push. That leftover pull presses the balloon against the wall, and friction between the balloon and the wall keeps it from sliding down.`,
        `WRONG: "The balloon charged the wall positive." CORRECT: "The wall still holds equal amounts of both kinds of charge. Its charges shifted a little way in place, and they settle back as soon as the balloon is taken away." Notice what the correct version does not need: in this whole story the wall does not gain or lose a single electron.`,
        `Now run the two checks a science answer needs, because there is no arithmetic here to redo. First, look for clues of DIFFERENT KINDS that agree. The inventory of what was touched says only the balloon and the hair were rubbed, so only those two should have ended up charged, and only those two show any new behavior. The directions agree next, and they agree in opposite senses: the hairs spread APART from one another, which is what like charges do, while the hair as a whole leans TOWARD the balloon, which is what opposite charges do -- one transfer predicting two different motions. And the wall behaves the same everywhere, which is a third kind of clue: peel the balloon off and press it against a fresh spot, and it holds on there too. That is what you would expect if the wall is simply neutral and its charges shift under whatever is brought near them, and not what you would expect if one particular patch had been handed a charge.`,
        `Second, change one thing about the setup and check that the answer moves the way it should. Take an identical balloon that has not been rubbed and press it against the same wall. It falls straight down. Same balloon, same wall, same press against the surface, and no holding on at all -- because no electrons were moved and neither object has an overall charge. The one condition that changed is the rubbing, and the result changed with it, which is exactly what the explanation says should happen.`,
      ],
      example: { problem: `You rub a balloon on your hair for a few seconds. The balloon then holds on to a wall that nobody has touched all day, and your hair is left standing up with single hairs spread apart from one another. A student says: "The balloon made new negative charge, and then it charged the wall positive so that it could stick." Say what charge the balloon, the hair and the wall each end up with, and explain why the balloon stays on the wall.`, solution: `The balloon ends up negatively charged and the hair positively charged, because rubbing moved electrons from the hair onto the balloon; nothing was created, and the two amounts match. The wall stays neutral. The balloon's negative charge shifts the charges in the wall's surface a little way in place, leaving the nearest part of the surface slightly positive, and because the electric force is stronger over a shorter distance the pull from the nearer positive charge beats the push from the farther negative charge. That leftover pull holds the balloon against the wall, and friction keeps it from sliding down.` },
      relatedLoIds: ['m8sci.electric-forces-and-charge'],
    },
    {
      title: 'Worked reading the trials',
      steps: [
        `Be clear about what is being measured before you compare anything. With nothing charged nearby, the ball hangs straight down. A sideways push moves it away from straight down until it settles in a new place, and a harder push settles it farther aside. So the number of centimeters aside is standing in for the strength of the electric force: more centimeters means a stronger push.`,
        `Find a pair of trials that differ in exactly one thing. Trials 1 and 2 were both run with the sphere 5 centimeters from the ball, and the only difference between them is the rubbing -- 10 times against 30 times. More rubbing drags more electrons onto the sphere, so the sphere carries more charge in Trial 2 than in Trial 1. The ball settles 1 centimeter aside in the first and 3 centimeters aside in the second. More charge, stronger force.`,
        `Now find the pair that isolates the other factor. Trials 2 and 3 were both run after 30 rubs, so the amount of charge is the same in both, and the only difference is how far away the sphere was held -- 5 centimeters against 9 centimeters. The ball settles 3 centimeters aside in the nearer trial and 1 centimeter aside in the farther one. Farther apart, weaker force; closer together, stronger force.`,
        `Look at Trials 1 and 3 together, because this is where a reader goes wrong. Both of them ended with the ball 1 centimeter aside, and it is tempting to read that tie as evidence that the rubbing made no difference, or that the distance made no difference. Neither reading is allowed, because those two trials differ in BOTH things at once: Trial 3 had more rubbing AND more distance, and the two changes worked against each other. WRONG: "Trials 1 and 3 gave the same result, so neither factor matters." CORRECT: "Trials 1 and 3 changed two things at once, so on their own they settle nothing. Compare Trial 1 with Trial 2 for the charge, and Trial 2 with Trial 3 for the distance."`,
        `Now run the two checks. First, three clues of DIFFERENT KINDS that agree. The two clean pairs are the first clue, and each moves the way the rule says it should. The direction of the swing is a second and different kind of clue: in every trial the ball moves AWAY from the sphere and never toward it, which is what two objects carrying the same kind of charge do, so the trials are also confirming that both objects are negatively charged. And the third clue is what happens when the sphere is carried out of the room: the ball settles back to hanging straight down, which says the push is there only while the charged sphere is near, and is not something that happened to the ball once and stayed with it.`,
        `Second, change one condition and check that the answer moves. Suppose the sphere had been given positive charge instead of negative, with everything else in the three trials left exactly as it was. Now the ball would settle aside TOWARD the sphere rather than away from it, because opposite charges attract -- and the two factors would still set how far it settled, with more charge moving it farther and more distance moving it less. The kind of charge decides which way; the amount of charge and the distance decide how strongly. Change the kind and the direction flips, which is how you know the direction was coming from the kinds of charge and not from the sphere being nearby at all.`,
      ],
      example: { problem: `A small foam ball hangs on a long thread and has been given negative charge. A plastic sphere on the end of a stick is rubbed until it is negatively charged too, and is then held near the hanging ball. The ball swings aside, away from the sphere, and settles there, and how far it settles aside from hanging straight down is the measure of how hard it is being pushed. Trial 1: the sphere is rubbed 10 times and held 5 centimeters from the ball, and the ball settles 1 centimeter aside. Trial 2: the sphere is rubbed 30 times and held 5 centimeters from the ball, and the ball settles 3 centimeters aside. Trial 3: the sphere is rubbed 30 times and held 9 centimeters from the ball, and the ball settles 1 centimeter aside. What do these trials show about what makes an electric force stronger or weaker?`, solution: `The trials show that the electric force gets stronger when there is more charge on the objects and weaker when the objects are farther apart. Trials 1 and 2 differ only in the rubbing, and the ball settles farther aside after more rubbing. Trials 2 and 3 differ only in the distance, and the ball settles less far aside from farther away. Trials 1 and 3 give the same result but differ in two things at once, so that pair settles nothing by itself.` },
      relatedLoIds: ['m8sci.electric-forces-and-charge'],
    },
  ],
  pointers: [
    { content: `Students often say "Rubbing creates negative charge on the balloon out of nothing." — Rubbing moves charge; it never makes any. Electrons are loose enough to be dragged from one surface onto another, and that is all the rubbing does. So the charge on the balloon is not new charge -- it is negative charge that used to be on your hair. And because it came from somewhere, the other object cannot be left alone: your hair is now short by exactly the electrons the balloon gained, which leaves the hair positively charged. Add the two together and the total is exactly what it was before you started. The hair is the evidence, and you can see it: the single hairs stand apart from one another, which is what like charges do, and the whole head of hair leans toward the balloon, which is what opposite charges do. WRONG: "The rubbing created charge on the balloon." CORRECT: "The rubbing moved electrons from the hair to the balloon, so the balloon went negative and the hair went positive by the same amount."`, kind: 'common-error' },
    { content: `Students often say "The balloon sticks to the wall because it has made the wall positively charged." — The wall is neutral before the balloon arrives and neutral the whole time the balloon is on it. What happens instead is that the charges inside the wall's surface shift a short way in place. The balloon's negative charge pushes the surface electrons slightly deeper in, so the part of the surface nearest the balloon is left slightly positive while the negative charge sits slightly farther back. The balloon is pulled by the nearer positive charge and pushed by the farther negative charge, and the electric force is stronger over a shorter distance, so the pull wins and the balloon is held against the wall. Nothing was handed over: no electron crosses from the balloon to the wall, and the wall's charges settle back the moment the balloon is taken away. The test is easy to run in your head. Peel the balloon off and press it against a fresh spot a meter along the wall, and it holds on there too -- and then at the spot after that. A wall that had been given a charge in one place could not keep doing that everywhere you move the balloon. WRONG: "The balloon charged the wall." CORRECT: "The wall stayed neutral, and its charges only shifted a little way in place, which is enough to make the pull beat the push."`, kind: 'common-error' },
    { content: `Electric charge comes in two kinds, positive and negative. An object with equal amounts of both is neutral, which means balanced, not empty.`, kind: 'tip' },
    { content: `Like charges repel and opposite charges attract, and the push or the pull acts across the gap between the objects without them touching.`, kind: 'tip' },
    { content: `Rubbing never creates charge. It drags electrons from one surface onto the other, so BOTH objects end up charged, with opposite kinds, and the total is unchanged.`, kind: 'tip' },
    { content: `Electrons are what moves between everyday objects. The positive charge stays fixed in place.`, kind: 'tip' },
    { content: `A charged object also attracts a neutral one: the charges in the neutral object shift a little way in place, the opposite kind ends up nearer, and the nearer pull beats the farther push.`, kind: 'tip' },
    { content: `That is why a rubbed balloon holds on to a wall that nobody rubbed, and the wall is still neutral the whole time.`, kind: 'tip' },
    { content: `Two things set how strong an electric force is: how much charge the objects carry, and how far apart they are. More charge is stronger, more distance is weaker.`, kind: 'tip' },
    { content: `To find a factor in a set of trials, compare two trials that differ in exactly one thing. A pair that differs in two things at once settles nothing on its own.`, kind: 'tip' },
    { content: `Neutral does NOT mean empty of charge. It means equal amounts of positive and negative charge balanced out. A neutral object still has plenty of both kinds — they just cancel.`, kind: 'vocab-note' },
    { content: `When you rub, BOTH objects get charged with opposite kinds. Don't say 'the balloon got negative charge.' Say 'electrons moved from the hair to the balloon, so the balloon went negative AND the hair went positive by the same amount.'`, kind: 'common-error' },
    { content: `The wall does NOT get charged when a balloon sticks to it. The wall stays neutral. Its charges just shift a tiny bit in place — nearer charges end up opposite to the balloon, and since electric force is stronger over shorter distances, the pull beats the push.`, kind: 'gotcha' },
    { content: `To find what factor matters in a set of trials, hunt for a PAIR that differs in exactly one thing. A pair that differs in two things tells you nothing — you can't say which change caused which result.`, kind: 'tip' },
    { content: `Electric force pushes or pulls across a gap — the objects don't have to touch. But don't worry about HOW the force crosses the gap yet; just know that it DOES.`, kind: 'edge-case' },
    { content: `A charged object can pull on a neutral one, but electrons do NOT move from the charged object to the neutral one. Only the charges in the neutral object's surface shift a little bit, then settle back when the charged object is taken away.`, kind: 'common-error' },
    { content: `When two rubbed objects end up with opposite charges, they don't 'attract back together' to undo the rubbing. They attract AND they both push on other nearby charged things. One rubbing, two independent charges doing two independent jobs.`, kind: 'gotcha' },
  ],
};
