/**
 * Grade 8 Science — Unit 5 CED 5.3: Mass, Material & Temperature Change.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.mass-material-and-temperature-change.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U5_MASS_MATERIAL_AND_TEMPERATURE_CHANGE: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.mass-material-and-temperature-change.v1',
  course: 'Grade 8 Science',
  cedUnit: 5,
  cedTopic: '5.3',
  cedTitle: 'Mass, Material & Temperature Change',
  planId: 'evelyn.ms.m8sci.mass-material-and-temperature-change.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.mass-material-and-temperature-change.v1' }],
  theory: [
    { loId: 'm8sci.mass-material-and-temperature-change', content: `THREE THINGS DECIDE HOW FAR A TEMPERATURE MOVES. When energy is transferred into a sample and the sample does not change state, how far its temperature climbs depends on exactly three things: how much energy went in, how much mass the sample has, and what the sample is made of. Change any one of the three and you get a different temperature change. Notice those two words, temperature change. What this lesson compares is always the DIFFERENCE between the starting temperature and the ending temperature, never the ending reading on its own. A sample that starts at 10 degrees Celsius and ends at 30 degrees Celsius has changed by 20 degrees Celsius, and so has one that starts at 50 degrees Celsius and ends at 70 degrees Celsius. The last lesson was about the ways thermal energy moves from a warmer thing to a cooler one. This lesson starts the moment it has arrived, and asks how far the temperature moves once it does.` },
    { loId: 'm8sci.mass-material-and-temperature-change', content: `MORE ENERGY IN MEANS A BIGGER TEMPERATURE CHANGE. Hold the sample itself the same -- same material, same mass -- and the temperature change grows with the energy transferred into it. The same heater left on for twice as long puts in about twice as much energy, and the temperature change is about twice as big. This is the one of the three relationships that runs the way everyday experience expects, which is exactly why it is worth saying out loud before the other two, because they do not.` },
    { loId: 'm8sci.mass-material-and-temperature-change', content: `MORE MASS MEANS A SMALLER TEMPERATURE CHANGE, FOR THE SAME ENERGY. Take the same material and put the same energy in, but use twice as much of it, and the temperature climbs only half as far. The reason is in the particles. The arriving energy is shared out among every particle in the sample, so with twice as many particles each one gains, on average, half as much, and the temperature is precisely that average. Now the careful part, and it is the part most people get wrong: the bigger sample did NOT receive less energy. It received the same energy and it gained the same thermal energy. Temperature is an average taken per particle and thermal energy is a total taken over the whole sample, which is the distinction from the earlier lesson, and this is where that distinction earns its keep.` },
    { loId: 'm8sci.mass-material-and-temperature-change', content: `WHAT THE SAMPLE IS MADE OF MATTERS ALL ON ITS OWN. Take two samples of the SAME mass, transfer the SAME energy into each, and their temperatures still do not climb by the same amount, because different materials take different amounts of energy to warm each gram by one degree. Water is the extreme case among everyday materials: a given mass of water takes far more energy to warm by one degree than the same mass of dry sand, dry soil or iron does. That is the main reason the sea beside a beach stays cool through an afternoon in which the dry sand becomes too hot to stand on. And it runs backward too -- a material whose temperature climbs only a little for a given amount of energy going in also falls only a little for the same amount coming back out. This lesson stops at the comparison, more energy per degree or less, and never puts a number on it.` },
    { loId: 'm8sci.mass-material-and-temperature-change', content: `THE ROUTINE FOR READING A SET OF TRIALS. One, write down what was held fixed across the trials and what was changed. Two, for every trial work out the temperature change: ending temperature minus starting temperature. Three, compare those changes with each other, by dividing if the numbers divide cleanly. Four, name the factor. If the mass was the only thing that differed, the difference is evidence about mass; if the material was the only thing that differed, it is evidence about material; if the energy was the only thing that differed, it is evidence about energy. Five, and this step saves you more often than the other four, if MORE THAN ONE thing differed between two trials, stop there. Those trials cannot tell you which of the changes caused the difference, and the honest answer is that the comparison does not settle it.` },
    { loId: 'm8sci.mass-material-and-temperature-change', content: `PLANNING A TRIAL IS THE SAME ROUTINE RUN BACKWARD. Decide which of the three factors you are asking about, then build two trials that differ in that factor and in nothing else. To test mass: same material, same heater, same heating time, two different masses. To test material: same mass, same heater, same heating time, two different materials. To test the energy: same material, same mass, one heater left on longer than the other. Measure every sample before the heater goes on and again when it goes off, so that what you end up holding is a change and not just a final reading. Then run each trial more than once, so a single odd result cannot decide the answer on its own.` },
    { loId: 'm8sci.mass-material-and-temperature-change', kind: 'definition', title: 'temperature change', content: `the ending temperature of a sample minus its starting temperature -- how far the temperature moved, not the reading it finished on.` },
    { loId: 'm8sci.mass-material-and-temperature-change', kind: 'definition', title: 'mass', content: 'the amount of matter in a sample, measured in grams or kilograms.' },
    { loId: 'm8sci.mass-material-and-temperature-change', kind: 'definition', title: 'energy transferred', content: `the energy that moves into a sample from something warmer, such as a heater; the same heater left on for the same time transfers about the same energy every trial.` },
    { loId: 'm8sci.mass-material-and-temperature-change', kind: 'definition', title: 'material', content: `what a sample is made of -- water, iron, sand -- as opposed to how much of it there is.` },
    { loId: 'm8sci.mass-material-and-temperature-change', kind: 'definition', title: 'thermal energy', content: `the total energy of the motion of all a sample's particles. A total, not an average, which is how it differs from temperature.` },
    { loId: 'm8sci.mass-material-and-temperature-change', kind: 'definition', title: 'held fixed', content: `kept deliberately the same in every trial, so that it cannot be the cause of any difference between them.` },
  ],
  methods: [
    {
      title: 'Worked two masses of water',
      steps: [
        `Step 1, name what was held fixed and what was changed. Held fixed: the material (water in both), the starting temperature (20 degrees Celsius in both), the heater (identical), and the heating time (2 minutes in both). Identical heaters left on for the same time transfer about the same energy, so the energy transferred in was held fixed as well. Changed: the mass, 100 grams in Trial 1 and 200 grams in Trial 2. Exactly one thing changed, and that is what makes this pair of trials worth reading at all.`,
        `Step 2, work out each temperature change. Trial 1: 40 degrees Celsius minus 20 degrees Celsius is a change of 20 degrees Celsius. Trial 2: 30 degrees Celsius minus 20 degrees Celsius is a change of 10 degrees Celsius. Compare the changes and not the final readings. Here both samples happened to start at the same temperature, so the two comparisons agree, but they will not always agree, and the change is the honest one.`,
        `Step 3, compare and name the factor. The mass doubled, from 100 grams to 200 grams, and the temperature change halved, from 20 degrees Celsius to 10 degrees Celsius: 200 divided by 100 is 2, and 20 divided by 10 is 2. Mass was the only thing that changed, so mass is what the difference is evidence about, and the pattern is an inverse one -- more mass, less temperature change, for the same energy.`,
        `Step 4, say WHY, in the particle picture. The same energy arrived in both samples. In Trial 2 that energy was shared among twice as many water particles, so each particle gained on average half as much, and the temperature is exactly that average. WRONG: "The 200-gram sample ended cooler, so less energy went into it." CORRECT: "The same energy went into it, and it gained the same thermal energy as the 100-gram sample. That energy simply had twice as much water to spread through, so the average per particle -- which is the temperature -- moved half as far."`,
        `Now run the two checks a science answer needs, because there is very little arithmetic here to redo. First, look for clues of DIFFERENT KINDS that agree. The design of the trials says mass was the only thing free to differ, so mass is the only candidate. The particle picture predicted the result before anyone read the data: one helping of energy split among twice as many particles gives half the average gain. And a rule from an earlier lesson agrees from a third direction: the 200-gram sample gained the same thermal energy while showing half the temperature change, which is exactly what has to happen if temperature is an average and thermal energy is a total. The trial design, the mechanism, and a rule from elsewhere -- three different kinds of evidence, one answer.`,
        `Second, change one condition and check that the answer moves the way it should. Leave the identical heater on the 200-gram sample for 4 minutes instead of 2. That is twice as long, so about twice as much energy goes in, and the temperature change doubles from 10 degrees Celsius to 20 degrees Celsius: the water ends at 40 degrees Celsius, which is exactly where the 100-gram sample finished in half the time. The mass did not change, so the mass explanation is untouched. What moved was the energy, and the answer moved with it in the direction the second key idea says it should. If the 200-gram sample had somehow been unable to warm, extra time could not have rescued it.`,
      ],
      example: { problem: `Two trials use water and two identical electric heaters. Trial 1: 100 grams of water, starting at 20 degrees Celsius, with the heater switched on for 2 minutes. The water ends at 40 degrees Celsius. Trial 2: 200 grams of water, also starting at 20 degrees Celsius, with an identical heater switched on for the same 2 minutes. That water ends at 30 degrees Celsius. Neither sample boils or changes state. What do these two trials show, and why did the second one end cooler?`, solution: `They show that for the same material, the same starting temperature and the same energy transferred in, doubling the mass halves the temperature change: a change of 20 degrees Celsius for 100 grams, and 10 degrees Celsius for 200 grams. The second sample did not end cooler because less energy reached it. It received the same energy and gained the same thermal energy; that energy was shared among twice as many water particles, so the average energy per particle -- which is what a temperature measures -- climbed only half as far.` },
      relatedLoIds: ['m8sci.mass-material-and-temperature-change'],
    },
    {
      title: 'Worked two liquids and a plan',
      steps: [
        `Step 1, held fixed and changed. Held fixed: the mass (100 grams each), the starting temperature (20 degrees Celsius each), the heater, and the heating time, so the energy transferred in was the same in both. Changed: the material, Liquid P in one trial and Liquid Q in the other. One thing changed, so the trials are readable.`,
        `Step 2, the temperature changes. Liquid P: 32 degrees Celsius minus 20 degrees Celsius is a change of 12 degrees Celsius. Liquid Q: 56 degrees Celsius minus 20 degrees Celsius is a change of 36 degrees Celsius. Step 3, compare them: 36 divided by 12 is 3, so Liquid Q's temperature climbed three times as far as Liquid P's did.`,
        `Step 4, name the factor and say what it means. Mass and energy were held fixed, so the material is the only candidate left, and the difference is evidence about the material. Now turn the comparison around, because that is the useful way to hold it: to move the same 100 grams by one degree, Liquid P needs about three times as much energy as Liquid Q does. Some materials take a lot of energy for each degree and some take very little, and that is a property of the material itself rather than of how much of it you have. WRONG: "Liquid Q ended hotter, so Liquid Q was given more energy." CORRECT: "Identical heaters ran for the same 3 minutes, so both were given about the same energy. Liquid Q's temperature simply travels farther on it."`,
        `Now the plan. The question is whether the MASS of Liquid Q changes how far its temperature climbs, so mass is the one thing to change and everything else is held fixed: Liquid Q in both trials, the same starting temperature, the same heater, the same heating time. Use 100 grams in one trial and 200 grams in the other. Take each sample's temperature before the heater goes on and again when it goes off, and subtract to get each change. Run the pair more than once. If the 200-gram trial shows about half the change of the 100-gram trial, the answer is yes, and the mass is the reason.`,
        `Run the two checks. First, three clues of DIFFERENT KINDS agree that the difference belongs to the material. The design of the trials leaves nothing else free to vary. The everyday world shows the same pattern: a given mass of water takes far more energy to warm by one degree than the same mass of dry sand does, which is the main reason the sea beside a beach stays cool through an afternoon in which the dry sand becomes too hot to stand on. And the pattern runs backward as well as forward -- a material that climbs only a little for a given amount of energy going in also falls only a little for the same amount coming back out, which is why that same sea is barely cooler at dawn while the sand that was scorching has gone cold.`,
        `Second, change one condition and check that the answer moves. Run Liquid Q again with its heater on for 1 minute instead of 3. One third of the time is about one third of the energy, so Liquid Q's temperature change falls from 36 degrees Celsius to 12 degrees Celsius -- which is exactly what Liquid P did in 3 minutes. Put those two trials side by side on their own and the two liquids look identical, and that would be the wrong conclusion. Nothing about either liquid changed. What changed is that the energy stopped being held fixed. That is the whole reason the routine begins by listing what was held fixed, and the reason a comparison that lets two things change cannot be repaired afterwards.`,
      ],
      example: { problem: `Two trials use two different liquids, Liquid P and Liquid Q, and two identical electric heaters. Trial 1: 100 grams of Liquid P, starting at 20 degrees Celsius, heater on for 3 minutes. It ends at 32 degrees Celsius. Trial 2: 100 grams of Liquid Q, also starting at 20 degrees Celsius, an identical heater on for the same 3 minutes. It ends at 56 degrees Celsius. Neither liquid boils or changes state at any point. What do these trials show? Then plan a trial that would find out whether the MASS of Liquid Q changes how far its temperature climbs.`, solution: `They show that what a sample is made of changes how far its temperature climbs all on its own, separately from mass and from energy: with the mass and the energy held fixed, Liquid Q changed by 36 degrees Celsius while Liquid P changed by 12 degrees Celsius, so Liquid P takes about three times as much energy as Liquid Q to warm the same mass by one degree. To test whether the mass of Liquid Q matters, keep the liquid, the starting temperature, the heater and the heating time the same and change only the mass -- 100 grams in one trial and 200 grams in the other -- measuring each sample before and after and comparing the two temperature changes.` },
      relatedLoIds: ['m8sci.mass-material-and-temperature-change'],
    },
  ],
  pointers: [
    { content: `Students often say "The 200-gram sample only warmed by 10 degrees Celsius, so it must have been given less energy." — Identical heaters left on for the same 2 minutes transfer about the same energy, so the same energy went into both samples and both gained the same amount of thermal energy. What differs is how far that energy moved the temperature. Temperature is an average taken per particle; thermal energy is a total taken over the whole sample. The 200-gram sample has twice as many particles sharing the same arriving energy, so each particle gains on average half as much and the average -- the temperature -- climbs half as far. WRONG: "It warmed less, so it was given less energy." CORRECT: "It was given the same energy and gained the same thermal energy, and that energy had twice as much water to spread through."`, kind: 'common-error' },
    { content: `Students often say "Sample R finished at 40 degrees Celsius and Sample S finished at 48 degrees Celsius, so Sample S is the one whose temperature moved further." — A final reading depends on where the sample started as well as on how far it moved, so it cannot be compared until you subtract. Suppose Sample R started at 10 degrees Celsius and finished at 40 degrees Celsius: its temperature changed by 30 degrees Celsius. Suppose Sample S started at 30 degrees Celsius and finished at 48 degrees Celsius: its temperature changed by 18 degrees Celsius. Sample R moved further, not Sample S, even though Sample S finished on the higher number. Always subtract the starting temperature from the ending temperature, for every trial, before any comparison is made. WRONG: "Sample S finished higher, so Sample S moved further." CORRECT: "Sample R changed by 30 degrees Celsius and Sample S by 18 degrees Celsius, so Sample R moved further, even though Sample S finished on the higher reading."`, kind: 'common-error' },
    { content: `How far a sample's temperature changes depends on three things at once: how much energy was transferred into it, how much mass it has, and what it is made of.`, kind: 'tip' },
    { content: `Always work with the temperature CHANGE -- ending temperature minus starting temperature -- and never with the final reading on its own.`, kind: 'tip' },
    { content: `More energy in, for the same sample, means a bigger temperature change. The same heater on for twice as long is about twice the energy and about twice the change.`, kind: 'tip' },
    { content: `More mass, for the same energy and the same material, means a SMALLER temperature change. The energy is shared among more particles, so the average gain per particle -- the temperature -- is smaller.`, kind: 'tip' },
    { content: `The bigger sample was not given less energy. It was given the same energy and gained the same thermal energy. Temperature is an average taken per particle; thermal energy is a total taken over the sample.`, kind: 'tip' },
    { content: `Two samples of the same mass given the same energy still change by different amounts when they are made of different materials. A given mass of water takes far more energy to warm by one degree than the same mass of dry sand does.`, kind: 'tip' },
    { content: `To read a set of trials: list what was held fixed and what was changed, subtract to get every temperature change, compare them, and name the factor. If more than one thing changed, the comparison settles nothing.`, kind: 'tip' },
    { content: `To plan a trial: change only the factor you are asking about, hold the other two fixed, measure before and after, and run it more than once.`, kind: 'tip' },
  ],
};
