/**
 * Grade 8 Science — Unit 6 CED 6.1: The Particle Model & States of Matter.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.the-particle-model-and-states-of-matter.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U6_THE_PARTICLE_MODEL_AND_STATES_OF_MATTER: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.the-particle-model-and-states-of-matter.v1',
  course: 'Grade 8 Science',
  cedUnit: 6,
  cedTopic: '6.1',
  cedTitle: 'The Particle Model & States of Matter',
  planId: 'evelyn.ms.m8sci.the-particle-model-and-states-of-matter.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.the-particle-model-and-states-of-matter.v1' }],
  theory: [
    { loId: 'm8sci.the-particle-model-and-states-of-matter', content: `ALL MATTER IS MADE OF PARTICLES FAR TOO SMALL TO SEE, AND THEY NEVER STOP MOVING. A sample of anything -- a coin, the water in a glass, the air in a sealed jar -- is built from enormous numbers of tiny particles, and every one of them is moving all the time. The particles also pull on one another: bring two of them close together and there is an attraction between them. Three questions about those particles decide everything a substance does. How far apart are they? How strongly do the pulls hold them? How freely can they move? One thing never changes, whatever state the substance is in, and it is the thing people get wrong first. WRONG: "A sample takes up more space because its particles got bigger." CORRECT: "The particles stay exactly the same. What changes is how far apart they are and how they are arranged." A single particle is not hard, not runny and not squashy; those words describe what countless particles do together.` },
    { loId: 'm8sci.the-particle-model-and-states-of-matter', content: `IN A SOLID THE PARTICLES ARE PACKED CLOSE AND EACH ONE KEEPS THE SAME NEIGHBORS. The particles of a solid are touching, with almost no space left between them, and the pulls between them are strong enough to hold every particle in one position. Held in place is not the same as stopped: each particle vibrates, shaking back and forth about its own fixed spot without ever leaving it. That one picture gives a solid all three of its everyday properties. It keeps its own shape, because no particle can travel to a new position. It keeps the same volume, because the particles are already touching. And pushing on it barely changes its volume at all, because there is almost no empty space in it to push out. WRONG: "The particles in a solid are completely still." CORRECT: "The particles in a solid vibrate in place; they are held to their positions, not stopped."` },
    { loId: 'm8sci.the-particle-model-and-states-of-matter', content: `IN A LIQUID THE PARTICLES ARE STILL TOUCHING, BUT THEY CAN CHANGE NEIGHBORS. The particles of a liquid are almost as close together as a solid's -- still touching, with very little space between them -- but the pulls, while strong enough to hold the particles together as one body, are not strong enough to hold each particle in a fixed position. So the particles slide past one another and swap neighbors constantly while staying in contact. Read the three properties straight off that. A liquid keeps the same volume, because its particles are still touching. It has no shape of its own and takes the shape of whatever holds it, because its particles are free to move to new positions. And it barely squashes, for exactly the reason a solid does not: there is almost no empty space between the particles to take out.` },
    { loId: 'm8sci.the-particle-model-and-states-of-matter', content: `IN A GAS THE PARTICLES ARE FAR APART, AND WHAT IS BETWEEN THEM IS NOTHING AT ALL. The particles of a gas are separated by distances many times their own size, and they move quickly, traveling in straight lines until they collide with each other or with the walls of whatever holds them and set off in a new direction. The pulls between them still exist, but across those distances, at those speeds, they are far too weak to hold the particles together. So a gas has no shape of its own and no volume of its own: its particles keep colliding and changing direction until they are spread through the whole container, however large it is. And a gas squashes easily, because the space between its particles is empty space, and moving the particles closer together takes nothing out of the way. WRONG: "The gaps between the particles of a gas are filled with air." CORRECT: "The gaps are empty. Air is itself a gas, made of its own particles with empty space between them."` },
    { loId: 'm8sci.the-particle-model-and-states-of-matter', content: `HOW TO ANSWER ANY QUESTION ABOUT A STATE: THREE QUESTIONS, IN ORDER. First, are the particles touching? If they are, the sample keeps the same volume when you move it to a different container, and it barely squashes. If they are not, it has no volume of its own: it spreads through its container, and it squashes easily. Second, does each particle keep the same neighbors? If it does, the sample keeps its own shape. If it does not, the sample flows and takes the shape of its container. Third, put the two answers together. Touching and fixed neighbors is a solid. Touching and free to change neighbors is a liquid. Far apart and free is a gas. Anything that flows -- a liquid or a gas -- is called a fluid, and both flow for the same single reason: no particle is locked to its neighbors.` },
    { loId: 'm8sci.the-particle-model-and-states-of-matter', content: `AN ANALOGY, AND WHERE IT BREAKS. Picture a crowded school hallway. In the solid version the hallway is so packed that everybody is shoulder to shoulder and nobody can get past anybody, though everyone is shifting their weight on the spot. In the liquid version the crowd is just as packed, but people are sliding past each other and standing beside different people every few seconds. In the gas version a handful of people are loose in an enormous empty gym, crossing it in straight lines and changing direction only when they bump into somebody or into a wall. The analogy is worth having, and here is its limit, which matters as much as the analogy does: people choose where to go, get tired, and stop. Particles do none of that. They do not decide, they do not aim at anything, and they never run down and stop on their own.` },
    { loId: 'm8sci.the-particle-model-and-states-of-matter', kind: 'definition', title: 'particle model', content: `the idea that all matter is made of extremely small particles that are always moving and that pull on one another.` },
    { loId: 'm8sci.the-particle-model-and-states-of-matter', kind: 'definition', title: 'attraction', content: `the pull between two particles that are close together; it is what holds a solid or a liquid together as one body.` },
    { loId: 'm8sci.the-particle-model-and-states-of-matter', kind: 'definition', title: 'vibrate', content: `to shake back and forth about one fixed position without leaving it, which is what the particles of a solid do.` },
    { loId: 'm8sci.the-particle-model-and-states-of-matter', kind: 'definition', title: 'volume', content: `the amount of space a sample of matter takes up, measured in units such as cubic centimeters.` },
    { loId: 'm8sci.the-particle-model-and-states-of-matter', kind: 'definition', title: 'fluid', content: 'anything that flows and takes the shape of its container: a liquid or a gas.' },
    { loId: 'm8sci.the-particle-model-and-states-of-matter', kind: 'definition', title: 'compress', content: `to push a sample into a smaller volume. A gas compresses easily because the space between its particles is empty; a solid or a liquid barely compresses at all.` },
  ],
  methods: [
    {
      title: 'Worked are solid particles still',
      steps: [
        `Take the part that is right first, because there is one. A gas really does have particles that move freely all through their container, and that freedom is why a sealed box of gas ends up with gas everywhere in it. Movement is genuinely part of the story, so the student is not starting from nowhere.`,
        `Now the part that is wrong, and it is the load-bearing one: the particles of a solid are not still. Every particle in the steel bolt is vibrating -- shaking back and forth about a fixed position -- the whole time the bolt sits on the table. There is a clean argument for that, and it does not need a microscope. You already know from the earlier lesson that temperature is a measure of the average kinetic energy of a sample's particles, and kinetic energy is the energy of motion. The bolt has a temperature. So its particles have energy of motion, so they are moving. WRONG: "The particles in a solid are completely still." CORRECT: "The particles in a solid vibrate about fixed positions; they are held in place, not stopped."`,
        `The second thing wrong is bigger than a detail: movement on its own does not sort the three states, because the particles are moving in all three. What sorts them is a pair of questions the student's account never asks. Are the particles touching? And can each particle travel to a new position and change neighbors? In the bolt the particles are touching AND each one keeps the same neighbors, so no part of the bolt can shift its place relative to the rest -- and that is exactly what having a shape of its own means. In the gas the particles are far apart AND free, so no part of the gas holds its place relative to any other part, and the gas has no shape of its own.`,
        `Say the repair in the student's own terms. It is not movement that changes from state to state; it is freedom. A particle in a solid moves without going anywhere. A particle in a liquid goes somewhere, but stays in contact with neighbors the whole way. A particle in a gas goes anywhere its container allows.`,
        `Now run the two checks a science answer needs, because there is no arithmetic here to redo. First, three clues of DIFFERENT KINDS that agree that the bolt's particles are held in position rather than stopped. The shape evidence: the bolt keeps its own shape however you turn it, which needs fixed positions and says nothing at all about being still. The temperature evidence: the bolt has a temperature, and temperature is the average energy of motion of its particles, so they cannot all be at rest. The squashing evidence: pushing hard on the bolt barely changes its volume, which tells you the particles are already touching -- a third fact again, about spacing rather than about motion or position. Three different kinds of evidence, and together they say "touching, and held in position", which is not the same claim as "still".`,
        `Second, change exactly one thing and check that the answer moves. Put the same bolt in a much larger sealed box: nothing happens. Same shape, same volume, and it stays in the one spot you set it down in. Put the gas in that same much larger sealed box and it spreads until it is everywhere inside it. One change of container, two different answers -- and the difference is not how fast anything is moving, it is whether the particles are free to leave their neighbors. If the student were right, and the difference between the states were simply more movement, then the bolt in the big box should at least spread out a little. It does not spread at all.`,
      ],
      example: { problem: `A student writes: "The three states are really about movement. In a solid the particles are completely still. In a liquid they have started to move. In a gas they are moving." Say what is right in that account and what is wrong. Then give the correct reason a steel bolt keeps its own shape while a gas sealed in a box does not.`, solution: `The student is right that a gas has freely moving particles, and wrong twice. First, the particles in a solid are not still: they vibrate about fixed positions, which is why the bolt has a temperature at all. Second, movement does not separate the three states, because the particles move in all three; what separates them is whether the particles are touching and whether each particle can change neighbors. The steel bolt keeps its own shape because its particles are touching and each is held to the same neighbors. The gas in the box does not, because its particles are far apart and free to move anywhere in the box.` },
      relatedLoIds: ['m8sci.the-particle-model-and-states-of-matter'],
    },
    {
      title: 'Worked two sealed syringes',
      steps: [
        `Step one, ask the question that decides squashing: is there empty space between the particles? Everything here turns on that one question, because pushing a sample into a smaller volume means taking space out of it, and the only space that can be taken out is space that was empty in the first place.`,
        `Step two, the air. Air is a gas, so its particles are far apart, separated by distances many times their own size, with nothing in between. Pushing the plunger moves those particles closer together into space that was empty, and there is a great deal of it to use, so the plunger travels a long way. Put the numbers on it: the air goes from 60 cubic centimeters to 20 cubic centimeters, and 60 cubic centimeters divided by 20 cubic centimeters is 3, so the same air now fills one third of the volume it started in. Sixty cubic centimeters minus 20 cubic centimeters leaves 40 cubic centimeters, and every bit of that 40 cubic centimeters was empty space, not particles.`,
        `Step three, the water. Water is a liquid, so its particles are already touching, with very little space between them. There is almost nothing empty to take out, so however hard you push, the volume changes far too little to see. That is not the plunger being stuck and it is not the water being strong. It is that the particles have nowhere left to go.`,
        `Step four, kill the wrong account of the air, because it is the one most people reach for. WRONG: "The air squashed because each air particle was squeezed smaller." CORRECT: "Not one particle changed. The particles were pushed closer together, and it is the empty space between them that got smaller." The spring-back is what settles it: let the plunger go and the air is back in all 60 cubic centimeters, exactly as it began. Nothing about the particles was altered by the push, or the air could not simply return to the volume it started in. The only thing that changed, and then changed back, is how far apart the particles were.`,
        `Now the two checks. First, three clues of DIFFERENT KINDS that agree the difference is empty space and not something about the push. The two syringes got the same push from the same hand and only one gave way, so the push is not what separated them. The air returned to its full 60 cubic centimeters the moment the plunger was released, which says the particles are unchanged and only their spacing moved. And the two substances differ in exactly the property the model says should matter -- a gas has empty space between its particles and a liquid does not -- which is the same property that already explained something else about them, that a gas spreads through a container and a liquid does not. Three different kinds of evidence, one answer.`,
        `Second, change exactly one thing and watch the answer move. Replace the water with a solid metal rod machined to fill the barrel and push again: the plunger does not move, and for the same reason as the water, because those particles are touching too. Then go the other way and seal only 20 cubic centimeters of air in the barrel to start with. The same hard push still moves the plunger, but through a much shorter distance, because there was less empty space between the particles to take out. The answer moves whenever the amount of empty space moves, and that is what makes the empty space the cause.`,
      ],
      example: { problem: `Two identical sealed syringes lie side by side, each with its tip plugged so that nothing can get in or out. The first holds 60 cubic centimeters of air and nothing else. The second holds 60 cubic centimeters of water and nothing else. You push each plunger as hard as you can. In the air syringe the plunger slides in until the air fills only 20 cubic centimeters, and when you let go it springs back out to 60 cubic centimeters. In the water syringe the plunger does not visibly move at all. Explain both results with the particle model.`, solution: `Both results come from one question: is there empty space between the particles? The air is a gas, its particles are far apart with empty space between them, and pushing moves them closer together into that space, so the volume falls from 60 cubic centimeters to 20 cubic centimeters -- one third of what it was. The water is a liquid, its particles are already touching, so there is almost no empty space to remove and the volume barely changes however hard you push. In neither syringe did a single particle change size; only the spacing between particles changed, which is why letting go returns the air to 60 cubic centimeters.` },
      relatedLoIds: ['m8sci.the-particle-model-and-states-of-matter'],
    },
  ],
  pointers: [
    { content: `Students often say "In a gas the particles float around in the air that fills the gaps between them." — There is nothing at all between the particles of a gas. Air is not a background that other things sit inside; air is itself a gas, made of its own particles with empty space between them, so filling the gaps with air would only raise the same question again about the gaps between the air particles. This matters because it is the reason a gas squashes and a liquid does not. Push on a sealed sample of gas and the particles move closer together into space that was empty, and the volume falls a long way; push on a sealed sample of liquid, whose particles are already touching, and almost nothing happens. WRONG: "The gaps between the particles of a gas are filled with air." CORRECT: "The gaps are empty, and the emptiness is exactly what makes a gas easy to squash."`, kind: 'common-error' },
    { content: `Students often say "The three states are made of three different kinds of particle: hard grains, runny ones, wispy ones." — A particle of a substance is the same particle whether that substance is a solid, a liquid or a gas, and a single particle is not hard, not runny and not wispy. Hardness, runniness and wispiness are properties of a whole sample with countless particles in it, and they come from the ARRANGEMENT: how far apart the particles sit, how strongly the pulls between them hold, and whether each particle keeps the same neighbors. A solid is hard because its particles are touching and each is held in one position, not because the particles are little pebbles. A gas is wispy because its particles are far apart with empty space between them, not because the particles are light and thin. WRONG: "A gas is made of wispy particles." CORRECT: "A gas is made of ordinary particles that happen to be far apart and moving freely."`, kind: 'common-error' },
    { content: `All matter is made of particles far too small to see. They are always moving, and they pull on one another.`, kind: 'tip' },
    { content: `Three things decide the state: how far apart the particles are, how strongly the pulls hold them, and how freely they can move.`, kind: 'tip' },
    { content: `Solid: particles touching, each held in one position, vibrating in place. Fixed shape, fixed volume, barely squashes.`, kind: 'tip' },
    { content: `Liquid: particles touching but free to slide past one another and change neighbors. Fixed volume, takes the shape of its container, barely squashes.`, kind: 'tip' },
    { content: `Gas: particles far apart with empty space between them, traveling in straight lines until they collide. No fixed shape, no fixed volume, spreads through its container, squashes easily.`, kind: 'tip' },
    { content: `The particles in a solid are held in place, not stopped. Every state has moving particles; what changes between the states is how free those particles are.`, kind: 'tip' },
    { content: `The particles themselves never grow, shrink or change. When a sample takes up more or less space, it is the spacing between the particles that changed.`, kind: 'tip' },
    { content: `What is between the particles of a gas is nothing at all -- not air. That empty space is why a gas can be pushed into a much smaller volume and a liquid cannot.`, kind: 'tip' },
    { content: `To work out any state question: ask whether the particles are touching, which settles the volume and the squashing, then ask whether each keeps the same neighbors, which settles the shape.`, kind: 'tip' },
  ],
};
