/**
 * Grade 8 Science — Unit 4 CED 4.1: Kinetic Energy: Mass & Speed.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.kinetic-energy-mass-and-speed.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U4_KINETIC_ENERGY_MASS_AND_SPEED: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.kinetic-energy-mass-and-speed.v1',
  course: 'Grade 8 Science',
  cedUnit: 4,
  cedTopic: '4.1',
  cedTitle: 'Kinetic Energy: Mass & Speed',
  planId: 'evelyn.ms.m8sci.kinetic-energy-mass-and-speed.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.kinetic-energy-mass-and-speed.v1' }],
  theory: [
    { loId: 'm8sci.kinetic-energy-mass-and-speed', content: `KINETIC ENERGY IS THE ENERGY AN OBJECT HAS BECAUSE IT IS MOVING. Anything that is moving has some: a rolling ball, a falling raindrop, a bus, a thrown stone. Anything that is not moving has none of it at all -- a parked bus has zero kinetic energy, however many kilograms are sitting there. Two things, and only two things, decide how much kinetic energy a moving object has: how much MASS is moving, measured in kilograms, and how FAST it is going, measured in meters per second. Nothing else on the object decides it -- not the color, not the shape, not what it is made of, not which direction it happens to be heading. Change one of those two things and the kinetic energy changes. Change neither, and it does not.` },
    { loId: 'm8sci.kinetic-energy-mass-and-speed', content: `THE MASS RULE: THE ENERGY GROWS BY THE SAME FACTOR THE MASS GROWS BY. Hold the speed still and change only the mass. Double the mass and you double the kinetic energy. Triple the mass and you triple it. Halve the mass and you halve it. This is the rule people already expect, and it is the easy one of the two. A tennis ball and a hollow plastic wiffle ball thrown at exactly the same speed are the clearest case: the tennis ball has more mass, so at that one shared speed it carries more kinetic energy, and that is why one of them stings when it hits you and the other one does not.` },
    { loId: 'm8sci.kinetic-energy-mass-and-speed', content: `THE SPEED RULE: THE ENERGY GROWS BY THE SPEED FACTOR MULTIPLIED BY ITSELF. Hold the mass still and change only the speed. Double the speed and the kinetic energy does not double -- it becomes FOUR times as large, because the factor 2 is multiplied by itself and 2 times 2 is 4. Triple the speed and the energy becomes nine times as large, because 3 times 3 is 9. Halve the speed and it drops to a quarter, because half of a half is a quarter. Riding a bike at 4 meters per second instead of 2 meters per second is twice the speed on the same bike with the same rider, and four times the kinetic energy. The short name for this is that kinetic energy grows with the SQUARE of the speed, and "squared" means exactly that and nothing more: the factor multiplied by itself.` },
    { loId: 'm8sci.kinetic-energy-mass-and-speed', content: `THE ROUTINE FOR READING A RECORD OF TRIALS, IN ORDER. (1) Take the trials one at a time and write down what each one gives you: the mass with its unit in kilograms, the speed with its unit in meters per second, and how that trial's kinetic energy compares with the trial you are using as the baseline. (2) Find two trials that differ in ONE thing only -- the same speed with different masses, or the same mass with different speeds. A pair that differs in two things at once tells you nothing about either one on its own, however tempting the pair looks. (3) Compare that one thing by HOW MANY TIMES. Ask how many of the smaller amount fit into the larger amount, which is a division; do not ask what the difference is, which is a subtraction. (4) Apply the matching rule: for a mass pair the energy factor equals the mass factor, and for a speed pair the energy factor is the speed factor multiplied by itself. If both the mass and the speed changed, work the two factors out separately and then multiply them together.` },
    { loId: 'm8sci.kinetic-energy-mass-and-speed', content: `THE TRAP IS SUBTRACTING WHEN YOU SHOULD BE DIVIDING, AND IT HIDES INSIDE ORDINARY LANGUAGE. "It went from 5 meters per second to 20 meters per second, so the speed went up by 15 meters per second" is a true sentence about the difference and a useless one here, because a difference cannot be turned into an energy comparison at all. The useful sentence is "20 meters per second is four times 5 meters per second", and four times the speed gives four times four, which is sixteen times the energy. WRONG: "The speed rose by 15 meters per second, so the kinetic energy is 15 times as large." CORRECT: "The speed is 4 times as large, so the kinetic energy is 4 times 4, which is 16 times as large." The second trap is smaller and runs the other way: do not multiply the MASS factor by itself. Double the mass is double the energy, not four times it. Only the speed gets squared, and the whole of this lesson lives in that difference.` },
    { loId: 'm8sci.kinetic-energy-mass-and-speed', kind: 'definition', title: 'kinetic energy', content: `the energy an object has because it is moving. An object that is standing still has none of it, whatever its mass.` },
    { loId: 'm8sci.kinetic-energy-mass-and-speed', kind: 'definition', title: 'mass', content: 'the amount of matter in an object, measured in kilograms.' },
    { loId: 'm8sci.kinetic-energy-mass-and-speed', kind: 'definition', title: 'speed', content: `how far an object travels in each second of its motion, measured in meters per second.` },
    { loId: 'm8sci.kinetic-energy-mass-and-speed', kind: 'definition', title: 'factor', content: `the number of times one amount fits into another. You find a factor by dividing the larger amount by the smaller one, never by subtracting.` },
    { loId: 'm8sci.kinetic-energy-mass-and-speed', kind: 'definition', title: 'squared', content: `multiplied by itself. Two squared is 2 times 2, which is 4; three squared is 3 times 3, which is 9.` },
  ],
  methods: [
    {
      title: 'Worked four trial record',
      steps: [
        `Step 1, take the trials one at a time and write down what each one gives you. Trial 1: a mass of 2 kilograms, a speed of 3 meters per second, and the energy that everything else is measured against. Trial 2: a mass of 4 kilograms, a speed of 3 meters per second, twice the energy. Trial 3: a mass of 2 kilograms, a speed of 6 meters per second, four times the energy. Trial 4: a mass of 6 kilograms, a speed of 3 meters per second, three times the energy. Three of the four runs share a speed of 3 meters per second, and two of them share a mass of 2 kilograms, so there are usable pairs sitting in this record.`,
        `Step 2, find the pairs that differ in one thing only, and do the mass first. Trials 1, 2 and 4 all pass the end at 3 meters per second, so across those three the speed is held still and only the mass moves. Trial 1 against Trial 2: the mass goes from 2 kilograms to 4 kilograms, and 4 divided by 2 is 2, so the mass is twice as large -- and the energy went from the baseline to twice the baseline. Same factor. Trial 1 against Trial 4: the mass goes from 2 kilograms to 6 kilograms, and 6 divided by 2 is 3, so the mass is three times as large, and the energy is three times as large. Same factor again. Two separate pairs, one rule: with the speed held still, the kinetic energy grows by exactly the factor the mass grows by.`,
        `Step 3, now the speed, using the pair that holds the mass still. Trials 1 and 3 both use a mass of 2 kilograms, so this time only the speed moves. The speed goes from 3 meters per second to 6 meters per second, and 6 divided by 3 is 2, so the speed is twice as large. But the energy is four times as large, not twice. The energy factor is not the speed factor; it is the speed factor multiplied by itself, and 2 times 2 is 4. That is the whole surprise of this lesson, and it is sitting in one row of this record.`,
        `Step 4, say the two rules back in the same shape, because they are not the same shape. Mass: the factor goes straight through, so 3 times the mass gives 3 times the energy. Speed: the factor is multiplied by itself, so 2 times the speed gives 2 times 2, which is 4 times the energy. WRONG: "From Trial 1 to Trial 3 the speed rose by 3 meters per second while the energy rose to four times the baseline, so the two numbers do not line up at all." CORRECT: "From Trial 1 to Trial 3 the speed is 2 times as large, and 2 times 2 is 4, which is exactly the energy factor." The rise of 3 meters per second is a true number and it is the wrong number to reach for. Every comparison in this lesson is a division, never a subtraction.`,
        `Now run the two checks a science answer needs, because there is no single calculation here to redo. First, look for clues of DIFFERENT KINDS that agree. The first clue is the paired-row comparison itself: two separate mass pairs, 2 kilograms against 4 kilograms and 2 kilograms against 6 kilograms, each give an energy factor equal to the mass factor, so the result does not depend on which pair you happened to pick. The second clue is a pair that does not involve the baseline at all: compare Trial 4 with Trial 2, both at 3 meters per second, where the mass goes from 4 kilograms to 6 kilograms. 6 divided by 4 is 1.5, and the energies are three times and twice the baseline, and 3 divided by 2 is also 1.5. The rule holds between two rows that were never measured against each other, which means it is not an artifact of choosing Trial 1 as the reference. The third clue is of a different kind again: the speed pair proves this record CAN produce an energy factor that is not equal to the factor of the thing that changed. If the record simply handed back whatever number you fed it, Trial 3 would have come out at twice the baseline. It came out at four times. So the mass result is a real finding about the mass column, not a habit of the record.`,
        `Second, change one thing and check that the answer moves the way it should. Suppose the club runs a fifth trial with the 2-kilogram ball at 9 meters per second. The mass is unchanged, and 9 divided by 3 is 3, so the speed is three times Trial 1's -- and the rule says the energy should be 3 times 3, which is nine times Trial 1's, not three times. Now compare that with a trial at 3 meters per second and three times the mass, which the record already has as Trial 4 at three times the energy. Tripling the speed and tripling the mass are both "three times", and they give completely different answers: nine times against three times. A rule that gave the same answer for both would not be describing this record at all. The two columns behave differently, and that fifth trial is exactly where you would see it.`,
      ],
      example: { problem: `A science club rolls a metal ball along a level track four times and records how much kinetic energy the ball has as it passes the far end. Trial 1 is the run everything else is compared against: a ball with a mass of 2 kilograms passes the end at 3 meters per second. Trial 2: a ball with a mass of 4 kilograms passes the end at 3 meters per second, and its kinetic energy is twice Trial 1's. Trial 3: a ball with a mass of 2 kilograms passes the end at 6 meters per second, and its kinetic energy is four times Trial 1's. Trial 4: a ball with a mass of 6 kilograms passes the end at 3 meters per second, and its kinetic energy is three times Trial 1's. Use the four trials to say how the kinetic energy depends on the mass and how it depends on the speed.`, solution: `With the speed held still, the kinetic energy grows by the same factor as the mass: twice the mass gives twice the energy, and three times the mass gives three times the energy. With the mass held still, the kinetic energy grows by the speed factor multiplied by itself: twice the speed gives 2 times 2, which is four times the energy.` },
      relatedLoIds: ['m8sci.kinetic-energy-mass-and-speed'],
    },
    {
      title: 'Worked both change at once',
      steps: [
        `Step 1, write down what you are given, with its units. First cart: a mass of 3 kilograms, a speed of 2 meters per second. Second cart: a mass of 6 kilograms, a speed of 4 meters per second. Both the mass and the speed are different, so there is no pair here that differs in one thing only. That is not a dead end. It means you take the two changes one at a time and then put them back together.`,
        `Step 2, the mass on its own. Divide to get the factor: 6 kilograms divided by 3 kilograms is 2, so the second cart has twice the mass. With the speed held still, twice the mass gives twice the kinetic energy. Write down 2 times and set it aside.`,
        `Step 3, the speed on its own. Divide again: 4 meters per second divided by 2 meters per second is 2, so the second cart has twice the speed. With the mass held still, a speed factor is multiplied by itself, and 2 times 2 is 4. Write down 4 times.`,
        `Step 4, put the two contributions together by multiplying them. The mass change multiplies the energy by 2 and the speed change multiplies it by 4, so together they multiply it by 2 times 4, which is 8. The second cart has eight times the kinetic energy of the first. WRONG: "The mass doubled and the speed doubled, so the energy doubled twice over -- 2 times for the mass and 2 times for the speed, which is 4 times in all." CORRECT: "The mass doubled, which is 2 times, and the speed doubled, which is 2 times 2, or 4 times; 2 times 4 is 8 times in all." The two doublings are not worth the same amount, and that is the entire point of this lesson.`,
        `Now run the two checks. First, three clues of DIFFERENT KINDS that agree. Clue one is a staged route through a cart that is not in the problem at all: start with the first cart at 3 kilograms and 2 meters per second, change only the mass, and a cart of 6 kilograms at 2 meters per second has twice the first cart's energy; now change only the speed of THAT cart, from 2 meters per second to 4 meters per second, and it has four times its own energy. Twice the baseline, then four times that, is 2 times 4, which is 8 times the baseline -- and every step of the staged route was a one-thing-at-a-time comparison of the kind the trial record taught. Clue two is the same journey taken in the other order: raise the first cart's speed to 4 meters per second and it has four times its energy, then double its mass to 6 kilograms and it has twice that, and 4 times 2 is 8 again. Two orders, one answer, which is what has to happen if the two factors really do just multiply. Clue three is a size check that needs no arithmetic: each change on its own makes the energy larger, so the answer has to be larger than either factor on its own. An answer of 4 -- the speed factor alone -- would fail that check immediately, because it leaves the doubled mass doing nothing at all.`,
        `Second, change exactly one condition and check that the answer moves. Give the second cart the same speed as the first, 2 meters per second, and leave its mass at 6 kilograms: the speed factor is now 1, and 1 multiplied by itself is still 1, so only the mass factor of 2 is left and the second cart has twice the first cart's energy, not eight times. Now change the other condition instead -- put both carts at a mass of 3 kilograms and leave their speeds at 2 meters per second and 4 meters per second -- and the mass factor is 1, so only the speed factor of 4 is left. Eight times was the product of two changes, and taking either one of them away drops the answer to what the other change is worth on its own.`,
      ],
      example: { problem: `Two carts run along the same level track. The first cart has a mass of 3 kilograms and moves at 2 meters per second. The second cart has a mass of 6 kilograms and moves at 4 meters per second. How many times as much kinetic energy does the second cart have as the first, and how do you work that out when two things have changed at once?`, solution: `Eight times as much. The mass factor is 6 kilograms divided by 3 kilograms, which is 2, and a mass factor goes into the energy unchanged, as 2. The speed factor is 4 meters per second divided by 2 meters per second, which is 2, and a speed factor goes into the energy multiplied by itself, as 2 times 2, which is 4. Multiply the two contributions: 2 times 4 is 8.` },
      relatedLoIds: ['m8sci.kinetic-energy-mass-and-speed'],
    },
  ],
  pointers: [
    { content: `Students often say "A car at 20 meters per second has twice the kinetic energy of the same car at 10 meters per second." — Start by dividing to get the factor: 20 meters per second divided by 10 meters per second is 2, so the speed is twice as large. Then multiply that factor by itself, because that is what a speed factor does on its way into the energy: 2 times 2 is 4. The car at 20 meters per second has FOUR times the kinetic energy of the same car at 10 meters per second, not twice. The mass never changed, so the mass contributes nothing to this particular comparison. WRONG: "Twice the speed, so twice the energy." CORRECT: "Twice the speed, so 2 times 2, which is four times the energy." The same rule is why a small-sounding rise in speed matters so much more than it sounds: the same car at three times the speed is carrying nine times the kinetic energy, because 3 times 3 is 9.`, kind: 'common-error' },
    { content: `Students often say "A truck parked at the curb has plenty of kinetic energy, because a truck is so heavy." — Kinetic energy is the energy an object has because it IS MOVING, and a parked truck is not moving. Its kinetic energy is zero, and it stays zero however many kilograms are sitting in it. Mass is not a supply of kinetic energy that an object carries around; mass is the factor that decides how much a given speed is worth. No speed at all means no energy of motion at all, whatever the mass, which is exactly why a parked truck is safe to walk past and the same truck rolling at a walking pace is not. WRONG: "It is heavy, so it has a lot of kinetic energy." CORRECT: "It is heavy, so IF it were moving it would have a lot of kinetic energy. Standing still, it has none." Whether a still object has energy stored in it in some other way is the next lesson, on energy stored by position; this lesson is about the energy of motion only.`, kind: 'common-error' },
    { content: `Kinetic energy is the energy an object has because it is moving. An object standing still has none, whatever its mass.`, kind: 'tip' },
    { content: `Only two things decide it: how much mass is moving, in kilograms, and how fast it is going, in meters per second.`, kind: 'tip' },
    { content: `The mass rule: with the speed held still, the energy grows by the same factor as the mass. Twice the mass gives twice the energy; three times the mass gives three times the energy.`, kind: 'tip' },
    { content: `The speed rule: with the mass held still, the energy grows by the speed factor multiplied by itself. Twice the speed gives 2 times 2, which is four times the energy; three times the speed gives 3 times 3, which is nine times.`, kind: 'tip' },
    { content: `Never multiply the mass factor by itself. Only the speed gets squared, and that one difference is the whole lesson.`, kind: 'tip' },
    { content: `Compare by dividing, never by subtracting. A rise of 4 meters per second is not a factor of four; ask how many times the smaller speed fits into the larger one.`, kind: 'tip' },
    { content: `When both the mass and the speed change, work out the two factors separately and multiply them together: twice the mass and twice the speed is 2 times 4, which is eight times the energy.`, kind: 'tip' },
    { content: `To read a record of trials: write each trial down with its units, find the pair that differs in one thing only, get that one thing's factor by dividing, and apply the matching rule.`, kind: 'tip' },
  ],
};
