/**
 * Grade 8 Science — Unit 3 CED 3.4: Fields: Forces Without Contact.
 *
 * Auto-extracted from the corresponding lesson plan
 * (evelyn.ms.m8sci.fields-forces-without-contact.v1). Hand-edit freely after extraction; bump
 * baselineVersion when you make material changes.
 *
 * Pointer-gen pass (scripts/gen-topic-notes-pointers.ts) enriches the
 * pointers section via Opus when run on this baseline.
 */

import type { TopicNotesBaseline } from '../types';

export const BASELINE_M8SCI_U3_FIELDS_FORCES_WITHOUT_CONTACT: TopicNotesBaseline = {
  baselineId: 'evelyn.ms.m8sci.fields-forces-without-contact.v1',
  course: 'Grade 8 Science',
  cedUnit: 3,
  cedTopic: '3.4',
  cedTitle: 'Fields: Forces Without Contact',
  planId: 'evelyn.ms.m8sci.fields-forces-without-contact.v1',
  baselineVersion: 1,
  lastUpdatedAt: '2026-09-20',
  sources: [{ type: 'plan', planId: 'evelyn.ms.m8sci.fields-forces-without-contact.v1' }],
  theory: [
    { loId: 'm8sci.fields-forces-without-contact', content: `MOST FORCES NEED CONTACT. THREE DO NOT. When you push a shopping cart, your hands are on the handle. When friction slows a rolling ball, the ball and the ground are touching. When air resistance pushes back on a cyclist, the air is against her. Those are contact forces, and every one of them ends the instant the two surfaces come apart. Three forces in this course work the other way, and you have met all three already: gravity, which pulls between any two masses; the electric force, which pulls or pushes between charged objects; and the magnetic force, which pulls or pushes between magnets and pulls on iron, steel, nickel and cobalt. Each of these acts with a gap of air, or of nothing at all, in between. Rub a plastic comb on a wool sweater and hold it beside a thin stream of water running from a tap, and the stream bends toward the comb without the comb ever touching it. The water carries no charge of its own, and it still bends -- for the reason you already know from the lesson on electric forces and charge, that a charged object shifts the charges inside a nearby object a little, so the near side is pulled toward it.` },
    { loId: 'm8sci.fields-forces-without-contact', content: `A FIELD IS THE CONDITION OF THE SPACE AROUND A SOURCE, NOT A SUBSTANCE COMING OUT OF IT. Every mass has a gravitational field around it. Every charged object has an electric field around it. Every magnet has a magnetic field around it. The field is the region in which another mass, another charge or another magnet would feel a force, and at each place in that region the field has a strength and a direction: this much pull, that way. That is the whole idea. The hardest part is what a field is NOT. WRONG: "Invisible magnetic stuff sprays out of the magnet, crosses the gap, takes hold of the nail, and the magnet slowly runs out of it." CORRECT: "The magnet fills the space around it with a magnetic field, and the nail is pulled by the field at the place where the nail sits." Nothing streams across the gap, nothing is used up, and a magnet that has lifted a hundred nails is not emptier than it was. A field is a condition of a place, in the way that being uphill is a condition of a place, and not a material you could catch in a jar.` },
    { loId: 'm8sci.fields-forces-without-contact', content: `THE FIELD IS THERE WHETHER OR NOT ANYTHING IS THERE TO FEEL IT. This is the sentence that catches people out, so take it slowly. Put a small magnetic object at some spot near a magnet and it is tugged; that tug is how you find out the field is there. Take the object away and put it in a drawer, and the field at that spot is exactly what it was. The object did not make the field. It revealed it. Scientists call an object used this way a test object, and it is worth saying what the word test means here: the object tests the space, the way a thermometer tests how warm a room is without making the room warm. The two errors that follow from getting this backward are worth naming now. WRONG: "There is no field at a place until something magnetic gets close enough, and then the two of them make it together." CORRECT: "The field is already at that place; bringing something magnetic there only shows you what was already true of the space."` },
    { loId: 'm8sci.fields-forces-without-contact', content: `A FIELD IS STRONGER NEARER ITS SOURCE. Put the same test object at two places, one near the source and one far from it, and the pull at the near place is the stronger of the two. That is true of all three fields: near a magnet the pull on a steel object is strong, and a few steps away it is too weak to notice; the hair on your arm lifts toward a charged balloon a couple of centimeters away and does nothing at all across a room. Two warnings come with this. First, a field does not stop at an edge. It gets weaker and weaker as you go out, and there is no line you can cross where it switches off -- eventually it is simply too weak to matter. Second, weaker is not gone: Earth is enormous, and its gravitational field is still strong enough at the Moon, far out in space, to keep pulling on it. Near, strong; far, weak; nowhere, never.` },
    { loId: 'm8sci.fields-forces-without-contact', content: `HOW TO JUDGE WHETHER AN INVESTIGATION IS EVIDENCE THAT A FIELD IS THERE. Three questions, in order, and a good investigation answers all three. (1) WAS THERE A REAL GAP? Nothing touching across it, and nothing else that could have done the job instead -- no tilt of the table, no thread being pulled, no puff of air from a hand waving nearby. If the two objects touched, the result says nothing about acting at a distance. (2) DOES THE EFFECT DEPEND ON THE SOURCE? Take the magnet or the charged object away, or swap it for something that is not a magnet and not charged, and the effect should disappear. An effect that happens either way was never coming from the source. (3) DOES THE EFFECT DEPEND ON WHERE YOU PUT THE TEST OBJECT? Move it nearer and the effect should grow; move it farther and it should shrink. That is the field being mapped, place by place. One more rule sits over all three, and you already use it: change one thing between trials and keep everything else the same, or you will not know which change did the work.` },
    { loId: 'm8sci.fields-forces-without-contact', kind: 'definition', title: 'contact force', content: `a push or a pull that acts only while two objects are touching, such as a hand on a cart, friction, or air resistance.` },
    { loId: 'm8sci.fields-forces-without-contact', kind: 'definition', title: 'non-contact force', content: `a push or a pull that acts between two objects that are not touching; gravity, the electric force and the magnetic force are the three in this course.` },
    { loId: 'm8sci.fields-forces-without-contact', kind: 'definition', title: 'field', content: `the region of space around a mass, a charged object or a magnet in which another mass, charge or magnet would feel a force, with a strength and a direction at every place in it.` },
    { loId: 'm8sci.fields-forces-without-contact', kind: 'definition', title: 'gravitational field', content: 'the field around any mass, in which another mass is pulled toward it.' },
    { loId: 'm8sci.fields-forces-without-contact', kind: 'definition', title: 'electric field', content: `the field around a charged object, in which another charged object is pushed or pulled.` },
    { loId: 'm8sci.fields-forces-without-contact', kind: 'definition', title: 'magnetic field', content: `the field around a magnet, in which another magnet, or a piece of iron, steel, nickel or cobalt, is pushed or pulled.` },
    { loId: 'm8sci.fields-forces-without-contact', kind: 'definition', title: 'test object', content: `a small object placed at a spot on purpose, to find out whether a force acts there and how strong it is; it reveals the field and does not create it.` },
  ],
  methods: [
    {
      title: 'Worked compass near a magnet',
      steps: [
        `Start with the gap, because that is question one. The needle turned, so a force acted on it -- a needle does not swing for no reason. Now ask what was touching the needle at the moment it turned. The magnet was 5 centimeters away and never reached the compass. The table was under the compass the whole time, before and after, so the table cannot be what changed. The air in the room did not move. There is a real gap, and something reached across it.`,
        `Name the force. A compass needle is itself a small magnet, balanced so that it can turn freely, which is exactly why it is useful here: it is a test object for magnetic fields. So what acted on it was a magnetic force, and it acted at the place where the needle sits, not at the place where the magnet sits.`,
        `Now question two, does the effect depend on the source. She lifted the magnet away and the needle swung back to north. Effect gone with the magnet gone: the magnet is the cause. Notice what the needle did when the magnet was absent, though, because it matters. It did not flop to a random direction -- it lined up pointing north, which it does because Earth has a magnetic field of its own and the needle lines up with it. So the space around that table was never free of field. Bringing the bar magnet close added a much stronger field nearby, and the needle lined up with that instead.`,
        `Now question three, and this is the part that turns a single result into evidence for a FIELD rather than for a one-off tug. She tried eight places, and at each one the needle settled in a different direction. A field has a direction at every place in it, and those directions are different from place to place around a magnet -- so a test object that reports a different direction at each place is reporting on the space, place by place. WRONG: "The needle turned, so the magnet pulled the compass toward it." CORRECT: "The needle turned to line up with the field where the needle was, and the direction it chose depended on where in the space it sat."`,
        `Say what the investigation does NOT show, because that is half of evaluating it. It does not show anything traveling out of the magnet: nothing was seen crossing the gap, and nothing needed to. It does not give a strength -- she read directions, not sizes, so no number about the field comes out of this at all. And it does not show that the field appears only when the compass is there; the compass is how she looked, and looking at something is not making it.`,
        `Run the two checks a science answer needs, because there is no arithmetic here to redo. First, three clues of DIFFERENT KINDS that agree. The gap clue: nothing touched the needle, so whatever acted on it acted across 5 centimeters of air. The on-and-off clue: the effect arrived with the magnet and left with the magnet, so the magnet is the source and not the table, the room or the compass itself. The many-places clue: the direction depended on where the compass sat, which is what a field filling a region does and what a single fixed tug could not do. Three different kinds of evidence, one answer. Second, change one thing and check that the answer moves. Slide a copper bar of the same size and shape to the same spot instead of the magnet. Copper is not one of the metals a magnet pulls on, and the needle stays pointing north. Same size, same motion across the same table, no turn -- so the turning was never about an object being brought near. It was about a magnet being brought near.`,
      ],
      example: { problem: `A student puts a compass on a wooden table, well away from anything magnetic. The needle settles, and one end of it points north. She then slides a bar magnet along the table toward the compass and stops it 5 centimeters away, so that the magnet and the compass never touch. The needle swings around and settles pointing toward the magnet instead. She lifts the magnet away, and the needle swings back to north. She repeats this with the magnet at eight different places around the compass, and at each one the needle settles pointing in a different direction. Is this good evidence that a magnetic field fills the space around the magnet? Say what the investigation shows, and what it does not show.`, solution: `Yes, it is good evidence. A force acted on the needle across a 5 centimeter gap with nothing touching it, the effect appeared and disappeared with the magnet, and the direction the needle settled in depended on where the compass sat -- which is a field being mapped place by place, not a single tug. What it does not show is any substance crossing the gap, any strength as a number, or any suggestion that the field exists only while the compass is there. Repeat it with a copper bar and the needle does not move, which is what pins the cause to the magnet.` },
      relatedLoIds: ['m8sci.fields-forces-without-contact'],
    },
    {
      title: 'Worked iron filings pattern',
      steps: [
        `Start with what one filing is doing, because the pattern is only a lot of filings each doing that. A filing is a tiny piece of iron, and a piece of iron placed in a magnetic field becomes a small magnet for as long as it is there. So each filing behaves like a very small compass needle: it turns until it lines up with the field at its own spot. There are thousands of them, so there are thousands of separate reports, one per place, all taken at the same moment.`,
        `Read the reports as a map. Every filing has turned, including the ones a long way from the magnet, and no filing is touching the magnet -- the card is in between. So the force reached across the card to each of them, at every place on the card, and the space above the magnet is filled with field rather than having field only in certain streaks.`,
        `Read the crowding as a strength map, which is question three from the concept segment, answered all at once. Near the two ends of the magnet the filings are packed together and stand right up on end, because the field there is strong enough to lift them against their own weight. Out at the corners of the card, far from the magnet, the same filings barely shifted. Same filings, same tap, different places: the field is strongest near the magnet and gets weaker the farther out you look. Stronger nearer its source.`,
        `Now the student sentence. WRONG: "A magnet shoots out invisible lines, and the filings are lying along the lines." CORRECT: "The magnet fills the space around it with a field, and each filing turns to match the field at its own spot; the lines are the pattern all that turning makes, not objects that came out of the magnet." Two things go wrong in the student version. Nothing is shot out -- see the first correction of the day, that a field is a condition of the space and not a substance leaving the source. And the lines are not real: people draw field lines because they are a handy way to show which way a field points, but there is no gap between two drawn lines where nothing happens. Drop one more filing into a space between two of the lines and it turns too, because the field is at that place as well.`,
        `One more thing the student sentence gets backward, and it is worth its own line: the filings did not create the pattern in the space. WRONG: "The lines are there because the filings are there." CORRECT: "The field was there before any filing landed; sweeping the filings off the card does not change the space above the magnet one bit."`,
        `Run the two checks. First, three clues of DIFFERENT KINDS that agree that a field fills the space. The no-contact clue: not one filing touched the magnet, and every one of them moved. The direction clue: the filings settle in different directions at different places, and a single compass carried around the magnet reports those same directions at those same places, so two very different test objects agree. The strength clue: the effect fades steadily with distance from the magnet, which is what a field around a source does. Second, change one thing and check that the answer moves. Slide the magnet out from under the card and tap again: the filings shuffle and stay wherever they land, in no pattern at all. Or keep the magnet and use a card three times as thick, which pushes every filing farther from the magnet: the same pattern forms, but it is fainter, and fewer filings stand on end. Farther away, weaker field -- the answer moved in the direction the field idea predicts.`,
      ],
      example: { problem: `A stiff card is laid flat on top of a bar magnet, so that the card rests on the magnet and nothing else touches either of them. Iron filings -- tiny bits of iron, like gray dust -- are sprinkled evenly all over the card, and the card is tapped gently with a finger. The filings do not stay where they landed. They swing around and settle into curved lines that sweep from one end of the magnet to the other. Near the two ends of the magnet the lines are crowded close together and the filings stand up on end; out at the corners of the card the filings barely moved from where they fell. A student looks at it and says: "That proves a magnet shoots out invisible lines, and the filings are lying along the lines." What does the pattern actually show, and what is wrong with the student sentence?`, solution: `The pattern shows that a magnetic field fills the whole space around the magnet, because every filing turned to match the field at its own place without touching the magnet, and it shows that the field is stronger nearer the magnet, because the filings are crowded and standing on end near the ends of the magnet and barely moved at the far corners of the card. The student sentence is wrong twice: nothing is shot out of a magnet, since a field is a condition of the space rather than a substance, and the lines are a pattern we draw rather than real objects -- a filing placed between two lines turns as well.` },
      relatedLoIds: ['m8sci.fields-forces-without-contact'],
    },
  ],
  pointers: [
    { content: `Students often say "A magnet sprays invisible stuff into the space, the stuff grabs the nail, and the magnet runs low on it." — A field is a condition of the space around the magnet, not a material in it. Saying there is a magnetic field at a place means that a magnet, or a piece of iron, steel, nickel or cobalt, placed at that place would be pushed or pulled, with a particular strength and in a particular direction. Nothing travels across the gap and nothing is consumed: the nail is pulled by the field at the place where the nail is. The picture to keep is a map rather than a spray. And the test that settles it is the one from the iron filings: every filing on the card turns at the same moment, all over the card at once, including filings far from the magnet and filings sitting between the curved lines of the pattern. That is a whole region being a certain way, not a stream going somewhere. Magnets can indeed lose strength -- dropping them hard or heating them will do it -- but not by being used, and picking up a nail costs a magnet nothing.`, kind: 'common-error' },
    { content: `Students often say "With nothing magnetic nearby, there is no field around the magnet at all." — The field is there whether or not anything is there to feel it. The second object is how you find out about the field, and finding out about something is not the same as making it. Put a small steel object at a spot near a magnet and it is tugged; take it away and shut it in a drawer, and the space at that spot is exactly as it was, and it will tug the next magnetic thing that arrives there. A thermometer is the comparison to hold on to: the room is warm before the thermometer goes in, the thermometer reports the warmth, and taking it out again does not cool the room. Like every comparison it has a limit -- warmth is the motion of particles in the air, and a field is not made of particles at all -- but the part that matters carries over exactly. WRONG: "Nothing is near it, so there is no field." CORRECT: "Nothing is near it, so nothing is being pulled -- and the field is there all the same."`, kind: 'common-error' },
    { content: `Most forces need contact. Three do not: gravity, the electric force and the magnetic force all act between objects that are not touching.`, kind: 'tip' },
    { content: `A field is the region of space around a mass, a charged object or a magnet in which another mass, charge or magnet would feel a force, with a strength and a direction at every place in it.`, kind: 'tip' },
    { content: `A field is a condition of the space, not a substance sprayed out of the source. Nothing crosses the gap and nothing is used up.`, kind: 'tip' },
    { content: `The field is there whether or not anything is there to feel it. A test object reveals the field; it does not create it.`, kind: 'tip' },
    { content: `A field is stronger nearer its source and weaker farther away. It fades out rather than stopping at an edge, and weaker never means gone -- Earth's gravitational field still reaches the Moon.`, kind: 'tip' },
    { content: `To judge whether an investigation is evidence of a field, ask three questions: was there a real gap with nothing else able to do the job; does the effect disappear when the source is taken away; and does the effect change when the test object is moved nearer or farther?`, kind: 'tip' },
    { content: `Between trials, change one thing and keep everything else the same, or you will not know which change did the work.`, kind: 'tip' },
    { content: `Field lines are a pattern people draw to show which way a field points. They are not objects coming out of a magnet, and the field is just as real in the spaces between the drawn lines.`, kind: 'tip' },
  ],
};
