/**
 * AP Environmental Science — CED Unit 7.6+7.8: Air Pollution Mitigation
 * and Noise Pollution.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U7_AIR_QUALITY_MITIGATION: LessonPlan = {
  id: 'evelyn.ap.envsci.air-quality-mitigation.v1', title: 'U7.4 Air Quality Mitigation and Noise Pollution',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.air-quality-mitigation', description: 'Identify technical and policy methods to reduce air pollution. Recognize noise pollution as a public health concern; identify sources and mitigation.', standard: 'AP-ENVSCI-7.6+7.8' }],
  prerequisites: ['apenvsci.acid-rain'], followUps: [], estimatedMinutes: 16,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame mitigation as policy + tech.', script: "Air pollution can be cut dramatically — the US has cut criteria pollutants ~75% since 1970 while economy grew. The tools combine TECHNOLOGY (scrubbers, catalytic converters) and POLICY (Clean Air Act, fuel standards). Today: how it works.", estimatedMinutes: 2 },
    { id: 'concept-mitigation', kind: 'concept', goal: 'Cover mitigation tech + policy + noise.',
      keyIdeas: [
        'TECHNOLOGY for reducing air pollution:',
        '',
        'POWER PLANT controls:',
        '  • SCRUBBERS (FGD — flue gas desulfurization): react SO₂ + lime → calcium sulfate (gypsum). Removes ~95%.',
        '  • ELECTROSTATIC PRECIPITATORS: charge particles, then collect on oppositely-charged plates. ~99% PM removal.',
        '  • BAGHOUSES (fabric filters): like vacuum bags for industrial exhaust. Remove fine particulates.',
        '  • SELECTIVE CATALYTIC REDUCTION (SCR): NH₃ + NOx → N₂ + H₂O over catalyst. Reduces NOx 80-95%.',
        '  • LOW-NOx BURNERS: combustion engineering reduces NOx formation.',
        '',
        'VEHICLE controls:',
        '  • CATALYTIC CONVERTERS: convert CO → CO₂; HC → CO₂ + H₂O; NOx → N₂ + O₂. Standard since 1975.',
        '  • UNLEADED GASOLINE: phased out lead in gasoline (US 1996). Lead emissions dropped >99%.',
        '  • LOW-SULFUR FUELS.',
        '  • EVAP CONTROLS: capture gasoline vapors (gas tank, fueling).',
        '  • EMISSIONS INSPECTIONS in many states.',
        '  • CAFE STANDARDS push fleet fuel economy up.',
        '',
        'INDUSTRIAL controls:',
        '  • FILTERS, condensers, absorbers for industrial emissions.',
        '  • PROCESS modifications (using less polluting solvents).',
        '  • LEAK detection and repair.',
        '',
        'POLICY tools:',
        '  • CLEAN AIR ACT (1970, amended 1990): set NAAQS for criteria pollutants; required state implementation plans (SIPs); New Source Performance Standards.',
        '  • CAP-AND-TRADE for SO₂ (highly successful — 70% reduction).',
        '  • Vehicle EMISSIONS STANDARDS (Tier 1, 2, 3).',
        '  • FUEL ECONOMY (CAFE) standards.',
        '  • International: MONTREAL PROTOCOL (CFCs/ozone depletion); KYOTO PROTOCOL/PARIS AGREEMENT (CO₂).',
        '',
        'NOISE POLLUTION:',
        '  • Excessive sound that disrupts the environment.',
        '  • Sources: traffic, aircraft, construction, industrial machinery, music, neighbors.',
        '  • Health impacts:\n     - Hearing damage (above 85 dB causes permanent damage with prolonged exposure).\n     - Stress, sleep disturbance, cardiovascular problems (chronic noise raises BP, cortisol).\n     - Cognitive effects in children.\n     - Wildlife — masks communication, disrupts breeding (e.g., whales near shipping lanes; birds near highways).',
        '  • Measured in DECIBELS (dB). Logarithmic scale: 70 dB is 10× louder than 60 dB; 80 dB is 100× louder than 60 dB.',
        '  • Examples: whisper 30 dB, conversation 60 dB, traffic 80 dB, lawnmower 90 dB, jackhammer 110 dB, jet engine 140 dB (pain threshold).',
        '  • OSHA limit: 85 dB for 8-hour exposure.',
        'NOISE POLLUTION mitigation:',
        '  • SOUND BARRIERS along highways.',
        '  • Vegetation buffers (also reduce air pollution).',
        '  • Urban planning: separate residential from industrial/transportation corridors.',
        '  • Quieter pavement (rubberized asphalt).',
        '  • Quieter vehicles (EVs are ~50% quieter than ICE at low speeds).',
        '  • Building soundproofing (insulated walls, double-paned windows).',
        '  • Personal: hearing protection (ear plugs/muffs).',
        '  • Marine: shipping lane changes, slower speeds reduce whale-strike + noise.',
      ],
      vocabulary: [
        { term: 'scrubber', definition: 'pollution control removing SO₂ from power-plant exhaust.' },
        { term: 'catalytic converter', definition: 'vehicle device that converts CO, HC, NOx to less harmful gases.' },
        { term: 'decibel', definition: 'logarithmic unit for sound pressure level.' },
      ],
      estimatedMinutes: 5 },
    { id: 'worked-clean-air', kind: 'worked_example',
      problem: 'The US has cut criteria air pollutants ~75% since 1970 while the economy tripled and population grew 60%. Identify three technical/policy actions that drove this success.',
      steps: [
        '(1) CLEAN AIR ACT (1970, 1990 amendments): set NAAQS, drove SIPs, mandated source standards.',
        '(2) CATALYTIC CONVERTERS (1975+): reduced auto CO, HC, NOx by ~90%.',
        '(3) UNLEADED GASOLINE (phased out 1973-1996): cut atmospheric lead 99%+.',
        '(4) SCRUBBERS on power plants: reduced SO₂.',
        '(5) CAP-AND-TRADE for SO₂ (1990): cut SO₂ ~70% by 2018.',
        '(6) FUEL ECONOMY standards: CAFE pushed mpg up.',
        '(7) Switching from COAL to natural gas + renewables (ongoing).',
        '(8) Stricter VEHICLE EMISSIONS standards (Tier 2, Tier 3).',
        '(9) ENERGY EFFICIENCY (less power consumed = less pollution).',
        'KEY INSIGHT: pollution and economic growth can DECOUPLE. Targeted policy + technology = real reductions.',
      ],
      answer: 'Clean Air Act, catalytic converters, unleaded gas, scrubbers, cap-and-trade, fuel economy.', estimatedMinutes: 3 },
    { id: 'try-noise', kind: 'try_yourself',
      problem: 'A new highway will be built within 100 feet of homes and a school. (a) Identify three potential noise impacts. (b) Suggest three mitigation strategies.',
      expectedAnswer: '(a) Noise impacts:\n• Residents: chronic stress, sleep disruption, increased blood pressure, cardiovascular risk. \n• Children at school: cognitive effects, reduced learning, hearing damage. \n• Property values decline near highway. \n• Wildlife (if any nearby): communication disrupted, possibly displaced. \n(b) Mitigation:\n• SOUND BARRIERS — concrete or earth berms along highway. Reduce noise by 5-10 dB. \n• VEGETATION BUFFERS — trees and dense plantings absorb sound and improve air quality. \n• QUIETER PAVEMENT — rubberized asphalt is 3-5 dB quieter. \n• SPEED LIMITS — slower traffic = less noise. \n• BUILDING SOUNDPROOFING — replace windows with double-pane; insulation. \n• REROUTING — preferred to consider alternative routes during planning. \n• TIME RESTRICTIONS — limit truck traffic at night.',
      responseFormat: 'free', hints: ['Engineering, design, and behavioral controls.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. Compare the regulatory approaches for: (a) SO₂ emissions (cap-and-trade), (b) lead in gasoline (phase-out / ban), and (c) NOx from cars (catalytic converters required). For each: how the policy worked, why successful.',
      expectedAnswer: '(a) SO₂ via CAP-AND-TRADE:\n• Total emissions capped, declining over time. \n• Polluters allocated permits; can trade. \n• Cheap reductions found; market efficient. \n• 70% reduction by 2018. \n• Worked because: SO₂ measurable, sources identifiable, market efficient. (1.5)\n(b) LEAD via OUTRIGHT BAN:\n• Government ordered phase-out 1973-1996.\n• Catalytic converters required (lead damages them).\n• Refiners were required to produce unleaded gasoline. \n• Lead removed from gasoline, paint, water pipes. \n• 99% reduction in atmospheric lead.\n• Worked because: complete substitution available; harm well-established; gradual phase-out gave industry time. (1.5)\n(c) NOx via TECHNOLOGY MANDATE (catalytic converters):\n• 1975 onward: all new gasoline cars required catalytic converters. \n• Converters reduce NOx 80-95% per vehicle. \n• Combined with unleaded gasoline (lead poisoned converters). \n• Reduced US NOx ~50% from peak.\n• Worked because: technology readily available; cost passed to consumers; gradual fleet turnover; standards updated as technology improved. (1.5)\nKey insights:\n• MULTIPLE policy tools — choice depends on pollutant + industry structure. \n• MARKET-based vs MANDATE-based both can work. \n• Technology + policy combine; policy alone or tech alone usually insufficient. (1)\nTotal: 5.5 points.',
      responseFormat: 'frq', hints: ['Compare three regulatory mechanisms.'], estimatedMinutes: 5 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Power plants: scrubbers (SO₂), precipitators (PM), SCR (NOx).',
      'Vehicles: catalytic converters, unleaded gasoline, fuel-economy standards.',
      'Policy: Clean Air Act, cap-and-trade for SO₂.',
      'Noise pollution: chronic stress, hearing damage; barriers, buffers, planning.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '7', cedTopic: '7.6+7.8', cedTitle: 'Air Quality Mitigation', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '17', note: 'Standard mitigation + noise.' }] },
};
