/**
 * AP Environmental Science — CED Unit 9.3+9.4+9.5: Greenhouse Effect,
 * Greenhouse Gases, and Global Climate Change.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U9_GREENHOUSE_CLIMATE: LessonPlan = {
  id: 'evelyn.ap.envsci.greenhouse-climate.v1', title: 'U9.2 Greenhouse Effect and Climate Change',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.greenhouse-climate', description: 'Explain the greenhouse effect. Identify major greenhouse gases and their relative warming potentials. Describe observed climate change and its predicted impacts.', standard: 'AP-ENVSCI-9.3-9.5' }],
  prerequisites: ['apenvsci.ozone'], followUps: ['apenvsci.ocean-changes'], estimatedMinutes: 22,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame climate change as the defining issue.', script: "Earth\'s climate has changed before — but never this fast. Atmospheric CO₂ has risen from 280 ppm pre-industrial to 420 ppm today, the fastest rate in 800,000 years. We are running a planetary experiment in real time. Today: how greenhouse gases trap heat and what we expect.", estimatedMinutes: 2 },
    { id: 'concept-greenhouse', kind: 'concept', goal: 'Cover greenhouse effect, GHGs, climate change.',
      keyIdeas: [
        'GREENHOUSE EFFECT: natural process where greenhouse gases (GHGs) absorb infrared radiation from Earth\'s surface, then re-emit it in all directions including back down — warms the surface.',
        '  • WITHOUT greenhouse effect, Earth would average -18°C (uninhabitable).',
        '  • WITH natural greenhouse effect, Earth averages +15°C (habitable).',
        '  • The PROBLEM: human emissions ENHANCE the effect, raising temperatures further.',
        'KEY GREENHOUSE GASES (memorize):',
        '  • CARBON DIOXIDE (CO₂): #1 by volume. From combustion of fossil fuels, deforestation. Lifetime: 100s-1000s of years in atmosphere. Pre-industrial 280 ppm; 2024 ~420 ppm (50% increase).',
        '  • METHANE (CH₄): from agriculture (cattle, rice paddies, manure), landfills, fossil-fuel extraction (especially fracking leaks), wetlands. ~25× more potent than CO₂ over 100 years (84× over 20 years). Lifetime: ~10 years.',
        '  • NITROUS OXIDE (N₂O): from agriculture (fertilizer breakdown), combustion. ~300× more potent than CO₂ (per molecule).',
        '  • FLUORINATED gases (HFCs, PFCs, SF₆): industrial. Thousands of times more potent than CO₂ but smaller volumes.',
        '  • WATER VAPOR (H₂O): natural greenhouse gas; not directly emitted but feedback-amplified by warming.',
        'GLOBAL WARMING POTENTIAL (GWP): comparative measure of how much heat a GHG traps relative to CO₂.',
        '  • CO₂ = 1 (baseline).',
        '  • CH₄ = 25-30 (over 100 years).',
        '  • N₂O = 273.',
        '  • HFC-134a = ~1,300.',
        '  • SF₆ = 22,800.',
        'CONTRIBUTIONS to current warming (lifecycle): CO₂ ~76%, CH₄ ~16%, N₂O ~6%, fluorinated ~2%.',
        'EVIDENCE OF CLIMATE CHANGE:',
        '  • Temperature: globally ~1.2°C warmer than pre-industrial baseline (2024). 9 of 10 warmest years on record have occurred since 2014.',
        '  • Arctic sea ice: 13% per decade decline.',
        '  • Greenland and Antarctic ice sheets losing mass (Greenland ~280 Gt/year).',
        '  • SEA-LEVEL RISE: ~21 cm since 1880; accelerating to ~3.4 mm/year. From thermal expansion + ice melt.',
        '  • OCEAN warming: top 700m absorbing 90% of excess heat.',
        '  • OCEAN ACIDIFICATION: pH dropped 0.1 unit (30% more acidic).',
        '  • Glacier retreat globally.',
        '  • Permafrost thaw (releases more methane → feedback).',
        '  • Extreme weather: more intense hurricanes, longer fire seasons, deeper droughts, heavier rainstorms.',
        '  • SHIFTS in plant/animal ranges (toward poles, higher altitudes).',
        '  • Ocean coral bleaching (90%+ of Great Barrier Reef damaged in repeated events).',
        'PROJECTED IMPACTS (IPCC):',
        '  • By 2100: 1.5-4°C+ warming depending on emissions.',
        '  • Sea-level rise: 0.4-1.2 m additional.',
        '  • Severe water + food security challenges.',
        '  • Climate refugees from coastal/arid regions.',
        '  • Mass extinction risk for many species.',
        '  • Health impacts: heat waves, expanded disease ranges, food insecurity.',
        'TIPPING POINTS (potential abrupt changes):',
        '  • Arctic permafrost thaw (large methane release).',
        '  • Greenland and West Antarctic ice sheet collapse.',
        '  • Amazon rainforest dieback.',
        '  • Atlantic Meridional Overturning Circulation (AMOC) slowdown.',
      ],
      vocabulary: [
        { term: 'greenhouse effect', definition: 'GHGs absorb and re-emit infrared, warming surface.' },
        { term: 'GWP', definition: 'global warming potential — relative warming impact vs CO₂.' },
        { term: 'tipping point', definition: 'threshold beyond which abrupt climate change becomes self-sustaining.' },
      ],
      estimatedMinutes: 7 },
    { id: 'worked-effect', kind: 'worked_example',
      problem: 'Walk through the energy-balance physics: why does adding CO₂ warm Earth?',
      steps: [
        'STEP 1 — Sun emits high-energy ULTRAVIOLET and VISIBLE radiation. Most passes through atmosphere to surface.',
        'STEP 2 — Earth\'s surface absorbs this energy → warms.',
        'STEP 3 — Warm Earth emits LONGER-WAVELENGTH (infrared) radiation in all directions, including up.',
        'STEP 4 — GREENHOUSE GASES (CO₂, CH₄, H₂O) ABSORB infrared radiation efficiently — different molecules absorb at different wavelengths.',
        'STEP 5 — Heated GHGs RE-EMIT infrared in all directions: half goes back DOWN to Earth\'s surface.',
        'STEP 6 — Net effect: surface receives MORE energy than without GHGs.',
        'STEP 7 — More CO₂ = more absorption + re-emission = warmer surface.',
        'STEP 8 — Energy balance: surface temperature rises until outgoing infrared balances incoming. With more CO₂, that balance occurs at a HIGHER temperature.',
        'STEP 9 — FEEDBACK LOOPS amplify: warmer air holds more water vapor (potent GHG); melting ice exposes dark surfaces (less reflection, more absorption); permafrost thaw releases methane.',
      ],
      answer: 'Sun→surface→IR up→GHGs absorb+re-emit→half down→warmer surface. Feedbacks amplify.', estimatedMinutes: 4 },
    { id: 'try-gwp', kind: 'try_yourself',
      problem: 'A farm releases 1 ton of methane and 100 tons of CO₂ per year. Methane GWP = 28 (over 100 years). (a) Compute CO₂-equivalent emissions of the methane. (b) Total emissions in CO₂ equivalents.',
      expectedAnswer: '(a) 1 ton CH₄ × 28 = 28 tons CO₂-equivalent. \n(b) Total = 28 + 100 = 128 tons CO₂-eq. \nMethane is 28% of equivalent emissions despite being only 1% of mass. This is why methane reductions (capping leaks, cutting livestock methane, etc.) get high climate priority — much more bang for buck than equivalent CO₂ reductions.',
      responseFormat: 'numeric', hints: ['CO₂-eq = mass × GWP.'], estimatedMinutes: 2 },
    { id: 'try-evidence', kind: 'try_yourself',
      problem: 'List 5 lines of evidence for ongoing climate change.',
      expectedAnswer: '(1) Global TEMPERATURE record — 1.2°C above pre-industrial; 9 of 10 hottest years since 2014. \n(2) ARCTIC SEA ICE DECLINE — 13%/decade summer ice. \n(3) GREENLAND + Antarctic ICE LOSS — 280-360 Gt/year combined. \n(4) SEA-LEVEL RISE — 21 cm since 1880; accelerating. \n(5) OCEAN WARMING — top 700m absorbed 90% of excess heat. \n(6) OCEAN ACIDIFICATION — pH dropped 0.1 unit (30% more acidic). \n(7) GLACIER RETREAT — most globally retreating. \n(8) PERMAFROST THAW. \n(9) Phenological shifts — earlier spring, later autumn. \n(10) Range shifts — species moving poleward and to higher altitudes. \n(11) Coral bleaching events. \n(12) ISOTOPIC SIGNATURE: rising CO₂ has signature of fossil-fuel origin (low ¹⁴C, low ¹³C). \n(13) Rising humidity following predictions.',
      responseFormat: 'free', hints: ['Multiple independent lines of evidence converge.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. (a) Suppose we stopped ALL GHG emissions today. Would temperatures stop rising immediately? Explain. (b) Identify TWO POSITIVE FEEDBACK loops that amplify warming. (c) What does the term "carbon neutrality" mean and why is it the goal?',
      expectedAnswer: '(a) Temperatures would NOT stop rising immediately. \n• CO₂ already in atmosphere persists for centuries. The "warming in pipeline" continues for 30-50 years. \n• Oceans have absorbed enormous heat — that heat will continue to drive ice melt and surface warming. \n• Permafrost will continue to thaw, releasing more methane (positive feedback). \n• ICE SHEETS responding to warming over decades-centuries. \n• Net: even with zero new emissions, ~0.5°C MORE warming is "locked in." Stabilizing climate requires NEGATIVE emissions, not just zero new emissions. \nThis is why URGENCY MATTERS — every year of delay locks in more warming. (2.5)\n(b) Positive feedback loops:\n(1) ALBEDO feedback: warming melts ice and snow → exposed darker surfaces (oceans, land) → more solar absorption → more warming → more melt. (Albedo = reflectivity.) \n(2) METHANE FROM PERMAFROST: warming thaws permafrost → microbes break down organic matter → release methane → more warming. \n(3) WATER VAPOR feedback: warming → more evaporation → more water vapor in atmosphere → water vapor is a GHG → more warming. \n(4) FOREST DIEBACK: drought + heat → trees die → carbon released → less photosynthesis → more warming. \n(5) FIRE feedback: hotter, drier conditions → more fires → CO₂ release. (2)\n(c) CARBON NEUTRALITY:\n• Definition: emissions BALANCED by removals (natural sinks like forests + technological removal like direct air capture). \n• Net zero EMISSIONS — not zero gross. \n• Requires ALL major economies to zero out plus DRAW DOWN already-emitted CO₂. \n• Goal because: stabilizes climate at SOME level (we can\'t reverse warming, but can stop adding to it). \n• 2050 target for many nations; 2070 for some; ~2070 for India, China. \n• Achieving it requires: transformation of energy system (renewables + nuclear), agriculture practices, industrial processes, transportation electrification, plus negative-emissions tech. (2)\nTotal: 6.5 points.',
      responseFormat: 'frq', hints: ['Lag, feedback, future framework.'], estimatedMinutes: 6 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Greenhouse effect: GHGs absorb + re-emit IR, warming surface.',
      'Major GHGs: CO₂ (76%), CH₄ (16%, 28× more potent), N₂O (300×), F-gases.',
      'Evidence: warming, ice loss, sea-level rise, ocean acidification, range shifts.',
      'Feedbacks (albedo, methane, water vapor) amplify warming.',
      'Goal: NET-ZERO emissions to stabilize climate; takes decades for response.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '9', cedTopic: '9.3-9.5', cedTitle: 'Greenhouse Effect and Climate Change', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '19', note: 'Standard climate change.' }] },
};
