/**
 * AP Environmental Science — Unit 2 FRQ Practice.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U2_FRQ_PRACTICE: LessonPlan = {
  id: 'evelyn.ap.envsci.u2-frq-practice.v1', title: 'U2 FRQ Practice',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.u2-frq-practice', description: 'Apply Unit 2 biodiversity / tolerance / disturbance concepts in AP-style FRQs.', standard: 'AP-ENVSCI-2-FRQ' }],
  prerequisites: ['apenvsci.disruptions-succession'], followUps: [], estimatedMinutes: 26,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Stakes.', script: "Three Unit 2 FRQs: island biogeography / fragmentation, tolerance / specialist vs generalist, succession after disturbance.", estimatedMinutes: 2 },
    { id: 'concept-strategy', kind: 'concept', goal: 'Refresh.', keyIdeas: [
      'Biodiversity at 3 levels; island biogeography (size, distance).',
      'Tolerance curves; Liebig (min); Shelford (range).',
      'Specialist vs generalist; structural/behavioral/physiological adaptations.',
      'Primary vs secondary succession; pioneer to climax.',
    ], estimatedMinutes: 2 },
    { id: 'try-frq-fragmentation', kind: 'try_yourself',
      problem: 'FRQ Practice 1 — Habitat Fragmentation. A 1,000-hectare forest preserve is bisected by a new highway, leaving two 500-hectare fragments. (a) Apply island biogeography theory to predict the impact. (b) Describe TWO mechanisms that reduce species in fragmented habitats. (c) Suggest two design features that would mitigate the damage. (d) For a top-predator species (e.g., bobcat) requiring 200-ha territories, predict whether the habitat is still viable.',
      expectedAnswer: '(a) Island biogeography: smaller "islands" (fragments) support fewer species (S ∝ A^z). Two 500-ha fragments combined support FEWER species than the original 1000-ha contiguous forest. The highway also creates a barrier limiting movement between fragments. (2)\n(b) Mechanisms:\n(1) EDGE EFFECTS — smaller fragments have proportionately more edge; interior species (those needing deep, dark forest interior) lose habitat. Edges are warmer, drier, windier, more prone to invasive species and predators. \n(2) ISOLATION — limited migration between fragments → reduced gene flow → inbreeding → genetic loss. Local extinctions in one fragment can\'t be repopulated from the other. \n(3) AREA EFFECTS — populations of large mammals, area-sensitive species drop below viable levels in smaller fragments. (3)\n(c) Mitigation:\n(i) WILDLIFE OVERPASSES/UNDERPASSES — let animals cross the highway. \n(ii) HABITAT CORRIDORS — vegetated strips connecting fragments. \n(iii) Speed reduction zones / wildlife crossing signs. \n(iv) Fencing to direct animals to crossings. (2)\n(d) For a bobcat needing 200 ha territory: each fragment of 500 ha can support maybe 2-3 bobcat territories — VIABLE if each fragment\'s population is large enough to avoid local extinction (probably 10+ individuals minimum). However, isolated populations risk inbreeding without corridor. With corridors connecting fragments → effectively a 1000-ha territory available, 5+ bobcats supported, viable long-term. Without corridors, may eventually go locally extinct. (2)\nTotal: 9 points.',
      rubric: { parts: [
        { criterionId: 'a', maxPoints: 2, scoringCriteria: 'Applies island biogeography (smaller area supports fewer species, S ∝ A^z) to predict the two fragments support fewer species than the original, and notes the highway is a movement barrier.', modelResponse: 'Smaller "islands" support fewer species (S ∝ A^z), so two 500-ha fragments hold fewer species than the original contiguous 1000-ha forest, and the highway barrier further limits movement between them.' },
        { criterionId: 'b', maxPoints: 3, scoringCriteria: 'Describes two valid mechanisms of species loss in fragments (edge effects, isolation/reduced gene flow, or area effects on large/area-sensitive species).', modelResponse: 'EDGE EFFECTS: smaller fragments have proportionately more edge — warmer, drier, more invasives — so interior species lose habitat. ISOLATION: limited migration reduces gene flow, causing inbreeding, and local extinctions cannot be recolonized.' },
        { criterionId: 'c', maxPoints: 2, scoringCriteria: 'Suggests two design features that reconnect fragments or reduce road mortality (wildlife over/underpasses, habitat corridors, crossing signage, fencing to crossings).', modelResponse: 'Build WILDLIFE OVERPASSES/UNDERPASSES so animals can cross the highway, and establish HABITAT CORRIDORS (vegetated strips) reconnecting the fragments.' },
        { criterionId: 'd', maxPoints: 2, scoringCriteria: 'Evaluates viability for a 200-ha-territory predator: a 500-ha fragment supports only 2-3 territories, so isolated populations risk inbreeding/local extinction, but corridors restore effective viability.', modelResponse: 'Each 500-ha fragment supports only 2-3 bobcat territories, so isolated it risks inbreeding and local extinction; with corridors the fragments function as ~1000 ha, supporting 5+ bobcats and remaining viable long-term.' },
      ] },
      responseFormat: 'frq', hints: ['Apply theory to specific case; multiple mechanisms; mitigation; minimum viable.'], estimatedMinutes: 7 },
    { id: 'try-frq-specialist', kind: 'try_yourself',
      problem: 'FRQ Practice 2 — Tolerance and Specialist Species. A region\'s climate is warming. Two species coexist: Species A (a generalist herbivore eating 20+ plants) and Species B (a specialist eating only one species of plant that requires cold winters). (a) Identify which is more vulnerable. Justify with reference to ecological tolerance. (b) Describe ONE structural and ONE behavioral adaptation that could help Species B persist. (c) Suggest a management intervention to support Species B.',
      expectedAnswer: '(a) Species B (specialist) is MORE VULNERABLE. \nReasoning: Species B\'s tolerance range is narrow (depends on one plant species + that plant\'s cold-winter requirement). Climate warming pushes the plant\'s tolerance toward extinction in the region → Species B loses its food source → Species B faces local extinction. Species A (generalist) has broad food tolerance and can shift to whichever plants survive — high adaptability. (2)\n(b) STRUCTURAL adaptation: improved digestion of alternative plant species (broader gut microbiome, altered teeth/jaw). Allows expanded diet. (1.5)\nBEHAVIORAL adaptation: range shift to higher elevations or northward (where the cold-loving plant still grows). Migration to track suitable conditions. (1.5)\n(c) Management:\n• ASSISTED MIGRATION: relocate Species B (or its food plant) to suitable cooler locations. \n• HABITAT CORRIDORS to enable range shifts naturally. \n• PROTECTED COOLER REFUGIA — preserve high-elevation or shaded habitats where the food plant can persist. \n• EX SITU CONSERVATION — captive breeding or seed banks. \n• Climate change mitigation broadly to slow warming pace. (2)\nTotal: 7 points.',
      rubric: { parts: [
        { criterionId: 'a', maxPoints: 3, scoringCriteria: 'Identifies Species B (specialist) as more vulnerable and justifies with tolerance: its narrow tolerance range and single cold-dependent food plant collapse under warming, while the generalist can shift foods.', modelResponse: 'Species B, the specialist, is MORE VULNERABLE: its narrow tolerance range depends on one cold-winter plant, so warming eliminates its food and it faces local extinction, whereas the generalist Species A has broad food tolerance and adapts.' },
        { criterionId: 'b', maxPoints: 3, scoringCriteria: 'Gives one structural and one behavioral adaptation that could help Species B persist.', modelResponse: 'STRUCTURAL: improved digestion of alternative plants (broader gut microbiome or altered teeth/jaw) to expand its diet. BEHAVIORAL: a range shift to higher elevations or northward to track cooler conditions where its food plant still grows.' },
        { criterionId: 'c', maxPoints: 3, scoringCriteria: 'Suggests a valid management intervention to support Species B (assisted migration, corridors, protected cool refugia, ex situ conservation, or broad climate mitigation).', modelResponse: 'ASSISTED MIGRATION of Species B or its food plant to cooler locations, supported by habitat CORRIDORS and PROTECTED COOL REFUGIA (high-elevation/shaded habitat); ex situ breeding or seed banks provide backup.' },
      ] },
      responseFormat: 'frq', hints: ['Specialist vulnerability; adaptation types; conservation actions.'], estimatedMinutes: 6 },
    { id: 'try-frq-succession', kind: 'try_yourself',
      problem: 'FRQ Practice 3 — Disturbance and Succession. A forest fire burns 5,000 hectares of pine forest. After the fire, biologists begin tracking recovery. (a) Identify the type of succession occurring. (b) Predict the sequence of dominant species over 50 years. (c) Identify ONE pioneer species and ONE climax species. (d) Explain why some ecosystems REQUIRE fire to maintain themselves.',
      expectedAnswer: '(a) SECONDARY SUCCESSION — soil is intact (the fire burned vegetation but soil and seedbanks remain). Recovery is faster than primary succession. (1.5)\n(b) Sequence:\nYear 0-2: bare burned ground; early colonizers from seed bank or wind-dispersed (grasses, fireweed, ragweed). \nYear 2-10: herbaceous plants and small shrubs dominate. \nYear 10-25: fast-growing trees (pines, birches) take over (these are r-selected, fast germinating in open ground). \nYear 25-50+: climax species like oaks and maples may begin replacing pines (in some regions); in pine-dominated regions, climax remains pine. (3)\n(c) PIONEER species: fireweed, ragweed, grasses, blackberry, or aspen seedlings. \nCLIMAX species: oak, hickory, beech (eastern US deciduous); pondering pine, ponderosa pine in western fire-adapted forests. (1.5)\n(d) Some ecosystems require fire because:\n• Fire-DEPENDENT species (longleaf pine, lodgepole pine, jack pine, sequoia) need fire to release seeds (serotinous cones), reduce competition, or stimulate germination. \n• Without fire: shade-tolerant hardwoods and shrubs invade → ecosystem CONVERTS to a different community type → fire-dependent species locally extinct. \n• Fuel accumulates and EVENTUALLY a catastrophic fire occurs (much larger and hotter than the natural fire regime would have been). \n• Result: managed/prescribed burning is essential for conserving these ecosystems. Examples: Great Plains grasslands (without periodic fire become brushland), longleaf pine savannas (Florida, Georgia). (2.5)\nTotal: 8.5 points.',
      rubric: { parts: [
        { criterionId: 'a', maxPoints: 2, scoringCriteria: 'Identifies secondary succession and justifies it because soil and seed banks remain intact after the fire.', modelResponse: 'SECONDARY SUCCESSION — the fire burned the vegetation but soil and seed banks remain, so recovery is faster than primary succession.' },
        { criterionId: 'b', maxPoints: 3, scoringCriteria: 'Predicts a plausible 50-year successional sequence from bare ground/pioneers through herbs and shrubs to fast-growing then climax trees.', modelResponse: 'Year 0-2: bare ground with grasses, fireweed, ragweed. Year 2-10: herbaceous plants and shrubs. Year 10-25: fast-growing r-selected trees (pines, birches). Year 25-50+: climax species (oaks, maples) begin replacing pines, or pine remains climax in pine-dominated regions.' },
        { criterionId: 'c', maxPoints: 2, scoringCriteria: 'Names one valid pioneer species and one valid climax species.', modelResponse: 'PIONEER: fireweed, ragweed, grasses, or aspen seedlings. CLIMAX: oak, hickory, or beech in eastern deciduous forest (ponderosa pine in western fire-adapted forest).' },
        { criterionId: 'd', maxPoints: 2, scoringCriteria: 'Explains why some ecosystems require fire: fire-dependent species need it for seed release/germination and to suppress competitors, and without it the community converts and fuel builds to catastrophic levels.', modelResponse: 'Fire-dependent species (longleaf, lodgepole, jack pine, sequoia) need fire to open serotinous cones, clear competitors, and stimulate germination; without periodic fire, hardwoods invade and the ecosystem converts, while fuel accumulates toward a catastrophic burn — so prescribed fire conserves grasslands and pine savannas.' },
      ] },
      responseFormat: 'frq', hints: ['Soil intact = secondary; pioneer to climax; fire as evolutionary force.'], estimatedMinutes: 7 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Habitat fragmentation = island biogeography; corridors mitigate.',
      'Specialists vulnerable to environmental change; tolerance curves predict.',
      'Succession: pioneer → mid-stages → climax; primary much slower than secondary.',
      'Some ecosystems are FIRE-DEPENDENT.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '2', cedTopic: '2-FRQ', cedTitle: 'Unit 2 FRQ Practice', sources: [{ type: 'frq-style', source: 'AP Plans Initiative author', note: 'Modeled on AP Env Sci Unit-2 FRQs.' }] },
};
