/**
 * AP Environmental Science — CED Unit 9.8+9.9+9.10: Invasive Species,
 * Endangered Species, and Human Impacts on Biodiversity.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_ENVSCI_U9_BIODIVERSITY_THREATS: LessonPlan = {
  id: 'evelyn.ap.envsci.biodiversity-threats.v1', title: 'U9.4 Invasive Species, Endangered Species, Biodiversity',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-environmental-science', locale: 'en',
  los: [{ id: 'apenvsci.biodiversity-threats', description: 'Identify mechanisms and impacts of invasive species. Distinguish endangered, threatened, and extinct species. Apply HIPPCO mnemonic for biodiversity threats.', standard: 'AP-ENVSCI-9.8-9.10' }],
  prerequisites: ['apenvsci.ocean-changes'], followUps: [], estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame biodiversity decline.', script: "Earth is in the SIXTH MASS EXTINCTION — the first caused by a species (us). Background extinction is ~1 species per million per year; current rates are 100-1000× that. Today: the threats and what we can do.", estimatedMinutes: 2 },
    { id: 'concept-threats', kind: 'concept', goal: 'Cover invasives, endangered, HIPPCO.',
      keyIdeas: [
        'HIPPCO — major drivers of biodiversity loss (memorize):',
        '  • H — HABITAT DESTRUCTION/DEGRADATION. Top driver. Land conversion, deforestation, urbanization. ~50% of habitat loss in tropical forests since 1990.',
        '  • I — INVASIVE SPECIES. Nonnative species outcompete or prey on natives.',
        '  • P — POPULATION (human). 8 billion humans demanding resources, land, water.',
        '  • P — POLLUTION. Toxic chemicals, plastics, eutrophication.',
        '  • C — CLIMATE CHANGE. Disrupts ranges, phenology, ecosystems.',
        '  • O — OVEREXPLOITATION (overharvesting). Hunting, fishing, illegal wildlife trade.',
        'INVASIVE SPECIES: nonnative species that establish in a new ecosystem and cause harm.',
        '  • Routes of introduction:\n     - Ballast water (zebra mussels in Great Lakes from Eastern Europe).\n     - Pet trade (lionfish in Atlantic from aquariums).\n     - Ornamental plants (kudzu, Asian carp).\n     - Accidental cargo (emerald ash borer, fire ants).\n     - Intentional introduction (rabbits in Australia, mongoose in Hawaii — for pest control).',
        '  • Why successful: NO NATURAL PREDATORS, abundant resources, often r-selected.',
        '  • IMPACTS: outcompete natives, reduce biodiversity, ecosystem damage, agricultural loss, economic loss.',
        '  • EXAMPLES:\n     - ZEBRA MUSSELS — clog water intake pipes, billions in damage.\n     - KUDZU — "the vine that ate the South." Smothers native vegetation.\n     - BURMESE PYTHONS in Florida — depleted small mammal populations.\n     - CANE TOADS in Australia — toxic to predators that try to eat them.\n     - ASIAN CARP in US rivers — outcompete natives, leap into boats.',
        '  • Management: prevention (best); manual removal; biocontrol (introducing natural predator — risky); chemical control.',
        'ENDANGERED SPECIES classifications (IUCN Red List):',
        '  • EXTINCT — none alive (e.g., dodo, passenger pigeon, thylacine).',
        '  • EXTINCT IN THE WILD — only captive specimens (Hawaiian crow, Père David\'s deer).',
        '  • CRITICALLY ENDANGERED — extreme risk; population very small/declining (mountain gorilla, vaquita porpoise).',
        '  • ENDANGERED — high risk (Bengal tiger, snow leopard, blue whale).',
        '  • THREATENED / VULNERABLE — at risk (polar bear, white rhino).',
        '  • LEAST CONCERN — common, stable (raccoon, white-tailed deer).',
        'US ENDANGERED SPECIES ACT (1973): protects listed species and their habitats.',
        '  • Federal agencies must consult before any project that may affect listed species.',
        '  • Critical Habitat designation.',
        '  • SUCCESS STORIES: bald eagle (delisted 2007), gray wolf (recovered), American alligator, peregrine falcon.',
        '  • CONTROVERSY: economic cost (forestry, ranching, oil), property rights, compensation.',
        'BIODIVERSITY DECLINE statistics:',
        '  • CURRENT extinction rate: 100-1000× background rate.',
        '  • IUCN: ~28,000 species threatened (2024 list).',
        '  • Many species not yet described — true loss higher.',
        '  • Vertebrate populations down ~70% since 1970 (WWF Living Planet Report).',
        '  • Insect populations down ~75% in some regions (German study).',
        'CONSEQUENCES of biodiversity loss:',
        '  • Ecosystem service loss (pollination, decomposition, water purification).',
        '  • Agricultural impacts (less genetic diversity in food crops).',
        '  • Loss of pharmaceutical potential (~25% of modern medicines from natural sources).',
        '  • Cascading ecosystem destabilization.',
        '  • Cultural/recreational losses.',
        'CONSERVATION strategies:',
        '  • PROTECTED AREAS (national parks, wildlife refuges, marine reserves).',
        '  • LEGAL PROTECTION (ESA, CITES — international wildlife trade treaty).',
        '  • CAPTIVE BREEDING + reintroduction (California condor, black-footed ferret).',
        '  • SEED BANKS / SPERM BANKS preserve genetic diversity.',
        '  • CORRIDORS connecting protected areas.',
        '  • SUSTAINABLE harvest practices.',
        '  • COMMUNITY-BASED conservation involving indigenous peoples.',
        '  • Public education + ecotourism.',
      ],
      vocabulary: [
        { term: 'HIPPCO', definition: 'Habitat, Invasive, Population, Pollution, Climate, Overexploitation.' },
        { term: 'invasive species', definition: 'nonnative species causing ecological/economic harm.' },
        { term: 'endangered species', definition: 'IUCN/ESA classification of imminent extinction risk.' },
      ],
      estimatedMinutes: 6 },
    { id: 'worked-hippco', kind: 'worked_example',
      problem: 'A polar bear population is declining. Apply HIPPCO to identify which threats are likely affecting it.',
      steps: [
        'H — HABITAT loss: SEA ICE is melting. Polar bears need ice to hunt seals. As Arctic ice declines, hunting grounds shrink. Most-cited threat. ✓ MAJOR.',
        'I — INVASIVE species: not significant for polar bears.',
        'P — Population (human): increasing Arctic activity (oil exploration, shipping, tourism) but limited direct human-bear conflict.',
        'P — Pollution: Persistent organic pollutants (POPs) bioaccumulate in polar bears (top predator); reduces immune function and reproduction. ✓ Significant.',
        'C — Climate CHANGE: ROOT CAUSE of habitat loss. Driving sea-ice retreat. ✓ MAJOR.',
        'O — Overexploitation: HUNTING was historic threat; now regulated. Less significant currently.',
        'CONCLUSION: H (habitat loss) and C (climate change) are dominant threats; P (pollution from biomagnification) significant. Polar bear became symbol of climate change\'s biological impacts.',
      ],
      answer: 'Sea ice loss (H, C) is the dominant threat for polar bears. Pollution (P) bioaccumulates.', estimatedMinutes: 4 },
    { id: 'try-invasive', kind: 'try_yourself',
      problem: 'Burmese pythons in Everglades National Park. (a) How did they get there? (b) Why have they thrived? (c) What\'s the impact? (d) Suggest a management approach.',
      expectedAnswer: '(a) PET TRADE — released by owners (intentionally or accidentally) when snakes outgrew enclosures. Pythons can grow to 5+ meters. \n(b) Thrived because:\n• NO NATURAL PREDATORS in Florida (alligators are theoretical predators but pythons are large/strong). \n• ABUNDANT PREY: small mammals (raccoons, opossums, deer fawn). \n• SUITABLE CLIMATE: subtropical Florida similar to native Burmese habitat. \n• Pythons are r-selected: produce many offspring, fast growth. \n(c) Impact:\n• 95-99% DECLINE in raccoons, opossums, marsh rabbits in deepest Everglades. \n• Cascading effects: predator depletion changes plant communities, wetland dynamics. \n• Estimated millions of pythons in S. Florida. \n• Cannot be eradicated — only controlled. \n(d) Management:\n• PROHIBITION on importation, ownership, breeding (since 2012 in Florida). \n• PYTHON ELIMINATION/REMOVAL programs — bounty hunters paid $50-150 per snake. \n• PUBLIC AWARENESS campaigns, hunting tournaments. \n• Research on attractants and detection (e.g., trained dogs). \n• Long-term: prevention of new invasive species via better pet-trade regulation.',
      responseFormat: 'free', hints: ['Introduction route, success factors, cascade, management.'], estimatedMinutes: 4 },
    { id: 'try-conservation', kind: 'try_yourself',
      problem: 'The bald eagle population recovered from ~400 nesting pairs in 1963 to >70,000 today. Identify three actions that contributed to recovery.',
      expectedAnswer: '(1) DDT BAN (1972) — eliminated source of eggshell thinning. Once DDT cleared from environment, eagle reproduction normalized. \n(2) Endangered Species Act (1973) — listed bald eagle in 1978 as endangered. Protected nests, established Critical Habitat. Federal agencies required to assess impact. \n(3) HABITAT PROTECTION — riparian areas, lake shores where eagles nest preserved. National Wildlife Refuges and Parks. \n(4) CAPTIVE BREEDING + reintroduction — released captive-bred eagles into reduced areas. \n(5) PUBLIC EDUCATION — symbolic species; widespread support for protection. \n(6) HUNTING BANS — prohibited shooting of eagles (some still occur but penalized). \n(7) INTERNATIONAL coordination (Migratory Bird Treaty Act). \n• Bald eagle DELISTED from federal endangered list in 2007. Continues to be protected under Bald and Golden Eagle Protection Act. Recovery story validates ESA approach.',
      responseFormat: 'free', hints: ['Multi-pronged intervention.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. The 6th mass extinction is occurring at 100-1000x background rate. (a) Identify the top THREE drivers. (b) For each, give a specific example. (c) Why is the loss IRREVERSIBLE on human timescales?',
      expectedAnswer: '(a) Top three drivers (HIPPCO):\n1. HABITAT DESTRUCTION (#1 driver). Land conversion for agriculture, urbanization, infrastructure. \n2. CLIMATE CHANGE — increasingly significant. Disrupts species\' ranges, phenology, breeding. \n3. INVASIVE SPECIES — outcompete natives, no natural predators. \n(Plus pollution, overharvesting, but H/I/C are top three.) (1.5)\n(b) Examples:\nH (Habitat destruction): \n• Tropical deforestation in Amazon → orangutan, sumatran tiger, hundreds of unidentified species lost. \n• Wetland drainage → salamander species, migratory birds. \nC (Climate change): \n• Polar bear, walrus, ringed seals → Arctic ice loss. \n• Coral reef fish → ocean warming + acidification. \n• Mountain species running out of altitude (pikas in Sierra Nevada). \nI (Invasive): \n• Burmese pythons in Everglades → mammal collapse. \n• Brown tree snakes in Guam → bird species extinct. \n• Zebra mussels in Great Lakes → native mussel species lost. (3)\n(c) IRREVERSIBLE because:\n• EXTINCTION is FOREVER — once a species\' last individual dies, it cannot return. \n• EVOLUTION of new species takes MILLIONS of years. \n• GENETIC DIVERSITY of lost species cannot be recreated. \n• ECOSYSTEMS that lost species reorganize permanently — cannot be "restored" to exact original. \n• Even with conservation efforts, only a few species rescued from brink (~10s); thousands lost permanently. \n• Many species go extinct UNNAMED (in tropical forests). \n• Cascading effects compound — losing keystone species damages ecosystem function for centuries. \n• 5 previous mass extinctions took 5-25 MILLION years for biodiversity to recover. (2.5)\nTotal: 7 points.',
      responseFormat: 'frq', hints: ['Drivers, examples, irreversibility.'], estimatedMinutes: 6 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'HIPPCO: Habitat, Invasive, Population, Pollution, Climate change, Overexploitation.',
      'Invasive species succeed: no predators + r-selected + suitable climate.',
      'IUCN red list: extinct, critically endangered, endangered, vulnerable.',
      'ESA (1973) — bald eagle, alligator, peregrine recovered.',
      '6th mass extinction: 100-1000× background. Habitat loss + climate are largest.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '9', cedTopic: '9.8-9.10', cedTitle: 'Biodiversity Threats', sources: [{ type: 'concept', book: 'miller-spoolman', chapter: '4,9', note: 'Standard biodiversity threats.' }] },
};
