/**
 * AP Psychology — CED Unit 5 (Disorders): Schizophrenia, Personality
 * Disorders, Other Disorders.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_PSYCH_U5_SCHIZO_PERSONALITY: LessonPlan = {
  id: 'evelyn.ap.psych.schizo-personality.v1', title: 'U5.4 Schizophrenia and Personality Disorders',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-psychology', locale: 'en',
  los: [{ id: 'appsych.schizo-personality', description: 'Identify schizophrenia symptoms and theories. Distinguish dissociative disorders. Identify personality disorders (especially antisocial, borderline). Recognize neurodevelopmental disorders.', standard: 'AP-PSYCH-5-SCHIZO' }],
  prerequisites: ['appsych.mood-disorders'], followUps: ['appsych.therapy'], estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame severe disorders.', script: "SCHIZOPHRENIA is one of the most severe mental illnesses — affects ~1% of population worldwide. Personality disorders affect ~10%. Today: schizo, dissociative, personality, and a glance at neurodevelopmental disorders.", estimatedMinutes: 2 },
    { id: 'concept-disorders', kind: 'concept', goal: 'Cover schizo + personality + dissociative + neurodevelopmental.',
      keyIdeas: [
        'SCHIZOPHRENIA — severe disorder of thought, perception, behavior.',
        '',
        'POSITIVE SYMPTOMS (extra/distorted):',
        '  • DELUSIONS: false beliefs (paranoia, grandiosity, reference).',
        '  • HALLUCINATIONS: sensory experiences without stimulus (most often AUDITORY voices).',
        '  • DISORGANIZED THOUGHT: incoherent speech, loose associations.',
        '  • DISORGANIZED BEHAVIOR.',
        '',
        'NEGATIVE SYMPTOMS (deficits):',
        '  • FLAT AFFECT (reduced emotional expression).',
        '  • ALOGIA (poverty of speech).',
        '  • AVOLITION (lack of motivation).',
        '  • Anhedonia.',
        '  • Social withdrawal.',
        '',
        'COGNITIVE SYMPTOMS:',
        '  • Difficulty concentrating, working memory, executive function.',
        '',
        'ONSET typically late teens to early 20s. Earlier in men.',
        '',
        'PREVALENCE: ~1% lifetime. Cross-cultural similarity in prevalence.',
        '',
        'EXPLANATIONS for schizophrenia:',
        '',
        'BIOLOGICAL:\n  • STRONG GENETIC component (heritability ~80%).\n  • DOPAMINE HYPOTHESIS: excess dopamine in mesolimbic pathway → positive symptoms.\n  • Glutamate also implicated.\n  • Brain abnormalities: enlarged ventricles, decreased gray matter.\n  • Prenatal factors: viral infections, malnutrition during pregnancy increase risk.',
        '',
        'PSYCHOSOCIAL:\n  • STRESS-DIATHESIS: genetic vulnerability + life stress → expression.\n  • EXPRESSED EMOTION (high-EE families: critical, hostile, over-involved) increase relapse.\n  • Migration (cultural displacement) raises rates.',
        '',
        'TREATMENT:\n  • ANTIPSYCHOTIC medication (D2 receptor antagonists). \n     - Typical (older): chlorpromazine, haloperidol — many side effects (tardive dyskinesia).\n     - Atypical (newer): risperidone, olanzapine, clozapine — better for negative symptoms; metabolic side effects.\n  • COGNITIVE BEHAVIORAL THERAPY adapted for psychosis.\n  • FAMILY THERAPY.\n  • SOCIAL SUPPORT and case management.',
        '',
        'DISSOCIATIVE DISORDERS — disruption of consciousness, identity, memory:',
        '',
        'DISSOCIATIVE AMNESIA — inability to recall important personal information after trauma.',
        '',
        'DISSOCIATIVE IDENTITY DISORDER (DID, formerly multiple personality):\n  • Two or more distinct identity states with separate memories/behaviors.\n  • CONTROVERSIAL — some clinicians question diagnostic validity.\n  • Often associated with severe early childhood trauma.\n  • Rare; treatment focuses on integration.',
        '',
        'DEPERSONALIZATION/DEREALIZATION — feeling detached from self/reality. Common in stress.',
        '',
        'PERSONALITY DISORDERS — long-standing maladaptive personality patterns. ~10% of population.',
        '',
        'CLUSTER A (odd/eccentric): paranoid, schizoid, schizotypal.',
        'CLUSTER B (dramatic/emotional): antisocial, borderline, histrionic, narcissistic.',
        'CLUSTER C (anxious/fearful): avoidant, dependent, obsessive-compulsive (different from OCD).',
        '',
        'ANTISOCIAL PERSONALITY DISORDER (ASPD):\n  • Disregard for others\' rights, lack of empathy/remorse.\n  • Manipulation, deceit, impulsivity, aggression, irresponsibility.\n  • Begins before age 15 as conduct disorder.\n  • Often called "psychopathy" in popular usage (technical: psychopathy is more specific).\n  • Heritability + adverse childhood factors.\n  • Most "criminal psychopaths" are subset.',
        '',
        'BORDERLINE PERSONALITY DISORDER (BPD):\n  • Unstable relationships, self-image, emotions.\n  • Intense fear of abandonment.\n  • Self-harm, suicide attempts.\n  • Often associated with childhood trauma.\n  • DIALECTICAL BEHAVIOR THERAPY (DBT) — gold standard treatment.',
        '',
        'NARCISSISTIC PERSONALITY DISORDER:\n  • Grandiosity, lack of empathy, need for admiration.',
        '',
        'NEURODEVELOPMENTAL DISORDERS (briefly for AP):',
        '',
        'AUTISM SPECTRUM DISORDER (ASD):\n  • Social-communication difficulties.\n  • Restricted/repetitive behaviors and interests.\n  • Spectrum severity from severely impaired to "high-functioning."\n  • ~1-2% prevalence.\n  • Strong genetic component; not caused by vaccines (debunked).\n  • Treatment: behavioral therapies (ABA), educational support, communication interventions.',
        '',
        'ADHD (Attention-Deficit/Hyperactivity Disorder):\n  • Inattention, hyperactivity, impulsivity.\n  • Onset childhood; persists into adulthood for many.\n  • Treatment: stimulant medication (methylphenidate, amphetamines), behavioral therapy.',
        '',
        'INTELLECTUAL DISABILITY: significantly below-average intellectual functioning + adaptive behavior deficits.',
      ],
      vocabulary: [
        { term: 'schizophrenia', definition: 'severe disorder; positive (delusions, hallucinations) + negative symptoms.' },
        { term: 'dopamine hypothesis', definition: 'excess dopamine causes positive symptoms of schizophrenia.' },
        { term: 'BPD', definition: 'borderline personality disorder; unstable relationships + emotions.' },
        { term: 'ASPD', definition: 'antisocial personality disorder; lack of empathy and remorse.' },
      ],
      estimatedMinutes: 6 },
    { id: 'worked-schizo', kind: 'worked_example',
      problem: 'A 22-year-old college student begins experiencing: voices commenting on his actions, belief his thoughts are being broadcast on TV, increasingly disorganized speech, withdrawn from friends, hasn\'t bathed in weeks. Diagnose and explain.',
      steps: [
        'STEP 1 — Diagnosis: SCHIZOPHRENIA (likely first episode).',
        'STEP 2 — POSITIVE SYMPTOMS:\n  ✓ Auditory hallucinations (voices commenting).\n  ✓ Delusion of reference (thoughts on TV — a delusion of influence/reference).\n  ✓ Disorganized speech.',
        'STEP 3 — NEGATIVE SYMPTOMS:\n  ✓ Social withdrawal.\n  ✓ Reduced self-care (avolition).',
        'STEP 4 — Onset: late teens/early 20s = typical schizophrenia onset.',
        'STEP 5 — Treatment plan:\n  • IMMEDIATE psychiatric evaluation.\n  • ANTIPSYCHOTIC medication (atypical preferred for first episode).\n  • Often hospitalization for safety initially.\n  • PSYCHOTHERAPY: family therapy, CBT-p (CBT for psychosis), social skills training.\n  • LONG-TERM care: medication adherence, vocational support, supportive housing if needed.',
        'STEP 6 — Prognosis: variable. Earlier diagnosis + treatment → better outcomes. ~25% recover well, ~50% partial recovery, ~25% chronic course.',
      ],
      answer: 'Schizophrenia first episode. Antipsychotic + therapy; early intervention crucial.', estimatedMinutes: 4 },
    { id: 'try-classify', kind: 'try_yourself',
      problem: 'For each scenario, identify the disorder: (a) Patient experiences "another self" who acts differently and has separate memories. (b) Patient repeatedly manipulates others, shows no remorse, has long history of crime. (c) Patient has unstable relationships, intense fear of abandonment, self-harms. (d) Patient hears voices, believes the FBI is monitoring him.',
      expectedAnswer: '(a) DISSOCIATIVE IDENTITY DISORDER (DID) — multiple identity states. \n(b) ANTISOCIAL PERSONALITY DISORDER (ASPD) — disregard for others\' rights, no remorse, criminal pattern. \n(c) BORDERLINE PERSONALITY DISORDER — unstable relationships, abandonment fear, self-harm. \n(d) SCHIZOPHRENIA (or psychotic disorder) — hallucinations + paranoid delusions.',
      responseFormat: 'free', hints: ['Match symptom patterns to disorders.'], estimatedMinutes: 2 },
    { id: 'try-treatment', kind: 'try_yourself',
      problem: 'For schizophrenia and BPD, identify the GOLD STANDARD treatments and explain why they\'re effective.',
      expectedAnswer: 'SCHIZOPHRENIA:\n• ANTIPSYCHOTIC MEDICATION (atypical preferred): risperidone, olanzapine, clozapine. \n  - Block dopamine D2 receptors → reduce positive symptoms (hallucinations, delusions). \n  - Some help with negative symptoms (atypicals better than typicals). \n  - Side effects: metabolic syndrome, sedation, occasionally tardive dyskinesia. \n• Combined with: family therapy, CBT-p, social skills training, vocational support. \n• Continuous treatment generally needed; relapse common if discontinued. \nBPD:\n• DIALECTICAL BEHAVIOR THERAPY (DBT) — Linehan. \n  - Combines CBT with mindfulness. \n  - Skills modules: distress tolerance, emotion regulation, interpersonal effectiveness, mindfulness. \n  - Reduces self-harm, suicide attempts, hospitalizations. \n  - Multiple components: weekly individual therapy, skills group, phone coaching. \n  - Year-long minimum commitment. \n• MEDICATION: variable; SSRIs for depressive symptoms; mood stabilizers sometimes; no single drug is BPD-specific. \n• SCHEMA THERAPY also evidence-based for BPD. \n• DBT had revolutionary impact on BPD treatment (1990s+).',
      responseFormat: 'free', hints: ['Antipsychotics + DBT.'], estimatedMinutes: 4 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Schizophrenia: positive (hallucinations, delusions) + negative (flat affect, withdrawal).',
      'Onset late teens-20s; ~1%; dopamine hypothesis; antipsychotics.',
      'BPD: unstable; DBT gold standard. ASPD: disregard for others.',
      'DID: dissociative identity; controversial diagnosis.',
      'Autism + ADHD: neurodevelopmental; behavioral interventions.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '5', cedTopic: '5-SCHIZO', cedTitle: 'Schizophrenia, Personality, Other Disorders', sources: [{ type: 'concept', book: 'feldman', chapter: '15', note: 'Standard severe disorders.' }] },
};
