/**
 * AP Psychology — CED Unit 4 (Social): Attribution, Attitudes, Cognitive
 * Dissonance.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_PSYCH_U4_ATTRIBUTION_ATTITUDES: LessonPlan = {
  id: 'evelyn.ap.psych.attribution-attitudes.v1', title: 'U4.1 Attribution and Attitudes',
  curriculum: 'AP', grade: '11', subject: 'ss', topic: 'ap-psychology', locale: 'en',
  los: [{ id: 'appsych.attribution-attitudes', description: 'Distinguish dispositional vs situational attributions. Identify fundamental attribution error, self-serving bias, just-world hypothesis. Understand attitudes and cognitive dissonance theory.', standard: 'AP-PSYCH-4-ATTRIBUTION' }],
  prerequisites: [], followUps: ['appsych.social-influence'], estimatedMinutes: 20,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame attribution as biased.', script: "When someone cuts you off in traffic, you assume they\'re a JERK. When YOU cut someone off, it\'s because you\'re LATE. We systematically attribute OTHERS\' actions to their personality, our OWN to circumstances. Today: this and other attribution biases.", estimatedMinutes: 2 },
    { id: 'concept-attribution', kind: 'concept', goal: 'Cover attribution + attitudes + dissonance.',
      keyIdeas: [
        'ATTRIBUTION THEORY (Heider): we explain behavior using one of two causes:',
        '  • DISPOSITIONAL (internal): personality, traits, character.',
        '  • SITUATIONAL (external): circumstances, environment, role.',
        '',
        'FUNDAMENTAL ATTRIBUTION ERROR (FAE):',
        '  • Tendency to OVERESTIMATE dispositional + UNDERESTIMATE situational causes when explaining OTHERS\' behavior.',
        '  • Example: friend is late → "she\'s irresponsible" (dispositional) rather than "she got stuck in traffic" (situational).',
        '  • CULTURAL: stronger in INDIVIDUALIST cultures (US, UK); weaker in COLLECTIVIST (East Asia).',
        '  • SELF-SERVING — we don\'t make this error about ourselves; we attribute OUR failures to situation.',
        '',
        'ACTOR-OBSERVER BIAS:',
        '  • OBSERVER (us watching others) → DISPOSITIONAL attributions.',
        '  • ACTOR (us doing the thing) → SITUATIONAL attributions.',
        '  • Why: when observing others, their action is salient (foreground); when acting, situation is salient.',
        '',
        'SELF-SERVING BIAS:',
        '  • We attribute our SUCCESSES to dispositional (our skill, intelligence).',
        '  • We attribute our FAILURES to situational (bad luck, unfair test).',
        '  • Protects self-esteem.',
        '  • In COLLECTIVIST cultures, sometimes reversed (humble for self, generous for others).',
        '',
        'JUST-WORLD HYPOTHESIS: belief that the world is fair and people get what they deserve.',
        '  • Comforting belief (good things happen to good people).',
        '  • LEADS TO: blaming victims of bad luck or injustice ("they must have done something").',
        '  • Example: blaming poverty on personal failings rather than structural causes.',
        '  • Not always conscious; serves to protect belief in fair world.',
        '',
        'ATTITUDES — beliefs and evaluations of objects, events, or people. Three components:',
        '  • COGNITIVE: beliefs (chocolate is delicious).',
        '  • AFFECTIVE: feelings (I like chocolate).',
        '  • BEHAVIORAL: actions (I eat chocolate).',
        '  • These can MISALIGN: "I should exercise" (cognitive) vs sitting on couch (behavioral).',
        '',
        'COGNITIVE DISSONANCE (Festinger, 1957):',
        '  • UNCOMFORTABLE psychological tension when behavior contradicts beliefs/attitudes.',
        '  • TO REDUCE TENSION:',
        '    1. CHANGE BEHAVIOR (quit smoking).',
        '    2. CHANGE ATTITUDE (decide smoking isn\'t that bad).',
        '    3. ADD JUSTIFICATION (rationalize: "everyone smokes," "I\'ll quit later").',
        '',
        'CLASSIC DISSONANCE EXPERIMENT (Festinger & Carlsmith, 1959):',
        '  • Subjects did boring task; paid $1 OR $20 to lie to next subject saying it was fun.',
        '  • Hypothesis: $20 is ENOUGH justification for lying — no dissonance.',
        '  • $1 is INSUFFICIENT justification — dissonance!',
        '  • Result: $1 group later REPORTED LIKING the task more (changed attitude to match behavior).',
        '  • $20 group: no attitude change.',
        '  • Demonstrates: when behavior is forced by external reward, no dissonance. When behavior is "freely chosen," people change beliefs to match.',
        '',
        'FOOT-IN-THE-DOOR PHENOMENON: agreeing to small request makes you more likely to agree to LARGE request later. Cognitive dissonance: "I helped before, so I must like helping" → bigger help.',
        '',
        'PERSUASION TECHNIQUES exploit dissonance and attribution biases.',
      ],
      vocabulary: [
        { term: 'fundamental attribution error', definition: 'overestimating dispositional and underestimating situational factors in others\' behavior.' },
        { term: 'self-serving bias', definition: 'attributing successes internally, failures externally.' },
        { term: 'cognitive dissonance', definition: 'tension when behavior contradicts attitudes; reduced by changing one.' },
      ],
      estimatedMinutes: 6 },
    { id: 'worked-fae', kind: 'worked_example',
      problem: 'A teacher sees a student fall asleep in class. Apply FAE to predict their attribution and consider the alternative.',
      steps: [
        'STEP 1 — Teacher\'s LIKELY ATTRIBUTION (FAE): "This student is LAZY/UNINTERESTED" (dispositional).',
        'STEP 2 — ALTERNATIVE situational explanation: \n  • Student worked the night shift to support family. \n  • Student has insomnia or a medical issue. \n  • Lecture content not relevant to student\'s interests. \n  • Classroom is too warm + no breakfast. \n  • Hidden circumstances we don\'t know.',
        'STEP 3 — FAE consequences:\n  • Student gets reprimanded for "laziness" \n  • Trust between teacher and student damaged \n  • Real cause not addressed \n  • Student-teacher relationship suffers.',
        'STEP 4 — DEBIASING: assume situational factors first; ask "why" privately. Better outcomes from situational mindset.',
      ],
      answer: 'FAE → assume disposition; alternative is situational; debias by asking, not assuming.', estimatedMinutes: 3 },
    { id: 'try-biases', kind: 'try_yourself',
      problem: 'Identify the bias in each: (a) "I aced the test because I\'m smart" / "I failed the test because the questions were unfair." (b) "She got robbed — she should have known not to walk there." (c) "He\'s yelling because he has a bad temper" (vs "I\'m yelling because traffic is awful").',
      expectedAnswer: '(a) SELF-SERVING BIAS — credit success internally, blame failure externally. \n(b) JUST-WORLD HYPOTHESIS / VICTIM BLAMING — assumes the victim must have done something to deserve their fate; protects belief in fairness. \n(c) FUNDAMENTAL ATTRIBUTION ERROR (or actor-observer bias) — attribute his behavior to disposition (temper) but mine to situation (traffic).',
      responseFormat: 'free', hints: ['Common biases applied.'], estimatedMinutes: 2 },
    { id: 'try-dissonance', kind: 'try_yourself',
      problem: 'A long-time smoker reads an article that smoking causes lung cancer. They feel uncomfortable. (a) What is this discomfort? (b) Three ways they might reduce it.',
      expectedAnswer: '(a) COGNITIVE DISSONANCE — tension between belief ("I want to be healthy") and behavior (smoking). \n(b) Reduction strategies:\n(1) CHANGE BEHAVIOR: quit smoking. Hardest but most direct. \n(2) CHANGE ATTITUDE: "Most studies are exaggerated"; "I\'ll quit when I\'m older"; "My grandfather smoked into his 80s." Discount the threat. \n(3) ADD JUSTIFICATION: "Everyone smokes," "Stress kills more than cigarettes," "Life is for enjoying." \nMost smokers do (2) or (3) rather than (1) initially. Quitting requires acknowledging dissonance and changing behavior. \nADVERTISERS exploit dissonance: showing healthy smokers in ads makes smoking seem less bad. \nPSYCHOLOGISTS use dissonance therapeutically: getting clients to ENGAGE in healthy behavior creates dissonance with old habits.',
      responseFormat: 'free', hints: ['Festinger\'s framework; behavior vs attitude vs justification.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. (a) An employer interviews two job applicants who arrive late. The first claims a flat tire; the employer believes it. The second claims traffic; the employer is suspicious. Apply ATTRIBUTION THEORY. (b) Festinger\'s $1 vs $20 dissonance experiment: explain why the $1 group changed their attitude but the $20 group did NOT.',
      expectedAnswer: '(a) Attribution theory + observer bias:\n• Both situations involve same DISPOSITIONAL outcome (lateness). \n• Employer\'s interpretation depends on AVAILABLE attribution: \n  - Flat tire is SPECIFIC, VERIFIABLE situational cause. Employer accepts. \n  - Traffic is GENERAL, ROUTINE situation. Employer attributes to disposition (this person is unreliable; hasn\'t prepared). \n• Implicit FAE: when situational cause seems weak, dispositional attribution is reflexive. \n• Employer would do better to ask follow-up questions OR assume situational factors typically cause minor issues. (2)\n(b) Festinger\'s experiment:\n• Subjects did BORING task → were paid $1 or $20 to LIE to next subject saying it was fun. \n• THE THREAT to consistency: how can I lie about it being fun if it really wasn\'t? \n• $20 group: PAID HEAVILY for the lie. Sufficient external justification → "I lied because I needed the money." NO DISSONANCE; no need to change attitude. \n• $1 group: PAID NOMINALLY. Cannot rationalize as "for the money." DISSONANCE: "Why did I lie?" To resolve: "Maybe the task wasn\'t SO BORING after all." Attitude shifts to MATCH behavior. \n• Result: when external justification is INSUFFICIENT, attitude changes to match behavior. \n• When external justification is SUFFICIENT, attitude doesn\'t change. \n• KEY INSIGHT: Larger reward = LESS attitude change (counter-intuitive). \n• Implication: persuading people through small (insufficient) inducements creates LASTING attitude change. (3)\nTotal: 5 points.',
      responseFormat: 'frq', hints: ['Apply theory; counter-intuitive Festinger result.'], estimatedMinutes: 5 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Dispositional vs situational attributions. FAE: overestimating disposition in OTHERS.',
      'Self-serving bias: success internal, failure external.',
      'Just-world hypothesis: belief world is fair; can lead to victim-blaming.',
      'Cognitive dissonance: tension reduced by changing behavior, attitude, or justification.',
      'Festinger $1/$20: less external justification → more attitude change.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '4', cedTopic: '4-ATTRIBUTION', cedTitle: 'Attribution and Attitudes', sources: [{ type: 'concept', book: 'feldman', chapter: '14', note: 'Standard attribution + cognitive dissonance.' }] },
};
