/**
 * AP Psychology — CED Unit 4 (Personality): Major Personality Theories.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_PSYCH_U4_PERSONALITY_THEORIES: LessonPlan = {
  id: 'evelyn.ap.psych.personality-theories.v1', title: 'U4.4 Personality Theories',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-psychology', locale: 'en',
  los: [{ id: 'appsych.personality-theories', description: 'Compare four major personality theories: psychodynamic (Freud), humanistic (Maslow, Rogers), trait (Big Five), and social-cognitive (Bandura, Rotter).', standard: 'AP-PSYCH-4-PERSONALITY' }],
  prerequisites: ['appsych.prejudice-stereotypes'], followUps: ['appsych.personality-assessment'], estimatedMinutes: 24,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame personality theories.', script: "Why are people DIFFERENT? Four major theories explain personality. Each emphasizes different forces — unconscious drives (Freud), self-actualization (humanists), stable traits (Big Five), or interaction with environment (social-cognitive). Today: each in turn.", estimatedMinutes: 2 },
    { id: 'concept-theories', kind: 'concept', goal: 'Cover Freud + humanistic + trait + social-cognitive.',
      keyIdeas: [
        'PSYCHODYNAMIC THEORY (Freud, 1900s):',
        '  • Personality emerges from CONFLICT between unconscious drives and conscious controls.',
        '  • THREE STRUCTURES:\n     - ID: instinctual drives (sex, aggression). UNCONSCIOUS. "I want it now."\n     - SUPEREGO: morals, conscience, internalized parental rules.\n     - EGO: realistic mediator. "How do I get it without getting in trouble?"',
        '  • PSYCHOSEXUAL STAGES (controversial): oral (0-1) → anal (1-3) → phallic (3-6, includes Oedipus complex) → latency (6-12) → genital (puberty+).',
        '  • Fixation at any stage → personality issues.',
        '  • DEFENSE MECHANISMS: ego protects itself from anxiety:\n     - REPRESSION: forcing unwanted thoughts to unconscious.\n     - DENIAL: refusing to acknowledge.\n     - PROJECTION: attributing own feelings to others ("you\'re angry, not me").\n     - DISPLACEMENT: redirecting feelings to safer target.\n     - RATIONALIZATION: making excuses.\n     - SUBLIMATION: channeling drives into socially acceptable activities (e.g., aggression → sports).',
        '  • Critics: hard to test scientifically; deterministic; gender-biased; many predictions disproved.',
        '  • Influenced: dream analysis, importance of unconscious, defense mechanisms.',
        '',
        'NEO-FREUDIANS:',
        '  • CARL JUNG: collective unconscious, archetypes, introversion/extraversion.',
        '  • ALFRED ADLER: feelings of inferiority drive striving; birth order influences.',
        '  • KAREN HORNEY: cultural and social factors shape personality more than sexual drives.',
        '',
        'HUMANISTIC THEORY (Maslow, Rogers, 1950s-60s):',
        '  • Reaction against Freud + behaviorism. Emphasizes potential for GROWTH.',
        '  • SELF-ACTUALIZATION (Maslow): fulfilling one\'s POTENTIAL. Top of hierarchy of needs.',
        '  • MASLOW\'S HIERARCHY (memorize from bottom):\n     - PHYSIOLOGICAL (food, water, sleep)\n     - SAFETY (security, stability)\n     - LOVE/BELONGING (relationships, affection)\n     - ESTEEM (achievement, respect)\n     - SELF-ACTUALIZATION (creativity, fulfilling potential)\n     - SELF-TRANSCENDENCE (added later: helping others, spiritual)',
        '  • CARL ROGERS: people have TENDENCY toward growth.',
        '  • KEY: UNCONDITIONAL POSITIVE REGARD — accepting person without conditions. Necessary for healthy self-development.',
        '  • CONDITIONS OF WORTH: when love is conditional, child develops INCONGRUENCE between real self and ideal self → anxiety.',
        '  • THERAPY: Person-Centered Therapy (CLIENT-CENTERED). Therapist provides empathy, genuineness, unconditional positive regard.',
        '',
        'TRAIT THEORY:',
        '  • Personality is a stable set of TRAITS that vary on dimensions.',
        '  • Big Five (FIVE-FACTOR MODEL — OCEAN):\n     - O — OPENNESS: curious, imaginative vs traditional, conventional.\n     - C — CONSCIENTIOUSNESS: organized, reliable vs careless, impulsive.\n     - E — EXTRAVERSION: outgoing, sociable vs quiet, reserved.\n     - A — AGREEABLENESS: trusting, helpful vs argumentative, cold.\n     - N — NEUROTICISM: anxious, moody vs calm, emotionally stable.',
        '  • EVIDENCE: traits relatively STABLE across lifespan, found CROSS-CULTURALLY, predict outcomes (job performance, relationships, longevity).',
        '  • CRITICS: ignores SITUATIONAL factors. Behavior varies by context.',
        '',
        'SOCIAL-COGNITIVE THEORY (Bandura, Rotter):',
        '  • Personality emerges from INTERACTION between person + environment + behavior.',
        '  • RECIPROCAL DETERMINISM: these three factors mutually influence each other.',
        '  • SELF-EFFICACY: belief in your ability to perform tasks. Higher → more effort → more success → reinforces belief.',
        '  • LOCUS OF CONTROL (Rotter):\n     - INTERNAL: outcomes depend on YOUR actions. Associated with achievement, health, persistence.\n     - EXTERNAL: outcomes depend on luck, fate, others. Associated with passivity.',
        '  • Emphasizes COGNITIVE processes + EXPECTATIONS + LEARNED BEHAVIORS.',
        '',
        'BIOPSYCHOSOCIAL APPROACH: integrates biological + psychological + social factors. Modern preferred view.',
      ],
      vocabulary: [
        { term: 'self-actualization', definition: 'fulfilling one\'s potential; top of Maslow\'s hierarchy.' },
        { term: 'unconditional positive regard', definition: 'accepting a person without conditions (Rogers).' },
        { term: 'Big Five (OCEAN)', definition: 'openness, conscientiousness, extraversion, agreeableness, neuroticism.' },
        { term: 'self-efficacy', definition: 'belief in one\'s ability to succeed; influences effort and outcomes.' },
      ],
      estimatedMinutes: 7 },
    { id: 'worked-defense', kind: 'worked_example',
      problem: 'A child who is angry at her mother kicks the family dog instead. (a) Identify the defense mechanism. (b) Why is this typically better understood as Freudian?',
      steps: [
        '(a) DISPLACEMENT — redirecting hostility to a SAFER target. Mother is too dangerous (would punish); dog is helpless and won\'t retaliate.',
        '(b) Why Freudian:\n  • Defense mechanisms are core to Freud\'s ego psychology. \n  • Modern psychology has confirmed that REDIRECTING aggression is real but explains it without Freud\'s structures (id/ego/superego). \n  • COGNITIVE BEHAVIORAL view: child has learned that overt anger toward mom causes problems; redirects to dog as "easier." \n  • EVOLUTIONARY view: aggression toward subordinate is a learned displacement strategy. \n  • Whether you call it "displacement" or simply "redirection," the behavior pattern is robust.',
        '(c) Therapeutic implication: help child SAFELY express anger at the source (talking to parent, healthy outlets). Otherwise pattern continues.',
      ],
      answer: 'Displacement — redirecting feelings to safer target.', estimatedMinutes: 3 },
    { id: 'try-theory-match', kind: 'try_yourself',
      problem: 'For each statement, identify the personality theory it represents: (a) "His issues stem from unresolved conflict in early childhood." (b) "She\'s naturally extraverted; that\'s just who she is." (c) "He\'ll succeed because he believes in his ability to figure it out." (d) "Their behavior depends on the situation, plus their values, plus past learning."',
      expectedAnswer: '(a) PSYCHODYNAMIC (Freudian) — emphasizes early childhood and unconscious conflicts. \n(b) TRAIT (Big Five) — describes a stable personality dimension. \n(c) SOCIAL-COGNITIVE (Bandura) — emphasizes self-efficacy. \n(d) SOCIAL-COGNITIVE (Bandura\'s reciprocal determinism: person × environment × behavior).',
      responseFormat: 'free', hints: ['Match concept to theory.'], estimatedMinutes: 2 },
    { id: 'try-maslow', kind: 'try_yourself',
      problem: 'A homeless person doesn\'t worry about creative fulfillment because they\'re focused on getting food and a safe place to sleep. Apply Maslow\'s hierarchy.',
      expectedAnswer: 'MASLOW\'S HIERARCHY explanation:\n• LOWER NEEDS must be reasonably met before HIGHER NEEDS become priority. \n• PHYSIOLOGICAL (food, sleep) and SAFETY (shelter) needs are foundation. \n• Until these are stable, individuals don\'t pursue LOVE/BELONGING (relationships), ESTEEM (achievement), or SELF-ACTUALIZATION (creativity, growth). \n• MAKES SENSE EVOLUTIONARILY: starvation makes you focus on food, not pottery class. \n• POLICY IMPLICATION: \n  - To support self-actualization, provide stability (housing, food, healthcare) first. \n  - Programs that ONLY focus on personal development without addressing basics are likely ineffective. \n• CRITICISMS: hierarchy isn\'t strict — some people pursue creativity even in distress; cultures emphasize different priorities. \n• Despite limitations, USEFUL FRAMEWORK for understanding human motivation.',
      responseFormat: 'free', hints: ['Lower needs first; situational not just personal.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. (a) Compare FREUD vs the BIG FIVE on whether personality is fixed or changeable. (b) Apply ROGERS\' "unconditional positive regard" to parenting. (c) Critically evaluate Maslow\'s hierarchy.',
      expectedAnswer: '(a) Freud vs Big Five on stability:\n• FREUD: Personality FIXED by ages 5-6 through psychosexual stages. Adult issues stem from childhood fixations. Hard to change without intensive therapy. Largely DETERMINISTIC. \n• BIG FIVE: Traits show STABILITY across adulthood (correlations ~0.7 over 10 years), but DO change gradually. Conscientiousness rises with age; neuroticism declines. Some change is possible through experience and effort. More OPTIMISTIC view than Freud\'s. \nIntermediate view: traits relatively stable (about 50%) but environment can shift specific behaviors. (2)\n(b) ROGERS\' unconditional positive regard in parenting:\n• Parent ACCEPTS child as they are, without making love conditional on behavior or achievement. \n• Doesn\'t mean ACCEPTING all behavior — but distinguishes BEHAVIOR (which can be guided) from PERSON (always loved). \n• "I love you" remains true even when "I don\'t like what you did." \n• PROMOTES healthy self-concept; child develops CONGRUENT self (real self matches ideal). \n• CONDITIONAL love → child develops INCONGRUENCE → anxiety, low self-worth, defensive behaviors. \n• Practical: "I\'m disappointed with this choice" rather than "you\'re a disappointment." (2)\n(c) Maslow\'s hierarchy critique:\n• PROS: Useful intuitive framework. Captures real psychological reality (basic needs do constrain higher needs). Applies cross-culturally to many contexts. \n• CONS: \n  - Hierarchy NOT STRICT. Artists pursue creativity through poverty; saints prioritize self-transcendence over self-care. \n  - CULTURALLY BIASED — some cultures emphasize collective/community needs over individual self-actualization. \n  - Doesn\'t WELL CAPTURE high-order needs of children before age 6. \n  - NEEDS overlap and interact more than hierarchy suggests. \n• Despite limitations, REMAINS pedagogically useful. Modern research extends but doesn\'t fully replace it. (2)\nTotal: 6 points.',
      responseFormat: 'frq', hints: ['Compare theories on stability; apply Rogers; evaluate Maslow.'], estimatedMinutes: 6 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Freud: id/ego/superego; psychosexual stages; defense mechanisms; controversial but historically influential.',
      'Humanistic (Maslow + Rogers): self-actualization; unconditional positive regard.',
      'Trait (Big Five OCEAN): stable cross-cultural dimensions.',
      'Social-cognitive (Bandura): reciprocal determinism, self-efficacy, locus of control.',
      'Modern view: integration; biopsychosocial approach.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '4', cedTopic: '4-PERSONALITY', cedTitle: 'Personality Theories', sources: [{ type: 'concept', book: 'feldman', chapter: '13', note: 'Standard four personality frameworks.' }] },
};
