/**
 * AP Psychology — CED Unit 1.1+1.2: Neurons and Neurotransmitters.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_PSYCH_U1_NEURONS_NEUROTRANSMITTERS: LessonPlan = {
  id: 'evelyn.ap.psych.neurons-neurotransmitters.v1', title: 'U1.1 Neurons and Neurotransmitters',
  curriculum: 'AP', grade: '11', subject: 'ss', topic: 'ap-psychology', locale: 'en',
  los: [{ id: 'appsych.neurons-neurotransmitters', description: 'Identify the parts of a neuron and trace the action potential. Distinguish neurotransmitters and their behavioral effects. Recognize how drugs (agonists vs antagonists) interact with neurotransmitter systems.', standard: 'AP-PSYCH-1.1-1.2' }],
  prerequisites: [], followUps: ['appsych.brain-structures'], estimatedMinutes: 22,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame neurons as the brain\'s building blocks.', script: "Your brain has 86 BILLION neurons. Each one fires up to 200 times per second, communicating via chemicals at junctions called synapses. Today: how a single neuron fires, and how chemical messengers shape your moods, thoughts, and actions.", estimatedMinutes: 2 },
    { id: 'concept-neurons', kind: 'concept', goal: 'Cover neuron structure, action potential, and major neurotransmitters.',
      keyIdeas: [
        'NEURON STRUCTURE:',
        '  • DENDRITES: branching extensions that RECEIVE signals from other neurons.',
        '  • CELL BODY (soma): contains nucleus; integrates incoming signals.',
        '  • AXON: long fiber that CARRIES the signal away from the cell body.',
        '  • MYELIN SHEATH: fatty insulation around axon; speeds signal transmission. Multiple sclerosis attacks myelin → slow/disrupted signals.',
        '  • TERMINAL BUTTONS (axon terminals): release neurotransmitters into synapse.',
        'ACTION POTENTIAL: brief electrical charge that travels down the axon.',
        '  • RESTING POTENTIAL: -70 mV (inside negative relative to outside).',
        '  • THRESHOLD: ~-55 mV. If sum of incoming signals reaches threshold, neuron fires.',
        '  • DEPOLARIZATION: Na⁺ rushes IN; charge briefly becomes positive (+40 mV).',
        '  • REPOLARIZATION: K⁺ rushes OUT; charge returns to negative.',
        '  • REFRACTORY PERIOD: brief recovery before neuron can fire again.',
        '  • ALL-OR-NONE: neuron either fires fully or not at all. Stronger stimulus = MORE neurons firing or HIGHER frequency, not stronger AP.',
        'SYNAPSE: junction between neurons.',
        '  • Action potential reaches axon terminal → triggers vesicles to release NEUROTRANSMITTERS into synaptic cleft.',
        '  • NTs bind to receptors on next neuron\'s dendrites.',
        '  • REUPTAKE: leftover NT is reabsorbed by sending neuron.',
        'MAJOR NEUROTRANSMITTERS (memorize):',
        '  • DOPAMINE (DA): movement, learning, attention, REWARD/PLEASURE. Excess linked to schizophrenia; deficit to Parkinson\'s.',
        '  • SEROTONIN (5-HT): mood, hunger, sleep, arousal. Low levels linked to DEPRESSION (SSRIs increase it).',
        '  • NOREPINEPHRINE (NE): alertness, arousal, fight-or-flight. Low levels linked to depression.',
        '  • GABA: major INHIBITORY NT. Reduces neuronal activity. Low levels linked to anxiety, seizures.',
        '  • GLUTAMATE: major EXCITATORY NT. Memory formation. Excess can over-stimulate (seizures, migraines).',
        '  • ACETYLCHOLINE (ACh): muscle action, memory. Alzheimer\'s linked to ACh deficit.',
        '  • ENDORPHINS: natural painkillers, "runner\'s high." Released during exercise, pain, eating chocolate.',
        '  • SUBSTANCE P: pain perception.',
        'AGONISTS vs ANTAGONISTS:',
        '  • AGONIST: drug that MIMICS or ENHANCES a neurotransmitter\'s action (binds to receptor and activates). E.g., morphine (mimics endorphins), nicotine (ACh agonist), cocaine (DA reuptake inhibitor).',
        '  • ANTAGONIST: drug that BLOCKS a neurotransmitter\'s action (binds to receptor without activating). E.g., antipsychotics (DA antagonists), atropine (ACh antagonist).',
      ],
      vocabulary: [
        { term: 'action potential', definition: 'electrical signal traveling down an axon.' },
        { term: 'neurotransmitter', definition: 'chemical messenger released at synapse.' },
        { term: 'agonist', definition: 'drug that mimics or enhances a neurotransmitter.' },
        { term: 'antagonist', definition: 'drug that blocks a neurotransmitter\'s action.' },
      ],
      estimatedMinutes: 7 },
    { id: 'worked-action', kind: 'worked_example',
      problem: 'Trace the path of a signal from your finger touching a hot stove to the moment your spinal cord triggers your hand to pull away.',
      steps: [
        '(1) HEAT receptors on finger SKIN activate sensory neurons.',
        '(2) SENSORY NEURON sends action potential up arm — Na⁺ rushes in, K⁺ out, depolarization-repolarization cycle propagates along myelinated axon at ~120 m/s.',
        '(3) Signal arrives at axon terminal in SPINAL CORD. Vesicles release NT (typically GLUTAMATE) into synaptic cleft.',
        '(4) NT binds to interneuron receptors → action potential in INTERNEURON.',
        '(5) Interneuron synapses with MOTOR NEURON. Motor neuron sends action potential down arm to bicep muscles.',
        '(6) Motor neuron releases ACETYLCHOLINE at neuromuscular junction → muscles contract → hand pulls away.',
        '(7) THE BRAIN gets the "ouch" signal AFTER the spinal-cord reflex already moved the hand. This reflex arc protects you faster than conscious processing would.',
      ],
      answer: 'Sensory neuron → spinal cord interneuron → motor neuron → muscle. Reflex arc.', estimatedMinutes: 4 },
    { id: 'try-nt', kind: 'try_yourself',
      problem: 'Match each neurotransmitter to its primary effect: (a) Dopamine. (b) Serotonin. (c) GABA. (d) Acetylcholine. (e) Endorphins.',
      expectedAnswer: '(a) Dopamine — REWARD, pleasure, movement (Parkinson\'s = low DA in motor regions). \n(b) Serotonin — MOOD, sleep (SSRI antidepressants raise it). \n(c) GABA — INHIBITION, calming (reduces neural activity; benzodiazepines enhance). \n(d) Acetylcholine — MUSCLE movement, memory (Alzheimer\'s = low ACh). \n(e) Endorphins — natural PAIN RELIEF (released during exercise, "runner\'s high").',
      responseFormat: 'free', hints: ['Memorize: DA reward, 5-HT mood, GABA inhibitory, ACh memory/muscle, endorphin pain.'], estimatedMinutes: 3 },
    { id: 'try-agonist', kind: 'try_yourself',
      problem: 'For each drug, identify whether it is an agonist or antagonist of its target neurotransmitter system: (a) Cocaine (blocks dopamine reuptake → more DA in synapse). (b) Antipsychotics (block dopamine receptors). (c) Caffeine (blocks adenosine receptors).',
      expectedAnswer: '(a) Cocaine: AGONIST effect on dopamine system (more DA available). Result: increased reward signaling, euphoria, addiction risk. \n(b) Antipsychotics: ANTAGONIST of dopamine receptors. Reduces dopamine signaling — used to treat schizophrenia (excess DA hypothesis). Side effects can mimic Parkinson\'s. \n(c) Caffeine: ANTAGONIST of adenosine (blocks the "sleepy" signal). Result: feels stimulating because adenosine inhibition is removed.',
      responseFormat: 'free', hints: ['Block receptor = antagonist; mimic/boost NT = agonist.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. SSRIs (selective serotonin reuptake inhibitors) like Prozac are commonly prescribed for depression. (a) Explain mechanism using neurotransmitter terminology. (b) Why might it take 4-6 weeks to feel effects? (c) What is the proposed link between serotonin and depression?',
      expectedAnswer: '(a) MECHANISM: SSRIs block SEROTONIN REUPTAKE. After serotonin is released into the synapse, the sending neuron normally reabsorbs leftover NT. SSRIs inhibit that reuptake → MORE serotonin remains in synaptic cleft → more serotonin binding to receptors. SSRIs are technically AGONISTS at the system level (more 5-HT signaling). (2)\n(b) DELAY: while serotonin levels rise within hours, downstream brain changes take WEEKS:\n• Receptor sensitivity slowly adjusts. \n• Gene expression patterns shift. \n• New neural connections form (neurogenesis). \n• Mood circuits gradually re-regulate. \nSimilar mechanism in many psychiatric medications. (1.5)\n(c) PROPOSED LINK: serotonin deficiency or dysregulation contributes to depression. Lower serotonin → less mood regulation, sleep disturbances, anhedonia. By raising serotonin, SSRIs help restore normal function for many (but not all) depressed patients. \nCAVEATS: \n• Not all depressions are serotonin-mediated. \n• Some patients don\'t respond to SSRIs. \n• Newer research suggests inflammation, network connectivity, and neuroplasticity are also involved. \n• Depression is multi-factorial. (1.5)\nTotal: 5 points.',
      responseFormat: 'frq', hints: ['Mechanism, delay rationale, theory.'], estimatedMinutes: 5 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Neuron parts: dendrite (receive), soma, axon (send), myelin (speed), terminal (release NT).',
      'Action potential: -70 mV resting → threshold → Na⁺ in → +40 mV → K⁺ out → reset. All-or-none.',
      'NTs: DA reward, 5-HT mood, NE alertness, GABA inhibitory, ACh muscle/memory, endorphin pain.',
      'Agonist mimics/boosts NT; antagonist blocks NT.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '1', cedTopic: '1.1-1.2', cedTitle: 'Neurons and Neurotransmitters', sources: [{ type: 'concept', book: 'feldman', chapter: '2', note: 'Standard biological psychology.' }] },
};
