/**
 * AP Psychology — Unit 3 FRQ Practice.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_PSYCH_U3_FRQ_PRACTICE: LessonPlan = {
  id: 'evelyn.ap.psych.u3-frq-practice.v1', title: 'U3 FRQ Practice',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-psychology', locale: 'en',
  los: [{ id: 'appsych.u3-frq-practice', description: 'Apply Unit 3 development and learning concepts to AP-style FRQs.', standard: 'AP-PSYCH-3-FRQ' }],
  prerequisites: ['appsych.observational-learning'], followUps: [], estimatedMinutes: 26,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Stakes.', script: "Three Unit 3 FRQs: development theories, classical/operant conditioning, observational learning.", estimatedMinutes: 2 },
    { id: 'concept-strategy', kind: 'concept', goal: 'Refresh.', keyIdeas: [
      'Piaget 4 stages; Vygotsky ZPD + scaffolding.',
      'Erikson 8 stages; attachment styles.',
      'Kohlberg: preconventional → conventional → postconventional.',
      'Classical conditioning (Pavlov): UCS, UCR, CS, CR.',
      'Operant conditioning (Skinner): reinforce/punish + positive/negative; schedules (FR/VR/FI/VI).',
      'Observational learning (Bandura): attention, retention, reproduction, motivation.',
    ], estimatedMinutes: 2 },
    { id: 'try-frq-development', kind: 'try_yourself',
      problem: 'FRQ Practice 1 — Development. A 5-year-old child is described by parents: "She thinks her shadow is alive. She insists there\'s more juice in a tall narrow glass than the same juice in a short wide glass. She gets upset when other children won\'t play exactly her way." (a) Identify the cognitive-development stage. (b) Match each behavior to a Piagetian concept. (c) Predict what cognitive abilities will emerge in 2-3 years.',
      expectedAnswer: '(a) PREOPERATIONAL stage (2-7 years). (1)\n(b) Behaviors match:\n• Shadow alive: ANIMISM — attributing life to inanimate objects. Common in preoperational. \n• Tall glass = "more": LACK OF CONSERVATION + CENTRATION on one dimension (height) without considering width. \n• Insisting others play her way: EGOCENTRISM — cannot take others\' perspectives. (2)\n(c) Around age 7+ (transitioning to CONCRETE OPERATIONAL):\n• MASTERS CONSERVATION — understands quantity stays constant. \n• Better PERSPECTIVE-TAKING (theory of mind develops; egocentrism declines). \n• Logical reasoning about CONCRETE problems. \n• Mental math operations. \n• Understanding REVERSIBILITY (operations can be undone). \n• Animism gradually fades. \n• These cognitive shifts happen gradually around age 6-7 as concrete operational stage begins. (1.5)\nTotal: 4.5 points.',
      responseFormat: 'frq', hints: ['Identify stage; match concepts; predict transition.'], estimatedMinutes: 5 },
    { id: 'try-frq-conditioning', kind: 'try_yourself',
      problem: 'FRQ Practice 2 — Conditioning. A child develops a fear of dogs after being bitten by one (UCS). Now she runs from any dog. (a) Identify CS, CR, UCS, UCR. (b) Suggest a treatment using classical-conditioning principles. (c) Compare with how OPERANT conditioning could maintain the fear. (d) Identify ONE schedule of reinforcement and explain why it produces strong, persistent behavior.',
      expectedAnswer: '(a) Components:\n• UCS: dog BITE — naturally causes fear/pain. \n• UCR: pain, fear (natural reaction to bite). \n• CS: any DOG (originally neutral, but now triggers fear after pairing with bite). \n• CR: fear, running away (learned response to dog). (1.5)\n(b) Treatment via SYSTEMATIC DESENSITIZATION:\n1. Build hierarchy from least to most fearful: pictures of dogs → small toy dog → film of dogs → real dog at distance → close real dog. \n2. Train RELAXATION (deep breathing, progressive muscle relaxation). \n3. Pair RELAXATION with each level of hierarchy, gradually moving up. \n4. The CR (fear) is replaced by RELAXATION. Counter-conditioning. \n5. Or EXPOSURE THERAPY: prolonged exposure in safe context → extinction of fear response. \n6. Effective in 70-90% of specific phobias. (2.5)\n(c) OPERANT CONDITIONING maintaining fear:\n• When child sees dog → fears → runs away. \n• Running provides ESCAPE from feared situation = NEGATIVE REINFORCEMENT (removes anxiety). \n• Negative reinforcement strengthens the avoidance behavior. \n• Each successful escape REINFORCES the avoidance, making it MORE likely next time. \n• This is why phobias are PERSISTENT — they self-reinforce through avoidance. (2)\n(d) VARIABLE RATIO (VR) schedule produces strong, persistent behavior:\n• Reward delivered after AVERAGE n responses but unpredictable timing. \n• Highest response rate of all schedules. \n• Most resistant to extinction. \n• Examples: slot machines, fishing, gambling. \n• Animal/human keeps responding because next response might be the rewarded one. \n• Essentially the behavior MAY pay off, so subject keeps trying. \n• Why VR is important in addiction research and habit formation. (2)\nTotal: 8 points.',
      responseFormat: 'frq', hints: ['Components; treatment; operant maintenance; powerful schedule.'], estimatedMinutes: 6 },
    { id: 'try-frq-observational', kind: 'try_yourself',
      problem: 'FRQ Practice 3 — Observational Learning. (a) Bandura\'s Bobo doll experiment: identify the FOUR components of observational learning required for imitation. (b) Explain why violent video games might or might not increase aggressive behavior in children, using Bandura\'s framework. (c) Identify ONE ETHICAL concern with the Bobo doll experiment and how modern researchers would address it.',
      expectedAnswer: '(a) Four components:\n1. ATTENTION — child observes the model carefully. \n2. RETENTION — child remembers what was observed. \n3. REPRODUCTION — child has the physical/cognitive capacity to reproduce the action. \n4. MOTIVATION — child has reason to perform (vicarious reinforcement, intrinsic interest, or external reward). \nAll 4 must be present for imitation to occur. (2)\n(b) Violent video games and aggression — Bandura\'s framework:\n• ATTENTION: child watches violent characters perform aggressive acts. \n• RETENTION: child remembers specific aggressive sequences. \n• REPRODUCTION: child has motor capacity to reproduce simple aggression (yelling, hitting). \n• MOTIVATION: depends on whether aggression is REWARDED in game (often is — game shows kills as desirable). VICARIOUS REINFORCEMENT operating. \nMODELS that PREDICT aggression increase: \n• Games with rewarded violence. \n• Realistic depictions. \n• Heavy/prolonged play. \nMODELS that PREDICT minimal effect: \n• Games where consequences are clear (anti-violence message). \n• Brief play. \n• Clear distinction between game and reality. \nResearch is MIXED — some studies show modest aggression increase; others find no effect. Effect smaller than parents/critics worry but exists in some contexts. \nALSO: violent media research subject to selection effects (aggressive children may seek violent games, not the reverse). (3)\n(c) Ethical concerns with Bobo doll experiment:\n1. Children EXPOSED to aggressive behavior; could be traumatic for some. \n2. Children may have learned aggressive behaviors that persist outside lab. \n3. Researchers did not DEBRIEF / extinguish learned aggression after experiment. \n4. INFORMED CONSENT from young children questionable. \nMODERN approach (IRB review, Belmont Report principles):\n• Study would likely require detailed parent consent + age-appropriate explanation to children. \n• De-escalation/debriefing required. \n• Minimize harm: use less-aggressive models, briefer exposure, or retrospective methodology (e.g., observing behavior in natural settings). \n• If conducted today, IRB might require alternatives or mitigation. (2)\nTotal: 7 points.',
      responseFormat: 'frq', hints: ['4 components; apply to media; ethical reflection.'], estimatedMinutes: 6 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Specific case studies: Piaget stages, Bobo doll, Pavlov dogs, Skinner rats.',
      'Conditioning: classical (passive association) vs operant (consequence-driven) vs observational (modeling).',
      'Development theories: Piaget, Erikson, Kohlberg, attachment, Vygotsky.',
      'AP rewards specific examples and theory application to scenarios.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '3', cedTopic: '3-FRQ', cedTitle: 'Unit 3 FRQ Practice', sources: [{ type: 'frq-style', source: 'AP Plans Initiative author', note: 'Modeled on AP Psych Unit-3 FRQs.' }] },
};
