/**
 * AP Psychology — CED Unit 3 (Learning): Operant Conditioning.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_PSYCH_U3_OPERANT_CONDITIONING: LessonPlan = {
  id: 'evelyn.ap.psych.operant-conditioning.v1', title: 'U3.4 Operant Conditioning (Skinner)',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-psychology', locale: 'en',
  los: [{ id: 'appsych.operant-conditioning', description: 'Distinguish positive vs negative reinforcement and punishment. Identify reinforcement schedules (fixed/variable, ratio/interval). Understand shaping and the role of consequences.', standard: 'AP-PSYCH-3-OPERANT' }],
  prerequisites: ['appsych.classical-conditioning'], followUps: ['appsych.observational-learning'], estimatedMinutes: 22,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame consequence-driven learning.', script: "Pavlov\'s dogs learned PASSIVE associations. Skinner\'s rats learned by ACTING on the world. Push a lever → get food. Push wrong button → get shocked. Behavior is shaped by CONSEQUENCES. Today: the most powerful framework for understanding behavior change.", estimatedMinutes: 2 },
    { id: 'concept-operant', kind: 'concept', goal: 'Cover reinforcement vs punishment + schedules + shaping.',
      keyIdeas: [
        'OPERANT CONDITIONING: learning by CONSEQUENCES of behavior. Behavior + consequence → behavior repeated or not.',
        '',
        'THORNDIKE\'S LAW OF EFFECT (1898): behaviors followed by good outcomes become MORE likely; bad outcomes → LESS likely. Foundation for Skinner.',
        '',
        'SKINNER (1930s+): formalized + experimentally studied with operant chambers ("Skinner boxes").',
        '',
        'KEY DISTINCTION — Reinforcement vs Punishment:',
        '  • REINFORCEMENT: increases behavior.',
        '  • PUNISHMENT: decreases behavior.',
        '',
        'POSITIVE vs NEGATIVE refers to ADDING vs REMOVING something:',
        '',
        'POSITIVE REINFORCEMENT: ADD a desirable stimulus → behavior INCREASES.\n  • Give child candy for cleaning room → child cleans more.\n  • Bonus pay for high performance → more high performance.',
        '',
        'NEGATIVE REINFORCEMENT: REMOVE an unpleasant stimulus → behavior INCREASES.\n  • Seatbelt buzzer stops when you buckle → buckling increases.\n  • Aspirin removes headache → take aspirin more often.\n  • NEGATIVE ≠ BAD. It\'s about removing aversive stimulus.',
        '',
        'POSITIVE PUNISHMENT: ADD an unpleasant stimulus → behavior DECREASES.\n  • Spanking, yelling, fines.\n  • Less effective than reinforcement; can have side effects (fear, aggression, modeling).',
        '',
        'NEGATIVE PUNISHMENT (or RESPONSE COST): REMOVE a desirable stimulus → behavior DECREASES.\n  • Take away phone for misbehavior.\n  • Time-out from fun activity.\n  • License revocation.',
        '',
        '4 BOX SUMMARY:\n  | | Add | Remove |\n  |Increase|+R|−R|\n  |Decrease|+P|−P|',
        '',
        'PRIMARY vs SECONDARY reinforcers:',
        '  • PRIMARY: innately reinforcing (food, water, sleep, sex). Don\'t require learning.',
        '  • SECONDARY: learned to associate with primary. Money, grades, praise, tokens. Become reinforcing through pairing.',
        '',
        'REINFORCEMENT SCHEDULES (memorize):',
        '',
        'CONTINUOUS reinforcement: reward EVERY response. Fast learning, fast extinction.',
        '',
        'INTERMITTENT (partial) reinforcement: reward SOME responses. Slower learning but RESISTANT TO EXTINCTION.',
        '',
        '4 PARTIAL SCHEDULES:',
        '',
        'FIXED RATIO (FR): reward every Nth response. Worker paid per piece. Predictable. Steady high response rate, brief pause after reinforcement.',
        '',
        'VARIABLE RATIO (VR): reward after AVERAGE of N responses (variable). Slot machines, fishing. UNPREDICTABLE. Highest, steadiest response rate. MOST RESISTANT to extinction.',
        '',
        'FIXED INTERVAL (FI): reward first response after N seconds. Paychecks, mail check. Response increases as time approaches.',
        '',
        'VARIABLE INTERVAL (VI): reward first response after AVERAGE N seconds (variable). Pop quizzes, checking phone for messages. Steady moderate rate.',
        '',
        'RATIO > interval for response rate.\nVARIABLE > fixed for resistance to extinction.\nVR (variable ratio) is the MOST POWERFUL — slot machines exploit it.',
        '',
        'SHAPING: gradually approximating a desired behavior through successive REINFORCEMENT of closer approximations.\n  • Train rat to push lever: first reinforce any movement, then movement toward lever, then touching, then pushing. Steps build the behavior.\n  • Used in animal training, language teaching for autism, athletic skills.',
        '',
        'EXTINCTION (operant): when reinforcement stops, behavior eventually stops. Slower for VR than continuous schedules.',
        '',
        'PUNISHMENT EFFECTIVENESS:\n  • Effective if: immediate, consistent, mild, alternative behavior reinforced.\n  • Ineffective if: delayed, inconsistent, severe, no alternative offered.\n  • Side effects: fear of punisher, aggression, suppression doesn\'t teach right behavior.\n  • Generally REINFORCEMENT preferred over punishment.',
      ],
      vocabulary: [
        { term: 'positive reinforcement', definition: 'add desirable stimulus → behavior increases.' },
        { term: 'negative reinforcement', definition: 'remove unpleasant stimulus → behavior increases.' },
        { term: 'variable ratio (VR)', definition: 'reinforce after avg N responses; most resistant to extinction.' },
        { term: 'shaping', definition: 'reinforce successive approximations of desired behavior.' },
      ],
      estimatedMinutes: 7 },
    { id: 'worked-classify', kind: 'worked_example',
      problem: 'For each scenario, identify reinforcement type: (a) Sister gives child cookie for finishing homework. (b) Mom stops nagging when child cleans room. (c) Dog gets shock for chasing cars. (d) Take child\'s video game away for hitting sibling.',
      steps: [
        '(a) POSITIVE REINFORCEMENT — ADD cookie (good) → behavior INCREASES (homework completion). +R.',
        '(b) NEGATIVE REINFORCEMENT — REMOVE nagging (bad) → behavior INCREASES (cleaning). −R. Note: this is reinforcement (increases behavior), not punishment.',
        '(c) POSITIVE PUNISHMENT — ADD shock (bad) → behavior DECREASES (chasing cars). +P.',
        '(d) NEGATIVE PUNISHMENT — REMOVE video game (good) → behavior DECREASES (hitting). −P.',
      ],
      answer: '(a) +R, (b) -R, (c) +P, (d) -P. The four-box framework.', estimatedMinutes: 4 },
    { id: 'try-schedules', kind: 'try_yourself',
      problem: 'Match each to a reinforcement schedule (FR, VR, FI, VI): (a) Slot machines. (b) Hourly wage. (c) Salesperson on commission per sale. (d) Workers expect paychecks every 2 weeks.',
      expectedAnswer: '(a) VARIABLE RATIO (VR) — pays out after average of N pulls but unpredictable. Most resistant to extinction; why gambling so addictive. \n(b) FIXED INTERVAL (FI) — paid every X hours. Workers may slow as paycheck approaches. \n(c) FIXED RATIO (FR) — paid per sale (every Nth response). Drives high response rates. \n(d) FIXED INTERVAL (FI) — every 2 weeks predictably. Workers know when to expect.',
      responseFormat: 'free', hints: ['Predictable count = fixed; unpredictable = variable. Time = interval; count = ratio.'], estimatedMinutes: 3 },
    { id: 'try-shaping', kind: 'try_yourself',
      problem: 'A teacher wants to shape a student to raise their hand instead of calling out. Describe the shaping procedure.',
      expectedAnswer: 'Apply successive reinforcement of approximations:\n• Step 1 — Reinforce ANY hand-raising, even when calling out simultaneously. \n• Step 2 — Reinforce hand-raising only when the calling-out is shorter. \n• Step 3 — Reinforce hand-raising before answering. \n• Step 4 — Reinforce hand-raising AND staying silent. \n• Step 5 — Eventually only reinforce raising hand without calling out at all.\nReinforcement could be: praise, points, recess, etc. \nGradually withdraw external rewards as behavior becomes habit. \nShaping makes complex behavior achievable through small steps.',
      responseFormat: 'free', hints: ['Successive approximations to target.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. (a) Why are slot machines so addictive in operant terms? (b) Why is REINFORCEMENT generally preferred over PUNISHMENT in behavior modification? (c) An animal trainer is teaching a dog to roll over. Apply OPERANT principles.',
      expectedAnswer: '(a) SLOT MACHINES use VARIABLE RATIO REINFORCEMENT — payouts after random number of pulls. Effects:\n• HIGHEST RESPONSE RATE — gambler keeps pulling lever expecting payoff.\n• MOST RESISTANT TO EXTINCTION — even after many losing pulls, gambler thinks "next one might be it."\n• ANIMALS show same pattern (lab rats, slot-machine like apparatus).\n• Combined with: lights, sounds (secondary reinforcers paired with primary reward), social environment, easy access.\n• Lottery, video games, fishing, cold-calling sales, social media notifications all exploit VR.\n• Designed to maximize compulsion. (2)\n(b) REINFORCEMENT > PUNISHMENT because:\n• Reinforcement TEACHES the desired behavior; punishment only suppresses unwanted.\n• Reinforcement creates POSITIVE associations with the trainer/system; punishment creates AVOIDANCE.\n• Punishment can produce side effects: fear, aggression, withdrawal, learned helplessness.\n• Punishment requires escalation as tolerance develops; reinforcement maintains effectiveness.\n• Punished behaviors return when punishment is absent; reinforced behaviors persist.\n• Children punished for behavior may develop AGGRESSION (modeling) or FEAR.\n• Modern applied behavior analysis (ABA): reinforcement-first; punishment as last resort. (2)\n(c) Teaching a dog to roll over (shaping):\n• REWARDS: small treats, praise (primary + secondary reinforcers).\n• Step 1: Reinforce dog when it lies down. \n• Step 2: Reinforce when dog tilts head while lying. \n• Step 3: Reinforce when dog rolls partly to side. \n• Step 4: Reinforce full half-roll. \n• Step 5: Reinforce full roll-over. \n• Eventually, can use VARIABLE RATIO to maintain behavior with intermittent treats. \n• ADD CUE (verbal "roll over") only after behavior is shaped — pair the cue with the behavior. (2)\nTotal: 6 points.',
      responseFormat: 'frq', hints: ['VR exploitation; reinforcement vs punishment; shaping example.'], estimatedMinutes: 6 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Reinforcement (increase) vs Punishment (decrease). Positive (add) vs Negative (remove).',
      'Schedules: FR, VR (most powerful), FI, VI. Variable > fixed in resistance to extinction.',
      'Shaping: reinforce successive approximations.',
      'Reinforcement preferred over punishment for behavior change.',
      'Slot machines, lotteries exploit VR — why so addictive.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '3', cedTopic: '3-OPERANT', cedTitle: 'Operant Conditioning', sources: [{ type: 'concept', book: 'feldman', chapter: '6', note: 'Standard Skinner + operant.' }] },
};
