/**
 * AP Psychology — CED Unit 5 (Disorders): Anxiety, OCD, PTSD.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_PSYCH_U5_ANXIETY_DISORDERS: LessonPlan = {
  id: 'evelyn.ap.psych.anxiety-disorders.v1', title: 'U5.2 Anxiety, OCD, PTSD',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-psychology', locale: 'en',
  los: [{ id: 'appsych.anxiety-disorders', description: 'Distinguish generalized anxiety disorder, panic disorder, phobias, OCD, PTSD. Identify diagnostic criteria, prevalence, and theoretical explanations.', standard: 'AP-PSYCH-5-ANXIETY' }],
  prerequisites: ['appsych.stress-health'], followUps: ['appsych.mood-disorders'], estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame anxiety as a major mental health category.', script: "ANXIETY is the most common psychiatric concern. ~30% of people will experience an anxiety disorder. Today: GAD, panic, phobias, OCD, and PTSD — and how they\'re distinguished.", estimatedMinutes: 2 },
    { id: 'concept-anxiety', kind: 'concept', goal: 'Cover anxiety disorders, OCD, PTSD.',
      keyIdeas: [
        'PSYCHOLOGICAL DISORDERS DEFINED: persistent disturbance in thinking, emotion, or behavior that causes distress + impairs functioning. DSM-5 (Diagnostic and Statistical Manual) is the classification used.',
        '',
        'GENERALIZED ANXIETY DISORDER (GAD):',
        '  • Persistent uncontrollable worry about MULTIPLE areas of life.',
        '  • > 6 months duration.',
        '  • Includes physical symptoms (muscle tension, fatigue, sleep disruption).',
        '  • Free-floating anxiety — not tied to specific stimulus.',
        '  • Prevalence: ~3% lifetime.',
        '',
        'PANIC DISORDER:',
        '  • Recurrent SUDDEN PANIC ATTACKS — intense fear with physical symptoms (racing heart, difficulty breathing, dizziness, "going crazy").',
        '  • Often misinterpreted as heart attack.',
        '  • Anticipatory anxiety about future attacks.',
        '  • Often leads to avoidance of places where attacks occurred.',
        '  • Prevalence: ~3% lifetime.',
        '',
        'PHOBIAS:',
        '  • SPECIFIC phobias: irrational fear of specific object/situation (spiders, flying, heights, blood).',
        '  • SOCIAL phobia (social anxiety disorder): fear of social judgment.',
        '  • AGORAPHOBIA: fear of places where escape is difficult (crowds, transportation, being alone). Often comorbid with panic.',
        '  • Prevalence: 12% lifetime for specific phobias (most common).',
        '',
        'OBSESSIVE-COMPULSIVE DISORDER (OCD):',
        '  • Originally classified as anxiety; now its own DSM-5 category.',
        '  • OBSESSIONS: intrusive recurrent thoughts (germs, harm, order).',
        '  • COMPULSIONS: repetitive behaviors (washing, checking, counting) to reduce anxiety from obsessions.',
        '  • Patients KNOW behaviors are excessive but cannot stop.',
        '  • TIME-CONSUMING (>1 hour/day) and impairing.',
        '  • Prevalence: ~1-2%.',
        '',
        'POST-TRAUMATIC STRESS DISORDER (PTSD):',
        '  • Following exposure to traumatic event (combat, assault, disaster).',
        '  • SYMPTOMS:\n     - INTRUSIVE memories (flashbacks, nightmares).\n     - AVOIDANCE of trauma reminders.\n     - NEGATIVE alterations in cognition/mood.\n     - HYPERAROUSAL (jumpy, irritable, sleep problems).',
        '  • >1 month duration after trauma.',
        '  • Prevalence: ~7% lifetime; higher in combat veterans (15-30%).',
        '  • Treatments: CBT, EMDR (eye movement desensitization + reprocessing), exposure therapy, SSRIs.',
        '',
        'EXPLANATIONS for anxiety disorders:',
        '',
        'BIOLOGICAL:\n  • GENETICS: heritability ~30-40%.\n  • NEUROTRANSMITTERS: low GABA (calming), high norepinephrine (arousal), serotonin imbalances.\n  • Brain: hyperactive AMYGDALA + dampened prefrontal regulation.',
        '',
        'COGNITIVE:\n  • Catastrophic thinking, attention bias toward threat.\n  • Beck\'s cognitive theory: distorted thinking patterns.',
        '',
        'BEHAVIORAL (LEARNING):\n  • Classical conditioning of fear (Watson\'s Little Albert principles).\n  • Negative reinforcement maintains avoidance (reduces anxiety → strengthens avoidance).',
        '',
        'PSYCHODYNAMIC: unresolved unconscious conflicts (controversial).',
        '',
        'EVOLUTIONARY: anxiety circuits prepared us for ancestral threats; now misfires.',
        '',
        'TREATMENTS for anxiety:\n  • CBT (cognitive-behavioral therapy) — gold standard for most anxiety disorders.\n  • EXPOSURE therapy — gradually face fears (desensitization).\n  • SSRIs / SNRIs (medications).\n  • RELAXATION training.\n  • MINDFULNESS-based therapies.',
      ],
      vocabulary: [
        { term: 'GAD', definition: 'generalized anxiety disorder — chronic broad worry.' },
        { term: 'panic disorder', definition: 'recurrent unexpected panic attacks + anticipatory anxiety.' },
        { term: 'OCD', definition: 'obsessions (thoughts) + compulsions (behaviors); time-consuming.' },
        { term: 'PTSD', definition: 'post-traumatic stress disorder; intrusive symptoms + hyperarousal after trauma.' },
      ],
      estimatedMinutes: 6 },
    { id: 'worked-disorder', kind: 'worked_example',
      problem: 'A patient describes: "I can\'t leave my house without checking the stove 7 times. I know it\'s irrational, but if I don\'t, I feel intense anxiety." Diagnose and explain.',
      steps: [
        'STEP 1 — Diagnosis: OBSESSIVE-COMPULSIVE DISORDER (OCD).',
        'STEP 2 — Components present:\n  • OBSESSION: intrusive thought about stove being on (or causing harm).\n  • COMPULSION: ritualistic checking (7 times specifically — common rigid pattern).\n  • Anxiety relief from compulsion.\n  • Patient knows it\'s irrational but can\'t stop.',
        'STEP 3 — Mechanism: \n  • Obsession creates anxiety. \n  • Compulsion temporarily reduces anxiety (negative reinforcement). \n  • This REINFORCES the compulsive behavior. \n  • Anxiety returns; cycle continues.',
        'STEP 4 — Differential: NOT generalized anxiety (specific to checking). NOT phobia (no specific feared object). NOT psychotic (patient knows it\'s irrational).',
        'STEP 5 — Treatment: \n  • EXPOSURE AND RESPONSE PREVENTION (ERP) — deliberately not doing the compulsion despite anxiety. Gold standard for OCD. \n  • SSRIs, especially at higher doses. \n  • CBT. \n  • Often combined.',
      ],
      answer: 'OCD with checking compulsion. Treated with ERP + SSRIs.', estimatedMinutes: 4 },
    { id: 'try-distinguish', kind: 'try_yourself',
      problem: 'For each scenario, identify the disorder: (a) Returning soldier has nightmares about combat; jumps at loud noises; avoids places that remind him of war. (b) Person can\'t use elevators because of intense fear. (c) Constant worry about everything — money, work, family, health — for the past year. (d) Sudden episodes of racing heart, sweating, "I\'m dying" feeling lasting 10 minutes.',
      expectedAnswer: '(a) PTSD — trauma + intrusive symptoms + avoidance + hyperarousal. \n(b) SPECIFIC PHOBIA — claustrophobia (fear of confined spaces). \n(c) GAD — generalized chronic worry across multiple areas. \n(d) PANIC DISORDER — sudden panic attacks with autonomic symptoms.',
      responseFormat: 'free', hints: ['Match symptoms to disorder.'], estimatedMinutes: 2 },
    { id: 'try-explanation', kind: 'try_yourself',
      problem: 'A combat veteran develops PTSD. Apply ONE biological and ONE psychological explanation.',
      expectedAnswer: 'BIOLOGICAL:\n• HYPERACTIVE AMYGDALA — fear circuit primed by trauma; over-responsive to triggers. \n• DAMPENED PREFRONTAL REGULATION — top-down control of amygdala impaired. \n• Lower CORTISOL response in some PTSD patients. \n• Neurotransmitter changes (norepinephrine, GABA). \n• Brain imaging shows altered hippocampus + amygdala connectivity. \nPSYCHOLOGICAL (Cognitive/Behavioral):\n• CLASSICAL CONDITIONING — combat (UCS) paired with situational stimuli (sounds, smells) → those become CS. Trigger PTSD response without the original threat. \n• NEGATIVE REINFORCEMENT — avoiding triggers reduces anxiety; reinforces avoidance behavior. \n• COGNITIVE distortions: "I should have done more" (survivor guilt); "the world is unsafe." \n• MEMORY processing failure — traumatic memories not integrated normally; remain "raw." \n• EMDR (eye movement desensitization + reprocessing) targets memory consolidation. \nMODERN INTEGRATIVE view: biological vulnerability + traumatic experience + cognitive interpretation → PTSD. Treatments combine medication (SSRIs) + psychotherapy (CBT, EMDR, prolonged exposure).',
      responseFormat: 'free', hints: ['Brain mechanism + learning theory.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. (a) Why is COGNITIVE-BEHAVIORAL THERAPY (CBT) considered the gold standard for most anxiety disorders? (b) Compare ERP (exposure and response prevention) for OCD with EXPOSURE therapy for phobias.',
      expectedAnswer: '(a) CBT gold standard because:\n• EVIDENCE-BASED — extensive research showing efficacy. \n• ADDRESSES root cognitive distortions + behaviors maintaining the disorder. \n• Multiple components: \n  - Cognitive restructuring (challenging catastrophic thoughts). \n  - Behavioral techniques (exposure, response prevention, relaxation). \n• Time-limited (12-20 sessions typically). \n• Provides PORTABLE skills patient can use after therapy ends. \n• Comparable to or better than medication for most anxiety disorders. \n• Combination CBT + medication often most effective. \n• ALTERNATIVES: psychodynamic less evidence-based; medication treats symptoms but doesn\'t teach skills. (3)\n(b) ERP vs Exposure therapy:\nERP for OCD:\n• Patient deliberately FACES the feared situation. \n• Patient PREVENTS the compulsion (e.g., touches doorknob, doesn\'t wash hands). \n• Anxiety RISES then FALLS naturally (extinction). \n• Repetition over many sessions reduces obsession-compulsion cycle. \n• Patient learns: anxiety can be tolerated; compulsion isn\'t needed. \nEXPOSURE therapy for phobias:\n• Patient gradually faces feared object/situation (hierarchy: pictures → videos → real). \n• Patient stays in situation until anxiety naturally decreases. \n• No compulsions to prevent — just sustained exposure. \nDIFFERENCES:\n• OCD has BOTH obsession + compulsion to address. \n• Phobia has ONE feared stimulus. \n• ERP is more demanding for patient (resisting compulsion increases short-term anxiety). \n• Both work via EXTINCTION of conditioned fear. \nBOTH have ~70-90% efficacy for specific cases. (3)\nTotal: 6 points.',
      responseFormat: 'frq', hints: ['CBT efficacy; mechanism of exposure.'], estimatedMinutes: 5 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'GAD (chronic worry), Panic (sudden attacks), Phobia (specific fear), OCD (obsessions + compulsions), PTSD (trauma + symptoms).',
      'Biological + cognitive + behavioral explanations integrated.',
      'CBT gold standard; ERP for OCD; exposure for phobias.',
      'SSRIs for medication management.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '5', cedTopic: '5-ANXIETY', cedTitle: 'Anxiety Disorders', sources: [{ type: 'concept', book: 'feldman', chapter: '15', note: 'Standard anxiety + OCD + PTSD.' }] },
};
