/**
 * AP Psychology — CED Unit 5 (Disorders): Mood (Depression and Bipolar).
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_PSYCH_U5_MOOD_DISORDERS: LessonPlan = {
  id: 'evelyn.ap.psych.mood-disorders.v1', title: 'U5.3 Mood Disorders',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-psychology', locale: 'en',
  los: [{ id: 'appsych.mood-disorders', description: 'Distinguish major depressive disorder, persistent depressive disorder, bipolar I and II. Identify biological, cognitive, and social explanations. Recognize suicide risk and treatment.', standard: 'AP-PSYCH-5-MOOD' }],
  prerequisites: ['appsych.anxiety-disorders'], followUps: ['appsych.schizo-personality'], estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame mood disorders.', script: "Depression is the leading cause of disability worldwide. ~17% of people will experience a major depressive episode. Today: how depression and bipolar disorder differ, what causes them, and what treats them.", estimatedMinutes: 2 },
    { id: 'concept-mood', kind: 'concept', goal: 'Cover depression, bipolar, explanations, treatments.',
      keyIdeas: [
        'MAJOR DEPRESSIVE DISORDER (MDD):',
        '  • At least 5 symptoms for ≥2 weeks, including either:\n     - Depressed mood, OR\n     - Loss of interest/pleasure (anhedonia).',
        '  • Plus other symptoms:\n     - Significant weight or sleep changes.\n     - Fatigue.\n     - Worthlessness or guilt.\n     - Difficulty concentrating.\n     - Psychomotor agitation or slowing.\n     - Suicidal ideation.',
        '  • Impairs functioning.',
        '  • Lifetime prevalence: ~17%.',
        '  • Twice as common in women than men.',
        '',
        'PERSISTENT DEPRESSIVE DISORDER (DYSTHYMIA):',
        '  • Less severe but ≥2 years of depressed mood.',
        '  • Chronic low mood; "always sad."',
        '',
        'BIPOLAR DISORDER:',
        '',
        'BIPOLAR I:\n  • At least one MANIC EPISODE — abnormally elevated/irritable mood, increased energy, decreased need for sleep, grandiosity, racing thoughts, impulsive behaviors. Severe, may require hospitalization.\n  • Often alternates with depressive episodes.',
        '',
        'BIPOLAR II:\n  • Hypomania (less severe) + major depressive episodes.\n  • Hypomania less impairing but still notable mood elevation.',
        '',
        'CYCLOTHYMIA: less severe but chronic mood swings (≥2 years).',
        '',
        'EXPLANATIONS for depression:',
        '',
        'BIOLOGICAL:\n  • GENETICS: heritability ~30-40% for MDD; higher (~70%) for bipolar.\n  • NEUROTRANSMITTERS: SEROTONIN deficit hypothesis (some support but not the whole story).\n  • Norepinephrine, dopamine also implicated.\n  • Brain structures: hippocampus shrinkage in chronic depression.\n  • Hormonal: cortisol elevated.\n  • Inflammation may play role.',
        '',
        'COGNITIVE (Beck):\n  • COGNITIVE TRIAD: negative views of self, world, future.\n  • Depressive cognitive distortions: catastrophizing, all-or-nothing, personalization.\n  • RUMINATION (Nolen-Hoeksema): repetitive negative thinking maintains depression.',
        '',
        'BEHAVIORAL:\n  • Reduced positive reinforcement; isolation; avoidance create depression cycle.\n  • LEARNED HELPLESSNESS (Seligman): repeated uncontrollable bad outcomes → passive resignation.',
        '',
        'SOCIAL:\n  • LIFE STRESS, particularly losses (death, divorce, job loss).\n  • SOCIAL SUPPORT protective.\n  • CULTURAL norms about expressing depression vary.',
        '',
        'EVOLUTIONARY:\n  • Some argue depression evolved as a "withdraw and rest" mechanism after losses or failed efforts.',
        '',
        'BIPOLAR explanations:\n  • Strong GENETIC component (heritability ~70%).\n  • NEUROTRANSMITTER dysregulation.\n  • Brain volume differences in some areas.\n  • Often emerges in late teens / 20s.',
        '',
        'SUICIDE RISK:',
        '  • DEPRESSION accounts for ~50% of suicides.',
        '  • RISK FACTORS: prior attempt, family history, hopelessness, substance abuse, recent loss, access to means, social isolation, chronic illness.',
        '  • PROTECTIVE: connectedness, mental health treatment, restricting access to means.',
        '  • SUICIDE INTERVENTION:\n     - ASK directly ("are you thinking about suicide?")\n     - LISTEN, don\'t lecture.\n     - REMOVE access to means.\n     - CONNECT with mental health services.\n     - National Suicide Prevention Lifeline: 988.',
        '',
        'TREATMENTS for mood disorders:',
        '',
        'PSYCHOTHERAPY:\n  • CBT — gold standard, evidence-based.\n  • Interpersonal Therapy (IPT) — focuses on relationships.\n  • Behavioral Activation — increase reinforcing activities.',
        '',
        'MEDICATIONS:\n  • SSRIs (Prozac, Zoloft) — most common antidepressants. Take 4-6 weeks for effect.\n  • SNRIs (Cymbalta, Effexor).\n  • TCAs (older, more side effects).\n  • Bipolar: LITHIUM (mood stabilizer); anticonvulsants; atypical antipsychotics.',
        '',
        'OTHER TREATMENTS:\n  • EXERCISE — comparable to medication for mild-moderate depression.\n  • LIGHT THERAPY for seasonal affective disorder.\n  • ECT (electroconvulsive therapy) — severe treatment-resistant cases. Effective.\n  • TMS (transcranial magnetic stimulation) — newer, FDA-approved.\n  • KETAMINE — rapid-acting; for treatment-resistant depression.\n  • PSYCHEDELIC-ASSISTED therapy (psilocybin, MDMA) — emerging research.',
      ],
      vocabulary: [
        { term: 'major depressive disorder', definition: 'persistent depressed mood + anhedonia for ≥2 weeks with multiple symptoms.' },
        { term: 'bipolar I', definition: 'manic episodes alternating with depression.' },
        { term: 'cognitive triad', definition: 'negative views of self, world, future (Beck).' },
        { term: 'learned helplessness', definition: 'passive response to uncontrollable bad outcomes.' },
      ],
      estimatedMinutes: 6 },
    { id: 'worked-depression', kind: 'worked_example',
      problem: 'A 28-year-old reports: depressed mood, lost interest in hobbies, sleeping 12+ hours, lost 15 pounds, can\'t concentrate at work, feels worthless. Symptoms began 3 months ago after a breakup. Diagnose and explain.',
      steps: [
        'STEP 1 — Diagnosis: MAJOR DEPRESSIVE DISORDER, single episode.',
        'STEP 2 — Symptoms present (need 5+):\n  ✓ Depressed mood\n  ✓ Anhedonia (lost interest)\n  ✓ Sleep changes (hypersomnia)\n  ✓ Significant weight loss (>5%)\n  ✓ Concentration difficulty\n  ✓ Worthlessness',
        'STEP 3 — Duration: 3 months > 2-week minimum. ✓',
        'STEP 4 — Functional impairment: yes (work problems).',
        'STEP 5 — Trigger: relationship loss is common precipitant.',
        'STEP 6 — Treatment plan:\n  • CBT (12-16 sessions) — address cognitive distortions, behavioral activation.\n  • SSRI consideration if symptoms persist or are severe.\n  • EXERCISE (proven mood booster).\n  • Sleep hygiene, social support.\n  • Monitor for suicide risk.',
      ],
      answer: 'MDD; multiple criteria met; treat with CBT + possibly SSRI.', estimatedMinutes: 4 },
    { id: 'try-bipolar-vs-dep', kind: 'try_yourself',
      problem: '(a) What\'s the difference between bipolar I and major depressive disorder? (b) Why is it dangerous to misdiagnose bipolar as depression?',
      expectedAnswer: '(a) Bipolar I has at least one MANIC EPISODE (extreme elevated/irritable mood, hyperactivity, decreased sleep need, grandiosity, impulsivity, may include psychosis). Often alternates with depression. \nMDD has ONLY depressive episodes — no mania ever. \nKey: presence of MANIA distinguishes the two. \n(b) Misdiagnosis dangers:\n• ANTIDEPRESSANTS in bipolar: can TRIGGER manic episode. SSRI in undiagnosed bipolar may shift patient from depression to dangerous mania. \n• Mania includes: impulsive financial decisions, risky behaviors, sleeplessness, irritability, even psychosis. \n• Without MOOD STABILIZER (lithium, anticonvulsant), patient cycles uncontrollably. \n• Treatment for bipolar is FUNDAMENTALLY DIFFERENT — antidepressants alone can worsen condition. \n• Diagnosis requires careful history (asking about prior manic episodes; family history). \n• Often takes years to correctly diagnose bipolar. \n• Patients in depression typically don\'t spontaneously report mania (it feels good or productive at the time). \n• Ask: "Have you ever felt unusually energetic, didn\'t need much sleep, did things that weren\'t like you?"',
      responseFormat: 'free', hints: ['Mania presence; SSRI risk.'], estimatedMinutes: 4 },
    { id: 'try-explanations', kind: 'try_yourself',
      problem: 'A patient with MDD is treated with CBT but also takes Prozac. Explain the COGNITIVE and BIOLOGICAL approaches.',
      expectedAnswer: 'COGNITIVE (CBT):\n• Identifies COGNITIVE DISTORTIONS — catastrophizing, all-or-nothing thinking, personalization, mind-reading. \n• Targets BECK\'S COGNITIVE TRIAD — negative views of self/world/future. \n• REPLACES distortions with realistic thoughts. \n• BEHAVIORAL ACTIVATION — increase reinforcing activities to break depression cycle. \n• Patient learns SKILLS to manage future episodes. \n• Time-limited (12-16 sessions); evidence-based; comparable to medication. \nBIOLOGICAL (Prozac/SSRI):\n• PROZAC blocks serotonin reuptake → MORE SEROTONIN in synapses. \n• Targets brain neurochemistry directly. \n• Effects take 4-6 weeks (downstream changes in receptors, gene expression). \n• Doesn\'t teach skills but treats acute symptoms. \nCOMBINATION (which patient is doing):\n• Often MOST EFFECTIVE — addresses both biology and cognition. \n• Medication may help patient engage with CBT (more energy, less foggy). \n• CBT provides skills; medication provides chemical correction. \n• Eventually, patient may taper medication while continuing to use CBT skills. \n• Complementary, not competing approaches. \n• Modern psychiatry emphasizes BIOPSYCHOSOCIAL INTEGRATION.',
      responseFormat: 'free', hints: ['Cognitive distortions vs neurotransmitter; complementary.'], estimatedMinutes: 4 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'MDD: ≥5 symptoms for ≥2 weeks. Common (17% lifetime).',
      'Bipolar I: at least one MANIC episode + depression.',
      'Cognitive triad (Beck): negative self/world/future.',
      'Learned helplessness (Seligman): uncontrollable → passive.',
      'CBT gold standard; SSRIs first-line meds. Bipolar: lithium/mood stabilizers.',
      'Suicide risk: ask directly; restrict means; 988 lifeline.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '5', cedTopic: '5-MOOD', cedTitle: 'Mood Disorders', sources: [{ type: 'concept', book: 'feldman', chapter: '15', note: 'Standard mood disorders.' }] },
};
