/**
 * AP Psychology — Unit 5 FRQ Practice.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_PSYCH_U5_FRQ_PRACTICE: LessonPlan = {
  id: 'evelyn.ap.psych.u5-frq-practice.v1', title: 'U5 FRQ Practice',
  curriculum: 'AP', grade: '11', subject: 'ss', topic: 'ap-psychology', locale: 'en',
  los: [{ id: 'appsych.u5-frq-practice', description: 'Apply Unit 5 health and disorders concepts to AP-style FRQs.', standard: 'AP-PSYCH-5-FRQ' }],
  prerequisites: ['appsych.therapy'], followUps: [], estimatedMinutes: 26,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Stakes.', script: "Three Unit 5 FRQs covering stress + disorders + therapy.", estimatedMinutes: 2 },
    { id: 'concept-strategy', kind: 'concept', goal: 'Refresh.', keyIdeas: [
      'GAS: alarm/resistance/exhaustion. Cortisol mechanism.',
      'Anxiety, mood, schizo, personality disorders — diagnostic criteria.',
      'Biological + cognitive + behavioral explanations.',
      'CBT gold standard; DBT for BPD; antipsychotics for schizo; SSRIs for depression.',
      'Therapeutic alliance + evidence-based practice.',
    ], estimatedMinutes: 2 },
    { id: 'try-frq-stress', kind: 'try_yourself',
      problem: 'FRQ Practice 1 — Stress. A college junior\'s grandmother dies. Within weeks: trouble sleeping, anhedonia, weight loss, can\'t concentrate. Has to ask for class extensions. (a) Identify possible disorder. (b) Apply Selye\'s GAS to her experience. (c) Distinguish PROBLEM-FOCUSED vs EMOTION-FOCUSED coping. Which is more applicable here? (d) Suggest TWO biological and TWO cognitive interventions.',
      expectedAnswer: '(a) Likely MAJOR DEPRESSIVE EPISODE (or grief reaction with depressive features). Triggered by significant loss; symptoms meet MDD criteria (anhedonia, sleep changes, weight loss, concentration difficulty). (1.5)\n(b) GAS application:\n• ALARM: news of death. Sympathetic NS surges. Cortisol elevated. Heart racing, sleep disrupted initially. \n• RESISTANCE: weeks of cumulative stress. Cortisol remains high. Body strained. Studies harder; struggles. \n• EXHAUSTION: if continued without resolution, body breaks down. Currently somewhere between resistance and exhaustion. \n• Without intervention, may progress to chronic depression. (2)\n(c) PROBLEM-FOCUSED vs EMOTION-FOCUSED:\n• PROBLEM-FOCUSED: directly address controllable problems (catch up on schoolwork; arrange logistics for grandmother\'s estate). \n• EMOTION-FOCUSED: manage feelings (talk to friends, journal, grief counseling). \n• EMOTION-FOCUSED is MORE APPLICABLE here because the primary stressor (grandmother\'s death) is UNCONTROLLABLE. \n• Combination: problem-focus on controllable academic stress + emotion-focus on grief. (2)\n(d) Interventions:\nBIOLOGICAL:\n(1) SSRI medication (Prozac, Zoloft) — addresses neurotransmitter imbalance contributing to mood. \n(2) EXERCISE — releases endorphins, reduces cortisol, improves sleep. Comparable to medication for mild-moderate depression. \n(3) Sleep regulation, healthy nutrition. \nCOGNITIVE:\n(1) CBT — identify cognitive distortions (e.g., "It\'s my fault for not visiting more"). Replace with realistic thoughts. \n(2) Behavioral activation — gradually re-engage with reinforcing activities. \n(3) Grief processing — acknowledge loss, find meaning. (2.5)\nTotal: 8 points.',
      rubric: { parts: [
        { criterionId: 'a', maxPoints: 2, scoringCriteria: 'Identifies a plausible disorder — major depressive episode (or grief with depressive features) — citing symptoms that meet MDD criteria (anhedonia, sleep change, weight loss, concentration difficulty).', modelResponse: 'A likely MAJOR DEPRESSIVE EPISODE (or grief reaction with depressive features) triggered by the loss; her anhedonia, sleep disturbance, weight loss, and concentration difficulty meet MDD criteria.' },
        { criterionId: 'b', maxPoints: 2, scoringCriteria: 'Applies Selye\'s General Adaptation Syndrome — alarm, resistance, exhaustion — to her timeline.', modelResponse: 'GAS: ALARM at the news (sympathetic surge, elevated cortisol, disrupted sleep); RESISTANCE over the following weeks (sustained high cortisol, strained coping); heading toward EXHAUSTION if unresolved, risking chronic depression.' },
        { criterionId: 'c', maxPoints: 2, scoringCriteria: 'Distinguishes problem-focused from emotion-focused coping and argues emotion-focused is more applicable because the primary stressor (the death) is uncontrollable.', modelResponse: 'PROBLEM-FOCUSED coping addresses controllable problems (catching up on schoolwork); EMOTION-FOCUSED coping manages feelings (grief counseling, talking, journaling). Because the grandmother\'s death is UNCONTROLLABLE, EMOTION-FOCUSED coping is more applicable, combined with problem-focus on the controllable academic stress.' },
        { criterionId: 'd', maxPoints: 3, scoringCriteria: 'Suggests two biological interventions (e.g., SSRI, exercise) and two cognitive interventions (e.g., CBT to challenge distortions, behavioral activation) appropriate to her condition.', modelResponse: 'BIOLOGICAL: an SSRI (e.g., Prozac/Zoloft) to address neurotransmitter imbalance, and EXERCISE to release endorphins and lower cortisol. COGNITIVE: CBT to identify and replace distortions (e.g., "it\'s my fault for not visiting"), and behavioral activation to re-engage with reinforcing activities.' },
      ] },
      responseFormat: 'frq', hints: ['Diagnose; GAS; coping; biopsychosocial intervention.'], estimatedMinutes: 6 },
    { id: 'try-frq-disorders', kind: 'try_yourself',
      problem: 'FRQ Practice 2 — Disorders. (a) Compare ANXIETY DISORDERS (e.g., GAD), MOOD DISORDERS (e.g., MDD), and PSYCHOTIC DISORDERS (e.g., schizophrenia) on: 1. Onset typical age, 2. Major symptoms, 3. Heritability. (b) Identify TWO ETHICAL ISSUES in mental health diagnosis.',
      expectedAnswer: '(a) Comparison:\n\nANXIETY (GAD):\n• Onset: any age; commonly teens-20s. \n• Symptoms: chronic worry, physical tension, sleep disruption. \n• Heritability: ~30-40%. Moderate genetic component. \n\nMDD:\n• Onset: any age; mean ~32; 2× more women than men. \n• Symptoms: ≥5 of 9 depressive symptoms for ≥2 weeks (depressed mood, anhedonia, sleep, weight, fatigue, worthlessness, concentration, suicidality, psychomotor changes). \n• Heritability: ~30-40%. \n\nSCHIZOPHRENIA:\n• Onset: late teens-early 20s typical (earlier in men). \n• Symptoms: positive (hallucinations, delusions, disorganization) + negative (flat affect, withdrawal). \n• Heritability: ~80%. Strongest genetic component of major mental illnesses. (4)\n(b) Ethical issues:\n(1) STIGMATIZATION — diagnosis can stigmatize a person, affecting employment, relationships, self-image. Some critics argue disorders are over-diagnosed (especially ADHD, depression). DSM diagnoses can be self-fulfilling. \n(2) MEDICALIZATION — treating normal life experiences as disorders. Where does normal sadness end and depression begin? Cultural variation in what counts as "disordered." \n(3) FALSE POSITIVES vs NEGATIVES — both have costs. False positive = unnecessary treatment, stigma. False negative = denied treatment. \n(4) CULTURAL BIAS in diagnosis — what\'s "normal" varies; DSM developed in Western contexts. \n(5) MISDIAGNOSIS RISKS — bipolar misdiagnosed as depression; SSRIs can trigger mania. \n(6) RESEARCH ETHICS in clinical trials. \n(7) INVOLUNTARY commitment — when?\n(8) ACCESS DISPARITIES — minority populations underdiagnosed for some conditions, overdiagnosed for others. (3)\nTotal: 7 points.',
      rubric: { parts: [
        { criterionId: 'a', maxPoints: 6, scoringCriteria: 'Compares anxiety (GAD), mood (MDD), and psychotic (schizophrenia) disorders across all three dimensions — typical onset age, major symptoms, and heritability.', modelResponse: 'GAD — onset any age (often teens-20s); chronic worry, tension, sleep disruption; heritability ~30-40%. MDD — mean onset ~32, twice as common in women; ≥5 of 9 depressive symptoms for ≥2 weeks; heritability ~30-40%. SCHIZOPHRENIA — onset late teens-early 20s (earlier in men); positive symptoms (hallucinations, delusions, disorganization) plus negative symptoms (flat affect, withdrawal); heritability ~80%, the strongest of the major mental illnesses.' },
        { criterionId: 'b', maxPoints: 3, scoringCriteria: 'Identifies two distinct ethical issues in mental-health diagnosis (e.g., stigmatization, medicalization of normal experience, cultural bias, false positives/negatives).', modelResponse: 'STIGMATIZATION — a diagnosis can harm employment, relationships, and self-image and may be self-fulfilling. MEDICALIZATION — treating normal life experiences (ordinary sadness) as disorders, with culturally variable and Western-developed criteria raising false-positive/negative and cultural-bias concerns.' },
      ] },
      responseFormat: 'frq', hints: ['Compare disorder categories; ethical issues.'], estimatedMinutes: 6 },
    { id: 'try-frq-therapy', kind: 'try_yourself',
      problem: 'FRQ Practice 3 — Therapy. (a) A patient with PTSD seeks treatment. Compare PSYCHOANALYSIS, CBT, and EMDR for this patient. Which is evidence-based? (b) What\'s the PLACEBO EFFECT and why does it complicate therapy research?',
      expectedAnswer: '(a) For PTSD:\nPSYCHOANALYSIS (psychodynamic):\n• Originally proposed for PTSD-like trauma in early 1900s. \n• EXPLORES unconscious conflicts related to trauma. \n• EVIDENCE: less robust than CBT for PTSD. \n• Long-term, expensive. \nCBT (Cognitive-Behavioral Therapy for trauma):\n• EVIDENCE-BASED — gold standard. \n• Components: PROLONGED EXPOSURE (face trauma memories), COGNITIVE PROCESSING, COPING SKILLS. \n• Time-limited (12-15 sessions typical). \n• 60-90% effectiveness for PTSD. \n• Strong research support. \nEMDR (Eye Movement Desensitization and Reprocessing):\n• Patient describes traumatic memory while making lateral eye movements. \n• Goal: reprocess traumatic memories. \n• Evidence-based — similar effectiveness to CBT for PTSD. \n• Mechanism debated; possibly reduces emotional intensity through working-memory dual-task interference. \n• FDA + APA both endorse. \nVERDICT: CBT and EMDR both gold-standard for PTSD. Psychoanalysis less evidence-based but may help some patients. (4)\n(b) PLACEBO EFFECT:\n• Improvement following SHAM treatment that has no medical effect. \n• Patient EXPECTATIONS + therapeutic alliance + hope all contribute. \n• In drug trials: typically 30-40% improvement on placebo. \n• In psychotherapy: similar — being TREATED creates improvement above no-treatment control. \nWHY IT COMPLICATES RESEARCH:\n• Hard to PROVE specific therapy ingredients work above placebo. \n• Many therapies (and meds) outperform NO TREATMENT but only modestly outperform PLACEBO. \n• Suggests COMMON FACTORS (alliance, expectation, structure) matter as much as specific techniques. \n• REQUIRES double-blind randomized controlled trials with active placebo. \n• Mental health research must be especially rigorous. \n• HOWEVER, when CBT outperforms placebo (and it does, especially for severe disorders), we can be confident in its specific effects. (3)\nTotal: 7 points.',
      rubric: { parts: [
        { criterionId: 'a', maxPoints: 6, scoringCriteria: 'Compares psychoanalysis, CBT, and EMDR for PTSD, describing each approach and correctly identifying CBT and EMDR as the evidence-based (gold-standard) treatments.', modelResponse: 'PSYCHOANALYSIS explores unconscious trauma-related conflicts but has weaker PTSD evidence and is long/expensive. CBT is EVIDENCE-BASED gold standard — prolonged exposure, cognitive processing, and coping skills, time-limited with 60-90% effectiveness. EMDR pairs recall of the memory with lateral eye movements to reprocess it and is also evidence-based, similarly effective to CBT and endorsed by the FDA/APA. Verdict: CBT and EMDR are the evidence-based choices; psychoanalysis is less so.' },
        { criterionId: 'b', maxPoints: 3, scoringCriteria: 'Defines the placebo effect (improvement from a sham/expectation-driven treatment) and explains why it complicates therapy research — making it hard to isolate specific treatment ingredients above common factors, requiring rigorous controlled designs.', modelResponse: 'The PLACEBO EFFECT is improvement following an inert treatment, driven by expectations, hope, and the therapeutic alliance (30-40% improvement in drug trials). It complicates research because many therapies beat no-treatment but only modestly beat placebo, so COMMON FACTORS (alliance, expectation, structure) may matter as much as specific techniques — requiring double-blind randomized controlled trials with active placebos to prove specific effects.' },
      ] },
      responseFormat: 'frq', hints: ['Compare therapies; placebo + research design.'], estimatedMinutes: 6 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'AP rewards specific case studies (Selye, Beck, Seligman).',
      'Diagnose carefully; consider biological + psychological + social factors.',
      'CBT, EMDR for PTSD; antipsychotics for schizo; DBT for BPD.',
      'Placebo and alliance complicate research; evidence-based practice integrates research + clinical + patient values.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '5', cedTopic: '5-FRQ', cedTitle: 'Unit 5 FRQ Practice', sources: [{ type: 'frq-style', source: 'AP Plans Initiative author', note: 'Modeled on AP Psych Unit-5 FRQs.' }] },
};
