/**
 * AP Psychology — CED Unit 1.6+1.7: Consciousness, Sleep, and Drugs.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_PSYCH_U1_CONSCIOUSNESS_SLEEP: LessonPlan = {
  id: 'evelyn.ap.psych.consciousness-sleep.v1', title: 'U1.4 Consciousness, Sleep, and Drugs',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-psychology', locale: 'en',
  los: [{ id: 'appsych.consciousness-sleep', description: 'Identify sleep stages and their characteristics. Compare sleep theories. Identify drug categories and their behavioral effects.', standard: 'AP-PSYCH-1.6-1.7' }],
  prerequisites: ['appsych.nervous-endocrine'], followUps: ['appsych.sensation-perception'], estimatedMinutes: 22,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame consciousness as variable.', script: "We spend a third of our lives ASLEEP. Yet we don\'t experience it as wasted time — sleep is essential for memory, mood, and immune function. Today: the stages of sleep, theories of dreaming, and how drugs alter consciousness.", estimatedMinutes: 2 },
    { id: 'concept-sleep', kind: 'concept', goal: 'Cover sleep stages, theories, drugs.',
      keyIdeas: [
        'CONSCIOUSNESS: awareness of self and environment.',
        '  • DUAL PROCESSING: parallel processing (unconscious, automatic) + serial processing (conscious, deliberate).',
        'CIRCADIAN RHYTHM: ~24-hour biological cycle. Driven by suprachiasmatic nucleus (SCN) in hypothalamus.',
        '  • Disrupted by jet lag, shift work, screen exposure (bright light suppresses melatonin).',
        'SLEEP STAGES (measured by EEG, brain waves):',
        '  • AWAKE: ALPHA waves (relaxed, eyes closed) and BETA waves (alert).',
        '  • STAGE 1 (N1): light sleep, ~5 minutes. THETA waves. Hypnagogic hallucinations.',
        '  • STAGE 2 (N2): deeper, ~20 minutes. SLEEP SPINDLES (bursts of activity). Memory consolidation begins.',
        '  • STAGE 3 (N3, formerly stages 3+4): DEEP SLEEP. DELTA waves (slow, large). Body restoration; growth hormone release. Hardest to wake.',
        '  • REM SLEEP: rapid eye movements; brain activity HIGH (looks like awake EEG); muscles paralyzed (atonia, prevents acting out dreams). Most vivid DREAMS occur here. Cycles every 90 min, longer as night progresses.',
        '  • Cycle: 1 → 2 → 3 → 2 → REM → repeat. ~90 min cycles. ~5 cycles per night.',
        'SLEEP THEORIES (why we sleep):',
        '  • PROTECTION: kept ancestors safe at night.',
        '  • RECUPERATION/RESTORATION: body and brain repair.',
        '  • MEMORY CONSOLIDATION: sleep transfers short-term to long-term memories. Especially REM.',
        '  • CREATIVITY: dream-state recombination of ideas.',
        '  • IMMUNE FUNCTION: sleep loss weakens immunity.',
        'DREAM THEORIES:',
        '  • FREUDIAN (psychoanalytic): dreams reflect unconscious wishes; manifest content (literal) vs latent content (symbolic). Mostly discredited but historically influential.',
        '  • INFORMATION-PROCESSING: dreams help process and consolidate the day\'s memories.',
        '  • PHYSIOLOGICAL ARGUMENT: dreams are random brain activity; cortex tries to make sense of it (activation-synthesis hypothesis).',
        '  • COGNITIVE: dreams reflect cognitive maturation and problem-solving.',
        'SLEEP DISORDERS:',
        '  • INSOMNIA: difficulty falling/staying asleep.',
        '  • NARCOLEPSY: sudden uncontrollable sleep attacks; entering REM directly.',
        '  • SLEEP APNEA: breathing repeatedly stops during sleep.',
        '  • NIGHT TERRORS: deep-sleep arousal, screaming/thrashing; child has no memory of it.',
        '  • SLEEPWALKING: deep-sleep, not REM (because muscles aren\'t paralyzed).',
        'DRUG CATEGORIES:',
        '  • DEPRESSANTS: slow CNS. Alcohol, barbiturates, opioids (heroin), benzodiazepines (Xanax, Valium). Effects: relaxation, slowed reflexes, drowsiness. Can be addictive; lethal in overdose.',
        '  • STIMULANTS: speed up CNS. Caffeine, nicotine, cocaine, methamphetamine, MDMA. Effects: alertness, energy, euphoria. High addiction potential.',
        '  • HALLUCINOGENS (psychedelics): distort perception. LSD, psilocybin (mushrooms), peyote, mescaline. Effects: visual/sensory distortions, altered consciousness.',
        '  • OPIOIDS (technically a depressant subtype): morphine, heroin, fentanyl, prescription painkillers. Bind to endorphin receptors. High addiction; overdose epidemic.',
        '  • MARIJUANA (THC): mild stimulant + hallucinogen + relaxant; complex effects.',
        'TOLERANCE: requires more drug for same effect (brain compensates).',
        'WITHDRAWAL: physical symptoms when drug stops; brain has adapted.',
        'ADDICTION: compulsive drug use despite harm. Driven by brain reward circuits (dopamine).',
      ],
      vocabulary: [
        { term: 'REM sleep', definition: 'rapid eye movement sleep; vivid dreams; muscle atonia.' },
        { term: 'circadian rhythm', definition: '~24-hour biological cycle.' },
        { term: 'tolerance', definition: 'requiring more of a drug for the same effect.' },
      ],
      estimatedMinutes: 7 },
    { id: 'worked-stages', kind: 'worked_example',
      problem: 'A college student goes to sleep at midnight. Trace their sleep stages until they wake at 7 AM.',
      steps: [
        'Cycles of ~90 minutes each, total 7 hours = ~5 cycles.',
        'Hour 0:00 — Awake → Stage 1 (5 min) → Stage 2 (20 min) → Stage 3 (deep sleep, 30 min, longest in early sleep) → Stage 2 (10 min) → REM (5 min).',
        'Hour 1:30 — Cycle 2: lighter Stage 3, longer REM.',
        'Hour 3:00 — Cycle 3: Stage 3 may be brief; REM longer (~20 min).',
        'Hour 4:30 — Cycle 4: minimal Stage 3; REM ~30 min.',
        'Hour 6:00 — Cycle 5 (partial): mostly Stage 2 + REM. Wakes during REM or Stage 2 most easily.',
        'PATTERN: Stage 3 (deep) DECREASES across the night. REM sleep INCREASES. Most REM occurs in last third of night.',
      ],
      answer: '5 cycles. Deep sleep early in night; REM dominates later cycles.', estimatedMinutes: 4 },
    { id: 'try-stage-id', kind: 'try_yourself',
      problem: 'Match each scenario to a sleep stage: (a) Body paralyzed, vivid dream, eye movements, brain very active. (b) Slow large delta waves, hardest to wake. (c) Sleep spindles, memory consolidation. (d) Brief drift to sleep, hypnagogic experience.',
      expectedAnswer: '(a) REM. (b) Stage 3 (deep sleep, delta waves). (c) Stage 2. (d) Stage 1.',
      responseFormat: 'free', hints: ['REM = dreams + paralysis. Delta = deep. Spindles = stage 2.'], estimatedMinutes: 2 },
    { id: 'try-drugs', kind: 'try_yourself',
      problem: 'Classify each drug as depressant, stimulant, hallucinogen, or opioid: (a) caffeine, (b) alcohol, (c) cocaine, (d) heroin, (e) LSD, (f) Xanax.',
      expectedAnswer: '(a) Stimulant. (b) Depressant. (c) Stimulant. (d) Opioid (depressant subtype). (e) Hallucinogen. (f) Depressant (benzodiazepine).',
      responseFormat: 'free', hints: ['Speeds up = stimulant. Slows = depressant. Distorts = hallucinogen.'], estimatedMinutes: 2 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. A college student studying for finals stays up until 3 AM every night, drinking energy drinks, and feels increasingly mentally foggy. (a) Identify the underlying physiological problems with this pattern. (b) Explain how stimulants like caffeine work and why they\'re NOT a true substitute for sleep. (c) Suggest evidence-based ways to improve their cognitive performance during finals.',
      expectedAnswer: '(a) Problems:\n• REDUCED REM SLEEP — most REM occurs in late night/morning. Cutting sleep short disproportionately reduces REM. \n• INTERRUPTED MEMORY CONSOLIDATION — REM and Stage 2 consolidate the day\'s memories. Without it, study material isn\'t encoded long-term well. \n• CIRCADIAN DYSREGULATION — irregular schedule disrupts SCN, lowers cognitive function. \n• SLEEP DEBT accumulates — performance degrades cumulatively. \n• Compromised IMMUNE FUNCTION → catching cold during finals worse. (2.5)\n(b) Caffeine mechanism:\n• Caffeine is an ANTAGONIST of ADENOSINE RECEPTORS. \n• Adenosine builds up during waking and promotes sleepiness. Caffeine blocks the sleepy signal. \n• Result: feels alert. \n• But: caffeine doesn\'t REPLACE the recovery functions of sleep. Memory consolidation, hormonal regulation, immune function still suffer. \n• Also: tolerance builds — same dose has less effect over time. Withdrawal headaches. (2)\n(c) Evidence-based improvements:\n• PRIORITIZE 7-8 HOURS SLEEP — far more effective for memory than late-night study. \n• SLEEP RIGHT AFTER STUDY — recent learning is consolidated during subsequent sleep. \n• AVOID LATE CAFFEINE (within 6+ hours of bed). \n• SHORT POWER NAPS (20-30 min) for alertness without drift into deep sleep. \n• LIGHT EXERCISE during day improves sleep quality. \n• EXPOSURE TO BRIGHT LIGHT in morning, DIM at night (regulates circadian). \n• Limit screens before bed. \n• Consistent SLEEP/WAKE TIMES even on weekends. (2.5)\nTotal: 7 points.',
      responseFormat: 'frq', hints: ['Mechanism, why caffeine ≠ sleep, recommendations.'], estimatedMinutes: 6 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Sleep stages: 1 (light, theta) → 2 (spindles) → 3 (deep, delta) → REM (paralyzed, dreams). Cycles ~90 min.',
      'REM increases across night; deep sleep decreases.',
      'Theories: protection, restoration, memory consolidation, creativity.',
      'Drugs: depressants (alcohol, opioids, benzos) slow CNS; stimulants speed up; hallucinogens distort.',
      'Tolerance and withdrawal indicate addiction.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '1', cedTopic: '1.6-1.7', cedTitle: 'Consciousness, Sleep, Drugs', sources: [{ type: 'concept', book: 'feldman', chapter: '4', note: 'Standard consciousness + sleep + drugs.' }] },
};
