/**
 * AP Psychology — CED Unit 2.8+2.9+2.10: Intelligence, Achievement, and
 * Standardized Testing.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_PSYCH_U2_INTELLIGENCE: LessonPlan = {
  id: 'evelyn.ap.psych.intelligence.v1', title: 'U2.5 Intelligence',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-psychology', locale: 'en',
  los: [{ id: 'appsych.intelligence', description: 'Distinguish theories of intelligence (Spearman g, Sternberg, Gardner, emotional intelligence). Identify intelligence test history and properties (validity, reliability, standardization). Discuss heritability and group differences.', standard: 'AP-PSYCH-2.8-2.10' }],
  prerequisites: ['appsych.thinking-language'], followUps: [], estimatedMinutes: 20,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame intelligence as multifaceted.', script: "What is INTELLIGENCE? A single mental ability, or many separate ones? Can a test measure it? AP loves these debates. Today: theories, tests, what they measure (and don\'t).", estimatedMinutes: 2 },
    { id: 'concept-intelligence', kind: 'concept', goal: 'Cover theories + tests + heritability.',
      keyIdeas: [
        'INTELLIGENCE THEORIES (memorize):',
        '',
        'SPEARMAN — General Intelligence (g):',
        '  • Single underlying factor explains performance across all cognitive tasks.',
        '  • People who are good at math also tend to do well at vocabulary, etc.',
        '  • g = positive correlation across tests.',
        '  • IQ tests measure g (mostly).',
        '',
        'STERNBERG — Triarchic Theory:',
        '  • ANALYTICAL: classic IQ tasks, school smarts.',
        '  • CREATIVE: novel problem-solving, originality.',
        '  • PRACTICAL: street smarts, applying knowledge to real situations.',
        '',
        'GARDNER — Multiple Intelligences (8 types):',
        '  • LINGUISTIC, LOGICAL-MATHEMATICAL, MUSICAL, SPATIAL, BODILY-KINESTHETIC, INTERPERSONAL, INTRAPERSONAL, NATURALISTIC.',
        '  • Each "intelligence" is a separate capacity.',
        '  • Critics: Gardner\'s "intelligences" may be talents/skills rather than intelligences. Lacks empirical support for separation.',
        '  • Influential in education despite weak empirical base.',
        '',
        'GOLEMAN — Emotional Intelligence (EQ):',
        '  • Self-awareness, self-regulation, motivation, empathy, social skills.',
        '  • Argued more important than IQ for life success.',
        '  • Some research supports correlations with workplace and relationship success.',
        '',
        'CRYSTALLIZED vs FLUID intelligence (Cattell):',
        '  • CRYSTALLIZED: accumulated knowledge, vocabulary, facts. Increases through life.',
        '  • FLUID: ability to solve NEW problems, reason quickly. Peaks in 20s, declines slowly with age.',
        '',
        'INTELLIGENCE TESTS:',
        '',
        'STANFORD-BINET (Lewis Terman, 1916):',
        '  • Adapted from Binet\'s scale (1905).',
        '  • IQ = (mental age / chronological age) × 100.',
        '  • Mental age determined by tasks at each age level.',
        '',
        'WECHSLER scales (most common today):',
        '  • WAIS (adults), WISC (children), WPPSI (preschool).',
        '  • Verbal + performance subscales.',
        '  • Modern IQ scoring: 100 average, 15 SD. Bell curve distribution.',
        '',
        'TEST PROPERTIES:',
        '  • RELIABILITY: same result on retesting. Most modern tests highly reliable (test-retest correlation .9+).',
        '  • VALIDITY: measures what it claims. Various validity types:\n     - Content validity (samples relevant content)\n     - Construct validity (measures the construct)\n     - Predictive validity (predicts outcomes — IQ predicts academic and job success modestly).',
        '  • STANDARDIZATION: tested on representative sample to establish norms.',
        '  • CULTURE-FAIR tests: attempt to minimize cultural bias.',
        '',
        'IQ DISTRIBUTION: ~95% of population scores 70-130 (within 2 SDs).',
        '  • <70: cognitive disability.',
        '  • >130: gifted.',
        '',
        'INTELLIGENCE HERITABILITY:',
        '  • Twin studies: identical twins separated at birth show similar IQs (~0.7-0.8 correlation).',
        '  • Adopted children: more similar to biological than adoptive parents.',
        '  • Estimated heritability: 50-80% in adults.',
        '  • IMPORTANT: heritability is POPULATION level. Doesn\'t mean YOUR IQ is mostly genetic.',
        '  • Heritability INCREASES with age (genes\' influence accumulates as environment effects average out).',
        '',
        'ENVIRONMENTAL FACTORS:',
        '  • Education, nutrition, parental engagement, socioeconomic status all affect IQ.',
        '  • FLYNN EFFECT: IQ scores have RISEN ~3 points per decade across world. Cannot be explained by genetics. Likely: better nutrition, education, technology, more abstract reasoning in modern world.',
        '',
        'GROUP DIFFERENCES (sensitive topic):',
        '  • Average score differences exist between groups (race, sex), but ~85% of variance is WITHIN groups, not between.',
        '  • Most differences EXPLAINED by environment (poverty, education access, stereotype threat).',
        '  • STEREOTYPE THREAT: anxiety about confirming negative stereotype reduces performance.',
        '  • Genetic explanations for between-group differences NOT well-supported.',
        '  • IQ is malleable; gaps NARROW with educational interventions.',
      ],
      vocabulary: [
        { term: 'g (general intelligence)', definition: 'single underlying cognitive ability across tasks.' },
        { term: 'multiple intelligences', definition: 'Gardner\'s 8 distinct intelligences.' },
        { term: 'crystallized intelligence', definition: 'accumulated knowledge; increases with age.' },
        { term: 'fluid intelligence', definition: 'novel problem-solving; peaks in 20s.' },
        { term: 'Flynn effect', definition: 'global IQ scores have risen ~3 points/decade.' },
      ],
      estimatedMinutes: 6 },
    { id: 'worked-theories', kind: 'worked_example',
      problem: 'Compare Spearman\'s g with Gardner\'s multiple intelligences. Which is better supported by research?',
      steps: [
        'SPEARMAN\'S g:\n  • Statistical evidence: positive correlations across cognitive tests.\n  • IQ tests measure g effectively.\n  • Psychometricians (statisticians of testing) generally accept g.\n  • Predictive validity: g correlates with academic + job + life outcomes.',
        'GARDNER\'S 8 INTELLIGENCES:\n  • Educationally appealing.\n  • Lacks rigorous statistical support for separate intelligences.\n  • Critics: musical "intelligence" is a talent, not a separate intelligence.\n  • IQ tests don\'t support multiple-factor model.\n  • Influential in schools (differentiated instruction) despite weak empirical base.',
        'BETTER SUPPORTED: g and Spearman/Cattell\'s factor analysis approach. Modern view: g exists but doesn\'t capture everything (e.g., creativity, emotional intelligence add useful info).',
        'Gardner\'s INTUITIVE appeal but not strongly supported in psychometric research.',
      ],
      answer: 'Spearman\'s g better empirically supported; Gardner influential but weaker.', estimatedMinutes: 4 },
    { id: 'try-iq', kind: 'try_yourself',
      problem: 'A 10-year-old child performs at the level of a 12-year-old on Stanford-Binet. (a) Compute IQ using the original formula. (b) Compute IQ using modern Wechsler scoring (mean=100, SD=15) if they score 1.33 SDs above mean.',
      expectedAnswer: '(a) Stanford-Binet original formula: IQ = (mental age / chronological age) × 100 = (12/10) × 100 = 120. \n(b) Wechsler scoring: mean = 100, SD = 15. Score 1.33 SDs above mean: 100 + 1.33(15) = 100 + 20 = 120. \nBoth approaches give the same value here. Modern IQ uses Wechsler approach (deviation IQ) which works better for adults. Original formula breaks down for adults (mental age plateaus, chronological keeps increasing → falsely declining IQ).',
      responseFormat: 'numeric', hints: ['Original ratio formula vs modern deviation.'], estimatedMinutes: 3 },
    { id: 'try-flynn', kind: 'try_yourself',
      problem: 'The Flynn effect shows that average IQ scores have risen ~3 points per decade for the past 100 years. (a) What rules out a genetic explanation? (b) Suggest THREE environmental causes.',
      expectedAnswer: '(a) GENETICS CAN\'T EXPLAIN because:\n• 3 points per decade × 100 years = 30 IQ points. Massive change.\n• Genetic change requires evolution over thousands of years, not 100.\n• Allele frequencies cannot have shifted that fast.\n• If genetic, populations not under same selection pressure would have different rates — they don\'t.\nMust be ENVIRONMENTAL change.\n(b) Environmental causes:\n(1) BETTER NUTRITION — adequate protein and micronutrients in early childhood support brain development.\n(2) MORE EDUCATION — more years of schooling, more abstract reasoning practice.\n(3) MEDIA + TECHNOLOGY — exposure to abstract problems, visual reasoning, novel concepts.\n(4) FEWER CHILDHOOD INFECTIONS — reduce nutritional stress, brain development disruption.\n(5) MODERN ABSTRACT thinking required for tests — culture has become more "test-friendly."\n(6) IMPROVED PRENATAL CARE.\n(7) Reduced lead exposure in environment.\nNote: Flynn effect appears to be SLOWING in developed countries — possibly approaching ceiling.',
      responseFormat: 'free', hints: ['Speed rules out genetics; environmental factors.'], estimatedMinutes: 4 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. IQ tests have predicted academic and career outcomes for a century. (a) State two STRENGTHS and two LIMITATIONS of IQ tests. (b) The "stereotype threat" research shows that just being aware of negative stereotypes can lower test performance. Why does this matter for measuring intelligence?',
      expectedAnswer: '(a) STRENGTHS:\n1. Reliable — high test-retest correlations. \n2. Predict outcomes: academic success, job performance, life outcomes (modestly). \n3. Identify cognitive disability (mental retardation) for educational support. \n4. Detect cognitive decline (Alzheimer\'s, dementia screening). \n5. Standardized norms allow comparisons. \nLIMITATIONS:\n1. Don\'t measure CREATIVITY, EMOTIONAL INTELLIGENCE, PRACTICAL skills, motivation. \n2. CULTURE-BIAS — questions privilege middle-class, English-speaking, educated test-takers. \n3. Don\'t fully capture variation — subtypes (verbal vs spatial, fluid vs crystallized) more useful. \n4. STEREOTYPE THREAT can artificially depress scores. \n5. FLYNN EFFECT — what does it mean to compare IQs across decades? \n6. Predictive but doesn\'t cause outcomes — strong predictor doesn\'t mean fixed destiny. (3)\n(b) Stereotype threat implications:\n• Tests are supposed to measure ABILITY independent of context. \n• Stereotype threat shows context (awareness of negative stereotype) AFFECTS PERFORMANCE. \n• Black students aware of stereotypes about race + intelligence score lower than identical students unaware. \n• Same effect for women in math contexts. \n• Implication: IQ tests measure performance under specific conditions, not pure ability. \n• In real situations, stereotype threat may DAMPEN actual real-world performance too, not just test scores. \n• Has IMPLICATIONS FOR INTERPRETING GROUP DIFFERENCES — apparent differences may reflect context, not capacity. \n• REDUCING STEREOTYPE THREAT in test-taking improves performance for affected groups. (3)\nTotal: 6 points.',
      responseFormat: 'frq', hints: ['Strengths/limitations; stereotype threat implication.'], estimatedMinutes: 5 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Theories: Spearman (g), Sternberg (analytical/creative/practical), Gardner (8 multiple), Goleman (EQ).',
      'Crystallized (knowledge) increases; fluid (problem-solving) peaks in 20s.',
      'IQ tests: 100 mean, 15 SD. Reliable + predictive. Modest validity.',
      'Heritability of IQ: 50-80% (population level, not individual).',
      'Flynn effect: ~3 points per decade rise; environmental.',
      'Stereotype threat affects test performance.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '2', cedTopic: '2.8-2.10', cedTitle: 'Intelligence', sources: [{ type: 'concept', book: 'feldman', chapter: '8', note: 'Standard intelligence theories and tests.' }] },
};
