/**
 * AP Psychology — Research Methods and Statistics.
 */

import type { LessonPlan } from '../types';

export const SEED_AP_PSYCHOLOGY_RESEARCH_METHODS: LessonPlan = {
  id: 'evelyn.ap.psychology.research-methods.v1',
  title: 'AP Psychology — Research Methods and Statistics',
  curriculum: 'AP',
  grade: '11',
  subject: 'social-studies',
  topic: 'ap-psychology',
  locale: 'en',
  los: [
    {
      id: 'ap.psychology.research-methods',
      description: 'Distinguish experimental from correlational designs, identify variables, recognise validity threats, and interpret descriptive statistics on the AP Psych exam.',
      standard: 'AP-PSYCH-UNIT-1',
    },
  ],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 18,
  segments: [
    {
      id: 'hook',
      kind: 'hook',
      goal: 'AP Psych research-methods questions are some of the highest-scoring units on the exam — and the rules transfer to any science.',
      script: 'A study claims caffeine improves memory. Was it an experiment? A correlation? Were variables controlled? AP Psych\'s research-methods unit teaches you to dissect any psychological claim in 30 seconds. Today: the canonical concepts and the question patterns the exam uses.',
      estimatedMinutes: 1,
    },
    {
      id: 'concept-research-methods',
      kind: 'concept',
      goal: 'Designs, variables, validity threats, descriptive stats.',
      keyIdeas: [
        'STUDY DESIGNS:',
        '  EXPERIMENTAL: researcher manipulates an independent variable + measures dependent. Random assignment to conditions. ONLY design that establishes CAUSATION.',
        '  CORRELATIONAL: observes naturally-occurring relationships. Cannot establish cause.',
        '  DESCRIPTIVE: case studies, surveys, naturalistic observation. Describes but doesn\'t test causal claims.',
        'KEY VARIABLES:',
        '  IV (independent variable): what researcher MANIPULATES.',
        '  DV (dependent variable): what researcher MEASURES.',
        '  CONTROL: treatment held constant; condition without treatment for comparison.',
        '  CONFOUNDING variable: varies WITH the IV and could explain the DV — RUINS internal validity.',
        '  OPERATIONAL DEFINITION: how you specify a fuzzy concept (e.g. "happiness" → score on a 1-7 scale).',
        'GROUPS:',
        '  EXPERIMENTAL group: receives treatment.',
        '  CONTROL group: doesn\'t (or gets placebo).',
        '  RANDOM ASSIGNMENT: each participant has equal chance of either group. CRUCIAL for valid experiments.',
        'VALIDITY threats:',
        '  INTERNAL VALIDITY: did the IV actually cause the change in DV (no confounds)?',
        '  EXTERNAL VALIDITY: do results generalise outside the study?',
        '  CONSTRUCT VALIDITY: did you measure what you claimed to measure?',
        'BIAS sources:',
        '  PARTICIPANT bias: demand characteristics, social desirability.',
        '  EXPERIMENTER bias: subtle influence on participants.',
        '  SOLUTION: DOUBLE-BLIND design (neither participant nor experimenter knows treatment assignment).',
        'CORRELATION COEFFICIENT (r): -1 to +1.',
        '  Magnitude = strength. Sign = direction.',
        '  r = 0.8: strong positive. r = -0.8: strong negative. r = 0.1: weak.',
        '  CORRELATION ≠ CAUSATION. Always.',
        'DESCRIPTIVE STATISTICS:',
        '  CENTRAL TENDENCY: mean, median, mode. (Mode = most frequent. Median = middle value. Mean = average.)',
        '  VARIABILITY: range, standard deviation. SD measures average distance from mean.',
        '  NORMAL DISTRIBUTION: bell curve. ~68% within 1 SD, ~95% within 2 SD.',
        'INFERENTIAL: statistical significance (p < 0.05 standard threshold). Tells whether observed difference is likely due to chance.',
      ],
      vocabulary: [
        { term: 'random assignment', definition: 'placing participants into conditions randomly; ensures groups are comparable on average; critical for causal inference.' },
        { term: 'double-blind', definition: 'a design where neither participant nor experimenter knows the treatment assignment, eliminating both biases.' },
      ],
      estimatedMinutes: 6,
    },
    {
      id: 'worked',
      kind: 'worked_example',
      problem: 'A study finds that students who eat breakfast score higher on tests. Researchers conclude breakfast causes better test performance. What\'s the major flaw and how would you fix it?',
      steps: [
        'Identify the design: this is CORRELATIONAL (observes naturally-occurring relationship between breakfast eating and test scores). NO manipulation.',
        'Correlation ≠ causation. Possible confounds:',
        '  Wealthier families more likely both to provide breakfast AND have better educational resources.',
        '  Health-conscious families do both.',
        '  Reverse causation: high-performing students wake up earlier, eat breakfast.',
        'TO ESTABLISH CAUSATION: run an experiment.',
        '  Random assignment: half of students randomly get breakfast, half don\'t.',
        '  Measure test scores in both groups.',
        '  Random assignment ensures groups are comparable on confounds (income, parenting, prior performance).',
        '  Conclusion if breakfast group scores higher: causal evidence (with appropriate caveats about external validity).',
      ],
      answer: 'Correlational design can\'t prove causation. Fix: experiment with random assignment.',
      estimatedMinutes: 5,
    },
    {
      id: 'try-1',
      kind: 'try_yourself',
      problem: 'A drug trial reports r = -0.7 between dose and depressive symptoms. What does this tell us, and what doesn\'t it tell us?',
      expectedAnswer: 'r = -0.7 means a STRONG NEGATIVE correlation: as dose increases, depressive symptoms decrease. The relationship is real and substantial. What it DOESN\'T tell us: (1) whether the drug CAUSES the improvement (could be placebo, regression to mean, confounds). (2) Whether the correlation holds outside the studied range. (3) Individual variation — most patients improve, but some may not. To establish causation, need a randomised double-blind placebo-controlled trial.',
      responseFormat: 'free',
      hints: [
        'r = -0.7 is strong; what does the negative sign mean?',
        'What does correlation NEVER prove?',
      ],
      estimatedMinutes: 3,
    },
    {
      id: 'misconception-experimental-as-correlation',
      kind: 'misconception_check',
      question: 'A student calls a study with no random assignment but two groups (smokers vs non-smokers) "experimental." Why is it not?',
      commonErrors: [
        {
          answer: 'Two-group study is experimental',
          misconception: 'Confusing the presence of groups with experimental design.',
          correctsTo: 'An EXPERIMENT requires the researcher to MANIPULATE the IV — random assignment to conditions. Comparing smokers vs non-smokers is QUASI-EXPERIMENTAL or CORRELATIONAL — the researcher didn\'t assign smoking; participants chose. Smokers and non-smokers may differ in dozens of ways (income, exercise, diet, genetics) that confound the comparison. To establish causation of smoking on health, you\'d need to randomly assign people to smoke (which is unethical) — hence the heavy reliance on observational + epidemiological studies for tobacco research, with all their causal limitations.',
        },
      ],
      estimatedMinutes: 3,
    },
    {
      id: 'recap',
      kind: 'recap',
      mustRemember: [
        'Experiments require manipulation + random assignment.',
        'Correlational designs: cannot establish causation.',
        'IV = manipulated; DV = measured.',
        'Confounds threaten internal validity.',
        'Double-blind eliminates participant + experimenter bias.',
        'r ranges -1 to +1; magnitude = strength, sign = direction.',
      ],
      estimatedMinutes: 1,
    },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
