/**
 * AP Physics 2 — Electrostatics (Coulomb's law, fields, potential).
 */

import type { LessonPlan } from '../types';

export const SEED_AP_PHYSICS_2_ELECTROSTATICS: LessonPlan = {
  id: 'evelyn.ap.physics-2.electrostatics.v1',
  title: 'AP Physics 2 — Electrostatics: Charges, Fields, Potentials',
  curriculum: 'AP',
  grade: '11',
  subject: 'science',
  topic: 'ap-physics-2',
  locale: 'en',
  los: [{ id: 'ap.physics-2.electrostatics', description: 'Apply Coulomb\'s law, electric field/potential calculations, Gauss\'s law for symmetric charge distributions.', standard: 'AP-PHYS-2-UNIT-1' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Electrostatics is half of AP Physics 2 — and Gauss\'s law is the unifying tool for symmetric charge distributions.', script: 'Coulomb\'s law for point charges. Field lines for visualisation. Gauss\'s law for high symmetry. Potential as energy per unit charge. Today: the workhorse formulas + symmetry exploitation.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Coulomb, field, potential, Gauss, capacitance.', keyIdeas: [
      'COULOMB\'S LAW: F = kq₁q₂/r². k = 1/(4πε₀) ≈ 8.99 × 10⁹ N·m²/C².',
      '  Same sign: repulsive. Different sign: attractive.',
      'ELECTRIC FIELD: E = F/q (field per unit positive test charge).',
      '  For point charge Q: E = kQ/r², direction radially outward (positive Q) or inward (negative Q).',
      '  Field lines: start on +, end on −. Density indicates magnitude.',
      'GAUSS\'S LAW: ∮ E·dA = Q_enclosed/ε₀.',
      '  Choose a Gaussian SURFACE matching symmetry of charge distribution.',
      '  SPHERE for point charge or sphere of charge.',
      '  CYLINDER for line of charge or infinite cylinder.',
      '  PILLBOX for plane of charge.',
      'COMMON results from Gauss:',
      '  Inside conductor at electrostatic equilibrium: E = 0.',
      '  Surface of conductor: E = σ/ε₀ (perpendicular).',
      '  Infinite plane of charge: E = σ/(2ε₀).',
      '  Two parallel plates with surface densities ±σ: E = σ/ε₀ between (uniform), 0 outside.',
      '  Infinite line charge with linear density λ: E = λ/(2πε₀r) at distance r.',
      'POTENTIAL: V = U/q. For point charge: V = kQ/r (with V → 0 at infinity).',
      '  E = −dV/dx (1D). Field points from high to low V.',
      '  Equipotential surfaces: V constant; E perpendicular to them.',
      '  ΔV = −∫E·dl.',
      'POTENTIAL ENERGY of point charges: U = kQ₁Q₂/r.',
      'CAPACITANCE: C = Q/V. For parallel plates: C = ε₀A/d (vacuum).',
      '  With dielectric κ: C = κε₀A/d. Increases by factor κ.',
      '  Energy stored: U = (1/2)CV² = (1/2)QV = Q²/(2C).',
      '  Capacitors in PARALLEL: C_eq = ΣC. In SERIES: 1/C_eq = Σ(1/C).',
      'WORK done by external agent moving charge: W = qΔV.',
    ], vocabulary: [{ term: 'electric field', definition: 'E = F/q; force per unit positive test charge; vector pointing in direction force on +q would point.' }, { term: 'Gauss\'s law', definition: '∮E·dA = Q_enc/ε₀; flux through closed surface equals enclosed charge / ε₀.' }], estimatedMinutes: 6 },
    { id: 'worked', kind: 'worked_example', problem: 'Use Gauss\'s law to find the electric field of a uniformly charged sphere of radius R, total charge Q, OUTSIDE the sphere (r > R).', steps: [
      'Symmetry: spherical. Use spherical Gaussian surface of radius r > R, concentric.',
      'E perpendicular to surface, magnitude same all over (by symmetry).',
      '∮ E·dA = E · 4πr² (uniform E over sphere area).',
      'Enclosed charge = total Q (since r > R).',
      'Gauss: E · 4πr² = Q/ε₀.',
      'E = Q/(4πε₀r²) = kQ/r².',
      'Result: looks identical to a POINT CHARGE at the center! (Standard "shell theorem" result.)',
    ], answer: 'E = kQ/r² (same as point charge)', estimatedMinutes: 5 },
    { id: 'try-1', kind: 'try_yourself', problem: 'Two parallel-plate capacitors of capacitance C₁ = 4 μF and C₂ = 6 μF are connected in series across 12 V. Find the equivalent capacitance and the charge on each.', expectedAnswer: 'Series: 1/C_eq = 1/4 + 1/6 = 3/12 + 2/12 = 5/12 → C_eq = 12/5 = 2.4 μF. In series, both capacitors carry the SAME charge: Q = C_eq · V = 2.4 × 10⁻⁶ × 12 = 2.88 × 10⁻⁵ C = 28.8 μC.', responseFormat: 'free', hints: ['Series adds reciprocals.', 'Charge is the same on each capacitor in series.'], estimatedMinutes: 3 },
    { id: 'misconception-field-vs-potential', kind: 'misconception_check', question: 'A student says "where E = 0, V must also be 0." Why is this wrong?', commonErrors: [{ answer: 'E = 0 implies V = 0', misconception: 'Confusing field magnitude with potential value.', correctsTo: 'E and V are different quantities. V is energy per charge; E is force per charge (related to V\'s spatial derivative). At a point where E = 0, V is just CONSTANT at that point — it can be any value (positive, negative, or zero). Counter-example: inside a conductor at electrostatic equilibrium, E = 0 everywhere inside, but V is some nonzero constant (e.g., 100 V if connected to a 100-V terminal). E = −dV/dx tells you E is zero where V is FLAT, not where V is zero.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['F = kq₁q₂/r²; E = F/q.', 'Gauss: ∮E·dA = Q_enc/ε₀; use symmetry.', 'V = kQ/r for point charge; E = −dV/dx.', 'Capacitor: C = Q/V; parallel sums; series adds reciprocals.', 'Energy stored: U = (1/2)CV².'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
