/**
 * AP Psychology — CED Unit 1.6+2.1: Sensation and Perception.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_PSYCH_U1_SENSATION_PERCEPTION: LessonPlan = {
  id: 'evelyn.ap.psych.sensation-perception.v1', title: 'U1.6 Sensation and Perception',
  curriculum: 'AP', grade: '11', subject: 'ss', topic: 'ap-psychology', locale: 'en',
  los: [{ id: 'appsych.sensation-perception', description: 'Distinguish sensation from perception. Identify thresholds and sensory adaptation. Trace visual and auditory pathways. Apply Gestalt principles, depth cues, and explanations of perceptual illusions.', standard: 'AP-PSYCH-1.6+2.1' }],
  prerequisites: ['appsych.consciousness-sleep'], followUps: [], estimatedMinutes: 22,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame the gap between sensation and perception.', script: "Sensation is what your sense organs DETECT. Perception is what your brain MAKES of it. They\'re different — illusions reveal the gap. Today: how the brain converts physical energy into meaningful experience.", estimatedMinutes: 2 },
    { id: 'concept-sensation', kind: 'concept', goal: 'Cover sensation, perception, vision, hearing, principles.',
      keyIdeas: [
        'SENSATION: detection of stimuli by sense organs (bottom-up).',
        'PERCEPTION: interpretation of sensations into meaningful experience (top-down).',
        '  • Top-down: experience, expectations, context shape what we perceive.',
        '  • Bottom-up: raw sensory input drives perception.',
        'THRESHOLDS:',
        '  • ABSOLUTE THRESHOLD: minimum stimulus intensity detectable 50% of the time. e.g., a candle 30 miles on a clear dark night.',
        '  • DIFFERENCE THRESHOLD (just-noticeable difference, JND): smallest difference between two stimuli detectable 50% of the time.',
        '  • WEBER\'S LAW: JND is a CONSTANT PROPORTION of original stimulus. e.g., for weight, JND ≈ 2% (so JND for 100 g is 2 g; for 10 kg is 200 g).',
        '  • SUBLIMINAL: below absolute threshold; minimal influence on behavior despite popular myth.',
        'SENSORY ADAPTATION: continuous unchanging stimulus diminishes in awareness. Cool pool feels less cold after a few minutes. Important: perception emphasizes CHANGE.',
        'SIGNAL DETECTION THEORY: detecting a stimulus depends on both sensory sensitivity AND psychological factors (motivation, expectation, fatigue). Explains why thresholds vary.',
        'VISION (most-tested):',
        '  • Light → CORNEA (clear front) → PUPIL (controlled by IRIS) → LENS (focuses) → RETINA (back of eye) → OPTIC NERVE → BRAIN (lateral geniculate nucleus → primary visual cortex).',
        '  • RETINA contains:',
        '    - RODS: dim-light/peripheral, no color.',
        '    - CONES: bright-light/color/sharp detail. Three types (red, green, blue) — TRICHROMATIC theory.',
        '  • OPPONENT-PROCESS theory: cells respond to PAIRS of colors (red-green, blue-yellow, white-black). Explains afterimages.',
        '  • COLORBLINDNESS: usually deficiency in one cone type; X-linked, more common in males.',
        '  • BLIND SPOT: where optic nerve exits retina; brain "fills in" so we don\'t notice.',
        'HEARING:',
        '  • Sound waves → OUTER EAR → EARDRUM → middle ear (3 BONES: hammer/anvil/stirrup) → COCHLEA (fluid-filled, contains hair cells) → AUDITORY NERVE → BRAIN.',
        '  • PITCH PERCEPTION: place theory (high pitch = vibration at base of cochlea); frequency theory (low pitch = neuron firing rate).',
        '  • CONDUCTIVE HEARING LOSS: damage to outer/middle ear (e.g., ruptured eardrum).',
        '  • SENSORINEURAL HEARING LOSS: damage to cochlea hair cells or auditory nerve. Permanent. Caused by aging, loud noise.',
        'GESTALT PRINCIPLES (Gestalt = "whole" — German): how we organize perception.',
        '  • FIGURE-GROUND: distinguish object (figure) from background.',
        '  • PROXIMITY: things near each other grouped together.',
        '  • SIMILARITY: similar things grouped.',
        '  • CLOSURE: brain fills in incomplete shapes.',
        '  • CONTINUITY: prefer smooth, continuous patterns.',
        '  • COMMON FATE: things moving together perceived as related.',
        'DEPTH PERCEPTION (3D):',
        '  • BINOCULAR cues (require both eyes):',
        '    - RETINAL DISPARITY: difference between L and R eye images. Greater disparity = closer.',
        '    - CONVERGENCE: eye muscles converge for closer objects.',
        '  • MONOCULAR cues (one eye sufficient):',
        '    - INTERPOSITION: closer objects block farther.',
        '    - LINEAR PERSPECTIVE: parallel lines converge in distance.',
        '    - RELATIVE SIZE: smaller image = farther.',
        '    - TEXTURE GRADIENT: details fade with distance.',
        '    - LIGHT AND SHADOW.',
        '    - ELEVATION (height in field): higher = farther.',
        '    - MOTION PARALLAX: closer objects move faster across visual field as you move.',
        'PERCEPTUAL CONSTANCIES: perceived size/shape stays constant despite changing retinal image.',
        '  • Size constancy: a friend stays "person-sized" whether near or far.',
        '  • Shape constancy: door is "rectangular" even when angled.',
      ],
      vocabulary: [
        { term: 'absolute threshold', definition: 'minimum stimulus detectable 50% of the time.' },
        { term: 'sensory adaptation', definition: 'diminishing awareness of unchanging stimulus.' },
        { term: 'top-down processing', definition: 'perception influenced by experience and expectations.' },
        { term: 'gestalt', definition: 'organized whole; perception groups elements.' },
      ],
      estimatedMinutes: 7 },
    { id: 'worked-illusion', kind: 'worked_example',
      problem: 'Why do railroad tracks appear to converge in the distance even though they are parallel? Use perception concepts.',
      steps: [
        'STEP 1 — LINEAR PERSPECTIVE: a monocular depth cue. The brain interprets converging lines as receding into distance.',
        'STEP 2 — Together with TEXTURE GRADIENT (railway ties getting more closely spaced) and RELATIVE SIZE (ties appearing smaller), the visual system constructs a 3D scene from a 2D retinal image.',
        'STEP 3 — Top-down processing fills in: we KNOW tracks don\'t actually converge. So we perceive them AS receding rather than as converging.',
        'STEP 4 — Despite the retinal image being literally converging, perceptual constancy and depth interpretation override this. We see depth, not literal convergence.',
        'STEP 5 — Artists use linear perspective deliberately: drawing parallel lines as converging gives the illusion of depth on a 2D page.',
      ],
      answer: 'Linear perspective + relative size cue depth; perceptual constancy maintains "parallel" interpretation.', estimatedMinutes: 4 },
    { id: 'try-gestalt', kind: 'try_yourself',
      problem: 'For each, identify the Gestalt principle: (a) Three dots arranged ::: are perceived as two columns. (b) An incomplete circle is perceived as a circle. (c) A flock of birds moving together is perceived as one entity.',
      expectedAnswer: '(a) PROXIMITY (close dots grouped) or possibly SIMILARITY. \n(b) CLOSURE (brain fills in gap). \n(c) COMMON FATE (moving together = related).',
      responseFormat: 'free', hints: ['Match: proximity/similarity/closure/continuity/common fate.'], estimatedMinutes: 2 },
    { id: 'try-depth', kind: 'try_yourself',
      problem: 'You close one eye and can still tell distances reasonably well. (a) Which depth cues are still available? (b) Which are lost? (c) Why might this matter for someone with vision loss in one eye?',
      expectedAnswer: '(a) MONOCULAR cues still available: linear perspective, relative size, texture gradient, interposition, elevation, motion parallax (especially if you move), light and shadow. \n(b) LOST: BINOCULAR cues — retinal disparity and convergence. \n(c) People with monocular vision (one eye blind) lose binocular depth cues. Can still drive, work, etc., but: \n• Reduced ability to judge distance precisely (parking, sports). \n• Tend to rely more on monocular cues (motion parallax — moving head). \n• Adaptation generally good, but some occupations (pilots, surgeons) require binocular depth perception.',
      responseFormat: 'free', hints: ['Binocular needs 2 eyes; monocular cues remain.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. A patient with cortical blindness (damage to occipital lobe, primary visual cortex) cannot CONSCIOUSLY see, yet shows "blindsight" — they can sometimes accurately point at objects placed in their visual field. (a) What does this reveal about the relationship between sensation, perception, and consciousness? (b) Trace where the visual signal must be reaching. (c) Compare to patients with damage to ASSOCIATION areas of cortex (where perception is interpreted) — what symptoms might they show?',
      expectedAnswer: '(a) BLINDSIGHT reveals:\n• SENSATION (eye detecting stimulus and signal reaching the brain) and CONSCIOUS PERCEPTION can be DECOUPLED. \n• Visual information can REACH and INFLUENCE behavior without entering conscious awareness. \n• Perception and consciousness emerge from cortical processing — not just from raw sensation. (2)\n(b) Pathway:\n• Signals from retina go to LATERAL GENICULATE NUCLEUS (LGN). \n• Most signals proceed to PRIMARY VISUAL CORTEX (V1) for conscious processing. \n• Some signals branch to OTHER ROUTES — the SUPERIOR COLLICULUS in midbrain (involved in orienting movements) and to extrastriate cortex via subcortical pathways. \n• These pathways enable behavior (pointing) without conscious awareness. \n• Cortical blindness: V1 damaged, conscious perception lost. But subcortical visual pathways still functioning. (2.5)\n(c) Patients with damage to ASSOCIATION (interpretation) areas:\n• Can SEE (V1 intact) but cannot RECOGNIZE objects/faces. \n• PROSOPAGNOSIA: face-blindness from damage to fusiform face area (right temporal). Patients can describe a face\'s features but cannot identify whose face it is. \n• AGNOSIA: more general — cannot recognize objects despite intact vision. \n• These are PERCEPTUAL deficits with SENSATION intact. Mirrors blindsight: sensation without perception (blindsight) vs. sensation without recognition (agnosia). (2)\nTotal: 6.5 points.',
      responseFormat: 'frq', hints: ['Decouple sensation/perception/consciousness; multiple pathways.'], estimatedMinutes: 6 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Sensation = detect; perception = interpret. Top-down + bottom-up.',
      'Vision: eye → retina (rods, cones — trichromatic) → optic nerve → cortex.',
      'Hearing: outer ear → eardrum → middle bones → cochlea hair cells.',
      'Gestalt: figure-ground, proximity, similarity, closure, continuity, common fate.',
      'Depth cues: binocular (retinal disparity, convergence) + monocular (perspective, size, texture).',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '1', cedTopic: '1.6+2.1', cedTitle: 'Sensation and Perception', sources: [{ type: 'concept', book: 'feldman', chapter: '3', note: 'Standard sensation + perception.' }] },
};
