/**
 * AP Psychology — CED Unit 4 (Social): Conformity, Obedience, Bystander
 * Effect, Group Behavior.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_PSYCH_U4_SOCIAL_INFLUENCE: LessonPlan = {
  id: 'evelyn.ap.psych.social-influence.v1', title: 'U4.2 Social Influence',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-psychology', locale: 'en',
  los: [{ id: 'appsych.social-influence', description: 'Identify conformity (Asch), obedience (Milgram), and bystander effect (Darley & Latané). Distinguish normative vs informational social influence. Recognize group polarization, groupthink, deindividuation, social facilitation/loafing.', standard: 'AP-PSYCH-4-INFLUENCE' }],
  prerequisites: ['appsych.attribution-attitudes'], followUps: ['appsych.prejudice-stereotypes'], estimatedMinutes: 22,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame social pressure.', script: "Most people will OBEY clearly unethical orders if given by an authority figure. They\'ll go along with a group even when the group is obviously wrong. They\'ll fail to help in emergencies if others are present. Today: the dark patterns of social influence.", estimatedMinutes: 2 },
    { id: 'concept-influence', kind: 'concept', goal: 'Cover conformity, obedience, bystander, group dynamics.',
      keyIdeas: [
        'CONFORMITY: changing behavior or beliefs to match a group.',
        '',
        'ASCH\'S LINE STUDY (1955):',
        '  • Subject + 5-7 confederates compared three lines to a standard.',
        '  • Confederates unanimously gave WRONG answer.',
        '  • ~37% of trials, real subjects CONFORMED to wrong answer.',
        '  • ~75% of subjects conformed at least ONCE.',
        '  • Showed: people conform even when answer is OBVIOUSLY WRONG.',
        '  • Conformity higher when: group of 3-5+, unanimous group, no allies, public response, ambiguous task.',
        '',
        'TWO TYPES OF SOCIAL INFLUENCE:',
        '  • NORMATIVE: conform to fit in, avoid rejection. Public compliance, private disagreement possible.',
        '  • INFORMATIONAL: conform to be RIGHT, accept group as valid info source. Private internalization.',
        '',
        'OBEDIENCE: changing behavior in response to a direct command from authority.',
        '',
        'MILGRAM\'S OBEDIENCE STUDY (1961-63):',
        '  • Subjects told to administer "shocks" to a "learner" (confederate) for wrong answers.',
        '  • Shocks ranged from 15V to 450V (XXX = "Danger: Severe Shock").',
        '  • As shocks increased, "learner" screamed, banged on wall, eventually went silent.',
        '  • EXPERIMENTER: "The experiment requires you continue."',
        '  • RESULTS: 65% of subjects continued to maximum 450V — even after the "learner" went silent.',
        '  • Many subjects showed visible distress but continued.',
        '  • Experimenter\'s authority + situational pressure overrode personal conscience.',
        '  • Conducted just after Holocaust; helped explain how ordinary people committed atrocities.',
        '',
        'OBEDIENCE FACTORS:',
        '  • CLOSER VICTIM: less obedience.',
        '  • PHYSICAL DISTANCE FROM AUTHORITY: less obedience.',
        '  • PRESTIGE OF INSTITUTION: more obedience.',
        '  • DISSENTING PEER: huge reduction in obedience.',
        '  • FOOT-IN-THE-DOOR: gradual escalation makes refusal harder.',
        '',
        'BYSTANDER EFFECT (Darley & Latané, 1968):',
        '  • The MORE BYSTANDERS, the LESS LIKELY any individual will help.',
        '  • Triggered by 1964 Kitty Genovese case (allegedly 38 witnesses ignored attack — later disputed).',
        '  • DIFFUSION OF RESPONSIBILITY: each person assumes someone else will help.',
        '  • PLURALISTIC IGNORANCE: looking at others\' inaction interprets situation as not requiring help.',
        '  • SOLO observer: 75% help. With 5 bystanders: only 38% help.',
        '  • OVERCOMING: directly call on specific people ("YOU, in the blue shirt — call 911").',
        '',
        'SOCIAL FACILITATION: presence of others IMPROVES performance on EASY/well-learned tasks but IMPAIRS performance on HARD/new tasks.',
        '',
        'SOCIAL LOAFING: people exert LESS effort in group tasks. Each individual\'s contribution less identifiable. Bigger groups → less individual effort.',
        '',
        'DEINDIVIDUATION: loss of self-awareness in group. Anonymity + arousal → uncharacteristic behavior. Riots, mob violence, online trolling.',
        '',
        'GROUP POLARIZATION: discussion among LIKE-MINDED people INTENSIFIES initial views. Group becomes MORE EXTREME than any individual.',
        '',
        'GROUPTHINK (Janis): in cohesive groups, desire for harmony OVERRIDES rational evaluation. Bay of Pigs, Challenger disaster.',
        '  • Symptoms: illusion of invulnerability, rationalization, suppression of dissent, mindguarding.',
      ],
      vocabulary: [
        { term: 'conformity', definition: 'changing behavior/beliefs to match group.' },
        { term: 'obedience', definition: 'compliance with command from authority.' },
        { term: 'bystander effect', definition: 'larger group → less individual likelihood of helping.' },
        { term: 'groupthink', definition: 'cohesive group prioritizes harmony over rational analysis.' },
      ],
      estimatedMinutes: 7 },
    { id: 'worked-milgram', kind: 'worked_example',
      problem: 'In Milgram\'s study, 65% of subjects went to 450V. Predict what would happen if: (a) experimenter was present in person but NOT in lab coat. (b) Two other "teachers" refused to continue.',
      steps: [
        '(a) Less prestige → LESS obedience. Authority cues (lab coat, professional setting) signal legitimacy.',
        '   - Milgram\'s actual variant: when experimenter wore street clothes, obedience dropped substantially.',
        '   - Suggests: AUTHORITY cues, not just authority figure, drive obedience.',
        '(b) Dissenting PEERS dramatically reduce obedience.',
        '   - Milgram\'s variant: with one defying peer, obedience dropped from 65% to ~10%.',
        '   - Two defying peers further reduced.',
        '   - SOCIAL ALLIES enable individual courage. Dissenters create permission to refuse.',
        '(c) Implication: ordinary people CAN resist if SUPPORTED. Resistance is contagious.',
      ],
      answer: 'Less authority → less obedience. Allies dramatically reduce obedience.', estimatedMinutes: 3 },
    { id: 'try-bystander', kind: 'try_yourself',
      problem: 'You see someone collapse on a busy street. (a) Why might NOBODY help? (b) Suggest TWO ways to overcome the bystander effect.',
      expectedAnswer: '(a) BYSTANDER EFFECT mechanisms:\n• DIFFUSION OF RESPONSIBILITY: "Someone else will call 911." Each bystander assumes another will. \n• PLURALISTIC IGNORANCE: "Nobody else looks alarmed, so maybe it\'s not an emergency." Looking at others\' calm inaction interprets situation as non-urgent. \n• EVALUATION APPREHENSION: fear of looking foolish if it\'s not actually an emergency. \n• In Latané\'s research: solo bystander → 75% help. With 5 bystanders → 38%. \n(b) Overcoming bystander effect:\n(1) DIRECT CALL: point to a specific person. "You, in the blue shirt — call 911 now." Removes diffusion. \n(2) ASSESS quickly and act first; others are more likely to follow once someone moves. \n(3) NAME the situation: "This man is having a heart attack — we need help!" Eliminates pluralistic ignorance. \n(4) Be the FIRST helper; create example for others. \n(5) Education on bystander effect makes future helping more likely (research-supported).',
      responseFormat: 'free', hints: ['Diffusion + ignorance; specific calls.'], estimatedMinutes: 3 },
    { id: 'try-group-dynamics', kind: 'try_yourself',
      problem: 'For each, identify the social phenomenon: (a) An online forum of conspiracy theorists radicalizes its members\' views. (b) JFK\'s advisors all agreed to the Bay of Pigs invasion despite individual doubts. (c) An anonymous mob at a sports event turns destructive. (d) Bigger group = less individual effort on a project.',
      expectedAnswer: '(a) GROUP POLARIZATION — like-minded people intensify each other\'s views. \n(b) GROUPTHINK — desire for harmony overrides rational evaluation; dissent suppressed. \n(c) DEINDIVIDUATION — loss of self-awareness in anonymous group. \n(d) SOCIAL LOAFING — individual effort decreases as group size grows; less individual accountability.',
      responseFormat: 'free', hints: ['Match phenomenon to symptom.'], estimatedMinutes: 2 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. (a) Compare ASCH\'s conformity finding (37% conform on wrong answer) and MILGRAM\'s obedience (65% to 450V). What\'s SIMILAR? What\'s DIFFERENT? (b) The Holocaust raised the question: how could ordinary people commit atrocities? Apply MILGRAM\'s framework. (c) Suggest TWO ways an organization could PROTECT against groupthink.',
      expectedAnswer: '(a) SIMILAR:\n• Both reveal SITUATIONAL POWER over individual judgment. \n• Both show PEOPLE GO ALONG against personal beliefs/values. \n• Both involve compliance to social/authority pressure. \nDIFFERENT:\n• Asch: PEER pressure (group of equals). Milgram: AUTHORITY pressure (experimenter). \n• Asch: subject knows answer is wrong (low ambiguity). Milgram: subject knows shock is harmful but is told to continue. \n• Asch: more about acceptance/rejection. Milgram: about responsibility/authority. \n• Both essential for understanding social influence. (2)\n(b) Milgram\'s framework on Holocaust:\n• Ordinary German citizens did atrocities under authority of Nazi officials. \n• Milgram\'s 65% obedience suggests this isn\'t exceptional moral failure but ORDINARY RESPONSE TO AUTHORITY structure. \n• AUTHORITY + GRADUAL ESCALATION + DISTANCE FROM VICTIM + STATE-LEGITIMIZED INSTITUTION → systematic harm. \n• Subjects in Milgram showed VISIBLE DISTRESS but continued — the PSYCHOLOGY OF OBEDIENCE creates internal conflict but rarely refusal. \n• Implications for accountability: individuals MUST resist authority that conflicts with conscience. Systemic changes needed too. (2)\n(c) Protection against groupthink:\n(1) DEVIL\'S ADVOCATE: assign one member to deliberately challenge consensus. \n(2) OUTSIDE EXPERTS — bring in fresh perspectives. \n(3) ANONYMOUS POLLING — voting before discussion captures genuine views. \n(4) LEADER WITHHELD opinion until others speak. Explicit ENCOURAGEMENT of dissent. \n(5) Multiple ALTERNATIVE PLANS evaluated. \n(6) PRE-MORTEM exercise: imagine plan failed; identify why. \n(7) Smaller subcommittees to question. \n(8) Time to RECONSIDER decisions. (2)\nTotal: 6 points.',
      responseFormat: 'frq', hints: ['Compare studies; apply to atrocities; preventive strategies.'], estimatedMinutes: 6 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Asch: ~37% conform on obviously wrong answer; allies reduce dramatically.',
      'Milgram: 65% obey to 450V; authority + escalation + distance.',
      'Bystander effect: more witnesses → less help (diffusion + pluralistic ignorance).',
      'Group polarization, groupthink, deindividuation, social loafing/facilitation.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '4', cedTopic: '4-INFLUENCE', cedTitle: 'Social Influence', sources: [{ type: 'concept', book: 'feldman', chapter: '14', note: 'Standard Asch + Milgram + bystander.' }] },
};
