/**
 * AP Psychology — CED Unit 2.2: Thinking, Problem Solving, and Language.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_PSYCH_U2_THINKING_LANGUAGE: LessonPlan = {
  id: 'evelyn.ap.psych.thinking-language.v1', title: 'U2.4 Thinking, Problem Solving, and Language',
  curriculum: 'AP', grade: '11', subject: 'science', topic: 'ap-psychology', locale: 'en',
  los: [{ id: 'appsych.thinking-language', description: 'Identify problem-solving strategies (algorithms, heuristics). Recognize cognitive biases (representativeness, availability, anchoring, confirmation bias). Trace language acquisition stages and the linguistic relativity hypothesis.', standard: 'AP-PSYCH-2.2' }],
  prerequisites: ['appsych.memory-forgetting'], followUps: ['appsych.intelligence'], estimatedMinutes: 22,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame thinking as biased.', script: "Humans are NOT rational decision-makers. We rely on shortcuts (HEURISTICS) that work most of the time but fail predictably. Today: how thinking actually works, the biases that fool us, and the parallel question of language.", estimatedMinutes: 2 },
    { id: 'concept-thinking', kind: 'concept', goal: 'Cover problem-solving + heuristics + biases + language.',
      keyIdeas: [
        'PROBLEM-SOLVING strategies:',
        '',
        '  • ALGORITHM: step-by-step procedure GUARANTEED to find solution. Slow but reliable. Long division, checking every cabinet for keys.',
        '  • HEURISTIC: mental shortcut. Fast but fallible. Works MOST of the time. Looking only where you LIKELY left the keys.',
        '',
        'INSIGHT: sudden realization (Aha! moment). Brain activity spikes in right temporal lobe.',
        '',
        'OBSTACLES to problem-solving:',
        '  • CONFIRMATION BIAS: seek info confirming beliefs, ignore contradicting. Big problem in research, politics, judgments.',
        '  • FIXATION: getting stuck on one approach.',
        '  • MENTAL SET: tendency to use solutions that worked before, even when inappropriate.',
        '  • FUNCTIONAL FIXEDNESS: difficulty seeing objects in new ways. Can\'t see a screwdriver as a chisel.',
        '',
        'JUDGMENT / DECISION-MAKING heuristics:',
        '',
        '  • REPRESENTATIVENESS: judge by how typical something is of a category. Misleading when:\n     - Stereotypes outweigh base rates.\n     - "Linda is a librarian or a feminist librarian" → people say more likely feminist librarian (false; conjunction can\'t be more probable than single).',
        '',
        '  • AVAILABILITY: judge by how easily examples come to mind.\n     - Overestimate plane crashes (memorable) but underestimate car deaths (mundane).\n     - News coverage skews availability.\n     - Recent personal experience also amplifies.',
        '',
        '  • ANCHORING: rely too heavily on first piece of info ("anchor").\n     - Negotiation: first offer biases all subsequent offers.\n     - Salaries, prices, even unrelated numbers (judge\'s sentence influenced by numbers given).',
        '',
        '  • CONFIRMATION BIAS: see above.',
        '',
        '  • OVERCONFIDENCE: people more confident than accurate. 90% sure → only right ~75% of time.',
        '',
        '  • FRAMING EFFECTS: same option different reactions depending on presentation.\n     - 90% survival rate sounds better than 10% mortality rate (same data).',
        '',
        '  • BELIEF PERSEVERANCE: clinging to beliefs even when evidence disproves them.',
        '',
        'LANGUAGE:',
        '  • PHONEMES: smallest sound units (~40 in English).',
        '  • MORPHEMES: smallest meaningful units. "cats" = "cat" + "-s" (two morphemes).',
        '  • SEMANTICS: meaning of words and combinations.',
        '  • SYNTAX: grammatical rules for ordering words.',
        '',
        'LANGUAGE ACQUISITION STAGES:',
        '  • BABBLING (~4 months): infants produce phonemes from many languages.',
        '  • ONE-WORD STAGE (~12 months): "ball," "doggie." Mostly nouns.',
        '  • TWO-WORD STAGE (~24 months): "want cookie," "more milk." Telegraphic speech.',
        '  • SENTENCES (~3-4 years): grammar emerges; vocabulary explodes.',
        '  • CRITICAL PERIOD: ~age 7. Languages learned BEFORE near-native; AFTER significantly harder.',
        '',
        'CHOMSKY: language acquisition device (LAD) — innate predisposition to language. Universal grammar across all languages.',
        '',
        'LINGUISTIC RELATIVITY (Sapir-Whorf): language SHAPES thought.',
        '  • STRONG version: language DETERMINES what we can think.',
        '  • WEAK version: language INFLUENCES thinking.',
        '  • Evidence: bilinguals report personality differences in different languages. Russian speakers (with two words for blue) discriminate shades faster.',
        '  • Modern view: weak version supported; thought possible without language.',
      ],
      vocabulary: [
        { term: 'heuristic', definition: 'mental shortcut for problem-solving; fast but fallible.' },
        { term: 'representativeness heuristic', definition: 'judge by similarity to category prototype.' },
        { term: 'availability heuristic', definition: 'judge by ease of recall from memory.' },
        { term: 'linguistic relativity', definition: 'language shapes thought (weak version supported).' },
      ],
      estimatedMinutes: 7 },
    { id: 'worked-bias', kind: 'worked_example',
      problem: 'A person hears about three plane crashes in two months. They become afraid to fly even though statistical risk hasn\'t changed. Identify the heuristic and explain.',
      steps: [
        'STEP 1 — AVAILABILITY HEURISTIC at work.',
        'STEP 2 — Plane crashes are RARE but DRAMATIC and EXTENSIVELY COVERED in news. Three recent events makes them MORE AVAILABLE in memory.',
        'STEP 3 — Brain estimates probability based on EASE OF RECALL.',
        'STEP 4 — Recent media coverage → easy recall → "feels likely."',
        'STEP 5 — REALITY: ~16,000 commercial flights per day. Crashes per million flights ~0.005. Driving 100 miles is statistically more dangerous.',
        'STEP 6 — Biased risk perception is COMMON: terrorism, shark attacks, lottery wins all overestimated due to availability.',
      ],
      answer: 'Availability heuristic — recent vivid examples bias risk perception.', estimatedMinutes: 3 },
    { id: 'try-bias', kind: 'try_yourself',
      problem: 'For each scenario, identify the cognitive bias: (a) An interviewer decides someone "isn\'t a fit" based on first 30 seconds. (b) Investing more in a stock you\'re losing money on because "it has to come back." (c) Believing your political party\'s claims while dismissing opposing party\'s.',
      expectedAnswer: '(a) FIRST IMPRESSION + ANCHORING + maybe CONFIRMATION BIAS — initial assessment becomes anchor; subsequent evidence is filtered to confirm. \n(b) SUNK COST FALLACY (related to belief perseverance) — past investment is gone, but emotional commitment makes it hard to cut losses. \n(c) CONFIRMATION BIAS — selectively accepting info that supports prior beliefs and dismissing contradicting info. The same study/quote received favorably by one party and dismissed by another.',
      responseFormat: 'free', hints: ['Match each to a named bias.'], estimatedMinutes: 3 },
    { id: 'try-language', kind: 'try_yourself',
      problem: '(a) Why are children better at learning a new language than adults? (b) Identify a piece of evidence supporting the linguistic relativity hypothesis.',
      expectedAnswer: '(a) Children advantage:\n• CRITICAL PERIOD — brain plasticity for language up to ~age 7. \n• Less inhibited; willing to make mistakes. \n• More exposure during peak language-learning years. \n• Easier to perceive non-native phonemes (adults\' phoneme discrimination narrows by age 1). \n• LAD (Chomsky): innate language acquisition device most active in early years. \n• ADULTS: must work harder, often retain accent (some never fully native-fluent). \n(b) Linguistic relativity evidence:\n• Russian speakers (siniy = dark blue, goluboy = light blue, two distinct words) discriminate blue shades FASTER than English speakers (one word "blue"). \n• Time perception: cultures with different metaphors for time (English: spatial linear, Mandarin: vertical) show different cognitive patterns. \n• Color naming influences color memory. \n• Bilingual people report personality differences across languages they speak. \n• WEAK version of Sapir-Whorf supported; STRONG version (language DETERMINES thought) less so — thought possible without language; pre-linguistic infants have rich cognition.',
      responseFormat: 'free', hints: ['Critical period; specific Whorf evidence.'], estimatedMinutes: 3 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. (a) Distinguish algorithms from heuristics with an example. (b) When ARE heuristics useful, despite their fallibility? (c) The ANCHORING bias is exploited in advertising. Give an example.',
      expectedAnswer: '(a) ALGORITHM: step-by-step procedure GUARANTEED to find solution. Slow but reliable. \nExample: long division — produces correct quotient by following all steps. \nHEURISTIC: mental shortcut. Fast but fallible. \nExample: trying solutions you\'ve seen work before; using rule-of-thumb to estimate price. (1.5)\n(b) Heuristics useful because:\n• REAL-WORLD problems often LACK time, info, or computational resources for algorithms. \n• Heuristics produce GOOD-ENOUGH answers QUICKLY. \n• Adaptive in evolutionary terms (faster survival decisions). \n• Most everyday decisions can\'t use algorithms (too many factors). \n• PROBLEM: predictable failures in specific cases (e.g., rare events, statistical reasoning). \n• KAHNEMAN/TVERSKY work shows the systematic biases that emerge. \n• KEY: heuristics work in PROBLEM-SPACES they evolved in (small-group decisions); fail in modern contexts (statistics, large-scale risks). (2)\n(c) ANCHORING in advertising:\n• Show "ORIGINAL PRICE: $100, NOW: $40" — $100 anchor makes $40 feel like a deal even if the market price is closer to $40. \n• Real estate agents show buyer expensive house first to anchor expectations. \n• "5 servings or fewer" packaging on cereal — implies smaller servings are normal. \n• Restaurant menus: place expensive item at top so other items seem cheaper. \n• Car dealerships start negotiations at high price; final price still benefits dealer. \n• Salary negotiation: employer\'s first offer anchors. (1.5)\nTotal: 5 points.',
      responseFormat: 'frq', hints: ['Mechanism + adaptive value + practical exploitation.'], estimatedMinutes: 5 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Algorithm (step-by-step, reliable) vs heuristic (shortcut, fast).',
      'Biases: representativeness, availability, anchoring, confirmation, overconfidence, framing.',
      'Functional fixedness, mental set, fixation block problem-solving.',
      'Language: phonemes → morphemes → semantics → syntax. Critical period ~age 7.',
      'Linguistic relativity: weak version supported (language influences thought).',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '2', cedTopic: '2.2', cedTitle: 'Thinking, Problem Solving, Language', sources: [{ type: 'concept', book: 'feldman', chapter: '8', note: 'Standard cognitive psychology + language.' }] },
};
