/**
 * AP Statistics — CED Unit 3.5+3.6: Experimental Design.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_STATS_U3_EXPERIMENTAL_DESIGN: LessonPlan = {
  id: 'evelyn.ap.stats.experimental-design.v1', title: 'U3.5 Experimental Design',
  curriculum: 'AP', grade: '12', subject: 'math', topic: 'ap-statistics', locale: 'en',
  los: [{ id: 'apstats.experimental-design', description: 'Identify experimental units, factors, treatments, response variable. Apply the principles of comparison, randomization, replication. Distinguish completely randomized, randomized block, and matched-pairs designs.', standard: 'AP-STATS-3.5-3.6' }],
  prerequisites: ['apstats.sampling-bias'], followUps: ['apstats.inference-experiments'], estimatedMinutes: 22,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame experiments and causation.', script: "Sampling tells us about a population. Experiments tell us whether ONE THING CAUSES ANOTHER. The trick: random ASSIGNMENT to treatments.", estimatedMinutes: 2 },
    { id: 'concept-experiment', kind: 'concept', goal: 'Cover experimental design vocabulary + principles + designs.',
      keyIdeas: [
        'KEY VOCABULARY:',
        '  • EXPERIMENTAL UNIT: the entity to which a treatment is applied (a person = subject; a plant; a plot of land).',
        '  • FACTOR: an explanatory variable that the experimenter manipulates.',
        '  • LEVELS: values of a factor (e.g., drug dose: 0mg, 50mg, 100mg).',
        '  • TREATMENT: a specific combination of factor levels applied to a unit.',
        '  • RESPONSE VARIABLE: what the experimenter measures.',
        'THREE PRINCIPLES of good experimental design:',
        '  • COMPARISON: include at least two treatment groups (often a CONTROL group). Without comparison, can\'t tell if treatment caused changes.',
        '  • RANDOMIZATION: randomly ASSIGN units to treatments. Balances out lurking variables across groups; this is what allows causal inference.',
        '  • REPLICATION: enough units per treatment to reduce chance variation.',
        'CONTROL GROUP: receives no treatment (or a placebo). Baseline for comparison.',
        'PLACEBO: a fake treatment that looks/tastes/feels real. Controls for the placebo effect.',
        'BLINDING:',
        '  • SINGLE-BLIND: subjects don\'t know which treatment they got.',
        '  • DOUBLE-BLIND: neither subjects nor those measuring outcomes know.',
        'CONFOUNDING: when an effect of one factor cannot be separated from the effect of another. Random assignment helps prevent confounding by lurking variables.',
        'DESIGN TYPES:',
        '  • COMPLETELY RANDOMIZED DESIGN (CRD): all units randomly assigned to treatments without grouping. Default and simplest.',
        '  • RANDOMIZED BLOCK DESIGN: group units into BLOCKS of similar units (e.g., by sex, age, school), then randomize WITHIN each block. Reduces variability when blocks differ on the response.',
        '  • MATCHED-PAIRS DESIGN: a special block design with blocks of size 2. Either pair similar subjects then randomize within each pair, OR each subject gets BOTH treatments (in random order).',
      ],
      vocabulary: [
        { term: 'control group', definition: 'a group receiving no treatment or a placebo, for comparison.' },
        { term: 'confounding', definition: 'when two variables\' effects are tangled and can\'t be separated.' },
        { term: 'block', definition: 'a group of similar experimental units; randomization happens within blocks.' },
      ],
      estimatedMinutes: 7 },
    { id: 'worked-design', kind: 'worked_example',
      problem: 'A researcher tests whether a new fertilizer increases tomato yield. She has 60 tomato plants. Describe a completely randomized design.',
      steps: [
        'STEP 1 — Identify: 60 experimental units (plants); factor = fertilizer (2 levels: new fertilizer vs control/standard); response = yield (lbs per plant).',
        'STEP 2 — Randomly assign 30 plants to "new fertilizer" and 30 to "control." Use RNG to label plants 1-60, draw 30 numbers without replacement for new-fertilizer group.',
        'STEP 3 — Apply treatments. Grow plants under otherwise identical conditions.',
        'STEP 4 — Measure yield. Compare mean yield in the two groups.',
        'STEP 5 — Use comparison + randomization + replication (n=30 per group). Single-blind isn\'t needed for plants. Apply standard significance test in Unit 7.',
      ],
      answer: 'Number plants 1-60; randomly assign 30 to new fertilizer, 30 to control; compare yields.', estimatedMinutes: 5 },
    { id: 'try-block', kind: 'try_yourself',
      problem: 'In a study of two reading methods on 4th-graders, the researcher knows MALE and FEMALE students often respond differently. There are 50 boys and 50 girls. Describe a randomized BLOCK design.',
      expectedAnswer: 'Block by sex: 50 boys form one block, 50 girls form another. WITHIN the boys block, randomly assign 25 to method A and 25 to method B. WITHIN the girls block, do the same. Compare methods within each block, then combine. This reduces variability due to sex differences.',
      responseFormat: 'free', hints: ['Blocks reduce variability when blocks differ on the response.'], estimatedMinutes: 4 },
    { id: 'try-confounding', kind: 'try_yourself',
      problem: 'A doctor compares two pain medications. He gives MEDICATION A to morning patients and MEDICATION B to afternoon patients. After 100 of each, B has lower pain scores. (a) Identify the lurking variable. (b) Why is causation suspect? (c) How to fix it?',
      expectedAnswer: '(a) Time of day (or anything correlating with morning vs afternoon — patient severity, alertness, doctor fatigue). (b) Time of day is CONFOUNDED with treatment. We can\'t tell if B is better than A or if afternoon patients differ from morning patients. (c) Use random assignment: take all patients (regardless of time) and randomly assign them to A or B with a random number generator. Or block by time-of-day and randomize within each block.',
      responseFormat: 'free', hints: ['Confounding = effects can\'t be separated.'], estimatedMinutes: 4 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Experiment vs observational: only experiment with random ASSIGNMENT can show causation.',
      'Three principles: COMPARISON, RANDOMIZATION, REPLICATION.',
      'CRD: random assignment overall. Block: randomize within blocks (similar units). Matched pairs: blocks of 2.',
      'Control + placebo + double-blind to handle the placebo effect.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '3', cedTopic: '3.5-3.6', cedTitle: 'Experimental Design', sources: [{ type: 'concept', book: 'tps5e', chapter: '4', note: 'Standard experimental design.' }] },
};
