/**
 * AP Statistics — CED Unit 8.4+8.5+8.6: Chi-Square Test for Two-Way
 * Tables (Homogeneity and Independence).
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_STATS_U8_TWOWAY: LessonPlan = {
  id: 'evelyn.ap.stats.chi-square-twoway.v1', title: 'U8.4 Chi-Square for Two-Way Tables',
  curriculum: 'AP', grade: '12', subject: 'math', topic: 'ap-statistics', locale: 'en',
  los: [{ id: 'apstats.chi-square-twoway', description: 'Compute expected counts in a two-way table: E = (row total · col total) / grand total. Distinguish chi-square test for HOMOGENEITY (multiple populations) vs INDEPENDENCE (one population, two variables). df = (r − 1)(c − 1).', standard: 'AP-STATS-8.4-8.6' }],
  prerequisites: ['apstats.chi-square-goodness-of-fit'], followUps: ['apstats.choosing-procedures'], estimatedMinutes: 24,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame two-variable chi-square.', script: "TWO categorical variables in a two-way table. We can ask: are the distributions the SAME across groups (homogeneity)? OR: are the two variables associated (independence)? Same test mechanics, different framing.", estimatedMinutes: 2 },
    { id: 'concept-twoway', kind: 'concept', goal: 'Cover homogeneity vs independence + the test.',
      keyIdeas: [
        'TWO TEST FLAVORS for two-way tables — same MECHANICS, different SETUP and HYPOTHESES:',
        'HOMOGENEITY: are the DISTRIBUTIONS of one variable the SAME across SEPARATE POPULATIONS or treatment groups?',
        '  • Multiple independent samples, one from each population (or treatment group).',
        '  • H_0: distribution of [response] is the same across [populations/groups].',
        '  • H_a: distributions differ.',
        'INDEPENDENCE (or association): are TWO VARIABLES INDEPENDENT in ONE POPULATION?',
        '  • One sample, classified by two variables.',
        '  • H_0: variables are INDEPENDENT.',
        '  • H_a: variables are NOT independent (associated).',
        'KEY: same data could be either test depending on study design. The math is identical; the framing differs.',
        'EXPECTED COUNT in a two-way table cell: E = (row total · column total) / grand total.',
        '  • Why: under H_0, the cell count = (row probability) × (col probability) × n. The expected formula computes this.',
        'TEST STATISTIC: χ² = Σ (O − E)² / E summed over ALL CELLS.',
        'DEGREES OF FREEDOM: df = (r − 1)(c − 1) where r = rows, c = columns.',
        'CONDITIONS:',
        '  • RANDOM: independent random samples (homogeneity) or one random sample (independence) or random assignment.',
        '  • LARGE COUNTS: ALL expected counts ≥ 5.',
        '  • 10% if applicable.',
        'AP CALCULATOR: χ²-Test (input matrix into [A]). Outputs χ², df, p-value, expected matrix.',
        'CONCLUSION TEMPLATE differs slightly:',
        '  • Homogeneity: "evidence that distribution of [response] DIFFERS across [populations]."',
        '  • Independence: "evidence of an ASSOCIATION between [variable A] and [variable B]."',
      ],
      vocabulary: [
        { term: 'chi-square test for homogeneity', definition: 'tests whether distributions of one variable are the same across multiple populations.' },
        { term: 'chi-square test for independence', definition: 'tests whether two variables are independent in a single population.' },
      ],
      estimatedMinutes: 6 },
    { id: 'worked-twoway', kind: 'worked_example',
      problem: 'In a survey of 300 students at a university, the table shows favorite drink by year: \n  | Coffee | Tea | Soda | Total\n  Freshman: 30 | 20 | 50 | 100\n  Sophomore: 50 | 30 | 20 | 100\n  Junior: 60 | 25 | 15 | 100\nIs there evidence of an association between year and drink preference?',
      steps: [
        'STEP 1 — H_0: year and drink preference are INDEPENDENT (one population, two variables → independence test). H_a: they are associated.',
        'STEP 2 — Column totals: Coffee 140, Tea 75, Soda 85. Grand total: 300.',
        'STEP 3 — Expected: E = (row total · col total) / grand total. Row totals = 100 each. \n  E_freshman_coffee = (100·140)/300 = 46.67. \n  E_freshman_tea = (100·75)/300 = 25. \n  E_freshman_soda = (100·85)/300 = 28.33. \n  Same for sophomores and juniors (since row totals are equal): E values repeat. \n  All E ≥ 5 ✓.',
        'STEP 4 — Conditions: Random ✓; Large Counts ✓; 10% ✓.',
        'STEP 5 — χ² = Σ(O−E)²/E. Computing each cell: \n  Freshman: (30−46.67)²/46.67 ≈ 5.95; (20−25)²/25 = 1; (50−28.33)²/28.33 ≈ 16.58. \n  Sophomore: (50−46.67)²/46.67 ≈ 0.24; (30−25)²/25 = 1; (20−28.33)²/28.33 ≈ 2.45. \n  Junior: (60−46.67)²/46.67 ≈ 3.81; (25−25)²/25 = 0; (15−28.33)²/28.33 ≈ 6.27. \n  Total χ² ≈ 5.95+1+16.58+0.24+1+2.45+3.81+0+6.27 ≈ 37.30.',
        'STEP 6 — df = (3−1)(3−1) = 4. p-value = P(χ²_4 ≥ 37.30) ≈ very small (< 0.001).',
        'STEP 7 — At α = 0.05: REJECT H_0.',
        'STEP 8 — Conclusion: "Because p < 0.001 < α = 0.05, we reject H_0. There IS convincing statistical evidence of an ASSOCIATION between year and drink preference at this university."',
      ],
      answer: 'χ² ≈ 37.3, df = 4, p < 0.001 → reject H_0; evidence of association.', estimatedMinutes: 7 },
    { id: 'try-test', kind: 'try_yourself',
      problem: 'A 2x3 table has observed counts:\nA: 30 | 40 | 30 (row total 100)\nB: 50 | 30 | 20 (row total 100)\nColumn totals: 80, 70, 50; Grand total: 200. Test whether the row distributions differ (homogeneity).',
      expectedAnswer: 'H_0: distributions are the same in A and B; H_a: they differ. \nExpected: cell = (row·col)/total. E_A1 = 100·80/200 = 40; E_A2 = 35; E_A3 = 25; E_B1 = 40; E_B2 = 35; E_B3 = 25. All ≥ 5 ✓. \nχ² = (30−40)²/40 + (40−35)²/35 + (30−25)²/25 + (50−40)²/40 + (30−35)²/35 + (20−25)²/25 \n= 2.5 + 0.714 + 1 + 2.5 + 0.714 + 1 = 8.428. \ndf = (2−1)(3−1) = 2. p-value = P(χ²_2 ≥ 8.428) ≈ 0.0148. \n0.0148 < 0.05 → REJECT H_0. \nConclusion: "Because p ≈ 0.015 < α = 0.05, we reject H_0. Evidence the two row distributions differ."',
      responseFormat: 'frq', hints: ['Compute expecteds; sum (O-E)²/E; df = (r-1)(c-1).'], estimatedMinutes: 6 },
    { id: 'try-which', kind: 'try_yourself',
      problem: 'For each scenario, identify whether to use chi-square for HOMOGENEITY or INDEPENDENCE: \n(a) A teacher takes ONE random sample of 200 students and asks each their favorite subject AND their grade level. Test if these are associated. \n(b) Three separate random samples of 100 from each of three different schools. Asks each student their favorite subject. Test if subject preferences differ across schools. \n(c) A clinical trial randomly assigns 200 subjects to drug A or placebo and records whether each improves.',
      expectedAnswer: '(a) INDEPENDENCE — one sample, two variables. (b) HOMOGENEITY — multiple separate samples (populations). (c) HOMOGENEITY — random ASSIGNMENT to treatments creates separate "populations." (Sometimes also analyzed as independence; AP convention: with random ASSIGNMENT call it homogeneity.)',
      responseFormat: 'free', hints: ['One sample with 2 variables → independence. Multiple samples → homogeneity.'], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'E = (row · col)/total. df = (r−1)(c−1).',
      'HOMOGENEITY: distributions same across populations? Multiple samples.',
      'INDEPENDENCE: two variables independent? One sample.',
      'Same math; phrase conclusion to match design.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '8', cedTopic: '8.4-8.6', cedTitle: 'Chi-Square Two-Way', sources: [{ type: 'concept', book: 'tps5e', chapter: '11', note: 'Standard 2-way chi-square.' }] },
};
