/**
 * AP Spanish Literature — Poetry Analysis.
 */

import type { LessonPlan } from '../types';

export const SEED_AP_SPANISH_LIT_POETRY: LessonPlan = {
  id: 'evelyn.ap.spanish-lit.poetry.v1',
  title: 'AP Spanish Literature — Poetry Analysis',
  curriculum: 'AP',
  grade: '11',
  subject: 'languages',
  topic: 'ap-spanish-lit',
  locale: 'en',
  los: [{ id: 'ap.spanish-lit.poetry', description: 'Apply AP Spanish Lit poetry analysis: form, meter, sound devices, theme, historical context.', standard: 'AP-SPAN-LIT' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 16,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'AP Spanish Lit poetry questions reward FORM-meaning analysis — same as English Lit but in Spanish.', script: 'Sonnets of Quevedo, free verse of Neruda, romances of Lorca. Each form constrains and enables. Today: how to analyse poetic form linked to theme + period.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Form types, sound devices, theme analysis, historical context.', keyIdeas: [
      'KEY POETIC FORMS in Spanish:',
      '  SONETO (sonnet): 14 lines, typically iambic pentameter (endecasílabo), rhymed ABBA ABBA CDC DCD or variant. Quevedo, Lope de Vega, Sor Juana Inés de la Cruz.',
      '  ROMANCE (ballad): 8-syllable lines (octosílabos), assonant rhyme on even lines. Folkloric and modern (Lorca\'s "Romancero gitano").',
      '  SILVA: irregular meter, traditionally 7- and 11-syllable lines mixed. Used by Quevedo, Góngora.',
      '  VERSO LIBRE (free verse): no fixed meter or rhyme. Used by Neruda, Vallejo, Pizarnik. Common in 20th-century poetry.',
      'METRICAL count: count syllables (Spanish counts diphthongs as 1; sometimes synalepha — combining final/initial vowels of adjacent words).',
      'SOUND DEVICES:',
      '  ASONANCIA: vowels rhyme; consonants vary.',
      '  CONSONANCIA: full rhyme.',
      '  ALITERACIÓN: repeated initial consonants.',
      '  ENCABALGAMIENTO: enjambment — meaning continues across line break.',
      'IMAGERY + FIGURES:',
      '  METÁFORA, SÍMIL, PERSONIFICACIÓN, METONIMIA.',
      '  GÓNGORA\'s culteranismo: dense classical references + Latinate syntax.',
      '  QUEVEDO\'s conceptismo: dense conceptual wordplay + paradox.',
      'KEY AUTHORS by period (memorise for AP):',
      '  Siglo de Oro: Garcilaso (Renaissance), Quevedo + Góngora (Baroque), Sor Juana.',
      '  Romanticism (1800s): Bécquer (Rimas).',
      '  Modernismo (~1900): Rubén Darío.',
      '  Generación del 27 (Spanish): Lorca, Salinas, Cernuda.',
      '  Latin American 20th c: Neruda (Chile), Vallejo (Peru), Mistral (Chile, Nobel 1945), Paz (Mexico).',
      'CONTEXT matters: Bécquer\'s melancholy reflects Romanticism; Neruda\'s "Veinte poemas" reflects Modernism + early existentialism; Lorca\'s "Romancero" weaves Andalusian folklore with universal themes.',
      'CLASSIC ANALYTICAL MOVES:',
      '  Identify form (sonnet vs free verse) → ask: how does the form constrain or enable meaning?',
      '  Find a striking image → unpack it: what does it suggest, what does it conceal?',
      '  Note shifts in tone, voice, or perspective.',
      '  Connect to historical/biographical context (sparingly — only when it changes meaning).',
    ], vocabulary: [{ term: 'encabalgamiento', definition: 'enjambment; the continuation of meaning across a line break, contrasting with end-stopped lines.' }, { term: 'asonancia', definition: 'rhyme based on vowel sounds only (not consonants); common in Spanish romances.' }], estimatedMinutes: 6 },
    { id: 'worked', kind: 'worked_example', problem: 'A student is asked to analyse Sor Juana\'s sonnet "En perseguirme, mundo, ¿qué interesas?" (Why do you persecute me, world, what interest is this to you?). Sketch the analysis approach.', steps: [
      'FORM: sonnet (14 lines, ABBA ABBA CDE CDE typical), endecasílabo. Form signals classical, intellectual ambition — appropriate for Sor Juana, the most learned woman of her era.',
      'CONTEXT: Sor Juana wrote in 17th-century New Spain (Mexico). Was a NUN BUT also a scholar — pushed against gender constraints of the church.',
      'CONTENT: speaker addresses "world" directly, asking why it pursues her. Defends choice of contemplative life over worldly engagement.',
      'KEY DEVICES:',
      '  APOSTROPHE — direct address to "mundo" (world) personifies it as antagonist.',
      '  ANTITHESIS — contemplation vs mundo, riqueza vs entendimiento.',
      '  RHETORICAL questions throughout — give voice to defense + critique.',
      'THEMATIC reading: defense of intellectual + spiritual life over material pursuits. Personal but also POLEMICAL — implicit critique of pressures on women + intellectuals.',
      'A HIGH-BAND analysis would link Sor Juana\'s sonnet form (classical, prestigious) to her implicit claim to intellectual STATUS in a culture that disputed it for women.',
    ], answer: 'Sonnet form, apostrophe + antithesis, defends contemplative life — biographical + cultural context strengthens reading.', estimatedMinutes: 5 },
    { id: 'try-1', kind: 'try_yourself', problem: 'In a Lorca romance ("Romance sonámbulo" for example), what does the meter signal that free verse would lose?', expectedAnswer: 'The romance form (octosílabo + assonance) is rooted in Spanish FOLK BALLAD tradition. Lorca chose this form deliberately to evoke ANDALUSIAN PEASANT speech, ORAL tradition, COLLECTIVE memory. Free verse would lose this folk-cultural anchoring — the poems would feel modern but rootless. The CONSTRAINT of the form is part of the meaning: Lorca claims Andalusian identity through the form, even when the imagery is surrealist + modern.', responseFormat: 'free', hints: ['What tradition does the romance form invoke?', 'How does that change what the poem MEANS?'], estimatedMinutes: 3 },
    { id: 'misconception-translation', kind: 'misconception_check', question: 'A student analyses a Spanish poem by translating it to English first, then analysing the English. What\'s lost?', commonErrors: [{ answer: 'Translate first, analyse English', misconception: 'Treating poetry as content rather than as language.', correctsTo: 'Poetry IS language — sound, rhythm, ambiguity, etymology. Translation strips: rhyme schemes, meter (English meter ≠ Spanish meter), word-play, double meanings. Sor Juana\'s rhetorical questions in Spanish have a specific cadence that translation loses. Analyse THE SPANISH directly. Identify form, sound, rhythm, key word choices in original. Translation is a CRUTCH — only justified for clarification, never as the primary analytical lens.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Spanish forms: soneto, romance, silva, verso libre.', 'Asonancia (vowel) vs consonancia (full rhyme).', 'Form signals tradition: sonnet = classical; romance = folk.', 'Encabalgamiento (enjambment) creates continuity.', 'Always analyse the SPANISH; translation loses sound.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
