/**
 * AP Spanish Literature — Prose Analysis (Cervantes, García Márquez, Borges).
 */

import type { LessonPlan } from '../types';

export const SEED_AP_SPANISH_LIT_PROSE: LessonPlan = {
  id: 'evelyn.ap.spanish-lit.prose.v1',
  title: 'AP Spanish Literature — Prose Analysis',
  curriculum: 'AP',
  grade: '11',
  subject: 'languages',
  topic: 'ap-spanish-lit',
  locale: 'en',
  los: [{ id: 'ap.spanish-lit.prose', description: 'Apply close-reading techniques to Spanish prose (Cervantes, modernismo, magical realism, Borges, contemporary).', standard: 'AP-SPAN-LIT' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 16,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Spanish prose tradition spans centuries — from Don Quixote to García Márquez and Borges.', script: 'AP Spanish Lit tests close-reading of fiction. Required works span Cervantes\' Don Quixote, modernist short stories, Borges\' philosophical fiction, García Márquez\'s magical realism, contemporary writers. Today: tools for analysing each.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Major prose periods, narrative techniques, key authors + works.', keyIdeas: [
      'KEY PROSE TRADITIONS:',
      '  SIGLO DE ORO (1500s-1600s): novela picaresca (Lazarillo de Tormes), Cervantes\' Don Quijote — first modern novel.',
      '  MODERNISMO (~1900): Rubén Darío influence in prose. Concentrated symbolism, refined language.',
      '  REALISMO + NATURALISMO (late 1800s): Galdós (España), Pérez Galdós\' Episodios Nacionales.',
      '  REGIONALISTA (~1900-30): Doña Bárbara (Gallegos, Venezuela), La Vorágine (Rivera, Colombia).',
      '  BOOM LATINOAMERICANO (~1960s-70s): García Márquez (Cien años de soledad, magical realism), Borges (short fiction, philosophical), Cortázar (Rayuela, ludic), Vargas Llosa (Conversación en La Catedral, social realism).',
      '  POST-BOOM + contemporary: Allende (Casa de los espíritus), Roberto Bolaño (Detectives salvajes), Valeria Luiselli, Yuri Herrera.',
      'NARRATIVE TECHNIQUES:',
      '  POINT OF VIEW: 1st person (subjective), 3rd limited, 3rd omniscient.',
      '  FREE INDIRECT DISCOURSE: narrator adopts character\'s voice (Galdós, Pérez Galdós).',
      '  STREAM OF CONSCIOUSNESS: interior monologue (Vargas Llosa, Joyce-influenced).',
      '  MAGICAL REALISM (García Márquez signature): supernatural elements treated as natural; common in Latin American literature; reflects indigenous + colonial cultural mixing.',
      '  METAFICTION: text aware of its own fictionality (Borges, Cortázar).',
      '  CYCLICAL TIME: contrast with Western linear time. Found in García Márquez, indigenous-influenced narratives.',
      'KEY AUTHORS by period (memorise):',
      '  Cervantes (1547-1616): Don Quixote, Novelas ejemplares.',
      '  Sor Juana Inés de la Cruz (1648-1695): "Respuesta a Sor Filotea" essay.',
      '  Gustavo Adolfo Bécquer (1836-1870): Leyendas (prose tales).',
      '  Federico García Lorca (1898-1936): drama (Bodas de sangre, La casa de Bernarda Alba) + poetry.',
      '  Jorge Luis Borges (1899-1986): Ficciones, El Aleph, Labyrinthian short fiction.',
      '  Pablo Neruda (1904-1973): poetry primarily; politically engaged.',
      '  Gabriel García Márquez (1927-2014): Cien años, Crónica de una muerte anunciada, Nobel 1982.',
      '  Octavio Paz (1914-1998): poetry + essay (Laberinto de la soledad), Nobel 1990.',
      '  Mario Vargas Llosa (b. 1936): novels of social realism + complex narrative structure, Nobel 2010.',
      '  Isabel Allende (b. 1942): magical realism continuation, post-Boom.',
      'COMMON THEMES across Spanish-language literature:',
      '  Identity (national, personal, racial, gendered).',
      '  History + memory (especially under dictatorship).',
      '  Religion + spirituality (Catholicism, indigenous beliefs, syncretism).',
      '  Power + oppression (colonialism, dictatorship, gender).',
      '  Love + desire across social barriers.',
      '  Reality + illusion (Quixote, Borges).',
    ], vocabulary: [{ term: 'magical realism', definition: 'a Latin American literary mode treating fantastic elements as natural parts of reality; signature of García Márquez.' }, { term: 'metafiction', definition: 'fiction that calls attention to its own fictional nature; Borges and Cortázar are masters.' }], estimatedMinutes: 6 },
    { id: 'worked', kind: 'worked_example', problem: 'A passage from "Cien años de soledad" describes Remedios la Bella ascending to heaven while folding sheets. How would you analyse this?', steps: [
      'IDENTIFY MAGICAL REALISM: a supernatural event (ascending to heaven) is described matter-of-factly, alongside ordinary task (folding sheets).',
      'WHY this technique matters: García Márquez treats the supernatural as PART OF EVERYDAY REALITY in Macondo. This is not metaphor or fantasy — characters and narrator accept it.',
      'SYMBOLIC reading: Remedios la Bella, who never married because suitors were destroyed by her beauty, escapes mortality entirely. The magical event reads as both ironic (she leaves the world that couldn\'t contain her) and literal (it just happens).',
      'CULTURAL context: magical realism reflects MESTIZAJE — mixing of European Catholic + indigenous + African beliefs in Latin America. Garcia Márquez treats this hybrid worldview as authentic, not exotic.',
      'NARRATIVE EFFECT: by NORMALISING the magical, the novel destabilises Western readers\' assumption that the natural and supernatural are clearly separate.',
      'High-band move: link to García Márquez\'s political comments — he saw magical realism as authentic Latin American storytelling, not artifice.',
    ], answer: 'Magical realism: supernatural treated as natural, reflecting Latin American mestizo worldview; narratively destabilises Western reality/fantasy boundary.', estimatedMinutes: 5 },
    { id: 'try-1', kind: 'try_yourself', problem: 'Why does Borges\' use of LIBRARIES, LABYRINTHS, and INFINITE BOOKS make his fiction philosophical rather than merely fantastical?', expectedAnswer: 'Each motif serves PHILOSOPHICAL inquiry. LIBRARIES (Babel) explore knowledge and meaning. LABYRINTHS (The House of Asterion) explore identity, time, fate. INFINITE BOOKS explore representation, language, totality. Borges uses fantastic devices to ask QUESTIONS about reality (is reality knowable?), language (does language mean what we think?), identity (am I one or many?). Unlike fantasy, the supernatural element serves philosophical exploration, not escape. His works invite re-reading because the philosophical content unfolds slowly.', responseFormat: 'free', hints: ['What ideas do labyrinths and infinite books explore?', 'How is this different from fantasy?'], estimatedMinutes: 3 },
    { id: 'misconception-magical-realism-fantasy', kind: 'misconception_check', question: 'A student says "magical realism is just Latin American fantasy." Why is this misleading?', commonErrors: [{ answer: 'Magical realism = fantasy', misconception: 'Conflating two different modes.', correctsTo: 'FANTASY presents alternate worlds (Tolkien\'s Middle Earth, Rowling\'s Hogwarts) — recognised as distinct from reality. MAGICAL REALISM presents OUR WORLD with magical elements treated as ORDINARY. Characters don\'t marvel at the magic; the narrator describes it matter-of-factly. The mode reflects authentic Latin American cultural worldviews where indigenous, African, and European beliefs co-exist. Calling it "fantasy" exoticises it as foreign/escapist; magical realism is, in its tradition, a CLAIM TO REALITY — that the supernatural is part of how Latin American cultures actually understand the world.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Major periods: Siglo de Oro, Modernismo, Boom, post-Boom.', 'Boom authors: García Márquez (magical realism), Borges (philosophical), Cortázar (ludic), Vargas Llosa.', 'Magical realism ≠ fantasy; supernatural treated as natural.', 'Free indirect discourse, stream of consciousness, metafiction = key narrative techniques.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
