/**
 * AP Statistics — CED Unit 6.7: Type I Error, Type II Error, Power.
 */
import type { LessonPlan } from '../types';
import { AP_PACING_THRESHOLDS, AP_SOURCE } from './_ap-shared';
export const SEED_AP_STATS_U6_TEST_ERRORS: LessonPlan = {
  id: 'evelyn.ap.stats.test-errors.v1', title: 'U6.7 Type I, Type II, and Power',
  curriculum: 'AP', grade: '12', subject: 'math', topic: 'ap-statistics', locale: 'en',
  los: [{ id: 'apstats.test-errors', description: 'Distinguish Type I error (rejecting H_0 when it is true) from Type II error (failing to reject when H_0 is false). Define and reason about power. Identify trade-offs.', standard: 'AP-STATS-6.7' }],
  prerequisites: ['apstats.one-prop-test'], followUps: ['apstats.two-prop-ci'], estimatedMinutes: 16,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Frame the two ways tests can be wrong.', script: "Significance tests can be wrong in two ways: rejecting H_0 when it\'s actually true (Type I), or failing to reject when H_0 is actually false (Type II). Understanding the trade-off is key to interpreting tests.", estimatedMinutes: 2 },
    { id: 'concept-errors', kind: 'concept', goal: 'Cover errors and power.',
      keyIdeas: [
        'TYPE I ERROR: REJECT H_0 when it is actually TRUE. False alarm.',
        '  • P(Type I error) = α (the significance level you chose).',
        '  • Common α: 0.05.',
        'TYPE II ERROR: FAIL to reject H_0 when it is actually FALSE. Missed detection.',
        '  • P(Type II error) = β. Depends on the actual true value of the parameter.',
        '  • Lower β = better.',
        'POWER: probability of correctly REJECTING H_0 when H_0 is FALSE. Power = 1 − β.',
        '  • Higher power = better. Common target: power ≥ 0.80.',
        'TRADE-OFF: lowering α (e.g., 0.01) → fewer Type I errors but MORE Type II errors (lower power) for fixed n. Raising α → more Type I but fewer Type II.',
        'INCREASING POWER (without changing α):',
        '  • Increase sample size n.',
        '  • Use a larger effect size (true parameter further from H_0).',
        '  • Reduce variability (better measurements).',
        '  • Use a one-sided test if directional alternative is appropriate.',
        'CHOOSING α IN CONTEXT: depends on which error is worse.',
        '  • If Type I is catastrophic (e.g., wrongly approving an unsafe drug): use small α (0.01).',
        '  • If Type II is catastrophic (e.g., missing a deadly disease): use larger α (0.10) or invest in larger n.',
        'COMMON CONFUSION: power is computed FOR A SPECIFIC ALTERNATIVE VALUE of p (not "for any deviation"). Power increases as the alternative value moves further from p_0.',
      ],
      vocabulary: [
        { term: 'Type I error', definition: 'rejecting H_0 when it is true; probability = α.' },
        { term: 'Type II error', definition: 'failing to reject H_0 when it is false; probability = β.' },
        { term: 'power', definition: '1 − β; probability of correctly rejecting a false H_0.' },
      ],
      estimatedMinutes: 5 },
    { id: 'worked-context', kind: 'worked_example',
      problem: 'A drug company tests if a new drug is more effective than the standard (H_0: same; H_a: better). (a) Describe a Type I error in context. (b) Describe a Type II error in context. (c) Which is worse? Why?',
      steps: [
        '(a) Type I = REJECTING H_0 when H_0 is true. Concluding the new drug is BETTER when actually it is the SAME (or worse). Patients prescribed an ineffective new drug.',
        '(b) Type II = FAILING to reject H_0 when H_0 is false. Concluding NO IMPROVEMENT when the drug ACTUALLY IS better. Patients miss out on a real improvement.',
        '(c) Depends on context. If approving an ineffective drug is dangerous (replaces a working drug, has side effects), Type I is worse → use small α. If missing a real improvement means patients suffer needlessly, Type II is worse → use larger α or bigger sample.',
      ],
      answer: 'Type I: false approval; Type II: missed improvement. Trade-off depends on consequences.', estimatedMinutes: 4 },
    { id: 'try-identify', kind: 'try_yourself',
      problem: 'A school principal tests H_0: dropout rate = 5% vs H_a: dropout rate > 5%. Identify Type I and Type II errors in context.',
      expectedAnswer: 'Type I: REJECTING H_0 when the true rate IS 5%. Wrongly concluding the dropout rate is higher than 5% when it isn\'t. School might needlessly invest resources on a non-problem. \nType II: FAILING to reject H_0 when the true rate IS higher than 5%. Missing a real dropout problem and not addressing it.',
      responseFormat: 'free', hints: ['Type I: rejecting a true H_0. Type II: missing a false H_0.'], estimatedMinutes: 3 },
    { id: 'try-power', kind: 'try_yourself',
      problem: 'A test has α = 0.05 and power = 0.70 against a specific alternative. (a) Find β. (b) Why might researchers want higher power? (c) Suggest two ways to increase power.',
      expectedAnswer: '(a) β = 1 − power = 1 − 0.70 = 0.30. \n(b) Higher power = better chance of detecting a true effect. With power 0.70, there\'s 30% chance of MISSING a real effect. Researchers want to avoid missing real findings; pharmaceutical/medical studies often require power ≥ 0.80. \n(c) (i) Increase sample size n. (ii) Increase α (riskier, more Type I). (iii) Reduce variability (better measurements, more careful protocol). (iv) Use a one-sided test if appropriate.',
      responseFormat: 'free', hints: ['Power = 1 − β; ways to boost: n, α, variability.'], estimatedMinutes: 4 },
    { id: 'try-synthesis', kind: 'try_yourself',
      problem: 'AP-style synthesis. A factory tests whether a process change reduces defective rate from 5%. They use H_0: p = 0.05 vs H_a: p < 0.05 with α = 0.05 and n = 200. (a) Describe the two error types in context. (b) The actual defective rate is now 3%. Power against this alternative is 0.65. Interpret. (c) Suggest one way to increase power without changing α.',
      expectedAnswer: '(a) Type I = REJECTING H_0 when p IS 0.05. Wrongly concluding defective rate has dropped when it has not. Factory celebrates success that didn\'t happen. \nType II = FAILING TO REJECT H_0 when p IS 0.03. Missing a real improvement. Factory continues old process even though the new one helps. (2)\n(b) "If the true defective rate has dropped to 3%, there is a 65% chance the test will correctly REJECT H_0 and detect the improvement. There\'s a 35% chance we\'ll miss this real improvement (Type II error at p = 0.03)." (1.5)\n(c) Increase sample size from 200 to a larger n (say 400 or 600). Or, reduce process measurement noise. (1.5)\nTotal: 5 points.',
      responseFormat: 'frq', hints: ['Errors in context; power as detection probability; n is the easiest dial.'], estimatedMinutes: 5 },
    { id: 'recap', kind: 'recap', mustRemember: [
      'Type I: reject true H_0; P = α.',
      'Type II: fail to reject false H_0; P = β.',
      'Power = 1 − β. Higher power = better at detecting real effects.',
      'Increase power: larger n, larger α (with cost), less variability.',
    ], estimatedMinutes: 1 },
  ],
  source: AP_SOURCE, schemaVersion: 1, pacingThresholds: AP_PACING_THRESHOLDS,
  metadata: { cedUnit: '6', cedTopic: '6.7', cedTitle: 'Type I/II Errors and Power', sources: [{ type: 'concept', book: 'tps5e', chapter: '9', note: 'Standard error types.' }] },
};
