/**
 * AP Spanish Language — Persuasive Essay Writing.
 */

import type { LessonPlan } from '../types';

export const SEED_AP_SPANISH_LANG_WRITING: LessonPlan = {
  id: 'evelyn.ap.spanish-lang.writing.v1',
  title: 'AP Spanish Language — Persuasive Essay Writing',
  curriculum: 'AP',
  grade: '11',
  subject: 'languages',
  topic: 'ap-spanish-lang',
  locale: 'en',
  los: [{ id: 'ap.spanish-lang.writing', description: 'Construct AP Spanish persuasive essay using three sources: structure, register, transitions, varied vocabulary.', standard: 'AP-SPAN-LANG-Q1' }],
  prerequisites: ['ap.spanish-lang.grammar'],
  followUps: [],
  estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'AP Spanish Lang Q1 (persuasive essay) is the highest-weight FRQ — and a structured approach earns 4-5s.', script: '40 minutes total. 3 sources (article, audio, table). Take a position responding to a question. Top scorers structure the essay carefully + use varied vocabulary + register.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Format, structure, register, transitions, scoring.', keyIdeas: [
      'FORMAT (current): 40 min total.',
      '  ~6 min: read prompt + Source 1 (article).',
      '  ~6 min: read Source 2 (table/chart).',
      '  ~6 min: listen to Source 3 (audio).',
      '  ~22 min: write the essay.',
      'STRUCTURE template (~250-300 words):',
      '  INTRO (1 paragraph): contextualise topic + state your THESIS clearly.',
      '  BODY 1: present your position + ONE supporting argument with at least one source citation.',
      '  BODY 2: ANOTHER supporting argument with another source citation.',
      '  BODY 3: address COUNTER-ARGUMENT briefly + refute or qualify; cite source.',
      '  CONCLUSION: synthesise + reaffirm thesis.',
      'KEY MOVES that earn marks:',
      '  CITE all 3 sources at least once (Q1 requirement).',
      '  USE TRANSITIONS: Por un lado / Por otro lado, Sin embargo, Además, En cambio, Por consiguiente, En conclusión.',
      '  VARY VERB TENSES: present, past, future, conditional. Use SUBJUNCTIVE in appropriate contexts.',
      '  USE FORMAL REGISTER: usted not tú (when generic), avoid contractions, use sophisticated vocabulary.',
      '  CONNECTORS for COMPARISON: a diferencia de, similar a, mientras que.',
      '  CONNECTORS for CAUSE: debido a, gracias a, a causa de.',
      '  CONNECTORS for CONCLUSION: en resumen, en definitiva, así pues.',
      'CITING SOURCES:',
      '  "Según la fuente 1..." or "El artículo afirma que..."',
      '  "La tabla en la fuente 2 muestra..."',
      '  "En el audio (fuente 3), se menciona..."',
      'COMMON ERRORS that lose marks:',
      '  Using only one or two sources (instead of all 3).',
      '  Repetitive vocabulary (no muy + no mucho when other options exist).',
      '  Mixing tú and usted inconsistently.',
      '  Wrong subjunctive triggers.',
      '  Generic statements without source evidence.',
      'SCORING criteria:',
      '  Task completion (addresses all parts of prompt).',
      '  Topic development (depth + sources).',
      '  Language use (variety, complexity, accuracy).',
      '  Vocabulary use (richness + appropriateness).',
    ], vocabulary: [{ term: 'register', definition: 'level of formality in speech/writing; AP Spanish writing should be formal (no contractions, sophisticated vocab, usted forms).' }, { term: 'connectors', definition: 'transition words/phrases that signal logical relationships between ideas (sin embargo, por consiguiente, etc.).' }], estimatedMinutes: 6 },
    { id: 'worked', kind: 'worked_example', problem: 'Sample prompt: "¿Es la tecnología beneficiosa para los jóvenes?" (Is technology beneficial for young people?) Sketch a thesis + structure.', steps: [
      'Pick a position. "La tecnología es beneficiosa para los jóvenes cuando se utiliza con moderación, pero presenta riesgos importantes que requieren orientación adulta."',
      'Body 1: Beneficios — acceso a información, oportunidades educativas. Cite Source 1.',
      'Body 2: Riesgos — adicción, salud mental, distracción académica. Cite Source 2 (table) + Source 3 (audio).',
      'Body 3: Counter-argument — algunos creen que la tecnología es totalmente positiva (cite if available). Refute: la moderación es clave; los excesos producen los problemas mencionados.',
      'Conclusion: Reafirmar tesis. La tecnología no es ni demonio ni salvador; es una herramienta cuya influencia depende del uso.',
    ], answer: 'Take a nuanced position; cite all 3 sources; structure with intro + 3 body + conclusion.', estimatedMinutes: 5 },
    { id: 'try-1', kind: 'try_yourself', problem: 'How would you transition from a paragraph supporting your thesis to a paragraph addressing a counter-argument?', expectedAnswer: 'Use a CONTRAST CONNECTOR: "Sin embargo, hay quienes argumentan que..." or "Por otro lado, no se puede ignorar que..." or "A pesar de los beneficios mencionados, también existe la preocupación de que...". The transition signals to the reader that you\'re shifting perspectives, while preserving your position. Always preface counter-argument acknowledgment with "Sin embargo," "Por otra parte," or similar contrast markers — graders look for this discourse signaling.', responseFormat: 'free', hints: ['Use a contrast connector.', 'Sin embargo, Por otro lado, A pesar de.'], estimatedMinutes: 3 },
    { id: 'misconception-tu-usted', kind: 'misconception_check', question: 'A student mixes tú and usted forms in the same essay. Why does this hurt the score?', commonErrors: [{ answer: 'Mixing tú and usted', misconception: 'Treating informal and formal as interchangeable.', correctsTo: 'AP Spanish Lang writing is FORMAL register. Use USTED consistently (or generic third-person constructions). Tú is for personal letters or informal conversation. Mixing breaks register, signals inconsistency, and graders penalise. Even if the original prompt uses tú, write your essay in formal register. Decide before writing: USTED throughout, or generic se / impersonal forms.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Cite ALL 3 sources at least once.', 'Use varied tenses + subjunctive correctly.', 'Formal register: usted, no contractions.', 'Connectors mark logical transitions.', 'Counter-argument acknowledgment with sin embargo, por otro lado.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
