/**
 * IB Biology — Cell Biology Topic Deep Dive.
 */

import type { LessonPlan } from '../types';

export const SEED_IB_BIOLOGY_CELL_BIO: LessonPlan = {
  id: 'evelyn.ibdp.biology.cell-bio.v1',
  title: 'IB Biology — Cell Biology Topic',
  curriculum: 'IB-DP',
  grade: '11-12',
  subject: 'science',
  topic: 'ib-biology',
  locale: 'en',
  los: [{ id: 'ibdp.biology.cell-bio', description: 'Apply IB Biology Topic 1 (Cell biology): cell theory, ultrastructure, membranes, transport.', standard: 'IB-DP-BIO-1' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'IB Bio Topic 1 (Cell biology) appears in BOTH papers — high yield to master.', script: 'Cell theory, prokaryote vs eukaryote, organelles, membrane structure + transport. IB rewards specific named experiments + Nature of Science context. Today\'s plan covers the testable content + the NoS angles.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Cell theory, ultrastructure, fluid mosaic membrane, transport mechanisms, NoS.', keyIdeas: [
      'CELL THEORY (postulates):',
      '  1. All living things composed of cells.',
      '  2. Cell is smallest unit of life.',
      '  3. Cells arise from pre-existing cells (Pasteur, against spontaneous generation).',
      'EXCEPTIONS to cell theory (IB tests these):',
      '  Striated muscle fibres are MULTINUCLEATE (one large cell with many nuclei).',
      '  Aseptate fungal hyphae lack cross-walls.',
      '  Giant algae like Acetabularia are huge single cells.',
      'PROKARYOTE vs EUKARYOTE:',
      '  Prokaryote: no nucleus or membrane-bound organelles. Smaller (~1-5 μm). Single circular chromosome. 70S ribosomes. Examples: bacteria, archaea.',
      '  Eukaryote: nucleus + organelles. Larger (~10-100 μm). Linear chromosomes. 80S cytoplasmic + 70S in mito/chloro.',
      'EUKARYOTIC ORGANELLES (memorise + function + image recognition):',
      '  Nucleus (DNA, transcription).',
      '  Mitochondria (ATP, double membrane, own DNA).',
      '  Chloroplasts (plants only; photosynthesis).',
      '  Rough ER (protein synthesis for export).',
      '  Smooth ER (lipids, detox).',
      '  Golgi (modifies/sorts proteins).',
      '  Lysosomes (digestion, animals only).',
      '  Vacuoles (large in plants).',
      '  Cytoskeleton (microtubules + microfilaments).',
      'FLUID MOSAIC MODEL (Singer-Nicolson 1972):',
      '  Phospholipid BILAYER with embedded proteins.',
      '  Heads HYDROPHILIC (face water); tails HYDROPHOBIC (face inward).',
      '  Cholesterol stabilises fluidity.',
      '  Membrane proteins: integral (channel, carrier, receptor), peripheral.',
      'TRANSPORT mechanisms:',
      '  PASSIVE (no ATP):',
      '    DIFFUSION: down concentration gradient.',
      '    OSMOSIS: water down water-potential gradient.',
      '    FACILITATED diffusion: through channel/carrier proteins.',
      '  ACTIVE (uses ATP):',
      '    Pumps move against gradient. Sodium-potassium pump example.',
      '  BULK transport:',
      '    Endocytosis (cell engulfs).',
      '    Exocytosis (cell ejects).',
      'NATURE OF SCIENCE (testable):',
      '  Pasteur\'s swan-neck flask experiment disproved spontaneous generation.',
      '  Falsifiability of theories.',
      '  Davson-Danielli model PRECEDED fluid mosaic; was REVISED based on freeze-fracture electron microscopy.',
      '  Endosymbiotic theory (Margulis) explains mitochondria + chloroplast origin from engulfed bacteria.',
    ], vocabulary: [{ term: 'fluid mosaic model', definition: 'current model of cell membrane: phospholipid bilayer with embedded mobile proteins.' }, { term: 'endosymbiotic theory', definition: 'theory that mitochondria and chloroplasts originated as free-living bacteria engulfed by an ancestral eukaryote.' }], estimatedMinutes: 6 },
    { id: 'worked', kind: 'worked_example', problem: 'Compare the structure of mitochondria and chloroplasts. Identify TWO similarities and TWO differences. (Command term: COMPARE — needs both.)', steps: [
      'SIMILARITIES:',
      '  1. Both are DOUBLE-MEMBRANED organelles found in eukaryotes.',
      '  2. Both contain own circular DNA + 70S ribosomes (consistent with endosymbiotic origin).',
      '  3. Both produce ATP (mitochondria via cellular respiration; chloroplast via photosynthesis).',
      'DIFFERENCES:',
      '  1. Mitochondria: in nearly ALL eukaryotes; chloroplasts: ONLY plants and algae.',
      '  2. Mito have folded inner membrane (CRISTAE); chloroplasts have stacked thylakoids (GRANA) inside the stroma.',
      '  3. Mito BREAK DOWN glucose (cellular respiration); chloroplasts BUILD UP glucose (photosynthesis).',
      'Top-band move: link both to ENDOSYMBIOTIC THEORY (NoS framing earns extra marks).',
    ], answer: 'Both: double-membrane, own DNA. Differ: location (chloro plants only), function (mito catabolic, chloro anabolic).', estimatedMinutes: 4 },
    { id: 'try-1', kind: 'try_yourself', problem: 'Why is the cell theory considered tentative — i.e., a "good theory but with exceptions"?', expectedAnswer: 'The cell theory states all life is made of cells, cell is smallest unit of life, and cells come from pre-existing cells. Exceptions complicate this: STRIATED MUSCLE FIBRES are huge multi-nucleate cells (one cell, many nuclei) — does each count as one or many "units"? ASEPTATE FUNGI have no cross walls. ACETABULARIA is a giant single-cell alga visible without microscope. NoS framing: theories are revised/refined, not abandoned, when exceptions emerge. The cell theory remains the BEST FRAMEWORK but with explicit exceptions for boundary cases.', responseFormat: 'free', hints: ['What examples violate "all life = cells" cleanly?', 'IB Bio loves these exceptions — memorise.'], estimatedMinutes: 3 },
    { id: 'misconception-membrane-static', kind: 'misconception_check', question: 'A student describes the cell membrane as "a static wall keeping things in." What\'s the IB-correct picture?', commonErrors: [{ answer: 'Static wall', misconception: 'Treating the membrane as rigid and one-purpose.', correctsTo: 'Cell membrane is FLUID and DYNAMIC. Phospholipids and proteins move laterally. Membrane SELECTIVELY allows substances in/out via passive diffusion, facilitated transport, active pumps, and bulk transport. It also functions in cell SIGNALING (receptor proteins) and cell-to-cell ADHESION (glycoproteins). The fluid mosaic model captures this dynamism. IB will dock you for "wall" language.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Cell theory + 3 main exceptions.', 'Pro vs Euk: nucleus + organelles distinction.', 'Fluid mosaic: bilayer + embedded proteins, fluid + dynamic.', 'Transport: passive (diffusion, osmosis, facilitated) vs active (ATP-required).', 'Endosymbiotic theory: mito + chloro from bacteria.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
