/**
 * IB History — Paper 1 Source-Based Skills.
 */

import type { LessonPlan } from '../types';

export const SEED_IB_HISTORY_PAPER1_SKILLS: LessonPlan = {
  id: 'evelyn.ibdp.history.paper1-skills.v1',
  title: 'IB History — Paper 1: Source-Based Question Skills',
  curriculum: 'IB-DP',
  grade: '11-12',
  subject: 'social-studies',
  topic: 'ib-history',
  locale: 'en',
  los: [{ id: 'ibdp.history.paper1-skills', description: 'Apply Paper 1 source-based skills: comprehension, comparison, OPVL evaluation, and synthesis answer.', standard: 'IB-DP-HIST-P1' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'IB History Paper 1 has a fixed structure — and the per-question marking is predictable.', script: 'Four questions on a "Prescribed Subject" with 4 sources. Each tests a specific skill: comprehension (Q1a-b), origin/purpose evaluation (Q2), comparison (Q3), synthesis (Q4). Once you know each skill, Paper 1 becomes a structured exercise.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Paper 1 format, per-question approach, time management.', keyIdeas: [
      'PAPER 1 FORMAT: 1 hour, 4 sources (typically labeled A-D). 4 questions worth 25 marks total.',
      'Q1a (3 marks): COMPREHENSION. "What does Source [X] suggest about...?"',
      '  Brief, FACTUAL response from the source. 3 distinct points.',
      '  ~5 min. Don\'t overspend.',
      'Q1b (2 marks): visual interpretation if a source is a cartoon, photo, or chart.',
      '  Identify what\'s shown + brief context.',
      '  ~3 min.',
      'Q2 (4 marks): ORIGIN, PURPOSE, VALUE, LIMITATION (OPVL) of ONE source.',
      '  Format: ORIGIN (who, when, where, what kind of source).',
      '  PURPOSE (intended audience, intended effect).',
      '  VALUE (what a historian can legitimately learn).',
      '  LIMITATION (what the source CANNOT tell us, biases).',
      '  ~10 min.',
      'Q3 (6 marks): COMPARE AND CONTRAST two sources. ',
      '  Equal SIMILARITIES + DIFFERENCES required.',
      '  Use the sources directly with quotes.',
      '  ~12 min.',
      'Q4 (9 marks): MINI-ESSAY using ALL FOUR SOURCES + your own knowledge.',
      '  Take a position; defend with sources + outside knowledge.',
      '  Cite each source by letter.',
      '  ~25 min.',
      'OPVL FRAMEWORK detail:',
      '  ORIGIN: don\'t just name the source; note WHEN (relative to events), WHERE, WHAT TYPE (memoir, official document, cartoon, etc.).',
      '  PURPOSE: what was the source TRYING to do? Persuade? Document? Justify?',
      '  VALUE: what RELIABLE info does this give? Often: insight into PERSPECTIVE rather than absolute facts.',
      '  LIMITATION: what kinds of questions can this source NOT answer?',
      'COMMON ERRORS:',
      '  Q1a: writing too much (it\'s only 3 marks).',
      '  Q2: reading "OPVL" as "is this source biased?" — too crude. Need all 4 elements.',
      '  Q3: doing similarities only or differences only.',
      '  Q4: forgetting to use all 4 sources or forgetting outside knowledge.',
      'TIME pacing: 5 + 3 + 10 + 12 + 25 = 55 minutes + 5 buffer for review.',
    ], vocabulary: [{ term: 'OPVL', definition: 'Origin, Purpose, Value, Limitation; IB History\'s framework for source evaluation.' }, { term: 'Q4 mini-essay', definition: 'the 9-mark synthesis question on Paper 1 using all 4 sources + own knowledge.' }], estimatedMinutes: 6 },
    { id: 'worked', kind: 'worked_example', problem: 'Apply OPVL to: "A 1939 newspaper editorial in The Times (London) criticising the Munich Agreement (signed 1938)."', steps: [
      'ORIGIN: Source is a newspaper editorial in The Times, London, 1939. Roughly one year after Munich. Published context: a year after appeasement; tensions rising; war soon.',
      'PURPOSE: editorial — opinion piece intended to influence public + government opinion. Likely targeting British readership.',
      'VALUE: source for understanding RETROSPECTIVE BRITISH OPINION on Munich after a year had passed. Reveals how perception of appeasement was shifting (towards critical) in mainstream British media.',
      'LIMITATION: editorial reflects The Times\'s position; not necessarily representative of all British opinion. As editorial, it intentionally takes a position rather than neutrally reporting facts. Cannot tell us what Chamberlain or other policymakers privately thought; cannot tell us about reactions outside Britain.',
      'High-band move: link to historiographical debate about whether appeasement was justified given British military weakness in 1938 vs naive enabling of Hitler.',
    ], answer: 'OPVL applied: clearly distinguishes WHAT the source can tell + LIMITATIONS.', estimatedMinutes: 5 },
    { id: 'try-1', kind: 'try_yourself', problem: 'A common Paper 1 Q4 mistake is to write about the topic without citing the sources. Why does this lose marks?', expectedAnswer: 'Q4 EXPLICITLY requires "use of sources A-D + your own knowledge." Writing a generic essay about the topic without citing sources misses the test\'s purpose. Each source must be referenced (by letter) at LEAST once. Missing 4-source coverage caps marks at ~5/9. Citation also serves analytical purpose: it forces you to engage with what the sources ACTUALLY say, including their nuances and biases.', responseFormat: 'free', hints: ['What does the question explicitly require?', 'How do graders see source-by-letter references?'], editor: 'free', estimatedMinutes: 3 },
    { id: 'misconception-bias-only', kind: 'misconception_check', question: 'A student answers Q2 (OPVL) by writing "Source A is biased." What\'s missing?', commonErrors: [{ answer: 'Source is biased', misconception: 'Reducing OPVL to a single judgment.', correctsTo: 'Bias is one element of LIMITATION, but Q2 asks for FOUR distinct things: ORIGIN, PURPOSE, VALUE, LIMITATION. "Biased" by itself misses 75% of the question. Even on Limitation alone, "biased" is too vague — say HOW biased (whose perspective is missing? whose is privileged? what facts are obscured?). And Value is often misunderstood: even biased sources have value — they reveal perspectives, propaganda methods, etc. Always do all 4 OPVL elements.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['1 hour, 4 sources, 4 questions (3 + 2 + 4 + 6 + 9 marks).', 'Q1a/b: comprehension. Q2: OPVL. Q3: compare/contrast. Q4: synthesis essay using all 4 sources + own knowledge.', 'OPVL = Origin, Purpose, Value, Limitation — all four required.', 'Time: 5 + 3 + 10 + 12 + 25 = 55 min.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
