/**
 * IB Spanish — Text Types and Conventions.
 */

import type { LessonPlan } from '../types';

export const SEED_IB_SPANISH_TEXT_TYPES: LessonPlan = {
  id: 'evelyn.ibdp.spanish.text-types.v1',
  title: 'IB Spanish — Text Types and Their Conventions',
  curriculum: 'IB-DP',
  grade: '11-12',
  subject: 'languages',
  topic: 'ib-spanish',
  locale: 'en',
  los: [{ id: 'ibdp.spanish.text-types', description: 'Identify the conventions of major IB Spanish text types (article, blog, formal/informal letter, speech, brochure, interview, diary).', standard: 'IB-DP-SPAN' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 16,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'IB Spanish demands awareness of TEXT TYPE conventions — same content, different conventions = different scores.', script: 'A blog and a formal letter cover different topics differently. IB explicitly tests whether you respect each text type\'s conventions: register, structure, formatting cues. Today: the major types + their markers.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Major text types + conventions for each.', keyIdeas: [
      'KEY TEXT TYPES on IB Spanish:',
      '  ARTÍCULO (article — newspaper/magazine):',
      '    Headline (title) + subheadline.',
      '    Byline (author).',
      '    Date.',
      '    Body in clear paragraphs, third-person mostly.',
      '    Concluding paragraph or quote.',
      '    Register: semi-formal to formal.',
      '  BLOG / ENTRADA DE BLOG:',
      '    Title + author/date.',
      '    First-person voice; subjective.',
      '    Conversational tone; can use rhetorical questions, exclamations.',
      '    Informal vocabulary acceptable.',
      '    Often ends with prompt for comments ("¿Tú qué piensas?").',
      '  CARTA FORMAL (formal letter):',
      '    Address (sender + receiver).',
      '    Date.',
      '    Salutation: "Estimado/a Sr./Sra. + Apellido:" (with colon).',
      '    Body: paragraphed; usted forms; formal vocabulary.',
      '    Closing: "Atentamente," "Cordialmente," followed by signature.',
      '    No contractions; no slang.',
      '  CARTA INFORMAL (informal letter / email):',
      '    Salutation: "¡Hola Pedro!" or "Querido amigo:".',
      '    Tú forms; conversational.',
      '    Closing: "Un abrazo," "Besos," "Hasta pronto."',
      '  DISCURSO (speech):',
      '    Opening to engage audience: "Estimados oyentes," or "Buenas tardes a todos."',
      '    Direct address ("ustedes" or "vosotros").',
      '    Rhetorical devices: questions, repetition, anecdotes.',
      '    Strong closing.',
      '  FOLLETO (brochure):',
      '    Headlines, bullet points, short paragraphs.',
      '    Sectioned (heading + content blocks).',
      '    Imperative for instructions: "Visite," "Llame," "Reserve."',
      '    Practical info: prices, addresses, dates.',
      '  ENTREVISTA (interview):',
      '    Q-A format: "Periodista:" / "Entrevistado:".',
      '    Brief intro about the interviewee.',
      '    Variety of questions (factual, opinion, biographical).',
      '  DIARIO (diary entry):',
      '    Date.',
      '    First-person; reflective; intimate register.',
      '    Past + present tenses.',
      'GRADER focus areas:',
      '  Did the student CORRECTLY identify text type from prompt?',
      '  Did they USE the conventions (register, format markers, vocabulary register)?',
      '  Did they MAINTAIN consistency throughout?',
      'COMMON ERRORS:',
      '  Writing a formal letter using tú forms.',
      '  Writing a blog without first-person voice.',
      '  Skipping the date/salutation/closing for letters.',
      '  Mixing register (formal + slang).',
    ], vocabulary: [{ term: 'register', definition: 'level of formality (formal vs informal); IB Spanish demands appropriate register matching text type.' }, { term: 'convenciones', definition: 'genre conventions; the structural and stylistic markers expected for each text type.' }], estimatedMinutes: 6 },
    { id: 'worked', kind: 'worked_example', problem: 'IB Spanish prompt asks you to write a FORMAL LETTER to the mayor about local pollution. Sketch the format + opening.', steps: [
      'Format markers needed: addresses (sender + receiver), date, formal salutation, body in usted forms, formal closing.',
      'Opening: address block (top right), then date, then "Estimado/a Sr./Sra. Alcalde/Alcaldesa:" (with colon).',
      'First paragraph: state purpose. "Por la presente, le escribo para manifestar mi preocupación por los niveles de contaminación en nuestra ciudad."',
      'Body: paragraphed argument with usted forms, formal vocabulary.',
      'Closing: "Le saluda cordialmente," + signature.',
      'AVOID: tú forms, contractions, conversational tone, exclamations.',
    ], answer: 'Format with addresses + date + formal salutation + usted body + formal closing.', estimatedMinutes: 4 },
    { id: 'try-1', kind: 'try_yourself', problem: 'A blog and a formal letter could both address "the impact of social media." How would the SAME content look different in each?', expectedAnswer: 'BLOG: first-person voice, subjective, conversational. "Hoy quiero hablar de algo que me preocupa: las redes sociales..." Uses tú or vosotros. Rhetorical questions inviting discussion. Less formal vocabulary.\nFORMAL LETTER: third-person + usted; formal address ("Estimado/a Sr./Sra."); structured paragraphs; formal vocabulary; closing salutation. The CONTENT is similar, but REGISTER, VOICE, and FORMAT differ entirely.', responseFormat: 'free', hints: ['Compare voice (first vs third person).', 'Compare register (informal vs formal).'], estimatedMinutes: 3 },
    { id: 'misconception-content-only', kind: 'misconception_check', question: 'A student writes a "speech" but it reads like an article. Why does IB penalise this?', commonErrors: [{ answer: 'Writes article-style speech', misconception: 'Treating text type as cosmetic, focusing only on content.', correctsTo: 'IB Spanish explicitly tests TEXT TYPE AWARENESS. A speech needs: opening greeting to listeners, direct address ("ustedes"), rhetorical devices for spoken delivery (questions, repetition), strong closing. An article doesn\'t have these — it has headlines + bylines + paragraphed prose. If the prompt says "discurso," the response must read as a speech to listeners. Identifying the text type and using its conventions earns substantial marks; ignoring them caps your score regardless of content quality.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['IB tests text-type CONVENTIONS, not just content.', 'Article: third-person, paragraphed, semi-formal.', 'Blog: first-person, conversational, can be informal.', 'Formal letter: addresses + date + salutation + usted + closing.', 'Speech: greeting + direct address + rhetorical devices.', 'Match register to text type consistently.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
