/**
 * NEET Chemistry — Coordination Compounds (CFT, Magnetism, IUPAC).
 */

import type { LessonPlan } from '../types';

export const SEED_NEET_CHEM_COORDINATION: LessonPlan = {
  id: 'evelyn.neet.chemistry.coordination.v1',
  title: 'NEET Chemistry — Coordination Compounds',
  curriculum: 'NEET',
  grade: 'medical-entrance',
  subject: 'test-prep',
  topic: 'neet-chemistry',
  locale: 'en',
  los: [{ id: 'neet.chem.coordination', description: 'Apply IUPAC nomenclature, Werner theory, isomerism, crystal field theory, magnetic moments to coordination compounds.', standard: 'NEET-CHEM-COORD' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 16,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Coordination chemistry is reliable NEET marks — IUPAC names and CFT colour/magnetism predictions.', script: 'Why is [Cu(NH₃)₄]²⁺ blue? Why is [Fe(CN)₆]³⁻ paramagnetic but low-spin? CFT explains both. Plus IUPAC nomenclature for naming complexes. NEET asks 2-3 per year.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Werner, IUPAC names, isomerism, CFT, magnetism.', keyIdeas: [
      'COMPLEX = central metal + ligands.',
      'WERNER: primary (oxidation state) vs secondary (coordination number) valence.',
      'COORDINATION NUMBER: 4 (square planar, tetrahedral) or 6 (octahedral) most common.',
      'LIGANDS:',
      '  Monodentate (1 donor): NH₃, H₂O, CN⁻, Cl⁻, Br⁻, I⁻, F⁻, OH⁻.',
      '  Bidentate (2): en (ethylenediamine), ox (oxalate), gly (glycinate).',
      '  Polydentate: EDTA (hexadentate), DMG (dimethylglyoxime, bidentate).',
      'IUPAC NOMENCLATURE:',
      '  Cation first, then anion (ionic compounds).',
      '  Within complex ion: ligands ALPHABETICALLY (ignoring numerical prefixes).',
      '  Anionic ligands end -o (chloro, cyano, hydroxo).',
      '  Numerical prefixes: di, tri, tetra, penta, hexa for simple ligands.',
      '  Use bis, tris, tetrakis for complex ligand names (with parens).',
      '  Metal\'s oxidation state in Roman numerals.',
      '  If complex ion is ANIONIC, metal name ends in -ate (cuprate, ferrate, aurate, plumbate).',
      'EXAMPLE: K₃[Fe(CN)₆] = potassium hexacyanoferrate(III).',
      'ISOMERISM:',
      '  STRUCTURAL: ionisation, hydrate, linkage (-NO₂ vs -ONO), coordination.',
      '  STEREO: geometric (cis/trans for square planar + octahedral), optical (chiral complexes).',
      'CRYSTAL FIELD THEORY (CFT) — octahedral case:',
      '  d-orbitals split into t₂g (lower energy: dxy, dxz, dyz) and eg (higher: dz², dx²−y²).',
      '  Splitting Δ_o.',
      '  STRONG-FIELD ligands (large Δ): CN⁻, CO, NO₂⁻, en, NH₃ (high in spectrochemical series). PAIR electrons → LOW SPIN.',
      '  WEAK-FIELD ligands (small Δ): I⁻, Br⁻, Cl⁻, F⁻, OH⁻, H₂O. Hund\'s rule applies → HIGH SPIN.',
      'SPECTROCHEMICAL SERIES (memorise):',
      '  I⁻ < Br⁻ < S²⁻ < SCN⁻ < Cl⁻ < NO₃⁻ < F⁻ < OH⁻ < OX²⁻ < H₂O < NH₃ < en < CN⁻ < CO.',
      'TETRAHEDRAL splitting Δ_t = (4/9) Δ_o → always smaller; tetrahedral complexes USUALLY high-spin.',
      'COLOUR: arises from d-d electron transition (t₂g → eg). Wavelength absorbed → complementary colour seen.',
      '  No d electrons (d⁰) or full d (d¹⁰) → COLOURLESS (no transition). E.g., Zn²⁺ d¹⁰ — colourless.',
      'MAGNETIC moment: μ = √(n(n+2)) BM (spin-only). n = unpaired e⁻.',
      '  Paramagnetic if μ > 0; diamagnetic if all paired.',
    ], vocabulary: [{ term: 'crystal field splitting', definition: 'Δ_o or Δ_t; energy gap between split d-orbitals; depends on ligand and geometry.' }, { term: 'spectrochemical series', definition: 'ranking of ligands by crystal-field strength.' }], estimatedMinutes: 6 },
    { id: 'worked', kind: 'worked_example', problem: 'Predict the magnetic moment of [Fe(H₂O)₆]³⁺.', steps: [
      'Fe³⁺: [Ar] 3d⁵.',
      'H₂O is a WEAK-FIELD ligand (low in spectrochemical series).',
      'Weak field → small Δ_o → high-spin.',
      'High-spin d⁵: t₂g³ eg² — five unpaired electrons.',
      'μ = √(5 · 7) = √35 ≈ 5.92 BM.',
    ], answer: '~5.92 BM (5 unpaired electrons, high-spin)', estimatedMinutes: 4 },
    { id: 'try-1', kind: 'try_yourself', problem: 'Name [Co(NH₃)₅Cl]Cl₂.', expectedAnswer: 'Inside brackets: 5 NH₃ + 1 Cl⁻ ligands on Co. Charge balance: complex must be +2 (since 2 Cl⁻ outside). 5(0) + 1(−1) + Co = +2 → Co = +3. Name: pentaamminechloridocobalt(III) chloride. (NH₃ = ammine; Cl⁻ ligand = chlorido; ligands alphabetical — ammine before chlorido; Co +3 in roman.)', responseFormat: 'free', hints: ['Determine oxidation state from charge balance.', 'Order ligands alphabetically; remember ammine and chlorido.'], estimatedMinutes: 3 },
    { id: 'misconception-tetrahedral-low', kind: 'misconception_check', question: 'A student says some tetrahedral complexes are low-spin. Why is this almost never true?', commonErrors: [{ answer: 'Tetrahedral can be low-spin', misconception: 'Generalising octahedral spin behavior to tetrahedral.', correctsTo: 'Tetrahedral splitting Δ_t = (4/9) Δ_o is much SMALLER than octahedral splitting. Even strong-field ligands rarely create enough splitting in tetrahedral geometry to overcome electron pairing energy. Result: tetrahedral complexes are ALMOST ALWAYS HIGH-SPIN. (Square planar — different geometry — is usually low-spin.) For NEET: assume tetrahedral = high-spin unless told otherwise.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Werner: primary (OS) + secondary (CN) valence.', 'IUPAC: ligands alphabetical (ignore prefixes); -o for anion ligands; -ate for anionic complex.', 'Strong-field ligands → low-spin (oct.). Tetrahedral usually high-spin.', 'μ = √(n(n+2)) BM.', 'Colour from d-d transitions; d⁰ and d¹⁰ are colourless.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
