/**
 * NEET Biology — Genetics Deep Dive (Mendelian + Chromosomal).
 */

import type { LessonPlan } from '../types';

export const SEED_NEET_BIO_GENETICS_DEEP: LessonPlan = {
  id: 'evelyn.neet.biology.genetics-deep.v1',
  title: 'NEET Biology — Genetics: Mendel + Chromosomal Theory + Pedigrees',
  curriculum: 'NEET',
  grade: 'medical-entrance',
  subject: 'test-prep',
  topic: 'neet-biology',
  locale: 'en',
  los: [{ id: 'neet.bio.genetics-deep', description: 'Apply Mendel\'s laws, chromosomal theory of inheritance, sex-linked inheritance, and pedigree analysis.', standard: 'NEET-BIO-GENETICS' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 18,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Genetics is a JEE/NEET workhorse — and pedigree problems are heavily tested.', script: 'NEET Biology asks 4-6 genetics questions per year, including pedigrees, blood types, color-blindness, hemophilia. Master Mendel + chromosomal extensions and you bank these marks easily.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Mendel laws, dihybrid + multiple alleles, sex-linked, pedigree.', keyIdeas: [
      'MENDEL\'S LAWS:',
      '  LAW OF DOMINANCE: in heterozygotes, dominant allele is expressed.',
      '  LAW OF SEGREGATION: each parent passes ONE allele per gene to gametes.',
      '  LAW OF INDEPENDENT ASSORTMENT: alleles for different genes assort independently (UNLESS linked on same chromosome).',
      'MONOHYBRID: Aa × Aa → 1 AA : 2 Aa : 1 aa (1:2:1 genotype, 3:1 phenotype).',
      'DIHYBRID: AaBb × AaBb → 9:3:3:1 phenotype ratio (when independent).',
      'TEST CROSS: unknown × homozygous recessive. If all offspring dominant → unknown is homozygous dominant. If 1:1 → heterozygous.',
      'INCOMPLETE DOMINANCE: heterozygote intermediate (red × white snapdragons → pink).',
      'CODOMINANCE: both alleles fully expressed. Example: ABO blood (IA + IB → AB).',
      'MULTIPLE ALLELES: > 2 alleles in population. ABO has IA, IB, i.',
      'PLEIOTROPY: one gene affects multiple traits. Sickle cell is classic example.',
      'POLYGENIC: many genes contribute. Skin color, height. Continuous variation.',
      'SEX-LINKED INHERITANCE:',
      '  Genes on X chromosome (mostly).',
      '  Examples: hemophilia, color-blindness, DMD.',
      '  Recessive sex-linked disorders: more common in MALES (XY) — just one X needs the recessive allele. Females need both Xs to express.',
      '  Carrier mother + normal father → 50% sons affected, all daughters normal (carriers).',
      'CHROMOSOMAL THEORY (Sutton-Boveri): genes are on chromosomes; chromosomes carry hereditary information.',
      'LINKAGE: genes on the same chromosome tend to inherit together.',
      'CROSSING OVER: meiosis I; physical exchange between homologous chromosomes; produces recombinants. Recombination frequency measures distance between linked genes.',
      'PEDIGREE ANALYSIS conventions:',
      '  Square = male, circle = female.',
      '  Filled = affected, unfilled = unaffected.',
      '  Half-filled = carrier (or unknown).',
      '  Horizontal line between parents; vertical line to offspring.',
      'PEDIGREE rules:',
      '  AUTOSOMAL DOMINANT: trait appears every generation; affected parent → 50% offspring.',
      '  AUTOSOMAL RECESSIVE: skips generations; both parents must be carriers; affected offspring 1/4 of crosses.',
      '  X-LINKED RECESSIVE: more males affected; trait skips through carrier mothers; never father-to-son.',
      '  X-LINKED DOMINANT: rare; affected mother → 50% all offspring; affected father → all daughters but no sons.',
    ], vocabulary: [{ term: 'pleiotropy', definition: 'one gene affecting multiple seemingly unrelated traits.' }, { term: 'recombination frequency', definition: 'fraction of offspring with recombinant phenotypes; measures genetic distance between linked genes.' }], estimatedMinutes: 6 },
    { id: 'worked', kind: 'worked_example', problem: 'A color-blind father and a non-carrier mother have offspring. What\'s the probability a daughter is color-blind? A son?', steps: [
      'Color blindness is X-LINKED RECESSIVE.',
      'Father is color-blind → his X carries the recessive allele. Genotype: X_c Y.',
      'Mother is non-carrier → both X chromosomes normal. Genotype: X_N X_N.',
      'Daughters get X from each parent: X_c (from dad) X_N (from mom) = X_c X_N (CARRIER, NOT affected).',
      'Sons get Y from father, X from mother: X_N Y. NOT affected, NOT carrier.',
      'P(daughter color-blind) = 0%. P(son color-blind) = 0%.',
      'But ALL daughters are CARRIERS — so their sons may be affected.',
    ], answer: '0% for daughters and sons; daughters are carriers.', estimatedMinutes: 5 },
    { id: 'try-1', kind: 'try_yourself', problem: 'A pedigree shows: both parents unaffected, one daughter affected, one son unaffected. Most likely inheritance pattern?', expectedAnswer: 'Affected daughter from unaffected parents → BOTH parents must be CARRIERS. Daughter is HOMOZYGOUS RECESSIVE. This pattern (skipping generation, female affected from carrier parents) suggests AUTOSOMAL RECESSIVE. (X-linked recessive in a daughter would require an affected father, since she needs two recessive X alleles — but father here is unaffected.)', responseFormat: 'free', hints: ['Both parents unaffected but child is — what does that tell you about the allele?', 'Female affected? Rule out X-linked recessive unless father is affected.'], estimatedMinutes: 3 },
    { id: 'misconception-male-female-carrier', kind: 'misconception_check', question: 'A student says males can be CARRIERS of X-linked recessive disorders without being affected. Why is this wrong?', commonErrors: [{ answer: 'Males can be carriers of X-linked recessive', misconception: 'Importing autosomal-carrier logic into sex-linked.', correctsTo: 'Males have only ONE X. If their X has the recessive allele, they are AFFECTED (not a carrier — they\'ll express the trait). Only FEMALES (XX) can be carriers — having one normal and one recessive X. This is exactly why X-linked recessive disorders (hemophilia, color-blindness, DMD) show up almost exclusively in males. Females need two recessive X\'s to be affected, which is rare.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Mendel: dominance, segregation, independent assortment.', 'Dihybrid 9:3:3:1; codominance/incomplete dominance/multiple alleles are extensions.', 'X-linked recessive: more affected males; carrier mothers; no father-to-son transmission.', 'Pedigree patterns: dominant doesn\'t skip; recessive skips.', 'Male carriers don\'t exist for X-linked recessive (one X = affected).'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
