/**
 * SAT R&W — Subject-Verb Agreement and Pronoun Agreement.
 */

import type { LessonPlan } from '../types';

export const SEED_SAT_RW_GRAMMAR_AGREEMENT: LessonPlan = {
  id: 'evelyn.testprep.sat-rw.grammar-agreement.v1',
  title: 'SAT R&W — Subject-Verb and Pronoun Agreement',
  curriculum: 'CCSS',
  grade: 'sat-act',
  subject: 'test-prep',
  topic: 'sat-reading-writing',
  locale: 'en',
  los: [{ id: 'satrw.grammar-agreement', description: 'Identify subject + verb agreement; pronoun antecedent agreement; pronoun case.', standard: 'CCSS.ELA.LANGUAGE' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 14,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Agreement errors are SAT favorites — and the trick is finding the actual subject (often hidden behind prep phrases).', script: '"The list of guests IS revised" — the verb agrees with "list" (singular), not "guests" (plural). Subject hides behind prep phrases. Find it carefully.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Subject-verb agreement, pronoun agreement, who/whom, pronoun case.', keyIdeas: [
      'SUBJECT-VERB AGREEMENT: subject and verb match in NUMBER (singular/plural).',
      '  Singular subject → singular verb. Plural subject → plural verb.',
      'STRATEGY: STRIP OUT prepositional phrases to find the SUBJECT.',
      '  "The list of guests is revised."',
      '  Strip "of guests" → "The list is revised." Subject is "list" (singular). Singular verb "is" ✓.',
      'TRICKY SUBJECTS:',
      '  Indefinite pronouns: EVERYONE, EVERYBODY, SOMEONE, SOMEBODY, NO ONE, NOBODY, EACH = SINGULAR.',
      '    "Everyone IS coming."',
      '  Collective nouns: TEAM, COMMITTEE, FAMILY = SINGULAR (usually treated as one unit).',
      '  Compound subjects with AND = PLURAL.',
      '    "Tom and Lisa ARE here."',
      '  EITHER...OR / NEITHER...NOR: verb matches the SECOND (closer) subject.',
      '    "Either the boys or the GIRL IS here."',
      '    "Either the girl or the BOYS ARE here."',
      'PRONOUN AGREEMENT: pronoun agrees with antecedent in NUMBER.',
      '  "Each student should bring HIS/HER (or THEIR) book." Modern usage accepts singular "their."',
      '  Watch ambiguity: "Sara told Lisa SHE was wrong." — unclear who.',
      '  AVOID ambiguous pronouns. Often SAT will give clearer alternatives.',
      'PRONOUN CASE:',
      '  SUBJECT pronouns: I, he, she, we, they, who.',
      '  OBJECT pronouns: me, him, her, us, them, whom.',
      '  Use SUBJECT before verb, OBJECT after verb or preposition.',
      '  "She and I went" (both subjects). "between you and me" (both objects of "between").',
      '  Common error: "She and me went" — wrong. "You and I" → check by removing one.',
      'WHO vs WHOM:',
      '  WHO = subject (does the action).',
      '  WHOM = object (receives action).',
      '  Trick: replace with he/him. He → who; him → whom.',
      '  "WHO went?" (he went) — who is correct.',
      '  "WHOM did you see?" (you saw him) — whom is correct.',
      'COMMON SAT TRAPS:',
      '  Long sentence with subject and verb FAR APART.',
      '  Prep phrase between subject and verb.',
      '  Inverted sentence: "There are five reasons..." — subject is "reasons" (plural), verb "are" (plural). NOT "There IS."',
    ], vocabulary: [{ term: 'antecedent', definition: 'the noun that a pronoun refers back to.' }, { term: 'inverted sentence', definition: 'sentence where verb comes before subject (common with "there is/are" or questions).' }], estimatedMinutes: 5 },
    { id: 'worked', kind: 'worked_example', problem: 'Choose: "The collection of rare books in the library ___ valuable." (A) is (B) are (C) were (D) have been', steps: [
      'Identify subject. Strip prep phrases: "of rare books," "in the library."',
      'Subject = "collection" (singular, despite "books" being plural).',
      'Singular subject needs singular verb.',
      'Answer: (A) is.',
      'Common trap: students see "books" or "library" and pick plural verb. Always strip prep phrases.',
    ], answer: '(A) is', estimatedMinutes: 3 },
    { id: 'try-1', kind: 'try_yourself', problem: 'Choose: "Either the players or the coach ___ to the meeting." (A) is going (B) are going (C) go (D) goes', expectedAnswer: '(A) is going. Either/or rule: verb matches the CLOSER subject. Closer to verb is "coach" (singular). Singular verb: "is going." (B) and (C) and (D) all wrong with respect to closer subject "coach."', responseFormat: 'free', hints: ['Either/or — verb matches closer subject.', 'Closer to verb is "coach."'], estimatedMinutes: 3 },
    { id: 'misconception-prep-phrase', kind: 'misconception_check', question: 'A student looks at "The list of guests" and picks plural verb because of "guests." What\'s the rule?', commonErrors: [{ answer: 'Plural verb because of "guests"', misconception: 'Treating the noun closest to the verb as the subject.', correctsTo: 'The actual subject is "list" (singular). "Of guests" is a PREPOSITIONAL PHRASE modifying "list" — it doesn\'t change the subject\'s number. Always: identify the head noun of the subject (here "list") and ignore prep phrases. The phrase "the list of guests" → singular subject "list." Use singular verb.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Strip prep phrases to find the subject.', 'Indefinite pronouns (everyone, each) = singular.', 'Either/or, neither/nor: verb matches CLOSER subject.', 'Who = subject, whom = object. Test with he/him.', 'Inverted sentences: subject after verb.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
