/**
 * SAT R&W — Rhetorical Synthesis (Digital SAT specific).
 */

import type { LessonPlan } from '../types';

export const SEED_SAT_RW_RHETORICAL_SYNTHESIS: LessonPlan = {
  id: 'evelyn.testprep.sat-rw.rhetorical-synthesis.v1',
  title: 'SAT R&W — Rhetorical Synthesis',
  curriculum: 'CCSS',
  grade: 'sat-act',
  subject: 'test-prep',
  topic: 'sat-reading-writing',
  locale: 'en',
  los: [{ id: 'satrw.rhetorical-synthesis', description: 'Combine bullet-point notes into a single sentence achieving a stated rhetorical goal.', standard: 'DSAT-RHET-SYNTH' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 14,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Rhetorical synthesis is unique to Digital SAT — and tests whether you can match RHETORICAL GOAL to RIGHT SENTENCE.', script: 'You get bullet-point research notes + a stated GOAL ("emphasize a difference," "introduce a topic to peers," "summarise findings"). Pick the option that ACHIEVES that goal best. Today: pattern recognition.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Format, common goals, strategy, traps.', keyIdeas: [
      'FORMAT (Digital SAT specific):',
      '  Bullet-point notes about a topic (4-6 bullets).',
      '  A SPECIFIC RHETORICAL GOAL: "emphasize a difference," "introduce the topic to a general audience," "summarize the main finding," etc.',
      '  Four sentence options. Pick the one that BEST achieves the stated goal.',
      'COMMON RHETORICAL GOALS:',
      '  "Emphasize a similarity / difference" — pick a sentence highlighting that comparison directly.',
      '  "Introduce X to an audience unfamiliar with the topic" — pick a general, accessible sentence.',
      '  "Summarize the main finding" — pick the conclusion-style sentence.',
      '  "Provide a specific example" — pick a concrete, illustrative sentence.',
      '  "Compare two methods" — pick a sentence that names both methods + the comparison.',
      '  "Explain the significance" — pick a sentence stating "why this matters."',
      'STRATEGY:',
      '  Read the GOAL FIRST.',
      '  Identify which BULLETS contain info needed.',
      '  Predict what kind of sentence achieves the goal.',
      '  Match against options.',
      'COMMON TRAPS:',
      '  Sentence is GRAMMATICALLY correct but doesn\'t MATCH the goal.',
      '  Sentence captures one bullet but doesn\'t fulfill the rhetorical purpose.',
      '  Sentence introduces info NOT in the bullets.',
      '  Sentence is overly detailed when goal asked for general.',
      '  Sentence is too general when goal asked for specific.',
      'EXAMPLE:',
      '  Bullets:',
      '    Plant A grows in full sun.',
      '    Plant A produces red flowers.',
      '    Plant B grows in shade.',
      '    Plant B produces white flowers.',
      '  Goal: "Emphasize a key difference between Plant A and Plant B."',
      '  WRONG: "Plant A produces red flowers." (doesn\'t mention Plant B; just one fact)',
      '  WRONG: "Both plants are flowering plants." (no contrast)',
      '  RIGHT: "Plant A requires full sun, while Plant B thrives in shade." (clear contrast).',
      'TONE matters. If the audience is "specialists," more technical vocabulary is OK. If "general public," simpler language wins.',
    ], vocabulary: [{ term: 'rhetorical synthesis', definition: 'Digital SAT R&W question type that asks you to combine notes into a sentence fulfilling a stated rhetorical goal.' }], estimatedMinutes: 5 },
    { id: 'worked', kind: 'worked_example', problem: 'Bullets: (1) Mendel studied pea plants in 1865. (2) He tracked pea color across generations. (3) He found a 3:1 ratio of dominant to recessive. (4) Mendel\'s work was ignored for 35 years.\n\nGoal: "Summarize the historical impact of Mendel\'s work on the field of genetics." Which is best? (A) Mendel studied pea plants in 1865. (B) Mendel\'s 1865 pea plant experiments revealed inheritance ratios that, although ignored for decades, became the foundation of modern genetics. (C) The 3:1 ratio is a key finding. (D) Pea plants were ideal for Mendel\'s study.', steps: [
      'Goal: SUMMARIZE HISTORICAL IMPACT.',
      'Need: a sentence connecting his work to lasting effect on genetics.',
      'Evaluate options:',
      '  (A) Just states a fact — no impact discussion. NO.',
      '  (B) Names work + acknowledges initial neglect + states "foundation of modern genetics." MATCHES goal.',
      '  (C) States a finding — no historical impact context.',
      '  (D) About pea plants — irrelevant to historical impact.',
      'Answer: (B). Captures the historical-impact angle.',
    ], answer: '(B)', estimatedMinutes: 4 },
    { id: 'try-1', kind: 'try_yourself', problem: 'Goal: "Introduce the topic to readers unfamiliar with quantum mechanics." Bullets give technical specifics. Which would you predict is the right answer style?', expectedAnswer: 'A SIMPLE, ACCESSIBLE sentence introducing quantum mechanics in everyday terms. Example: "Quantum mechanics is the branch of physics that studies the strange behaviour of particles at extremely small scales — where they can be in multiple places at once and behave in ways that defy everyday intuition." Avoid sentences with technical jargon, equations, or specific findings — those would suit "explain the latest development" goal, not "introduce."', responseFormat: 'free', hints: ['Match accessibility to "unfamiliar audience."', 'Avoid jargon for general intros.'], estimatedMinutes: 3 },
    { id: 'misconception-grammar-vs-fit', kind: 'misconception_check', question: 'A student picks the most grammatically polished option even when it doesn\'t fit the rhetorical goal. Why does this often hurt?', commonErrors: [{ answer: 'Grammar > goal fit', misconception: 'Treating the question as a grammar test.', correctsTo: 'All four options on rhetorical synthesis are usually GRAMMATICALLY CORRECT. The test is whether the sentence FULFILS THE GOAL. A polished, correct sentence that introduces a topic when the goal is to summarise findings is WRONG. Match the option to the GOAL first; grammar is secondary because all options pass it.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['READ THE GOAL FIRST.', 'Predict the kind of sentence the goal needs.', 'Match: ALL options usually grammatical, so pick by GOAL fit.', 'Avoid: too detailed when general needed; too general when specific needed.', 'Tone matches audience.'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
