/**
 * SAT R&W — Main Idea and Central Claim.
 */

import type { LessonPlan } from '../types';

export const SEED_SAT_RW_MAIN_IDEA: LessonPlan = {
  id: 'evelyn.testprep.sat-rw.main-idea.v1',
  title: 'SAT R&W — Main Idea and Central Claim',
  curriculum: 'CCSS',
  grade: 'sat-act',
  subject: 'test-prep',
  topic: 'sat-reading-writing',
  locale: 'en',
  los: [{ id: 'satrw.main-idea', description: 'Identify central claim, main purpose, and overall organisation of SAT R&W passages.', standard: 'CCSS.ELA.READ.MAIN-IDEA' }],
  prerequisites: [],
  followUps: [],
  estimatedMinutes: 14,
  segments: [
    { id: 'hook', kind: 'hook', goal: 'Main-idea questions appear in nearly every SAT passage — and the answer hides in 2-3 specific places.', script: 'Where\'s the main idea? Almost always: opening sentence, last sentence, or topic sentences of paragraphs. Today: how to find it fast.', estimatedMinutes: 1 },
    { id: 'concept', kind: 'concept', goal: 'Main idea vs detail vs purpose, common locations, common traps.', keyIdeas: [
      'MAIN IDEA = overall message or central claim of the passage.',
      'PURPOSE = what the author is trying to do (persuade, inform, describe, narrate).',
      'OFTEN ASKED:',
      '  "Which best describes the central idea?"',
      '  "The main purpose of the passage is to..."',
      '  "Which choice best summarises the passage?"',
      'WHERE TO FIND main idea (in order of likelihood):',
      '  1. THESIS sentence — usually first or last sentence of intro paragraph.',
      '  2. CONCLUSION — restated in last paragraph.',
      '  3. TOPIC SENTENCES of body paragraphs (collectively reveal main idea).',
      'STRATEGY:',
      '  Skim first paragraph carefully.',
      '  Note topic sentences.',
      '  Skim last paragraph.',
      '  Synthesise: what is the AUTHOR\'S ONE MAIN POINT?',
      'TYPES OF PURPOSE (memorise — SAT often picks):',
      '  TO INFORM / EXPLAIN — neutral, factual.',
      '  TO PERSUADE / ARGUE — takes a position.',
      '  TO DESCRIBE — depicts a person, place, event.',
      '  TO NARRATE — tells a story.',
      '  TO ANALYSE — examines + interprets.',
      '  TO COMPARE — discusses similarities + differences.',
      'COMMON TRAPS:',
      '  TOO NARROW: an answer that\'s a specific detail, not the main idea.',
      '  TOO BROAD: an answer that\'s vague + could apply to many passages.',
      '  HALF-RIGHT: captures part but missing key qualification.',
      '  EXTREME LANGUAGE: "always," "never," "completely" rarely matches a nuanced passage.',
      '  OFF-TOPIC: introduces concepts not in the passage.',
      'TEST your answer: does it apply to the WHOLE passage, not just one part?',
      'PURPOSE questions: the verb (inform, persuade, describe) must match the AUTHOR\'S TONE + structure.',
    ], vocabulary: [{ term: 'main idea', definition: 'the overall central claim or message of a passage; usually stated explicitly in the intro or conclusion.' }, { term: 'purpose', definition: 'what the author is trying to accomplish (inform, persuade, describe, narrate).' }], estimatedMinutes: 5 },
    { id: 'worked', kind: 'worked_example', problem: 'A passage opens: "Despite advances in air-quality regulation, urban pollution continues to disproportionately affect low-income communities." What\'s likely the main idea?', steps: [
      'Identify thesis-style sentence: this opening sentence makes a CLAIM.',
      'Claim: pollution disproportionately affects low-income communities.',
      'Despite + phrase signals: counter-expectation argument is being made.',
      'Likely main idea: passage will argue that REGULATIONS HAVEN\'T FIXED POLLUTION INEQUITIES (still persists, still uneven).',
      'TEST hypotheses against the rest of the passage.',
      'Reject answers that focus on (a) air-quality regulations success, (b) general urban issues without inequity angle.',
    ], answer: 'Pollution disproportionately affects low-income communities despite regulation.', estimatedMinutes: 4 },
    { id: 'try-1', kind: 'try_yourself', problem: 'A 4-paragraph passage describes Marie Curie\'s scientific work, then her struggle for recognition as a woman. The author seems to admire her but acknowledge the challenges she faced. What\'s the likely main idea?', expectedAnswer: 'Likely main idea: Curie\'s SCIENTIFIC ACHIEVEMENTS WERE EXTRAORDINARY YET CAME WITH PERSISTENT GENDER-RELATED OBSTACLES. The passage balances admiration + acknowledgment. Wrong answers would be: too narrow (just achievements), too broad (women in science generally), or extreme (Curie was completely unappreciated).', responseFormat: 'free', hints: ['Synthesise the achievements + challenges.', 'Avoid extremes; favour nuanced.'], estimatedMinutes: 3 },
    { id: 'misconception-detail-as-main', kind: 'misconception_check', question: 'A student picks an answer because it appeared verbatim in the passage. Why is this risky?', commonErrors: [{ answer: 'Verbatim = main idea', misconception: 'Confusing recall of details with grasp of central claim.', correctsTo: 'A passage contains many details. Most are NOT the main idea. SAT trap answers often contain exact phrases from the passage but are NARROWER than the main idea (just a detail) or NOT supported as the central claim. The main idea is usually a synthesis — not a quote. Predict the main idea in YOUR words, then find the answer that matches your prediction in MEANING. Words can be different.' }], estimatedMinutes: 3 },
    { id: 'recap', kind: 'recap', mustRemember: ['Main idea usually in first or last paragraph + topic sentences.', 'Predict in your own words, then match.', 'Avoid: too narrow, too broad, too extreme, off-topic.', 'Test: does the answer apply to the WHOLE passage?'], estimatedMinutes: 1 },
  ],
  source: { author: 'Evelyn Learning', org: 'Evelyn', license: 'proprietary' },
  schemaVersion: 1,
};
