import type { Passage } from '../types';

/**
 * ACT Form C (mock exam) — Reading section, 4 original shared passages.
 * ORIGINAL content authored for this mock; not derived from any released
 * ACT test. Passage 4 is a paired passage (Passage A / Passage B inside
 * fullText) supporting act.paired-passages items.
 */
export const ACT_MOCK_C_READING_PASSAGES: Passage[] = [
  {
    id: 'evelyn.passage.act-mock-c-reading-1.v1',
    title: 'The Tap Tone',
    author: 'Evelyn (original)',
    year: 2026,
    sourceUrl: 'internal:act-mock-c',
    license: 'internal-original',
    genre: 'fiction',
    fullText:
      `Marisol had graduated eleven violin plates before she ruined one badly enough to notice.\n\n` +
      `She was seventeen, apprenticed to Teodor Vronsky, a violin maker whose shop occupied the ground floor of a converted mill two towns over from where she'd grown up. For the first four months he had let her do nothing but sand corner blocks and sweep spruce dust into a bin he emptied by hand, as though the shavings were too valuable to trust to a broom. Only in her fifth month had he set a rough-cut top plate on the bench in front of her and told her to graduate it — to carve the underside so the wood thinned gradually from a thick thumb's width at the center to something closer to a coin's edge near the rim.\n\n` +
      `"You are not sculpting a shape," he said, tapping the plate with one knuckle. "You are tuning a shape. Listen."\n\n` +
      `He struck the wood again, and Marisol heard nothing but a dull, papery knock. Vronsky struck a finished plate from the shelf behind him, and the sound that came back was almost a note — round, sustained, faintly resonant, the way a struck wine glass rings after the ring of a struck table does not. He wanted her to carve until the dull knock became something closer to that note. He gave her no thickness gauge for the first weeks, only calipers she wasn't allowed to look at until she had already decided, by ear and by the flex of the wood under her thumb, where the plate still felt "asleep."\n\n` +
      `For a long time she thinned by rule instead. She had found an old diagram in one of Vronsky's books showing a violin top divided into concentric rings, each ring assigned a target thickness in millimeters, and she began working to those numbers, checking the calipers every few strokes of the thumb plane. The plate came out even and symmetrical, its bass side and treble side thinned to matching tolerances. When she tapped it, the tone was clearer than her earlier attempts, but Vronsky shook his head before she had finished the second knuckle-rap.\n\n` +
      `"You measured a good plate," he said. "You did not make one."\n\n` +
      `He explained, not unkindly, that no two pieces of spruce were the same animal. One plank might have tight, stiff growth rings that already carried tone with barely any material removed; another, cut from a tree that had grown crookedly against a hillside wind, might need to be thinned unevenly, more on one side than the other, to sing at all. The concentric-ring diagram was a starting sketch for someone who had not yet learned to feel the difference, not a formula to be trusted over the wood itself. "The caliper tells you what is already true," he told her. "It cannot tell you what the wood wants."\n\n` +
      `Marisol ruined the twelfth plate on a Tuesday, thinning one section so far past what the wood could bear that it cracked audibly under her thumb plane, a short flat sound like a dry branch. She set the plane down and did not touch anything for several minutes, certain Vronsky would send her back to sanding blocks. Instead he picked up the cracked plate, turned it over twice, and asked her what she had been listening for when she cut that final pass.\n\n` +
      `She admitted, after a pause, that she had stopped listening — that she had been chasing a caliper number she remembered from the ruined plate two weeks earlier, trying to repeat a success instead of reading the plate in front of her.\n\n` +
      `Vronsky nodded slowly, as if this were the answer he had been carving toward all along. He handed her a fresh, unthinned blank and did not mention the calipers again that afternoon. When she tapped the new plate for the first time, the sound was still dull. But this time, thinning it stroke by stroke, checking the note against her own memory of the resonant plate rather than against any number, she found she could hear, faintly, which corner of the wood was still asleep.\n\n` +
      `By the following week, when she tapped the finished plate and it rang back at her — not perfectly, but truly — she understood that Vronsky had never been teaching her to carve wood. He had been teaching her to trust her own ear over a measurement, patiently, until the trusting became a kind of skill in itself.`,
    lineNumbered: false,
    wordCount: 746,
  },
  {
    id: 'evelyn.passage.act-mock-c-reading-2.v1',
    title: 'An Hour for an Hour',
    author: 'Evelyn (original)',
    year: 2026,
    sourceUrl: 'internal:act-mock-c',
    license: 'internal-original',
    genre: 'informational',
    fullText:
      `In several hundred communities across the world, membership in a local exchange network entitles a person to something unusual: an hour of somebody else's labor in return for an hour of their own, regardless of what either hour was spent doing. A retired electrician who spends sixty minutes rewiring a neighbor's lamp earns exactly the same credit as a teenager who spends sixty minutes walking an elderly resident's dog. Both are paid an hour, not a wage, and the currency that changes hands isn't currency in the conventional sense at all — it's simply an entry, logged by a coordinator or a piece of software, that one member now owes the network an hour and another is owed one back.\n\n` +
      `The practice is usually called time banking, and its earliest large-scale form is often credited to the lawyer and community organizer Edgar Cahn, who began experimenting with the model in Washington, D.C., in the early 1980s after his own work had left him, in his words, feeling like "a discarded resource" during a long hospital recovery. Cahn's insight was less about economics than about status: conventional markets assign wildly different dollar values to an hour of legal advice and an hour of childcare, a hierarchy that, in his view, quietly tells people whose skills sit lower on that scale that what they have to offer is worth less. A time bank, by design, refuses to make that comparison. An hour is an hour.\n\n` +
      `Supporters argue that this flattening does something markets cannot: it brings people who have no spare cash, but do have spare time, into a system of mutual obligation they might otherwise be shut out of. A single parent with no money for after-school tutoring might instead earn credits by delivering meals to homebound seniors, then spend those same credits on math help from a retired teacher. Because the exchange never touches actual currency, some time banks are also able to operate largely outside tax rules that would apply to ordinary paid labor, though organizers are careful to note this exemption depends on how narrowly a given program defines its services and on the tax code of the country involved.\n\n` +
      `Critics, including some economists who study informal exchange, raise a different concern: that treating all hours as interchangeable can create exactly the kind of shortage a flexible price would normally solve. If a network badly needs someone willing to do home repairs but has an abundance of members offering conversation and companionship, a flat hour-for-hour rate gives repair-minded members no particular incentive to spend their scarce time on the network rather than on paid work elsewhere. Some networks have responded by weighting certain categories of service more heavily, awarding, say, ninety minutes of credit for an hour of a skill the network has identified as chronically undersupplied — a compromise that keeps the core one-hour principle intact while nudging behavior toward what members most need.\n\n` +
      `There is also a quieter argument for time banking that has less to do with efficiency than with what its advocates call relational value: the claim that an exchange logged as a transaction between neighbors, rather than a service purchased from a stranger, tends to produce an ongoing relationship rather than a one-time errand. A member who tutors another member's child, organizers report, is statistically more likely to check in on that family later, informally, than a paid tutor hired through an agency would be. Whether this pattern reflects something durable about the way time banking is structured, or simply the fact that people who join such networks were already inclined toward that kind of neighborliness, is difficult to establish with the kind of data currently available; most published accounts of the practice remain descriptive rather than experimental, drawn from case studies of individual networks rather than controlled comparisons across many of them.\n\n` +
      `Time banks remain a marginal presence in most local economies, numbering in the low thousands worldwide and rarely reaching more than a few hundred active members apiece. But their persistence, four decades after Cahn's initial experiment, suggests that for at least some communities, the appeal of an hour valued only as an hour has proven durable even where the underlying economic case for it remains unsettled.`,
    lineNumbered: false,
    wordCount: 706,
  },
  {
    id: 'evelyn.passage.act-mock-c-reading-3.v1',
    title: 'What the Escapement Remembers',
    author: 'Evelyn (original)',
    year: 2026,
    sourceUrl: 'internal:act-mock-c',
    license: 'internal-original',
    genre: 'informational',
    fullText:
      `When a longcase clock arrives at Priya Anand's workbench with its pendulum silent and its hands frozen at whatever hour it stopped, the temptation, she says, is to treat the mechanism the way a surgeon treats a patient: diagnose the single failed part, replace it, and set the whole system moving again. Anand, who has restored mechanical clocks for over twenty years in a converted stable behind a regional history museum, resists that instinct almost every time. A clock's escapement — the ratcheting mechanism that releases the gear train one tooth at a time, converting the pendulum's swing into a steady, audible tick — rarely fails because of one broken component. More often, she says, it fails because of an accumulation of small, tolerable wear across a dozen parts, none of which alone would stop the clock, but which together shift the mechanism just far enough out of its original balance that it can no longer sustain motion.\n\n` +
      `This is why Anand's first step with any incoming clock is rarely repair at all. She spends, by her own estimate, roughly twice as long recording the clock's current condition — measuring pivot diameters, photographing wear patterns on the pallets, noting where old oil has gummed into a dark varnish — as she later spends fixing it. Only after that record exists does she decide which parts genuinely need intervention and which have simply aged in ways that do not affect function. A worn pivot hole, elongated slightly by a century of a rotating shaft pressing against brass, might look alarming to an untrained eye but still keep the gear running true; replacing it unnecessarily, Anand argues, destroys evidence of the clock's working life for no functional gain.\n\n` +
      `The instinct to over-repair, she notes, is common among restorers trained primarily as machinists rather than as conservators, and it produces two opposite failure modes. Some over-repair by replacing anything imperfect, leaving a clock that runs beautifully but has been stripped of nearly every original part, evidence that a conservation review board would later flag as historically compromised. Others under-repair out of an exaggerated caution about originality, refusing to replace even a demonstrably cracked mainspring for fear of altering the object, and end up with a clock that looks untouched but cannot safely be wound. Anand describes her own approach as sitting deliberately between these poles: intervene wherever the mechanism cannot function or cannot safely be operated, and stop there.\n\n` +
      `Much of the actual diagnostic work depends on listening rather than looking. A healthy escapement produces a tick with a distinctive, evenly spaced rhythm; Anand can often tell, before she opens the case, whether the trouble lies in the escapement itself or somewhere further back in the gear train simply by timing the gaps between ticks with a stopwatch and comparing the pattern to what a functioning clock of the same design should produce. An escapement that is failing tends to produce ticks that grow gradually, almost imperceptibly, uneven, while a problem in the gear train further upstream tends to produce a tick that stays regular until it suddenly stops altogether, the way a chain finally snaps rather than gradually loosening.\n\n` +
      `Not every repair Anand makes is invisible, and she is candid that conservation orthodoxy sometimes collides with what a clock's owner actually wants. A museum piece destined for a glass case might be restored to run, but never wound, preserving wear patterns exactly as found; a family heirloom the owner intends to keep on a mantel and wind every Sunday needs parts that will hold up to decades of continued use, which sometimes means accepting a less strictly "original" repair in exchange for a clock that will keep functioning long after Anand herself has stopped working on it. She keeps a small shelf of clocks in her workshop that she considers unfinished on purpose: mechanisms whose owners asked her to pause once she reached the edge of what she felt she could responsibly touch, leaving the rest of the repair, and the decision about how far restoration should go, for someone else to make later.\n\n` +
      `For Anand, that shelf is less a failure of nerve than a record of the profession's central tension: a good restoration does not simply make an old clock tick again, it decides, deliberately, how much of the object's history that tick is allowed to erase.`,
    lineNumbered: false,
    wordCount: 727,
  },
  {
    id: 'evelyn.passage.act-mock-c-reading-4.v1',
    title: 'What Tells a Monarch When to Fly',
    author: 'Evelyn (original)',
    year: 2026,
    sourceUrl: 'internal:act-mock-c',
    license: 'internal-original',
    genre: 'informational',
    fullText:
      `Passage A\n\n` +
      `Every autumn, monarch butterflies east of the Rocky Mountains abandon the breeding behavior of the three or four generations that preceded them that same year and instead fly, sometimes more than two thousand miles, to a set of high-altitude fir forests in central Mexico that none of them has ever visited. Biologist Renata Osei has spent much of the last decade arguing that this switch is driven chiefly by an internal genetic clock rather than by anything the butterflies encounter along the way. In Osei's view, the "migratory generation" hatches already carrying a distinct developmental program, activated primarily by the shortening daylight hours its parents experienced as pupae, that reroutes the insect's metabolism away from reproduction and toward long-distance flight before the butterfly has flown a single mile south.\n\n` +
      `Osei's strongest evidence comes from laboratory colonies raised entirely indoors, shielded from any temperature drop, wind shift, or dying milkweed that a wild monarch would encounter in the field. When she shortened the artificial daylight these lab-raised pupae experienced to match the daylight hours of late August, a majority of the resulting adults still oriented southward in flight simulators and showed the same suppressed reproductive development characteristic of wild migratory monarchs, even though every other environmental cue available to a wild insect had been held constant or removed. To Osei, this result shows that day length acting on the pupa is sufficient, on its own, to switch on migratory behavior; the many other cues a wild monarch experiences along its route, she argues, mostly fine-tune a program that has already been set in motion before the butterfly ever leaves the milkweed patch where it hatched.\n\n` +
      `Osei has since extended this argument by tracking activity in a handful of genes known to regulate circadian rhythm in other insects. In monarchs collected from the same lab colonies, these clock genes showed a consistent shift in expression timing that tracked the shortened daylight schedule almost precisely, appearing between two and four days after the daylight change regardless of which colony the pupae came from. Osei considers this consistency further evidence that the migratory switch is governed by an internal, day-length-sensitive clock rather than by the varied conditions any individual butterfly happens to encounter outside the laboratory.\n\n` +
      `Passage B\n\n` +
      `A different reading of the same broad phenomenon comes from entomologist Marcus Feldt, who has spent years tracking wild monarch populations across their migratory range rather than working primarily with lab colonies. Feldt does not dispute that shortened daylight plays some role, but he argues that Osei's laboratory results overstate how much day length alone can explain, because they remove the layered combination of cues a monarch actually integrates in the wild. Feldt's field data show that migratory departure dates from a given breeding site vary by as much as three weeks from year to year even though day length on any given calendar date is essentially identical from one year to the next; what does shift year to year, in his tagged populations, is the timing of the first sustained nighttime temperature drop below roughly 54 degrees Fahrenheit and the corresponding senescence of local milkweed stands, both of which correlate far more tightly with departure timing across his eleven years of field data than day length does. Feldt proposes that day length instead functions as what he calls a "readiness cue," priming the insect's physiology to respond, while a cluster of environmental triggers — cooling nights chief among them — actually determines the specific date on which a given population departs. In field sites where an unusually warm autumn delayed the first hard temperature drop, Feldt's tagged monarchs delayed their departure by a comparable number of days even though daylight hours followed the identical seasonal schedule as in colder years, a pattern he argues Osei's indoor design, by holding temperature artificially constant, was never positioned to detect.\n\n` +
      `Feldt's team has also tracked milkweed condition directly rather than inferring it from temperature alone, walking fixed transects at each field site every three days throughout September and October to record the proportion of plants that had visibly yellowed. Across his eleven years of data, the week in which half of a site's milkweed had yellowed predicted that site's peak departure week more precisely than the calendar date did, a relationship Feldt argues would be difficult to explain if day length alone were doing the work Osei's laboratory result assigns to it.`,
    lineNumbered: false,
    wordCount: 736,
  },
];
