import type { Passage } from '../types';

/**
 * ACT Form B (mock exam) — Reading section, 4 original shared passages.
 * ORIGINAL content authored for this mock; not derived from any released
 * ACT test. Passage 4 is a paired passage (Passage A / Passage B inside
 * fullText) supporting act.paired-passages items.
 */
export const ACT_MOCK_B_READING_PASSAGES: Passage[] = [
  {
    id: 'evelyn.passage.act-mock-b-reading-1.v1',
    title: 'The Ribs That Didn\'t Hold',
    author: 'Evelyn (original)',
    year: 2026,
    sourceUrl: 'internal:act-mock-b',
    license: 'internal-original',
    genre: 'fiction',
    fullText:
      `Dario had spent six weeks sanding hulls and coiling scrap line before Ilsa Voss let him near a boat that wasn't already beyond saving. The one she set him in front of that April morning was the Kestrel, a thirty-year-old fishing boat hauled out of the water with a cracked rib low in her frame, the oak split clean through where decades of salt and flexing had finally worn it out. "A bad rib you replace quiet, and nobody ever knows," Ilsa said, laying a coil of steamed white oak across the bench. "A bad rib you botch, the whole hull remembers it for the next forty years. Figure out which one you can live with."\n\n` +
      `Dario had come to Voss Boatworks the way most of Ilsa's apprentices did, without an appointment, walking down from the road one June morning and asking if she needed an extra pair of hands. His uncle ran a marine insurance office three streets from the harbor and had already offered him a steady clerking job, a desk out of the weather. Dario had told his uncle, and occasionally his mother, that the boatyard was temporary, something to do until the office job made more sense. Ten months later he was still sweeping sawdust off the same floor.\n\n` +
      `The new rib took him three tries. On the first attempt, he pulled the stave from the steam box a few seconds too slowly, and by the time he had it clamped against the hull form, the oak had cooled past the point where it would bend without complaint; it cracked cleanly at the tightest curve, the same way the old rib had. On the second attempt, he worked faster, mindful of the cooling wood, but clamped down hard against a knot he hadn't noticed running through the grain, and the stave split lengthwise before it had traveled halfway around the form.\n\n` +
      `Ilsa did not offer to finish either attempt for him. She nailed both broken staves to the rafter beam above the workbench, where he would see them every time he reached for a tool. "Why not just toss them?" he asked, on the afternoon of the second failure, tired enough to ask a question he would normally have kept to himself. "Because you'll remember exactly how careful you thought you were being," she said, "right up until you look up and see the crack."\n\n` +
      `She worked with an unstudied economy of motion that made forty years of practice look like nothing at all, running a hand along a hull's curve and knowing by feel alone where the fairing was off by an eighth of an inch. It had not occurred to Dario that this kind of economy might be built rather than born, one split stave at a time, on a rafter where a person couldn't quietly take it down.\n\n` +
      `On the third attempt, Dario slowed down. He ran his palm along the length of the new stave before it went into the steam box, feeling for knots the way Ilsa had shown him, and pulled it out the moment it went pliable rather than waiting to feel ready himself. He set the clamps in order, easing each one down evenly instead of cinching the nearest one tight first. When he stepped back, he did not know yet whether the rib had taken the curve cleanly. He only knew that, for the first time, he had not been racing the wood to beat a mistake to the finish.\n\n` +
      `By the next afternoon, once the oak had fully set, the rib sat flush against the hull's inner curve, following the same line as its neighbors without a single proud edge. Ilsa ran her thumb along the seam for a long moment, said nothing, and then reached up and nailed Dario's stave to the rafter beside the two broken ones — not because it had failed, she told him, but so he would remember what the difference between a rushed rib and a patient one actually felt like under his hand. "You'll split worse wood than that again," she added. "Everyone does. What matters is whether you're the kind of person who leaves the evidence where you'll trip over it, or the kind who sweeps it out with the shavings."\n\n` +
      `Dario did not mention the rib to his mother that week, or the rafter, or the clerking job he had quietly turned down for the second time. But walking home past his uncle's dark office windows that evening, he realized he was no longer bracing for the argument he had been rehearsing in his head for months. He was thinking instead about grain direction, and about how long a stave needed to sit in the steam before it would forgive being asked to bend.`,
    lineNumbered: false,
    wordCount: 797,
  },
  {
    id: 'evelyn.passage.act-mock-b-reading-2.v1',
    title: 'Let the Neighborhood Decide: Participatory Budgeting',
    author: 'Evelyn (original)',
    year: 2026,
    sourceUrl: 'internal:act-mock-b',
    license: 'internal-original',
    genre: 'informational',
    fullText:
      `In a conventional city budget process, elected officials and department staff decide, largely on their own, how public money is spent on new sidewalks, playground equipment, streetlights, and other neighborhood-scale improvements; residents may comment at a public hearing, but the final decisions belong to people they elected months or years earlier. Participatory budgeting inverts part of that process. A city, school district, or other public agency sets aside a fixed sum of its capital budget — often a few hundred thousand to a few million dollars within a single district or ward — and lets residents themselves propose specific projects, refine them with the help of city engineers and budget staff, and then vote directly on which proposals get funded. The results are binding: whichever projects receive enough votes get built, without a further vote by any elected body.\n\n` +
      `The practice was first developed in city governments in South America in the late 1980s, as a way of giving working-class residents direct control over a portion of municipal spending that had previously been allocated through closed-door negotiations. It reached city councils and school districts in the United States roughly two decades later, beginning with a single city council district experimenting with a modest sum before other cities and, eventually, entire school systems adopted versions of the process for their own capital budgets. In its most expansive form, participatory budgeting has been used to allocate spending across dozens of council districts within a single city in the same budget cycle, with each district running its own independent proposal and voting process.\n\n` +
      `Supporters of the model point first to who participates. Unlike general municipal elections, which require voters to be adult citizens registered well in advance, many participatory budgeting processes set their own eligibility rules, and some of the most expansive allow any resident of a district — regardless of citizenship status, and starting at an age as young as eleven — to vote on the final project list. Because of this, supporters argue, participatory budgeting regularly draws in residents, including noncitizens, renters, and teenagers, who have no path to voting in a general election at all, and who research on civic participation has repeatedly found are otherwise among the least likely to attend a conventional public budget hearing.\n\n` +
      `Critics raise a more practical objection: turnout. Even in cities that have run participatory budgeting for a decade or more, the share of eligible residents who actually cast a vote in a given cycle typically remains in the low single digits, meaning that decisions binding an entire district's capital spending are frequently made by a few hundred voters out of a population of tens of thousands. Critics also note that the sums involved are usually a small fraction of a city's total capital budget, a detail that leads some to describe participatory budgeting as more symbolic than transformative, a way of building goodwill around discretionary funds while decisions over the much larger operating budget remain entirely with elected officials and department heads.\n\n` +
      `Proponents generally concede the turnout numbers but argue they measure the wrong thing. What matters, they say, is not what fraction of eligible residents vote, but who shows up relative to who typically participates in local government at all; several studies comparing participatory budgeting voters to attendees at conventional public hearings have found the former group to be younger, more racially diverse, and more likely to be renters than the latter, suggesting the process reaches residents that traditional public engagement structurally excludes, even if it does not reach a majority of any given district.\n\n` +
      `Whether the model can be extended meaningfully beyond small, discretionary sums remains an open question. A handful of cities have begun experimenting with applying participatory processes to larger categories of spending, including some operating expenses rather than one-time capital projects, but administrators in those cities acknowledge that running a fair, well-informed vote becomes substantially harder once the choices involve trade-offs between, for instance, hiring more staff and fixing more streets rather than simply choosing among a list of discrete, already-costed projects. For now, most participatory budgeting programs continue to operate at the scale where they began: a modest, clearly bounded sum, decided directly by the residents who will live with the result.`,
    lineNumbered: false,
    wordCount: 705,
  },
  {
    id: 'evelyn.passage.act-mock-b-reading-3.v1',
    title: 'Voicing the Pipes: Restoring a Historic Organ',
    author: 'Evelyn (original)',
    year: 2026,
    sourceUrl: 'internal:act-mock-b',
    license: 'internal-original',
    genre: 'informational',
    fullText:
      `A large pipe organ installed in a European church several centuries ago may contain anywhere from a few hundred to several thousand individual pipes, each one built to sound a single pitch when a supply of compressed air, called wind, is allowed to pass through it. The wind itself is generated by a bellows or, in older instruments, by teams of assistants pumping by hand, and is distributed to the correct pipes through a wind chest fitted with a valve, called a pallet, for every note on the keyboard. Restoring such an instrument is unlike restoring most other historical artifacts, because a restored organ is still expected to function exactly as it did when new: to be played, in tune, in an active church service, rather than simply preserved behind glass.\n\n` +
      `The parts of an organ most vulnerable to age are not the pipes themselves but the materials that move air through them. Bellows and wind chests rely on leather hinges and gaskets to remain airtight, and that leather dries and cracks over the course of decades, allowing wind to leak out before it reaches the pipes and causing notes to speak weakly or not at all. Restorers address this through a process called releathering, stripping the old, brittle leather from every joint and seam and replacing it, piece by piece, with new leather cut and glued to match the original dimensions exactly, since a seam even slightly too loose will leak and one too tight will bind and refuse to move.\n\n` +
      `Wood pipes present a separate problem. Because they are typically built from resinous softwood glued into rectangular tubes, wood pipes expand and contract with changes in humidity far more than the metal pipes standing beside them, and a wood pipe that has warped even slightly can produce a note that sounds flat, breathy, or unstable compared with its neighbors. Metal pipes, usually cast from alloys of tin and lead, resist warping but are prone to their own damage: centuries of handling can dent the delicate metal walls, and dents as small as a few millimeters across can measurably change a pipe's pitch and tone.\n\n` +
      `Once an organ's mechanical problems are solved, restorers face a task that resists standardization more than almost any other part of the work: voicing, the process of adjusting each individual pipe until it blends properly with its neighbors. A restorer adjusts the width of a pipe's mouth opening and cuts small notches, called nicks, along the edge where the air stream first splits, shaping the specific character of the tone one pipe at a time, entirely by ear. Piano technicians today can rely on electronic tuning devices to set a piano's pitch with mechanical precision, but organ voicing has no equivalent shortcut; a restorer must still stand in the room, listen to how a single pipe sounds against the pipes around it, and adjust by hand until the trained ear is satisfied, a method that has changed remarkably little since the instruments were first built.\n\n` +
      `Perhaps the thorniest decision in restoring a historic organ concerns not its mechanics but its tuning system, or temperament. Long before modern equal temperament divided the octave into twelve identical intervals, letting a piece move freely between any key, many historic organs were tuned to older temperaments that made certain keys sound unusually sweet and consonant at the cost of making other, more distant keys sound harsh, a tradeoff musicians of the period called a wolf interval. Restoring an organ to its original historical temperament preserves the exact chord colors its builder and the composers of its era intended, but it also means the instrument cannot comfortably play later repertoire written for equal temperament, a genuine loss for a working church organ expected to accompany music from many centuries.\n\n` +
      `Organ restorers and the musicologists who advise them remain divided over how to resolve that tradeoff, and the disagreement is rarely settled the same way twice; some historic instruments have been restored to their original temperament and now play only period-appropriate repertoire, while others have been deliberately retuned to a compromise temperament that plays acceptably, if not perfectly, in every key. Meanwhile, restorers increasingly monitor the temperature and humidity inside the churches that house these organs with embedded sensors, since even a well-restored instrument will drift out of tune and its wood pipes will begin to warp again if a church's heating system is switched on and off unevenly through the winter, undoing in a single erratic season work that may have taken a restoration team the better part of a year.`,
    lineNumbered: false,
    wordCount: 762,
  },
  {
    id: 'evelyn.passage.act-mock-b-reading-4.v1',
    title: 'How Old Are Saturn\'s Rings? Two Views',
    author: 'Evelyn (original)',
    year: 2026,
    sourceUrl: 'internal:act-mock-b',
    license: 'internal-original',
    genre: 'informational',
    fullText:
      `Passage A\n\n` +
      `For most of the twentieth century, astronomers generally assumed that Saturn's rings formed alongside the planet itself, more than four and a half billion years ago, and had simply persisted since as a leftover disk of debris orbiting the planet's equator. Data gathered by the Cassini spacecraft during its thirteen years orbiting Saturn, and especially during its final months skimming between the planet and its innermost ring, has convinced a growing number of researchers that the rings are instead remarkably young, perhaps only a few hundred million years old, younger than many of the dinosaurs that once walked on Earth.\n\n` +
      `The case for a young age begins with composition. Saturn's rings are made almost entirely of water ice, with only a small fraction, by some estimates well under one percent, made up of dark, rocky material. Because interplanetary space continuously rains fine meteoroid dust onto anything orbiting a planet, a ring system as old as Saturn itself should have accumulated far more of this dark material over four and a half billion years, gradually dulling the rings' brightness the way exposed snow darkens as dust settles onto it. Cassini's instruments measured the current rate of meteoroid bombardment and found it fast enough to darken bright, young rings within a few hundred million years, but far too fast to explain rings that had somehow stayed clean for the planet's entire history.\n\n` +
      `The second line of evidence concerns mass. Cassini's final orbits let scientists measure the combined mass of Saturn's rings with far greater precision, by tracking tiny changes in the spacecraft's radio signal as Saturn's gravity, subtly altered by the rings, tugged on it. The rings turned out to contain substantially less material than earlier estimates suggested, only a small fraction of the mass of Saturn's icy moon Mimas. A ring system this modest in mass, proponents argue, is more consistent with material shed recently from a single disrupted object than with a primordial disk that has had billions of years to lose mass to collisions and drift.\n\n` +
      `That disrupted object, in the leading version of this hypothesis, was a large icy moon or comet that wandered too close to Saturn and crossed the Roche limit, the distance inside which a planet's tidal forces overcome an object's own gravity and pull it apart. The shredded ice fragments, still orbiting where the object was torn apart, flattened into the ring system observed today, a process that could account for both the rings' youth and their icy, unpolluted composition.\n\n` +
      `Passage B\n\n` +
      `Not every researcher who has examined the Cassini data accepts that Saturn's rings are young. Many still argue the rings could be nearly as old as Saturn itself, and that their brightness and low mass reflect ongoing processes that clean the rings continuously, rather than a recent origin.\n\n` +
      `Central to this argument is a phenomenon Cassini helped confirm, called ring rain. Fine, charged particles of ice and dust in the rings are pulled by Saturn's magnetic field out of the ring plane and sent raining down into the planet's upper atmosphere, where they disintegrate. Because this process continuously removes material, including much of the dark pollution meteoroid bombardment deposits over time, proponents of an old-ring hypothesis argue the rings could accumulate dark material for billions of years and still look bright and icy today, simply because ring rain carries the pollution away roughly as fast as it arrives, rather than building up as a simple accumulation model assumes.\n\n` +
      `A second argument concerns internal structure. Saturn's rings are not a uniform sheet of debris but a layered system of narrow ringlets, gaps, and wave patterns, many shaped by resonances with Saturn's moons, features some researchers argue require a very long time to settle into their present configuration. A ring system flung outward by the sudden tidal disruption of a single icy moon, these researchers argue, would likely still show signs of that chaotic origin, rather than the smooth structure Cassini's cameras actually recorded.\n\n` +
      `Proponents of a young ring age respond that resonance patterns can develop far more quickly than once assumed, on timescales of millions rather than billions of years, once debris has flattened into a disk. They also note that the low mass Cassini measured is hard to reconcile with billions of years of continuous bombardment, ring rain or no ring rain, since even a well-cleaned ring system should show some buildup the measured mass does not contain. Most researchers who have examined the Cassini results now accept the rings are almost certainly less massive, and probably younger, than the twentieth-century assumption of a primordial, planet-aged system; what remains unresolved is whether the rings are merely young, or whether an old ring system continuously scrubbed by ring rain could explain the same observations without a recent catastrophic origin at all.`,
    lineNumbered: false,
    wordCount: 800,
  },
];
